import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Hash Generator (SHA)", short: "Generate SHA-1, SHA-256, SHA-384 and SHA-512 hashes of any text.", description: "Free hash generator. Compute SHA-1, SHA-256, SHA-384 and SHA-512 hex digests of any text using the Web Crypto API. Useful for checksums and integrity checks. Everything runs locally.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "checksum", "text hash"], placeholder: "Enter text to hash…", algorithm: "Algorithm" },
  nl: { title: "Hash Generator (SHA)", short: "Genereer SHA-1, SHA-256, SHA-384 and SHA-512 hashes of any tekst.", description: "Gratis hash generator. Compute SHA-1, SHA-256, SHA-384 and SHA-512 hex digests of any tekst using the Web Crypto API. Useful for controleersums and integrity controleers. Everything runs lokaal.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "controleersum", "tekst hash"], placeholder: "Enter tekst to hash…", algorithm: "Algorithm" },

  pl: { title: "Hash Generator (SHA)", short: "Generuj SHA-1, SHA-256, SHA-384 and SHA-512 hashes of any tekst.", description: "Darmowy hash generator. Compute SHA-1, SHA-256, SHA-384 and SHA-512 hex digests of any tekst using the Web Crypto API. Useful for sprawdźsums and integrity sprawdźs. Everything runs lokalnie.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "sprawdźsum", "tekst hash"], placeholder: "Enter tekst to hash…", algorithm: "Algorithm" },
  pt: { title: "Hash Generator (SHA)", short: "Gerar SHA-1, SHA-256, SHA-384 e SHA-512 hashes de any text.", description: "Gratuito - hash generator. Compute SHA-1, SHA-256, SHA-384 e SHA-512 hex digests de any text usando the Web Crypto API. Useful para checksums e integrity checks. Everything runs locally.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "checksum", "text hash"], placeholder: "Enter text to hash…", algorithm: "Algorithm" },
  id: { title: "Hash Generator (SHA)", short: "Hasilkan SHA-1, SHA-256, SHA-384 dan SHA-512 hashes dari any text.", description: "Gratis - hash generator. Compute SHA-1, SHA-256, SHA-384 dan SHA-512 hex digests dari any text menggunakan the Web Crypto API. Useful for checksums dan integrity checks. Everything runs locally.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "checksum", "text hash"], placeholder: "Enter text to hash…", algorithm: "Algorithm" },

  tr: { title: "Hash Üretici (SHA)", short: "Herhangi bir metnin SHA-1, SHA-256, SHA-384 ve SHA-512 hash'lerini üretin.", description: "Ücretsiz hash üretici. Web Crypto API kullanarak herhangi bir metnin SHA-1, SHA-256, SHA-384 ve SHA-512 onaltılık özetlerini hesaplayın. Sağlama toplamları ve bütünlük kontrolleri için kullanışlıdır. Her şey yerel çalışır.", keywords: ["hash üretici", "sha256 üretici", "sha1 hash", "sha512", "sağlama toplamı", "metin hash"], placeholder: "Hashlenecek metni girin…", algorithm: "Algoritma" },
  de: { title: "Hash-Generator (SHA)", short: "Erzeugen Sie SHA-1-, SHA-256-, SHA-384- und SHA-512-Hashes von Text.", description: "Kostenloser Hash-Generator. Berechnen Sie SHA-1-, SHA-256-, SHA-384- und SHA-512-Hex-Digests von Text mit der Web Crypto API. Nützlich für Prüfsummen und Integritätsprüfungen. Alles läuft lokal.", keywords: ["hash generator", "sha256 generator", "sha1 hash", "sha512", "prüfsumme", "text hash"], placeholder: "Text zum Hashen eingeben…", algorithm: "Algorithmus" },
  fr: { title: "Générateur de Hash (SHA)", short: "Générez des hachages SHA-1, SHA-256, SHA-384 et SHA-512 de tout texte.", description: "Générateur de hachage gratuit. Calculez les empreintes hexadécimales SHA-1, SHA-256, SHA-384 et SHA-512 de tout texte via la Web Crypto API. Utile pour les sommes de contrôle. Tout s'exécute localement.", keywords: ["générateur de hash", "sha256", "hash sha1", "sha512", "somme de contrôle", "hash de texte"], placeholder: "Saisissez le texte à hacher…", algorithm: "Algorithme" },
  es: { title: "Generador de Hash (SHA)", short: "Genera hashes SHA-1, SHA-256, SHA-384 y SHA-512 de cualquier texto.", description: "Generador de hash gratuito. Calcula los resúmenes hexadecimales SHA-1, SHA-256, SHA-384 y SHA-512 de cualquier texto con la Web Crypto API. Útil para sumas de verificación. Todo se ejecuta localmente.", keywords: ["generador de hash", "sha256", "hash sha1", "sha512", "suma de verificación", "hash de texto"], placeholder: "Introduce el texto a hashear…", algorithm: "Algoritmo" },
  it: { title: "Generatore di Hash (SHA)", short: "Genera hash SHA-1, SHA-256, SHA-384 e SHA-512 di qualsiasi testo.", description: "Generatore di hash gratuito. Calcola i digest esadecimali SHA-1, SHA-256, SHA-384 e SHA-512 di qualsiasi testo con la Web Crypto API. Utile per checksum e controlli di integrità. Tutto in locale.", keywords: ["generatore di hash", "sha256", "hash sha1", "sha512", "checksum", "hash di testo"], placeholder: "Inserisci il testo da hashare…", algorithm: "Algoritmo" },
  ar: { title: "مولّد التجزئة (SHA)", short: "أنشئ تجزئات SHA-1 و SHA-256 و SHA-384 و SHA-512 لأي نص.", description: "مولّد تجزئة مجاني. احسب ملخصات SHA-1 و SHA-256 و SHA-384 و SHA-512 السداسية لأي نص باستخدام Web Crypto API. مفيد للمجاميع الاختبارية. كل شيء يعمل محليًا.", keywords: ["مولد التجزئة", "sha256", "تجزئة sha1", "sha512", "مجموع اختباري", "تجزئة النص"], placeholder: "أدخل النص المراد تجزئته…", algorithm: "الخوارزمية" },
  ru: { title: "Генератор Хешей (SHA)", short: "Генерируйте хеши SHA-1, SHA-256, SHA-384 и SHA-512 любого текста.", description: "Бесплатный генератор хешей. Вычисляйте шестнадцатеричные дайджесты SHA-1, SHA-256, SHA-384 и SHA-512 любого текста через Web Crypto API. Полезно для контрольных сумм. Всё работает локально.", keywords: ["генератор хешей", "sha256", "хеш sha1", "sha512", "контрольная сумма", "хеш текста"], placeholder: "Введите текст для хеширования…", algorithm: "Алгоритм" },
  zh: { title: "哈希生成器 (SHA)", short: "生成任意文本的 SHA-1、SHA-256、SHA-384 和 SHA-512 哈希。", description: "免费的哈希生成器。使用 Web Crypto API 计算任意文本的 SHA-1、SHA-256、SHA-384 和 SHA-512 十六进制摘要。适用于校验和与完整性检查。一切都在本地运行。", keywords: ["哈希生成器", "sha256生成器", "sha1哈希", "sha512", "校验和", "文本哈希"], placeholder: "输入要哈希的文本…", algorithm: "算法" },
  ja: { title: "ハッシュ生成 (SHA)", short: "任意テキストの SHA-1・SHA-256・SHA-384・SHA-512 ハッシュを生成します。", description: "無料のハッシュ生成ツール。Web Crypto API を使って任意テキストの SHA-1・SHA-256・SHA-384・SHA-512 の 16 進ダイジェストを計算します。チェックサムや整合性チェックに便利。すべてローカルで実行されます。", keywords: ["ハッシュ生成", "sha256 生成", "sha1 ハッシュ", "sha512", "チェックサム", "テキストハッシュ"], placeholder: "ハッシュ化するテキストを入力…", algorithm: "アルゴリズム" },
  ko: { title: "해시 생성기 (SHA)", short: "임의 텍스트의 SHA-1, SHA-256, SHA-384, SHA-512 해시를 생성합니다.", description: "무료 해시 생성기. Web Crypto API로 임의 텍스트의 SHA-1, SHA-256, SHA-384, SHA-512 16진수 다이제스트를 계산합니다. 체크섬과 무결성 검사에 유용합니다. 모든 것이 로컬에서 실행됩니다.", keywords: ["해시 생성기", "sha256 생성기", "sha1 해시", "sha512", "체크섬", "텍스트 해시"], placeholder: "해시할 텍스트 입력…", algorithm: "알고리즘" },
  hi: { title: "हैश जनरेटर (SHA)", short: "किसी भी टेक्स्ट के SHA-1, SHA-256, SHA-384 और SHA-512 हैश बनाएं।", description: "मुफ्त हैश जनरेटर। Web Crypto API का उपयोग करके किसी भी टेक्स्ट के SHA-1, SHA-256, SHA-384 और SHA-512 हेक्स डाइजेस्ट की गणना करें। चेकसम और अखंडता जाँच के लिए उपयोगी। सब कुछ स्थानीय रूप से चलता है।", keywords: ["हैश जनरेटर", "sha256 जनरेटर", "sha1 हैश", "sha512", "चेकसम", "टेक्स्ट हैश"], placeholder: "हैश करने के लिए टेक्स्ट दर्ज करें…", algorithm: "एल्गोरिदम" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
