import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Regex Tester", short: "Test a regular expression against text and see every match.", description: "Free regex tester. Enter a JavaScript regular expression and flags, paste your text, and instantly see all matches with their positions and capture groups. Runs in your browser.", keywords: ["regex tester", "regular expression tester", "test regex", "regex match", "regexp online"], pattern: "Pattern", flags: "Flags", placeholder: "Text to test against…", invalid: "Invalid regular expression.", matches: "matches", noMatches: "No matches.", match: "Match", index: "Index", groups: "Groups" },
  tr: { title: "Regex Test Aracı", short: "Bir düzenli ifadeyi metne karşı test edin ve tüm eşleşmeleri görün.", description: "Ücretsiz regex test aracı. Bir JavaScript düzenli ifadesi ve bayraklar girin, metninizi yapıştırın ve tüm eşleşmeleri konumları ve yakalama gruplarıyla anında görün. Tarayıcınızda çalışır.", keywords: ["regex test aracı", "düzenli ifade test", "regex test", "regex eşleşme", "regexp çevrimiçi"], pattern: "Desen", flags: "Bayraklar", placeholder: "Test edilecek metin…", invalid: "Geçersiz düzenli ifade.", matches: "eşleşme", noMatches: "Eşleşme yok.", match: "Eşleşme", index: "Konum", groups: "Gruplar" },
  de: { title: "Regex-Tester", short: "Testen Sie einen regulären Ausdruck gegen Text und sehen Sie jeden Treffer.", description: "Kostenloser Regex-Tester. Geben Sie einen JavaScript-Regex und Flags ein, fügen Sie Ihren Text ein und sehen Sie sofort alle Treffer mit Positionen und Gruppen. Läuft im Browser.", keywords: ["regex tester", "regulärer ausdruck tester", "regex testen", "regex treffer", "regexp online"], pattern: "Muster", flags: "Flags", placeholder: "Zu testender Text…", invalid: "Ungültiger regulärer Ausdruck.", matches: "Treffer", noMatches: "Keine Treffer.", match: "Treffer", index: "Position", groups: "Gruppen" },
  fr: { title: "Testeur de Regex", short: "Testez une expression régulière sur du texte et voyez chaque correspondance.", description: "Testeur de regex gratuit. Saisissez une expression régulière JavaScript et des drapeaux, collez votre texte et voyez instantanément toutes les correspondances avec positions et groupes. S'exécute dans votre navigateur.", keywords: ["testeur de regex", "testeur expression régulière", "tester regex", "correspondance regex", "regexp en ligne"], pattern: "Motif", flags: "Drapeaux", placeholder: "Texte à tester…", invalid: "Expression régulière non valide.", matches: "correspondances", noMatches: "Aucune correspondance.", match: "Correspondance", index: "Position", groups: "Groupes" },
  es: { title: "Probador de Regex", short: "Prueba una expresión regular contra texto y ve cada coincidencia.", description: "Probador de regex gratuito. Introduce una expresión regular de JavaScript y banderas, pega tu texto y ve al instante todas las coincidencias con sus posiciones y grupos. Se ejecuta en tu navegador.", keywords: ["probador de regex", "probador expresión regular", "probar regex", "coincidencia regex", "regexp en línea"], pattern: "Patrón", flags: "Banderas", placeholder: "Texto a probar…", invalid: "Expresión regular no válida.", matches: "coincidencias", noMatches: "Sin coincidencias.", match: "Coincidencia", index: "Posición", groups: "Grupos" },
  it: { title: "Tester di Regex", short: "Testa un'espressione regolare su un testo e vedi ogni corrispondenza.", description: "Tester di regex gratuito. Inserisci un'espressione regolare JavaScript e i flag, incolla il tuo testo e vedi all'istante tutte le corrispondenze con posizioni e gruppi. Funziona nel browser.", keywords: ["tester regex", "tester espressione regolare", "testare regex", "corrispondenza regex", "regexp online"], pattern: "Pattern", flags: "Flag", placeholder: "Testo da testare…", invalid: "Espressione regolare non valida.", matches: "corrispondenze", noMatches: "Nessuna corrispondenza.", match: "Corrispondenza", index: "Posizione", groups: "Gruppi" },
  ar: { title: "أداة اختبار Regex", short: "اختبر تعبيرًا نمطيًا على نص وشاهد كل تطابق.", description: "أداة اختبار regex مجانية. أدخل تعبيرًا نمطيًا بلغة JavaScript والأعلام، الصق نصك، وشاهد فورًا كل التطابقات مع مواضعها ومجموعات الالتقاط. تعمل في متصفحك.", keywords: ["أداة اختبار regex", "اختبار التعبير النمطي", "اختبار regex", "تطابق regex", "regexp عبر الإنترنت"], pattern: "النمط", flags: "الأعلام", placeholder: "النص المراد اختباره…", invalid: "تعبير نمطي غير صالح.", matches: "تطابقات", noMatches: "لا توجد تطابقات.", match: "تطابق", index: "الموضع", groups: "المجموعات" },
  ru: { title: "Тестер Regex", short: "Проверьте регулярное выражение на тексте и посмотрите все совпадения.", description: "Бесплатный тестер regex. Введите регулярное выражение JavaScript и флаги, вставьте текст и сразу увидьте все совпадения с их позициями и группами. Работает в браузере.", keywords: ["тестер regex", "тестер регулярных выражений", "проверить regex", "совпадение regex", "regexp онлайн"], pattern: "Шаблон", flags: "Флаги", placeholder: "Текст для проверки…", invalid: "Недопустимое регулярное выражение.", matches: "совпадений", noMatches: "Нет совпадений.", match: "Совпадение", index: "Позиция", groups: "Группы" },
  zh: { title: "正则表达式测试器", short: "用文本测试正则表达式并查看每个匹配。", description: "免费的正则表达式测试器。输入 JavaScript 正则表达式和标志，粘贴文本，即可立即查看所有匹配及其位置和捕获组。在浏览器中运行。", keywords: ["正则测试器", "正则表达式测试", "测试正则", "正则匹配", "regexp在线"], pattern: "模式", flags: "标志", placeholder: "要测试的文本…", invalid: "无效的正则表达式。", matches: "处匹配", noMatches: "无匹配。", match: "匹配", index: "位置", groups: "捕获组" },
  ja: { title: "正規表現テスター", short: "正規表現をテキストに対してテストし、すべての一致を確認します。", description: "無料の正規表現テスター。JavaScript の正規表現とフラグを入力し、テキストを貼り付けると、すべての一致が位置とキャプチャグループとともに即座に表示されます。ブラウザ内で動作します。", keywords: ["正規表現テスター", "正規表現 テスト", "regex テスト", "regex 一致", "regexp オンライン"], pattern: "パターン", flags: "フラグ", placeholder: "テスト対象のテキスト…", invalid: "無効な正規表現です。", matches: "件一致", noMatches: "一致なし。", match: "一致", index: "位置", groups: "グループ" },
  ko: { title: "정규식 테스터", short: "정규식을 텍스트에 대해 테스트하고 모든 일치를 확인합니다.", description: "무료 정규식 테스터. JavaScript 정규식과 플래그를 입력하고 텍스트를 붙여넣으면 모든 일치 항목이 위치와 캡처 그룹과 함께 즉시 표시됩니다. 브라우저에서 실행됩니다.", keywords: ["정규식 테스터", "정규 표현식 테스트", "regex 테스트", "regex 일치", "regexp 온라인"], pattern: "패턴", flags: "플래그", placeholder: "테스트할 텍스트…", invalid: "잘못된 정규식입니다.", matches: "개 일치", noMatches: "일치 없음.", match: "일치", index: "위치", groups: "그룹" },
  hi: { title: "Regex टेस्टर", short: "टेक्स्ट के विरुद्ध रेगुलर एक्सप्रेशन का परीक्षण करें और हर मिलान देखें।", description: "मुफ्त regex टेस्टर। एक JavaScript रेगुलर एक्सप्रेशन और फ्लैग दर्ज करें, अपना टेक्स्ट पेस्ट करें, और सभी मिलान उनकी स्थिति व कैप्चर समूहों के साथ तुरंत देखें। ब्राउज़र में चलता है।", keywords: ["regex टेस्टर", "रेगुलर एक्सप्रेशन परीक्षण", "regex परीक्षण", "regex मिलान", "regexp ऑनलाइन"], pattern: "पैटर्न", flags: "फ्लैग", placeholder: "परीक्षण के लिए टेक्स्ट…", invalid: "अमान्य रेगुलर एक्सप्रेशन।", matches: "मिलान", noMatches: "कोई मिलान नहीं।", match: "मिलान", index: "स्थिति", groups: "समूह" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
