import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Duration Between Two Datetimes", short: "Compute days, hours, minutes and seconds between two times.", description: "Free duration calculator. Pick a start and end datetime to see the difference in days, hours, minutes, seconds plus the total in milliseconds and weeks.", keywords: ["duration calculator", "time between two dates", "datetime difference", "how long between", "elapsed time"], start: "Start", end: "End", days: "Days", hours: "Hours", minutes: "Minutes", seconds: "Seconds", weeks: "Weeks", totalMs: "Total (ms)", humanized: "Humanized" },
  tr: { title: "İki Zaman Arasındaki Süre", short: "İki zaman arasındaki gün, saat, dakika ve saniyeyi hesaplayın.", description: "Ücretsiz süre hesaplayıcı. Başlangıç ve bitiş zamanı seçin; aradaki farkı gün, saat, dakika, saniye olarak ve toplam milisaniye ve hafta cinsinden görün.", keywords: ["süre hesaplayıcı", "iki tarih arasındaki zaman", "tarih farkı", "ne kadar zaman", "geçen süre"], start: "Başlangıç", end: "Bitiş", days: "Gün", hours: "Saat", minutes: "Dakika", seconds: "Saniye", weeks: "Hafta", totalMs: "Toplam (ms)", humanized: "İnsan okunaklı" },
  de: { title: "Dauer zwischen zwei Zeitpunkten", short: "Berechnen Sie Tage, Stunden, Minuten und Sekunden zwischen zwei Zeiten.", description: "Kostenloser Dauer-Rechner. Wählen Sie einen Start- und Endzeitpunkt, um die Differenz in Tagen, Stunden, Minuten, Sekunden plus Gesamtmillisekunden und Wochen zu sehen.", keywords: ["dauer rechner", "zeit zwischen zwei daten", "zeitdifferenz", "wie lange zwischen", "verstrichene zeit"], start: "Start", end: "Ende", days: "Tage", hours: "Stunden", minutes: "Minuten", seconds: "Sekunden", weeks: "Wochen", totalMs: "Gesamt (ms)", humanized: "Lesbar" },
  fr: { title: "Durée entre deux dates", short: "Calculez jours, heures, minutes et secondes entre deux moments.", description: "Calculateur de durée gratuit. Choisissez une date/heure de début et de fin pour voir la différence en jours, heures, minutes, secondes plus le total en millisecondes et semaines.", keywords: ["calculateur durée", "temps entre deux dates", "différence date heure", "combien de temps entre", "temps écoulé"], start: "Début", end: "Fin", days: "Jours", hours: "Heures", minutes: "Minutes", seconds: "Secondes", weeks: "Semaines", totalMs: "Total (ms)", humanized: "Lisible" },
  es: { title: "Duración entre dos fechas", short: "Calcula días, horas, minutos y segundos entre dos momentos.", description: "Calculadora de duración gratuita. Elige fecha/hora de inicio y fin para ver la diferencia en días, horas, minutos, segundos más el total en milisegundos y semanas.", keywords: ["calculadora duración", "tiempo entre dos fechas", "diferencia fecha hora", "cuánto tiempo entre", "tiempo transcurrido"], start: "Inicio", end: "Fin", days: "Días", hours: "Horas", minutes: "Minutos", seconds: "Segundos", weeks: "Semanas", totalMs: "Total (ms)", humanized: "Legible" },
  it: { title: "Durata tra due date e ore", short: "Calcola giorni, ore, minuti e secondi tra due momenti.", description: "Calcolatore di durata gratuito. Scegli un orario di inizio e fine per vedere la differenza in giorni, ore, minuti, secondi più il totale in millisecondi e settimane.", keywords: ["calcolatore durata", "tempo tra due date", "differenza data ora", "quanto tempo tra", "tempo trascorso"], start: "Inizio", end: "Fine", days: "Giorni", hours: "Ore", minutes: "Minuti", seconds: "Secondi", weeks: "Settimane", totalMs: "Totale (ms)", humanized: "Leggibile" },
  ar: { title: "المدة بين تاريخين ووقتين", short: "احسب الأيام والساعات والدقائق والثواني بين وقتين.", description: "حاسبة مدة مجانية. اختر وقتي بداية ونهاية لرؤية الفرق بالأيام والساعات والدقائق والثواني بالإضافة إلى الإجمالي بالميلي ثانية والأسابيع.", keywords: ["حاسبة المدة", "الوقت بين تاريخين", "فرق التاريخ والوقت", "كم من الوقت بين", "الوقت المنقضي"], start: "البداية", end: "النهاية", days: "أيام", hours: "ساعات", minutes: "دقائق", seconds: "ثوانٍ", weeks: "أسابيع", totalMs: "الإجمالي (ms)", humanized: "قابل للقراءة" },
  ru: { title: "Длительность между двумя датами", short: "Вычислите дни, часы, минуты и секунды между двумя моментами.", description: "Бесплатный калькулятор длительности. Выберите начальное и конечное время, чтобы увидеть разницу в днях, часах, минутах, секундах плюс общую в миллисекундах и неделях.", keywords: ["калькулятор длительности", "время между датами", "разница даты времени", "сколько времени между", "прошедшее время"], start: "Начало", end: "Конец", days: "Дни", hours: "Часы", minutes: "Минуты", seconds: "Секунды", weeks: "Недели", totalMs: "Всего (ms)", humanized: "Читаемо" },
  zh: { title: "两个时间之间的时长", short: "计算两个时间之间的天数、小时、分钟和秒。", description: "免费的时长计算器。选择起始和结束时间以查看天、小时、分钟、秒的差值以及总毫秒数和周数。", keywords: ["时长计算器", "两个日期之间的时间", "日期时间差", "之间多久", "已用时间"], start: "开始", end: "结束", days: "天", hours: "小时", minutes: "分钟", seconds: "秒", weeks: "周", totalMs: "总计 (ms)", humanized: "可读" },
  ja: { title: "2つの日時間の経過時間", short: "2つの時刻の間の日、時、分、秒を計算。", description: "無料の経過時間計算ツール。開始と終了の日時を選んで、日、時、分、秒の差と総ミリ秒、週を確認できます。", keywords: ["経過時間 計算", "2つの日付の間の時間", "日時差", "間どのくらい", "経過した時間"], start: "開始", end: "終了", days: "日", hours: "時", minutes: "分", seconds: "秒", weeks: "週", totalMs: "合計 (ms)", humanized: "読みやすい" },
  ko: { title: "두 날짜/시간 사이의 기간", short: "두 시점 사이의 일, 시간, 분, 초를 계산합니다.", description: "무료 기간 계산기. 시작과 종료 날짜/시간을 선택해 일, 시간, 분, 초의 차이와 총 밀리초 및 주를 확인하세요.", keywords: ["기간 계산기", "두 날짜 사이의 시간", "날짜 시간 차이", "얼마나 사이", "경과 시간"], start: "시작", end: "끝", days: "일", hours: "시간", minutes: "분", seconds: "초", weeks: "주", totalMs: "총 (ms)", humanized: "사람이 읽기 쉬운" },
  hi: { title: "दो तिथियों के बीच की अवधि", short: "दो समय बिंदुओं के बीच दिन, घंटे, मिनट और सेकंड की गणना करें।", description: "मुफ्त अवधि कैलकुलेटर। शुरुआत और अंत का दिन/समय चुनें और दिन, घंटे, मिनट, सेकंड के अंतर के साथ-साथ कुल मिलीसेकंड और सप्ताह देखें।", keywords: ["अवधि कैलकुलेटर", "दो तारीखों के बीच समय", "तारीख समय अंतर", "कितना समय बीच", "बीता समय"], start: "शुरुआत", end: "अंत", days: "दिन", hours: "घंटे", minutes: "मिनट", seconds: "सेकंड", weeks: "सप्ताह", totalMs: "कुल (ms)", humanized: "मानव पठनीय" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
