import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text to Hex Converter", short: "Convert text to hexadecimal and hex back to text (UTF-8).", description: "Free text-to-hex converter. Turn any text into the hexadecimal of its UTF-8 bytes, or decode hex (with or without spaces and 0x prefixes) back to text. Runs in your browser.", keywords: ["text to hex", "hex to text", "ascii to hex", "hexadecimal converter", "hex encoder"], toHex: "Text → Hex", toText: "Hex → Text", placeholder: "Enter text or hex…", invalid: "Invalid hex input." },
  pt: { title: "Text to Hex Converter", short: "Convert text to hexadecimal and hex back to text (UTF-8).", description: "Free text-to-hex converter. Turn any text into the hexadecimal of its UTF-8 bytes, or decode hex (with or without spaces and 0x prefixes) back to text. Runs in your browser.", keywords: ["text to hex", "hex to text", "ascii to hex", "hexadecimal converter", "hex encoder"], toHex: "Text → Hex", toText: "Hex → Text", placeholder: "Enter text or hex…", invalid: "Invalid hex input." },
  id: { title: "Text to Hex Converter", short: "Convert text to hexadecimal and hex back to text (UTF-8).", description: "Free text-to-hex converter. Turn any text into the hexadecimal of its UTF-8 bytes, or decode hex (with or without spaces and 0x prefixes) back to text. Runs in your browser.", keywords: ["text to hex", "hex to text", "ascii to hex", "hexadecimal converter", "hex encoder"], toHex: "Text → Hex", toText: "Hex → Text", placeholder: "Enter text or hex…", invalid: "Invalid hex input." },

  tr: { title: "Metin–Hex Dönüştürücü", short: "Metni onaltılığa (hex) ve hex'i metne çevirin (UTF-8).", description: "Ücretsiz metin–hex dönüştürücü. Herhangi bir metni UTF-8 baytlarının onaltılığına çevirin veya hex'i (boşluklu/boşluksuz ve 0x önekli) metne geri çözün. Tarayıcınızda çalışır.", keywords: ["metinden hex", "hexten metne", "ascii hex", "onaltılık dönüştürücü", "hex kodlayıcı"], toHex: "Metin → Hex", toText: "Hex → Metin", placeholder: "Metin veya hex girin…", invalid: "Geçersiz hex girdi." },
  de: { title: "Text-zu-Hex-Konverter", short: "Text in Hexadezimal und Hex zurück in Text umwandeln (UTF-8).", description: "Kostenloser Text-zu-Hex-Konverter. Wandeln Sie Text in das Hexadezimal seiner UTF-8-Bytes um oder dekodieren Sie Hex (mit/ohne Leerzeichen und 0x-Präfixe) zurück in Text.", keywords: ["text zu hex", "hex zu text", "ascii hex", "hexadezimal konverter", "hex encoder"], toHex: "Text → Hex", toText: "Hex → Text", placeholder: "Text oder Hex eingeben…", invalid: "Ungültige Hex-Eingabe." },
  fr: { title: "Convertisseur Texte–Hexadécimal", short: "Convertissez du texte en hexadécimal et inversement (UTF-8).", description: "Convertisseur texte-hexadécimal gratuit. Transformez n'importe quel texte en l'hexadécimal de ses octets UTF-8, ou décodez de l'hex (avec ou sans espaces et préfixes 0x) en texte.", keywords: ["texte vers hex", "hex vers texte", "ascii hex", "convertisseur hexadécimal", "encodeur hex"], toHex: "Texte → Hex", toText: "Hex → Texte", placeholder: "Saisissez du texte ou de l'hex…", invalid: "Entrée hex invalide." },
  es: { title: "Conversor de Texto a Hex", short: "Convierte texto a hexadecimal y hex a texto (UTF-8).", description: "Conversor de texto a hex gratuito. Convierte cualquier texto en el hexadecimal de sus bytes UTF-8, o decodifica hex (con o sin espacios y prefijos 0x) a texto. Se ejecuta en tu navegador.", keywords: ["texto a hex", "hex a texto", "ascii a hex", "conversor hexadecimal", "codificador hex"], toHex: "Texto → Hex", toText: "Hex → Texto", placeholder: "Introduce texto o hex…", invalid: "Entrada hex no válida." },
  it: { title: "Convertitore Testo–Esadecimale", short: "Converti testo in esadecimale ed esadecimale in testo (UTF-8).", description: "Convertitore testo-esadecimale gratuito. Trasforma qualsiasi testo nell'esadecimale dei suoi byte UTF-8, o decodifica l'hex (con o senza spazi e prefissi 0x) in testo.", keywords: ["testo in hex", "hex in testo", "ascii hex", "convertitore esadecimale", "encoder hex"], toHex: "Testo → Hex", toText: "Hex → Testo", placeholder: "Inserisci testo o hex…", invalid: "Input hex non valido." },
  ar: { title: "محوّل النص إلى سداسي عشري", short: "حوّل النص إلى سداسي عشري والعكس (UTF-8).", description: "محوّل نص إلى سداسي عشري مجاني. حوّل أي نص إلى السداسي العشري لبايتات UTF-8، أو فك ترميز السداسي العشري (مع/بدون مسافات وبادئات 0x) إلى نص.", keywords: ["نص إلى hex", "hex إلى نص", "ascii hex", "محول سداسي عشري", "مرمز hex"], toHex: "نص → Hex", toText: "Hex → نص", placeholder: "أدخل نصًا أو hex…", invalid: "إدخال hex غير صالح." },
  ru: { title: "Конвертер Текста в Hex", short: "Преобразуйте текст в шестнадцатеричный код и обратно (UTF-8).", description: "Бесплатный конвертер текста в hex. Преобразуйте любой текст в шестнадцатеричный код его UTF-8 байтов или декодируйте hex (с пробелами/без и с префиксами 0x) обратно в текст.", keywords: ["текст в hex", "hex в текст", "ascii в hex", "шестнадцатеричный конвертер", "hex кодировщик"], toHex: "Текст → Hex", toText: "Hex → Текст", placeholder: "Введите текст или hex…", invalid: "Недопустимый hex-ввод." },
  zh: { title: "文本转十六进制转换器", short: "在文本与十六进制之间相互转换（UTF-8）。", description: "免费的文本转十六进制转换器。将任意文本转换为其 UTF-8 字节的十六进制，或将十六进制（可含空格和 0x 前缀）解码为文本。在浏览器中运行。", keywords: ["文本转十六进制", "十六进制转文本", "ascii转十六进制", "十六进制转换器", "hex编码"], toHex: "文本 → 十六进制", toText: "十六进制 → 文本", placeholder: "输入文本或十六进制…", invalid: "无效的十六进制输入。" },
  ja: { title: "テキスト⇔16進数変換", short: "テキストを16進数に、16進数をテキストに変換します（UTF-8）。", description: "無料のテキスト⇔16進数変換ツール。任意のテキストを UTF-8 バイトの16進数に変換、または16進数（空白や 0x 接頭辞の有無を問わず）をテキストにデコードします。", keywords: ["テキスト 16進数", "16進数 テキスト", "ascii 16進", "16進数 変換", "hex エンコード"], toHex: "テキスト → 16進数", toText: "16進数 → テキスト", placeholder: "テキストまたは16進数を入力…", invalid: "無効な16進数入力です。" },
  ko: { title: "텍스트 ⇔ 16진수 변환기", short: "텍스트를 16진수로, 16진수를 텍스트로 변환합니다(UTF-8).", description: "무료 텍스트-16진수 변환기. 임의의 텍스트를 UTF-8 바이트의 16진수로 변환하거나 16진수(공백 및 0x 접두사 유무 무관)를 텍스트로 디코딩합니다. 브라우저에서 실행됩니다.", keywords: ["텍스트 16진수", "16진수 텍스트", "ascii 16진수", "16진수 변환기", "hex 인코더"], toHex: "텍스트 → 16진수", toText: "16진수 → 텍스트", placeholder: "텍스트 또는 16진수 입력…", invalid: "잘못된 16진수 입력입니다." },
  hi: { title: "टेक्स्ट से हेक्स कन्वर्टर", short: "टेक्स्ट को हेक्साडेसिमल में और हेक्स को टेक्स्ट में बदलें (UTF-8)।", description: "मुफ्त टेक्स्ट-से-हेक्स कन्वर्टर। किसी भी टेक्स्ट को उसके UTF-8 बाइट्स के हेक्साडेसिमल में बदलें, या हेक्स (स्पेस और 0x उपसर्ग सहित/बिना) को टेक्स्ट में डिकोड करें। ब्राउज़र में चलता है।", keywords: ["टेक्स्ट से हेक्स", "हेक्स से टेक्स्ट", "ascii से हेक्स", "हेक्साडेसिमल कन्वर्टर", "हेक्स एन्कोडर"], toHex: "टेक्स्ट → हेक्स", toText: "हेक्स → टेक्स्ट", placeholder: "टेक्स्ट या हेक्स दर्ज करें…", invalid: "अमान्य हेक्स इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
