import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Fake Data Generator", short: "Generate fake people for testing and seed data.", description: "Free fake data generator. Create a batch of fake people with names, emails, phones, addresses and companies — view as a table, export as CSV or JSON, generated in your browser.", keywords: ["fake data generator", "faker", "test data", "mock data", "seed data generator"], count: "Count", generate: "Generate", csv: "CSV", json: "JSON" },
  tr: { title: "Sahte Veri Oluşturucu", short: "Test ve seed verisi için sahte kişiler oluşturun.", description: "Ücretsiz sahte veri oluşturucu. Ad, e-posta, telefon, adres ve şirket bilgileriyle bir grup sahte kişi oluşturun — tablo olarak görüntüleyin, CSV veya JSON olarak dışa aktarın, tarayıcınızda oluşturulur.", keywords: ["sahte veri oluşturucu", "faker", "test verisi", "mock veri", "seed veri oluşturucu"], count: "Adet", generate: "Oluştur", csv: "CSV", json: "JSON" },
  de: { title: "Fake-Daten-Generator", short: "Erzeugen Sie fiktive Personen für Tests und Seed-Daten.", description: "Kostenloser Fake-Daten-Generator. Erstellen Sie eine Reihe fiktiver Personen mit Namen, E-Mails, Telefonnummern, Adressen und Firmen — als Tabelle anzeigen, als CSV oder JSON exportieren, im Browser erzeugt.", keywords: ["fake daten generator", "faker", "testdaten", "mock daten", "seed daten generator"], count: "Anzahl", generate: "Erzeugen", csv: "CSV", json: "JSON" },
  fr: { title: "Générateur de Données Fictives", short: "Générez des personnes fictives pour tests et données seed.", description: "Générateur de données fictives gratuit. Créez un lot de personnes fictives avec noms, emails, téléphones, adresses et entreprises — vue tableau, export CSV ou JSON, généré dans votre navigateur.", keywords: ["générateur données fictives", "faker", "données test", "données mock", "générateur données seed"], count: "Nombre", generate: "Générer", csv: "CSV", json: "JSON" },
  es: { title: "Generador de Datos Falsos", short: "Genera personas falsas para pruebas y datos seed.", description: "Generador de datos falsos gratuito. Crea un lote de personas falsas con nombres, emails, teléfonos, direcciones y empresas — vista en tabla, exporta a CSV o JSON, generado en tu navegador.", keywords: ["generador datos falsos", "faker", "datos prueba", "datos mock", "generador datos seed"], count: "Cantidad", generate: "Generar", csv: "CSV", json: "JSON" },
  it: { title: "Generatore di Dati Falsi", short: "Genera persone fittizie per test e dati seed.", description: "Generatore di dati falsi gratuito. Crea un lotto di persone fittizie con nomi, email, telefoni, indirizzi e aziende — visualizza come tabella, esporta come CSV o JSON, generato nel browser.", keywords: ["generatore dati falsi", "faker", "dati di test", "dati mock", "generatore dati seed"], count: "Quantità", generate: "Genera", csv: "CSV", json: "JSON" },
  ar: { title: "مولّد بيانات وهمية", short: "أنشئ أشخاصًا وهميين للاختبار وبيانات seed.", description: "مولّد بيانات وهمية مجاني. أنشئ دفعة من الأشخاص الوهميين مع الأسماء والبريد الإلكتروني والهواتف والعناوين والشركات — اعرضها كجدول، صدّر كـ CSV أو JSON، تُنشأ في متصفحك.", keywords: ["مولد بيانات وهمية", "faker", "بيانات اختبار", "بيانات وهمية", "مولد بيانات seed"], count: "العدد", generate: "توليد", csv: "CSV", json: "JSON" },
  ru: { title: "Генератор фейковых данных", short: "Создавайте фейковых людей для тестов и seed-данных.", description: "Бесплатный генератор фейковых данных. Создайте пакет фейковых людей с именами, email, телефонами, адресами и компаниями — таблица, экспорт в CSV или JSON, генерируется в браузере.", keywords: ["генератор фейковых данных", "faker", "тестовые данные", "mock данные", "генератор seed данных"], count: "Количество", generate: "Создать", csv: "CSV", json: "JSON" },
  zh: { title: "假数据生成器", short: "为测试和种子数据生成虚构人物。", description: "免费的假数据生成器。生成一批包含姓名、电子邮件、电话、地址和公司的虚构人物——以表格查看、导出为 CSV 或 JSON，在浏览器中生成。", keywords: ["假数据生成器", "faker", "测试数据", "模拟数据", "种子数据生成器"], count: "数量", generate: "生成", csv: "CSV", json: "JSON" },
  ja: { title: "フェイクデータ生成", short: "テストやシードデータ用の架空の人物を生成。", description: "無料のフェイクデータ生成ツール。名前、メール、電話、住所、会社を持つ架空の人物のバッチを作成し、テーブル表示、CSV または JSON でエクスポート——ブラウザ内で生成。", keywords: ["フェイクデータ 生成", "faker", "テストデータ", "モック データ", "シード データ 生成"], count: "数", generate: "生成", csv: "CSV", json: "JSON" },
  ko: { title: "가짜 데이터 생성기", short: "테스트 및 시드 데이터용 가짜 인물을 생성합니다.", description: "무료 가짜 데이터 생성기. 이름, 이메일, 전화, 주소, 회사를 가진 가짜 인물 배치를 생성하고 테이블로 보거나 CSV/JSON으로 내보냅니다 — 브라우저에서 생성됩니다.", keywords: ["가짜 데이터 생성기", "faker", "테스트 데이터", "목 데이터", "시드 데이터 생성기"], count: "개수", generate: "생성", csv: "CSV", json: "JSON" },
  hi: { title: "नकली डेटा जनरेटर", short: "परीक्षण और सीड डेटा के लिए नकली व्यक्ति बनाएं।", description: "मुफ्त नकली डेटा जनरेटर। नाम, ईमेल, फोन, पते और कंपनियों वाले नकली व्यक्तियों का एक बैच बनाएं — तालिका के रूप में देखें, CSV या JSON के रूप में निर्यात करें, आपके ब्राउज़र में जनरेट होते हैं।", keywords: ["नकली डेटा जनरेटर", "faker", "परीक्षण डेटा", "मॉक डेटा", "सीड डेटा जनरेटर"], count: "संख्या", generate: "जनरेट करें", csv: "CSV", json: "JSON" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
