import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const KW = ["ipv6 ula generator", "unique local address", "rfc 4193 prefix", "fd00 prefix generator", "ipv6 private address"];

const data = {
  en: { title: "IPv6 ULA Generator", short: "Generate a random RFC 4193 Unique Local Address prefix (fd00::/8) for private IPv6 networks.", description: "Free IPv6 ULA generator. Create a random RFC 4193 Unique Local Address with a /48 prefix and a sample /64 subnet for your private IPv6 network. Uses a secure random Global ID and runs entirely in your browser.", keywords: KW, generate: "Generate", globalId: "Global ID", prefix48: "/48 prefix", sampleSubnet: "Sample /64 subnet" },
  nl: { title: "IPv6 ULA Generator", short: "Genereer a willekeurig RFC 4193 Unique Local Address prefix (fd00::/8) for private IPv6 networks.", description: "Gratis IPv6 ULA generator. Maak aan a willekeurig RFC 4193 Unique Local Address with a /48 prefix and a sample /64 subnet for your private IPv6 network. Uses a veilig willekeurig Global ID and runs entirely in uw browser.", keywords: KW, generate: "Genereer", globalId: "Global ID", prefix48: "/48 prefix", sampleSubnet: "Sample /64 subnet" },

  pl: { title: "IPv6 ULA Generator", short: "Generuj a losowy RFC 4193 Unique Local Address prefix (fd00::/8) for private IPv6 networks.", description: "Darmowy IPv6 ULA generator. Utwórz a losowy RFC 4193 Unique Local Address with a /48 prefix and a sample /64 subnet for your private IPv6 network. Uses a bezpieczne losowy Global ID and runs entirely w Twojej przeglądarce.", keywords: KW, generate: "Generuj", globalId: "Global ID", prefix48: "/48 prefix", sampleSubnet: "Sample /64 subnet" },
  pt: { title: "Gerador de ULA IPv6", short: "Gere um prefixo de Endereço Local Único RFC 4193 (fd00::/8) aleatório para redes IPv6 privadas.", description: "Gerador de ULA IPv6 gratuito. Crie um Endereço Local Único RFC 4193 aleatório com prefixo /48 e uma sub-rede /64 de exemplo para sua rede IPv6 privada. Usa um Global ID aleatório seguro e roda inteiramente no seu navegador.", keywords: KW, generate: "Gerar", globalId: "Global ID", prefix48: "Prefixo /48", sampleSubnet: "Sub-rede /64 de exemplo" },
  id: { title: "Generator ULA IPv6", short: "Hasilkan prefiks Unique Local Address RFC 4193 (fd00::/8) acak untuk jaringan IPv6 privat.", description: "Generator ULA IPv6 gratis. Buat Unique Local Address RFC 4193 acak dengan prefiks /48 dan contoh subnet /64 untuk jaringan IPv6 privat Anda. Menggunakan Global ID acak yang aman dan berjalan sepenuhnya di browser Anda.", keywords: KW, generate: "Hasilkan", globalId: "Global ID", prefix48: "Prefiks /48", sampleSubnet: "Contoh subnet /64" },

  tr: { title: "IPv6 ULA Üreticisi", short: "Özel IPv6 ağları için rastgele bir RFC 4193 Benzersiz Yerel Adres öneki (fd00::/8) üretin.", description: "Ücretsiz IPv6 ULA üreticisi. Özel IPv6 ağınız için /48 öneki ve örnek bir /64 alt ağı olan rastgele bir RFC 4193 Benzersiz Yerel Adresi oluşturun. Güvenli rastgele bir Global ID kullanır ve tamamen tarayıcınızda çalışır.", keywords: ["ipv6 ula üretici", "benzersiz yerel adres", "rfc 4193 öneki", "fd00 öneki üretici", "ipv6 özel adres"], generate: "Üret", globalId: "Global ID", prefix48: "/48 öneki", sampleSubnet: "Örnek /64 alt ağı" },
  de: { title: "IPv6 ULA Generator", short: "Erzeugen Sie ein zufälliges RFC-4193-Präfix für eindeutige lokale Adressen (fd00::/8) für private IPv6-Netze.", description: "Kostenloser IPv6-ULA-Generator. Erstellen Sie eine zufällige eindeutige lokale RFC-4193-Adresse mit einem /48-Präfix und einem Beispiel-/64-Subnetz für Ihr privates IPv6-Netz. Verwendet eine sichere zufällige Global ID und läuft vollständig in Ihrem Browser.", keywords: ["ipv6 ula generator", "eindeutige lokale adresse", "rfc 4193 präfix", "fd00 präfix generator", "ipv6 private adresse"], generate: "Generieren", globalId: "Global ID", prefix48: "/48-Präfix", sampleSubnet: "Beispiel-/64-Subnetz" },
  fr: { title: "Générateur ULA IPv6", short: "Générez un préfixe d'adresse locale unique RFC 4193 (fd00::/8) aléatoire pour les réseaux IPv6 privés.", description: "Générateur ULA IPv6 gratuit. Créez une adresse locale unique RFC 4193 aléatoire avec un préfixe /48 et un sous-réseau /64 d'exemple pour votre réseau IPv6 privé. Utilise un Global ID aléatoire sécurisé et fonctionne entièrement dans votre navigateur.", keywords: ["générateur ula ipv6", "adresse locale unique", "préfixe rfc 4193", "générateur préfixe fd00", "adresse privée ipv6"], generate: "Générer", globalId: "Global ID", prefix48: "Préfixe /48", sampleSubnet: "Sous-réseau /64 d'exemple" },
  es: { title: "Generador de ULA IPv6", short: "Genera un prefijo de dirección local única RFC 4193 (fd00::/8) aleatorio para redes IPv6 privadas.", description: "Generador de ULA IPv6 gratuito. Crea una dirección local única RFC 4193 aleatoria con un prefijo /48 y una subred /64 de ejemplo para tu red IPv6 privada. Usa un Global ID aleatorio seguro y se ejecuta completamente en tu navegador.", keywords: ["generador ula ipv6", "dirección local única", "prefijo rfc 4193", "generador prefijo fd00", "dirección privada ipv6"], generate: "Generar", globalId: "Global ID", prefix48: "Prefijo /48", sampleSubnet: "Subred /64 de ejemplo" },
  it: { title: "Generatore di ULA IPv6", short: "Genera un prefisso di indirizzo locale univoco RFC 4193 (fd00::/8) casuale per reti IPv6 private.", description: "Generatore di ULA IPv6 gratuito. Crea un indirizzo locale univoco RFC 4193 casuale con un prefisso /48 e una subnet /64 di esempio per la tua rete IPv6 privata. Usa un Global ID casuale sicuro e funziona interamente nel tuo browser.", keywords: ["generatore ula ipv6", "indirizzo locale univoco", "prefisso rfc 4193", "generatore prefisso fd00", "indirizzo privato ipv6"], generate: "Genera", globalId: "Global ID", prefix48: "Prefisso /48", sampleSubnet: "Subnet /64 di esempio" },
  ar: { title: "مولّد ULA لـ IPv6", short: "ولّد بادئة عنوان محلي فريد RFC 4193 (fd00::/8) عشوائية لشبكات IPv6 الخاصة.", description: "مولّد ULA لـ IPv6 مجاني. أنشئ عنوانًا محليًا فريدًا RFC 4193 عشوائيًا ببادئة /48 وشبكة فرعية /64 كمثال لشبكة IPv6 الخاصة بك. يستخدم Global ID عشوائيًا آمنًا ويعمل بالكامل في متصفحك.", keywords: ["مولد ula ipv6", "عنوان محلي فريد", "بادئة rfc 4193", "مولد بادئة fd00", "عنوان خاص ipv6"], generate: "توليد", globalId: "Global ID", prefix48: "بادئة /48", sampleSubnet: "شبكة فرعية /64 كمثال" },
  ru: { title: "Генератор IPv6 ULA", short: "Сгенерируйте случайный префикс уникального локального адреса RFC 4193 (fd00::/8) для частных IPv6-сетей.", description: "Бесплатный генератор IPv6 ULA. Создайте случайный уникальный локальный адрес RFC 4193 с префиксом /48 и примером подсети /64 для вашей частной IPv6-сети. Использует безопасный случайный Global ID и работает полностью в браузере.", keywords: ["генератор ula ipv6", "уникальный локальный адрес", "префикс rfc 4193", "генератор префикса fd00", "частный адрес ipv6"], generate: "Сгенерировать", globalId: "Global ID", prefix48: "Префикс /48", sampleSubnet: "Пример подсети /64" },
  zh: { title: "IPv6 ULA 生成器", short: "为私有 IPv6 网络生成随机的 RFC 4193 唯一本地地址前缀（fd00::/8）。", description: "免费的 IPv6 ULA 生成器。为您的私有 IPv6 网络创建带 /48 前缀和示例 /64 子网的随机 RFC 4193 唯一本地地址。使用安全的随机 Global ID，完全在浏览器中运行。", keywords: ["ipv6 ula 生成器", "唯一本地地址", "rfc 4193 前缀", "fd00 前缀生成器", "ipv6 私有地址"], generate: "生成", globalId: "Global ID", prefix48: "/48 前缀", sampleSubnet: "示例 /64 子网" },
  ja: { title: "IPv6 ULA ジェネレーター", short: "プライベート IPv6 ネットワーク向けにランダムな RFC 4193 ユニークローカルアドレスのプレフィックス（fd00::/8）を生成します。", description: "無料の IPv6 ULA ジェネレーター。プライベート IPv6 ネットワーク用に、/48 プレフィックスとサンプルの /64 サブネットを備えたランダムな RFC 4193 ユニークローカルアドレスを作成します。安全なランダム Global ID を使用し、すべてブラウザ内で動作します。", keywords: ["ipv6 ula ジェネレーター", "ユニークローカルアドレス", "rfc 4193 プレフィックス", "fd00 プレフィックス生成", "ipv6 プライベートアドレス"], generate: "生成", globalId: "Global ID", prefix48: "/48 プレフィックス", sampleSubnet: "サンプル /64 サブネット" },
  ko: { title: "IPv6 ULA 생성기", short: "사설 IPv6 네트워크를 위한 무작위 RFC 4193 고유 로컬 주소 접두사(fd00::/8)를 생성합니다.", description: "무료 IPv6 ULA 생성기. 사설 IPv6 네트워크용으로 /48 접두사와 예시 /64 서브넷이 포함된 무작위 RFC 4193 고유 로컬 주소를 만듭니다. 안전한 무작위 Global ID를 사용하며 브라우저에서 완전히 실행됩니다.", keywords: ["ipv6 ula 생성기", "고유 로컬 주소", "rfc 4193 접두사", "fd00 접두사 생성기", "ipv6 사설 주소"], generate: "생성", globalId: "Global ID", prefix48: "/48 접두사", sampleSubnet: "예시 /64 서브넷" },
  hi: { title: "IPv6 ULA जनरेटर", short: "निजी IPv6 नेटवर्क के लिए एक यादृच्छिक RFC 4193 यूनिक लोकल एड्रेस प्रीफ़िक्स (fd00::/8) उत्पन्न करें।", description: "मुफ्त IPv6 ULA जनरेटर। अपने निजी IPv6 नेटवर्क के लिए /48 प्रीफ़िक्स और एक नमूना /64 सबनेट के साथ एक यादृच्छिक RFC 4193 यूनिक लोकल एड्रेस बनाएं। एक सुरक्षित यादृच्छिक Global ID का उपयोग करता है और पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["ipv6 ula जनरेटर", "यूनिक लोकल एड्रेस", "rfc 4193 प्रीफ़िक्स", "fd00 प्रीफ़िक्स जनरेटर", "ipv6 निजी पता"], generate: "उत्पन्न करें", globalId: "Global ID", prefix48: "/48 प्रीफ़िक्स", sampleSubnet: "नमूना /64 सबनेट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
