import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Unix Timestamp Converter", short: "Convert Unix epoch timestamps to dates and dates back to timestamps.", description: "Free Unix timestamp converter. Turn an epoch timestamp (seconds or milliseconds) into a readable UTC date, or convert a date back into a Unix timestamp. Includes a 'now' button.", keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time", "unix time"], toDate: "Timestamp → Date", toUnix: "Date → Timestamp", seconds: "Seconds", milliseconds: "Milliseconds", now: "Now", invalid: "Invalid input.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "e.g. 1700000000", datePlaceholder: "e.g. 2023-11-14T22:13:20Z" },
  nl: { title: "Unix Tijdstempel Converteerer", short: "Converteer Unix epoch tijdstempels to dates and dates back to tijdstempels.", description: "Gratis Unix tijdstempel converteerer. Turn an epoch tijdstempel (seconden or milliseconden) into a readable UTC date, or converteer a date back into a Unix tijdstempel. Includes a 'now' button.", keywords: ["unix tijdstempel converteerer", "epoch converteerer", "tijdstempel to date", "date to tijdstempel", "epoch time", "unix time"], toDate: "Tijdstempel → Date", toUnix: "Date → Tijdstempel", seconds: "Seconds", milliseconds: "Milliseconden", now: "Now", invalid: "Invalid input.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "e.g. 1700000000", datePlaceholder: "e.g. 2023-11-14T22:13:20Z" },

  pl: { title: "Unix Znacznik czasu Konwerter", short: "Konwertuj Unix epoch znacznik czasus to dates and dates back to znacznik czasus.", description: "Darmowy Unix znacznik czasu konwerter. Turn an epoch znacznik czasu (sekund or millisekund) into a readable UTC date, or konwertuj a date back into a Unix znacznik czasu. Includes a 'now' button.", keywords: ["unix znacznik czasu konwerter", "epoch konwerter", "znacznik czasu to date", "date to znacznik czasu", "epoch time", "unix time"], toDate: "Znacznik czasu → Date", toUnix: "Date → Znacznik czasu", seconds: "Seconds", milliseconds: "Millisekund", now: "Now", invalid: "Invalid input.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "e.g. 1700000000", datePlaceholder: "e.g. 2023-11-14T22:13:20Z" },
  pt: { title: "Conversor de Unix Timestamp", short: "Converter Unix epoch timestamps para dates e dates back para timestamps.", description: "Gratuito - Unix timestamp converter. Turn an epoch timestamp (seconds ou milliseconds) into a readable UTC date, ou converter a date back into a Unix timestamp. Includes a 'now' button.", keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time", "unix time"], toDate: "Timestamp → Date", toUnix: "Date → Timestamp", seconds: "Seconds", milliseconds: "Milliseconds", now: "Now", invalid: "Invalid input.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "e.g. 1700000000", datePlaceholder: "e.g. 2023-11-14T22:13:20Z" },
  id: { title: "Konverter Unix Timestamp", short: "Konversi Unix epoch timestamps to dates dan dates back to timestamps.", description: "Gratis - Unix timestamp converter. Turn an epoch timestamp (seconds atau milliseconds) into a readable UTC date, atau konversi a date back into a Unix timestamp. Includes a 'now' button.", keywords: ["unix timestamp converter", "epoch converter", "timestamp to date", "date to timestamp", "epoch time", "unix time"], toDate: "Timestamp → Date", toUnix: "Date → Timestamp", seconds: "Seconds", milliseconds: "Milliseconds", now: "Now", invalid: "Invalid input.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "e.g. 1700000000", datePlaceholder: "e.g. 2023-11-14T22:13:20Z" },

  tr: { title: "Unix Zaman Damgası Dönüştürücü", short: "Unix epoch zaman damgalarını tarihe ve tarihleri zaman damgasına çevirin.", description: "Ücretsiz Unix zaman damgası dönüştürücü. Bir epoch zaman damgasını (saniye veya milisaniye) okunabilir UTC tarihine çevirin veya bir tarihi Unix zaman damgasına dönüştürün. 'Şimdi' düğmesi içerir.", keywords: ["unix zaman damgası", "epoch dönüştürücü", "zaman damgasından tarihe", "tarihten zaman damgasına", "epoch zaman"], toDate: "Zaman damgası → Tarih", toUnix: "Tarih → Zaman damgası", seconds: "Saniye", milliseconds: "Milisaniye", now: "Şimdi", invalid: "Geçersiz girdi.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "örn. 1700000000", datePlaceholder: "örn. 2023-11-14T22:13:20Z" },
  de: { title: "Unix-Zeitstempel-Konverter", short: "Unix-Epoch-Zeitstempel in Daten und Daten zurück in Zeitstempel umwandeln.", description: "Kostenloser Unix-Zeitstempel-Konverter. Wandeln Sie einen Epoch-Zeitstempel (Sekunden oder Millisekunden) in ein lesbares UTC-Datum um oder ein Datum zurück in einen Unix-Zeitstempel. Mit 'Jetzt'-Schaltfläche.", keywords: ["unix zeitstempel", "epoch konverter", "zeitstempel in datum", "datum in zeitstempel", "epoch zeit"], toDate: "Zeitstempel → Datum", toUnix: "Datum → Zeitstempel", seconds: "Sekunden", milliseconds: "Millisekunden", now: "Jetzt", invalid: "Ungültige Eingabe.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "z. B. 1700000000", datePlaceholder: "z. B. 2023-11-14T22:13:20Z" },
  fr: { title: "Convertisseur d'Horodatage Unix", short: "Convertissez les horodatages Unix en dates et inversement.", description: "Convertisseur d'horodatage Unix gratuit. Transformez un horodatage epoch (secondes ou millisecondes) en date UTC lisible, ou convertissez une date en horodatage Unix. Bouton « maintenant » inclus.", keywords: ["horodatage unix", "convertisseur epoch", "horodatage en date", "date en horodatage", "temps epoch"], toDate: "Horodatage → Date", toUnix: "Date → Horodatage", seconds: "Secondes", milliseconds: "Millisecondes", now: "Maintenant", invalid: "Entrée invalide.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "ex. 1700000000", datePlaceholder: "ex. 2023-11-14T22:13:20Z" },
  es: { title: "Conversor de Marca de Tiempo Unix", short: "Convierte marcas de tiempo Unix a fechas y fechas a marcas de tiempo.", description: "Conversor de marca de tiempo Unix gratuito. Convierte una marca de tiempo epoch (segundos o milisegundos) en una fecha UTC legible, o una fecha en una marca de tiempo Unix. Incluye botón 'ahora'.", keywords: ["marca de tiempo unix", "conversor epoch", "timestamp a fecha", "fecha a timestamp", "tiempo epoch"], toDate: "Marca de tiempo → Fecha", toUnix: "Fecha → Marca de tiempo", seconds: "Segundos", milliseconds: "Milisegundos", now: "Ahora", invalid: "Entrada no válida.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "p. ej. 1700000000", datePlaceholder: "p. ej. 2023-11-14T22:13:20Z" },
  it: { title: "Convertitore di Timestamp Unix", short: "Converti i timestamp Unix in date e le date in timestamp.", description: "Convertitore di timestamp Unix gratuito. Trasforma un timestamp epoch (secondi o millisecondi) in una data UTC leggibile, o una data in un timestamp Unix. Include il pulsante 'adesso'.", keywords: ["timestamp unix", "convertitore epoch", "timestamp in data", "data in timestamp", "tempo epoch"], toDate: "Timestamp → Data", toUnix: "Data → Timestamp", seconds: "Secondi", milliseconds: "Millisecondi", now: "Adesso", invalid: "Input non valido.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "es. 1700000000", datePlaceholder: "es. 2023-11-14T22:13:20Z" },
  ar: { title: "محوّل طابع Unix الزمني", short: "حوّل طوابع Unix الزمنية إلى تواريخ والعكس.", description: "محوّل طابع Unix الزمني مجاني. حوّل طابعًا زمنيًا (بالثواني أو المللي ثانية) إلى تاريخ UTC مقروء، أو حوّل تاريخًا إلى طابع Unix زمني. يتضمن زر 'الآن'.", keywords: ["طابع unix الزمني", "محول epoch", "طابع زمني إلى تاريخ", "تاريخ إلى طابع زمني", "وقت epoch"], toDate: "الطابع الزمني → التاريخ", toUnix: "التاريخ → الطابع الزمني", seconds: "ثوانٍ", milliseconds: "مللي ثانية", now: "الآن", invalid: "إدخال غير صالح.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "مثل 1700000000", datePlaceholder: "مثل 2023-11-14T22:13:20Z" },
  ru: { title: "Конвертер Unix-времени", short: "Преобразуйте Unix-таймстампы в даты и обратно.", description: "Бесплатный конвертер Unix-времени. Преобразуйте таймстамп epoch (секунды или миллисекунды) в читаемую дату UTC или дату обратно в Unix-таймстамп. Есть кнопка «сейчас».", keywords: ["unix таймстамп", "конвертер epoch", "таймстамп в дату", "дата в таймстамп", "epoch время"], toDate: "Таймстамп → Дата", toUnix: "Дата → Таймстамп", seconds: "Секунды", milliseconds: "Миллисекунды", now: "Сейчас", invalid: "Недопустимый ввод.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "напр. 1700000000", datePlaceholder: "напр. 2023-11-14T22:13:20Z" },
  zh: { title: "Unix 时间戳转换器", short: "将 Unix 纪元时间戳转换为日期，或将日期转换回时间戳。", description: "免费的 Unix 时间戳转换器。将纪元时间戳（秒或毫秒）转换为可读的 UTC 日期，或将日期转换回 Unix 时间戳。含'现在'按钮。", keywords: ["unix时间戳", "纪元转换器", "时间戳转日期", "日期转时间戳", "纪元时间"], toDate: "时间戳 → 日期", toUnix: "日期 → 时间戳", seconds: "秒", milliseconds: "毫秒", now: "现在", invalid: "输入无效。", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "例如 1700000000", datePlaceholder: "例如 2023-11-14T22:13:20Z" },
  ja: { title: "Unix タイムスタンプ変換", short: "Unix エポックタイムスタンプを日付に、日付をタイムスタンプに変換します。", description: "無料の Unix タイムスタンプ変換ツール。エポックタイムスタンプ（秒またはミリ秒）を読みやすい UTC 日付に、または日付を Unix タイムスタンプに変換します。「現在」ボタン付き。", keywords: ["unix タイムスタンプ", "エポック変換", "タイムスタンプから日付", "日付からタイムスタンプ", "エポック時間"], toDate: "タイムスタンプ → 日付", toUnix: "日付 → タイムスタンプ", seconds: "秒", milliseconds: "ミリ秒", now: "現在", invalid: "無効な入力です。", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "例: 1700000000", datePlaceholder: "例: 2023-11-14T22:13:20Z" },
  ko: { title: "Unix 타임스탬프 변환기", short: "Unix 에포크 타임스탬프를 날짜로, 날짜를 타임스탬프로 변환합니다.", description: "무료 Unix 타임스탬프 변환기. 에포크 타임스탬프(초 또는 밀리초)를 읽기 쉬운 UTC 날짜로, 또는 날짜를 Unix 타임스탬프로 변환합니다. '지금' 버튼 포함.", keywords: ["unix 타임스탬프", "에포크 변환기", "타임스탬프를 날짜로", "날짜를 타임스탬프로", "에포크 시간"], toDate: "타임스탬프 → 날짜", toUnix: "날짜 → 타임스탬프", seconds: "초", milliseconds: "밀리초", now: "지금", invalid: "잘못된 입력입니다.", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "예: 1700000000", datePlaceholder: "예: 2023-11-14T22:13:20Z" },
  hi: { title: "Unix टाइमस्टैम्प कन्वर्टर", short: "Unix एपॉक टाइमस्टैम्प को तिथि में और तिथि को टाइमस्टैम्प में बदलें।", description: "मुफ्त Unix टाइमस्टैम्प कन्वर्टर। एपॉक टाइमस्टैम्प (सेकंड या मिलीसेकंड) को पठनीय UTC तिथि में, या तिथि को Unix टाइमस्टैम्प में बदलें। 'अभी' बटन शामिल।", keywords: ["unix टाइमस्टैम्प", "एपॉक कन्वर्टर", "टाइमस्टैम्प से तिथि", "तिथि से टाइमस्टैम्प", "एपॉक समय"], toDate: "टाइमस्टैम्प → तिथि", toUnix: "तिथि → टाइमस्टैम्प", seconds: "सेकंड", milliseconds: "मिलीसेकंड", now: "अभी", invalid: "अमान्य इनपुट।", iso: "ISO 8601 (UTC)", utc: "UTC", tsPlaceholder: "जैसे 1700000000", datePlaceholder: "जैसे 2023-11-14T22:13:20Z" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
