import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image Color Picker", short: "Extract a dominant-colour palette from any image.", description: "Free image colour picker. Drop a photo, logo or screenshot to extract its dominant colours as a palette of hex codes — useful for building brand and theme palettes. Runs entirely in your browser.", keywords: ["image color picker", "extract palette from image", "dominant colors", "image to palette", "color from photo"], drop: "Drop an image here or click to choose", count: "Colors", palette: "Palette" },
  nl: { title: "Afbeelding Kleur Kiezer", short: "Extract a dominant-colour palette from any afbeelding.", description: "Gratis afbeelding colour picker. Drop a photo, logo or screenshot to extract its dominant colours as a palette of hex codes — useful for building brand and theme palettes. Runs entirely in uw browser.", keywords: ["afbeelding kleur picker", "extract palette from afbeelding", "dominant kleurs", "afbeelding to palette", "kleur from photo"], drop: "Drop an afbeelding here or click to choose", count: "Kleurs", palette: "Palette" },

  pl: { title: "Obraz Kolor Wybór", short: "Extract a dominant-colour palette from any obraz.", description: "Darmowy obraz colour picker. Drop a photo, logo or screenshot to extract its dominant colours as a palette of hex kods — useful for building brand and theme palettes. Runs entirely w Twojej przeglądarce.", keywords: ["obraz kolor picker", "extract palette from obraz", "dominant kolors", "obraz to palette", "kolor from photo"], drop: "Drop an obraz here or click to choose", count: "Kolors", palette: "Palette" },
  pt: { title: "Seletor de Image Color", short: "Extract a dominant-colour palette a partir de any image.", description: "Gratuito - image colour picker. Drop a photo, logo ou screenshot para extract its dominant colours as a palette de hex codes â useful para building brand e theme palettes. Runs entirely no seu navegador.", keywords: ["image color picker", "extract palette from image", "dominant colors", "image to palette", "color from photo"], drop: "Drop an image here or click to choose", count: "Colors", palette: "Palette" },
  id: { title: "Pemilih Image Color", short: "Extract a dominant-colour palette from any image.", description: "Gratis - image colour picker. Drop a photo, logo atau screenshot to extract its dominant colours as a palette dari hex codes â useful for building brand dan theme palettes. Runs entirely di browser Anda.", keywords: ["image color picker", "extract palette from image", "dominant colors", "image to palette", "color from photo"], drop: "Drop an image here or click to choose", count: "Colors", palette: "Palette" },

  tr: { title: "Görselden Renk Seçici", short: "Herhangi bir görselden baskın renk paleti çıkarın.", description: "Ücretsiz görsel renk seçici. Bir fotoğraf, logo veya ekran görüntüsü bırakarak baskın renklerini hex kod paleti olarak çıkarın — marka ve tema paletleri oluşturmak için kullanışlı. Tamamen tarayıcınızda çalışır.", keywords: ["görsel renk seçici", "görselden palet çıkar", "baskın renkler", "görselden palet", "fotoğraftan renk"], drop: "Bir görsel bırakın veya seçmek için tıklayın", count: "Renkler", palette: "Palet" },
  de: { title: "Bild-Farbwähler", short: "Extrahieren Sie eine dominante Farbpalette aus jedem Bild.", description: "Kostenloser Bild-Farbwähler. Legen Sie ein Foto, Logo oder Screenshot ab, um seine dominanten Farben als Hex-Code-Palette zu extrahieren — nützlich für Marken- und Theme-Paletten. Läuft vollständig im Browser.", keywords: ["bild farbwähler", "palette aus bild extrahieren", "dominante farben", "bild zu palette", "farbe aus foto"], drop: "Bild hier ablegen oder klicken zum Auswählen", count: "Farben", palette: "Palette" },
  fr: { title: "Sélecteur de Couleur d'Image", short: "Extrayez une palette de couleurs dominantes de toute image.", description: "Sélecteur de couleur d'image gratuit. Déposez une photo, un logo ou une capture d'écran pour extraire ses couleurs dominantes en palette de codes hex — utile pour créer des palettes de marque et de thème. Fonctionne entièrement dans votre navigateur.", keywords: ["sélecteur couleur image", "extraire palette depuis image", "couleurs dominantes", "image vers palette", "couleur depuis photo"], drop: "Déposez une image ici ou cliquez pour choisir", count: "Couleurs", palette: "Palette" },
  es: { title: "Selector de Color de Imagen", short: "Extrae una paleta de colores dominantes de cualquier imagen.", description: "Selector de color de imagen gratuito. Arrastra una foto, logo o captura para extraer sus colores dominantes como paleta de códigos hex — útil para crear paletas de marca y tema. Funciona completamente en tu navegador.", keywords: ["selector color imagen", "extraer paleta de imagen", "colores dominantes", "imagen a paleta", "color desde foto"], drop: "Arrastra una imagen aquí o haz clic para elegir", count: "Colores", palette: "Paleta" },
  it: { title: "Selettore di Colore Immagine", short: "Estrai una palette di colori dominanti da qualsiasi immagine.", description: "Selettore di colore immagine gratuito. Trascina una foto, logo o screenshot per estrarre i colori dominanti come palette di codici hex — utile per palette di brand e temi. Funziona interamente nel browser.", keywords: ["selettore colore immagine", "estrai palette da immagine", "colori dominanti", "immagine a palette", "colore da foto"], drop: "Trascina un'immagine qui o clicca per scegliere", count: "Colori", palette: "Palette" },
  ar: { title: "منتقي ألوان الصور", short: "استخرج لوحة الألوان السائدة من أي صورة.", description: "منتقي ألوان صور مجاني. أفلِت صورة أو شعارًا أو لقطة شاشة لاستخراج ألوانها السائدة كلوحة أكواد hex — مفيد لبناء لوحات العلامة التجارية والسمة. يعمل بالكامل في متصفحك.", keywords: ["منتقي ألوان الصور", "استخراج لوحة من صورة", "ألوان سائدة", "صورة إلى لوحة", "لون من الصورة"], drop: "أفلِت صورة هنا أو انقر للاختيار", count: "الألوان", palette: "اللوحة" },
  ru: { title: "Подбор цвета из изображения", short: "Извлеките палитру доминирующих цветов из любого изображения.", description: "Бесплатный подбор цвета из изображения. Перетащите фото, логотип или скриншот, чтобы извлечь его доминирующие цвета как палитру hex-кодов — полезно для создания палитр бренда и темы. Работает полностью в браузере.", keywords: ["подбор цвета из изображения", "извлечь палитру из изображения", "доминирующие цвета", "изображение в палитру", "цвет из фото"], drop: "Перетащите изображение сюда или нажмите для выбора", count: "Цвета", palette: "Палитра" },
  zh: { title: "图片取色器", short: "从任意图片提取主色调色板。", description: "免费的图片取色器。拖入照片、logo 或截图，将其主色提取为十六进制代码的调色板——适用于构建品牌和主题调色板。完全在浏览器中运行。", keywords: ["图片取色器", "从图片提取调色板", "主色", "图片转调色板", "从照片取色"], drop: "将图片拖到此处或点击选择", count: "颜色数量", palette: "调色板" },
  ja: { title: "画像カラーピッカー", short: "任意の画像から主要カラーパレットを抽出。", description: "無料の画像カラーピッカー。写真、ロゴ、スクリーンショットをドロップして、主要な色を16進コードのパレットとして抽出——ブランドやテーマパレットの作成に便利。すべてブラウザ内で動作します。", keywords: ["画像 カラーピッカー", "画像から パレット 抽出", "主要色", "画像から パレット", "写真から 色"], drop: "画像をここにドロップまたはクリックして選択", count: "色数", palette: "パレット" },
  ko: { title: "이미지 색상 선택기", short: "모든 이미지에서 주요 색상 팔레트를 추출합니다.", description: "무료 이미지 색상 선택기. 사진, 로고, 스크린샷을 드롭해 주요 색상을 hex 코드 팔레트로 추출하세요 — 브랜드와 테마 팔레트 구축에 유용합니다. 모두 브라우저에서 실행됩니다.", keywords: ["이미지 색상 선택기", "이미지에서 팔레트 추출", "주요 색상", "이미지를 팔레트로", "사진에서 색상"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", count: "색상", palette: "팔레트" },
  hi: { title: "इमेज कलर पिकर", short: "किसी भी इमेज से प्रमुख रंगों का पैलेट निकालें।", description: "मुफ्त इमेज कलर पिकर। एक फोटो, लोगो या स्क्रीनशॉट छोड़ें ताकि उसके प्रमुख रंगों को hex कोड पैलेट के रूप में निकाला जा सके — ब्रांड और थीम पैलेट बनाने के लिए उपयोगी। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["इमेज कलर पिकर", "इमेज से पैलेट निकालें", "प्रमुख रंग", "इमेज से पैलेट", "फोटो से रंग"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", count: "रंग", palette: "पैलेट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
