import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Punycode Converter", short: "Convert internationalized domains between Unicode and Punycode (xn--).", description: "Free Punycode converter. Convert internationalized domain names between their Unicode form and ASCII Punycode (xn--) form using the RFC 3492 algorithm. Runs entirely in your browser.", keywords: ["punycode converter", "idn to ascii", "xn-- decoder", "unicode domain converter", "internationalized domain name"], domain: "Domain", placeholder: "münchen.de or xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Could not convert this domain." },
  pt: { title: "Punycode Converter", short: "Convert internationalized domains entre Unicode e Punycode (xn--).", description: "Gratuito - punycode converter. Convert internationalized domain names entre their Unicode form e ASCII Punycode (xn--) form usando the RFC 3492 algorithm. Runs entirely no seu navegador.", keywords: ["punycode converter", "idn to ascii", "xn-- decoder", "unicode domain converter", "internationalized domain name"], domain: "Domínio", placeholder: "münchen.de ou xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Não foi possível converter este domínio." },
  id: { title: "Punycode Converter", short: "Convert internationalized domains antara Unicode dan Punycode (xn--).", description: "Gratis - punycode converter. Convert internationalized domain names antara their Unicode form dan ASCII Punycode (xn--) form menggunakan the RFC 3492 algorithm. Runs entirely di browser Anda.", keywords: ["punycode converter", "idn to ascii", "xn-- decoder", "unicode domain converter", "internationalized domain name"], domain: "Domain", placeholder: "münchen.de atau xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Tidak dapat mengonversi domain ini." },

  tr: { title: "Punycode Dönüştürücü", short: "Uluslararası alan adlarını Unicode ile Punycode (xn--) arasında dönüştürün.", description: "Ücretsiz Punycode dönüştürücü. Uluslararası alan adlarını RFC 3492 algoritmasını kullanarak Unicode biçimi ile ASCII Punycode (xn--) biçimi arasında dönüştürün. Tamamen tarayıcınızda çalışır.", keywords: ["punycode dönüştürücü", "idn ascii", "xn-- çözücü", "unicode alan adı dönüştürücü", "uluslararası alan adı"], domain: "Alan adı", placeholder: "münchen.de veya xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Bu alan adı dönüştürülemedi." },
  de: { title: "Punycode-Konverter", short: "Wandeln Sie internationalisierte Domains zwischen Unicode und Punycode (xn--) um.", description: "Kostenloser Punycode-Konverter. Wandeln Sie internationalisierte Domainnamen mit dem RFC-3492-Algorithmus zwischen ihrer Unicode-Form und der ASCII-Punycode-Form (xn--) um. Läuft vollständig in Ihrem Browser.", keywords: ["punycode konverter", "idn zu ascii", "xn-- decoder", "unicode domain konverter", "internationalisierter domainname"], domain: "Domain", placeholder: "münchen.de oder xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Diese Domain konnte nicht umgewandelt werden." },
  fr: { title: "Convertisseur Punycode", short: "Convertissez les domaines internationalisés entre Unicode et Punycode (xn--).", description: "Convertisseur Punycode gratuit. Convertissez les noms de domaine internationalisés entre leur forme Unicode et la forme ASCII Punycode (xn--) à l'aide de l'algorithme RFC 3492. Fonctionne entièrement dans votre navigateur.", keywords: ["convertisseur punycode", "idn vers ascii", "décodeur xn--", "convertisseur domaine unicode", "nom de domaine internationalisé"], domain: "Domaine", placeholder: "münchen.de ou xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Impossible de convertir ce domaine." },
  es: { title: "Conversor Punycode", short: "Convierte dominios internacionalizados entre Unicode y Punycode (xn--).", description: "Conversor Punycode gratuito. Convierte nombres de dominio internacionalizados entre su forma Unicode y la forma ASCII Punycode (xn--) usando el algoritmo RFC 3492. Funciona enteramente en tu navegador.", keywords: ["conversor punycode", "idn a ascii", "decodificador xn--", "conversor de dominio unicode", "nombre de dominio internacionalizado"], domain: "Dominio", placeholder: "münchen.de o xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "No se pudo convertir este dominio." },
  it: { title: "Convertitore Punycode", short: "Converti i domini internazionalizzati tra Unicode e Punycode (xn--).", description: "Convertitore Punycode gratuito. Converti i nomi di dominio internazionalizzati tra la forma Unicode e la forma ASCII Punycode (xn--) usando l'algoritmo RFC 3492. Funziona interamente nel tuo browser.", keywords: ["convertitore punycode", "idn in ascii", "decoder xn--", "convertitore dominio unicode", "nome di dominio internazionalizzato"], domain: "Dominio", placeholder: "münchen.de o xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Impossibile convertire questo dominio." },
  ar: { title: "محوّل Punycode", short: "حوّل النطاقات الدولية بين Unicode وPunycode (xn--).", description: "محوّل Punycode مجاني. حوّل أسماء النطاقات الدولية بين شكلها Unicode وشكل ASCII Punycode (xn--) باستخدام خوارزمية RFC 3492. يعمل بالكامل في متصفحك.", keywords: ["محول punycode", "idn إلى ascii", "فك ترميز xn--", "محول نطاق unicode", "اسم نطاق دولي"], domain: "النطاق", placeholder: "münchen.de أو xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "تعذّر تحويل هذا النطاق." },
  ru: { title: "Конвертер Punycode", short: "Преобразуйте интернационализированные домены между Unicode и Punycode (xn--).", description: "Бесплатный конвертер Punycode. Преобразуйте интернационализированные доменные имена между формой Unicode и ASCII-формой Punycode (xn--) по алгоритму RFC 3492. Работает полностью в браузере.", keywords: ["конвертер punycode", "idn в ascii", "декодер xn--", "конвертер unicode домена", "интернационализированное доменное имя"], domain: "Домен", placeholder: "münchen.de или xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "Не удалось преобразовать этот домен." },
  zh: { title: "Punycode 转换器", short: "在 Unicode 和 Punycode (xn--) 之间转换国际化域名。", description: "免费的 Punycode 转换器。使用 RFC 3492 算法在 Unicode 形式和 ASCII Punycode (xn--) 形式之间转换国际化域名。完全在浏览器中运行。", keywords: ["punycode 转换器", "idn 转 ascii", "xn-- 解码器", "unicode 域名转换器", "国际化域名"], domain: "域名", placeholder: "münchen.de 或 xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "无法转换此域名。" },
  ja: { title: "Punycode 変換ツール", short: "国際化ドメインを Unicode と Punycode (xn--) の間で変換します。", description: "無料の Punycode 変換ツール。RFC 3492 アルゴリズムを使い、国際化ドメイン名を Unicode 形式と ASCII Punycode (xn--) 形式の間で変換します。すべてブラウザ内で動作します。", keywords: ["punycode 変換", "idn から ascii", "xn-- デコーダー", "unicode ドメイン変換", "国際化ドメイン名"], domain: "ドメイン", placeholder: "münchen.de または xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "このドメインを変換できませんでした。" },
  ko: { title: "Punycode 변환기", short: "국제화 도메인을 Unicode와 Punycode (xn--) 사이에서 변환합니다.", description: "무료 Punycode 변환기. RFC 3492 알고리즘을 사용하여 국제화 도메인 이름을 Unicode 형식과 ASCII Punycode (xn--) 형식 사이에서 변환합니다. 모두 브라우저에서 실행됩니다.", keywords: ["punycode 변환기", "idn을 ascii로", "xn-- 디코더", "unicode 도메인 변환기", "국제화 도메인 이름"], domain: "도메인", placeholder: "münchen.de 또는 xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "이 도메인을 변환할 수 없습니다." },
  hi: { title: "Punycode कन्वर्टर", short: "अंतरराष्ट्रीयकृत डोमेन को Unicode और Punycode (xn--) के बीच बदलें।", description: "मुफ्त Punycode कन्वर्टर। RFC 3492 एल्गोरिदम का उपयोग करके अंतरराष्ट्रीयकृत डोमेन नामों को उनके Unicode रूप और ASCII Punycode (xn--) रूप के बीच बदलें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["punycode कन्वर्टर", "idn से ascii", "xn-- डिकोडर", "unicode डोमेन कन्वर्टर", "अंतरराष्ट्रीयकृत डोमेन नाम"], domain: "डोमेन", placeholder: "münchen.de या xn--mnchen-3ya.de", unicode: "Unicode", ascii: "ASCII (xn--)", invalid: "इस डोमेन को बदला नहीं जा सका।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
