import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "YAML ↔ JSON Converter", short: "Convert between YAML and JSON, both directions.", description: "Free YAML to JSON and JSON to YAML converter. Paste a YAML document or a JSON document and switch the direction with one click — runs entirely in your browser.", keywords: ["yaml to json", "json to yaml", "yaml json converter", "yml to json", "convert yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Input", output: "Output" },
  pt: { title: "Conversor de YAML â JSON", short: "Converter entre YAML e JSON, both directions.", description: "Gratuito - YAML para JSON e JSON para YAML converter. Paste a YAML document ou a JSON document e switch the direction com one click â runs entirely no seu navegador.", keywords: ["yaml to json", "json to yaml", "yaml json converter", "yml to json", "convert yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Input", output: "Output" },
  id: { title: "Konverter YAML â JSON", short: "Konversi antara YAML dan JSON, both directions.", description: "Gratis - YAML to JSON dan JSON to YAML converter. Paste a YAML document atau a JSON document dan switch the direction with one click â runs entirely di browser Anda.", keywords: ["yaml to json", "json to yaml", "yaml json converter", "yml to json", "convert yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Input", output: "Output" },

  tr: { title: "YAML ↔ JSON Dönüştürücü", short: "YAML ile JSON arasında iki yönlü dönüşüm yapın.", description: "Ücretsiz YAML'dan JSON'a ve JSON'dan YAML'a dönüştürücü. Bir YAML veya JSON belgesini yapıştırın ve yönü tek tıkla değiştirin — tamamen tarayıcınızda çalışır.", keywords: ["yaml json", "json yaml", "yaml json dönüştürücü", "yml json", "yaml json dönüştür"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Giriş", output: "Çıkış" },
  de: { title: "YAML ↔ JSON Konverter", short: "Konvertieren Sie zwischen YAML und JSON in beide Richtungen.", description: "Kostenloser YAML-zu-JSON- und JSON-zu-YAML-Konverter. Fügen Sie ein YAML- oder JSON-Dokument ein und wechseln Sie die Richtung mit einem Klick — läuft vollständig im Browser.", keywords: ["yaml zu json", "json zu yaml", "yaml json konverter", "yml zu json", "yaml json konvertieren"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Eingabe", output: "Ausgabe" },
  fr: { title: "Convertisseur YAML ↔ JSON", short: "Convertissez entre YAML et JSON dans les deux sens.", description: "Convertisseur YAML vers JSON et JSON vers YAML gratuit. Collez un document YAML ou JSON et changez le sens en un clic — fonctionne entièrement dans votre navigateur.", keywords: ["yaml vers json", "json vers yaml", "convertisseur yaml json", "yml vers json", "convertir yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Entrée", output: "Sortie" },
  es: { title: "Convertidor YAML ↔ JSON", short: "Convierte entre YAML y JSON en ambos sentidos.", description: "Convertidor YAML a JSON y JSON a YAML gratuito. Pega un documento YAML o JSON y cambia la dirección con un clic — funciona completamente en tu navegador.", keywords: ["yaml a json", "json a yaml", "convertidor yaml json", "yml a json", "convertir yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Entrada", output: "Salida" },
  it: { title: "Convertitore YAML ↔ JSON", short: "Converti tra YAML e JSON in entrambe le direzioni.", description: "Convertitore da YAML a JSON e da JSON a YAML gratuito. Incolla un documento YAML o JSON e cambia direzione con un clic — funziona interamente nel browser.", keywords: ["yaml a json", "json a yaml", "convertitore yaml json", "yml a json", "convertire yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Input", output: "Output" },
  ar: { title: "محوّل YAML ↔ JSON", short: "حوّل بين YAML و JSON في الاتجاهين.", description: "محوّل YAML إلى JSON و JSON إلى YAML مجاني. الصق مستند YAML أو JSON وغيّر الاتجاه بنقرة واحدة — يعمل بالكامل في متصفحك.", keywords: ["yaml إلى json", "json إلى yaml", "محول yaml json", "yml إلى json", "تحويل yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "الإدخال", output: "الإخراج" },
  ru: { title: "Конвертер YAML ↔ JSON", short: "Конвертируйте между YAML и JSON в обоих направлениях.", description: "Бесплатный конвертер YAML в JSON и JSON в YAML. Вставьте YAML или JSON документ и переключайте направление одним кликом — работает полностью в браузере.", keywords: ["yaml в json", "json в yaml", "конвертер yaml json", "yml в json", "конвертировать yaml json"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "Ввод", output: "Вывод" },
  zh: { title: "YAML ↔ JSON 转换器", short: "在 YAML 和 JSON 之间双向转换。", description: "免费的 YAML 转 JSON 和 JSON 转 YAML 转换器。粘贴 YAML 或 JSON 文档，一键切换方向——完全在浏览器中运行。", keywords: ["yaml 转 json", "json 转 yaml", "yaml json 转换器", "yml 转 json", "yaml json 转换"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "输入", output: "输出" },
  ja: { title: "YAML ↔ JSON 変換", short: "YAML と JSON を双方向に変換。", description: "無料の YAML から JSON、JSON から YAML 変換ツール。YAML または JSON ドキュメントを貼り付け、ワンクリックで方向を切り替えられます——すべてブラウザ内で動作します。", keywords: ["yaml から json", "json から yaml", "yaml json 変換", "yml から json", "yaml json 変換"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "入力", output: "出力" },
  ko: { title: "YAML ↔ JSON 변환기", short: "YAML과 JSON 사이를 양방향으로 변환합니다.", description: "무료 YAML to JSON 및 JSON to YAML 변환기. YAML 또는 JSON 문서를 붙여넣고 한 번의 클릭으로 방향을 전환하세요 — 모두 브라우저에서 실행됩니다.", keywords: ["yaml to json", "json to yaml", "yaml json 변환기", "yml to json", "yaml json 변환"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "입력", output: "출력" },
  hi: { title: "YAML ↔ JSON कन्वर्टर", short: "YAML और JSON के बीच दोनों दिशाओं में बदलें।", description: "मुफ्त YAML से JSON और JSON से YAML कन्वर्टर। एक YAML या JSON दस्तावेज़ पेस्ट करें और एक क्लिक से दिशा बदलें — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["yaml से json", "json से yaml", "yaml json कन्वर्टर", "yml से json", "yaml json बदलें"], yamlToJson: "YAML → JSON", jsonToYaml: "JSON → YAML", input: "इनपुट", output: "आउटपुट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
