import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text Encrypt / Decrypt (AES)", short: "Encrypt and decrypt text with a passphrase using AES-256-GCM.", description: "Free AES text encryption tool. Protect a message with a passphrase using AES-256-GCM and a PBKDF2-derived key — all in your browser, nothing uploaded. Paste the result back to decrypt.", keywords: ["text encrypt", "aes encryption online", "encrypt text with password", "aes-gcm encrypt", "decrypt text"], encrypt: "Encrypt", decrypt: "Decrypt", passphrase: "Passphrase", message: "Message", result: "Result", run: "Run" },
  pt: { title: "Text Encrypt / Decrypt (AES)", short: "Encrypt and decrypt text with a passphrase using AES-256-GCM.", description: "Free AES text encryption tool. Protect a message with a passphrase using AES-256-GCM and a PBKDF2-derived key — all in your browser, nothing uploaded. Paste the result back to decrypt.", keywords: ["text encrypt", "aes encryption online", "encrypt text with password", "aes-gcm encrypt", "decrypt text"], encrypt: "Encrypt", decrypt: "Decrypt", passphrase: "Passphrase", message: "Message", result: "Result", run: "Run" },
  id: { title: "Text Encrypt / Decrypt (AES)", short: "Encrypt and decrypt text with a passphrase using AES-256-GCM.", description: "Free AES text encryption tool. Protect a message with a passphrase using AES-256-GCM and a PBKDF2-derived key — all in your browser, nothing uploaded. Paste the result back to decrypt.", keywords: ["text encrypt", "aes encryption online", "encrypt text with password", "aes-gcm encrypt", "decrypt text"], encrypt: "Encrypt", decrypt: "Decrypt", passphrase: "Passphrase", message: "Message", result: "Result", run: "Run" },

  tr: { title: "Metin Şifrele / Çöz (AES)", short: "AES-256-GCM ile metni parolayla şifreleyin ve çözün.", description: "Ücretsiz AES metin şifreleme aracı. Bir mesajı AES-256-GCM ve PBKDF2 türetilmiş anahtarla parolayla koruyun — hepsi tarayıcınızda, hiçbir şey yüklenmez. Çözmek için sonucu geri yapıştırın.", keywords: ["metin şifrele", "aes şifreleme online", "metni parolayla şifrele", "aes-gcm şifrele", "metin çöz"], encrypt: "Şifrele", decrypt: "Çöz", passphrase: "Parola", message: "Mesaj", result: "Sonuç", run: "Çalıştır" },
  de: { title: "Text Verschlüsseln / Entschlüsseln (AES)", short: "Text mit Passphrase per AES-256-GCM ver- und entschlüsseln.", description: "Kostenloses AES-Textverschlüsselungstool. Schützen Sie eine Nachricht mit einer Passphrase per AES-256-GCM und PBKDF2-abgeleitetem Schlüssel — alles im Browser, nichts wird hochgeladen. Ergebnis zum Entschlüsseln zurück einfügen.", keywords: ["text verschlüsseln", "aes verschlüsselung online", "text mit passwort verschlüsseln", "aes-gcm verschlüsseln", "text entschlüsseln"], encrypt: "Verschlüsseln", decrypt: "Entschlüsseln", passphrase: "Passphrase", message: "Nachricht", result: "Ergebnis", run: "Ausführen" },
  fr: { title: "Chiffrer / Déchiffrer du Texte (AES)", short: "Chiffrez et déchiffrez du texte avec une phrase secrète via AES-256-GCM.", description: "Outil de chiffrement de texte AES gratuit. Protégez un message avec une phrase secrète via AES-256-GCM et une clé dérivée PBKDF2 — le tout dans votre navigateur, rien n'est envoyé. Recollez le résultat pour déchiffrer.", keywords: ["chiffrer texte", "chiffrement aes en ligne", "chiffrer texte avec mot de passe", "chiffrer aes-gcm", "déchiffrer texte"], encrypt: "Chiffrer", decrypt: "Déchiffrer", passphrase: "Phrase secrète", message: "Message", result: "Résultat", run: "Exécuter" },
  es: { title: "Cifrar / Descifrar Texto (AES)", short: "Cifra y descifra texto con una frase de contraseña usando AES-256-GCM.", description: "Herramienta gratuita de cifrado de texto AES. Protege un mensaje con una frase de contraseña usando AES-256-GCM y una clave derivada con PBKDF2 — todo en tu navegador, nada se sube. Pega el resultado para descifrar.", keywords: ["cifrar texto", "cifrado aes online", "cifrar texto con contraseña", "cifrar aes-gcm", "descifrar texto"], encrypt: "Cifrar", decrypt: "Descifrar", passphrase: "Frase de contraseña", message: "Mensaje", result: "Resultado", run: "Ejecutar" },
  it: { title: "Cifra / Decifra Testo (AES)", short: "Cifra e decifra testo con una passphrase usando AES-256-GCM.", description: "Strumento gratuito di cifratura testo AES. Proteggi un messaggio con una passphrase usando AES-256-GCM e una chiave derivata con PBKDF2 — tutto nel browser, nulla viene caricato. Incolla il risultato per decifrare.", keywords: ["cifra testo", "cifratura aes online", "cifra testo con password", "cifra aes-gcm", "decifra testo"], encrypt: "Cifra", decrypt: "Decifra", passphrase: "Passphrase", message: "Messaggio", result: "Risultato", run: "Esegui" },
  ar: { title: "تشفير / فك تشفير النص (AES)", short: "شفّر وفك تشفير النص بعبارة مرور باستخدام AES-256-GCM.", description: "أداة تشفير نص AES مجانية. احمِ رسالة بعبارة مرور باستخدام AES-256-GCM ومفتاح مشتق بـ PBKDF2 — كل ذلك في متصفحك، لا شيء يُرفع. الصق النتيجة لفك التشفير.", keywords: ["تشفير النص", "تشفير aes عبر الإنترنت", "تشفير النص بكلمة مرور", "تشفير aes-gcm", "فك تشفير النص"], encrypt: "تشفير", decrypt: "فك التشفير", passphrase: "عبارة المرور", message: "الرسالة", result: "النتيجة", run: "تشغيل" },
  ru: { title: "Шифрование / Расшифровка текста (AES)", short: "Шифруйте и расшифровывайте текст парольной фразой через AES-256-GCM.", description: "Бесплатный инструмент AES-шифрования текста. Защитите сообщение парольной фразой через AES-256-GCM и ключ, полученный PBKDF2 — всё в браузере, ничего не загружается. Вставьте результат обратно для расшифровки.", keywords: ["шифрование текста", "aes шифрование онлайн", "шифровать текст паролем", "aes-gcm шифрование", "расшифровать текст"], encrypt: "Шифровать", decrypt: "Расшифровать", passphrase: "Парольная фраза", message: "Сообщение", result: "Результат", run: "Выполнить" },
  zh: { title: "文本加密 / 解密（AES）", short: "使用 AES-256-GCM 通过口令加密和解密文本。", description: "免费的 AES 文本加密工具。使用 AES-256-GCM 和 PBKDF2 派生密钥通过口令保护消息——全部在浏览器中完成，不上传任何内容。粘贴结果即可解密。", keywords: ["文本加密", "aes 加密 在线", "用密码加密文本", "aes-gcm 加密", "解密文本"], encrypt: "加密", decrypt: "解密", passphrase: "口令", message: "消息", result: "结果", run: "运行" },
  ja: { title: "テキスト暗号化 / 復号（AES）", short: "AES-256-GCM でパスフレーズによりテキストを暗号化・復号。", description: "無料の AES テキスト暗号化ツール。AES-256-GCM と PBKDF2 派生鍵を使い、パスフレーズでメッセージを保護します——すべてブラウザ内で、何もアップロードされません。結果を貼り戻して復号できます。", keywords: ["テキスト暗号化", "aes 暗号化 オンライン", "パスワードでテキスト暗号化", "aes-gcm 暗号化", "テキスト復号"], encrypt: "暗号化", decrypt: "復号", passphrase: "パスフレーズ", message: "メッセージ", result: "結果", run: "実行" },
  ko: { title: "텍스트 암호화 / 복호화 (AES)", short: "AES-256-GCM으로 암호문구를 사용해 텍스트를 암호화·복호화합니다.", description: "무료 AES 텍스트 암호화 도구. AES-256-GCM과 PBKDF2 파생 키를 사용해 암호문구로 메시지를 보호합니다 — 모두 브라우저에서, 아무것도 업로드되지 않습니다. 결과를 다시 붙여넣어 복호화하세요.", keywords: ["텍스트 암호화", "aes 암호화 온라인", "비밀번호로 텍스트 암호화", "aes-gcm 암호화", "텍스트 복호화"], encrypt: "암호화", decrypt: "복호화", passphrase: "암호문구", message: "메시지", result: "결과", run: "실행" },
  hi: { title: "टेक्स्ट एन्क्रिप्ट / डिक्रिप्ट (AES)", short: "AES-256-GCM का उपयोग करके पासफ़्रेज़ से टेक्स्ट एन्क्रिप्ट और डिक्रिप्ट करें।", description: "मुफ्त AES टेक्स्ट एन्क्रिप्शन टूल। AES-256-GCM और PBKDF2-व्युत्पन्न कुंजी का उपयोग करके किसी संदेश को पासफ़्रेज़ से सुरक्षित करें — सब आपके ब्राउज़र में, कुछ भी अपलोड नहीं होता। डिक्रिप्ट करने के लिए परिणाम वापस पेस्ट करें।", keywords: ["टेक्स्ट एन्क्रिप्ट", "aes एन्क्रिप्शन ऑनलाइन", "पासवर्ड से टेक्स्ट एन्क्रिप्ट", "aes-gcm एन्क्रिप्ट", "टेक्स्ट डिक्रिप्ट"], encrypt: "एन्क्रिप्ट", decrypt: "डिक्रिप्ट", passphrase: "पासफ़्रेज़", message: "संदेश", result: "परिणाम", run: "चलाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
