import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image to PDF", short: "Combine JPG and PNG images into a single PDF.", description: "Free image-to-PDF converter. Drop JPG and PNG images and combine them into a single PDF — choose Fit (one image per page at its native size), A4 or Letter. Runs entirely in your browser via pdf-lib.", keywords: ["image to pdf", "jpg to pdf", "png to pdf", "photos to pdf", "convert image to pdf"], drop: "Drop images here or click to choose", pageSize: "Page size", fit: "Fit to image", a4: "A4", letter: "Letter", build: "Build PDF", up: "Move up", down: "Move down", remove: "Remove" },
  pt: { title: "Image to PDF", short: "Combine JPG and PNG images into a single PDF.", description: "Free image-to-PDF converter. Drop JPG and PNG images and combine them into a single PDF — choose Fit (one image per page at its native size), A4 or Letter. Runs entirely in your browser via pdf-lib.", keywords: ["image to pdf", "jpg to pdf", "png to pdf", "photos to pdf", "convert image to pdf"], drop: "Drop images here or click to choose", pageSize: "Page size", fit: "Fit to image", a4: "A4", letter: "Letter", build: "Build PDF", up: "Move up", down: "Move down", remove: "Remove" },
  id: { title: "Image to PDF", short: "Combine JPG and PNG images into a single PDF.", description: "Free image-to-PDF converter. Drop JPG and PNG images and combine them into a single PDF — choose Fit (one image per page at its native size), A4 or Letter. Runs entirely in your browser via pdf-lib.", keywords: ["image to pdf", "jpg to pdf", "png to pdf", "photos to pdf", "convert image to pdf"], drop: "Drop images here or click to choose", pageSize: "Page size", fit: "Fit to image", a4: "A4", letter: "Letter", build: "Build PDF", up: "Move up", down: "Move down", remove: "Remove" },

  tr: { title: "Görsel'den PDF'e", short: "JPG ve PNG görselleri tek bir PDF'te birleştirin.", description: "Ücretsiz görsel-PDF dönüştürücü. JPG ve PNG görselleri bırakın ve tek bir PDF'te birleştirin — Sığdır (kendi boyutunda sayfa başına bir görsel), A4 veya Letter seçin. Tamamen tarayıcınızda pdf-lib ile çalışır.", keywords: ["görsel pdf", "jpg pdf", "png pdf", "fotoğraflar pdf", "görseli pdf'e dönüştür"], drop: "Görselleri buraya bırakın veya seçmek için tıklayın", pageSize: "Sayfa boyutu", fit: "Görsele sığdır", a4: "A4", letter: "Letter", build: "PDF oluştur", up: "Yukarı taşı", down: "Aşağı taşı", remove: "Kaldır" },
  de: { title: "Bilder zu PDF", short: "Kombinieren Sie JPG- und PNG-Bilder zu einer einzigen PDF.", description: "Kostenloser Bild-zu-PDF-Konverter. Legen Sie JPG- und PNG-Bilder ab und kombinieren Sie sie zu einer einzigen PDF — wählen Sie Anpassen (ein Bild pro Seite in nativer Größe), A4 oder Letter. Läuft vollständig im Browser über pdf-lib.", keywords: ["bild zu pdf", "jpg zu pdf", "png zu pdf", "fotos zu pdf", "bild in pdf konvertieren"], drop: "Bilder hier ablegen oder klicken zum Auswählen", pageSize: "Seitengröße", fit: "An Bild anpassen", a4: "A4", letter: "Letter", build: "PDF erstellen", up: "Nach oben", down: "Nach unten", remove: "Entfernen" },
  fr: { title: "Image vers PDF", short: "Combinez les images JPG et PNG en un seul PDF.", description: "Convertisseur image vers PDF gratuit. Déposez des images JPG et PNG et combinez-les en un seul PDF — choisissez Ajuster (une image par page à sa taille native), A4 ou Letter. Fonctionne entièrement dans votre navigateur via pdf-lib.", keywords: ["image vers pdf", "jpg vers pdf", "png vers pdf", "photos vers pdf", "convertir image en pdf"], drop: "Déposez les images ici ou cliquez pour choisir", pageSize: "Taille de page", fit: "Ajuster à l'image", a4: "A4", letter: "Letter", build: "Créer le PDF", up: "Monter", down: "Descendre", remove: "Supprimer" },
  es: { title: "Imagen a PDF", short: "Combina imágenes JPG y PNG en un solo PDF.", description: "Convertidor de imagen a PDF gratuito. Arrastra imágenes JPG y PNG y combínalas en un solo PDF — elige Ajustar (una imagen por página a su tamaño nativo), A4 o Letter. Funciona completamente en tu navegador con pdf-lib.", keywords: ["imagen a pdf", "jpg a pdf", "png a pdf", "fotos a pdf", "convertir imagen a pdf"], drop: "Arrastra imágenes aquí o haz clic para elegir", pageSize: "Tamaño de página", fit: "Ajustar a imagen", a4: "A4", letter: "Letter", build: "Crear PDF", up: "Subir", down: "Bajar", remove: "Eliminar" },
  it: { title: "Immagine a PDF", short: "Combina immagini JPG e PNG in un singolo PDF.", description: "Convertitore immagine-PDF gratuito. Trascina immagini JPG e PNG e combinale in un singolo PDF — scegli Adatta (una immagine per pagina alla sua dimensione nativa), A4 o Letter. Funziona interamente nel browser tramite pdf-lib.", keywords: ["immagine a pdf", "jpg a pdf", "png a pdf", "foto a pdf", "convertire immagine in pdf"], drop: "Trascina le immagini qui o clicca per scegliere", pageSize: "Dimensione pagina", fit: "Adatta all'immagine", a4: "A4", letter: "Letter", build: "Crea PDF", up: "Su", down: "Giù", remove: "Rimuovi" },
  ar: { title: "صورة إلى PDF", short: "ادمج صور JPG و PNG في ملف PDF واحد.", description: "محوّل صور إلى PDF مجاني. أفلِت صور JPG و PNG وادمجها في ملف PDF واحد — اختر ملاءمة (صورة واحدة لكل صفحة بحجمها الأصلي) أو A4 أو Letter. يعمل بالكامل في متصفحك عبر pdf-lib.", keywords: ["صورة إلى pdf", "jpg إلى pdf", "png إلى pdf", "صور إلى pdf", "تحويل الصورة إلى pdf"], drop: "أفلِت الصور هنا أو انقر للاختيار", pageSize: "حجم الصفحة", fit: "ملاءمة الصورة", a4: "A4", letter: "Letter", build: "إنشاء PDF", up: "للأعلى", down: "للأسفل", remove: "إزالة" },
  ru: { title: "Изображения в PDF", short: "Объедините JPG и PNG в один PDF.", description: "Бесплатный конвертер изображений в PDF. Перетащите JPG и PNG и объедините их в один PDF — выберите По размеру (одно изображение на страницу в исходном размере), A4 или Letter. Работает полностью в браузере через pdf-lib.", keywords: ["изображение в pdf", "jpg в pdf", "png в pdf", "фото в pdf", "конвертер изображения в pdf"], drop: "Перетащите изображения сюда или нажмите для выбора", pageSize: "Размер страницы", fit: "По размеру изображения", a4: "A4", letter: "Letter", build: "Создать PDF", up: "Вверх", down: "Вниз", remove: "Удалить" },
  zh: { title: "图片转 PDF", short: "将 JPG 和 PNG 图片合并为一个 PDF。", description: "免费的图片转 PDF 转换器。拖入 JPG 和 PNG 图片并将其合并为一个 PDF——选择适配（每页一张图片，按原始尺寸）、A4 或 Letter。通过 pdf-lib 完全在浏览器中运行。", keywords: ["图片转 pdf", "jpg 转 pdf", "png 转 pdf", "照片转 pdf", "将图片转换为 pdf"], drop: "将图片拖到此处或点击选择", pageSize: "页面大小", fit: "适配图片", a4: "A4", letter: "Letter", build: "构建 PDF", up: "上移", down: "下移", remove: "移除" },
  ja: { title: "画像から PDF", short: "JPG と PNG 画像を 1 つの PDF にまとめる。", description: "無料の画像から PDF 変換ツール。JPG と PNG 画像をドロップして 1 つの PDF にまとめます——フィット（1 ページに 1 画像をネイティブサイズで）、A4、Letter から選べます。pdf-lib によりすべてブラウザ内で動作します。", keywords: ["画像 pdf", "jpg pdf", "png pdf", "写真 pdf", "画像を pdf に変換"], drop: "画像をここにドロップまたはクリックして選択", pageSize: "ページサイズ", fit: "画像に合わせる", a4: "A4", letter: "Letter", build: "PDF を作成", up: "上へ", down: "下へ", remove: "削除" },
  ko: { title: "이미지에서 PDF로", short: "JPG와 PNG 이미지를 단일 PDF로 결합합니다.", description: "무료 이미지-PDF 변환기. JPG와 PNG 이미지를 드롭하여 단일 PDF로 결합하세요 — 맞춤(페이지당 한 이미지를 원본 크기로), A4 또는 Letter 중 선택. pdf-lib를 통해 모두 브라우저에서 실행됩니다.", keywords: ["이미지 pdf", "jpg pdf", "png pdf", "사진 pdf", "이미지를 pdf로 변환"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", pageSize: "페이지 크기", fit: "이미지에 맞춤", a4: "A4", letter: "Letter", build: "PDF 만들기", up: "위로", down: "아래로", remove: "제거" },
  hi: { title: "इमेज से PDF", short: "JPG और PNG इमेज को एक PDF में संयोजित करें।", description: "मुफ्त इमेज-से-PDF कन्वर्टर। JPG और PNG इमेज छोड़ें और उन्हें एक PDF में संयोजित करें — फ़िट (पेज पर एक इमेज मूल आकार में), A4 या Letter चुनें। pdf-lib के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["इमेज से pdf", "jpg से pdf", "png से pdf", "फ़ोटो से pdf", "इमेज को pdf में बदलें"], drop: "यहाँ इमेज छोड़ें या चुनने के लिए क्लिक करें", pageSize: "पेज आकार", fit: "इमेज में फ़िट करें", a4: "A4", letter: "Letter", build: "PDF बनाएं", up: "ऊपर", down: "नीचे", remove: "हटाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
