import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: ".env File Validator", short: "Lint a .env file for bad keys, duplicates and quoting issues.", description: "Free .env validator. Paste a dotenv file to surface invalid keys, duplicate variables, unquoted hashes and unterminated quotes — and to see the parsed key/value table. Runs entirely in your browser.", keywords: ["env validator", "dotenv validator", ".env parser", "env file checker", "dotenv linter"], input: ".env contents", issues: "Issues", parsed: "Parsed", key: "Key", value: "Value", line: "Line", noIssues: "No issues detected." },
  pt: { title: ".env File Validator", short: "Lint a .env file for bad keys, duplicates and quoting issues.", description: "Free .env validator. Paste a dotenv file to surface invalid keys, duplicate variables, unquoted hashes and unterminated quotes — and to see the parsed key/value table. Runs entirely in your browser.", keywords: ["env validator", "dotenv validator", ".env parser", "env file checker", "dotenv linter"], input: ".env contents", issues: "Issues", parsed: "Parsed", key: "Key", value: "Value", line: "Line", noIssues: "No issues detected." },
  id: { title: ".env File Validator", short: "Lint a .env file for bad keys, duplicates and quoting issues.", description: "Free .env validator. Paste a dotenv file to surface invalid keys, duplicate variables, unquoted hashes and unterminated quotes — and to see the parsed key/value table. Runs entirely in your browser.", keywords: ["env validator", "dotenv validator", ".env parser", "env file checker", "dotenv linter"], input: ".env contents", issues: "Issues", parsed: "Parsed", key: "Key", value: "Value", line: "Line", noIssues: "No issues detected." },

  tr: { title: ".env Dosya Doğrulayıcı", short: "Bir .env dosyasını hatalı anahtarlar, kopyalar ve tırnak sorunları için kontrol edin.", description: "Ücretsiz .env doğrulayıcı. Geçersiz anahtarları, kopya değişkenleri, tırnaksız hash'leri ve sonlandırılmamış tırnakları yüzeye çıkarmak ve ayrıştırılmış anahtar/değer tablosunu görmek için bir dotenv dosyası yapıştırın. Tamamen tarayıcınızda çalışır.", keywords: ["env doğrulayıcı", "dotenv doğrulayıcı", ".env ayrıştırıcı", "env dosya denetleyici", "dotenv linter"], input: ".env içeriği", issues: "Sorunlar", parsed: "Ayrıştırılmış", key: "Anahtar", value: "Değer", line: "Satır", noIssues: "Sorun tespit edilmedi." },
  de: { title: ".env-Datei-Validator", short: "Linten Sie eine .env-Datei auf schlechte Schlüssel, Duplikate und Anführungszeichen-Probleme.", description: "Kostenloser .env-Validator. Fügen Sie eine Dotenv-Datei ein, um ungültige Schlüssel, doppelte Variablen, ungequotete Hashes und nicht beendete Anführungszeichen aufzudecken — und um die geparste Schlüssel/Wert-Tabelle zu sehen. Läuft vollständig im Browser.", keywords: ["env validator", "dotenv validator", ".env parser", "env datei checker", "dotenv linter"], input: ".env Inhalt", issues: "Probleme", parsed: "Geparst", key: "Schlüssel", value: "Wert", line: "Zeile", noIssues: "Keine Probleme erkannt." },
  fr: { title: "Validateur de Fichier .env", short: "Lintez un fichier .env pour les mauvaises clés, doublons et problèmes de guillemets.", description: "Validateur .env gratuit. Collez un fichier dotenv pour faire ressortir les clés invalides, variables en double, hashes non échappés et guillemets non fermés — et voir le tableau clé/valeur parsé. Fonctionne entièrement dans votre navigateur.", keywords: ["validateur env", "validateur dotenv", "parser .env", "vérificateur fichier env", "linter dotenv"], input: "Contenu .env", issues: "Problèmes", parsed: "Parsé", key: "Clé", value: "Valeur", line: "Ligne", noIssues: "Aucun problème détecté." },
  es: { title: "Validador de Archivo .env", short: "Lint un archivo .env para claves incorrectas, duplicados y problemas de comillas.", description: "Validador .env gratuito. Pega un archivo dotenv para descubrir claves no válidas, variables duplicadas, hashes sin entrecomillar y comillas sin terminar — y ver la tabla clave/valor parseada. Funciona completamente en tu navegador.", keywords: ["validador env", "validador dotenv", "parser .env", "verificador archivo env", "linter dotenv"], input: "Contenido .env", issues: "Problemas", parsed: "Parseado", key: "Clave", value: "Valor", line: "Línea", noIssues: "No se detectaron problemas." },
  it: { title: "Validatore di File .env", short: "Lint un file .env per chiavi non valide, duplicati e problemi di virgolette.", description: "Validatore .env gratuito. Incolla un file dotenv per individuare chiavi non valide, variabili duplicate, hash non quotati e virgolette non chiuse — e vedere la tabella chiave/valore parsata. Funziona interamente nel browser.", keywords: ["validatore env", "validatore dotenv", "parser .env", "controllore file env", "linter dotenv"], input: "Contenuto .env", issues: "Problemi", parsed: "Parsato", key: "Chiave", value: "Valore", line: "Riga", noIssues: "Nessun problema rilevato." },
  ar: { title: "مدقّق ملف .env", short: "افحص ملف .env بحثًا عن المفاتيح السيئة والتكرارات ومشكلات الاقتباس.", description: "مدقّق .env مجاني. الصق ملف dotenv لإظهار المفاتيح غير الصالحة والمتغيرات المكررة والعلامات # غير المقتبسة والاقتباسات غير المغلقة — ولرؤية جدول المفاتيح/القيم المحلَّل. يعمل بالكامل في متصفحك.", keywords: ["مدقق env", "مدقق dotenv", "محلل .env", "فاحص ملف env", "linter dotenv"], input: "محتوى .env", issues: "المشكلات", parsed: "المحلّل", key: "المفتاح", value: "القيمة", line: "السطر", noIssues: "لم يتم اكتشاف أي مشكلات." },
  ru: { title: "Валидатор .env-файла", short: "Проверьте .env на плохие ключи, дубликаты и проблемы с кавычками.", description: "Бесплатный валидатор .env. Вставьте dotenv-файл, чтобы найти невалидные ключи, дублирующиеся переменные, неэкранированные хеши и незакрытые кавычки — и увидеть распарсенную таблицу ключ/значение. Работает полностью в браузере.", keywords: ["env валидатор", "dotenv валидатор", ".env парсер", "проверка env файла", "dotenv линтер"], input: "Содержимое .env", issues: "Проблемы", parsed: "Распарсено", key: "Ключ", value: "Значение", line: "Строка", noIssues: "Проблем не обнаружено." },
  zh: { title: ".env 文件验证器", short: "对 .env 文件进行 lint 检查，发现错误的键、重复项和引号问题。", description: "免费的 .env 验证器。粘贴 dotenv 文件以发现无效键、重复变量、未引用的哈希和未终止的引号——并查看解析后的键/值表。完全在浏览器中运行。", keywords: ["env 验证器", "dotenv 验证器", ".env 解析器", "env 文件检查器", "dotenv linter"], input: ".env 内容", issues: "问题", parsed: "已解析", key: "键", value: "值", line: "行", noIssues: "未检测到问题。" },
  ja: { title: ".env ファイルバリデーター", short: ".env ファイルの不正なキー、重複、クォート問題を lint。", description: "無料の .env バリデーター。dotenv ファイルを貼り付けて無効なキー、重複変数、引用符のないハッシュ、終端のない引用符を表示——そしてパースされたキー/値テーブルを確認します。すべてブラウザ内で動作します。", keywords: ["env バリデーター", "dotenv バリデーター", ".env パーサー", "env ファイル チェッカー", "dotenv リンター"], input: ".env コンテンツ", issues: "問題", parsed: "パース済み", key: "キー", value: "値", line: "行", noIssues: "問題は検出されませんでした。" },
  ko: { title: ".env 파일 검증기", short: "잘못된 키, 중복, 인용 문제에 대해 .env 파일을 lint합니다.", description: "무료 .env 검증기. dotenv 파일을 붙여넣어 잘못된 키, 중복 변수, 인용되지 않은 해시, 종료되지 않은 인용을 표면화하고 파싱된 키/값 테이블을 확인하세요. 모두 브라우저에서 실행됩니다.", keywords: ["env 검증기", "dotenv 검증기", ".env 파서", "env 파일 검사기", "dotenv 린터"], input: ".env 내용", issues: "문제", parsed: "파싱됨", key: "키", value: "값", line: "줄", noIssues: "문제가 감지되지 않았습니다." },
  hi: { title: ".env फ़ाइल वैलिडेटर", short: "खराब कुंजियों, डुप्लिकेट और उद्धरण समस्याओं के लिए .env फ़ाइल लिंट करें।", description: "मुफ्त .env वैलिडेटर। एक dotenv फ़ाइल पेस्ट करें ताकि अमान्य कुंजियाँ, डुप्लिकेट चर, बिना उद्धरण वाले हैश और बिना समाप्त उद्धरण सामने आ सकें — और पार्स की हुई कुंजी/मान तालिका देख सकें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["env वैलिडेटर", "dotenv वैलिडेटर", ".env पार्सर", "env फ़ाइल चेकर", "dotenv लिंटर"], input: ".env सामग्री", issues: "समस्याएं", parsed: "पार्स किया गया", key: "कुंजी", value: "मान", line: "पंक्ति", noIssues: "कोई समस्या नहीं मिली।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
