import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Twitter / X Card Generator", short: "Build twitter:* meta tags with a card preview.", description: "Free Twitter / X Card generator. Choose summary, summary_large_image, app or player; fill in handles, title, description and image; copy the meta tags with a live card preview.", keywords: ["twitter card generator", "twitter meta tags", "x cards", "summary large image", "twitter preview"], card: "Card type", site: "Site (@handle)", creator: "Creator (@handle)", titleField: "Title", descriptionField: "Description", image: "Image URL", imageAlt: "Image alt", output: "Twitter tags", preview: "Preview" },
  tr: { title: "Twitter / X Card Oluşturucu", short: "Kart önizlemesiyle twitter:* meta etiketleri oluşturun.", description: "Ücretsiz Twitter / X Card oluşturucu. summary, summary_large_image, app veya player seçin; kullanıcı adı, başlık, açıklama ve görsel girin; canlı kart önizlemesiyle meta etiketleri kopyalayın.", keywords: ["twitter card oluşturucu", "twitter meta etiketleri", "x cards", "summary large image", "twitter önizleme"], card: "Kart türü", site: "Site (@kullanıcı)", creator: "Oluşturan (@kullanıcı)", titleField: "Başlık", descriptionField: "Açıklama", image: "Görsel URL'si", imageAlt: "Görsel alt metni", output: "Twitter etiketleri", preview: "Önizleme" },
  de: { title: "Twitter / X Card Generator", short: "Erzeugen Sie twitter:* Meta-Tags mit Card-Vorschau.", description: "Kostenloser Twitter / X Card Generator. Wählen Sie summary, summary_large_image, app oder player; geben Sie Handles, Titel, Beschreibung und Bild ein; kopieren Sie die Meta-Tags mit einer Live-Card-Vorschau.", keywords: ["twitter card generator", "twitter meta tags", "x cards", "summary large image", "twitter vorschau"], card: "Kartentyp", site: "Site (@handle)", creator: "Ersteller (@handle)", titleField: "Titel", descriptionField: "Beschreibung", image: "Bild-URL", imageAlt: "Bild-Alt", output: "Twitter-Tags", preview: "Vorschau" },
  fr: { title: "Générateur Twitter / X Card", short: "Construisez les meta tags twitter:* avec aperçu de carte.", description: "Générateur Twitter / X Card gratuit. Choisissez summary, summary_large_image, app ou player ; remplissez handles, titre, description et image ; copiez les meta tags avec aperçu de carte en direct.", keywords: ["générateur twitter card", "twitter meta tags", "x cards", "summary large image", "aperçu twitter"], card: "Type de carte", site: "Site (@handle)", creator: "Créateur (@handle)", titleField: "Titre", descriptionField: "Description", image: "URL de l'image", imageAlt: "Alt de l'image", output: "Tags Twitter", preview: "Aperçu" },
  es: { title: "Generador de Twitter / X Card", short: "Construye meta tags twitter:* con vista previa de tarjeta.", description: "Generador de Twitter / X Card gratuito. Elige summary, summary_large_image, app o player; rellena handles, título, descripción e imagen; copia las meta tags con vista previa de tarjeta en vivo.", keywords: ["generador twitter card", "twitter meta tags", "x cards", "summary large image", "vista previa twitter"], card: "Tipo de tarjeta", site: "Sitio (@handle)", creator: "Creador (@handle)", titleField: "Título", descriptionField: "Descripción", image: "URL imagen", imageAlt: "Alt imagen", output: "Tags Twitter", preview: "Vista previa" },
  it: { title: "Generatore Twitter / X Card", short: "Costruisci meta tag twitter:* con anteprima card.", description: "Generatore Twitter / X Card gratuito. Scegli summary, summary_large_image, app o player; compila handle, titolo, descrizione e immagine; copia i meta tag con anteprima card dal vivo.", keywords: ["generatore twitter card", "twitter meta tag", "x cards", "summary large image", "anteprima twitter"], card: "Tipo card", site: "Sito (@handle)", creator: "Autore (@handle)", titleField: "Titolo", descriptionField: "Descrizione", image: "URL immagine", imageAlt: "Alt immagine", output: "Tag Twitter", preview: "Anteprima" },
  ar: { title: "مولّد Twitter / X Card", short: "أنشئ علامات twitter:* مع معاينة البطاقة.", description: "مولّد Twitter / X Card مجاني. اختر summary أو summary_large_image أو app أو player؛ املأ المعرّفات والعنوان والوصف والصورة؛ انسخ علامات Meta مع معاينة بطاقة حية.", keywords: ["مولد twitter card", "علامات twitter meta", "x cards", "summary large image", "معاينة twitter"], card: "نوع البطاقة", site: "الموقع (@معرف)", creator: "المؤلف (@معرف)", titleField: "العنوان", descriptionField: "الوصف", image: "عنوان URL للصورة", imageAlt: "نص بديل للصورة", output: "علامات Twitter", preview: "معاينة" },
  ru: { title: "Генератор Twitter / X Card", short: "Создайте twitter:* meta-теги с превью карточки.", description: "Бесплатный генератор Twitter / X Card. Выберите summary, summary_large_image, app или player; заполните handles, title, description и image; скопируйте meta-теги с живым превью карточки.", keywords: ["генератор twitter card", "twitter meta теги", "x cards", "summary large image", "twitter превью"], card: "Тип карточки", site: "Сайт (@handle)", creator: "Автор (@handle)", titleField: "Заголовок", descriptionField: "Описание", image: "URL изображения", imageAlt: "Alt изображения", output: "Twitter теги", preview: "Превью" },
  zh: { title: "Twitter / X Card 生成器", short: "构建带卡片预览的 twitter:* meta 标签。", description: "免费的 Twitter / X Card 生成器。选择 summary、summary_large_image、app 或 player；填入 handle、标题、描述和图片；复制 meta 标签并预览卡片效果。", keywords: ["twitter card 生成器", "twitter meta 标签", "x cards", "summary large image", "twitter 预览"], card: "卡片类型", site: "站点（@handle）", creator: "作者（@handle）", titleField: "标题", descriptionField: "描述", image: "图片 URL", imageAlt: "图片 Alt", output: "Twitter 标签", preview: "预览" },
  ja: { title: "Twitter / X Card 生成", short: "カードプレビュー付きで twitter:* メタタグを構築。", description: "無料の Twitter / X Card 生成ツール。summary、summary_large_image、app、player から選択し、ハンドル、タイトル、説明、画像を入力すると、ライブカードプレビュー付きでメタタグをコピーできます。", keywords: ["twitter card 生成", "twitter meta タグ", "x cards", "summary large image", "twitter プレビュー"], card: "カードタイプ", site: "サイト（@ハンドル）", creator: "作成者（@ハンドル）", titleField: "タイトル", descriptionField: "説明", image: "画像 URL", imageAlt: "画像 alt", output: "Twitter タグ", preview: "プレビュー" },
  ko: { title: "Twitter / X Card 생성기", short: "카드 미리보기와 함께 twitter:* meta 태그를 만듭니다.", description: "무료 Twitter / X Card 생성기. summary, summary_large_image, app 또는 player를 선택하고 핸들, 제목, 설명, 이미지를 입력해 카드 미리보기와 함께 meta 태그를 복사하세요.", keywords: ["twitter card 생성기", "twitter meta 태그", "x cards", "summary large image", "twitter 미리보기"], card: "카드 유형", site: "사이트 (@핸들)", creator: "작성자 (@핸들)", titleField: "제목", descriptionField: "설명", image: "이미지 URL", imageAlt: "이미지 alt", output: "Twitter 태그", preview: "미리보기" },
  hi: { title: "Twitter / X Card जनरेटर", short: "कार्ड प्रीव्यू के साथ twitter:* meta टैग बनाएं।", description: "मुफ्त Twitter / X Card जनरेटर। summary, summary_large_image, app या player चुनें; हैंडल, शीर्षक, विवरण और छवि भरें; लाइव कार्ड प्रीव्यू के साथ meta टैग कॉपी करें।", keywords: ["twitter card जनरेटर", "twitter meta टैग", "x cards", "summary large image", "twitter प्रीव्यू"], card: "कार्ड प्रकार", site: "साइट (@हैंडल)", creator: "क्रिएटर (@हैंडल)", titleField: "शीर्षक", descriptionField: "विवरण", image: "छवि URL", imageAlt: "छवि alt", output: "Twitter टैग", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
