import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text Diff Checker", short: "Compare two texts and highlight added and removed lines.", description: "Free text diff checker. Paste two versions of text to see a line-by-line comparison, with added lines highlighted in green and removed lines in red. Great for comparing drafts, configs and code.", keywords: ["text diff", "compare text", "diff checker", "text comparison", "difference between two texts"], original: "Original", changed: "Changed", placeholder: "Paste text…", added: "added", removed: "removed", identical: "The two texts are identical." },
  pt: { title: "Verificador de Text Diff", short: "Compare two texts e highlight added e removed lines.", description: "Gratuito - text diff checker. Paste two versions de text para see a line-by-line comparison, com added lines highlighted em green e removed lines em red. Great para comparing drafts, configs e code.", keywords: ["text diff", "compare text", "diff checker", "text comparison", "difference between two texts"], original: "Original", changed: "Changed", placeholder: "Paste text…", added: "added", removed: "removed", identical: "The two texts are identical." },
  id: { title: "Pemeriksa Text Diff", short: "Compare two texts dan highlight added dan removed lines.", description: "Gratis - text diff checker. Paste two versions dari text to see a line-by-line comparison, with added lines highlighted in green dan removed lines in red. Great for comparing drafts, configs dan code.", keywords: ["text diff", "compare text", "diff checker", "text comparison", "difference between two texts"], original: "Original", changed: "Changed", placeholder: "Paste text…", added: "added", removed: "removed", identical: "The two texts are identical." },

  tr: { title: "Metin Karşılaştırma (Diff)", short: "İki metni karşılaştırın, eklenen ve kaldırılan satırları vurgulayın.", description: "Ücretsiz metin diff aracı. Metnin iki sürümünü yapıştırın; satır satır karşılaştırma görün, eklenen satırlar yeşil, kaldırılanlar kırmızı vurgulanır. Taslakları, yapılandırmaları ve kodu karşılaştırmak için harika.", keywords: ["metin diff", "metin karşılaştır", "diff aracı", "metin karşılaştırma", "iki metin arasındaki fark"], original: "Orijinal", changed: "Değişen", placeholder: "Metni yapıştırın…", added: "eklendi", removed: "kaldırıldı", identical: "İki metin aynı." },
  de: { title: "Text-Diff-Prüfer", short: "Vergleichen Sie zwei Texte und heben Sie hinzugefügte/entfernte Zeilen hervor.", description: "Kostenloser Text-Diff-Prüfer. Fügen Sie zwei Textversionen ein, um einen zeilenweisen Vergleich zu sehen — hinzugefügte Zeilen grün, entfernte rot. Ideal zum Vergleichen von Entwürfen, Konfigs und Code.", keywords: ["text diff", "text vergleichen", "diff prüfer", "textvergleich", "unterschied zweier texte"], original: "Original", changed: "Geändert", placeholder: "Text einfügen…", added: "hinzugefügt", removed: "entfernt", identical: "Die beiden Texte sind identisch." },
  fr: { title: "Comparateur de Texte (Diff)", short: "Comparez deux textes et mettez en évidence les lignes ajoutées et supprimées.", description: "Comparateur de texte gratuit. Collez deux versions d'un texte pour voir une comparaison ligne par ligne, avec les lignes ajoutées en vert et supprimées en rouge. Idéal pour comparer brouillons, configs et code.", keywords: ["diff texte", "comparer texte", "comparateur de texte", "comparaison de texte", "différence entre deux textes"], original: "Original", changed: "Modifié", placeholder: "Collez le texte…", added: "ajoutées", removed: "supprimées", identical: "Les deux textes sont identiques." },
  es: { title: "Comparador de Texto (Diff)", short: "Compara dos textos y resalta las líneas añadidas y eliminadas.", description: "Comparador de texto gratuito. Pega dos versiones de un texto para ver una comparación línea por línea, con líneas añadidas en verde y eliminadas en rojo. Ideal para comparar borradores, configuraciones y código.", keywords: ["diff de texto", "comparar texto", "comparador de texto", "comparación de texto", "diferencia entre dos textos"], original: "Original", changed: "Modificado", placeholder: "Pega el texto…", added: "añadidas", removed: "eliminadas", identical: "Los dos textos son idénticos." },
  it: { title: "Confronto di Testo (Diff)", short: "Confronta due testi ed evidenzia le righe aggiunte e rimosse.", description: "Confronto di testo gratuito. Incolla due versioni di un testo per vedere un confronto riga per riga, con righe aggiunte in verde e rimosse in rosso. Ottimo per confrontare bozze, configurazioni e codice.", keywords: ["diff testo", "confronta testo", "confronto testo", "comparazione testo", "differenza tra due testi"], original: "Originale", changed: "Modificato", placeholder: "Incolla il testo…", added: "aggiunte", removed: "rimosse", identical: "I due testi sono identici." },
  ar: { title: "أداة مقارنة النصوص (Diff)", short: "قارن نصين وأبرز الأسطر المضافة والمحذوفة.", description: "أداة مقارنة نصوص مجانية. الصق نسختين من النص لرؤية مقارنة سطرًا بسطر، مع إبراز الأسطر المضافة بالأخضر والمحذوفة بالأحمر. رائعة لمقارنة المسودات والإعدادات والشيفرة.", keywords: ["مقارنة النصوص", "قارن النص", "أداة diff", "مقارنة نص", "الفرق بين نصين"], original: "الأصلي", changed: "المعدّل", placeholder: "الصق النص…", added: "مضافة", removed: "محذوفة", identical: "النصان متطابقان." },
  ru: { title: "Сравнение Текстов (Diff)", short: "Сравните два текста и подсветите добавленные и удалённые строки.", description: "Бесплатное сравнение текстов. Вставьте две версии текста, чтобы увидеть построчное сравнение: добавленные строки — зелёным, удалённые — красным. Отлично для сравнения черновиков, конфигов и кода.", keywords: ["diff текста", "сравнить текст", "сравнение текстов", "разница между текстами", "diff checker"], original: "Оригинал", changed: "Изменённый", placeholder: "Вставьте текст…", added: "добавлено", removed: "удалено", identical: "Два текста идентичны." },
  zh: { title: "文本差异对比", short: "比较两段文本并高亮新增和删除的行。", description: "免费的文本差异对比工具。粘贴两个版本的文本，即可查看逐行比较，新增行以绿色高亮、删除行以红色高亮。适合比较草稿、配置和代码。", keywords: ["文本差异", "比较文本", "diff工具", "文本对比", "两段文本的区别"], original: "原始", changed: "修改后", placeholder: "粘贴文本…", added: "新增", removed: "删除", identical: "两段文本完全相同。" },
  ja: { title: "テキスト差分チェッカー", short: "2つのテキストを比較し、追加・削除された行を強調表示します。", description: "無料のテキスト差分チェッカー。2つのバージョンのテキストを貼り付けると、行ごとの比較が表示され、追加行は緑、削除行は赤で強調されます。下書き・設定・コードの比較に最適。", keywords: ["テキスト差分", "テキスト比較", "diff チェッカー", "テキスト比較ツール", "2つのテキストの違い"], original: "オリジナル", changed: "変更後", placeholder: "テキストを貼り付け…", added: "追加", removed: "削除", identical: "2つのテキストは同一です。" },
  ko: { title: "텍스트 비교(Diff) 검사기", short: "두 텍스트를 비교하고 추가/삭제된 줄을 강조합니다.", description: "무료 텍스트 비교 검사기. 두 버전의 텍스트를 붙여넣으면 줄 단위 비교가 표시되며 추가된 줄은 녹색, 삭제된 줄은 빨간색으로 강조됩니다. 초안, 설정, 코드 비교에 적합합니다.", keywords: ["텍스트 diff", "텍스트 비교", "diff 검사기", "텍스트 비교 도구", "두 텍스트 차이"], original: "원본", changed: "변경됨", placeholder: "텍스트 붙여넣기…", added: "추가됨", removed: "삭제됨", identical: "두 텍스트가 동일합니다." },
  hi: { title: "टेक्स्ट डिफ चेकर", short: "दो टेक्स्ट की तुलना करें और जोड़ी/हटाई गई पंक्तियाँ हाइलाइट करें।", description: "मुफ्त टेक्स्ट डिफ चेकर। टेक्स्ट के दो संस्करण पेस्ट करें और पंक्ति-दर-पंक्ति तुलना देखें — जोड़ी गई पंक्तियाँ हरे और हटाई गई लाल रंग में। ड्राफ्ट, कॉन्फ़िग और कोड की तुलना के लिए बढ़िया।", keywords: ["टेक्स्ट डिफ", "टेक्स्ट तुलना", "डिफ चेकर", "टेक्स्ट तुलना उपकरण", "दो टेक्स्ट का अंतर"], original: "मूल", changed: "बदला हुआ", placeholder: "टेक्स्ट पेस्ट करें…", added: "जोड़ी गई", removed: "हटाई गई", identical: "दोनों टेक्स्ट समान हैं।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
