import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Gradient Generator", short: "Create linear or radial CSS gradients with a live preview.", description: "Free CSS gradient generator. Pick two colors, choose linear or radial and set the angle to get ready-to-paste CSS gradient code with a live preview.", keywords: ["css gradient generator", "linear gradient", "radial gradient", "background gradient", "css gradient code"], type: "Type", angle: "Angle", color1: "Color 1", color2: "Color 2", linear: "Linear", radial: "Radial", preview: "Preview" },
  nl: { title: "CSS Gradient Generator", short: "Maak aan linear or radial CSS gradients with a live voorbeeld.", description: "Gratis CSS gradient generator. Pick two kleurs, choose linear or radial and set the angle to get ready-to-paste CSS gradient code with a live voorbeeld.", keywords: ["css gradient generator", "linear gradient", "radial gradient", "background gradient", "css gradient code"], type: "Type", angle: "Angle", color1: "Kleur 1", color2: "Kleur 2", linear: "Linear", radial: "Radial", preview: "Voorbeeld" },

  pl: { title: "CSS Gradient Generator", short: "Utwórz linear or radial CSS gradients with a live podgląd.", description: "Darmowy CSS gradient generator. Pick two kolors, choose linear or radial and set the angle to get ready-to-paste CSS gradient kod with a live podgląd.", keywords: ["css gradient generator", "linear gradient", "radial gradient", "background gradient", "css gradient kod"], type: "Typ", angle: "Angle", color1: "Kolor 1", color2: "Kolor 2", linear: "Linear", radial: "Radial", preview: "Podgląd" },
  pt: { title: "Gerador de CSS Gradient", short: "Create linear ou radial CSS gradients com a live preview.", description: "Gratuito - CSS gradient generator. Pick two colors, choose linear ou radial e set the angle para get ready-para-paste CSS gradient code com a live preview.", keywords: ["css gradient generator", "linear gradient", "radial gradient", "background gradient", "css gradient code"], type: "Type", angle: "Angle", color1: "Color 1", color2: "Color 2", linear: "Linear", radial: "Radial", preview: "Preview" },
  id: { title: "Generator CSS Gradient", short: "Create linear atau radial CSS gradients with a live preview.", description: "Gratis - CSS gradient generator. Pick two colors, choose linear atau radial dan set the angle to get ready-to-paste CSS gradient code with a live preview.", keywords: ["css gradient generator", "linear gradient", "radial gradient", "background gradient", "css gradient code"], type: "Type", angle: "Angle", color1: "Color 1", color2: "Color 2", linear: "Linear", radial: "Radial", preview: "Preview" },

  tr: { title: "CSS Gradyan Oluşturucu", short: "Canlı önizlemeyle doğrusal veya dairesel CSS gradyanları oluşturun.", description: "Ücretsiz CSS gradyan oluşturucu. İki renk seçin, doğrusal veya dairesel belirleyin ve açıyı ayarlayarak canlı önizlemeyle yapıştırmaya hazır CSS gradyan kodu alın.", keywords: ["css gradyan oluşturucu", "doğrusal gradyan", "dairesel gradyan", "arka plan gradyanı", "css gradyan kodu"], type: "Tür", angle: "Açı", color1: "Renk 1", color2: "Renk 2", linear: "Doğrusal", radial: "Dairesel", preview: "Önizleme" },
  de: { title: "CSS-Verlauf-Generator", short: "Erstellen Sie lineare oder radiale CSS-Verläufe mit Live-Vorschau.", description: "Kostenloser CSS-Verlauf-Generator. Wählen Sie zwei Farben, linear oder radial und den Winkel, um einsatzbereiten CSS-Verlaufscode mit Live-Vorschau zu erhalten.", keywords: ["css verlauf generator", "linearer verlauf", "radialer verlauf", "hintergrundverlauf", "css gradient code"], type: "Typ", angle: "Winkel", color1: "Farbe 1", color2: "Farbe 2", linear: "Linear", radial: "Radial", preview: "Vorschau" },
  fr: { title: "Générateur de Dégradé CSS", short: "Créez des dégradés CSS linéaires ou radiaux avec aperçu en direct.", description: "Générateur de dégradé CSS gratuit. Choisissez deux couleurs, linéaire ou radial et l'angle pour obtenir un code de dégradé CSS prêt à coller avec aperçu en direct.", keywords: ["générateur dégradé css", "dégradé linéaire", "dégradé radial", "dégradé d'arrière-plan", "code dégradé css"], type: "Type", angle: "Angle", color1: "Couleur 1", color2: "Couleur 2", linear: "Linéaire", radial: "Radial", preview: "Aperçu" },
  es: { title: "Generador de Degradados CSS", short: "Crea degradados CSS lineales o radiales con vista previa en vivo.", description: "Generador de degradados CSS gratuito. Elige dos colores, lineal o radial y el ángulo para obtener código de degradado CSS listo para pegar con vista previa en vivo.", keywords: ["generador degradado css", "degradado lineal", "degradado radial", "degradado de fondo", "código degradado css"], type: "Tipo", angle: "Ángulo", color1: "Color 1", color2: "Color 2", linear: "Lineal", radial: "Radial", preview: "Vista previa" },
  it: { title: "Generatore di Gradiente CSS", short: "Crea gradienti CSS lineari o radiali con anteprima dal vivo.", description: "Generatore di gradiente CSS gratuito. Scegli due colori, lineare o radiale e l'angolo per ottenere codice di gradiente CSS pronto da incollare con anteprima dal vivo.", keywords: ["generatore gradiente css", "gradiente lineare", "gradiente radiale", "gradiente sfondo", "codice gradiente css"], type: "Tipo", angle: "Angolo", color1: "Colore 1", color2: "Colore 2", linear: "Lineare", radial: "Radiale", preview: "Anteprima" },
  ar: { title: "مولّد تدرّج CSS", short: "أنشئ تدرّجات CSS خطية أو شعاعية مع معاينة حية.", description: "مولّد تدرّج CSS مجاني. اختر لونين، خطيًا أو شعاعيًا واضبط الزاوية للحصول على كود تدرّج CSS جاهز للصق مع معاينة حية.", keywords: ["مولد تدرج css", "تدرج خطي", "تدرج شعاعي", "تدرج الخلفية", "كود تدرج css"], type: "النوع", angle: "الزاوية", color1: "اللون 1", color2: "اللون 2", linear: "خطي", radial: "شعاعي", preview: "معاينة" },
  ru: { title: "Генератор CSS-градиентов", short: "Создавайте линейные или радиальные CSS-градиенты с живым превью.", description: "Бесплатный генератор CSS-градиентов. Выберите два цвета, линейный или радиальный и угол, чтобы получить готовый CSS-код градиента с живым превью.", keywords: ["генератор css градиентов", "линейный градиент", "радиальный градиент", "фоновый градиент", "css градиент код"], type: "Тип", angle: "Угол", color1: "Цвет 1", color2: "Цвет 2", linear: "Линейный", radial: "Радиальный", preview: "Превью" },
  zh: { title: "CSS 渐变生成器", short: "创建线性或径向 CSS 渐变并实时预览。", description: "免费的 CSS 渐变生成器。选择两种颜色、线性或径向并设置角度，即可获得可直接粘贴的 CSS 渐变代码并实时预览。", keywords: ["css渐变生成器", "线性渐变", "径向渐变", "背景渐变", "css渐变代码"], type: "类型", angle: "角度", color1: "颜色 1", color2: "颜色 2", linear: "线性", radial: "径向", preview: "预览" },
  ja: { title: "CSS グラデーション生成", short: "ライブプレビュー付きで線形・放射状 CSS グラデーションを作成。", description: "無料の CSS グラデーション生成ツール。2 色を選び、線形か放射状かと角度を設定すると、貼り付け可能な CSS グラデーションコードがライブプレビュー付きで得られます。", keywords: ["css グラデーション 生成", "線形グラデーション", "放射状グラデーション", "背景グラデーション", "css グラデーション コード"], type: "種類", angle: "角度", color1: "色 1", color2: "色 2", linear: "線形", radial: "放射状", preview: "プレビュー" },
  ko: { title: "CSS 그라디언트 생성기", short: "실시간 미리보기로 선형 또는 방사형 CSS 그라디언트를 만듭니다.", description: "무료 CSS 그라디언트 생성기. 두 색상을 선택하고 선형 또는 방사형과 각도를 설정하면 붙여넣을 수 있는 CSS 그라디언트 코드를 실시간 미리보기와 함께 얻습니다.", keywords: ["css 그라디언트 생성기", "선형 그라디언트", "방사형 그라디언트", "배경 그라디언트", "css 그라디언트 코드"], type: "유형", angle: "각도", color1: "색상 1", color2: "색상 2", linear: "선형", radial: "방사형", preview: "미리보기" },
  hi: { title: "CSS ग्रेडिएंट जनरेटर", short: "लाइव प्रीव्यू के साथ रैखिक या रेडियल CSS ग्रेडिएंट बनाएं।", description: "मुफ्त CSS ग्रेडिएंट जनरेटर। दो रंग चुनें, रैखिक या रेडियल और कोण सेट करें और लाइव प्रीव्यू के साथ पेस्ट-तैयार CSS ग्रेडिएंट कोड पाएं।", keywords: ["css ग्रेडिएंट जनरेटर", "रैखिक ग्रेडिएंट", "रेडियल ग्रेडिएंट", "बैकग्राउंड ग्रेडिएंट", "css ग्रेडिएंट कोड"], type: "प्रकार", angle: "कोण", color1: "रंग 1", color2: "रंग 2", linear: "रैखिक", radial: "रेडियल", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
