import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IP Address Info", short: "Classify an IPv4 or IPv6 address (private, loopback, multicast, …).", description: "Free IP address classifier. Paste an IPv4 or IPv6 to see its classful class, whether it's private, loopback, link-local, multicast or a documentation range — plus RFC notes.", keywords: ["ip class lookup", "private ip range", "ip address info", "rfc 1918 check", "ipv4 class"], input: "IP address", version: "Version", classful: "Classful class", flag: "Flag", notes: "Notes", privateRange: "Private", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },
  nl: { title: "IP Address Info", short: "Classify an IPv4 or IPv6 address (private, loopback, multicast, …).", description: "Gratis IP address classifier. Paste an IPv4 or IPv6 to see its classful class, whether it's private, loopback, link-local, multicast or a documentation range — plus RFC notes.", keywords: ["ip class lookup", "private ip range", "ip address info", "rfc 1918 controleer", "ipv4 class"], input: "IP address", version: "Version", classful: "Classful class", flag: "Flag", notes: "Notes", privateRange: "Private", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },

  pl: { title: "IP Address Info", short: "Classify an IPv4 or IPv6 address (private, loopback, multicast, …).", description: "Darmowy IP address classifier. Paste an IPv4 or IPv6 to see its classful class, whether it's private, loopback, link-local, multicast or a documentation range — plus RFC notes.", keywords: ["ip class lookup", "private ip range", "ip address info", "rfc 1918 sprawdź", "ipv4 class"], input: "IP address", version: "Version", classful: "Classful class", flag: "Flag", notes: "Notes", privateRange: "Private", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },
  pt: { title: "IP Address Info", short: "Classify an IPv4 ou IPv6 address (private, loopback, multicast, â¦).", description: "Gratuito - IP address classifier. Paste an IPv4 ou IPv6 para see its classful class, whether it's private, loopback, link-local, multicast ou a documentation range â plus RFC notes.", keywords: ["ip class lookup", "private ip range", "ip address info", "rfc 1918 check", "ipv4 class"], input: "IP address", version: "Version", classful: "Classful class", flag: "Flag", notes: "Notes", privateRange: "Private", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },
  id: { title: "IP Address Info", short: "Classify an IPv4 atau IPv6 address (private, loopback, multicast, â¦).", description: "Gratis - IP address classifier. Paste an IPv4 atau IPv6 to see its classful class, whether it's private, loopback, link-local, multicast atau a documentation range â plus RFC notes.", keywords: ["ip class lookup", "private ip range", "ip address info", "rfc 1918 check", "ipv4 class"], input: "IP address", version: "Version", classful: "Classful class", flag: "Flag", notes: "Notes", privateRange: "Private", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },

  tr: { title: "IP Adres Bilgisi", short: "Bir IPv4 veya IPv6 adresini sınıflandırın (özel, loopback, multicast, …).", description: "Ücretsiz IP adres sınıflandırıcı. Bir IPv4 veya IPv6 yapıştırın ve sınıfsal sınıfını, özel, loopback, link-local, multicast veya dokümantasyon aralığında olup olmadığını görün — RFC notlarıyla birlikte.", keywords: ["ip sınıf arama", "özel ip aralığı", "ip adres bilgisi", "rfc 1918 kontrol", "ipv4 sınıfı"], input: "IP adresi", version: "Sürüm", classful: "Sınıfsal sınıf", flag: "Bayrak", notes: "Notlar", privateRange: "Özel", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Dokümantasyon" },
  de: { title: "IP-Adressen-Info", short: "Klassifiziert eine IPv4- oder IPv6-Adresse (privat, loopback, multicast, …).", description: "Kostenloser IP-Adressen-Klassifizierer. Fügen Sie eine IPv4 oder IPv6 ein, um die classful-Klasse zu sehen sowie ob sie privat, loopback, link-local, multicast oder Dokumentationsbereich ist — mit RFC-Hinweisen.", keywords: ["ip klasse lookup", "privater ip bereich", "ip adressen info", "rfc 1918 check", "ipv4 klasse"], input: "IP-Adresse", version: "Version", classful: "Classful-Klasse", flag: "Flag", notes: "Hinweise", privateRange: "Privat", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Dokumentation" },
  fr: { title: "Info Adresse IP", short: "Classez une adresse IPv4 ou IPv6 (privée, loopback, multicast, …).", description: "Classificateur d'adresses IP gratuit. Collez une IPv4 ou IPv6 pour voir sa classe classful, si elle est privée, loopback, link-local, multicast ou plage de documentation — avec notes RFC.", keywords: ["lookup classe ip", "plage ip privée", "info adresse ip", "vérification rfc 1918", "classe ipv4"], input: "Adresse IP", version: "Version", classful: "Classe classful", flag: "Drapeau", notes: "Notes", privateRange: "Privée", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentation" },
  es: { title: "Información de IP", short: "Clasifica una dirección IPv4 o IPv6 (privada, loopback, multicast, …).", description: "Clasificador de IP gratuito. Pega una IPv4 o IPv6 para ver su clase classful, si es privada, loopback, link-local, multicast o rango de documentación — con notas RFC.", keywords: ["lookup clase ip", "rango ip privado", "info dirección ip", "verificación rfc 1918", "clase ipv4"], input: "Dirección IP", version: "Versión", classful: "Clase classful", flag: "Bandera", notes: "Notas", privateRange: "Privada", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentación" },
  it: { title: "Info Indirizzo IP", short: "Classifica un indirizzo IPv4 o IPv6 (privato, loopback, multicast, …).", description: "Classificatore IP gratuito. Incolla un IPv4 o IPv6 per vedere la sua classe classful, se è privato, loopback, link-local, multicast o range di documentazione — con note RFC.", keywords: ["ricerca classe ip", "range ip privato", "info indirizzo ip", "verifica rfc 1918", "classe ipv4"], input: "Indirizzo IP", version: "Versione", classful: "Classe classful", flag: "Flag", notes: "Note", privateRange: "Privato", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Documentazione" },
  ar: { title: "معلومات عنوان IP", short: "صنّف عنوان IPv4 أو IPv6 (خاص، loopback، multicast، …).", description: "مصنّف عناوين IP مجاني. الصق عنوان IPv4 أو IPv6 لرؤية فئته classful وما إذا كان خاصًا أو loopback أو link-local أو multicast أو نطاق توثيق — مع ملاحظات RFC.", keywords: ["بحث فئة ip", "نطاق ip خاص", "معلومات عنوان ip", "تحقق rfc 1918", "فئة ipv4"], input: "عنوان IP", version: "الإصدار", classful: "فئة classful", flag: "العلامة", notes: "ملاحظات", privateRange: "خاص", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "توثيق" },
  ru: { title: "Информация об IP-адресе", short: "Классифицируйте IPv4 или IPv6 (частный, loopback, multicast, …).", description: "Бесплатный классификатор IP. Вставьте IPv4 или IPv6, чтобы увидеть его классовую (classful) принадлежность и является ли он частным, loopback, link-local, multicast или диапазоном документации — с примечаниями RFC.", keywords: ["поиск класса ip", "частный диапазон ip", "информация об ip", "проверка rfc 1918", "класс ipv4"], input: "IP-адрес", version: "Версия", classful: "Класс (classful)", flag: "Флаг", notes: "Примечания", privateRange: "Частный", loopback: "Loopback", linkLocal: "Link-local", multicast: "Multicast", documentation: "Документация" },
  zh: { title: "IP 地址信息", short: "分类 IPv4 或 IPv6 地址（私有、回环、组播 …）。", description: "免费的 IP 地址分类器。粘贴 IPv4 或 IPv6 以查看其有类（classful）类别，是否为私有、回环、链路本地、组播或文档范围——附带 RFC 备注。", keywords: ["ip 类别查询", "私有 ip 范围", "ip 地址信息", "rfc 1918 检查", "ipv4 类别"], input: "IP 地址", version: "版本", classful: "有类 类别", flag: "标志", notes: "备注", privateRange: "私有", loopback: "回环", linkLocal: "链路本地", multicast: "组播", documentation: "文档" },
  ja: { title: "IP アドレス情報", short: "IPv4 や IPv6 アドレスを分類（プライベート、loopback、マルチキャスト、…）。", description: "無料の IP アドレス分類器。IPv4 や IPv6 を貼り付けて、クラスフル クラス、プライベート、loopback、リンクローカル、マルチキャスト、ドキュメンテーション範囲かを確認——RFC ノート付き。", keywords: ["ip クラス 検索", "プライベート ip 範囲", "ip アドレス 情報", "rfc 1918 チェック", "ipv4 クラス"], input: "IP アドレス", version: "バージョン", classful: "クラスフル クラス", flag: "フラグ", notes: "ノート", privateRange: "プライベート", loopback: "Loopback", linkLocal: "リンクローカル", multicast: "マルチキャスト", documentation: "ドキュメント" },
  ko: { title: "IP 주소 정보", short: "IPv4 또는 IPv6 주소를 분류합니다(사설, 루프백, 멀티캐스트, …).", description: "무료 IP 주소 분류기. IPv4 또는 IPv6를 붙여넣으면 클래스풀(classful) 클래스, 사설/루프백/링크 로컬/멀티캐스트/문서 범위 여부를 RFC 노트와 함께 표시합니다.", keywords: ["ip 클래스 조회", "사설 ip 범위", "ip 주소 정보", "rfc 1918 확인", "ipv4 클래스"], input: "IP 주소", version: "버전", classful: "클래스풀 클래스", flag: "플래그", notes: "노트", privateRange: "사설", loopback: "루프백", linkLocal: "링크 로컬", multicast: "멀티캐스트", documentation: "문서" },
  hi: { title: "IP एड्रेस जानकारी", short: "IPv4 या IPv6 एड्रेस को वर्गीकृत करें (निजी, लूपबैक, मल्टीकास्ट, …)।", description: "मुफ्त IP एड्रेस वर्गीकरण। IPv4 या IPv6 पेस्ट करें ताकि उसकी क्लासफुल श्रेणी और यह निजी, लूपबैक, लिंक-लोकल, मल्टीकास्ट या डॉक्यूमेंटेशन रेंज है या नहीं देख सकें — RFC नोट्स के साथ।", keywords: ["ip क्लास खोज", "निजी ip रेंज", "ip एड्रेस जानकारी", "rfc 1918 जाँच", "ipv4 क्लास"], input: "IP एड्रेस", version: "संस्करण", classful: "क्लासफुल वर्ग", flag: "ध्वज", notes: "नोट्स", privateRange: "निजी", loopback: "लूपबैक", linkLocal: "लिंक-लोकल", multicast: "मल्टीकास्ट", documentation: "डॉक्यूमेंटेशन" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
