import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Number to Words", short: "Spell out any whole number in English words.", description: "Free number-to-words converter. Type any integer (positive or negative) and get it spelled out in English words — useful for cheques, contracts and learning. Handles values up to the sextillions.", keywords: ["number to words", "spell number", "write number in words", "number speller", "amount in words"], placeholder: "e.g. 1234567", invalid: "Enter a whole number.", note: "Output is in English." },
  nl: { title: "Nummer to Words", short: "Spell out any whole nummer in English words.", description: "Gratis nummer-to-words converteerer. Type any integer (positive or negative) and get it spelled out in English words — useful for cheques, contracts and learning. Handles values up to the sextillions.", keywords: ["nummer to words", "spell nummer", "write nummer in words", "nummer speller", "amount in words"], placeholder: "e.g. 1234567", invalid: "Enter a whole nummer.", note: "Output is in English." },

  pl: { title: "Liczba to Words", short: "Spell out any whole liczba in English words.", description: "Darmowy liczba-to-words konwerter. Typ any integer (positive or negative) and get it spelled out in English words — useful for cheques, contracts and learning. Handles values up to the sextillions.", keywords: ["liczba to words", "spell liczba", "write liczba in words", "liczba speller", "amount in words"], placeholder: "e.g. 1234567", invalid: "Enter a whole liczba.", note: "Output is in English." },
  pt: { title: "Number to Words", short: "Spell out any whole number em English words.", description: "Gratuito - number-para-words converter. Type any integer (positive ou negative) e get it spelled out em English words â useful para cheques, contracts e learning. Handles values up para the sextillions.", keywords: ["number to words", "spell number", "write number in words", "number speller", "amount in words"], placeholder: "e.g. 1234567", invalid: "Enter a whole number.", note: "Output is in English." },
  id: { title: "Number to Words", short: "Spell out any whole number in English words.", description: "Gratis - number-to-words converter. Type any integer (positive atau negative) dan get it spelled out in English words â useful for cheques, contracts dan learning. Handles values up to the sextillions.", keywords: ["number to words", "spell number", "write number in words", "number speller", "amount in words"], placeholder: "e.g. 1234567", invalid: "Enter a whole number.", note: "Output is in English." },

  tr: { title: "Sayıyı Kelimeye Çevir", short: "Herhangi bir tam sayıyı İngilizce kelimelerle yazın.", description: "Ücretsiz sayıdan kelimeye dönüştürücü. Herhangi bir tam sayı (pozitif veya negatif) yazın ve İngilizce kelimelerle yazılışını alın — çekler, sözleşmeler ve öğrenme için kullanışlı. Sekstilyonlara kadar değerleri işler.", keywords: ["sayıyı kelimeye çevir", "sayıyı yaz", "sayıyı kelimelerle yaz", "sayı yazımı", "tutarın yazısı"], placeholder: "örn. 1234567", invalid: "Bir tam sayı girin.", note: "Çıktı İngilizcedir." },
  de: { title: "Zahl in Worte", short: "Schreiben Sie jede ganze Zahl in englischen Worten aus.", description: "Kostenloser Zahl-in-Worte-Konverter. Geben Sie eine ganze Zahl (positiv oder negativ) ein und erhalten Sie sie in englischen Worten ausgeschrieben — nützlich für Schecks, Verträge und zum Lernen.", keywords: ["zahl in worte", "zahl ausschreiben", "zahl in wörtern", "zahlen ausschreiben", "betrag in worten"], placeholder: "z. B. 1234567", invalid: "Geben Sie eine ganze Zahl ein.", note: "Die Ausgabe ist auf Englisch." },
  fr: { title: "Nombre en Lettres", short: "Écrivez n'importe quel nombre entier en lettres anglaises.", description: "Convertisseur nombre-en-lettres gratuit. Saisissez un entier (positif ou négatif) et obtenez-le écrit en lettres anglaises — utile pour les chèques, contrats et l'apprentissage. Gère jusqu'aux trilliards.", keywords: ["nombre en lettres", "écrire un nombre", "nombre en toutes lettres", "montant en lettres"], placeholder: "ex. 1234567", invalid: "Saisissez un nombre entier.", note: "La sortie est en anglais." },
  es: { title: "Número a Palabras", short: "Escribe cualquier número entero en palabras en inglés.", description: "Conversor de número a palabras gratuito. Escribe un entero (positivo o negativo) y obtén su forma escrita en palabras en inglés — útil para cheques, contratos y aprendizaje. Maneja hasta los trillones.", keywords: ["número a palabras", "escribir número", "número en letras", "cantidad en letras"], placeholder: "p. ej. 1234567", invalid: "Introduce un número entero.", note: "La salida está en inglés." },
  it: { title: "Numero in Parole", short: "Scrivi qualsiasi numero intero in parole inglesi.", description: "Convertitore numero-in-parole gratuito. Digita un intero (positivo o negativo) e ottienilo scritto in parole inglesi — utile per assegni, contratti e apprendimento. Gestisce fino ai trilioni.", keywords: ["numero in parole", "scrivere un numero", "numero in lettere", "importo in lettere"], placeholder: "es. 1234567", invalid: "Inserisci un numero intero.", note: "L'output è in inglese." },
  ar: { title: "تحويل الأرقام إلى كلمات", short: "اكتب أي عدد صحيح بالكلمات الإنجليزية.", description: "محوّل أرقام إلى كلمات مجاني. اكتب أي عدد صحيح (موجب أو سالب) واحصل عليه مكتوبًا بالكلمات الإنجليزية — مفيد للشيكات والعقود والتعلّم.", keywords: ["الأرقام إلى كلمات", "كتابة العدد", "العدد بالكلمات", "المبلغ بالكلمات"], placeholder: "مثل 1234567", invalid: "أدخل عددًا صحيحًا.", note: "الإخراج باللغة الإنجليزية." },
  ru: { title: "Число Прописью", short: "Запишите любое целое число английскими словами.", description: "Бесплатный конвертер числа в слова. Введите целое число (положительное или отрицательное) и получите его прописью на английском — полезно для чеков, договоров и обучения. Обрабатывает значения до секстиллионов.", keywords: ["число прописью", "написать число словами", "число словами", "сумма прописью"], placeholder: "напр. 1234567", invalid: "Введите целое число.", note: "Вывод на английском языке." },
  zh: { title: "数字转英文单词", short: "用英文单词拼写任意整数。", description: "免费的数字转单词转换器。输入任意整数（正或负），即可获得其英文单词拼写——适用于支票、合同和学习。支持到百万兆（sextillion）级别。", keywords: ["数字转单词", "数字拼写", "数字转英文", "金额大写"], placeholder: "例如 1234567", invalid: "请输入整数。", note: "输出为英文。" },
  ja: { title: "数字を英単語に変換", short: "任意の整数を英語の単語で表記します。", description: "無料の数字→単語変換ツール。整数（正・負）を入力すると、英語の単語で表記されます。小切手・契約・学習に便利。10の24乗未満まで対応。", keywords: ["数字を単語に", "数字 スペル", "数字 英語 表記", "金額 英字"], placeholder: "例: 1234567", invalid: "整数を入力してください。", note: "出力は英語です。" },
  ko: { title: "숫자를 단어로", short: "임의의 정수를 영어 단어로 표기합니다.", description: "무료 숫자-단어 변환기. 정수(양수 또는 음수)를 입력하면 영어 단어로 표기됩니다 — 수표, 계약, 학습에 유용합니다. 섹스틸리언 미만까지 처리합니다.", keywords: ["숫자를 단어로", "숫자 철자", "숫자 영어 표기", "금액 영문"], placeholder: "예: 1234567", invalid: "정수를 입력하세요.", note: "출력은 영어입니다." },
  hi: { title: "संख्या को शब्दों में", short: "किसी भी पूर्णांक को अंग्रेज़ी शब्दों में लिखें।", description: "मुफ्त संख्या-से-शब्द कन्वर्टर। कोई भी पूर्णांक (धनात्मक या ऋणात्मक) टाइप करें और उसे अंग्रेज़ी शब्दों में लिखा पाएं — चेक, अनुबंध और सीखने के लिए उपयोगी।", keywords: ["संख्या को शब्दों में", "संख्या वर्तनी", "संख्या शब्दों में लिखें", "राशि शब्दों में"], placeholder: "जैसे 1234567", invalid: "एक पूर्णांक दर्ज करें।", note: "आउटपुट अंग्रेज़ी में है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
