import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Colorblind Simulator", short: "Preview an image as seen with red/green/blue colour blindness.", description: "Free colorblind simulator. Drop an image and see how it appears under protanopia, deuteranopia, tritanopia and full achromatopsia. Runs entirely in your browser via Canvas.", keywords: ["colorblind simulator", "color blindness preview", "protanopia simulator", "deuteranopia simulator", "tritanopia preview"], drop: "Drop an image here or click to choose", kind: "Type", protanopia: "Protanopia (no red)", deuteranopia: "Deuteranopia (no green)", tritanopia: "Tritanopia (no blue)", achromatopsia: "Achromatopsia (greyscale)", original: "Original", simulated: "Simulated", download: "Download" },
  pt: { title: "Colorblind Simulator", short: "Preview an image as seen com red/green/blue colour blindness.", description: "Gratuito - colorblind simulator. Drop an image e see how it appears under protanopia, deuteranopia, tritanopia e full achromatopsia. Runs entirely no seu navegador via Canvas.", keywords: ["colorblind simulator", "color blindness preview", "protanopia simulator", "deuteranopia simulator", "tritanopia preview"], drop: "Drop an image here or click to choose", kind: "Type", protanopia: "Protanopia (no red)", deuteranopia: "Deuteranopia (no green)", tritanopia: "Tritanopia (no blue)", achromatopsia: "Achromatopsia (greyscale)", original: "Original", simulated: "Simulated", download: "Download" },
  id: { title: "Colorblind Simulator", short: "Preview an image as seen with red/green/blue colour blindness.", description: "Gratis - colorblind simulator. Drop an image dan see how it appears under protanopia, deuteranopia, tritanopia dan full achromatopsia. Runs entirely di browser Anda via Canvas.", keywords: ["colorblind simulator", "color blindness preview", "protanopia simulator", "deuteranopia simulator", "tritanopia preview"], drop: "Drop an image here or click to choose", kind: "Type", protanopia: "Protanopia (no red)", deuteranopia: "Deuteranopia (no green)", tritanopia: "Tritanopia (no blue)", achromatopsia: "Achromatopsia (greyscale)", original: "Original", simulated: "Simulated", download: "Download" },

  tr: { title: "Renk Körlüğü Simülatörü", short: "Bir görseli kırmızı/yeşil/mavi renk körlüğü ile görüldüğü gibi önizleyin.", description: "Ücretsiz renk körlüğü simülatörü. Bir görsel bırakın ve protanopi, döteranopi, tritanopi ve tam akromatopsi altında nasıl göründüğünü görün. Tamamen tarayıcınızda Canvas ile çalışır.", keywords: ["renk körlüğü simülatörü", "renk körlüğü önizleme", "protanopi simülatörü", "döteranopi simülatörü", "tritanopi önizleme"], drop: "Bir görsel bırakın veya seçmek için tıklayın", kind: "Tür", protanopia: "Protanopi (kırmızı yok)", deuteranopia: "Döteranopi (yeşil yok)", tritanopia: "Tritanopi (mavi yok)", achromatopsia: "Akromatopsi (gri tonlamalı)", original: "Orijinal", simulated: "Simüle edilmiş", download: "İndir" },
  de: { title: "Farbenblindheits-Simulator", short: "Vorschau eines Bildes mit rot/grün/blau Farbenblindheit.", description: "Kostenloser Farbenblindheits-Simulator. Legen Sie ein Bild ab und sehen Sie, wie es unter Protanopie, Deuteranopie, Tritanopie und vollständiger Achromatopsie erscheint. Läuft vollständig im Browser über Canvas.", keywords: ["farbenblindheits simulator", "farbenblindheit vorschau", "protanopie simulator", "deuteranopie simulator", "tritanopie vorschau"], drop: "Bild hier ablegen oder klicken zum Auswählen", kind: "Typ", protanopia: "Protanopie (kein Rot)", deuteranopia: "Deuteranopie (kein Grün)", tritanopia: "Tritanopie (kein Blau)", achromatopsia: "Achromatopsie (Graustufen)", original: "Original", simulated: "Simuliert", download: "Herunterladen" },
  fr: { title: "Simulateur de Daltonisme", short: "Aperçu d'une image vue avec un daltonisme rouge/vert/bleu.", description: "Simulateur de daltonisme gratuit. Déposez une image et voyez comment elle apparaît avec protanopie, deutéranopie, tritanopie et achromatopsie totale. Fonctionne entièrement dans votre navigateur via Canvas.", keywords: ["simulateur daltonisme", "aperçu daltonisme", "simulateur protanopie", "simulateur deutéranopie", "aperçu tritanopie"], drop: "Déposez une image ici ou cliquez pour choisir", kind: "Type", protanopia: "Protanopie (pas de rouge)", deuteranopia: "Deutéranopie (pas de vert)", tritanopia: "Tritanopie (pas de bleu)", achromatopsia: "Achromatopsie (niveaux de gris)", original: "Original", simulated: "Simulé", download: "Télécharger" },
  es: { title: "Simulador de Daltonismo", short: "Previsualiza una imagen vista con daltonismo rojo/verde/azul.", description: "Simulador de daltonismo gratuito. Arrastra una imagen y mira cómo se ve con protanopía, deuteranopía, tritanopía y acromatopsia total. Funciona completamente en tu navegador con Canvas.", keywords: ["simulador daltonismo", "vista previa daltonismo", "simulador protanopía", "simulador deuteranopía", "vista previa tritanopía"], drop: "Arrastra una imagen aquí o haz clic para elegir", kind: "Tipo", protanopia: "Protanopía (sin rojo)", deuteranopia: "Deuteranopía (sin verde)", tritanopia: "Tritanopía (sin azul)", achromatopsia: "Acromatopsia (escala de grises)", original: "Original", simulated: "Simulado", download: "Descargar" },
  it: { title: "Simulatore di Daltonismo", short: "Anteprima di un'immagine vista con daltonismo rosso/verde/blu.", description: "Simulatore di daltonismo gratuito. Trascina un'immagine e vedi come appare con protanopia, deuteranopia, tritanopia e acromatopsia completa. Funziona interamente nel browser tramite Canvas.", keywords: ["simulatore daltonismo", "anteprima daltonismo", "simulatore protanopia", "simulatore deuteranopia", "anteprima tritanopia"], drop: "Trascina un'immagine qui o clicca per scegliere", kind: "Tipo", protanopia: "Protanopia (no rosso)", deuteranopia: "Deuteranopia (no verde)", tritanopia: "Tritanopia (no blu)", achromatopsia: "Acromatopsia (scala di grigi)", original: "Originale", simulated: "Simulato", download: "Scarica" },
  ar: { title: "محاكي عمى الألوان", short: "عاين صورة كما تُرى مع عمى الألوان الأحمر/الأخضر/الأزرق.", description: "محاكي عمى ألوان مجاني. أفلِت صورة وشاهد كيف تظهر تحت أنواع protanopia و deuteranopia و tritanopia و achromatopsia الكاملة. يعمل بالكامل في متصفحك عبر Canvas.", keywords: ["محاكي عمى الألوان", "معاينة عمى الألوان", "محاكي protanopia", "محاكي deuteranopia", "معاينة tritanopia"], drop: "أفلِت صورة هنا أو انقر للاختيار", kind: "النوع", protanopia: "Protanopia (لا أحمر)", deuteranopia: "Deuteranopia (لا أخضر)", tritanopia: "Tritanopia (لا أزرق)", achromatopsia: "Achromatopsia (تدرج رمادي)", original: "الأصلي", simulated: "محاكى", download: "تنزيل" },
  ru: { title: "Симулятор дальтонизма", short: "Предпросмотр изображения с красным/зелёным/синим дальтонизмом.", description: "Бесплатный симулятор дальтонизма. Перетащите изображение и посмотрите, как оно выглядит при протанопии, дейтеранопии, тританопии и полной ахроматопсии. Работает полностью в браузере через Canvas.", keywords: ["симулятор дальтонизма", "превью дальтонизма", "симулятор протанопии", "симулятор дейтеранопии", "превью тританопии"], drop: "Перетащите изображение сюда или нажмите для выбора", kind: "Тип", protanopia: "Протанопия (без красного)", deuteranopia: "Дейтеранопия (без зелёного)", tritanopia: "Тританопия (без синего)", achromatopsia: "Ахроматопсия (оттенки серого)", original: "Оригинал", simulated: "Симуляция", download: "Скачать" },
  zh: { title: "色盲模拟器", short: "预览图片在红/绿/蓝色盲眼中的样子。", description: "免费的色盲模拟器。拖入图片，查看在红色盲（protanopia）、绿色盲（deuteranopia）、蓝色盲（tritanopia）和完全色盲（achromatopsia）下的效果。完全在浏览器中通过 Canvas 运行。", keywords: ["色盲模拟器", "色盲预览", "红色盲模拟器", "绿色盲模拟器", "蓝色盲预览"], drop: "将图片拖到此处或点击选择", kind: "类型", protanopia: "红色盲（无红）", deuteranopia: "绿色盲（无绿）", tritanopia: "蓝色盲（无蓝）", achromatopsia: "完全色盲（灰度）", original: "原始", simulated: "模拟", download: "下载" },
  ja: { title: "色覚多様性シミュレーター", short: "画像が赤/緑/青色覚異常でどう見えるかをプレビュー。", description: "無料の色覚多様性シミュレーター。画像をドロップして、第一色覚異常（protanopia）、第二色覚異常（deuteranopia）、第三色覚異常（tritanopia）、全色盲（achromatopsia）でどう見えるかを確認できます。Canvas によりすべてブラウザ内で動作。", keywords: ["色覚 シミュレーター", "色覚異常 プレビュー", "protanopia シミュレーター", "deuteranopia シミュレーター", "tritanopia プレビュー"], drop: "画像をここにドロップまたはクリックして選択", kind: "種類", protanopia: "Protanopia（赤なし）", deuteranopia: "Deuteranopia（緑なし）", tritanopia: "Tritanopia（青なし）", achromatopsia: "Achromatopsia（グレースケール）", original: "オリジナル", simulated: "シミュレート", download: "ダウンロード" },
  ko: { title: "색맹 시뮬레이터", short: "빨강/녹색/파랑 색맹의 시각으로 이미지를 미리 봅니다.", description: "무료 색맹 시뮬레이터. 이미지를 드롭하고 적색맹(protanopia), 녹색맹(deuteranopia), 청색맹(tritanopia), 완전색맹(achromatopsia)에서 어떻게 보이는지 확인하세요. Canvas를 통해 모두 브라우저에서 실행됩니다.", keywords: ["색맹 시뮬레이터", "색맹 미리보기", "protanopia 시뮬레이터", "deuteranopia 시뮬레이터", "tritanopia 미리보기"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", kind: "유형", protanopia: "Protanopia (빨강 없음)", deuteranopia: "Deuteranopia (녹색 없음)", tritanopia: "Tritanopia (파랑 없음)", achromatopsia: "Achromatopsia (회색조)", original: "원본", simulated: "시뮬레이션", download: "다운로드" },
  hi: { title: "रंग अंधता सिम्युलेटर", short: "एक इमेज को लाल/हरा/नीला रंग अंधता के साथ देखें।", description: "मुफ्त रंग अंधता सिम्युलेटर। एक इमेज छोड़ें और देखें कि यह protanopia, deuteranopia, tritanopia और पूर्ण achromatopsia के साथ कैसी दिखती है। Canvas के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["रंग अंधता सिम्युलेटर", "रंग अंधता प्रीव्यू", "protanopia सिम्युलेटर", "deuteranopia सिम्युलेटर", "tritanopia प्रीव्यू"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", kind: "प्रकार", protanopia: "Protanopia (लाल नहीं)", deuteranopia: "Deuteranopia (हरा नहीं)", tritanopia: "Tritanopia (नीला नहीं)", achromatopsia: "Achromatopsia (ग्रेस्केल)", original: "मूल", simulated: "सिम्युलेटेड", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
