import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Reverse Text", short: "Reverse text by characters, words or line order.", description: "Free reverse text tool. Flip any text backwards by characters, reverse the order of words, or reverse the order of lines. Runs entirely in your browser.", keywords: ["reverse text", "text reverser", "backwards text", "reverse string", "reverse words", "reverse lines"], placeholder: "Enter text to reverse…", characters: "Characters", words: "Words", lines: "Lines" },
  pt: { title: "Reverse Text", short: "Reverse text by characters, words ou line order.", description: "Gratuito - reverse text tool. Flip any text backwards by characters, reverse the order de words, ou reverse the order de lines. Runs entirely no seu navegador.", keywords: ["reverse text", "text reverser", "backwards text", "reverse string", "reverse words", "reverse lines"], placeholder: "Enter text to reverse…", characters: "Characters", words: "Words", lines: "Lines" },
  id: { title: "Reverse Text", short: "Reverse text by characters, words atau line order.", description: "Gratis - reverse text tool. Flip any text backwards by characters, reverse the order dari words, atau reverse the order dari lines. Runs entirely di browser Anda.", keywords: ["reverse text", "text reverser", "backwards text", "reverse string", "reverse words", "reverse lines"], placeholder: "Enter text to reverse…", characters: "Characters", words: "Words", lines: "Lines" },

  tr: { title: "Metni Ters Çevir", short: "Metni karaktere, kelimeye veya satır sırasına göre ters çevirin.", description: "Ücretsiz metin ters çevirme aracı. Herhangi bir metni karakter karakter tersine çevirin, kelime sırasını veya satır sırasını ters çevirin. Tamamen tarayıcınızda çalışır.", keywords: ["metni ters çevir", "metin ters çevirici", "tersten yazı", "string ters", "kelimeleri ters", "satırları ters"], placeholder: "Ters çevrilecek metni girin…", characters: "Karakter", words: "Kelime", lines: "Satır" },
  de: { title: "Text Umkehren", short: "Text nach Zeichen, Wörtern oder Zeilenreihenfolge umkehren.", description: "Kostenloses Tool zum Umkehren von Text. Drehen Sie beliebigen Text zeichenweise um, kehren Sie die Wort- oder Zeilenreihenfolge um. Läuft komplett im Browser.", keywords: ["text umkehren", "text rückwärts", "string umkehren", "wörter umkehren", "zeilen umkehren"], placeholder: "Text zum Umkehren eingeben…", characters: "Zeichen", words: "Wörter", lines: "Zeilen" },
  fr: { title: "Inverser le Texte", short: "Inversez le texte par caractères, mots ou ordre des lignes.", description: "Outil gratuit d'inversion de texte. Retournez n'importe quel texte caractère par caractère, inversez l'ordre des mots ou l'ordre des lignes. S'exécute dans votre navigateur.", keywords: ["inverser texte", "texte à l'envers", "inverser chaîne", "inverser mots", "inverser lignes"], placeholder: "Saisissez le texte à inverser…", characters: "Caractères", words: "Mots", lines: "Lignes" },
  es: { title: "Invertir Texto", short: "Invierte texto por caracteres, palabras u orden de líneas.", description: "Herramienta gratuita para invertir texto. Da la vuelta a cualquier texto carácter por carácter, invierte el orden de las palabras o el orden de las líneas. Se ejecuta en tu navegador.", keywords: ["invertir texto", "texto al revés", "invertir cadena", "invertir palabras", "invertir líneas"], placeholder: "Introduce el texto a invertir…", characters: "Caracteres", words: "Palabras", lines: "Líneas" },
  it: { title: "Inverti Testo", short: "Inverti il testo per caratteri, parole o ordine delle righe.", description: "Strumento gratuito per invertire il testo. Capovolgi qualsiasi testo carattere per carattere, inverti l'ordine delle parole o delle righe. Funziona nel browser.", keywords: ["inverti testo", "testo al contrario", "inverti stringa", "inverti parole", "inverti righe"], placeholder: "Inserisci il testo da invertire…", characters: "Caratteri", words: "Parole", lines: "Righe" },
  ar: { title: "عكس النص", short: "اعكس النص حسب الأحرف أو الكلمات أو ترتيب الأسطر.", description: "أداة مجانية لعكس النص. اقلب أي نص حرفًا بحرف، أو اعكس ترتيب الكلمات أو الأسطر. تعمل بالكامل في متصفحك.", keywords: ["عكس النص", "نص معكوس", "عكس السلسلة", "عكس الكلمات", "عكس الأسطر"], placeholder: "أدخل النص المراد عكسه…", characters: "أحرف", words: "كلمات", lines: "أسطر" },
  ru: { title: "Реверс Текста", short: "Переворачивайте текст по символам, словам или порядку строк.", description: "Бесплатный инструмент реверса текста. Переверните любой текст посимвольно, измените порядок слов или строк. Работает целиком в браузере.", keywords: ["реверс текста", "текст наоборот", "перевернуть строку", "реверс слов", "реверс строк"], placeholder: "Введите текст для реверса…", characters: "Символы", words: "Слова", lines: "Строки" },
  zh: { title: "文本反转", short: "按字符、单词或行序反转文本。", description: "免费的文本反转工具。将任意文本逐字符反转、反转单词顺序或反转行顺序。完全在浏览器中运行。", keywords: ["文本反转", "反转文字", "字符串反转", "反转单词", "反转行"], placeholder: "输入要反转的文本…", characters: "字符", words: "单词", lines: "行" },
  ja: { title: "テキスト反転", short: "テキストを文字単位、単語単位、行単位で反転します。", description: "無料のテキスト反転ツール。任意のテキストを文字ごとに反転、単語の順序を反転、行の順序を反転できます。すべてブラウザ内で動作します。", keywords: ["テキスト反転", "逆さ文字", "文字列反転", "単語反転", "行反転"], placeholder: "反転するテキストを入力…", characters: "文字", words: "単語", lines: "行" },
  ko: { title: "텍스트 뒤집기", short: "문자, 단어 또는 줄 순서로 텍스트를 뒤집습니다.", description: "무료 텍스트 뒤집기 도구. 모든 텍스트를 문자 단위로 뒤집거나 단어 순서, 줄 순서를 뒤집습니다. 모든 것이 브라우저에서 실행됩니다.", keywords: ["텍스트 뒤집기", "거꾸로 텍스트", "문자열 뒤집기", "단어 뒤집기", "줄 뒤집기"], placeholder: "뒤집을 텍스트 입력…", characters: "문자", words: "단어", lines: "줄" },
  hi: { title: "टेक्स्ट उलटें", short: "टेक्स्ट को वर्ण, शब्द या पंक्ति क्रम से उलटें।", description: "मुफ्त टेक्स्ट उलटने का टूल। किसी भी टेक्स्ट को वर्ण-दर-वर्ण उलटें, शब्दों का क्रम या पंक्तियों का क्रम उलटें। पूरी तरह ब्राउज़र में चलता है।", keywords: ["टेक्स्ट उलटें", "उल्टा टेक्स्ट", "स्ट्रिंग उलटें", "शब्द उलटें", "पंक्तियाँ उलटें"], placeholder: "उलटने के लिए टेक्स्ट दर्ज करें…", characters: "वर्ण", words: "शब्द", lines: "पंक्तियाँ" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
