import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Subnet / CIDR Calculator", short: "Calculate IPv4 subnet details from a CIDR notation.", description: "Free IPv4 subnet calculator. Enter a CIDR like 192.168.1.0/24 to see the network address, broadcast, first and last usable host, netmask, wildcard mask and total / usable host counts — all in your browser.", keywords: ["subnet calculator", "cidr calculator", "ipv4 subnet calculator", "network calculator", "ip range calculator"], input: "CIDR (e.g. 192.168.1.0/24)", network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", netmask: "Netmask", wildcard: "Wildcard mask", totalHosts: "Total addresses", usableHosts: "Usable hosts" },
  nl: { title: "Subnet / CIDR Calculator", short: "Bereken IPv4 subnet details from a CIDR notation.", description: "Gratis IPv4 subnet calculator. Enter a CIDR like 192.168.1.0/24 to see the network address, broadcast, first and last usable host, netmask, wildcard mask and total / usable host counts — all in uw browser.", keywords: ["subnet calculator", "cidr calculator", "ipv4 subnet calculator", "network calculator", "ip range calculator"], input: "CIDR (e.g. 192.168.1.0/24)", network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", netmask: "Netmask", wildcard: "Wildcard mask", totalHosts: "Total addresses", usableHosts: "Usable hosts" },

  pl: { title: "Podsieć / CIDR Kalkulator", short: "Oblicz IPv4 subnet details from a CIDR notation.", description: "Darmowy IPv4 subnet kalkulator. Enter a CIDR like 192.168.1.0/24 to see the network address, broadcast, first and last usable host, netmask, wildcard mask and total / usable host counts — all w Twojej przeglądarce.", keywords: ["subnet kalkulator", "cidr kalkulator", "ipv4 subnet kalkulator", "network kalkulator", "ip range kalkulator"], input: "CIDR (e.g. 192.168.1.0/24)", network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", netmask: "Netmask", wildcard: "Wildcard mask", totalHosts: "Total addresses", usableHosts: "Usable hosts" },
  pt: { title: "Calculadora de Subnet / CIDR", short: "Calcular IPv4 subnet details a partir de a CIDR notation.", description: "Gratuito - IPv4 subnet calculator. Enter a CIDR like 192.168.1.0/24 para see the network address, broadcast, first e last usable host, netmask, wildcard mask e total / usable host counts â all no seu navegador.", keywords: ["subnet calculator", "cidr calculator", "ipv4 subnet calculator", "network calculator", "ip range calculator"], input: "CIDR (e.g. 192.168.1.0/24)", network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", netmask: "Netmask", wildcard: "Wildcard mask", totalHosts: "Total addresses", usableHosts: "Usable hosts" },
  id: { title: "Kalkulator Subnet / CIDR", short: "Hitung IPv4 subnet details from a CIDR notation.", description: "Gratis - IPv4 subnet calculator. Enter a CIDR like 192.168.1.0/24 to see the network address, broadcast, first dan last usable host, netmask, wildcard mask dan total / usable host counts â all di browser Anda.", keywords: ["subnet calculator", "cidr calculator", "ipv4 subnet calculator", "network calculator", "ip range calculator"], input: "CIDR (e.g. 192.168.1.0/24)", network: "Network address", broadcast: "Broadcast address", firstHost: "First usable host", lastHost: "Last usable host", netmask: "Netmask", wildcard: "Wildcard mask", totalHosts: "Total addresses", usableHosts: "Usable hosts" },

  tr: { title: "Subnet / CIDR Hesaplayıcı", short: "Bir CIDR gösteriminden IPv4 subnet ayrıntılarını hesaplayın.", description: "Ücretsiz IPv4 subnet hesaplayıcı. 192.168.1.0/24 gibi bir CIDR girin ve ağ adresi, yayın, ilk ve son kullanılabilir host, ağ maskesi, joker maske ile toplam / kullanılabilir host sayısını görün — hepsi tarayıcınızda.", keywords: ["subnet hesaplayıcı", "cidr hesaplayıcı", "ipv4 subnet hesaplama", "ağ hesaplayıcı", "ip aralığı hesaplayıcı"], input: "CIDR (örn. 192.168.1.0/24)", network: "Ağ adresi", broadcast: "Yayın adresi", firstHost: "İlk kullanılabilir host", lastHost: "Son kullanılabilir host", netmask: "Ağ maskesi", wildcard: "Joker maske", totalHosts: "Toplam adres", usableHosts: "Kullanılabilir host" },
  de: { title: "Subnetz- / CIDR-Rechner", short: "Berechnen Sie IPv4-Subnetzdetails aus einer CIDR-Notation.", description: "Kostenloser IPv4-Subnetzrechner. Geben Sie eine CIDR wie 192.168.1.0/24 ein, um Netzwerkadresse, Broadcast, ersten und letzten nutzbaren Host, Netzmaske, Wildcard-Maske und Gesamt-/nutzbare Hostanzahl anzuzeigen — alles im Browser.", keywords: ["subnetz rechner", "cidr rechner", "ipv4 subnetz rechner", "netzwerk rechner", "ip bereich rechner"], input: "CIDR (z. B. 192.168.1.0/24)", network: "Netzwerkadresse", broadcast: "Broadcast-Adresse", firstHost: "Erster nutzbarer Host", lastHost: "Letzter nutzbarer Host", netmask: "Netzmaske", wildcard: "Wildcard-Maske", totalHosts: "Adressen gesamt", usableHosts: "Nutzbare Hosts" },
  fr: { title: "Calculateur de Sous-Réseau / CIDR", short: "Calculez les détails d'un sous-réseau IPv4 à partir d'une notation CIDR.", description: "Calculateur de sous-réseau IPv4 gratuit. Entrez un CIDR comme 192.168.1.0/24 pour voir l'adresse réseau, le broadcast, le premier et le dernier hôte utilisable, le masque, le masque générique et le nombre total / utilisable d'hôtes — le tout dans votre navigateur.", keywords: ["calculateur sous-réseau", "calculateur cidr", "calculateur sous-réseau ipv4", "calculateur réseau", "calculateur plage ip"], input: "CIDR (ex. 192.168.1.0/24)", network: "Adresse réseau", broadcast: "Adresse broadcast", firstHost: "Premier hôte utilisable", lastHost: "Dernier hôte utilisable", netmask: "Masque de réseau", wildcard: "Masque générique", totalHosts: "Adresses totales", usableHosts: "Hôtes utilisables" },
  es: { title: "Calculadora de Subred / CIDR", short: "Calcula los detalles de una subred IPv4 a partir de notación CIDR.", description: "Calculadora de subred IPv4 gratuita. Introduce un CIDR como 192.168.1.0/24 para ver la dirección de red, broadcast, primer y último host utilizable, máscara de red, máscara comodín y conteo total / utilizable de hosts — todo en tu navegador.", keywords: ["calculadora subred", "calculadora cidr", "calculadora subred ipv4", "calculadora red", "calculadora rango ip"], input: "CIDR (p. ej. 192.168.1.0/24)", network: "Dirección de red", broadcast: "Dirección broadcast", firstHost: "Primer host utilizable", lastHost: "Último host utilizable", netmask: "Máscara de red", wildcard: "Máscara comodín", totalHosts: "Direcciones totales", usableHosts: "Hosts utilizables" },
  it: { title: "Calcolatore di Subnet / CIDR", short: "Calcola i dettagli di una subnet IPv4 da una notazione CIDR.", description: "Calcolatore di subnet IPv4 gratuito. Inserisci un CIDR come 192.168.1.0/24 per vedere indirizzo di rete, broadcast, primo e ultimo host utilizzabile, maschera di rete, maschera wildcard e conteggio totale / utilizzabile di host — tutto nel browser.", keywords: ["calcolatore subnet", "calcolatore cidr", "calcolatore subnet ipv4", "calcolatore rete", "calcolatore range ip"], input: "CIDR (es. 192.168.1.0/24)", network: "Indirizzo di rete", broadcast: "Indirizzo broadcast", firstHost: "Primo host utilizzabile", lastHost: "Ultimo host utilizzabile", netmask: "Maschera di rete", wildcard: "Maschera wildcard", totalHosts: "Indirizzi totali", usableHosts: "Host utilizzabili" },
  ar: { title: "حاسبة الشبكة الفرعية / CIDR", short: "احسب تفاصيل شبكة فرعية IPv4 من تدوين CIDR.", description: "حاسبة شبكة فرعية IPv4 مجانية. أدخل CIDR مثل 192.168.1.0/24 لرؤية عنوان الشبكة والبث وأول وآخر مضيف قابل للاستخدام وقناع الشبكة وقناع البدل وإجمالي/المضيفون القابلون للاستخدام — كل ذلك في متصفحك.", keywords: ["حاسبة شبكة فرعية", "حاسبة cidr", "حاسبة شبكة فرعية ipv4", "حاسبة الشبكة", "حاسبة نطاق ip"], input: "CIDR (مثال 192.168.1.0/24)", network: "عنوان الشبكة", broadcast: "عنوان البث", firstHost: "أول مضيف قابل للاستخدام", lastHost: "آخر مضيف قابل للاستخدام", netmask: "قناع الشبكة", wildcard: "قناع البدل", totalHosts: "إجمالي العناوين", usableHosts: "المضيفون القابلون للاستخدام" },
  ru: { title: "Калькулятор подсети / CIDR", short: "Вычисляйте параметры подсети IPv4 из нотации CIDR.", description: "Бесплатный калькулятор подсети IPv4. Введите CIDR вроде 192.168.1.0/24, чтобы увидеть сетевой адрес, широковещательный, первый и последний используемый хост, маску подсети, инверсную маску и общее / используемое число хостов — всё в браузере.", keywords: ["калькулятор подсети", "калькулятор cidr", "калькулятор подсети ipv4", "сетевой калькулятор", "калькулятор диапазона ip"], input: "CIDR (напр. 192.168.1.0/24)", network: "Сетевой адрес", broadcast: "Широковещательный", firstHost: "Первый используемый хост", lastHost: "Последний используемый хост", netmask: "Маска подсети", wildcard: "Инверсная маска", totalHosts: "Всего адресов", usableHosts: "Используемые хосты" },
  zh: { title: "子网 / CIDR 计算器", short: "从 CIDR 表示法计算 IPv4 子网详细信息。", description: "免费的 IPv4 子网计算器。输入 192.168.1.0/24 这样的 CIDR，查看网络地址、广播地址、首个和末个可用主机、子网掩码、通配符掩码以及总/可用主机数——全部在浏览器中完成。", keywords: ["子网计算器", "cidr 计算器", "ipv4 子网计算器", "网络计算器", "ip 范围计算器"], input: "CIDR（如 192.168.1.0/24）", network: "网络地址", broadcast: "广播地址", firstHost: "首个可用主机", lastHost: "末个可用主机", netmask: "子网掩码", wildcard: "通配符掩码", totalHosts: "地址总数", usableHosts: "可用主机数" },
  ja: { title: "サブネット / CIDR 計算機", short: "CIDR 表記から IPv4 サブネットの詳細を計算。", description: "無料の IPv4 サブネット計算機。192.168.1.0/24 のような CIDR を入力すると、ネットワークアドレス、ブロードキャスト、最初と最後の使用可能なホスト、サブネットマスク、ワイルドカードマスク、合計/使用可能ホスト数を表示します——すべてブラウザ内で。", keywords: ["サブネット 計算", "cidr 計算", "ipv4 サブネット", "ネットワーク 計算", "ip 範囲 計算"], input: "CIDR（例 192.168.1.0/24）", network: "ネットワークアドレス", broadcast: "ブロードキャスト", firstHost: "最初の使用可能ホスト", lastHost: "最後の使用可能ホスト", netmask: "サブネットマスク", wildcard: "ワイルドカードマスク", totalHosts: "アドレス総数", usableHosts: "使用可能ホスト" },
  ko: { title: "서브넷 / CIDR 계산기", short: "CIDR 표기에서 IPv4 서브넷 세부사항을 계산합니다.", description: "무료 IPv4 서브넷 계산기. 192.168.1.0/24 같은 CIDR을 입력하면 네트워크 주소, 브로드캐스트, 첫 번째와 마지막 사용 가능한 호스트, 서브넷 마스크, 와일드카드 마스크와 전체/사용 가능 호스트 수를 보여줍니다 — 모두 브라우저에서.", keywords: ["서브넷 계산기", "cidr 계산기", "ipv4 서브넷 계산기", "네트워크 계산기", "ip 범위 계산기"], input: "CIDR (예: 192.168.1.0/24)", network: "네트워크 주소", broadcast: "브로드캐스트 주소", firstHost: "첫 번째 사용 가능한 호스트", lastHost: "마지막 사용 가능한 호스트", netmask: "서브넷 마스크", wildcard: "와일드카드 마스크", totalHosts: "총 주소", usableHosts: "사용 가능 호스트" },
  hi: { title: "सबनेट / CIDR कैलकुलेटर", short: "CIDR नोटेशन से IPv4 सबनेट विवरण की गणना करें।", description: "मुफ्त IPv4 सबनेट कैलकुलेटर। 192.168.1.0/24 जैसा CIDR दर्ज करें और नेटवर्क पता, ब्रॉडकास्ट, पहला और अंतिम उपयोग योग्य होस्ट, नेटमास्क, वाइल्डकार्ड मास्क और कुल / उपयोग योग्य होस्ट संख्या देखें — सब आपके ब्राउज़र में।", keywords: ["सबनेट कैलकुलेटर", "cidr कैलकुलेटर", "ipv4 सबनेट कैलकुलेटर", "नेटवर्क कैलकुलेटर", "ip रेंज कैलकुलेटर"], input: "CIDR (उदा. 192.168.1.0/24)", network: "नेटवर्क पता", broadcast: "ब्रॉडकास्ट पता", firstHost: "पहला उपयोग योग्य होस्ट", lastHost: "अंतिम उपयोग योग्य होस्ट", netmask: "नेटमास्क", wildcard: "वाइल्डकार्ड मास्क", totalHosts: "कुल पते", usableHosts: "उपयोग योग्य होस्ट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
