import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Find and Replace", short: "Find and replace text, with case-insensitive and regex options.", description: "Free find-and-replace tool. Replace all occurrences of a word or pattern in your text, with optional case-insensitive matching and full regular-expression support. Runs in your browser.", keywords: ["find and replace", "search and replace", "replace text", "regex replace", "bulk find replace"], placeholder: "Paste your text here…", find: "Find", replaceWith: "Replace with", caseInsensitive: "Case-insensitive", regex: "Regular expression", matches: "matches", invalidRegex: "Invalid regular expression." },
  nl: { title: "Find and Replace", short: "Find and replace tekst, with case-insensitive and regex options.", description: "Gratis find-and-replace tool. Replace all occurrences of a word or pattern in your tekst, with optional case-insensitive matching and full regular-expression support. Runs in uw browser.", keywords: ["find and replace", "zoek and replace", "replace tekst", "regex replace", "bulk find replace"], placeholder: "Paste your tekst here…", find: "Find", replaceWith: "Replace with", caseInsensitive: "Hoofdletter-insensitive", regex: "Regular expression", matches: "matches", invalidRegex: "Invalid regular expression." },

  pl: { title: "Find and Replace", short: "Find and replace tekst, with case-insensitive and regex options.", description: "Darmowy find-and-replace narzędzie. Replace all occurrences of a word or pattern in your tekst, with optional case-insensitive matching and full regular-expression support. Runs w Twojej przeglądarce.", keywords: ["find and replace", "szukaj and replace", "replace tekst", "regex replace", "bulk find replace"], placeholder: "Paste your tekst here…", find: "Find", replaceWith: "Replace with", caseInsensitive: "Wielkość liter-insensitive", regex: "Regular expression", matches: "matches", invalidRegex: "Invalid regular expression." },
  pt: { title: "Find and Replace", short: "Find e replace text, com case-insensitive e regex options.", description: "Gratuito - find-e-replace tool. Replace all occurrences de a word ou pattern em seu text, com optional case-insensitive matching e full regular-expression support. Runs no seu navegador.", keywords: ["find and replace", "search and replace", "replace text", "regex replace", "bulk find replace"], placeholder: "Paste your text here…", find: "Find", replaceWith: "Replace with", caseInsensitive: "Case-insensitive", regex: "Regular expression", matches: "matches", invalidRegex: "Invalid regular expression." },
  id: { title: "Find and Replace", short: "Find dan replace text, with case-insensitive dan regex options.", description: "Gratis - find-dan-replace tool. Replace all occurrences dari a word atau pattern in Anda text, with optional case-insensitive matching dan full regular-expression support. Runs di browser Anda.", keywords: ["find and replace", "search and replace", "replace text", "regex replace", "bulk find replace"], placeholder: "Paste your text here…", find: "Find", replaceWith: "Replace with", caseInsensitive: "Case-insensitive", regex: "Regular expression", matches: "matches", invalidRegex: "Invalid regular expression." },

  tr: { title: "Bul ve Değiştir", short: "Büyük/küçük harf duyarsız ve regex seçenekleriyle metin bulup değiştirin.", description: "Ücretsiz bul-değiştir aracı. Metninizdeki bir kelimenin veya kalıbın tüm geçtiği yerleri değiştirin; isteğe bağlı büyük/küçük harf duyarsız eşleşme ve tam düzenli ifade desteğiyle. Tarayıcınızda çalışır.", keywords: ["bul ve değiştir", "ara ve değiştir", "metni değiştir", "regex değiştir", "toplu değiştir"], placeholder: "Metninizi buraya yapıştırın…", find: "Bul", replaceWith: "Şununla değiştir", caseInsensitive: "Büyük/küçük harf duyarsız", regex: "Düzenli ifade", matches: "eşleşme", invalidRegex: "Geçersiz düzenli ifade." },
  de: { title: "Suchen und Ersetzen", short: "Text suchen und ersetzen, mit Optionen für Groß-/Kleinschreibung und Regex.", description: "Kostenloses Suchen-und-Ersetzen-Tool. Ersetzen Sie alle Vorkommen eines Worts oder Musters in Ihrem Text, mit optionaler Groß-/Kleinschreibung-Ignorierung und voller Regex-Unterstützung.", keywords: ["suchen und ersetzen", "text ersetzen", "regex ersetzen", "massenersetzung"], placeholder: "Text hier einfügen…", find: "Suchen", replaceWith: "Ersetzen durch", caseInsensitive: "Groß-/Kleinschreibung ignorieren", regex: "Regulärer Ausdruck", matches: "Treffer", invalidRegex: "Ungültiger regulärer Ausdruck." },
  fr: { title: "Rechercher et Remplacer", short: "Recherchez et remplacez du texte, avec options insensible à la casse et regex.", description: "Outil de recherche-remplacement gratuit. Remplacez toutes les occurrences d'un mot ou d'un motif, avec correspondance insensible à la casse optionnelle et prise en charge complète des expressions régulières.", keywords: ["rechercher et remplacer", "remplacer texte", "regex remplacer", "remplacement en masse"], placeholder: "Collez votre texte ici…", find: "Rechercher", replaceWith: "Remplacer par", caseInsensitive: "Insensible à la casse", regex: "Expression régulière", matches: "correspondances", invalidRegex: "Expression régulière non valide." },
  es: { title: "Buscar y Reemplazar", short: "Busca y reemplaza texto, con opciones sin distinción de mayúsculas y regex.", description: "Herramienta gratuita de buscar y reemplazar. Reemplaza todas las apariciones de una palabra o patrón, con coincidencia opcional sin distinción de mayúsculas y soporte completo de expresiones regulares.", keywords: ["buscar y reemplazar", "reemplazar texto", "regex reemplazar", "reemplazo masivo"], placeholder: "Pega tu texto aquí…", find: "Buscar", replaceWith: "Reemplazar con", caseInsensitive: "Sin distinción de mayúsculas", regex: "Expresión regular", matches: "coincidencias", invalidRegex: "Expresión regular no válida." },
  it: { title: "Trova e Sostituisci", short: "Trova e sostituisci testo, con opzioni senza distinzione di maiuscole e regex.", description: "Strumento gratuito trova e sostituisci. Sostituisci tutte le occorrenze di una parola o di un pattern, con corrispondenza opzionale senza distinzione di maiuscole e pieno supporto delle espressioni regolari.", keywords: ["trova e sostituisci", "sostituisci testo", "regex sostituisci", "sostituzione di massa"], placeholder: "Incolla il tuo testo qui…", find: "Trova", replaceWith: "Sostituisci con", caseInsensitive: "Senza distinzione di maiuscole", regex: "Espressione regolare", matches: "corrispondenze", invalidRegex: "Espressione regolare non valida." },
  ar: { title: "بحث واستبدال", short: "ابحث واستبدل النص، مع خيارات عدم حساسية الأحرف والتعبيرات النمطية.", description: "أداة بحث واستبدال مجانية. استبدل كل تكرارات كلمة أو نمط في نصك، مع مطابقة اختيارية غير حساسة لحالة الأحرف ودعم كامل للتعبيرات النمطية. تعمل في متصفحك.", keywords: ["بحث واستبدال", "استبدال النص", "استبدال regex", "استبدال جماعي"], placeholder: "الصق نصك هنا…", find: "بحث", replaceWith: "استبدال بـ", caseInsensitive: "غير حساس لحالة الأحرف", regex: "تعبير نمطي", matches: "تطابقات", invalidRegex: "تعبير نمطي غير صالح." },
  ru: { title: "Найти и Заменить", short: "Находите и заменяйте текст, с опциями без учёта регистра и regex.", description: "Бесплатный инструмент «найти и заменить». Замените все вхождения слова или шаблона в тексте, с необязательным поиском без учёта регистра и полной поддержкой регулярных выражений.", keywords: ["найти и заменить", "заменить текст", "regex замена", "массовая замена"], placeholder: "Вставьте текст сюда…", find: "Найти", replaceWith: "Заменить на", caseInsensitive: "Без учёта регистра", regex: "Регулярное выражение", matches: "совпадений", invalidRegex: "Недопустимое регулярное выражение." },
  zh: { title: "查找和替换", short: "查找并替换文本，支持不区分大小写和正则选项。", description: "免费的查找替换工具。替换文本中某个词或模式的所有出现，可选不区分大小写匹配并完整支持正则表达式。在浏览器中运行。", keywords: ["查找和替换", "替换文本", "正则替换", "批量替换"], placeholder: "在此粘贴你的文本…", find: "查找", replaceWith: "替换为", caseInsensitive: "不区分大小写", regex: "正则表达式", matches: "处匹配", invalidRegex: "无效的正则表达式。" },
  ja: { title: "検索と置換", short: "大文字小文字を無視・正規表現のオプション付きでテキストを検索・置換します。", description: "無料の検索・置換ツール。テキスト内の単語やパターンのすべての出現を置換します。大文字小文字を無視するマッチングや完全な正規表現サポート（オプション）。ブラウザ内で動作します。", keywords: ["検索と置換", "テキスト置換", "正規表現 置換", "一括置換"], placeholder: "ここにテキストを貼り付け…", find: "検索", replaceWith: "置換後", caseInsensitive: "大文字小文字を無視", regex: "正規表現", matches: "件一致", invalidRegex: "無効な正規表現です。" },
  ko: { title: "찾기 및 바꾸기", short: "대소문자 무시 및 정규식 옵션으로 텍스트를 찾아 바꿉니다.", description: "무료 찾기/바꾸기 도구. 텍스트에서 단어나 패턴의 모든 항목을 바꿉니다. 선택적 대소문자 무시 일치와 완전한 정규식 지원. 브라우저에서 실행됩니다.", keywords: ["찾기 및 바꾸기", "텍스트 바꾸기", "정규식 바꾸기", "일괄 바꾸기"], placeholder: "여기에 텍스트를 붙여넣으세요…", find: "찾기", replaceWith: "바꿀 내용", caseInsensitive: "대소문자 무시", regex: "정규식", matches: "개 일치", invalidRegex: "잘못된 정규식입니다." },
  hi: { title: "खोजें और बदलें", short: "केस-असंवेदनशील और regex विकल्पों के साथ टेक्स्ट खोजें और बदलें।", description: "मुफ्त खोज-बदलें टूल। अपने टेक्स्ट में किसी शब्द या पैटर्न की सभी घटनाओं को बदलें, वैकल्पिक केस-असंवेदनशील मिलान और पूर्ण रेगुलर एक्सप्रेशन समर्थन के साथ। ब्राउज़र में चलता है।", keywords: ["खोजें और बदलें", "टेक्स्ट बदलें", "regex बदलें", "बल्क बदलें"], placeholder: "अपना टेक्स्ट यहाँ पेस्ट करें…", find: "खोजें", replaceWith: "इससे बदलें", caseInsensitive: "केस-असंवेदनशील", regex: "रेगुलर एक्सप्रेशन", matches: "मिलान", invalidRegex: "अमान्य रेगुलर एक्सप्रेशन।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
