import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Reverse Image Search", short: "Search Google, Bing, Yandex and TinEye by a public image URL.", description: "Free reverse image search by URL. Paste a public image link and open the search on Google Lens, Bing, Yandex and TinEye in one click to find the source or similar images. Runs in your browser.", keywords: ["reverse image search", "search by image url", "find image source", "google lens by url", "tineye yandex search"], imageUrl: "Image URL", placeholder: "https://example.com/photo.jpg", urlNote: "Only public image URLs work. Searching by an uploaded file isn't possible from this page — upload directly on each engine instead.", previewAlt: "Image preview" },
  nl: { title: "Reverse Afbeelding Zoek", short: "Zoek Google, Bing, Yandex and TinEye by a public afbeelding URL.", description: "Gratis reverse afbeelding zoek by URL. Paste a public afbeelding link and open the zoek on Google Lens, Bing, Yandex and TinEye in one click to find the source or similar afbeeldings. Runs in uw browser.", keywords: ["reverse afbeelding zoek", "zoek by afbeelding url", "find afbeelding source", "google lens by url", "tineye yandex zoek"], imageUrl: "Afbeelding URL", placeholder: "https://example.com/photo.jpg", urlNote: "Only public afbeelding URLs work. Zoeking by an uploaded file isn't possible from this page — upload directly on each engine instead.", previewAlt: "Afbeelding voorbeeld" },

  pl: { title: "Reverse Obraz Szukaj", short: "Szukaj Google, Bing, Yandex and TinEye by a public obraz URL.", description: "Darmowy reverse obraz szukaj by URL. Paste a public obraz link and open the szukaj on Google Lens, Bing, Yandex and TinEye in one click to find the source or similar obrazs. Runs w Twojej przeglądarce.", keywords: ["reverse obraz szukaj", "szukaj by obraz url", "find obraz source", "google lens by url", "tineye yandex szukaj"], imageUrl: "Obraz URL", placeholder: "https://example.com/photo.jpg", urlNote: "Only public obraz URLs work. Szukajing by an uploaded file isn't possible from this page — upload directly on each engine instead.", previewAlt: "Obraz podgląd" },
  pt: { title: "Reverse Image Search", short: "Search Google, Bing, Yandex e TinEye por a public image URL.", description: "Gratuito - reverse image search by URL. Paste a public image link e open the search no Google Lens, Bing, Yandex e TinEye em one click para find the source ou similar images. Runs no seu navegador.", keywords: ["reverse image search", "search by image url", "find image source", "google lens by url", "tineye yandex search"], imageUrl: "URL da imagem", placeholder: "https://example.com/photo.jpg", urlNote: "Apenas URLs de imagens públicas funcionam. Pesquisar por um arquivo enviado não é possível nesta página — envie diretamente em cada mecanismo.", previewAlt: "Pré-visualização da imagem" },
  id: { title: "Reverse Image Search", short: "Search Google, Bing, Yandex dan TinEye dengan a public image URL.", description: "Gratis - reverse image search by URL. Paste a public image link dan open the search di Google Lens, Bing, Yandex dan TinEye dalam one click untuk find the source atau similar images. Runs di browser Anda.", keywords: ["reverse image search", "search by image url", "find image source", "google lens by url", "tineye yandex search"], imageUrl: "URL gambar", placeholder: "https://example.com/photo.jpg", urlNote: "Hanya URL gambar publik yang berfungsi. Mencari dengan file yang diunggah tidak mungkin dari halaman ini — unggah langsung di setiap mesin.", previewAlt: "Pratinjau gambar" },

  tr: { title: "Tersine Görsel Arama", short: "Genel bir görsel URL'siyle Google, Bing, Yandex ve TinEye'de arayın.", description: "Ücretsiz URL ile tersine görsel arama. Genel bir görsel bağlantısı yapıştırın ve kaynağı veya benzer görselleri bulmak için aramayı tek tıklamayla Google Lens, Bing, Yandex ve TinEye'de açın. Tarayıcınızda çalışır.", keywords: ["tersine görsel arama", "görsel url ile arama", "görsel kaynağını bul", "url ile google lens", "tineye yandex arama"], imageUrl: "Görsel URL'si", placeholder: "https://example.com/photo.jpg", urlNote: "Yalnızca genel görsel URL'leri çalışır. Bu sayfadan yüklenen bir dosyayla arama yapmak mümkün değildir — bunun yerine doğrudan her motora yükleyin.", previewAlt: "Görsel önizlemesi" },
  de: { title: "Umgekehrte Bildersuche", short: "Suchen Sie über eine öffentliche Bild-URL bei Google, Bing, Yandex und TinEye.", description: "Kostenlose umgekehrte Bildersuche per URL. Fügen Sie einen öffentlichen Bildlink ein und öffnen Sie die Suche mit einem Klick bei Google Lens, Bing, Yandex und TinEye, um die Quelle oder ähnliche Bilder zu finden. Läuft in Ihrem Browser.", keywords: ["umgekehrte bildersuche", "suche per bild url", "bildquelle finden", "google lens per url", "tineye yandex suche"], imageUrl: "Bild-URL", placeholder: "https://example.com/photo.jpg", urlNote: "Nur öffentliche Bild-URLs funktionieren. Eine Suche per hochgeladener Datei ist von dieser Seite aus nicht möglich – laden Sie stattdessen direkt bei jeder Engine hoch.", previewAlt: "Bildvorschau" },
  fr: { title: "Recherche d'Image Inversée", short: "Recherchez sur Google, Bing, Yandex et TinEye via une URL d'image publique.", description: "Recherche d'image inversée gratuite par URL. Collez un lien d'image public et ouvrez la recherche en un clic sur Google Lens, Bing, Yandex et TinEye pour trouver la source ou des images similaires. Fonctionne dans votre navigateur.", keywords: ["recherche image inversée", "recherche par url image", "trouver source image", "google lens par url", "recherche tineye yandex"], imageUrl: "URL de l'image", placeholder: "https://example.com/photo.jpg", urlNote: "Seules les URL d'images publiques fonctionnent. La recherche par fichier téléversé n'est pas possible depuis cette page — téléversez directement sur chaque moteur.", previewAlt: "Aperçu de l'image" },
  es: { title: "Búsqueda Inversa de Imágenes", short: "Busca en Google, Bing, Yandex y TinEye con una URL de imagen pública.", description: "Búsqueda inversa de imágenes gratuita por URL. Pega un enlace de imagen público y abre la búsqueda con un clic en Google Lens, Bing, Yandex y TinEye para encontrar la fuente o imágenes similares. Funciona en tu navegador.", keywords: ["búsqueda inversa de imágenes", "buscar por url de imagen", "encontrar fuente de imagen", "google lens por url", "búsqueda tineye yandex"], imageUrl: "URL de la imagen", placeholder: "https://example.com/photo.jpg", urlNote: "Solo funcionan las URL de imágenes públicas. Buscar por un archivo subido no es posible desde esta página: sube directamente en cada motor.", previewAlt: "Vista previa de la imagen" },
  it: { title: "Ricerca Inversa di Immagini", short: "Cerca su Google, Bing, Yandex e TinEye con un URL di immagine pubblico.", description: "Ricerca inversa di immagini gratuita tramite URL. Incolla un link di immagine pubblico e apri la ricerca con un clic su Google Lens, Bing, Yandex e TinEye per trovare la fonte o immagini simili. Funziona nel tuo browser.", keywords: ["ricerca inversa immagini", "cerca per url immagine", "trova fonte immagine", "google lens tramite url", "ricerca tineye yandex"], imageUrl: "URL dell'immagine", placeholder: "https://example.com/photo.jpg", urlNote: "Funzionano solo gli URL di immagini pubbliche. La ricerca tramite file caricato non è possibile da questa pagina: carica direttamente su ciascun motore.", previewAlt: "Anteprima dell'immagine" },
  ar: { title: "بحث عكسي عن الصور", short: "ابحث في Google وBing وYandex وTinEye عبر رابط صورة عام.", description: "بحث عكسي مجاني عن الصور عبر الرابط. الصق رابط صورة عامًا وافتح البحث بنقرة واحدة على Google Lens وBing وYandex وTinEye للعثور على المصدر أو صور مشابهة. يعمل في متصفحك.", keywords: ["بحث عكسي عن الصور", "البحث عبر رابط الصورة", "العثور على مصدر الصورة", "google lens عبر الرابط", "بحث tineye yandex"], imageUrl: "رابط الصورة", placeholder: "https://example.com/photo.jpg", urlNote: "تعمل روابط الصور العامة فقط. البحث عبر ملف مرفوع غير ممكن من هذه الصفحة — ارفع الملف مباشرة في كل محرك.", previewAlt: "معاينة الصورة" },
  ru: { title: "Обратный Поиск по Картинке", short: "Ищите в Google, Bing, Yandex и TinEye по публичному URL изображения.", description: "Бесплатный обратный поиск по картинке через URL. Вставьте публичную ссылку на изображение и откройте поиск одним кликом в Google Lens, Bing, Yandex и TinEye, чтобы найти источник или похожие изображения. Работает в браузере.", keywords: ["обратный поиск по картинке", "поиск по url изображения", "найти источник изображения", "google lens по url", "поиск tineye yandex"], imageUrl: "URL изображения", placeholder: "https://example.com/photo.jpg", urlNote: "Работают только публичные URL изображений. Поиск по загруженному файлу с этой страницы невозможен — загружайте напрямую в каждой системе.", previewAlt: "Предпросмотр изображения" },
  zh: { title: "以图搜图", short: "通过公开图片 URL 在 Google、Bing、Yandex 和 TinEye 中搜索。", description: "免费的以图搜图（按 URL）。粘贴公开图片链接，一键在 Google Lens、Bing、Yandex 和 TinEye 中打开搜索，查找来源或相似图片。在浏览器中运行。", keywords: ["以图搜图", "按图片 url 搜索", "查找图片来源", "google lens 按 url", "tineye yandex 搜索"], imageUrl: "图片 URL", placeholder: "https://example.com/photo.jpg", urlNote: "仅公开图片 URL 有效。无法从此页面按上传的文件搜索——请直接在各搜索引擎上上传。", previewAlt: "图片预览" },
  ja: { title: "画像逆検索", short: "公開画像 URL で Google・Bing・Yandex・TinEye を検索します。", description: "無料の URL による画像逆検索。公開画像リンクを貼り付け、ワンクリックで Google Lens・Bing・Yandex・TinEye の検索を開き、出典や類似画像を探します。ブラウザ内で動作します。", keywords: ["画像逆検索", "画像 url で検索", "画像の出典を探す", "url で google lens", "tineye yandex 検索"], imageUrl: "画像 URL", placeholder: "https://example.com/photo.jpg", urlNote: "公開画像 URL のみ有効です。このページからアップロードしたファイルで検索することはできません——各エンジンで直接アップロードしてください。", previewAlt: "画像プレビュー" },
  ko: { title: "역방향 이미지 검색", short: "공개 이미지 URL로 Google, Bing, Yandex, TinEye를 검색합니다.", description: "URL로 하는 무료 역방향 이미지 검색. 공개 이미지 링크를 붙여넣고 클릭 한 번으로 Google Lens, Bing, Yandex, TinEye에서 검색을 열어 출처나 유사 이미지를 찾으세요. 브라우저에서 실행됩니다.", keywords: ["역방향 이미지 검색", "이미지 url로 검색", "이미지 출처 찾기", "url로 google lens", "tineye yandex 검색"], imageUrl: "이미지 URL", placeholder: "https://example.com/photo.jpg", urlNote: "공개 이미지 URL만 작동합니다. 이 페이지에서 업로드한 파일로 검색할 수는 없습니다 — 각 엔진에서 직접 업로드하세요.", previewAlt: "이미지 미리보기" },
  hi: { title: "रिवर्स इमेज सर्च", short: "सार्वजनिक इमेज URL से Google, Bing, Yandex और TinEye में खोजें।", description: "URL द्वारा मुफ्त रिवर्स इमेज सर्च। एक सार्वजनिक इमेज लिंक चिपकाएँ और स्रोत या समान इमेज खोजने के लिए एक क्लिक में Google Lens, Bing, Yandex और TinEye पर खोज खोलें। ब्राउज़र में चलता है।", keywords: ["रिवर्स इमेज सर्च", "इमेज url से खोजें", "इमेज स्रोत खोजें", "url से google lens", "tineye yandex खोज"], imageUrl: "इमेज URL", placeholder: "https://example.com/photo.jpg", urlNote: "केवल सार्वजनिक इमेज URL काम करते हैं। इस पेज से अपलोड की गई फ़ाइल द्वारा खोज संभव नहीं है — इसके बजाय प्रत्येक इंजन पर सीधे अपलोड करें।", previewAlt: "इमेज पूर्वावलोकन" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
