import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IBAN Generator (Test)", short: "Generate IBANs with valid checksums for testing.", description: "Free IBAN generator. Pick a country to get a structurally valid IBAN with the correct length and mod-97 check digits — for QA and testing only. These IBANs are NOT real bank accounts.", keywords: ["iban generator", "test iban", "fake iban", "generate iban", "iban validator test"], country: "Country", count: "Count", generate: "Generate", result: "Generated IBANs" },
  tr: { title: "IBAN Oluşturucu (Test)", short: "Test için geçerli sağlama toplamlarıyla IBAN'lar oluşturun.", description: "Ücretsiz IBAN oluşturucu. Bir ülke seçin ve doğru uzunluk ve mod-97 kontrol haneleriyle yapısal olarak geçerli bir IBAN alın — sadece QA ve test için. Bu IBAN'lar GERÇEK banka hesapları DEĞİLDİR.", keywords: ["iban oluşturucu", "test iban", "sahte iban", "iban oluştur", "iban doğrulayıcı test"], country: "Ülke", count: "Adet", generate: "Oluştur", result: "Oluşturulan IBAN'lar" },
  de: { title: "IBAN-Generator (Test)", short: "Erzeugen Sie IBANs mit gültigen Prüfsummen zum Testen.", description: "Kostenloser IBAN-Generator. Wählen Sie ein Land, um eine strukturell gültige IBAN mit korrekter Länge und mod-97-Prüfziffern zu erhalten — nur für QA und Tests. Diese IBANs sind KEINE echten Bankkonten.", keywords: ["iban generator", "test iban", "fake iban", "iban erzeugen", "iban validator test"], country: "Land", count: "Anzahl", generate: "Erzeugen", result: "Erzeugte IBANs" },
  fr: { title: "Générateur d'IBAN (Test)", short: "Générez des IBAN avec des sommes de contrôle valides pour les tests.", description: "Générateur d'IBAN gratuit. Choisissez un pays pour obtenir un IBAN structurellement valide avec la longueur et les chiffres de contrôle mod-97 corrects — pour QA et tests uniquement. Ces IBAN ne sont PAS de vrais comptes bancaires.", keywords: ["générateur iban", "test iban", "faux iban", "générer iban", "test validateur iban"], country: "Pays", count: "Nombre", generate: "Générer", result: "IBAN générés" },
  es: { title: "Generador de IBAN (Test)", short: "Genera IBANs con sumas de verificación válidas para pruebas.", description: "Generador de IBAN gratuito. Elige un país para obtener un IBAN estructuralmente válido con la longitud y dígitos de control mod-97 correctos — solo para QA y pruebas. Estos IBANs NO son cuentas bancarias reales.", keywords: ["generador iban", "test iban", "iban falso", "generar iban", "test validador iban"], country: "País", count: "Cantidad", generate: "Generar", result: "IBANs generados" },
  it: { title: "Generatore IBAN (Test)", short: "Genera IBAN con checksum validi per i test.", description: "Generatore IBAN gratuito. Scegli un paese per ottenere un IBAN strutturalmente valido con la lunghezza e le cifre di controllo mod-97 corrette — solo per QA e test. Questi IBAN NON sono conti bancari reali.", keywords: ["generatore iban", "test iban", "iban falso", "generare iban", "test validatore iban"], country: "Paese", count: "Quantità", generate: "Genera", result: "IBAN generati" },
  ar: { title: "مولّد IBAN (للاختبار)", short: "أنشئ IBAN بمجاميع تحقق صالحة للاختبار.", description: "مولّد IBAN مجاني. اختر بلدًا للحصول على IBAN صالح من الناحية الهيكلية بطول صحيح وأرقام تحقق mod-97 — للاختبار فقط. هذه ليست حسابات بنكية حقيقية.", keywords: ["مولد iban", "iban اختبار", "iban وهمي", "إنشاء iban", "اختبار iban"], country: "البلد", count: "العدد", generate: "توليد", result: "IBAN المُولَّدة" },
  ru: { title: "Генератор IBAN (Тест)", short: "Создавайте IBAN с валидными контрольными суммами для тестов.", description: "Бесплатный генератор IBAN. Выберите страну, чтобы получить структурно валидный IBAN правильной длины и с корректными mod-97 контрольными цифрами — только для QA и тестов. Это НЕ настоящие банковские счета.", keywords: ["генератор iban", "тестовый iban", "фейковый iban", "сгенерировать iban", "тест валидатора iban"], country: "Страна", count: "Количество", generate: "Создать", result: "Сгенерированные IBAN" },
  zh: { title: "IBAN 生成器（测试）", short: "生成具有有效校验和的 IBAN 用于测试。", description: "免费的 IBAN 生成器。选择国家以获得结构上有效的 IBAN，具有正确的长度和 mod-97 校验位——仅用于 QA 和测试。这些 IBAN 不是真实的银行账户。", keywords: ["iban 生成器", "测试 iban", "假 iban", "生成 iban", "iban 验证器测试"], country: "国家", count: "数量", generate: "生成", result: "生成的 IBAN" },
  ja: { title: "IBAN ジェネレーター（テスト）", short: "テスト用に有効なチェックサムを持つ IBAN を生成。", description: "無料の IBAN ジェネレーター。国を選んで、正しい長さと mod-97 チェック数字を持つ構造的に有効な IBAN を取得——QA とテスト専用。これらの IBAN は実際の銀行口座ではありません。", keywords: ["iban ジェネレーター", "テスト iban", "偽 iban", "iban 生成", "iban バリデーター テスト"], country: "国", count: "数", generate: "生成", result: "生成された IBAN" },
  ko: { title: "IBAN 생성기 (테스트)", short: "테스트용 유효한 체크섬을 가진 IBAN을 생성합니다.", description: "무료 IBAN 생성기. 국가를 선택하면 올바른 길이와 mod-97 검사 자릿수를 가진 구조적으로 유효한 IBAN을 얻습니다 — QA 및 테스트 전용. 이 IBAN은 실제 은행 계좌가 아닙니다.", keywords: ["iban 생성기", "테스트 iban", "가짜 iban", "iban 생성", "iban 검증기 테스트"], country: "국가", count: "개수", generate: "생성", result: "생성된 IBAN" },
  hi: { title: "IBAN जनरेटर (परीक्षण)", short: "परीक्षण के लिए मान्य चेकसम वाले IBAN बनाएं।", description: "मुफ्त IBAN जनरेटर। एक देश चुनें ताकि सही लंबाई और mod-97 चेक अंकों के साथ संरचनात्मक रूप से मान्य IBAN प्राप्त करें — केवल QA और परीक्षण के लिए। ये IBAN वास्तविक बैंक खाते नहीं हैं।", keywords: ["iban जनरेटर", "परीक्षण iban", "नकली iban", "iban जनरेट करें", "iban सत्यापक परीक्षण"], country: "देश", count: "संख्या", generate: "जनरेट करें", result: "जनरेट किए गए IBAN" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
