import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "PDF Watermark", short: "Stamp a text watermark on every page of a PDF.", description: "Free PDF watermark tool. Drop a PDF, set the text, font size, rotation, colour and opacity, then download a watermarked copy — runs entirely in your browser via pdf-lib. Nothing is uploaded.", keywords: ["pdf watermark", "watermark pdf", "stamp pdf", "draft watermark", "add watermark pdf"], drop: "Drop a PDF here or click to choose", text: "Watermark text", fontSize: "Font size", rotation: "Rotation", color: "Color", opacity: "Opacity", run: "Add watermark", download: "Download watermarked.pdf" },
  tr: { title: "PDF Filigran", short: "Bir PDF'in her sayfasına metin filigranı basın.", description: "Ücretsiz PDF filigran aracı. Bir PDF bırakın, metin, yazı tipi boyutu, döndürme, renk ve şeffaflık ayarlayın, ardından filigranlı kopyayı indirin — tamamen tarayıcınızda pdf-lib ile çalışır. Hiçbir şey yüklenmez.", keywords: ["pdf filigran", "pdf filigranı", "pdf damga", "taslak filigran", "pdf'e filigran ekle"], drop: "Bir PDF bırakın veya seçmek için tıklayın", text: "Filigran metni", fontSize: "Yazı boyutu", rotation: "Döndürme", color: "Renk", opacity: "Şeffaflık", run: "Filigran ekle", download: "watermarked.pdf indir" },
  de: { title: "PDF-Wasserzeichen", short: "Stempeln Sie ein Text-Wasserzeichen auf jede PDF-Seite.", description: "Kostenloses PDF-Wasserzeichen-Tool. Legen Sie eine PDF ab, stellen Sie Text, Schriftgröße, Rotation, Farbe und Deckkraft ein und laden Sie eine markierte Kopie herunter — läuft vollständig im Browser über pdf-lib. Nichts wird hochgeladen.", keywords: ["pdf wasserzeichen", "wasserzeichen pdf", "pdf stempel", "entwurf wasserzeichen", "pdf wasserzeichen hinzufügen"], drop: "PDF hier ablegen oder klicken zum Auswählen", text: "Wasserzeichentext", fontSize: "Schriftgröße", rotation: "Rotation", color: "Farbe", opacity: "Deckkraft", run: "Wasserzeichen hinzufügen", download: "watermarked.pdf herunterladen" },
  fr: { title: "Filigrane PDF", short: "Apposez un filigrane texte sur chaque page d'un PDF.", description: "Outil de filigrane PDF gratuit. Déposez un PDF, définissez le texte, la taille de police, la rotation, la couleur et l'opacité, puis téléchargez une copie filigranée — fonctionne entièrement dans votre navigateur via pdf-lib. Rien n'est envoyé.", keywords: ["filigrane pdf", "watermark pdf", "tampon pdf", "filigrane brouillon", "ajouter filigrane pdf"], drop: "Déposez un PDF ici ou cliquez pour choisir", text: "Texte du filigrane", fontSize: "Taille de police", rotation: "Rotation", color: "Couleur", opacity: "Opacité", run: "Ajouter le filigrane", download: "Télécharger watermarked.pdf" },
  es: { title: "Marca de Agua PDF", short: "Estampa una marca de agua de texto en cada página de un PDF.", description: "Herramienta gratuita de marca de agua PDF. Arrastra un PDF, establece el texto, tamaño de fuente, rotación, color y opacidad, luego descarga una copia con marca de agua — funciona completamente en tu navegador con pdf-lib. Nada se sube.", keywords: ["marca agua pdf", "watermark pdf", "sello pdf", "marca borrador", "añadir marca pdf"], drop: "Arrastra un PDF aquí o haz clic para elegir", text: "Texto marca agua", fontSize: "Tamaño fuente", rotation: "Rotación", color: "Color", opacity: "Opacidad", run: "Añadir marca", download: "Descargar watermarked.pdf" },
  it: { title: "Filigrana PDF", short: "Applica una filigrana di testo su ogni pagina di un PDF.", description: "Strumento di filigrana PDF gratuito. Trascina un PDF, imposta testo, dimensione font, rotazione, colore e opacità, quindi scarica una copia con filigrana — funziona interamente nel browser tramite pdf-lib. Nulla viene caricato.", keywords: ["filigrana pdf", "watermark pdf", "timbro pdf", "filigrana bozza", "aggiungere filigrana pdf"], drop: "Trascina un PDF qui o clicca per scegliere", text: "Testo filigrana", fontSize: "Dimensione font", rotation: "Rotazione", color: "Colore", opacity: "Opacità", run: "Aggiungi filigrana", download: "Scarica watermarked.pdf" },
  ar: { title: "علامة مائية لـ PDF", short: "اطبع علامة مائية نصية على كل صفحة من PDF.", description: "أداة علامة مائية PDF مجانية. أفلِت PDF، اضبط النص وحجم الخط والتدوير واللون والشفافية، ثم نزّل نسخة بعلامة مائية — يعمل بالكامل في متصفحك عبر pdf-lib. لا شيء يُرفع.", keywords: ["علامة مائية pdf", "ختم pdf", "pdf مسودة", "إضافة علامة مائية pdf", "علامة مائية pdf عبر الإنترنت"], drop: "أفلِت ملف PDF هنا أو انقر للاختيار", text: "نص العلامة المائية", fontSize: "حجم الخط", rotation: "التدوير", color: "اللون", opacity: "الشفافية", run: "إضافة علامة مائية", download: "تنزيل watermarked.pdf" },
  ru: { title: "Водяной знак PDF", short: "Нанесите текстовый водяной знак на каждую страницу PDF.", description: "Бесплатный инструмент водяного знака PDF. Перетащите PDF, задайте текст, размер шрифта, поворот, цвет и прозрачность, затем скачайте копию с водяным знаком — работает полностью в браузере через pdf-lib. Ничего не загружается.", keywords: ["водяной знак pdf", "watermark pdf", "штамп pdf", "черновой водяной знак", "добавить водяной знак pdf"], drop: "Перетащите PDF сюда или нажмите для выбора", text: "Текст водяного знака", fontSize: "Размер шрифта", rotation: "Поворот", color: "Цвет", opacity: "Непрозрачность", run: "Добавить водяной знак", download: "Скачать watermarked.pdf" },
  zh: { title: "PDF 水印", short: "在 PDF 的每一页上添加文字水印。", description: "免费的 PDF 水印工具。拖入 PDF，设置文字、字号、旋转、颜色和不透明度，然后下载带水印的副本——通过 pdf-lib 完全在浏览器中运行。不上传任何内容。", keywords: ["pdf 水印", "添加 pdf 水印", "pdf 印章", "草稿水印", "在线 pdf 水印"], drop: "将 PDF 拖到此处或点击选择", text: "水印文字", fontSize: "字号", rotation: "旋转", color: "颜色", opacity: "不透明度", run: "添加水印", download: "下载 watermarked.pdf" },
  ja: { title: "PDF 透かし", short: "PDF の各ページにテキスト透かしを押す。", description: "無料の PDF 透かしツール。PDF をドロップし、テキスト、フォントサイズ、回転、色、不透明度を設定して透かし入りのコピーをダウンロード——pdf-lib によりすべてブラウザ内で動作。何もアップロードされません。", keywords: ["pdf 透かし", "pdf ウォーターマーク", "pdf スタンプ", "下書き 透かし", "pdf に透かしを追加"], drop: "PDF をここにドロップまたはクリックして選択", text: "透かしテキスト", fontSize: "フォントサイズ", rotation: "回転", color: "色", opacity: "不透明度", run: "透かしを追加", download: "watermarked.pdf をダウンロード" },
  ko: { title: "PDF 워터마크", short: "PDF의 모든 페이지에 텍스트 워터마크를 찍습니다.", description: "무료 PDF 워터마크 도구. PDF를 드롭하고 텍스트, 글꼴 크기, 회전, 색상, 투명도를 설정한 다음 워터마크가 적용된 사본을 다운로드하세요 — pdf-lib를 통해 모두 브라우저에서 실행됩니다. 아무것도 업로드되지 않습니다.", keywords: ["pdf 워터마크", "pdf 워터마킹", "pdf 도장", "초안 워터마크", "pdf 워터마크 추가"], drop: "여기에 PDF를 드롭하거나 클릭하여 선택", text: "워터마크 텍스트", fontSize: "글꼴 크기", rotation: "회전", color: "색상", opacity: "투명도", run: "워터마크 추가", download: "watermarked.pdf 다운로드" },
  hi: { title: "PDF वॉटरमार्क", short: "PDF के हर पेज पर टेक्स्ट वॉटरमार्क लगाएं।", description: "मुफ्त PDF वॉटरमार्क टूल। एक PDF छोड़ें, टेक्स्ट, फ़ॉन्ट आकार, घूर्णन, रंग और अपारदर्शिता सेट करें, फिर वॉटरमार्क की हुई कॉपी डाउनलोड करें — pdf-lib के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है। कुछ भी अपलोड नहीं होता।", keywords: ["pdf वॉटरमार्क", "pdf पर वॉटरमार्क", "pdf स्टैम्प", "ड्राफ्ट वॉटरमार्क", "pdf में वॉटरमार्क जोड़ें"], drop: "यहाँ एक PDF छोड़ें या चुनने के लिए क्लिक करें", text: "वॉटरमार्क टेक्स्ट", fontSize: "फ़ॉन्ट आकार", rotation: "घूर्णन", color: "रंग", opacity: "अपारदर्शिता", run: "वॉटरमार्क जोड़ें", download: "watermarked.pdf डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
