import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "ULID Generator", short: "Generate ULIDs — sortable, time-based unique identifiers.", description: "Free ULID generator. Create Universally Unique Lexicographically Sortable Identifiers — 26-character Crockford Base32 IDs that sort by creation time. Generates in your browser using crypto-grade randomness.", keywords: ["ulid generator", "ulid", "sortable uuid", "lexicographic id", "crockford base32"], count: "Count", generate: "Generate", result: "Result" },
  tr: { title: "ULID Oluşturucu", short: "Sıralanabilir, zaman tabanlı benzersiz tanımlayıcılar olan ULID oluşturun.", description: "Ücretsiz ULID oluşturucu. Evrensel Benzersiz Sözlüksel Sıralanabilir Tanımlayıcılar — oluşturma zamanına göre sıralanan 26 karakterlik Crockford Base32 kimlikleri — oluşturun. Tarayıcınızda kripto sınıfı rastgelelikle oluşturulur.", keywords: ["ulid oluşturucu", "ulid", "sıralanabilir uuid", "sözlüksel kimlik", "crockford base32"], count: "Adet", generate: "Oluştur", result: "Sonuç" },
  de: { title: "ULID-Generator", short: "Erzeugen Sie ULIDs — sortierbare, zeitbasierte eindeutige Bezeichner.", description: "Kostenloser ULID-Generator. Erstellen Sie Universally Unique Lexicographically Sortable Identifiers — 26-stellige Crockford-Base32-IDs, die nach Erstellungszeit sortieren. Wird im Browser mit kryptographischer Zufälligkeit erzeugt.", keywords: ["ulid generator", "ulid", "sortierbare uuid", "lexikographische id", "crockford base32"], count: "Anzahl", generate: "Erzeugen", result: "Ergebnis" },
  fr: { title: "Générateur ULID", short: "Générez des ULID — identifiants uniques triables basés sur le temps.", description: "Générateur ULID gratuit. Créez des Universally Unique Lexicographically Sortable Identifiers — identifiants Crockford Base32 de 26 caractères qui se trient par heure de création. Généré dans votre navigateur avec un aléa de qualité cryptographique.", keywords: ["générateur ulid", "ulid", "uuid triable", "id lexicographique", "crockford base32"], count: "Nombre", generate: "Générer", result: "Résultat" },
  es: { title: "Generador ULID", short: "Genera ULIDs — identificadores únicos ordenables basados en tiempo.", description: "Generador ULID gratuito. Crea Universally Unique Lexicographically Sortable Identifiers — IDs Crockford Base32 de 26 caracteres que se ordenan por hora de creación. Se genera en tu navegador con aleatoriedad criptográfica.", keywords: ["generador ulid", "ulid", "uuid ordenable", "id lexicográfico", "crockford base32"], count: "Cantidad", generate: "Generar", result: "Resultado" },
  it: { title: "Generatore ULID", short: "Genera ULID — identificatori univoci ordinabili basati sul tempo.", description: "Generatore ULID gratuito. Crea Universally Unique Lexicographically Sortable Identifiers — ID Crockford Base32 di 26 caratteri che si ordinano per ora di creazione. Generato nel browser con casualità di qualità crittografica.", keywords: ["generatore ulid", "ulid", "uuid ordinabile", "id lessicografico", "crockford base32"], count: "Quantità", generate: "Genera", result: "Risultato" },
  ar: { title: "مولّد ULID", short: "أنشئ ULIDs — معرّفات فريدة قابلة للفرز قائمة على الوقت.", description: "مولّد ULID مجاني. أنشئ معرّفات فريدة عالمياً قابلة للفرز معجمياً — معرّفات Crockford Base32 من 26 حرفًا تُفرز حسب وقت الإنشاء. يتم التوليد في متصفحك بعشوائية بمستوى تشفيري.", keywords: ["مولد ulid", "ulid", "uuid قابل للفرز", "معرف معجمي", "crockford base32"], count: "العدد", generate: "توليد", result: "النتيجة" },
  ru: { title: "Генератор ULID", short: "Создавайте ULID — сортируемые, временные уникальные идентификаторы.", description: "Бесплатный генератор ULID. Создавайте универсально уникальные лексикографически сортируемые идентификаторы — 26-символьные Crockford Base32 ID, которые сортируются по времени создания. Генерируются в браузере с криптографической случайностью.", keywords: ["генератор ulid", "ulid", "сортируемый uuid", "лексикографический id", "crockford base32"], count: "Количество", generate: "Создать", result: "Результат" },
  zh: { title: "ULID 生成器", short: "生成基于时间且可排序的唯一标识符 ULID。", description: "免费的 ULID 生成器。创建通用唯一、按字典序可排序的标识符——26 个字符的 Crockford Base32 ID，按创建时间排序。在浏览器中使用加密级随机性生成。", keywords: ["ulid 生成器", "ulid", "可排序 uuid", "字典序 id", "crockford base32"], count: "数量", generate: "生成", result: "结果" },
  ja: { title: "ULID 生成", short: "並び替え可能な時刻ベースのユニーク識別子 ULID を生成。", description: "無料の ULID 生成ツール。世界的に一意で辞書順に並び替え可能な識別子——作成時刻でソートされる26文字の Crockford Base32 ID——を作成します。ブラウザ内で暗号級の乱数で生成されます。", keywords: ["ulid 生成", "ulid", "ソート可能 uuid", "辞書順 id", "crockford base32"], count: "数", generate: "生成", result: "結果" },
  ko: { title: "ULID 생성기", short: "정렬 가능한 시간 기반 고유 식별자 ULID를 생성합니다.", description: "무료 ULID 생성기. 보편적으로 고유하고 사전순으로 정렬 가능한 식별자 — 생성 시간 순으로 정렬되는 26자 Crockford Base32 ID — 를 만듭니다. 브라우저에서 암호화 수준의 난수로 생성됩니다.", keywords: ["ulid 생성기", "ulid", "정렬 가능한 uuid", "사전순 id", "crockford base32"], count: "개수", generate: "생성", result: "결과" },
  hi: { title: "ULID जनरेटर", short: "सॉर्ट करने योग्य, समय-आधारित अद्वितीय पहचानकर्ता ULID बनाएं।", description: "मुफ्त ULID जनरेटर। सार्वभौमिक रूप से अद्वितीय शब्दकोषीय रूप से सॉर्ट करने योग्य पहचानकर्ता बनाएं — निर्माण समय के अनुसार सॉर्ट होने वाले 26 अक्षरों के Crockford Base32 ID। आपके ब्राउज़र में क्रिप्टो-ग्रेड यादृच्छिकता के साथ जनरेट होते हैं।", keywords: ["ulid जनरेटर", "ulid", "सॉर्ट करने योग्य uuid", "शब्दकोषीय id", "crockford base32"], count: "संख्या", generate: "जनरेट करें", result: "परिणाम" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
