import type { CalculatorI18n } from "@/types/i18n";

const io = (fs: string, fu: string, sp: string, su: string, s: string, m: string, h: string) => ({
  inputs: { fileSize: { label: fs }, fileSizeUnit: { label: fu }, speed: { label: sp }, speedUnit: { label: su } },
  outputs: { seconds: { label: s }, minutes: { label: m }, hours: { label: h } },
  options: { fileSizeUnit: { MB: "MB", GB: "GB", TB: "TB" }, speedUnit: { Mbps: "Mbps", MBps: "MB/s", Gbps: "Gbps" } },
});

const i18n: CalculatorI18n = {
  en: { title: "Download Time Calculator", short: "Estimate how long a file takes to transfer at a given speed.", description: "Free download/transfer time calculator. Enter a file size and connection speed (Mbps, MB/s or Gbps) to estimate the time to download or upload it, in seconds, minutes and hours.", keywords: ["download time calculator", "data transfer time", "file transfer time", "upload time", "bandwidth calculator"], ...io("File size", "Size unit", "Connection speed", "Speed unit", "Time (seconds)", "Time (minutes)", "Time (hours)"), faq: [{ q: "How is download time calculated?", a: "Divide the file size in bits by the speed in bits per second. A 5 GB file over a 100 Mbps line takes about 400 seconds (≈6.7 minutes) at full speed." }, { q: "Why is my real download slower?", a: "Quoted speeds are maximums. Protocol overhead, latency, Wi-Fi, disk speed and network congestion all reduce real throughput." }] },
  tr: { title: "İndirme Süresi Hesaplayıcı", short: "Bir dosyanın belirli bir hızda ne kadar sürede aktarılacağını tahmin edin.", description: "Ücretsiz indirme/aktarma süresi hesaplayıcı. Dosya boyutu ve bağlantı hızını (Mbps, MB/s veya Gbps) girerek indirme veya yükleme süresini saniye, dakika ve saat olarak tahmin edin.", keywords: ["indirme süresi hesaplama", "veri aktarma süresi", "dosya aktarma süresi", "yükleme süresi", "bant genişliği hesaplama"], ...io("Dosya boyutu", "Boyut birimi", "Bağlantı hızı", "Hız birimi", "Süre (saniye)", "Süre (dakika)", "Süre (saat)"), faq: [{ q: "İndirme süresi nasıl hesaplanır?", a: "Dosya boyutunu bit cinsinden, hızı bit/sn cinsinden bölün. 100 Mbps hatta 5 GB dosya tam hızda yaklaşık 400 saniye (≈6,7 dakika) sürer." }, { q: "Gerçek indirmem neden daha yavaş?", a: "Belirtilen hızlar maksimumdur. Protokol yükü, gecikme, Wi-Fi, disk hızı ve ağ tıkanıklığı gerçek hızı düşürür." }] },
  de: { title: "Download-Zeit-Rechner", short: "Schätzen Sie, wie lange eine Datei bei einer bestimmten Geschwindigkeit braucht.", description: "Kostenloser Download-/Übertragungszeit-Rechner. Geben Sie Dateigröße und Verbindungsgeschwindigkeit (Mbps, MB/s oder Gbps) ein, um die Zeit in Sekunden, Minuten und Stunden zu schätzen.", keywords: ["download zeit rechner", "datenübertragungszeit", "dateiübertragungszeit", "upload zeit", "bandbreiten rechner"], ...io("Dateigröße", "Größeneinheit", "Verbindungsgeschwindigkeit", "Geschwindigkeitseinheit", "Zeit (Sekunden)", "Zeit (Minuten)", "Zeit (Stunden)") },
  fr: { title: "Calculateur de Temps de Téléchargement", short: "Estimez la durée de transfert d'un fichier à une vitesse donnée.", description: "Calculateur de temps de téléchargement/transfert gratuit. Saisissez une taille de fichier et une vitesse de connexion (Mbps, Mo/s ou Gbps) pour estimer la durée en secondes, minutes et heures.", keywords: ["calculateur temps téléchargement", "temps de transfert", "temps de transfert de fichier", "temps d'upload", "calculateur bande passante"], ...io("Taille du fichier", "Unité de taille", "Vitesse de connexion", "Unité de vitesse", "Temps (secondes)", "Temps (minutes)", "Temps (heures)") },
  es: { title: "Calculadora de Tiempo de Descarga", short: "Estima cuánto tarda en transferirse un archivo a una velocidad dada.", description: "Calculadora de tiempo de descarga/transferencia gratuita. Introduce un tamaño de archivo y una velocidad de conexión (Mbps, MB/s o Gbps) para estimar el tiempo en segundos, minutos y horas.", keywords: ["calculadora tiempo de descarga", "tiempo de transferencia", "tiempo de transferencia de archivo", "tiempo de subida", "calculadora de ancho de banda"], ...io("Tamaño del archivo", "Unidad de tamaño", "Velocidad de conexión", "Unidad de velocidad", "Tiempo (segundos)", "Tiempo (minutos)", "Tiempo (horas)") },
  it: { title: "Calcolatore Tempo di Download", short: "Stima quanto tempo impiega un file a trasferirsi a una data velocità.", description: "Calcolatore di tempo di download/trasferimento gratuito. Inserisci una dimensione file e una velocità di connessione (Mbps, MB/s o Gbps) per stimare il tempo in secondi, minuti e ore.", keywords: ["calcolatore tempo download", "tempo di trasferimento", "tempo trasferimento file", "tempo di upload", "calcolatore banda"], ...io("Dimensione file", "Unità dimensione", "Velocità connessione", "Unità velocità", "Tempo (secondi)", "Tempo (minuti)", "Tempo (ore)") },
  ar: { title: "حاسبة وقت التنزيل", short: "قدّر المدة التي يستغرقها نقل ملف بسرعة معينة.", description: "حاسبة وقت تنزيل/نقل مجانية. أدخل حجم الملف وسرعة الاتصال (Mbps أو MB/s أو Gbps) لتقدير الوقت بالثواني والدقائق والساعات.", keywords: ["حاسبة وقت التنزيل", "وقت نقل البيانات", "وقت نقل الملف", "وقت الرفع", "حاسبة النطاق"], ...io("حجم الملف", "وحدة الحجم", "سرعة الاتصال", "وحدة السرعة", "الوقت (ثوانٍ)", "الوقت (دقائق)", "الوقت (ساعات)") },
  ru: { title: "Калькулятор Времени Загрузки", short: "Оцените, сколько времени займёт передача файла на заданной скорости.", description: "Бесплатный калькулятор времени загрузки/передачи. Введите размер файла и скорость соединения (Mbps, MB/s или Gbps), чтобы оценить время в секундах, минутах и часах.", keywords: ["калькулятор времени загрузки", "время передачи данных", "время передачи файла", "время выгрузки", "калькулятор пропускной способности"], ...io("Размер файла", "Единица размера", "Скорость соединения", "Единица скорости", "Время (секунды)", "Время (минуты)", "Время (часы)") },
  zh: { title: "下载时间计算器", short: "估算文件在给定速度下的传输时间。", description: "免费的下载/传输时间计算器。输入文件大小和连接速度（Mbps、MB/s 或 Gbps），估算下载或上传所需的秒、分钟和小时。", keywords: ["下载时间计算器", "数据传输时间", "文件传输时间", "上传时间", "带宽计算器"], ...io("文件大小", "大小单位", "连接速度", "速度单位", "时间（秒）", "时间（分钟）", "时间（小时）") },
  ja: { title: "ダウンロード時間計算機", short: "指定の速度でファイル転送にかかる時間を見積もります。", description: "無料のダウンロード/転送時間計算機。ファイルサイズと接続速度（Mbps・MB/s・Gbps）を入力すると、ダウンロードやアップロードにかかる時間を秒・分・時間で見積もります。", keywords: ["ダウンロード時間 計算機", "データ転送時間", "ファイル転送時間", "アップロード時間", "帯域 計算機"], ...io("ファイルサイズ", "サイズ単位", "接続速度", "速度単位", "時間（秒）", "時間（分）", "時間（時間）") },
  ko: { title: "다운로드 시간 계산기", short: "주어진 속도에서 파일 전송에 걸리는 시간을 추정합니다.", description: "무료 다운로드/전송 시간 계산기. 파일 크기와 연결 속도(Mbps, MB/s 또는 Gbps)를 입력하면 다운로드 또는 업로드 시간을 초, 분, 시간으로 추정합니다.", keywords: ["다운로드 시간 계산기", "데이터 전송 시간", "파일 전송 시간", "업로드 시간", "대역폭 계산기"], ...io("파일 크기", "크기 단위", "연결 속도", "속도 단위", "시간(초)", "시간(분)", "시간(시간)") },
  hi: { title: "डाउनलोड समय कैलकुलेटर", short: "किसी फ़ाइल को दी गई गति पर स्थानांतरित होने में लगने वाला समय अनुमानित करें।", description: "मुफ्त डाउनलोड/स्थानांतरण समय कैलकुलेटर। फ़ाइल आकार और कनेक्शन गति (Mbps, MB/s या Gbps) दर्ज करें और डाउनलोड या अपलोड का समय सेकंड, मिनट और घंटे में अनुमानित करें।", keywords: ["डाउनलोड समय कैलकुलेटर", "डेटा स्थानांतरण समय", "फ़ाइल स्थानांतरण समय", "अपलोड समय", "बैंडविड्थ कैलकुलेटर"], ...io("फ़ाइल आकार", "आकार इकाई", "कनेक्शन गति", "गति इकाई", "समय (सेकंड)", "समय (मिनट)", "समय (घंटे)") },
};

export default i18n;
