import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const KW = ["ipv4 to ipv6 converter", "ipv4 mapped ipv6", "6to4 address", "ipv6 to ipv4", "ipv4 in ipv6"];

const data = {
  en: { title: "IPv4 ↔ IPv6 Converter", short: "Convert IPv4 addresses to IPv4-mapped and 6to4 IPv6, and back.", description: "Free IPv4 to IPv6 converter. Turn a dotted IPv4 address into its IPv4-mapped (::ffff:) and 6to4 (2002:) IPv6 forms, or extract the embedded IPv4 from an IPv6 address. Runs entirely in your browser.", keywords: KW, modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (dotted)", sixToFour: "6to4 prefix", embedded: "Embedded IPv4", invalid: "Invalid address for the selected mode." },
  nl: { title: "IPv4 ↔ IPv6 Converteerer", short: "Converteer IPv4 addresses to IPv4-mapped and 6to4 IPv6, and back.", description: "Gratis IPv4 to IPv6 converteerer. Turn a dotted IPv4 address into its IPv4-mapped (::ffff:) and 6to4 (2002:) IPv6 forms, or extract the embedded IPv4 from an IPv6 address. Runs entirely in uw browser.", keywords: KW, modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (dotted)", sixToFour: "6to4 prefix", embedded: "Embedded IPv4", invalid: "Invalid address for the selected mode." },

  pl: { title: "IPv4 ↔ IPv6 Konwerter", short: "Konwertuj IPv4 addresses to IPv4-mapped and 6to4 IPv6, and back.", description: "Darmowy IPv4 to IPv6 konwerter. Turn a dotted IPv4 address into its IPv4-mapped (::ffff:) and 6to4 (2002:) IPv6 forms, or extract the embedded IPv4 from an IPv6 address. Runs entirely w Twojej przeglądarce.", keywords: KW, modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (dotted)", sixToFour: "6to4 prefix", embedded: "Embedded IPv4", invalid: "Invalid address for the selected mode." },
  pt: { title: "Conversor IPv4 ↔ IPv6", short: "Converta endereços IPv4 em IPv6 IPv4-mapped e 6to4, e vice-versa.", description: "Conversor IPv4 para IPv6 gratuito. Transforme um endereço IPv4 nas formas IPv4-mapped (::ffff:) e 6to4 (2002:), ou extraia o IPv4 embutido em um endereço IPv6. Executa inteiramente no seu navegador.", keywords: KW, modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (decimal)", sixToFour: "Prefixo 6to4", embedded: "IPv4 embutido", invalid: "Endereço inválido para o modo selecionado." },
  id: { title: "Konverter IPv4 ↔ IPv6", short: "Konversi alamat IPv4 ke IPv6 IPv4-mapped dan 6to4, dan sebaliknya.", description: "Konverter IPv4 ke IPv6 gratis. Ubah alamat IPv4 menjadi bentuk IPv4-mapped (::ffff:) dan 6to4 (2002:), atau ekstrak IPv4 yang tertanam dari alamat IPv6. Berjalan sepenuhnya di browser Anda.", keywords: KW, modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (desimal)", sixToFour: "Prefiks 6to4", embedded: "IPv4 tertanam", invalid: "Alamat tidak valid untuk mode yang dipilih." },

  tr: { title: "IPv4 ↔ IPv6 Dönüştürücü", short: "IPv4 adreslerini IPv4-mapped ve 6to4 IPv6 biçimlerine ve geri dönüştürün.", description: "Ücretsiz IPv4'ten IPv6'ya dönüştürücü. Noktalı bir IPv4 adresini IPv4-mapped (::ffff:) ve 6to4 (2002:) IPv6 biçimlerine çevirin veya IPv6 adresine gömülü IPv4'ü çıkarın. Tamamen tarayıcınızda çalışır.", keywords: ["ipv4 ipv6 dönüştürücü", "ipv4 eşlemeli ipv6", "6to4 adresi", "ipv6 ipv4 dönüştürücü", "ipv4 ipv6 içinde"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (onaltılık)", mappedDotted: "IPv4-mapped (noktalı)", sixToFour: "6to4 öneki", embedded: "Gömülü IPv4", invalid: "Seçilen mod için geçersiz adres." },
  de: { title: "IPv4 ↔ IPv6 Konverter", short: "IPv4-Adressen in IPv4-mapped und 6to4 IPv6 umwandeln und zurück.", description: "Kostenloser IPv4-zu-IPv6-Konverter. Wandeln Sie eine IPv4-Adresse in die IPv4-mapped (::ffff:) und 6to4 (2002:) IPv6-Formen um oder extrahieren Sie die eingebettete IPv4 aus einer IPv6-Adresse. Läuft vollständig in Ihrem Browser.", keywords: ["ipv4 zu ipv6 konverter", "ipv4-mapped ipv6", "6to4 adresse", "ipv6 zu ipv4", "ipv4 in ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (Punktnotation)", sixToFour: "6to4-Präfix", embedded: "Eingebettete IPv4", invalid: "Ungültige Adresse für den gewählten Modus." },
  fr: { title: "Convertisseur IPv4 ↔ IPv6", short: "Convertissez des adresses IPv4 en IPv6 IPv4-mapped et 6to4, et inversement.", description: "Convertisseur IPv4 vers IPv6 gratuit. Transformez une adresse IPv4 en ses formes IPv4-mapped (::ffff:) et 6to4 (2002:), ou extrayez l'IPv4 intégrée d'une adresse IPv6. S'exécute entièrement dans votre navigateur.", keywords: ["convertisseur ipv4 ipv6", "ipv4 mappée ipv6", "adresse 6to4", "ipv6 vers ipv4", "ipv4 dans ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (pointée)", sixToFour: "Préfixe 6to4", embedded: "IPv4 intégrée", invalid: "Adresse invalide pour le mode sélectionné." },
  es: { title: "Conversor IPv4 ↔ IPv6", short: "Convierte direcciones IPv4 a IPv6 IPv4-mapped y 6to4, y viceversa.", description: "Conversor IPv4 a IPv6 gratuito. Convierte una dirección IPv4 en sus formas IPv4-mapped (::ffff:) y 6to4 (2002:), o extrae la IPv4 incrustada de una dirección IPv6. Se ejecuta completamente en tu navegador.", keywords: ["conversor ipv4 ipv6", "ipv4 mapeada ipv6", "dirección 6to4", "ipv6 a ipv4", "ipv4 en ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (decimal)", sixToFour: "Prefijo 6to4", embedded: "IPv4 incrustada", invalid: "Dirección no válida para el modo seleccionado." },
  it: { title: "Convertitore IPv4 ↔ IPv6", short: "Converti indirizzi IPv4 in IPv6 IPv4-mapped e 6to4, e viceversa.", description: "Convertitore IPv4 in IPv6 gratuito. Trasforma un indirizzo IPv4 nelle forme IPv4-mapped (::ffff:) e 6to4 (2002:), oppure estrai l'IPv4 incorporato da un indirizzo IPv6. Funziona interamente nel tuo browser.", keywords: ["convertitore ipv4 ipv6", "ipv4 mappato ipv6", "indirizzo 6to4", "ipv6 in ipv4", "ipv4 in ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (decimale)", sixToFour: "Prefisso 6to4", embedded: "IPv4 incorporato", invalid: "Indirizzo non valido per la modalità selezionata." },
  ar: { title: "محوّل IPv4 ↔ IPv6", short: "حوّل عناوين IPv4 إلى IPv6 من نوع IPv4-mapped و6to4 والعكس.", description: "محوّل IPv4 إلى IPv6 مجاني. حوّل عنوان IPv4 إلى صيغتي IPv4-mapped (::ffff:) و6to4 (2002:)، أو استخرج عنوان IPv4 المضمّن من عنوان IPv6. يعمل بالكامل في متصفحك.", keywords: ["محول ipv4 ipv6", "ipv4 معين ipv6", "عنوان 6to4", "ipv6 إلى ipv4", "ipv4 داخل ipv6"], modeTo6: "IPv4 ← IPv6", modeTo4: "IPv6 ← IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (ست عشري)", mappedDotted: "IPv4-mapped (منقّط)", sixToFour: "بادئة 6to4", embedded: "IPv4 المضمّن", invalid: "عنوان غير صالح للوضع المحدد." },
  ru: { title: "Конвертер IPv4 ↔ IPv6", short: "Преобразуйте адреса IPv4 в IPv4-mapped и 6to4 IPv6 и обратно.", description: "Бесплатный конвертер IPv4 в IPv6. Превратите IPv4-адрес в формы IPv4-mapped (::ffff:) и 6to4 (2002:) или извлеките встроенный IPv4 из IPv6-адреса. Работает полностью в вашем браузере.", keywords: ["конвертер ipv4 ipv6", "ipv4-mapped ipv6", "адрес 6to4", "ipv6 в ipv4", "ipv4 в ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (hex)", mappedDotted: "IPv4-mapped (точечный)", sixToFour: "Префикс 6to4", embedded: "Встроенный IPv4", invalid: "Недопустимый адрес для выбранного режима." },
  zh: { title: "IPv4 ↔ IPv6 转换器", short: "在 IPv4 地址与 IPv4-mapped、6to4 形式的 IPv6 之间相互转换。", description: "免费的 IPv4 转 IPv6 转换器。将点分 IPv4 地址转换为 IPv4-mapped (::ffff:) 和 6to4 (2002:) 形式的 IPv6，或从 IPv6 地址中提取内嵌的 IPv4。完全在浏览器中运行。", keywords: ["ipv4 转 ipv6", "ipv4 映射 ipv6", "6to4 地址", "ipv6 转 ipv4", "ipv4 嵌入 ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped（十六进制）", mappedDotted: "IPv4-mapped（点分）", sixToFour: "6to4 前缀", embedded: "内嵌 IPv4", invalid: "对于所选模式无效的地址。" },
  ja: { title: "IPv4 ↔ IPv6 変換ツール", short: "IPv4 アドレスを IPv4-mapped・6to4 の IPv6 へ、またはその逆へ変換します。", description: "無料の IPv4 から IPv6 への変換ツール。ドット付き IPv4 アドレスを IPv4-mapped (::ffff:) と 6to4 (2002:) の IPv6 形式に変換したり、IPv6 アドレスから埋め込まれた IPv4 を抽出します。すべてブラウザ内で動作します。", keywords: ["ipv4 ipv6 変換", "ipv4 マップド ipv6", "6to4 アドレス", "ipv6 から ipv4", "ipv4 埋め込み ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped（16進）", mappedDotted: "IPv4-mapped（ドット）", sixToFour: "6to4 プレフィックス", embedded: "埋め込み IPv4", invalid: "選択したモードに対して無効なアドレスです。" },
  ko: { title: "IPv4 ↔ IPv6 변환기", short: "IPv4 주소를 IPv4-mapped 및 6to4 IPv6로, 그리고 그 반대로 변환합니다.", description: "무료 IPv4 to IPv6 변환기. 점으로 구분된 IPv4 주소를 IPv4-mapped (::ffff:) 및 6to4 (2002:) IPv6 형식으로 변환하거나 IPv6 주소에서 내장된 IPv4를 추출합니다. 브라우저에서 완전히 실행됩니다.", keywords: ["ipv4 ipv6 변환기", "ipv4 매핑 ipv6", "6to4 주소", "ipv6에서 ipv4", "ipv4 내장 ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (16진수)", mappedDotted: "IPv4-mapped (점 표기)", sixToFour: "6to4 접두사", embedded: "내장 IPv4", invalid: "선택한 모드에 유효하지 않은 주소입니다." },
  hi: { title: "IPv4 ↔ IPv6 कन्वर्टर", short: "IPv4 पतों को IPv4-mapped और 6to4 IPv6 में और वापस बदलें।", description: "मुफ्त IPv4 से IPv6 कन्वर्टर। एक IPv4 पते को उसके IPv4-mapped (::ffff:) और 6to4 (2002:) IPv6 रूपों में बदलें, या IPv6 पते से अंतर्निहित IPv4 निकालें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["ipv4 ipv6 कन्वर्टर", "ipv4 मैप्ड ipv6", "6to4 पता", "ipv6 से ipv4", "ipv4 इन ipv6"], modeTo6: "IPv4 → IPv6", modeTo4: "IPv6 → IPv4", ipv4Placeholder: "192.168.1.1", ipv6Placeholder: "::ffff:c0a8:0101", mappedHex: "IPv4-mapped (हेक्स)", mappedDotted: "IPv4-mapped (डॉटेड)", sixToFour: "6to4 प्रीफ़िक्स", embedded: "अंतर्निहित IPv4", invalid: "चयनित मोड के लिए अमान्य पता।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
