import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Tailwind Shade Generator", short: "Build a Tailwind-style 50–950 colour scale from any hex.", description: "Free Tailwind shade generator. Pick a base hex colour and get a complete Tailwind-style 50, 100, 200 … 950 scale, ready to drop into your tailwind.config.js or design tokens.", keywords: ["tailwind shade generator", "tailwind color palette", "tailwind 50 950 generator", "tailwind color scale", "tw color generator"], baseColor: "Base color", scale: "Scale" },
  tr: { title: "Tailwind Ton Oluşturucu", short: "Herhangi bir hex'ten Tailwind tarzı 50–950 renk skalası oluşturun.", description: "Ücretsiz Tailwind ton oluşturucu. Bir temel hex rengi seçin ve tailwind.config.js veya tasarım belirteçlerinize bırakmaya hazır eksiksiz bir Tailwind tarzı 50, 100, 200 … 950 skalası alın.", keywords: ["tailwind ton oluşturucu", "tailwind renk paleti", "tailwind 50 950 oluşturucu", "tailwind renk skalası", "tw renk oluşturucu"], baseColor: "Temel renk", scale: "Skala" },
  de: { title: "Tailwind-Schattierungs-Generator", short: "Erzeugen Sie eine Tailwind-50–950-Farbskala aus jedem Hex.", description: "Kostenloser Tailwind-Schattierungs-Generator. Wählen Sie eine Basis-Hex-Farbe und erhalten Sie eine vollständige Tailwind-Skala 50, 100, 200 … 950 zum direkten Einsatz in tailwind.config.js oder Design-Tokens.", keywords: ["tailwind schattierungen generator", "tailwind farbpalette", "tailwind 50 950 generator", "tailwind farbskala", "tw farb generator"], baseColor: "Grundfarbe", scale: "Skala" },
  fr: { title: "Générateur de Nuances Tailwind", short: "Créez une échelle de couleurs 50–950 Tailwind à partir de n'importe quel hex.", description: "Générateur de nuances Tailwind gratuit. Choisissez une couleur hex de base et obtenez une échelle Tailwind 50, 100, 200 … 950 complète, prête à insérer dans votre tailwind.config.js ou vos design tokens.", keywords: ["générateur nuances tailwind", "palette couleurs tailwind", "générateur 50 950 tailwind", "échelle couleurs tailwind", "générateur couleurs tw"], baseColor: "Couleur de base", scale: "Échelle" },
  es: { title: "Generador de Tonos Tailwind", short: "Crea una escala de colores 50–950 Tailwind desde cualquier hex.", description: "Generador de tonos Tailwind gratuito. Elige un color hex base y obtén una escala Tailwind 50, 100, 200 … 950 completa, lista para colocar en tu tailwind.config.js o design tokens.", keywords: ["generador tonos tailwind", "paleta colores tailwind", "generador 50 950 tailwind", "escala colores tailwind", "generador colores tw"], baseColor: "Color base", scale: "Escala" },
  it: { title: "Generatore di Tonalità Tailwind", short: "Crea una scala colori 50–950 Tailwind da qualsiasi hex.", description: "Generatore di tonalità Tailwind gratuito. Scegli un colore hex base e ottieni una scala Tailwind 50, 100, 200 … 950 completa, pronta da inserire nel tuo tailwind.config.js o design token.", keywords: ["generatore tonalità tailwind", "palette colori tailwind", "generatore 50 950 tailwind", "scala colori tailwind", "generatore colori tw"], baseColor: "Colore base", scale: "Scala" },
  ar: { title: "مولّد درجات Tailwind", short: "أنشئ مقياس ألوان 50–950 على نمط Tailwind من أي hex.", description: "مولّد درجات Tailwind مجاني. اختر لونًا hex أساسيًا واحصل على مقياس Tailwind كامل 50، 100، 200 … 950، جاهز للإضافة إلى tailwind.config.js أو رموز التصميم.", keywords: ["مولد درجات tailwind", "لوحة ألوان tailwind", "مولد 50 950 tailwind", "مقياس ألوان tailwind", "مولد ألوان tw"], baseColor: "اللون الأساسي", scale: "المقياس" },
  ru: { title: "Генератор оттенков Tailwind", short: "Создайте шкалу 50–950 в стиле Tailwind из любого hex.", description: "Бесплатный генератор оттенков Tailwind. Выберите базовый hex и получите полную шкалу Tailwind 50, 100, 200 … 950, готовую к вставке в tailwind.config.js или дизайн-токены.", keywords: ["генератор оттенков tailwind", "палитра tailwind", "генератор 50 950 tailwind", "шкала цветов tailwind", "генератор цветов tw"], baseColor: "Базовый цвет", scale: "Шкала" },
  zh: { title: "Tailwind 色阶生成器", short: "从任意 hex 生成 Tailwind 风格的 50–950 色阶。", description: "免费的 Tailwind 色阶生成器。选择基础 hex 颜色，获得完整的 Tailwind 50、100、200 … 950 色阶，可直接放入 tailwind.config.js 或设计令牌。", keywords: ["tailwind 色阶生成器", "tailwind 调色板", "tailwind 50 950 生成器", "tailwind 颜色比例", "tw 颜色生成器"], baseColor: "基础颜色", scale: "色阶" },
  ja: { title: "Tailwind シェード生成", short: "任意の hex から Tailwind スタイルの 50–950 カラースケールを構築。", description: "無料の Tailwind シェード生成ツール。ベース hex カラーを選ぶと、tailwind.config.js やデザイントークンに直接配置できる Tailwind スタイルの 50、100、200 … 950 スケールが完成します。", keywords: ["tailwind シェード 生成", "tailwind カラーパレット", "tailwind 50 950 生成", "tailwind カラースケール", "tw カラー 生成"], baseColor: "ベースカラー", scale: "スケール" },
  ko: { title: "Tailwind 셰이드 생성기", short: "모든 hex에서 Tailwind 스타일의 50–950 색상 스케일을 만듭니다.", description: "무료 Tailwind 셰이드 생성기. 기본 hex 색상을 선택하면 tailwind.config.js 또는 디자인 토큰에 바로 넣을 수 있는 완전한 Tailwind 스타일 50, 100, 200 … 950 스케일을 얻습니다.", keywords: ["tailwind 셰이드 생성기", "tailwind 색상 팔레트", "tailwind 50 950 생성기", "tailwind 색상 스케일", "tw 색상 생성기"], baseColor: "기준 색상", scale: "스케일" },
  hi: { title: "Tailwind शेड जनरेटर", short: "किसी भी hex से Tailwind शैली के 50–950 रंग स्केल बनाएं।", description: "मुफ्त Tailwind शेड जनरेटर। एक आधार hex रंग चुनें और tailwind.config.js या डिज़ाइन टोकन में सीधे डालने के लिए तैयार पूर्ण Tailwind शैली 50, 100, 200 … 950 स्केल पाएं।", keywords: ["tailwind शेड जनरेटर", "tailwind रंग पैलेट", "tailwind 50 950 जनरेटर", "tailwind रंग स्केल", "tw रंग जनरेटर"], baseColor: "आधार रंग", scale: "स्केल" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
