import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IP Location Lookup", short: "Geolocate any IP address: country, city, ISP and ASN.", description: "Free IP location lookup. Enter any IPv4 or IPv6 address to see its approximate country, region, city, ISP/organisation, ASN and coordinates with a map link — all from your browser.", keywords: ["ip location lookup", "ip geolocation", "ip address location", "find ip location", "ip to location"], ip: "IP address", run: "Look up", location: "Location", isp: "ISP / Organisation", asn: "ASN", coords: "Coordinates", map: "View on map", placeholder: "8.8.8.8", invalid: "Enter a valid IPv4 or IPv6 address.", unavailable: "Lookup unavailable. The IP service may be rate-limited or blocked by your network." },
  pt: { title: "IP Location Lookup", short: "Geolocate any IP address: country, city, ISP e ASN.", description: "Gratuito - IP location lookup. Enter any IPv4 ou IPv6 address para see its approximate country, region, city, ISP/organisation, ASN e coordinates with a map link â todos a partir de seu browser.", keywords: ["ip location lookup", "ip geolocation", "ip address location", "find ip location", "ip to location"], ip: "Endereço IP", run: "Pesquisar", location: "Localização", isp: "ISP / Organização", asn: "ASN", coords: "Coordenadas", map: "Ver no mapa", placeholder: "8.8.8.8", invalid: "Insira um endereço IPv4 ou IPv6 válido.", unavailable: "Consulta indisponível. O serviço de IP pode estar limitado ou bloqueado pela sua rede." },
  id: { title: "IP Location Lookup", short: "Geolocate any IP address: country, city, ISP dan ASN.", description: "Gratis - IP location lookup. Enter any IPv4 atau IPv6 address to see its approximate country, region, city, ISP/organisation, ASN dan coordinates with a map link â semua from Anda browser.", keywords: ["ip location lookup", "ip geolocation", "ip address location", "find ip location", "ip to location"], ip: "Alamat IP", run: "Cari", location: "Lokasi", isp: "ISP / Organisasi", asn: "ASN", coords: "Koordinat", map: "Lihat di peta", placeholder: "8.8.8.8", invalid: "Masukkan alamat IPv4 atau IPv6 yang valid.", unavailable: "Pencarian tidak tersedia. Layanan IP mungkin dibatasi atau diblokir oleh jaringan Anda." },

  tr: { title: "IP Konum Sorgu", short: "Herhangi bir IP adresini coğrafi konumlandırın: ülke, şehir, ISS, ASN.", description: "Ücretsiz IP konum sorgu aracı. Herhangi bir IPv4 veya IPv6 adresi girin; yaklaşık ülke, bölge, şehir, ISS/kuruluş, ASN ve koordinatları harita bağlantısıyla görün — tamamen tarayıcınızdan.", keywords: ["ip konum sorgu", "ip coğrafi konum", "ip adresi konumu", "ip konum bul", "ip'den konuma"], ip: "IP adresi", run: "Sorgula", location: "Konum", isp: "ISS / Kuruluş", asn: "ASN", coords: "Koordinatlar", map: "Haritada gör", placeholder: "8.8.8.8", invalid: "Geçerli bir IPv4 veya IPv6 adresi girin.", unavailable: "Sorgu kullanılamıyor. IP hizmeti hız sınırlı olabilir veya ağınız tarafından engellenmiş olabilir." },
  de: { title: "IP-Standort-Lookup", short: "Jede IP-Adresse geolokalisieren: Land, Stadt, ISP und ASN.", description: "Kostenloser IP-Standort-Lookup. Geben Sie eine beliebige IPv4- oder IPv6-Adresse ein, um ungefähres Land, Region, Stadt, ISP/Organisation, ASN und Koordinaten samt Kartenlink zu sehen — alles im Browser.", keywords: ["ip standort lookup", "ip geolokalisierung", "ip adresse standort", "ip standort finden", "ip zu standort"], ip: "IP-Adresse", run: "Abfragen", location: "Standort", isp: "ISP / Organisation", asn: "ASN", coords: "Koordinaten", map: "Auf Karte ansehen", placeholder: "8.8.8.8", invalid: "Geben Sie eine gültige IPv4- oder IPv6-Adresse ein.", unavailable: "Abfrage nicht verfügbar. Der IP-Dienst ist möglicherweise gedrosselt oder von Ihrem Netzwerk blockiert." },
  fr: { title: "Localisation d'IP", short: "Géolocalisez n'importe quelle IP : pays, ville, FAI et ASN.", description: "Outil de localisation d'IP gratuit. Saisissez une adresse IPv4 ou IPv6 pour voir son pays, sa région, sa ville, son FAI/organisation, son ASN et ses coordonnées avec un lien carte — depuis votre navigateur.", keywords: ["localisation ip", "géolocalisation ip", "localisation adresse ip", "trouver localisation ip", "ip vers localisation"], ip: "Adresse IP", run: "Rechercher", location: "Localisation", isp: "FAI / Organisation", asn: "ASN", coords: "Coordonnées", map: "Voir sur la carte", placeholder: "8.8.8.8", invalid: "Saisissez une adresse IPv4 ou IPv6 valide.", unavailable: "Recherche indisponible. Le service IP est peut-être limité ou bloqué par votre réseau." },
  es: { title: "Localización de IP", short: "Geolocaliza cualquier IP: país, ciudad, ISP y ASN.", description: "Búsqueda de localización de IP gratuita. Introduce cualquier dirección IPv4 o IPv6 para ver su país, región, ciudad, ISP/organización, ASN y coordenadas con un enlace al mapa — desde tu navegador.", keywords: ["localización de ip", "geolocalización ip", "ubicación dirección ip", "encontrar ubicación ip", "ip a ubicación"], ip: "Dirección IP", run: "Buscar", location: "Ubicación", isp: "ISP / Organización", asn: "ASN", coords: "Coordenadas", map: "Ver en el mapa", placeholder: "8.8.8.8", invalid: "Introduce una dirección IPv4 o IPv6 válida.", unavailable: "Consulta no disponible. El servicio de IP puede estar limitado o bloqueado por tu red." },
  it: { title: "Localizzazione IP", short: "Geolocalizza qualsiasi IP: paese, città, ISP e ASN.", description: "Ricerca localizzazione IP gratuita. Inserisci un indirizzo IPv4 o IPv6 per vederne paese, regione, città, ISP/organizzazione, ASN e coordinate con un link alla mappa — dal tuo browser.", keywords: ["localizzazione ip", "geolocalizzazione ip", "posizione indirizzo ip", "trova posizione ip", "ip a posizione"], ip: "Indirizzo IP", run: "Cerca", location: "Posizione", isp: "ISP / Organizzazione", asn: "ASN", coords: "Coordinate", map: "Vedi sulla mappa", placeholder: "8.8.8.8", invalid: "Inserisci un indirizzo IPv4 o IPv6 valido.", unavailable: "Ricerca non disponibile. Il servizio IP potrebbe essere limitato o bloccato dalla tua rete." },
  ar: { title: "بحث موقع IP", short: "حدّد الموقع الجغرافي لأي عنوان IP: الدولة والمدينة ومزود الخدمة و ASN.", description: "بحث مجاني عن موقع IP. أدخل أي عنوان IPv4 أو IPv6 لرؤية دولته ومنطقته ومدينته ومزود الخدمة/المؤسسة و ASN والإحداثيات مع رابط خريطة — من متصفحك.", keywords: ["بحث موقع ip", "تحديد موقع ip", "موقع عنوان ip", "اعثر على موقع ip", "ip إلى موقع"], ip: "عنوان IP", run: "بحث", location: "الموقع", isp: "مزود الخدمة / المؤسسة", asn: "ASN", coords: "الإحداثيات", map: "عرض على الخريطة", placeholder: "8.8.8.8", invalid: "أدخل عنوان IPv4 أو IPv6 صالحًا.", unavailable: "البحث غير متاح. قد تكون خدمة IP محدودة المعدل أو محظورة من شبكتك." },
  ru: { title: "Геолокация IP", short: "Геолокация любого IP-адреса: страна, город, провайдер и ASN.", description: "Бесплатная геолокация IP. Введите любой IPv4- или IPv6-адрес, чтобы увидеть его страну, регион, город, провайдера/организацию, ASN и координаты со ссылкой на карту — прямо из браузера.", keywords: ["геолокация ip", "местоположение ip", "местоположение ip адреса", "найти местоположение ip", "ip в местоположение"], ip: "IP-адрес", run: "Найти", location: "Местоположение", isp: "Провайдер / Организация", asn: "ASN", coords: "Координаты", map: "Показать на карте", placeholder: "8.8.8.8", invalid: "Введите корректный IPv4- или IPv6-адрес.", unavailable: "Запрос недоступен. Служба IP может быть ограничена или заблокирована вашей сетью." },
  zh: { title: "IP 位置查询", short: "对任意 IP 地址进行地理定位：国家、城市、ISP 和 ASN。", description: "免费的 IP 位置查询。输入任意 IPv4 或 IPv6 地址，即可查看其大致国家、地区、城市、ISP/组织、ASN 和坐标，并附带地图链接——全在浏览器中运行。", keywords: ["ip 位置查询", "ip 地理定位", "ip 地址位置", "查找 ip 位置", "ip 转位置"], ip: "IP 地址", run: "查询", location: "位置", isp: "ISP / 组织", asn: "ASN", coords: "坐标", map: "在地图上查看", placeholder: "8.8.8.8", invalid: "请输入有效的 IPv4 或 IPv6 地址。", unavailable: "查询不可用。IP 服务可能受到速率限制或被你的网络阻止。" },
  ja: { title: "IP 位置検索", short: "任意の IP アドレスを地理位置情報化：国・都市・ISP・ASN。", description: "無料の IP 位置検索。任意の IPv4 または IPv6 アドレスを入力すると、おおよその国・地域・都市・ISP/組織・ASN・座標を地図リンク付きで表示します——すべてブラウザ内で動作します。", keywords: ["ip 位置検索", "ip 地理位置情報", "ip アドレス 位置", "ip 位置を調べる", "ip から位置"], ip: "IP アドレス", run: "検索", location: "位置", isp: "ISP / 組織", asn: "ASN", coords: "座標", map: "地図で見る", placeholder: "8.8.8.8", invalid: "有効な IPv4 または IPv6 アドレスを入力してください。", unavailable: "検索を利用できません。IP サービスがレート制限されているか、ネットワークによってブロックされている可能性があります。" },
  ko: { title: "IP 위치 조회", short: "모든 IP 주소를 지오로케이션: 국가, 도시, ISP, ASN.", description: "무료 IP 위치 조회. IPv4 또는 IPv6 주소를 입력하면 대략적인 국가, 지역, 도시, ISP/조직, ASN, 좌표를 지도 링크와 함께 표시합니다 — 모두 브라우저에서 실행됩니다.", keywords: ["ip 위치 조회", "ip 지오로케이션", "ip 주소 위치", "ip 위치 찾기", "ip 위치 변환"], ip: "IP 주소", run: "조회", location: "위치", isp: "ISP / 조직", asn: "ASN", coords: "좌표", map: "지도에서 보기", placeholder: "8.8.8.8", invalid: "유효한 IPv4 또는 IPv6 주소를 입력하세요.", unavailable: "조회를 사용할 수 없습니다. IP 서비스가 속도 제한되었거나 네트워크에서 차단되었을 수 있습니다." },
  hi: { title: "IP स्थान लुकअप", short: "किसी भी IP पते को जियोलोकेट करें: देश, शहर, ISP और ASN।", description: "मुफ्त IP स्थान लुकअप। कोई भी IPv4 या IPv6 पता दर्ज करें और उसका अनुमानित देश, क्षेत्र, शहर, ISP/संगठन, ASN और निर्देशांक मानचित्र लिंक के साथ देखें — सब आपके ब्राउज़र से।", keywords: ["ip स्थान लुकअप", "ip जियोलोकेशन", "ip पता स्थान", "ip स्थान खोजें", "ip से स्थान"], ip: "IP पता", run: "खोजें", location: "स्थान", isp: "ISP / संगठन", asn: "ASN", coords: "निर्देशांक", map: "मानचित्र पर देखें", placeholder: "8.8.8.8", invalid: "एक मान्य IPv4 या IPv6 पता दर्ज करें।", unavailable: "लुकअप अनुपलब्ध। IP सेवा दर-सीमित हो सकती है या आपके नेटवर्क द्वारा अवरुद्ध हो सकती है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
