import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Lorem Ipsum Generator", short: "Generate placeholder paragraphs, sentences or words for mockups.", description: "Free Lorem Ipsum generator. Create dummy placeholder text by paragraphs, sentences or words, optionally starting with the classic 'Lorem ipsum dolor sit amet'. Perfect for design mockups and layout testing.", keywords: ["lorem ipsum", "placeholder text", "dummy text generator", "lipsum", "filler text"], count: "How many", paragraphs: "Paragraphs", sentences: "Sentences", words: "Words", startWith: "Start with “Lorem ipsum”", generate: "Generate" },
  tr: { title: "Lorem Ipsum Üretici", short: "Maketler için yer tutucu paragraf, cümle veya kelime üretin.", description: "Ücretsiz Lorem Ipsum üretici. Paragraf, cümle veya kelime olarak sahte yer tutucu metin oluşturun; isteğe bağlı olarak klasik 'Lorem ipsum dolor sit amet' ile başlayın. Tasarım maketleri ve düzen testi için idealdir.", keywords: ["lorem ipsum", "yer tutucu metin", "sahte metin üretici", "lipsum", "dolgu metni"], count: "Adet", paragraphs: "Paragraf", sentences: "Cümle", words: "Kelime", startWith: "“Lorem ipsum” ile başla", generate: "Üret" },
  de: { title: "Lorem-Ipsum-Generator", short: "Erzeugen Sie Platzhalter-Absätze, -Sätze oder -Wörter für Mockups.", description: "Kostenloser Lorem-Ipsum-Generator. Erstellen Sie Blindtext nach Absätzen, Sätzen oder Wörtern, optional beginnend mit dem klassischen 'Lorem ipsum dolor sit amet'. Ideal für Design-Mockups.", keywords: ["lorem ipsum", "platzhaltertext", "blindtext generator", "lipsum", "fülltext"], count: "Anzahl", paragraphs: "Absätze", sentences: "Sätze", words: "Wörter", startWith: "Mit „Lorem ipsum“ beginnen", generate: "Erzeugen" },
  fr: { title: "Générateur de Lorem Ipsum", short: "Générez des paragraphes, phrases ou mots de remplissage pour vos maquettes.", description: "Générateur de Lorem Ipsum gratuit. Créez du faux texte par paragraphes, phrases ou mots, en commençant éventuellement par le classique « Lorem ipsum dolor sit amet ». Parfait pour les maquettes.", keywords: ["lorem ipsum", "texte de remplissage", "faux texte", "lipsum", "texte fictif"], count: "Combien", paragraphs: "Paragraphes", sentences: "Phrases", words: "Mots", startWith: "Commencer par « Lorem ipsum »", generate: "Générer" },
  es: { title: "Generador de Lorem Ipsum", short: "Genera párrafos, oraciones o palabras de relleno para maquetas.", description: "Generador de Lorem Ipsum gratuito. Crea texto de relleno por párrafos, oraciones o palabras, comenzando opcionalmente con el clásico 'Lorem ipsum dolor sit amet'. Perfecto para maquetas de diseño.", keywords: ["lorem ipsum", "texto de relleno", "generador de texto ficticio", "lipsum", "texto de marcador"], count: "Cuántos", paragraphs: "Párrafos", sentences: "Oraciones", words: "Palabras", startWith: "Empezar con “Lorem ipsum”", generate: "Generar" },
  it: { title: "Generatore di Lorem Ipsum", short: "Genera paragrafi, frasi o parole segnaposto per i mockup.", description: "Generatore di Lorem Ipsum gratuito. Crea testo segnaposto per paragrafi, frasi o parole, iniziando facoltativamente con il classico 'Lorem ipsum dolor sit amet'. Perfetto per i mockup di design.", keywords: ["lorem ipsum", "testo segnaposto", "generatore testo fittizio", "lipsum", "testo riempitivo"], count: "Quanti", paragraphs: "Paragrafi", sentences: "Frasi", words: "Parole", startWith: "Inizia con “Lorem ipsum”", generate: "Genera" },
  ar: { title: "مولّد Lorem Ipsum", short: "أنشئ فقرات أو جملًا أو كلمات نائبة للنماذج.", description: "مولّد Lorem Ipsum مجاني. أنشئ نصًا نائبًا حسب الفقرات أو الجمل أو الكلمات، مع خيار البدء بالعبارة الكلاسيكية 'Lorem ipsum dolor sit amet'. مثالي لنماذج التصميم.", keywords: ["lorem ipsum", "نص نائب", "مولد نص وهمي", "lipsum", "نص حشو"], count: "العدد", paragraphs: "فقرات", sentences: "جمل", words: "كلمات", startWith: "ابدأ بـ ”Lorem ipsum“", generate: "توليد" },
  ru: { title: "Генератор Lorem Ipsum", short: "Генерируйте текст-заполнитель абзацами, предложениями или словами.", description: "Бесплатный генератор Lorem Ipsum. Создавайте текст-заполнитель по абзацам, предложениям или словам, при желании начиная с классического 'Lorem ipsum dolor sit amet'. Идеально для макетов.", keywords: ["lorem ipsum", "текст-заполнитель", "генератор рыбного текста", "lipsum", "заполняющий текст"], count: "Количество", paragraphs: "Абзацы", sentences: "Предложения", words: "Слова", startWith: "Начать с «Lorem ipsum»", generate: "Сгенерировать" },
  zh: { title: "Lorem Ipsum 生成器", short: "为原型生成占位段落、句子或单词。", description: "免费的 Lorem Ipsum 生成器。按段落、句子或单词创建占位文本，可选择以经典的 'Lorem ipsum dolor sit amet' 开头。非常适合设计原型和布局测试。", keywords: ["lorem ipsum", "占位文本", "假文生成器", "lipsum", "填充文本"], count: "数量", paragraphs: "段落", sentences: "句子", words: "单词", startWith: "以 “Lorem ipsum” 开头", generate: "生成" },
  ja: { title: "Lorem Ipsum ジェネレーター", short: "モックアップ用のダミー段落・文・単語を生成します。", description: "無料の Lorem Ipsum ジェネレーター。段落・文・単語単位でダミーのプレースホルダーテキストを作成。オプションで定番の 'Lorem ipsum dolor sit amet' から開始できます。デザインのモックアップに最適。", keywords: ["lorem ipsum", "プレースホルダーテキスト", "ダミーテキスト生成", "lipsum", "ダミー文"], count: "個数", paragraphs: "段落", sentences: "文", words: "単語", startWith: "「Lorem ipsum」で開始", generate: "生成" },
  ko: { title: "Lorem Ipsum 생성기", short: "목업용 자리표시 단락, 문장 또는 단어를 생성합니다.", description: "무료 Lorem Ipsum 생성기. 단락, 문장 또는 단어 단위로 더미 자리표시 텍스트를 만들고, 선택적으로 고전적인 'Lorem ipsum dolor sit amet'로 시작할 수 있습니다. 디자인 목업에 적합합니다.", keywords: ["lorem ipsum", "자리표시 텍스트", "더미 텍스트 생성기", "lipsum", "채움 텍스트"], count: "개수", paragraphs: "단락", sentences: "문장", words: "단어", startWith: "“Lorem ipsum”으로 시작", generate: "생성" },
  hi: { title: "Lorem Ipsum जनरेटर", short: "मॉकअप के लिए प्लेसहोल्डर अनुच्छेद, वाक्य या शब्द बनाएं।", description: "मुफ्त Lorem Ipsum जनरेटर। अनुच्छेद, वाक्य या शब्द के अनुसार डमी प्लेसहोल्डर टेक्स्ट बनाएं, वैकल्पिक रूप से क्लासिक 'Lorem ipsum dolor sit amet' से शुरू करें। डिज़ाइन मॉकअप के लिए उत्तम।", keywords: ["lorem ipsum", "प्लेसहोल्डर टेक्स्ट", "डमी टेक्स्ट जनरेटर", "lipsum", "फिलर टेक्स्ट"], count: "कितने", paragraphs: "अनुच्छेद", sentences: "वाक्य", words: "शब्द", startWith: "“Lorem ipsum” से शुरू करें", generate: "बनाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
