import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "HTML to Text", short: "Strip HTML tags to get clean, readable plain text.", description: "Free HTML-to-text converter. Remove all HTML tags, drop scripts and styles, convert block elements and line breaks to newlines, and decode entities — leaving clean plain text. Runs in your browser.", keywords: ["html to text", "strip html", "remove html tags", "html to plain text", "extract text from html"], placeholder: "Paste HTML here…" },
  pt: { title: "HTML to Text", short: "Strip HTML tags to get clean, readable plain text.", description: "Free HTML-to-text converter. Remove all HTML tags, drop scripts and styles, convert block elements and line breaks to newlines, and decode entities — leaving clean plain text. Runs in your browser.", keywords: ["html to text", "strip html", "remove html tags", "html to plain text", "extract text from html"], placeholder: "Paste HTML here…" },
  id: { title: "HTML to Text", short: "Strip HTML tags to get clean, readable plain text.", description: "Free HTML-to-text converter. Remove all HTML tags, drop scripts and styles, convert block elements and line breaks to newlines, and decode entities — leaving clean plain text. Runs in your browser.", keywords: ["html to text", "strip html", "remove html tags", "html to plain text", "extract text from html"], placeholder: "Paste HTML here…" },

  tr: { title: "HTML'den Metne", short: "Temiz, okunabilir düz metin elde etmek için HTML etiketlerini kaldırın.", description: "Ücretsiz HTML'den metne dönüştürücü. Tüm HTML etiketlerini kaldırın, script ve stilleri atın, blok öğeleri ve satır sonlarını yeni satıra çevirin ve varlıkları çözün — temiz düz metin kalsın. Tarayıcınızda çalışır.", keywords: ["html'den metne", "html ayıkla", "html etiketlerini kaldır", "html düz metne", "htmlden metin çıkar"], placeholder: "HTML'i buraya yapıştırın…" },
  de: { title: "HTML zu Text", short: "Entfernen Sie HTML-Tags für sauberen, lesbaren Klartext.", description: "Kostenloser HTML-zu-Text-Konverter. Entfernen Sie alle HTML-Tags, verwerfen Sie Skripte und Styles, wandeln Sie Blockelemente und Zeilenumbrüche in Newlines um und dekodieren Sie Entitäten – für sauberen Klartext.", keywords: ["html zu text", "html entfernen", "html tags entfernen", "html zu klartext", "text aus html"], placeholder: "HTML hier einfügen…" },
  fr: { title: "HTML vers Texte", short: "Supprimez les balises HTML pour obtenir un texte brut propre et lisible.", description: "Convertisseur HTML-vers-texte gratuit. Supprimez toutes les balises HTML, retirez scripts et styles, convertissez les éléments de bloc et sauts de ligne en retours à la ligne et décodez les entités — pour un texte brut propre.", keywords: ["html vers texte", "supprimer html", "retirer balises html", "html en texte brut", "extraire texte html"], placeholder: "Collez le HTML ici…" },
  es: { title: "HTML a Texto", short: "Elimina las etiquetas HTML para obtener texto plano limpio y legible.", description: "Conversor HTML-a-texto gratuito. Elimina todas las etiquetas HTML, descarta scripts y estilos, convierte elementos de bloque y saltos de línea en nuevas líneas y decodifica entidades — dejando texto plano limpio.", keywords: ["html a texto", "eliminar html", "quitar etiquetas html", "html a texto plano", "extraer texto de html"], placeholder: "Pega el HTML aquí…" },
  it: { title: "HTML in Testo", short: "Rimuovi i tag HTML per ottenere testo semplice pulito e leggibile.", description: "Convertitore HTML-in-testo gratuito. Rimuovi tutti i tag HTML, scarta script e stili, converti gli elementi di blocco e le interruzioni di riga in a capo e decodifica le entità — lasciando testo semplice pulito.", keywords: ["html in testo", "rimuovi html", "rimuovi tag html", "html in testo semplice", "estrai testo da html"], placeholder: "Incolla l'HTML qui…" },
  ar: { title: "HTML إلى نص", short: "أزِل وسوم HTML للحصول على نص عادي نظيف وقابل للقراءة.", description: "محوّل HTML إلى نص مجاني. أزِل كل وسوم HTML، واحذف النصوص البرمجية والأنماط، وحوّل عناصر الكتل وفواصل الأسطر إلى أسطر جديدة، وفك ترميز الكيانات — لتبقى نصًا عاديًا نظيفًا. يعمل في متصفحك.", keywords: ["html إلى نص", "تجريد html", "إزالة وسوم html", "html إلى نص عادي", "استخراج النص من html"], placeholder: "الصق HTML هنا…" },
  ru: { title: "HTML в Текст", short: "Удалите HTML-теги, чтобы получить чистый читаемый текст.", description: "Бесплатный конвертер HTML в текст. Удалите все HTML-теги, отбросьте скрипты и стили, преобразуйте блочные элементы и переносы строк в новые строки и декодируйте сущности — оставив чистый текст. Работает в браузере.", keywords: ["html в текст", "удалить html", "убрать html-теги", "html в обычный текст", "извлечь текст из html"], placeholder: "Вставьте HTML сюда…" },
  zh: { title: "HTML 转文本", short: "去除 HTML 标签，获得干净、可读的纯文本。", description: "免费的 HTML 转文本转换器。移除所有 HTML 标签，丢弃脚本和样式，将块级元素和换行转换为换行符，并解码实体——留下干净的纯文本。在浏览器中运行。", keywords: ["html转文本", "去除html", "移除html标签", "html转纯文本", "从html提取文本"], placeholder: "在此粘贴 HTML…" },
  ja: { title: "HTML をテキストに変換", short: "HTML タグを除去して、きれいで読みやすいプレーンテキストにします。", description: "無料の HTML→テキスト変換ツール。すべての HTML タグを除去し、スクリプトとスタイルを破棄し、ブロック要素と改行を改行に変換し、エンティティをデコードして、きれいなプレーンテキストにします。ブラウザ内で動作します。", keywords: ["html テキスト変換", "html 除去", "html タグ削除", "html プレーンテキスト", "html からテキスト抽出"], placeholder: "ここに HTML を貼り付け…" },
  ko: { title: "HTML을 텍스트로", short: "HTML 태그를 제거하여 깔끔하고 읽기 쉬운 일반 텍스트를 얻습니다.", description: "무료 HTML-텍스트 변환기. 모든 HTML 태그를 제거하고 스크립트와 스타일을 버리며 블록 요소와 줄바꿈을 개행으로 변환하고 엔티티를 디코딩하여 깔끔한 일반 텍스트만 남깁니다. 브라우저에서 실행됩니다.", keywords: ["html을 텍스트로", "html 제거", "html 태그 제거", "html 일반 텍스트", "html에서 텍스트 추출"], placeholder: "여기에 HTML을 붙여넣으세요…" },
  hi: { title: "HTML से टेक्स्ट", short: "साफ, पठनीय सादा टेक्स्ट पाने के लिए HTML टैग हटाएं।", description: "मुफ्त HTML-से-टेक्स्ट कन्वर्टर। सभी HTML टैग हटाएं, स्क्रिप्ट व स्टाइल छोड़ें, ब्लॉक तत्वों व लाइन ब्रेक को नई पंक्तियों में बदलें, और एंटिटी डिकोड करें — साफ सादा टेक्स्ट छोड़ते हुए। ब्राउज़र में चलता है।", keywords: ["html से टेक्स्ट", "html हटाएं", "html टैग हटाएं", "html से सादा टेक्स्ट", "html से टेक्स्ट निकालें"], placeholder: "यहाँ HTML पेस्ट करें…" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
