import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Stopwatch", short: "Millisecond-precision stopwatch with lap times.", description: "Free browser stopwatch. Start, stop, reset and lap with millisecond precision — useful for timing tasks, drills or focus blocks. Runs entirely in your browser.", keywords: ["stopwatch", "lap timer", "ms timer", "browser stopwatch", "millisecond timer"], start: "Start", stop: "Stop", reset: "Reset", lap: "Lap", laps: "Laps" },
  pt: { title: "Cronómetro", short: "Millisecond-precision stopwatch com lap times.", description: "Gratuito - browser stopwatch. Start, stop, reset e lap com millisecond precision â useful para timing tasks, drills ou focus blocks. Runs entirely no seu navegador.", keywords: ["stopwatch", "lap timer", "ms timer", "browser stopwatch", "millisecond timer"], start: "Start", stop: "Stop", reset: "Reset", lap: "Lap", laps: "Laps" },
  id: { title: "Stopwatch", short: "Millisecond-precision stopwatch with lap times.", description: "Gratis - browser stopwatch. Start, stop, reset dan lap with millisecond precision â useful for timing tasks, drills atau focus blocks. Runs entirely di browser Anda.", keywords: ["stopwatch", "lap timer", "ms timer", "browser stopwatch", "millisecond timer"], start: "Start", stop: "Stop", reset: "Reset", lap: "Lap", laps: "Laps" },

  tr: { title: "Kronometre", short: "Milisaniye hassasiyetinde tur sürelerine sahip kronometre.", description: "Ücretsiz tarayıcı kronometresi. Milisaniye hassasiyetinde başlat, durdur, sıfırla ve tur — görevleri, egzersizleri veya odak bloklarını zamanlamak için kullanışlı. Tamamen tarayıcınızda çalışır.", keywords: ["kronometre", "tur zamanlayıcı", "ms zamanlayıcı", "tarayıcı kronometre", "milisaniye zamanlayıcı"], start: "Başlat", stop: "Durdur", reset: "Sıfırla", lap: "Tur", laps: "Turlar" },
  de: { title: "Stoppuhr", short: "Millisekundengenaue Stoppuhr mit Rundenzeiten.", description: "Kostenlose Browser-Stoppuhr. Starten, stoppen, zurücksetzen und Runden mit Millisekundengenauigkeit — nützlich für Aufgaben, Übungen oder Fokusblöcke. Läuft vollständig im Browser.", keywords: ["stoppuhr", "runden timer", "ms timer", "browser stoppuhr", "millisekunden timer"], start: "Start", stop: "Stopp", reset: "Zurücksetzen", lap: "Runde", laps: "Runden" },
  fr: { title: "Chronomètre", short: "Chronomètre à précision milliseconde avec temps au tour.", description: "Chronomètre navigateur gratuit. Démarrer, arrêter, réinitialiser et lap à la milliseconde — utile pour chronométrer des tâches, exercices ou blocs de concentration. Fonctionne entièrement dans votre navigateur.", keywords: ["chronomètre", "minuteur tour", "minuteur ms", "chronomètre navigateur", "minuteur milliseconde"], start: "Démarrer", stop: "Arrêter", reset: "Réinitialiser", lap: "Tour", laps: "Tours" },
  es: { title: "Cronómetro", short: "Cronómetro con precisión de milisegundos y tiempos de vuelta.", description: "Cronómetro navegador gratuito. Iniciar, detener, reiniciar y dar vuelta con precisión de milisegundos — útil para cronometrar tareas, ejercicios o bloques de enfoque. Funciona completamente en tu navegador.", keywords: ["cronómetro", "temporizador vuelta", "temporizador ms", "cronómetro navegador", "temporizador milisegundo"], start: "Iniciar", stop: "Detener", reset: "Reiniciar", lap: "Vuelta", laps: "Vueltas" },
  it: { title: "Cronometro", short: "Cronometro a precisione millisecondo con tempi di giro.", description: "Cronometro browser gratuito. Avvia, ferma, resetta e giro con precisione al millisecondo — utile per cronometrare attività, esercizi o blocchi di concentrazione. Funziona interamente nel browser.", keywords: ["cronometro", "timer giro", "timer ms", "cronometro browser", "timer millisecondo"], start: "Avvia", stop: "Ferma", reset: "Reset", lap: "Giro", laps: "Giri" },
  ar: { title: "ساعة إيقاف", short: "ساعة إيقاف بدقة الميلي ثانية مع أوقات اللفات.", description: "ساعة إيقاف متصفح مجانية. ابدأ وأوقف وأعد الضبط واللفة بدقة الميلي ثانية — مفيدة لتوقيت المهام أو التمارين أو فترات التركيز. تعمل بالكامل في متصفحك.", keywords: ["ساعة إيقاف", "مؤقت اللفة", "مؤقت ms", "ساعة إيقاف المتصفح", "مؤقت الميلي ثانية"], start: "ابدأ", stop: "إيقاف", reset: "إعادة تعيين", lap: "لفة", laps: "اللفات" },
  ru: { title: "Секундомер", short: "Секундомер с миллисекундной точностью и временами кругов.", description: "Бесплатный браузерный секундомер. Старт, стоп, сброс и круг с миллисекундной точностью — полезно для замера задач, упражнений или блоков фокусирования. Работает полностью в браузере.", keywords: ["секундомер", "таймер круга", "ms таймер", "секундомер браузера", "миллисекундный таймер"], start: "Старт", stop: "Стоп", reset: "Сброс", lap: "Круг", laps: "Круги" },
  zh: { title: "秒表", short: "毫秒精度的秒表，支持分段计时。", description: "免费的浏览器秒表。以毫秒精度开始、停止、重置和分段——适用于计时任务、练习或专注时段。完全在浏览器中运行。", keywords: ["秒表", "分段计时器", "毫秒计时器", "浏览器秒表", "毫秒定时器"], start: "开始", stop: "停止", reset: "重置", lap: "分段", laps: "分段" },
  ja: { title: "ストップウォッチ", short: "ミリ秒精度のラップタイム付きストップウォッチ。", description: "無料のブラウザストップウォッチ。ミリ秒精度で開始、停止、リセット、ラップ——タスク、訓練、集中ブロックの計測に便利。すべてブラウザ内で動作します。", keywords: ["ストップウォッチ", "ラップ タイマー", "ms タイマー", "ブラウザ ストップウォッチ", "ミリ秒 タイマー"], start: "開始", stop: "停止", reset: "リセット", lap: "ラップ", laps: "ラップ" },
  ko: { title: "스톱워치", short: "밀리초 정확도의 랩 타임이 있는 스톱워치.", description: "무료 브라우저 스톱워치. 밀리초 정확도로 시작, 정지, 초기화 및 랩 — 작업, 훈련 또는 집중 시간 측정에 유용. 모두 브라우저에서 실행됩니다.", keywords: ["스톱워치", "랩 타이머", "ms 타이머", "브라우저 스톱워치", "밀리초 타이머"], start: "시작", stop: "정지", reset: "초기화", lap: "랩", laps: "랩" },
  hi: { title: "स्टॉपवॉच", short: "मिलीसेकंड परिशुद्धता के साथ लैप टाइम वाली स्टॉपवॉच।", description: "मुफ्त ब्राउज़र स्टॉपवॉच। मिलीसेकंड परिशुद्धता के साथ शुरू, बंद, रीसेट और लैप — कार्यों, अभ्यासों या फोकस ब्लॉकों के समय के लिए उपयोगी। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["स्टॉपवॉच", "लैप टाइमर", "ms टाइमर", "ब्राउज़र स्टॉपवॉच", "मिलीसेकंड टाइमर"], start: "शुरू", stop: "बंद", reset: "रीसेट", lap: "लैप", laps: "लैप्स" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
