import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "PDF Splitter", short: "Extract page ranges from a PDF, in your browser.", description: "Free PDF splitter. Drop a PDF and enter page ranges like 1,3-5,7 to extract those pages into a new PDF — runs entirely in your browser via pdf-lib. Nothing is uploaded.", keywords: ["pdf splitter", "split pdf", "extract pdf pages", "pdf page extractor", "pdf split online"], drop: "Drop a PDF here or click to choose", pages: "Pages (e.g. 1,3-5,7)", totalPages: "Total pages", split: "Extract", download: "Download extracted.pdf" },
  pt: { title: "PDF Splitter", short: "Extract page ranges a partir de a PDF, no seu navegador.", description: "Gratuito - PDF splitter. Drop a PDF e enter page ranges like 1,3-5,7 para extract those pages into a new PDF â runs entirely no seu navegador via pdf-lib. Nothing is uploaded.", keywords: ["pdf splitter", "split pdf", "extract pdf pages", "pdf page extractor", "pdf split online"], drop: "Drop a PDF here or click to choose", pages: "Pages (e.g. 1,3-5,7)", totalPages: "Total pages", split: "Extract", download: "Download extracted.pdf" },
  id: { title: "PDF Splitter", short: "Extract page ranges from a PDF, di browser Anda.", description: "Gratis - PDF splitter. Drop a PDF dan enter page ranges like 1,3-5,7 to extract those pages into a new PDF â runs entirely di browser Anda via pdf-lib. Nothing is uploaded.", keywords: ["pdf splitter", "split pdf", "extract pdf pages", "pdf page extractor", "pdf split online"], drop: "Drop a PDF here or click to choose", pages: "Pages (e.g. 1,3-5,7)", totalPages: "Total pages", split: "Extract", download: "Download extracted.pdf" },

  tr: { title: "PDF Bölücü", short: "Bir PDF'ten sayfa aralıklarını tarayıcınızda çıkarın.", description: "Ücretsiz PDF bölücü. Bir PDF bırakın ve 1,3-5,7 gibi sayfa aralıkları girerek bu sayfaları yeni bir PDF'e çıkarın — tamamen tarayıcınızda pdf-lib ile çalışır. Hiçbir şey yüklenmez.", keywords: ["pdf bölücü", "pdf böl", "pdf sayfaları çıkart", "pdf sayfa çıkarıcı", "online pdf böl"], drop: "Bir PDF bırakın veya seçmek için tıklayın", pages: "Sayfalar (örn. 1,3-5,7)", totalPages: "Toplam sayfa", split: "Çıkart", download: "extracted.pdf indir" },
  de: { title: "PDF-Splitter", short: "Extrahieren Sie Seitenbereiche aus einer PDF im Browser.", description: "Kostenloser PDF-Splitter. Legen Sie eine PDF ab und geben Sie Seitenbereiche wie 1,3-5,7 ein, um diese Seiten in eine neue PDF zu extrahieren — läuft vollständig im Browser über pdf-lib. Nichts wird hochgeladen.", keywords: ["pdf splitter", "pdf teilen", "pdf seiten extrahieren", "pdf seitenextraktor", "pdf split online"], drop: "PDF hier ablegen oder klicken zum Auswählen", pages: "Seiten (z. B. 1,3-5,7)", totalPages: "Gesamtseiten", split: "Extrahieren", download: "extracted.pdf herunterladen" },
  fr: { title: "Diviseur de PDF", short: "Extrayez des plages de pages d'un PDF, dans votre navigateur.", description: "Diviseur de PDF gratuit. Déposez un PDF et saisissez des plages de pages comme 1,3-5,7 pour extraire ces pages dans un nouveau PDF — fonctionne entièrement dans votre navigateur via pdf-lib. Rien n'est envoyé.", keywords: ["diviseur pdf", "diviser pdf", "extraire pages pdf", "extracteur pages pdf", "diviser pdf en ligne"], drop: "Déposez un PDF ici ou cliquez pour choisir", pages: "Pages (ex. 1,3-5,7)", totalPages: "Pages totales", split: "Extraire", download: "Télécharger extracted.pdf" },
  es: { title: "Divisor de PDF", short: "Extrae rangos de páginas de un PDF, en tu navegador.", description: "Divisor de PDF gratuito. Arrastra un PDF e introduce rangos de páginas como 1,3-5,7 para extraer esas páginas en un nuevo PDF — funciona completamente en tu navegador con pdf-lib. Nada se sube.", keywords: ["divisor pdf", "dividir pdf", "extraer páginas pdf", "extractor páginas pdf", "dividir pdf online"], drop: "Arrastra un PDF aquí o haz clic para elegir", pages: "Páginas (p. ej. 1,3-5,7)", totalPages: "Total de páginas", split: "Extraer", download: "Descargar extracted.pdf" },
  it: { title: "Divisore di PDF", short: "Estrai intervalli di pagine da un PDF nel browser.", description: "Divisore di PDF gratuito. Trascina un PDF e inserisci intervalli di pagine come 1,3-5,7 per estrarre quelle pagine in un nuovo PDF — funziona interamente nel browser tramite pdf-lib. Nulla viene caricato.", keywords: ["divisore pdf", "dividi pdf", "estrai pagine pdf", "estrattore pagine pdf", "dividi pdf online"], drop: "Trascina un PDF qui o clicca per scegliere", pages: "Pagine (es. 1,3-5,7)", totalPages: "Pagine totali", split: "Estrai", download: "Scarica extracted.pdf" },
  ar: { title: "أداة تقسيم PDF", short: "استخرج نطاقات الصفحات من PDF في متصفحك.", description: "أداة تقسيم PDF مجانية. أفلِت PDF وأدخل نطاقات صفحات مثل 1,3-5,7 لاستخراج تلك الصفحات إلى PDF جديد — يعمل بالكامل في متصفحك عبر pdf-lib. لا شيء يُرفع.", keywords: ["تقسيم pdf", "قسم pdf", "استخراج صفحات pdf", "مستخرج صفحات pdf", "تقسيم pdf عبر الإنترنت"], drop: "أفلِت ملف PDF هنا أو انقر للاختيار", pages: "الصفحات (مثال 1,3-5,7)", totalPages: "إجمالي الصفحات", split: "استخراج", download: "تنزيل extracted.pdf" },
  ru: { title: "Разделитель PDF", short: "Извлекайте диапазоны страниц из PDF в браузере.", description: "Бесплатный разделитель PDF. Перетащите PDF и введите диапазоны страниц вроде 1,3-5,7, чтобы извлечь их в новый PDF — работает полностью в браузере через pdf-lib. Ничего не загружается.", keywords: ["разделитель pdf", "разделить pdf", "извлечь страницы pdf", "экстрактор страниц pdf", "разделить pdf онлайн"], drop: "Перетащите PDF сюда или нажмите для выбора", pages: "Страницы (напр. 1,3-5,7)", totalPages: "Всего страниц", split: "Извлечь", download: "Скачать extracted.pdf" },
  zh: { title: "PDF 拆分器", short: "在浏览器中从 PDF 中提取页面范围。", description: "免费的 PDF 拆分器。拖入 PDF，输入像 1,3-5,7 这样的页面范围，将这些页面提取到一个新的 PDF——通过 pdf-lib 完全在浏览器中运行。不上传任何内容。", keywords: ["pdf 拆分器", "拆分 pdf", "提取 pdf 页面", "pdf 页面提取器", "在线拆分 pdf"], drop: "将 PDF 拖到此处或点击选择", pages: "页面（例如 1,3-5,7）", totalPages: "总页数", split: "提取", download: "下载 extracted.pdf" },
  ja: { title: "PDF 分割", short: "ブラウザで PDF からページ範囲を抽出。", description: "無料の PDF 分割ツール。PDF をドロップし、1,3-5,7 のようなページ範囲を入力すると、そのページを新しい PDF に抽出します——pdf-lib によりすべてブラウザ内で動作。何もアップロードされません。", keywords: ["pdf 分割", "pdf を分ける", "pdf ページ 抽出", "pdf ページ 抽出器", "オンライン pdf 分割"], drop: "PDF をここにドロップまたはクリックして選択", pages: "ページ（例 1,3-5,7）", totalPages: "総ページ数", split: "抽出", download: "extracted.pdf をダウンロード" },
  ko: { title: "PDF 분할기", short: "브라우저에서 PDF의 페이지 범위를 추출합니다.", description: "무료 PDF 분할기. PDF를 드롭하고 1,3-5,7과 같은 페이지 범위를 입력해 해당 페이지를 새 PDF로 추출하세요 — pdf-lib를 통해 모두 브라우저에서 실행됩니다. 아무것도 업로드되지 않습니다.", keywords: ["pdf 분할기", "pdf 분할", "pdf 페이지 추출", "pdf 페이지 추출기", "온라인 pdf 분할"], drop: "여기에 PDF를 드롭하거나 클릭하여 선택", pages: "페이지 (예: 1,3-5,7)", totalPages: "총 페이지", split: "추출", download: "extracted.pdf 다운로드" },
  hi: { title: "PDF स्प्लिटर", short: "अपने ब्राउज़र में PDF से पेज रेंज निकालें।", description: "मुफ्त PDF स्प्लिटर। एक PDF छोड़ें और 1,3-5,7 जैसी पेज रेंज दर्ज करें ताकि उन पेजों को एक नए PDF में निकाला जा सके — pdf-lib के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है। कुछ भी अपलोड नहीं होता।", keywords: ["pdf स्प्लिटर", "pdf विभाजित करें", "pdf पेज निकालें", "pdf पेज एक्सट्रैक्टर", "ऑनलाइन pdf विभाजित"], drop: "यहाँ एक PDF छोड़ें या चुनने के लिए क्लिक करें", pages: "पेज (उदा. 1,3-5,7)", totalPages: "कुल पेज", split: "निकालें", download: "extracted.pdf डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
