import type { CalculatorI18n } from "@/types/i18n";

const io = (w: string, h: string, tw: string, ar: string, dr: string, sh: string) => ({
  inputs: { width: { label: w }, height: { label: h }, targetWidth: { label: tw } },
  outputs: { aspectRatio: { label: ar }, decimalRatio: { label: dr }, scaledHeight: { label: sh } },
});

const i18n: CalculatorI18n = {
  en: { title: "Aspect Ratio Calculator", short: "Find the simplest aspect ratio and scale dimensions proportionally.", description: "Free aspect ratio calculator. Enter a width and height to get the simplest ratio (like 16:9), the decimal ratio, and the proportional height for a target width when resizing.", keywords: ["aspect ratio calculator", "16:9 calculator", "ratio of width to height", "resize keeping aspect ratio", "screen ratio"], ...io("Width", "Height", "Target width (optional)", "Aspect ratio", "Decimal ratio", "Scaled height"), faq: [{ q: "What is an aspect ratio?", a: "It's the proportional relationship between width and height, written w:h. 1920×1080 reduces to 16:9, the standard widescreen ratio." }, { q: "How do I resize without distortion?", a: "Keep the same ratio: new height = target width × original height ÷ original width. The 'scaled height' output does this for you." }] },
  pt: { title: "Calculadora de Proporção (Aspect Ratio)", short: "Calcule proporções de imagem e vídeo (16:9, 4:3, etc.).", description: "Calculadora gratuita de proporção. Calcule a altura ou largura mantendo a proporção (16:9, 4:3, 21:9, 1:1) original.", keywords: ["proporção tela", "aspect ratio", "16:9", "4:3", "resolução vídeo"], ...io("Width", "Height", "Target width (optional)", "Aspect ratio", "Decimal ratio", "Scaled height"), faq: [{ q: "What is an aspect ratio?", a: "It's the proportional relationship between width and height, written w:h. 1920×1080 reduces to 16:9, the standard widescreen ratio." }, { q: "How do I resize without distortion?", a: "Keep the same ratio: new height = target width × original height ÷ original width. The 'scaled height' output does this for you." }] },
  id: { title: "Kalkulator Rasio Aspek", short: "Hitung rasio aspek gambar dan video (16:9, 4:3, dll).", description: "Kalkulator rasio aspek gratis. Hitung tinggi atau lebar dengan mempertahankan rasio (16:9, 4:3, 21:9, 1:1) asli.", keywords: ["rasio aspek", "aspect ratio", "16:9", "4:3", "resolusi video"], ...io("Width", "Height", "Target width (optional)", "Aspect ratio", "Decimal ratio", "Scaled height"), faq: [{ q: "What is an aspect ratio?", a: "It's the proportional relationship between width and height, written w:h. 1920×1080 reduces to 16:9, the standard widescreen ratio." }, { q: "How do I resize without distortion?", a: "Keep the same ratio: new height = target width × original height ÷ original width. The 'scaled height' output does this for you." }] },

  tr: { title: "En Boy Oranı Hesaplayıcı", short: "En basit en boy oranını bulun ve boyutları orantılı ölçekleyin.", description: "Ücretsiz en boy oranı hesaplayıcı. Genişlik ve yükseklik girerek en basit oranı (16:9 gibi), ondalık oranı ve yeniden boyutlandırırken hedef genişlik için orantılı yüksekliği öğrenin.", keywords: ["en boy oranı hesaplama", "16:9 hesaplama", "genişlik yükseklik oranı", "oranı koruyarak boyutlandırma", "ekran oranı"], ...io("Genişlik", "Yükseklik", "Hedef genişlik (isteğe bağlı)", "En boy oranı", "Ondalık oran", "Ölçekli yükseklik"), faq: [{ q: "En boy oranı nedir?", a: "Genişlik ile yükseklik arasındaki orantısal ilişkidir, g:y yazılır. 1920×1080, standart geniş ekran oranı olan 16:9'a sadeleşir." }, { q: "Bozulma olmadan nasıl boyutlandırırım?", a: "Aynı oranı koruyun: yeni yükseklik = hedef genişlik × orijinal yükseklik ÷ orijinal genişlik. 'Ölçekli yükseklik' çıktısı bunu yapar." }] },
  de: { title: "Seitenverhältnis-Rechner", short: "Das einfachste Seitenverhältnis finden und Maße proportional skalieren.", description: "Kostenloser Seitenverhältnis-Rechner. Geben Sie Breite und Höhe ein, um das einfachste Verhältnis (z. B. 16:9), das Dezimalverhältnis und die proportionale Höhe für eine Zielbreite zu erhalten.", keywords: ["seitenverhältnis rechner", "16:9 rechner", "breite zu höhe", "proportional skalieren", "bildschirmverhältnis"], ...io("Breite", "Höhe", "Zielbreite (optional)", "Seitenverhältnis", "Dezimalverhältnis", "Skalierte Höhe") },
  fr: { title: "Calculateur de Rapport d'Aspect", short: "Trouvez le rapport d'aspect le plus simple et redimensionnez proportionnellement.", description: "Calculateur de rapport d'aspect gratuit. Saisissez une largeur et une hauteur pour obtenir le rapport le plus simple (comme 16:9), le rapport décimal et la hauteur proportionnelle pour une largeur cible.", keywords: ["calculateur rapport d'aspect", "16:9", "rapport largeur hauteur", "redimensionner en gardant le ratio", "ratio écran"], ...io("Largeur", "Hauteur", "Largeur cible (optionnel)", "Rapport d'aspect", "Rapport décimal", "Hauteur mise à l'échelle") },
  es: { title: "Calculadora de Relación de Aspecto", short: "Halla la relación de aspecto más simple y escala dimensiones proporcionalmente.", description: "Calculadora de relación de aspecto gratuita. Introduce ancho y alto para obtener la relación más simple (como 16:9), la relación decimal y el alto proporcional para un ancho objetivo.", keywords: ["calculadora relación de aspecto", "16:9", "relación ancho alto", "redimensionar manteniendo proporción", "relación de pantalla"], ...io("Ancho", "Alto", "Ancho objetivo (opcional)", "Relación de aspecto", "Relación decimal", "Alto escalado") },
  it: { title: "Calcolatore Rapporto d'Aspetto", short: "Trova il rapporto d'aspetto più semplice e ridimensiona proporzionalmente.", description: "Calcolatore di rapporto d'aspetto gratuito. Inserisci larghezza e altezza per ottenere il rapporto più semplice (come 16:9), il rapporto decimale e l'altezza proporzionale per una larghezza obiettivo.", keywords: ["calcolatore rapporto aspetto", "16:9", "rapporto larghezza altezza", "ridimensionare mantenendo rapporto", "rapporto schermo"], ...io("Larghezza", "Altezza", "Larghezza obiettivo (opzionale)", "Rapporto d'aspetto", "Rapporto decimale", "Altezza scalata") },
  ar: { title: "حاسبة نسبة العرض إلى الارتفاع", short: "أوجد أبسط نسبة عرض إلى ارتفاع وقِس الأبعاد بالتناسب.", description: "حاسبة نسبة العرض إلى الارتفاع مجانية. أدخل العرض والارتفاع للحصول على أبسط نسبة (مثل 16:9) والنسبة العشرية والارتفاع المتناسب لعرض مستهدف عند تغيير الحجم.", keywords: ["حاسبة نسبة العرض إلى الارتفاع", "16:9", "نسبة العرض للارتفاع", "تغيير الحجم مع الحفاظ على النسبة", "نسبة الشاشة"], ...io("العرض", "الارتفاع", "العرض المستهدف (اختياري)", "نسبة العرض إلى الارتفاع", "النسبة العشرية", "الارتفاع المقاس") },
  ru: { title: "Калькулятор Соотношения Сторон", short: "Найдите простейшее соотношение сторон и масштабируйте размеры пропорционально.", description: "Бесплатный калькулятор соотношения сторон. Введите ширину и высоту, чтобы получить простейшее соотношение (например 16:9), десятичное соотношение и пропорциональную высоту для целевой ширины.", keywords: ["калькулятор соотношения сторон", "16:9", "отношение ширины к высоте", "масштабирование с сохранением пропорций", "соотношение экрана"], ...io("Ширина", "Высота", "Целевая ширина (необяз.)", "Соотношение сторон", "Десятичное соотношение", "Масштабированная высота") },
  zh: { title: "宽高比计算器", short: "求最简宽高比并按比例缩放尺寸。", description: "免费的宽高比计算器。输入宽度和高度，得到最简比例（如 16:9）、小数比值，以及调整大小时目标宽度对应的等比高度。", keywords: ["宽高比计算器", "16:9", "宽高比例", "保持比例缩放", "屏幕比例"], ...io("宽度", "高度", "目标宽度（可选）", "宽高比", "小数比值", "缩放高度") },
  ja: { title: "アスペクト比計算機", short: "最も簡単なアスペクト比を求め、寸法を比例して拡大縮小します。", description: "無料のアスペクト比計算機。幅と高さを入力すると、最も簡単な比（16:9 など）、小数の比、リサイズ時に目標幅に対応する比例した高さが得られます。", keywords: ["アスペクト比 計算機", "16:9", "幅と高さの比", "比率を保ってリサイズ", "画面比"], ...io("幅", "高さ", "目標幅（任意）", "アスペクト比", "小数比", "スケール後の高さ") },
  ko: { title: "화면 비율 계산기", short: "가장 간단한 화면 비율을 찾고 치수를 비례로 조정합니다.", description: "무료 화면 비율 계산기. 너비와 높이를 입력하면 가장 간단한 비율(예: 16:9), 소수 비율, 크기 조정 시 목표 너비에 대한 비례 높이를 얻을 수 있습니다.", keywords: ["화면 비율 계산기", "16:9", "가로 세로 비율", "비율 유지 크기 조정", "화면비"], ...io("너비", "높이", "목표 너비(선택)", "화면 비율", "소수 비율", "조정된 높이") },
  hi: { title: "आस्पेक्ट रेशियो कैलकुलेटर", short: "सबसे सरल आस्पेक्ट रेशियो ज्ञात करें और आयामों को आनुपातिक रूप से स्केल करें।", description: "मुफ्त आस्पेक्ट रेशियो कैलकुलेटर। चौड़ाई और ऊंचाई दर्ज करें और सबसे सरल अनुपात (जैसे 16:9), दशमलव अनुपात, तथा रीसाइज़ करते समय लक्ष्य चौड़ाई के लिए आनुपातिक ऊंचाई पाएं।", keywords: ["आस्पेक्ट रेशियो कैलकुलेटर", "16:9", "चौड़ाई ऊंचाई अनुपात", "अनुपात बनाए रखते हुए रीसाइज़", "स्क्रीन अनुपात"], ...io("चौड़ाई", "ऊंचाई", "लक्ष्य चौड़ाई (वैकल्पिक)", "आस्पेक्ट रेशियो", "दशमलव अनुपात", "स्केल की ऊंचाई") },
};

export default i18n;
