import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Placeholder Image Generator", short: "Generate lightweight SVG placeholders at any size.", description: "Free placeholder image generator. Pick width, height, label and colours to get an inline SVG placeholder you can copy as a data URL or save as an .svg — no HTTP request needed, runs entirely in your browser.", keywords: ["placeholder image generator", "placeholder svg", "dummy image", "mockup image", "blank image generator"], width: "Width", height: "Height", text: "Label", background: "Background", foreground: "Foreground", svg: "SVG", dataUrl: "Data URL", preview: "Preview", download: "Download SVG" },
  pt: { title: "Placeholder Image Generator", short: "Generate lightweight SVG placeholders at any size.", description: "Free placeholder image generator. Pick width, height, label and colours to get an inline SVG placeholder you can copy as a data URL or save as an .svg — no HTTP request needed, runs entirely in your browser.", keywords: ["placeholder image generator", "placeholder svg", "dummy image", "mockup image", "blank image generator"], width: "Width", height: "Height", text: "Label", background: "Background", foreground: "Foreground", svg: "SVG", dataUrl: "Data URL", preview: "Preview", download: "Download SVG" },
  id: { title: "Placeholder Image Generator", short: "Generate lightweight SVG placeholders at any size.", description: "Free placeholder image generator. Pick width, height, label and colours to get an inline SVG placeholder you can copy as a data URL or save as an .svg — no HTTP request needed, runs entirely in your browser.", keywords: ["placeholder image generator", "placeholder svg", "dummy image", "mockup image", "blank image generator"], width: "Width", height: "Height", text: "Label", background: "Background", foreground: "Foreground", svg: "SVG", dataUrl: "Data URL", preview: "Preview", download: "Download SVG" },

  tr: { title: "Yer Tutucu Görsel Oluşturucu", short: "Herhangi bir boyutta hafif SVG yer tutucular oluşturun.", description: "Ücretsiz yer tutucu görsel oluşturucu. Genişlik, yükseklik, etiket ve renkleri seçerek veri URL'si olarak kopyalayabileceğiniz veya .svg olarak kaydedebileceğiniz satır içi bir SVG yer tutucu alın — HTTP isteği gerektirmez, tamamen tarayıcınızda çalışır.", keywords: ["yer tutucu görsel oluşturucu", "placeholder svg", "sahte görsel", "mockup görsel", "boş görsel oluşturucu"], width: "Genişlik", height: "Yükseklik", text: "Etiket", background: "Arka plan", foreground: "Ön plan", svg: "SVG", dataUrl: "Veri URL'si", preview: "Önizleme", download: "SVG indir" },
  de: { title: "Platzhalter-Bild-Generator", short: "Erzeugen Sie leichte SVG-Platzhalter in beliebiger Größe.", description: "Kostenloser Platzhalter-Bild-Generator. Wählen Sie Breite, Höhe, Beschriftung und Farben, um einen Inline-SVG-Platzhalter zu erhalten, den Sie als Data-URL kopieren oder als .svg speichern können — keine HTTP-Anfrage nötig, läuft vollständig im Browser.", keywords: ["platzhalter bild generator", "platzhalter svg", "dummy bild", "mockup bild", "leeres bild generator"], width: "Breite", height: "Höhe", text: "Beschriftung", background: "Hintergrund", foreground: "Vordergrund", svg: "SVG", dataUrl: "Daten-URL", preview: "Vorschau", download: "SVG herunterladen" },
  fr: { title: "Générateur d'Image Placeholder", short: "Générez des placeholders SVG légers à toute taille.", description: "Générateur d'image placeholder gratuit. Choisissez largeur, hauteur, libellé et couleurs pour obtenir un placeholder SVG en ligne que vous pouvez copier comme data URL ou enregistrer en .svg — pas de requête HTTP, fonctionne entièrement dans votre navigateur.", keywords: ["générateur image placeholder", "placeholder svg", "image fictive", "image mockup", "générateur image vide"], width: "Largeur", height: "Hauteur", text: "Libellé", background: "Fond", foreground: "Premier plan", svg: "SVG", dataUrl: "Data URL", preview: "Aperçu", download: "Télécharger SVG" },
  es: { title: "Generador de Imagen Placeholder", short: "Genera placeholders SVG ligeros en cualquier tamaño.", description: "Generador de imagen placeholder gratuito. Elige ancho, alto, etiqueta y colores para obtener un placeholder SVG en línea que puedes copiar como data URL o guardar como .svg — sin solicitudes HTTP, funciona completamente en tu navegador.", keywords: ["generador imagen placeholder", "placeholder svg", "imagen ficticia", "imagen mockup", "generador imagen vacía"], width: "Ancho", height: "Alto", text: "Etiqueta", background: "Fondo", foreground: "Primer plano", svg: "SVG", dataUrl: "Data URL", preview: "Vista previa", download: "Descargar SVG" },
  it: { title: "Generatore di Immagini Placeholder", short: "Genera placeholder SVG leggeri di qualsiasi dimensione.", description: "Generatore di immagini placeholder gratuito. Scegli larghezza, altezza, etichetta e colori per ottenere un placeholder SVG inline da copiare come data URL o salvare come .svg — nessuna richiesta HTTP, funziona interamente nel browser.", keywords: ["generatore immagine placeholder", "placeholder svg", "immagine fittizia", "immagine mockup", "generatore immagine vuota"], width: "Larghezza", height: "Altezza", text: "Etichetta", background: "Sfondo", foreground: "Primo piano", svg: "SVG", dataUrl: "Data URL", preview: "Anteprima", download: "Scarica SVG" },
  ar: { title: "مولّد صورة Placeholder", short: "أنشئ placeholder خفيفة بصيغة SVG بأي حجم.", description: "مولّد صورة placeholder مجاني. اختر العرض والارتفاع والتسمية والألوان للحصول على placeholder SVG مضمّن يمكنك نسخه كعنوان URL لبيانات أو حفظه كملف .svg — لا حاجة لطلب HTTP، يعمل بالكامل في متصفحك.", keywords: ["مولد صورة placeholder", "placeholder svg", "صورة وهمية", "صورة mockup", "مولد صورة فارغة"], width: "العرض", height: "الارتفاع", text: "التسمية", background: "الخلفية", foreground: "اللون الأمامي", svg: "SVG", dataUrl: "عنوان URL للبيانات", preview: "معاينة", download: "تنزيل SVG" },
  ru: { title: "Генератор изображения-плейсхолдера", short: "Создавайте лёгкие SVG-плейсхолдеры любого размера.", description: "Бесплатный генератор изображения-плейсхолдера. Выберите ширину, высоту, надпись и цвета, чтобы получить встроенный SVG-плейсхолдер для копирования как data URL или сохранения как .svg — без HTTP-запросов, всё в браузере.", keywords: ["генератор плейсхолдер изображения", "placeholder svg", "фиктивное изображение", "мокап изображения", "генератор пустого изображения"], width: "Ширина", height: "Высота", text: "Надпись", background: "Фон", foreground: "Передний план", svg: "SVG", dataUrl: "Data URL", preview: "Превью", download: "Скачать SVG" },
  zh: { title: "占位图生成器", short: "生成任意尺寸的轻量 SVG 占位图。", description: "免费的占位图生成器。选择宽度、高度、文字和颜色，即可获得可作为 data URL 复制或保存为 .svg 的内联 SVG 占位图——无需 HTTP 请求，完全在浏览器中运行。", keywords: ["占位图生成器", "占位 svg", "虚拟图片", "mockup 图片", "空白图片生成器"], width: "宽度", height: "高度", text: "文字", background: "背景", foreground: "前景", svg: "SVG", dataUrl: "Data URL", preview: "预览", download: "下载 SVG" },
  ja: { title: "プレースホルダー画像生成", short: "任意サイズの軽量 SVG プレースホルダーを生成。", description: "無料のプレースホルダー画像生成ツール。幅、高さ、ラベル、色を選ぶと、data URL としてコピーまたは .svg として保存できるインライン SVG プレースホルダーが得られます——HTTP リクエスト不要、すべてブラウザ内で動作します。", keywords: ["プレースホルダー画像 生成", "プレースホルダー svg", "ダミー画像", "モックアップ画像", "空画像 生成"], width: "幅", height: "高さ", text: "ラベル", background: "背景", foreground: "前景", svg: "SVG", dataUrl: "データ URL", preview: "プレビュー", download: "SVG をダウンロード" },
  ko: { title: "플레이스홀더 이미지 생성기", short: "어느 크기든 가벼운 SVG 플레이스홀더를 생성합니다.", description: "무료 플레이스홀더 이미지 생성기. 너비, 높이, 레이블, 색상을 선택해 data URL로 복사하거나 .svg로 저장할 수 있는 인라인 SVG 플레이스홀더를 얻습니다 — HTTP 요청 불필요, 모두 브라우저에서.", keywords: ["플레이스홀더 이미지 생성기", "플레이스홀더 svg", "더미 이미지", "목업 이미지", "빈 이미지 생성기"], width: "너비", height: "높이", text: "레이블", background: "배경", foreground: "전경", svg: "SVG", dataUrl: "데이터 URL", preview: "미리보기", download: "SVG 다운로드" },
  hi: { title: "प्लेसहोल्डर इमेज जनरेटर", short: "किसी भी आकार के हल्के SVG प्लेसहोल्डर बनाएं।", description: "मुफ्त प्लेसहोल्डर इमेज जनरेटर। चौड़ाई, ऊँचाई, लेबल और रंग चुनें और एक इनलाइन SVG प्लेसहोल्डर पाएं जिसे आप data URL के रूप में कॉपी या .svg के रूप में सेव कर सकते हैं — HTTP अनुरोध की आवश्यकता नहीं, पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["प्लेसहोल्डर इमेज जनरेटर", "प्लेसहोल्डर svg", "डमी इमेज", "मॉकअप इमेज", "खाली इमेज जनरेटर"], width: "चौड़ाई", height: "ऊँचाई", text: "लेबल", background: "पृष्ठभूमि", foreground: "अग्रभूमि", svg: "SVG", dataUrl: "डेटा URL", preview: "प्रीव्यू", download: "SVG डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
