import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const KW = ["random mac address generator", "mac address generator", "locally administered mac", "fake mac address", "mac address creator"];

const data = {
  en: { title: "MAC Address Generator", short: "Generate random MAC addresses with your choice of separator, case and locally-administered bit.", description: "Free random MAC address generator. Create one or many MAC addresses with a colon, hyphen or dot separator, upper or lower case, and an optional locally-administered bit. Uses a secure random source and runs in your browser.", keywords: KW, separator: "Separator", colon: "Colon (:)", hyphen: "Hyphen (-)", dot: "Dot (.)", uppercase: "Uppercase", localAdmin: "Locally administered", count: "Count", generate: "Generate" },
  pt: { title: "Gerador de Endereço MAC", short: "Gere endereços MAC aleatórios com sua escolha de separador, caixa e bit administrado localmente.", description: "Gerador de endereço MAC aleatório gratuito. Crie um ou vários endereços MAC com separador de dois-pontos, hífen ou ponto, em maiúsculas ou minúsculas, e um bit administrado localmente opcional. Usa uma fonte aleatória segura e roda no seu navegador.", keywords: KW, separator: "Separador", colon: "Dois-pontos (:)", hyphen: "Hífen (-)", dot: "Ponto (.)", uppercase: "Maiúsculas", localAdmin: "Administrado localmente", count: "Quantidade", generate: "Gerar" },
  id: { title: "Generator Alamat MAC", short: "Hasilkan alamat MAC acak dengan pilihan pemisah, huruf, dan bit yang dikelola lokal.", description: "Generator alamat MAC acak gratis. Buat satu atau banyak alamat MAC dengan pemisah titik dua, tanda hubung, atau titik, huruf besar atau kecil, dan bit yang dikelola lokal opsional. Menggunakan sumber acak yang aman dan berjalan di browser Anda.", keywords: KW, separator: "Pemisah", colon: "Titik dua (:)", hyphen: "Tanda hubung (-)", dot: "Titik (.)", uppercase: "Huruf besar", localAdmin: "Dikelola lokal", count: "Jumlah", generate: "Hasilkan" },

  tr: { title: "MAC Adresi Üreticisi", short: "Ayırıcı, harf büyüklüğü ve yerel olarak yönetilen bit seçiminizle rastgele MAC adresleri üretin.", description: "Ücretsiz rastgele MAC adresi üreticisi. İki nokta, tire veya nokta ayırıcısı, büyük veya küçük harf ve isteğe bağlı yerel olarak yönetilen bit ile bir veya birçok MAC adresi oluşturun. Güvenli bir rastgele kaynak kullanır ve tarayıcınızda çalışır.", keywords: ["rastgele mac adresi üretici", "mac adresi üretici", "yerel yönetilen mac", "sahte mac adresi", "mac adresi oluşturucu"], separator: "Ayırıcı", colon: "İki nokta (:)", hyphen: "Tire (-)", dot: "Nokta (.)", uppercase: "Büyük harf", localAdmin: "Yerel olarak yönetilen", count: "Adet", generate: "Üret" },
  de: { title: "MAC-Adressen-Generator", short: "Erzeugen Sie zufällige MAC-Adressen mit wählbarem Trennzeichen, Groß-/Kleinschreibung und lokal verwaltetem Bit.", description: "Kostenloser MAC-Adressen-Generator. Erstellen Sie eine oder viele MAC-Adressen mit Doppelpunkt-, Bindestrich- oder Punkt-Trennzeichen, in Groß- oder Kleinschreibung und mit optionalem lokal verwaltetem Bit. Verwendet eine sichere Zufallsquelle und läuft in Ihrem Browser.", keywords: ["zufälliger mac generator", "mac adressen generator", "lokal verwaltete mac", "gefälschte mac adresse", "mac adresse erstellen"], separator: "Trennzeichen", colon: "Doppelpunkt (:)", hyphen: "Bindestrich (-)", dot: "Punkt (.)", uppercase: "Großschreibung", localAdmin: "Lokal verwaltet", count: "Anzahl", generate: "Generieren" },
  fr: { title: "Générateur d'Adresse MAC", short: "Générez des adresses MAC aléatoires avec votre choix de séparateur, de casse et de bit administré localement.", description: "Générateur d'adresse MAC aléatoire gratuit. Créez une ou plusieurs adresses MAC avec un séparateur deux-points, tiret ou point, en majuscules ou minuscules, et un bit administré localement optionnel. Utilise une source aléatoire sécurisée et fonctionne dans votre navigateur.", keywords: ["générateur mac aléatoire", "générateur adresse mac", "mac administrée localement", "fausse adresse mac", "créateur adresse mac"], separator: "Séparateur", colon: "Deux-points (:)", hyphen: "Tiret (-)", dot: "Point (.)", uppercase: "Majuscules", localAdmin: "Administré localement", count: "Nombre", generate: "Générer" },
  es: { title: "Generador de Direcciones MAC", short: "Genera direcciones MAC aleatorias con tu elección de separador, mayúsculas y bit administrado localmente.", description: "Generador de direcciones MAC aleatorias gratuito. Crea una o varias direcciones MAC con separador de dos puntos, guion o punto, en mayúsculas o minúsculas, y un bit administrado localmente opcional. Usa una fuente aleatoria segura y se ejecuta en tu navegador.", keywords: ["generador mac aleatorio", "generador dirección mac", "mac administrada localmente", "dirección mac falsa", "creador dirección mac"], separator: "Separador", colon: "Dos puntos (:)", hyphen: "Guion (-)", dot: "Punto (.)", uppercase: "Mayúsculas", localAdmin: "Administrado localmente", count: "Cantidad", generate: "Generar" },
  it: { title: "Generatore di Indirizzi MAC", short: "Genera indirizzi MAC casuali con il separatore, il maiuscolo/minuscolo e il bit amministrato localmente a tua scelta.", description: "Generatore di indirizzi MAC casuali gratuito. Crea uno o più indirizzi MAC con separatore due punti, trattino o punto, in maiuscolo o minuscolo, e un bit amministrato localmente opzionale. Usa una fonte casuale sicura e funziona nel tuo browser.", keywords: ["generatore mac casuale", "generatore indirizzo mac", "mac amministrato localmente", "indirizzo mac falso", "creatore indirizzo mac"], separator: "Separatore", colon: "Due punti (:)", hyphen: "Trattino (-)", dot: "Punto (.)", uppercase: "Maiuscolo", localAdmin: "Amministrato localmente", count: "Quantità", generate: "Genera" },
  ar: { title: "مولّد عناوين MAC", short: "ولّد عناوين MAC عشوائية باختيارك للفاصل وحالة الأحرف وبت الإدارة المحلية.", description: "مولّد عناوين MAC عشوائية مجاني. أنشئ عنوان MAC واحدًا أو عدة عناوين بفاصل نقطتين أو شرطة أو نقطة، بأحرف كبيرة أو صغيرة، وبت إدارة محلية اختياري. يستخدم مصدرًا عشوائيًا آمنًا ويعمل في متصفحك.", keywords: ["مولد mac عشوائي", "مولد عنوان mac", "mac مدار محليًا", "عنوان mac وهمي", "منشئ عنوان mac"], separator: "الفاصل", colon: "نقطتان (:)", hyphen: "شرطة (-)", dot: "نقطة (.)", uppercase: "أحرف كبيرة", localAdmin: "مُدار محليًا", count: "العدد", generate: "توليد" },
  ru: { title: "Генератор MAC-адресов", short: "Генерируйте случайные MAC-адреса с выбором разделителя, регистра и локально-администрируемого бита.", description: "Бесплатный генератор случайных MAC-адресов. Создавайте один или несколько MAC-адресов с разделителем-двоеточием, дефисом или точкой, в верхнем или нижнем регистре и с необязательным локально-администрируемым битом. Использует безопасный случайный источник и работает в браузере.", keywords: ["генератор случайных mac", "генератор mac адресов", "локально администрируемый mac", "поддельный mac адрес", "создание mac адреса"], separator: "Разделитель", colon: "Двоеточие (:)", hyphen: "Дефис (-)", dot: "Точка (.)", uppercase: "Верхний регистр", localAdmin: "Локально администрируемый", count: "Количество", generate: "Сгенерировать" },
  zh: { title: "MAC 地址生成器", short: "生成随机 MAC 地址，可选择分隔符、大小写和本地管理位。", description: "免费的随机 MAC 地址生成器。生成一个或多个 MAC 地址，可使用冒号、连字符或点作为分隔符，选择大写或小写，并可选本地管理位。使用安全的随机源，在浏览器中运行。", keywords: ["随机 mac 生成器", "mac 地址生成器", "本地管理 mac", "虚假 mac 地址", "mac 地址创建器"], separator: "分隔符", colon: "冒号 (:)", hyphen: "连字符 (-)", dot: "点 (.)", uppercase: "大写", localAdmin: "本地管理", count: "数量", generate: "生成" },
  ja: { title: "MAC アドレスジェネレーター", short: "区切り文字・大文字小文字・ローカル管理ビットを選んでランダムな MAC アドレスを生成します。", description: "無料のランダム MAC アドレスジェネレーター。コロン・ハイフン・ドットの区切り文字、大文字または小文字、任意のローカル管理ビットで、1 つまたは複数の MAC アドレスを生成します。安全なランダムソースを使用し、ブラウザ内で動作します。", keywords: ["ランダム mac ジェネレーター", "mac アドレス生成", "ローカル管理 mac", "偽の mac アドレス", "mac アドレス作成"], separator: "区切り文字", colon: "コロン (:)", hyphen: "ハイフン (-)", dot: "ドット (.)", uppercase: "大文字", localAdmin: "ローカル管理", count: "個数", generate: "生成" },
  ko: { title: "MAC 주소 생성기", short: "구분자, 대소문자, 로컬 관리 비트를 선택해 무작위 MAC 주소를 생성합니다.", description: "무료 무작위 MAC 주소 생성기. 콜론, 하이픈 또는 점 구분자, 대문자 또는 소문자, 선택적 로컬 관리 비트로 하나 또는 여러 개의 MAC 주소를 생성합니다. 안전한 무작위 소스를 사용하며 브라우저에서 실행됩니다.", keywords: ["무작위 mac 생성기", "mac 주소 생성기", "로컬 관리 mac", "가짜 mac 주소", "mac 주소 생성"], separator: "구분자", colon: "콜론 (:)", hyphen: "하이픈 (-)", dot: "점 (.)", uppercase: "대문자", localAdmin: "로컬 관리", count: "개수", generate: "생성" },
  hi: { title: "MAC एड्रेस जनरेटर", short: "विभाजक, केस और स्थानीय रूप से प्रबंधित बिट के अपने चयन के साथ यादृच्छिक MAC एड्रेस उत्पन्न करें।", description: "मुफ्त यादृच्छिक MAC एड्रेस जनरेटर। कोलन, हाइफ़न या डॉट विभाजक, अपर या लोअर केस, और एक वैकल्पिक स्थानीय रूप से प्रबंधित बिट के साथ एक या कई MAC एड्रेस बनाएं। एक सुरक्षित यादृच्छिक स्रोत का उपयोग करता है और आपके ब्राउज़र में चलता है।", keywords: ["यादृच्छिक mac जनरेटर", "mac एड्रेस जनरेटर", "स्थानीय प्रबंधित mac", "नकली mac एड्रेस", "mac एड्रेस निर्माता"], separator: "विभाजक", colon: "कोलन (:)", hyphen: "हाइफ़न (-)", dot: "डॉट (.)", uppercase: "अपरकेस", localAdmin: "स्थानीय रूप से प्रबंधित", count: "संख्या", generate: "उत्पन्न करें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
