import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Random Number Generator", short: "Generate random integers in a range, optionally with no repeats.", description: "Free random number generator. Pick a minimum, maximum and how many numbers you need; optionally make them unique (no repeats). Uses the cryptographically-secure Web Crypto API.", keywords: ["random number generator", "rng", "random integer generator", "number picker", "lottery number generator"], min: "Minimum", max: "Maximum", count: "How many", unique: "No repeats", generate: "Generate" },
  pt: { title: "Random Number Generator", short: "Generate random integers in a range, optionally with no repeats.", description: "Free random number generator. Pick a minimum, maximum and how many numbers you need; optionally make them unique (no repeats). Uses the cryptographically-secure Web Crypto API.", keywords: ["random number generator", "rng", "random integer generator", "number picker", "lottery number generator"], min: "Minimum", max: "Maximum", count: "How many", unique: "No repeats", generate: "Generate" },
  id: { title: "Random Number Generator", short: "Generate random integers in a range, optionally with no repeats.", description: "Free random number generator. Pick a minimum, maximum and how many numbers you need; optionally make them unique (no repeats). Uses the cryptographically-secure Web Crypto API.", keywords: ["random number generator", "rng", "random integer generator", "number picker", "lottery number generator"], min: "Minimum", max: "Maximum", count: "How many", unique: "No repeats", generate: "Generate" },

  tr: { title: "Rastgele Sayı Üretici", short: "Bir aralıkta, isteğe bağlı tekrarsız rastgele tam sayılar üretin.", description: "Ücretsiz rastgele sayı üretici. Bir minimum, maksimum ve kaç sayı istediğinizi seçin; isteğe bağlı olarak benzersiz (tekrarsız) yapın. Kriptografik olarak güvenli Web Crypto API kullanır.", keywords: ["rastgele sayı üretici", "rng", "rastgele tam sayı", "sayı seçici", "loto sayı üretici"], min: "Minimum", max: "Maksimum", count: "Adet", unique: "Tekrarsız", generate: "Üret" },
  de: { title: "Zufallszahlen-Generator", short: "Erzeugen Sie zufällige ganze Zahlen in einem Bereich, optional ohne Wiederholungen.", description: "Kostenloser Zufallszahlen-Generator. Wählen Sie Minimum, Maximum und Anzahl; optional eindeutig (ohne Wiederholungen). Nutzt die kryptografisch sichere Web Crypto API.", keywords: ["zufallszahlen generator", "rng", "zufällige ganzzahl", "zahlen wähler", "lottozahlen generator"], min: "Minimum", max: "Maximum", count: "Anzahl", unique: "Ohne Wiederholungen", generate: "Erzeugen" },
  fr: { title: "Générateur de Nombres Aléatoires", short: "Générez des entiers aléatoires dans une plage, sans répétition en option.", description: "Générateur de nombres aléatoires gratuit. Choisissez un minimum, un maximum et combien de nombres ; option sans répétition. Utilise la Web Crypto API cryptographiquement sûre.", keywords: ["générateur de nombres aléatoires", "rng", "entier aléatoire", "sélecteur de nombres", "générateur loto"], min: "Minimum", max: "Maximum", count: "Combien", unique: "Sans répétition", generate: "Générer" },
  es: { title: "Generador de Números Aleatorios", short: "Genera enteros aleatorios en un rango, opcionalmente sin repetir.", description: "Generador de números aleatorios gratuito. Elige mínimo, máximo y cuántos números; opción sin repeticiones. Usa la Web Crypto API criptográficamente segura.", keywords: ["generador de números aleatorios", "rng", "entero aleatorio", "selector de números", "generador de lotería"], min: "Mínimo", max: "Máximo", count: "Cuántos", unique: "Sin repetir", generate: "Generar" },
  it: { title: "Generatore di Numeri Casuali", short: "Genera interi casuali in un intervallo, opzionalmente senza ripetizioni.", description: "Generatore di numeri casuali gratuito. Scegli minimo, massimo e quanti numeri; opzione senza ripetizioni. Usa la Web Crypto API crittograficamente sicura.", keywords: ["generatore di numeri casuali", "rng", "intero casuale", "selettore di numeri", "generatore lotto"], min: "Minimo", max: "Massimo", count: "Quanti", unique: "Senza ripetizioni", generate: "Genera" },
  ar: { title: "مولّد أرقام عشوائية", short: "أنشئ أعدادًا صحيحة عشوائية ضمن نطاق، مع خيار عدم التكرار.", description: "مولّد أرقام عشوائية مجاني. اختر الحد الأدنى والأقصى وعدد الأرقام؛ مع خيار جعلها فريدة (بدون تكرار). يستخدم Web Crypto API الآمنة تشفيريًا.", keywords: ["مولد أرقام عشوائية", "rng", "عدد صحيح عشوائي", "منتقي الأرقام", "مولد أرقام اليانصيب"], min: "الحد الأدنى", max: "الحد الأقصى", count: "العدد", unique: "بدون تكرار", generate: "توليد" },
  ru: { title: "Генератор Случайных Чисел", short: "Генерируйте случайные целые в диапазоне, при желании без повторов.", description: "Бесплатный генератор случайных чисел. Выберите минимум, максимум и количество; опционально без повторов. Использует криптографически стойкий Web Crypto API.", keywords: ["генератор случайных чисел", "rng", "случайное целое", "выбор чисел", "генератор лото"], min: "Минимум", max: "Максимум", count: "Количество", unique: "Без повторов", generate: "Сгенерировать" },
  zh: { title: "随机数生成器", short: "在范围内生成随机整数，可选不重复。", description: "免费的随机数生成器。选择最小值、最大值和数量；可选不重复（唯一）。使用加密安全的 Web Crypto API。", keywords: ["随机数生成器", "rng", "随机整数", "数字选择器", "彩票号码生成器"], min: "最小值", max: "最大值", count: "数量", unique: "不重复", generate: "生成" },
  ja: { title: "乱数ジェネレーター", short: "範囲内の乱数（整数）を生成。重複なしも選べます。", description: "無料の乱数ジェネレーター。最小・最大・個数を選択。重複なし（一意）も選べます。暗号学的に安全な Web Crypto API を使用します。", keywords: ["乱数ジェネレーター", "rng", "ランダム整数", "数字ピッカー", "宝くじ番号生成"], min: "最小", max: "最大", count: "個数", unique: "重複なし", generate: "生成" },
  ko: { title: "난수 생성기", short: "범위 내 무작위 정수를 생성하며 중복 없이 옵션을 제공합니다.", description: "무료 난수 생성기. 최소, 최대, 개수를 선택하고 선택적으로 중복 없이(고유) 생성합니다. 암호학적으로 안전한 Web Crypto API를 사용합니다.", keywords: ["난수 생성기", "rng", "무작위 정수", "숫자 선택기", "로또 번호 생성기"], min: "최소", max: "최대", count: "개수", unique: "중복 없음", generate: "생성" },
  hi: { title: "रैंडम नंबर जनरेटर", short: "किसी रेंज में रैंडम पूर्णांक बनाएं, वैकल्पिक रूप से बिना दोहराव।", description: "मुफ्त रैंडम नंबर जनरेटर। न्यूनतम, अधिकतम और कितने नंबर चाहिए चुनें; वैकल्पिक रूप से अद्वितीय (बिना दोहराव) बनाएं। क्रिप्टोग्राफ़िक रूप से सुरक्षित Web Crypto API का उपयोग करता है।", keywords: ["रैंडम नंबर जनरेटर", "rng", "रैंडम पूर्णांक", "नंबर पिकर", "लॉटरी नंबर जनरेटर"], min: "न्यूनतम", max: "अधिकतम", count: "कितने", unique: "बिना दोहराव", generate: "बनाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
