import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "HTTP Status Codes Reference", short: "Search and look up HTTP status codes and their meanings.", description: "Free HTTP status code reference. Search by number or name to find what a status code like 200, 301, 404 or 500 means, grouped by class (1xx–5xx). Handy for API and web development.", keywords: ["http status codes", "http codes list", "404 meaning", "500 error", "rest api status codes"], searchPlaceholder: "Search by code or name (e.g. 404, gateway)…", noResults: "No matching status codes." },
  tr: { title: "HTTP Durum Kodları Referansı", short: "HTTP durum kodlarını ve anlamlarını arayın ve bulun.", description: "Ücretsiz HTTP durum kodu referansı. Numara veya ada göre arayarak 200, 301, 404 veya 500 gibi bir durum kodunun ne anlama geldiğini sınıfa (1xx–5xx) göre gruplanmış bulun. API ve web geliştirme için kullanışlı.", keywords: ["http durum kodları", "http kodları listesi", "404 anlamı", "500 hatası", "rest api durum kodları"], searchPlaceholder: "Koda veya ada göre ara (örn. 404, gateway)…", noResults: "Eşleşen durum kodu yok." },
  de: { title: "HTTP-Statuscodes-Referenz", short: "HTTP-Statuscodes und ihre Bedeutung suchen und nachschlagen.", description: "Kostenlose HTTP-Statuscode-Referenz. Suchen Sie nach Nummer oder Name, um zu sehen, was ein Code wie 200, 301, 404 oder 500 bedeutet, gruppiert nach Klasse (1xx–5xx). Praktisch für API- und Webentwicklung.", keywords: ["http statuscodes", "http codes liste", "404 bedeutung", "500 fehler", "rest api statuscodes"], searchPlaceholder: "Nach Code oder Name suchen (z. B. 404, gateway)…", noResults: "Keine passenden Statuscodes." },
  fr: { title: "Référence des Codes HTTP", short: "Recherchez et consultez les codes de statut HTTP et leur signification.", description: "Référence gratuite des codes de statut HTTP. Recherchez par numéro ou nom pour savoir ce que signifie un code comme 200, 301, 404 ou 500, groupé par classe (1xx–5xx). Pratique pour le développement API et web.", keywords: ["codes de statut http", "liste codes http", "signification 404", "erreur 500", "codes api rest"], searchPlaceholder: "Recherche par code ou nom (ex. 404, gateway)…", noResults: "Aucun code de statut correspondant." },
  es: { title: "Referencia de Códigos HTTP", short: "Busca y consulta los códigos de estado HTTP y su significado.", description: "Referencia gratuita de códigos de estado HTTP. Busca por número o nombre para saber qué significa un código como 200, 301, 404 o 500, agrupado por clase (1xx–5xx). Útil para desarrollo de API y web.", keywords: ["códigos de estado http", "lista de códigos http", "significado 404", "error 500", "códigos api rest"], searchPlaceholder: "Busca por código o nombre (p. ej. 404, gateway)…", noResults: "No hay códigos de estado coincidentes." },
  it: { title: "Riferimento Codici di Stato HTTP", short: "Cerca e consulta i codici di stato HTTP e il loro significato.", description: "Riferimento gratuito dei codici di stato HTTP. Cerca per numero o nome per scoprire cosa significa un codice come 200, 301, 404 o 500, raggruppato per classe (1xx–5xx). Utile per lo sviluppo di API e web.", keywords: ["codici di stato http", "lista codici http", "significato 404", "errore 500", "codici api rest"], searchPlaceholder: "Cerca per codice o nome (es. 404, gateway)…", noResults: "Nessun codice di stato corrispondente." },
  ar: { title: "مرجع رموز حالة HTTP", short: "ابحث عن رموز حالة HTTP ومعانيها.", description: "مرجع رموز حالة HTTP مجاني. ابحث بالرقم أو الاسم لمعرفة معنى رمز مثل 200 أو 301 أو 404 أو 500، مجمّعًا حسب الفئة (1xx–5xx). مفيد لتطوير واجهات API والويب.", keywords: ["رموز حالة http", "قائمة رموز http", "معنى 404", "خطأ 500", "رموز حالة rest api"], searchPlaceholder: "ابحث بالرمز أو الاسم (مثل 404، gateway)…", noResults: "لا توجد رموز حالة مطابقة." },
  ru: { title: "Справочник Кодов HTTP", short: "Ищите и смотрите коды состояния HTTP и их значения.", description: "Бесплатный справочник кодов состояния HTTP. Ищите по номеру или названию, чтобы узнать, что означает код вроде 200, 301, 404 или 500, сгруппированный по классу (1xx–5xx). Удобно для разработки API и веба.", keywords: ["коды состояния http", "список кодов http", "значение 404", "ошибка 500", "коды rest api"], searchPlaceholder: "Поиск по коду или названию (напр. 404, gateway)…", noResults: "Нет подходящих кодов состояния." },
  zh: { title: "HTTP 状态码参考", short: "搜索并查询 HTTP 状态码及其含义。", description: "免费的 HTTP 状态码参考。按编号或名称搜索，了解 200、301、404 或 500 等状态码的含义，按类别（1xx–5xx）分组。适合 API 和 Web 开发。", keywords: ["http状态码", "http代码列表", "404含义", "500错误", "rest api状态码"], searchPlaceholder: "按代码或名称搜索（如 404、gateway）…", noResults: "没有匹配的状态码。" },
  ja: { title: "HTTP ステータスコード一覧", short: "HTTP ステータスコードとその意味を検索・参照します。", description: "無料の HTTP ステータスコード一覧。番号や名前で検索して、200・301・404・500 などのコードの意味をクラス（1xx〜5xx）別に確認できます。API や Web 開発に便利。", keywords: ["http ステータスコード", "http コード一覧", "404 の意味", "500 エラー", "rest api ステータスコード"], searchPlaceholder: "コードや名前で検索（例: 404, gateway）…", noResults: "一致するステータスコードがありません。" },
  ko: { title: "HTTP 상태 코드 참조", short: "HTTP 상태 코드와 그 의미를 검색하고 찾아봅니다.", description: "무료 HTTP 상태 코드 참조. 번호나 이름으로 검색하여 200, 301, 404, 500 같은 상태 코드의 의미를 클래스(1xx–5xx)별로 확인하세요. API 및 웹 개발에 유용합니다.", keywords: ["http 상태 코드", "http 코드 목록", "404 의미", "500 오류", "rest api 상태 코드"], searchPlaceholder: "코드 또는 이름으로 검색 (예: 404, gateway)…", noResults: "일치하는 상태 코드가 없습니다." },
  hi: { title: "HTTP स्टेटस कोड संदर्भ", short: "HTTP स्टेटस कोड और उनके अर्थ खोजें और देखें।", description: "मुफ्त HTTP स्टेटस कोड संदर्भ। संख्या या नाम से खोजें और जानें कि 200, 301, 404 या 500 जैसे कोड का क्या अर्थ है, श्रेणी (1xx–5xx) के अनुसार समूहित। API और वेब विकास के लिए उपयोगी।", keywords: ["http स्टेटस कोड", "http कोड सूची", "404 अर्थ", "500 त्रुटि", "rest api स्टेटस कोड"], searchPlaceholder: "कोड या नाम से खोजें (जैसे 404, gateway)…", noResults: "कोई मिलान स्टेटस कोड नहीं।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
