import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "UTF-8 Byte Inspector", short: "See each character's code point and UTF-8 / UTF-16 bytes.", description: "Free UTF-8 inspector. Paste any text to see total UTF-8 bytes, UTF-16 code units, and a per-character breakdown showing the Unicode code point and exact byte values — useful for debugging encoding bugs and emoji surrogate pairs.", keywords: ["utf-8 inspector", "utf-8 byte counter", "unicode code point", "utf-16 code units", "byte length of string"], input: "Text", characters: "Characters (JS length)", codePoints: "Code points", utf8Bytes: "UTF-8 bytes", utf16Units: "UTF-16 code units", char: "Char", codePoint: "Code point", utf8: "UTF-8", utf16: "UTF-16" },
  pt: { title: "UTF-8 Byte Inspector", short: "See each character's code point and UTF-8 / UTF-16 bytes.", description: "Free UTF-8 inspector. Paste any text to see total UTF-8 bytes, UTF-16 code units, and a per-character breakdown showing the Unicode code point and exact byte values — useful for debugging encoding bugs and emoji surrogate pairs.", keywords: ["utf-8 inspector", "utf-8 byte counter", "unicode code point", "utf-16 code units", "byte length of string"], input: "Text", characters: "Characters (JS length)", codePoints: "Code points", utf8Bytes: "UTF-8 bytes", utf16Units: "UTF-16 code units", char: "Char", codePoint: "Code point", utf8: "UTF-8", utf16: "UTF-16" },
  id: { title: "UTF-8 Byte Inspector", short: "See each character's code point and UTF-8 / UTF-16 bytes.", description: "Free UTF-8 inspector. Paste any text to see total UTF-8 bytes, UTF-16 code units, and a per-character breakdown showing the Unicode code point and exact byte values — useful for debugging encoding bugs and emoji surrogate pairs.", keywords: ["utf-8 inspector", "utf-8 byte counter", "unicode code point", "utf-16 code units", "byte length of string"], input: "Text", characters: "Characters (JS length)", codePoints: "Code points", utf8Bytes: "UTF-8 bytes", utf16Units: "UTF-16 code units", char: "Char", codePoint: "Code point", utf8: "UTF-8", utf16: "UTF-16" },

  tr: { title: "UTF-8 Bayt İnceleyici", short: "Her karakterin kod noktasını ve UTF-8 / UTF-16 baytlarını görün.", description: "Ücretsiz UTF-8 inceleyici. Herhangi bir metni yapıştırın ve toplam UTF-8 baytlarını, UTF-16 kod birimlerini ve karakter başına Unicode kod noktasını ve tam bayt değerlerini gösteren ayrıntıları görün — kodlama hatalarını ve emoji vekil çiftlerini ayıklamak için kullanışlı.", keywords: ["utf-8 inceleyici", "utf-8 bayt sayacı", "unicode kod noktası", "utf-16 kod birimleri", "dize bayt uzunluğu"], input: "Metin", characters: "Karakter (JS uzunluk)", codePoints: "Kod noktaları", utf8Bytes: "UTF-8 bayt", utf16Units: "UTF-16 kod birimi", char: "Karakter", codePoint: "Kod noktası", utf8: "UTF-8", utf16: "UTF-16" },
  de: { title: "UTF-8-Byte-Inspektor", short: "Sehen Sie für jedes Zeichen den Code-Point und UTF-8- / UTF-16-Bytes.", description: "Kostenloser UTF-8-Inspektor. Fügen Sie einen Text ein, um die gesamten UTF-8-Bytes, UTF-16-Codeeinheiten und eine Zeichen-für-Zeichen-Aufschlüsselung mit Unicode-Codepunkt und exakten Bytewerten zu sehen — nützlich zum Debuggen von Encoding-Bugs und Emoji-Surrogate-Paaren.", keywords: ["utf-8 inspektor", "utf-8 byte zähler", "unicode codepunkt", "utf-16 codeeinheiten", "byte länge string"], input: "Text", characters: "Zeichen (JS-Länge)", codePoints: "Codepunkte", utf8Bytes: "UTF-8-Bytes", utf16Units: "UTF-16-Codeeinheiten", char: "Zeichen", codePoint: "Codepunkt", utf8: "UTF-8", utf16: "UTF-16" },
  fr: { title: "Inspecteur d'Octets UTF-8", short: "Voyez le point de code et les octets UTF-8 / UTF-16 de chaque caractère.", description: "Inspecteur UTF-8 gratuit. Collez n'importe quel texte pour voir le total d'octets UTF-8, les unités de code UTF-16 et une décomposition par caractère montrant le point de code Unicode et les valeurs d'octets exactes — utile pour déboguer les bugs d'encodage et les paires de substituts emoji.", keywords: ["inspecteur utf-8", "compteur octets utf-8", "point de code unicode", "unités de code utf-16", "longueur octets chaîne"], input: "Texte", characters: "Caractères (longueur JS)", codePoints: "Points de code", utf8Bytes: "Octets UTF-8", utf16Units: "Unités UTF-16", char: "Caractère", codePoint: "Point de code", utf8: "UTF-8", utf16: "UTF-16" },
  es: { title: "Inspector de Bytes UTF-8", short: "Ve el punto de código y los bytes UTF-8 / UTF-16 de cada carácter.", description: "Inspector UTF-8 gratuito. Pega cualquier texto para ver el total de bytes UTF-8, unidades de código UTF-16 y un desglose por carácter mostrando el punto de código Unicode y los valores exactos de bytes — útil para depurar bugs de codificación y pares sustitutos de emoji.", keywords: ["inspector utf-8", "contador bytes utf-8", "punto código unicode", "unidades código utf-16", "longitud bytes cadena"], input: "Texto", characters: "Caracteres (longitud JS)", codePoints: "Puntos de código", utf8Bytes: "Bytes UTF-8", utf16Units: "Unidades UTF-16", char: "Carácter", codePoint: "Punto de código", utf8: "UTF-8", utf16: "UTF-16" },
  it: { title: "Ispettore di Byte UTF-8", short: "Vedi il code point e i byte UTF-8 / UTF-16 di ogni carattere.", description: "Ispettore UTF-8 gratuito. Incolla qualsiasi testo per vedere il totale di byte UTF-8, le unità di codice UTF-16 e un'analisi per carattere che mostra il code point Unicode e i valori esatti dei byte — utile per il debug di bug di codifica e coppie surrogate emoji.", keywords: ["ispettore utf-8", "contatore byte utf-8", "code point unicode", "unità codice utf-16", "lunghezza byte stringa"], input: "Testo", characters: "Caratteri (lunghezza JS)", codePoints: "Code point", utf8Bytes: "Byte UTF-8", utf16Units: "Unità UTF-16", char: "Carattere", codePoint: "Code point", utf8: "UTF-8", utf16: "UTF-16" },
  ar: { title: "مفحّص بايتات UTF-8", short: "اعرف نقطة كود كل حرف وبايتاته بـ UTF-8 / UTF-16.", description: "مفحّص UTF-8 مجاني. الصق أي نص لرؤية إجمالي بايتات UTF-8 ووحدات UTF-16 وتحليل لكل حرف يُظهر نقطة كود Unicode وقيم البايت الدقيقة — مفيد لتصحيح أخطاء الترميز وأزواج البديل لرموز الإيموجي.", keywords: ["مفحص utf-8", "عداد بايتات utf-8", "نقطة كود unicode", "وحدات كود utf-16", "طول بايت السلسلة"], input: "النص", characters: "الأحرف (طول JS)", codePoints: "نقاط الكود", utf8Bytes: "بايتات UTF-8", utf16Units: "وحدات UTF-16", char: "الحرف", codePoint: "نقطة الكود", utf8: "UTF-8", utf16: "UTF-16" },
  ru: { title: "Инспектор UTF-8 байтов", short: "Смотрите код-поинт и UTF-8 / UTF-16 байты каждого символа.", description: "Бесплатный инспектор UTF-8. Вставьте любой текст, чтобы увидеть общее число UTF-8 байтов, UTF-16 код-единиц и посимвольную разбивку с Unicode код-поинтом и точными байтовыми значениями — полезно для отладки ошибок кодировки и эмодзи-суррогатных пар.", keywords: ["инспектор utf-8", "счётчик байтов utf-8", "код-поинт unicode", "код-единицы utf-16", "длина байт строки"], input: "Текст", characters: "Символы (длина JS)", codePoints: "Код-поинты", utf8Bytes: "UTF-8 байты", utf16Units: "UTF-16 единицы", char: "Символ", codePoint: "Код-поинт", utf8: "UTF-8", utf16: "UTF-16" },
  zh: { title: "UTF-8 字节检查器", short: "查看每个字符的代码点和 UTF-8 / UTF-16 字节。", description: "免费的 UTF-8 检查器。粘贴任何文本以查看总 UTF-8 字节、UTF-16 代码单元，以及显示 Unicode 代码点和精确字节值的每字符分解——用于调试编码错误和表情符号代理对。", keywords: ["utf-8 检查器", "utf-8 字节计数器", "unicode 代码点", "utf-16 代码单元", "字符串字节长度"], input: "文本", characters: "字符（JS 长度）", codePoints: "代码点", utf8Bytes: "UTF-8 字节", utf16Units: "UTF-16 代码单元", char: "字符", codePoint: "代码点", utf8: "UTF-8", utf16: "UTF-16" },
  ja: { title: "UTF-8 バイト インスペクター", short: "各文字のコードポイントと UTF-8 / UTF-16 バイトを確認。", description: "無料の UTF-8 インスペクター。任意のテキストを貼り付けると、合計 UTF-8 バイト、UTF-16 コード単位、Unicode コードポイントと正確なバイト値を示す文字ごとの内訳が確認できます——エンコーディングのバグや絵文字のサロゲートペアのデバッグに便利。", keywords: ["utf-8 インスペクター", "utf-8 バイト カウンター", "unicode コードポイント", "utf-16 コード単位", "文字列のバイト長"], input: "テキスト", characters: "文字（JS 長さ）", codePoints: "コードポイント", utf8Bytes: "UTF-8 バイト", utf16Units: "UTF-16 コード単位", char: "文字", codePoint: "コードポイント", utf8: "UTF-8", utf16: "UTF-16" },
  ko: { title: "UTF-8 바이트 검사기", short: "각 문자의 코드 포인트와 UTF-8 / UTF-16 바이트를 봅니다.", description: "무료 UTF-8 검사기. 텍스트를 붙여넣어 총 UTF-8 바이트, UTF-16 코드 단위, 그리고 Unicode 코드 포인트와 정확한 바이트 값을 보여주는 문자별 분석을 확인하세요 — 인코딩 버그와 이모지 대리 쌍 디버깅에 유용합니다.", keywords: ["utf-8 검사기", "utf-8 바이트 카운터", "unicode 코드 포인트", "utf-16 코드 단위", "문자열 바이트 길이"], input: "텍스트", characters: "문자 (JS 길이)", codePoints: "코드 포인트", utf8Bytes: "UTF-8 바이트", utf16Units: "UTF-16 코드 단위", char: "문자", codePoint: "코드 포인트", utf8: "UTF-8", utf16: "UTF-16" },
  hi: { title: "UTF-8 बाइट इंस्पेक्टर", short: "हर वर्ण के कोड पॉइंट और UTF-8 / UTF-16 बाइट देखें।", description: "मुफ्त UTF-8 इंस्पेक्टर। किसी भी टेक्स्ट को पेस्ट करें ताकि कुल UTF-8 बाइट, UTF-16 कोड इकाइयाँ और Unicode कोड पॉइंट तथा सटीक बाइट मानों को दिखाने वाला प्रति-वर्ण ब्रेकडाउन देख सकें — एन्कोडिंग बग और इमोजी सरोगेट जोड़े डीबग करने के लिए उपयोगी।", keywords: ["utf-8 इंस्पेक्टर", "utf-8 बाइट काउंटर", "unicode कोड पॉइंट", "utf-16 कोड यूनिट", "स्ट्रिंग बाइट लंबाई"], input: "टेक्स्ट", characters: "वर्ण (JS लंबाई)", codePoints: "कोड पॉइंट", utf8Bytes: "UTF-8 बाइट", utf16Units: "UTF-16 कोड इकाइयाँ", char: "वर्ण", codePoint: "कोड पॉइंट", utf8: "UTF-8", utf16: "UTF-16" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
