import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "HTML Formatter", short: "Beautify and indent HTML, in your browser.", description: "Free HTML beautifier. Paste minified or messy HTML to get an indented version with block tags on their own lines, inline tags on the same line, and `<pre>`/`<script>`/`<style>` preserved.", keywords: ["html formatter", "html beautifier", "format html", "pretty print html", "html indent"], input: "HTML", output: "Formatted HTML" },
  pt: { title: "HTML Formatter", short: "Beautify and indent HTML, in your browser.", description: "Free HTML beautifier. Paste minified or messy HTML to get an indented version with block tags on their own lines, inline tags on the same line, and `<pre>`/`<script>`/`<style>` preserved.", keywords: ["html formatter", "html beautifier", "format html", "pretty print html", "html indent"], input: "HTML", output: "Formatted HTML" },
  id: { title: "HTML Formatter", short: "Beautify and indent HTML, in your browser.", description: "Free HTML beautifier. Paste minified or messy HTML to get an indented version with block tags on their own lines, inline tags on the same line, and `<pre>`/`<script>`/`<style>` preserved.", keywords: ["html formatter", "html beautifier", "format html", "pretty print html", "html indent"], input: "HTML", output: "Formatted HTML" },

  tr: { title: "HTML Biçimlendirici", short: "HTML'i tarayıcınızda güzelleştirin ve girintileyin.", description: "Ücretsiz HTML güzelleştirici. Küçültülmüş veya dağınık HTML yapıştırın; blok etiketleri kendi satırlarında, satır içi etiketler aynı satırda ve `<pre>`/`<script>`/`<style>` korunarak girintili sürüm alın.", keywords: ["html biçimlendirici", "html güzelleştirici", "html biçimlendir", "html yazdır", "html girinti"], input: "HTML", output: "Biçimlendirilmiş HTML" },
  de: { title: "HTML-Formatierer", short: "Verschönern und einrücken Sie HTML im Browser.", description: "Kostenloser HTML-Verschönerer. Fügen Sie minifizierten oder unübersichtlichen HTML-Code ein, um eine eingerückte Version zu erhalten — Block-Tags in eigenen Zeilen, Inline-Tags in derselben Zeile, `<pre>`/`<script>`/`<style>` werden bewahrt.", keywords: ["html formatierer", "html verschönerer", "html formatieren", "html einrücken", "html schön"], input: "HTML", output: "Formatiertes HTML" },
  fr: { title: "Formateur HTML", short: "Embellissez et indentez le HTML dans votre navigateur.", description: "Embellisseur HTML gratuit. Collez du HTML minifié ou désordonné pour obtenir une version indentée — balises bloc sur leurs propres lignes, balises inline sur la même ligne, et `<pre>`/`<script>`/`<style>` préservés.", keywords: ["formateur html", "embellisseur html", "formater html", "indenter html", "html propre"], input: "HTML", output: "HTML formaté" },
  es: { title: "Formateador HTML", short: "Embellece e indenta HTML, en tu navegador.", description: "Embellecedor HTML gratuito. Pega HTML minificado o desordenado para obtener una versión indentada — etiquetas de bloque en sus propias líneas, etiquetas en línea en la misma línea, y `<pre>`/`<script>`/`<style>` preservados.", keywords: ["formateador html", "embellecedor html", "formatear html", "indentar html", "html limpio"], input: "HTML", output: "HTML formateado" },
  it: { title: "Formattatore HTML", short: "Abbellisci e indenta HTML, nel browser.", description: "Abbellitore HTML gratuito. Incolla HTML minificato o disordinato per ottenere una versione indentata — tag di blocco sulle proprie righe, tag inline sulla stessa riga, e `<pre>`/`<script>`/`<style>` preservati.", keywords: ["formattatore html", "abbellitore html", "formattare html", "indentare html", "html pulito"], input: "HTML", output: "HTML formattato" },
  ar: { title: "منسّق HTML", short: "زيّن وأزِح HTML في متصفحك.", description: "مجمّل HTML مجاني. الصق HTML مصغّر أو فوضوي للحصول على نسخة مُزاحة — علامات الكتلة على أسطرها الخاصة، العلامات السطرية على نفس السطر، و `<pre>`/`<script>`/`<style>` محفوظة.", keywords: ["منسق html", "مجمل html", "تنسيق html", "إزاحة html", "html نظيف"], input: "HTML", output: "HTML المنسّق" },
  ru: { title: "Форматер HTML", short: "Украсьте и сделайте отступы в HTML в браузере.", description: "Бесплатный украшатель HTML. Вставьте минифицированный или беспорядочный HTML, чтобы получить версию с отступами — блочные теги на собственных строках, инлайн-теги на той же строке, а `<pre>`/`<script>`/`<style>` сохраняются.", keywords: ["форматер html", "украшатель html", "форматировать html", "отступы html", "красивый html"], input: "HTML", output: "Форматированный HTML" },
  zh: { title: "HTML 格式化工具", short: "在浏览器中美化并缩进 HTML。", description: "免费的 HTML 美化工具。粘贴压缩或杂乱的 HTML 获得缩进版本——块级标签独占一行，行内标签在同一行，并保留 `<pre>`/`<script>`/`<style>`。", keywords: ["html 格式化", "html 美化", "格式化 html", "html 缩进", "html 美化"], input: "HTML", output: "格式化的 HTML" },
  ja: { title: "HTML フォーマッタ", short: "ブラウザで HTML を整形・インデント。", description: "無料の HTML 整形ツール。圧縮された HTML や乱雑な HTML を貼り付けると、ブロックタグは独自の行に、インラインタグは同じ行に、そして `<pre>`/`<script>`/`<style>` は保持されたインデント版が得られます。", keywords: ["html フォーマッタ", "html 整形", "html 整形する", "html インデント", "html 整形 オンライン"], input: "HTML", output: "整形された HTML" },
  ko: { title: "HTML 포맷터", short: "브라우저에서 HTML을 미화하고 들여씁니다.", description: "무료 HTML 미화 도구. 압축되거나 지저분한 HTML을 붙여넣으면 블록 태그는 자체 줄에, 인라인 태그는 같은 줄에, `<pre>`/`<script>`/`<style>`는 보존된 들여쓰기된 버전을 얻습니다.", keywords: ["html 포맷터", "html 미화", "html 포맷", "html 들여쓰기", "html 정리"], input: "HTML", output: "포맷된 HTML" },
  hi: { title: "HTML फॉर्मेटर", short: "अपने ब्राउज़र में HTML को सुंदर बनाएं और इंडेंट करें।", description: "मुफ्त HTML सौंदर्यकर्ता। संक्षिप्त या गन्दा HTML पेस्ट करें और इंडेंट किया हुआ संस्करण पाएं — ब्लॉक टैग अपनी पंक्तियों में, इनलाइन टैग एक ही पंक्ति में, और `<pre>`/`<script>`/`<style>` संरक्षित।", keywords: ["html फॉर्मेटर", "html सौंदर्यकर्ता", "html फॉर्मेट", "html इंडेंट", "html सुंदर"], input: "HTML", output: "फॉर्मेट किया HTML" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
