import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Morse Code Translator", short: "Translate text to Morse code and Morse code back to text.", description: "Free Morse code translator. Convert letters, numbers and punctuation to Morse code (dots and dashes) and decode Morse back to text. Words are separated by a slash. Runs in your browser.", keywords: ["morse code translator", "text to morse", "morse to text", "morse decoder", "morse code converter"], toMorse: "Text → Morse", toText: "Morse → Text", placeholder: "Enter text, or Morse using . - and /…" },
  pt: { title: "Morse Code Translator", short: "Translate text para Morse code e Morse code back para text.", description: "Gratuito - Morse code translator. Converter letters, numbers e punctuation para Morse code (dots e dashes) e descodificar Morse back para text. Words are separated by a slash. Runs no seu navegador.", keywords: ["morse code translator", "text to morse", "morse to text", "morse decoder", "morse code converter"], toMorse: "Text → Morse", toText: "Morse → Text", placeholder: "Enter text, or Morse using . - and /…" },
  id: { title: "Morse Code Translator", short: "Translate text to Morse code dan Morse code back to text.", description: "Gratis - Morse code translator. Konversi letters, numbers dan punctuation to Morse code (dots dan dashes) dan dekode Morse back to text. Words are separated by a slash. Runs di browser Anda.", keywords: ["morse code translator", "text to morse", "morse to text", "morse decoder", "morse code converter"], toMorse: "Text → Morse", toText: "Morse → Text", placeholder: "Enter text, or Morse using . - and /…" },

  tr: { title: "Mors Kodu Çevirici", short: "Metni Mors koduna ve Mors kodunu metne çevirin.", description: "Ücretsiz Mors kodu çevirici. Harfleri, sayıları ve noktalama işaretlerini Mors koduna (nokta ve çizgiler) çevirin ve Mors'u metne geri çözün. Kelimeler eğik çizgiyle ayrılır. Tarayıcınızda çalışır.", keywords: ["mors kodu çevirici", "metinden mors", "morstan metne", "mors çözücü", "mors kodu dönüştürücü"], toMorse: "Metin → Mors", toText: "Mors → Metin", placeholder: "Metin girin veya . - ve / ile Mors…" },
  de: { title: "Morsecode-Übersetzer", short: "Übersetzen Sie Text in Morsecode und Morsecode zurück in Text.", description: "Kostenloser Morsecode-Übersetzer. Wandeln Sie Buchstaben, Zahlen und Satzzeichen in Morsecode (Punkte und Striche) um und dekodieren Sie Morse zurück in Text. Wörter werden durch einen Schrägstrich getrennt.", keywords: ["morsecode übersetzer", "text zu morse", "morse zu text", "morse decoder", "morsecode konverter"], toMorse: "Text → Morse", toText: "Morse → Text", placeholder: "Text eingeben, oder Morse mit . - und /…" },
  fr: { title: "Traducteur de Code Morse", short: "Traduisez du texte en code Morse et du code Morse en texte.", description: "Traducteur de code Morse gratuit. Convertissez lettres, chiffres et ponctuation en code Morse (points et traits) et décodez le Morse en texte. Les mots sont séparés par une barre oblique.", keywords: ["traducteur code morse", "texte en morse", "morse en texte", "décodeur morse", "convertisseur morse"], toMorse: "Texte → Morse", toText: "Morse → Texte", placeholder: "Saisissez du texte, ou du Morse avec . - et /…" },
  es: { title: "Traductor de Código Morse", short: "Traduce texto a código Morse y código Morse a texto.", description: "Traductor de código Morse gratuito. Convierte letras, números y puntuación a código Morse (puntos y rayas) y decodifica Morse a texto. Las palabras se separan con una barra. Se ejecuta en tu navegador.", keywords: ["traductor código morse", "texto a morse", "morse a texto", "decodificador morse", "convertidor morse"], toMorse: "Texto → Morse", toText: "Morse → Texto", placeholder: "Introduce texto, o Morse con . - y /…" },
  it: { title: "Traduttore di Codice Morse", short: "Traduci testo in codice Morse e codice Morse in testo.", description: "Traduttore di codice Morse gratuito. Converti lettere, numeri e punteggiatura in codice Morse (punti e linee) e decodifica il Morse in testo. Le parole sono separate da una barra. Funziona nel browser.", keywords: ["traduttore codice morse", "testo in morse", "morse in testo", "decodificatore morse", "convertitore morse"], toMorse: "Testo → Morse", toText: "Morse → Testo", placeholder: "Inserisci testo, o Morse con . - e /…" },
  ar: { title: "مترجم شيفرة مورس", short: "ترجم النص إلى شيفرة مورس وشيفرة مورس إلى نص.", description: "مترجم شيفرة مورس مجاني. حوّل الأحرف والأرقام وعلامات الترقيم إلى شيفرة مورس (نقاط وشرطات) وفك ترميز مورس إلى نص. تُفصل الكلمات بشرطة مائلة. يعمل في متصفحك.", keywords: ["مترجم شيفرة مورس", "نص إلى مورس", "مورس إلى نص", "فك مورس", "محول مورس"], toMorse: "نص → مورس", toText: "مورس → نص", placeholder: "أدخل نصًا، أو مورس باستخدام . - و /…" },
  ru: { title: "Переводчик Азбуки Морзе", short: "Переводите текст в азбуку Морзе и обратно.", description: "Бесплатный переводчик азбуки Морзе. Преобразуйте буквы, цифры и знаки препинания в код Морзе (точки и тире) и декодируйте Морзе обратно в текст. Слова разделяются косой чертой. Работает в браузере.", keywords: ["переводчик азбуки морзе", "текст в морзе", "морзе в текст", "декодер морзе", "конвертер морзе"], toMorse: "Текст → Морзе", toText: "Морзе → Текст", placeholder: "Введите текст или Морзе с помощью . - и /…" },
  zh: { title: "摩尔斯电码翻译器", short: "将文本翻译为摩尔斯电码，或将摩尔斯电码翻译为文本。", description: "免费的摩尔斯电码翻译器。将字母、数字和标点转换为摩尔斯电码（点和划），并将摩尔斯解码为文本。单词以斜杠分隔。在浏览器中运行。", keywords: ["摩尔斯电码翻译", "文本转摩尔斯", "摩尔斯转文本", "摩尔斯解码", "摩尔斯转换器"], toMorse: "文本 → 摩尔斯", toText: "摩尔斯 → 文本", placeholder: "输入文本，或使用 . - 和 / 的摩尔斯…" },
  ja: { title: "モールス信号翻訳", short: "テキストをモールス信号に、モールス信号をテキストに翻訳します。", description: "無料のモールス信号翻訳ツール。文字・数字・句読点をモールス信号（点と線）に変換し、モールスをテキストにデコードします。単語はスラッシュで区切ります。ブラウザ内で動作します。", keywords: ["モールス信号 翻訳", "テキストからモールス", "モールスからテキスト", "モールス デコード", "モールス 変換"], toMorse: "テキスト → モールス", toText: "モールス → テキスト", placeholder: "テキスト、または . - と / でモールスを入力…" },
  ko: { title: "모스 부호 변환기", short: "텍스트를 모스 부호로, 모스 부호를 텍스트로 번역합니다.", description: "무료 모스 부호 변환기. 문자, 숫자, 문장 부호를 모스 부호(점과 선)로 변환하고 모스를 텍스트로 디코딩합니다. 단어는 슬래시로 구분됩니다. 브라우저에서 실행됩니다.", keywords: ["모스 부호 변환기", "텍스트를 모스로", "모스를 텍스트로", "모스 디코더", "모스 변환"], toMorse: "텍스트 → 모스", toText: "모스 → 텍스트", placeholder: "텍스트, 또는 . - 와 / 로 모스 입력…" },
  hi: { title: "मोर्स कोड अनुवादक", short: "टेक्स्ट को मोर्स कोड में और मोर्स कोड को टेक्स्ट में अनुवाद करें।", description: "मुफ्त मोर्स कोड अनुवादक। अक्षरों, संख्याओं और विराम चिह्नों को मोर्स कोड (बिंदु और डैश) में बदलें और मोर्स को टेक्स्ट में डिकोड करें। शब्द स्लैश से अलग होते हैं। ब्राउज़र में चलता है।", keywords: ["मोर्स कोड अनुवादक", "टेक्स्ट से मोर्स", "मोर्स से टेक्स्ट", "मोर्स डिकोडर", "मोर्स कन्वर्टर"], toMorse: "टेक्स्ट → मोर्स", toText: "मोर्स → टेक्स्ट", placeholder: "टेक्स्ट दर्ज करें, या . - और / से मोर्स…" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
