import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Line Break Remover", short: "Remove or replace line breaks to join wrapped text into one block.", description: "Free line break remover. Join text split across many lines into a single block — replace breaks with spaces, remove them entirely, or keep paragraph gaps. Great for un-wrapping copied PDFs and emails.", keywords: ["remove line breaks", "remove newlines", "join lines", "unwrap text", "strip line breaks"], placeholder: "Paste text with line breaks…", mode: "Mode", spaces: "Replace with spaces", remove: "Remove completely", paragraphs: "Keep paragraphs" },
  pt: { title: "Line Break Remover", short: "Remove or replace line breaks to join wrapped text into one block.", description: "Free line break remover. Join text split across many lines into a single block — replace breaks with spaces, remove them entirely, or keep paragraph gaps. Great for un-wrapping copied PDFs and emails.", keywords: ["remove line breaks", "remove newlines", "join lines", "unwrap text", "strip line breaks"], placeholder: "Paste text with line breaks…", mode: "Mode", spaces: "Replace with spaces", remove: "Remove completely", paragraphs: "Keep paragraphs" },
  id: { title: "Line Break Remover", short: "Remove or replace line breaks to join wrapped text into one block.", description: "Free line break remover. Join text split across many lines into a single block — replace breaks with spaces, remove them entirely, or keep paragraph gaps. Great for un-wrapping copied PDFs and emails.", keywords: ["remove line breaks", "remove newlines", "join lines", "unwrap text", "strip line breaks"], placeholder: "Paste text with line breaks…", mode: "Mode", spaces: "Replace with spaces", remove: "Remove completely", paragraphs: "Keep paragraphs" },

  tr: { title: "Satır Sonu Kaldırıcı", short: "Sarılmış metni tek bloğa birleştirmek için satır sonlarını kaldırın veya değiştirin.", description: "Ücretsiz satır sonu kaldırıcı. Birçok satıra bölünmüş metni tek bloğa birleştirin — satır sonlarını boşlukla değiştirin, tamamen kaldırın veya paragraf boşluklarını koruyun. Kopyalanan PDF ve e-postaları düzeltmek için harika.", keywords: ["satır sonlarını kaldır", "yeni satırları kaldır", "satırları birleştir", "metni düzelt", "satır sonu temizle"], placeholder: "Satır sonlu metni yapıştırın…", mode: "Mod", spaces: "Boşlukla değiştir", remove: "Tamamen kaldır", paragraphs: "Paragrafları koru" },
  de: { title: "Zeilenumbruch-Entferner", short: "Zeilenumbrüche entfernen oder ersetzen, um umbrochenen Text zu einem Block zu verbinden.", description: "Kostenloser Zeilenumbruch-Entferner. Verbinden Sie über viele Zeilen verteilten Text zu einem Block — Umbrüche durch Leerzeichen ersetzen, ganz entfernen oder Absatzabstände behalten. Ideal für kopierte PDFs und E-Mails.", keywords: ["zeilenumbrüche entfernen", "newlines entfernen", "zeilen verbinden", "text entwirren"], placeholder: "Text mit Zeilenumbrüchen einfügen…", mode: "Modus", spaces: "Durch Leerzeichen ersetzen", remove: "Komplett entfernen", paragraphs: "Absätze behalten" },
  fr: { title: "Suppresseur de Sauts de Ligne", short: "Supprimez ou remplacez les sauts de ligne pour réunir un texte en un seul bloc.", description: "Suppresseur de sauts de ligne gratuit. Réunissez un texte réparti sur plusieurs lignes en un seul bloc — remplacez les sauts par des espaces, supprimez-les, ou gardez les sauts de paragraphe. Idéal pour les PDF et e-mails copiés.", keywords: ["supprimer sauts de ligne", "supprimer retours à la ligne", "joindre lignes", "déwrapper texte"], placeholder: "Collez du texte avec des sauts de ligne…", mode: "Mode", spaces: "Remplacer par des espaces", remove: "Supprimer entièrement", paragraphs: "Garder les paragraphes" },
  es: { title: "Eliminador de Saltos de Línea", short: "Elimina o reemplaza saltos de línea para unir texto en un solo bloque.", description: "Eliminador de saltos de línea gratuito. Une texto repartido en muchas líneas en un solo bloque — reemplaza saltos por espacios, elimínalos por completo o conserva los saltos de párrafo. Ideal para PDF y correos copiados.", keywords: ["eliminar saltos de línea", "quitar saltos de línea", "unir líneas", "desenvolver texto"], placeholder: "Pega texto con saltos de línea…", mode: "Modo", spaces: "Reemplazar por espacios", remove: "Eliminar por completo", paragraphs: "Conservar párrafos" },
  it: { title: "Rimozione Interruzioni di Riga", short: "Rimuovi o sostituisci le interruzioni di riga per unire il testo in un unico blocco.", description: "Rimozione interruzioni di riga gratuita. Unisci testo distribuito su più righe in un unico blocco — sostituisci le interruzioni con spazi, rimuovile del tutto o mantieni gli spazi tra paragrafi. Ottimo per PDF ed email copiati.", keywords: ["rimuovi interruzioni di riga", "rimuovi a capo", "unisci righe", "srotolare testo"], placeholder: "Incolla testo con interruzioni di riga…", mode: "Modalità", spaces: "Sostituisci con spazi", remove: "Rimuovi completamente", paragraphs: "Mantieni i paragrafi" },
  ar: { title: "مزيل فواصل الأسطر", short: "أزِل فواصل الأسطر أو استبدلها لدمج النص في كتلة واحدة.", description: "مزيل فواصل أسطر مجاني. ادمج النص الموزّع على أسطر كثيرة في كتلة واحدة — استبدل الفواصل بمسافات، أو أزِلها تمامًا، أو احتفظ بفواصل الفقرات. رائع لملفات PDF والبريد المنسوخ.", keywords: ["إزالة فواصل الأسطر", "إزالة الأسطر الجديدة", "دمج الأسطر", "فرد النص"], placeholder: "الصق نصًا به فواصل أسطر…", mode: "الوضع", spaces: "استبدال بمسافات", remove: "إزالة تامة", paragraphs: "الاحتفاظ بالفقرات" },
  ru: { title: "Удаление Переносов Строк", short: "Удалите или замените переносы строк, чтобы собрать текст в один блок.", description: "Бесплатное удаление переносов строк. Соберите текст, разбитый на много строк, в один блок — замените переносы пробелами, уберите их полностью или сохраните разрывы абзацев. Отлично для скопированных PDF и писем.", keywords: ["удалить переносы строк", "убрать переводы строк", "объединить строки", "развернуть текст"], placeholder: "Вставьте текст с переносами строк…", mode: "Режим", spaces: "Заменить пробелами", remove: "Удалить полностью", paragraphs: "Сохранить абзацы" },
  zh: { title: "换行符移除器", short: "移除或替换换行符，将换行的文本合并为一个整块。", description: "免费的换行符移除器。将分散在多行的文本合并为一个整块——将换行替换为空格、完全删除，或保留段落间隔。适合处理复制的 PDF 和邮件。", keywords: ["移除换行符", "删除换行", "合并行", "展开文本", "去除换行"], placeholder: "粘贴含换行的文本…", mode: "模式", spaces: "替换为空格", remove: "完全删除", paragraphs: "保留段落" },
  ja: { title: "改行削除ツール", short: "改行を削除または置換して、折り返されたテキストを1つのブロックに結合します。", description: "無料の改行削除ツール。多くの行に分かれたテキストを1つのブロックに結合します — 改行をスペースに置換、完全に削除、または段落の区切りを維持。コピーした PDF やメールの整形に最適。", keywords: ["改行削除", "改行を消す", "行を結合", "テキスト展開"], placeholder: "改行を含むテキストを貼り付け…", mode: "モード", spaces: "スペースに置換", remove: "完全に削除", paragraphs: "段落を保持" },
  ko: { title: "줄바꿈 제거기", short: "줄바꿈을 제거하거나 바꿔서 줄바꿈된 텍스트를 한 블록으로 합칩니다.", description: "무료 줄바꿈 제거기. 여러 줄로 나뉜 텍스트를 한 블록으로 합칩니다 — 줄바꿈을 공백으로 바꾸거나 완전히 제거하거나 단락 간격을 유지합니다. 복사한 PDF와 이메일 정리에 적합합니다.", keywords: ["줄바꿈 제거", "개행 제거", "줄 합치기", "텍스트 펼치기"], placeholder: "줄바꿈이 있는 텍스트 붙여넣기…", mode: "모드", spaces: "공백으로 바꾸기", remove: "완전히 제거", paragraphs: "단락 유지" },
  hi: { title: "लाइन ब्रेक रिमूवर", short: "रैप किए गए टेक्स्ट को एक ब्लॉक में जोड़ने के लिए लाइन ब्रेक हटाएं या बदलें।", description: "मुफ्त लाइन ब्रेक रिमूवर। कई पंक्तियों में बंटे टेक्स्ट को एक ब्लॉक में जोड़ें — ब्रेक को स्पेस से बदलें, पूरी तरह हटाएं, या अनुच्छेद अंतराल रखें। कॉपी किए गए PDF और ईमेल को ठीक करने के लिए बढ़िया।", keywords: ["लाइन ब्रेक हटाएं", "न्यूलाइन हटाएं", "पंक्तियाँ जोड़ें", "टेक्स्ट अनरैप"], placeholder: "लाइन ब्रेक वाला टेक्स्ट पेस्ट करें…", mode: "मोड", spaces: "स्पेस से बदलें", remove: "पूरी तरह हटाएं", paragraphs: "अनुच्छेद रखें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
