import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Whitespace Remover", short: "Trim lines, collapse spaces, remove blank lines or strip all whitespace.", description: "Free whitespace cleaner. Trim leading/trailing spaces from each line, collapse multiple spaces into one, remove blank lines, or strip every space. Great for cleaning up pasted text.", keywords: ["whitespace remover", "remove spaces", "trim text", "remove blank lines", "collapse spaces", "clean text"], placeholder: "Paste messy text here…", trimLines: "Trim each line", collapseSpaces: "Collapse multiple spaces", removeBlankLines: "Remove blank lines", removeAllSpaces: "Remove all whitespace" },
  pt: { title: "Removedor de Whitespace", short: "Trim lines, collapse spaces, remove blank lines ou strip all whitespace.", description: "Gratuito - whitespace cleaner. Trim leading/trailing spaces a partir de each line, collapse multiple spaces into one, remove blank lines, ou strip every space. Great para cleaning up pasted text.", keywords: ["whitespace remover", "remove spaces", "trim text", "remove blank lines", "collapse spaces", "clean text"], placeholder: "Paste messy text here…", trimLines: "Trim each line", collapseSpaces: "Collapse multiple spaces", removeBlankLines: "Remove blank lines", removeAllSpaces: "Remove all whitespace" },
  id: { title: "Penghapus Whitespace", short: "Trim lines, collapse spaces, remove blank lines atau strip all whitespace.", description: "Gratis - whitespace cleaner. Trim leading/trailing spaces from each line, collapse multiple spaces into one, remove blank lines, atau strip every space. Great for cleaning up pasted text.", keywords: ["whitespace remover", "remove spaces", "trim text", "remove blank lines", "collapse spaces", "clean text"], placeholder: "Paste messy text here…", trimLines: "Trim each line", collapseSpaces: "Collapse multiple spaces", removeBlankLines: "Remove blank lines", removeAllSpaces: "Remove all whitespace" },

  tr: { title: "Boşluk Temizleyici", short: "Satırları kırpın, boşlukları birleştirin, boş satırları kaldırın veya tüm boşlukları silin.", description: "Ücretsiz boşluk temizleyici. Her satırın baştaki/sondaki boşluklarını kırpın, birden çok boşluğu tek boşluğa indirin, boş satırları kaldırın veya tüm boşlukları silin. Yapıştırılan metni temizlemek için harika.", keywords: ["boşluk temizleyici", "boşlukları kaldır", "metin kırpma", "boş satırları kaldır", "boşlukları birleştir", "metin temizleme"], placeholder: "Dağınık metni buraya yapıştırın…", trimLines: "Her satırı kırp", collapseSpaces: "Birden çok boşluğu birleştir", removeBlankLines: "Boş satırları kaldır", removeAllSpaces: "Tüm boşlukları kaldır" },
  de: { title: "Leerzeichen-Entferner", short: "Zeilen trimmen, Leerzeichen zusammenfassen, leere Zeilen entfernen oder alle Leerzeichen löschen.", description: "Kostenloser Leerzeichen-Reiniger. Trimmen Sie führende/abschließende Leerzeichen, fassen Sie mehrere Leerzeichen zusammen, entfernen Sie leere Zeilen oder löschen Sie jeden Leerraum.", keywords: ["leerzeichen entfernen", "leerzeichen löschen", "text trimmen", "leere zeilen entfernen", "text bereinigen"], placeholder: "Unordentlichen Text hier einfügen…", trimLines: "Jede Zeile trimmen", collapseSpaces: "Mehrere Leerzeichen zusammenfassen", removeBlankLines: "Leere Zeilen entfernen", removeAllSpaces: "Alle Leerzeichen entfernen" },
  fr: { title: "Suppresseur d'Espaces", short: "Élaguez les lignes, fusionnez les espaces, supprimez les lignes vides ou tous les espaces.", description: "Nettoyeur d'espaces gratuit. Élaguez les espaces de début/fin de chaque ligne, fusionnez les espaces multiples, supprimez les lignes vides ou retirez tous les espaces. Idéal pour nettoyer du texte collé.", keywords: ["suppresseur d'espaces", "supprimer les espaces", "élaguer le texte", "supprimer les lignes vides", "nettoyer le texte"], placeholder: "Collez le texte désordonné ici…", trimLines: "Élaguer chaque ligne", collapseSpaces: "Fusionner les espaces multiples", removeBlankLines: "Supprimer les lignes vides", removeAllSpaces: "Supprimer tous les espaces" },
  es: { title: "Eliminador de Espacios", short: "Recorta líneas, colapsa espacios, elimina líneas vacías o quita todos los espacios.", description: "Limpiador de espacios gratuito. Recorta los espacios iniciales/finales de cada línea, colapsa varios espacios en uno, elimina líneas vacías o quita todos los espacios. Ideal para limpiar texto pegado.", keywords: ["eliminador de espacios", "quitar espacios", "recortar texto", "eliminar líneas vacías", "limpiar texto"], placeholder: "Pega el texto desordenado aquí…", trimLines: "Recortar cada línea", collapseSpaces: "Colapsar espacios múltiples", removeBlankLines: "Eliminar líneas vacías", removeAllSpaces: "Quitar todos los espacios" },
  it: { title: "Rimozione Spazi", short: "Taglia le righe, comprimi gli spazi, rimuovi righe vuote o elimina tutti gli spazi.", description: "Pulitore di spazi gratuito. Taglia gli spazi iniziali/finali di ogni riga, comprimi più spazi in uno, rimuovi le righe vuote o elimina ogni spazio. Ottimo per ripulire testo incollato.", keywords: ["rimozione spazi", "rimuovi spazi", "taglia testo", "rimuovi righe vuote", "pulisci testo"], placeholder: "Incolla qui il testo disordinato…", trimLines: "Taglia ogni riga", collapseSpaces: "Comprimi spazi multipli", removeBlankLines: "Rimuovi righe vuote", removeAllSpaces: "Rimuovi tutti gli spazi" },
  ar: { title: "مزيل المسافات", short: "قص الأسطر، وادمج المسافات، واحذف الأسطر الفارغة أو أزل كل المسافات.", description: "منظّف مسافات مجاني. قص المسافات في بداية/نهاية كل سطر، وادمج المسافات المتعددة في واحدة، واحذف الأسطر الفارغة، أو أزل كل مسافة. رائع لتنظيف النص الملصق.", keywords: ["مزيل المسافات", "إزالة المسافات", "قص النص", "حذف الأسطر الفارغة", "تنظيف النص"], placeholder: "الصق النص الفوضوي هنا…", trimLines: "قص كل سطر", collapseSpaces: "دمج المسافات المتعددة", removeBlankLines: "حذف الأسطر الفارغة", removeAllSpaces: "إزالة كل المسافات" },
  ru: { title: "Удаление Пробелов", short: "Обрезайте строки, схлопывайте пробелы, удаляйте пустые строки или все пробелы.", description: "Бесплатный очиститель пробелов. Обрежьте начальные/конечные пробелы каждой строки, схлопните несколько пробелов в один, удалите пустые строки или уберите все пробелы. Отлично для очистки вставленного текста.", keywords: ["удаление пробелов", "убрать пробелы", "обрезать текст", "удалить пустые строки", "очистить текст"], placeholder: "Вставьте неаккуратный текст сюда…", trimLines: "Обрезать каждую строку", collapseSpaces: "Схлопнуть несколько пробелов", removeBlankLines: "Удалить пустые строки", removeAllSpaces: "Удалить все пробелы" },
  zh: { title: "空白删除器", short: "修剪行、合并空格、删除空行或去除所有空白。", description: "免费的空白清理工具。修剪每行首尾空格、将多个空格合并为一个、删除空行或去除所有空白。非常适合清理粘贴的文本。", keywords: ["空白删除", "删除空格", "修剪文本", "删除空行", "清理文本"], placeholder: "在此粘贴杂乱的文本…", trimLines: "修剪每行", collapseSpaces: "合并多个空格", removeBlankLines: "删除空行", removeAllSpaces: "删除所有空白" },
  ja: { title: "空白除去ツール", short: "行のトリム、空白の圧縮、空行の削除、すべての空白の除去を行います。", description: "無料の空白クリーナー。各行の前後の空白をトリム、複数の空白を 1 つに圧縮、空行を削除、またはすべての空白を除去します。貼り付けたテキストの整理に最適。", keywords: ["空白除去", "スペース削除", "テキストトリム", "空行削除", "テキスト整理"], placeholder: "乱雑なテキストをここに貼り付け…", trimLines: "各行をトリム", collapseSpaces: "複数の空白を圧縮", removeBlankLines: "空行を削除", removeAllSpaces: "すべての空白を除去" },
  ko: { title: "공백 제거기", short: "줄 다듬기, 공백 합치기, 빈 줄 제거 또는 모든 공백 제거를 수행합니다.", description: "무료 공백 정리 도구. 각 줄의 앞뒤 공백을 다듬고, 여러 공백을 하나로 합치고, 빈 줄을 제거하거나 모든 공백을 제거합니다. 붙여넣은 텍스트 정리에 적합합니다.", keywords: ["공백 제거기", "공백 삭제", "텍스트 다듬기", "빈 줄 제거", "텍스트 정리"], placeholder: "지저분한 텍스트를 여기에 붙여넣으세요…", trimLines: "각 줄 다듬기", collapseSpaces: "여러 공백 합치기", removeBlankLines: "빈 줄 제거", removeAllSpaces: "모든 공백 제거" },
  hi: { title: "व्हाइटस्पेस रिमूवर", short: "पंक्तियाँ ट्रिम करें, स्पेस मिलाएं, खाली पंक्तियाँ हटाएं या सभी व्हाइटस्पेस हटाएं।", description: "मुफ्त व्हाइटस्पेस क्लीनर। हर पंक्ति के आगे/पीछे के स्पेस ट्रिम करें, कई स्पेस को एक में मिलाएं, खाली पंक्तियाँ हटाएं, या हर स्पेस हटाएं। पेस्ट किए गए टेक्स्ट को साफ करने के लिए बढ़िया।", keywords: ["व्हाइटस्पेस रिमूवर", "स्पेस हटाएं", "टेक्स्ट ट्रिम", "खाली पंक्तियाँ हटाएं", "टेक्स्ट साफ करें"], placeholder: "गड़बड़ टेक्स्ट यहाँ पेस्ट करें…", trimLines: "हर पंक्ति ट्रिम करें", collapseSpaces: "कई स्पेस मिलाएं", removeBlankLines: "खाली पंक्तियाँ हटाएं", removeAllSpaces: "सभी व्हाइटस्पेस हटाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
