import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "HTML Meta Tag Generator", short: "Generate the SEO meta tags for your <head>.", description: "Free HTML meta tag generator. Fill in title, description, keywords, canonical URL and viewport to get a clean SEO-ready <head> snippet — runs entirely in your browser.", keywords: ["meta tag generator", "html meta tags", "seo meta tags", "title description generator", "viewport tag"], titleField: "Title", descriptionField: "Description", keywordsField: "Keywords", author: "Author", canonical: "Canonical URL", robots: "Robots", viewport: "Viewport", charset: "Charset", output: "Meta tags" },
  tr: { title: "HTML Meta Etiketi Oluşturucu", short: "<head> bölümü için SEO meta etiketleri oluşturun.", description: "Ücretsiz HTML meta etiketi oluşturucu. Başlık, açıklama, anahtar kelimeler, kanonik URL ve görünüm alanı girerek temiz, SEO'ya hazır bir <head> parçası alın — tamamen tarayıcınızda çalışır.", keywords: ["meta etiketi oluşturucu", "html meta etiketleri", "seo meta etiketleri", "başlık açıklama oluşturucu", "viewport etiketi"], titleField: "Başlık", descriptionField: "Açıklama", keywordsField: "Anahtar Kelimeler", author: "Yazar", canonical: "Kanonik URL", robots: "Robots", viewport: "Viewport", charset: "Karakter Seti", output: "Meta etiketleri" },
  de: { title: "HTML-Meta-Tag-Generator", short: "Erzeugen Sie die SEO-Meta-Tags für Ihren <head>.", description: "Kostenloser HTML-Meta-Tag-Generator. Füllen Sie Titel, Beschreibung, Schlüsselwörter, kanonische URL und Viewport aus, um einen sauberen SEO-fertigen <head>-Ausschnitt zu erhalten — läuft vollständig im Browser.", keywords: ["meta tag generator", "html meta tags", "seo meta tags", "titel beschreibung generator", "viewport tag"], titleField: "Titel", descriptionField: "Beschreibung", keywordsField: "Schlüsselwörter", author: "Autor", canonical: "Kanonische URL", robots: "Robots", viewport: "Viewport", charset: "Zeichensatz", output: "Meta-Tags" },
  fr: { title: "Générateur de Meta Tags HTML", short: "Générez les meta tags SEO pour votre <head>.", description: "Générateur de meta tags HTML gratuit. Remplissez titre, description, mots-clés, URL canonique et viewport pour obtenir un snippet <head> propre prêt pour le SEO — fonctionne entièrement dans votre navigateur.", keywords: ["générateur meta tag", "meta tags html", "meta tags seo", "générateur titre description", "tag viewport"], titleField: "Titre", descriptionField: "Description", keywordsField: "Mots-clés", author: "Auteur", canonical: "URL canonique", robots: "Robots", viewport: "Viewport", charset: "Charset", output: "Meta tags" },
  es: { title: "Generador de Meta Tags HTML", short: "Genera las meta tags SEO para tu <head>.", description: "Generador de meta tags HTML gratuito. Rellena título, descripción, palabras clave, URL canónica y viewport para obtener un snippet <head> limpio listo para SEO — funciona completamente en tu navegador.", keywords: ["generador meta tag", "meta tags html", "meta tags seo", "generador título descripción", "tag viewport"], titleField: "Título", descriptionField: "Descripción", keywordsField: "Palabras clave", author: "Autor", canonical: "URL canónica", robots: "Robots", viewport: "Viewport", charset: "Charset", output: "Meta tags" },
  it: { title: "Generatore di Meta Tag HTML", short: "Genera i meta tag SEO per il tuo <head>.", description: "Generatore di meta tag HTML gratuito. Compila titolo, descrizione, parole chiave, URL canonico e viewport per ottenere uno snippet <head> pulito pronto per SEO — funziona interamente nel browser.", keywords: ["generatore meta tag", "meta tag html", "meta tag seo", "generatore titolo descrizione", "tag viewport"], titleField: "Titolo", descriptionField: "Descrizione", keywordsField: "Parole chiave", author: "Autore", canonical: "URL canonico", robots: "Robots", viewport: "Viewport", charset: "Charset", output: "Meta tag" },
  ar: { title: "مولّد علامات Meta لـ HTML", short: "أنشئ علامات Meta لتحسين محركات البحث في <head>.", description: "مولّد علامات Meta HTML مجاني. املأ العنوان والوصف والكلمات المفتاحية وعنوان URL الكنسي و viewport للحصول على مقتطف <head> نظيف جاهز لـ SEO — يعمل بالكامل في متصفحك.", keywords: ["مولد علامات meta", "علامات meta html", "علامات meta seo", "مولد عنوان وصف", "علامة viewport"], titleField: "العنوان", descriptionField: "الوصف", keywordsField: "الكلمات المفتاحية", author: "المؤلف", canonical: "URL الكنسي", robots: "Robots", viewport: "Viewport", charset: "الترميز", output: "علامات Meta" },
  ru: { title: "Генератор HTML Meta-тегов", short: "Создайте SEO meta-теги для вашего <head>.", description: "Бесплатный генератор HTML meta-тегов. Заполните title, description, keywords, canonical URL и viewport, чтобы получить чистый SEO-готовый <head>-сниппет — работает полностью в браузере.", keywords: ["генератор meta тегов", "html meta теги", "seo meta теги", "генератор title description", "viewport тег"], titleField: "Заголовок", descriptionField: "Описание", keywordsField: "Ключевые слова", author: "Автор", canonical: "Канонический URL", robots: "Robots", viewport: "Viewport", charset: "Кодировка", output: "Meta-теги" },
  zh: { title: "HTML Meta 标签生成器", short: "为你的 <head> 生成 SEO meta 标签。", description: "免费的 HTML meta 标签生成器。填写标题、描述、关键词、规范 URL 和 viewport，即可获得 SEO 就绪的 <head> 代码片段——完全在浏览器中运行。", keywords: ["meta 标签生成器", "html meta 标签", "seo meta 标签", "标题描述生成器", "viewport 标签"], titleField: "标题", descriptionField: "描述", keywordsField: "关键词", author: "作者", canonical: "规范 URL", robots: "Robots", viewport: "Viewport", charset: "字符集", output: "Meta 标签" },
  ja: { title: "HTML Meta タグ生成", short: "<head> 用の SEO Meta タグを生成。", description: "無料の HTML Meta タグ生成ツール。タイトル、説明、キーワード、正規 URL、ビューポートを記入すると、SEO 対応の <head> スニペットが得られます——すべてブラウザ内で動作します。", keywords: ["meta タグ 生成", "html meta タグ", "seo meta タグ", "タイトル 説明 生成", "viewport タグ"], titleField: "タイトル", descriptionField: "説明", keywordsField: "キーワード", author: "著者", canonical: "正規 URL", robots: "Robots", viewport: "Viewport", charset: "文字セット", output: "Meta タグ" },
  ko: { title: "HTML Meta 태그 생성기", short: "<head>를 위한 SEO Meta 태그를 생성합니다.", description: "무료 HTML Meta 태그 생성기. 제목, 설명, 키워드, 정규 URL, 뷰포트를 입력하면 SEO 준비된 <head> 스니펫을 얻습니다 — 모두 브라우저에서 실행됩니다.", keywords: ["meta 태그 생성기", "html meta 태그", "seo meta 태그", "제목 설명 생성기", "viewport 태그"], titleField: "제목", descriptionField: "설명", keywordsField: "키워드", author: "작성자", canonical: "정규 URL", robots: "Robots", viewport: "Viewport", charset: "문자셋", output: "Meta 태그" },
  hi: { title: "HTML Meta टैग जनरेटर", short: "अपने <head> के लिए SEO meta टैग बनाएं।", description: "मुफ्त HTML meta टैग जनरेटर। शीर्षक, विवरण, कीवर्ड, कैनोनिकल URL और व्यूपोर्ट भरें और SEO-तैयार <head> स्निपेट पाएं — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["meta टैग जनरेटर", "html meta टैग", "seo meta टैग", "शीर्षक विवरण जनरेटर", "viewport टैग"], titleField: "शीर्षक", descriptionField: "विवरण", keywordsField: "कीवर्ड", author: "लेखक", canonical: "कैनोनिकल URL", robots: "Robots", viewport: "Viewport", charset: "वर्ण सेट", output: "Meta टैग" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
