import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JWT Signer (HMAC)", short: "Sign a JWT payload with HS256, HS384 or HS512.", description: "Free JWT signer. Provide a JSON payload, a secret and the HMAC algorithm to produce a signed JSON Web Token (RFC 7519) — generated entirely in your browser via Web Crypto.", keywords: ["jwt signer", "sign jwt", "create jwt", "jwt hs256", "jwt generator online"], algorithm: "Algorithm", secret: "Secret", payload: "Payload (JSON)", token: "JWT", sign: "Sign" },
  tr: { title: "JWT İmzalayıcı (HMAC)", short: "Bir JWT yükünü HS256, HS384 veya HS512 ile imzalayın.", description: "Ücretsiz JWT imzalayıcı. Bir JSON yükü, gizli anahtar ve HMAC algoritmasını verin ve imzalı bir JSON Web Token (RFC 7519) üretin — tamamen tarayıcınızda Web Crypto ile oluşturulur.", keywords: ["jwt imzalayıcı", "jwt imzala", "jwt oluştur", "jwt hs256", "jwt oluşturucu online"], algorithm: "Algoritma", secret: "Gizli anahtar", payload: "Yük (JSON)", token: "JWT", sign: "İmzala" },
  de: { title: "JWT-Signierer (HMAC)", short: "Signieren Sie ein JWT-Payload mit HS256, HS384 oder HS512.", description: "Kostenloser JWT-Signierer. Geben Sie ein JSON-Payload, ein Geheimnis und den HMAC-Algorithmus an, um ein signiertes JSON Web Token (RFC 7519) zu erzeugen — vollständig im Browser über Web Crypto.", keywords: ["jwt signierer", "jwt signieren", "jwt erstellen", "jwt hs256", "jwt generator online"], algorithm: "Algorithmus", secret: "Geheimnis", payload: "Payload (JSON)", token: "JWT", sign: "Signieren" },
  fr: { title: "Signeur JWT (HMAC)", short: "Signez un payload JWT avec HS256, HS384 ou HS512.", description: "Signeur JWT gratuit. Fournissez un payload JSON, un secret et l'algorithme HMAC pour produire un JSON Web Token signé (RFC 7519) — généré entièrement dans votre navigateur via Web Crypto.", keywords: ["signeur jwt", "signer jwt", "créer jwt", "jwt hs256", "générateur jwt en ligne"], algorithm: "Algorithme", secret: "Secret", payload: "Payload (JSON)", token: "JWT", sign: "Signer" },
  es: { title: "Firmador JWT (HMAC)", short: "Firma un payload JWT con HS256, HS384 o HS512.", description: "Firmador JWT gratuito. Proporciona un payload JSON, un secreto y el algoritmo HMAC para producir un JSON Web Token firmado (RFC 7519) — generado completamente en tu navegador vía Web Crypto.", keywords: ["firmador jwt", "firmar jwt", "crear jwt", "jwt hs256", "generador jwt online"], algorithm: "Algoritmo", secret: "Secreto", payload: "Payload (JSON)", token: "JWT", sign: "Firmar" },
  it: { title: "Firmatore JWT (HMAC)", short: "Firma un payload JWT con HS256, HS384 o HS512.", description: "Firmatore JWT gratuito. Fornisci un payload JSON, un segreto e l'algoritmo HMAC per produrre un JSON Web Token firmato (RFC 7519) — generato interamente nel browser tramite Web Crypto.", keywords: ["firmatore jwt", "firmare jwt", "creare jwt", "jwt hs256", "generatore jwt online"], algorithm: "Algoritmo", secret: "Segreto", payload: "Payload (JSON)", token: "JWT", sign: "Firma" },
  ar: { title: "موقّع JWT (HMAC)", short: "وقّع حمولة JWT بـ HS256 أو HS384 أو HS512.", description: "موقّع JWT مجاني. زوّد بحمولة JSON وسر وخوارزمية HMAC لإنتاج JSON Web Token موقّع (RFC 7519) — يتم توليده بالكامل في متصفحك عبر Web Crypto.", keywords: ["موقع jwt", "توقيع jwt", "إنشاء jwt", "jwt hs256", "مولد jwt عبر الإنترنت"], algorithm: "الخوارزمية", secret: "السر", payload: "الحمولة (JSON)", token: "JWT", sign: "توقيع" },
  ru: { title: "Подписант JWT (HMAC)", short: "Подпишите payload JWT с HS256, HS384 или HS512.", description: "Бесплатный подписант JWT. Укажите JSON payload, секрет и HMAC-алгоритм, чтобы сгенерировать подписанный JSON Web Token (RFC 7519) — всё в браузере через Web Crypto.", keywords: ["подпись jwt", "подписать jwt", "создать jwt", "jwt hs256", "генератор jwt онлайн"], algorithm: "Алгоритм", secret: "Секрет", payload: "Payload (JSON)", token: "JWT", sign: "Подписать" },
  zh: { title: "JWT 签名器（HMAC）", short: "使用 HS256、HS384 或 HS512 签名 JWT。", description: "免费的 JWT 签名器。提供 JSON payload、密钥和 HMAC 算法即可生成签名的 JSON Web Token（RFC 7519）——通过 Web Crypto 完全在浏览器中生成。", keywords: ["jwt 签名器", "签名 jwt", "创建 jwt", "jwt hs256", "在线 jwt 生成器"], algorithm: "算法", secret: "密钥", payload: "Payload（JSON）", token: "JWT", sign: "签名" },
  ja: { title: "JWT 署名（HMAC）", short: "HS256、HS384、HS512 で JWT ペイロードに署名。", description: "無料の JWT 署名ツール。JSON ペイロード、シークレット、HMAC アルゴリズムを指定して署名済み JSON Web Token（RFC 7519）を生成します——Web Crypto によりすべてブラウザ内で生成。", keywords: ["jwt 署名", "jwt 署名する", "jwt 作成", "jwt hs256", "jwt 生成 オンライン"], algorithm: "アルゴリズム", secret: "シークレット", payload: "ペイロード（JSON）", token: "JWT", sign: "署名" },
  ko: { title: "JWT 서명기(HMAC)", short: "HS256, HS384 또는 HS512로 JWT 페이로드에 서명합니다.", description: "무료 JWT 서명기. JSON 페이로드, 시크릿, HMAC 알고리즘을 제공해 서명된 JSON Web Token(RFC 7519)을 생성합니다 — Web Crypto를 통해 모두 브라우저에서 생성됩니다.", keywords: ["jwt 서명기", "jwt 서명", "jwt 생성", "jwt hs256", "jwt 생성기 온라인"], algorithm: "알고리즘", secret: "시크릿", payload: "페이로드 (JSON)", token: "JWT", sign: "서명" },
  hi: { title: "JWT साइनर (HMAC)", short: "HS256, HS384 या HS512 के साथ JWT पेलोड पर हस्ताक्षर करें।", description: "मुफ्त JWT साइनर। एक JSON पेलोड, सीक्रेट और HMAC एल्गोरिथम प्रदान करें और एक हस्ताक्षरित JSON Web Token (RFC 7519) उत्पन्न करें — Web Crypto के माध्यम से पूरी तरह आपके ब्राउज़र में जनरेट।", keywords: ["jwt साइनर", "jwt हस्ताक्षर", "jwt बनाएं", "jwt hs256", "jwt जनरेटर ऑनलाइन"], algorithm: "एल्गोरिथम", secret: "सीक्रेट", payload: "पेलोड (JSON)", token: "JWT", sign: "हस्ताक्षर करें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
