import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "SVG Optimizer", short: "Strip metadata and shrink SVG files in your browser.", description: "Free SVG optimizer. Paste or drop an SVG to strip XML declarations, comments, editor metadata, default-value attributes and redundant whitespace — a lightweight cleanup that runs entirely in your browser.", keywords: ["svg optimizer", "svg minifier", "shrink svg", "clean svg", "svg cleanup"], input: "SVG", output: "Optimized SVG", originalSize: "Original", optimizedSize: "Optimized", reduction: "Reduction" },
  pt: { title: "SVG Optimizer", short: "Strip metadata and shrink SVG files in your browser.", description: "Free SVG optimizer. Paste or drop an SVG to strip XML declarations, comments, editor metadata, default-value attributes and redundant whitespace — a lightweight cleanup that runs entirely in your browser.", keywords: ["svg optimizer", "svg minifier", "shrink svg", "clean svg", "svg cleanup"], input: "SVG", output: "Optimized SVG", originalSize: "Original", optimizedSize: "Optimized", reduction: "Reduction" },
  id: { title: "SVG Optimizer", short: "Strip metadata and shrink SVG files in your browser.", description: "Free SVG optimizer. Paste or drop an SVG to strip XML declarations, comments, editor metadata, default-value attributes and redundant whitespace — a lightweight cleanup that runs entirely in your browser.", keywords: ["svg optimizer", "svg minifier", "shrink svg", "clean svg", "svg cleanup"], input: "SVG", output: "Optimized SVG", originalSize: "Original", optimizedSize: "Optimized", reduction: "Reduction" },

  tr: { title: "SVG Optimizasyonu", short: "SVG dosyalarındaki meta verileri kaldırın ve boyutu küçültün.", description: "Ücretsiz SVG optimizasyonu. XML bildirimi, yorumlar, editör meta verileri, varsayılan değerli özellikler ve gereksiz boşlukları kaldırmak için bir SVG yapıştırın veya bırakın — tamamen tarayıcınızda çalışan hafif bir temizleme.", keywords: ["svg optimizasyonu", "svg küçültücü", "svg küçült", "svg temizle", "svg temizleme"], input: "SVG", output: "Optimize edilmiş SVG", originalSize: "Orijinal", optimizedSize: "Optimize", reduction: "Azalma" },
  de: { title: "SVG-Optimierer", short: "Entfernen Sie Metadaten und verkleinern Sie SVG-Dateien im Browser.", description: "Kostenloser SVG-Optimierer. Fügen Sie ein SVG ein oder legen Sie es ab, um XML-Deklarationen, Kommentare, Editor-Metadaten, Standardwert-Attribute und überflüssige Leerzeichen zu entfernen — eine schlanke Bereinigung im Browser.", keywords: ["svg optimierer", "svg verkleinerer", "svg schrumpfen", "svg bereinigen", "svg cleanup"], input: "SVG", output: "Optimiertes SVG", originalSize: "Original", optimizedSize: "Optimiert", reduction: "Reduktion" },
  fr: { title: "Optimiseur SVG", short: "Supprimez les métadonnées et réduisez les fichiers SVG.", description: "Optimiseur SVG gratuit. Collez ou déposez un SVG pour supprimer les déclarations XML, commentaires, métadonnées d'éditeur, attributs de valeur par défaut et espaces redondants — un nettoyage léger qui fonctionne entièrement dans votre navigateur.", keywords: ["optimiseur svg", "minifieur svg", "réduire svg", "nettoyer svg", "svg cleanup"], input: "SVG", output: "SVG optimisé", originalSize: "Original", optimizedSize: "Optimisé", reduction: "Réduction" },
  es: { title: "Optimizador de SVG", short: "Elimina metadatos y reduce archivos SVG en tu navegador.", description: "Optimizador SVG gratuito. Pega o arrastra un SVG para eliminar declaraciones XML, comentarios, metadatos de editor, atributos de valor por defecto y espacios redundantes — una limpieza ligera que funciona completamente en tu navegador.", keywords: ["optimizador svg", "minificador svg", "reducir svg", "limpiar svg", "svg cleanup"], input: "SVG", output: "SVG optimizado", originalSize: "Original", optimizedSize: "Optimizado", reduction: "Reducción" },
  it: { title: "Ottimizzatore SVG", short: "Rimuovi metadati e riduci file SVG nel browser.", description: "Ottimizzatore SVG gratuito. Incolla o trascina un SVG per rimuovere dichiarazioni XML, commenti, metadati editor, attributi di valore predefinito e spazi ridondanti — una pulizia leggera che funziona interamente nel browser.", keywords: ["ottimizzatore svg", "minificatore svg", "ridurre svg", "pulire svg", "svg cleanup"], input: "SVG", output: "SVG ottimizzato", originalSize: "Originale", optimizedSize: "Ottimizzato", reduction: "Riduzione" },
  ar: { title: "محسّن SVG", short: "أزِل البيانات الوصفية وقلّل حجم ملفات SVG في متصفحك.", description: "محسّن SVG مجاني. الصق أو أفلِت ملف SVG لإزالة إعلانات XML والتعليقات وبيانات المحرر الوصفية وسمات القيم الافتراضية والمسافات الزائدة — تنظيف خفيف يعمل بالكامل في متصفحك.", keywords: ["محسن svg", "مصغر svg", "تقليل svg", "تنظيف svg", "svg cleanup"], input: "SVG", output: "SVG المحسّن", originalSize: "الأصلي", optimizedSize: "المحسّن", reduction: "التقليل" },
  ru: { title: "Оптимизатор SVG", short: "Удалите метаданные и уменьшите SVG-файлы в браузере.", description: "Бесплатный оптимизатор SVG. Вставьте или перетащите SVG, чтобы удалить XML-объявления, комментарии, метаданные редактора, атрибуты со значениями по умолчанию и лишние пробелы — лёгкая очистка, работающая полностью в браузере.", keywords: ["оптимизатор svg", "минификатор svg", "уменьшить svg", "очистить svg", "svg cleanup"], input: "SVG", output: "Оптимизированный SVG", originalSize: "Оригинал", optimizedSize: "Оптимизированный", reduction: "Сокращение" },
  zh: { title: "SVG 优化器", short: "在浏览器中删除元数据并压缩 SVG 文件。", description: "免费的 SVG 优化器。粘贴或拖入 SVG，删除 XML 声明、注释、编辑器元数据、默认值属性和多余空白——完全在浏览器中运行的轻量清理。", keywords: ["svg 优化器", "svg 压缩", "缩小 svg", "清理 svg", "svg 清理"], input: "SVG", output: "优化的 SVG", originalSize: "原始", optimizedSize: "优化后", reduction: "缩减" },
  ja: { title: "SVG オプティマイザー", short: "ブラウザ内で SVG ファイルからメタデータを削除して縮小。", description: "無料の SVG オプティマイザー。SVG を貼り付けまたはドロップして、XML 宣言、コメント、エディタメタデータ、デフォルト値属性、冗長な空白を削除——すべてブラウザ内で動作する軽量クリーンアップ。", keywords: ["svg オプティマイザー", "svg ミニファイア", "svg 縮小", "svg クリーン", "svg クリーンアップ"], input: "SVG", output: "最適化された SVG", originalSize: "オリジナル", optimizedSize: "最適化", reduction: "削減" },
  ko: { title: "SVG 옵티마이저", short: "브라우저에서 메타데이터를 제거하고 SVG 파일을 축소합니다.", description: "무료 SVG 옵티마이저. SVG를 붙여넣거나 드롭하여 XML 선언, 주석, 편집기 메타데이터, 기본값 속성, 불필요한 공백을 제거하세요 — 모두 브라우저에서 실행되는 가벼운 정리입니다.", keywords: ["svg 옵티마이저", "svg 미니파이어", "svg 축소", "svg 정리", "svg 클린업"], input: "SVG", output: "최적화된 SVG", originalSize: "원본", optimizedSize: "최적화", reduction: "감소" },
  hi: { title: "SVG ऑप्टिमाइज़र", short: "अपने ब्राउज़र में मेटाडेटा हटाएं और SVG फ़ाइलें छोटी करें।", description: "मुफ्त SVG ऑप्टिमाइज़र। XML घोषणाएँ, टिप्पणियाँ, संपादक मेटाडेटा, डिफ़ॉल्ट-मान विशेषताएँ और अतिरिक्त रिक्त स्थान हटाने के लिए SVG पेस्ट करें या छोड़ें — पूरी तरह आपके ब्राउज़र में चलने वाला हल्का सफाई।", keywords: ["svg ऑप्टिमाइज़र", "svg मिनिफायर", "svg छोटा करें", "svg सफाई", "svg क्लीनअप"], input: "SVG", output: "ऑप्टिमाइज़्ड SVG", originalSize: "मूल", optimizedSize: "ऑप्टिमाइज़्ड", reduction: "कमी" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
