import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Query String Builder", short: "Build a URL-encoded query string from key=value lines.", description: "Free query string builder. Enter parameters as key=value lines and get a properly percent-encoded query string (?a=1&b=2) to append to any URL. Runs in your browser.", keywords: ["query string builder", "url parameters", "build query string", "url params", "querystring generator"], placeholder: "key=value, one per line\npage=2\nsort=name desc" },
  pt: { title: "Query String Builder", short: "Build a URL-encoded query string from key=value lines.", description: "Free query string builder. Enter parameters as key=value lines and get a properly percent-encoded query string (?a=1&b=2) to append to any URL. Runs in your browser.", keywords: ["query string builder", "url parameters", "build query string", "url params", "querystring generator"], placeholder: "key=value, one per line\npage=2\nsort=name desc" },
  id: { title: "Query String Builder", short: "Build a URL-encoded query string from key=value lines.", description: "Free query string builder. Enter parameters as key=value lines and get a properly percent-encoded query string (?a=1&b=2) to append to any URL. Runs in your browser.", keywords: ["query string builder", "url parameters", "build query string", "url params", "querystring generator"], placeholder: "key=value, one per line\npage=2\nsort=name desc" },

  tr: { title: "Sorgu Dizesi Oluşturucu", short: "key=value satırlarından URL-kodlu sorgu dizesi oluşturun.", description: "Ücretsiz sorgu dizesi oluşturucu. Parametreleri key=value satırları olarak girin ve herhangi bir URL'ye eklenecek düzgün yüzde-kodlu sorgu dizesi (?a=1&b=2) alın. Tarayıcınızda çalışır.", keywords: ["sorgu dizesi oluşturucu", "url parametreleri", "sorgu dizesi oluştur", "url params", "querystring üretici"], placeholder: "key=value, her satıra bir tane\npage=2\nsort=name desc" },
  de: { title: "Query-String-Builder", short: "Erstellen Sie einen URL-kodierten Query-String aus key=value-Zeilen.", description: "Kostenloser Query-String-Builder. Geben Sie Parameter als key=value-Zeilen ein und erhalten Sie einen korrekt prozentkodierten Query-String (?a=1&b=2) zum Anhängen an jede URL.", keywords: ["query-string builder", "url parameter", "query-string erstellen", "url params", "querystring generator"], placeholder: "key=value, eine pro Zeile\npage=2\nsort=name desc" },
  fr: { title: "Constructeur de Query String", short: "Construisez une query string encodée à partir de lignes clé=valeur.", description: "Constructeur de query string gratuit. Saisissez des paramètres en lignes clé=valeur et obtenez une query string correctement encodée (?a=1&b=2) à ajouter à n'importe quelle URL.", keywords: ["constructeur query string", "paramètres url", "construire query string", "url params", "générateur querystring"], placeholder: "clé=valeur, une par ligne\npage=2\nsort=name desc" },
  es: { title: "Constructor de Query String", short: "Construye una query string codificada a partir de líneas clave=valor.", description: "Constructor de query string gratuito. Introduce parámetros como líneas clave=valor y obtén una query string correctamente codificada (?a=1&b=2) para añadir a cualquier URL.", keywords: ["constructor query string", "parámetros url", "construir query string", "url params", "generador querystring"], placeholder: "clave=valor, una por línea\npage=2\nsort=name desc" },
  it: { title: "Generatore di Query String", short: "Crea una query string codificata da righe chiave=valore.", description: "Generatore di query string gratuito. Inserisci i parametri come righe chiave=valore e ottieni una query string correttamente codificata (?a=1&b=2) da aggiungere a qualsiasi URL.", keywords: ["generatore query string", "parametri url", "crea query string", "url params", "querystring"], placeholder: "chiave=valore, una per riga\npage=2\nsort=name desc" },
  ar: { title: "منشئ سلسلة الاستعلام", short: "أنشئ سلسلة استعلام مُرمّزة من أسطر key=value.", description: "منشئ سلسلة استعلام مجاني. أدخل المعلمات كأسطر key=value واحصل على سلسلة استعلام مُرمّزة بشكل صحيح (?a=1&b=2) لإلحاقها بأي رابط. يعمل في متصفحك.", keywords: ["منشئ سلسلة الاستعلام", "معلمات url", "إنشاء سلسلة استعلام", "url params", "querystring"], placeholder: "key=value، واحد لكل سطر\npage=2\nsort=name desc" },
  ru: { title: "Построитель Query-строки", short: "Соберите URL-кодированную query-строку из строк ключ=значение.", description: "Бесплатный построитель query-строки. Введите параметры строками ключ=значение и получите корректно процентно-кодированную query-строку (?a=1&b=2) для добавления к любому URL.", keywords: ["построитель query строки", "параметры url", "собрать query строку", "url params", "querystring"], placeholder: "ключ=значение, по одному в строке\npage=2\nsort=name desc" },
  zh: { title: "查询字符串构建器", short: "从 key=value 行构建 URL 编码的查询字符串。", description: "免费的查询字符串构建器。以 key=value 行输入参数，即可得到正确百分号编码的查询字符串（?a=1&b=2），可附加到任意 URL。在浏览器中运行。", keywords: ["查询字符串构建器", "url参数", "构建查询字符串", "url params", "querystring生成"], placeholder: "key=value，每行一个\npage=2\nsort=name desc" },
  ja: { title: "クエリ文字列ビルダー", short: "key=value の行から URL エンコードされたクエリ文字列を作成します。", description: "無料のクエリ文字列ビルダー。パラメータを key=value の行で入力すると、任意の URL に追加できる正しくパーセントエンコードされたクエリ文字列（?a=1&b=2）が得られます。", keywords: ["クエリ文字列 ビルダー", "url パラメータ", "クエリ文字列 作成", "url params", "querystring 生成"], placeholder: "key=value、1行に1つ\npage=2\nsort=name desc" },
  ko: { title: "쿼리 문자열 빌더", short: "key=value 줄에서 URL 인코딩된 쿼리 문자열을 만듭니다.", description: "무료 쿼리 문자열 빌더. 매개변수를 key=value 줄로 입력하면 어떤 URL에도 붙일 수 있는 올바르게 퍼센트 인코딩된 쿼리 문자열(?a=1&b=2)을 얻습니다. 브라우저에서 실행됩니다.", keywords: ["쿼리 문자열 빌더", "url 매개변수", "쿼리 문자열 만들기", "url params", "querystring 생성"], placeholder: "key=value, 한 줄에 하나\npage=2\nsort=name desc" },
  hi: { title: "क्वेरी स्ट्रिंग बिल्डर", short: "key=value पंक्तियों से URL-एन्कोडेड क्वेरी स्ट्रिंग बनाएं।", description: "मुफ्त क्वेरी स्ट्रिंग बिल्डर। पैरामीटर को key=value पंक्तियों के रूप में दर्ज करें और किसी भी URL में जोड़ने के लिए सही ढंग से परसेंट-एन्कोडेड क्वेरी स्ट्रिंग (?a=1&b=2) पाएं। ब्राउज़र में चलता है।", keywords: ["क्वेरी स्ट्रिंग बिल्डर", "url पैरामीटर", "क्वेरी स्ट्रिंग बनाएं", "url params", "querystring जनरेटर"], placeholder: "key=value, प्रति पंक्ति एक\npage=2\nsort=name desc" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
