import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "What's My IP", short: "See your public IP address plus location, ISP and ASN.", description: "Free what's-my-IP tool. Instantly shows your public IP address along with approximate location, ISP/organisation, ASN and timezone, with a map link — all from your browser.", keywords: ["what is my ip", "my ip address", "public ip lookup", "find my ip", "ip location"], yourIp: "Your IP address", location: "Location", isp: "ISP / Organisation", asn: "ASN", timezone: "Timezone", map: "View on map", refresh: "Refresh", unavailable: "Lookup unavailable. The IP service may be rate-limited or blocked by your network." },
  nl: { title: "What's My IP", short: "See your public IP address plus location, ISP and ASN.", description: "Gratis what's-my-IP tool. Direct shows your public IP address along with approximate location, ISP/organisation, ASN and timezone, with a map link — all from uw browser.", keywords: ["what is my ip", "my ip address", "public ip lookup", "find my ip", "ip location"], yourIp: "Your IP address", location: "Location", isp: "ISP / Organisation", asn: "ASN", timezone: "Tijdzone", map: "View on map", refresh: "Refresh", unavailable: "Opzoeken unavailable. The IP service may be rate-limited or blocked by your network." },

  pl: { title: "What's My IP", short: "See your public IP address plus location, ISP and ASN.", description: "Darmowy what's-my-IP narzędzie. Natychmiast shows your public IP address along with approximate location, ISP/organisation, ASN and timezone, with a map link — all from Twoja przeglądarka.", keywords: ["what is my ip", "my ip address", "public ip lookup", "find my ip", "ip location"], yourIp: "Your IP address", location: "Location", isp: "ISP / Organisation", asn: "ASN", timezone: "Strefa Czasowa", map: "View on map", refresh: "Refresh", unavailable: "Wyszukaj unavailable. The IP service may be rate-limited or blocked by your network." },
  pt: { title: "What's My IP", short: "See your public IP address plus location, ISP e ASN.", description: "Gratuito - what's-my-IP tool. Instantly shows your public IP address along with approximate location, ISP/organisation, ASN e timezone, with a map link â todos a partir de seu browser.", keywords: ["what is my ip", "my ip address", "public ip lookup", "find my ip", "ip location"], yourIp: "Seu endereço IP", location: "Localização", isp: "ISP / Organização", asn: "ASN", timezone: "Fuso horário", map: "Ver no mapa", refresh: "Atualizar", unavailable: "Consulta indisponível. O serviço de IP pode estar limitado ou bloqueado pela sua rede." },
  id: { title: "What's My IP", short: "See your public IP address plus location, ISP dan ASN.", description: "Gratis - what's-my-IP tool. Instantly shows your public IP address along with approximate location, ISP/organisation, ASN dan timezone, with a map link â semua from Anda browser.", keywords: ["what is my ip", "my ip address", "public ip lookup", "find my ip", "ip location"], yourIp: "Alamat IP Anda", location: "Lokasi", isp: "ISP / Organisasi", asn: "ASN", timezone: "Zona waktu", map: "Lihat di peta", refresh: "Segarkan", unavailable: "Pencarian tidak tersedia. Layanan IP mungkin dibatasi atau diblokir oleh jaringan Anda." },

  tr: { title: "IP Adresim Nedir", short: "Genel IP adresinizi, konumunuzu, ISS'nizi ve ASN'nizi görün.", description: "Ücretsiz IP adresim aracı. Genel IP adresinizi yaklaşık konum, ISS/kuruluş, ASN ve saat dilimiyle birlikte anında gösterir; harita bağlantısıyla — tamamen tarayıcınızdan.", keywords: ["ip adresim nedir", "ip adresim", "genel ip sorgu", "ip bul", "ip konum"], yourIp: "IP adresiniz", location: "Konum", isp: "ISS / Kuruluş", asn: "ASN", timezone: "Saat dilimi", map: "Haritada gör", refresh: "Yenile", unavailable: "Sorgu kullanılamıyor. IP hizmeti hız sınırlı olabilir veya ağınız tarafından engellenmiş olabilir." },
  de: { title: "Was ist meine IP", short: "Sehen Sie Ihre öffentliche IP-Adresse samt Standort, ISP und ASN.", description: "Kostenloses Was-ist-meine-IP-Tool. Zeigt sofort Ihre öffentliche IP-Adresse samt ungefährem Standort, ISP/Organisation, ASN und Zeitzone mit Kartenlink — alles im Browser.", keywords: ["was ist meine ip", "meine ip adresse", "öffentliche ip abfrage", "ip finden", "ip standort"], yourIp: "Ihre IP-Adresse", location: "Standort", isp: "ISP / Organisation", asn: "ASN", timezone: "Zeitzone", map: "Auf Karte ansehen", refresh: "Aktualisieren", unavailable: "Abfrage nicht verfügbar. Der IP-Dienst ist möglicherweise gedrosselt oder von Ihrem Netzwerk blockiert." },
  fr: { title: "Quelle est mon IP", short: "Voyez votre adresse IP publique, sa localisation, le FAI et l'ASN.", description: "Outil quelle-est-mon-IP gratuit. Affiche instantanément votre adresse IP publique avec localisation approximative, FAI/organisation, ASN et fuseau horaire, avec un lien carte — depuis votre navigateur.", keywords: ["quelle est mon ip", "mon adresse ip", "ip publique", "trouver mon ip", "localisation ip"], yourIp: "Votre adresse IP", location: "Localisation", isp: "FAI / Organisation", asn: "ASN", timezone: "Fuseau horaire", map: "Voir sur la carte", refresh: "Actualiser", unavailable: "Recherche indisponible. Le service IP est peut-être limité ou bloqué par votre réseau." },
  es: { title: "Cuál es mi IP", short: "Mira tu IP pública con ubicación, ISP y ASN.", description: "Herramienta cuál-es-mi-IP gratuita. Muestra al instante tu dirección IP pública con ubicación aproximada, ISP/organización, ASN y zona horaria, con un enlace al mapa — desde tu navegador.", keywords: ["cuál es mi ip", "mi dirección ip", "ip pública", "encontrar mi ip", "ubicación ip"], yourIp: "Tu dirección IP", location: "Ubicación", isp: "ISP / Organización", asn: "ASN", timezone: "Zona horaria", map: "Ver en el mapa", refresh: "Actualizar", unavailable: "Consulta no disponible. El servicio de IP puede estar limitado o bloqueado por tu red." },
  it: { title: "Qual è il mio IP", short: "Visualizza il tuo IP pubblico con posizione, ISP e ASN.", description: "Strumento qual-è-il-mio-IP gratuito. Mostra subito il tuo indirizzo IP pubblico con posizione approssimativa, ISP/organizzazione, ASN e fuso orario, con un link alla mappa — dal tuo browser.", keywords: ["qual è il mio ip", "mio indirizzo ip", "ip pubblico", "trova il mio ip", "posizione ip"], yourIp: "Il tuo indirizzo IP", location: "Posizione", isp: "ISP / Organizzazione", asn: "ASN", timezone: "Fuso orario", map: "Vedi sulla mappa", refresh: "Aggiorna", unavailable: "Ricerca non disponibile. Il servizio IP potrebbe essere limitato o bloccato dalla tua rete." },
  ar: { title: "ما هو عنوان IP الخاص بي", short: "اعرف عنوان IP العام مع الموقع ومزود الخدمة و ASN.", description: "أداة مجانية لمعرفة عنوان IP الخاص بك. تعرض فورًا عنوان IP العام مع الموقع التقريبي ومزود الخدمة/المؤسسة و ASN والمنطقة الزمنية، مع رابط خريطة — من متصفحك.", keywords: ["ما هو عنوان ip الخاص بي", "عنوان ip الخاص بي", "بحث ip العام", "اعثر على ip", "موقع ip"], yourIp: "عنوان IP الخاص بك", location: "الموقع", isp: "مزود الخدمة / المؤسسة", asn: "ASN", timezone: "المنطقة الزمنية", map: "عرض على الخريطة", refresh: "تحديث", unavailable: "البحث غير متاح. قد تكون خدمة IP محدودة المعدل أو محظورة من شبكتك." },
  ru: { title: "Какой у меня IP", short: "Узнайте свой публичный IP-адрес, местоположение, провайдера и ASN.", description: "Бесплатный инструмент «какой у меня IP». Мгновенно показывает ваш публичный IP-адрес с приблизительным местоположением, провайдером/организацией, ASN и часовым поясом, со ссылкой на карту — прямо из браузера.", keywords: ["какой у меня ip", "мой ip адрес", "публичный ip", "узнать мой ip", "местоположение ip"], yourIp: "Ваш IP-адрес", location: "Местоположение", isp: "Провайдер / Организация", asn: "ASN", timezone: "Часовой пояс", map: "Показать на карте", refresh: "Обновить", unavailable: "Запрос недоступен. Служба IP может быть ограничена или заблокирована вашей сетью." },
  zh: { title: "我的 IP 是什么", short: "查看你的公网 IP 地址以及位置、ISP 和 ASN。", description: "免费的「我的 IP」工具。立即显示你的公网 IP 地址，以及大致位置、ISP/组织、ASN 和时区，并附带地图链接——全在浏览器中运行。", keywords: ["我的 ip 是什么", "我的 ip 地址", "公网 ip 查询", "查找我的 ip", "ip 位置"], yourIp: "你的 IP 地址", location: "位置", isp: "ISP / 组织", asn: "ASN", timezone: "时区", map: "在地图上查看", refresh: "刷新", unavailable: "查询不可用。IP 服务可能受到速率限制或被你的网络阻止。" },
  ja: { title: "私の IP アドレスは", short: "あなたのグローバル IP、位置、ISP、ASN を表示します。", description: "無料の「私の IP」ツール。あなたのグローバル IP アドレスと、おおよその位置、ISP/組織、ASN、タイムゾーンを即座に表示し、地図リンクも付きます——すべてブラウザ内で動作します。", keywords: ["私の ip アドレスは", "私の ip アドレス", "グローバル ip 検索", "ip を調べる", "ip 位置"], yourIp: "あなたの IP アドレス", location: "位置", isp: "ISP / 組織", asn: "ASN", timezone: "タイムゾーン", map: "地図で見る", refresh: "更新", unavailable: "検索を利用できません。IP サービスがレート制限されているか、ネットワークによってブロックされている可能性があります。" },
  ko: { title: "내 IP 주소는", short: "공인 IP 주소와 위치, ISP, ASN을 확인하세요.", description: "무료 내-IP 확인 도구. 공인 IP 주소와 대략적인 위치, ISP/조직, ASN, 시간대를 즉시 표시하고 지도 링크도 제공합니다 — 모두 브라우저에서 실행됩니다.", keywords: ["내 ip 주소는", "내 ip 주소", "공인 ip 조회", "내 ip 찾기", "ip 위치"], yourIp: "내 IP 주소", location: "위치", isp: "ISP / 조직", asn: "ASN", timezone: "시간대", map: "지도에서 보기", refresh: "새로고침", unavailable: "조회를 사용할 수 없습니다. IP 서비스가 속도 제한되었거나 네트워크에서 차단되었을 수 있습니다." },
  hi: { title: "मेरा IP क्या है", short: "अपना सार्वजनिक IP पता, स्थान, ISP और ASN देखें।", description: "मुफ्त मेरा-IP टूल। आपका सार्वजनिक IP पता तुरंत दिखाता है, साथ ही अनुमानित स्थान, ISP/संगठन, ASN और समय क्षेत्र, मानचित्र लिंक के साथ — सब आपके ब्राउज़र से।", keywords: ["मेरा ip क्या है", "मेरा ip पता", "सार्वजनिक ip लुकअप", "मेरा ip खोजें", "ip स्थान"], yourIp: "आपका IP पता", location: "स्थान", isp: "ISP / संगठन", asn: "ASN", timezone: "समय क्षेत्र", map: "मानचित्र पर देखें", refresh: "रिफ़्रेश", unavailable: "लुकअप अनुपलब्ध। IP सेवा दर-सीमित हो सकती है या आपके नेटवर्क द्वारा अवरुद्ध हो सकती है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
