import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Base58 Encode / Decode", short: "Encode text to Base58 or decode Base58 back to text.", description: "Free Base58 encoder and decoder using the Bitcoin alphabet. Convert any UTF-8 text to Base58 and back — useful for Bitcoin addresses, IPFS hashes and compact identifiers. Runs in your browser.", keywords: ["base58 encode", "base58 decode", "base58 converter", "bitcoin base58", "base58 online"], encode: "Encode", decode: "Decode", placeholder: "Enter text or Base58…", invalid: "Invalid Base58 input." },
  tr: { title: "Base58 Kodla / Çöz", short: "Metni Base58'e kodlayın veya Base58'i metne çözün.", description: "Bitcoin alfabesini kullanan ücretsiz Base58 kodlayıcı ve çözücü. Herhangi bir UTF-8 metni Base58'e ve geri çevirin — Bitcoin adresleri, IPFS özetleri ve kompakt tanımlayıcılar için kullanışlı. Tarayıcınızda çalışır.", keywords: ["base58 kodlama", "base58 çözme", "base58 dönüştürücü", "bitcoin base58", "base58 online"], encode: "Kodla", decode: "Çöz", placeholder: "Metin veya Base58 girin…", invalid: "Geçersiz Base58 girdisi." },
  de: { title: "Base58 Kodieren / Dekodieren", short: "Text in Base58 kodieren oder Base58 zurück in Text dekodieren.", description: "Kostenloser Base58-Encoder und -Decoder mit dem Bitcoin-Alphabet. Wandeln Sie beliebigen UTF-8-Text in Base58 und zurück — nützlich für Bitcoin-Adressen, IPFS-Hashes und kompakte Bezeichner. Läuft im Browser.", keywords: ["base58 kodieren", "base58 dekodieren", "base58 konverter", "bitcoin base58", "base58 online"], encode: "Kodieren", decode: "Dekodieren", placeholder: "Text oder Base58 eingeben…", invalid: "Ungültige Base58-Eingabe." },
  fr: { title: "Encoder / Décoder Base58", short: "Encodez du texte en Base58 ou décodez du Base58 en texte.", description: "Encodeur et décodeur Base58 gratuit utilisant l'alphabet Bitcoin. Convertissez tout texte UTF-8 en Base58 et inversement — utile pour les adresses Bitcoin, hachages IPFS et identifiants compacts. Fonctionne dans votre navigateur.", keywords: ["encoder base58", "décoder base58", "convertisseur base58", "bitcoin base58", "base58 en ligne"], encode: "Encoder", decode: "Décoder", placeholder: "Saisissez du texte ou du Base58…", invalid: "Entrée Base58 invalide." },
  es: { title: "Codificar / Decodificar Base58", short: "Codifica texto a Base58 o decodifica Base58 a texto.", description: "Codificador y decodificador Base58 gratuito con el alfabeto Bitcoin. Convierte cualquier texto UTF-8 a Base58 y viceversa — útil para direcciones Bitcoin, hashes IPFS e identificadores compactos. Funciona en tu navegador.", keywords: ["codificar base58", "decodificar base58", "conversor base58", "bitcoin base58", "base58 online"], encode: "Codificar", decode: "Decodificar", placeholder: "Introduce texto o Base58…", invalid: "Entrada Base58 no válida." },
  it: { title: "Codifica / Decodifica Base58", short: "Codifica testo in Base58 o decodifica Base58 in testo.", description: "Codificatore e decodificatore Base58 gratuito con l'alfabeto Bitcoin. Converti qualsiasi testo UTF-8 in Base58 e viceversa — utile per indirizzi Bitcoin, hash IPFS e identificatori compatti. Funziona nel browser.", keywords: ["codifica base58", "decodifica base58", "convertitore base58", "bitcoin base58", "base58 online"], encode: "Codifica", decode: "Decodifica", placeholder: "Inserisci testo o Base58…", invalid: "Input Base58 non valido." },
  ar: { title: "ترميز / فك ترميز Base58", short: "رمّز النص إلى Base58 أو فك ترميز Base58 إلى نص.", description: "مرمّز ومفكّك Base58 مجاني باستخدام أبجدية Bitcoin. حوّل أي نص UTF-8 إلى Base58 والعكس — مفيد لعناوين Bitcoin وتجزئات IPFS والمعرّفات المضغوطة. يعمل في متصفحك.", keywords: ["ترميز base58", "فك ترميز base58", "محول base58", "bitcoin base58", "base58 عبر الإنترنت"], encode: "ترميز", decode: "فك الترميز", placeholder: "أدخل نصًا أو Base58…", invalid: "إدخال Base58 غير صالح." },
  ru: { title: "Кодирование / Декодирование Base58", short: "Кодируйте текст в Base58 или декодируйте Base58 обратно.", description: "Бесплатный кодировщик и декодировщик Base58 с алфавитом Bitcoin. Преобразуйте любой UTF-8 текст в Base58 и обратно — полезно для адресов Bitcoin, хешей IPFS и компактных идентификаторов. Работает в браузере.", keywords: ["кодирование base58", "декодирование base58", "конвертер base58", "bitcoin base58", "base58 онлайн"], encode: "Кодировать", decode: "Декодировать", placeholder: "Введите текст или Base58…", invalid: "Недопустимый ввод Base58." },
  zh: { title: "Base58 编码 / 解码", short: "将文本编码为 Base58 或将 Base58 解码为文本。", description: "使用比特币字母表的免费 Base58 编码器和解码器。将任意 UTF-8 文本转换为 Base58 并还原——适用于比特币地址、IPFS 哈希和紧凑标识符。在浏览器中运行。", keywords: ["base58 编码", "base58 解码", "base58 转换器", "比特币 base58", "base58 在线"], encode: "编码", decode: "解码", placeholder: "输入文本或 Base58…", invalid: "无效的 Base58 输入。" },
  ja: { title: "Base58 エンコード / デコード", short: "テキストを Base58 にエンコード、または Base58 をテキストにデコード。", description: "Bitcoin アルファベットを使う無料の Base58 エンコーダー・デコーダー。任意の UTF-8 テキストを Base58 に変換し元に戻せます——Bitcoin アドレス、IPFS ハッシュ、コンパクトな識別子に便利。ブラウザ内で動作します。", keywords: ["base58 エンコード", "base58 デコード", "base58 変換", "bitcoin base58", "base58 オンライン"], encode: "エンコード", decode: "デコード", placeholder: "テキストまたは Base58 を入力…", invalid: "無効な Base58 入力です。" },
  ko: { title: "Base58 인코딩 / 디코딩", short: "텍스트를 Base58로 인코딩하거나 Base58을 텍스트로 디코딩합니다.", description: "비트코인 알파벳을 사용하는 무료 Base58 인코더 및 디코더. 모든 UTF-8 텍스트를 Base58로 변환하고 되돌립니다 — 비트코인 주소, IPFS 해시, 간결한 식별자에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["base58 인코딩", "base58 디코딩", "base58 변환기", "비트코인 base58", "base58 온라인"], encode: "인코딩", decode: "디코딩", placeholder: "텍스트 또는 Base58 입력…", invalid: "잘못된 Base58 입력입니다." },
  hi: { title: "Base58 एन्कोड / डिकोड", short: "टेक्स्ट को Base58 में एन्कोड करें या Base58 को टेक्स्ट में डिकोड करें।", description: "बिटकॉइन वर्णमाला का उपयोग करते हुए मुफ्त Base58 एन्कोडर और डिकोडर। किसी भी UTF-8 टेक्स्ट को Base58 में और वापस बदलें — बिटकॉइन पते, IPFS हैश और कॉम्पैक्ट पहचानकर्ताओं के लिए उपयोगी। आपके ब्राउज़र में चलता है।", keywords: ["base58 एन्कोड", "base58 डिकोड", "base58 कन्वर्टर", "बिटकॉइन base58", "base58 ऑनलाइन"], encode: "एन्कोड", decode: "डिकोड", placeholder: "टेक्स्ट या Base58 दर्ज करें…", invalid: "अमान्य Base58 इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
