import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Time Card Calculator", short: "Add daily clock-in/out times and breaks to total weekly hours and pay.", description: "Free time card calculator. Enter daily clock-in and clock-out times with break minutes to total your weekly hours, split regular and overtime, and estimate pay. Handles overnight shifts. Runs in your browser.", keywords: ["time card calculator", "work hours calculator", "timesheet calculator", "overtime calculator", "payroll hours calculator"], timeIn: "Clock in", timeOut: "Clock out", breakMin: "Break (min)", hours: "Hours", addRow: "Add day", remove: "Remove", otThreshold: "Overtime after (h/week)", rate: "Hourly rate", total: "Total hours", regular: "Regular", overtime: "Overtime", pay: "Estimated pay", invalid: "Enter valid times in HH:MM format." },
  nl: { title: "Tijdkaart Calculator", short: "Add daily clock-in/out times and breaks to total weekly uren and pay.", description: "Gratis time card calculator. Enter daily clock-in and clock-out times with break minuten to total your weekly uren, split regular and overtime, and estimate pay. Handles overnight shifts. Runs in uw browser.", keywords: ["time card calculator", "work uren calculator", "timesheet calculator", "overtime calculator", "payroll uren calculator"], timeIn: "Clock in", timeOut: "Clock out", breakMin: "Break (min)", hours: "Hours", addRow: "Add day", remove: "Verwijder", otThreshold: "Overuren after (h/week)", rate: "Hourly rate", total: "Total uren", regular: "Regular", overtime: "Overuren", pay: "Estimated pay", invalid: "Enter valid times in HH:MM formatteer." },

  pl: { title: "Karta Czasu Kalkulator", short: "Add daily clock-in/out times and breaks to total weekly godzin and pay.", description: "Darmowy time card kalkulator. Enter daily clock-in and clock-out times with break minut to total your weekly godzin, split regular and overtime, and estimate pay. Handles overnight shifts. Runs w Twojej przeglądarce.", keywords: ["time card kalkulator", "work godzin kalkulator", "timesheet kalkulator", "overtime kalkulator", "payroll godzin kalkulator"], timeIn: "Clock in", timeOut: "Clock out", breakMin: "Break (min)", hours: "Hours", addRow: "Add day", remove: "Usuń", otThreshold: "Nadgodziny after (h/week)", rate: "Hourly rate", total: "Total godzin", regular: "Regular", overtime: "Nadgodziny", pay: "Estimated pay", invalid: "Enter valid times in HH:MM formatuj." },
  pt: { title: "Calculadora de Cartão de Ponto", short: "Adicione horários diários de entrada/saída e pausas para totalizar horas e pagamento semanais.", description: "Calculadora de cartão de ponto gratuita. Insira horários diários de entrada e saída com minutos de pausa para totalizar suas horas semanais, dividir normais e extras, e estimar o pagamento. Lida com turnos noturnos. Roda no navegador.", keywords: ["time card calculator", "work hours calculator", "timesheet calculator", "overtime calculator", "payroll hours calculator"], timeIn: "Entrada", timeOut: "Saída", breakMin: "Pausa (min)", hours: "Horas", addRow: "Adicionar dia", remove: "Remover", otThreshold: "Hora extra após (h/semana)", rate: "Valor por hora", total: "Total de horas", regular: "Normais", overtime: "Extras", pay: "Pagamento estimado", invalid: "Insira horários válidos no formato HH:MM." },
  id: { title: "Kalkulator Kartu Waktu", short: "Tambahkan jam masuk/keluar harian dan istirahat untuk menjumlahkan jam dan upah mingguan.", description: "Kalkulator kartu waktu gratis. Masukkan jam masuk dan keluar harian dengan menit istirahat untuk menjumlahkan jam mingguan Anda, memisahkan reguler dan lembur, serta memperkirakan upah. Menangani shift malam. Berjalan di browser.", keywords: ["time card calculator", "work hours calculator", "timesheet calculator", "overtime calculator", "payroll hours calculator"], timeIn: "Jam masuk", timeOut: "Jam keluar", breakMin: "Istirahat (mnt)", hours: "Jam", addRow: "Tambah hari", remove: "Hapus", otThreshold: "Lembur setelah (jam/minggu)", rate: "Tarif per jam", total: "Total jam", regular: "Reguler", overtime: "Lembur", pay: "Perkiraan upah", invalid: "Masukkan waktu yang valid dalam format JJ:MM." },

  tr: { title: "Mesai Kartı Hesaplayıcı", short: "Günlük giriş/çıkış saatleri ve molaları ekleyerek haftalık saat ve ücreti toplayın.", description: "Ücretsiz mesai kartı hesaplayıcı. Günlük giriş ve çıkış saatlerini mola dakikalarıyla girerek haftalık saatlerinizi toplayın, normal ve fazla mesaiyi ayırın ve ücreti tahmin edin. Gece vardiyalarını destekler. Tarayıcınızda çalışır.", keywords: ["mesai kartı hesaplayıcı", "çalışma saati hesaplayıcı", "puantaj hesaplayıcı", "fazla mesai hesaplayıcı", "bordro saat hesaplayıcı"], timeIn: "Giriş", timeOut: "Çıkış", breakMin: "Mola (dk)", hours: "Saat", addRow: "Gün ekle", remove: "Kaldır", otThreshold: "Fazla mesai eşiği (sa/hafta)", rate: "Saatlik ücret", total: "Toplam saat", regular: "Normal", overtime: "Fazla mesai", pay: "Tahmini ücret", invalid: "SS:DD biçiminde geçerli saatler girin." },
  de: { title: "Stundenzettel-Rechner", short: "Tägliche Kommen-/Gehen-Zeiten und Pausen addieren, um Wochenstunden und Lohn zu berechnen.", description: "Kostenloser Stundenzettel-Rechner. Geben Sie tägliche Kommen- und Gehen-Zeiten mit Pausenminuten ein, um Ihre Wochenstunden zu summieren, regulär und Überstunden zu trennen und den Lohn zu schätzen. Unterstützt Nachtschichten. Läuft im Browser.", keywords: ["stundenzettel rechner", "arbeitsstunden rechner", "zeiterfassung rechner", "überstunden rechner", "lohnstunden rechner"], timeIn: "Kommen", timeOut: "Gehen", breakMin: "Pause (Min)", hours: "Stunden", addRow: "Tag hinzufügen", remove: "Entfernen", otThreshold: "Überstunden ab (Std/Woche)", rate: "Stundenlohn", total: "Gesamtstunden", regular: "Regulär", overtime: "Überstunden", pay: "Geschätzter Lohn", invalid: "Geben Sie gültige Zeiten im Format SS:MM ein." },
  fr: { title: "Calculateur de Feuille de Temps", short: "Ajoutez les heures d'entrée/sortie et pauses pour totaliser les heures et la paie hebdomadaires.", description: "Calculateur de feuille de temps gratuit. Saisissez les heures d'entrée et de sortie quotidiennes avec les minutes de pause pour totaliser vos heures hebdomadaires, séparer heures normales et supplémentaires, et estimer la paie. Gère les quarts de nuit.", keywords: ["calculateur de feuille de temps", "calculateur d'heures de travail", "calculateur de pointage", "calculateur d'heures supplémentaires", "calculateur d'heures de paie"], timeIn: "Entrée", timeOut: "Sortie", breakMin: "Pause (min)", hours: "Heures", addRow: "Ajouter un jour", remove: "Supprimer", otThreshold: "Heures sup après (h/semaine)", rate: "Taux horaire", total: "Total des heures", regular: "Normales", overtime: "Supplémentaires", pay: "Paie estimée", invalid: "Saisissez des heures valides au format HH:MM." },
  es: { title: "Calculadora de Tarjeta de Tiempo", short: "Agrega horas diarias de entrada/salida y descansos para totalizar horas y pago semanales.", description: "Calculadora de tarjeta de tiempo gratuita. Introduce las horas diarias de entrada y salida con minutos de descanso para totalizar tus horas semanales, separar horas regulares y extra, y estimar el pago. Maneja turnos nocturnos. Funciona en tu navegador.", keywords: ["calculadora de tarjeta de tiempo", "calculadora de horas de trabajo", "calculadora de hoja de horas", "calculadora de horas extra", "calculadora de horas de nómina"], timeIn: "Entrada", timeOut: "Salida", breakMin: "Descanso (min)", hours: "Horas", addRow: "Agregar día", remove: "Eliminar", otThreshold: "Horas extra tras (h/semana)", rate: "Tarifa por hora", total: "Total de horas", regular: "Regulares", overtime: "Extra", pay: "Pago estimado", invalid: "Introduce horas válidas en formato HH:MM." },
  it: { title: "Calcolatore Cartellino Orario", short: "Aggiungi orari di entrata/uscita e pause per totalizzare ore e paga settimanali.", description: "Calcolatore di cartellino orario gratuito. Inserisci orari di entrata e uscita giornalieri con i minuti di pausa per totalizzare le ore settimanali, separare ordinarie e straordinarie e stimare la paga. Gestisce i turni notturni. Funziona nel browser.", keywords: ["calcolatore cartellino orario", "calcolatore ore di lavoro", "calcolatore foglio presenze", "calcolatore straordinari", "calcolatore ore busta paga"], timeIn: "Entrata", timeOut: "Uscita", breakMin: "Pausa (min)", hours: "Ore", addRow: "Aggiungi giorno", remove: "Rimuovi", otThreshold: "Straordinari oltre (h/settimana)", rate: "Tariffa oraria", total: "Ore totali", regular: "Ordinarie", overtime: "Straordinari", pay: "Paga stimata", invalid: "Inserisci orari validi in formato HH:MM." },
  ar: { title: "حاسبة بطاقة الدوام", short: "أضف أوقات الدخول/الخروج اليومية والاستراحات لحساب الساعات والأجر الأسبوعي.", description: "حاسبة بطاقة دوام مجانية. أدخل أوقات الدخول والخروج اليومية مع دقائق الاستراحة لحساب ساعاتك الأسبوعية، وفصل الساعات العادية والإضافية، وتقدير الأجر. تدعم نوبات الليل. تعمل في متصفحك.", keywords: ["حاسبة بطاقة الدوام", "حاسبة ساعات العمل", "حاسبة جدول الدوام", "حاسبة العمل الإضافي", "حاسبة ساعات الرواتب"], timeIn: "الدخول", timeOut: "الخروج", breakMin: "استراحة (دقيقة)", hours: "الساعات", addRow: "إضافة يوم", remove: "إزالة", otThreshold: "العمل الإضافي بعد (ساعة/أسبوع)", rate: "الأجر بالساعة", total: "إجمالي الساعات", regular: "عادية", overtime: "إضافية", pay: "الأجر التقديري", invalid: "أدخل أوقاتًا صالحة بصيغة HH:MM." },
  ru: { title: "Калькулятор Табеля Учёта", short: "Добавьте ежедневное время входа/выхода и перерывы для подсчёта недельных часов и оплаты.", description: "Бесплатный калькулятор табеля учёта рабочего времени. Введите ежедневное время прихода и ухода с минутами перерыва, чтобы подсчитать недельные часы, разделить обычные и сверхурочные и оценить оплату. Поддерживает ночные смены. Работает в браузере.", keywords: ["калькулятор табеля", "калькулятор рабочих часов", "калькулятор учёта времени", "калькулятор сверхурочных", "калькулятор часов для зарплаты"], timeIn: "Приход", timeOut: "Уход", breakMin: "Перерыв (мин)", hours: "Часы", addRow: "Добавить день", remove: "Удалить", otThreshold: "Сверхурочные после (ч/неделю)", rate: "Ставка в час", total: "Всего часов", regular: "Обычные", overtime: "Сверхурочные", pay: "Оценочная оплата", invalid: "Введите корректное время в формате ЧЧ:ММ." },
  zh: { title: "工时卡计算器", short: "添加每日上下班时间和休息以汇总每周工时和工资。", description: "免费的工时卡计算器。输入每日上下班时间和休息分钟数，汇总每周工时，区分正常工时和加班，并估算工资。支持跨夜班次。在浏览器中运行。", keywords: ["工时卡计算器", "工作时长计算器", "考勤表计算器", "加班计算器", "工资工时计算器"], timeIn: "上班", timeOut: "下班", breakMin: "休息（分钟）", hours: "工时", addRow: "添加一天", remove: "删除", otThreshold: "加班阈值（小时/周）", rate: "时薪", total: "总工时", regular: "正常", overtime: "加班", pay: "预估工资", invalid: "请按 HH:MM 格式输入有效时间。" },
  ja: { title: "タイムカード計算ツール", short: "毎日の出退勤時刻と休憩を入力して、週の労働時間と給与を集計します。", description: "無料のタイムカード計算ツール。毎日の出勤・退勤時刻と休憩分を入力して、週の労働時間を集計し、通常と残業を分け、給与を見積もります。深夜勤務にも対応。ブラウザ内で動作します。", keywords: ["タイムカード計算", "労働時間計算", "勤怠計算", "残業計算", "給与時間計算"], timeIn: "出勤", timeOut: "退勤", breakMin: "休憩（分）", hours: "時間", addRow: "日を追加", remove: "削除", otThreshold: "残業基準（時間/週）", rate: "時給", total: "合計時間", regular: "通常", overtime: "残業", pay: "推定給与", invalid: "HH:MM 形式で有効な時刻を入力してください。" },
  ko: { title: "근무 카드 계산기", short: "매일 출퇴근 시간과 휴식을 추가해 주간 근무 시간과 급여를 합산합니다.", description: "무료 근무 카드 계산기. 매일 출근 및 퇴근 시간과 휴식 분을 입력해 주간 근무 시간을 합산하고, 일반과 초과 근무를 나누며, 급여를 추정하세요. 야간 근무를 지원합니다. 브라우저에서 실행됩니다.", keywords: ["근무 카드 계산기", "근무 시간 계산기", "출퇴근 계산기", "초과 근무 계산기", "급여 시간 계산기"], timeIn: "출근", timeOut: "퇴근", breakMin: "휴식(분)", hours: "시간", addRow: "날짜 추가", remove: "제거", otThreshold: "초과 근무 기준(시간/주)", rate: "시급", total: "총 시간", regular: "일반", overtime: "초과", pay: "예상 급여", invalid: "HH:MM 형식으로 유효한 시간을 입력하세요." },
  hi: { title: "टाइम कार्ड कैलकुलेटर", short: "दैनिक प्रवेश/निकास समय और ब्रेक जोड़कर साप्ताहिक घंटे और वेतन की गणना करें।", description: "मुफ्त टाइम कार्ड कैलकुलेटर। दैनिक प्रवेश और निकास समय को ब्रेक मिनटों के साथ दर्ज करें ताकि अपने साप्ताहिक घंटे जोड़ सकें, सामान्य और ओवरटाइम अलग कर सकें, और वेतन का अनुमान लगा सकें। रात की शिफ्ट को संभालता है। ब्राउज़र में चलता है।", keywords: ["टाइम कार्ड कैलकुलेटर", "कार्य घंटे कैलकुलेटर", "टाइमशीट कैलकुलेटर", "ओवरटाइम कैलकुलेटर", "पेरोल घंटे कैलकुलेटर"], timeIn: "प्रवेश", timeOut: "निकास", breakMin: "ब्रेक (मिनट)", hours: "घंटे", addRow: "दिन जोड़ें", remove: "हटाएं", otThreshold: "ओवरटाइम सीमा (घंटे/सप्ताह)", rate: "प्रति घंटा दर", total: "कुल घंटे", regular: "सामान्य", overtime: "ओवरटाइम", pay: "अनुमानित वेतन", invalid: "HH:MM प्रारूप में मान्य समय दर्ज करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
