import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image Format Converter", short: "Convert PNG, JPG and WebP images in your browser.", description: "Free image format converter. Drop a PNG, JPG, GIF or WebP image, pick the target format (PNG, JPEG or WebP) and download the converted file — runs entirely in your browser, nothing uploaded.", keywords: ["image format converter", "png to jpg", "jpg to webp", "convert image format", "image converter online"], drop: "Drop an image here or click to choose", format: "Target format", quality: "Quality", download: "Download" },
  nl: { title: "Afbeelding Formatteer Converteerer", short: "Converteer PNG, JPG and WebP afbeeldings in uw browser.", description: "Gratis afbeelding formatteer converteerer. Drop a PNG, JPG, GIF or WebP afbeelding, pick the target formatteer (PNG, JPEG or WebP) and download the converteered file — runs entirely in uw browser, nothing uploaded.", keywords: ["afbeelding formatteer converteerer", "png to jpg", "jpg to webp", "converteer afbeelding formatteer", "afbeelding converteerer online"], drop: "Drop an afbeelding here or click to choose", format: "Target formatteer", quality: "Quality", download: "Download" },

  pl: { title: "Obraz Formatuj Konwerter", short: "Konwertuj PNG, JPG and WebP obrazs w Twojej przeglądarce.", description: "Darmowy obraz formatuj konwerter. Drop a PNG, JPG, GIF or WebP obraz, pick the target formatuj (PNG, JPEG or WebP) and download the konwertujed file — runs entirely w Twojej przeglądarce, nothing uploaded.", keywords: ["obraz formatuj konwerter", "png to jpg", "jpg to webp", "konwertuj obraz formatuj", "obraz konwerter online"], drop: "Drop an obraz here or click to choose", format: "Target formatuj", quality: "Quality", download: "Download" },
  pt: { title: "Conversor de Image Format", short: "Converter PNG, JPG e WebP images no seu navegador.", description: "Gratuito - image formatar converter. Drop a PNG, JPG, GIF ou WebP image, pick the target formatar (PNG, JPEG ou WebP) e descarregar the converted file â runs entirely no seu navegador, nothing uploaded.", keywords: ["image format converter", "png to jpg", "jpg to webp", "convert image format", "image converter online"], drop: "Drop an image here or click to choose", format: "Target format", quality: "Quality", download: "Download" },
  id: { title: "Konverter Image Format", short: "Konversi PNG, JPG dan WebP images di browser Anda.", description: "Gratis - image format converter. Drop a PNG, JPG, GIF atau WebP image, pick the target format (PNG, JPEG atau WebP) dan unduh the converted file â runs entirely di browser Anda, nothing uploaded.", keywords: ["image format converter", "png to jpg", "jpg to webp", "convert image format", "image converter online"], drop: "Drop an image here or click to choose", format: "Target format", quality: "Quality", download: "Download" },

  tr: { title: "Görsel Format Dönüştürücü", short: "PNG, JPG ve WebP görsellerini tarayıcınızda dönüştürün.", description: "Ücretsiz görsel format dönüştürücü. Bir PNG, JPG, GIF veya WebP görseli bırakın, hedef formatı (PNG, JPEG veya WebP) seçin ve dönüştürülmüş dosyayı indirin — tamamen tarayıcınızda çalışır, hiçbir şey yüklenmez.", keywords: ["görsel format dönüştürücü", "png jpg", "jpg webp", "görsel format dönüştürme", "online görsel dönüştürücü"], drop: "Bir görsel bırakın veya seçmek için tıklayın", format: "Hedef format", quality: "Kalite", download: "İndir" },
  de: { title: "Bildformat-Konverter", short: "Konvertieren Sie PNG-, JPG- und WebP-Bilder im Browser.", description: "Kostenloser Bildformat-Konverter. Legen Sie ein PNG-, JPG-, GIF- oder WebP-Bild ab, wählen Sie das Zielformat (PNG, JPEG oder WebP) und laden Sie die konvertierte Datei herunter — läuft vollständig im Browser, nichts wird hochgeladen.", keywords: ["bildformat konverter", "png zu jpg", "jpg zu webp", "bildformat umwandeln", "bild konverter online"], drop: "Bild hier ablegen oder klicken zum Auswählen", format: "Zielformat", quality: "Qualität", download: "Herunterladen" },
  fr: { title: "Convertisseur de Format d'Image", short: "Convertissez les images PNG, JPG et WebP dans votre navigateur.", description: "Convertisseur de format d'image gratuit. Déposez une image PNG, JPG, GIF ou WebP, choisissez le format cible (PNG, JPEG ou WebP) et téléchargez le fichier converti — fonctionne entièrement dans votre navigateur, rien n'est envoyé.", keywords: ["convertisseur format image", "png vers jpg", "jpg vers webp", "convertir format image", "convertisseur image en ligne"], drop: "Déposez une image ici ou cliquez pour choisir", format: "Format cible", quality: "Qualité", download: "Télécharger" },
  es: { title: "Convertidor de Formato de Imagen", short: "Convierte imágenes PNG, JPG y WebP en tu navegador.", description: "Convertidor de formato de imagen gratuito. Arrastra una imagen PNG, JPG, GIF o WebP, elige el formato objetivo (PNG, JPEG o WebP) y descarga el archivo convertido — funciona completamente en tu navegador, nada se sube.", keywords: ["convertidor formato imagen", "png a jpg", "jpg a webp", "convertir formato imagen", "convertidor imagen online"], drop: "Arrastra una imagen aquí o haz clic para elegir", format: "Formato objetivo", quality: "Calidad", download: "Descargar" },
  it: { title: "Convertitore di Formato Immagine", short: "Converti immagini PNG, JPG e WebP nel browser.", description: "Convertitore di formato immagine gratuito. Trascina un'immagine PNG, JPG, GIF o WebP, scegli il formato target (PNG, JPEG o WebP) e scarica il file convertito — funziona interamente nel browser, nulla viene caricato.", keywords: ["convertitore formato immagine", "png a jpg", "jpg a webp", "convertire formato immagine", "convertitore immagine online"], drop: "Trascina un'immagine qui o clicca per scegliere", format: "Formato target", quality: "Qualità", download: "Scarica" },
  ar: { title: "محوّل تنسيق الصور", short: "حوّل صور PNG و JPG و WebP في متصفحك.", description: "محوّل تنسيق صور مجاني. أفلِت صورة PNG أو JPG أو GIF أو WebP، اختر التنسيق المستهدف (PNG أو JPEG أو WebP) ونزّل الملف المحوّل — يعمل بالكامل في متصفحك، لا شيء يُرفع.", keywords: ["محول تنسيق الصور", "png إلى jpg", "jpg إلى webp", "تحويل تنسيق الصورة", "محول الصور عبر الإنترنت"], drop: "أفلِت صورة هنا أو انقر للاختيار", format: "التنسيق المستهدف", quality: "الجودة", download: "تنزيل" },
  ru: { title: "Конвертер форматов изображений", short: "Конвертируйте PNG, JPG и WebP изображения в браузере.", description: "Бесплатный конвертер форматов изображений. Перетащите PNG, JPG, GIF или WebP, выберите целевой формат (PNG, JPEG или WebP) и скачайте конвертированный файл — работает полностью в браузере, ничего не загружается.", keywords: ["конвертер формата изображения", "png в jpg", "jpg в webp", "конвертировать формат изображения", "онлайн конвертер изображений"], drop: "Перетащите изображение сюда или нажмите для выбора", format: "Целевой формат", quality: "Качество", download: "Скачать" },
  zh: { title: "图片格式转换器", short: "在浏览器中转换 PNG、JPG 和 WebP 图片。", description: "免费的图片格式转换器。拖入 PNG、JPG、GIF 或 WebP 图片，选择目标格式（PNG、JPEG 或 WebP），下载转换后的文件——完全在浏览器中运行，不上传任何内容。", keywords: ["图片格式转换器", "png 转 jpg", "jpg 转 webp", "图片格式转换", "在线图片转换器"], drop: "将图片拖到此处或点击选择", format: "目标格式", quality: "质量", download: "下载" },
  ja: { title: "画像形式変換", short: "PNG、JPG、WebP 画像をブラウザで変換。", description: "無料の画像形式変換ツール。PNG、JPG、GIF、WebP 画像をドロップし、ターゲット形式（PNG、JPEG、WebP）を選んで変換されたファイルをダウンロード——すべてブラウザ内で動作、アップロードなし。", keywords: ["画像 形式 変換", "png から jpg", "jpg から webp", "画像形式 変換", "画像 変換 オンライン"], drop: "画像をここにドロップまたはクリックして選択", format: "ターゲット形式", quality: "品質", download: "ダウンロード" },
  ko: { title: "이미지 형식 변환기", short: "브라우저에서 PNG, JPG, WebP 이미지를 변환합니다.", description: "무료 이미지 형식 변환기. PNG, JPG, GIF, WebP 이미지를 드롭하고 대상 형식(PNG, JPEG, WebP)을 선택해 변환된 파일을 다운로드하세요 — 모두 브라우저에서 실행, 업로드 없음.", keywords: ["이미지 형식 변환기", "png를 jpg로", "jpg를 webp로", "이미지 형식 변환", "온라인 이미지 변환기"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", format: "대상 형식", quality: "품질", download: "다운로드" },
  hi: { title: "इमेज प्रारूप कन्वर्टर", short: "अपने ब्राउज़र में PNG, JPG और WebP इमेज को बदलें।", description: "मुफ्त इमेज प्रारूप कन्वर्टर। एक PNG, JPG, GIF या WebP इमेज छोड़ें, लक्ष्य प्रारूप (PNG, JPEG या WebP) चुनें और परिवर्तित फ़ाइल डाउनलोड करें — पूरी तरह आपके ब्राउज़र में चलता है, कुछ भी अपलोड नहीं होता।", keywords: ["इमेज प्रारूप कन्वर्टर", "png से jpg", "jpg से webp", "इमेज प्रारूप बदलें", "ऑनलाइन इमेज कन्वर्टर"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", format: "लक्ष्य प्रारूप", quality: "गुणवत्ता", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
