import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Regex Cheatsheet", short: "Searchable JavaScript regex reference.", description: "Free regex cheatsheet. Searchable list of JavaScript-flavoured regular-expression syntax: anchors, character classes, quantifiers, groups, lookarounds and flags — with examples for each.", keywords: ["regex cheatsheet", "regular expression reference", "regex syntax", "regex anchors", "regex quantifiers"], search: "Search", pattern: "Pattern", meaning: "Meaning", example: "Example" },
  pt: { title: "Regex Cheatsheet", short: "Searchable JavaScript regex reference.", description: "Free regex cheatsheet. Searchable list of JavaScript-flavoured regular-expression syntax: anchors, character classes, quantifiers, groups, lookarounds and flags — with examples for each.", keywords: ["regex cheatsheet", "regular expression reference", "regex syntax", "regex anchors", "regex quantifiers"], search: "Search", pattern: "Pattern", meaning: "Meaning", example: "Example" },
  id: { title: "Regex Cheatsheet", short: "Searchable JavaScript regex reference.", description: "Free regex cheatsheet. Searchable list of JavaScript-flavoured regular-expression syntax: anchors, character classes, quantifiers, groups, lookarounds and flags — with examples for each.", keywords: ["regex cheatsheet", "regular expression reference", "regex syntax", "regex anchors", "regex quantifiers"], search: "Search", pattern: "Pattern", meaning: "Meaning", example: "Example" },

  tr: { title: "Regex Hile Kağıdı", short: "Aranabilir JavaScript regex referansı.", description: "Ücretsiz regex hile kağıdı. JavaScript regex sözdiziminin aranabilir listesi: çapalar, karakter sınıfları, niceleyiciler, gruplar, ileri/geri bakışlar ve bayraklar — her biri için örneklerle.", keywords: ["regex hile kağıdı", "düzenli ifade referansı", "regex sözdizimi", "regex çapalar", "regex niceleyiciler"], search: "Ara", pattern: "Desen", meaning: "Anlam", example: "Örnek" },
  de: { title: "Regex-Cheatsheet", short: "Durchsuchbare JavaScript-Regex-Referenz.", description: "Kostenloses Regex-Cheatsheet. Durchsuchbare Liste der JavaScript-Regex-Syntax: Anker, Zeichenklassen, Quantifizierer, Gruppen, Lookarounds und Flags — mit Beispielen für jeden.", keywords: ["regex cheatsheet", "regulärer ausdruck referenz", "regex syntax", "regex anker", "regex quantifizierer"], search: "Suchen", pattern: "Muster", meaning: "Bedeutung", example: "Beispiel" },
  fr: { title: "Cheatsheet Regex", short: "Référence regex JavaScript consultable.", description: "Cheatsheet regex gratuit. Liste consultable de la syntaxe regex JavaScript : ancres, classes de caractères, quantificateurs, groupes, lookarounds et drapeaux — avec exemples pour chacun.", keywords: ["cheatsheet regex", "référence expression régulière", "syntaxe regex", "ancres regex", "quantificateurs regex"], search: "Rechercher", pattern: "Motif", meaning: "Signification", example: "Exemple" },
  es: { title: "Cheatsheet de Regex", short: "Referencia de regex JavaScript con búsqueda.", description: "Cheatsheet de regex gratuito. Lista buscable de sintaxis regex de JavaScript: anclas, clases de caracteres, cuantificadores, grupos, lookarounds y banderas — con ejemplos para cada uno.", keywords: ["cheatsheet regex", "referencia expresión regular", "sintaxis regex", "anclas regex", "cuantificadores regex"], search: "Buscar", pattern: "Patrón", meaning: "Significado", example: "Ejemplo" },
  it: { title: "Cheatsheet Regex", short: "Riferimento regex JavaScript ricercabile.", description: "Cheatsheet regex gratuito. Elenco ricercabile della sintassi regex JavaScript: ancoraggi, classi di caratteri, quantificatori, gruppi, lookaround e flag — con esempi per ciascuno.", keywords: ["cheatsheet regex", "riferimento espressione regolare", "sintassi regex", "ancoraggi regex", "quantificatori regex"], search: "Cerca", pattern: "Pattern", meaning: "Significato", example: "Esempio" },
  ar: { title: "ورقة غش Regex", short: "مرجع regex لـ JavaScript قابل للبحث.", description: "ورقة غش regex مجانية. قائمة قابلة للبحث لبناء جملة regex بـ JavaScript: المراسي وفئات الأحرف ومحددات الكمية والمجموعات و lookarounds والأعلام — مع أمثلة لكل منها.", keywords: ["ورقة غش regex", "مرجع التعبير العادي", "بناء جملة regex", "مراسي regex", "محددات كمية regex"], search: "بحث", pattern: "النمط", meaning: "المعنى", example: "مثال" },
  ru: { title: "Шпаргалка по Regex", short: "Поисковый JavaScript regex справочник.", description: "Бесплатная regex шпаргалка. Поисковый список синтаксиса regex JavaScript: якоря, классы символов, квантификаторы, группы, lookarounds и флаги — с примерами для каждого.", keywords: ["regex шпаргалка", "регулярное выражение справочник", "regex синтаксис", "regex якоря", "regex квантификаторы"], search: "Поиск", pattern: "Шаблон", meaning: "Значение", example: "Пример" },
  zh: { title: "Regex 速查表", short: "可搜索的 JavaScript regex 参考。", description: "免费的 regex 速查表。可搜索的 JavaScript 风格正则表达式语法列表：锚点、字符类、量词、分组、lookarounds 和标志——每个都附带示例。", keywords: ["regex 速查表", "正则表达式参考", "regex 语法", "regex 锚点", "regex 量词"], search: "搜索", pattern: "模式", meaning: "含义", example: "示例" },
  ja: { title: "Regex チートシート", short: "検索可能な JavaScript regex リファレンス。", description: "無料の regex チートシート。JavaScript 風の正規表現構文の検索可能な一覧：アンカー、文字クラス、量指定子、グループ、lookarounds、フラグ——それぞれに例付き。", keywords: ["regex チートシート", "正規表現 リファレンス", "regex 構文", "regex アンカー", "regex 量指定子"], search: "検索", pattern: "パターン", meaning: "意味", example: "例" },
  ko: { title: "Regex 치트시트", short: "검색 가능한 JavaScript regex 참조.", description: "무료 regex 치트시트. JavaScript 스타일의 정규 표현식 구문을 검색 가능한 목록으로: 앵커, 문자 클래스, 수량자, 그룹, lookarounds, 플래그 — 각각의 예제 포함.", keywords: ["regex 치트시트", "정규 표현식 참조", "regex 구문", "regex 앵커", "regex 수량자"], search: "검색", pattern: "패턴", meaning: "의미", example: "예제" },
  hi: { title: "Regex चीटशीट", short: "खोज योग्य JavaScript regex संदर्भ।", description: "मुफ्त regex चीटशीट। JavaScript स्टाइल के नियमित अभिव्यक्ति वाक्यविन्यास की खोज योग्य सूची: एंकर, वर्ण वर्ग, परिमाणक, समूह, lookarounds और फ्लैग्स — प्रत्येक के लिए उदाहरण सहित।", keywords: ["regex चीटशीट", "नियमित अभिव्यक्ति संदर्भ", "regex वाक्यविन्यास", "regex एंकर", "regex परिमाणक"], search: "खोजें", pattern: "पैटर्न", meaning: "अर्थ", example: "उदाहरण" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
