import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Timezone Converter", short: "Convert times between IANA time zones, side by side.", description: "Free timezone converter. Compare a moment in time across multiple IANA zones (UTC, New York, London, Tokyo …) — pick zones, set a source time and see the equivalent local time in each.", keywords: ["timezone converter", "world clock", "time zone calculator", "iana timezones", "meeting planner"], sourceTime: "Source time", sourceZone: "Source zone", addZone: "Add zone", removeZone: "Remove" },
  pt: { title: "Timezone Converter", short: "Convert times between IANA time zones, side by side.", description: "Free timezone converter. Compare a moment in time across multiple IANA zones (UTC, New York, London, Tokyo …) — pick zones, set a source time and see the equivalent local time in each.", keywords: ["timezone converter", "world clock", "time zone calculator", "iana timezones", "meeting planner"], sourceTime: "Source time", sourceZone: "Source zone", addZone: "Add zone", removeZone: "Remove" },
  id: { title: "Timezone Converter", short: "Convert times between IANA time zones, side by side.", description: "Free timezone converter. Compare a moment in time across multiple IANA zones (UTC, New York, London, Tokyo …) — pick zones, set a source time and see the equivalent local time in each.", keywords: ["timezone converter", "world clock", "time zone calculator", "iana timezones", "meeting planner"], sourceTime: "Source time", sourceZone: "Source zone", addZone: "Add zone", removeZone: "Remove" },

  tr: { title: "Saat Dilimi Dönüştürücü", short: "IANA saat dilimleri arasında yan yana zaman dönüştürün.", description: "Ücretsiz saat dilimi dönüştürücü. Bir anı birden fazla IANA dilimi (UTC, New York, London, Tokyo …) arasında karşılaştırın — dilimleri seçin, bir kaynak zamanı ayarlayın ve her birindeki yerel zamanı görün.", keywords: ["saat dilimi dönüştürücü", "dünya saati", "saat dilimi hesaplayıcı", "iana saat dilimleri", "toplantı planlayıcı"], sourceTime: "Kaynak zaman", sourceZone: "Kaynak dilim", addZone: "Dilim ekle", removeZone: "Kaldır" },
  de: { title: "Zeitzonen-Konverter", short: "Zeiten zwischen IANA-Zeitzonen nebeneinander umrechnen.", description: "Kostenloser Zeitzonen-Konverter. Vergleichen Sie einen Zeitpunkt in mehreren IANA-Zonen (UTC, New York, London, Tokyo …) — Zonen wählen, eine Quellzeit setzen und die entsprechende Ortszeit in jeder sehen.", keywords: ["zeitzonen konverter", "weltuhr", "zeitzonen rechner", "iana zeitzonen", "meeting planer"], sourceTime: "Quellzeit", sourceZone: "Quellzone", addZone: "Zone hinzufügen", removeZone: "Entfernen" },
  fr: { title: "Convertisseur de Fuseau Horaire", short: "Convertissez les heures entre fuseaux horaires IANA, côte à côte.", description: "Convertisseur de fuseau horaire gratuit. Comparez un instant dans plusieurs zones IANA (UTC, New York, Londres, Tokyo …) — choisissez les zones, définissez une heure source et voyez l'heure locale équivalente dans chacune.", keywords: ["convertisseur fuseau horaire", "horloge mondiale", "calculateur fuseau horaire", "fuseaux iana", "planificateur réunion"], sourceTime: "Heure source", sourceZone: "Zone source", addZone: "Ajouter une zone", removeZone: "Supprimer" },
  es: { title: "Convertidor de Zona Horaria", short: "Convierte horas entre zonas horarias IANA, lado a lado.", description: "Convertidor de zona horaria gratuito. Compara un instante en múltiples zonas IANA (UTC, Nueva York, Londres, Tokio …) — elige zonas, establece una hora origen y mira la hora local equivalente en cada una.", keywords: ["convertidor zona horaria", "reloj mundial", "calculadora zona horaria", "zonas iana", "planificador reuniones"], sourceTime: "Hora origen", sourceZone: "Zona origen", addZone: "Añadir zona", removeZone: "Eliminar" },
  it: { title: "Convertitore di Fuso Orario", short: "Converti orari tra fusi orari IANA, fianco a fianco.", description: "Convertitore di fuso orario gratuito. Confronta un momento in più fusi IANA (UTC, New York, Londra, Tokyo …) — scegli i fusi, imposta un'ora sorgente e vedi l'ora locale equivalente in ciascuno.", keywords: ["convertitore fuso orario", "orologio mondiale", "calcolatore fuso orario", "fusi iana", "pianificatore riunioni"], sourceTime: "Ora sorgente", sourceZone: "Fuso sorgente", addZone: "Aggiungi fuso", removeZone: "Rimuovi" },
  ar: { title: "محوّل المناطق الزمنية", short: "حوّل بين مناطق IANA الزمنية جنبًا إلى جنب.", description: "محوّل مناطق زمنية مجاني. قارن لحظة عبر عدة مناطق IANA (UTC، نيويورك، لندن، طوكيو …) — اختر المناطق، حدد وقت المصدر، وانظر إلى الوقت المحلي المكافئ في كل منها.", keywords: ["محول المنطقة الزمنية", "ساعة عالمية", "حاسبة المنطقة الزمنية", "مناطق iana الزمنية", "مخطط الاجتماعات"], sourceTime: "وقت المصدر", sourceZone: "منطقة المصدر", addZone: "إضافة منطقة", removeZone: "إزالة" },
  ru: { title: "Конвертер часовых поясов", short: "Конвертируйте время между IANA-часовыми поясами параллельно.", description: "Бесплатный конвертер часовых поясов. Сравните момент времени в нескольких IANA-зонах (UTC, Нью-Йорк, Лондон, Токио …) — выберите зоны, задайте исходное время и посмотрите эквивалентное локальное время в каждой.", keywords: ["конвертер часовых поясов", "мировые часы", "калькулятор часовых поясов", "iana часовые пояса", "планировщик встреч"], sourceTime: "Исходное время", sourceZone: "Исходный пояс", addZone: "Добавить зону", removeZone: "Удалить" },
  zh: { title: "时区转换器", short: "并排转换 IANA 时区之间的时间。", description: "免费的时区转换器。在多个 IANA 时区（UTC、纽约、伦敦、东京 …）之间比较时间——选择时区，设置源时间，查看每个时区中的等效本地时间。", keywords: ["时区转换器", "世界时钟", "时区计算器", "iana 时区", "会议规划器"], sourceTime: "源时间", sourceZone: "源时区", addZone: "添加时区", removeZone: "移除" },
  ja: { title: "タイムゾーン変換", short: "IANA タイムゾーン間で時刻を並べて変換。", description: "無料のタイムゾーン変換ツール。複数の IANA ゾーン（UTC、ニューヨーク、ロンドン、東京 …）でモーメントを比較——ゾーンを選び、ソース時刻を設定し、各ゾーンの現地時刻を確認できます。", keywords: ["タイムゾーン 変換", "世界時計", "タイムゾーン 計算機", "iana タイムゾーン", "ミーティング プランナー"], sourceTime: "ソース時刻", sourceZone: "ソースゾーン", addZone: "ゾーンを追加", removeZone: "削除" },
  ko: { title: "시간대 변환기", short: "IANA 시간대 사이의 시간을 나란히 변환합니다.", description: "무료 시간대 변환기. 여러 IANA 영역(UTC, 뉴욕, 런던, 도쿄 …)에서 한 시점을 비교하세요 — 영역을 선택하고 소스 시간을 설정해 각 영역의 동등한 현지 시간을 확인합니다.", keywords: ["시간대 변환기", "세계 시계", "시간대 계산기", "iana 시간대", "회의 플래너"], sourceTime: "소스 시간", sourceZone: "소스 영역", addZone: "영역 추가", removeZone: "제거" },
  hi: { title: "टाइमज़ोन कन्वर्टर", short: "IANA टाइमज़ोन के बीच साथ-साथ समय बदलें।", description: "मुफ्त टाइमज़ोन कन्वर्टर। एक क्षण की कई IANA ज़ोन (UTC, न्यूयॉर्क, लंदन, टोक्यो …) में तुलना करें — ज़ोन चुनें, स्रोत समय सेट करें और प्रत्येक में समकक्ष स्थानीय समय देखें।", keywords: ["टाइमज़ोन कन्वर्टर", "विश्व घड़ी", "टाइमज़ोन कैलकुलेटर", "iana टाइमज़ोन", "मीटिंग प्लानर"], sourceTime: "स्रोत समय", sourceZone: "स्रोत ज़ोन", addZone: "ज़ोन जोड़ें", removeZone: "हटाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
