import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Readability Score Checker", short: "Compute Flesch, Flesch–Kincaid, Gunning Fog, ARI and SMOG.", description: "Free readability checker. Paste English text to score it with Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index and SMOG — useful for editing for clarity. Runs entirely in your browser.", keywords: ["readability checker", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Text", sentences: "Sentences", words: "Words", syllables: "Syllables", complexWords: "Complex words", characters: "Characters", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Grade", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG Index" },
  nl: { title: "Readability Score Controleur", short: "Compute Flesch, Flesch–Kincaid, Gunning Fog, ARI and SMOG.", description: "Gratis readability controleur. Paste English tekst to score it with Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index and SMOG — useful for editing for clarity. Runs entirely in uw browser.", keywords: ["readability controleur", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Tekst", sentences: "Sentences", words: "Words", syllables: "Lettergreeps", complexWords: "Complex words", characters: "Characters", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Grade", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG Index" },

  pl: { title: "Readability Score Sprawdzarka", short: "Compute Flesch, Flesch–Kincaid, Gunning Fog, ARI and SMOG.", description: "Darmowy readability sprawdzarka. Paste English tekst to score it with Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index and SMOG — useful for editing for clarity. Runs entirely w Twojej przeglądarce.", keywords: ["readability sprawdzarka", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Tekst", sentences: "Sentences", words: "Words", syllables: "Sylabas", complexWords: "Complex words", characters: "Characters", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Grade", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG Index" },
  pt: { title: "Verificador de Readability Score", short: "Compute Flesch, FleschâKincaid, Gunning Fog, ARI e SMOG.", description: "Gratuito - readability checker. Paste English text para score it com Flesch Reading Ease, FleschâKincaid Grade Level, Gunning Fog, Automated Readability Index e SMOG â useful para editing para clarity. Runs entirely no seu navegador.", keywords: ["readability checker", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Text", sentences: "Sentences", words: "Words", syllables: "Syllables", complexWords: "Complex words", characters: "Characters", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Grade", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG Index" },
  id: { title: "Pemeriksa Readability Score", short: "Compute Flesch, FleschâKincaid, Gunning Fog, ARI dan SMOG.", description: "Gratis - readability checker. Paste English text to score it with Flesch Reading Ease, FleschâKincaid Grade Level, Gunning Fog, Automated Readability Index dan SMOG â useful for editing for clarity. Runs entirely di browser Anda.", keywords: ["readability checker", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Text", sentences: "Sentences", words: "Words", syllables: "Syllables", complexWords: "Complex words", characters: "Characters", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Grade", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG Index" },

  tr: { title: "Okunabilirlik Puanı Denetleyici", short: "Flesch, Flesch–Kincaid, Gunning Fog, ARI ve SMOG hesaplayın.", description: "Ücretsiz okunabilirlik denetleyicisi. İngilizce metin yapıştırın ve Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index ve SMOG ile puanlayın — netlik için düzenleme yapmak için kullanışlı. Tamamen tarayıcınızda çalışır.", keywords: ["okunabilirlik denetleyici", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Metin", sentences: "Cümle", words: "Kelime", syllables: "Hece", complexWords: "Karmaşık kelime", characters: "Karakter", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid Sınıfı", fog: "Gunning Fog İndeksi", ari: "Otomatik Okunabilirlik İndeksi", smog: "SMOG İndeksi" },
  de: { title: "Lesbarkeits-Score-Prüfer", short: "Flesch, Flesch–Kincaid, Gunning Fog, ARI und SMOG berechnen.", description: "Kostenloser Lesbarkeits-Prüfer. Fügen Sie englischen Text ein, um ihn mit Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index und SMOG zu bewerten — nützlich für Klarheit beim Bearbeiten. Läuft vollständig im Browser.", keywords: ["lesbarkeits prüfer", "flesch reading ease", "flesch kincaid", "gunning fog", "smog index"], input: "Text", sentences: "Sätze", words: "Wörter", syllables: "Silben", complexWords: "Komplexe Wörter", characters: "Zeichen", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid-Klasse", fog: "Gunning Fog Index", ari: "Automated Readability Index", smog: "SMOG-Index" },
  fr: { title: "Vérificateur de Score de Lisibilité", short: "Calculez Flesch, Flesch–Kincaid, Gunning Fog, ARI et SMOG.", description: "Vérificateur de lisibilité gratuit. Collez un texte anglais pour le noter avec Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index et SMOG — utile pour éditer pour la clarté. Fonctionne entièrement dans votre navigateur.", keywords: ["vérificateur lisibilité", "flesch reading ease", "flesch kincaid", "gunning fog", "indice smog"], input: "Texte", sentences: "Phrases", words: "Mots", syllables: "Syllabes", complexWords: "Mots complexes", characters: "Caractères", flesch: "Flesch Reading Ease (0–100)", fk: "Niveau Flesch–Kincaid", fog: "Indice Gunning Fog", ari: "Indice ARI", smog: "Indice SMOG" },
  es: { title: "Verificador de Puntuación de Legibilidad", short: "Calcula Flesch, Flesch–Kincaid, Gunning Fog, ARI y SMOG.", description: "Verificador de legibilidad gratuito. Pega texto en inglés para puntuarlo con Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index y SMOG — útil para editar buscando claridad. Funciona completamente en tu navegador.", keywords: ["verificador legibilidad", "flesch reading ease", "flesch kincaid", "gunning fog", "índice smog"], input: "Texto", sentences: "Oraciones", words: "Palabras", syllables: "Sílabas", complexWords: "Palabras complejas", characters: "Caracteres", flesch: "Flesch Reading Ease (0–100)", fk: "Grado Flesch–Kincaid", fog: "Índice Gunning Fog", ari: "Índice ARI", smog: "Índice SMOG" },
  it: { title: "Verificatore di Punteggio di Leggibilità", short: "Calcola Flesch, Flesch–Kincaid, Gunning Fog, ARI e SMOG.", description: "Verificatore di leggibilità gratuito. Incolla testo inglese per valutarlo con Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index e SMOG — utile per modificare per chiarezza. Funziona interamente nel browser.", keywords: ["verificatore leggibilità", "flesch reading ease", "flesch kincaid", "gunning fog", "indice smog"], input: "Testo", sentences: "Frasi", words: "Parole", syllables: "Sillabe", complexWords: "Parole complesse", characters: "Caratteri", flesch: "Flesch Reading Ease (0–100)", fk: "Livello Flesch–Kincaid", fog: "Indice Gunning Fog", ari: "Indice ARI", smog: "Indice SMOG" },
  ar: { title: "مدقّق درجة سهولة القراءة", short: "احسب Flesch و Flesch–Kincaid و Gunning Fog و ARI و SMOG.", description: "مدقّق سهولة قراءة مجاني. الصق نصًا إنجليزيًا لتقييمه باستخدام Flesch Reading Ease و Flesch–Kincaid Grade Level و Gunning Fog و Automated Readability Index و SMOG — مفيد للتحرير من أجل الوضوح. يعمل بالكامل في متصفحك.", keywords: ["مدقق سهولة القراءة", "flesch reading ease", "flesch kincaid", "gunning fog", "مؤشر smog"], input: "النص", sentences: "الجمل", words: "الكلمات", syllables: "المقاطع", complexWords: "كلمات معقّدة", characters: "الأحرف", flesch: "Flesch Reading Ease (0–100)", fk: "درجة Flesch–Kincaid", fog: "مؤشر Gunning Fog", ari: "مؤشر ARI", smog: "مؤشر SMOG" },
  ru: { title: "Проверка читабельности", short: "Вычисляйте Flesch, Flesch–Kincaid, Gunning Fog, ARI и SMOG.", description: "Бесплатная проверка читабельности. Вставьте английский текст, чтобы оценить его по Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index и SMOG — полезно для редактирования с целью ясности. Работает полностью в браузере.", keywords: ["проверка читабельности", "flesch reading ease", "flesch kincaid", "gunning fog", "индекс smog"], input: "Текст", sentences: "Предложения", words: "Слова", syllables: "Слоги", complexWords: "Сложные слова", characters: "Символы", flesch: "Flesch Reading Ease (0–100)", fk: "Класс Flesch–Kincaid", fog: "Индекс Gunning Fog", ari: "Индекс ARI", smog: "Индекс SMOG" },
  zh: { title: "可读性评分检查器", short: "计算 Flesch、Flesch–Kincaid、Gunning Fog、ARI 和 SMOG。", description: "免费的可读性检查器。粘贴英文文本，使用 Flesch Reading Ease、Flesch–Kincaid Grade Level、Gunning Fog、Automated Readability Index 和 SMOG 进行评分——有助于编辑使其更清晰。完全在浏览器中运行。", keywords: ["可读性检查器", "flesch reading ease", "flesch kincaid", "gunning fog", "smog 指数"], input: "文本", sentences: "句子", words: "单词", syllables: "音节", complexWords: "复杂词", characters: "字符", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid 等级", fog: "Gunning Fog 指数", ari: "自动可读性指数", smog: "SMOG 指数" },
  ja: { title: "可読性スコアチェッカー", short: "Flesch、Flesch–Kincaid、Gunning Fog、ARI、SMOG を計算。", description: "無料の可読性チェッカー。英語のテキストを貼り付けて、Flesch Reading Ease、Flesch–Kincaid Grade Level、Gunning Fog、Automated Readability Index、SMOG でスコアリング——明瞭性のための編集に便利。すべてブラウザ内で動作します。", keywords: ["可読性 チェッカー", "flesch reading ease", "flesch kincaid", "gunning fog", "smog 指数"], input: "テキスト", sentences: "文", words: "単語", syllables: "音節", complexWords: "複雑な単語", characters: "文字", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid グレード", fog: "Gunning Fog 指数", ari: "自動可読性指数", smog: "SMOG 指数" },
  ko: { title: "가독성 점수 검사기", short: "Flesch, Flesch–Kincaid, Gunning Fog, ARI, SMOG를 계산합니다.", description: "무료 가독성 검사기. 영어 텍스트를 붙여넣어 Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index, SMOG로 점수화하세요 — 명확성을 위한 편집에 유용합니다. 모두 브라우저에서 실행됩니다.", keywords: ["가독성 검사기", "flesch reading ease", "flesch kincaid", "gunning fog", "smog 지수"], input: "텍스트", sentences: "문장", words: "단어", syllables: "음절", complexWords: "복잡한 단어", characters: "문자", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid 학년", fog: "Gunning Fog 지수", ari: "자동 가독성 지수", smog: "SMOG 지수" },
  hi: { title: "पठनीयता स्कोर चेकर", short: "Flesch, Flesch–Kincaid, Gunning Fog, ARI और SMOG गणना करें।", description: "मुफ्त पठनीयता चेकर। अंग्रेज़ी पाठ पेस्ट करें और Flesch Reading Ease, Flesch–Kincaid Grade Level, Gunning Fog, Automated Readability Index और SMOG से स्कोर करें — स्पष्टता के लिए संपादन में उपयोगी। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["पठनीयता चेकर", "flesch reading ease", "flesch kincaid", "gunning fog", "smog सूचकांक"], input: "टेक्स्ट", sentences: "वाक्य", words: "शब्द", syllables: "अक्षर", complexWords: "जटिल शब्द", characters: "वर्ण", flesch: "Flesch Reading Ease (0–100)", fk: "Flesch–Kincaid ग्रेड", fog: "Gunning Fog सूचकांक", ari: "स्वचालित पठनीयता सूचकांक", smog: "SMOG सूचकांक" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
