import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Online Notepad", short: "A free distraction-free notepad that autosaves in your browser.", description: "Free online notepad. Write notes that autosave to your browser's local storage, see live word and character counts, and download your text as a .txt file. No account, no upload — everything stays on your device.", keywords: ["online notepad", "free notepad", "browser notepad", "autosave notes", "text editor online"], placeholder: "Start typing your notes…", words: "Words", characters: "Characters", noSpaces: "No spaces", lines: "Lines", download: "Download .txt", saved: "Saved", saving: "Saving…" },
  nl: { title: "Online Notepad", short: "A gratis distraction-gratis notepad that autosaves in uw browser.", description: "Gratis online notepad. Write notes that autosave to uw browser's local storage, see live word and character counts, and download your tekst as a .txt file. No account, no upload — everything stays on your device.", keywords: ["online notepad", "gratis notepad", "browser notepad", "autosave notes", "tekst editor online"], placeholder: "Start typing your notes…", words: "Words", characters: "Characters", noSpaces: "No spaces", lines: "Lines", download: "Download .txt", saved: "Opslaand", saving: "Saving…" },

  pl: { title: "Online Notepad", short: "A darmowy distraction-darmowy notepad that autosaves w Twojej przeglądarce.", description: "Darmowy online notepad. Write notes that autosave to Twoja przeglądarka's local storage, see live word and character counts, and download your tekst as a .txt file. No account, no upload — everything stays on your device.", keywords: ["online notepad", "darmowy notepad", "browser notepad", "autosave notes", "tekst editor online"], placeholder: "Start typing your notes…", words: "Words", characters: "Characters", noSpaces: "No spaces", lines: "Lines", download: "Download .txt", saved: "Zapiszd", saving: "Saving…" },
  pt: { title: "Bloco de Notas Online", short: "Um bloco de notas gratuito sem distrações que salva automaticamente no navegador.", description: "Bloco de notas online gratuito. Escreva notas que são salvas automaticamente no armazenamento local do navegador, veja contagens de palavras e caracteres ao vivo e baixe seu texto como um arquivo .txt. Sem conta, sem upload.", keywords: ["online notepad", "free notepad", "browser notepad", "autosave notes", "text editor online"], placeholder: "Comece a digitar suas notas…", words: "Palavras", characters: "Caracteres", noSpaces: "Sem espaços", lines: "Linhas", download: "Baixar .txt", saved: "Salvo", saving: "Salvando…" },
  id: { title: "Notepad Online", short: "Notepad gratis tanpa gangguan yang menyimpan otomatis di browser.", description: "Notepad online gratis. Tulis catatan yang tersimpan otomatis ke penyimpanan lokal browser, lihat jumlah kata dan karakter secara langsung, dan unduh teks sebagai file .txt. Tanpa akun, tanpa unggah.", keywords: ["online notepad", "free notepad", "browser notepad", "autosave notes", "text editor online"], placeholder: "Mulai ketik catatan Anda…", words: "Kata", characters: "Karakter", noSpaces: "Tanpa spasi", lines: "Baris", download: "Unduh .txt", saved: "Tersimpan", saving: "Menyimpan…" },

  tr: { title: "Çevrimiçi Not Defteri", short: "Tarayıcınızda otomatik kaydeden, dikkat dağıtmayan ücretsiz bir not defteri.", description: "Ücretsiz çevrimiçi not defteri. Tarayıcınızın yerel depolamasına otomatik kaydedilen notlar yazın, canlı kelime ve karakter sayılarını görün ve metninizi .txt dosyası olarak indirin. Hesap yok, yükleme yok.", keywords: ["çevrimiçi not defteri", "ücretsiz not defteri", "tarayıcı not defteri", "otomatik kayıt notlar", "çevrimiçi metin editörü"], placeholder: "Notlarınızı yazmaya başlayın…", words: "Kelime", characters: "Karakter", noSpaces: "Boşluksuz", lines: "Satır", download: ".txt indir", saved: "Kaydedildi", saving: "Kaydediliyor…" },
  de: { title: "Online-Notizblock", short: "Ein kostenloser, ablenkungsfreier Notizblock mit automatischem Speichern im Browser.", description: "Kostenloser Online-Notizblock. Schreiben Sie Notizen, die automatisch im lokalen Speicher Ihres Browsers gespeichert werden, sehen Sie Wort- und Zeichenzahlen in Echtzeit und laden Sie Ihren Text als .txt-Datei herunter. Kein Konto, kein Upload.", keywords: ["online notizblock", "kostenloser notizblock", "browser notizblock", "notizen automatisch speichern", "texteditor online"], placeholder: "Beginnen Sie mit dem Schreiben Ihrer Notizen…", words: "Wörter", characters: "Zeichen", noSpaces: "Ohne Leerzeichen", lines: "Zeilen", download: ".txt herunterladen", saved: "Gespeichert", saving: "Speichern…" },
  fr: { title: "Bloc-notes en Ligne", short: "Un bloc-notes gratuit sans distraction qui s'enregistre automatiquement dans votre navigateur.", description: "Bloc-notes en ligne gratuit. Écrivez des notes enregistrées automatiquement dans le stockage local de votre navigateur, voyez le nombre de mots et de caractères en temps réel et téléchargez votre texte en fichier .txt. Sans compte, sans envoi.", keywords: ["bloc-notes en ligne", "bloc-notes gratuit", "bloc-notes navigateur", "notes enregistrement auto", "éditeur de texte en ligne"], placeholder: "Commencez à écrire vos notes…", words: "Mots", characters: "Caractères", noSpaces: "Sans espaces", lines: "Lignes", download: "Télécharger .txt", saved: "Enregistré", saving: "Enregistrement…" },
  es: { title: "Bloc de Notas en Línea", short: "Un bloc de notas gratuito sin distracciones que se guarda automáticamente en tu navegador.", description: "Bloc de notas en línea gratuito. Escribe notas que se guardan automáticamente en el almacenamiento local de tu navegador, ve el recuento de palabras y caracteres en vivo y descarga tu texto como archivo .txt. Sin cuenta, sin subidas.", keywords: ["bloc de notas en línea", "bloc de notas gratis", "bloc de notas navegador", "notas autoguardado", "editor de texto en línea"], placeholder: "Empieza a escribir tus notas…", words: "Palabras", characters: "Caracteres", noSpaces: "Sin espacios", lines: "Líneas", download: "Descargar .txt", saved: "Guardado", saving: "Guardando…" },
  it: { title: "Blocco Note Online", short: "Un blocco note gratuito senza distrazioni che si salva automaticamente nel browser.", description: "Blocco note online gratuito. Scrivi note che vengono salvate automaticamente nella memoria locale del browser, vedi il conteggio di parole e caratteri in tempo reale e scarica il tuo testo come file .txt. Nessun account, nessun caricamento.", keywords: ["blocco note online", "blocco note gratuito", "blocco note browser", "note salvataggio automatico", "editor di testo online"], placeholder: "Inizia a scrivere le tue note…", words: "Parole", characters: "Caratteri", noSpaces: "Senza spazi", lines: "Righe", download: "Scarica .txt", saved: "Salvato", saving: "Salvataggio…" },
  ar: { title: "مفكرة على الإنترنت", short: "مفكرة مجانية خالية من التشتيت تحفظ تلقائيًا في متصفحك.", description: "مفكرة مجانية على الإنترنت. اكتب ملاحظات تُحفظ تلقائيًا في التخزين المحلي لمتصفحك، وشاهد عدد الكلمات والأحرف مباشرة، ونزّل نصك كملف .txt. بدون حساب، بدون رفع — كل شيء يبقى على جهازك.", keywords: ["مفكرة على الإنترنت", "مفكرة مجانية", "مفكرة المتصفح", "حفظ تلقائي للملاحظات", "محرر نصوص على الإنترنت"], placeholder: "ابدأ بكتابة ملاحظاتك…", words: "الكلمات", characters: "الأحرف", noSpaces: "بدون مسافات", lines: "الأسطر", download: "تنزيل .txt", saved: "تم الحفظ", saving: "جارٍ الحفظ…" },
  ru: { title: "Онлайн-блокнот", short: "Бесплатный блокнот без отвлечений, который автосохраняется в браузере.", description: "Бесплатный онлайн-блокнот. Пишите заметки, которые автоматически сохраняются в локальном хранилище браузера, смотрите счётчик слов и символов в реальном времени и скачивайте текст в виде файла .txt. Без аккаунта и без загрузки на сервер.", keywords: ["онлайн блокнот", "бесплатный блокнот", "блокнот в браузере", "автосохранение заметок", "текстовый редактор онлайн"], placeholder: "Начните печатать свои заметки…", words: "Слова", characters: "Символы", noSpaces: "Без пробелов", lines: "Строки", download: "Скачать .txt", saved: "Сохранено", saving: "Сохранение…" },
  zh: { title: "在线记事本", short: "一个免费、无干扰、在浏览器中自动保存的记事本。", description: "免费的在线记事本。撰写自动保存到浏览器本地存储的笔记，实时查看字数和字符数，并将文本下载为 .txt 文件。无需账户、无需上传，一切都留在您的设备上。", keywords: ["在线记事本", "免费记事本", "浏览器记事本", "自动保存笔记", "在线文本编辑器"], placeholder: "开始输入你的笔记…", words: "字数", characters: "字符", noSpaces: "不含空格", lines: "行数", download: "下载 .txt", saved: "已保存", saving: "保存中…" },
  ja: { title: "オンラインメモ帳", short: "ブラウザに自動保存される、無料で気が散らないメモ帳。", description: "無料のオンラインメモ帳。ブラウザのローカルストレージに自動保存されるメモを書き、単語数と文字数をリアルタイムで確認し、テキストを .txt ファイルとしてダウンロードできます。アカウント不要、アップロードなし。", keywords: ["オンラインメモ帳", "無料メモ帳", "ブラウザメモ帳", "メモ自動保存", "オンラインテキストエディタ"], placeholder: "メモを入力してください…", words: "単語数", characters: "文字数", noSpaces: "空白を除く", lines: "行数", download: ".txt をダウンロード", saved: "保存済み", saving: "保存中…" },
  ko: { title: "온라인 메모장", short: "브라우저에 자동 저장되는 무료 방해 없는 메모장.", description: "무료 온라인 메모장. 브라우저의 로컬 저장소에 자동 저장되는 메모를 작성하고, 단어 및 문자 수를 실시간으로 확인하며, 텍스트를 .txt 파일로 다운로드하세요. 계정도 업로드도 필요 없으며 모든 것이 기기에 남습니다.", keywords: ["온라인 메모장", "무료 메모장", "브라우저 메모장", "메모 자동 저장", "온라인 텍스트 편집기"], placeholder: "메모를 입력하세요…", words: "단어", characters: "문자", noSpaces: "공백 제외", lines: "줄", download: ".txt 다운로드", saved: "저장됨", saving: "저장 중…" },
  hi: { title: "ऑनलाइन नोटपैड", short: "एक मुफ्त, ध्यान भटकाने वाला नहीं, ब्राउज़र में स्वतः सहेजने वाला नोटपैड।", description: "मुफ्त ऑनलाइन नोटपैड। ऐसे नोट लिखें जो आपके ब्राउज़र के लोकल स्टोरेज में स्वतः सहेजे जाते हैं, शब्द और वर्ण गणना लाइव देखें, और अपने टेक्स्ट को .txt फ़ाइल के रूप में डाउनलोड करें। कोई खाता नहीं, कोई अपलोड नहीं।", keywords: ["ऑनलाइन नोटपैड", "मुफ्त नोटपैड", "ब्राउज़र नोटपैड", "स्वतः सहेजने वाले नोट", "ऑनलाइन टेक्स्ट एडिटर"], placeholder: "अपने नोट टाइप करना शुरू करें…", words: "शब्द", characters: "वर्ण", noSpaces: "बिना स्पेस", lines: "पंक्तियाँ", download: ".txt डाउनलोड करें", saved: "सहेजा गया", saving: "सहेजा जा रहा है…" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
