import type { CalculatorI18n } from "@/types/i18n";

const io = (pa: string, qa: string, pb: string, qb: string, ua: string, ub: string, sv: string) => ({
  inputs: { priceA: { label: pa }, quantityA: { label: qa }, priceB: { label: pb }, quantityB: { label: qb } },
  outputs: { unitPriceA: { label: ua }, unitPriceB: { label: ub }, savingsPercent: { label: sv } },
});

const i18n: CalculatorI18n = {
  en: { title: "Unit Price Comparison Calculator", short: "Compare two products by price per unit to find the better value.", description: "Free unit price calculator. Enter the price and quantity of two products to compare their price per unit and see how much cheaper the better-value option is. Perfect for smart grocery shopping.", keywords: ["unit price calculator", "price per unit", "cost comparison", "price comparison", "best value calculator"], ...io("Price A", "Quantity A", "Price B", "Quantity B", "Unit price A", "Unit price B", "Cheaper by"), faq: [{ q: "How do I compare prices by unit?", a: "Divide each price by its quantity to get price per unit, then compare. $3.50 for 500 g is $0.007/g; $6 for 1000 g is $0.006/g — B is cheaper per gram." }, { q: "Why use the same unit?", a: "Only compare price per gram with price per gram (or per ml, per item). Mixing units gives a meaningless comparison." }] },
  pt: { title: "Calculadora de Preço Unitário", short: "Compare preços unitários para encontrar a melhor oferta.", description: "Calculadora gratuita de preço unitário. Compare o custo por unidade (g, kg, ml, l) de produtos para encontrar a opção mais barata.", keywords: ["preço unitário", "preço por kg", "comparar preços", "melhor oferta", "preço por litro"], ...io("Price A", "Quantity A", "Price B", "Quantity B", "Unit price A", "Unit price B", "Cheaper by"), faq: [{ q: "How do I compare prices by unit?", a: "Divide each price by its quantity to get price per unit, then compare. $3.50 for 500 g is $0.007/g; $6 for 1000 g is $0.006/g — B is cheaper per gram." }, { q: "Why use the same unit?", a: "Only compare price per gram with price per gram (or per ml, per item). Mixing units gives a meaningless comparison." }] },
  id: { title: "Kalkulator Harga Satuan", short: "Bandingkan harga per satuan untuk menemukan penawaran terbaik.", description: "Kalkulator harga satuan gratis. Bandingkan harga per satuan (g, kg, ml, l) produk untuk menemukan pilihan paling murah.", keywords: ["harga satuan", "harga per kg", "bandingkan harga", "penawaran terbaik", "harga per liter"], ...io("Price A", "Quantity A", "Price B", "Quantity B", "Unit price A", "Unit price B", "Cheaper by"), faq: [{ q: "How do I compare prices by unit?", a: "Divide each price by its quantity to get price per unit, then compare. $3.50 for 500 g is $0.007/g; $6 for 1000 g is $0.006/g — B is cheaper per gram." }, { q: "Why use the same unit?", a: "Only compare price per gram with price per gram (or per ml, per item). Mixing units gives a meaningless comparison." }] },

  tr: { title: "Birim Fiyat Karşılaştırma Hesaplayıcı", short: "İki ürünü birim fiyata göre karşılaştırarak daha avantajlısını bulun.", description: "Ücretsiz birim fiyat hesaplayıcı. İki ürünün fiyat ve miktarını girerek birim fiyatlarını karşılaştırın ve daha avantajlı seçeneğin ne kadar ucuz olduğunu görün. Akıllı market alışverişi için ideal.", keywords: ["birim fiyat hesaplama", "birim başına fiyat", "maliyet karşılaştırma", "fiyat karşılaştırma", "en avantajlı"], ...io("Fiyat A", "Miktar A", "Fiyat B", "Miktar B", "Birim fiyat A", "Birim fiyat B", "Şu kadar ucuz"), faq: [{ q: "Fiyatları birime göre nasıl karşılaştırırım?", a: "Her fiyatı miktarına bölerek birim fiyatı bulun ve karşılaştırın. 500 g için 3,50 ₺ → 0,007 ₺/g; 1000 g için 6 ₺ → 0,006 ₺/g — B gram başına daha ucuz." }, { q: "Neden aynı birimi kullanmalıyım?", a: "Gram başına fiyatı yalnızca gram başına fiyatla (veya ml, adet başına) karşılaştırın. Birimleri karıştırmak anlamsız sonuç verir." }] },
  de: { title: "Grundpreis-Vergleichsrechner", short: "Vergleichen Sie zwei Produkte nach Preis pro Einheit.", description: "Kostenloser Grundpreis-Rechner. Geben Sie Preis und Menge zweier Produkte ein, um den Preis pro Einheit zu vergleichen und zu sehen, um wie viel das günstigere Angebot billiger ist.", keywords: ["grundpreis rechner", "preis pro einheit", "kostenvergleich", "preisvergleich", "bester wert"], ...io("Preis A", "Menge A", "Preis B", "Menge B", "Grundpreis A", "Grundpreis B", "Günstiger um") },
  fr: { title: "Calculateur de Prix Unitaire", short: "Comparez deux produits par prix à l'unité pour trouver le meilleur rapport.", description: "Calculateur de prix unitaire gratuit. Saisissez le prix et la quantité de deux produits pour comparer leur prix à l'unité et voir de combien l'option la plus avantageuse est moins chère.", keywords: ["calculateur prix unitaire", "prix à l'unité", "comparaison de coûts", "comparaison de prix", "meilleur rapport"], ...io("Prix A", "Quantité A", "Prix B", "Quantité B", "Prix unitaire A", "Prix unitaire B", "Moins cher de") },
  es: { title: "Calculadora de Precio por Unidad", short: "Compara dos productos por precio unitario para hallar el mejor valor.", description: "Calculadora de precio unitario gratuita. Introduce el precio y la cantidad de dos productos para comparar su precio por unidad y ver cuánto más barata es la opción de mejor valor.", keywords: ["calculadora precio por unidad", "precio unitario", "comparación de costes", "comparación de precios", "mejor valor"], ...io("Precio A", "Cantidad A", "Precio B", "Cantidad B", "Precio unitario A", "Precio unitario B", "Más barato un") },
  it: { title: "Calcolatore Prezzo Unitario", short: "Confronta due prodotti per prezzo unitario per trovare la convenienza.", description: "Calcolatore di prezzo unitario gratuito. Inserisci prezzo e quantità di due prodotti per confrontare il prezzo per unità e vedere quanto è più economica l'opzione più conveniente.", keywords: ["calcolatore prezzo unitario", "prezzo per unità", "confronto costi", "confronto prezzi", "miglior valore"], ...io("Prezzo A", "Quantità A", "Prezzo B", "Quantità B", "Prezzo unitario A", "Prezzo unitario B", "Più economico del") },
  ar: { title: "حاسبة سعر الوحدة", short: "قارن منتجين حسب سعر الوحدة لإيجاد الأفضل قيمة.", description: "حاسبة سعر وحدة مجانية. أدخل سعر وكمية منتجين لمقارنة سعر الوحدة ومعرفة كم يكون الخيار الأفضل أرخص. مثالية للتسوق الذكي.", keywords: ["حاسبة سعر الوحدة", "السعر لكل وحدة", "مقارنة التكلفة", "مقارنة الأسعار", "أفضل قيمة"], ...io("السعر A", "الكمية A", "السعر B", "الكمية B", "سعر الوحدة A", "سعر الوحدة B", "أرخص بنسبة") },
  ru: { title: "Калькулятор Цены за Единицу", short: "Сравните два товара по цене за единицу, чтобы найти выгоднее.", description: "Бесплатный калькулятор цены за единицу. Введите цену и количество двух товаров, чтобы сравнить цену за единицу и увидеть, насколько дешевле более выгодный вариант.", keywords: ["калькулятор цены за единицу", "цена за единицу", "сравнение стоимости", "сравнение цен", "лучшая цена"], ...io("Цена A", "Количество A", "Цена B", "Количество B", "Цена за ед. A", "Цена за ед. B", "Дешевле на") },
  zh: { title: "单价比较计算器", short: "按单价比较两种商品，找出更划算的选择。", description: "免费的单价计算器。输入两种商品的价格和数量，比较它们的单价，并查看更划算的选项便宜多少。适合精明的超市购物。", keywords: ["单价计算器", "每单位价格", "成本比较", "价格比较", "最佳性价比"], ...io("价格 A", "数量 A", "价格 B", "数量 B", "单价 A", "单价 B", "便宜了") },
  ja: { title: "単価比較計算機", short: "2つの商品を単価で比較してお得な方を見つけます。", description: "無料の単価計算機。2つの商品の価格と数量を入力すると、単価を比較し、お得な方がどれだけ安いかがわかります。賢い買い物に最適。", keywords: ["単価 計算機", "1単位あたりの価格", "コスト比較", "価格比較", "最もお得"], ...io("価格 A", "数量 A", "価格 B", "数量 B", "単価 A", "単価 B", "安さ") },
  ko: { title: "단가 비교 계산기", short: "두 상품을 단가로 비교하여 더 나은 가치를 찾습니다.", description: "무료 단가 계산기. 두 상품의 가격과 수량을 입력하면 단가를 비교하고 더 나은 옵션이 얼마나 저렴한지 확인할 수 있습니다. 현명한 장보기에 적합합니다.", keywords: ["단가 계산기", "단위당 가격", "비용 비교", "가격 비교", "최고 가성비"], ...io("가격 A", "수량 A", "가격 B", "수량 B", "단가 A", "단가 B", "더 저렴") },
  hi: { title: "इकाई मूल्य तुलना कैलकुलेटर", short: "बेहतर मूल्य खोजने के लिए दो उत्पादों की प्रति इकाई कीमत तुलना करें।", description: "मुफ्त इकाई मूल्य कैलकुलेटर। दो उत्पादों की कीमत और मात्रा दर्ज करें और उनकी प्रति इकाई कीमत तुलना करें और देखें कि बेहतर विकल्प कितना सस्ता है। स्मार्ट खरीदारी के लिए उत्तम।", keywords: ["इकाई मूल्य कैलकुलेटर", "प्रति इकाई कीमत", "लागत तुलना", "मूल्य तुलना", "सर्वोत्तम मूल्य"], ...io("कीमत A", "मात्रा A", "कीमत B", "मात्रा B", "इकाई मूल्य A", "इकाई मूल्य B", "इतना सस्ता") },
};

export default i18n;
