import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "HTML Entity Encode / Decode", short: "Escape text to HTML entities or decode HTML entities back to text.", description: "Free HTML entity encoder and decoder. Escape characters like &, <, >, \" and ' to safe HTML entities, or decode named and numeric entities back to plain text. Runs in your browser.", keywords: ["html entities", "html encode", "html decode", "escape html", "entity encoder", "html escape"], encode: "Encode", decode: "Decode", placeholder: "Enter text or HTML…" },
  tr: { title: "HTML Varlık Kodla / Çöz", short: "Metni HTML varlıklarına kaçışlayın veya HTML varlıklarını metne çözün.", description: "Ücretsiz HTML varlık kodlayıcı ve çözücü. &, <, >, \" ve ' gibi karakterleri güvenli HTML varlıklarına kaçışlayın veya adlandırılmış ve sayısal varlıkları düz metne çözün. Tarayıcınızda çalışır.", keywords: ["html varlıkları", "html kodlama", "html çözme", "html kaçış", "varlık kodlayıcı"], encode: "Kodla", decode: "Çöz", placeholder: "Metin veya HTML girin…" },
  de: { title: "HTML-Entitäten Kodieren / Dekodieren", short: "Text in HTML-Entitäten umwandeln oder HTML-Entitäten zurück dekodieren.", description: "Kostenloser HTML-Entitäten-Encoder und -Decoder. Maskieren Sie Zeichen wie &, <, >, \" und ' zu sicheren HTML-Entitäten oder dekodieren Sie benannte und numerische Entitäten zurück.", keywords: ["html entitäten", "html kodieren", "html dekodieren", "html maskieren", "entity encoder"], encode: "Kodieren", decode: "Dekodieren", placeholder: "Text oder HTML eingeben…" },
  fr: { title: "Encoder / Décoder les Entités HTML", short: "Échappez du texte en entités HTML ou décodez des entités HTML en texte.", description: "Encodeur et décodeur d'entités HTML gratuit. Échappez des caractères comme &, <, >, \" et ' en entités HTML sûres, ou décodez les entités nommées et numériques en texte brut.", keywords: ["entités html", "encoder html", "décoder html", "échapper html", "encodeur d'entités"], encode: "Encoder", decode: "Décoder", placeholder: "Saisissez du texte ou du HTML…" },
  es: { title: "Codificar / Decodificar Entidades HTML", short: "Escapa texto a entidades HTML o decodifica entidades HTML a texto.", description: "Codificador y decodificador de entidades HTML gratuito. Escapa caracteres como &, <, >, \" y ' a entidades HTML seguras, o decodifica entidades con nombre y numéricas a texto.", keywords: ["entidades html", "codificar html", "decodificar html", "escapar html", "codificador de entidades"], encode: "Codificar", decode: "Decodificar", placeholder: "Introduce texto o HTML…" },
  it: { title: "Codifica / Decodifica Entità HTML", short: "Converti il testo in entità HTML o decodifica le entità HTML in testo.", description: "Codificatore e decodificatore di entità HTML gratuito. Effettua l'escape di caratteri come &, <, >, \" e ' in entità HTML sicure, o decodifica entità con nome e numeriche in testo.", keywords: ["entità html", "codifica html", "decodifica html", "escape html", "codificatore di entità"], encode: "Codifica", decode: "Decodifica", placeholder: "Inserisci testo o HTML…" },
  ar: { title: "ترميز / فك ترميز كيانات HTML", short: "حوّل النص إلى كيانات HTML أو فك ترميز كيانات HTML إلى نص.", description: "مرمّز ومفكّك كيانات HTML مجاني. حوّل أحرفًا مثل &، <، >، \" و' إلى كيانات HTML آمنة، أو فك ترميز الكيانات المسماة والرقمية إلى نص.", keywords: ["كيانات html", "ترميز html", "فك ترميز html", "هروب html", "مرمز الكيانات"], encode: "ترميز", decode: "فك الترميز", placeholder: "أدخل نصًا أو HTML…" },
  ru: { title: "Кодирование / Декодирование HTML-сущностей", short: "Экранируйте текст в HTML-сущности или декодируйте HTML-сущности обратно.", description: "Бесплатный кодировщик и декодировщик HTML-сущностей. Экранируйте символы вроде &, <, >, \" и ' в безопасные HTML-сущности или декодируйте именованные и числовые сущности в текст.", keywords: ["html сущности", "кодирование html", "декодирование html", "экранирование html", "кодировщик сущностей"], encode: "Кодировать", decode: "Декодировать", placeholder: "Введите текст или HTML…" },
  zh: { title: "HTML 实体编码 / 解码", short: "将文本转义为 HTML 实体，或将 HTML 实体解码为文本。", description: "免费的 HTML 实体编码器和解码器。将 &、<、>、\" 和 ' 等字符转义为安全的 HTML 实体，或将命名实体和数字实体解码为纯文本。在浏览器中运行。", keywords: ["html实体", "html编码", "html解码", "转义html", "实体编码器"], encode: "编码", decode: "解码", placeholder: "输入文本或 HTML…" },
  ja: { title: "HTML エンティティ エンコード / デコード", short: "テキストを HTML エンティティにエスケープ、または HTML エンティティをデコードします。", description: "無料の HTML エンティティ エンコーダー・デコーダー。&、<、>、\"、' などの文字を安全な HTML エンティティにエスケープ、または名前付き・数値エンティティをテキストにデコードします。", keywords: ["html エンティティ", "html エンコード", "html デコード", "html エスケープ", "エンティティ エンコーダー"], encode: "エンコード", decode: "デコード", placeholder: "テキストまたは HTML を入力…" },
  ko: { title: "HTML 엔티티 인코딩 / 디코딩", short: "텍스트를 HTML 엔티티로 이스케이프하거나 HTML 엔티티를 텍스트로 디코딩합니다.", description: "무료 HTML 엔티티 인코더 및 디코더. &, <, >, \", ' 같은 문자를 안전한 HTML 엔티티로 이스케이프하거나, 명명된/숫자 엔티티를 텍스트로 디코딩합니다.", keywords: ["html 엔티티", "html 인코딩", "html 디코딩", "html 이스케이프", "엔티티 인코더"], encode: "인코딩", decode: "디코딩", placeholder: "텍스트 또는 HTML 입력…" },
  hi: { title: "HTML एंटिटी एन्कोड / डिकोड", short: "टेक्स्ट को HTML एंटिटी में एस्केप करें या HTML एंटिटी को टेक्स्ट में डिकोड करें।", description: "मुफ्त HTML एंटिटी एन्कोडर और डिकोडर। &, <, >, \" और ' जैसे वर्णों को सुरक्षित HTML एंटिटी में एस्केप करें, या नामित व संख्यात्मक एंटिटी को सादे टेक्स्ट में डिकोड करें।", keywords: ["html एंटिटी", "html एन्कोड", "html डिकोड", "html एस्केप", "एंटिटी एन्कोडर"], encode: "एन्कोड", decode: "डिकोड", placeholder: "टेक्स्ट या HTML दर्ज करें…" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
