import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Schema Markup (JSON-LD) Generator", short: "Generate schema.org JSON-LD for articles, products, FAQs and more.", description: "Free schema.org JSON-LD generator. Pick a schema type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) and fill in the fields to get a ready-to-paste <script type=\"application/ld+json\"> block.", keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org json-ld", "rich snippets"], type: "Schema type", output: "JSON-LD", headline: "Headline", author: "Author", datePublished: "Date published", image: "Image URL", descriptionField: "Description", name: "Name", brand: "Brand", price: "Price", currency: "Currency", question: "Question", answer: "Answer", addQuestion: "Add question", street: "Street", locality: "Locality", region: "Region", postal: "Postal code", country: "Country", telephone: "Telephone", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Add breadcrumb" },
  nl: { title: "Schema Markup (JSON-LD) Generator", short: "Genereer schema.org JSON-LD for articles, products, FAQs and more.", description: "Gratis schema.org JSON-LD generator. Pick a schema type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) and fill in the fields to get a ready-to-paste <script type=\"application/ld+json\"> block.", keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org json-ld", "rich snippets"], type: "Schema type", output: "JSON-LD", headline: "Headline", author: "Author", datePublished: "Date published", image: "Afbeelding URL", descriptionField: "Description", name: "Name", brand: "Brand", price: "Price", currency: "Valuta", question: "Question", answer: "Answer", addQuestion: "Add question", street: "Street", locality: "Locality", region: "Region", postal: "Postal code", country: "Country", telephone: "Telephone", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Add breadcrumb" },

  pl: { title: "Schema Markup (JSON-LD) Generator", short: "Generuj schema.org JSON-LD for articles, products, FAQs and more.", description: "Darmowy schema.org JSON-LD generator. Pick a schema type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) and fill in the fields to get a ready-to-paste <script type=\"application/ld+json\"> block.", keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org json-ld", "rich snippets"], type: "Schema type", output: "JSON-LD", headline: "Headline", author: "Author", datePublished: "Date published", image: "Obraz URL", descriptionField: "Description", name: "Name", brand: "Brand", price: "Price", currency: "Waluta", question: "Question", answer: "Answer", addQuestion: "Add question", street: "Street", locality: "Locality", region: "Region", postal: "Postal kod", country: "Country", telephone: "Telephone", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Add breadcrumb" },
  pt: { title: "Gerador de Schema Markup (JSON-LD)", short: "Gerar schema.org JSON-LD para articles, products, FAQs e more.", description: "Gratuito - schema.org JSON-LD generator. Pick a schema type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) e fill em the fields para get a ready-para-paste <script type=\"application/ld+json\"> block.", keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org json-ld", "rich snippets"], type: "Schema type", output: "JSON-LD", headline: "Headline", author: "Author", datePublished: "Date published", image: "Image URL", descriptionField: "Description", name: "Name", brand: "Brand", price: "Price", currency: "Currency", question: "Question", answer: "Answer", addQuestion: "Add question", street: "Street", locality: "Locality", region: "Region", postal: "Postal code", country: "Country", telephone: "Telephone", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Add breadcrumb" },
  id: { title: "Generator Schema Markup (JSON-LD)", short: "Hasilkan schema.org JSON-LD for articles, products, FAQs dan more.", description: "Gratis - schema.org JSON-LD generator. Pick a schema type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) dan fill in the fields to get a ready-to-paste <script type=\"application/ld+json\"> block.", keywords: ["schema markup generator", "json-ld generator", "structured data generator", "schema.org json-ld", "rich snippets"], type: "Schema type", output: "JSON-LD", headline: "Headline", author: "Author", datePublished: "Date published", image: "Image URL", descriptionField: "Description", name: "Name", brand: "Brand", price: "Price", currency: "Currency", question: "Question", answer: "Answer", addQuestion: "Add question", street: "Street", locality: "Locality", region: "Region", postal: "Postal code", country: "Country", telephone: "Telephone", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Add breadcrumb" },

  tr: { title: "Schema Markup (JSON-LD) Oluşturucu", short: "Makale, ürün, SSS ve daha fazlası için schema.org JSON-LD oluşturun.", description: "Ücretsiz schema.org JSON-LD oluşturucu. Şema türünü (Article, Product, FAQ, LocalBusiness, BreadcrumbList) seçin ve alanları doldurarak yapıştırmaya hazır <script type=\"application/ld+json\"> bloğu alın.", keywords: ["schema markup oluşturucu", "json-ld oluşturucu", "yapılandırılmış veri oluşturucu", "schema.org json-ld", "rich snippets"], type: "Şema türü", output: "JSON-LD", headline: "Başlık", author: "Yazar", datePublished: "Yayın tarihi", image: "Görsel URL'si", descriptionField: "Açıklama", name: "Ad", brand: "Marka", price: "Fiyat", currency: "Para birimi", question: "Soru", answer: "Cevap", addQuestion: "Soru ekle", street: "Sokak", locality: "İlçe", region: "Bölge", postal: "Posta kodu", country: "Ülke", telephone: "Telefon", url: "URL", crumbName: "Ad", crumbUrl: "URL", addCrumb: "Breadcrumb ekle" },
  de: { title: "Schema-Markup-(JSON-LD)-Generator", short: "Erzeugen Sie schema.org JSON-LD für Artikel, Produkte, FAQs und mehr.", description: "Kostenloser schema.org-JSON-LD-Generator. Wählen Sie einen Schematyp (Article, Product, FAQ, LocalBusiness, BreadcrumbList) und füllen Sie die Felder aus, um einen einsatzbereiten <script type=\"application/ld+json\">-Block zu erhalten.", keywords: ["schema markup generator", "json-ld generator", "strukturierte daten generator", "schema.org json-ld", "rich snippets"], type: "Schematyp", output: "JSON-LD", headline: "Überschrift", author: "Autor", datePublished: "Veröffentlichungsdatum", image: "Bild-URL", descriptionField: "Beschreibung", name: "Name", brand: "Marke", price: "Preis", currency: "Währung", question: "Frage", answer: "Antwort", addQuestion: "Frage hinzufügen", street: "Straße", locality: "Stadt", region: "Region", postal: "Postleitzahl", country: "Land", telephone: "Telefon", url: "URL", crumbName: "Name", crumbUrl: "URL", addCrumb: "Breadcrumb hinzufügen" },
  fr: { title: "Générateur Schema Markup (JSON-LD)", short: "Générez du JSON-LD schema.org pour articles, produits, FAQs et plus.", description: "Générateur JSON-LD schema.org gratuit. Choisissez un type (Article, Product, FAQ, LocalBusiness, BreadcrumbList) et remplissez les champs pour obtenir un bloc <script type=\"application/ld+json\"> prêt à coller.", keywords: ["générateur schema markup", "générateur json-ld", "générateur données structurées", "schema.org json-ld", "rich snippets"], type: "Type de schéma", output: "JSON-LD", headline: "Titre", author: "Auteur", datePublished: "Date de publication", image: "URL de l'image", descriptionField: "Description", name: "Nom", brand: "Marque", price: "Prix", currency: "Devise", question: "Question", answer: "Réponse", addQuestion: "Ajouter une question", street: "Rue", locality: "Localité", region: "Région", postal: "Code postal", country: "Pays", telephone: "Téléphone", url: "URL", crumbName: "Nom", crumbUrl: "URL", addCrumb: "Ajouter un fil d'Ariane" },
  es: { title: "Generador de Schema Markup (JSON-LD)", short: "Genera JSON-LD schema.org para artículos, productos, FAQs y más.", description: "Generador JSON-LD schema.org gratuito. Elige un tipo (Article, Product, FAQ, LocalBusiness, BreadcrumbList) y rellena los campos para obtener un bloque <script type=\"application/ld+json\"> listo para pegar.", keywords: ["generador schema markup", "generador json-ld", "generador datos estructurados", "schema.org json-ld", "rich snippets"], type: "Tipo de schema", output: "JSON-LD", headline: "Titular", author: "Autor", datePublished: "Fecha de publicación", image: "URL de la imagen", descriptionField: "Descripción", name: "Nombre", brand: "Marca", price: "Precio", currency: "Moneda", question: "Pregunta", answer: "Respuesta", addQuestion: "Añadir pregunta", street: "Calle", locality: "Localidad", region: "Región", postal: "Código postal", country: "País", telephone: "Teléfono", url: "URL", crumbName: "Nombre", crumbUrl: "URL", addCrumb: "Añadir breadcrumb" },
  it: { title: "Generatore di Schema Markup (JSON-LD)", short: "Genera JSON-LD schema.org per articoli, prodotti, FAQ e altro.", description: "Generatore JSON-LD schema.org gratuito. Scegli un tipo (Article, Product, FAQ, LocalBusiness, BreadcrumbList) e compila i campi per ottenere un blocco <script type=\"application/ld+json\"> pronto da incollare.", keywords: ["generatore schema markup", "generatore json-ld", "generatore dati strutturati", "schema.org json-ld", "rich snippets"], type: "Tipo schema", output: "JSON-LD", headline: "Titolo", author: "Autore", datePublished: "Data di pubblicazione", image: "URL immagine", descriptionField: "Descrizione", name: "Nome", brand: "Marca", price: "Prezzo", currency: "Valuta", question: "Domanda", answer: "Risposta", addQuestion: "Aggiungi domanda", street: "Via", locality: "Località", region: "Regione", postal: "CAP", country: "Paese", telephone: "Telefono", url: "URL", crumbName: "Nome", crumbUrl: "URL", addCrumb: "Aggiungi breadcrumb" },
  ar: { title: "مولّد Schema Markup (JSON-LD)", short: "أنشئ JSON-LD لـ schema.org للمقالات والمنتجات والأسئلة الشائعة والمزيد.", description: "مولّد JSON-LD لـ schema.org مجاني. اختر نوع المخطط (Article، Product، FAQ، LocalBusiness، BreadcrumbList) واملأ الحقول للحصول على كتلة <script type=\"application/ld+json\"> جاهزة للصق.", keywords: ["مولد schema markup", "مولد json-ld", "مولد البيانات المنظمة", "schema.org json-ld", "rich snippets"], type: "نوع المخطط", output: "JSON-LD", headline: "العنوان الرئيسي", author: "المؤلف", datePublished: "تاريخ النشر", image: "عنوان URL للصورة", descriptionField: "الوصف", name: "الاسم", brand: "العلامة التجارية", price: "السعر", currency: "العملة", question: "السؤال", answer: "الإجابة", addQuestion: "إضافة سؤال", street: "الشارع", locality: "المدينة", region: "المنطقة", postal: "الرمز البريدي", country: "البلد", telephone: "الهاتف", url: "URL", crumbName: "الاسم", crumbUrl: "URL", addCrumb: "إضافة فتات الخبز" },
  ru: { title: "Генератор Schema Markup (JSON-LD)", short: "Создавайте schema.org JSON-LD для статей, товаров, FAQ и др.", description: "Бесплатный генератор schema.org JSON-LD. Выберите тип (Article, Product, FAQ, LocalBusiness, BreadcrumbList) и заполните поля, чтобы получить готовый блок <script type=\"application/ld+json\">.", keywords: ["генератор schema markup", "генератор json-ld", "генератор структурированных данных", "schema.org json-ld", "rich snippets"], type: "Тип схемы", output: "JSON-LD", headline: "Заголовок", author: "Автор", datePublished: "Дата публикации", image: "URL изображения", descriptionField: "Описание", name: "Имя", brand: "Бренд", price: "Цена", currency: "Валюта", question: "Вопрос", answer: "Ответ", addQuestion: "Добавить вопрос", street: "Улица", locality: "Город", region: "Регион", postal: "Индекс", country: "Страна", telephone: "Телефон", url: "URL", crumbName: "Имя", crumbUrl: "URL", addCrumb: "Добавить breadcrumb" },
  zh: { title: "Schema Markup（JSON-LD）生成器", short: "为文章、产品、FAQ 等生成 schema.org JSON-LD。", description: "免费的 schema.org JSON-LD 生成器。选择类型（Article、Product、FAQ、LocalBusiness、BreadcrumbList）并填写字段，即可获得可直接粘贴的 <script type=\"application/ld+json\"> 块。", keywords: ["schema 标记生成器", "json-ld 生成器", "结构化数据生成器", "schema.org json-ld", "富文本摘要"], type: "Schema 类型", output: "JSON-LD", headline: "标题", author: "作者", datePublished: "发布日期", image: "图片 URL", descriptionField: "描述", name: "名称", brand: "品牌", price: "价格", currency: "货币", question: "问题", answer: "答案", addQuestion: "添加问题", street: "街道", locality: "城市", region: "地区", postal: "邮编", country: "国家", telephone: "电话", url: "URL", crumbName: "名称", crumbUrl: "URL", addCrumb: "添加面包屑" },
  ja: { title: "Schema Markup（JSON-LD）生成", short: "記事、商品、FAQ などの schema.org JSON-LD を生成。", description: "無料の schema.org JSON-LD 生成ツール。タイプ（Article、Product、FAQ、LocalBusiness、BreadcrumbList）を選び、フィールドを記入すると、貼り付け可能な <script type=\"application/ld+json\"> ブロックが得られます。", keywords: ["schema マークアップ 生成", "json-ld 生成", "構造化データ 生成", "schema.org json-ld", "リッチスニペット"], type: "Schema タイプ", output: "JSON-LD", headline: "見出し", author: "著者", datePublished: "公開日", image: "画像 URL", descriptionField: "説明", name: "名前", brand: "ブランド", price: "価格", currency: "通貨", question: "質問", answer: "回答", addQuestion: "質問を追加", street: "番地", locality: "市区町村", region: "都道府県", postal: "郵便番号", country: "国", telephone: "電話", url: "URL", crumbName: "名前", crumbUrl: "URL", addCrumb: "パンくずを追加" },
  ko: { title: "Schema Markup(JSON-LD) 생성기", short: "기사, 제품, FAQ 등에 대한 schema.org JSON-LD를 생성합니다.", description: "무료 schema.org JSON-LD 생성기. 유형(Article, Product, FAQ, LocalBusiness, BreadcrumbList)을 선택하고 필드를 채우면 붙여넣을 수 있는 <script type=\"application/ld+json\"> 블록을 얻습니다.", keywords: ["schema 마크업 생성기", "json-ld 생성기", "구조화된 데이터 생성기", "schema.org json-ld", "리치 스니펫"], type: "Schema 유형", output: "JSON-LD", headline: "헤드라인", author: "작성자", datePublished: "게시일", image: "이미지 URL", descriptionField: "설명", name: "이름", brand: "브랜드", price: "가격", currency: "통화", question: "질문", answer: "답변", addQuestion: "질문 추가", street: "도로명", locality: "지역", region: "광역", postal: "우편번호", country: "국가", telephone: "전화", url: "URL", crumbName: "이름", crumbUrl: "URL", addCrumb: "브레드크럼 추가" },
  hi: { title: "Schema Markup (JSON-LD) जनरेटर", short: "लेख, उत्पाद, FAQ और अधिक के लिए schema.org JSON-LD बनाएं।", description: "मुफ्त schema.org JSON-LD जनरेटर। एक प्रकार (Article, Product, FAQ, LocalBusiness, BreadcrumbList) चुनें और फ़ील्ड भरें, और पेस्ट करने के लिए तैयार <script type=\"application/ld+json\"> ब्लॉक पाएं।", keywords: ["schema मार्कअप जनरेटर", "json-ld जनरेटर", "स्ट्रक्चर्ड डेटा जनरेटर", "schema.org json-ld", "रिच स्निपेट"], type: "Schema प्रकार", output: "JSON-LD", headline: "शीर्षक", author: "लेखक", datePublished: "प्रकाशन तिथि", image: "छवि URL", descriptionField: "विवरण", name: "नाम", brand: "ब्रांड", price: "मूल्य", currency: "मुद्रा", question: "प्रश्न", answer: "उत्तर", addQuestion: "प्रश्न जोड़ें", street: "गली", locality: "इलाका", region: "क्षेत्र", postal: "पिन कोड", country: "देश", telephone: "टेलीफोन", url: "URL", crumbName: "नाम", crumbUrl: "URL", addCrumb: "ब्रेडक्रंब जोड़ें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
