import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image to ASCII Art", short: "Convert any image to ASCII art in your browser.", description: "Free image to ASCII art generator. Drop an image, pick a character ramp and target width, and get ASCII art ready to paste — runs entirely in your browser via Canvas.", keywords: ["image to ascii", "ascii art generator", "photo to ascii", "ascii art", "text art"], drop: "Drop an image here or click to choose", width: "Width (cols)", ramp: "Character ramp", short2: "Short", long: "Detailed", invert: "Invert", output: "ASCII art" },
  pt: { title: "Image to ASCII Art", short: "Converter any image para ASCII art no seu navegador.", description: "Gratuito - image para ASCII art generator. Drop an image, pick a character ramp e target width, e get ASCII art ready para paste â runs entirely no seu navegador via Canvas.", keywords: ["image to ascii", "ascii art generator", "photo to ascii", "ascii art", "text art"], drop: "Drop an image here or click to choose", width: "Width (cols)", ramp: "Character ramp", short2: "Short", long: "Detailed", invert: "Invert", output: "ASCII art" },
  id: { title: "Image to ASCII Art", short: "Konversi any image to ASCII art di browser Anda.", description: "Gratis - image to ASCII art generator. Drop an image, pick a character ramp dan target width, dan get ASCII art ready to paste â runs entirely di browser Anda via Canvas.", keywords: ["image to ascii", "ascii art generator", "photo to ascii", "ascii art", "text art"], drop: "Drop an image here or click to choose", width: "Width (cols)", ramp: "Character ramp", short2: "Short", long: "Detailed", invert: "Invert", output: "ASCII art" },

  tr: { title: "Görselden ASCII Sanatı", short: "Herhangi bir görseli tarayıcınızda ASCII sanatına dönüştürün.", description: "Ücretsiz görselden ASCII sanatı oluşturucu. Bir görsel bırakın, karakter rampası ve hedef genişlik seçin ve yapıştırmaya hazır ASCII sanatı alın — tamamen tarayıcınızda Canvas ile çalışır.", keywords: ["görselden ascii", "ascii sanat oluşturucu", "fotoğraftan ascii", "ascii sanatı", "metin sanatı"], drop: "Bir görsel bırakın veya seçmek için tıklayın", width: "Genişlik (sütun)", ramp: "Karakter rampası", short2: "Kısa", long: "Ayrıntılı", invert: "Ters çevir", output: "ASCII sanatı" },
  de: { title: "Bild zu ASCII-Art", short: "Konvertieren Sie jedes Bild im Browser in ASCII-Kunst.", description: "Kostenloser Bild-zu-ASCII-Kunst-Generator. Legen Sie ein Bild ab, wählen Sie eine Zeichenleiter und Zielbreite und erhalten Sie ASCII-Kunst zum Einfügen — läuft vollständig im Browser über Canvas.", keywords: ["bild zu ascii", "ascii kunst generator", "foto zu ascii", "ascii kunst", "text kunst"], drop: "Bild hier ablegen oder klicken zum Auswählen", width: "Breite (Spalten)", ramp: "Zeichenleiter", short2: "Kurz", long: "Detailliert", invert: "Invertieren", output: "ASCII-Kunst" },
  fr: { title: "Image vers ASCII Art", short: "Convertissez n'importe quelle image en ASCII art dans votre navigateur.", description: "Générateur d'image vers ASCII art gratuit. Déposez une image, choisissez une rampe de caractères et une largeur cible, et obtenez de l'ASCII art prêt à coller — fonctionne entièrement dans votre navigateur via Canvas.", keywords: ["image vers ascii", "générateur ascii art", "photo vers ascii", "art ascii", "art texte"], drop: "Déposez une image ici ou cliquez pour choisir", width: "Largeur (colonnes)", ramp: "Rampe de caractères", short2: "Courte", long: "Détaillée", invert: "Inverser", output: "ASCII art" },
  es: { title: "Imagen a Arte ASCII", short: "Convierte cualquier imagen en arte ASCII en tu navegador.", description: "Generador de imagen a arte ASCII gratuito. Arrastra una imagen, elige una rampa de caracteres y un ancho objetivo, y obtén arte ASCII listo para pegar — funciona completamente en tu navegador con Canvas.", keywords: ["imagen a ascii", "generador arte ascii", "foto a ascii", "arte ascii", "arte texto"], drop: "Arrastra una imagen aquí o haz clic para elegir", width: "Ancho (columnas)", ramp: "Rampa de caracteres", short2: "Corta", long: "Detallada", invert: "Invertir", output: "Arte ASCII" },
  it: { title: "Immagine a Arte ASCII", short: "Converti qualsiasi immagine in arte ASCII nel browser.", description: "Generatore di arte ASCII gratuito. Trascina un'immagine, scegli una rampa di caratteri e una larghezza target, e ottieni arte ASCII pronta da incollare — funziona interamente nel browser tramite Canvas.", keywords: ["immagine a ascii", "generatore arte ascii", "foto a ascii", "arte ascii", "arte testo"], drop: "Trascina un'immagine qui o clicca per scegliere", width: "Larghezza (colonne)", ramp: "Rampa caratteri", short2: "Breve", long: "Dettagliata", invert: "Inverti", output: "Arte ASCII" },
  ar: { title: "صورة إلى فن ASCII", short: "حوّل أي صورة إلى فن ASCII في متصفحك.", description: "مولّد صورة إلى فن ASCII مجاني. أفلِت صورة، اختر سلم أحرف وعرضًا مستهدفًا واحصل على فن ASCII جاهز للصق — يعمل بالكامل في متصفحك عبر Canvas.", keywords: ["صورة إلى ascii", "مولد فن ascii", "صورة إلى ascii", "فن ascii", "فن النص"], drop: "أفلِت صورة هنا أو انقر للاختيار", width: "العرض (أعمدة)", ramp: "سلم الأحرف", short2: "قصير", long: "مفصل", invert: "عكس", output: "فن ASCII" },
  ru: { title: "Изображение в ASCII-арт", short: "Преобразуйте любое изображение в ASCII-арт в браузере.", description: "Бесплатный генератор ASCII-арта из изображения. Перетащите изображение, выберите шкалу символов и целевую ширину и получите ASCII-арт, готовый к вставке — работает полностью в браузере через Canvas.", keywords: ["изображение в ascii", "генератор ascii арта", "фото в ascii", "ascii арт", "текстовый арт"], drop: "Перетащите изображение сюда или нажмите для выбора", width: "Ширина (колонки)", ramp: "Шкала символов", short2: "Короткая", long: "Детальная", invert: "Инвертировать", output: "ASCII-арт" },
  zh: { title: "图片转 ASCII 艺术", short: "在浏览器中将任意图片转换为 ASCII 艺术。", description: "免费的图片转 ASCII 艺术生成器。拖入图片，选择字符梯度和目标宽度，获得可粘贴的 ASCII 艺术——通过 Canvas 完全在浏览器中运行。", keywords: ["图片转 ascii", "ascii 艺术生成器", "照片转 ascii", "ascii 艺术", "文字艺术"], drop: "将图片拖到此处或点击选择", width: "宽度（列）", ramp: "字符梯度", short2: "短", long: "详细", invert: "反转", output: "ASCII 艺术" },
  ja: { title: "画像から ASCII アート", short: "ブラウザ内で任意の画像を ASCII アートに変換。", description: "無料の画像から ASCII アート生成ツール。画像をドロップし、文字ランプとターゲット幅を選んで、貼り付け可能な ASCII アートを得ます——Canvas によりすべてブラウザ内で動作します。", keywords: ["画像 ascii", "ascii アート 生成", "写真 ascii", "ascii アート", "テキスト アート"], drop: "画像をここにドロップまたはクリックして選択", width: "幅（列）", ramp: "文字ランプ", short2: "短い", long: "詳細", invert: "反転", output: "ASCII アート" },
  ko: { title: "이미지를 ASCII 아트로", short: "브라우저에서 모든 이미지를 ASCII 아트로 변환합니다.", description: "무료 이미지를 ASCII 아트로 변환하는 생성기. 이미지를 드롭하고 문자 램프와 목표 너비를 선택해 붙여넣을 수 있는 ASCII 아트를 얻으세요 — Canvas를 통해 모두 브라우저에서 실행됩니다.", keywords: ["이미지 ascii", "ascii 아트 생성기", "사진 ascii", "ascii 아트", "텍스트 아트"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", width: "너비 (열)", ramp: "문자 램프", short2: "짧음", long: "상세", invert: "반전", output: "ASCII 아트" },
  hi: { title: "इमेज से ASCII कला", short: "अपने ब्राउज़र में किसी भी छवि को ASCII कला में बदलें।", description: "मुफ्त इमेज से ASCII कला जनरेटर। एक छवि छोड़ें, एक वर्ण रैंप और लक्ष्य चौड़ाई चुनें, और पेस्ट करने के लिए तैयार ASCII कला पाएं — Canvas के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["इमेज से ascii", "ascii कला जनरेटर", "फोटो से ascii", "ascii कला", "टेक्स्ट कला"], drop: "यहाँ एक छवि छोड़ें या चुनने के लिए क्लिक करें", width: "चौड़ाई (कॉलम)", ramp: "वर्ण रैंप", short2: "छोटा", long: "विस्तृत", invert: "उलटें", output: "ASCII कला" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
