import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Cron Next Runs", short: "Preview the next N execution times of a cron expression.", description: "Free cron next-run calculator. Paste a 5-field cron expression and see when it will fire next — handy for sanity-checking a schedule before deploying.", keywords: ["cron next runs", "cron preview", "next 10 cron runs", "cron simulator", "cron schedule preview"], expression: "Cron expression", count: "How many", upcoming: "Upcoming runs" },
  pt: { title: "Cron Next Runs", short: "Preview the next N execution times of a cron expression.", description: "Free cron next-run calculator. Paste a 5-field cron expression and see when it will fire next — handy for sanity-checking a schedule before deploying.", keywords: ["cron next runs", "cron preview", "next 10 cron runs", "cron simulator", "cron schedule preview"], expression: "Cron expression", count: "How many", upcoming: "Upcoming runs" },
  id: { title: "Cron Next Runs", short: "Preview the next N execution times of a cron expression.", description: "Free cron next-run calculator. Paste a 5-field cron expression and see when it will fire next — handy for sanity-checking a schedule before deploying.", keywords: ["cron next runs", "cron preview", "next 10 cron runs", "cron simulator", "cron schedule preview"], expression: "Cron expression", count: "How many", upcoming: "Upcoming runs" },

  tr: { title: "Cron Sonraki Çalışmalar", short: "Bir cron ifadesinin sonraki N çalışma zamanını önizleyin.", description: "Ücretsiz cron sonraki çalışma hesaplayıcı. 5 alanlı bir cron ifadesi yapıştırın ve bir sonraki ne zaman çalışacağını görün — bir zamanlamayı dağıtmadan önce doğrulamak için kullanışlı.", keywords: ["cron sonraki çalışmalar", "cron önizleme", "sonraki 10 cron çalışması", "cron simülatörü", "cron zamanlama önizleme"], expression: "Cron ifadesi", count: "Kaç tane", upcoming: "Yaklaşan çalışmalar" },
  de: { title: "Cron Nächste Ausführungen", short: "Sehen Sie die nächsten N Ausführungszeiten eines Cron-Ausdrucks.", description: "Kostenloser Cron-Nächste-Ausführungs-Rechner. Fügen Sie einen 5-Feld-Cron-Ausdruck ein und sehen Sie, wann er als nächstes ausgeführt wird — praktisch zur Plausibilitätsprüfung eines Zeitplans vor dem Deployment.", keywords: ["cron nächste ausführungen", "cron vorschau", "nächste 10 cron läufe", "cron simulator", "cron zeitplan vorschau"], expression: "Cron-Ausdruck", count: "Wie viele", upcoming: "Anstehende Ausführungen" },
  fr: { title: "Cron Prochaines Exécutions", short: "Prévisualisez les N prochaines exécutions d'une expression cron.", description: "Calculateur de prochaines exécutions cron gratuit. Collez une expression cron à 5 champs et voyez quand elle s'exécutera ensuite — pratique pour vérifier un planning avant déploiement.", keywords: ["cron prochaines exécutions", "aperçu cron", "10 prochaines exécutions cron", "simulateur cron", "aperçu planning cron"], expression: "Expression cron", count: "Combien", upcoming: "Exécutions à venir" },
  es: { title: "Próximas Ejecuciones Cron", short: "Previsualiza los próximos N tiempos de ejecución de una expresión cron.", description: "Calculadora gratuita de próximas ejecuciones cron. Pega una expresión cron de 5 campos y mira cuándo se ejecutará a continuación — útil para verificar un horario antes de implementar.", keywords: ["próximas ejecuciones cron", "vista previa cron", "próximas 10 ejecuciones cron", "simulador cron", "vista previa horario cron"], expression: "Expresión cron", count: "Cuántas", upcoming: "Próximas ejecuciones" },
  it: { title: "Prossime Esecuzioni Cron", short: "Anteprima delle prossime N esecuzioni di un'espressione cron.", description: "Calcolatore gratuito di prossime esecuzioni cron. Incolla un'espressione cron a 5 campi e vedi quando verrà eseguita successivamente — utile per verificare una pianificazione prima del deploy.", keywords: ["prossime esecuzioni cron", "anteprima cron", "prossime 10 esecuzioni cron", "simulatore cron", "anteprima pianificazione cron"], expression: "Espressione cron", count: "Quante", upcoming: "Prossime esecuzioni" },
  ar: { title: "تشغيلات Cron القادمة", short: "عاين أوقات التشغيل القادمة N لتعبير cron.", description: "حاسبة تشغيلات cron القادمة مجانية. الصق تعبير cron بـ 5 حقول واطلع على متى سيُشغَّل بعد ذلك — مفيد للتحقق من جدولة قبل النشر.", keywords: ["تشغيلات cron القادمة", "معاينة cron", "أول 10 تشغيلات cron", "محاكي cron", "معاينة جدولة cron"], expression: "تعبير cron", count: "كم العدد", upcoming: "التشغيلات القادمة" },
  ru: { title: "Cron Следующие Запуски", short: "Превью следующих N запусков cron-выражения.", description: "Бесплатный калькулятор следующих запусков cron. Вставьте 5-полевое cron-выражение и посмотрите, когда оно сработает дальше — удобно для проверки расписания перед развёртыванием.", keywords: ["cron следующие запуски", "превью cron", "следующие 10 запусков cron", "симулятор cron", "превью расписания cron"], expression: "Cron-выражение", count: "Сколько", upcoming: "Предстоящие запуски" },
  zh: { title: "Cron 后续运行", short: "预览 cron 表达式的下 N 次执行时间。", description: "免费的 cron 后续运行计算器。粘贴 5 字段 cron 表达式，查看下次执行时间——在部署前验证计划很有用。", keywords: ["cron 后续运行", "cron 预览", "下 10 次 cron 运行", "cron 模拟器", "cron 计划预览"], expression: "Cron 表达式", count: "数量", upcoming: "即将运行" },
  ja: { title: "Cron 次回実行", short: "Cron 式の次回 N 回の実行時刻をプレビュー。", description: "無料の cron 次回実行計算ツール。5 フィールドの cron 式を貼り付けて、次回いつ実行されるかを確認——デプロイ前のスケジュール検証に便利。", keywords: ["cron 次回実行", "cron プレビュー", "次回 10 回の cron 実行", "cron シミュレーター", "cron スケジュール プレビュー"], expression: "Cron 式", count: "件数", upcoming: "次回実行" },
  ko: { title: "Cron 다음 실행", short: "Cron 표현식의 다음 N개 실행 시간을 미리 봅니다.", description: "무료 cron 다음 실행 계산기. 5필드 cron 표현식을 붙여넣어 다음 실행 시점을 확인하세요 — 배포 전 일정 검증에 유용합니다.", keywords: ["cron 다음 실행", "cron 미리보기", "다음 10개 cron 실행", "cron 시뮬레이터", "cron 일정 미리보기"], expression: "Cron 표현식", count: "개수", upcoming: "다가오는 실행" },
  hi: { title: "Cron अगले रन", short: "एक cron एक्सप्रेशन के अगले N निष्पादन समय का पूर्वावलोकन करें।", description: "मुफ्त cron अगले रन कैलकुलेटर। 5-फ़ील्ड cron एक्सप्रेशन पेस्ट करें और देखें कि यह अगली बार कब चलेगा — तैनाती से पहले शेड्यूल की जांच के लिए उपयोगी।", keywords: ["cron अगले रन", "cron पूर्वावलोकन", "अगले 10 cron रन", "cron सिम्युलेटर", "cron शेड्यूल पूर्वावलोकन"], expression: "Cron एक्सप्रेशन", count: "कितने", upcoming: "आगामी रन" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
