import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Pong (Browser)", short: "The classic Pong, playable in your browser.", description: "A minimal browser-side Pong clone. Two-player on one keyboard (W/S vs ↑/↓) or you-vs-CPU. Canvas-based, runs entirely in your browser.", keywords: ["pong game", "browser pong", "javascript pong", "play pong online", "classic pong"], rightMode: "Right paddle", human: "Human (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Reset" },
  nl: { title: "Pong (Browser)", short: "The classic Pong, playable in uw browser.", description: "A minimal browser-side Pong clone. Two-player on one keyboard (W/S vs ↑/↓) or you-vs-CPU. Canvas-based, runs entirely in uw browser.", keywords: ["pong game", "browser pong", "javascript pong", "play pong online", "classic pong"], rightMode: "Right paddle", human: "Human (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Reset" },

  pl: { title: "Pong (Browser)", short: "The classic Pong, playable w Twojej przeglądarce.", description: "A minimal browser-side Pong clone. Two-player on one keyboard (W/S vs ↑/↓) or you-vs-CPU. Canvas-based, runs entirely w Twojej przeglądarce.", keywords: ["pong game", "browser pong", "javascript pong", "play pong online", "classic pong"], rightMode: "Right paddle", human: "Human (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Reset" },
  pt: { title: "Pong (Navegador)", short: "O classic Pong, playable no seu navegador.", description: "Um minimal browser-side Pong clone. Two-player on one keyboard (W/S vs â/â) ou you-vs-CPU. Canvas-based, runs entirely no seu navegador.", keywords: ["pong game", "browser pong", "javascript pong", "play pong online", "classic pong"], rightMode: "Right paddle", human: "Human (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Reset" },
  id: { title: "Pong (Browser)", short: " classic Pong, playable di browser Anda.", description: "Sebuah minimal browser-side Pong clone. Two-player on one keyboard (W/S vs â/â) atau you-vs-CPU. Canvas-based, runs entirely di browser Anda.", keywords: ["pong game", "browser pong", "javascript pong", "play pong online", "classic pong"], rightMode: "Right paddle", human: "Human (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Reset" },

  tr: { title: "Pong (Tarayıcı)", short: "Klasik Pong, tarayıcınızda oynanabilir.", description: "Minimal tarayıcı tabanlı Pong klonu. Bir klavyede iki oyunculu (W/S ile ↑/↓) veya CPU'ya karşı. Canvas tabanlı, tamamen tarayıcınızda çalışır.", keywords: ["pong oyunu", "tarayıcı pong", "javascript pong", "online pong oyna", "klasik pong"], rightMode: "Sağ raket", human: "İnsan (↑/↓)", cpu: "CPU", start: "Başla", pause: "Duraklat", reset: "Sıfırla" },
  de: { title: "Pong (Browser)", short: "Das klassische Pong, spielbar im Browser.", description: "Ein minimaler Browser-Pong-Klon. Zwei Spieler auf einer Tastatur (W/S vs ↑/↓) oder Du-gegen-CPU. Canvas-basiert, läuft vollständig im Browser.", keywords: ["pong spiel", "browser pong", "javascript pong", "pong online spielen", "klassisches pong"], rightMode: "Rechter Schläger", human: "Mensch (↑/↓)", cpu: "CPU", start: "Start", pause: "Pause", reset: "Zurücksetzen" },
  fr: { title: "Pong (Navigateur)", short: "Le Pong classique, jouable dans votre navigateur.", description: "Un clone Pong minimal dans le navigateur. Deux joueurs sur un clavier (W/S vs ↑/↓) ou vous-contre-CPU. Basé sur Canvas, fonctionne entièrement dans votre navigateur.", keywords: ["pong jeu", "pong navigateur", "javascript pong", "jouer pong en ligne", "pong classique"], rightMode: "Raquette droite", human: "Humain (↑/↓)", cpu: "CPU", start: "Démarrer", pause: "Pause", reset: "Réinitialiser" },
  es: { title: "Pong (Navegador)", short: "El Pong clásico, jugable en tu navegador.", description: "Un clon Pong minimal en el navegador. Dos jugadores en un teclado (W/S vs ↑/↓) o tú-contra-CPU. Basado en Canvas, funciona completamente en tu navegador.", keywords: ["juego pong", "pong navegador", "javascript pong", "jugar pong online", "pong clásico"], rightMode: "Pala derecha", human: "Humano (↑/↓)", cpu: "CPU", start: "Iniciar", pause: "Pausar", reset: "Reiniciar" },
  it: { title: "Pong (Browser)", short: "Il Pong classico, giocabile nel tuo browser.", description: "Un clone Pong minimale nel browser. Due giocatori su una tastiera (W/S vs ↑/↓) o tu-contro-CPU. Basato su Canvas, funziona interamente nel browser.", keywords: ["gioco pong", "pong browser", "javascript pong", "giocare pong online", "pong classico"], rightMode: "Racchetta destra", human: "Umano (↑/↓)", cpu: "CPU", start: "Avvia", pause: "Pausa", reset: "Reset" },
  ar: { title: "Pong (المتصفح)", short: "Pong الكلاسيكية، يمكن لعبها في متصفحك.", description: "نسخة Pong مينيمالية في المتصفح. لعب لاعبَين على لوحة مفاتيح واحدة (W/S مقابل ↑/↓) أو أنت ضد الكمبيوتر. Canvas، تعمل بالكامل في متصفحك.", keywords: ["لعبة pong", "متصفح pong", "javascript pong", "العب pong عبر الإنترنت", "pong كلاسيكية"], rightMode: "المضرب الأيمن", human: "إنسان (↑/↓)", cpu: "كمبيوتر", start: "ابدأ", pause: "إيقاف مؤقت", reset: "إعادة تعيين" },
  ru: { title: "Pong (Браузер)", short: "Классический Pong, играбельный в браузере.", description: "Минимальный клон Pong в браузере. Двое на одной клавиатуре (W/S vs ↑/↓) или ты-против-CPU. На Canvas, работает полностью в браузере.", keywords: ["игра pong", "браузер pong", "javascript pong", "играть pong онлайн", "классический pong"], rightMode: "Правая ракетка", human: "Человек (↑/↓)", cpu: "CPU", start: "Старт", pause: "Пауза", reset: "Сброс" },
  zh: { title: "Pong（浏览器）", short: "经典 Pong，可在浏览器中游玩。", description: "极简浏览器 Pong 克隆。同一键盘两人对战（W/S vs ↑/↓）或玩家对 CPU。基于 Canvas，完全在浏览器中运行。", keywords: ["pong 游戏", "浏览器 pong", "javascript pong", "在线玩 pong", "经典 pong"], rightMode: "右挡板", human: "人类 (↑/↓)", cpu: "CPU", start: "开始", pause: "暂停", reset: "重置" },
  ja: { title: "Pong（ブラウザ）", short: "クラシックな Pong をブラウザで。", description: "ミニマルなブラウザ Pong クローン。同じキーボードで2人プレイ（W/S vs ↑/↓）または対 CPU。Canvas ベース、すべてブラウザ内で動作します。", keywords: ["pong ゲーム", "ブラウザ pong", "javascript pong", "オンライン pong", "クラシック pong"], rightMode: "右パドル", human: "人間 (↑/↓)", cpu: "CPU", start: "開始", pause: "一時停止", reset: "リセット" },
  ko: { title: "Pong (브라우저)", short: "클래식 Pong, 브라우저에서 플레이.", description: "미니멀한 브라우저 Pong 클론. 한 키보드로 2인 플레이(W/S vs ↑/↓) 또는 사용자 대 CPU. Canvas 기반, 모두 브라우저에서 실행됩니다.", keywords: ["pong 게임", "브라우저 pong", "javascript pong", "온라인 pong", "클래식 pong"], rightMode: "오른쪽 패들", human: "사람 (↑/↓)", cpu: "CPU", start: "시작", pause: "일시 정지", reset: "초기화" },
  hi: { title: "Pong (ब्राउज़र)", short: "क्लासिक Pong, आपके ब्राउज़र में खेलने योग्य।", description: "मिनिमल ब्राउज़र Pong क्लोन। एक कीबोर्ड पर दो खिलाड़ी (W/S बनाम ↑/↓) या आप बनाम CPU। Canvas पर आधारित, पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["pong खेल", "ब्राउज़र pong", "javascript pong", "ऑनलाइन pong", "क्लासिक pong"], rightMode: "दाहिना पैडल", human: "मानव (↑/↓)", cpu: "CPU", start: "शुरू", pause: "रोकें", reset: "रीसेट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
