import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "UTM Campaign URL Builder", short: "Tag a URL with Google Analytics utm_* parameters.", description: "Free UTM URL builder. Fill in source, medium, campaign and optional term/content/id to tag a URL for Google Analytics or other analytics tools — runs entirely in your browser.", keywords: ["utm builder", "utm parameter generator", "campaign url builder", "google analytics utm", "utm tag generator"], url: "URL", source: "Source", medium: "Medium", campaign: "Campaign", term: "Term", content: "Content", id: "ID", result: "Tagged URL" },
  pt: { title: "Construtor de UTM Campaign URL", short: "Tag a URL com Google Analytics utm_* parameters.", description: "Gratuito - UTM URL builder. Fill em source, medium, campaign e optional term/content/id para tag a URL para Google Analytics ou other analytics tools â runs entirely no seu navegador.", keywords: ["utm builder", "utm parameter generator", "campaign url builder", "google analytics utm", "utm tag generator"], url: "URL", source: "Source", medium: "Medium", campaign: "Campaign", term: "Term", content: "Content", id: "ID", result: "Tagged URL" },
  id: { title: "Pembuat UTM Campaign URL", short: "Tag a URL with Google Analytics utm_* parameters.", description: "Gratis - UTM URL builder. Fill in source, medium, campaign dan optional term/content/id to tag a URL for Google Analytics atau other analytics tools â runs entirely di browser Anda.", keywords: ["utm builder", "utm parameter generator", "campaign url builder", "google analytics utm", "utm tag generator"], url: "URL", source: "Source", medium: "Medium", campaign: "Campaign", term: "Term", content: "Content", id: "ID", result: "Tagged URL" },

  tr: { title: "UTM Kampanya URL Oluşturucu", short: "Bir URL'yi Google Analytics utm_* parametreleriyle etiketleyin.", description: "Ücretsiz UTM URL oluşturucu. Kaynak, ortam, kampanya ve isteğe bağlı terim/içerik/ID alanlarını doldurarak Google Analytics veya diğer analiz araçları için bir URL etiketleyin — tamamen tarayıcınızda çalışır.", keywords: ["utm oluşturucu", "utm parametre oluşturucu", "kampanya url oluşturucu", "google analytics utm", "utm etiket oluşturucu"], url: "URL", source: "Kaynak", medium: "Ortam", campaign: "Kampanya", term: "Terim", content: "İçerik", id: "ID", result: "Etiketli URL" },
  de: { title: "UTM-Kampagnen-URL-Builder", short: "Markieren Sie eine URL mit Google-Analytics-utm_*-Parametern.", description: "Kostenloser UTM-URL-Builder. Füllen Sie Quelle, Medium, Kampagne und optional Begriff/Inhalt/ID aus, um eine URL für Google Analytics oder andere Analyse-Tools zu taggen — läuft vollständig im Browser.", keywords: ["utm builder", "utm parameter generator", "kampagnen url builder", "google analytics utm", "utm tag generator"], url: "URL", source: "Quelle", medium: "Medium", campaign: "Kampagne", term: "Begriff", content: "Inhalt", id: "ID", result: "Getaggte URL" },
  fr: { title: "Constructeur d'URL UTM", short: "Taguez une URL avec les paramètres utm_* de Google Analytics.", description: "Constructeur d'URL UTM gratuit. Remplissez source, médium, campagne et optionnellement terme/contenu/ID pour taguer une URL pour Google Analytics ou d'autres outils d'analyse — fonctionne entièrement dans votre navigateur.", keywords: ["constructeur utm", "générateur paramètres utm", "constructeur url campagne", "google analytics utm", "générateur tag utm"], url: "URL", source: "Source", medium: "Médium", campaign: "Campagne", term: "Terme", content: "Contenu", id: "ID", result: "URL taguée" },
  es: { title: "Constructor de URL UTM", short: "Etiqueta una URL con parámetros utm_* de Google Analytics.", description: "Constructor de URL UTM gratuito. Rellena fuente, medio, campaña y opcionalmente término/contenido/ID para etiquetar una URL para Google Analytics u otras herramientas de análisis — funciona completamente en tu navegador.", keywords: ["constructor utm", "generador parámetros utm", "constructor url campaña", "google analytics utm", "generador etiqueta utm"], url: "URL", source: "Fuente", medium: "Medio", campaign: "Campaña", term: "Término", content: "Contenido", id: "ID", result: "URL etiquetada" },
  it: { title: "Costruttore di URL UTM", short: "Tagga un URL con parametri utm_* di Google Analytics.", description: "Costruttore di URL UTM gratuito. Compila sorgente, mezzo, campagna e opzionalmente termine/contenuto/ID per taggare un URL per Google Analytics o altri strumenti di analisi — funziona interamente nel browser.", keywords: ["costruttore utm", "generatore parametri utm", "costruttore url campagna", "google analytics utm", "generatore tag utm"], url: "URL", source: "Sorgente", medium: "Mezzo", campaign: "Campagna", term: "Termine", content: "Contenuto", id: "ID", result: "URL taggato" },
  ar: { title: "منشئ URL لحملة UTM", short: "ضع علامة على URL باستخدام معلمات utm_* الخاصة بـ Google Analytics.", description: "منشئ URL لـ UTM مجاني. املأ المصدر والوسيط والحملة واختياريًا المصطلح/المحتوى/المعرّف لوضع علامة على URL لـ Google Analytics أو أدوات تحليل أخرى — يعمل بالكامل في متصفحك.", keywords: ["منشئ utm", "مولد معلمات utm", "منشئ url للحملة", "google analytics utm", "مولد علامة utm"], url: "URL", source: "المصدر", medium: "الوسيط", campaign: "الحملة", term: "المصطلح", content: "المحتوى", id: "المعرّف", result: "URL الموسوم" },
  ru: { title: "Конструктор UTM-URL", short: "Помечайте URL параметрами utm_* для Google Analytics.", description: "Бесплатный конструктор UTM-URL. Заполните source, medium, campaign и опционально term/content/id, чтобы пометить URL для Google Analytics или других аналитических инструментов — работает полностью в браузере.", keywords: ["конструктор utm", "генератор utm параметров", "конструктор url кампании", "google analytics utm", "генератор utm тегов"], url: "URL", source: "Источник", medium: "Канал", campaign: "Кампания", term: "Термин", content: "Контент", id: "ID", result: "URL с метками" },
  zh: { title: "UTM 营销活动 URL 构建器", short: "用 Google Analytics 的 utm_* 参数标记 URL。", description: "免费的 UTM URL 构建器。填写来源、媒介、活动以及可选的关键词/内容/ID，为 Google Analytics 或其他分析工具标记 URL——完全在浏览器中运行。", keywords: ["utm 构建器", "utm 参数生成器", "营销活动 url 构建器", "google analytics utm", "utm 标签生成器"], url: "URL", source: "来源", medium: "媒介", campaign: "活动", term: "关键词", content: "内容", id: "ID", result: "已标记 URL" },
  ja: { title: "UTM キャンペーン URL ビルダー", short: "Google Analytics の utm_* パラメータで URL にタグを付ける。", description: "無料の UTM URL ビルダー。ソース、メディア、キャンペーンとオプションのターム/コンテンツ/ID を入力して、Google Analytics や他の分析ツール用に URL をタグ付け——すべてブラウザ内で動作します。", keywords: ["utm ビルダー", "utm パラメータ ジェネレーター", "キャンペーン url ビルダー", "google analytics utm", "utm タグ ジェネレーター"], url: "URL", source: "ソース", medium: "メディア", campaign: "キャンペーン", term: "ターム", content: "コンテンツ", id: "ID", result: "タグ付き URL" },
  ko: { title: "UTM 캠페인 URL 빌더", short: "Google Analytics utm_* 매개변수로 URL에 태그를 추가합니다.", description: "무료 UTM URL 빌더. 소스, 매체, 캠페인 및 선택적 용어/콘텐츠/ID를 입력해 Google Analytics 또는 기타 분석 도구용으로 URL에 태그를 지정하세요 — 모두 브라우저에서 실행됩니다.", keywords: ["utm 빌더", "utm 매개변수 생성기", "캠페인 url 빌더", "google analytics utm", "utm 태그 생성기"], url: "URL", source: "소스", medium: "매체", campaign: "캠페인", term: "용어", content: "콘텐츠", id: "ID", result: "태그된 URL" },
  hi: { title: "UTM कैम्पेन URL बिल्डर", short: "Google Analytics utm_* पैरामीटर के साथ एक URL को टैग करें।", description: "मुफ्त UTM URL बिल्डर। स्रोत, माध्यम, अभियान और वैकल्पिक रूप से शब्द/सामग्री/ID भरें ताकि Google Analytics या अन्य विश्लेषण उपकरणों के लिए URL को टैग किया जा सके — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["utm बिल्डर", "utm पैरामीटर जनरेटर", "कैम्पेन url बिल्डर", "google analytics utm", "utm टैग जनरेटर"], url: "URL", source: "स्रोत", medium: "माध्यम", campaign: "अभियान", term: "शब्द", content: "सामग्री", id: "ID", result: "टैग किया गया URL" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
