import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "EXIF / Metadata Stripper", short: "Remove EXIF, GPS and other metadata from JPEG and PNG.", description: "Free EXIF metadata stripper. Drop a JPEG to remove EXIF, IPTC, XMP, ICC and comments — or drop a PNG/WebP to re-encode it without metadata. Useful for privacy before sharing photos. Runs in your browser.", keywords: ["exif remover", "strip exif", "remove image metadata", "photo privacy", "gps remover photo"], drop: "Drop a photo here or click to choose", originalSize: "Original", strippedSize: "Stripped", reduction: "Reduction", download: "Download" },
  pt: { title: "Removedor de EXIF / Metadata", short: "Remove EXIF, GPS e other metadata a partir de JPEG e PNG.", description: "Gratuito - EXIF metadata stripper. Drop a JPEG para remove EXIF, IPTC, XMP, ICC e comments â ou drop a PNG/WebP para re-codificar it without metadata. Useful para privacy before sharing photos. Runs no seu navegador.", keywords: ["exif remover", "strip exif", "remove image metadata", "photo privacy", "gps remover photo"], drop: "Drop a photo here or click to choose", originalSize: "Original", strippedSize: "Stripped", reduction: "Reduction", download: "Download" },
  id: { title: "Penghapus EXIF / Metadata", short: "Remove EXIF, GPS dan other metadata from JPEG dan PNG.", description: "Gratis - EXIF metadata stripper. Drop a JPEG to remove EXIF, IPTC, XMP, ICC dan comments â atau drop a PNG/WebP to re-enkode it without metadata. Useful for privacy before sharing photos. Runs di browser Anda.", keywords: ["exif remover", "strip exif", "remove image metadata", "photo privacy", "gps remover photo"], drop: "Drop a photo here or click to choose", originalSize: "Original", strippedSize: "Stripped", reduction: "Reduction", download: "Download" },

  tr: { title: "EXIF / Meta Veri Temizleyici", short: "JPEG ve PNG'den EXIF, GPS ve diğer meta verileri kaldırın.", description: "Ücretsiz EXIF meta veri temizleyici. EXIF, IPTC, XMP, ICC ve yorumları kaldırmak için bir JPEG bırakın — veya bir PNG/WebP'yi meta veri olmadan yeniden kodlamak için bırakın. Fotoğrafları paylaşmadan önce gizlilik için yararlıdır. Tarayıcınızda çalışır.", keywords: ["exif kaldırıcı", "exif sil", "görsel meta veri kaldır", "fotoğraf gizliliği", "fotoğraf gps kaldır"], drop: "Bir fotoğraf bırakın veya seçmek için tıklayın", originalSize: "Orijinal", strippedSize: "Temizlenmiş", reduction: "Azalma", download: "İndir" },
  de: { title: "EXIF-/Metadaten-Entferner", short: "Entfernen Sie EXIF, GPS und andere Metadaten aus JPEG und PNG.", description: "Kostenloser EXIF-Metadaten-Entferner. Legen Sie ein JPEG ab, um EXIF, IPTC, XMP, ICC und Kommentare zu entfernen — oder ein PNG/WebP, um es ohne Metadaten neu zu codieren. Nützlich für die Privatsphäre vor dem Teilen von Fotos. Läuft im Browser.", keywords: ["exif entferner", "exif entfernen", "bild metadaten entfernen", "foto privatsphäre", "gps aus foto entfernen"], drop: "Foto hier ablegen oder klicken zum Auswählen", originalSize: "Original", strippedSize: "Bereinigt", reduction: "Reduktion", download: "Herunterladen" },
  fr: { title: "Suppresseur EXIF / Métadonnées", short: "Supprimez EXIF, GPS et autres métadonnées des JPEG et PNG.", description: "Suppresseur de métadonnées EXIF gratuit. Déposez un JPEG pour supprimer EXIF, IPTC, XMP, ICC et commentaires — ou déposez un PNG/WebP pour le ré-encoder sans métadonnées. Utile pour la confidentialité avant de partager des photos. Fonctionne dans votre navigateur.", keywords: ["suppresseur exif", "supprimer exif", "supprimer métadonnées image", "confidentialité photo", "supprimer gps photo"], drop: "Déposez une photo ici ou cliquez pour choisir", originalSize: "Original", strippedSize: "Nettoyé", reduction: "Réduction", download: "Télécharger" },
  es: { title: "Eliminador de EXIF / Metadatos", short: "Elimina EXIF, GPS y otros metadatos de JPEG y PNG.", description: "Eliminador de metadatos EXIF gratuito. Arrastra un JPEG para eliminar EXIF, IPTC, XMP, ICC y comentarios — o arrastra un PNG/WebP para re-codificarlo sin metadatos. Útil para la privacidad antes de compartir fotos. Funciona en tu navegador.", keywords: ["eliminador exif", "eliminar exif", "eliminar metadatos imagen", "privacidad foto", "eliminar gps foto"], drop: "Arrastra una foto aquí o haz clic para elegir", originalSize: "Original", strippedSize: "Limpio", reduction: "Reducción", download: "Descargar" },
  it: { title: "Rimozione EXIF / Metadati", short: "Rimuovi EXIF, GPS e altri metadati da JPEG e PNG.", description: "Rimuovi metadati EXIF gratuito. Trascina un JPEG per rimuovere EXIF, IPTC, XMP, ICC e commenti — oppure un PNG/WebP per ricodificarlo senza metadati. Utile per la privacy prima di condividere foto. Funziona nel browser.", keywords: ["rimuovi exif", "elimina exif", "rimuovi metadati immagine", "privacy foto", "rimuovi gps foto"], drop: "Trascina una foto qui o clicca per scegliere", originalSize: "Originale", strippedSize: "Pulito", reduction: "Riduzione", download: "Scarica" },
  ar: { title: "مزيل EXIF / البيانات الوصفية", short: "أزِل EXIF و GPS والبيانات الوصفية الأخرى من JPEG و PNG.", description: "مزيل بيانات EXIF الوصفية مجاني. أفلِت ملف JPEG لإزالة EXIF و IPTC و XMP و ICC والتعليقات — أو أفلِت PNG/WebP لإعادة ترميزه بدون بيانات وصفية. مفيد للخصوصية قبل مشاركة الصور. يعمل في متصفحك.", keywords: ["مزيل exif", "إزالة exif", "إزالة البيانات الوصفية للصورة", "خصوصية الصورة", "إزالة gps من الصورة"], drop: "أفلِت صورة هنا أو انقر للاختيار", originalSize: "الأصلي", strippedSize: "المنظف", reduction: "التقليل", download: "تنزيل" },
  ru: { title: "Удаление EXIF / метаданных", short: "Удаляйте EXIF, GPS и другие метаданные из JPEG и PNG.", description: "Бесплатное удаление метаданных EXIF. Перетащите JPEG для удаления EXIF, IPTC, XMP, ICC и комментариев — или перетащите PNG/WebP для повторного кодирования без метаданных. Полезно для приватности перед публикацией фото. Работает в браузере.", keywords: ["удалить exif", "очистка exif", "удалить метаданные изображения", "приватность фото", "удалить gps из фото"], drop: "Перетащите фото сюда или нажмите для выбора", originalSize: "Оригинал", strippedSize: "Очищенный", reduction: "Сокращение", download: "Скачать" },
  zh: { title: "EXIF / 元数据清除器", short: "从 JPEG 和 PNG 中删除 EXIF、GPS 等元数据。", description: "免费的 EXIF 元数据清除器。拖入 JPEG 以删除 EXIF、IPTC、XMP、ICC 和注释——或拖入 PNG/WebP 以重新编码并去除元数据。在分享照片前用于隐私保护。在浏览器中运行。", keywords: ["exif 清除", "删除 exif", "删除图片元数据", "照片隐私", "照片 gps 删除"], drop: "将照片拖到此处或点击选择", originalSize: "原始", strippedSize: "清除后", reduction: "缩减", download: "下载" },
  ja: { title: "EXIF / メタデータ削除", short: "JPEG と PNG から EXIF、GPS、その他のメタデータを削除。", description: "無料の EXIF メタデータ削除ツール。JPEG をドロップして EXIF、IPTC、XMP、ICC、コメントを削除——または PNG/WebP をドロップしてメタデータなしで再エンコード。写真共有前のプライバシーに役立ちます。ブラウザ内で動作します。", keywords: ["exif 削除", "exif 除去", "画像メタデータ削除", "写真 プライバシー", "写真 gps 削除"], drop: "写真をここにドロップまたはクリックして選択", originalSize: "オリジナル", strippedSize: "クリア", reduction: "削減", download: "ダウンロード" },
  ko: { title: "EXIF / 메타데이터 제거", short: "JPEG와 PNG에서 EXIF, GPS 및 기타 메타데이터를 제거합니다.", description: "무료 EXIF 메타데이터 제거기. JPEG를 드롭하여 EXIF, IPTC, XMP, ICC, 코멘트를 제거하거나 PNG/WebP를 드롭하여 메타데이터 없이 재인코딩합니다. 사진 공유 전 개인정보 보호에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["exif 제거", "exif 삭제", "이미지 메타데이터 제거", "사진 개인정보", "사진 gps 제거"], drop: "여기에 사진을 드롭하거나 클릭하여 선택", originalSize: "원본", strippedSize: "정리됨", reduction: "감소", download: "다운로드" },
  hi: { title: "EXIF / मेटाडेटा रिमूवर", short: "JPEG और PNG से EXIF, GPS और अन्य मेटाडेटा हटाएं।", description: "मुफ्त EXIF मेटाडेटा रिमूवर। एक JPEG छोड़ें ताकि EXIF, IPTC, XMP, ICC और टिप्पणियाँ हटें — या PNG/WebP छोड़ें ताकि मेटाडेटा के बिना फिर से एन्कोड हो। फ़ोटो साझा करने से पहले गोपनीयता के लिए उपयोगी। आपके ब्राउज़र में चलता है।", keywords: ["exif रिमूवर", "exif हटाएं", "इमेज मेटाडेटा हटाएं", "फ़ोटो गोपनीयता", "फ़ोटो gps हटाएं"], drop: "यहाँ एक फ़ोटो छोड़ें या चुनने के लिए क्लिक करें", originalSize: "मूल", strippedSize: "साफ़", reduction: "कमी", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
