import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Word Frequency Counter", short: "Count how often each word appears in your text, ranked by frequency.", description: "Free word frequency counter. Paste text to see how many times each word appears, ranked from most to least frequent, with totals for word count and unique words. Useful for keyword density and writing analysis.", keywords: ["word frequency counter", "keyword density", "word count list", "frequency analysis", "most common words"], placeholder: "Paste your text here…", caseInsensitive: "Ignore case", word: "Word", count: "Count", totalWords: "Total words", uniqueWords: "Unique words" },
  pt: { title: "Word Frequency Counter", short: "Count how often each word appears in your text, ranked by frequency.", description: "Free word frequency counter. Paste text to see how many times each word appears, ranked from most to least frequent, with totals for word count and unique words. Useful for keyword density and writing analysis.", keywords: ["word frequency counter", "keyword density", "word count list", "frequency analysis", "most common words"], placeholder: "Paste your text here…", caseInsensitive: "Ignore case", word: "Word", count: "Count", totalWords: "Total words", uniqueWords: "Unique words" },
  id: { title: "Word Frequency Counter", short: "Count how often each word appears in your text, ranked by frequency.", description: "Free word frequency counter. Paste text to see how many times each word appears, ranked from most to least frequent, with totals for word count and unique words. Useful for keyword density and writing analysis.", keywords: ["word frequency counter", "keyword density", "word count list", "frequency analysis", "most common words"], placeholder: "Paste your text here…", caseInsensitive: "Ignore case", word: "Word", count: "Count", totalWords: "Total words", uniqueWords: "Unique words" },

  tr: { title: "Kelime Frekansı Sayacı", short: "Metninizde her kelimenin kaç kez geçtiğini frekansa göre sıralı görün.", description: "Ücretsiz kelime frekansı sayacı. Metni yapıştırın; her kelimenin kaç kez geçtiğini en sıktan en seyreğe sıralı, toplam kelime ve benzersiz kelime sayılarıyla görün. Anahtar kelime yoğunluğu ve yazı analizi için kullanışlı.", keywords: ["kelime frekansı sayacı", "anahtar kelime yoğunluğu", "kelime sayısı listesi", "frekans analizi", "en sık kelimeler"], placeholder: "Metninizi buraya yapıştırın…", caseInsensitive: "Harf duyarsız", word: "Kelime", count: "Sayı", totalWords: "Toplam kelime", uniqueWords: "Benzersiz kelime" },
  de: { title: "Worthäufigkeits-Zähler", short: "Zählen Sie, wie oft jedes Wort in Ihrem Text vorkommt, nach Häufigkeit sortiert.", description: "Kostenloser Worthäufigkeits-Zähler. Fügen Sie Text ein, um zu sehen, wie oft jedes Wort vorkommt, von häufig zu selten sortiert, mit Gesamt- und Unique-Wortzahl. Nützlich für Keyword-Dichte und Textanalyse.", keywords: ["worthäufigkeit zähler", "keyword-dichte", "wortzählung liste", "häufigkeitsanalyse", "häufigste wörter"], placeholder: "Text hier einfügen…", caseInsensitive: "Groß/klein ignorieren", word: "Wort", count: "Anzahl", totalWords: "Wörter gesamt", uniqueWords: "Eindeutige Wörter" },
  fr: { title: "Compteur de Fréquence des Mots", short: "Comptez combien de fois chaque mot apparaît, classé par fréquence.", description: "Compteur de fréquence des mots gratuit. Collez du texte pour voir combien de fois chaque mot apparaît, du plus au moins fréquent, avec le total et le nombre de mots uniques. Utile pour la densité de mots-clés.", keywords: ["compteur de fréquence des mots", "densité de mots-clés", "liste de fréquence", "analyse de fréquence", "mots les plus courants"], placeholder: "Collez votre texte ici…", caseInsensitive: "Ignorer la casse", word: "Mot", count: "Nombre", totalWords: "Total de mots", uniqueWords: "Mots uniques" },
  es: { title: "Contador de Frecuencia de Palabras", short: "Cuenta cuántas veces aparece cada palabra, ordenado por frecuencia.", description: "Contador de frecuencia de palabras gratuito. Pega texto para ver cuántas veces aparece cada palabra, de mayor a menor frecuencia, con totales de palabras y palabras únicas. Útil para densidad de palabras clave.", keywords: ["contador de frecuencia de palabras", "densidad de palabras clave", "lista de frecuencia", "análisis de frecuencia", "palabras más comunes"], placeholder: "Pega tu texto aquí…", caseInsensitive: "Ignorar mayúsculas", word: "Palabra", count: "Conteo", totalWords: "Palabras totales", uniqueWords: "Palabras únicas" },
  it: { title: "Contatore Frequenza Parole", short: "Conta quante volte appare ogni parola, ordinato per frequenza.", description: "Contatore di frequenza delle parole gratuito. Incolla il testo per vedere quante volte appare ogni parola, dalla più alla meno frequente, con totali di parole e parole uniche. Utile per la densità di parole chiave.", keywords: ["contatore frequenza parole", "densità parole chiave", "lista di frequenza", "analisi di frequenza", "parole più comuni"], placeholder: "Incolla il tuo testo qui…", caseInsensitive: "Ignora maiuscole", word: "Parola", count: "Conteggio", totalWords: "Parole totali", uniqueWords: "Parole uniche" },
  ar: { title: "عدّاد تكرار الكلمات", short: "احسب كم مرة تظهر كل كلمة في نصك، مرتبة حسب التكرار.", description: "عدّاد تكرار كلمات مجاني. الصق النص لترى كم مرة تظهر كل كلمة، من الأكثر إلى الأقل تكرارًا، مع إجمالي الكلمات والكلمات الفريدة. مفيد لكثافة الكلمات المفتاحية وتحليل الكتابة.", keywords: ["عداد تكرار الكلمات", "كثافة الكلمات المفتاحية", "قائمة التكرار", "تحليل التكرار", "الكلمات الأكثر شيوعًا"], placeholder: "الصق نصك هنا…", caseInsensitive: "تجاهل حالة الأحرف", word: "الكلمة", count: "العدد", totalWords: "إجمالي الكلمات", uniqueWords: "كلمات فريدة" },
  ru: { title: "Счётчик Частоты Слов", short: "Подсчитайте, сколько раз каждое слово встречается в тексте, по частоте.", description: "Бесплатный счётчик частоты слов. Вставьте текст, чтобы увидеть, сколько раз встречается каждое слово, от частых к редким, с итогами по словам и уникальным словам. Полезно для плотности ключевых слов.", keywords: ["счётчик частоты слов", "плотность ключевых слов", "список частот", "частотный анализ", "самые частые слова"], placeholder: "Вставьте текст сюда…", caseInsensitive: "Игнорировать регистр", word: "Слово", count: "Счёт", totalWords: "Всего слов", uniqueWords: "Уникальных слов" },
  zh: { title: "词频统计器", short: "统计每个词在文本中出现的次数，按频率排序。", description: "免费的词频统计器。粘贴文本即可查看每个词出现的次数，从高频到低频排序，并显示总词数和唯一词数。适合关键词密度和写作分析。", keywords: ["词频统计", "关键词密度", "词频列表", "频率分析", "最常见词"], placeholder: "在此粘贴你的文本…", caseInsensitive: "忽略大小写", word: "词", count: "次数", totalWords: "总词数", uniqueWords: "唯一词数" },
  ja: { title: "単語頻度カウンター", short: "テキスト内で各単語が出現する回数を頻度順に集計します。", description: "無料の単語頻度カウンター。テキストを貼り付けると、各単語の出現回数を多い順に表示し、総単語数とユニーク単語数も示します。キーワード密度や文章分析に便利。", keywords: ["単語頻度カウンター", "キーワード密度", "単語頻度リスト", "頻度分析", "最頻出単語"], placeholder: "ここにテキストを貼り付け…", caseInsensitive: "大文字小文字を無視", word: "単語", count: "回数", totalWords: "総単語数", uniqueWords: "ユニーク単語数" },
  ko: { title: "단어 빈도 계산기", short: "텍스트에서 각 단어가 나타나는 횟수를 빈도순으로 셉니다.", description: "무료 단어 빈도 계산기. 텍스트를 붙여넣으면 각 단어의 출현 횟수를 많은 순으로 표시하고 총 단어 수와 고유 단어 수를 보여줍니다. 키워드 밀도와 글 분석에 유용합니다.", keywords: ["단어 빈도 계산기", "키워드 밀도", "단어 빈도 목록", "빈도 분석", "가장 흔한 단어"], placeholder: "여기에 텍스트를 붙여넣으세요…", caseInsensitive: "대소문자 무시", word: "단어", count: "횟수", totalWords: "총 단어", uniqueWords: "고유 단어" },
  hi: { title: "शब्द आवृत्ति गणक", short: "अपने टेक्स्ट में हर शब्द कितनी बार आता है, आवृत्ति के अनुसार गिनें।", description: "मुफ्त शब्द आवृत्ति गणक। टेक्स्ट पेस्ट करें और देखें कि हर शब्द कितनी बार आता है, सबसे अधिक से कम आवृत्ति क्रम में, कुल शब्द और अद्वितीय शब्द संख्या सहित। कीवर्ड घनत्व और लेखन विश्लेषण के लिए उपयोगी।", keywords: ["शब्द आवृत्ति गणक", "कीवर्ड घनत्व", "शब्द आवृत्ति सूची", "आवृत्ति विश्लेषण", "सबसे आम शब्द"], placeholder: "अपना टेक्स्ट यहाँ पेस्ट करें…", caseInsensitive: "केस अनदेखा करें", word: "शब्द", count: "गिनती", totalWords: "कुल शब्द", uniqueWords: "अद्वितीय शब्द" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
