import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "ASCII Table", short: "Full ASCII table with decimal, hex, octal and binary.", description: "Free ASCII table reference. Look up all 128 ASCII characters with their decimal, hexadecimal, octal and binary codes, and search by value or character.", keywords: ["ascii table", "ascii chart", "ascii codes", "character codes", "ascii to hex"], search: "Search", dec: "Dec", hex: "Hex", oct: "Oct", bin: "Binary", char: "Char" },
  tr: { title: "ASCII Tablosu", short: "Ondalık, hex, sekizlik ve ikili ile tam ASCII tablosu.", description: "Ücretsiz ASCII tablosu referansı. Tüm 128 ASCII karakterini ondalık, onaltılık, sekizlik ve ikili kodlarıyla görün, değere veya karaktere göre arayın.", keywords: ["ascii tablosu", "ascii çizelgesi", "ascii kodları", "karakter kodları", "ascii hex"], search: "Ara", dec: "Ondalık", hex: "Hex", oct: "Sekizlik", bin: "İkili", char: "Karakter" },
  de: { title: "ASCII-Tabelle", short: "Vollständige ASCII-Tabelle mit Dezimal, Hex, Oktal und Binär.", description: "Kostenlose ASCII-Tabellen-Referenz. Schlagen Sie alle 128 ASCII-Zeichen mit ihren Dezimal-, Hexadezimal-, Oktal- und Binärcodes nach und suchen Sie nach Wert oder Zeichen.", keywords: ["ascii tabelle", "ascii diagramm", "ascii codes", "zeichencodes", "ascii zu hex"], search: "Suchen", dec: "Dez", hex: "Hex", oct: "Okt", bin: "Binär", char: "Zeichen" },
  fr: { title: "Table ASCII", short: "Table ASCII complète avec décimal, hex, octal et binaire.", description: "Référence de table ASCII gratuite. Consultez les 128 caractères ASCII avec leurs codes décimaux, hexadécimaux, octaux et binaires, et recherchez par valeur ou caractère.", keywords: ["table ascii", "tableau ascii", "codes ascii", "codes caractères", "ascii vers hex"], search: "Rechercher", dec: "Déc", hex: "Hex", oct: "Oct", bin: "Binaire", char: "Caractère" },
  es: { title: "Tabla ASCII", short: "Tabla ASCII completa con decimal, hex, octal y binario.", description: "Referencia de tabla ASCII gratuita. Consulta los 128 caracteres ASCII con sus códigos decimal, hexadecimal, octal y binario, y busca por valor o carácter.", keywords: ["tabla ascii", "carta ascii", "códigos ascii", "códigos de caracteres", "ascii a hex"], search: "Buscar", dec: "Dec", hex: "Hex", oct: "Oct", bin: "Binario", char: "Carácter" },
  it: { title: "Tabella ASCII", short: "Tabella ASCII completa con decimale, hex, ottale e binario.", description: "Riferimento gratuito tabella ASCII. Consulta tutti i 128 caratteri ASCII con i loro codici decimale, esadecimale, ottale e binario, e cerca per valore o carattere.", keywords: ["tabella ascii", "carta ascii", "codici ascii", "codici caratteri", "ascii in hex"], search: "Cerca", dec: "Dec", hex: "Hex", oct: "Ott", bin: "Binario", char: "Carattere" },
  ar: { title: "جدول ASCII", short: "جدول ASCII كامل بالعشري والست عشري والثماني والثنائي.", description: "مرجع مجاني لجدول ASCII. ابحث عن جميع أحرف ASCII الـ128 مع أكوادها العشرية والست عشرية والثمانية والثنائية، وابحث بالقيمة أو الحرف.", keywords: ["جدول ascii", "مخطط ascii", "أكواد ascii", "أكواد الأحرف", "ascii إلى hex"], search: "بحث", dec: "عشري", hex: "ست عشري", oct: "ثماني", bin: "ثنائي", char: "حرف" },
  ru: { title: "Таблица ASCII", short: "Полная таблица ASCII: десятичный, hex, восьмеричный, двоичный.", description: "Бесплатный справочник таблицы ASCII. Просматривайте все 128 символов ASCII с их десятичными, шестнадцатеричными, восьмеричными и двоичными кодами, ищите по значению или символу.", keywords: ["таблица ascii", "карта ascii", "коды ascii", "коды символов", "ascii в hex"], search: "Поиск", dec: "Дес", hex: "Hex", oct: "Вос", bin: "Двоичный", char: "Символ" },
  zh: { title: "ASCII 表", short: "完整 ASCII 表，含十进制、十六进制、八进制和二进制。", description: "免费的 ASCII 表参考。查询全部 128 个 ASCII 字符的十进制、十六进制、八进制和二进制代码，并按值或字符搜索。", keywords: ["ascii 表", "ascii 图表", "ascii 代码", "字符代码", "ascii 转 hex"], search: "搜索", dec: "十进制", hex: "十六进制", oct: "八进制", bin: "二进制", char: "字符" },
  ja: { title: "ASCII 表", short: "10進・16進・8進・2進を含む完全な ASCII 表。", description: "無料の ASCII 表リファレンス。128 すべての ASCII 文字を10進・16進・8進・2進コードで調べ、値や文字で検索できます。", keywords: ["ascii 表", "ascii チャート", "ascii コード", "文字コード", "ascii から hex"], search: "検索", dec: "10進", hex: "16進", oct: "8進", bin: "2進", char: "文字" },
  ko: { title: "ASCII 표", short: "10진수, 16진수, 8진수, 2진수를 포함한 전체 ASCII 표.", description: "무료 ASCII 표 참조. 128개의 모든 ASCII 문자를 10진수, 16진수, 8진수, 2진수 코드로 조회하고 값 또는 문자로 검색하세요.", keywords: ["ascii 표", "ascii 차트", "ascii 코드", "문자 코드", "ascii를 hex로"], search: "검색", dec: "10진수", hex: "16진수", oct: "8진수", bin: "2진수", char: "문자" },
  hi: { title: "ASCII तालिका", short: "दशमलव, हेक्स, अष्टक और बाइनरी के साथ पूर्ण ASCII तालिका।", description: "मुफ्त ASCII तालिका संदर्भ। सभी 128 ASCII वर्णों को उनके दशमलव, हेक्साडेसिमल, अष्टक और बाइनरी कोड के साथ देखें, और मान या वर्ण से खोजें।", keywords: ["ascii तालिका", "ascii चार्ट", "ascii कोड", "वर्ण कोड", "ascii से hex"], search: "खोजें", dec: "दशमलव", hex: "हेक्स", oct: "अष्टक", bin: "बाइनरी", char: "वर्ण" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
