import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Browser Ping / Latency Test", short: "Approximate latency to common hosts from your browser.", description: "Free in-browser latency test. Sends repeated fetch requests to popular endpoints (Cloudflare, Google, GitHub …) and reports min/avg/max plus jitter — useful for spot-checking connectivity from a tab.", keywords: ["ping latency test", "browser ping", "latency check", "rtt test", "network latency"], samples: "Samples per host", run: "Run", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  nl: { title: "Browser Ping / Latency Test", short: "Approximate latency to common hosts from uw browser.", description: "Gratis in-browser latency test. Sends repeated fetch requests to popular endpoints (Cloudflare, Google, GitHub …) and reports min/avg/max plus jitter — useful for spot-controleering connectivity from a tab.", keywords: ["ping latency test", "browser ping", "latency controleer", "rtt test", "network latency"], samples: "Samples per host", run: "Run", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },

  pl: { title: "Browser Ping / Latency Test", short: "Approximate latency to common hosts from Twoja przeglądarka.", description: "Darmowy in-browser latency test. Sends repeated fetch requests to popular endpoints (Cloudflare, Google, GitHub …) and reports min/avg/max plus jitter — useful for spot-sprawdźing connectivity from a tab.", keywords: ["ping latency test", "browser ping", "latency sprawdź", "rtt test", "network latency"], samples: "Samples per host", run: "Run", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  pt: { title: "Teste de Browser Ping / Latency", short: "Approximate latency para common hosts a partir de seu browser.", description: "Gratuito - em-browser latency test. Sends repeated fetch requests para popular endpoints (Cloudflare, Google, GitHub â¦) e reports min/avg/max plus jitter â useful para spot-checking connectivity a partir de a tab.", keywords: ["ping latency test", "browser ping", "latency check", "rtt test", "network latency"], samples: "Samples per host", run: "Run", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  id: { title: "Tes Browser Ping / Latency", short: "Approximate latency to common hosts from Anda browser.", description: "Gratis - in-browser latency test. Sends repeated fetch requests to popular endpoints (Cloudflare, Google, GitHub â¦) dan reports min/avg/max plus jitter â useful for spot-checking connectivity from a tab.", keywords: ["ping latency test", "browser ping", "latency check", "rtt test", "network latency"], samples: "Samples per host", run: "Run", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },

  tr: { title: "Tarayıcı Ping / Gecikme Testi", short: "Tarayıcınızdan yaygın sunuculara yaklaşık gecikme.", description: "Ücretsiz tarayıcı içi gecikme testi. Popüler uç noktalara (Cloudflare, Google, GitHub …) tekrarlı fetch istekleri gönderir ve min/ort/maks ile jitter raporlar — bir sekmeden bağlantıyı hızlıca kontrol etmek için kullanışlı.", keywords: ["ping gecikme testi", "tarayıcı ping", "gecikme kontrolü", "rtt testi", "ağ gecikmesi"], samples: "Sunucu başına örnek", run: "Çalıştır", target: "Hedef", avg: "Ort", min: "Min", max: "Maks", jitter: "Jitter" },
  de: { title: "Browser-Ping- / Latenz-Test", short: "Annähernde Latenz zu gängigen Hosts aus Ihrem Browser.", description: "Kostenloser Latenz-Test im Browser. Sendet wiederholte Fetch-Anfragen an beliebte Endpunkte (Cloudflare, Google, GitHub …) und meldet Min/Avg/Max plus Jitter — nützlich für schnelle Konnektivitätschecks aus einem Tab.", keywords: ["ping latenz test", "browser ping", "latenz check", "rtt test", "netzwerk latenz"], samples: "Samples pro Host", run: "Ausführen", target: "Ziel", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  fr: { title: "Test Ping / Latence Navigateur", short: "Latence approximative vers des hôtes courants depuis votre navigateur.", description: "Test de latence dans le navigateur gratuit. Envoie des requêtes fetch répétées à des endpoints populaires (Cloudflare, Google, GitHub …) et rapporte min/moy/max plus jitter — utile pour des contrôles de connectivité depuis un onglet.", keywords: ["test ping latence", "ping navigateur", "vérification latence", "test rtt", "latence réseau"], samples: "Échantillons par hôte", run: "Exécuter", target: "Cible", avg: "Moy", min: "Min", max: "Max", jitter: "Jitter" },
  es: { title: "Test de Ping / Latencia desde el Navegador", short: "Latencia aproximada a hosts comunes desde tu navegador.", description: "Test de latencia en el navegador gratuito. Envía solicitudes fetch repetidas a endpoints populares (Cloudflare, Google, GitHub …) y reporta min/avg/max más jitter — útil para revisar la conectividad desde una pestaña.", keywords: ["test ping latencia", "ping navegador", "comprobación latencia", "test rtt", "latencia red"], samples: "Muestras por host", run: "Ejecutar", target: "Destino", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  it: { title: "Test Ping / Latenza nel Browser", short: "Latenza approssimativa verso host comuni dal tuo browser.", description: "Test di latenza nel browser gratuito. Invia richieste fetch ripetute a endpoint popolari (Cloudflare, Google, GitHub …) e riporta min/avg/max più jitter — utile per controlli rapidi di connettività da una scheda.", keywords: ["test ping latenza", "ping browser", "controllo latenza", "test rtt", "latenza rete"], samples: "Campioni per host", run: "Esegui", target: "Target", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  ar: { title: "اختبار Ping / زمن الاستجابة من المتصفح", short: "زمن استجابة تقريبي إلى المضيفين الشائعين من متصفحك.", description: "اختبار زمن استجابة مجاني داخل المتصفح. يرسل طلبات fetch متكررة إلى نقاط نهاية شائعة (Cloudflare و Google و GitHub …) ويُبلغ عن الأدنى/المتوسط/الأقصى بالإضافة إلى الـ jitter — مفيد للتحقق من الاتصال من علامة تبويب.", keywords: ["اختبار ping زمن الاستجابة", "ping المتصفح", "فحص زمن الاستجابة", "اختبار rtt", "زمن الاستجابة الشبكة"], samples: "العينات لكل مضيف", run: "تشغيل", target: "الهدف", avg: "متوسط", min: "أدنى", max: "أقصى", jitter: "Jitter" },
  ru: { title: "Тест ping / задержки в браузере", short: "Приблизительная задержка до популярных хостов из браузера.", description: "Бесплатный тест задержки в браузере. Отправляет повторные fetch-запросы к популярным эндпоинтам (Cloudflare, Google, GitHub …) и сообщает min/avg/max плюс джиттер — удобно для быстрых проверок соединения из вкладки.", keywords: ["тест ping задержка", "браузер ping", "проверка задержки", "тест rtt", "сетевая задержка"], samples: "Семплов на хост", run: "Запустить", target: "Цель", avg: "Avg", min: "Min", max: "Max", jitter: "Jitter" },
  zh: { title: "浏览器 Ping / 延迟测试", short: "从浏览器对常见主机的近似延迟。", description: "免费的浏览器内延迟测试。向常见端点（Cloudflare、Google、GitHub …）发送重复的 fetch 请求，并报告最小值/平均值/最大值以及抖动——适合从标签页快速检查连接。", keywords: ["ping 延迟测试", "浏览器 ping", "延迟检查", "rtt 测试", "网络延迟"], samples: "每主机样本数", run: "运行", target: "目标", avg: "平均", min: "最小", max: "最大", jitter: "抖动" },
  ja: { title: "ブラウザ Ping / レイテンシテスト", short: "ブラウザから一般的なホストへのおおよそのレイテンシ。", description: "無料のブラウザ内レイテンシテスト。人気のエンドポイント（Cloudflare、Google、GitHub …）に繰り返し fetch リクエストを送信し、min/avg/max とジッターを報告——タブから接続性をすばやくチェックするのに便利。", keywords: ["ping レイテンシ テスト", "ブラウザ ping", "レイテンシ チェック", "rtt テスト", "ネットワーク レイテンシ"], samples: "ホストあたりのサンプル", run: "実行", target: "ターゲット", avg: "平均", min: "最小", max: "最大", jitter: "ジッター" },
  ko: { title: "브라우저 Ping / 지연 시간 테스트", short: "브라우저에서 일반 호스트까지 대략적인 지연 시간.", description: "무료 브라우저 내 지연 시간 테스트. 인기 엔드포인트(Cloudflare, Google, GitHub …)에 반복 fetch 요청을 보내고 min/avg/max와 지터를 보고합니다 — 탭에서 빠른 연결 점검에 유용합니다.", keywords: ["ping 지연 시간 테스트", "브라우저 ping", "지연 점검", "rtt 테스트", "네트워크 지연"], samples: "호스트당 샘플", run: "실행", target: "대상", avg: "평균", min: "최소", max: "최대", jitter: "지터" },
  hi: { title: "ब्राउज़र Ping / लेटेंसी टेस्ट", short: "अपने ब्राउज़र से सामान्य होस्ट तक अनुमानित लेटेंसी।", description: "मुफ्त इन-ब्राउज़र लेटेंसी टेस्ट। लोकप्रिय एंडपॉइंट (Cloudflare, Google, GitHub …) पर बार-बार fetch अनुरोध भेजता है और min/avg/max और jitter रिपोर्ट करता है — टैब से कनेक्टिविटी की त्वरित जांच के लिए उपयोगी।", keywords: ["ping लेटेंसी टेस्ट", "ब्राउज़र ping", "लेटेंसी जाँच", "rtt टेस्ट", "नेटवर्क लेटेंसी"], samples: "प्रति होस्ट सैंपल", run: "चलाएं", target: "लक्ष्य", avg: "औसत", min: "न्यूनतम", max: "अधिकतम", jitter: "जिटर" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
