import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image to Base64 Converter", short: "Convert an image to a Base64 data URL.", description: "Free image to Base64 converter. Drop a PNG, JPG, GIF, SVG or WebP to get a Base64 data URL plus ready-to-use CSS and HTML snippets — all in your browser, no upload.", keywords: ["image to base64", "base64 image encoder", "image data url", "png to base64", "convert image to base64"], drop: "Drop an image here or click to choose", dataUrl: "Data URL", css: "CSS", html: "HTML", size: "Size", preview: "Preview" },
  tr: { title: "Görselden Base64'e Dönüştürücü", short: "Bir görseli Base64 veri URL'sine dönüştürün.", description: "Ücretsiz görselden Base64'e dönüştürücü. Bir PNG, JPG, GIF, SVG veya WebP bırakın ve Base64 veri URL'si ile kullanıma hazır CSS ve HTML parçacıkları alın — hepsi tarayıcınızda, yükleme yok.", keywords: ["görsel base64", "base64 görsel kodlayıcı", "görsel veri url", "png base64", "görseli base64'e çevir"], drop: "Bir görsel bırakın veya seçmek için tıklayın", dataUrl: "Veri URL'si", css: "CSS", html: "HTML", size: "Boyut", preview: "Önizleme" },
  de: { title: "Bild-zu-Base64-Konverter", short: "Konvertieren Sie ein Bild in eine Base64-Daten-URL.", description: "Kostenloser Bild-zu-Base64-Konverter. Legen Sie ein PNG, JPG, GIF, SVG oder WebP ab, um eine Base64-Daten-URL plus einsatzbereite CSS- und HTML-Snippets zu erhalten — alles im Browser, kein Upload.", keywords: ["bild zu base64", "base64 bild encoder", "bild daten url", "png zu base64", "bild in base64 konvertieren"], drop: "Bild hier ablegen oder klicken zum Auswählen", dataUrl: "Daten-URL", css: "CSS", html: "HTML", size: "Größe", preview: "Vorschau" },
  fr: { title: "Convertisseur Image vers Base64", short: "Convertissez une image en URL de données Base64.", description: "Convertisseur image vers Base64 gratuit. Déposez un PNG, JPG, GIF, SVG ou WebP pour obtenir une URL de données Base64 plus des extraits CSS et HTML prêts à l'emploi — le tout dans votre navigateur, sans téléversement.", keywords: ["image vers base64", "encodeur image base64", "url données image", "png vers base64", "convertir image en base64"], drop: "Déposez une image ici ou cliquez pour choisir", dataUrl: "URL de données", css: "CSS", html: "HTML", size: "Taille", preview: "Aperçu" },
  es: { title: "Convertidor de Imagen a Base64", short: "Convierte una imagen a una URL de datos Base64.", description: "Convertidor de imagen a Base64 gratuito. Arrastra un PNG, JPG, GIF, SVG o WebP para obtener una URL de datos Base64 más fragmentos CSS y HTML listos para usar — todo en tu navegador, sin subida.", keywords: ["imagen a base64", "codificador imagen base64", "url datos imagen", "png a base64", "convertir imagen a base64"], drop: "Arrastra una imagen aquí o haz clic para elegir", dataUrl: "URL de datos", css: "CSS", html: "HTML", size: "Tamaño", preview: "Vista previa" },
  it: { title: "Convertitore da Immagine a Base64", short: "Converti un'immagine in un URL di dati Base64.", description: "Convertitore da immagine a Base64 gratuito. Trascina un PNG, JPG, GIF, SVG o WebP per ottenere un URL di dati Base64 più frammenti CSS e HTML pronti all'uso — tutto nel browser, nessun caricamento.", keywords: ["immagine a base64", "codificatore immagine base64", "url dati immagine", "png a base64", "convertire immagine in base64"], drop: "Trascina un'immagine qui o clicca per scegliere", dataUrl: "URL dati", css: "CSS", html: "HTML", size: "Dimensione", preview: "Anteprima" },
  ar: { title: "محوّل الصورة إلى Base64", short: "حوّل صورة إلى عنوان URL لبيانات Base64.", description: "محوّل صورة إلى Base64 مجاني. أفلِت صورة PNG أو JPG أو GIF أو SVG أو WebP للحصول على عنوان URL لبيانات Base64 بالإضافة إلى مقتطفات CSS وHTML جاهزة — كل ذلك في متصفحك، دون رفع.", keywords: ["صورة إلى base64", "مرمّز صورة base64", "url بيانات الصورة", "png إلى base64", "تحويل الصورة إلى base64"], drop: "أفلِت صورة هنا أو انقر للاختيار", dataUrl: "عنوان URL للبيانات", css: "CSS", html: "HTML", size: "الحجم", preview: "معاينة" },
  ru: { title: "Конвертер изображения в Base64", short: "Преобразуйте изображение в data URL Base64.", description: "Бесплатный конвертер изображения в Base64. Перетащите PNG, JPG, GIF, SVG или WebP, чтобы получить data URL Base64 плюс готовые фрагменты CSS и HTML — всё в браузере, без загрузки.", keywords: ["изображение в base64", "кодировщик изображения base64", "data url изображения", "png в base64", "преобразовать изображение в base64"], drop: "Перетащите изображение сюда или нажмите для выбора", dataUrl: "Data URL", css: "CSS", html: "HTML", size: "Размер", preview: "Превью" },
  zh: { title: "图片转 Base64 转换器", short: "将图片转换为 Base64 数据 URL。", description: "免费的图片转 Base64 转换器。拖入 PNG、JPG、GIF、SVG 或 WebP，即可获得 Base64 数据 URL 以及可直接使用的 CSS 和 HTML 代码片段——全部在浏览器中完成，无需上传。", keywords: ["图片转 base64", "base64 图片编码器", "图片数据 url", "png 转 base64", "将图片转换为 base64"], drop: "将图片拖到此处或点击选择", dataUrl: "数据 URL", css: "CSS", html: "HTML", size: "大小", preview: "预览" },
  ja: { title: "画像から Base64 変換", short: "画像を Base64 データ URL に変換。", description: "無料の画像から Base64 変換ツール。PNG、JPG、GIF、SVG、WebP をドロップすると、Base64 データ URL とすぐ使える CSS・HTML スニペットが得られます——すべてブラウザ内で、アップロードなし。", keywords: ["画像 base64", "base64 画像エンコーダー", "画像 データ url", "png base64", "画像を base64 に変換"], drop: "画像をここにドロップまたはクリックして選択", dataUrl: "データ URL", css: "CSS", html: "HTML", size: "サイズ", preview: "プレビュー" },
  ko: { title: "이미지 to Base64 변환기", short: "이미지를 Base64 데이터 URL로 변환합니다.", description: "무료 이미지 to Base64 변환기. PNG, JPG, GIF, SVG, WebP를 드롭하면 Base64 데이터 URL과 바로 사용 가능한 CSS·HTML 스니펫을 얻습니다 — 모두 브라우저에서, 업로드 없음.", keywords: ["이미지 base64", "base64 이미지 인코더", "이미지 데이터 url", "png base64", "이미지를 base64로 변환"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", dataUrl: "데이터 URL", css: "CSS", html: "HTML", size: "크기", preview: "미리보기" },
  hi: { title: "इमेज से Base64 कन्वर्टर", short: "एक इमेज को Base64 डेटा URL में बदलें।", description: "मुफ्त इमेज से Base64 कन्वर्टर। एक PNG, JPG, GIF, SVG या WebP छोड़ें और Base64 डेटा URL के साथ उपयोग के लिए तैयार CSS और HTML स्निपेट पाएं — सब आपके ब्राउज़र में, कोई अपलोड नहीं।", keywords: ["इमेज से base64", "base64 इमेज एन्कोडर", "इमेज डेटा url", "png से base64", "इमेज को base64 में बदलें"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", dataUrl: "डेटा URL", css: "CSS", html: "HTML", size: "आकार", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
