import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "PDF Merger", short: "Merge multiple PDF files into one, in your browser.", description: "Free PDF merger. Drop two or more PDFs to combine them into a single file — reorder by dragging numbers, runs entirely in your browser via pdf-lib. Nothing is uploaded.", keywords: ["pdf merger", "combine pdf", "join pdfs", "merge pdf online", "pdf joiner"], drop: "Drop PDF files here or click to choose", merge: "Merge PDFs", download: "Download merged.pdf", up: "Move up", down: "Move down", remove: "Remove" },
  pt: { title: "PDF Merger", short: "Merge multiple PDF files into one, no seu navegador.", description: "Gratuito - PDF merger. Drop two ou more PDFs para combine them into a single file â reorder by dragging numbers, runs entirely no seu navegador via pdf-lib. Nothing is uploaded.", keywords: ["pdf merger", "combine pdf", "join pdfs", "merge pdf online", "pdf joiner"], drop: "Drop PDF files here or click to choose", merge: "Merge PDFs", download: "Download merged.pdf", up: "Move up", down: "Move down", remove: "Remove" },
  id: { title: "PDF Merger", short: "Merge multiple PDF files into one, di browser Anda.", description: "Gratis - PDF merger. Drop two atau more PDFs to combine them into a single file â reorder by dragging numbers, runs entirely di browser Anda via pdf-lib. Nothing is uploaded.", keywords: ["pdf merger", "combine pdf", "join pdfs", "merge pdf online", "pdf joiner"], drop: "Drop PDF files here or click to choose", merge: "Merge PDFs", download: "Download merged.pdf", up: "Move up", down: "Move down", remove: "Remove" },

  tr: { title: "PDF Birleştirici", short: "Birden fazla PDF dosyasını tarayıcınızda tek bir PDF'te birleştirin.", description: "Ücretsiz PDF birleştirici. İki veya daha fazla PDF bırakın ve tek bir dosyada birleştirin — sırayı değiştirebilirsiniz, tamamen tarayıcınızda pdf-lib ile çalışır. Hiçbir şey yüklenmez.", keywords: ["pdf birleştirici", "pdf birleştir", "pdf'leri birleştir", "online pdf birleştir", "pdf birleştirme"], drop: "PDF dosyalarını buraya bırakın veya seçmek için tıklayın", merge: "PDF'leri birleştir", download: "merged.pdf indir", up: "Yukarı taşı", down: "Aşağı taşı", remove: "Kaldır" },
  de: { title: "PDF-Zusammenführer", short: "Führen Sie mehrere PDF-Dateien zu einer im Browser zusammen.", description: "Kostenloser PDF-Zusammenführer. Legen Sie zwei oder mehr PDFs ab, um sie zu einer Datei zu kombinieren — neu anordnen ist möglich, läuft vollständig im Browser über pdf-lib. Nichts wird hochgeladen.", keywords: ["pdf zusammenführer", "pdf kombinieren", "pdfs verbinden", "pdf zusammenfügen online", "pdf merger"], drop: "PDF-Dateien hier ablegen oder klicken zum Auswählen", merge: "PDFs zusammenführen", download: "merged.pdf herunterladen", up: "Nach oben", down: "Nach unten", remove: "Entfernen" },
  fr: { title: "Fusionneur de PDF", short: "Fusionnez plusieurs fichiers PDF en un seul, dans votre navigateur.", description: "Fusionneur de PDF gratuit. Déposez deux PDF ou plus pour les combiner en un seul fichier — réordonnable, fonctionne entièrement dans votre navigateur via pdf-lib. Rien n'est envoyé.", keywords: ["fusionneur pdf", "combiner pdf", "joindre pdfs", "fusionner pdf en ligne", "assembleur pdf"], drop: "Déposez les fichiers PDF ici ou cliquez pour choisir", merge: "Fusionner les PDF", download: "Télécharger merged.pdf", up: "Monter", down: "Descendre", remove: "Supprimer" },
  es: { title: "Fusionador de PDF", short: "Fusiona varios archivos PDF en uno, en tu navegador.", description: "Fusionador de PDF gratuito. Arrastra dos o más PDF para combinarlos en un solo archivo — reordenable, funciona completamente en tu navegador con pdf-lib. Nada se sube.", keywords: ["fusionador pdf", "combinar pdf", "unir pdfs", "fusionar pdf online", "juntar pdf"], drop: "Arrastra archivos PDF aquí o haz clic para elegir", merge: "Fusionar PDF", download: "Descargar merged.pdf", up: "Mover arriba", down: "Mover abajo", remove: "Eliminar" },
  it: { title: "Unione di PDF", short: "Unisci più file PDF in uno solo, nel tuo browser.", description: "Unione di PDF gratuita. Trascina due o più PDF per combinarli in un unico file — riordinabile, funziona interamente nel browser tramite pdf-lib. Nulla viene caricato.", keywords: ["unione pdf", "combina pdf", "unisci pdfs", "unire pdf online", "merger pdf"], drop: "Trascina i file PDF qui o clicca per scegliere", merge: "Unisci PDF", download: "Scarica merged.pdf", up: "Su", down: "Giù", remove: "Rimuovi" },
  ar: { title: "دمج PDF", short: "ادمج عدة ملفات PDF في ملف واحد داخل متصفحك.", description: "أداة دمج PDF مجانية. أفلِت ملفي PDF أو أكثر لدمجها في ملف واحد — قابل لإعادة الترتيب، يعمل بالكامل في متصفحك عبر pdf-lib. لا شيء يُرفع.", keywords: ["دمج pdf", "ضم pdf", "دمج ملفات pdf", "دمج pdf عبر الإنترنت", "موحد pdf"], drop: "أفلِت ملفات PDF هنا أو انقر للاختيار", merge: "دمج ملفات PDF", download: "تنزيل merged.pdf", up: "للأعلى", down: "للأسفل", remove: "إزالة" },
  ru: { title: "Объединение PDF", short: "Объединяйте несколько PDF-файлов в один, в браузере.", description: "Бесплатное объединение PDF. Перетащите два или больше PDF, чтобы объединить их в один файл — порядок можно менять, работает полностью в браузере через pdf-lib. Ничего не загружается.", keywords: ["объединение pdf", "объединить pdf", "склейка pdfs", "объединить pdf онлайн", "слияние pdf"], drop: "Перетащите PDF-файлы сюда или нажмите для выбора", merge: "Объединить PDF", download: "Скачать merged.pdf", up: "Вверх", down: "Вниз", remove: "Удалить" },
  zh: { title: "PDF 合并", short: "在浏览器中将多个 PDF 合并为一个。", description: "免费的 PDF 合并器。拖入两个或更多 PDF 即可合并为一个文件——可重新排序，通过 pdf-lib 完全在浏览器中运行。不上传任何内容。", keywords: ["pdf 合并", "合并 pdf", "连接 pdf", "在线合并 pdf", "pdf 联合"], drop: "将 PDF 文件拖到此处或点击选择", merge: "合并 PDF", download: "下载 merged.pdf", up: "上移", down: "下移", remove: "移除" },
  ja: { title: "PDF 結合", short: "複数の PDF ファイルをブラウザ内で 1 つに結合。", description: "無料の PDF 結合ツール。2 つ以上の PDF をドロップすると 1 つのファイルに結合できます——並べ替え可能、pdf-lib によりすべてブラウザ内で動作。何もアップロードされません。", keywords: ["pdf 結合", "pdf 統合", "pdf 連結", "オンライン pdf 結合", "pdf マージ"], drop: "PDF ファイルをここにドロップまたはクリックして選択", merge: "PDF を結合", download: "merged.pdf をダウンロード", up: "上へ", down: "下へ", remove: "削除" },
  ko: { title: "PDF 병합", short: "여러 PDF 파일을 브라우저에서 하나로 병합합니다.", description: "무료 PDF 병합기. 두 개 이상의 PDF를 드롭하여 단일 파일로 결합하세요 — 순서 변경 가능, pdf-lib를 통해 모두 브라우저에서 실행됩니다. 아무것도 업로드되지 않습니다.", keywords: ["pdf 병합", "pdf 결합", "pdf 합치기", "온라인 pdf 병합", "pdf 합치기"], drop: "여기에 PDF 파일을 드롭하거나 클릭하여 선택", merge: "PDF 병합", download: "merged.pdf 다운로드", up: "위로", down: "아래로", remove: "제거" },
  hi: { title: "PDF मर्जर", short: "अपने ब्राउज़र में कई PDF फ़ाइलों को एक में मर्ज करें।", description: "मुफ्त PDF मर्जर। दो या अधिक PDF छोड़ें ताकि उन्हें एक फ़ाइल में संयोजित किया जा सके — पुनः व्यवस्थित किया जा सकता है, pdf-lib के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है। कुछ भी अपलोड नहीं होता।", keywords: ["pdf मर्जर", "pdf संयोजित करें", "pdfs जोड़ें", "ऑनलाइन pdf मर्ज", "pdf जॉइनर"], drop: "PDF फ़ाइलों को यहाँ छोड़ें या चुनने के लिए क्लिक करें", merge: "PDF मर्ज करें", download: "merged.pdf डाउनलोड", up: "ऊपर", down: "नीचे", remove: "हटाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
