import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Border Radius Generator", short: "Create CSS border-radius code with a live preview.", description: "Free CSS border-radius generator. Set each corner radius to get ready-to-paste border-radius CSS with a live preview.", keywords: ["border radius generator", "css border radius", "rounded corners", "border-radius code", "rounded corner css"], topLeft: "Top Left", topRight: "Top Right", bottomRight: "Bottom Right", bottomLeft: "Bottom Left", preview: "Preview" },
  tr: { title: "Border Radius Oluşturucu", short: "Canlı önizlemeyle CSS border-radius kodu oluşturun.", description: "Ücretsiz CSS border-radius oluşturucu. Her köşe yarıçapını ayarlayarak canlı önizlemeyle yapıştırmaya hazır border-radius CSS alın.", keywords: ["border radius oluşturucu", "css border radius", "yuvarlak köşeler", "border-radius kodu", "yuvarlak köşe css"], topLeft: "Sol Üst", topRight: "Sağ Üst", bottomRight: "Sağ Alt", bottomLeft: "Sol Alt", preview: "Önizleme" },
  de: { title: "Border-Radius-Generator", short: "Erstellen Sie CSS-border-radius-Code mit Live-Vorschau.", description: "Kostenloser CSS-border-radius-Generator. Legen Sie jeden Eckradius fest, um einsatzbereiten border-radius-CSS mit Live-Vorschau zu erhalten.", keywords: ["border radius generator", "css border radius", "abgerundete ecken", "border-radius code", "runde ecken css"], topLeft: "Oben Links", topRight: "Oben Rechts", bottomRight: "Unten Rechts", bottomLeft: "Unten Links", preview: "Vorschau" },
  fr: { title: "Générateur de Border-Radius", short: "Créez du code CSS border-radius avec aperçu en direct.", description: "Générateur de border-radius CSS gratuit. Définissez chaque rayon de coin pour obtenir du CSS border-radius prêt à coller avec aperçu en direct.", keywords: ["générateur border radius", "css border radius", "coins arrondis", "code border-radius", "coin arrondi css"], topLeft: "Haut Gauche", topRight: "Haut Droite", bottomRight: "Bas Droite", bottomLeft: "Bas Gauche", preview: "Aperçu" },
  es: { title: "Generador de Border-Radius", short: "Crea código CSS border-radius con vista previa en vivo.", description: "Generador de border-radius CSS gratuito. Define el radio de cada esquina para obtener CSS border-radius listo para pegar con vista previa en vivo.", keywords: ["generador border radius", "css border radius", "esquinas redondeadas", "código border-radius", "esquina redondeada css"], topLeft: "Superior Izquierda", topRight: "Superior Derecha", bottomRight: "Inferior Derecha", bottomLeft: "Inferior Izquierda", preview: "Vista previa" },
  it: { title: "Generatore di Border-Radius", short: "Crea codice CSS border-radius con anteprima dal vivo.", description: "Generatore di border-radius CSS gratuito. Imposta il raggio di ogni angolo per ottenere CSS border-radius pronto da incollare con anteprima dal vivo.", keywords: ["generatore border radius", "css border radius", "angoli arrotondati", "codice border-radius", "angolo arrotondato css"], topLeft: "In Alto a Sinistra", topRight: "In Alto a Destra", bottomRight: "In Basso a Destra", bottomLeft: "In Basso a Sinistra", preview: "Anteprima" },
  ar: { title: "مولّد نصف قطر الحدود", short: "أنشئ كود CSS border-radius مع معاينة حية.", description: "مولّد border-radius مجاني. اضبط نصف قطر كل زاوية للحصول على كود border-radius جاهز للصق مع معاينة حية.", keywords: ["مولد border radius", "css border radius", "زوايا مدورة", "كود border-radius", "زاوية مدورة css"], topLeft: "أعلى اليسار", topRight: "أعلى اليمين", bottomRight: "أسفل اليمين", bottomLeft: "أسفل اليسار", preview: "معاينة" },
  ru: { title: "Генератор Border-Radius", short: "Создавайте CSS border-radius с живым превью.", description: "Бесплатный генератор border-radius CSS. Задайте радиус каждого угла, чтобы получить готовый CSS border-radius с живым превью.", keywords: ["генератор border radius", "css border radius", "скруглённые углы", "border-radius код", "скруглённый угол css"], topLeft: "Верхний Левый", topRight: "Верхний Правый", bottomRight: "Нижний Правый", bottomLeft: "Нижний Левый", preview: "Превью" },
  zh: { title: "Border Radius 生成器", short: "创建 CSS border-radius 代码并实时预览。", description: "免费的 CSS border-radius 生成器。设置每个角的半径，即可获得可直接粘贴的 border-radius CSS 并实时预览。", keywords: ["border radius 生成器", "css border radius", "圆角", "border-radius 代码", "圆角 css"], topLeft: "左上", topRight: "右上", bottomRight: "右下", bottomLeft: "左下", preview: "预览" },
  ja: { title: "Border Radius 生成", short: "ライブプレビュー付きで CSS border-radius コードを作成。", description: "無料の CSS border-radius 生成ツール。各角の半径を設定すると、貼り付け可能な border-radius CSS がライブプレビュー付きで得られます。", keywords: ["border radius 生成", "css border radius", "角丸", "border-radius コード", "角丸 css"], topLeft: "左上", topRight: "右上", bottomRight: "右下", bottomLeft: "左下", preview: "プレビュー" },
  ko: { title: "Border Radius 생성기", short: "실시간 미리보기로 CSS border-radius 코드를 만듭니다.", description: "무료 CSS border-radius 생성기. 각 모서리 반경을 설정하면 붙여넣을 수 있는 border-radius CSS를 실시간 미리보기와 함께 얻습니다.", keywords: ["border radius 생성기", "css border radius", "둥근 모서리", "border-radius 코드", "둥근 모서리 css"], topLeft: "왼쪽 위", topRight: "오른쪽 위", bottomRight: "오른쪽 아래", bottomLeft: "왼쪽 아래", preview: "미리보기" },
  hi: { title: "Border Radius जनरेटर", short: "लाइव प्रीव्यू के साथ CSS border-radius कोड बनाएं।", description: "मुफ्त CSS border-radius जनरेटर। प्रत्येक कोने का रेडियस सेट करें और लाइव प्रीव्यू के साथ पेस्ट-तैयार border-radius CSS पाएं।", keywords: ["border radius जनरेटर", "css border radius", "गोल कोने", "border-radius कोड", "गोल कोना css"], topLeft: "ऊपर बाएं", topRight: "ऊपर दाएं", bottomRight: "नीचे दाएं", bottomLeft: "नीचे बाएं", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
