import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Pomodoro Timer", short: "A simple 25/5/15 Pomodoro timer with rounds.", description: "Free Pomodoro timer. Focus for 25 minutes, take a 5-minute break, and a 15-minute long break every fourth round — all customisable. Runs entirely in your browser.", keywords: ["pomodoro timer", "25 5 timer", "focus timer", "tomato timer", "study timer"], focus: "Focus", shortBreak: "Short break", longBreak: "Long break", round: "Round", start: "Start", pause: "Pause", reset: "Reset", focusLen: "Focus (min)", shortLen: "Short break (min)", longLen: "Long break (min)", roundsLen: "Rounds before long break" },
  nl: { title: "Pomodoro Timer", short: "A simple 25/5/15 Pomodoro timer with rounds.", description: "Gratis Pomodoro timer. Focus for 25 minuten, take a 5-minute break, and a 15-minute long break every fourth round — all customisable. Runs entirely in uw browser.", keywords: ["pomodoro timer", "25 5 timer", "focus timer", "tomato timer", "study timer"], focus: "Focus", shortBreak: "Short break", longBreak: "Long break", round: "Afronden", start: "Start", pause: "Pause", reset: "Reset", focusLen: "Focus (min)", shortLen: "Short break (min)", longLen: "Long break (min)", roundsLen: "Afrondens before long break" },

  pl: { title: "Pomodoro Timer", short: "A simple 25/5/15 Pomodoro timer with rounds.", description: "Darmowy Pomodoro timer. Focus for 25 minut, take a 5-minute break, and a 15-minute long break every fourth round — all customisable. Runs entirely w Twojej przeglądarce.", keywords: ["pomodoro timer", "25 5 timer", "focus timer", "tomato timer", "study timer"], focus: "Focus", shortBreak: "Short break", longBreak: "Long break", round: "Zaokrąglanie", start: "Start", pause: "Pause", reset: "Reset", focusLen: "Focus (min)", shortLen: "Short break (min)", longLen: "Long break (min)", roundsLen: "Zaokrąglanies before long break" },
  pt: { title: "Temporizador Pomodoro", short: "Um simple 25/5/15 Pomodoro timer com rounds.", description: "Gratuito - Pomodoro timer. Focus para 25 minutes, take a 5-minute break, e a 15-minute long break every fourth round â all customisable. Runs entirely no seu navegador.", keywords: ["pomodoro timer", "25 5 timer", "focus timer", "tomato timer", "study timer"], focus: "Focus", shortBreak: "Short break", longBreak: "Long break", round: "Round", start: "Start", pause: "Pause", reset: "Reset", focusLen: "Focus (min)", shortLen: "Short break (min)", longLen: "Long break (min)", roundsLen: "Rounds before long break" },
  id: { title: "Timer Pomodoro", short: "Sebuah simple 25/5/15 Pomodoro timer with rounds.", description: "Gratis - Pomodoro timer. Focus for 25 minutes, take a 5-minute break, dan a 15-minute long break every fourth round â all customisable. Runs entirely di browser Anda.", keywords: ["pomodoro timer", "25 5 timer", "focus timer", "tomato timer", "study timer"], focus: "Focus", shortBreak: "Short break", longBreak: "Long break", round: "Round", start: "Start", pause: "Pause", reset: "Reset", focusLen: "Focus (min)", shortLen: "Short break (min)", longLen: "Long break (min)", roundsLen: "Rounds before long break" },

  tr: { title: "Pomodoro Zamanlayıcı", short: "Turlu basit 25/5/15 Pomodoro zamanlayıcı.", description: "Ücretsiz Pomodoro zamanlayıcı. 25 dakika odaklanın, 5 dakika ara verin ve her dördüncü turda 15 dakika uzun ara verin — hepsi özelleştirilebilir. Tamamen tarayıcınızda çalışır.", keywords: ["pomodoro zamanlayıcı", "25 5 zamanlayıcı", "odak zamanlayıcı", "domates zamanlayıcı", "çalışma zamanlayıcı"], focus: "Odaklan", shortBreak: "Kısa ara", longBreak: "Uzun ara", round: "Tur", start: "Başlat", pause: "Duraklat", reset: "Sıfırla", focusLen: "Odak (dk)", shortLen: "Kısa ara (dk)", longLen: "Uzun ara (dk)", roundsLen: "Uzun aradan önce tur" },
  de: { title: "Pomodoro-Timer", short: "Ein einfacher 25/5/15-Pomodoro-Timer mit Runden.", description: "Kostenloser Pomodoro-Timer. 25 Minuten fokussieren, 5 Minuten Pause, alle vier Runden 15 Minuten lange Pause — alles anpassbar. Läuft vollständig im Browser.", keywords: ["pomodoro timer", "25 5 timer", "fokus timer", "tomaten timer", "lern timer"], focus: "Fokus", shortBreak: "Kurze Pause", longBreak: "Lange Pause", round: "Runde", start: "Start", pause: "Pause", reset: "Zurücksetzen", focusLen: "Fokus (Min)", shortLen: "Kurze Pause (Min)", longLen: "Lange Pause (Min)", roundsLen: "Runden vor langer Pause" },
  fr: { title: "Minuteur Pomodoro", short: "Un simple minuteur Pomodoro 25/5/15 avec tours.", description: "Minuteur Pomodoro gratuit. Concentrez-vous 25 minutes, faites une pause de 5 minutes et une longue pause de 15 minutes tous les 4 tours — tout personnalisable. Fonctionne entièrement dans votre navigateur.", keywords: ["minuteur pomodoro", "minuteur 25 5", "minuteur concentration", "minuteur tomate", "minuteur étude"], focus: "Concentration", shortBreak: "Pause courte", longBreak: "Pause longue", round: "Tour", start: "Démarrer", pause: "Pause", reset: "Réinitialiser", focusLen: "Concentration (min)", shortLen: "Pause courte (min)", longLen: "Pause longue (min)", roundsLen: "Tours avant pause longue" },
  es: { title: "Temporizador Pomodoro", short: "Un simple temporizador Pomodoro 25/5/15 con rondas.", description: "Temporizador Pomodoro gratuito. Concéntrate 25 minutos, descansa 5 minutos y un descanso largo de 15 minutos cada cuarta ronda — todo personalizable. Funciona completamente en tu navegador.", keywords: ["temporizador pomodoro", "temporizador 25 5", "temporizador concentración", "temporizador tomate", "temporizador estudio"], focus: "Concentración", shortBreak: "Descanso corto", longBreak: "Descanso largo", round: "Ronda", start: "Iniciar", pause: "Pausar", reset: "Reiniciar", focusLen: "Concentración (min)", shortLen: "Descanso corto (min)", longLen: "Descanso largo (min)", roundsLen: "Rondas antes del descanso largo" },
  it: { title: "Timer Pomodoro", short: "Un semplice timer Pomodoro 25/5/15 con round.", description: "Timer Pomodoro gratuito. Concentrati per 25 minuti, fai una pausa di 5 minuti e una pausa lunga di 15 minuti ogni quattro round — tutto personalizzabile. Funziona interamente nel browser.", keywords: ["timer pomodoro", "timer 25 5", "timer concentrazione", "timer pomodoro", "timer studio"], focus: "Concentrazione", shortBreak: "Pausa breve", longBreak: "Pausa lunga", round: "Round", start: "Avvia", pause: "Pausa", reset: "Reset", focusLen: "Concentrazione (min)", shortLen: "Pausa breve (min)", longLen: "Pausa lunga (min)", roundsLen: "Round prima della pausa lunga" },
  ar: { title: "مؤقّت Pomodoro", short: "مؤقّت Pomodoro بسيط 25/5/15 مع جولات.", description: "مؤقّت Pomodoro مجاني. ركّز لمدة 25 دقيقة، خذ استراحة 5 دقائق، واستراحة طويلة 15 دقيقة كل جولة رابعة — كل ذلك قابل للتخصيص. يعمل بالكامل في متصفحك.", keywords: ["مؤقت pomodoro", "مؤقت 25 5", "مؤقت التركيز", "مؤقت الطماطم", "مؤقت الدراسة"], focus: "التركيز", shortBreak: "استراحة قصيرة", longBreak: "استراحة طويلة", round: "جولة", start: "ابدأ", pause: "إيقاف مؤقت", reset: "إعادة تعيين", focusLen: "تركيز (دقيقة)", shortLen: "استراحة قصيرة (دقيقة)", longLen: "استراحة طويلة (دقيقة)", roundsLen: "جولات قبل الاستراحة الطويلة" },
  ru: { title: "Помодоро-таймер", short: "Простой Помодоро-таймер 25/5/15 с раундами.", description: "Бесплатный Помодоро-таймер. Сосредоточьтесь на 25 минут, сделайте перерыв 5 минут и длинный перерыв 15 минут каждый четвёртый раунд — всё настраивается. Работает полностью в браузере.", keywords: ["помодоро таймер", "таймер 25 5", "таймер концентрации", "томатный таймер", "учебный таймер"], focus: "Фокус", shortBreak: "Короткий перерыв", longBreak: "Длинный перерыв", round: "Раунд", start: "Старт", pause: "Пауза", reset: "Сброс", focusLen: "Фокус (мин)", shortLen: "Короткий перерыв (мин)", longLen: "Длинный перерыв (мин)", roundsLen: "Раундов до длинного перерыва" },
  zh: { title: "番茄钟", short: "带轮次的简单 25/5/15 番茄钟。", description: "免费的番茄钟。专注 25 分钟，休息 5 分钟，每 4 轮后休息 15 分钟——全部可自定义。完全在浏览器中运行。", keywords: ["番茄钟", "25 5 计时器", "专注计时器", "番茄计时器", "学习计时器"], focus: "专注", shortBreak: "短休息", longBreak: "长休息", round: "轮次", start: "开始", pause: "暂停", reset: "重置", focusLen: "专注（分钟）", shortLen: "短休息（分钟）", longLen: "长休息（分钟）", roundsLen: "长休息前的轮次" },
  ja: { title: "ポモドーロタイマー", short: "ラウンド付きのシンプルな 25/5/15 ポモドーロタイマー。", description: "無料のポモドーロタイマー。25 分集中し、5 分休憩、4 ラウンドごとに 15 分の長い休憩——すべてカスタマイズ可能。すべてブラウザ内で動作します。", keywords: ["ポモドーロ タイマー", "25 5 タイマー", "集中 タイマー", "トマト タイマー", "勉強 タイマー"], focus: "集中", shortBreak: "短い休憩", longBreak: "長い休憩", round: "ラウンド", start: "開始", pause: "一時停止", reset: "リセット", focusLen: "集中（分）", shortLen: "短い休憩（分）", longLen: "長い休憩（分）", roundsLen: "長い休憩までのラウンド" },
  ko: { title: "뽀모도로 타이머", short: "라운드가 있는 간단한 25/5/15 뽀모도로 타이머.", description: "무료 뽀모도로 타이머. 25분 집중, 5분 휴식, 4라운드마다 15분 긴 휴식 — 모두 사용자 정의 가능. 모두 브라우저에서 실행됩니다.", keywords: ["뽀모도로 타이머", "25 5 타이머", "집중 타이머", "토마토 타이머", "공부 타이머"], focus: "집중", shortBreak: "짧은 휴식", longBreak: "긴 휴식", round: "라운드", start: "시작", pause: "일시 정지", reset: "초기화", focusLen: "집중 (분)", shortLen: "짧은 휴식 (분)", longLen: "긴 휴식 (분)", roundsLen: "긴 휴식 전 라운드" },
  hi: { title: "पोमोडोरो टाइमर", short: "राउंड के साथ एक सरल 25/5/15 पोमोडोरो टाइमर।", description: "मुफ्त पोमोडोरो टाइमर। 25 मिनट ध्यान केंद्रित करें, 5 मिनट ब्रेक लें, और हर चौथे राउंड के बाद 15 मिनट लंबा ब्रेक — सब अनुकूलन योग्य। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["पोमोडोरो टाइमर", "25 5 टाइमर", "फोकस टाइमर", "टमाटर टाइमर", "अध्ययन टाइमर"], focus: "फोकस", shortBreak: "छोटा ब्रेक", longBreak: "लंबा ब्रेक", round: "राउंड", start: "शुरू", pause: "रोकें", reset: "रीसेट", focusLen: "फोकस (मिनट)", shortLen: "छोटा ब्रेक (मिनट)", longLen: "लंबा ब्रेक (मिनट)", roundsLen: "लंबे ब्रेक से पहले राउंड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
