import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Minecraft Color Codes", short: "Generate Minecraft color and format codes with a live styled preview.", description: "Free Minecraft color code generator. Click colors and formatting buttons to build §-coded text, see a live styled preview, and copy both the § and & variants for signs, books, server MOTDs and more.", keywords: ["minecraft color codes", "minecraft formatting codes", "minecraft chat colors", "motd generator", "minecraft text generator"], placeholder: "Type your text…", colors: "Colors", formats: "Formats", preview: "Preview", sectionVariant: "§ code", ampVariant: "& code" },
  nl: { title: "Minecraft Kleur Codes", short: "Genereer Minecraft kleur and formatteer codes with a live styled voorbeeld.", description: "Gratis Minecraft kleur code generator. Click kleurs and formatteerting buttons to build §-coded tekst, see a live styled voorbeeld, and copy both the § and & variants for signs, books, server MOTDs and more.", keywords: ["minecraft kleur codes", "minecraft formatteerting codes", "minecraft chat kleurs", "motd generator", "minecraft tekst generator"], placeholder: "Type your tekst…", colors: "Kleurs", formats: "Formatteers", preview: "Voorbeeld", sectionVariant: "§ code", ampVariant: "& code" },

  pl: { title: "Minecraft Kolor Kods", short: "Generuj Minecraft kolor and formatuj kods with a live styled podgląd.", description: "Darmowy Minecraft kolor kod generator. Click kolors and formatujting buttons to build §-kodd tekst, see a live styled podgląd, and copy both the § and & variants for signs, books, server MOTDs and more.", keywords: ["minecraft kolor kods", "minecraft formatujting kods", "minecraft chat kolors", "motd generator", "minecraft tekst generator"], placeholder: "Typ your tekst…", colors: "Kolors", formats: "Formatujs", preview: "Podgląd", sectionVariant: "§ kod", ampVariant: "& kod" },
  pt: { title: "Códigos de Cor do Minecraft", short: "Gere códigos de cor e formatação do Minecraft com pré-visualização ao vivo.", description: "Gerador gratuito de códigos de cor do Minecraft. Clique em cores e botões de formatação para montar texto com código §, veja uma pré-visualização ao vivo e copie as variantes § e & para placas, livros, MOTDs de servidor e mais.", keywords: ["minecraft color codes", "minecraft formatting codes", "minecraft chat colors", "motd generator", "minecraft text generator"], placeholder: "Digite seu texto…", colors: "Cores", formats: "Formatos", preview: "Pré-visualização", sectionVariant: "Código §", ampVariant: "Código &" },
  id: { title: "Kode Warna Minecraft", short: "Buat kode warna dan format Minecraft dengan pratinjau langsung bergaya.", description: "Generator kode warna Minecraft gratis. Klik warna dan tombol format untuk menyusun teks berkode §, lihat pratinjau langsung bergaya, dan salin varian § dan & untuk papan, buku, MOTD server, dan lainnya.", keywords: ["minecraft color codes", "minecraft formatting codes", "minecraft chat colors", "motd generator", "minecraft text generator"], placeholder: "Ketik teks Anda…", colors: "Warna", formats: "Format", preview: "Pratinjau", sectionVariant: "Kode §", ampVariant: "Kode &" },

  tr: { title: "Minecraft Renk Kodları", short: "Canlı stilize önizlemeyle Minecraft renk ve biçim kodları oluşturun.", description: "Ücretsiz Minecraft renk kodu oluşturucu. Renklere ve biçimlendirme düğmelerine tıklayarak § kodlu metin oluşturun, canlı stilize önizleme görün ve tabelalar, kitaplar, sunucu MOTD'leri için § ve & varyantlarını kopyalayın.", keywords: ["minecraft renk kodları", "minecraft biçim kodları", "minecraft sohbet renkleri", "motd oluşturucu", "minecraft metin oluşturucu"], placeholder: "Metninizi yazın…", colors: "Renkler", formats: "Biçimler", preview: "Önizleme", sectionVariant: "§ kodu", ampVariant: "& kodu" },
  de: { title: "Minecraft-Farbcodes", short: "Erstellen Sie Minecraft-Farb- und Formatcodes mit Live-Vorschau.", description: "Kostenloser Minecraft-Farbcode-Generator. Klicken Sie auf Farben und Formatierungsschaltflächen, um §-codierten Text zu erstellen, sehen Sie eine Live-Vorschau und kopieren Sie die §- und &-Varianten für Schilder, Bücher, Server-MOTDs und mehr.", keywords: ["minecraft farbcodes", "minecraft formatcodes", "minecraft chat-farben", "motd generator", "minecraft text-generator"], placeholder: "Geben Sie Ihren Text ein…", colors: "Farben", formats: "Formate", preview: "Vorschau", sectionVariant: "§-Code", ampVariant: "&-Code" },
  fr: { title: "Codes Couleur Minecraft", short: "Générez des codes couleur et de mise en forme Minecraft avec aperçu en direct.", description: "Générateur gratuit de codes couleur Minecraft. Cliquez sur les couleurs et les boutons de mise en forme pour créer du texte codé §, voyez un aperçu stylisé en direct et copiez les variantes § et & pour les pancartes, livres, MOTD de serveur et plus.", keywords: ["codes couleur minecraft", "codes de mise en forme minecraft", "couleurs de chat minecraft", "générateur motd", "générateur de texte minecraft"], placeholder: "Saisissez votre texte…", colors: "Couleurs", formats: "Formats", preview: "Aperçu", sectionVariant: "Code §", ampVariant: "Code &" },
  es: { title: "Códigos de Color de Minecraft", short: "Genera códigos de color y formato de Minecraft con vista previa en vivo.", description: "Generador gratuito de códigos de color de Minecraft. Haz clic en colores y botones de formato para crear texto con código §, ve una vista previa estilizada en vivo y copia las variantes § y & para letreros, libros, MOTD de servidor y más.", keywords: ["códigos de color minecraft", "códigos de formato minecraft", "colores de chat minecraft", "generador motd", "generador de texto minecraft"], placeholder: "Escribe tu texto…", colors: "Colores", formats: "Formatos", preview: "Vista previa", sectionVariant: "Código §", ampVariant: "Código &" },
  it: { title: "Codici Colore Minecraft", short: "Genera codici colore e formato di Minecraft con anteprima dal vivo.", description: "Generatore gratuito di codici colore Minecraft. Clicca su colori e pulsanti di formattazione per creare testo con codice §, guarda un'anteprima stilizzata dal vivo e copia le varianti § e & per cartelli, libri, MOTD del server e altro.", keywords: ["codici colore minecraft", "codici formato minecraft", "colori chat minecraft", "generatore motd", "generatore di testo minecraft"], placeholder: "Scrivi il tuo testo…", colors: "Colori", formats: "Formati", preview: "Anteprima", sectionVariant: "Codice §", ampVariant: "Codice &" },
  ar: { title: "أكواد ألوان ماين كرافت", short: "أنشئ أكواد ألوان وتنسيق ماين كرافت مع معاينة مباشرة بالأنماط.", description: "مولّد أكواد ألوان ماين كرافت مجاني. انقر على الألوان وأزرار التنسيق لإنشاء نص بكود §، وشاهد معاينة مباشرة بالأنماط، وانسخ متغيري § و& للافتات والكتب ورسائل MOTD للخوادم وغيرها.", keywords: ["أكواد ألوان ماين كرافت", "أكواد تنسيق ماين كرافت", "ألوان دردشة ماين كرافت", "مولد motd", "مولد نص ماين كرافت"], placeholder: "اكتب نصك…", colors: "الألوان", formats: "التنسيقات", preview: "المعاينة", sectionVariant: "كود §", ampVariant: "كود &" },
  ru: { title: "Цветовые Коды Minecraft", short: "Создавайте цветовые коды и коды форматирования Minecraft с живым предпросмотром.", description: "Бесплатный генератор цветовых кодов Minecraft. Нажимайте на цвета и кнопки форматирования, чтобы создать текст с кодом §, смотрите живой стилизованный предпросмотр и копируйте варианты § и & для табличек, книг, MOTD серверов и другого.", keywords: ["цветовые коды minecraft", "коды форматирования minecraft", "цвета чата minecraft", "генератор motd", "генератор текста minecraft"], placeholder: "Введите ваш текст…", colors: "Цвета", formats: "Форматы", preview: "Предпросмотр", sectionVariant: "Код §", ampVariant: "Код &" },
  zh: { title: "我的世界颜色代码", short: "生成带实时样式预览的我的世界颜色和格式代码。", description: "免费的我的世界颜色代码生成器。点击颜色和格式按钮来构建 § 代码文本，查看实时样式预览，并复制 § 和 & 两种变体，用于告示牌、书本、服务器 MOTD 等。", keywords: ["我的世界颜色代码", "我的世界格式代码", "我的世界聊天颜色", "motd 生成器", "我的世界文本生成器"], placeholder: "输入你的文本…", colors: "颜色", formats: "格式", preview: "预览", sectionVariant: "§ 代码", ampVariant: "& 代码" },
  ja: { title: "Minecraft カラーコード", short: "ライブスタイルプレビュー付きで Minecraft のカラー・書式コードを生成。", description: "無料の Minecraft カラーコードジェネレーター。色と書式ボタンをクリックして § コード付きテキストを作成し、ライブのスタイル付きプレビューを確認して、看板・本・サーバー MOTD などに使える § と & の両バリアントをコピーできます。", keywords: ["minecraft カラーコード", "minecraft 書式コード", "minecraft チャットカラー", "motd ジェネレーター", "minecraft テキストジェネレーター"], placeholder: "テキストを入力…", colors: "色", formats: "書式", preview: "プレビュー", sectionVariant: "§ コード", ampVariant: "& コード" },
  ko: { title: "마인크래프트 색상 코드", short: "실시간 스타일 미리보기로 마인크래프트 색상 및 서식 코드를 생성합니다.", description: "무료 마인크래프트 색상 코드 생성기. 색상과 서식 버튼을 클릭해 § 코드 텍스트를 만들고, 실시간 스타일 미리보기를 확인하며, 표지판·책·서버 MOTD 등에 쓸 § 및 & 두 가지 변형을 복사하세요.", keywords: ["마인크래프트 색상 코드", "마인크래프트 서식 코드", "마인크래프트 채팅 색상", "motd 생성기", "마인크래프트 텍스트 생성기"], placeholder: "텍스트를 입력하세요…", colors: "색상", formats: "서식", preview: "미리보기", sectionVariant: "§ 코드", ampVariant: "& 코드" },
  hi: { title: "माइनक्राफ्ट रंग कोड", short: "लाइव स्टाइल पूर्वावलोकन के साथ माइनक्राफ्ट रंग और प्रारूप कोड बनाएं।", description: "मुफ्त माइनक्राफ्ट रंग कोड जनरेटर। § कोड वाला टेक्स्ट बनाने के लिए रंगों और प्रारूप बटनों पर क्लिक करें, लाइव स्टाइल पूर्वावलोकन देखें, और साइन, किताबों, सर्वर MOTD आदि के लिए § और & दोनों वेरिएंट कॉपी करें।", keywords: ["माइनक्राफ्ट रंग कोड", "माइनक्राफ्ट प्रारूप कोड", "माइनक्राफ्ट चैट रंग", "motd जनरेटर", "माइनक्राफ्ट टेक्स्ट जनरेटर"], placeholder: "अपना टेक्स्ट टाइप करें…", colors: "रंग", formats: "प्रारूप", preview: "पूर्वावलोकन", sectionVariant: "§ कोड", ampVariant: "& कोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
