import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "User-Agent Parser", short: "Parse a browser user-agent string into browser, OS and device.", description: "Free user-agent parser. Paste any browser User-Agent string to see the detected browser and version, rendering engine, operating system and device class — runs entirely in your browser.", keywords: ["user agent parser", "ua parser", "browser detect", "useragent string", "parse user agent"], input: "User-Agent string", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Device", useMine: "Use my user agent" },
  nl: { title: "User-Leeftijdnt Parser", short: "Parse a browser user-agent string into browser, OS and device.", description: "Gratis user-agent parser. Paste any browser User-Leeftijdnt string to see the detected browser and version, rendering engine, operating system and device class — runs entirely in uw browser.", keywords: ["user agent parser", "ua parser", "browser detect", "useragent string", "parse user agent"], input: "User-Leeftijdnt string", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Device", useMine: "Use my user agent" },

  pl: { title: "User-Wieknt Parser", short: "Parse a browser user-agent string into browser, OS and device.", description: "Darmowy user-agent parser. Paste any browser User-Wieknt string to see the detected browser and version, rendering engine, operating system and device class — runs entirely w Twojej przeglądarce.", keywords: ["user agent parser", "ua parser", "browser detect", "useragent string", "parse user agent"], input: "User-Wieknt string", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Device", useMine: "Use my user agent" },
  pt: { title: "Analisador de User-Agent", short: "Parse a browser user-agent string into browser, OS e device.", description: "Gratuito - user-agent parser. Paste any browser User-Agent string para see the detected browser e version, rendering engine, operating system e device class â runs entirely no seu navegador.", keywords: ["user agent parser", "ua parser", "browser detect", "useragent string", "parse user agent"], input: "User-Agent string", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Device", useMine: "Use my user agent" },
  id: { title: "Parser User-Agent", short: "Parse a browser user-agent string into browser, OS dan device.", description: "Gratis - user-agent parser. Paste any browser User-Agent string to see the detected browser dan version, rendering engine, operating system dan device class â runs entirely di browser Anda.", keywords: ["user agent parser", "ua parser", "browser detect", "useragent string", "parse user agent"], input: "User-Agent string", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Device", useMine: "Use my user agent" },

  tr: { title: "User-Agent Ayrıştırıcı", short: "Bir tarayıcı user-agent dizesini tarayıcı, OS ve cihaza ayrıştırın.", description: "Ücretsiz user-agent ayrıştırıcı. Herhangi bir tarayıcı User-Agent dizesini yapıştırın; algılanan tarayıcı ve sürümünü, render motorunu, işletim sistemini ve cihaz sınıfını görün — tamamen tarayıcınızda çalışır.", keywords: ["user agent ayrıştırıcı", "ua ayrıştırıcı", "tarayıcı algılama", "useragent dizesi", "user agent ayrıştır"], input: "User-Agent dizesi", browser: "Tarayıcı", browserVersion: "Sürüm", engine: "Motor", os: "OS", device: "Cihaz", useMine: "Kendi user agent'ımı kullan" },
  de: { title: "User-Agent-Parser", short: "Parsen Sie einen User-Agent-String in Browser, OS und Gerät.", description: "Kostenloser User-Agent-Parser. Fügen Sie einen beliebigen User-Agent-String ein, um Browser und Version, Rendering-Engine, Betriebssystem und Geräteklasse zu sehen — läuft vollständig im Browser.", keywords: ["user agent parser", "ua parser", "browser erkennen", "useragent string", "user agent parsen"], input: "User-Agent-String", browser: "Browser", browserVersion: "Version", engine: "Engine", os: "OS", device: "Gerät", useMine: "Meinen User-Agent verwenden" },
  fr: { title: "Analyseur User-Agent", short: "Analysez une chaîne user-agent en navigateur, OS et appareil.", description: "Analyseur user-agent gratuit. Collez n'importe quelle chaîne User-Agent pour voir le navigateur et sa version, le moteur de rendu, le système d'exploitation et la classe d'appareil — fonctionne entièrement dans votre navigateur.", keywords: ["analyseur user agent", "ua parser", "détection navigateur", "chaîne useragent", "analyser user agent"], input: "Chaîne User-Agent", browser: "Navigateur", browserVersion: "Version", engine: "Moteur", os: "OS", device: "Appareil", useMine: "Utiliser mon user agent" },
  es: { title: "Analizador User-Agent", short: "Analiza una cadena user-agent en navegador, SO y dispositivo.", description: "Analizador user-agent gratuito. Pega cualquier cadena User-Agent para ver el navegador y versión, motor de renderizado, sistema operativo y clase de dispositivo — funciona completamente en tu navegador.", keywords: ["analizador user agent", "ua parser", "detección navegador", "cadena useragent", "analizar user agent"], input: "Cadena User-Agent", browser: "Navegador", browserVersion: "Versión", engine: "Motor", os: "SO", device: "Dispositivo", useMine: "Usar mi user agent" },
  it: { title: "Analizzatore User-Agent", short: "Analizza una stringa user-agent in browser, OS e dispositivo.", description: "Analizzatore user-agent gratuito. Incolla qualsiasi stringa User-Agent per vedere browser e versione, motore di rendering, sistema operativo e classe di dispositivo — funziona interamente nel browser.", keywords: ["analizzatore user agent", "ua parser", "rilevamento browser", "stringa useragent", "analizzare user agent"], input: "Stringa User-Agent", browser: "Browser", browserVersion: "Versione", engine: "Motore", os: "OS", device: "Dispositivo", useMine: "Usa il mio user agent" },
  ar: { title: "محلّل User-Agent", short: "حلّل سلسلة user-agent إلى متصفح ونظام تشغيل وجهاز.", description: "محلّل user-agent مجاني. الصق أي سلسلة User-Agent لرؤية المتصفح المكتشف وإصداره ومحرك العرض ونظام التشغيل وفئة الجهاز — يعمل بالكامل في متصفحك.", keywords: ["محلل user agent", "ua parser", "كشف المتصفح", "سلسلة useragent", "تحليل user agent"], input: "سلسلة User-Agent", browser: "المتصفح", browserVersion: "الإصدار", engine: "المحرك", os: "نظام التشغيل", device: "الجهاز", useMine: "استخدم user agent الخاص بي" },
  ru: { title: "Парсер User-Agent", short: "Разберите строку user-agent на браузер, ОС и устройство.", description: "Бесплатный парсер user-agent. Вставьте любую строку User-Agent, чтобы увидеть определённый браузер и версию, движок рендеринга, операционную систему и класс устройства — работает полностью в браузере.", keywords: ["парсер user agent", "ua parser", "определение браузера", "строка useragent", "разобрать user agent"], input: "Строка User-Agent", browser: "Браузер", browserVersion: "Версия", engine: "Движок", os: "ОС", device: "Устройство", useMine: "Использовать мой user agent" },
  zh: { title: "User-Agent 解析器", short: "将浏览器 user-agent 字符串解析为浏览器、操作系统和设备。", description: "免费的 user-agent 解析器。粘贴任何浏览器 User-Agent 字符串以查看识别的浏览器及版本、渲染引擎、操作系统和设备类别——完全在浏览器中运行。", keywords: ["user agent 解析器", "ua 解析器", "浏览器检测", "useragent 字符串", "解析 user agent"], input: "User-Agent 字符串", browser: "浏览器", browserVersion: "版本", engine: "引擎", os: "操作系统", device: "设备", useMine: "使用我的 user agent" },
  ja: { title: "User-Agent パーサー", short: "ブラウザ user-agent 文字列をブラウザ、OS、デバイスに解析。", description: "無料の user-agent パーサー。任意のブラウザ User-Agent 文字列を貼り付けると、検出されたブラウザとバージョン、レンダリングエンジン、OS、デバイスクラスを表示します——すべてブラウザ内で動作します。", keywords: ["user agent パーサー", "ua パーサー", "ブラウザ 検出", "useragent 文字列", "user agent 解析"], input: "User-Agent 文字列", browser: "ブラウザ", browserVersion: "バージョン", engine: "エンジン", os: "OS", device: "デバイス", useMine: "自分の user agent を使用" },
  ko: { title: "User-Agent 파서", short: "브라우저 user-agent 문자열을 브라우저, OS, 기기로 파싱합니다.", description: "무료 user-agent 파서. 모든 브라우저 User-Agent 문자열을 붙여넣으면 감지된 브라우저와 버전, 렌더링 엔진, 운영체제, 기기 클래스를 표시합니다 — 모두 브라우저에서 실행됩니다.", keywords: ["user agent 파서", "ua 파서", "브라우저 감지", "useragent 문자열", "user agent 파싱"], input: "User-Agent 문자열", browser: "브라우저", browserVersion: "버전", engine: "엔진", os: "OS", device: "기기", useMine: "내 user agent 사용" },
  hi: { title: "User-Agent पार्सर", short: "एक ब्राउज़र user-agent स्ट्रिंग को ब्राउज़र, OS और डिवाइस में पार्स करें।", description: "मुफ्त user-agent पार्सर। किसी भी ब्राउज़र User-Agent स्ट्रिंग को पेस्ट करें और पता लगाए गए ब्राउज़र व संस्करण, रेंडरिंग इंजन, ऑपरेटिंग सिस्टम और डिवाइस वर्ग देखें — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["user agent पार्सर", "ua पार्सर", "ब्राउज़र पहचान", "useragent स्ट्रिंग", "user agent पार्स"], input: "User-Agent स्ट्रिंग", browser: "ब्राउज़र", browserVersion: "संस्करण", engine: "इंजन", os: "OS", device: "डिवाइस", useMine: "मेरा user agent उपयोग करें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
