import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Password Strength Checker", short: "Estimate password entropy and crack time.", description: "Free password strength checker. See the entropy, estimated offline crack time and concrete suggestions for any password — runs entirely in your browser, never sent to a server.", keywords: ["password strength checker", "password entropy", "how strong is my password", "crack time estimator", "password tester"], input: "Password", strength: "Strength", entropy: "Entropy (bits)", crackTime: "Estimated crack time", suggestions: "Suggestions" },
  tr: { title: "Parola Gücü Denetleyici", short: "Parola entropisini ve kırılma süresini tahmin edin.", description: "Ücretsiz parola gücü denetleyici. Herhangi bir parola için entropisini, tahmini çevrimdışı kırılma süresini ve somut önerileri görün — tamamen tarayıcınızda çalışır, asla sunucuya gönderilmez.", keywords: ["parola gücü denetleyici", "parola entropisi", "parolam ne kadar güçlü", "kırılma süresi tahmini", "parola test"], input: "Parola", strength: "Güç", entropy: "Entropi (bit)", crackTime: "Tahmini kırılma süresi", suggestions: "Öneriler" },
  de: { title: "Passwort-Stärke-Prüfer", short: "Passwort-Entropie und Cracking-Zeit schätzen.", description: "Kostenloser Passwort-Stärke-Prüfer. Sehen Sie Entropie, geschätzte Offline-Cracking-Zeit und konkrete Vorschläge für jedes Passwort — läuft vollständig im Browser, nie an einen Server gesendet.", keywords: ["passwort stärke prüfer", "passwort entropie", "wie stark ist mein passwort", "cracking zeit schätzung", "passwort test"], input: "Passwort", strength: "Stärke", entropy: "Entropie (Bit)", crackTime: "Geschätzte Cracking-Zeit", suggestions: "Vorschläge" },
  fr: { title: "Vérificateur de Force de Mot de Passe", short: "Estimez l'entropie du mot de passe et le temps de craquage.", description: "Vérificateur de force de mot de passe gratuit. Voyez l'entropie, le temps estimé de craquage hors ligne et des suggestions concrètes pour tout mot de passe — fonctionne entièrement dans votre navigateur, jamais envoyé à un serveur.", keywords: ["vérificateur force mot passe", "entropie mot passe", "force de mon mot de passe", "estimation temps craquage", "testeur mot passe"], input: "Mot de passe", strength: "Force", entropy: "Entropie (bits)", crackTime: "Temps de craquage estimé", suggestions: "Suggestions" },
  es: { title: "Verificador de Fortaleza de Contraseña", short: "Estima la entropía de contraseña y el tiempo de descifrado.", description: "Verificador de fortaleza de contraseña gratuito. Ve la entropía, el tiempo estimado de descifrado offline y sugerencias concretas para cualquier contraseña — funciona completamente en tu navegador, nunca se envía a un servidor.", keywords: ["verificador fortaleza contraseña", "entropía contraseña", "fortaleza de mi contraseña", "estimación tiempo descifrado", "tester contraseña"], input: "Contraseña", strength: "Fortaleza", entropy: "Entropía (bits)", crackTime: "Tiempo estimado de descifrado", suggestions: "Sugerencias" },
  it: { title: "Controllo Forza Password", short: "Stima l'entropia della password e il tempo di cracking.", description: "Controllo gratuito della forza della password. Vedi l'entropia, il tempo stimato di cracking offline e suggerimenti concreti per qualsiasi password — funziona interamente nel browser, mai inviato a un server.", keywords: ["controllo forza password", "entropia password", "quanto è forte la mia password", "stima tempo cracking", "tester password"], input: "Password", strength: "Forza", entropy: "Entropia (bit)", crackTime: "Tempo stimato di cracking", suggestions: "Suggerimenti" },
  ar: { title: "مدقّق قوة كلمة المرور", short: "قدّر إنتروبيا كلمة المرور ووقت الكسر.", description: "مدقّق قوة كلمة مرور مجاني. شاهد الإنتروبيا والوقت المُقدَّر لكسر كلمة المرور دون اتصال والاقتراحات الملموسة لأي كلمة مرور — يعمل بالكامل في متصفحك، ولا يُرسَل أبدًا إلى خادم.", keywords: ["مدقق قوة كلمة المرور", "إنتروبيا كلمة المرور", "ما مدى قوة كلمة مروري", "تقدير وقت الكسر", "اختبار كلمة المرور"], input: "كلمة المرور", strength: "القوة", entropy: "الإنتروبيا (بت)", crackTime: "وقت الكسر المُقدَّر", suggestions: "الاقتراحات" },
  ru: { title: "Проверка надёжности пароля", short: "Оцените энтропию пароля и время взлома.", description: "Бесплатная проверка надёжности пароля. Узнайте энтропию, оценочное время оффлайн-взлома и конкретные предложения для любого пароля — работает полностью в браузере, никогда не отправляется на сервер.", keywords: ["проверка надёжности пароля", "энтропия пароля", "насколько надёжен мой пароль", "оценка времени взлома", "тестер пароля"], input: "Пароль", strength: "Надёжность", entropy: "Энтропия (бит)", crackTime: "Оценочное время взлома", suggestions: "Предложения" },
  zh: { title: "密码强度检查器", short: "估算密码熵和破解时间。", description: "免费的密码强度检查器。查看任何密码的熵、估计离线破解时间和具体建议——完全在浏览器中运行，从不发送到服务器。", keywords: ["密码强度检查器", "密码熵", "我的密码有多强", "破解时间估算", "密码测试器"], input: "密码", strength: "强度", entropy: "熵（位）", crackTime: "估计破解时间", suggestions: "建议" },
  ja: { title: "パスワード強度チェッカー", short: "パスワードのエントロピーとクラック時間を推定。", description: "無料のパスワード強度チェッカー。任意のパスワードのエントロピー、オフラインでの推定クラック時間、具体的な提案を確認——すべてブラウザ内で動作し、サーバーには送信されません。", keywords: ["パスワード 強度 チェッカー", "パスワード エントロピー", "パスワードの強度", "クラック 時間 推定", "パスワード テスター"], input: "パスワード", strength: "強度", entropy: "エントロピー（ビット）", crackTime: "推定クラック時間", suggestions: "提案" },
  ko: { title: "비밀번호 강도 검사기", short: "비밀번호 엔트로피와 해독 시간을 추정합니다.", description: "무료 비밀번호 강도 검사기. 모든 비밀번호의 엔트로피, 오프라인 해독 추정 시간 및 구체적인 제안을 확인하세요 — 모두 브라우저에서 실행되며 서버로 전송되지 않습니다.", keywords: ["비밀번호 강도 검사기", "비밀번호 엔트로피", "내 비밀번호 강도", "해독 시간 추정", "비밀번호 테스터"], input: "비밀번호", strength: "강도", entropy: "엔트로피 (비트)", crackTime: "예상 해독 시간", suggestions: "제안" },
  hi: { title: "पासवर्ड शक्ति परीक्षक", short: "पासवर्ड एन्ट्रॉपी और क्रैक समय का अनुमान लगाएं।", description: "मुफ्त पासवर्ड शक्ति परीक्षक। किसी भी पासवर्ड के लिए एन्ट्रॉपी, अनुमानित ऑफ़लाइन क्रैक समय और ठोस सुझाव देखें — पूरी तरह आपके ब्राउज़र में चलता है, कभी सर्वर पर नहीं भेजा जाता।", keywords: ["पासवर्ड शक्ति परीक्षक", "पासवर्ड एन्ट्रॉपी", "मेरा पासवर्ड कितना मजबूत", "क्रैक समय अनुमानक", "पासवर्ड टेस्टर"], input: "पासवर्ड", strength: "शक्ति", entropy: "एन्ट्रॉपी (बिट)", crackTime: "अनुमानित क्रैक समय", suggestions: "सुझाव" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
