import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "SPF Record Checker", short: "Look up and validate a domain's SPF record.", description: "Free SPF checker. Look up a domain's SPF (Sender Policy Framework) TXT record, parse its mechanisms, count DNS lookups against the RFC 7208 limit of 10 and flag issues. Runs in your browser via Cloudflare DoH.", keywords: ["spf checker", "spf record lookup", "spf validator", "sender policy framework", "email authentication"], domain: "Domain", check: "Check", record: "SPF record", mechanisms: "Mechanisms", lookups: "DNS lookups", noRecord: "No SPF record found for this domain.", hint: "Enter a domain (e.g. example.com) to look up its SPF record." },
  pt: { title: "Verificador de Registro SPF", short: "Pesquise e valide o registro SPF de um domínio.", description: "Verificador SPF gratuito. Pesquise o registro TXT SPF (Sender Policy Framework) de um domínio, analise seus mecanismos, conte as consultas DNS contra o limite de 10 do RFC 7208 e sinalize problemas. Roda no seu navegador via Cloudflare DoH.", keywords: ["spf checker", "spf record lookup", "spf validator", "sender policy framework", "email authentication"], domain: "Domínio", check: "Verificar", record: "Registro SPF", mechanisms: "Mecanismos", lookups: "Consultas DNS", noRecord: "Nenhum registro SPF encontrado para este domínio.", hint: "Digite um domínio (ex.: example.com) para pesquisar seu registro SPF." },
  id: { title: "Pemeriksa Rekaman SPF", short: "Cari dan validasi rekaman SPF domain.", description: "Pemeriksa SPF gratis. Cari rekaman TXT SPF (Sender Policy Framework) domain, urai mekanismenya, hitung pencarian DNS terhadap batas 10 dari RFC 7208 dan tandai masalah. Berjalan di browser Anda via Cloudflare DoH.", keywords: ["spf checker", "spf record lookup", "spf validator", "sender policy framework", "email authentication"], domain: "Domain", check: "Periksa", record: "Rekaman SPF", mechanisms: "Mekanisme", lookups: "Pencarian DNS", noRecord: "Tidak ada rekaman SPF ditemukan untuk domain ini.", hint: "Masukkan domain (mis. example.com) untuk mencari rekaman SPF-nya." },

  tr: { title: "SPF Kaydı Denetleyici", short: "Bir alan adının SPF kaydını sorgulayın ve doğrulayın.", description: "Ücretsiz SPF denetleyici. Bir alan adının SPF (Sender Policy Framework) TXT kaydını sorgulayın, mekanizmalarını ayrıştırın, DNS sorgularını RFC 7208'in 10 sınırına göre sayın ve sorunları işaretleyin. Cloudflare DoH üzerinden tarayıcınızda çalışır.", keywords: ["spf denetleyici", "spf kaydı sorgu", "spf doğrulayıcı", "sender policy framework", "e-posta kimlik doğrulama"], domain: "Alan adı", check: "Denetle", record: "SPF kaydı", mechanisms: "Mekanizmalar", lookups: "DNS sorguları", noRecord: "Bu alan adı için SPF kaydı bulunamadı.", hint: "SPF kaydını sorgulamak için bir alan adı girin (ör. example.com)." },
  de: { title: "SPF-Eintrag-Prüfer", short: "SPF-Eintrag einer Domain abfragen und validieren.", description: "Kostenloser SPF-Prüfer. Fragen Sie den SPF-TXT-Eintrag (Sender Policy Framework) einer Domain ab, analysieren Sie die Mechanismen, zählen Sie DNS-Abfragen gegen das RFC-7208-Limit von 10 und markieren Sie Probleme. Läuft im Browser über Cloudflare DoH.", keywords: ["spf prüfer", "spf eintrag abfrage", "spf validator", "sender policy framework", "e-mail authentifizierung"], domain: "Domain", check: "Prüfen", record: "SPF-Eintrag", mechanisms: "Mechanismen", lookups: "DNS-Abfragen", noRecord: "Kein SPF-Eintrag für diese Domain gefunden.", hint: "Geben Sie eine Domain ein (z. B. example.com), um den SPF-Eintrag abzufragen." },
  fr: { title: "Vérificateur d'Enregistrement SPF", short: "Recherchez et validez l'enregistrement SPF d'un domaine.", description: "Vérificateur SPF gratuit. Recherchez l'enregistrement TXT SPF (Sender Policy Framework) d'un domaine, analysez ses mécanismes, comptez les requêtes DNS par rapport à la limite de 10 du RFC 7208 et signalez les problèmes. Fonctionne dans votre navigateur via Cloudflare DoH.", keywords: ["vérificateur spf", "recherche enregistrement spf", "validateur spf", "sender policy framework", "authentification email"], domain: "Domaine", check: "Vérifier", record: "Enregistrement SPF", mechanisms: "Mécanismes", lookups: "Requêtes DNS", noRecord: "Aucun enregistrement SPF trouvé pour ce domaine.", hint: "Saisissez un domaine (ex. example.com) pour rechercher son enregistrement SPF." },
  es: { title: "Verificador de Registro SPF", short: "Consulta y valida el registro SPF de un dominio.", description: "Verificador SPF gratuito. Consulta el registro TXT SPF (Sender Policy Framework) de un dominio, analiza sus mecanismos, cuenta las consultas DNS frente al límite de 10 del RFC 7208 y señala problemas. Funciona en tu navegador vía Cloudflare DoH.", keywords: ["verificador spf", "consulta registro spf", "validador spf", "sender policy framework", "autenticación de correo"], domain: "Dominio", check: "Verificar", record: "Registro SPF", mechanisms: "Mecanismos", lookups: "Consultas DNS", noRecord: "No se encontró un registro SPF para este dominio.", hint: "Introduce un dominio (p. ej. example.com) para consultar su registro SPF." },
  it: { title: "Verificatore Record SPF", short: "Cerca e valida il record SPF di un dominio.", description: "Verificatore SPF gratuito. Cerca il record TXT SPF (Sender Policy Framework) di un dominio, analizza i suoi meccanismi, conta le query DNS rispetto al limite di 10 del RFC 7208 e segnala i problemi. Funziona nel tuo browser tramite Cloudflare DoH.", keywords: ["verificatore spf", "ricerca record spf", "validatore spf", "sender policy framework", "autenticazione email"], domain: "Dominio", check: "Verifica", record: "Record SPF", mechanisms: "Meccanismi", lookups: "Query DNS", noRecord: "Nessun record SPF trovato per questo dominio.", hint: "Inserisci un dominio (es. example.com) per cercare il suo record SPF." },
  ar: { title: "فاحص سجل SPF", short: "ابحث عن سجل SPF لنطاق وتحقق منه.", description: "فاحص SPF مجاني. ابحث عن سجل TXT لـ SPF (Sender Policy Framework) لنطاق، وحلّل آلياته، واحسب استعلامات DNS مقابل حد RFC 7208 البالغ 10، وأبرز المشكلات. يعمل في متصفحك عبر Cloudflare DoH.", keywords: ["فاحص spf", "بحث سجل spf", "مدقق spf", "sender policy framework", "مصادقة البريد"], domain: "النطاق", check: "فحص", record: "سجل SPF", mechanisms: "الآليات", lookups: "استعلامات DNS", noRecord: "لم يتم العثور على سجل SPF لهذا النطاق.", hint: "أدخل نطاقًا (مثل example.com) للبحث عن سجل SPF الخاص به." },
  ru: { title: "Проверка SPF-записи", short: "Найдите и проверьте SPF-запись домена.", description: "Бесплатная проверка SPF. Найдите SPF TXT-запись (Sender Policy Framework) домена, разберите её механизмы, посчитайте DNS-запросы относительно лимита RFC 7208 в 10 и выявите проблемы. Работает в браузере через Cloudflare DoH.", keywords: ["проверка spf", "поиск spf записи", "валидатор spf", "sender policy framework", "аутентификация почты"], domain: "Домен", check: "Проверить", record: "SPF-запись", mechanisms: "Механизмы", lookups: "DNS-запросы", noRecord: "Для этого домена SPF-запись не найдена.", hint: "Введите домен (например, example.com), чтобы найти его SPF-запись." },
  zh: { title: "SPF 记录检查器", short: "查询并验证域名的 SPF 记录。", description: "免费的 SPF 检查器。查询域名的 SPF（Sender Policy Framework）TXT 记录，解析其机制，按 RFC 7208 的 10 次限制统计 DNS 查询并标记问题。通过 Cloudflare DoH 在浏览器中运行。", keywords: ["spf 检查器", "spf 记录查询", "spf 验证器", "sender policy framework", "邮件认证"], domain: "域名", check: "检查", record: "SPF 记录", mechanisms: "机制", lookups: "DNS 查询", noRecord: "未找到此域名的 SPF 记录。", hint: "输入域名（如 example.com）以查询其 SPF 记录。" },
  ja: { title: "SPF レコードチェッカー", short: "ドメインの SPF レコードを検索・検証します。", description: "無料の SPF チェッカー。ドメインの SPF（Sender Policy Framework）TXT レコードを検索し、メカニズムを解析、RFC 7208 の上限 10 に対して DNS 検索回数を数え、問題を指摘します。Cloudflare DoH を介してブラウザ内で動作します。", keywords: ["spf チェッカー", "spf レコード 検索", "spf 検証", "sender policy framework", "メール認証"], domain: "ドメイン", check: "チェック", record: "SPF レコード", mechanisms: "メカニズム", lookups: "DNS 検索", noRecord: "このドメインの SPF レコードは見つかりませんでした。", hint: "ドメイン（例: example.com）を入力して SPF レコードを検索します。" },
  ko: { title: "SPF 레코드 검사기", short: "도메인의 SPF 레코드를 조회하고 검증합니다.", description: "무료 SPF 검사기. 도메인의 SPF(Sender Policy Framework) TXT 레코드를 조회하고 메커니즘을 분석하며, RFC 7208의 10 제한에 대해 DNS 조회 수를 세고 문제를 표시합니다. Cloudflare DoH를 통해 브라우저에서 실행됩니다.", keywords: ["spf 검사기", "spf 레코드 조회", "spf 검증기", "sender policy framework", "이메일 인증"], domain: "도메인", check: "검사", record: "SPF 레코드", mechanisms: "메커니즘", lookups: "DNS 조회", noRecord: "이 도메인에 대한 SPF 레코드를 찾을 수 없습니다.", hint: "도메인(예: example.com)을 입력하여 SPF 레코드를 조회하세요." },
  hi: { title: "SPF रिकॉर्ड चेकर", short: "किसी डोमेन का SPF रिकॉर्ड देखें और मान्य करें।", description: "मुफ्त SPF चेकर। किसी डोमेन का SPF (Sender Policy Framework) TXT रिकॉर्ड देखें, उसके मैकेनिज्म पार्स करें, RFC 7208 की 10 की सीमा के विरुद्ध DNS लुकअप गिनें और समस्याएं चिह्नित करें। Cloudflare DoH के माध्यम से आपके ब्राउज़र में चलता है।", keywords: ["spf चेकर", "spf रिकॉर्ड lookup", "spf validator", "sender policy framework", "ईमेल प्रमाणीकरण"], domain: "डोमेन", check: "जाँचें", record: "SPF रिकॉर्ड", mechanisms: "मैकेनिज्म", lookups: "DNS लुकअप", noRecord: "इस डोमेन के लिए कोई SPF रिकॉर्ड नहीं मिला।", hint: "इसका SPF रिकॉर्ड देखने के लिए एक डोमेन दर्ज करें (जैसे example.com)।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
