import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Triangle Generator", short: "Generate a CSS triangle with the border trick.", description: "Free CSS triangle generator. Pick a direction (up/down/left/right), size and colour to get single-element triangle CSS — no SVG required, with a live preview.", keywords: ["css triangle generator", "border trick triangle", "css arrow", "css triangle code", "single element triangle"], direction: "Direction", size: "Size", color: "Color", up: "Up", down: "Down", left: "Left", right: "Right", preview: "Preview" },
  pt: { title: "CSS Triangle Generator", short: "Generate a CSS triangle with the border trick.", description: "Free CSS triangle generator. Pick a direction (up/down/left/right), size and colour to get single-element triangle CSS — no SVG required, with a live preview.", keywords: ["css triangle generator", "border trick triangle", "css arrow", "css triangle code", "single element triangle"], direction: "Direction", size: "Size", color: "Color", up: "Up", down: "Down", left: "Left", right: "Right", preview: "Preview" },
  id: { title: "CSS Triangle Generator", short: "Generate a CSS triangle with the border trick.", description: "Free CSS triangle generator. Pick a direction (up/down/left/right), size and colour to get single-element triangle CSS — no SVG required, with a live preview.", keywords: ["css triangle generator", "border trick triangle", "css arrow", "css triangle code", "single element triangle"], direction: "Direction", size: "Size", color: "Color", up: "Up", down: "Down", left: "Left", right: "Right", preview: "Preview" },

  tr: { title: "CSS Üçgen Oluşturucu", short: "Sınır numarasıyla CSS üçgeni oluşturun.", description: "Ücretsiz CSS üçgen oluşturucu. Yön (yukarı/aşağı/sol/sağ), boyut ve renk seçerek tek elementli üçgen CSS alın — SVG gerekmez, canlı önizlemeyle.", keywords: ["css üçgen oluşturucu", "sınır numarası üçgen", "css ok", "css üçgen kodu", "tek element üçgen"], direction: "Yön", size: "Boyut", color: "Renk", up: "Yukarı", down: "Aşağı", left: "Sol", right: "Sağ", preview: "Önizleme" },
  de: { title: "CSS-Dreieck-Generator", short: "Erzeugen Sie ein CSS-Dreieck mit dem Border-Trick.", description: "Kostenloser CSS-Dreieck-Generator. Wählen Sie Richtung (oben/unten/links/rechts), Größe und Farbe für ein Single-Element-Dreieck-CSS — kein SVG nötig, mit Live-Vorschau.", keywords: ["css dreieck generator", "border trick dreieck", "css pfeil", "css dreieck code", "single element dreieck"], direction: "Richtung", size: "Größe", color: "Farbe", up: "Oben", down: "Unten", left: "Links", right: "Rechts", preview: "Vorschau" },
  fr: { title: "Générateur de Triangle CSS", short: "Générez un triangle CSS avec le truc des bordures.", description: "Générateur de triangle CSS gratuit. Choisissez la direction (haut/bas/gauche/droite), la taille et la couleur pour obtenir du CSS de triangle à un seul élément — sans SVG, avec aperçu en direct.", keywords: ["générateur triangle css", "triangle truc bordure", "flèche css", "code triangle css", "triangle un élément"], direction: "Direction", size: "Taille", color: "Couleur", up: "Haut", down: "Bas", left: "Gauche", right: "Droite", preview: "Aperçu" },
  es: { title: "Generador de Triángulo CSS", short: "Genera un triángulo CSS con el truco del borde.", description: "Generador de triángulo CSS gratuito. Elige dirección (arriba/abajo/izquierda/derecha), tamaño y color para obtener CSS de triángulo de un solo elemento — sin SVG, con vista previa en vivo.", keywords: ["generador triángulo css", "truco borde triángulo", "flecha css", "código triángulo css", "triángulo un elemento"], direction: "Dirección", size: "Tamaño", color: "Color", up: "Arriba", down: "Abajo", left: "Izquierda", right: "Derecha", preview: "Vista previa" },
  it: { title: "Generatore di Triangolo CSS", short: "Genera un triangolo CSS con il trucco del bordo.", description: "Generatore di triangolo CSS gratuito. Scegli direzione (su/giù/sinistra/destra), dimensione e colore per ottenere CSS di triangolo a singolo elemento — senza SVG, con anteprima dal vivo.", keywords: ["generatore triangolo css", "trucco bordo triangolo", "freccia css", "codice triangolo css", "triangolo singolo elemento"], direction: "Direzione", size: "Dimensione", color: "Colore", up: "Su", down: "Giù", left: "Sinistra", right: "Destra", preview: "Anteprima" },
  ar: { title: "مولّد المثلث CSS", short: "أنشئ مثلث CSS باستخدام خدعة الحدود.", description: "مولّد مثلث CSS مجاني. اختر الاتجاه (أعلى/أسفل/يسار/يمين) والحجم واللون للحصول على CSS مثلث بعنصر واحد — لا حاجة لـ SVG، مع معاينة حية.", keywords: ["مولد المثلث css", "حدود الخدعة مثلث", "سهم css", "كود مثلث css", "مثلث عنصر واحد"], direction: "الاتجاه", size: "الحجم", color: "اللون", up: "أعلى", down: "أسفل", left: "يسار", right: "يمين", preview: "معاينة" },
  ru: { title: "Генератор CSS-треугольника", short: "Создавайте CSS-треугольник с помощью трюка с границами.", description: "Бесплатный генератор CSS-треугольника. Выберите направление (вверх/вниз/влево/вправо), размер и цвет, чтобы получить CSS треугольника на одном элементе — без SVG, с живым превью.", keywords: ["генератор треугольника css", "трюк границ треугольник", "css стрелка", "код треугольника css", "треугольник один элемент"], direction: "Направление", size: "Размер", color: "Цвет", up: "Вверх", down: "Вниз", left: "Влево", right: "Вправо", preview: "Превью" },
  zh: { title: "CSS 三角形生成器", short: "使用边框技巧生成 CSS 三角形。", description: "免费的 CSS 三角形生成器。选择方向（上/下/左/右）、尺寸和颜色，获得单元素三角形 CSS——无需 SVG，带实时预览。", keywords: ["css 三角形生成器", "边框技巧三角形", "css 箭头", "css 三角形代码", "单元素三角形"], direction: "方向", size: "尺寸", color: "颜色", up: "上", down: "下", left: "左", right: "右", preview: "预览" },
  ja: { title: "CSS 三角形ジェネレーター", short: "ボーダーのトリックで CSS 三角形を生成。", description: "無料の CSS 三角形ジェネレーター。方向（上下左右）、サイズ、色を選んで単一要素の三角形 CSS を取得——SVG 不要、ライブプレビュー付き。", keywords: ["css 三角形 ジェネレーター", "ボーダー トリック 三角形", "css 矢印", "css 三角形 コード", "単一要素 三角形"], direction: "方向", size: "サイズ", color: "色", up: "上", down: "下", left: "左", right: "右", preview: "プレビュー" },
  ko: { title: "CSS 삼각형 생성기", short: "테두리 트릭으로 CSS 삼각형을 생성합니다.", description: "무료 CSS 삼각형 생성기. 방향(위/아래/왼쪽/오른쪽), 크기, 색상을 선택해 단일 요소 삼각형 CSS를 얻으세요 — SVG 불필요, 실시간 미리보기 포함.", keywords: ["css 삼각형 생성기", "테두리 트릭 삼각형", "css 화살표", "css 삼각형 코드", "단일 요소 삼각형"], direction: "방향", size: "크기", color: "색상", up: "위", down: "아래", left: "왼쪽", right: "오른쪽", preview: "미리보기" },
  hi: { title: "CSS त्रिकोण जनरेटर", short: "बॉर्डर ट्रिक से CSS त्रिकोण बनाएं।", description: "मुफ्त CSS त्रिकोण जनरेटर। दिशा (ऊपर/नीचे/बाएं/दाएं), आकार और रंग चुनें ताकि एकल-तत्व त्रिकोण CSS पाएं — SVG की आवश्यकता नहीं, लाइव प्रीव्यू के साथ।", keywords: ["css त्रिकोण जनरेटर", "बॉर्डर ट्रिक त्रिकोण", "css तीर", "css त्रिकोण कोड", "एकल तत्व त्रिकोण"], direction: "दिशा", size: "आकार", color: "रंग", up: "ऊपर", down: "नीचे", left: "बाएं", right: "दाएं", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
