import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Box Shadow Generator", short: "Create CSS box-shadow code with a live preview.", description: "Free CSS box-shadow generator. Adjust offset, blur, spread, color and inset to get ready-to-paste box-shadow CSS with a live preview.", keywords: ["box shadow generator", "css box shadow", "shadow generator", "drop shadow css", "box-shadow code"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", spread: "Spread", color: "Color", inset: "Inset", preview: "Preview" },
  nl: { title: "Boxschaduw Generator", short: "Maak aan CSS box-shadow code with a live voorbeeld.", description: "Gratis CSS box-shadow generator. Adjust offset, blur, spread, kleur and inset to get ready-to-paste box-shadow CSS with a live voorbeeld.", keywords: ["box shadow generator", "css box shadow", "shadow generator", "drop shadow css", "box-shadow code"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", spread: "Spread", color: "Kleur", inset: "Inset", preview: "Voorbeeld" },

  pl: { title: "Cień Ramki Generator", short: "Utwórz CSS box-shadow kod with a live podgląd.", description: "Darmowy CSS box-shadow generator. Adjust offset, blur, spread, kolor and inset to get ready-to-paste box-shadow CSS with a live podgląd.", keywords: ["box shadow generator", "css box shadow", "shadow generator", "drop shadow css", "box-shadow kod"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", spread: "Spread", color: "Kolor", inset: "Inset", preview: "Podgląd" },
  pt: { title: "Gerador de Box Shadow", short: "Create CSS box-shadow code com a live preview.", description: "Gratuito - CSS box-shadow generator. Adjust offset, blur, spread, color e inset para get ready-para-paste box-shadow CSS com a live preview.", keywords: ["box shadow generator", "css box shadow", "shadow generator", "drop shadow css", "box-shadow code"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", spread: "Spread", color: "Color", inset: "Inset", preview: "Preview" },
  id: { title: "Generator Box Shadow", short: "Create CSS box-shadow code with a live preview.", description: "Gratis - CSS box-shadow generator. Adjust offset, blur, spread, color dan inset to get ready-to-paste box-shadow CSS with a live preview.", keywords: ["box shadow generator", "css box shadow", "shadow generator", "drop shadow css", "box-shadow code"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", spread: "Spread", color: "Color", inset: "Inset", preview: "Preview" },

  tr: { title: "Box Shadow Oluşturucu", short: "Canlı önizlemeyle CSS box-shadow kodu oluşturun.", description: "Ücretsiz CSS box-shadow oluşturucu. Konum, bulanıklık, yayılma, renk ve inset ayarlayarak canlı önizlemeyle yapıştırmaya hazır box-shadow CSS alın.", keywords: ["box shadow oluşturucu", "css box shadow", "gölge oluşturucu", "gölge css", "box-shadow kodu"], offsetX: "Konum X", offsetY: "Konum Y", blur: "Bulanıklık", spread: "Yayılma", color: "Renk", inset: "İç gölge", preview: "Önizleme" },
  de: { title: "Box-Shadow-Generator", short: "Erstellen Sie CSS-box-shadow-Code mit Live-Vorschau.", description: "Kostenloser CSS-box-shadow-Generator. Versatz, Unschärfe, Streuung, Farbe und Inset anpassen, um einsatzbereiten box-shadow-CSS mit Live-Vorschau zu erhalten.", keywords: ["box shadow generator", "css box shadow", "schatten generator", "schatten css", "box-shadow code"], offsetX: "Versatz X", offsetY: "Versatz Y", blur: "Unschärfe", spread: "Streuung", color: "Farbe", inset: "Innen", preview: "Vorschau" },
  fr: { title: "Générateur de Box-Shadow", short: "Créez du code CSS box-shadow avec aperçu en direct.", description: "Générateur de box-shadow CSS gratuit. Ajustez le décalage, le flou, l'étalement, la couleur et l'inset pour obtenir du CSS box-shadow prêt à coller avec aperçu en direct.", keywords: ["générateur box shadow", "css box shadow", "générateur ombre", "ombre css", "code box-shadow"], offsetX: "Décalage X", offsetY: "Décalage Y", blur: "Flou", spread: "Étalement", color: "Couleur", inset: "Intérieur", preview: "Aperçu" },
  es: { title: "Generador de Box-Shadow", short: "Crea código CSS box-shadow con vista previa en vivo.", description: "Generador de box-shadow CSS gratuito. Ajusta el desplazamiento, desenfoque, expansión, color e inset para obtener CSS box-shadow listo para pegar con vista previa en vivo.", keywords: ["generador box shadow", "css box shadow", "generador sombra", "sombra css", "código box-shadow"], offsetX: "Desplazamiento X", offsetY: "Desplazamiento Y", blur: "Desenfoque", spread: "Expansión", color: "Color", inset: "Interior", preview: "Vista previa" },
  it: { title: "Generatore di Box-Shadow", short: "Crea codice CSS box-shadow con anteprima dal vivo.", description: "Generatore di box-shadow CSS gratuito. Regola offset, sfocatura, diffusione, colore e inset per ottenere CSS box-shadow pronto da incollare con anteprima dal vivo.", keywords: ["generatore box shadow", "css box shadow", "generatore ombra", "ombra css", "codice box-shadow"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Sfocatura", spread: "Diffusione", color: "Colore", inset: "Interno", preview: "Anteprima" },
  ar: { title: "مولّد ظل الصندوق", short: "أنشئ كود CSS box-shadow مع معاينة حية.", description: "مولّد box-shadow مجاني. اضبط الإزاحة والتمويه والانتشار واللون والداخلي للحصول على كود box-shadow جاهز للصق مع معاينة حية.", keywords: ["مولد box shadow", "css box shadow", "مولد الظل", "ظل css", "كود box-shadow"], offsetX: "الإزاحة X", offsetY: "الإزاحة Y", blur: "التمويه", spread: "الانتشار", color: "اللون", inset: "داخلي", preview: "معاينة" },
  ru: { title: "Генератор Box-Shadow", short: "Создавайте CSS box-shadow с живым превью.", description: "Бесплатный генератор box-shadow CSS. Настройте смещение, размытие, растяжение, цвет и inset, чтобы получить готовый CSS box-shadow с живым превью.", keywords: ["генератор box shadow", "css box shadow", "генератор тени", "тень css", "box-shadow код"], offsetX: "Смещение X", offsetY: "Смещение Y", blur: "Размытие", spread: "Растяжение", color: "Цвет", inset: "Внутренняя", preview: "Превью" },
  zh: { title: "Box Shadow 生成器", short: "创建 CSS box-shadow 代码并实时预览。", description: "免费的 CSS box-shadow 生成器。调整偏移、模糊、扩展、颜色和内阴影，即可获得可直接粘贴的 box-shadow CSS 并实时预览。", keywords: ["box shadow 生成器", "css box shadow", "阴影生成器", "阴影 css", "box-shadow 代码"], offsetX: "水平偏移", offsetY: "垂直偏移", blur: "模糊", spread: "扩展", color: "颜色", inset: "内阴影", preview: "预览" },
  ja: { title: "Box Shadow 生成", short: "ライブプレビュー付きで CSS box-shadow コードを作成。", description: "無料の CSS box-shadow 生成ツール。オフセット、ぼかし、広がり、色、insetを調整すると、貼り付け可能な box-shadow CSS がライブプレビュー付きで得られます。", keywords: ["box shadow 生成", "css box shadow", "シャドウ 生成", "影 css", "box-shadow コード"], offsetX: "オフセット X", offsetY: "オフセット Y", blur: "ぼかし", spread: "広がり", color: "色", inset: "内側", preview: "プレビュー" },
  ko: { title: "Box Shadow 생성기", short: "실시간 미리보기로 CSS box-shadow 코드를 만듭니다.", description: "무료 CSS box-shadow 생성기. 오프셋, 흐림, 확산, 색상, inset을 조정하면 붙여넣을 수 있는 box-shadow CSS를 실시간 미리보기와 함께 얻습니다.", keywords: ["box shadow 생성기", "css box shadow", "그림자 생성기", "그림자 css", "box-shadow 코드"], offsetX: "오프셋 X", offsetY: "오프셋 Y", blur: "흐림", spread: "확산", color: "색상", inset: "내부", preview: "미리보기" },
  hi: { title: "Box Shadow जनरेटर", short: "लाइव प्रीव्यू के साथ CSS box-shadow कोड बनाएं।", description: "मुफ्त CSS box-shadow जनरेटर। ऑफसेट, ब्लर, स्प्रेड, रंग और inset समायोजित करें और लाइव प्रीव्यू के साथ पेस्ट-तैयार box-shadow CSS पाएं।", keywords: ["box shadow जनरेटर", "css box shadow", "शैडो जनरेटर", "शैडो css", "box-shadow कोड"], offsetX: "ऑफसेट X", offsetY: "ऑफसेट Y", blur: "ब्लर", spread: "स्प्रेड", color: "रंग", inset: "इनसेट", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
