import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Viewport & Screen Info", short: "See your viewport size, screen resolution and DPR.", description: "Free viewport info tool. See your live browser viewport width and height, physical screen resolution, device-pixel-ratio, orientation and aspect ratio — useful for responsive-design testing.", keywords: ["viewport size", "screen resolution", "what's my screen size", "device pixel ratio", "responsive design"], viewport: "Viewport", screen: "Screen", dpr: "Device pixel ratio", orientation: "Orientation", aspect: "Aspect ratio" },
  pt: { title: "Viewport & Screen Info", short: "See your viewport size, screen resolution and DPR.", description: "Free viewport info tool. See your live browser viewport width and height, physical screen resolution, device-pixel-ratio, orientation and aspect ratio — useful for responsive-design testing.", keywords: ["viewport size", "screen resolution", "what's my screen size", "device pixel ratio", "responsive design"], viewport: "Viewport", screen: "Screen", dpr: "Device pixel ratio", orientation: "Orientation", aspect: "Aspect ratio" },
  id: { title: "Viewport & Screen Info", short: "See your viewport size, screen resolution and DPR.", description: "Free viewport info tool. See your live browser viewport width and height, physical screen resolution, device-pixel-ratio, orientation and aspect ratio — useful for responsive-design testing.", keywords: ["viewport size", "screen resolution", "what's my screen size", "device pixel ratio", "responsive design"], viewport: "Viewport", screen: "Screen", dpr: "Device pixel ratio", orientation: "Orientation", aspect: "Aspect ratio" },

  tr: { title: "Görüntü Alanı & Ekran Bilgisi", short: "Görüntü alanı boyutunuzu, ekran çözünürlüğünüzü ve DPR'yi görün.", description: "Ücretsiz görüntü alanı bilgi aracı. Tarayıcı görüntü alanı genişlik ve yüksekliğinizi, fiziksel ekran çözünürlüğünüzü, cihaz piksel oranı, yönelim ve en boy oranını canlı olarak görün — duyarlı tasarım testi için kullanışlı.", keywords: ["görüntü alanı boyutu", "ekran çözünürlüğü", "ekran boyutum nedir", "cihaz piksel oranı", "duyarlı tasarım"], viewport: "Görüntü Alanı", screen: "Ekran", dpr: "Cihaz piksel oranı", orientation: "Yönelim", aspect: "En boy oranı" },
  de: { title: "Viewport- & Bildschirm-Info", short: "Sehen Sie Ihre Viewport-Größe, Bildschirmauflösung und DPR.", description: "Kostenloses Viewport-Info-Tool. Sehen Sie Ihre Live-Browser-Viewport-Breite und -Höhe, physische Bildschirmauflösung, Device-Pixel-Ratio, Orientierung und Seitenverhältnis — nützlich für Responsive-Design-Tests.", keywords: ["viewport größe", "bildschirm auflösung", "wie groß ist mein bildschirm", "device pixel ratio", "responsive design"], viewport: "Viewport", screen: "Bildschirm", dpr: "Device Pixel Ratio", orientation: "Orientierung", aspect: "Seitenverhältnis" },
  fr: { title: "Infos Viewport & Écran", short: "Voyez la taille de votre viewport, résolution d'écran et DPR.", description: "Outil d'infos viewport gratuit. Voyez la largeur et hauteur en direct de votre viewport navigateur, la résolution physique d'écran, le device-pixel-ratio, l'orientation et le rapport d'aspect — utile pour les tests de responsive design.", keywords: ["taille viewport", "résolution écran", "taille de mon écran", "device pixel ratio", "responsive design"], viewport: "Viewport", screen: "Écran", dpr: "Device pixel ratio", orientation: "Orientation", aspect: "Rapport d'aspect" },
  es: { title: "Info de Viewport y Pantalla", short: "Ve el tamaño de tu viewport, resolución de pantalla y DPR.", description: "Herramienta de info de viewport gratuita. Ve el ancho y alto en vivo del viewport del navegador, resolución física de pantalla, device-pixel-ratio, orientación y relación de aspecto — útil para pruebas de diseño responsive.", keywords: ["tamaño viewport", "resolución pantalla", "tamaño de mi pantalla", "device pixel ratio", "diseño responsive"], viewport: "Viewport", screen: "Pantalla", dpr: "Device pixel ratio", orientation: "Orientación", aspect: "Relación de aspecto" },
  it: { title: "Info Viewport e Schermo", short: "Vedi la dimensione del viewport, risoluzione schermo e DPR.", description: "Strumento info viewport gratuito. Vedi la larghezza e altezza dal vivo del viewport browser, risoluzione fisica schermo, device-pixel-ratio, orientamento e rapporto d'aspetto — utile per test di design responsive.", keywords: ["dimensione viewport", "risoluzione schermo", "dimensione mio schermo", "device pixel ratio", "design responsive"], viewport: "Viewport", screen: "Schermo", dpr: "Device pixel ratio", orientation: "Orientamento", aspect: "Rapporto d'aspetto" },
  ar: { title: "معلومات Viewport والشاشة", short: "اعرف حجم viewport ودقة الشاشة و DPR.", description: "أداة معلومات viewport مجانية. اعرض عرض وارتفاع viewport المتصفح المباشر، ودقة الشاشة الفيزيائية، ونسبة بكسل الجهاز، والاتجاه، ونسبة العرض — مفيد لاختبار التصميم المتجاوب.", keywords: ["حجم viewport", "دقة الشاشة", "حجم شاشتي", "نسبة بكسل الجهاز", "تصميم متجاوب"], viewport: "Viewport", screen: "الشاشة", dpr: "نسبة بكسل الجهاز", orientation: "الاتجاه", aspect: "نسبة العرض" },
  ru: { title: "Информация о Viewport и экране", short: "Узнайте размер вашего viewport, разрешение экрана и DPR.", description: "Бесплатный инструмент информации о viewport. Смотрите вживую ширину и высоту viewport браузера, физическое разрешение экрана, device-pixel-ratio, ориентацию и соотношение сторон — полезно для тестов адаптивного дизайна.", keywords: ["размер viewport", "разрешение экрана", "размер моего экрана", "device pixel ratio", "адаптивный дизайн"], viewport: "Viewport", screen: "Экран", dpr: "Device pixel ratio", orientation: "Ориентация", aspect: "Соотношение сторон" },
  zh: { title: "Viewport 和屏幕信息", short: "查看你的 viewport 大小、屏幕分辨率和 DPR。", description: "免费的 viewport 信息工具。实时查看你的浏览器 viewport 宽高、物理屏幕分辨率、设备像素比、方向和宽高比——适用于响应式设计测试。", keywords: ["viewport 大小", "屏幕分辨率", "我的屏幕尺寸", "设备像素比", "响应式设计"], viewport: "Viewport", screen: "屏幕", dpr: "设备像素比", orientation: "方向", aspect: "宽高比" },
  ja: { title: "Viewport & 画面情報", short: "viewport サイズ、画面解像度、DPR を確認。", description: "無料の viewport 情報ツール。ブラウザの viewport の幅と高さ、物理的な画面解像度、デバイスピクセル比、向き、アスペクト比をライブで確認——レスポンシブデザインのテストに便利。", keywords: ["viewport サイズ", "画面解像度", "私の画面サイズ", "デバイスピクセル比", "レスポンシブ デザイン"], viewport: "Viewport", screen: "画面", dpr: "デバイスピクセル比", orientation: "向き", aspect: "アスペクト比" },
  ko: { title: "Viewport 및 화면 정보", short: "Viewport 크기, 화면 해상도, DPR을 확인합니다.", description: "무료 viewport 정보 도구. 브라우저의 viewport 너비와 높이, 물리적 화면 해상도, 디바이스 픽셀 비율, 방향, 가로세로 비율을 실시간으로 확인하세요 — 반응형 디자인 테스트에 유용합니다.", keywords: ["viewport 크기", "화면 해상도", "내 화면 크기", "디바이스 픽셀 비율", "반응형 디자인"], viewport: "Viewport", screen: "화면", dpr: "디바이스 픽셀 비율", orientation: "방향", aspect: "가로세로 비율" },
  hi: { title: "Viewport और स्क्रीन जानकारी", short: "अपने viewport आकार, स्क्रीन रिज़ॉल्यूशन और DPR देखें।", description: "मुफ्त viewport जानकारी टूल। अपने ब्राउज़र viewport की चौड़ाई और ऊँचाई, भौतिक स्क्रीन रिज़ॉल्यूशन, डिवाइस पिक्सेल अनुपात, अभिविन्यास और आस्पेक्ट रेशियो को लाइव देखें — उत्तरदायी डिज़ाइन परीक्षण के लिए उपयोगी।", keywords: ["viewport आकार", "स्क्रीन रिज़ॉल्यूशन", "मेरा स्क्रीन आकार", "डिवाइस पिक्सेल अनुपात", "उत्तरदायी डिज़ाइन"], viewport: "Viewport", screen: "स्क्रीन", dpr: "डिवाइस पिक्सेल अनुपात", orientation: "अभिविन्यास", aspect: "आस्पेक्ट रेशियो" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
