import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image to Text (OCR)", short: "Extract text from an image or screenshot with OCR.", description: "Free image-to-text OCR tool. Upload a photo, scan or screenshot and extract the text it contains in 13 languages — recognition runs in your browser, the image is never uploaded.", keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "photo to text converter"], drop: "Drop an image here or click to upload", language: "Language", extract: "Extract text", working: "Recognizing…", engineNote: "The first run downloads the OCR engine and language data (a few MB) and needs a network connection. Recognition then runs in your browser.", failed: "Text extraction failed. Please try another image.", download: "Download .txt" },
  tr: { title: "Görselden Metne (OCR)", short: "OCR ile bir görsel veya ekran görüntüsünden metin çıkarın.", description: "Ücretsiz görselden metne OCR aracı. Bir fotoğraf, tarama veya ekran görüntüsü yükleyin ve içindeki metni 13 dilde çıkarın — tanıma tarayıcınızda çalışır, görsel hiçbir zaman yüklenmez.", keywords: ["görselden metne", "çevrimiçi ocr", "görselden metin çıkar", "resimden metne", "fotoğraftan metne"], drop: "Bir görseli buraya bırakın veya yüklemek için tıklayın", language: "Dil", extract: "Metni çıkar", working: "Tanınıyor…", engineNote: "İlk çalıştırma OCR motorunu ve dil verisini (birkaç MB) indirir ve internet bağlantısı gerektirir. Ardından tanıma tarayıcınızda çalışır.", failed: "Metin çıkarma başarısız oldu. Lütfen başka bir görsel deneyin.", download: ".txt indir" },
  de: { title: "Bild zu Text (OCR)", short: "Extrahieren Sie Text aus einem Bild oder Screenshot per OCR.", description: "Kostenloses Bild-zu-Text-OCR-Tool. Laden Sie ein Foto, einen Scan oder Screenshot hoch und extrahieren Sie den enthaltenen Text in 13 Sprachen — die Erkennung läuft im Browser, das Bild wird nie hochgeladen.", keywords: ["bild zu text", "ocr online", "text aus bild extrahieren", "bild in text", "foto zu text"], drop: "Bild hierher ziehen oder zum Hochladen klicken", language: "Sprache", extract: "Text extrahieren", working: "Erkenne…", engineNote: "Der erste Lauf lädt die OCR-Engine und Sprachdaten (einige MB) und benötigt eine Internetverbindung. Die Erkennung läuft dann im Browser.", failed: "Texterkennung fehlgeschlagen. Bitte versuchen Sie ein anderes Bild.", download: ".txt herunterladen" },
  fr: { title: "Image vers Texte (OCR)", short: "Extrayez le texte d'une image ou capture d'écran par OCR.", description: "Outil OCR image-vers-texte gratuit. Importez une photo, un scan ou une capture d'écran et extrayez le texte qu'elle contient en 13 langues — la reconnaissance s'exécute dans votre navigateur, l'image n'est jamais envoyée.", keywords: ["image vers texte", "ocr en ligne", "extraire texte d'une image", "photo en texte", "convertisseur image texte"], drop: "Déposez une image ici ou cliquez pour importer", language: "Langue", extract: "Extraire le texte", working: "Reconnaissance…", engineNote: "Le premier lancement télécharge le moteur OCR et les données de langue (quelques Mo) et nécessite une connexion. La reconnaissance s'exécute ensuite dans votre navigateur.", failed: "Échec de l'extraction de texte. Essayez une autre image.", download: "Télécharger .txt" },
  es: { title: "Imagen a Texto (OCR)", short: "Extrae texto de una imagen o captura de pantalla con OCR.", description: "Herramienta OCR de imagen a texto gratuita. Sube una foto, escaneo o captura y extrae el texto que contiene en 13 idiomas — el reconocimiento se ejecuta en tu navegador, la imagen nunca se sube.", keywords: ["imagen a texto", "ocr online", "extraer texto de imagen", "foto a texto", "convertidor imagen texto"], drop: "Suelta una imagen aquí o haz clic para subir", language: "Idioma", extract: "Extraer texto", working: "Reconociendo…", engineNote: "La primera ejecución descarga el motor OCR y los datos de idioma (unos MB) y necesita conexión. El reconocimiento se ejecuta luego en tu navegador.", failed: "La extracción de texto falló. Prueba con otra imagen.", download: "Descargar .txt" },
  it: { title: "Immagine in Testo (OCR)", short: "Estrai testo da un'immagine o screenshot con OCR.", description: "Strumento OCR immagine-in-testo gratuito. Carica una foto, scansione o screenshot ed estrai il testo contenuto in 13 lingue — il riconoscimento avviene nel browser, l'immagine non viene mai caricata.", keywords: ["immagine in testo", "ocr online", "estrai testo da immagine", "foto in testo", "convertitore immagine testo"], drop: "Trascina un'immagine qui o clicca per caricare", language: "Lingua", extract: "Estrai testo", working: "Riconoscimento…", engineNote: "La prima esecuzione scarica il motore OCR e i dati lingua (alcuni MB) e richiede una connessione. Il riconoscimento avviene poi nel browser.", failed: "Estrazione del testo non riuscita. Prova un'altra immagine.", download: "Scarica .txt" },
  pt: { title: "Imagem para Texto (OCR)", short: "Extraia texto de uma imagem ou captura de tela com OCR.", description: "Ferramenta OCR de imagem para texto gratuita. Envie uma foto, digitalização ou captura de tela e extraia o texto que ela contém em 13 idiomas — o reconhecimento é feito no seu navegador, a imagem nunca é enviada.", keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "photo to text converter"], drop: "Solte uma imagem aqui ou clique para enviar", language: "Idioma", extract: "Extrair texto", working: "Reconhecendo…", engineNote: "A primeira execução baixa o motor OCR e os dados de idioma (alguns MB) e precisa de conexão. O reconhecimento é feito então no seu navegador.", failed: "Falha na extração de texto. Tente outra imagem.", download: "Baixar .txt" },
  id: { title: "Gambar ke Teks (OCR)", short: "Ekstrak teks dari gambar atau tangkapan layar dengan OCR.", description: "Alat OCR gambar-ke-teks gratis. Unggah foto, pindaian, atau tangkapan layar dan ekstrak teks di dalamnya dalam 13 bahasa — pengenalan berjalan di browser Anda, gambar tidak pernah diunggah.", keywords: ["image to text", "ocr online", "extract text from image", "picture to text", "photo to text converter"], drop: "Letakkan gambar di sini atau klik untuk mengunggah", language: "Bahasa", extract: "Ekstrak teks", working: "Mengenali…", engineNote: "Proses pertama mengunduh mesin OCR dan data bahasa (beberapa MB) dan memerlukan koneksi. Pengenalan kemudian berjalan di browser Anda.", failed: "Ekstraksi teks gagal. Silakan coba gambar lain.", download: "Unduh .txt" },
  ar: { title: "صورة إلى نص (OCR)", short: "استخرج النص من صورة أو لقطة شاشة باستخدام OCR.", description: "أداة OCR مجانية لتحويل الصورة إلى نص. ارفع صورة أو مسحًا ضوئيًا أو لقطة شاشة واستخرج النص الموجود بها بـ 13 لغة — يتم التعرّف في متصفحك، ولا يتم رفع الصورة أبدًا.", keywords: ["صورة إلى نص", "ocr عبر الإنترنت", "استخراج النص من صورة", "صورة إلى نص", "محول الصور إلى نص"], drop: "أفلت صورة هنا أو انقر للرفع", language: "اللغة", extract: "استخراج النص", working: "جارٍ التعرّف…", engineNote: "تقوم أول عملية بتنزيل محرك OCR وبيانات اللغة (بضعة ميغابايت) وتتطلب اتصالاً بالإنترنت. ثم يجري التعرّف في متصفحك.", failed: "فشل استخراج النص. يرجى تجربة صورة أخرى.", download: "تنزيل .txt" },
  ru: { title: "Изображение в текст (OCR)", short: "Извлеките текст из изображения или скриншота с помощью OCR.", description: "Бесплатный OCR-инструмент изображение-в-текст. Загрузите фото, скан или скриншот и извлеките содержащийся текст на 13 языках — распознавание выполняется в браузере, изображение никогда не загружается.", keywords: ["изображение в текст", "ocr онлайн", "извлечь текст из изображения", "фото в текст", "конвертер изображение текст"], drop: "Перетащите изображение сюда или нажмите для загрузки", language: "Язык", extract: "Извлечь текст", working: "Распознавание…", engineNote: "Первый запуск скачивает движок OCR и языковые данные (несколько МБ) и требует подключения. Затем распознавание выполняется в браузере.", failed: "Не удалось извлечь текст. Попробуйте другое изображение.", download: "Скачать .txt" },
  zh: { title: "图片转文字 (OCR)", short: "用 OCR 从图片或截图中提取文字。", description: "免费的图片转文字 OCR 工具。上传照片、扫描件或截图，以 13 种语言提取其中的文字——识别在浏览器中进行，图片绝不上传。", keywords: ["图片转文字", "在线 ocr", "从图片提取文字", "图片识别文字", "照片转文字"], drop: "将图片拖到此处或点击上传", language: "语言", extract: "提取文字", working: "识别中…", engineNote: "首次运行会下载 OCR 引擎和语言数据（几 MB）并需要网络连接。之后识别在浏览器中进行。", failed: "文字提取失败。请尝试其他图片。", download: "下载 .txt" },
  ja: { title: "画像から文字 (OCR)", short: "OCR で画像やスクリーンショットから文字を抽出。", description: "無料の画像から文字への OCR ツール。写真、スキャン、スクリーンショットをアップロードし、含まれる文字を 13 言語で抽出——認識はブラウザ内で行われ、画像はアップロードされません。", keywords: ["画像から文字", "オンライン ocr", "画像から文字抽出", "画像を文字に", "写真を文字に"], drop: "画像をここにドロップまたはクリックしてアップロード", language: "言語", extract: "文字を抽出", working: "認識中…", engineNote: "初回実行時に OCR エンジンと言語データ（数 MB）をダウンロードし、ネットワーク接続が必要です。その後の認識はブラウザ内で行われます。", failed: "文字抽出に失敗しました。別の画像をお試しください。", download: ".txt をダウンロード" },
  ko: { title: "이미지에서 텍스트 (OCR)", short: "OCR로 이미지나 스크린샷에서 텍스트를 추출합니다.", description: "무료 이미지-텍스트 OCR 도구. 사진, 스캔 또는 스크린샷을 업로드하고 그 안의 텍스트를 13개 언어로 추출하세요 — 인식은 브라우저에서 실행되며 이미지는 업로드되지 않습니다.", keywords: ["이미지에서 텍스트", "온라인 ocr", "이미지에서 텍스트 추출", "사진을 텍스트로", "이미지 텍스트 변환"], drop: "여기에 이미지를 놓거나 클릭하여 업로드", language: "언어", extract: "텍스트 추출", working: "인식 중…", engineNote: "첫 실행 시 OCR 엔진과 언어 데이터(수 MB)를 내려받으며 네트워크 연결이 필요합니다. 이후 인식은 브라우저에서 실행됩니다.", failed: "텍스트 추출에 실패했습니다. 다른 이미지를 시도하세요.", download: ".txt 다운로드" },
  hi: { title: "इमेज से टेक्स्ट (OCR)", short: "OCR से इमेज या स्क्रीनशॉट से टेक्स्ट निकालें।", description: "मुफ्त इमेज-से-टेक्स्ट OCR टूल। एक फोटो, स्कैन या स्क्रीनशॉट अपलोड करें और उसमें मौजूद टेक्स्ट को 13 भाषाओं में निकालें — पहचान आपके ब्राउज़र में चलती है, इमेज कभी अपलोड नहीं होती।", keywords: ["इमेज से टेक्स्ट", "ऑनलाइन ocr", "इमेज से टेक्स्ट निकालें", "तस्वीर से टेक्स्ट", "फोटो से टेक्स्ट कन्वर्टर"], drop: "यहाँ एक इमेज छोड़ें या अपलोड करने के लिए क्लिक करें", language: "भाषा", extract: "टेक्स्ट निकालें", working: "पहचान रहे हैं…", engineNote: "पहली बार चलाने पर OCR इंजन और भाषा डेटा (कुछ MB) डाउनलोड होता है और नेटवर्क कनेक्शन चाहिए। फिर पहचान आपके ब्राउज़र में चलती है।", failed: "टेक्स्ट निकालना विफल रहा। कृपया दूसरी इमेज आज़माएँ।", download: ".txt डाउनलोड करें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
