import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Bcrypt Hash Generator & Verifier", short: "Hash and verify passwords with bcrypt.", description: "Free bcrypt hash generator and verifier. Hash a password at a configurable cost (4–15 rounds) or check whether a password matches a bcrypt hash — runs entirely in your browser via bcryptjs.", keywords: ["bcrypt hash", "bcrypt generator", "bcrypt verify", "password hash", "bcrypt online"], hash: "Hash", verify: "Verify", password: "Password", rounds: "Rounds", result: "Bcrypt hash", hashToVerify: "Hash", match: "Password matches the hash", noMatch: "Password does not match the hash" },
  pt: { title: "Bcrypt Hash Generator & Verifier", short: "Hash and verify passwords with bcrypt.", description: "Free bcrypt hash generator and verifier. Hash a password at a configurable cost (4–15 rounds) or check whether a password matches a bcrypt hash — runs entirely in your browser via bcryptjs.", keywords: ["bcrypt hash", "bcrypt generator", "bcrypt verify", "password hash", "bcrypt online"], hash: "Hash", verify: "Verify", password: "Password", rounds: "Rounds", result: "Bcrypt hash", hashToVerify: "Hash", match: "Password matches the hash", noMatch: "Password does not match the hash" },
  id: { title: "Bcrypt Hash Generator & Verifier", short: "Hash and verify passwords with bcrypt.", description: "Free bcrypt hash generator and verifier. Hash a password at a configurable cost (4–15 rounds) or check whether a password matches a bcrypt hash — runs entirely in your browser via bcryptjs.", keywords: ["bcrypt hash", "bcrypt generator", "bcrypt verify", "password hash", "bcrypt online"], hash: "Hash", verify: "Verify", password: "Password", rounds: "Rounds", result: "Bcrypt hash", hashToVerify: "Hash", match: "Password matches the hash", noMatch: "Password does not match the hash" },

  tr: { title: "Bcrypt Karma Oluşturucu ve Doğrulayıcı", short: "Parolaları bcrypt ile hashleyin ve doğrulayın.", description: "Ücretsiz bcrypt karma oluşturucu ve doğrulayıcı. Bir parolayı yapılandırılabilir maliyetle (4–15 tur) hashleyin veya bir parolanın bcrypt karmasıyla eşleşip eşleşmediğini kontrol edin — tamamen tarayıcınızda bcryptjs ile çalışır.", keywords: ["bcrypt karma", "bcrypt oluşturucu", "bcrypt doğrulama", "parola karma", "bcrypt online"], hash: "Karma oluştur", verify: "Doğrula", password: "Parola", rounds: "Tur", result: "Bcrypt karması", hashToVerify: "Karma", match: "Parola karmayla eşleşiyor", noMatch: "Parola karmayla eşleşmiyor" },
  de: { title: "Bcrypt-Hash-Generator & -Verifier", short: "Passwörter mit bcrypt hashen und verifizieren.", description: "Kostenloser bcrypt-Hash-Generator und -Verifier. Hashen Sie ein Passwort mit konfigurierbarem Kostenfaktor (4–15 Runden) oder prüfen Sie, ob ein Passwort einem bcrypt-Hash entspricht — läuft vollständig im Browser über bcryptjs.", keywords: ["bcrypt hash", "bcrypt generator", "bcrypt verifizieren", "passwort hash", "bcrypt online"], hash: "Hashen", verify: "Verifizieren", password: "Passwort", rounds: "Runden", result: "Bcrypt-Hash", hashToVerify: "Hash", match: "Passwort stimmt mit dem Hash überein", noMatch: "Passwort stimmt nicht mit dem Hash überein" },
  fr: { title: "Générateur & Vérificateur de Hash Bcrypt", short: "Hashez et vérifiez des mots de passe avec bcrypt.", description: "Générateur et vérificateur de hash bcrypt gratuit. Hashez un mot de passe avec un coût configurable (4–15 rounds) ou vérifiez si un mot de passe correspond à un hash bcrypt — fonctionne entièrement dans votre navigateur via bcryptjs.", keywords: ["hash bcrypt", "générateur bcrypt", "vérifier bcrypt", "hash mot de passe", "bcrypt en ligne"], hash: "Hasher", verify: "Vérifier", password: "Mot de passe", rounds: "Rounds", result: "Hash bcrypt", hashToVerify: "Hash", match: "Le mot de passe correspond au hash", noMatch: "Le mot de passe ne correspond pas au hash" },
  es: { title: "Generador & Verificador de Hash Bcrypt", short: "Hashea y verifica contraseñas con bcrypt.", description: "Generador y verificador de hash bcrypt gratuito. Hashea una contraseña con coste configurable (4–15 rondas) o comprueba si una contraseña coincide con un hash bcrypt — funciona completamente en tu navegador vía bcryptjs.", keywords: ["bcrypt hash", "generador bcrypt", "verificar bcrypt", "hash contraseña", "bcrypt online"], hash: "Hashear", verify: "Verificar", password: "Contraseña", rounds: "Rondas", result: "Hash bcrypt", hashToVerify: "Hash", match: "La contraseña coincide con el hash", noMatch: "La contraseña no coincide con el hash" },
  it: { title: "Generatore & Verificatore di Hash Bcrypt", short: "Hash e verifica password con bcrypt.", description: "Generatore e verificatore di hash bcrypt gratuito. Hash di una password con costo configurabile (4–15 round) o verifica se una password corrisponde a un hash bcrypt — funziona interamente nel browser tramite bcryptjs.", keywords: ["hash bcrypt", "generatore bcrypt", "verifica bcrypt", "hash password", "bcrypt online"], hash: "Hash", verify: "Verifica", password: "Password", rounds: "Round", result: "Hash bcrypt", hashToVerify: "Hash", match: "La password corrisponde al hash", noMatch: "La password non corrisponde al hash" },
  ar: { title: "مولّد ومحقّق Bcrypt Hash", short: "اهش وتحقّق من كلمات المرور باستخدام bcrypt.", description: "مولّد ومحقّق bcrypt hash مجاني. هش كلمة مرور بتكلفة قابلة للتخصيص (4–15 جولة) أو تحقّق مما إذا كانت كلمة المرور تطابق bcrypt hash — يعمل بالكامل في متصفحك عبر bcryptjs.", keywords: ["bcrypt hash", "مولد bcrypt", "تحقق bcrypt", "تجزئة كلمة المرور", "bcrypt عبر الإنترنت"], hash: "تجزئة", verify: "تحقق", password: "كلمة المرور", rounds: "الجولات", result: "Bcrypt hash", hashToVerify: "Hash", match: "كلمة المرور تطابق الـ hash", noMatch: "كلمة المرور لا تطابق الـ hash" },
  ru: { title: "Генератор и проверка Bcrypt", short: "Хешируйте и проверяйте пароли с bcrypt.", description: "Бесплатный генератор и проверка bcrypt-хеша. Захешируйте пароль с настраиваемой стоимостью (4–15 раундов) или проверьте, соответствует ли пароль bcrypt-хешу — работает полностью в браузере через bcryptjs.", keywords: ["bcrypt хеш", "генератор bcrypt", "проверить bcrypt", "хеш пароля", "bcrypt онлайн"], hash: "Захешировать", verify: "Проверить", password: "Пароль", rounds: "Раунды", result: "Bcrypt-хеш", hashToVerify: "Хеш", match: "Пароль совпадает с хешем", noMatch: "Пароль не совпадает с хешем" },
  zh: { title: "Bcrypt 哈希生成与校验", short: "用 bcrypt 哈希并校验密码。", description: "免费的 bcrypt 哈希生成器和校验器。用可配置的成本（4–15 轮）对密码进行哈希，或检查密码是否匹配 bcrypt 哈希——通过 bcryptjs 完全在浏览器中运行。", keywords: ["bcrypt 哈希", "bcrypt 生成器", "bcrypt 校验", "密码哈希", "bcrypt 在线"], hash: "生成哈希", verify: "校验", password: "密码", rounds: "轮数", result: "Bcrypt 哈希", hashToVerify: "哈希", match: "密码与哈希匹配", noMatch: "密码与哈希不匹配" },
  ja: { title: "Bcrypt ハッシュ生成と検証", short: "bcrypt でパスワードをハッシュ化・検証。", description: "無料の bcrypt ハッシュ生成・検証ツール。設定可能なコスト（4〜15 ラウンド）でパスワードをハッシュ化、またはパスワードが bcrypt ハッシュと一致するか確認します——bcryptjs によりすべてブラウザ内で動作します。", keywords: ["bcrypt ハッシュ", "bcrypt 生成", "bcrypt 検証", "パスワード ハッシュ", "bcrypt オンライン"], hash: "ハッシュ化", verify: "検証", password: "パスワード", rounds: "ラウンド", result: "Bcrypt ハッシュ", hashToVerify: "ハッシュ", match: "パスワードはハッシュと一致します", noMatch: "パスワードはハッシュと一致しません" },
  ko: { title: "Bcrypt 해시 생성기 및 검증기", short: "bcrypt로 비밀번호를 해시하고 검증합니다.", description: "무료 bcrypt 해시 생성기 및 검증기. 구성 가능한 비용(4–15 라운드)으로 비밀번호를 해시하거나 비밀번호가 bcrypt 해시와 일치하는지 확인합니다 — bcryptjs를 통해 모두 브라우저에서 실행됩니다.", keywords: ["bcrypt 해시", "bcrypt 생성기", "bcrypt 검증", "비밀번호 해시", "bcrypt 온라인"], hash: "해시", verify: "검증", password: "비밀번호", rounds: "라운드", result: "Bcrypt 해시", hashToVerify: "해시", match: "비밀번호가 해시와 일치합니다", noMatch: "비밀번호가 해시와 일치하지 않습니다" },
  hi: { title: "Bcrypt हैश जनरेटर और सत्यापनकर्ता", short: "bcrypt के साथ पासवर्ड को हैश और सत्यापित करें।", description: "मुफ्त bcrypt हैश जनरेटर और सत्यापनकर्ता। कॉन्फ़िगर करने योग्य लागत (4–15 राउंड) के साथ पासवर्ड हैश करें या जांचें कि कोई पासवर्ड bcrypt हैश से मेल खाता है — पूरी तरह bcryptjs के माध्यम से आपके ब्राउज़र में चलता है।", keywords: ["bcrypt हैश", "bcrypt जनरेटर", "bcrypt सत्यापित", "पासवर्ड हैश", "bcrypt ऑनलाइन"], hash: "हैश करें", verify: "सत्यापित करें", password: "पासवर्ड", rounds: "राउंड", result: "Bcrypt हैश", hashToVerify: "हैश", match: "पासवर्ड हैश से मेल खाता है", noMatch: "पासवर्ड हैश से मेल नहीं खाता" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
