import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const KW = ["ipv6 cidr calculator", "ipv6 range to cidr", "cidr to range", "ipv6 subnet range", "ipv6 address range"];

const data = {
  en: { title: "IPv6 CIDR Range Calculator", short: "Expand an IPv6 CIDR to its address range, or collapse a range into CIDR blocks.", description: "Free IPv6 CIDR range calculator. Expand a CIDR like 2001:db8::/126 into its first and last address and total count, or convert a start–end range into the minimal set of CIDR blocks. Uses BigInt and runs in your browser.", keywords: KW, modeToRange: "CIDR → Range", modeToCidr: "Range → CIDR", cidrLabel: "CIDR block", startLabel: "Start address", endLabel: "End address", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "First address", last: "Last address", count: "Address count", cidrBlocks: "CIDR blocks", invalid: "Invalid input for the selected mode." },
  nl: { title: "IPv6 CIDR Range Calculator", short: "Expand an IPv6 CIDR to its address range, or collapse a range into CIDR blocks.", description: "Gratis IPv6 CIDR range calculator. Expand a CIDR like 2001:db8::/126 into its first and last address and total count, or converteer a start–end range into the minimal set of CIDR blocks. Uses BigInt and runs in uw browser.", keywords: KW, modeToRange: "CIDR → Range", modeToCidr: "Range → CIDR", cidrLabel: "CIDR block", startLabel: "Start address", endLabel: "End address", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "First address", last: "Last address", count: "Address count", cidrBlocks: "CIDR blocks", invalid: "Invalid input for the selected mode." },

  pl: { title: "IPv6 CIDR Range Kalkulator", short: "Expand an IPv6 CIDR to its address range, or collapse a range into CIDR blocks.", description: "Darmowy IPv6 CIDR range kalkulator. Expand a CIDR like 2001:db8::/126 into its first and last address and total count, or konwertuj a start–end range into the minimal set of CIDR blocks. Uses BigInt and runs w Twojej przeglądarce.", keywords: KW, modeToRange: "CIDR → Range", modeToCidr: "Range → CIDR", cidrLabel: "CIDR block", startLabel: "Start address", endLabel: "End address", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "First address", last: "Last address", count: "Address count", cidrBlocks: "CIDR blocks", invalid: "Invalid input for the selected mode." },
  pt: { title: "Calculadora de Intervalo CIDR IPv6", short: "Expanda um CIDR IPv6 em seu intervalo de endereços ou colapse um intervalo em blocos CIDR.", description: "Calculadora de intervalo CIDR IPv6 gratuita. Expanda um CIDR como 2001:db8::/126 em seu primeiro e último endereço e contagem total, ou converta um intervalo início–fim no conjunto mínimo de blocos CIDR. Usa BigInt e roda no seu navegador.", keywords: KW, modeToRange: "CIDR → Intervalo", modeToCidr: "Intervalo → CIDR", cidrLabel: "Bloco CIDR", startLabel: "Endereço inicial", endLabel: "Endereço final", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Primeiro endereço", last: "Último endereço", count: "Total de endereços", cidrBlocks: "Blocos CIDR", invalid: "Entrada inválida para o modo selecionado." },
  id: { title: "Kalkulator Rentang CIDR IPv6", short: "Perluas CIDR IPv6 menjadi rentang alamatnya, atau ciutkan rentang menjadi blok CIDR.", description: "Kalkulator rentang CIDR IPv6 gratis. Perluas CIDR seperti 2001:db8::/126 menjadi alamat pertama dan terakhir serta jumlah total, atau konversi rentang awal–akhir menjadi kumpulan blok CIDR minimal. Menggunakan BigInt dan berjalan di browser Anda.", keywords: KW, modeToRange: "CIDR → Rentang", modeToCidr: "Rentang → CIDR", cidrLabel: "Blok CIDR", startLabel: "Alamat awal", endLabel: "Alamat akhir", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Alamat pertama", last: "Alamat terakhir", count: "Jumlah alamat", cidrBlocks: "Blok CIDR", invalid: "Input tidak valid untuk mode yang dipilih." },

  tr: { title: "IPv6 CIDR Aralık Hesaplayıcı", short: "Bir IPv6 CIDR'ını adres aralığına genişletin veya bir aralığı CIDR bloklarına daraltın.", description: "Ücretsiz IPv6 CIDR aralık hesaplayıcı. 2001:db8::/126 gibi bir CIDR'ı ilk ve son adresine ve toplam sayısına genişletin veya başlangıç–bitiş aralığını minimum CIDR blokları kümesine dönüştürün. BigInt kullanır ve tarayıcınızda çalışır.", keywords: ["ipv6 cidr hesaplayıcı", "ipv6 aralık cidr", "cidr aralık dönüştürücü", "ipv6 alt ağ aralığı", "ipv6 adres aralığı"], modeToRange: "CIDR → Aralık", modeToCidr: "Aralık → CIDR", cidrLabel: "CIDR bloğu", startLabel: "Başlangıç adresi", endLabel: "Bitiş adresi", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "İlk adres", last: "Son adres", count: "Adres sayısı", cidrBlocks: "CIDR blokları", invalid: "Seçilen mod için geçersiz giriş." },
  de: { title: "IPv6 CIDR-Bereichsrechner", short: "Erweitern Sie einen IPv6-CIDR zu seinem Adressbereich oder fassen Sie einen Bereich zu CIDR-Blöcken zusammen.", description: "Kostenloser IPv6-CIDR-Bereichsrechner. Erweitern Sie einen CIDR wie 2001:db8::/126 zu seiner ersten und letzten Adresse und Gesamtanzahl oder wandeln Sie einen Start–End-Bereich in die minimale Menge an CIDR-Blöcken um. Verwendet BigInt und läuft in Ihrem Browser.", keywords: ["ipv6 cidr rechner", "ipv6 bereich cidr", "cidr zu bereich", "ipv6 subnetz bereich", "ipv6 adressbereich"], modeToRange: "CIDR → Bereich", modeToCidr: "Bereich → CIDR", cidrLabel: "CIDR-Block", startLabel: "Startadresse", endLabel: "Endadresse", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Erste Adresse", last: "Letzte Adresse", count: "Adressanzahl", cidrBlocks: "CIDR-Blöcke", invalid: "Ungültige Eingabe für den gewählten Modus." },
  fr: { title: "Calculateur de Plage CIDR IPv6", short: "Développez un CIDR IPv6 en sa plage d'adresses, ou réduisez une plage en blocs CIDR.", description: "Calculateur de plage CIDR IPv6 gratuit. Développez un CIDR comme 2001:db8::/126 en sa première et dernière adresse et son nombre total, ou convertissez une plage début–fin en l'ensemble minimal de blocs CIDR. Utilise BigInt et fonctionne dans votre navigateur.", keywords: ["calculateur cidr ipv6", "plage ipv6 cidr", "cidr vers plage", "plage sous-réseau ipv6", "plage adresses ipv6"], modeToRange: "CIDR → Plage", modeToCidr: "Plage → CIDR", cidrLabel: "Bloc CIDR", startLabel: "Adresse de début", endLabel: "Adresse de fin", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Première adresse", last: "Dernière adresse", count: "Nombre d'adresses", cidrBlocks: "Blocs CIDR", invalid: "Entrée invalide pour le mode sélectionné." },
  es: { title: "Calculadora de Rango CIDR IPv6", short: "Expande un CIDR IPv6 a su rango de direcciones, o colapsa un rango en bloques CIDR.", description: "Calculadora de rango CIDR IPv6 gratuita. Expande un CIDR como 2001:db8::/126 a su primera y última dirección y recuento total, o convierte un rango inicio–fin en el conjunto mínimo de bloques CIDR. Usa BigInt y se ejecuta en tu navegador.", keywords: ["calculadora cidr ipv6", "rango ipv6 cidr", "cidr a rango", "rango subred ipv6", "rango direcciones ipv6"], modeToRange: "CIDR → Rango", modeToCidr: "Rango → CIDR", cidrLabel: "Bloque CIDR", startLabel: "Dirección inicial", endLabel: "Dirección final", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Primera dirección", last: "Última dirección", count: "Recuento de direcciones", cidrBlocks: "Bloques CIDR", invalid: "Entrada no válida para el modo seleccionado." },
  it: { title: "Calcolatore di Intervallo CIDR IPv6", short: "Espandi un CIDR IPv6 nel suo intervallo di indirizzi o comprimi un intervallo in blocchi CIDR.", description: "Calcolatore di intervallo CIDR IPv6 gratuito. Espandi un CIDR come 2001:db8::/126 nel suo primo e ultimo indirizzo e conteggio totale, oppure converti un intervallo inizio–fine nell'insieme minimo di blocchi CIDR. Usa BigInt e funziona nel tuo browser.", keywords: ["calcolatore cidr ipv6", "intervallo ipv6 cidr", "cidr in intervallo", "intervallo subnet ipv6", "intervallo indirizzi ipv6"], modeToRange: "CIDR → Intervallo", modeToCidr: "Intervallo → CIDR", cidrLabel: "Blocco CIDR", startLabel: "Indirizzo iniziale", endLabel: "Indirizzo finale", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Primo indirizzo", last: "Ultimo indirizzo", count: "Conteggio indirizzi", cidrBlocks: "Blocchi CIDR", invalid: "Input non valido per la modalità selezionata." },
  ar: { title: "حاسبة نطاق CIDR لـ IPv6", short: "وسّع نطاق CIDR لـ IPv6 إلى مدى عناوينه، أو اجمع مدى في كتل CIDR.", description: "حاسبة نطاق CIDR لـ IPv6 مجانية. وسّع CIDR مثل 2001:db8::/126 إلى أول وآخر عنوان والعدد الإجمالي، أو حوّل مدى البداية–النهاية إلى أقل مجموعة من كتل CIDR. تستخدم BigInt وتعمل في متصفحك.", keywords: ["حاسبة cidr ipv6", "نطاق ipv6 cidr", "cidr إلى نطاق", "نطاق شبكة فرعية ipv6", "نطاق عناوين ipv6"], modeToRange: "CIDR ← المدى", modeToCidr: "المدى ← CIDR", cidrLabel: "كتلة CIDR", startLabel: "عنوان البداية", endLabel: "عنوان النهاية", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "أول عنوان", last: "آخر عنوان", count: "عدد العناوين", cidrBlocks: "كتل CIDR", invalid: "إدخال غير صالح للوضع المحدد." },
  ru: { title: "Калькулятор Диапазона CIDR IPv6", short: "Разверните IPv6 CIDR в диапазон адресов или сверните диапазон в блоки CIDR.", description: "Бесплатный калькулятор диапазона CIDR IPv6. Разверните CIDR вроде 2001:db8::/126 в первый и последний адрес и общее количество или преобразуйте диапазон начало–конец в минимальный набор блоков CIDR. Использует BigInt и работает в браузере.", keywords: ["калькулятор cidr ipv6", "диапазон ipv6 cidr", "cidr в диапазон", "диапазон подсети ipv6", "диапазон адресов ipv6"], modeToRange: "CIDR → Диапазон", modeToCidr: "Диапазон → CIDR", cidrLabel: "Блок CIDR", startLabel: "Начальный адрес", endLabel: "Конечный адрес", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "Первый адрес", last: "Последний адрес", count: "Количество адресов", cidrBlocks: "Блоки CIDR", invalid: "Недопустимый ввод для выбранного режима." },
  zh: { title: "IPv6 CIDR 范围计算器", short: "将 IPv6 CIDR 展开为地址范围，或将范围合并为 CIDR 块。", description: "免费的 IPv6 CIDR 范围计算器。将诸如 2001:db8::/126 的 CIDR 展开为首尾地址和总数，或将起始–结束范围转换为最小的 CIDR 块集合。使用 BigInt，在浏览器中运行。", keywords: ["ipv6 cidr 计算器", "ipv6 范围 cidr", "cidr 转范围", "ipv6 子网范围", "ipv6 地址范围"], modeToRange: "CIDR → 范围", modeToCidr: "范围 → CIDR", cidrLabel: "CIDR 块", startLabel: "起始地址", endLabel: "结束地址", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "首个地址", last: "末个地址", count: "地址数量", cidrBlocks: "CIDR 块", invalid: "对于所选模式无效的输入。" },
  ja: { title: "IPv6 CIDR 範囲計算ツール", short: "IPv6 の CIDR をアドレス範囲に展開、または範囲を CIDR ブロックにまとめます。", description: "無料の IPv6 CIDR 範囲計算ツール。2001:db8::/126 のような CIDR を最初と最後のアドレスおよび総数に展開したり、開始–終了の範囲を最小の CIDR ブロック集合に変換します。BigInt を使用し、ブラウザ内で動作します。", keywords: ["ipv6 cidr 計算", "ipv6 範囲 cidr", "cidr から範囲", "ipv6 サブネット範囲", "ipv6 アドレス範囲"], modeToRange: "CIDR → 範囲", modeToCidr: "範囲 → CIDR", cidrLabel: "CIDR ブロック", startLabel: "開始アドレス", endLabel: "終了アドレス", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "最初のアドレス", last: "最後のアドレス", count: "アドレス数", cidrBlocks: "CIDR ブロック", invalid: "選択したモードに対して無効な入力です。" },
  ko: { title: "IPv6 CIDR 범위 계산기", short: "IPv6 CIDR을 주소 범위로 확장하거나 범위를 CIDR 블록으로 축소합니다.", description: "무료 IPv6 CIDR 범위 계산기. 2001:db8::/126 같은 CIDR을 첫 번째와 마지막 주소 및 총 개수로 확장하거나, 시작–끝 범위를 최소 CIDR 블록 집합으로 변환합니다. BigInt를 사용하며 브라우저에서 실행됩니다.", keywords: ["ipv6 cidr 계산기", "ipv6 범위 cidr", "cidr에서 범위", "ipv6 서브넷 범위", "ipv6 주소 범위"], modeToRange: "CIDR → 범위", modeToCidr: "범위 → CIDR", cidrLabel: "CIDR 블록", startLabel: "시작 주소", endLabel: "끝 주소", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "첫 번째 주소", last: "마지막 주소", count: "주소 개수", cidrBlocks: "CIDR 블록", invalid: "선택한 모드에 유효하지 않은 입력입니다." },
  hi: { title: "IPv6 CIDR रेंज कैलकुलेटर", short: "IPv6 CIDR को उसके पता रेंज में विस्तृत करें, या रेंज को CIDR ब्लॉकों में संकुचित करें।", description: "मुफ्त IPv6 CIDR रेंज कैलकुलेटर। 2001:db8::/126 जैसे CIDR को उसके पहले और अंतिम पते और कुल गणना में विस्तृत करें, या आरंभ–अंत रेंज को न्यूनतम CIDR ब्लॉकों के सेट में बदलें। BigInt का उपयोग करता है और आपके ब्राउज़र में चलता है।", keywords: ["ipv6 cidr कैलकुलेटर", "ipv6 रेंज cidr", "cidr से रेंज", "ipv6 सबनेट रेंज", "ipv6 पता रेंज"], modeToRange: "CIDR → रेंज", modeToCidr: "रेंज → CIDR", cidrLabel: "CIDR ब्लॉक", startLabel: "आरंभिक पता", endLabel: "अंतिम पता", cidrPlaceholder: "2001:db8::/126", startPlaceholder: "2001:db8::", endPlaceholder: "2001:db8::3", first: "पहला पता", last: "अंतिम पता", count: "पता गणना", cidrBlocks: "CIDR ब्लॉक", invalid: "चयनित मोड के लिए अमान्य इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
