import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JSON to CSV Converter", short: "Convert a JSON array of objects to CSV.", description: "Free JSON-to-CSV converter. Paste a JSON array of objects to get CSV with a header row of all keys and properly quoted values. Great for exporting data to spreadsheets. Runs in your browser.", keywords: ["json to csv", "convert json to csv", "json csv converter", "export json to spreadsheet", "json to excel"], placeholder: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]', invalid: "Enter a JSON array of objects." },
  nl: { title: "JSON to CSV Converteerer", short: "Converteer a JSON array of objects to CSV.", description: "Gratis JSON-to-CSV converteerer. Paste a JSON array of objects to get CSV with a header row of all keys and properly quoted values. Great for exporting data to spreadsheets. Runs in uw browser.", keywords: ["json to csv", "converteer json to csv", "json csv converteerer", "export json to spreadsheet", "json to excel"], placeholder: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]', invalid: "Enter a JSON array of objects." },

  pl: { title: "JSON to CSV Konwerter", short: "Konwertuj a JSON array of objects to CSV.", description: "Darmowy JSON-to-CSV konwerter. Paste a JSON array of objects to get CSV with a header row of all keys and properly quoted values. Great for exporting data to spreadsheets. Runs w Twojej przeglądarce.", keywords: ["json to csv", "konwertuj json to csv", "json csv konwerter", "export json to spreadsheet", "json to excel"], placeholder: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]', invalid: "Enter a JSON array of objects." },
  pt: { title: "Conversor de JSON to CSV", short: "Converter a JSON array de objects para CSV.", description: "Gratuito - JSON-para-CSV converter. Paste a JSON array de objects para get CSV com a header row de all keys e properly quoted values. Great para exporting data para spreadsheets. Runs no seu navegador.", keywords: ["json to csv", "convert json to csv", "json csv converter", "export json to spreadsheet", "json to excel"], placeholder: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]', invalid: "Enter a JSON array of objects." },
  id: { title: "Konverter JSON to CSV", short: "Konversi a JSON array dari objects to CSV.", description: "Gratis - JSON-to-CSV converter. Paste a JSON array dari objects to get CSV with a header row dari all keys dan properly quoted values. Great for exporting data to spreadsheets. Runs di browser Anda.", keywords: ["json to csv", "convert json to csv", "json csv converter", "export json to spreadsheet", "json to excel"], placeholder: '[{"name":"Alice","age":30},{"name":"Bob","age":25}]', invalid: "Enter a JSON array of objects." },

  tr: { title: "JSON'dan CSV'ye Dönüştürücü", short: "Bir JSON nesne dizisini CSV'ye dönüştürün.", description: "Ücretsiz JSON'dan CSV'ye dönüştürücü. Bir JSON nesne dizisi yapıştırın; tüm anahtarlardan oluşan başlık satırı ve düzgün tırnaklanmış değerlerle CSV alın. Verileri elektronik tablolara aktarmak için harika. Tarayıcınızda çalışır.", keywords: ["json'dan csv'ye", "json csv dönüştür", "json csv dönüştürücü", "json'u tabloya aktar"], placeholder: '[{"ad":"Ali","yas":30},{"ad":"Veli","yas":25}]', invalid: "Bir JSON nesne dizisi girin." },
  de: { title: "JSON-zu-CSV-Konverter", short: "Konvertieren Sie ein JSON-Array von Objekten in CSV.", description: "Kostenloser JSON-zu-CSV-Konverter. Fügen Sie ein JSON-Array von Objekten ein und erhalten Sie CSV mit einer Kopfzeile aller Schlüssel und korrekt zitierten Werten. Ideal zum Export in Tabellen.", keywords: ["json zu csv", "json in csv konvertieren", "json csv konverter", "json in tabelle"], placeholder: '[{"name":"Alice","alter":30},{"name":"Bob","alter":25}]', invalid: "Geben Sie ein JSON-Array von Objekten ein." },
  fr: { title: "Convertisseur JSON vers CSV", short: "Convertissez un tableau JSON d'objets en CSV.", description: "Convertisseur JSON-vers-CSV gratuit. Collez un tableau JSON d'objets pour obtenir un CSV avec une ligne d'en-tête de toutes les clés et des valeurs correctement entre guillemets. Idéal pour exporter vers un tableur.", keywords: ["json vers csv", "convertir json en csv", "convertisseur json csv", "exporter json tableur"], placeholder: '[{"nom":"Alice","age":30},{"nom":"Bob","age":25}]', invalid: "Saisissez un tableau JSON d'objets." },
  es: { title: "Convertidor de JSON a CSV", short: "Convierte un array JSON de objetos a CSV.", description: "Convertidor JSON-a-CSV gratuito. Pega un array JSON de objetos para obtener CSV con una fila de encabezado de todas las claves y valores entrecomillados correctamente. Ideal para exportar a hojas de cálculo.", keywords: ["json a csv", "convertir json a csv", "convertidor json csv", "exportar json a hoja de cálculo"], placeholder: '[{"nombre":"Alicia","edad":30},{"nombre":"Bob","edad":25}]', invalid: "Introduce un array JSON de objetos." },
  it: { title: "Convertitore da JSON a CSV", short: "Converti un array JSON di oggetti in CSV.", description: "Convertitore JSON-a-CSV gratuito. Incolla un array JSON di oggetti per ottenere CSV con una riga di intestazione di tutte le chiavi e valori correttamente tra virgolette. Ottimo per esportare in fogli di calcolo.", keywords: ["json a csv", "convertire json in csv", "convertitore json csv", "esporta json foglio di calcolo"], placeholder: '[{"nome":"Alice","eta":30},{"nome":"Bob","eta":25}]', invalid: "Inserisci un array JSON di oggetti." },
  ar: { title: "محوّل JSON إلى CSV", short: "حوّل مصفوفة JSON من الكائنات إلى CSV.", description: "محوّل JSON إلى CSV مجاني. الصق مصفوفة JSON من الكائنات للحصول على CSV مع صف رأس بكل المفاتيح وقيم مقتبسة بشكل صحيح. رائع لتصدير البيانات إلى جداول البيانات. يعمل في متصفحك.", keywords: ["json إلى csv", "تحويل json إلى csv", "محول json csv", "تصدير json إلى جدول"], placeholder: '[{"الاسم":"علي","العمر":30}]', invalid: "أدخل مصفوفة JSON من الكائنات." },
  ru: { title: "Конвертер JSON в CSV", short: "Преобразуйте JSON-массив объектов в CSV.", description: "Бесплатный конвертер JSON в CSV. Вставьте JSON-массив объектов, чтобы получить CSV со строкой заголовка из всех ключей и корректно экранированными значениями. Отлично для экспорта в таблицы.", keywords: ["json в csv", "преобразовать json в csv", "конвертер json csv", "экспорт json в таблицу"], placeholder: '[{"имя":"Алиса","возраст":30}]', invalid: "Введите JSON-массив объектов." },
  zh: { title: "JSON 转 CSV 转换器", short: "将 JSON 对象数组转换为 CSV。", description: "免费的 JSON 转 CSV 转换器。粘贴 JSON 对象数组，即可得到带有所有键的表头行和正确引用值的 CSV。适合将数据导出到电子表格。在浏览器中运行。", keywords: ["json转csv", "json转csv转换", "json csv转换器", "导出json到表格"], placeholder: '[{"name":"Alice","age":30}]', invalid: "请输入 JSON 对象数组。" },
  ja: { title: "JSON → CSV 変換", short: "オブジェクトの JSON 配列を CSV に変換します。", description: "無料の JSON→CSV 変換ツール。オブジェクトの JSON 配列を貼り付けると、全キーのヘッダー行と適切に引用された値を持つ CSV が得られます。スプレッドシートへのエクスポートに最適。ブラウザ内で動作します。", keywords: ["json csv 変換", "json を csv に", "json csv コンバーター", "json スプレッドシート 出力"], placeholder: '[{"name":"Alice","age":30}]', invalid: "オブジェクトの JSON 配列を入力してください。" },
  ko: { title: "JSON → CSV 변환기", short: "객체의 JSON 배열을 CSV로 변환합니다.", description: "무료 JSON→CSV 변환기. 객체의 JSON 배열을 붙여넣으면 모든 키의 헤더 행과 올바르게 따옴표 처리된 값을 가진 CSV를 얻습니다. 스프레드시트로 내보내기에 적합합니다. 브라우저에서 실행됩니다.", keywords: ["json csv 변환", "json을 csv로", "json csv 변환기", "json 스프레드시트 내보내기"], placeholder: '[{"name":"Alice","age":30}]', invalid: "객체의 JSON 배열을 입력하세요." },
  hi: { title: "JSON से CSV कन्वर्टर", short: "ऑब्जेक्ट की JSON सरणी को CSV में बदलें।", description: "मुफ्त JSON-से-CSV कन्वर्टर। ऑब्जेक्ट की JSON सरणी पेस्ट करें और सभी कुंजियों की हेडर पंक्ति तथा सही ढंग से उद्धृत मानों वाला CSV पाएं। डेटा को स्प्रेडशीट में निर्यात करने के लिए बढ़िया। ब्राउज़र में चलता है।", keywords: ["json से csv", "json को csv में बदलें", "json csv कन्वर्टर", "json स्प्रेडशीट निर्यात"], placeholder: '[{"name":"Alice","age":30}]', invalid: "ऑब्जेक्ट की JSON सरणी दर्ज करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
