import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Flexbox Generator", short: "Build a CSS flex container with a live preview.", description: "Free CSS Flexbox playground. Pick direction, wrap, justify-content, align-items and gap — see the layout update live and copy the CSS.", keywords: ["css flexbox generator", "flex container builder", "css flex layout", "justify content generator", "align items generator"], direction: "Direction", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Gap (px)", preview: "Preview" },
  tr: { title: "CSS Flexbox Oluşturucu", short: "Canlı önizlemeyle bir CSS flex kapsayıcı oluşturun.", description: "Ücretsiz CSS Flexbox oyun alanı. Yön, wrap, justify-content, align-items ve aralık seçin — düzeni canlı olarak güncellenirken görün ve CSS'i kopyalayın.", keywords: ["css flexbox oluşturucu", "flex kapsayıcı oluşturucu", "css flex düzen", "justify content oluşturucu", "align items oluşturucu"], direction: "Yön", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Aralık (px)", preview: "Önizleme" },
  de: { title: "CSS-Flexbox-Generator", short: "Erstellen Sie einen CSS-Flex-Container mit Live-Vorschau.", description: "Kostenloses CSS-Flexbox-Spielfeld. Wählen Sie Richtung, Wrap, justify-content, align-items und Gap — sehen Sie das Layout live aktualisiert und kopieren Sie das CSS.", keywords: ["css flexbox generator", "flex container builder", "css flex layout", "justify content generator", "align items generator"], direction: "Richtung", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Abstand (px)", preview: "Vorschau" },
  fr: { title: "Générateur CSS Flexbox", short: "Construisez un conteneur flex CSS avec aperçu en direct.", description: "Aire de jeu CSS Flexbox gratuite. Choisissez direction, wrap, justify-content, align-items et gap — voyez la mise en page se mettre à jour en direct et copiez le CSS.", keywords: ["générateur css flexbox", "constructeur flex container", "mise en page css flex", "générateur justify content", "générateur align items"], direction: "Direction", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Espacement (px)", preview: "Aperçu" },
  es: { title: "Generador CSS Flexbox", short: "Crea un contenedor flex CSS con vista previa en vivo.", description: "Patio de juegos CSS Flexbox gratuito. Elige dirección, wrap, justify-content, align-items y gap — ve el diseño actualizarse en vivo y copia el CSS.", keywords: ["generador css flexbox", "constructor flex container", "diseño css flex", "generador justify content", "generador align items"], direction: "Dirección", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Espacio (px)", preview: "Vista previa" },
  it: { title: "Generatore CSS Flexbox", short: "Crea un contenitore flex CSS con anteprima dal vivo.", description: "Playground CSS Flexbox gratuito. Scegli direzione, wrap, justify-content, align-items e gap — vedi il layout aggiornarsi dal vivo e copia il CSS.", keywords: ["generatore css flexbox", "costruttore flex container", "layout css flex", "generatore justify content", "generatore align items"], direction: "Direzione", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Gap (px)", preview: "Anteprima" },
  ar: { title: "مولّد CSS Flexbox", short: "أنشئ حاوية flex CSS مع معاينة حية.", description: "ساحة لعب CSS Flexbox مجانية. اختر الاتجاه و wrap و justify-content و align-items و gap — شاهد التخطيط يتم تحديثه مباشرة وانسخ CSS.", keywords: ["مولد css flexbox", "منشئ حاوية flex", "تخطيط css flex", "مولد justify content", "مولد align items"], direction: "الاتجاه", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "الفجوة (px)", preview: "معاينة" },
  ru: { title: "Генератор CSS Flexbox", short: "Создайте flex-контейнер CSS с живым превью.", description: "Бесплатная песочница CSS Flexbox. Выберите направление, wrap, justify-content, align-items и gap — смотрите, как макет обновляется вживую, и копируйте CSS.", keywords: ["генератор css flexbox", "конструктор flex container", "css flex layout", "генератор justify content", "генератор align items"], direction: "Направление", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "Gap (px)", preview: "Превью" },
  zh: { title: "CSS Flexbox 生成器", short: "构建带实时预览的 CSS flex 容器。", description: "免费的 CSS Flexbox 游乐场。选择方向、wrap、justify-content、align-items 和 gap——实时查看布局并复制 CSS。", keywords: ["css flexbox 生成器", "flex 容器构建器", "css flex 布局", "justify content 生成器", "align items 生成器"], direction: "方向", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "间距 (px)", preview: "预览" },
  ja: { title: "CSS Flexbox ジェネレーター", short: "ライブプレビュー付きで CSS flex コンテナを構築。", description: "無料の CSS Flexbox プレイグラウンド。方向、wrap、justify-content、align-items、gap を選んで——レイアウトがライブで更新されるのを見て CSS をコピーできます。", keywords: ["css flexbox ジェネレーター", "flex コンテナ ビルダー", "css flex レイアウト", "justify content ジェネレーター", "align items ジェネレーター"], direction: "方向", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "ギャップ (px)", preview: "プレビュー" },
  ko: { title: "CSS Flexbox 생성기", short: "실시간 미리보기로 CSS flex 컨테이너를 만듭니다.", description: "무료 CSS Flexbox 플레이그라운드. 방향, wrap, justify-content, align-items, gap을 선택해 레이아웃이 실시간으로 업데이트되는 것을 보고 CSS를 복사하세요.", keywords: ["css flexbox 생성기", "flex 컨테이너 빌더", "css flex 레이아웃", "justify content 생성기", "align items 생성기"], direction: "방향", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "간격 (px)", preview: "미리보기" },
  hi: { title: "CSS Flexbox जनरेटर", short: "लाइव प्रीव्यू के साथ एक CSS flex कंटेनर बनाएं।", description: "मुफ्त CSS Flexbox प्लेग्राउंड। दिशा, wrap, justify-content, align-items और gap चुनें — लेआउट को लाइव अपडेट होते देखें और CSS कॉपी करें।", keywords: ["css flexbox जनरेटर", "flex कंटेनर बिल्डर", "css flex लेआउट", "justify content जनरेटर", "align items जनरेटर"], direction: "दिशा", wrap: "Wrap", justify: "Justify content", align: "Align items", gap: "अंतर (px)", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
