import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image Compressor", short: "Compress JPG, PNG or WebP images in your browser.", description: "Free image compressor. Drop a JPG, PNG or WebP image and re-encode it as JPEG or WebP at a configurable quality to shrink the file — runs entirely in your browser, nothing uploaded.", keywords: ["image compressor", "compress jpg", "compress webp", "shrink image online", "reduce image size"], drop: "Drop an image here or click to choose", format: "Output format", quality: "Quality", originalSize: "Original", compressedSize: "Compressed", reduction: "Reduction", download: "Download" },
  pt: { title: "Compressor de Image", short: "Compress JPG, PNG ou WebP images no seu navegador.", description: "Gratuito - image compressor. Drop a JPG, PNG ou WebP image e re-codificar it as JPEG ou WebP at a configurable quality para shrink the file â runs entirely no seu navegador, nothing uploaded.", keywords: ["image compressor", "compress jpg", "compress webp", "shrink image online", "reduce image size"], drop: "Drop an image here or click to choose", format: "Output format", quality: "Quality", originalSize: "Original", compressedSize: "Compressed", reduction: "Reduction", download: "Download" },
  id: { title: "Kompresor Image", short: "Compress JPG, PNG atau WebP images di browser Anda.", description: "Gratis - image compressor. Drop a JPG, PNG atau WebP image dan re-enkode it as JPEG atau WebP at a configurable quality to shrink the file â runs entirely di browser Anda, nothing uploaded.", keywords: ["image compressor", "compress jpg", "compress webp", "shrink image online", "reduce image size"], drop: "Drop an image here or click to choose", format: "Output format", quality: "Quality", originalSize: "Original", compressedSize: "Compressed", reduction: "Reduction", download: "Download" },

  tr: { title: "Görsel Sıkıştırıcı", short: "JPG, PNG veya WebP görsellerini tarayıcınızda sıkıştırın.", description: "Ücretsiz görsel sıkıştırıcı. Bir JPG, PNG veya WebP görseli bırakın ve dosyayı küçültmek için yapılandırılabilir kalitede JPEG veya WebP olarak yeniden kodlayın — tamamen tarayıcınızda çalışır, hiçbir şey yüklenmez.", keywords: ["görsel sıkıştırıcı", "jpg sıkıştır", "webp sıkıştır", "görsel küçültme online", "görsel boyutunu azalt"], drop: "Bir görsel bırakın veya seçmek için tıklayın", format: "Çıktı formatı", quality: "Kalite", originalSize: "Orijinal", compressedSize: "Sıkıştırılmış", reduction: "Azalma", download: "İndir" },
  de: { title: "Bildkompressor", short: "Komprimieren Sie JPG-, PNG- oder WebP-Bilder im Browser.", description: "Kostenloser Bildkompressor. Legen Sie ein JPG-, PNG- oder WebP-Bild ab und kodieren Sie es als JPEG oder WebP mit konfigurierbarer Qualität neu, um die Datei zu verkleinern — läuft vollständig im Browser, nichts wird hochgeladen.", keywords: ["bildkompressor", "jpg komprimieren", "webp komprimieren", "bild verkleinern online", "bildgröße reduzieren"], drop: "Bild hier ablegen oder klicken zum Auswählen", format: "Ausgabeformat", quality: "Qualität", originalSize: "Original", compressedSize: "Komprimiert", reduction: "Reduktion", download: "Herunterladen" },
  fr: { title: "Compresseur d'Image", short: "Compressez les images JPG, PNG ou WebP dans votre navigateur.", description: "Compresseur d'image gratuit. Déposez une image JPG, PNG ou WebP et ré-encodez-la en JPEG ou WebP avec qualité configurable pour réduire la taille du fichier — fonctionne entièrement dans votre navigateur, rien n'est envoyé.", keywords: ["compresseur image", "compresser jpg", "compresser webp", "réduire image en ligne", "réduire taille image"], drop: "Déposez une image ici ou cliquez pour choisir", format: "Format de sortie", quality: "Qualité", originalSize: "Original", compressedSize: "Compressé", reduction: "Réduction", download: "Télécharger" },
  es: { title: "Compresor de Imágenes", short: "Comprime imágenes JPG, PNG o WebP en tu navegador.", description: "Compresor de imágenes gratuito. Arrastra una imagen JPG, PNG o WebP y vuelve a codificarla como JPEG o WebP con calidad configurable para reducir el archivo — funciona completamente en tu navegador, nada se sube.", keywords: ["compresor imagen", "comprimir jpg", "comprimir webp", "reducir imagen online", "reducir tamaño imagen"], drop: "Arrastra una imagen aquí o haz clic para elegir", format: "Formato de salida", quality: "Calidad", originalSize: "Original", compressedSize: "Comprimido", reduction: "Reducción", download: "Descargar" },
  it: { title: "Compressore di Immagini", short: "Comprimi immagini JPG, PNG o WebP nel browser.", description: "Compressore di immagini gratuito. Trascina un'immagine JPG, PNG o WebP e ricodificala come JPEG o WebP con qualità configurabile per ridurre la dimensione — funziona interamente nel browser, nulla viene caricato.", keywords: ["compressore immagine", "comprimi jpg", "comprimi webp", "ridurre immagine online", "ridurre dimensione immagine"], drop: "Trascina un'immagine qui o clicca per scegliere", format: "Formato di output", quality: "Qualità", originalSize: "Originale", compressedSize: "Compresso", reduction: "Riduzione", download: "Scarica" },
  ar: { title: "ضاغط الصور", short: "اضغط صور JPG أو PNG أو WebP في متصفحك.", description: "ضاغط صور مجاني. أفلِت صورة JPG أو PNG أو WebP وأعد ترميزها كـ JPEG أو WebP بجودة قابلة للتخصيص لتقليل حجم الملف — يعمل بالكامل في متصفحك، لا شيء يُرفع.", keywords: ["ضاغط الصور", "ضغط jpg", "ضغط webp", "تقليل حجم الصورة عبر الإنترنت", "تقليل حجم الصورة"], drop: "أفلِت صورة هنا أو انقر للاختيار", format: "تنسيق الإخراج", quality: "الجودة", originalSize: "الأصلي", compressedSize: "المضغوط", reduction: "التقليل", download: "تنزيل" },
  ru: { title: "Сжатие изображений", short: "Сжимайте JPG, PNG или WebP изображения в браузере.", description: "Бесплатный компрессор изображений. Перетащите JPG, PNG или WebP и перекодируйте его в JPEG или WebP с настраиваемым качеством, чтобы уменьшить файл — работает полностью в браузере, ничего не загружается.", keywords: ["компрессор изображений", "сжать jpg", "сжать webp", "уменьшить изображение онлайн", "уменьшить размер изображения"], drop: "Перетащите изображение сюда или нажмите для выбора", format: "Формат вывода", quality: "Качество", originalSize: "Оригинал", compressedSize: "Сжатый", reduction: "Сокращение", download: "Скачать" },
  zh: { title: "图片压缩器", short: "在浏览器中压缩 JPG、PNG 或 WebP 图片。", description: "免费的图片压缩器。拖入 JPG、PNG 或 WebP 图片，并以可配置的质量重新编码为 JPEG 或 WebP 以缩小文件——完全在浏览器中运行，不上传任何内容。", keywords: ["图片压缩器", "压缩 jpg", "压缩 webp", "在线缩小图片", "减小图片大小"], drop: "将图片拖到此处或点击选择", format: "输出格式", quality: "质量", originalSize: "原始", compressedSize: "压缩后", reduction: "缩减", download: "下载" },
  ja: { title: "画像圧縮", short: "JPG、PNG、WebP 画像をブラウザで圧縮。", description: "無料の画像圧縮ツール。JPG、PNG、WebP 画像をドロップし、設定可能な品質で JPEG または WebP に再エンコードしてファイルを縮小します——すべてブラウザ内で動作、アップロードなし。", keywords: ["画像 圧縮", "jpg 圧縮", "webp 圧縮", "画像 縮小 オンライン", "画像 サイズ 削減"], drop: "画像をここにドロップまたはクリックして選択", format: "出力形式", quality: "品質", originalSize: "オリジナル", compressedSize: "圧縮", reduction: "削減", download: "ダウンロード" },
  ko: { title: "이미지 압축기", short: "브라우저에서 JPG, PNG, WebP 이미지를 압축합니다.", description: "무료 이미지 압축기. JPG, PNG, WebP 이미지를 드롭하고 구성 가능한 품질로 JPEG 또는 WebP로 재인코딩하여 파일을 축소합니다 — 모두 브라우저에서 실행, 업로드 없음.", keywords: ["이미지 압축기", "jpg 압축", "webp 압축", "이미지 축소 온라인", "이미지 크기 줄이기"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", format: "출력 형식", quality: "품질", originalSize: "원본", compressedSize: "압축됨", reduction: "감소", download: "다운로드" },
  hi: { title: "इमेज कंप्रेसर", short: "अपने ब्राउज़र में JPG, PNG या WebP इमेज को संपीड़ित करें।", description: "मुफ्त इमेज कंप्रेसर। एक JPG, PNG या WebP इमेज छोड़ें और फ़ाइल को छोटा करने के लिए कॉन्फ़िगर करने योग्य गुणवत्ता पर JPEG या WebP के रूप में फिर से एन्कोड करें — पूरी तरह आपके ब्राउज़र में चलता है, कुछ भी अपलोड नहीं होता।", keywords: ["इमेज कंप्रेसर", "jpg संपीड़ित", "webp संपीड़ित", "ऑनलाइन इमेज छोटी करें", "इमेज आकार घटाएं"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", format: "आउटपुट प्रारूप", quality: "गुणवत्ता", originalSize: "मूल", compressedSize: "संपीड़ित", reduction: "कमी", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
