import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Favicon Generator", short: "Generate multi-size PNG favicons from a single image.", description: "Free favicon generator. Drop a square logo or icon and download a complete PNG favicon set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus the matching HTML link tags and manifest — runs entirely in your browser.", keywords: ["favicon generator", "create favicon", "favicon png", "apple touch icon", "site favicon"], drop: "Drop an image here or click to choose", siteName: "Site name", html: "HTML", manifest: "Manifest", sizes: "Sizes", download: "Download" },
  nl: { title: "Favicon Generator", short: "Genereer multi-grootte PNG favicons from a single afbeelding.", description: "Gratis favicon generator. Drop a square logo or icon and download a complete PNG favicon set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus the matching HTML link tags and manifest — runs entirely in uw browser.", keywords: ["favicon generator", "maak aan favicon", "favicon png", "apple touch icon", "site favicon"], drop: "Drop an afbeelding here or click to choose", siteName: "Site name", html: "HTML", manifest: "Manifest", sizes: "Groottes", download: "Download" },

  pl: { title: "Favicon Generator", short: "Generuj multi-rozmiar PNG favicons from a single obraz.", description: "Darmowy favicon generator. Drop a square logo or icon and download a complete PNG favicon set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus the matching HTML link tags and manifest — runs entirely w Twojej przeglądarce.", keywords: ["favicon generator", "utwórz favicon", "favicon png", "apple touch icon", "site favicon"], drop: "Drop an obraz here or click to choose", siteName: "Site name", html: "HTML", manifest: "Manifest", sizes: "Rozmiars", download: "Download" },
  pt: { title: "Gerador de Favicon", short: "Gerar multi-size PNG favicons a partir de a single image.", description: "Gratuito - favicon generator. Drop a square logo ou icon e descarregar a complete PNG favicon set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus the matching HTML link tags e manifest â runs entirely no seu navegador.", keywords: ["favicon generator", "create favicon", "favicon png", "apple touch icon", "site favicon"], drop: "Drop an image here or click to choose", siteName: "Site name", html: "HTML", manifest: "Manifest", sizes: "Sizes", download: "Download" },
  id: { title: "Generator Favicon", short: "Hasilkan multi-size PNG favicons from a single image.", description: "Gratis - favicon generator. Drop a square logo atau icon dan unduh a complete PNG favicon set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus the matching HTML link tags dan manifest â runs entirely di browser Anda.", keywords: ["favicon generator", "create favicon", "favicon png", "apple touch icon", "site favicon"], drop: "Drop an image here or click to choose", siteName: "Site name", html: "HTML", manifest: "Manifest", sizes: "Sizes", download: "Download" },

  tr: { title: "Favicon Oluşturucu", short: "Tek bir görselden çoklu boyutta PNG faviconlar oluşturun.", description: "Ücretsiz favicon oluşturucu. Kare bir logo veya simge bırakın ve eksiksiz bir PNG favicon seti (16, 32, 48, 96, 128, 180, 192, 256, 512) ile uygun HTML link etiketleri ve manifest indirin — tamamen tarayıcınızda çalışır.", keywords: ["favicon oluşturucu", "favicon oluştur", "favicon png", "apple touch icon", "site favicon"], drop: "Bir görsel bırakın veya seçmek için tıklayın", siteName: "Site adı", html: "HTML", manifest: "Manifest", sizes: "Boyutlar", download: "İndir" },
  de: { title: "Favicon-Generator", short: "Erzeugen Sie PNG-Favicons in mehreren Größen aus einem Bild.", description: "Kostenloser Favicon-Generator. Legen Sie ein quadratisches Logo oder Icon ab und laden Sie ein komplettes PNG-Favicon-Set (16, 32, 48, 96, 128, 180, 192, 256, 512) plus die passenden HTML-Link-Tags und Manifest herunter — läuft vollständig im Browser.", keywords: ["favicon generator", "favicon erstellen", "favicon png", "apple touch icon", "site favicon"], drop: "Bild hier ablegen oder klicken zum Auswählen", siteName: "Site-Name", html: "HTML", manifest: "Manifest", sizes: "Größen", download: "Herunterladen" },
  fr: { title: "Générateur de Favicon", short: "Générez des favicons PNG multi-tailles à partir d'une seule image.", description: "Générateur de favicon gratuit. Déposez un logo ou une icône carrée et téléchargez un set PNG favicon complet (16, 32, 48, 96, 128, 180, 192, 256, 512) plus les balises HTML link correspondantes et le manifest — fonctionne entièrement dans votre navigateur.", keywords: ["générateur favicon", "créer favicon", "favicon png", "apple touch icon", "favicon site"], drop: "Déposez une image ici ou cliquez pour choisir", siteName: "Nom du site", html: "HTML", manifest: "Manifest", sizes: "Tailles", download: "Télécharger" },
  es: { title: "Generador de Favicon", short: "Genera favicons PNG multi-tamaño desde una sola imagen.", description: "Generador de favicon gratuito. Arrastra un logo o icono cuadrado y descarga un set PNG favicon completo (16, 32, 48, 96, 128, 180, 192, 256, 512) más las etiquetas HTML link correspondientes y manifest — funciona completamente en tu navegador.", keywords: ["generador favicon", "crear favicon", "favicon png", "apple touch icon", "favicon sitio"], drop: "Arrastra una imagen aquí o haz clic para elegir", siteName: "Nombre del sitio", html: "HTML", manifest: "Manifest", sizes: "Tamaños", download: "Descargar" },
  it: { title: "Generatore di Favicon", short: "Genera favicon PNG multi-dimensione da un'unica immagine.", description: "Generatore di favicon gratuito. Trascina un logo o un'icona quadrata e scarica un set PNG favicon completo (16, 32, 48, 96, 128, 180, 192, 256, 512) più i tag HTML link e il manifest corrispondenti — funziona interamente nel browser.", keywords: ["generatore favicon", "creare favicon", "favicon png", "apple touch icon", "favicon sito"], drop: "Trascina un'immagine qui o clicca per scegliere", siteName: "Nome sito", html: "HTML", manifest: "Manifest", sizes: "Dimensioni", download: "Scarica" },
  ar: { title: "مولّد Favicon", short: "أنشئ favicon بصيغة PNG بأحجام متعددة من صورة واحدة.", description: "مولّد favicon مجاني. أفلِت شعارًا أو أيقونة مربعة وقم بتنزيل مجموعة favicon PNG كاملة (16، 32، 48، 96، 128، 180، 192، 256، 512) بالإضافة إلى علامات HTML link المطابقة و manifest — يعمل بالكامل في متصفحك.", keywords: ["مولد favicon", "إنشاء favicon", "favicon png", "apple touch icon", "favicon الموقع"], drop: "أفلِت صورة هنا أو انقر للاختيار", siteName: "اسم الموقع", html: "HTML", manifest: "Manifest", sizes: "الأحجام", download: "تنزيل" },
  ru: { title: "Генератор Favicon", short: "Создавайте PNG-favicon разных размеров из одной картинки.", description: "Бесплатный генератор favicon. Перетащите квадратный логотип или значок и скачайте полный набор PNG-favicon (16, 32, 48, 96, 128, 180, 192, 256, 512) плюс соответствующие HTML link-теги и manifest — работает полностью в браузере.", keywords: ["генератор favicon", "создать favicon", "favicon png", "apple touch icon", "favicon сайта"], drop: "Перетащите изображение сюда или нажмите для выбора", siteName: "Имя сайта", html: "HTML", manifest: "Manifest", sizes: "Размеры", download: "Скачать" },
  zh: { title: "Favicon 生成器", short: "从单张图片生成多尺寸 PNG favicon。", description: "免费的 favicon 生成器。拖入方形 logo 或图标，下载完整的 PNG favicon 集（16、32、48、96、128、180、192、256、512）以及匹配的 HTML link 标签和 manifest——完全在浏览器中运行。", keywords: ["favicon 生成器", "创建 favicon", "favicon png", "apple touch icon", "网站 favicon"], drop: "将图片拖到此处或点击选择", siteName: "站点名称", html: "HTML", manifest: "Manifest", sizes: "尺寸", download: "下载" },
  ja: { title: "Favicon 生成", short: "1 枚の画像からマルチサイズの PNG favicon を生成。", description: "無料の favicon 生成ツール。正方形のロゴやアイコンをドロップし、完全な PNG favicon セット（16、32、48、96、128、180、192、256、512）と対応する HTML link タグ、manifest をダウンロード——すべてブラウザ内で動作します。", keywords: ["favicon 生成", "favicon 作成", "favicon png", "apple touch icon", "サイト favicon"], drop: "画像をここにドロップまたはクリックして選択", siteName: "サイト名", html: "HTML", manifest: "Manifest", sizes: "サイズ", download: "ダウンロード" },
  ko: { title: "Favicon 생성기", short: "단일 이미지에서 멀티 사이즈 PNG favicon을 생성합니다.", description: "무료 favicon 생성기. 정사각형 로고나 아이콘을 드롭하고 완전한 PNG favicon 세트(16, 32, 48, 96, 128, 180, 192, 256, 512)와 일치하는 HTML link 태그 및 manifest를 다운로드하세요 — 모두 브라우저에서 실행됩니다.", keywords: ["favicon 생성기", "favicon 만들기", "favicon png", "apple touch icon", "사이트 favicon"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", siteName: "사이트 이름", html: "HTML", manifest: "Manifest", sizes: "크기", download: "다운로드" },
  hi: { title: "Favicon जनरेटर", short: "एक छवि से बहु-आकार PNG favicon बनाएं।", description: "मुफ्त favicon जनरेटर। एक चौकोर लोगो या आइकन छोड़ें और एक पूर्ण PNG favicon सेट (16, 32, 48, 96, 128, 180, 192, 256, 512) और मेल खाने वाले HTML link टैग व manifest डाउनलोड करें — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["favicon जनरेटर", "favicon बनाएं", "favicon png", "apple touch icon", "साइट favicon"], drop: "यहाँ एक छवि छोड़ें या चुनने के लिए क्लिक करें", siteName: "साइट नाम", html: "HTML", manifest: "Manifest", sizes: "आकार", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
