import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Vigenère Cipher", short: "Encode and decode with a polyalphabetic keyword cipher.", description: "Free Vigenère cipher tool. Provide a keyword and a message — encode or decode using the classic polyalphabetic shift. Non-letter characters pass through unchanged.", keywords: ["vigenere cipher", "vigenere decoder", "vigenere encoder", "polyalphabetic cipher", "keyword cipher"], encode: "Encode", decode: "Decode", key: "Keyword", input: "Text", output: "Result" },
  pt: { title: "Vigenère Cipher", short: "Encode and decode with a polyalphabetic keyword cipher.", description: "Free Vigenère cipher tool. Provide a keyword and a message — encode or decode using the classic polyalphabetic shift. Non-letter characters pass through unchanged.", keywords: ["vigenere cipher", "vigenere decoder", "vigenere encoder", "polyalphabetic cipher", "keyword cipher"], encode: "Encode", decode: "Decode", key: "Keyword", input: "Text", output: "Result" },
  id: { title: "Vigenère Cipher", short: "Encode and decode with a polyalphabetic keyword cipher.", description: "Free Vigenère cipher tool. Provide a keyword and a message — encode or decode using the classic polyalphabetic shift. Non-letter characters pass through unchanged.", keywords: ["vigenere cipher", "vigenere decoder", "vigenere encoder", "polyalphabetic cipher", "keyword cipher"], encode: "Encode", decode: "Decode", key: "Keyword", input: "Text", output: "Result" },

  tr: { title: "Vigenère Şifresi", short: "Çok-alfabeli anahtar kelime şifresiyle kodlayın ve çözün.", description: "Ücretsiz Vigenère şifre aracı. Bir anahtar kelime ve mesaj sağlayın — klasik çok-alfabeli kayma ile kodlayın veya çözün. Harf dışı karakterler değişmeden geçer.", keywords: ["vigenere şifresi", "vigenere çözücü", "vigenere kodlayıcı", "çok-alfabeli şifre", "anahtar kelime şifresi"], encode: "Kodla", decode: "Çöz", key: "Anahtar kelime", input: "Metin", output: "Sonuç" },
  de: { title: "Vigenère-Chiffre", short: "Kodieren und dekodieren Sie mit einer polyalphabetischen Schlüsselwort-Chiffre.", description: "Kostenloses Vigenère-Chiffre-Tool. Geben Sie ein Schlüsselwort und eine Nachricht an — kodieren oder dekodieren Sie mit der klassischen polyalphabetischen Verschiebung. Nicht-Buchstaben passieren unverändert.", keywords: ["vigenere chiffre", "vigenere decoder", "vigenere encoder", "polyalphabetische chiffre", "schlüsselwort chiffre"], encode: "Kodieren", decode: "Dekodieren", key: "Schlüsselwort", input: "Text", output: "Ergebnis" },
  fr: { title: "Chiffre de Vigenère", short: "Encodez et décodez avec un chiffre polyalphabétique à mot-clé.", description: "Outil Vigenère gratuit. Fournissez un mot-clé et un message — encodez ou décodez en utilisant le décalage polyalphabétique classique. Les caractères non-alphabétiques passent inchangés.", keywords: ["chiffre vigenere", "décodeur vigenere", "encodeur vigenere", "chiffre polyalphabétique", "chiffre mot-clé"], encode: "Encoder", decode: "Décoder", key: "Mot-clé", input: "Texte", output: "Résultat" },
  es: { title: "Cifrado de Vigenère", short: "Codifica y decodifica con un cifrado polialfabético de palabra clave.", description: "Herramienta de cifrado Vigenère gratuita. Proporciona una palabra clave y un mensaje — codifica o decodifica usando el desplazamiento polialfabético clásico. Los caracteres no alfabéticos pasan sin cambios.", keywords: ["cifrado vigenere", "decodificador vigenere", "codificador vigenere", "cifrado polialfabético", "cifrado palabra clave"], encode: "Codificar", decode: "Decodificar", key: "Palabra clave", input: "Texto", output: "Resultado" },
  it: { title: "Cifrario di Vigenère", short: "Codifica e decodifica con un cifrario polialfabetico a parola chiave.", description: "Strumento Vigenère gratuito. Fornisci una parola chiave e un messaggio — codifica o decodifica usando lo spostamento polialfabetico classico. I caratteri non alfabetici passano invariati.", keywords: ["cifrario vigenere", "decodificatore vigenere", "codificatore vigenere", "cifrario polialfabetico", "cifrario parola chiave"], encode: "Codifica", decode: "Decodifica", key: "Parola chiave", input: "Testo", output: "Risultato" },
  ar: { title: "شيفرة Vigenère", short: "شفّر وفك تشفير بشيفرة استبدال متعددة الأبجدية بكلمة مفتاح.", description: "أداة Vigenère مجانية. زوّد بكلمة مفتاح ورسالة — شفّر أو فك تشفير باستخدام الإزاحة متعددة الأبجدية الكلاسيكية. تمر الأحرف غير الأبجدية دون تغيير.", keywords: ["شيفرة vigenere", "فاك تشفير vigenere", "مرمّز vigenere", "شيفرة متعددة الأبجدية", "شيفرة كلمة مفتاح"], encode: "تشفير", decode: "فك التشفير", key: "كلمة المفتاح", input: "النص", output: "النتيجة" },
  ru: { title: "Шифр Виженера", short: "Кодируйте и декодируйте полиалфавитным ключевым шифром.", description: "Бесплатный инструмент шифра Виженера. Укажите ключевое слово и сообщение — кодируйте или декодируйте с помощью классического полиалфавитного сдвига. Не-буквенные символы проходят без изменений.", keywords: ["шифр виженера", "декодер виженера", "кодировщик виженера", "полиалфавитный шифр", "ключевой шифр"], encode: "Кодировать", decode: "Декодировать", key: "Ключевое слово", input: "Текст", output: "Результат" },
  zh: { title: "维吉尼亚密码", short: "使用多表替换关键字密码进行编码和解码。", description: "免费的维吉尼亚密码工具。提供关键字和消息——使用经典的多表移位进行编码或解码。非字母字符保持不变。", keywords: ["维吉尼亚密码", "维吉尼亚解码器", "维吉尼亚编码器", "多表密码", "关键字密码"], encode: "编码", decode: "解码", key: "关键字", input: "文本", output: "结果" },
  ja: { title: "ヴィジュネル暗号", short: "多表式キーワード暗号でエンコード・デコード。", description: "無料のヴィジュネル暗号ツール。キーワードとメッセージを提供して——古典的な多表シフトでエンコードまたはデコード。文字以外はそのまま通過します。", keywords: ["ヴィジュネル暗号", "ヴィジュネル デコーダー", "ヴィジュネル エンコーダー", "多表暗号", "キーワード暗号"], encode: "エンコード", decode: "デコード", key: "キーワード", input: "テキスト", output: "結果" },
  ko: { title: "비제네르 암호", short: "다표 키워드 암호로 인코딩하고 디코딩합니다.", description: "무료 비제네르 암호 도구. 키워드와 메시지를 제공하세요 — 고전적인 다표 시프트로 인코딩 또는 디코딩하세요. 문자가 아닌 문자는 변경 없이 통과합니다.", keywords: ["비제네르 암호", "비제네르 디코더", "비제네르 인코더", "다표 암호", "키워드 암호"], encode: "인코딩", decode: "디코딩", key: "키워드", input: "텍스트", output: "결과" },
  hi: { title: "विजेनेरे सिफर", short: "बहु-वर्णक्रमी कीवर्ड सिफर के साथ एन्कोड और डिकोड करें।", description: "मुफ्त विजेनेरे सिफर टूल। एक कीवर्ड और संदेश प्रदान करें — क्लासिक बहु-वर्णक्रमी शिफ्ट का उपयोग करके एन्कोड या डिकोड करें। गैर-अक्षर वर्ण अपरिवर्तित गुजरते हैं।", keywords: ["विजेनेरे सिफर", "विजेनेरे डिकोडर", "विजेनेरे एन्कोडर", "बहु-वर्णक्रमी सिफर", "कीवर्ड सिफर"], encode: "एन्कोड", decode: "डिकोड", key: "कीवर्ड", input: "टेक्स्ट", output: "परिणाम" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
