import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image Cropper", short: "Crop images with an aspect-ratio preset.", description: "Free image cropper. Drop an image, pick an aspect ratio preset (square, 4:5, 9:16, 16:9 …) and adjust the X/Y/width/height to crop and download — runs entirely in your browser.", keywords: ["image cropper", "crop image", "instagram crop", "square crop", "crop jpg png"], drop: "Drop an image here or click to choose", aspect: "Aspect", x: "X", y: "Y", width: "Width", height: "Height", crop: "Crop", download: "Download" },
  tr: { title: "Görsel Kırpıcı", short: "Görselleri en boy oranı şablonuyla kırpın.", description: "Ücretsiz görsel kırpıcı. Bir görsel bırakın, bir en boy oranı şablonu seçin (kare, 4:5, 9:16, 16:9 …) ve X/Y/genişlik/yüksekliği ayarlayarak kırpın ve indirin — tamamen tarayıcınızda çalışır.", keywords: ["görsel kırpıcı", "görsel kırp", "instagram kırpma", "kare kırpma", "jpg png kırp"], drop: "Bir görsel bırakın veya seçmek için tıklayın", aspect: "Oran", x: "X", y: "Y", width: "Genişlik", height: "Yükseklik", crop: "Kırp", download: "İndir" },
  de: { title: "Bild-Cropper", short: "Bilder mit einem Seitenverhältnis-Preset zuschneiden.", description: "Kostenloser Bild-Cropper. Legen Sie ein Bild ab, wählen Sie ein Seitenverhältnis-Preset (Quadrat, 4:5, 9:16, 16:9 …) und passen Sie X/Y/Breite/Höhe an, um zuzuschneiden und herunterzuladen — läuft vollständig im Browser.", keywords: ["bild cropper", "bild zuschneiden", "instagram zuschneiden", "quadrat zuschneiden", "jpg png zuschneiden"], drop: "Bild hier ablegen oder klicken zum Auswählen", aspect: "Verhältnis", x: "X", y: "Y", width: "Breite", height: "Höhe", crop: "Zuschneiden", download: "Herunterladen" },
  fr: { title: "Recadrer une Image", short: "Recadrez les images avec un preset de rapport d'aspect.", description: "Outil de recadrage d'image gratuit. Déposez une image, choisissez un preset de rapport d'aspect (carré, 4:5, 9:16, 16:9 …) et ajustez X/Y/largeur/hauteur pour recadrer et télécharger — fonctionne entièrement dans votre navigateur.", keywords: ["recadrer image", "recadrer instagram", "recadrer carré", "recadrer jpg png", "outil recadrage"], drop: "Déposez une image ici ou cliquez pour choisir", aspect: "Aspect", x: "X", y: "Y", width: "Largeur", height: "Hauteur", crop: "Recadrer", download: "Télécharger" },
  es: { title: "Recortar Imagen", short: "Recorta imágenes con un preset de relación de aspecto.", description: "Recortador de imágenes gratuito. Arrastra una imagen, elige un preset de relación de aspecto (cuadrado, 4:5, 9:16, 16:9 …) y ajusta X/Y/ancho/alto para recortar y descargar — funciona completamente en tu navegador.", keywords: ["recortar imagen", "recortar instagram", "recortar cuadrado", "recortar jpg png", "recortador imagen"], drop: "Arrastra una imagen aquí o haz clic para elegir", aspect: "Aspecto", x: "X", y: "Y", width: "Ancho", height: "Alto", crop: "Recortar", download: "Descargar" },
  it: { title: "Ritaglia Immagine", short: "Ritaglia immagini con un preset di rapporto d'aspetto.", description: "Strumento di ritaglio immagini gratuito. Trascina un'immagine, scegli un preset di rapporto (quadrato, 4:5, 9:16, 16:9 …) e regola X/Y/larghezza/altezza per ritagliare e scaricare — funziona interamente nel browser.", keywords: ["ritaglia immagine", "ritaglio instagram", "ritaglio quadrato", "ritaglia jpg png", "ritagliatore immagine"], drop: "Trascina un'immagine qui o clicca per scegliere", aspect: "Aspetto", x: "X", y: "Y", width: "Larghezza", height: "Altezza", crop: "Ritaglia", download: "Scarica" },
  ar: { title: "أداة قص الصور", short: "اقتص الصور باستخدام إعداد مسبق لنسبة العرض إلى الارتفاع.", description: "أداة قص صور مجانية. أفلِت صورة، اختر إعدادًا مسبقًا (مربع، 4:5، 9:16، 16:9 …) واضبط X/Y/العرض/الارتفاع للقص والتنزيل — يعمل بالكامل في متصفحك.", keywords: ["قص الصورة", "قص instagram", "قص مربع", "قص jpg png", "أداة قص الصور"], drop: "أفلِت صورة هنا أو انقر للاختيار", aspect: "النسبة", x: "X", y: "Y", width: "العرض", height: "الارتفاع", crop: "قص", download: "تنزيل" },
  ru: { title: "Обрезка изображения", short: "Обрезайте изображения с пресетом пропорций.", description: "Бесплатный инструмент обрезки изображений. Перетащите изображение, выберите пресет пропорций (квадрат, 4:5, 9:16, 16:9 …) и настройте X/Y/ширину/высоту, чтобы обрезать и скачать — работает полностью в браузере.", keywords: ["обрезка изображения", "обрезка instagram", "обрезка квадрат", "обрезать jpg png", "кадрирование изображения"], drop: "Перетащите изображение сюда или нажмите для выбора", aspect: "Пропорции", x: "X", y: "Y", width: "Ширина", height: "Высота", crop: "Обрезать", download: "Скачать" },
  zh: { title: "图片裁剪器", short: "使用宽高比预设裁剪图片。", description: "免费的图片裁剪器。拖入图片，选择宽高比预设（方形、4:5、9:16、16:9 …），调整 X/Y/宽度/高度即可裁剪和下载——完全在浏览器中运行。", keywords: ["图片裁剪", "instagram 裁剪", "方形裁剪", "裁剪 jpg png", "图片裁剪器"], drop: "将图片拖到此处或点击选择", aspect: "宽高比", x: "X", y: "Y", width: "宽度", height: "高度", crop: "裁剪", download: "下载" },
  ja: { title: "画像トリミング", short: "アスペクト比プリセットで画像をトリミング。", description: "無料の画像トリミングツール。画像をドロップし、アスペクト比プリセット（正方形、4:5、9:16、16:9 …）を選び、X/Y/幅/高さを調整してトリミング・ダウンロード——すべてブラウザ内で動作します。", keywords: ["画像 トリミング", "instagram トリミング", "正方形 トリミング", "jpg png トリミング", "画像 トリミング ツール"], drop: "画像をここにドロップまたはクリックして選択", aspect: "アスペクト", x: "X", y: "Y", width: "幅", height: "高さ", crop: "トリミング", download: "ダウンロード" },
  ko: { title: "이미지 자르기", short: "가로세로 비율 프리셋으로 이미지를 자릅니다.", description: "무료 이미지 자르기 도구. 이미지를 드롭하고 가로세로 비율 프리셋(정사각형, 4:5, 9:16, 16:9 …)을 선택해 X/Y/너비/높이를 조정하여 자르고 다운로드하세요 — 모두 브라우저에서 실행됩니다.", keywords: ["이미지 자르기", "instagram 자르기", "정사각형 자르기", "jpg png 자르기", "이미지 자르기 도구"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", aspect: "비율", x: "X", y: "Y", width: "너비", height: "높이", crop: "자르기", download: "다운로드" },
  hi: { title: "इमेज क्रॉपर", short: "एक आस्पेक्ट-रेशियो प्रीसेट से इमेज क्रॉप करें।", description: "मुफ्त इमेज क्रॉपर। एक इमेज छोड़ें, एक आस्पेक्ट रेशियो प्रीसेट चुनें (वर्ग, 4:5, 9:16, 16:9 …) और X/Y/चौड़ाई/ऊँचाई समायोजित करके क्रॉप करें व डाउनलोड करें — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["इमेज क्रॉपर", "instagram क्रॉप", "वर्ग क्रॉप", "jpg png क्रॉप", "इमेज क्रॉप टूल"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", aspect: "आस्पेक्ट", x: "X", y: "Y", width: "चौड़ाई", height: "ऊँचाई", crop: "क्रॉप", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
