import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Fancy Text Generator", short: "Turn text into bold, italic, monospace and other Unicode styles.", description: "Free fancy text generator. Convert plain text into 𝐛𝐨𝐥𝐝, 𝑖𝑡𝑎𝑙𝑖𝑐, 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎 and full-width Unicode styles you can paste into social media bios, posts and usernames.", keywords: ["fancy text generator", "bold text generator", "unicode text", "stylish text", "cool fonts for instagram"], placeholder: "Type your text…", bold: "Bold", italic: "Italic", monospace: "Monospace", sansBold: "Sans bold", fullwidth: "Full-width" },
  pt: { title: "Gerador de Fancy Text", short: "Turn text into bold, italic, monospace e other Unicode styles.", description: "Gratuito - fancy text generator. Converter plain text into ðð¨ð¥ð, ðð¡ðððð, ððððððððð e full-width Unicode styles you can paste into social media bios, posts e usernames.", keywords: ["fancy text generator", "bold text generator", "unicode text", "stylish text", "cool fonts for instagram"], placeholder: "Type your text…", bold: "Bold", italic: "Italic", monospace: "Monospace", sansBold: "Sans bold", fullwidth: "Full-width" },
  id: { title: "Generator Fancy Text", short: "Turn text into bold, italic, monospace dan other Unicode styles.", description: "Gratis - fancy text generator. Konversi plain text into ðð¨ð¥ð, ðð¡ðððð, ððððððððð dan full-width Unicode styles you can paste into social media bios, posts dan usernames.", keywords: ["fancy text generator", "bold text generator", "unicode text", "stylish text", "cool fonts for instagram"], placeholder: "Type your text…", bold: "Bold", italic: "Italic", monospace: "Monospace", sansBold: "Sans bold", fullwidth: "Full-width" },

  tr: { title: "Süslü Yazı Oluşturucu", short: "Metni kalın, italik, tek aralıklı ve diğer Unicode stillerine çevirin.", description: "Ücretsiz süslü yazı oluşturucu. Düz metni 𝐤𝐚𝐥𝐢𝐧, 𝑖𝑡𝑎𝑙𝑖𝑘, 𝚝𝚎𝚔 𝚊𝚛𝚊𝚕𝚒𝚔𝚕𝚒 ve tam genişlik Unicode stillerine çevirin; sosyal medya biyografilerine, gönderilere ve kullanıcı adlarına yapıştırın.", keywords: ["süslü yazı oluşturucu", "kalın yazı oluşturucu", "unicode yazı", "şık yazı", "instagram için yazı tipi"], placeholder: "Metninizi yazın…", bold: "Kalın", italic: "İtalik", monospace: "Tek aralıklı", sansBold: "Sans kalın", fullwidth: "Tam genişlik" },
  de: { title: "Schriftarten-Generator", short: "Verwandeln Sie Text in fett, kursiv, Monospace und andere Unicode-Stile.", description: "Kostenloser Schriftarten-Generator. Wandeln Sie Text in 𝐟𝐞𝐭𝐭, 𝑘𝑢𝑟𝑠𝑖𝑣, 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎 und Vollbreite-Unicode-Stile um, die Sie in Social-Media-Bios, Posts und Benutzernamen einfügen können.", keywords: ["schriftarten generator", "fettschrift generator", "unicode text", "stylischer text", "coole schriften"], placeholder: "Text eingeben…", bold: "Fett", italic: "Kursiv", monospace: "Monospace", sansBold: "Sans fett", fullwidth: "Vollbreite" },
  fr: { title: "Générateur de Texte Stylé", short: "Transformez le texte en gras, italique, monospace et autres styles Unicode.", description: "Générateur de texte stylé gratuit. Convertissez du texte en 𝐠𝐫𝐚𝐬, 𝑖𝑡𝑎𝑙𝑖𝑞𝑢𝑒, 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚌𝚎 et styles Unicode pleine largeur à coller dans les bios, posts et pseudos.", keywords: ["générateur de texte stylé", "générateur de texte en gras", "texte unicode", "texte stylé", "polices cool"], placeholder: "Tapez votre texte…", bold: "Gras", italic: "Italique", monospace: "Monospace", sansBold: "Sans gras", fullwidth: "Pleine largeur" },
  es: { title: "Generador de Texto Elegante", short: "Convierte texto en negrita, cursiva, monoespaciado y otros estilos Unicode.", description: "Generador de texto elegante gratuito. Convierte texto plano en 𝐧𝐞𝐠𝐫𝐢𝐭𝐚, 𝑐𝑢𝑟𝑠𝑖𝑣𝑎, 𝚖𝚘𝚗𝚘𝚎𝚜𝚙𝚊𝚌𝚒𝚊𝚍𝚘 y estilos Unicode de ancho completo para pegar en biografías, publicaciones y nombres de usuario.", keywords: ["generador de texto elegante", "generador de negrita", "texto unicode", "texto estilizado", "fuentes para instagram"], placeholder: "Escribe tu texto…", bold: "Negrita", italic: "Cursiva", monospace: "Monoespaciado", sansBold: "Sans negrita", fullwidth: "Ancho completo" },
  it: { title: "Generatore di Testo Stiloso", short: "Trasforma il testo in grassetto, corsivo, monospazio e altri stili Unicode.", description: "Generatore di testo stiloso gratuito. Converti testo semplice in 𝐠𝐫𝐚𝐬𝐬𝐞𝐭𝐭𝐨, 𝑐𝑜𝑟𝑠𝑖𝑣𝑜, 𝚖𝚘𝚗𝚘𝚜𝚙𝚊𝚣𝚒𝚘 e stili Unicode a larghezza piena da incollare in bio, post e nomi utente.", keywords: ["generatore di testo stiloso", "generatore di grassetto", "testo unicode", "testo stiloso", "font per instagram"], placeholder: "Digita il tuo testo…", bold: "Grassetto", italic: "Corsivo", monospace: "Monospazio", sansBold: "Sans grassetto", fullwidth: "Larghezza piena" },
  ar: { title: "مولّد النص المزخرف", short: "حوّل النص إلى عريض ومائل وأحادي المسافة وأنماط Unicode أخرى.", description: "مولّد نص مزخرف مجاني. حوّل النص العادي إلى أنماط Unicode عريضة ومائلة وأحادية المسافة وكاملة العرض يمكنك لصقها في السير الذاتية والمنشورات وأسماء المستخدمين.", keywords: ["مولد النص المزخرف", "مولد النص العريض", "نص unicode", "نص مزخرف", "خطوط انستغرام"], placeholder: "اكتب نصك…", bold: "عريض", italic: "مائل", monospace: "أحادي المسافة", sansBold: "Sans عريض", fullwidth: "كامل العرض" },
  ru: { title: "Генератор Красивого Текста", short: "Превратите текст в жирный, курсив, моноширинный и другие стили Unicode.", description: "Бесплатный генератор красивого текста. Преобразуйте обычный текст в 𝐠𝐠жирный, 𝑘𝑢курсив, моноширинный и полноширинные стили Unicode для вставки в био, посты и ники соцсетей.", keywords: ["генератор красивого текста", "генератор жирного текста", "unicode текст", "стильный текст", "шрифты для инстаграм"], placeholder: "Введите ваш текст…", bold: "Жирный", italic: "Курсив", monospace: "Моноширинный", sansBold: "Sans жирный", fullwidth: "Полноширинный" },
  zh: { title: "花式文字生成器", short: "将文本转换为粗体、斜体、等宽及其他 Unicode 样式。", description: "免费的花式文字生成器。将纯文本转换为𝐛𝐨𝐥𝐝（粗体）、𝑖𝑡𝑎𝑙𝑖𝑐（斜体）、𝚖𝚘𝚗𝚘（等宽）和全角 Unicode 样式，可粘贴到社交媒体简介、帖子和用户名中。", keywords: ["花式文字生成器", "粗体文字生成器", "unicode文字", "炫酷文字", "ins字体"], placeholder: "输入你的文本…", bold: "粗体", italic: "斜体", monospace: "等宽", sansBold: "无衬线粗体", fullwidth: "全角" },
  ja: { title: "おしゃれ文字ジェネレーター", short: "テキストを太字・斜体・等幅などの Unicode スタイルに変換します。", description: "無料のおしゃれ文字ジェネレーター。プレーンテキストを 𝐛𝐨𝐥𝐝（太字）、𝑖𝑡𝑎𝑙𝑖𝑐（斜体）、𝚖𝚘𝚗𝚘（等幅）や全角の Unicode スタイルに変換し、SNS のプロフィール・投稿・ユーザー名に貼り付けられます。", keywords: ["おしゃれ文字 ジェネレーター", "太字 ジェネレーター", "unicode 文字", "かわいい文字", "インスタ フォント"], placeholder: "テキストを入力…", bold: "太字", italic: "斜体", monospace: "等幅", sansBold: "サンセリフ太字", fullwidth: "全角" },
  ko: { title: "특수문자 텍스트 생성기", short: "텍스트를 굵게, 기울임, 고정폭 등 유니코드 스타일로 변환합니다.", description: "무료 특수문자 텍스트 생성기. 일반 텍스트를 𝐛𝐨𝐥𝐝(굵게), 𝑖𝑡𝑎𝑙𝑖𝑐(기울임), 𝚖𝚘𝚗𝚘(고정폭) 및 전각 유니코드 스타일로 변환하여 SNS 소개, 게시물, 사용자 이름에 붙여넣을 수 있습니다.", keywords: ["특수문자 텍스트 생성기", "굵은 글씨 생성기", "유니코드 텍스트", "예쁜 글씨", "인스타 폰트"], placeholder: "텍스트를 입력하세요…", bold: "굵게", italic: "기울임", monospace: "고정폭", sansBold: "산세리프 굵게", fullwidth: "전각" },
  hi: { title: "फैंसी टेक्स्ट जनरेटर", short: "टेक्स्ट को बोल्ड, इटैलिक, मोनोस्पेस और अन्य यूनिकोड शैलियों में बदलें।", description: "मुफ्त फैंसी टेक्स्ट जनरेटर। सादे टेक्स्ट को 𝐛𝐨𝐥𝐝, 𝑖𝑡𝑎𝑙𝑖𝑐, 𝚖𝚘𝚗𝚘 और पूर्ण-चौड़ाई यूनिकोड शैलियों में बदलें जिन्हें आप सोशल मीडिया बायो, पोस्ट और यूज़रनेम में पेस्ट कर सकते हैं।", keywords: ["फैंसी टेक्स्ट जनरेटर", "बोल्ड टेक्स्ट जनरेटर", "यूनिकोड टेक्स्ट", "स्टाइलिश टेक्स्ट", "इंस्टाग्राम फॉन्ट"], placeholder: "अपना टेक्स्ट टाइप करें…", bold: "बोल्ड", italic: "इटैलिक", monospace: "मोनोस्पेस", sansBold: "सैन्स बोल्ड", fullwidth: "पूर्ण-चौड़ाई" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
