import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Cron Expression Explainer", short: "Translate a cron expression into plain English.", description: "Free cron expression explainer. Paste a standard 5-field crontab schedule and get a plain-English description of when it runs, validated field by field — all in your browser.", keywords: ["cron explainer", "cron expression", "crontab generator", "cron to english", "cron schedule explainer"], input: "Cron expression", explanation: "Schedule", placeholder: "e.g. 0 9 * * 1-5" },
  nl: { title: "Cron Expression Explainer", short: "Translate a cron expression into plain English.", description: "Gratis cron expression explainer. Paste a standard 5-field crontab schedule and get a plain-English description of when it runs, valideerd field by field — all in uw browser.", keywords: ["cron explainer", "cron expression", "crontab generator", "cron to english", "cron schedule explainer"], input: "Cron expression", explanation: "Schedule", placeholder: "e.g. 0 9 * * 1-5" },

  pl: { title: "Cron Expression Explainer", short: "Translate a cron expression into plain English.", description: "Darmowy cron expression explainer. Paste a standard 5-field crontab schedule and get a plain-English description of when it runs, walidujd field by field — all w Twojej przeglądarce.", keywords: ["cron explainer", "cron expression", "crontab generator", "cron to english", "cron schedule explainer"], input: "Cron expression", explanation: "Schedule", placeholder: "e.g. 0 9 * * 1-5" },
  pt: { title: "Cron Expression Explainer", short: "Translate a cron expression into plain English.", description: "Gratuito - cron expression explainer. Paste a standard 5-field crontab schedule e get a plain-English description de when it runs, validated field by field â all no seu navegador.", keywords: ["cron explainer", "cron expression", "crontab generator", "cron to english", "cron schedule explainer"], input: "Cron expression", explanation: "Schedule", placeholder: "e.g. 0 9 * * 1-5" },
  id: { title: "Cron Expression Explainer", short: "Translate a cron expression into plain English.", description: "Gratis - cron expression explainer. Paste a standard 5-field crontab schedule dan get a plain-English description dari when it runs, validated field by field â all di browser Anda.", keywords: ["cron explainer", "cron expression", "crontab generator", "cron to english", "cron schedule explainer"], input: "Cron expression", explanation: "Schedule", placeholder: "e.g. 0 9 * * 1-5" },

  tr: { title: "Cron İfadesi Açıklayıcı", short: "Bir cron ifadesini sade dile çevirin.", description: "Ücretsiz cron ifadesi açıklayıcı. Standart 5 alanlı bir crontab zamanlamasını yapıştırın ve ne zaman çalışacağının sade dilde açıklamasını alın, alan alan doğrulanmış — hepsi tarayıcınızda.", keywords: ["cron açıklayıcı", "cron ifadesi", "crontab oluşturucu", "cron açıklama", "cron zamanlama açıklayıcı"], input: "Cron ifadesi", explanation: "Zamanlama", placeholder: "örn. 0 9 * * 1-5" },
  de: { title: "Cron-Ausdruck-Erklärer", short: "Übersetzen Sie einen Cron-Ausdruck in einfache Sprache.", description: "Kostenloser Cron-Ausdruck-Erklärer. Fügen Sie einen standardmäßigen 5-Feld-Crontab-Zeitplan ein und erhalten Sie eine verständliche Beschreibung, wann er läuft, Feld für Feld validiert — alles im Browser.", keywords: ["cron erklärer", "cron ausdruck", "crontab generator", "cron erklärung", "cron zeitplan erklärer"], input: "Cron-Ausdruck", explanation: "Zeitplan", placeholder: "z. B. 0 9 * * 1-5" },
  fr: { title: "Explicateur d'Expression Cron", short: "Traduisez une expression cron en langage clair.", description: "Explicateur d'expression cron gratuit. Collez un planning crontab standard à 5 champs et obtenez une description en langage clair de son exécution, validée champ par champ — le tout dans votre navigateur.", keywords: ["explicateur cron", "expression cron", "générateur crontab", "cron en français", "explicateur planning cron"], input: "Expression cron", explanation: "Planning", placeholder: "ex. 0 9 * * 1-5" },
  es: { title: "Explicador de Expresiones Cron", short: "Traduce una expresión cron a lenguaje sencillo.", description: "Explicador de expresiones cron gratuito. Pega un horario crontab estándar de 5 campos y obtén una descripción en lenguaje sencillo de cuándo se ejecuta, validada campo por campo — todo en tu navegador.", keywords: ["explicador cron", "expresión cron", "generador crontab", "cron a español", "explicador horario cron"], input: "Expresión cron", explanation: "Horario", placeholder: "p. ej. 0 9 * * 1-5" },
  it: { title: "Spiegatore di Espressioni Cron", short: "Traduci un'espressione cron in linguaggio semplice.", description: "Spiegatore di espressioni cron gratuito. Incolla una pianificazione crontab standard a 5 campi e ottieni una descrizione in linguaggio semplice di quando viene eseguita, validata campo per campo — tutto nel browser.", keywords: ["spiegatore cron", "espressione cron", "generatore crontab", "cron in italiano", "spiegatore pianificazione cron"], input: "Espressione cron", explanation: "Pianificazione", placeholder: "es. 0 9 * * 1-5" },
  ar: { title: "شارح تعبير Cron", short: "ترجم تعبير cron إلى لغة بسيطة.", description: "شارح تعبير cron مجاني. الصق جدول crontab قياسي من 5 حقول واحصل على وصف بلغة بسيطة لوقت تشغيله، مُتحقق منه حقلاً بحقل — كل ذلك في متصفحك.", keywords: ["شارح cron", "تعبير cron", "مولد crontab", "cron إلى الإنجليزية", "شارح جدولة cron"], input: "تعبير cron", explanation: "الجدولة", placeholder: "مثال 0 9 * * 1-5" },
  ru: { title: "Объяснение выражения Cron", short: "Переведите выражение cron на простой язык.", description: "Бесплатный разъяснитель выражений cron. Вставьте стандартное 5-полевое расписание crontab и получите понятное описание того, когда оно выполняется, проверенное поле за полем — всё в браузере.", keywords: ["объяснение cron", "выражение cron", "генератор crontab", "cron на русском", "разъяснение расписания cron"], input: "Выражение cron", explanation: "Расписание", placeholder: "напр. 0 9 * * 1-5" },
  zh: { title: "Cron 表达式解释器", short: "将 cron 表达式翻译成通俗易懂的语言。", description: "免费的 cron 表达式解释器。粘贴标准的 5 字段 crontab 计划，即可获得其运行时间的通俗描述，并逐字段验证——全部在浏览器中完成。", keywords: ["cron 解释器", "cron 表达式", "crontab 生成器", "cron 转中文", "cron 计划解释"], input: "Cron 表达式", explanation: "计划", placeholder: "例如 0 9 * * 1-5" },
  ja: { title: "Cron 式エクスプレイナー", short: "cron 式を分かりやすい言葉に翻訳。", description: "無料の cron 式エクスプレイナー。標準的な5フィールドの crontab スケジュールを貼り付けると、いつ実行されるかを分かりやすく説明し、フィールドごとに検証します——すべてブラウザ内で。", keywords: ["cron エクスプレイナー", "cron 式", "crontab 生成", "cron を日本語に", "cron スケジュール説明"], input: "Cron 式", explanation: "スケジュール", placeholder: "例 0 9 * * 1-5" },
  ko: { title: "Cron 표현식 설명기", short: "cron 표현식을 쉬운 말로 번역합니다.", description: "무료 cron 표현식 설명기. 표준 5필드 crontab 일정을 붙여넣으면 실행 시점을 쉬운 말로 설명하고 필드별로 검증합니다 — 모두 브라우저에서.", keywords: ["cron 설명기", "cron 표현식", "crontab 생성기", "cron 한국어로", "cron 일정 설명"], input: "Cron 표현식", explanation: "일정", placeholder: "예: 0 9 * * 1-5" },
  hi: { title: "Cron एक्सप्रेशन व्याख्याकार", short: "एक cron एक्सप्रेशन को सरल भाषा में अनुवाद करें।", description: "मुफ्त cron एक्सप्रेशन व्याख्याकार। एक मानक 5-फ़ील्ड crontab शेड्यूल पेस्ट करें और यह कब चलता है इसका सरल भाषा में विवरण पाएं, फ़ील्ड-दर-फ़ील्ड सत्यापित — सब आपके ब्राउज़र में।", keywords: ["cron व्याख्याकार", "cron एक्सप्रेशन", "crontab जनरेटर", "cron से अंग्रेज़ी", "cron शेड्यूल व्याख्याकार"], input: "Cron एक्सप्रेशन", explanation: "शेड्यूल", placeholder: "उदा. 0 9 * * 1-5" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
