import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const KW = ["raid calculator", "raid capacity calculator", "raid 5 usable space", "raid storage efficiency", "raid fault tolerance"];

const data = {
  en: { title: "RAID Calculator", short: "Calculate usable capacity, redundancy and fault tolerance for RAID 0, 1, 5, 6 and 10 arrays.", description: "Free RAID calculator. Pick a RAID level, the number of disks and the size of each disk to see usable capacity, redundancy overhead, fault tolerance and storage efficiency. Runs entirely in your browser.", keywords: KW, level: "RAID level", disks: "Number of disks", size: "Disk size (TB)", usable: "Usable capacity", redundancy: "Redundancy", faultTolerance: "Fault tolerance", efficiency: "Storage efficiency", tb: "TB", disksUnit: "disks", invalid: "Invalid disk count for the selected RAID level." },
  nl: { title: "RAID Calculator", short: "Bereken usable capacity, redundancy and fault tolerance for RAID 0, 1, 5, 6 and 10 arrays.", description: "Gratis RAID calculator. Pick a RAID level, the nummer of disks and the grootte of each disk to see usable capacity, redundancy overhead, fault tolerance and storage efficiency. Runs entirely in uw browser.", keywords: KW, level: "RAID level", disks: "Nummer of disks", size: "Disk grootte (TB)", usable: "Usable capacity", redundancy: "Redundancy", faultTolerance: "Fault tolerance", efficiency: "Storage efficiency", tb: "TB", disksUnit: "disks", invalid: "Invalid disk count for the selected RAID level." },

  pl: { title: "RAID Kalkulator", short: "Oblicz usable capacity, redundancy and fault tolerance for RAID 0, 1, 5, 6 and 10 arrays.", description: "Darmowy RAID kalkulator. Pick a RAID level, the liczba of disks and the rozmiar of each disk to see usable capacity, redundancy overhead, fault tolerance and storage efficiency. Runs entirely w Twojej przeglądarce.", keywords: KW, level: "RAID level", disks: "Liczba of disks", size: "Disk rozmiar (TB)", usable: "Usable capacity", redundancy: "Redundancy", faultTolerance: "Fault tolerance", efficiency: "Storage efficiency", tb: "TB", disksUnit: "disks", invalid: "Invalid disk count for the selected RAID level." },
  pt: { title: "Calculadora RAID", short: "Calcule capacidade utilizável, redundância e tolerância a falhas para arranjos RAID 0, 1, 5, 6 e 10.", description: "Calculadora RAID gratuita. Escolha um nível RAID, o número de discos e o tamanho de cada disco para ver capacidade utilizável, sobrecarga de redundância, tolerância a falhas e eficiência de armazenamento. Roda inteiramente no seu navegador.", keywords: KW, level: "Nível RAID", disks: "Número de discos", size: "Tamanho do disco (TB)", usable: "Capacidade utilizável", redundancy: "Redundância", faultTolerance: "Tolerância a falhas", efficiency: "Eficiência de armazenamento", tb: "TB", disksUnit: "discos", invalid: "Contagem de discos inválida para o nível RAID selecionado." },
  id: { title: "Kalkulator RAID", short: "Hitung kapasitas yang dapat digunakan, redundansi, dan toleransi kesalahan untuk array RAID 0, 1, 5, 6, dan 10.", description: "Kalkulator RAID gratis. Pilih level RAID, jumlah disk, dan ukuran setiap disk untuk melihat kapasitas yang dapat digunakan, overhead redundansi, toleransi kesalahan, dan efisiensi penyimpanan. Berjalan sepenuhnya di browser Anda.", keywords: KW, level: "Level RAID", disks: "Jumlah disk", size: "Ukuran disk (TB)", usable: "Kapasitas yang dapat digunakan", redundancy: "Redundansi", faultTolerance: "Toleransi kesalahan", efficiency: "Efisiensi penyimpanan", tb: "TB", disksUnit: "disk", invalid: "Jumlah disk tidak valid untuk level RAID yang dipilih." },

  tr: { title: "RAID Hesaplayıcı", short: "RAID 0, 1, 5, 6 ve 10 dizileri için kullanılabilir kapasite, yedeklilik ve hata toleransını hesaplayın.", description: "Ücretsiz RAID hesaplayıcı. Kullanılabilir kapasiteyi, yedeklilik yükünü, hata toleransını ve depolama verimliliğini görmek için bir RAID seviyesi, disk sayısı ve her diskin boyutunu seçin. Tamamen tarayıcınızda çalışır.", keywords: ["raid hesaplayıcı", "raid kapasite hesaplayıcı", "raid 5 kullanılabilir alan", "raid depolama verimliliği", "raid hata toleransı"], level: "RAID seviyesi", disks: "Disk sayısı", size: "Disk boyutu (TB)", usable: "Kullanılabilir kapasite", redundancy: "Yedeklilik", faultTolerance: "Hata toleransı", efficiency: "Depolama verimliliği", tb: "TB", disksUnit: "disk", invalid: "Seçilen RAID seviyesi için geçersiz disk sayısı." },
  de: { title: "RAID-Rechner", short: "Berechnen Sie nutzbare Kapazität, Redundanz und Fehlertoleranz für RAID 0, 1, 5, 6 und 10.", description: "Kostenloser RAID-Rechner. Wählen Sie ein RAID-Level, die Anzahl der Festplatten und die Größe jeder Festplatte, um nutzbare Kapazität, Redundanz-Overhead, Fehlertoleranz und Speichereffizienz zu sehen. Läuft vollständig in Ihrem Browser.", keywords: ["raid rechner", "raid kapazitätsrechner", "raid 5 nutzbarer speicher", "raid speichereffizienz", "raid fehlertoleranz"], level: "RAID-Level", disks: "Anzahl der Festplatten", size: "Festplattengröße (TB)", usable: "Nutzbare Kapazität", redundancy: "Redundanz", faultTolerance: "Fehlertoleranz", efficiency: "Speichereffizienz", tb: "TB", disksUnit: "Festplatten", invalid: "Ungültige Festplattenanzahl für das gewählte RAID-Level." },
  fr: { title: "Calculateur RAID", short: "Calculez la capacité utilisable, la redondance et la tolérance aux pannes pour les grappes RAID 0, 1, 5, 6 et 10.", description: "Calculateur RAID gratuit. Choisissez un niveau RAID, le nombre de disques et la taille de chaque disque pour voir la capacité utilisable, la surcharge de redondance, la tolérance aux pannes et l'efficacité de stockage. Fonctionne entièrement dans votre navigateur.", keywords: ["calculateur raid", "calculateur capacité raid", "espace utilisable raid 5", "efficacité stockage raid", "tolérance pannes raid"], level: "Niveau RAID", disks: "Nombre de disques", size: "Taille du disque (TB)", usable: "Capacité utilisable", redundancy: "Redondance", faultTolerance: "Tolérance aux pannes", efficiency: "Efficacité de stockage", tb: "TB", disksUnit: "disques", invalid: "Nombre de disques invalide pour le niveau RAID sélectionné." },
  es: { title: "Calculadora RAID", short: "Calcula la capacidad utilizable, la redundancia y la tolerancia a fallos para matrices RAID 0, 1, 5, 6 y 10.", description: "Calculadora RAID gratuita. Elige un nivel RAID, el número de discos y el tamaño de cada disco para ver la capacidad utilizable, la sobrecarga de redundancia, la tolerancia a fallos y la eficiencia de almacenamiento. Se ejecuta completamente en tu navegador.", keywords: ["calculadora raid", "calculadora capacidad raid", "espacio utilizable raid 5", "eficiencia almacenamiento raid", "tolerancia fallos raid"], level: "Nivel RAID", disks: "Número de discos", size: "Tamaño del disco (TB)", usable: "Capacidad utilizable", redundancy: "Redundancia", faultTolerance: "Tolerancia a fallos", efficiency: "Eficiencia de almacenamiento", tb: "TB", disksUnit: "discos", invalid: "Número de discos no válido para el nivel RAID seleccionado." },
  it: { title: "Calcolatore RAID", short: "Calcola capacità utilizzabile, ridondanza e tolleranza ai guasti per array RAID 0, 1, 5, 6 e 10.", description: "Calcolatore RAID gratuito. Scegli un livello RAID, il numero di dischi e la dimensione di ogni disco per vedere capacità utilizzabile, overhead di ridondanza, tolleranza ai guasti ed efficienza di archiviazione. Funziona interamente nel tuo browser.", keywords: ["calcolatore raid", "calcolatore capacità raid", "spazio utilizzabile raid 5", "efficienza archiviazione raid", "tolleranza guasti raid"], level: "Livello RAID", disks: "Numero di dischi", size: "Dimensione disco (TB)", usable: "Capacità utilizzabile", redundancy: "Ridondanza", faultTolerance: "Tolleranza ai guasti", efficiency: "Efficienza di archiviazione", tb: "TB", disksUnit: "dischi", invalid: "Numero di dischi non valido per il livello RAID selezionato." },
  ar: { title: "حاسبة RAID", short: "احسب السعة القابلة للاستخدام والتكرار وتحمّل الأعطال لمصفوفات RAID 0 و1 و5 و6 و10.", description: "حاسبة RAID مجانية. اختر مستوى RAID وعدد الأقراص وحجم كل قرص لرؤية السعة القابلة للاستخدام وعبء التكرار وتحمّل الأعطال وكفاءة التخزين. تعمل بالكامل في متصفحك.", keywords: ["حاسبة raid", "حاسبة سعة raid", "مساحة raid 5 القابلة للاستخدام", "كفاءة تخزين raid", "تحمل أعطال raid"], level: "مستوى RAID", disks: "عدد الأقراص", size: "حجم القرص (TB)", usable: "السعة القابلة للاستخدام", redundancy: "التكرار", faultTolerance: "تحمّل الأعطال", efficiency: "كفاءة التخزين", tb: "TB", disksUnit: "أقراص", invalid: "عدد أقراص غير صالح لمستوى RAID المحدد." },
  ru: { title: "Калькулятор RAID", short: "Рассчитайте полезную ёмкость, избыточность и отказоустойчивость для массивов RAID 0, 1, 5, 6 и 10.", description: "Бесплатный калькулятор RAID. Выберите уровень RAID, количество дисков и размер каждого диска, чтобы увидеть полезную ёмкость, накладные расходы на избыточность, отказоустойчивость и эффективность хранения. Работает полностью в браузере.", keywords: ["калькулятор raid", "калькулятор ёмкости raid", "полезное место raid 5", "эффективность хранения raid", "отказоустойчивость raid"], level: "Уровень RAID", disks: "Количество дисков", size: "Размер диска (TB)", usable: "Полезная ёмкость", redundancy: "Избыточность", faultTolerance: "Отказоустойчивость", efficiency: "Эффективность хранения", tb: "TB", disksUnit: "дисков", invalid: "Недопустимое количество дисков для выбранного уровня RAID." },
  zh: { title: "RAID 计算器", short: "计算 RAID 0、1、5、6 和 10 阵列的可用容量、冗余和容错能力。", description: "免费的 RAID 计算器。选择 RAID 级别、磁盘数量和每块磁盘的大小，即可查看可用容量、冗余开销、容错能力和存储效率。完全在浏览器中运行。", keywords: ["raid 计算器", "raid 容量计算器", "raid 5 可用空间", "raid 存储效率", "raid 容错"], level: "RAID 级别", disks: "磁盘数量", size: "磁盘大小 (TB)", usable: "可用容量", redundancy: "冗余", faultTolerance: "容错能力", efficiency: "存储效率", tb: "TB", disksUnit: "块磁盘", invalid: "对于所选 RAID 级别的磁盘数量无效。" },
  ja: { title: "RAID 計算ツール", short: "RAID 0・1・5・6・10 アレイの使用可能容量、冗長性、耐障害性を計算します。", description: "無料の RAID 計算ツール。RAID レベル、ディスク数、各ディスクのサイズを選ぶと、使用可能容量、冗長性のオーバーヘッド、耐障害性、ストレージ効率が表示されます。すべてブラウザ内で動作します。", keywords: ["raid 計算ツール", "raid 容量計算", "raid 5 使用可能容量", "raid ストレージ効率", "raid 耐障害性"], level: "RAID レベル", disks: "ディスク数", size: "ディスクサイズ (TB)", usable: "使用可能容量", redundancy: "冗長性", faultTolerance: "耐障害性", efficiency: "ストレージ効率", tb: "TB", disksUnit: "台", invalid: "選択した RAID レベルに対して無効なディスク数です。" },
  ko: { title: "RAID 계산기", short: "RAID 0, 1, 5, 6, 10 어레이의 사용 가능 용량, 중복성, 내결함성을 계산합니다.", description: "무료 RAID 계산기. RAID 레벨, 디스크 수, 각 디스크 크기를 선택하면 사용 가능 용량, 중복성 오버헤드, 내결함성, 저장 효율을 확인할 수 있습니다. 브라우저에서 완전히 실행됩니다.", keywords: ["raid 계산기", "raid 용량 계산기", "raid 5 사용 가능 공간", "raid 저장 효율", "raid 내결함성"], level: "RAID 레벨", disks: "디스크 수", size: "디스크 크기 (TB)", usable: "사용 가능 용량", redundancy: "중복성", faultTolerance: "내결함성", efficiency: "저장 효율", tb: "TB", disksUnit: "개", invalid: "선택한 RAID 레벨에 유효하지 않은 디스크 수입니다." },
  hi: { title: "RAID कैलकुलेटर", short: "RAID 0, 1, 5, 6 और 10 ऐरे के लिए उपयोग योग्य क्षमता, अतिरेक और दोष सहनशीलता की गणना करें।", description: "मुफ्त RAID कैलकुलेटर। उपयोग योग्य क्षमता, अतिरेक ओवरहेड, दोष सहनशीलता और भंडारण दक्षता देखने के लिए एक RAID स्तर, डिस्क की संख्या और प्रत्येक डिस्क का आकार चुनें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["raid कैलकुलेटर", "raid क्षमता कैलकुलेटर", "raid 5 उपयोग योग्य स्थान", "raid भंडारण दक्षता", "raid दोष सहनशीलता"], level: "RAID स्तर", disks: "डिस्क की संख्या", size: "डिस्क आकार (TB)", usable: "उपयोग योग्य क्षमता", redundancy: "अतिरेक", faultTolerance: "दोष सहनशीलता", efficiency: "भंडारण दक्षता", tb: "TB", disksUnit: "डिस्क", invalid: "चयनित RAID स्तर के लिए अमान्य डिस्क संख्या।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
