import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Sort Text Lines", short: "Sort lines alphabetically, by length or numerically, with reverse option.", description: "Free line sorter. Sort a list of lines alphabetically, by length or numerically, optionally reversed and case-insensitive. Handy for ordering lists, keywords and data. Runs in your browser.", keywords: ["sort lines", "alphabetical sort", "sort list online", "sort by length", "numeric sort", "text sorter"], placeholder: "Paste lines to sort…", mode: "Sort by", alphabetical: "Alphabetical", byLength: "Length", numeric: "Numeric", reverse: "Reverse", caseInsensitive: "Ignore case" },
  pt: { title: "Sort Text Lines", short: "Sort lines alphabetically, by length or numerically, with reverse option.", description: "Free line sorter. Sort a list of lines alphabetically, by length or numerically, optionally reversed and case-insensitive. Handy for ordering lists, keywords and data. Runs in your browser.", keywords: ["sort lines", "alphabetical sort", "sort list online", "sort by length", "numeric sort", "text sorter"], placeholder: "Paste lines to sort…", mode: "Sort by", alphabetical: "Alphabetical", byLength: "Length", numeric: "Numeric", reverse: "Reverse", caseInsensitive: "Ignore case" },
  id: { title: "Sort Text Lines", short: "Sort lines alphabetically, by length or numerically, with reverse option.", description: "Free line sorter. Sort a list of lines alphabetically, by length or numerically, optionally reversed and case-insensitive. Handy for ordering lists, keywords and data. Runs in your browser.", keywords: ["sort lines", "alphabetical sort", "sort list online", "sort by length", "numeric sort", "text sorter"], placeholder: "Paste lines to sort…", mode: "Sort by", alphabetical: "Alphabetical", byLength: "Length", numeric: "Numeric", reverse: "Reverse", caseInsensitive: "Ignore case" },

  tr: { title: "Metin Satırlarını Sırala", short: "Satırları alfabetik, uzunluğa veya sayısal olarak sıralayın, ters seçeneğiyle.", description: "Ücretsiz satır sıralayıcı. Bir satır listesini alfabetik, uzunluğa veya sayısal olarak sıralayın; isteğe bağlı ters ve büyük/küçük harf duyarsız. Listeleri, anahtar kelimeleri ve verileri sıralamak için kullanışlı.", keywords: ["satırları sırala", "alfabetik sıralama", "liste sırala", "uzunluğa göre sırala", "sayısal sıralama", "metin sıralayıcı"], placeholder: "Sıralanacak satırları yapıştırın…", mode: "Sıralama ölçütü", alphabetical: "Alfabetik", byLength: "Uzunluk", numeric: "Sayısal", reverse: "Ters", caseInsensitive: "Harf duyarsız" },
  de: { title: "Textzeilen Sortieren", short: "Zeilen alphabetisch, nach Länge oder numerisch sortieren, mit Umkehroption.", description: "Kostenloser Zeilensortierer. Sortieren Sie eine Zeilenliste alphabetisch, nach Länge oder numerisch, optional umgekehrt und ohne Berücksichtigung der Groß-/Kleinschreibung.", keywords: ["zeilen sortieren", "alphabetisch sortieren", "liste sortieren", "nach länge sortieren", "numerisch sortieren"], placeholder: "Zu sortierende Zeilen einfügen…", mode: "Sortieren nach", alphabetical: "Alphabetisch", byLength: "Länge", numeric: "Numerisch", reverse: "Umkehren", caseInsensitive: "Groß/klein ignorieren" },
  fr: { title: "Trier les Lignes de Texte", short: "Triez les lignes par ordre alphabétique, par longueur ou numériquement.", description: "Trieur de lignes gratuit. Triez une liste de lignes par ordre alphabétique, par longueur ou numériquement, avec option d'inversion et insensible à la casse.", keywords: ["trier lignes", "tri alphabétique", "trier liste", "trier par longueur", "tri numérique"], placeholder: "Collez les lignes à trier…", mode: "Trier par", alphabetical: "Alphabétique", byLength: "Longueur", numeric: "Numérique", reverse: "Inverser", caseInsensitive: "Ignorer la casse" },
  es: { title: "Ordenar Líneas de Texto", short: "Ordena líneas alfabéticamente, por longitud o numéricamente, con opción inversa.", description: "Ordenador de líneas gratuito. Ordena una lista de líneas alfabéticamente, por longitud o numéricamente, con opción inversa y sin distinción de mayúsculas.", keywords: ["ordenar líneas", "orden alfabético", "ordenar lista", "ordenar por longitud", "orden numérico"], placeholder: "Pega las líneas a ordenar…", mode: "Ordenar por", alphabetical: "Alfabético", byLength: "Longitud", numeric: "Numérico", reverse: "Invertir", caseInsensitive: "Ignorar mayúsculas" },
  it: { title: "Ordina Righe di Testo", short: "Ordina le righe alfabeticamente, per lunghezza o numericamente, con opzione inversa.", description: "Ordinatore di righe gratuito. Ordina un elenco di righe alfabeticamente, per lunghezza o numericamente, con opzione inversa e senza distinzione di maiuscole.", keywords: ["ordina righe", "ordinamento alfabetico", "ordina elenco", "ordina per lunghezza", "ordinamento numerico"], placeholder: "Incolla le righe da ordinare…", mode: "Ordina per", alphabetical: "Alfabetico", byLength: "Lunghezza", numeric: "Numerico", reverse: "Inverti", caseInsensitive: "Ignora maiuscole" },
  ar: { title: "فرز أسطر النص", short: "افرز الأسطر أبجديًا أو حسب الطول أو رقميًا، مع خيار العكس.", description: "فارز أسطر مجاني. افرز قائمة أسطر أبجديًا أو حسب الطول أو رقميًا، مع خيار العكس وعدم حساسية حالة الأحرف. مفيد لترتيب القوائم والكلمات المفتاحية والبيانات.", keywords: ["فرز الأسطر", "فرز أبجدي", "فرز قائمة", "فرز حسب الطول", "فرز رقمي"], placeholder: "الصق الأسطر للفرز…", mode: "الفرز حسب", alphabetical: "أبجدي", byLength: "الطول", numeric: "رقمي", reverse: "عكس", caseInsensitive: "تجاهل حالة الأحرف" },
  ru: { title: "Сортировка Строк Текста", short: "Сортируйте строки по алфавиту, длине или численно, с опцией реверса.", description: "Бесплатный сортировщик строк. Отсортируйте список строк по алфавиту, длине или численно, с опцией реверса и без учёта регистра. Удобно для упорядочивания списков, ключевых слов и данных.", keywords: ["сортировка строк", "алфавитная сортировка", "сортировать список", "сортировка по длине", "числовая сортировка"], placeholder: "Вставьте строки для сортировки…", mode: "Сортировать по", alphabetical: "Алфавит", byLength: "Длина", numeric: "Числам", reverse: "Реверс", caseInsensitive: "Игнорировать регистр" },
  zh: { title: "文本行排序", short: "按字母、长度或数值对行排序，可选反向。", description: "免费的行排序器。将一组行按字母、长度或数值排序，可选反向和忽略大小写。适合排序列表、关键词和数据。在浏览器中运行。", keywords: ["行排序", "字母排序", "列表排序", "按长度排序", "数值排序"], placeholder: "粘贴要排序的行…", mode: "排序方式", alphabetical: "字母", byLength: "长度", numeric: "数值", reverse: "反向", caseInsensitive: "忽略大小写" },
  ja: { title: "テキスト行の並べ替え", short: "行をアルファベット順・長さ・数値で並べ替え、逆順オプション付き。", description: "無料の行ソーター。行のリストをアルファベット順、長さ、数値で並べ替えます。逆順や大文字小文字を無視するオプションもあります。リストやキーワード、データの整列に便利。", keywords: ["行 並べ替え", "アルファベット順", "リスト ソート", "長さ順", "数値順"], placeholder: "並べ替える行を貼り付け…", mode: "並べ替え基準", alphabetical: "アルファベット順", byLength: "長さ", numeric: "数値", reverse: "逆順", caseInsensitive: "大文字小文字を無視" },
  ko: { title: "텍스트 줄 정렬", short: "줄을 알파벳순, 길이 또는 숫자로 정렬하며 역순 옵션을 제공합니다.", description: "무료 줄 정렬기. 줄 목록을 알파벳순, 길이 또는 숫자로 정렬하며 역순 및 대소문자 무시 옵션이 있습니다. 목록, 키워드, 데이터 정렬에 유용합니다.", keywords: ["줄 정렬", "알파벳 정렬", "목록 정렬", "길이순 정렬", "숫자 정렬"], placeholder: "정렬할 줄을 붙여넣으세요…", mode: "정렬 기준", alphabetical: "알파벳", byLength: "길이", numeric: "숫자", reverse: "역순", caseInsensitive: "대소문자 무시" },
  hi: { title: "टेक्स्ट पंक्तियाँ क्रमबद्ध करें", short: "पंक्तियों को वर्णानुक्रम, लंबाई या संख्यात्मक रूप से क्रमबद्ध करें, उलटने के विकल्प के साथ।", description: "मुफ्त लाइन सॉर्टर। पंक्तियों की सूची को वर्णानुक्रम, लंबाई या संख्यात्मक रूप से क्रमबद्ध करें, वैकल्पिक उलट और केस अनदेखा के साथ। सूची, कीवर्ड और डेटा क्रमबद्ध करने के लिए उपयोगी।", keywords: ["पंक्तियाँ क्रमबद्ध", "वर्णानुक्रम क्रम", "सूची क्रमबद्ध", "लंबाई से क्रमबद्ध", "संख्यात्मक क्रम"], placeholder: "क्रमबद्ध करने के लिए पंक्तियाँ पेस्ट करें…", mode: "इसके अनुसार क्रमबद्ध करें", alphabetical: "वर्णानुक्रम", byLength: "लंबाई", numeric: "संख्यात्मक", reverse: "उलटें", caseInsensitive: "केस अनदेखा करें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
