import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "DNS Health Checker", short: "Check NS, A, AAAA, MX, SPF and DMARC for a domain at once.", description: "Free DNS health checker. Enter a domain to audit its nameservers, A/AAAA addresses, MX mail servers, SPF and DMARC records via Cloudflare DoH — a one-glance report card, all from your browser.", keywords: ["dns health checker", "domain dns audit", "spf dmarc check", "mx record check", "dns report card"], domain: "Domain", run: "Check", check: "Check", status: "Status", detail: "Detail", unavailable: "Lookup unavailable. The DNS service may be rate-limited or blocked by your network.", placeholder: "example.com" },
  pt: { title: "DNS Health Checker", short: "Check NS, A, AAAA, MX, SPF e DMARC for a domain at once.", description: "Gratuito - DNS health checker. Enter a domain para audit its nameservers, A/AAAA addresses, MX mail servers, SPF e DMARC records via Cloudflare DoH â a one-glance report card, todos a partir de seu browser.", keywords: ["dns health checker", "domain dns audit", "spf dmarc check", "mx record check", "dns report card"], domain: "Domínio", run: "Verificar", check: "Verificação", status: "Status", detail: "Detalhe", unavailable: "Consulta indisponível. O serviço DNS pode estar limitado ou bloqueado pela sua rede.", placeholder: "example.com" },
  id: { title: "DNS Health Checker", short: "Check NS, A, AAAA, MX, SPF dan DMARC for a domain at once.", description: "Gratis - DNS health checker. Enter a domain to audit its nameservers, A/AAAA addresses, MX mail servers, SPF dan DMARC records via Cloudflare DoH â a one-glance report card, semua from Anda browser.", keywords: ["dns health checker", "domain dns audit", "spf dmarc check", "mx record check", "dns report card"], domain: "Domain", run: "Periksa", check: "Pemeriksaan", status: "Status", detail: "Detail", unavailable: "Pencarian tidak tersedia. Layanan DNS mungkin dibatasi atau diblokir oleh jaringan Anda.", placeholder: "example.com" },

  tr: { title: "DNS Sağlık Denetleyici", short: "Bir alan adı için NS, A, AAAA, MX, SPF ve DMARC kayıtlarını tek seferde kontrol edin.", description: "Ücretsiz DNS sağlık denetleyici. Bir alan adı girin ve ad sunucularını, A/AAAA adreslerini, MX posta sunucularını, SPF ve DMARC kayıtlarını Cloudflare DoH üzerinden denetleyin — tek bakışta rapor kartı, tamamen tarayıcınızdan.", keywords: ["dns sağlık denetleyici", "alan adı dns denetimi", "spf dmarc kontrol", "mx kaydı kontrol", "dns rapor kartı"], domain: "Alan adı", run: "Kontrol Et", check: "Kontrol", status: "Durum", detail: "Ayrıntı", unavailable: "Sorgu kullanılamıyor. DNS hizmeti hız sınırlı olabilir veya ağınız tarafından engellenmiş olabilir.", placeholder: "example.com" },
  de: { title: "DNS-Health-Checker", short: "NS, A, AAAA, MX, SPF und DMARC einer Domain auf einmal prüfen.", description: "Kostenloser DNS-Health-Checker. Geben Sie eine Domain ein, um Nameserver, A/AAAA-Adressen, MX-Mailserver, SPF- und DMARC-Einträge über Cloudflare DoH zu prüfen — ein Report-Card auf einen Blick, ganz im Browser.", keywords: ["dns health checker", "domain dns audit", "spf dmarc prüfung", "mx-record check", "dns report card"], domain: "Domain", run: "Prüfen", check: "Prüfung", status: "Status", detail: "Detail", unavailable: "Abfrage nicht verfügbar. Der DNS-Dienst ist möglicherweise gedrosselt oder von Ihrem Netzwerk blockiert.", placeholder: "example.com" },
  fr: { title: "Vérificateur de Santé DNS", short: "Vérifiez NS, A, AAAA, MX, SPF et DMARC d'un domaine en une fois.", description: "Vérificateur de santé DNS gratuit. Saisissez un domaine pour auditer ses serveurs de noms, adresses A/AAAA, serveurs MX, enregistrements SPF et DMARC via Cloudflare DoH — un bilan en un coup d'œil, depuis votre navigateur.", keywords: ["vérificateur santé dns", "audit dns domaine", "vérification spf dmarc", "vérification mx", "bilan dns"], domain: "Domaine", run: "Vérifier", check: "Vérification", status: "Statut", detail: "Détail", unavailable: "Recherche indisponible. Le service DNS est peut-être limité ou bloqué par votre réseau.", placeholder: "example.com" },
  es: { title: "Verificador de Salud DNS", short: "Comprueba NS, A, AAAA, MX, SPF y DMARC de un dominio a la vez.", description: "Verificador de salud DNS gratuito. Introduce un dominio para auditar sus servidores de nombres, direcciones A/AAAA, servidores MX, registros SPF y DMARC vía Cloudflare DoH — un informe de un vistazo, desde tu navegador.", keywords: ["verificador salud dns", "auditoría dns dominio", "comprobación spf dmarc", "comprobación mx", "informe dns"], domain: "Dominio", run: "Comprobar", check: "Comprobación", status: "Estado", detail: "Detalle", unavailable: "Consulta no disponible. El servicio DNS puede estar limitado o bloqueado por tu red.", placeholder: "example.com" },
  it: { title: "Verifica Salute DNS", short: "Controlla NS, A, AAAA, MX, SPF e DMARC di un dominio in una volta.", description: "Verifica salute DNS gratuita. Inserisci un dominio per controllare i suoi name server, indirizzi A/AAAA, server MX, record SPF e DMARC tramite Cloudflare DoH — una scheda di valutazione a colpo d'occhio, dal tuo browser.", keywords: ["verifica salute dns", "audit dns dominio", "controllo spf dmarc", "controllo mx", "scheda dns"], domain: "Dominio", run: "Controlla", check: "Controllo", status: "Stato", detail: "Dettaglio", unavailable: "Ricerca non disponibile. Il servizio DNS potrebbe essere limitato o bloccato dalla tua rete.", placeholder: "example.com" },
  ar: { title: "فاحص صحة DNS", short: "افحص NS و A و AAAA و MX و SPF و DMARC لنطاق دفعة واحدة.", description: "أداة فحص صحة DNS مجانية. أدخل نطاقًا لتدقيق خوادم الأسماء وعناوين A/AAAA وخوادم بريد MX وسجلات SPF و DMARC عبر Cloudflare DoH — بطاقة تقرير بنظرة واحدة، من متصفحك.", keywords: ["فاحص صحة dns", "تدقيق dns النطاق", "فحص spf dmarc", "فحص سجل mx", "بطاقة تقرير dns"], domain: "النطاق", run: "فحص", check: "الفحص", status: "الحالة", detail: "التفاصيل", unavailable: "البحث غير متاح. قد تكون خدمة DNS محدودة المعدل أو محظورة من شبكتك.", placeholder: "example.com" },
  ru: { title: "Проверка Здоровья DNS", short: "Проверьте NS, A, AAAA, MX, SPF и DMARC домена за один раз.", description: "Бесплатная проверка здоровья DNS. Введите домен, чтобы проверить его серверы имён, адреса A/AAAA, почтовые серверы MX, записи SPF и DMARC через Cloudflare DoH — отчёт с одного взгляда, прямо из браузера.", keywords: ["проверка здоровья dns", "аудит dns домена", "проверка spf dmarc", "проверка mx", "отчёт dns"], domain: "Домен", run: "Проверить", check: "Проверка", status: "Статус", detail: "Детали", unavailable: "Запрос недоступен. Служба DNS может быть ограничена или заблокирована вашей сетью.", placeholder: "example.com" },
  zh: { title: "DNS 健康检查器", short: "一次性检查域名的 NS、A、AAAA、MX、SPF 和 DMARC。", description: "免费的 DNS 健康检查器。输入域名，通过 Cloudflare DoH 审计其名称服务器、A/AAAA 地址、MX 邮件服务器、SPF 和 DMARC 记录——一目了然的报告卡，全在浏览器中运行。", keywords: ["dns 健康检查器", "域名 dns 审计", "spf dmarc 检查", "mx 记录检查", "dns 报告卡"], domain: "域名", run: "检查", check: "检查项", status: "状态", detail: "详情", unavailable: "查询不可用。DNS 服务可能受到速率限制或被你的网络阻止。", placeholder: "example.com" },
  ja: { title: "DNS ヘルスチェッカー", short: "ドメインの NS・A・AAAA・MX・SPF・DMARC を一度に確認。", description: "無料の DNS ヘルスチェッカー。ドメインを入力すると、ネームサーバー、A/AAAA アドレス、MX メールサーバー、SPF・DMARC レコードを Cloudflare DoH 経由で監査——一目で分かるレポートカードをブラウザ内で表示します。", keywords: ["dns ヘルスチェッカー", "ドメイン dns 監査", "spf dmarc チェック", "mx レコード チェック", "dns レポートカード"], domain: "ドメイン", run: "チェック", check: "チェック項目", status: "ステータス", detail: "詳細", unavailable: "検索を利用できません。DNS サービスがレート制限されているか、ネットワークによってブロックされている可能性があります。", placeholder: "example.com" },
  ko: { title: "DNS 상태 검사기", short: "도메인의 NS, A, AAAA, MX, SPF, DMARC를 한 번에 확인.", description: "무료 DNS 상태 검사기. 도메인을 입력하면 네임서버, A/AAAA 주소, MX 메일 서버, SPF 및 DMARC 레코드를 Cloudflare DoH로 감사합니다 — 한눈에 보는 리포트 카드를 브라우저에서 실행합니다.", keywords: ["dns 상태 검사기", "도메인 dns 감사", "spf dmarc 확인", "mx 레코드 확인", "dns 리포트 카드"], domain: "도메인", run: "검사", check: "검사 항목", status: "상태", detail: "세부 정보", unavailable: "조회를 사용할 수 없습니다. DNS 서비스가 속도 제한되었거나 네트워크에서 차단되었을 수 있습니다.", placeholder: "example.com" },
  hi: { title: "DNS हेल्थ चेकर", short: "किसी डोमेन के NS, A, AAAA, MX, SPF और DMARC एक साथ जाँचें।", description: "मुफ्त DNS हेल्थ चेकर। एक डोमेन दर्ज करें और Cloudflare DoH के माध्यम से उसके नेमसर्वर, A/AAAA पते, MX मेल सर्वर, SPF और DMARC रिकॉर्ड का ऑडिट करें — एक नज़र में रिपोर्ट कार्ड, सब आपके ब्राउज़र से।", keywords: ["dns हेल्थ चेकर", "डोमेन dns ऑडिट", "spf dmarc जाँच", "mx रिकॉर्ड जाँच", "dns रिपोर्ट कार्ड"], domain: "डोमेन", run: "जाँचें", check: "जाँच", status: "स्थिति", detail: "विवरण", unavailable: "लुकअप अनुपलब्ध। DNS सेवा दर-सीमित हो सकती है या आपके नेटवर्क द्वारा अवरुद्ध हो सकती है।", placeholder: "example.com" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
