import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Base32 Encode / Decode", short: "Encode text to Base32 or decode Base32 back to text (RFC 4648).", description: "Free Base32 encoder and decoder. Convert any UTF-8 text to RFC 4648 Base32 and back. Useful for TOTP secrets, identifiers and systems that need case-insensitive encoding. Runs in your browser.", keywords: ["base32", "base32 encode", "base32 decode", "rfc 4648", "base32 converter"], encode: "Encode", decode: "Decode", placeholder: "Enter text or Base32…", invalid: "Invalid Base32 input." },
  pt: { title: "Base32 Encode / Decode", short: "Codificar text para Base32 ou descodificar Base32 back para text (RFC 4648).", description: "Gratuito - Base32 encoder e decoder. Converter any UTF-8 text para RFC 4648 Base32 e back. Useful para TOTP secrets, identifiers e systems that need case-insensitive encoding. Runs no seu navegador.", keywords: ["base32", "base32 encode", "base32 decode", "rfc 4648", "base32 converter"], encode: "Encode", decode: "Decode", placeholder: "Enter text or Base32…", invalid: "Invalid Base32 input." },
  id: { title: "Base32 Encode / Decode", short: "Enkode text to Base32 atau dekode Base32 back to text (RFC 4648).", description: "Gratis - Base32 encoder dan decoder. Konversi any UTF-8 text to RFC 4648 Base32 dan back. Useful for TOTP secrets, identifiers dan systems that need case-insensitive encoding. Runs di browser Anda.", keywords: ["base32", "base32 encode", "base32 decode", "rfc 4648", "base32 converter"], encode: "Encode", decode: "Decode", placeholder: "Enter text or Base32…", invalid: "Invalid Base32 input." },

  tr: { title: "Base32 Kodla / Çöz", short: "Metni Base32'ye kodlayın veya Base32'yi metne çözün (RFC 4648).", description: "Ücretsiz Base32 kodlayıcı ve çözücü. Herhangi bir UTF-8 metni RFC 4648 Base32'ye ve geri çevirin. TOTP gizli anahtarları, tanımlayıcılar ve büyük/küçük harf duyarsız kodlama gerektiren sistemler için kullanışlı.", keywords: ["base32", "base32 kodlama", "base32 çözme", "rfc 4648", "base32 dönüştürücü"], encode: "Kodla", decode: "Çöz", placeholder: "Metin veya Base32 girin…", invalid: "Geçersiz Base32 girdisi." },
  de: { title: "Base32 Kodieren / Dekodieren", short: "Text in Base32 kodieren oder Base32 zurück in Text dekodieren (RFC 4648).", description: "Kostenloser Base32-Encoder und -Decoder. Wandeln Sie beliebigen UTF-8-Text in RFC-4648-Base32 und zurück. Nützlich für TOTP-Secrets, Bezeichner und Systeme mit Groß-/Kleinschreibung-unabhängiger Kodierung.", keywords: ["base32", "base32 kodieren", "base32 dekodieren", "rfc 4648", "base32 konverter"], encode: "Kodieren", decode: "Dekodieren", placeholder: "Text oder Base32 eingeben…", invalid: "Ungültige Base32-Eingabe." },
  fr: { title: "Encoder / Décoder Base32", short: "Encodez du texte en Base32 ou décodez du Base32 en texte (RFC 4648).", description: "Encodeur et décodeur Base32 gratuit. Convertissez tout texte UTF-8 en Base32 RFC 4648 et inversement. Utile pour les secrets TOTP, identifiants et systèmes nécessitant un encodage insensible à la casse.", keywords: ["base32", "encoder base32", "décoder base32", "rfc 4648", "convertisseur base32"], encode: "Encoder", decode: "Décoder", placeholder: "Saisissez du texte ou du Base32…", invalid: "Entrée Base32 invalide." },
  es: { title: "Codificar / Decodificar Base32", short: "Codifica texto a Base32 o decodifica Base32 a texto (RFC 4648).", description: "Codificador y decodificador Base32 gratuito. Convierte cualquier texto UTF-8 a Base32 RFC 4648 y viceversa. Útil para secretos TOTP, identificadores y sistemas que necesitan codificación sin distinción de mayúsculas.", keywords: ["base32", "codificar base32", "decodificar base32", "rfc 4648", "conversor base32"], encode: "Codificar", decode: "Decodificar", placeholder: "Introduce texto o Base32…", invalid: "Entrada Base32 no válida." },
  it: { title: "Codifica / Decodifica Base32", short: "Codifica testo in Base32 o decodifica Base32 in testo (RFC 4648).", description: "Codificatore e decodificatore Base32 gratuito. Converti qualsiasi testo UTF-8 in Base32 RFC 4648 e viceversa. Utile per segreti TOTP, identificatori e sistemi con codifica senza distinzione di maiuscole.", keywords: ["base32", "codifica base32", "decodifica base32", "rfc 4648", "convertitore base32"], encode: "Codifica", decode: "Decodifica", placeholder: "Inserisci testo o Base32…", invalid: "Input Base32 non valido." },
  ar: { title: "ترميز / فك ترميز Base32", short: "رمّز النص إلى Base32 أو فك ترميز Base32 إلى نص (RFC 4648).", description: "مرمّز ومفكّك Base32 مجاني. حوّل أي نص UTF-8 إلى Base32 وفق RFC 4648 والعكس. مفيد لأسرار TOTP والمعرّفات والأنظمة التي تحتاج ترميزًا غير حساس لحالة الأحرف.", keywords: ["base32", "ترميز base32", "فك ترميز base32", "rfc 4648", "محول base32"], encode: "ترميز", decode: "فك الترميز", placeholder: "أدخل نصًا أو Base32…", invalid: "إدخال Base32 غير صالح." },
  ru: { title: "Кодирование / Декодирование Base32", short: "Кодируйте текст в Base32 или декодируйте Base32 обратно (RFC 4648).", description: "Бесплатный кодировщик и декодировщик Base32. Преобразуйте любой UTF-8 текст в Base32 RFC 4648 и обратно. Полезно для TOTP-секретов, идентификаторов и систем с регистронезависимым кодированием.", keywords: ["base32", "кодирование base32", "декодирование base32", "rfc 4648", "конвертер base32"], encode: "Кодировать", decode: "Декодировать", placeholder: "Введите текст или Base32…", invalid: "Недопустимый ввод Base32." },
  zh: { title: "Base32 编码 / 解码", short: "将文本编码为 Base32 或将 Base32 解码为文本（RFC 4648）。", description: "免费的 Base32 编码器和解码器。将任意 UTF-8 文本转换为 RFC 4648 Base32 并还原。适用于 TOTP 密钥、标识符以及需要不区分大小写编码的系统。在浏览器中运行。", keywords: ["base32", "base32 编码", "base32 解码", "rfc 4648", "base32 转换器"], encode: "编码", decode: "解码", placeholder: "输入文本或 Base32…", invalid: "无效的 Base32 输入。" },
  ja: { title: "Base32 エンコード / デコード", short: "テキストを Base32 にエンコード、または Base32 をテキストにデコード（RFC 4648）。", description: "無料の Base32 エンコーダー・デコーダー。任意の UTF-8 テキストを RFC 4648 の Base32 に変換し、元に戻せます。TOTP シークレット、識別子、大文字小文字を区別しないエンコードが必要なシステムに便利。", keywords: ["base32", "base32 エンコード", "base32 デコード", "rfc 4648", "base32 変換"], encode: "エンコード", decode: "デコード", placeholder: "テキストまたは Base32 を入力…", invalid: "無効な Base32 入力です。" },
  ko: { title: "Base32 인코딩 / 디코딩", short: "텍스트를 Base32로 인코딩하거나 Base32를 텍스트로 디코딩합니다(RFC 4648).", description: "무료 Base32 인코더 및 디코더. 모든 UTF-8 텍스트를 RFC 4648 Base32로 변환하고 되돌립니다. TOTP 시크릿, 식별자, 대소문자를 구분하지 않는 인코딩이 필요한 시스템에 유용합니다.", keywords: ["base32", "base32 인코딩", "base32 디코딩", "rfc 4648", "base32 변환기"], encode: "인코딩", decode: "디코딩", placeholder: "텍스트 또는 Base32 입력…", invalid: "잘못된 Base32 입력입니다." },
  hi: { title: "Base32 एन्कोड / डिकोड", short: "टेक्स्ट को Base32 में एन्कोड करें या Base32 को टेक्स्ट में डिकोड करें (RFC 4648)।", description: "मुफ्त Base32 एन्कोडर और डिकोडर। किसी भी UTF-8 टेक्स्ट को RFC 4648 Base32 में और वापस बदलें। TOTP सीक्रेट, पहचानकर्ता और केस-असंवेदनशील एन्कोडिंग वाले सिस्टम के लिए उपयोगी।", keywords: ["base32", "base32 एन्कोड", "base32 डिकोड", "rfc 4648", "base32 कन्वर्टर"], encode: "एन्कोड", decode: "डिकोड", placeholder: "टेक्स्ट या Base32 दर्ज करें…", invalid: "अमान्य Base32 इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
