import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "RDAP Lookup", short: "Query RDAP for a domain, IP or ASN — the modern WHOIS.", description: "Free RDAP lookup tool. Enter a domain, IP address or ASN and it auto-detects the type, queries RDAP (the structured successor to WHOIS) and shows registrar, country, key dates and raw JSON — all from your browser.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domain, IP or ASN", run: "Look up", detected: "Detected type", handle: "Handle", name: "Name", registrar: "Registrar", country: "Country", events: "Events", entities: "Entities", raw: "Raw JSON", placeholder: "example.com, 8.8.8.8 or AS15169", unavailable: "Lookup unavailable. The RDAP service may be rate-limited, redirected, or blocked by your network (CORS)." },
  nl: { title: "RDAP Opzoeken", short: "Query RDAP for a domain, IP or ASN — the modern WHOIS.", description: "Gratis RDAP lookup tool. Enter a domain, IP address or ASN and it auto-detects the type, queries RDAP (the structured successor to WHOIS) and shows registrar, country, key dates and raw JSON — all from uw browser.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domain, IP or ASN", run: "Look up", detected: "Detected type", handle: "Handle", name: "Name", registrar: "Registrar", country: "Country", events: "Events", entities: "Entities", raw: "Raw JSON", placeholder: "example.com, 8.8.8.8 or AS15169", unavailable: "Opzoeken unavailable. The RDAP service may be rate-limited, redirected, or blocked by your network (CORS)." },

  pl: { title: "RDAP Wyszukaj", short: "Query RDAP for a domain, IP or ASN — the modern WHOIS.", description: "Darmowy RDAP lookup narzędzie. Enter a domain, IP address or ASN and it auto-detects the type, queries RDAP (the structured successor to WHOIS) and shows registrar, country, key dates and raw JSON — all from Twoja przeglądarka.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domain, IP or ASN", run: "Look up", detected: "Detected type", handle: "Handle", name: "Name", registrar: "Registrar", country: "Country", events: "Events", entities: "Entities", raw: "Raw JSON", placeholder: "example.com, 8.8.8.8 or AS15169", unavailable: "Wyszukaj unavailable. The RDAP service may be rate-limited, redirected, or blocked by your network (CORS)." },
  pt: { title: "RDAP Lookup", short: "Query RDAP for a domain, IP ou ASN â the modern WHOIS.", description: "Gratuito - RDAP lookup tool. Enter a domain, IP address ou ASN e it auto-detects the type, queries RDAP (the structured successor to WHOIS) e shows registrar, country, key dates e raw JSON â todos a partir de seu browser.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domínio, IP ou ASN", run: "Pesquisar", detected: "Tipo detectado", handle: "Identificador", name: "Nome", registrar: "Registrador", country: "País", events: "Eventos", entities: "Entidades", raw: "JSON bruto", placeholder: "example.com, 8.8.8.8 ou AS15169", unavailable: "Consulta indisponível. O serviço RDAP pode estar limitado, redirecionado ou bloqueado pela sua rede (CORS)." },
  id: { title: "RDAP Lookup", short: "Query RDAP for a domain, IP atau ASN â the modern WHOIS.", description: "Gratis - RDAP lookup tool. Enter a domain, IP address atau ASN dan it auto-detects the type, queries RDAP (the structured successor to WHOIS) dan shows registrar, country, key dates dan raw JSON â semua from Anda browser.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domain, IP atau ASN", run: "Cari", detected: "Tipe terdeteksi", handle: "Handle", name: "Nama", registrar: "Registrar", country: "Negara", events: "Peristiwa", entities: "Entitas", raw: "JSON mentah", placeholder: "example.com, 8.8.8.8 atau AS15169", unavailable: "Pencarian tidak tersedia. Layanan RDAP mungkin dibatasi, dialihkan, atau diblokir oleh jaringan Anda (CORS)." },

  tr: { title: "RDAP Sorgu", short: "Bir alan adı, IP veya ASN için RDAP sorgulayın — modern WHOIS.", description: "Ücretsiz RDAP sorgu aracı. Bir alan adı, IP adresi veya ASN girin; türü otomatik algılar, RDAP'ı (WHOIS'in yapılandırılmış halefi) sorgular ve kayıt kuruluşu, ülke, önemli tarihler ve ham JSON gösterir — tamamen tarayıcınızdan.", keywords: ["rdap sorgu", "whois sorgu", "alan adı rdap", "ip rdap", "asn sorgu"], query: "Alan adı, IP veya ASN", run: "Sorgula", detected: "Algılanan tür", handle: "Tanımlayıcı", name: "Ad", registrar: "Kayıt kuruluşu", country: "Ülke", events: "Olaylar", entities: "Varlıklar", raw: "Ham JSON", placeholder: "example.com, 8.8.8.8 veya AS15169", unavailable: "Sorgu kullanılamıyor. RDAP hizmeti hız sınırlı, yönlendirilmiş veya ağınız tarafından engellenmiş olabilir (CORS)." },
  de: { title: "RDAP-Lookup", short: "RDAP für Domain, IP oder ASN abfragen — das moderne WHOIS.", description: "Kostenloses RDAP-Lookup-Tool. Geben Sie eine Domain, IP-Adresse oder ASN ein; der Typ wird automatisch erkannt, RDAP (der strukturierte WHOIS-Nachfolger) abgefragt und Registrar, Land, wichtige Daten und das rohe JSON angezeigt — alles im Browser.", keywords: ["rdap lookup", "whois lookup", "domain rdap", "ip rdap", "asn lookup"], query: "Domain, IP oder ASN", run: "Abfragen", detected: "Erkannter Typ", handle: "Handle", name: "Name", registrar: "Registrar", country: "Land", events: "Ereignisse", entities: "Entitäten", raw: "Rohes JSON", placeholder: "example.com, 8.8.8.8 oder AS15169", unavailable: "Abfrage nicht verfügbar. Der RDAP-Dienst ist möglicherweise gedrosselt, umgeleitet oder von Ihrem Netzwerk blockiert (CORS)." },
  fr: { title: "Lookup RDAP", short: "Interrogez RDAP pour un domaine, une IP ou un ASN — le WHOIS moderne.", description: "Outil RDAP lookup gratuit. Saisissez un domaine, une adresse IP ou un ASN ; le type est détecté automatiquement, RDAP (le successeur structuré de WHOIS) est interrogé et le registraire, le pays, les dates clés et le JSON brut sont affichés — depuis votre navigateur.", keywords: ["rdap lookup", "whois lookup", "rdap domaine", "rdap ip", "lookup asn"], query: "Domaine, IP ou ASN", run: "Rechercher", detected: "Type détecté", handle: "Identifiant", name: "Nom", registrar: "Registraire", country: "Pays", events: "Événements", entities: "Entités", raw: "JSON brut", placeholder: "example.com, 8.8.8.8 ou AS15169", unavailable: "Recherche indisponible. Le service RDAP est peut-être limité, redirigé ou bloqué par votre réseau (CORS)." },
  es: { title: "Búsqueda RDAP", short: "Consulta RDAP de un dominio, IP o ASN — el WHOIS moderno.", description: "Herramienta RDAP lookup gratuita. Introduce un dominio, dirección IP o ASN; detecta el tipo automáticamente, consulta RDAP (el sucesor estructurado de WHOIS) y muestra el registrador, país, fechas clave y el JSON sin procesar — desde tu navegador.", keywords: ["rdap lookup", "whois lookup", "rdap dominio", "rdap ip", "búsqueda asn"], query: "Dominio, IP o ASN", run: "Buscar", detected: "Tipo detectado", handle: "Identificador", name: "Nombre", registrar: "Registrador", country: "País", events: "Eventos", entities: "Entidades", raw: "JSON sin procesar", placeholder: "example.com, 8.8.8.8 o AS15169", unavailable: "Consulta no disponible. El servicio RDAP puede estar limitado, redirigido o bloqueado por tu red (CORS)." },
  it: { title: "Ricerca RDAP", short: "Interroga RDAP per un dominio, IP o ASN — il WHOIS moderno.", description: "Strumento RDAP lookup gratuito. Inserisci un dominio, indirizzo IP o ASN; rileva automaticamente il tipo, interroga RDAP (il successore strutturato di WHOIS) e mostra registrar, paese, date chiave e il JSON grezzo — dal tuo browser.", keywords: ["rdap lookup", "whois lookup", "rdap dominio", "rdap ip", "ricerca asn"], query: "Dominio, IP o ASN", run: "Cerca", detected: "Tipo rilevato", handle: "Identificatore", name: "Nome", registrar: "Registrar", country: "Paese", events: "Eventi", entities: "Entità", raw: "JSON grezzo", placeholder: "example.com, 8.8.8.8 o AS15169", unavailable: "Ricerca non disponibile. Il servizio RDAP potrebbe essere limitato, reindirizzato o bloccato dalla tua rete (CORS)." },
  ar: { title: "بحث RDAP", short: "استعلم عن RDAP لنطاق أو IP أو ASN — بديل WHOIS الحديث.", description: "أداة بحث RDAP مجانية. أدخل نطاقًا أو عنوان IP أو ASN؛ تكتشف النوع تلقائيًا، تستعلم عن RDAP (الخلف المنظم لـ WHOIS) وتعرض المُسجّل والدولة والتواريخ الرئيسية و JSON الخام — من متصفحك.", keywords: ["بحث rdap", "بحث whois", "rdap النطاق", "rdap ip", "بحث asn"], query: "نطاق أو IP أو ASN", run: "بحث", detected: "النوع المكتشف", handle: "المعرّف", name: "الاسم", registrar: "المُسجّل", country: "الدولة", events: "الأحداث", entities: "الكيانات", raw: "JSON الخام", placeholder: "example.com أو 8.8.8.8 أو AS15169", unavailable: "البحث غير متاح. قد تكون خدمة RDAP محدودة المعدل أو معاد توجيهها أو محظورة من شبكتك (CORS)." },
  ru: { title: "RDAP-запрос", short: "Запросите RDAP для домена, IP или ASN — современный WHOIS.", description: "Бесплатный инструмент RDAP-запроса. Введите домен, IP-адрес или ASN; тип определяется автоматически, выполняется запрос RDAP (структурированный преемник WHOIS) и отображаются регистратор, страна, ключевые даты и необработанный JSON — прямо из браузера.", keywords: ["rdap запрос", "whois запрос", "rdap домена", "rdap ip", "asn запрос"], query: "Домен, IP или ASN", run: "Найти", detected: "Определённый тип", handle: "Идентификатор", name: "Имя", registrar: "Регистратор", country: "Страна", events: "События", entities: "Сущности", raw: "Необработанный JSON", placeholder: "example.com, 8.8.8.8 или AS15169", unavailable: "Запрос недоступен. Служба RDAP может быть ограничена, перенаправлена или заблокирована вашей сетью (CORS)." },
  zh: { title: "RDAP 查询", short: "查询域名、IP 或 ASN 的 RDAP——现代 WHOIS。", description: "免费的 RDAP 查询工具。输入域名、IP 地址或 ASN，它会自动检测类型，查询 RDAP（WHOIS 的结构化继任者），并显示注册商、国家、关键日期和原始 JSON——全在浏览器中运行。", keywords: ["rdap 查询", "whois 查询", "域名 rdap", "ip rdap", "asn 查询"], query: "域名、IP 或 ASN", run: "查询", detected: "检测到的类型", handle: "句柄", name: "名称", registrar: "注册商", country: "国家", events: "事件", entities: "实体", raw: "原始 JSON", placeholder: "example.com、8.8.8.8 或 AS15169", unavailable: "查询不可用。RDAP 服务可能受到速率限制、被重定向或被你的网络阻止（CORS）。" },
  ja: { title: "RDAP 検索", short: "ドメイン・IP・ASN の RDAP を照会——現代の WHOIS。", description: "無料の RDAP 検索ツール。ドメイン・IP アドレス・ASN を入力すると種類を自動検出し、RDAP（WHOIS の構造化された後継）を照会して、レジストラ・国・主要な日付・生の JSON を表示します——すべてブラウザ内で動作します。", keywords: ["rdap 検索", "whois 検索", "ドメイン rdap", "ip rdap", "asn 検索"], query: "ドメイン・IP・ASN", run: "検索", detected: "検出された種類", handle: "ハンドル", name: "名前", registrar: "レジストラ", country: "国", events: "イベント", entities: "エンティティ", raw: "生の JSON", placeholder: "example.com、8.8.8.8、AS15169", unavailable: "検索を利用できません。RDAP サービスがレート制限、リダイレクト、またはネットワークによってブロックされている可能性があります（CORS）。" },
  ko: { title: "RDAP 조회", short: "도메인, IP 또는 ASN의 RDAP 조회 — 현대적인 WHOIS.", description: "무료 RDAP 조회 도구. 도메인, IP 주소 또는 ASN을 입력하면 유형을 자동 감지하고 RDAP(WHOIS의 구조화된 후속)를 조회하여 등록기관, 국가, 주요 날짜 및 원시 JSON을 표시합니다 — 모두 브라우저에서 실행됩니다.", keywords: ["rdap 조회", "whois 조회", "도메인 rdap", "ip rdap", "asn 조회"], query: "도메인, IP 또는 ASN", run: "조회", detected: "감지된 유형", handle: "핸들", name: "이름", registrar: "등록기관", country: "국가", events: "이벤트", entities: "엔티티", raw: "원시 JSON", placeholder: "example.com, 8.8.8.8 또는 AS15169", unavailable: "조회를 사용할 수 없습니다. RDAP 서비스가 속도 제한, 리디렉션되었거나 네트워크에서 차단되었을 수 있습니다(CORS)." },
  hi: { title: "RDAP लुकअप", short: "किसी डोमेन, IP या ASN के लिए RDAP क्वेरी करें — आधुनिक WHOIS।", description: "मुफ्त RDAP लुकअप टूल। एक डोमेन, IP पता या ASN दर्ज करें; यह प्रकार का स्वतः पता लगाता है, RDAP (WHOIS का संरचित उत्तराधिकारी) क्वेरी करता है और रजिस्ट्रार, देश, मुख्य तिथियाँ और कच्चा JSON दिखाता है — सब आपके ब्राउज़र से।", keywords: ["rdap लुकअप", "whois लुकअप", "डोमेन rdap", "ip rdap", "asn लुकअप"], query: "डोमेन, IP या ASN", run: "खोजें", detected: "पता लगाया गया प्रकार", handle: "हैंडल", name: "नाम", registrar: "रजिस्ट्रार", country: "देश", events: "घटनाएँ", entities: "इकाइयाँ", raw: "कच्चा JSON", placeholder: "example.com, 8.8.8.8 या AS15169", unavailable: "लुकअप अनुपलब्ध। RDAP सेवा दर-सीमित, पुनर्निर्देशित या आपके नेटवर्क द्वारा अवरुद्ध हो सकती है (CORS)।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
