import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Reading Time Estimator", short: "Estimate how long a piece of text takes to read.", description: "Free reading time estimator. Paste any text to get the word count, character count and an estimated reading time at a configurable words-per-minute speed — runs entirely in your browser.", keywords: ["reading time estimator", "reading time calculator", "words per minute", "wpm calculator", "minutes to read"], input: "Text", wpm: "Reading speed (WPM)", words: "Words", characters: "Characters", time: "Reading time" },
  tr: { title: "Okuma Süresi Tahmincisi", short: "Bir metnin okunma süresini tahmin edin.", description: "Ücretsiz okuma süresi tahmincisi. Herhangi bir metni yapıştırarak kelime sayısı, karakter sayısı ve yapılandırılabilir kelime/dakika hızında tahmini okuma süresi alın — tamamen tarayıcınızda çalışır.", keywords: ["okuma süresi tahmincisi", "okuma süresi hesaplayıcı", "dakikada kelime", "wpm hesaplayıcı", "okuma dakika"], input: "Metin", wpm: "Okuma hızı (WPM)", words: "Kelime", characters: "Karakter", time: "Okuma süresi" },
  de: { title: "Lesezeit-Schätzer", short: "Schätzen Sie, wie lange ein Text zum Lesen dauert.", description: "Kostenloser Lesezeit-Schätzer. Fügen Sie beliebigen Text ein, um Wortzahl, Zeichenzahl und geschätzte Lesezeit bei konfigurierbarer Wörter-pro-Minute-Geschwindigkeit zu erhalten — läuft vollständig im Browser.", keywords: ["lesezeit schätzer", "lesezeit rechner", "wörter pro minute", "wpm rechner", "minuten lesen"], input: "Text", wpm: "Lesegeschwindigkeit (WPM)", words: "Wörter", characters: "Zeichen", time: "Lesezeit" },
  fr: { title: "Estimateur de Temps de Lecture", short: "Estimez combien de temps un texte prend à lire.", description: "Estimateur de temps de lecture gratuit. Collez n'importe quel texte pour obtenir le nombre de mots, de caractères et un temps de lecture estimé à une vitesse mots/minute configurable — fonctionne entièrement dans votre navigateur.", keywords: ["estimateur temps de lecture", "calculateur temps de lecture", "mots par minute", "calculateur wpm", "minutes de lecture"], input: "Texte", wpm: "Vitesse de lecture (WPM)", words: "Mots", characters: "Caractères", time: "Temps de lecture" },
  es: { title: "Estimador de Tiempo de Lectura", short: "Estima cuánto tarda en leerse un texto.", description: "Estimador de tiempo de lectura gratuito. Pega cualquier texto para obtener el número de palabras, caracteres y un tiempo de lectura estimado a una velocidad de palabras por minuto configurable — funciona completamente en tu navegador.", keywords: ["estimador tiempo lectura", "calculadora tiempo lectura", "palabras por minuto", "calculadora wpm", "minutos de lectura"], input: "Texto", wpm: "Velocidad de lectura (PPM)", words: "Palabras", characters: "Caracteres", time: "Tiempo de lectura" },
  it: { title: "Stimatore Tempo di Lettura", short: "Stima quanto tempo richiede leggere un testo.", description: "Stimatore tempo di lettura gratuito. Incolla qualsiasi testo per ottenere conteggio di parole, caratteri e tempo di lettura stimato a una velocità parole-al-minuto configurabile — funziona interamente nel browser.", keywords: ["stimatore tempo lettura", "calcolatore tempo lettura", "parole al minuto", "calcolatore wpm", "minuti di lettura"], input: "Testo", wpm: "Velocità di lettura (PPM)", words: "Parole", characters: "Caratteri", time: "Tempo di lettura" },
  ar: { title: "مقدّر زمن القراءة", short: "قدّر كم يستغرق قراءة نص ما.", description: "مقدّر زمن قراءة مجاني. الصق أي نص للحصول على عدد الكلمات والأحرف وزمن قراءة مقدَّر بسرعة كلمات-في-الدقيقة قابلة للتخصيص — يعمل بالكامل في متصفحك.", keywords: ["مقدر زمن القراءة", "حاسبة زمن القراءة", "كلمات في الدقيقة", "حاسبة wpm", "دقائق للقراءة"], input: "النص", wpm: "سرعة القراءة (WPM)", words: "الكلمات", characters: "الأحرف", time: "زمن القراءة" },
  ru: { title: "Оценщик времени чтения", short: "Оцените, сколько времени займёт чтение текста.", description: "Бесплатный оценщик времени чтения. Вставьте любой текст, чтобы получить количество слов, символов и оценочное время чтения при настраиваемой скорости слов в минуту — работает полностью в браузере.", keywords: ["оценщик времени чтения", "калькулятор времени чтения", "слов в минуту", "wpm калькулятор", "минуты на чтение"], input: "Текст", wpm: "Скорость чтения (СВМ)", words: "Слова", characters: "Символы", time: "Время чтения" },
  zh: { title: "阅读时间估算器", short: "估算阅读一段文字所需的时间。", description: "免费的阅读时间估算器。粘贴任何文字以获取字数、字符数和按可配置每分钟字数速度估算的阅读时间——完全在浏览器中运行。", keywords: ["阅读时间估算器", "阅读时间计算器", "每分钟字数", "wpm 计算器", "阅读分钟"], input: "文本", wpm: "阅读速度（WPM）", words: "字数", characters: "字符", time: "阅读时间" },
  ja: { title: "読書時間推定", short: "テキストの読書時間を推定します。", description: "無料の読書時間推定ツール。任意のテキストを貼り付けると、単語数、文字数、設定可能な毎分単語数による推定読書時間が得られます——すべてブラウザ内で動作します。", keywords: ["読書時間 推定", "読書時間 計算", "毎分単語数", "wpm 計算", "読書 分"], input: "テキスト", wpm: "読書速度（WPM）", words: "単語", characters: "文字", time: "読書時間" },
  ko: { title: "독서 시간 추정기", short: "글을 읽는 데 걸리는 시간을 추정합니다.", description: "무료 독서 시간 추정기. 텍스트를 붙여넣어 단어 수, 문자 수, 그리고 구성 가능한 분당 단어 속도로 추정한 독서 시간을 확인합니다 — 모두 브라우저에서 실행됩니다.", keywords: ["독서 시간 추정기", "독서 시간 계산기", "분당 단어", "wpm 계산기", "독서 분"], input: "텍스트", wpm: "독서 속도(WPM)", words: "단어", characters: "문자", time: "독서 시간" },
  hi: { title: "पठन समय अनुमानक", short: "किसी पाठ को पढ़ने में लगने वाले समय का अनुमान लगाएं।", description: "मुफ्त पठन समय अनुमानक। किसी भी पाठ को पेस्ट करें और शब्द संख्या, वर्ण संख्या और कॉन्फ़िगर करने योग्य शब्द-प्रति-मिनट गति पर अनुमानित पठन समय पाएं — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["पठन समय अनुमानक", "पठन समय कैलकुलेटर", "शब्द प्रति मिनट", "wpm कैलकुलेटर", "पठन मिनट"], input: "टेक्स्ट", wpm: "पठन गति (WPM)", words: "शब्द", characters: "वर्ण", time: "पठन समय" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
