import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Image Resizer", short: "Resize an image to any width and height.", description: "Free image resizer. Drop a JPG, PNG, WebP or SVG image and set the target width and height (with optional aspect lock) to download a resized copy — runs entirely in your browser, nothing uploaded.", keywords: ["image resizer", "resize image", "resize jpg", "scale image online", "shrink image"], drop: "Drop an image here or click to choose", width: "Width", height: "Height", lockAspect: "Lock aspect ratio", download: "Download" },
  nl: { title: "Afbeelding Regrootter", short: "Regrootte an afbeelding to any breedte and hoogte.", description: "Gratis afbeelding regrootter. Drop a JPG, PNG, WebP or SVG afbeelding and set the target breedte and hoogte (with optional aspect lock) to download a regrootted copy — runs entirely in uw browser, nothing uploaded.", keywords: ["afbeelding regrootter", "regrootte afbeelding", "regrootte jpg", "scale afbeelding online", "shrink afbeelding"], drop: "Drop an afbeelding here or click to choose", width: "Breedte", height: "Hoogte", lockAspect: "Lock aspect ratio", download: "Download" },

  pl: { title: "Obraz Rerozmiarr", short: "Rerozmiar an obraz to any szerokość and wysokość.", description: "Darmowy obraz rerozmiarr. Drop a JPG, PNG, WebP or SVG obraz and set the target szerokość and wysokość (with optional aspect lock) to download a rerozmiard copy — runs entirely w Twojej przeglądarce, nothing uploaded.", keywords: ["obraz rerozmiarr", "rerozmiar obraz", "rerozmiar jpg", "scale obraz online", "shrink obraz"], drop: "Drop an obraz here or click to choose", width: "Szerokość", height: "Wysokość", lockAspect: "Lock aspect ratio", download: "Download" },
  pt: { title: "Redimensionador de Image", short: "Resize an image para any width e height.", description: "Gratuito - image resizer. Drop a JPG, PNG, WebP ou SVG image e set the target width e height (com optional aspect lock) para descarregar a resized copy â runs entirely no seu navegador, nothing uploaded.", keywords: ["image resizer", "resize image", "resize jpg", "scale image online", "shrink image"], drop: "Drop an image here or click to choose", width: "Width", height: "Height", lockAspect: "Lock aspect ratio", download: "Download" },
  id: { title: "Pengubah Ukuran Image", short: "Resize an image to any width dan height.", description: "Gratis - image resizer. Drop a JPG, PNG, WebP atau SVG image dan set the target width dan height (with optional aspect lock) to unduh a resized copy â runs entirely di browser Anda, nothing uploaded.", keywords: ["image resizer", "resize image", "resize jpg", "scale image online", "shrink image"], drop: "Drop an image here or click to choose", width: "Width", height: "Height", lockAspect: "Lock aspect ratio", download: "Download" },

  tr: { title: "Görsel Yeniden Boyutlandırıcı", short: "Bir görseli istediğiniz genişlik ve yüksekliğe yeniden boyutlandırın.", description: "Ücretsiz görsel yeniden boyutlandırıcı. Bir JPG, PNG, WebP veya SVG görseli bırakın, hedef genişlik ve yüksekliği (isteğe bağlı en boy kilidi ile) ayarlayın ve yeniden boyutlandırılmış kopyayı indirin — tamamen tarayıcınızda çalışır, hiçbir şey yüklenmez.", keywords: ["görsel yeniden boyutlandırma", "görseli boyutlandır", "jpg boyutlandır", "online görsel ölçeklendir", "görseli küçült"], drop: "Bir görsel bırakın veya seçmek için tıklayın", width: "Genişlik", height: "Yükseklik", lockAspect: "En boy oranını kilitle", download: "İndir" },
  de: { title: "Bild-Größenänderung", short: "Ändern Sie die Größe eines Bildes auf beliebige Breite und Höhe.", description: "Kostenloser Bildgrößen-Änderer. Legen Sie ein JPG-, PNG-, WebP- oder SVG-Bild ab und stellen Sie Zielbreite und -höhe (mit optionaler Seitenverhältnis-Sperre) ein, um eine angepasste Kopie herunterzuladen — läuft vollständig im Browser, nichts wird hochgeladen.", keywords: ["bild größe ändern", "bild größe", "jpg größe ändern", "bild skalieren online", "bild verkleinern"], drop: "Bild hier ablegen oder klicken zum Auswählen", width: "Breite", height: "Höhe", lockAspect: "Seitenverhältnis sperren", download: "Herunterladen" },
  fr: { title: "Redimensionneur d'Image", short: "Redimensionnez une image à n'importe quelle largeur et hauteur.", description: "Redimensionneur d'image gratuit. Déposez une image JPG, PNG, WebP ou SVG et définissez la largeur et la hauteur cibles (avec verrouillage du rapport d'aspect optionnel) pour télécharger une copie redimensionnée — fonctionne entièrement dans votre navigateur, rien n'est envoyé.", keywords: ["redimensionneur image", "redimensionner image", "redimensionner jpg", "redimensionner image en ligne", "réduire image"], drop: "Déposez une image ici ou cliquez pour choisir", width: "Largeur", height: "Hauteur", lockAspect: "Verrouiller le rapport d'aspect", download: "Télécharger" },
  es: { title: "Redimensionador de Imágenes", short: "Redimensiona una imagen a cualquier ancho y alto.", description: "Redimensionador de imágenes gratuito. Arrastra una imagen JPG, PNG, WebP o SVG y establece el ancho y alto objetivo (con bloqueo de relación de aspecto opcional) para descargar una copia redimensionada — funciona completamente en tu navegador, nada se sube.", keywords: ["redimensionador imagen", "redimensionar imagen", "redimensionar jpg", "redimensionar imagen online", "reducir imagen"], drop: "Arrastra una imagen aquí o haz clic para elegir", width: "Ancho", height: "Alto", lockAspect: "Bloquear relación de aspecto", download: "Descargar" },
  it: { title: "Ridimensionatore di Immagini", short: "Ridimensiona un'immagine a qualsiasi larghezza e altezza.", description: "Ridimensionatore di immagini gratuito. Trascina un'immagine JPG, PNG, WebP o SVG e imposta larghezza e altezza target (con blocco aspetto opzionale) per scaricare una copia ridimensionata — funziona interamente nel browser, nulla viene caricato.", keywords: ["ridimensiona immagine", "ridimensionatore immagine", "ridimensiona jpg", "ridimensiona immagine online", "ridurre immagine"], drop: "Trascina un'immagine qui o clicca per scegliere", width: "Larghezza", height: "Altezza", lockAspect: "Blocca aspetto", download: "Scarica" },
  ar: { title: "محول حجم الصورة", short: "غيّر حجم الصورة إلى أي عرض وارتفاع.", description: "محول حجم صور مجاني. أفلِت صورة JPG أو PNG أو WebP أو SVG وحدد العرض والارتفاع المستهدفين (مع قفل النسبة الاختياري) لتنزيل نسخة بحجم جديد — يعمل بالكامل في متصفحك، لا شيء يُرفع.", keywords: ["تغيير حجم الصورة", "محول حجم الصورة", "تغيير حجم jpg", "تغيير حجم الصورة عبر الإنترنت", "تصغير الصورة"], drop: "أفلِت صورة هنا أو انقر للاختيار", width: "العرض", height: "الارتفاع", lockAspect: "قفل النسبة", download: "تنزيل" },
  ru: { title: "Изменение размера изображения", short: "Измените размер изображения до любой ширины и высоты.", description: "Бесплатный инструмент изменения размера изображения. Перетащите JPG, PNG, WebP или SVG и задайте целевую ширину и высоту (с опциональной блокировкой пропорций), чтобы скачать изменённую копию — работает полностью в браузере, ничего не загружается.", keywords: ["изменить размер изображения", "ресайз изображения", "ресайз jpg", "изменить размер изображения онлайн", "уменьшить изображение"], drop: "Перетащите изображение сюда или нажмите для выбора", width: "Ширина", height: "Высота", lockAspect: "Блокировать пропорции", download: "Скачать" },
  zh: { title: "图片尺寸调整", short: "将图片调整为任意宽度和高度。", description: "免费的图片尺寸调整器。拖入 JPG、PNG、WebP 或 SVG 图片，设置目标宽度和高度（可选锁定宽高比），下载调整后的副本——完全在浏览器中运行，不上传任何内容。", keywords: ["图片调整大小", "调整图片", "jpg 调整大小", "在线图片缩放", "缩小图片"], drop: "将图片拖到此处或点击选择", width: "宽度", height: "高度", lockAspect: "锁定宽高比", download: "下载" },
  ja: { title: "画像リサイズ", short: "画像を任意の幅と高さにリサイズ。", description: "無料の画像リサイズツール。JPG、PNG、WebP、SVG 画像をドロップし、目標の幅と高さ（任意でアスペクト比ロック）を設定してリサイズ済みのコピーをダウンロード——すべてブラウザ内で動作、アップロードなし。", keywords: ["画像 リサイズ", "画像 サイズ変更", "jpg リサイズ", "オンライン 画像 スケール", "画像 縮小"], drop: "画像をここにドロップまたはクリックして選択", width: "幅", height: "高さ", lockAspect: "アスペクト比をロック", download: "ダウンロード" },
  ko: { title: "이미지 크기 조정", short: "이미지를 원하는 너비와 높이로 조정합니다.", description: "무료 이미지 크기 조정기. JPG, PNG, WebP, SVG 이미지를 드롭하고 목표 너비와 높이를 설정해(선택적 가로세로 비율 잠금) 크기가 조정된 사본을 다운로드하세요 — 모두 브라우저에서 실행, 업로드 없음.", keywords: ["이미지 크기 조정", "이미지 리사이즈", "jpg 크기 조정", "온라인 이미지 스케일", "이미지 축소"], drop: "여기에 이미지를 드롭하거나 클릭하여 선택", width: "너비", height: "높이", lockAspect: "가로세로 비율 잠금", download: "다운로드" },
  hi: { title: "इमेज रिसाइज़र", short: "एक इमेज को किसी भी चौड़ाई और ऊँचाई पर रिसाइज़ करें।", description: "मुफ्त इमेज रिसाइज़र। एक JPG, PNG, WebP या SVG इमेज छोड़ें और लक्ष्य चौड़ाई और ऊँचाई सेट करें (वैकल्पिक आस्पेक्ट लॉक के साथ) और रिसाइज़ की हुई कॉपी डाउनलोड करें — पूरी तरह आपके ब्राउज़र में चलता है, कुछ भी अपलोड नहीं होता।", keywords: ["इमेज रिसाइज़र", "इमेज रिसाइज़", "jpg रिसाइज़", "ऑनलाइन इमेज स्केल", "इमेज छोटी करें"], drop: "यहाँ एक इमेज छोड़ें या चुनने के लिए क्लिक करें", width: "चौड़ाई", height: "ऊँचाई", lockAspect: "आस्पेक्ट रेशियो लॉक करें", download: "डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
