import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Color Contrast Checker (WCAG)", short: "Check the contrast ratio between two colors against WCAG AA and AAA.", description: "Free WCAG color contrast checker. Enter a foreground and background color (HEX, RGB or HSL) to get the contrast ratio and whether it passes WCAG AA and AAA for normal and large text, with a live preview.", keywords: ["color contrast checker", "wcag contrast", "contrast ratio", "accessibility checker", "aa aaa contrast"], foreground: "Text color", background: "Background", ratio: "Contrast ratio", normalText: "Normal text", largeText: "Large text", pass: "Pass", fail: "Fail", invalid: "Enter valid colors.", sample: "The quick brown fox jumps over the lazy dog." },
  tr: { title: "Renk Kontrastı Denetleyici (WCAG)", short: "İki renk arasındaki kontrast oranını WCAG AA ve AAA'ya göre kontrol edin.", description: "Ücretsiz WCAG renk kontrastı denetleyici. Bir ön plan ve arka plan rengi (HEX, RGB veya HSL) girin; kontrast oranını ve normal ile büyük metin için WCAG AA ve AAA'yı geçip geçmediğini canlı önizlemeyle öğrenin.", keywords: ["renk kontrastı denetleyici", "wcag kontrast", "kontrast oranı", "erişilebilirlik", "aa aaa kontrast"], foreground: "Metin rengi", background: "Arka plan", ratio: "Kontrast oranı", normalText: "Normal metin", largeText: "Büyük metin", pass: "Geçti", fail: "Kaldı", invalid: "Geçerli renkler girin.", sample: "Pijamalı hasta yağız şoföre çabucak güvendi." },
  de: { title: "Farbkontrast-Prüfer (WCAG)", short: "Prüfen Sie das Kontrastverhältnis zweier Farben gegen WCAG AA und AAA.", description: "Kostenloser WCAG-Farbkontrast-Prüfer. Geben Sie eine Vordergrund- und Hintergrundfarbe (HEX, RGB oder HSL) ein, um das Kontrastverhältnis und das Bestehen von WCAG AA/AAA für normalen und großen Text mit Live-Vorschau zu sehen.", keywords: ["farbkontrast prüfer", "wcag kontrast", "kontrastverhältnis", "barrierefreiheit", "aa aaa kontrast"], foreground: "Textfarbe", background: "Hintergrund", ratio: "Kontrastverhältnis", normalText: "Normaler Text", largeText: "Großer Text", pass: "Bestanden", fail: "Durchgefallen", invalid: "Gültige Farben eingeben.", sample: "Franz jagt im Taxi quer durch Bayern." },
  fr: { title: "Vérificateur de Contraste (WCAG)", short: "Vérifiez le rapport de contraste entre deux couleurs selon WCAG AA et AAA.", description: "Vérificateur de contraste WCAG gratuit. Saisissez une couleur de texte et d'arrière-plan (HEX, RGB ou HSL) pour obtenir le rapport de contraste et savoir s'il respecte WCAG AA et AAA pour le texte normal et grand, avec un aperçu.", keywords: ["vérificateur de contraste", "contraste wcag", "rapport de contraste", "accessibilité", "contraste aa aaa"], foreground: "Couleur du texte", background: "Arrière-plan", ratio: "Rapport de contraste", normalText: "Texte normal", largeText: "Grand texte", pass: "Réussi", fail: "Échec", invalid: "Saisissez des couleurs valides.", sample: "Portez ce vieux whisky au juge blond qui fume." },
  es: { title: "Verificador de Contraste de Color (WCAG)", short: "Comprueba la relación de contraste entre dos colores según WCAG AA y AAA.", description: "Verificador de contraste WCAG gratuito. Introduce un color de texto y de fondo (HEX, RGB o HSL) para obtener la relación de contraste y si cumple WCAG AA y AAA para texto normal y grande, con vista previa.", keywords: ["verificador de contraste", "contraste wcag", "relación de contraste", "accesibilidad", "contraste aa aaa"], foreground: "Color del texto", background: "Fondo", ratio: "Relación de contraste", normalText: "Texto normal", largeText: "Texto grande", pass: "Pasa", fail: "Falla", invalid: "Introduce colores válidos.", sample: "El veloz murciélago hindú comía feliz cardillo." },
  it: { title: "Verificatore di Contrasto Colore (WCAG)", short: "Verifica il rapporto di contrasto tra due colori rispetto a WCAG AA e AAA.", description: "Verificatore di contrasto WCAG gratuito. Inserisci un colore di testo e di sfondo (HEX, RGB o HSL) per ottenere il rapporto di contrasto e se supera WCAG AA e AAA per testo normale e grande, con anteprima.", keywords: ["verificatore contrasto", "contrasto wcag", "rapporto di contrasto", "accessibilità", "contrasto aa aaa"], foreground: "Colore del testo", background: "Sfondo", ratio: "Rapporto di contrasto", normalText: "Testo normale", largeText: "Testo grande", pass: "Superato", fail: "Fallito", invalid: "Inserisci colori validi.", sample: "Ma la volpe, col suo balzo, ha raggiunto il quieto Fido." },
  ar: { title: "فاحص تباين الألوان (WCAG)", short: "تحقق من نسبة التباين بين لونين وفق WCAG AA و AAA.", description: "فاحص تباين ألوان WCAG مجاني. أدخل لون النص والخلفية (HEX أو RGB أو HSL) للحصول على نسبة التباين وما إذا كانت تجتاز WCAG AA و AAA للنص العادي والكبير، مع معاينة حية.", keywords: ["فاحص تباين الألوان", "تباين wcag", "نسبة التباين", "إمكانية الوصول", "تباين aa aaa"], foreground: "لون النص", background: "الخلفية", ratio: "نسبة التباين", normalText: "نص عادي", largeText: "نص كبير", pass: "ناجح", fail: "فاشل", invalid: "أدخل ألوانًا صالحة.", sample: "نص تجريبي للمعاينة." },
  ru: { title: "Проверка Контраста Цвета (WCAG)", short: "Проверьте коэффициент контраста двух цветов по WCAG AA и AAA.", description: "Бесплатная проверка контраста WCAG. Введите цвет текста и фона (HEX, RGB или HSL), чтобы получить коэффициент контраста и соответствие WCAG AA и AAA для обычного и крупного текста, с предпросмотром.", keywords: ["проверка контраста", "контраст wcag", "коэффициент контраста", "доступность", "контраст aa aaa"], foreground: "Цвет текста", background: "Фон", ratio: "Коэффициент контраста", normalText: "Обычный текст", largeText: "Крупный текст", pass: "Пройдено", fail: "Не пройдено", invalid: "Введите корректные цвета.", sample: "Съешь же ещё этих мягких французских булок." },
  zh: { title: "颜色对比度检查器 (WCAG)", short: "依据 WCAG AA 和 AAA 检查两种颜色之间的对比度。", description: "免费的 WCAG 颜色对比度检查器。输入前景色和背景色（HEX、RGB 或 HSL），即可获得对比度以及是否通过普通和大号文本的 WCAG AA 和 AAA，并提供实时预览。", keywords: ["颜色对比度检查", "wcag对比度", "对比度", "无障碍", "aa aaa对比度"], foreground: "文本颜色", background: "背景", ratio: "对比度", normalText: "普通文本", largeText: "大号文本", pass: "通过", fail: "未通过", invalid: "请输入有效的颜色。", sample: "快速的棕色狐狸跳过懒狗。" },
  ja: { title: "カラーコントラストチェッカー (WCAG)", short: "2 色間のコントラスト比を WCAG AA・AAA に対して確認します。", description: "無料の WCAG カラーコントラストチェッカー。前景色と背景色（HEX・RGB・HSL）を入力すると、コントラスト比と、通常・大きい文字での WCAG AA・AAA 合否がライブプレビューとともに表示されます。", keywords: ["カラーコントラスト チェック", "wcag コントラスト", "コントラスト比", "アクセシビリティ", "aa aaa コントラスト"], foreground: "文字色", background: "背景", ratio: "コントラスト比", normalText: "通常テキスト", largeText: "大きいテキスト", pass: "合格", fail: "不合格", invalid: "有効な色を入力してください。", sample: "いろはにほへと ちりぬるを。" },
  ko: { title: "색상 대비 검사기 (WCAG)", short: "두 색상 간의 대비율을 WCAG AA 및 AAA에 대해 확인합니다.", description: "무료 WCAG 색상 대비 검사기. 전경색과 배경색(HEX, RGB 또는 HSL)을 입력하면 대비율과 보통/큰 텍스트에 대한 WCAG AA 및 AAA 통과 여부를 미리보기와 함께 확인할 수 있습니다.", keywords: ["색상 대비 검사기", "wcag 대비", "대비율", "접근성", "aa aaa 대비"], foreground: "텍스트 색", background: "배경", ratio: "대비율", normalText: "보통 텍스트", largeText: "큰 텍스트", pass: "통과", fail: "실패", invalid: "유효한 색상을 입력하세요.", sample: "다람쥐 헌 쳇바퀴에 타고파." },
  hi: { title: "रंग कंट्रास्ट चेकर (WCAG)", short: "दो रंगों के बीच कंट्रास्ट अनुपात को WCAG AA और AAA के विरुद्ध जांचें।", description: "मुफ्त WCAG रंग कंट्रास्ट चेकर। एक अग्रभूमि और पृष्ठभूमि रंग (HEX, RGB या HSL) दर्ज करें और कंट्रास्ट अनुपात तथा यह सामान्य व बड़े टेक्स्ट के लिए WCAG AA और AAA पास करता है या नहीं, लाइव प्रीव्यू के साथ पाएं।", keywords: ["रंग कंट्रास्ट चेकर", "wcag कंट्रास्ट", "कंट्रास्ट अनुपात", "एक्सेसिबिलिटी", "aa aaa कंट्रास्ट"], foreground: "टेक्स्ट रंग", background: "पृष्ठभूमि", ratio: "कंट्रास्ट अनुपात", normalText: "सामान्य टेक्स्ट", largeText: "बड़ा टेक्स्ट", pass: "पास", fail: "फेल", invalid: "मान्य रंग दर्ज करें।", sample: "तेज़ भूरी लोमड़ी आलसी कुत्ते के ऊपर कूदती है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
