import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Bionic Reading Converter", short: "Bold the first half of every word to aid skim-reading.", description: "Free Bionic Reading converter. Paste text and bold the leading portion of every word to help your eyes skim faster — adjust the fraction to taste. Runs entirely in your browser.", keywords: ["bionic reading", "bionic reading converter", "bold reading", "skim reading", "reading aid"], input: "Text", fraction: "Bold fraction", preview: "Preview" },
  pt: { title: "Bionic Reading Converter", short: "Bold the first half of every word to aid skim-reading.", description: "Free Bionic Reading converter. Paste text and bold the leading portion of every word to help your eyes skim faster — adjust the fraction to taste. Runs entirely in your browser.", keywords: ["bionic reading", "bionic reading converter", "bold reading", "skim reading", "reading aid"], input: "Text", fraction: "Bold fraction", preview: "Preview" },
  id: { title: "Bionic Reading Converter", short: "Bold the first half of every word to aid skim-reading.", description: "Free Bionic Reading converter. Paste text and bold the leading portion of every word to help your eyes skim faster — adjust the fraction to taste. Runs entirely in your browser.", keywords: ["bionic reading", "bionic reading converter", "bold reading", "skim reading", "reading aid"], input: "Text", fraction: "Bold fraction", preview: "Preview" },

  tr: { title: "Bionic Okuma Dönüştürücü", short: "Her kelimenin ilk yarısını kalınlaştırarak hızlı tarama sağlayın.", description: "Ücretsiz Bionic Okuma dönüştürücü. Metni yapıştırın ve her kelimenin baş kısmını kalınlaştırarak gözünüzün daha hızlı taramasına yardım edin — oranı zevkinize göre ayarlayın. Tamamen tarayıcınızda çalışır.", keywords: ["bionic okuma", "bionic okuma dönüştürücü", "kalın okuma", "hızlı tarama", "okuma yardımcısı"], input: "Metin", fraction: "Kalın oranı", preview: "Önizleme" },
  de: { title: "Bionic-Reading-Konverter", short: "Erste Hälfte jedes Wortes fett markieren, um schnelles Überfliegen zu erleichtern.", description: "Kostenloser Bionic-Reading-Konverter. Fügen Sie Text ein und markieren Sie den Anfang jedes Wortes fett, damit Ihre Augen schneller scannen — Anteil nach Geschmack einstellbar. Läuft vollständig im Browser.", keywords: ["bionic reading", "bionic reading konverter", "fett lesen", "schnelles überfliegen", "lesehilfe"], input: "Text", fraction: "Fett-Anteil", preview: "Vorschau" },
  fr: { title: "Convertisseur Bionic Reading", short: "Mettez en gras la première moitié de chaque mot pour faciliter la lecture rapide.", description: "Convertisseur Bionic Reading gratuit. Collez du texte et mettez en gras le début de chaque mot pour aider vos yeux à parcourir plus vite — ajustez la fraction au goût. Fonctionne entièrement dans votre navigateur.", keywords: ["bionic reading", "convertisseur bionic reading", "lecture en gras", "lecture rapide", "aide à la lecture"], input: "Texte", fraction: "Fraction en gras", preview: "Aperçu" },
  es: { title: "Convertidor Bionic Reading", short: "Pon en negrita la primera mitad de cada palabra para facilitar la lectura rápida.", description: "Convertidor Bionic Reading gratuito. Pega texto y pon en negrita la parte inicial de cada palabra para que tus ojos escaneen más rápido — ajusta la fracción a gusto. Funciona completamente en tu navegador.", keywords: ["bionic reading", "convertidor bionic reading", "lectura en negrita", "lectura rápida", "ayuda lectura"], input: "Texto", fraction: "Fracción en negrita", preview: "Vista previa" },
  it: { title: "Convertitore Bionic Reading", short: "Metti in grassetto la prima metà di ogni parola per facilitare la lettura veloce.", description: "Convertitore Bionic Reading gratuito. Incolla testo e metti in grassetto la parte iniziale di ogni parola per aiutare gli occhi a scorrere più rapidamente — regola la frazione a piacere. Funziona interamente nel browser.", keywords: ["bionic reading", "convertitore bionic reading", "lettura in grassetto", "lettura veloce", "aiuto lettura"], input: "Testo", fraction: "Frazione in grassetto", preview: "Anteprima" },
  ar: { title: "محوّل Bionic Reading", short: "اجعل النصف الأول من كل كلمة عريضًا لتسهيل القراءة السريعة.", description: "محوّل Bionic Reading مجاني. الصق نصًا واجعل الجزء الأول من كل كلمة عريضًا لتساعد عينيك على المسح بشكل أسرع — اضبط النسبة حسب الذوق. يعمل بالكامل في متصفحك.", keywords: ["bionic reading", "محول bionic reading", "قراءة عريضة", "قراءة سريعة", "مساعد القراءة"], input: "النص", fraction: "نسبة العريض", preview: "معاينة" },
  ru: { title: "Конвертер Bionic Reading", short: "Выделяйте жирным первую половину каждого слова для быстрого чтения.", description: "Бесплатный конвертер Bionic Reading. Вставьте текст и выделяйте жирным начало каждого слова, чтобы глаза быстрее сканировали — настраивайте долю по вкусу. Работает полностью в браузере.", keywords: ["bionic reading", "конвертер bionic reading", "жирное чтение", "быстрое чтение", "помощник чтения"], input: "Текст", fraction: "Доля жирного", preview: "Превью" },
  zh: { title: "Bionic Reading 转换器", short: "将每个单词的前半部分加粗以辅助快速浏览。", description: "免费的 Bionic Reading 转换器。粘贴文字并将每个单词的前半部分加粗，让你的眼睛更快扫读——按喜好调整比例。完全在浏览器中运行。", keywords: ["bionic reading", "bionic reading 转换器", "粗体阅读", "快速浏览", "阅读辅助"], input: "文本", fraction: "粗体比例", preview: "预览" },
  ja: { title: "バイオニックリーディング変換", short: "各単語の前半を太字にして速読を助けます。", description: "無料のバイオニックリーディング変換ツール。テキストを貼り付け、各単語の先頭部分を太字にして目の走査を高速化します——比率は好みに合わせて調整可能。すべてブラウザ内で動作します。", keywords: ["バイオニックリーディング", "バイオニックリーディング 変換", "太字 読書", "速読", "読書 補助"], input: "テキスト", fraction: "太字の割合", preview: "プレビュー" },
  ko: { title: "Bionic Reading 변환기", short: "각 단어의 앞 절반을 굵게 표시해 빠른 훑어보기를 돕습니다.", description: "무료 Bionic Reading 변환기. 텍스트를 붙여넣고 각 단어의 앞부분을 굵게 표시해 눈이 더 빨리 훑을 수 있도록 도와줍니다 — 비율은 취향대로 조정하세요. 모두 브라우저에서 실행됩니다.", keywords: ["bionic reading", "bionic reading 변환기", "굵은 글씨 읽기", "빠른 읽기", "읽기 보조"], input: "텍스트", fraction: "굵게 비율", preview: "미리보기" },
  hi: { title: "Bionic Reading कन्वर्टर", short: "स्किम-रीडिंग में मदद के लिए हर शब्द के पहले आधे को बोल्ड करें।", description: "मुफ्त Bionic Reading कन्वर्टर। टेक्स्ट पेस्ट करें और हर शब्द के शुरुआती भाग को बोल्ड करें ताकि आपकी आँखें तेज़ी से स्कैन कर सकें — अनुपात अपनी पसंद से समायोजित करें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["bionic reading", "bionic reading कन्वर्टर", "बोल्ड पठन", "स्किम पठन", "पठन सहायता"], input: "टेक्स्ट", fraction: "बोल्ड अनुपात", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
