import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text Shadow Generator", short: "Create CSS text-shadow code with a live preview.", description: "Free CSS text-shadow generator. Adjust offset, blur and color to get ready-to-paste text-shadow CSS with a live preview.", keywords: ["text shadow generator", "css text shadow", "text-shadow code", "text shadow css", "text effect"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", color: "Color", preview: "Preview" },
  pt: { title: "Text Shadow Generator", short: "Create CSS text-shadow code with a live preview.", description: "Free CSS text-shadow generator. Adjust offset, blur and color to get ready-to-paste text-shadow CSS with a live preview.", keywords: ["text shadow generator", "css text shadow", "text-shadow code", "text shadow css", "text effect"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", color: "Color", preview: "Preview" },
  id: { title: "Text Shadow Generator", short: "Create CSS text-shadow code with a live preview.", description: "Free CSS text-shadow generator. Adjust offset, blur and color to get ready-to-paste text-shadow CSS with a live preview.", keywords: ["text shadow generator", "css text shadow", "text-shadow code", "text shadow css", "text effect"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Blur", color: "Color", preview: "Preview" },

  tr: { title: "Text Shadow Oluşturucu", short: "Canlı önizlemeyle CSS text-shadow kodu oluşturun.", description: "Ücretsiz CSS text-shadow oluşturucu. Konum, bulanıklık ve renk ayarlayarak canlı önizlemeyle yapıştırmaya hazır text-shadow CSS alın.", keywords: ["text shadow oluşturucu", "css text shadow", "text-shadow kodu", "metin gölge css", "metin efekti"], offsetX: "Konum X", offsetY: "Konum Y", blur: "Bulanıklık", color: "Renk", preview: "Önizleme" },
  de: { title: "Text-Shadow-Generator", short: "Erstellen Sie CSS-text-shadow-Code mit Live-Vorschau.", description: "Kostenloser CSS-text-shadow-Generator. Versatz, Unschärfe und Farbe anpassen, um einsatzbereiten text-shadow-CSS mit Live-Vorschau zu erhalten.", keywords: ["text shadow generator", "css text shadow", "text-shadow code", "textschatten css", "texteffekt"], offsetX: "Versatz X", offsetY: "Versatz Y", blur: "Unschärfe", color: "Farbe", preview: "Vorschau" },
  fr: { title: "Générateur de Text-Shadow", short: "Créez du code CSS text-shadow avec aperçu en direct.", description: "Générateur de text-shadow CSS gratuit. Ajustez le décalage, le flou et la couleur pour obtenir du CSS text-shadow prêt à coller avec aperçu en direct.", keywords: ["générateur text shadow", "css text shadow", "code text-shadow", "ombre texte css", "effet texte"], offsetX: "Décalage X", offsetY: "Décalage Y", blur: "Flou", color: "Couleur", preview: "Aperçu" },
  es: { title: "Generador de Text-Shadow", short: "Crea código CSS text-shadow con vista previa en vivo.", description: "Generador de text-shadow CSS gratuito. Ajusta el desplazamiento, desenfoque y color para obtener CSS text-shadow listo para pegar con vista previa en vivo.", keywords: ["generador text shadow", "css text shadow", "código text-shadow", "sombra texto css", "efecto texto"], offsetX: "Desplazamiento X", offsetY: "Desplazamiento Y", blur: "Desenfoque", color: "Color", preview: "Vista previa" },
  it: { title: "Generatore di Text-Shadow", short: "Crea codice CSS text-shadow con anteprima dal vivo.", description: "Generatore di text-shadow CSS gratuito. Regola offset, sfocatura e colore per ottenere CSS text-shadow pronto da incollare con anteprima dal vivo.", keywords: ["generatore text shadow", "css text shadow", "codice text-shadow", "ombra testo css", "effetto testo"], offsetX: "Offset X", offsetY: "Offset Y", blur: "Sfocatura", color: "Colore", preview: "Anteprima" },
  ar: { title: "مولّد ظل النص", short: "أنشئ كود CSS text-shadow مع معاينة حية.", description: "مولّد text-shadow مجاني. اضبط الإزاحة والتمويه واللون للحصول على كود text-shadow جاهز للصق مع معاينة حية.", keywords: ["مولد text shadow", "css text shadow", "كود text-shadow", "ظل النص css", "تأثير النص"], offsetX: "الإزاحة X", offsetY: "الإزاحة Y", blur: "التمويه", color: "اللون", preview: "معاينة" },
  ru: { title: "Генератор Text-Shadow", short: "Создавайте CSS text-shadow с живым превью.", description: "Бесплатный генератор text-shadow CSS. Настройте смещение, размытие и цвет, чтобы получить готовый CSS text-shadow с живым превью.", keywords: ["генератор text shadow", "css text shadow", "text-shadow код", "тень текста css", "эффект текста"], offsetX: "Смещение X", offsetY: "Смещение Y", blur: "Размытие", color: "Цвет", preview: "Превью" },
  zh: { title: "Text Shadow 生成器", short: "创建 CSS text-shadow 代码并实时预览。", description: "免费的 CSS text-shadow 生成器。调整偏移、模糊和颜色，即可获得可直接粘贴的 text-shadow CSS 并实时预览。", keywords: ["text shadow 生成器", "css text shadow", "text-shadow 代码", "文字阴影 css", "文字效果"], offsetX: "水平偏移", offsetY: "垂直偏移", blur: "模糊", color: "颜色", preview: "预览" },
  ja: { title: "Text Shadow 生成", short: "ライブプレビュー付きで CSS text-shadow コードを作成。", description: "無料の CSS text-shadow 生成ツール。オフセット、ぼかし、色を調整すると、貼り付け可能な text-shadow CSS がライブプレビュー付きで得られます。", keywords: ["text shadow 生成", "css text shadow", "text-shadow コード", "テキストシャドウ css", "テキスト効果"], offsetX: "オフセット X", offsetY: "オフセット Y", blur: "ぼかし", color: "色", preview: "プレビュー" },
  ko: { title: "Text Shadow 생성기", short: "실시간 미리보기로 CSS text-shadow 코드를 만듭니다.", description: "무료 CSS text-shadow 생성기. 오프셋, 흐림, 색상을 조정하면 붙여넣을 수 있는 text-shadow CSS를 실시간 미리보기와 함께 얻습니다.", keywords: ["text shadow 생성기", "css text shadow", "text-shadow 코드", "텍스트 그림자 css", "텍스트 효과"], offsetX: "오프셋 X", offsetY: "오프셋 Y", blur: "흐림", color: "색상", preview: "미리보기" },
  hi: { title: "Text Shadow जनरेटर", short: "लाइव प्रीव्यू के साथ CSS text-shadow कोड बनाएं।", description: "मुफ्त CSS text-shadow जनरेटर। ऑफसेट, ब्लर और रंग समायोजित करें और लाइव प्रीव्यू के साथ पेस्ट-तैयार text-shadow CSS पाएं।", keywords: ["text shadow जनरेटर", "css text shadow", "text-shadow कोड", "टेक्स्ट शैडो css", "टेक्स्ट इफेक्ट"], offsetX: "ऑफसेट X", offsetY: "ऑफसेट Y", blur: "ब्लर", color: "रंग", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
