import type { CalculatorI18n } from "@/types/i18n";

const io = (d: string, h: string, m: string, k: string, mph: string, ms: string) => ({
  inputs: { distance: { label: d }, hours: { label: h }, minutes: { label: m } },
  outputs: { speedKmh: { label: k }, speedMph: { label: mph }, speedMs: { label: ms } },
});

const i18n: CalculatorI18n = {
  en: { title: "Average Speed Calculator", short: "Calculate average speed from a distance and a travel time.", description: "Free average speed calculator. Enter a distance and the time taken (hours and minutes) to get the average speed in km/h, mph and m/s. Useful for trips, runs and physics problems.", keywords: ["average speed calculator", "speed from distance and time", "km/h calculator", "mph calculator", "distance time speed"], ...io("Distance", "Hours", "Minutes", "Speed (km/h)", "Speed (mph)", "Speed (m/s)"), faq: [{ q: "How is average speed calculated?", a: "Divide the total distance by the total time. 120 km in 1.5 hours is 80 km/h." }, { q: "How do I convert km/h to mph and m/s?", a: "Divide km/h by 1.609 for mph, and by 3.6 for m/s. This tool shows all three." }] },
  nl: { title: "Gemiddelde Speed Calculator", short: "Bereken average speed from a distance and a travel time.", description: "Gratis average speed calculator. Enter a distance and the time taken (uren and minuten) to get the average speed in km/h, mph and m/s. Useful for trips, runs and physics problems.", keywords: ["average speed calculator", "speed from distance and time", "km/h calculator", "mph calculator", "distance time speed"], ...io("Distance", "Hours", "Minutes", "Speed (km/h)", "Speed (mph)", "Speed (m/s)"), faq: [{ q: "How is average speed berekend?", a: "Divide the total distance by the total time. 120 km in 1.5 uren is 80 km/h." }, { q: "How do I converteer km/h to mph and m/s?", a: "Divide km/h by 1.609 for mph, and by 3.6 for m/s. This tool shows all three." }] },

  pl: { title: "Średnia Speed Kalkulator", short: "Oblicz average speed from a distance and a travel time.", description: "Darmowy average speed kalkulator. Enter a distance and the time taken (godzin and minut) to get the average speed in km/h, mph and m/s. Useful for trips, runs and physics problems.", keywords: ["average speed kalkulator", "speed from distance and time", "km/h kalkulator", "mph kalkulator", "distance time speed"], ...io("Distance", "Hours", "Minutes", "Speed (km/h)", "Speed (mph)", "Speed (m/s)"), faq: [{ q: "How is average speed obliczd?", a: "Divide the total distance by the total time. 120 km in 1.5 godzin is 80 km/h." }, { q: "How do I konwertuj km/h to mph and m/s?", a: "Divide km/h by 1.609 for mph, and by 3.6 for m/s. This narzędzie shows all three." }] },
  pt: { title: "Calculadora de Velocidade Média", short: "Calcule a velocidade média, distância ou tempo de uma viagem.", description: "Calculadora gratuita de velocidade média. Dados dois valores entre distância, tempo e velocidade, calcule o terceiro.", keywords: ["velocidade média", "distância tempo", "calculadora viagem", "km/h", "MRU"], ...io("Distance", "Hours", "Minutes", "Speed (km/h)", "Speed (mph)", "Speed (m/s)"), faq: [{ q: "How is average speed calculated?", a: "Divide the total distance by the total time. 120 km in 1.5 hours is 80 km/h." }, { q: "How do I convert km/h to mph and m/s?", a: "Divide km/h by 1.609 for mph, and by 3.6 for m/s. This tool shows all three." }] },
  id: { title: "Kalkulator Kecepatan Rata-rata", short: "Hitung kecepatan rata-rata, jarak, atau waktu perjalanan.", description: "Kalkulator kecepatan rata-rata gratis. Dari dua nilai antara jarak, waktu, dan kecepatan, hitung nilai ketiga.", keywords: ["kecepatan rata-rata", "jarak waktu", "kalkulator perjalanan", "km/jam", "GLB"], ...io("Distance", "Hours", "Minutes", "Speed (km/h)", "Speed (mph)", "Speed (m/s)"), faq: [{ q: "How is average speed calculated?", a: "Divide the total distance by the total time. 120 km in 1.5 hours is 80 km/h." }, { q: "How do I convert km/h to mph and m/s?", a: "Divide km/h by 1.609 for mph, and by 3.6 for m/s. This tool shows all three." }] },

  tr: { title: "Ortalama Hız Hesaplayıcı", short: "Mesafe ve yolculuk süresinden ortalama hızı hesaplayın.", description: "Ücretsiz ortalama hız hesaplayıcı. Bir mesafe ve geçen süreyi (saat ve dakika) girerek ortalama hızı km/sa, mph ve m/s cinsinden öğrenin. Yolculuklar, koşular ve fizik problemleri için kullanışlı.", keywords: ["ortalama hız hesaplama", "mesafe ve zamandan hız", "km/sa hesaplama", "mph hesaplama", "mesafe zaman hız"], ...io("Mesafe", "Saat", "Dakika", "Hız (km/sa)", "Hız (mph)", "Hız (m/s)"), faq: [{ q: "Ortalama hız nasıl hesaplanır?", a: "Toplam mesafeyi toplam süreye bölün. 1,5 saatte 120 km, 80 km/sa'tir." }, { q: "km/sa'i mph ve m/s'ye nasıl çeviririm?", a: "mph için km/sa'i 1,609'a, m/s için 3,6'ya bölün. Bu araç üçünü de gösterir." }] },
  de: { title: "Durchschnittsgeschwindigkeit-Rechner", short: "Berechnen Sie die Durchschnittsgeschwindigkeit aus Distanz und Fahrzeit.", description: "Kostenloser Rechner für Durchschnittsgeschwindigkeit. Geben Sie Distanz und benötigte Zeit (Stunden und Minuten) ein, um die Geschwindigkeit in km/h, mph und m/s zu erhalten.", keywords: ["durchschnittsgeschwindigkeit rechner", "geschwindigkeit aus distanz und zeit", "km/h rechner", "mph rechner", "distanz zeit geschwindigkeit"], ...io("Distanz", "Stunden", "Minuten", "Geschwindigkeit (km/h)", "Geschwindigkeit (mph)", "Geschwindigkeit (m/s)") },
  fr: { title: "Calculateur de Vitesse Moyenne", short: "Calculez la vitesse moyenne à partir d'une distance et d'un temps de trajet.", description: "Calculateur de vitesse moyenne gratuit. Saisissez une distance et le temps mis (heures et minutes) pour obtenir la vitesse moyenne en km/h, mph et m/s.", keywords: ["calculateur vitesse moyenne", "vitesse à partir de distance et temps", "calculateur km/h", "calculateur mph", "distance temps vitesse"], ...io("Distance", "Heures", "Minutes", "Vitesse (km/h)", "Vitesse (mph)", "Vitesse (m/s)") },
  es: { title: "Calculadora de Velocidad Media", short: "Calcula la velocidad media a partir de una distancia y un tiempo de viaje.", description: "Calculadora de velocidad media gratuita. Introduce una distancia y el tiempo empleado (horas y minutos) para obtener la velocidad media en km/h, mph y m/s.", keywords: ["calculadora velocidad media", "velocidad a partir de distancia y tiempo", "calculadora km/h", "calculadora mph", "distancia tiempo velocidad"], ...io("Distancia", "Horas", "Minutos", "Velocidad (km/h)", "Velocidad (mph)", "Velocidad (m/s)") },
  it: { title: "Calcolatore Velocità Media", short: "Calcola la velocità media da una distanza e un tempo di percorrenza.", description: "Calcolatore di velocità media gratuito. Inserisci una distanza e il tempo impiegato (ore e minuti) per ottenere la velocità media in km/h, mph e m/s.", keywords: ["calcolatore velocità media", "velocità da distanza e tempo", "calcolatore km/h", "calcolatore mph", "distanza tempo velocità"], ...io("Distanza", "Ore", "Minuti", "Velocità (km/h)", "Velocità (mph)", "Velocità (m/s)") },
  ar: { title: "حاسبة السرعة المتوسطة", short: "احسب السرعة المتوسطة من المسافة وزمن الرحلة.", description: "حاسبة سرعة متوسطة مجانية. أدخل المسافة والزمن المستغرق (ساعات ودقائق) للحصول على السرعة المتوسطة بالـ كم/س والـ ميل/س والـ م/ث.", keywords: ["حاسبة السرعة المتوسطة", "السرعة من المسافة والزمن", "حاسبة كم/س", "حاسبة ميل/س", "المسافة الزمن السرعة"], ...io("المسافة", "ساعات", "دقائق", "السرعة (كم/س)", "السرعة (ميل/س)", "السرعة (م/ث)") },
  ru: { title: "Калькулятор Средней Скорости", short: "Рассчитайте среднюю скорость по расстоянию и времени в пути.", description: "Бесплатный калькулятор средней скорости. Введите расстояние и затраченное время (часы и минуты), чтобы получить среднюю скорость в км/ч, миль/ч и м/с.", keywords: ["калькулятор средней скорости", "скорость по расстоянию и времени", "калькулятор км/ч", "калькулятор миль/ч", "расстояние время скорость"], ...io("Расстояние", "Часы", "Минуты", "Скорость (км/ч)", "Скорость (миль/ч)", "Скорость (м/с)") },
  zh: { title: "平均速度计算器", short: "根据距离和行驶时间计算平均速度。", description: "免费的平均速度计算器。输入距离和所用时间（小时和分钟），即可得到以 km/h、mph 和 m/s 表示的平均速度。适合行程、跑步和物理题。", keywords: ["平均速度计算器", "由距离和时间求速度", "km/h计算器", "mph计算器", "距离时间速度"], ...io("距离", "小时", "分钟", "速度 (km/h)", "速度 (mph)", "速度 (m/s)") },
  ja: { title: "平均速度計算機", short: "距離と所要時間から平均速度を計算します。", description: "無料の平均速度計算機。距離と所要時間（時間と分）を入力すると、km/h・mph・m/s の平均速度が得られます。移動・ランニング・物理の問題に便利。", keywords: ["平均速度 計算機", "距離と時間から速度", "km/h 計算機", "mph 計算機", "距離 時間 速度"], ...io("距離", "時間", "分", "速度 (km/h)", "速度 (mph)", "速度 (m/s)") },
  ko: { title: "평균 속도 계산기", short: "거리와 이동 시간으로 평균 속도를 계산합니다.", description: "무료 평균 속도 계산기. 거리와 소요 시간(시간 및 분)을 입력하면 km/h, mph, m/s 단위의 평균 속도를 얻을 수 있습니다. 여행, 달리기, 물리 문제에 유용합니다.", keywords: ["평균 속도 계산기", "거리와 시간으로 속도", "km/h 계산기", "mph 계산기", "거리 시간 속도"], ...io("거리", "시간", "분", "속도 (km/h)", "속도 (mph)", "속도 (m/s)") },
  hi: { title: "औसत गति कैलकुलेटर", short: "दूरी और यात्रा समय से औसत गति की गणना करें।", description: "मुफ्त औसत गति कैलकुलेटर। एक दूरी और लगा समय (घंटे और मिनट) दर्ज करें और औसत गति km/h, mph और m/s में पाएं। यात्राओं, दौड़ और भौतिकी समस्याओं के लिए उपयोगी।", keywords: ["औसत गति कैलकुलेटर", "दूरी और समय से गति", "km/h कैलकुलेटर", "mph कैलकुलेटर", "दूरी समय गति"], ...io("दूरी", "घंटे", "मिनट", "गति (km/h)", "गति (mph)", "गति (m/s)") },
};

export default i18n;
