import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "URL Encode / Decode", short: "Percent-encode text for URLs or decode an encoded URL back to plain text.", description: "Free URL encoder and decoder. Convert text to percent-encoded (URL-safe) form or decode %XX sequences back to readable text. Handles UTF-8 and runs entirely in your browser.", keywords: ["url encode", "url decode", "percent encoding", "uri encoder", "urlencode", "url converter"], encode: "Encode", decode: "Decode", placeholder: "Enter text or an encoded URL…", invalid: "Malformed percent-encoding." },
  tr: { title: "URL Kodla / Çöz", short: "Metni URL için yüzde-kodlayın veya kodlanmış URL'yi düz metne çözün.", description: "Ücretsiz URL kodlayıcı ve çözücü. Metni yüzde-kodlu (URL-güvenli) biçime çevirin veya %XX dizilerini okunabilir metne çözün. UTF-8 destekler ve tamamen tarayıcınızda çalışır.", keywords: ["url kodlama", "url çözme", "yüzde kodlama", "uri kodlayıcı", "urlencode", "url dönüştürücü"], encode: "Kodla", decode: "Çöz", placeholder: "Metin veya kodlanmış URL girin…", invalid: "Hatalı yüzde-kodlaması." },
  de: { title: "URL Kodieren / Dekodieren", short: "Text für URLs prozentkodieren oder eine kodierte URL in Klartext dekodieren.", description: "Kostenloser URL-Encoder und -Decoder. Wandeln Sie Text in prozentkodierte (URL-sichere) Form um oder dekodieren Sie %XX-Sequenzen zurück. UTF-8-fähig, läuft im Browser.", keywords: ["url kodieren", "url dekodieren", "prozentkodierung", "uri encoder", "urlencode"], encode: "Kodieren", decode: "Dekodieren", placeholder: "Text oder kodierte URL eingeben…", invalid: "Fehlerhafte Prozentkodierung." },
  fr: { title: "Encoder / Décoder URL", short: "Encodez du texte pour les URL ou décodez une URL encodée en texte clair.", description: "Encodeur et décodeur d'URL gratuit. Convertissez du texte en forme encodée en pourcentage (compatible URL) ou décodez les séquences %XX. Compatible UTF-8, s'exécute dans votre navigateur.", keywords: ["encoder url", "décoder url", "encodage pourcentage", "encodeur uri", "urlencode"], encode: "Encoder", decode: "Décoder", placeholder: "Saisissez du texte ou une URL encodée…", invalid: "Encodage en pourcentage incorrect." },
  es: { title: "Codificar / Decodificar URL", short: "Codifica texto en porcentaje para URL o decodifica una URL codificada a texto.", description: "Codificador y decodificador de URL gratuito. Convierte texto a forma codificada en porcentaje (apta para URL) o decodifica secuencias %XX. Compatible con UTF-8 y se ejecuta en tu navegador.", keywords: ["codificar url", "decodificar url", "codificación porcentaje", "codificador uri", "urlencode"], encode: "Codificar", decode: "Decodificar", placeholder: "Introduce texto o una URL codificada…", invalid: "Codificación de porcentaje no válida." },
  it: { title: "Codifica / Decodifica URL", short: "Codifica testo in percentuale per URL o decodifica un URL codificato in testo.", description: "Codificatore e decodificatore URL gratuito. Converti il testo in forma codificata in percentuale (adatta agli URL) o decodifica le sequenze %XX. Supporta UTF-8 e gira nel browser.", keywords: ["codifica url", "decodifica url", "codifica percentuale", "codificatore uri", "urlencode"], encode: "Codifica", decode: "Decodifica", placeholder: "Inserisci testo o un URL codificato…", invalid: "Codifica percentuale non valida." },
  ar: { title: "ترميز / فك ترميز URL", short: "رمّز النص للروابط بترميز النسبة المئوية أو فك ترميز رابط مرمّز إلى نص.", description: "مرمّز ومفكّك URL مجاني. حوّل النص إلى صيغة مرمّزة بالنسبة المئوية (آمنة للروابط) أو فك تسلسلات %XX. يدعم UTF-8 ويعمل في متصفحك.", keywords: ["ترميز url", "فك ترميز url", "ترميز النسبة المئوية", "مرمز uri", "urlencode"], encode: "ترميز", decode: "فك الترميز", placeholder: "أدخل نصًا أو رابطًا مرمّزًا…", invalid: "ترميز نسبة مئوية غير صالح." },
  ru: { title: "URL Кодирование / Декодирование", short: "Процентное кодирование текста для URL или декодирование закодированного URL.", description: "Бесплатный кодировщик и декодировщик URL. Преобразуйте текст в процентно-кодированную (URL-безопасную) форму или декодируйте последовательности %XX. Поддержка UTF-8, работает в браузере.", keywords: ["url кодирование", "url декодирование", "процентное кодирование", "uri кодировщик", "urlencode"], encode: "Кодировать", decode: "Декодировать", placeholder: "Введите текст или закодированный URL…", invalid: "Некорректное процентное кодирование." },
  zh: { title: "URL 编码 / 解码", short: "对文本进行 URL 百分号编码，或将编码后的 URL 解码为纯文本。", description: "免费的 URL 编码器和解码器。将文本转换为百分号编码（URL 安全）形式，或将 %XX 序列解码为可读文本。支持 UTF-8，完全在浏览器中运行。", keywords: ["url 编码", "url 解码", "百分号编码", "uri 编码器", "urlencode"], encode: "编码", decode: "解码", placeholder: "输入文本或编码后的 URL…", invalid: "百分号编码格式错误。" },
  ja: { title: "URL エンコード / デコード", short: "テキストを URL 用にパーセントエンコード、またはエンコード済み URL をデコード。", description: "無料の URL エンコーダー・デコーダー。テキストをパーセントエンコード（URL セーフ）形式に変換、または %XX シーケンスをデコードします。UTF-8 対応、ブラウザ内で動作。", keywords: ["url エンコード", "url デコード", "パーセントエンコード", "uri エンコーダー", "urlencode"], encode: "エンコード", decode: "デコード", placeholder: "テキストまたはエンコード済み URL を入力…", invalid: "不正なパーセントエンコードです。" },
  ko: { title: "URL 인코딩 / 디코딩", short: "텍스트를 URL용 퍼센트 인코딩하거나 인코딩된 URL을 일반 텍스트로 디코딩합니다.", description: "무료 URL 인코더 및 디코더. 텍스트를 퍼센트 인코딩(URL 안전) 형식으로 변환하거나 %XX 시퀀스를 디코딩합니다. UTF-8 지원, 브라우저에서 실행.", keywords: ["url 인코딩", "url 디코딩", "퍼센트 인코딩", "uri 인코더", "urlencode"], encode: "인코딩", decode: "디코딩", placeholder: "텍스트 또는 인코딩된 URL 입력…", invalid: "잘못된 퍼센트 인코딩입니다." },
  hi: { title: "URL एन्कोड / डिकोड", short: "URL के लिए टेक्स्ट को परसेंट-एन्कोड करें या एन्कोडेड URL को सादे टेक्स्ट में डिकोड करें।", description: "मुफ्त URL एन्कोडर और डिकोडर। टेक्स्ट को परसेंट-एन्कोडेड (URL-सुरक्षित) रूप में बदलें या %XX अनुक्रमों को पठनीय टेक्स्ट में डिकोड करें। UTF-8 समर्थित, पूरी तरह ब्राउज़र में चलता है।", keywords: ["url एन्कोड", "url डिकोड", "परसेंट एन्कोडिंग", "uri एन्कोडर", "urlencode"], encode: "एन्कोड", decode: "डिकोड", placeholder: "टेक्स्ट या एन्कोडेड URL दर्ज करें…", invalid: "गलत परसेंट-एन्कोडिंग।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, encode, decode, placeholder, invalid } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], encode, decode, placeholder, invalid } }];
  }),
) as unknown as ToolI18n;

export default i18n;
