import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "BIMI Record Checker & Generator", short: "Look up or build a domain's BIMI record.", description: "Free BIMI checker and generator. Look up a domain's default._bimi TXT record to read its logo (l) and VMC (a) URLs, or generate a BIMI record from your logo SVG and optional Verified Mark Certificate. Runs in your browser via Cloudflare DoH.", keywords: ["bimi checker", "bimi record", "bimi generator", "brand indicators", "email logo"], tabCheck: "Check", tabGenerate: "Generate", domain: "Domain", check: "Check", record: "BIMI record", logoUrl: "Logo SVG URL (l)", vmcUrl: "VMC URL (a)", vmcOptional: "optional", logo: "Logo (l)", vmc: "VMC (a)", generated: "Generated record", noRecord: "No BIMI record found for this domain.", hint: "Enter a domain (e.g. example.com); we look up default._bimi.<domain>." },
  pt: { title: "Verificador e Gerador de BIMI", short: "Pesquise ou crie o registro BIMI de um domínio.", description: "Verificador e gerador BIMI gratuito. Pesquise o registro TXT default._bimi de um domínio para ler as URLs do logo (l) e do VMC (a), ou gere um registro BIMI a partir do seu logo SVG e do Certificado de Marca Verificada opcional. Roda no navegador via Cloudflare DoH.", keywords: ["bimi checker", "bimi record", "bimi generator", "brand indicators", "email logo"], tabCheck: "Verificar", tabGenerate: "Gerar", domain: "Domínio", check: "Verificar", record: "Registro BIMI", logoUrl: "URL do logo SVG (l)", vmcUrl: "URL do VMC (a)", vmcOptional: "opcional", logo: "Logo (l)", vmc: "VMC (a)", generated: "Registro gerado", noRecord: "Nenhum registro BIMI encontrado para este domínio.", hint: "Digite um domínio (ex.: example.com); pesquisamos default._bimi.<domínio>." },
  id: { title: "Pemeriksa & Pembuat BIMI", short: "Cari atau buat rekaman BIMI domain.", description: "Pemeriksa dan pembuat BIMI gratis. Cari rekaman TXT default._bimi domain untuk membaca URL logo (l) dan VMC (a), atau buat rekaman BIMI dari logo SVG Anda dan Sertifikat Merek Terverifikasi opsional. Berjalan di browser via Cloudflare DoH.", keywords: ["bimi checker", "bimi record", "bimi generator", "brand indicators", "email logo"], tabCheck: "Periksa", tabGenerate: "Buat", domain: "Domain", check: "Periksa", record: "Rekaman BIMI", logoUrl: "URL logo SVG (l)", vmcUrl: "URL VMC (a)", vmcOptional: "opsional", logo: "Logo (l)", vmc: "VMC (a)", generated: "Rekaman yang dibuat", noRecord: "Tidak ada rekaman BIMI ditemukan untuk domain ini.", hint: "Masukkan domain (mis. example.com); kami mencari default._bimi.<domain>." },

  tr: { title: "BIMI Kaydı Denetleyici ve Oluşturucu", short: "Bir alan adının BIMI kaydını sorgulayın veya oluşturun.", description: "Ücretsiz BIMI denetleyici ve oluşturucu. Bir alan adının default._bimi TXT kaydını sorgulayarak logo (l) ve VMC (a) URL'lerini okuyun veya logo SVG'nizden ve isteğe bağlı Doğrulanmış Marka Sertifikasından bir BIMI kaydı oluşturun. Cloudflare DoH üzerinden tarayıcınızda çalışır.", keywords: ["bimi denetleyici", "bimi kaydı", "bimi oluşturucu", "marka göstergeleri", "e-posta logosu"], tabCheck: "Denetle", tabGenerate: "Oluştur", domain: "Alan adı", check: "Denetle", record: "BIMI kaydı", logoUrl: "Logo SVG URL'si (l)", vmcUrl: "VMC URL'si (a)", vmcOptional: "isteğe bağlı", logo: "Logo (l)", vmc: "VMC (a)", generated: "Oluşturulan kayıt", noRecord: "Bu alan adı için BIMI kaydı bulunamadı.", hint: "Bir alan adı girin (ör. example.com); default._bimi.<alan> sorgulanır." },
  de: { title: "BIMI-Eintrag-Prüfer & -Generator", short: "BIMI-Eintrag einer Domain abfragen oder erstellen.", description: "Kostenloser BIMI-Prüfer und -Generator. Fragen Sie den default._bimi-TXT-Eintrag einer Domain ab, um die Logo- (l) und VMC- (a) URLs zu lesen, oder erstellen Sie einen BIMI-Eintrag aus Ihrem Logo-SVG und einem optionalen Verified Mark Certificate. Läuft im Browser über Cloudflare DoH.", keywords: ["bimi prüfer", "bimi eintrag", "bimi generator", "markenindikatoren", "e-mail logo"], tabCheck: "Prüfen", tabGenerate: "Erstellen", domain: "Domain", check: "Prüfen", record: "BIMI-Eintrag", logoUrl: "Logo-SVG-URL (l)", vmcUrl: "VMC-URL (a)", vmcOptional: "optional", logo: "Logo (l)", vmc: "VMC (a)", generated: "Erzeugter Eintrag", noRecord: "Kein BIMI-Eintrag für diese Domain gefunden.", hint: "Geben Sie eine Domain ein (z. B. example.com); wir fragen default._bimi.<Domain> ab." },
  fr: { title: "Vérificateur & Générateur BIMI", short: "Recherchez ou créez l'enregistrement BIMI d'un domaine.", description: "Vérificateur et générateur BIMI gratuit. Recherchez l'enregistrement TXT default._bimi d'un domaine pour lire les URL du logo (l) et du VMC (a), ou générez un enregistrement BIMI à partir de votre logo SVG et d'un certificat Verified Mark optionnel. Fonctionne dans votre navigateur via Cloudflare DoH.", keywords: ["vérificateur bimi", "enregistrement bimi", "générateur bimi", "indicateurs de marque", "logo email"], tabCheck: "Vérifier", tabGenerate: "Générer", domain: "Domaine", check: "Vérifier", record: "Enregistrement BIMI", logoUrl: "URL du logo SVG (l)", vmcUrl: "URL du VMC (a)", vmcOptional: "facultatif", logo: "Logo (l)", vmc: "VMC (a)", generated: "Enregistrement généré", noRecord: "Aucun enregistrement BIMI trouvé pour ce domaine.", hint: "Saisissez un domaine (ex. example.com) ; nous interrogeons default._bimi.<domaine>." },
  es: { title: "Verificador y Generador BIMI", short: "Consulta o crea el registro BIMI de un dominio.", description: "Verificador y generador BIMI gratuito. Consulta el registro TXT default._bimi de un dominio para leer las URL del logo (l) y del VMC (a), o genera un registro BIMI a partir de tu logo SVG y un Certificado de Marca Verificada opcional. Funciona en tu navegador vía Cloudflare DoH.", keywords: ["verificador bimi", "registro bimi", "generador bimi", "indicadores de marca", "logo de correo"], tabCheck: "Verificar", tabGenerate: "Generar", domain: "Dominio", check: "Verificar", record: "Registro BIMI", logoUrl: "URL del logo SVG (l)", vmcUrl: "URL del VMC (a)", vmcOptional: "opcional", logo: "Logo (l)", vmc: "VMC (a)", generated: "Registro generado", noRecord: "No se encontró un registro BIMI para este dominio.", hint: "Introduce un dominio (p. ej. example.com); consultamos default._bimi.<dominio>." },
  it: { title: "Verificatore e Generatore BIMI", short: "Cerca o crea il record BIMI di un dominio.", description: "Verificatore e generatore BIMI gratuito. Cerca il record TXT default._bimi di un dominio per leggere gli URL del logo (l) e del VMC (a), oppure genera un record BIMI dal tuo logo SVG e da un Verified Mark Certificate opzionale. Funziona nel tuo browser tramite Cloudflare DoH.", keywords: ["verificatore bimi", "record bimi", "generatore bimi", "indicatori di marca", "logo email"], tabCheck: "Verifica", tabGenerate: "Genera", domain: "Dominio", check: "Verifica", record: "Record BIMI", logoUrl: "URL del logo SVG (l)", vmcUrl: "URL del VMC (a)", vmcOptional: "facoltativo", logo: "Logo (l)", vmc: "VMC (a)", generated: "Record generato", noRecord: "Nessun record BIMI trovato per questo dominio.", hint: "Inserisci un dominio (es. example.com); cerchiamo default._bimi.<dominio>." },
  ar: { title: "فاحص ومولّد BIMI", short: "ابحث عن سجل BIMI لنطاق أو أنشئه.", description: "فاحص ومولّد BIMI مجاني. ابحث عن سجل TXT الخاص بـ default._bimi لنطاق لقراءة عناوين URL للشعار (l) وVMC (a)، أو أنشئ سجل BIMI من شعار SVG الخاص بك وشهادة العلامة الموثقة الاختيارية. يعمل في متصفحك عبر Cloudflare DoH.", keywords: ["فاحص bimi", "سجل bimi", "مولّد bimi", "مؤشرات العلامة", "شعار البريد"], tabCheck: "فحص", tabGenerate: "إنشاء", domain: "النطاق", check: "فحص", record: "سجل BIMI", logoUrl: "عنوان URL لشعار SVG (l)", vmcUrl: "عنوان URL لـ VMC (a)", vmcOptional: "اختياري", logo: "الشعار (l)", vmc: "VMC (a)", generated: "السجل المُنشأ", noRecord: "لم يتم العثور على سجل BIMI لهذا النطاق.", hint: "أدخل نطاقًا (مثل example.com)؛ نبحث عن default._bimi.<النطاق>." },
  ru: { title: "Проверка и генератор BIMI", short: "Найдите или создайте BIMI-запись домена.", description: "Бесплатная проверка и генератор BIMI. Найдите default._bimi TXT-запись домена, чтобы прочитать URL логотипа (l) и VMC (a), или создайте BIMI-запись из вашего SVG-логотипа и необязательного сертификата Verified Mark. Работает в браузере через Cloudflare DoH.", keywords: ["проверка bimi", "запись bimi", "генератор bimi", "индикаторы бренда", "логотип почты"], tabCheck: "Проверить", tabGenerate: "Создать", domain: "Домен", check: "Проверить", record: "BIMI-запись", logoUrl: "URL SVG-логотипа (l)", vmcUrl: "URL VMC (a)", vmcOptional: "необязательно", logo: "Логотип (l)", vmc: "VMC (a)", generated: "Сгенерированная запись", noRecord: "Для этого домена BIMI-запись не найдена.", hint: "Введите домен (например, example.com); мы запросим default._bimi.<домен>." },
  zh: { title: "BIMI 记录检查器与生成器", short: "查询或生成域名的 BIMI 记录。", description: "免费的 BIMI 检查器和生成器。查询域名的 default._bimi TXT 记录以读取其徽标 (l) 和 VMC (a) URL，或从你的徽标 SVG 和可选的验证标记证书生成 BIMI 记录。通过 Cloudflare DoH 在浏览器中运行。", keywords: ["bimi 检查器", "bimi 记录", "bimi 生成器", "品牌标识", "邮件徽标"], tabCheck: "检查", tabGenerate: "生成", domain: "域名", check: "检查", record: "BIMI 记录", logoUrl: "徽标 SVG URL (l)", vmcUrl: "VMC URL (a)", vmcOptional: "可选", logo: "徽标 (l)", vmc: "VMC (a)", generated: "生成的记录", noRecord: "未找到此域名的 BIMI 记录。", hint: "输入域名（如 example.com）；我们查询 default._bimi.<域名>。" },
  ja: { title: "BIMI レコードチェッカー＆ジェネレーター", short: "ドメインの BIMI レコードを検索または作成します。", description: "無料の BIMI チェッカーとジェネレーター。ドメインの default._bimi TXT レコードを検索してロゴ (l) と VMC (a) の URL を読み取るか、ロゴ SVG と任意の Verified Mark Certificate から BIMI レコードを生成します。Cloudflare DoH を介してブラウザ内で動作します。", keywords: ["bimi チェッカー", "bimi レコード", "bimi ジェネレーター", "ブランドインジケーター", "メールロゴ"], tabCheck: "チェック", tabGenerate: "生成", domain: "ドメイン", check: "チェック", record: "BIMI レコード", logoUrl: "ロゴ SVG URL (l)", vmcUrl: "VMC URL (a)", vmcOptional: "任意", logo: "ロゴ (l)", vmc: "VMC (a)", generated: "生成されたレコード", noRecord: "このドメインの BIMI レコードは見つかりませんでした。", hint: "ドメイン（例: example.com）を入力します。default._bimi.<ドメイン> を検索します。" },
  ko: { title: "BIMI 레코드 검사기 및 생성기", short: "도메인의 BIMI 레코드를 조회하거나 생성합니다.", description: "무료 BIMI 검사기 및 생성기. 도메인의 default._bimi TXT 레코드를 조회하여 로고(l)와 VMC(a) URL을 읽거나, 로고 SVG와 선택적 Verified Mark Certificate로 BIMI 레코드를 생성합니다. Cloudflare DoH를 통해 브라우저에서 실행됩니다.", keywords: ["bimi 검사기", "bimi 레코드", "bimi 생성기", "브랜드 표시기", "이메일 로고"], tabCheck: "검사", tabGenerate: "생성", domain: "도메인", check: "검사", record: "BIMI 레코드", logoUrl: "로고 SVG URL (l)", vmcUrl: "VMC URL (a)", vmcOptional: "선택", logo: "로고 (l)", vmc: "VMC (a)", generated: "생성된 레코드", noRecord: "이 도메인에 대한 BIMI 레코드를 찾을 수 없습니다.", hint: "도메인(예: example.com)을 입력하세요. default._bimi.<도메인>을 조회합니다." },
  hi: { title: "BIMI रिकॉर्ड चेकर और जेनरेटर", short: "किसी डोमेन का BIMI रिकॉर्ड देखें या बनाएं।", description: "मुफ्त BIMI चेकर और जेनरेटर। किसी डोमेन का default._bimi TXT रिकॉर्ड देखकर उसके लोगो (l) और VMC (a) URL पढ़ें, या अपने लोगो SVG और वैकल्पिक Verified Mark Certificate से एक BIMI रिकॉर्ड बनाएं। Cloudflare DoH के माध्यम से आपके ब्राउज़र में चलता है।", keywords: ["bimi checker", "bimi record", "bimi generator", "brand indicators", "email logo"], tabCheck: "जाँचें", tabGenerate: "बनाएं", domain: "डोमेन", check: "जाँचें", record: "BIMI रिकॉर्ड", logoUrl: "लोगो SVG URL (l)", vmcUrl: "VMC URL (a)", vmcOptional: "वैकल्पिक", logo: "लोगो (l)", vmc: "VMC (a)", generated: "उत्पन्न रिकॉर्ड", noRecord: "इस डोमेन के लिए कोई BIMI रिकॉर्ड नहीं मिला।", hint: "एक डोमेन दर्ज करें (जैसे example.com); हम default._bimi.<डोमेन> देखते हैं।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
