import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "DKIM Record Checker", short: "Look up and validate a domain's DKIM public-key record.", description: "Free DKIM checker. Enter a selector and domain to look up the <selector>._domainkey.<domain> TXT record, confirm a public key is present, read the key type and flag revoked keys. Runs in your browser via Cloudflare DoH.", keywords: ["dkim checker", "dkim record lookup", "dkim selector", "domainkeys", "email authentication"], selector: "Selector", domain: "Domain", check: "Check", record: "DKIM record", keyType: "Key type (k)", publicKey: "Public key", present: "Present", absent: "Absent / revoked", noRecord: "No DKIM record found for this selector and domain.", hint: "You must know the selector (e.g. google, default, s1). The record is looked up at <selector>._domainkey.<domain>." },
  pt: { title: "Verificador de Registro DKIM", short: "Pesquise e valide o registro de chave pública DKIM de um domínio.", description: "Verificador DKIM gratuito. Informe um seletor e domínio para pesquisar o registro TXT <seletor>._domainkey.<domínio>, confirmar a presença de chave pública, ler o tipo de chave e sinalizar chaves revogadas. Roda no navegador via Cloudflare DoH.", keywords: ["dkim checker", "dkim record lookup", "dkim selector", "domainkeys", "email authentication"], selector: "Seletor", domain: "Domínio", check: "Verificar", record: "Registro DKIM", keyType: "Tipo de chave (k)", publicKey: "Chave pública", present: "Presente", absent: "Ausente / revogada", noRecord: "Nenhum registro DKIM encontrado para este seletor e domínio.", hint: "Você precisa saber o seletor (ex.: google, default, s1). O registro é pesquisado em <seletor>._domainkey.<domínio>." },
  id: { title: "Pemeriksa Rekaman DKIM", short: "Cari dan validasi rekaman kunci publik DKIM domain.", description: "Pemeriksa DKIM gratis. Masukkan selektor dan domain untuk mencari rekaman TXT <selektor>._domainkey.<domain>, konfirmasi kunci publik ada, baca tipe kunci, dan tandai kunci yang dicabut. Berjalan di browser via Cloudflare DoH.", keywords: ["dkim checker", "dkim record lookup", "dkim selector", "domainkeys", "email authentication"], selector: "Selektor", domain: "Domain", check: "Periksa", record: "Rekaman DKIM", keyType: "Tipe kunci (k)", publicKey: "Kunci publik", present: "Ada", absent: "Tidak ada / dicabut", noRecord: "Tidak ada rekaman DKIM ditemukan untuk selektor dan domain ini.", hint: "Anda harus tahu selektornya (mis. google, default, s1). Rekaman dicari di <selektor>._domainkey.<domain>." },

  tr: { title: "DKIM Kaydı Denetleyici", short: "Bir alan adının DKIM açık anahtar kaydını sorgulayın ve doğrulayın.", description: "Ücretsiz DKIM denetleyici. Bir seçici ve alan adı girerek <seçici>._domainkey.<alan> TXT kaydını sorgulayın, açık anahtarın varlığını doğrulayın, anahtar türünü okuyun ve iptal edilmiş anahtarları işaretleyin. Cloudflare DoH üzerinden tarayıcınızda çalışır.", keywords: ["dkim denetleyici", "dkim kaydı sorgu", "dkim seçici", "domainkeys", "e-posta kimlik doğrulama"], selector: "Seçici", domain: "Alan adı", check: "Denetle", record: "DKIM kaydı", keyType: "Anahtar türü (k)", publicKey: "Açık anahtar", present: "Mevcut", absent: "Yok / iptal edilmiş", noRecord: "Bu seçici ve alan adı için DKIM kaydı bulunamadı.", hint: "Seçiciyi bilmeniz gerekir (ör. google, default, s1). Kayıt <seçici>._domainkey.<alan> adresinde sorgulanır." },
  de: { title: "DKIM-Eintrag-Prüfer", short: "DKIM-Public-Key-Eintrag einer Domain abfragen und validieren.", description: "Kostenloser DKIM-Prüfer. Geben Sie einen Selektor und eine Domain ein, um den TXT-Eintrag <Selektor>._domainkey.<Domain> abzufragen, das Vorhandensein eines öffentlichen Schlüssels zu bestätigen, den Schlüsseltyp zu lesen und widerrufene Schlüssel zu markieren. Läuft im Browser über Cloudflare DoH.", keywords: ["dkim prüfer", "dkim eintrag abfrage", "dkim selektor", "domainkeys", "e-mail authentifizierung"], selector: "Selektor", domain: "Domain", check: "Prüfen", record: "DKIM-Eintrag", keyType: "Schlüsseltyp (k)", publicKey: "Öffentlicher Schlüssel", present: "Vorhanden", absent: "Fehlt / widerrufen", noRecord: "Kein DKIM-Eintrag für diesen Selektor und diese Domain gefunden.", hint: "Sie müssen den Selektor kennen (z. B. google, default, s1). Der Eintrag wird unter <Selektor>._domainkey.<Domain> abgefragt." },
  fr: { title: "Vérificateur d'Enregistrement DKIM", short: "Recherchez et validez l'enregistrement de clé publique DKIM d'un domaine.", description: "Vérificateur DKIM gratuit. Saisissez un sélecteur et un domaine pour rechercher l'enregistrement TXT <sélecteur>._domainkey.<domaine>, confirmer la présence d'une clé publique, lire le type de clé et signaler les clés révoquées. Fonctionne dans votre navigateur via Cloudflare DoH.", keywords: ["vérificateur dkim", "recherche enregistrement dkim", "sélecteur dkim", "domainkeys", "authentification email"], selector: "Sélecteur", domain: "Domaine", check: "Vérifier", record: "Enregistrement DKIM", keyType: "Type de clé (k)", publicKey: "Clé publique", present: "Présente", absent: "Absente / révoquée", noRecord: "Aucun enregistrement DKIM trouvé pour ce sélecteur et ce domaine.", hint: "Vous devez connaître le sélecteur (ex. google, default, s1). L'enregistrement est recherché sur <sélecteur>._domainkey.<domaine>." },
  es: { title: "Verificador de Registro DKIM", short: "Consulta y valida el registro de clave pública DKIM de un dominio.", description: "Verificador DKIM gratuito. Introduce un selector y un dominio para consultar el registro TXT <selector>._domainkey.<dominio>, confirmar la presencia de una clave pública, leer el tipo de clave y señalar claves revocadas. Funciona en tu navegador vía Cloudflare DoH.", keywords: ["verificador dkim", "consulta registro dkim", "selector dkim", "domainkeys", "autenticación de correo"], selector: "Selector", domain: "Dominio", check: "Verificar", record: "Registro DKIM", keyType: "Tipo de clave (k)", publicKey: "Clave pública", present: "Presente", absent: "Ausente / revocada", noRecord: "No se encontró un registro DKIM para este selector y dominio.", hint: "Debes conocer el selector (p. ej. google, default, s1). El registro se consulta en <selector>._domainkey.<dominio>." },
  it: { title: "Verificatore Record DKIM", short: "Cerca e valida il record di chiave pubblica DKIM di un dominio.", description: "Verificatore DKIM gratuito. Inserisci un selettore e un dominio per cercare il record TXT <selettore>._domainkey.<dominio>, confermare la presenza di una chiave pubblica, leggere il tipo di chiave e segnalare chiavi revocate. Funziona nel tuo browser tramite Cloudflare DoH.", keywords: ["verificatore dkim", "ricerca record dkim", "selettore dkim", "domainkeys", "autenticazione email"], selector: "Selettore", domain: "Dominio", check: "Verifica", record: "Record DKIM", keyType: "Tipo di chiave (k)", publicKey: "Chiave pubblica", present: "Presente", absent: "Assente / revocata", noRecord: "Nessun record DKIM trovato per questo selettore e dominio.", hint: "Devi conoscere il selettore (es. google, default, s1). Il record viene cercato su <selettore>._domainkey.<dominio>." },
  ar: { title: "فاحص سجل DKIM", short: "ابحث عن سجل المفتاح العام DKIM لنطاق وتحقق منه.", description: "فاحص DKIM مجاني. أدخل محددًا ونطاقًا للبحث عن سجل TXT الخاص بـ <المحدد>._domainkey.<النطاق>، وتأكيد وجود مفتاح عام، وقراءة نوع المفتاح، والإبلاغ عن المفاتيح الملغاة. يعمل في متصفحك عبر Cloudflare DoH.", keywords: ["فاحص dkim", "بحث سجل dkim", "محدد dkim", "domainkeys", "مصادقة البريد"], selector: "المحدد", domain: "النطاق", check: "فحص", record: "سجل DKIM", keyType: "نوع المفتاح (k)", publicKey: "المفتاح العام", present: "موجود", absent: "غير موجود / ملغى", noRecord: "لم يتم العثور على سجل DKIM لهذا المحدد والنطاق.", hint: "يجب أن تعرف المحدد (مثل google أو default أو s1). يُبحث عن السجل في <المحدد>._domainkey.<النطاق>." },
  ru: { title: "Проверка DKIM-записи", short: "Найдите и проверьте запись открытого ключа DKIM домена.", description: "Бесплатная проверка DKIM. Введите селектор и домен, чтобы найти TXT-запись <селектор>._domainkey.<домен>, подтвердить наличие открытого ключа, прочитать тип ключа и выявить отозванные ключи. Работает в браузере через Cloudflare DoH.", keywords: ["проверка dkim", "поиск dkim записи", "селектор dkim", "domainkeys", "аутентификация почты"], selector: "Селектор", domain: "Домен", check: "Проверить", record: "DKIM-запись", keyType: "Тип ключа (k)", publicKey: "Открытый ключ", present: "Присутствует", absent: "Отсутствует / отозван", noRecord: "Для этого селектора и домена DKIM-запись не найдена.", hint: "Нужно знать селектор (например, google, default, s1). Запись ищется по <селектор>._domainkey.<домен>." },
  zh: { title: "DKIM 记录检查器", short: "查询并验证域名的 DKIM 公钥记录。", description: "免费的 DKIM 检查器。输入选择器和域名以查询 <选择器>._domainkey.<域名> 的 TXT 记录，确认公钥是否存在，读取密钥类型并标记已吊销的密钥。通过 Cloudflare DoH 在浏览器中运行。", keywords: ["dkim 检查器", "dkim 记录查询", "dkim 选择器", "domainkeys", "邮件认证"], selector: "选择器", domain: "域名", check: "检查", record: "DKIM 记录", keyType: "密钥类型 (k)", publicKey: "公钥", present: "存在", absent: "缺失 / 已吊销", noRecord: "未找到此选择器和域名的 DKIM 记录。", hint: "您必须知道选择器（如 google、default、s1）。记录在 <选择器>._domainkey.<域名> 处查询。" },
  ja: { title: "DKIM レコードチェッカー", short: "ドメインの DKIM 公開鍵レコードを検索・検証します。", description: "無料の DKIM チェッカー。セレクターとドメインを入力して <セレクター>._domainkey.<ドメイン> の TXT レコードを検索し、公開鍵の有無を確認、鍵の種類を読み取り、失効した鍵を指摘します。Cloudflare DoH を介してブラウザ内で動作します。", keywords: ["dkim チェッカー", "dkim レコード 検索", "dkim セレクター", "domainkeys", "メール認証"], selector: "セレクター", domain: "ドメイン", check: "チェック", record: "DKIM レコード", keyType: "鍵の種類 (k)", publicKey: "公開鍵", present: "あり", absent: "なし / 失効", noRecord: "このセレクターとドメインの DKIM レコードは見つかりませんでした。", hint: "セレクター（例: google, default, s1）を知っている必要があります。レコードは <セレクター>._domainkey.<ドメイン> で検索されます。" },
  ko: { title: "DKIM 레코드 검사기", short: "도메인의 DKIM 공개 키 레코드를 조회하고 검증합니다.", description: "무료 DKIM 검사기. 셀렉터와 도메인을 입력하여 <셀렉터>._domainkey.<도메인> TXT 레코드를 조회하고, 공개 키 존재를 확인하며, 키 유형을 읽고, 폐기된 키를 표시합니다. Cloudflare DoH를 통해 브라우저에서 실행됩니다.", keywords: ["dkim 검사기", "dkim 레코드 조회", "dkim 셀렉터", "domainkeys", "이메일 인증"], selector: "셀렉터", domain: "도메인", check: "검사", record: "DKIM 레코드", keyType: "키 유형 (k)", publicKey: "공개 키", present: "있음", absent: "없음 / 폐기됨", noRecord: "이 셀렉터와 도메인에 대한 DKIM 레코드를 찾을 수 없습니다.", hint: "셀렉터(예: google, default, s1)를 알아야 합니다. 레코드는 <셀렉터>._domainkey.<도메인>에서 조회됩니다." },
  hi: { title: "DKIM रिकॉर्ड चेकर", short: "किसी डोमेन का DKIM सार्वजनिक कुंजी रिकॉर्ड देखें और मान्य करें।", description: "मुफ्त DKIM चेकर। <सेलेक्टर>._domainkey.<डोमेन> TXT रिकॉर्ड देखने, सार्वजनिक कुंजी की उपस्थिति की पुष्टि करने, कुंजी प्रकार पढ़ने और निरस्त कुंजियों को चिह्नित करने के लिए एक सेलेक्टर और डोमेन दर्ज करें। Cloudflare DoH के माध्यम से आपके ब्राउज़र में चलता है।", keywords: ["dkim चेकर", "dkim रिकॉर्ड lookup", "dkim selector", "domainkeys", "ईमेल प्रमाणीकरण"], selector: "सेलेक्टर", domain: "डोमेन", check: "जाँचें", record: "DKIM रिकॉर्ड", keyType: "कुंजी प्रकार (k)", publicKey: "सार्वजनिक कुंजी", present: "मौजूद", absent: "अनुपस्थित / निरस्त", noRecord: "इस सेलेक्टर और डोमेन के लिए कोई DKIM रिकॉर्ड नहीं मिला।", hint: "आपको सेलेक्टर पता होना चाहिए (जैसे google, default, s1)। रिकॉर्ड <सेलेक्टर>._domainkey.<डोमेन> पर देखा जाता है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
