import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Clip-Path Generator", short: "Pick a clip-path shape and copy the CSS.", description: "Free CSS clip-path generator. Choose from common shapes (triangle, rhombus, pentagon, hexagon, star, circle, arrow, …) and copy the ready-to-paste CSS — with a live preview.", keywords: ["css clip-path generator", "clip path shapes", "polygon clip path", "css star shape", "css hexagon"], shape: "Shape", color: "Color", preview: "Preview" },
  tr: { title: "CSS Clip-Path Oluşturucu", short: "Bir clip-path şekli seçin ve CSS'i kopyalayın.", description: "Ücretsiz CSS clip-path oluşturucu. Yaygın şekiller (üçgen, eşkenar dörtgen, beşgen, altıgen, yıldız, daire, ok, …) arasından seçin ve yapıştırmaya hazır CSS'i kopyalayın — canlı önizlemeyle.", keywords: ["css clip-path oluşturucu", "clip path şekilleri", "polygon clip path", "css yıldız şekli", "css altıgen"], shape: "Şekil", color: "Renk", preview: "Önizleme" },
  de: { title: "CSS-Clip-Path-Generator", short: "Wählen Sie eine Clip-Path-Form und kopieren Sie das CSS.", description: "Kostenloser CSS-Clip-Path-Generator. Wählen Sie aus gängigen Formen (Dreieck, Raute, Fünfeck, Sechseck, Stern, Kreis, Pfeil, …) und kopieren Sie einsatzbereites CSS — mit Live-Vorschau.", keywords: ["css clip-path generator", "clip path formen", "polygon clip path", "css stern form", "css sechseck"], shape: "Form", color: "Farbe", preview: "Vorschau" },
  fr: { title: "Générateur CSS Clip-Path", short: "Choisissez une forme clip-path et copiez le CSS.", description: "Générateur CSS clip-path gratuit. Choisissez parmi des formes courantes (triangle, losange, pentagone, hexagone, étoile, cercle, flèche, …) et copiez le CSS prêt à coller — avec aperçu en direct.", keywords: ["générateur css clip-path", "formes clip path", "polygone clip path", "forme étoile css", "css hexagone"], shape: "Forme", color: "Couleur", preview: "Aperçu" },
  es: { title: "Generador CSS Clip-Path", short: "Elige una forma clip-path y copia el CSS.", description: "Generador CSS clip-path gratuito. Elige entre formas comunes (triángulo, rombo, pentágono, hexágono, estrella, círculo, flecha, …) y copia el CSS listo para pegar — con vista previa en vivo.", keywords: ["generador css clip-path", "formas clip path", "polígono clip path", "forma estrella css", "css hexágono"], shape: "Forma", color: "Color", preview: "Vista previa" },
  it: { title: "Generatore CSS Clip-Path", short: "Scegli una forma clip-path e copia il CSS.", description: "Generatore CSS clip-path gratuito. Scegli tra forme comuni (triangolo, rombo, pentagono, esagono, stella, cerchio, freccia, …) e copia il CSS pronto da incollare — con anteprima dal vivo.", keywords: ["generatore css clip-path", "forme clip path", "poligono clip path", "forma stella css", "css esagono"], shape: "Forma", color: "Colore", preview: "Anteprima" },
  ar: { title: "مولّد CSS Clip-Path", short: "اختر شكل clip-path وانسخ CSS.", description: "مولّد CSS clip-path مجاني. اختر من أشكال شائعة (مثلث، معين، خماسي، سداسي، نجمة، دائرة، سهم، …) وانسخ CSS جاهز للصق — مع معاينة حية.", keywords: ["مولد css clip-path", "أشكال clip path", "polygon clip path", "شكل نجمة css", "css سداسي"], shape: "الشكل", color: "اللون", preview: "معاينة" },
  ru: { title: "Генератор CSS Clip-Path", short: "Выберите форму clip-path и скопируйте CSS.", description: "Бесплатный генератор CSS clip-path. Выберите из распространённых форм (треугольник, ромб, пятиугольник, шестиугольник, звезда, круг, стрелка, …) и скопируйте готовый к вставке CSS — с живым превью.", keywords: ["генератор css clip-path", "формы clip path", "polygon clip path", "форма звезды css", "css шестиугольник"], shape: "Форма", color: "Цвет", preview: "Превью" },
  zh: { title: "CSS Clip-Path 生成器", short: "选择 clip-path 形状并复制 CSS。", description: "免费的 CSS clip-path 生成器。从常见形状（三角形、菱形、五边形、六边形、星形、圆形、箭头 …）中选择，复制可直接粘贴的 CSS——带实时预览。", keywords: ["css clip-path 生成器", "clip path 形状", "polygon clip path", "css 星形", "css 六边形"], shape: "形状", color: "颜色", preview: "预览" },
  ja: { title: "CSS Clip-Path ジェネレーター", short: "clip-path 形状を選んで CSS をコピー。", description: "無料の CSS clip-path ジェネレーター。一般的な形状（三角形、菱形、五角形、六角形、星、円、矢印、…）から選び、貼り付け可能な CSS をコピー——ライブプレビュー付き。", keywords: ["css clip-path ジェネレーター", "clip path 形状", "polygon clip path", "css 星形", "css 六角形"], shape: "形状", color: "色", preview: "プレビュー" },
  ko: { title: "CSS Clip-Path 생성기", short: "clip-path 모양을 선택하고 CSS를 복사하세요.", description: "무료 CSS clip-path 생성기. 일반적인 모양(삼각형, 마름모, 오각형, 육각형, 별, 원, 화살표, …) 중에서 선택하고 붙여넣을 수 있는 CSS를 복사하세요 — 실시간 미리보기 포함.", keywords: ["css clip-path 생성기", "clip path 모양", "polygon clip path", "css 별 모양", "css 육각형"], shape: "모양", color: "색상", preview: "미리보기" },
  hi: { title: "CSS Clip-Path जनरेटर", short: "एक clip-path आकार चुनें और CSS कॉपी करें।", description: "मुफ्त CSS clip-path जनरेटर। सामान्य आकृतियों (त्रिकोण, समभुज, पंचभुज, षट्भुज, तारा, वृत्त, तीर, …) में से चुनें और पेस्ट करने योग्य CSS कॉपी करें — लाइव प्रीव्यू के साथ।", keywords: ["css clip-path जनरेटर", "clip path आकार", "polygon clip path", "css तारा आकार", "css षट्भुज"], shape: "आकार", color: "रंग", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
