import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Markdown Table Generator", short: "Turn CSV or tab-separated data into a Markdown table.", description: "Free Markdown table generator. Paste CSV or tab-separated rows, pick column alignment, and get a clean GitHub-flavoured Markdown table ready to copy.", keywords: ["markdown table generator", "csv to markdown", "markdown table", "md table generator", "create markdown table"], input: "Data (CSV or tab-separated)", output: "Markdown", align: "Alignment", left: "Left", center: "Center", right: "Right" },
  tr: { title: "Markdown Tablo Oluşturucu", short: "CSV veya sekmeyle ayrılmış veriyi Markdown tablosuna dönüştürün.", description: "Ücretsiz Markdown tablo oluşturucu. CSV veya sekmeyle ayrılmış satırları yapıştırın, sütun hizalamasını seçin ve kopyalamaya hazır temiz bir GitHub Markdown tablosu alın.", keywords: ["markdown tablo oluşturucu", "csv markdown", "markdown tablo", "md tablo oluşturucu", "markdown tablo yap"], input: "Veri (CSV veya sekmeyle ayrılmış)", output: "Markdown", align: "Hizalama", left: "Sol", center: "Orta", right: "Sağ" },
  de: { title: "Markdown-Tabellen-Generator", short: "CSV oder tabgetrennte Daten in eine Markdown-Tabelle umwandeln.", description: "Kostenloser Markdown-Tabellen-Generator. Fügen Sie CSV- oder tabgetrennte Zeilen ein, wählen Sie die Spaltenausrichtung und erhalten Sie eine saubere Markdown-Tabelle zum Kopieren.", keywords: ["markdown tabellen generator", "csv zu markdown", "markdown tabelle", "md tabelle generator", "markdown tabelle erstellen"], input: "Daten (CSV oder tabgetrennt)", output: "Markdown", align: "Ausrichtung", left: "Links", center: "Mitte", right: "Rechts" },
  fr: { title: "Générateur de Tableau Markdown", short: "Transformez des données CSV ou tabulées en tableau Markdown.", description: "Générateur de tableau Markdown gratuit. Collez des lignes CSV ou tabulées, choisissez l'alignement des colonnes et obtenez un tableau Markdown propre prêt à copier.", keywords: ["générateur tableau markdown", "csv vers markdown", "tableau markdown", "générateur table md", "créer tableau markdown"], input: "Données (CSV ou tabulées)", output: "Markdown", align: "Alignement", left: "Gauche", center: "Centre", right: "Droite" },
  es: { title: "Generador de Tablas Markdown", short: "Convierte datos CSV o separados por tabulación en una tabla Markdown.", description: "Generador de tablas Markdown gratuito. Pega filas CSV o separadas por tabulación, elige la alineación de columnas y obtén una tabla Markdown limpia lista para copiar.", keywords: ["generador tablas markdown", "csv a markdown", "tabla markdown", "generador tabla md", "crear tabla markdown"], input: "Datos (CSV o separados por tabulación)", output: "Markdown", align: "Alineación", left: "Izquierda", center: "Centro", right: "Derecha" },
  it: { title: "Generatore di Tabelle Markdown", short: "Converti dati CSV o separati da tab in una tabella Markdown.", description: "Generatore di tabelle Markdown gratuito. Incolla righe CSV o separate da tab, scegli l'allineamento delle colonne e ottieni una tabella Markdown pulita pronta da copiare.", keywords: ["generatore tabelle markdown", "csv a markdown", "tabella markdown", "generatore tabella md", "creare tabella markdown"], input: "Dati (CSV o separati da tab)", output: "Markdown", align: "Allineamento", left: "Sinistra", center: "Centro", right: "Destra" },
  ar: { title: "مولّد جداول Markdown", short: "حوّل بيانات CSV أو المفصولة بعلامات جدولة إلى جدول Markdown.", description: "مولّد جداول Markdown مجاني. الصق صفوف CSV أو مفصولة بعلامات جدولة، اختر محاذاة الأعمدة، واحصل على جدول Markdown نظيف جاهز للنسخ.", keywords: ["مولد جداول markdown", "csv إلى markdown", "جدول markdown", "مولد جدول md", "إنشاء جدول markdown"], input: "البيانات (CSV أو مفصولة بعلامات جدولة)", output: "Markdown", align: "المحاذاة", left: "يسار", center: "وسط", right: "يمين" },
  ru: { title: "Генератор таблиц Markdown", short: "Превратите данные CSV или с табуляцией в таблицу Markdown.", description: "Бесплатный генератор таблиц Markdown. Вставьте строки CSV или с табуляцией, выберите выравнивание столбцов и получите чистую таблицу Markdown, готовую к копированию.", keywords: ["генератор таблиц markdown", "csv в markdown", "таблица markdown", "генератор md таблиц", "создать таблицу markdown"], input: "Данные (CSV или с табуляцией)", output: "Markdown", align: "Выравнивание", left: "Слева", center: "По центру", right: "Справа" },
  zh: { title: "Markdown 表格生成器", short: "将 CSV 或制表符分隔的数据转换为 Markdown 表格。", description: "免费的 Markdown 表格生成器。粘贴 CSV 或制表符分隔的行，选择列对齐方式，即可获得整洁的 GitHub 风格 Markdown 表格，随时可复制。", keywords: ["markdown 表格生成器", "csv 转 markdown", "markdown 表格", "md 表格生成器", "创建 markdown 表格"], input: "数据（CSV 或制表符分隔）", output: "Markdown", align: "对齐", left: "左对齐", center: "居中", right: "右对齐" },
  ja: { title: "Markdown テーブル生成", short: "CSV やタブ区切りデータを Markdown テーブルに変換。", description: "無料の Markdown テーブル生成ツール。CSV またはタブ区切りの行を貼り付け、列の配置を選ぶと、コピー可能な GitHub 風 Markdown テーブルが得られます。", keywords: ["markdown テーブル 生成", "csv から markdown", "markdown テーブル", "md テーブル 生成", "markdown テーブル 作成"], input: "データ（CSV またはタブ区切り）", output: "Markdown", align: "配置", left: "左", center: "中央", right: "右" },
  ko: { title: "Markdown 표 생성기", short: "CSV 또는 탭으로 구분된 데이터를 Markdown 표로 변환합니다.", description: "무료 Markdown 표 생성기. CSV 또는 탭으로 구분된 행을 붙여넣고 열 정렬을 선택하면 복사할 수 있는 깔끔한 GitHub 스타일 Markdown 표를 얻습니다.", keywords: ["markdown 표 생성기", "csv를 markdown으로", "markdown 표", "md 표 생성기", "markdown 표 만들기"], input: "데이터 (CSV 또는 탭 구분)", output: "Markdown", align: "정렬", left: "왼쪽", center: "가운데", right: "오른쪽" },
  hi: { title: "Markdown तालिका जनरेटर", short: "CSV या टैब-सेपरेटेड डेटा को Markdown तालिका में बदलें।", description: "मुफ्त Markdown तालिका जनरेटर। CSV या टैब-सेपरेटेड पंक्तियाँ पेस्ट करें, कॉलम संरेखण चुनें, और कॉपी करने के लिए तैयार एक स्वच्छ GitHub-शैली Markdown तालिका पाएं।", keywords: ["markdown तालिका जनरेटर", "csv से markdown", "markdown तालिका", "md तालिका जनरेटर", "markdown तालिका बनाएं"], input: "डेटा (CSV या टैब-सेपरेटेड)", output: "Markdown", align: "संरेखण", left: "बाएं", center: "मध्य", right: "दाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
