import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Palindrome Checker", short: "Check whether a word or phrase reads the same backwards.", description: "Free palindrome checker. Test if a word, phrase or number is a palindrome — reads the same forwards and backwards. Options to ignore case and punctuation so phrases like 'A man, a plan, a canal: Panama' pass.", keywords: ["palindrome checker", "is it a palindrome", "palindrome test", "check palindrome", "palindrome detector"], placeholder: "Enter a word or phrase…", ignoreCase: "Ignore case", ignorePunctuation: "Ignore spaces & punctuation", isPalindrome: "It's a palindrome!", notPalindrome: "Not a palindrome." },
  nl: { title: "Palindrome Controleur", short: "Controleer whether a word or phrase reads the same backwards.", description: "Gratis palindrome controleur. Test if a word, phrase or nummer is a palindrome — reads the same forwards and backwards. Options to ignore case and punctuation so phrases like 'A man, a plan, a canal: Panama' pass.", keywords: ["palindrome controleur", "is it a palindrome", "palindrome test", "controleer palindrome", "palindrome detector"], placeholder: "Enter a word or phrase…", ignoreCase: "Ignore case", ignorePunctuation: "Ignore spaces & punctuation", isPalindrome: "It's a palindrome!", notPalindrome: "Not a palindrome." },

  pl: { title: "Palindrome Sprawdzarka", short: "Sprawdź whether a word or phrase reads the same backwards.", description: "Darmowy palindrome sprawdzarka. Test if a word, phrase or liczba is a palindrome — reads the same forwards and backwards. Options to ignore case and punctuation so phrases like 'A man, a plan, a canal: Panama' pass.", keywords: ["palindrome sprawdzarka", "is it a palindrome", "palindrome test", "sprawdź palindrome", "palindrome detector"], placeholder: "Enter a word or phrase…", ignoreCase: "Ignore case", ignorePunctuation: "Ignore spaces & punctuation", isPalindrome: "It's a palindrome!", notPalindrome: "Not a palindrome." },
  pt: { title: "Verificador de Palindrome", short: "Verificar whether a word ou phrase reads the same backwards.", description: "Gratuito - palindrome checker. Test if a word, phrase ou number is a palindrome â reads the same forwards e backwards. Options para ignore case e punctuation so phrases like 'Um man, a plan, a canal: Panama' pass.", keywords: ["palindrome checker", "is it a palindrome", "palindrome test", "check palindrome", "palindrome detector"], placeholder: "Enter a word or phrase…", ignoreCase: "Ignore case", ignorePunctuation: "Ignore spaces & punctuation", isPalindrome: "It's a palindrome!", notPalindrome: "Not a palindrome." },
  id: { title: "Pemeriksa Palindrome", short: "Periksa whether a word atau phrase reads the same backwards.", description: "Gratis - palindrome checker. Test if a word, phrase atau number is a palindrome â reads the same forwards dan backwards. Options to ignore case dan punctuation so phrases like 'Sebuah man, a plan, a canal: Panama' pass.", keywords: ["palindrome checker", "is it a palindrome", "palindrome test", "check palindrome", "palindrome detector"], placeholder: "Enter a word or phrase…", ignoreCase: "Ignore case", ignorePunctuation: "Ignore spaces & punctuation", isPalindrome: "It's a palindrome!", notPalindrome: "Not a palindrome." },

  tr: { title: "Palindrom Denetleyici", short: "Bir kelimenin veya ifadenin tersten aynı okunup okunmadığını kontrol edin.", description: "Ücretsiz palindrom denetleyici. Bir kelime, ifade veya sayının palindrom olup olmadığını test edin — düz ve tersten aynı okunur. Büyük/küçük harf ve noktalamayı yok sayma seçenekleriyle.", keywords: ["palindrom denetleyici", "palindrom mu", "palindrom testi", "palindrom kontrol", "palindrom bulucu"], placeholder: "Bir kelime veya ifade girin…", ignoreCase: "Harf duyarsız", ignorePunctuation: "Boşluk ve noktalamayı yok say", isPalindrome: "Bu bir palindrom!", notPalindrome: "Palindrom değil." },
  de: { title: "Palindrom-Prüfer", short: "Prüfen Sie, ob ein Wort oder Satz rückwärts gleich gelesen wird.", description: "Kostenloser Palindrom-Prüfer. Testen Sie, ob ein Wort, Satz oder eine Zahl ein Palindrom ist — vorwärts und rückwärts gleich. Mit Optionen, Groß-/Kleinschreibung und Satzzeichen zu ignorieren.", keywords: ["palindrom prüfer", "ist es ein palindrom", "palindrom test", "palindrom prüfen"], placeholder: "Wort oder Satz eingeben…", ignoreCase: "Groß/klein ignorieren", ignorePunctuation: "Leerzeichen & Satzzeichen ignorieren", isPalindrome: "Es ist ein Palindrom!", notPalindrome: "Kein Palindrom." },
  fr: { title: "Vérificateur de Palindrome", short: "Vérifiez si un mot ou une phrase se lit pareil à l'envers.", description: "Vérificateur de palindrome gratuit. Testez si un mot, une phrase ou un nombre est un palindrome — se lit pareil dans les deux sens. Options pour ignorer la casse et la ponctuation.", keywords: ["vérificateur de palindrome", "est-ce un palindrome", "test palindrome", "vérifier palindrome"], placeholder: "Saisissez un mot ou une phrase…", ignoreCase: "Ignorer la casse", ignorePunctuation: "Ignorer espaces & ponctuation", isPalindrome: "C'est un palindrome !", notPalindrome: "Pas un palindrome." },
  es: { title: "Verificador de Palíndromos", short: "Comprueba si una palabra o frase se lee igual al revés.", description: "Verificador de palíndromos gratuito. Comprueba si una palabra, frase o número es un palíndromo — se lee igual en ambos sentidos. Opciones para ignorar mayúsculas y puntuación.", keywords: ["verificador de palíndromos", "es un palíndromo", "test de palíndromo", "comprobar palíndromo"], placeholder: "Introduce una palabra o frase…", ignoreCase: "Ignorar mayúsculas", ignorePunctuation: "Ignorar espacios y puntuación", isPalindrome: "¡Es un palíndromo!", notPalindrome: "No es un palíndromo." },
  it: { title: "Verificatore di Palindromi", short: "Controlla se una parola o frase si legge uguale al contrario.", description: "Verificatore di palindromi gratuito. Verifica se una parola, frase o numero è un palindromo — si legge uguale in entrambi i sensi. Opzioni per ignorare maiuscole e punteggiatura.", keywords: ["verificatore di palindromi", "è un palindromo", "test palindromo", "controlla palindromo"], placeholder: "Inserisci una parola o frase…", ignoreCase: "Ignora maiuscole", ignorePunctuation: "Ignora spazi e punteggiatura", isPalindrome: "È un palindromo!", notPalindrome: "Non è un palindromo." },
  ar: { title: "فاحص الجناس المقلوب", short: "تحقق مما إذا كانت كلمة أو عبارة تُقرأ بنفس الشكل عكسيًا.", description: "فاحص جناس مقلوب مجاني. اختبر ما إذا كانت كلمة أو عبارة أو رقم جناسًا مقلوبًا — يُقرأ بنفس الشكل من الاتجاهين. خيارات لتجاهل حالة الأحرف وعلامات الترقيم.", keywords: ["فاحص الجناس المقلوب", "هل هو جناس مقلوب", "اختبار الجناس", "فحص الجناس المقلوب"], placeholder: "أدخل كلمة أو عبارة…", ignoreCase: "تجاهل حالة الأحرف", ignorePunctuation: "تجاهل المسافات وعلامات الترقيم", isPalindrome: "إنه جناس مقلوب!", notPalindrome: "ليس جناسًا مقلوبًا." },
  ru: { title: "Проверка Палиндрома", short: "Проверьте, читается ли слово или фраза одинаково задом наперёд.", description: "Бесплатная проверка палиндрома. Проверьте, является ли слово, фраза или число палиндромом — читается одинаково в обе стороны. Опции игнорирования регистра и пунктуации.", keywords: ["проверка палиндрома", "это палиндром", "тест палиндрома", "проверить палиндром"], placeholder: "Введите слово или фразу…", ignoreCase: "Игнорировать регистр", ignorePunctuation: "Игнорировать пробелы и пунктуацию", isPalindrome: "Это палиндром!", notPalindrome: "Не палиндром." },
  zh: { title: "回文检查器", short: "检查单词或短语正读和反读是否相同。", description: "免费的回文检查器。测试单词、短语或数字是否为回文——正读反读相同。可选择忽略大小写和标点，让“上海自来水来自海上”这类短语通过。", keywords: ["回文检查器", "是不是回文", "回文测试", "检查回文"], placeholder: "输入单词或短语…", ignoreCase: "忽略大小写", ignorePunctuation: "忽略空格和标点", isPalindrome: "这是一个回文！", notPalindrome: "不是回文。" },
  ja: { title: "回文チェッカー", short: "単語やフレーズが逆から読んでも同じか確認します。", description: "無料の回文チェッカー。単語・フレーズ・数字が回文か（前からも後ろからも同じに読めるか）をテストします。大文字小文字や句読点を無視するオプション付き。", keywords: ["回文チェッカー", "回文かどうか", "回文テスト", "回文 判定"], placeholder: "単語やフレーズを入力…", ignoreCase: "大文字小文字を無視", ignorePunctuation: "空白と句読点を無視", isPalindrome: "回文です！", notPalindrome: "回文ではありません。" },
  ko: { title: "회문 검사기", short: "단어나 구절이 거꾸로 읽어도 같은지 확인합니다.", description: "무료 회문 검사기. 단어, 구절, 숫자가 회문인지(앞뒤로 같게 읽히는지) 테스트합니다. 대소문자와 문장 부호를 무시하는 옵션이 있습니다.", keywords: ["회문 검사기", "회문인가", "회문 테스트", "회문 확인"], placeholder: "단어나 구절을 입력하세요…", ignoreCase: "대소문자 무시", ignorePunctuation: "공백과 문장 부호 무시", isPalindrome: "회문입니다!", notPalindrome: "회문이 아닙니다." },
  hi: { title: "पैलिंड्रोम चेकर", short: "जांचें कि कोई शब्द या वाक्यांश उल्टा पढ़ने पर भी वही पढ़ा जाता है या नहीं।", description: "मुफ्त पैलिंड्रोम चेकर। जांचें कि कोई शब्द, वाक्यांश या संख्या पैलिंड्रोम है या नहीं — आगे और पीछे से समान पढ़ी जाती है। केस और विराम चिह्न अनदेखा करने के विकल्प के साथ।", keywords: ["पैलिंड्रोम चेकर", "क्या यह पैलिंड्रोम है", "पैलिंड्रोम टेस्ट", "पैलिंड्रोम जांचें"], placeholder: "एक शब्द या वाक्यांश दर्ज करें…", ignoreCase: "केस अनदेखा करें", ignorePunctuation: "स्पेस और विराम चिह्न अनदेखा करें", isPalindrome: "यह एक पैलिंड्रोम है!", notPalindrome: "पैलिंड्रोम नहीं है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
