import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Batch Unix Timestamp Converter", short: "Convert many Unix timestamps to human dates at once.", description: "Free batch Unix timestamp converter. Paste many timestamps (seconds, milliseconds or ISO strings) — one per line — to see ISO, UTC, local and relative dates for each. Runs entirely in your browser.", keywords: ["unix timestamp batch", "epoch batch converter", "bulk timestamp converter", "many timestamps", "timestamps to dates"], input: "Timestamps (one per line)", iso: "ISO 8601", utc: "UTC", local: "Local", relative: "Relative" },
  tr: { title: "Toplu Unix Zaman Damgası Dönüştürücü", short: "Çoklu Unix zaman damgalarını aynı anda insan tarihlerine dönüştürün.", description: "Ücretsiz toplu Unix zaman damgası dönüştürücü. Birden fazla zaman damgasını (saniye, milisaniye veya ISO dizeleri) — her satıra bir tane — yapıştırın ve her biri için ISO, UTC, yerel ve göreli tarihleri görün. Tamamen tarayıcınızda çalışır.", keywords: ["unix zaman damgası toplu", "epoch toplu dönüştürücü", "toplu zaman damgası dönüştürücü", "çok zaman damgası", "zaman damgalarından tarihlere"], input: "Zaman damgaları (her satıra bir)", iso: "ISO 8601", utc: "UTC", local: "Yerel", relative: "Göreli" },
  de: { title: "Batch-Unix-Zeitstempel-Konverter", short: "Konvertieren Sie viele Unix-Zeitstempel auf einmal in menschliche Daten.", description: "Kostenloser Batch-Unix-Zeitstempel-Konverter. Fügen Sie viele Zeitstempel (Sekunden, Millisekunden oder ISO-Strings) — einen pro Zeile — ein, um ISO, UTC, lokale und relative Daten für jeden zu sehen. Läuft vollständig im Browser.", keywords: ["unix zeitstempel batch", "epoch batch konverter", "massen zeitstempel konverter", "viele zeitstempel", "zeitstempel zu daten"], input: "Zeitstempel (einer pro Zeile)", iso: "ISO 8601", utc: "UTC", local: "Lokal", relative: "Relativ" },
  fr: { title: "Convertisseur Batch d'Horodatages Unix", short: "Convertissez de nombreux horodatages Unix en dates lisibles en une fois.", description: "Convertisseur batch d'horodatages Unix gratuit. Collez de nombreux horodatages (secondes, millisecondes ou chaînes ISO) — un par ligne — pour voir les dates ISO, UTC, locales et relatives pour chacun. Fonctionne entièrement dans votre navigateur.", keywords: ["batch horodatage unix", "convertisseur batch epoch", "convertisseur horodatage en masse", "nombreux horodatages", "horodatages vers dates"], input: "Horodatages (un par ligne)", iso: "ISO 8601", utc: "UTC", local: "Local", relative: "Relatif" },
  es: { title: "Convertidor por Lotes de Timestamps Unix", short: "Convierte muchos timestamps Unix a fechas humanas a la vez.", description: "Convertidor por lotes de timestamps Unix gratuito. Pega muchos timestamps (segundos, milisegundos o cadenas ISO) — uno por línea — para ver las fechas ISO, UTC, locales y relativas de cada uno. Funciona completamente en tu navegador.", keywords: ["timestamp unix lote", "convertidor epoch lote", "convertidor masivo timestamp", "muchos timestamps", "timestamps a fechas"], input: "Timestamps (uno por línea)", iso: "ISO 8601", utc: "UTC", local: "Local", relative: "Relativo" },
  it: { title: "Convertitore Batch di Timestamp Unix", short: "Converti molti timestamp Unix in date umane in una volta.", description: "Convertitore batch di timestamp Unix gratuito. Incolla molti timestamp (secondi, millisecondi o stringhe ISO) — uno per riga — per vedere le date ISO, UTC, locali e relative per ciascuno. Funziona interamente nel browser.", keywords: ["timestamp unix batch", "convertitore epoch batch", "convertitore timestamp di massa", "molti timestamp", "timestamp in date"], input: "Timestamp (uno per riga)", iso: "ISO 8601", utc: "UTC", local: "Locale", relative: "Relativo" },
  ar: { title: "محوّل دفعات الطوابع الزمنية Unix", short: "حوّل العديد من الطوابع الزمنية Unix إلى تواريخ بشرية دفعة واحدة.", description: "محوّل دفعات طوابع زمنية Unix مجاني. الصق العديد من الطوابع الزمنية (ثوانٍ أو ميلي ثانية أو سلاسل ISO) — واحدة لكل سطر — لرؤية تواريخ ISO و UTC والمحلية والنسبية لكل منها. يعمل بالكامل في متصفحك.", keywords: ["unix طابع زمني دفعة", "محول epoch دفعة", "محول طابع زمني مجمّع", "طوابع زمنية متعددة", "طوابع زمنية إلى تواريخ"], input: "الطوابع الزمنية (واحدة لكل سطر)", iso: "ISO 8601", utc: "UTC", local: "محلي", relative: "نسبي" },
  ru: { title: "Пакетный конвертер Unix-таймстампов", short: "Конвертируйте множество Unix-таймстампов в человеческие даты сразу.", description: "Бесплатный пакетный конвертер Unix-таймстампов. Вставьте множество таймстампов (секунды, миллисекунды или ISO-строки) — по одному в строке — чтобы увидеть ISO, UTC, локальные и относительные даты для каждого. Работает полностью в браузере.", keywords: ["unix таймстамп пакет", "epoch пакет конвертер", "массовый конвертер таймстампов", "много таймстампов", "таймстампы в даты"], input: "Таймстампы (по одному в строке)", iso: "ISO 8601", utc: "UTC", local: "Локальное", relative: "Относительное" },
  zh: { title: "批量 Unix 时间戳转换器", short: "一次将多个 Unix 时间戳转换为可读日期。", description: "免费的批量 Unix 时间戳转换器。粘贴多个时间戳（秒、毫秒或 ISO 字符串）——每行一个——查看每个的 ISO、UTC、本地和相对日期。完全在浏览器中运行。", keywords: ["unix 时间戳 批量", "epoch 批量转换器", "批量时间戳转换器", "多个时间戳", "时间戳转日期"], input: "时间戳（每行一个）", iso: "ISO 8601", utc: "UTC", local: "本地", relative: "相对" },
  ja: { title: "バッチ Unix タイムスタンプ変換", short: "多数の Unix タイムスタンプを一度に人間が読める日付に変換。", description: "無料のバッチ Unix タイムスタンプ変換ツール。多数のタイムスタンプ（秒、ミリ秒、ISO 文字列）—1 行に 1 つ—を貼り付けて、それぞれの ISO、UTC、ローカル、相対日付を表示します。すべてブラウザ内で動作します。", keywords: ["unix タイムスタンプ バッチ", "epoch バッチ 変換", "一括 タイムスタンプ 変換", "多数の タイムスタンプ", "タイムスタンプから日付"], input: "タイムスタンプ（1 行に 1 つ）", iso: "ISO 8601", utc: "UTC", local: "ローカル", relative: "相対" },
  ko: { title: "배치 Unix 타임스탬프 변환기", short: "여러 Unix 타임스탬프를 한 번에 사람이 읽을 수 있는 날짜로 변환합니다.", description: "무료 배치 Unix 타임스탬프 변환기. 여러 타임스탬프(초, 밀리초 또는 ISO 문자열)를 — 한 줄에 하나 — 붙여넣으면 각각의 ISO, UTC, 로컬, 상대 날짜를 볼 수 있습니다. 모두 브라우저에서 실행됩니다.", keywords: ["unix 타임스탬프 배치", "epoch 배치 변환기", "대량 타임스탬프 변환기", "여러 타임스탬프", "타임스탬프를 날짜로"], input: "타임스탬프 (한 줄에 하나)", iso: "ISO 8601", utc: "UTC", local: "로컬", relative: "상대" },
  hi: { title: "बैच Unix टाइमस्टैम्प कन्वर्टर", short: "एक साथ कई Unix टाइमस्टैम्प को मानव तिथियों में बदलें।", description: "मुफ्त बैच Unix टाइमस्टैम्प कन्वर्टर। कई टाइमस्टैम्प (सेकंड, मिलीसेकंड या ISO स्ट्रिंग) — प्रति पंक्ति एक — पेस्ट करें ताकि प्रत्येक के लिए ISO, UTC, स्थानीय और सापेक्ष तिथियाँ देख सकें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["unix टाइमस्टैम्प बैच", "epoch बैच कन्वर्टर", "बल्क टाइमस्टैम्प कन्वर्टर", "कई टाइमस्टैम्प", "टाइमस्टैम्प से तिथियाँ"], input: "टाइमस्टैम्प (प्रति पंक्ति एक)", iso: "ISO 8601", utc: "UTC", local: "स्थानीय", relative: "सापेक्ष" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
