import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSV to JSON Converter", short: "Convert CSV data to JSON, with optional header row.", description: "Free CSV-to-JSON converter. Paste CSV and get JSON — either an array of objects keyed by the header row, or an array of arrays. Handles quoted fields and custom delimiters. Runs in your browser.", keywords: ["csv to json", "convert csv to json", "csv parser", "csv json converter", "csv to json online"], placeholder: "name,age\nAlice,30\nBob,25", header: "First row is header", delimiter: "Delimiter", comma: "Comma (,)", semicolon: "Semicolon (;)", tab: "Tab" },
  pt: { title: "Conversor de CSV to JSON", short: "Converter CSV data para JSON, com optional header row.", description: "Gratuito - CSV-para-JSON converter. Paste CSV e get JSON â either an array de objects keyed by the header row, ou an array de arrays. Handles quoted fields e custom delimiters. Runs no seu navegador.", keywords: ["csv to json", "convert csv to json", "csv parser", "csv json converter", "csv to json online"], placeholder: "name,age\nAlice,30\nBob,25", header: "First row is header", delimiter: "Delimiter", comma: "Comma (,)", semicolon: "Semicolon (;)", tab: "Tab" },
  id: { title: "Konverter CSV to JSON", short: "Konversi CSV data to JSON, with optional header row.", description: "Gratis - CSV-to-JSON converter. Paste CSV dan get JSON â either an array dari objects keyed by the header row, atau an array dari arrays. Handles quoted fields dan custom delimiters. Runs di browser Anda.", keywords: ["csv to json", "convert csv to json", "csv parser", "csv json converter", "csv to json online"], placeholder: "name,age\nAlice,30\nBob,25", header: "First row is header", delimiter: "Delimiter", comma: "Comma (,)", semicolon: "Semicolon (;)", tab: "Tab" },

  tr: { title: "CSV'den JSON'a Dönüştürücü", short: "CSV verisini JSON'a dönüştürün, isteğe bağlı başlık satırıyla.", description: "Ücretsiz CSV'den JSON'a dönüştürücü. CSV yapıştırın ve JSON alın — başlık satırına göre anahtarlanmış nesne dizisi veya dizi dizisi olarak. Tırnaklı alanları ve özel ayırıcıları işler. Tarayıcınızda çalışır.", keywords: ["csv'den json'a", "csv json dönüştür", "csv ayrıştırıcı", "csv json dönüştürücü"], placeholder: "ad,yas\nAli,30\nVeli,25", header: "İlk satır başlık", delimiter: "Ayırıcı", comma: "Virgül (,)", semicolon: "Noktalı virgül (;)", tab: "Sekme" },
  de: { title: "CSV-zu-JSON-Konverter", short: "Konvertieren Sie CSV-Daten in JSON, mit optionaler Kopfzeile.", description: "Kostenloser CSV-zu-JSON-Konverter. CSV einfügen und JSON erhalten — als Array von Objekten (mit der Kopfzeile als Schlüssel) oder als Array von Arrays. Behandelt zitierte Felder und Trennzeichen.", keywords: ["csv zu json", "csv in json konvertieren", "csv parser", "csv json konverter"], placeholder: "name,alter\nAlice,30\nBob,25", header: "Erste Zeile ist Kopfzeile", delimiter: "Trennzeichen", comma: "Komma (,)", semicolon: "Semikolon (;)", tab: "Tabulator" },
  fr: { title: "Convertisseur CSV vers JSON", short: "Convertissez des données CSV en JSON, avec ligne d'en-tête optionnelle.", description: "Convertisseur CSV-vers-JSON gratuit. Collez du CSV et obtenez du JSON — un tableau d'objets indexés par l'en-tête, ou un tableau de tableaux. Gère les champs entre guillemets et les délimiteurs.", keywords: ["csv vers json", "convertir csv en json", "analyseur csv", "convertisseur csv json"], placeholder: "nom,age\nAlice,30\nBob,25", header: "Première ligne = en-tête", delimiter: "Délimiteur", comma: "Virgule (,)", semicolon: "Point-virgule (;)", tab: "Tabulation" },
  es: { title: "Convertidor de CSV a JSON", short: "Convierte datos CSV a JSON, con fila de encabezado opcional.", description: "Convertidor CSV-a-JSON gratuito. Pega CSV y obtén JSON — un array de objetos con claves de la fila de encabezado, o un array de arrays. Maneja campos entrecomillados y delimitadores.", keywords: ["csv a json", "convertir csv a json", "analizador csv", "convertidor csv json"], placeholder: "nombre,edad\nAlicia,30\nBob,25", header: "La primera fila es encabezado", delimiter: "Delimitador", comma: "Coma (,)", semicolon: "Punto y coma (;)", tab: "Tabulación" },
  it: { title: "Convertitore da CSV a JSON", short: "Converti dati CSV in JSON, con riga di intestazione opzionale.", description: "Convertitore CSV-a-JSON gratuito. Incolla CSV e ottieni JSON — un array di oggetti con chiavi dalla riga di intestazione, o un array di array. Gestisce campi tra virgolette e delimitatori.", keywords: ["csv a json", "convertire csv in json", "parser csv", "convertitore csv json"], placeholder: "nome,eta\nAlice,30\nBob,25", header: "La prima riga è intestazione", delimiter: "Delimitatore", comma: "Virgola (,)", semicolon: "Punto e virgola (;)", tab: "Tabulazione" },
  ar: { title: "محوّل CSV إلى JSON", short: "حوّل بيانات CSV إلى JSON، مع صف رأس اختياري.", description: "محوّل CSV إلى JSON مجاني. الصق CSV واحصل على JSON — مصفوفة كائنات مفهرسة بصف الرأس، أو مصفوفة مصفوفات. يعالج الحقول المقتبسة والفواصل المخصصة. يعمل في متصفحك.", keywords: ["csv إلى json", "تحويل csv إلى json", "محلل csv", "محول csv json"], placeholder: "الاسم,العمر\nعلي,30\nسارة,25", header: "الصف الأول رأس", delimiter: "الفاصل", comma: "فاصلة (,)", semicolon: "فاصلة منقوطة (;)", tab: "جدولة" },
  ru: { title: "Конвертер CSV в JSON", short: "Преобразуйте данные CSV в JSON, с необязательной строкой заголовка.", description: "Бесплатный конвертер CSV в JSON. Вставьте CSV и получите JSON — массив объектов с ключами из заголовка или массив массивов. Обрабатывает поля в кавычках и разделители. Работает в браузере.", keywords: ["csv в json", "преобразовать csv в json", "парсер csv", "конвертер csv json"], placeholder: "имя,возраст\nАлиса,30\nБоб,25", header: "Первая строка — заголовок", delimiter: "Разделитель", comma: "Запятая (,)", semicolon: "Точка с запятой (;)", tab: "Таб" },
  zh: { title: "CSV 转 JSON 转换器", short: "将 CSV 数据转换为 JSON，可选表头行。", description: "免费的 CSV 转 JSON 转换器。粘贴 CSV 即可得到 JSON——以表头行为键的对象数组，或数组的数组。处理带引号的字段和自定义分隔符。在浏览器中运行。", keywords: ["csv转json", "csv转json转换", "csv解析器", "csv json转换器"], placeholder: "姓名,年龄\nAlice,30\nBob,25", header: "首行为表头", delimiter: "分隔符", comma: "逗号 (,)", semicolon: "分号 (;)", tab: "制表符" },
  ja: { title: "CSV → JSON 変換", short: "CSV データを JSON に変換します（ヘッダー行は任意）。", description: "無料の CSV→JSON 変換ツール。CSV を貼り付けると JSON が得られます — ヘッダー行をキーにしたオブジェクト配列、または配列の配列。引用フィールドやカスタム区切りに対応。ブラウザ内で動作します。", keywords: ["csv json 変換", "csv を json に", "csv パーサー", "csv json コンバーター"], placeholder: "名前,年齢\nAlice,30\nBob,25", header: "1行目はヘッダー", delimiter: "区切り文字", comma: "カンマ (,)", semicolon: "セミコロン (;)", tab: "タブ" },
  ko: { title: "CSV → JSON 변환기", short: "CSV 데이터를 JSON으로 변환합니다(헤더 행 선택).", description: "무료 CSV→JSON 변환기. CSV를 붙여넣으면 JSON을 얻습니다 — 헤더 행을 키로 하는 객체 배열 또는 배열의 배열. 따옴표 필드와 사용자 지정 구분자를 처리합니다. 브라우저에서 실행됩니다.", keywords: ["csv json 변환", "csv를 json으로", "csv 파서", "csv json 변환기"], placeholder: "이름,나이\nAlice,30\nBob,25", header: "첫 행이 헤더", delimiter: "구분자", comma: "쉼표 (,)", semicolon: "세미콜론 (;)", tab: "탭" },
  hi: { title: "CSV से JSON कन्वर्टर", short: "CSV डेटा को JSON में बदलें, वैकल्पिक हेडर पंक्ति के साथ।", description: "मुफ्त CSV-से-JSON कन्वर्टर। CSV पेस्ट करें और JSON पाएं — हेडर पंक्ति को कुंजी मानते हुए ऑब्जेक्ट की सरणी, या सरणियों की सरणी। उद्धृत फ़ील्ड और कस्टम विभाजक संभालता है। ब्राउज़र में चलता है।", keywords: ["csv से json", "csv को json में बदलें", "csv पार्सर", "csv json कन्वर्टर"], placeholder: "नाम,आयु\nAlice,30\nBob,25", header: "पहली पंक्ति हेडर है", delimiter: "विभाजक", comma: "अल्पविराम (,)", semicolon: "अर्धविराम (;)", tab: "टैब" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
