import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "QR Code Scanner", short: "Scan a QR code with your camera or by uploading an image.", description: "Free online QR code scanner. Read a QR code live with your device camera or by uploading a photo — decoding happens entirely in your browser, nothing is uploaded.", keywords: ["qr code scanner", "qr reader online", "scan qr code", "read qr code", "qr code reader webcam"], useCamera: "Use camera", stopCamera: "Stop camera", uploadImage: "Upload image", decoded: "Decoded content", noQr: "No QR code found in that image.", cameraDenied: "Camera unavailable or permission denied. Try uploading an image instead.", openLink: "Open", privacyNote: "Scanning runs entirely in your browser; nothing is uploaded." },
  nl: { title: "QR Code Scanner", short: "Scan a QR code with your camera or by uploading an afbeelding.", description: "Gratis online QR code scanner. Read a QR code live with your device camera or by uploading a photo — decoding happens entirely in uw browser, nothing is uploaded.", keywords: ["qr code scanner", "qr reader online", "scan qr code", "read qr code", "qr code reader webcam"], useCamera: "Use camera", stopCamera: "Stop camera", uploadImage: "Upload afbeelding", decoded: "Decoded content", noQr: "No QR code found in that afbeelding.", cameraDenied: "Camera unavailable or permission denied. Try uploading an afbeelding instead.", openLink: "Open", privacyNote: "Scanning runs entirely in uw browser; nothing is uploaded." },

  pl: { title: "QR Kod Scanner", short: "Scan a QR kod with your camera or by uploading an obraz.", description: "Darmowy online QR kod scanner. Read a QR kod live with your device camera or by uploading a photo — decoding happens entirely w Twojej przeglądarce, nothing is uploaded.", keywords: ["qr kod scanner", "qr reader online", "scan qr kod", "read qr kod", "qr kod reader webcam"], useCamera: "Use camera", stopCamera: "Stop camera", uploadImage: "Upload obraz", decoded: "Dekodd content", noQr: "No QR kod found in that obraz.", cameraDenied: "Camera unavailable or permission denied. Try uploading an obraz instead.", openLink: "Open", privacyNote: "Scanning runs entirely w Twojej przeglądarce; nothing is uploaded." },
  tr: { title: "QR Kod Tarayıcı", short: "Kameranızla veya bir görsel yükleyerek QR kod tarayın.", description: "Ücretsiz çevrimiçi QR kod tarayıcı. Cihaz kameranızla canlı olarak veya bir fotoğraf yükleyerek QR kodu okuyun — çözümleme tamamen tarayıcınızda yapılır, hiçbir şey yüklenmez.", keywords: ["qr kod tarayıcı", "çevrimiçi qr okuyucu", "qr kod tara", "qr kod oku", "webcam qr okuyucu"], useCamera: "Kamerayı kullan", stopCamera: "Kamerayı durdur", uploadImage: "Görsel yükle", decoded: "Çözülen içerik", noQr: "Bu görselde QR kod bulunamadı.", cameraDenied: "Kamera kullanılamıyor veya izin reddedildi. Bunun yerine bir görsel yüklemeyi deneyin.", openLink: "Aç", privacyNote: "Tarama tamamen tarayıcınızda çalışır; hiçbir şey yüklenmez." },
  de: { title: "QR-Code-Scanner", short: "Scannen Sie einen QR-Code mit der Kamera oder per Bild-Upload.", description: "Kostenloser Online-QR-Code-Scanner. Lesen Sie einen QR-Code live mit der Gerätekamera oder durch Hochladen eines Fotos — die Dekodierung erfolgt vollständig im Browser, nichts wird hochgeladen.", keywords: ["qr code scanner", "qr reader online", "qr code scannen", "qr code lesen", "qr code reader webcam"], useCamera: "Kamera verwenden", stopCamera: "Kamera stoppen", uploadImage: "Bild hochladen", decoded: "Dekodierter Inhalt", noQr: "Kein QR-Code in diesem Bild gefunden.", cameraDenied: "Kamera nicht verfügbar oder Zugriff verweigert. Laden Sie stattdessen ein Bild hoch.", openLink: "Öffnen", privacyNote: "Das Scannen läuft vollständig im Browser; nichts wird hochgeladen." },
  fr: { title: "Scanner de QR Code", short: "Scannez un QR code avec votre caméra ou en important une image.", description: "Scanner de QR code en ligne gratuit. Lisez un QR code en direct avec la caméra de votre appareil ou en important une photo — le décodage se fait entièrement dans votre navigateur, rien n'est envoyé.", keywords: ["scanner qr code", "lecteur qr en ligne", "scanner un qr code", "lire un qr code", "lecteur qr webcam"], useCamera: "Utiliser la caméra", stopCamera: "Arrêter la caméra", uploadImage: "Importer une image", decoded: "Contenu décodé", noQr: "Aucun QR code trouvé dans cette image.", cameraDenied: "Caméra indisponible ou autorisation refusée. Essayez d'importer une image.", openLink: "Ouvrir", privacyNote: "Le scan s'effectue entièrement dans votre navigateur ; rien n'est envoyé." },
  es: { title: "Escáner de Códigos QR", short: "Escanea un código QR con la cámara o subiendo una imagen.", description: "Escáner de códigos QR en línea gratuito. Lee un código QR en vivo con la cámara de tu dispositivo o subiendo una foto — la decodificación ocurre completamente en tu navegador, nada se sube.", keywords: ["escáner qr", "lector qr online", "escanear código qr", "leer código qr", "lector qr webcam"], useCamera: "Usar cámara", stopCamera: "Detener cámara", uploadImage: "Subir imagen", decoded: "Contenido decodificado", noQr: "No se encontró ningún código QR en esa imagen.", cameraDenied: "Cámara no disponible o permiso denegado. Prueba a subir una imagen.", openLink: "Abrir", privacyNote: "El escaneo se ejecuta completamente en tu navegador; nada se sube." },
  it: { title: "Scanner di Codici QR", short: "Scansiona un codice QR con la fotocamera o caricando un'immagine.", description: "Scanner di codici QR online gratuito. Leggi un codice QR dal vivo con la fotocamera del dispositivo o caricando una foto — la decodifica avviene interamente nel browser, nulla viene caricato.", keywords: ["scanner qr", "lettore qr online", "scansiona codice qr", "leggi codice qr", "lettore qr webcam"], useCamera: "Usa fotocamera", stopCamera: "Ferma fotocamera", uploadImage: "Carica immagine", decoded: "Contenuto decodificato", noQr: "Nessun codice QR trovato in quell'immagine.", cameraDenied: "Fotocamera non disponibile o permesso negato. Prova a caricare un'immagine.", openLink: "Apri", privacyNote: "La scansione avviene interamente nel browser; nulla viene caricato." },
  pt: { title: "Leitor de QR Code", short: "Escaneie um QR code com a câmera ou enviando uma imagem.", description: "Leitor de QR code online gratuito. Leia um QR code ao vivo com a câmera do seu dispositivo ou enviando uma foto — a decodificação acontece inteiramente no seu navegador, nada é enviado.", keywords: ["qr code scanner", "qr reader online", "scan qr code", "read qr code", "qr code reader webcam"], useCamera: "Usar câmera", stopCamera: "Parar câmera", uploadImage: "Enviar imagem", decoded: "Conteúdo decodificado", noQr: "Nenhum QR code encontrado nessa imagem.", cameraDenied: "Câmera indisponível ou permissão negada. Tente enviar uma imagem.", openLink: "Abrir", privacyNote: "A leitura é feita inteiramente no seu navegador; nada é enviado." },
  id: { title: "Pemindai Kode QR", short: "Pindai kode QR dengan kamera atau mengunggah gambar.", description: "Pemindai kode QR online gratis. Baca kode QR secara langsung dengan kamera perangkat Anda atau dengan mengunggah foto — dekode terjadi sepenuhnya di browser Anda, tidak ada yang diunggah.", keywords: ["qr code scanner", "qr reader online", "scan qr code", "read qr code", "qr code reader webcam"], useCamera: "Gunakan kamera", stopCamera: "Hentikan kamera", uploadImage: "Unggah gambar", decoded: "Konten terdekode", noQr: "Tidak ada kode QR ditemukan pada gambar itu.", cameraDenied: "Kamera tidak tersedia atau izin ditolak. Coba unggah gambar saja.", openLink: "Buka", privacyNote: "Pemindaian berjalan sepenuhnya di browser Anda; tidak ada yang diunggah." },
  ar: { title: "ماسح رمز QR", short: "امسح رمز QR بالكاميرا أو عبر رفع صورة.", description: "ماسح رموز QR مجاني عبر الإنترنت. اقرأ رمز QR مباشرة بكاميرا جهازك أو برفع صورة — يتم فك التشفير بالكامل في متصفحك، ولا يتم رفع أي شيء.", keywords: ["ماسح qr", "قارئ qr عبر الإنترنت", "مسح رمز qr", "قراءة رمز qr", "قارئ qr بالكاميرا"], useCamera: "استخدام الكاميرا", stopCamera: "إيقاف الكاميرا", uploadImage: "رفع صورة", decoded: "المحتوى المفكوك", noQr: "لم يتم العثور على رمز QR في تلك الصورة.", cameraDenied: "الكاميرا غير متاحة أو تم رفض الإذن. حاول رفع صورة بدلاً من ذلك.", openLink: "فتح", privacyNote: "يتم المسح بالكامل في متصفحك؛ لا يتم رفع أي شيء." },
  ru: { title: "Сканер QR-кодов", short: "Сканируйте QR-код камерой или загрузив изображение.", description: "Бесплатный онлайн-сканер QR-кодов. Считайте QR-код в реальном времени камерой устройства или загрузив фото — декодирование происходит полностью в браузере, ничего не загружается.", keywords: ["сканер qr", "qr ридер онлайн", "сканировать qr-код", "прочитать qr-код", "qr ридер веб-камера"], useCamera: "Использовать камеру", stopCamera: "Остановить камеру", uploadImage: "Загрузить изображение", decoded: "Декодированное содержимое", noQr: "QR-код на этом изображении не найден.", cameraDenied: "Камера недоступна или доступ запрещён. Попробуйте загрузить изображение.", openLink: "Открыть", privacyNote: "Сканирование выполняется полностью в браузере; ничего не загружается." },
  zh: { title: "二维码扫描器", short: "用相机或上传图片扫描二维码。", description: "免费在线二维码扫描器。使用设备相机实时读取二维码，或上传照片识别——解码完全在浏览器中完成，不上传任何内容。", keywords: ["二维码扫描器", "在线二维码读取", "扫描二维码", "读取二维码", "网络摄像头二维码读取"], useCamera: "使用相机", stopCamera: "停止相机", uploadImage: "上传图片", decoded: "解码内容", noQr: "在该图片中未找到二维码。", cameraDenied: "相机不可用或权限被拒绝。请尝试上传图片。", openLink: "打开", privacyNote: "扫描完全在您的浏览器中进行，不上传任何内容。" },
  ja: { title: "QR コードスキャナー", short: "カメラまたは画像アップロードで QR コードをスキャン。", description: "無料のオンライン QR コードスキャナー。デバイスのカメラでリアルタイムに、または写真をアップロードして QR コードを読み取り——デコードはすべてブラウザ内で行われ、何もアップロードされません。", keywords: ["qr コードスキャナー", "オンライン qr リーダー", "qr コードスキャン", "qr コード読み取り", "webカメラ qr リーダー"], useCamera: "カメラを使う", stopCamera: "カメラを停止", uploadImage: "画像をアップロード", decoded: "デコード結果", noQr: "その画像に QR コードが見つかりませんでした。", cameraDenied: "カメラが利用できないか権限が拒否されました。画像のアップロードをお試しください。", openLink: "開く", privacyNote: "スキャンはすべてブラウザ内で行われ、何もアップロードされません。" },
  ko: { title: "QR 코드 스캐너", short: "카메라 또는 이미지 업로드로 QR 코드를 스캔합니다.", description: "무료 온라인 QR 코드 스캐너. 기기 카메라로 실시간으로 또는 사진을 업로드하여 QR 코드를 읽으세요 — 디코딩은 모두 브라우저에서 이루어지며 아무것도 업로드되지 않습니다.", keywords: ["qr 코드 스캐너", "온라인 qr 리더", "qr 코드 스캔", "qr 코드 읽기", "웹캠 qr 리더"], useCamera: "카메라 사용", stopCamera: "카메라 중지", uploadImage: "이미지 업로드", decoded: "디코딩된 내용", noQr: "해당 이미지에서 QR 코드를 찾을 수 없습니다.", cameraDenied: "카메라를 사용할 수 없거나 권한이 거부되었습니다. 이미지 업로드를 시도하세요.", openLink: "열기", privacyNote: "스캔은 모두 브라우저에서 실행되며 아무것도 업로드되지 않습니다." },
  hi: { title: "QR कोड स्कैनर", short: "कैमरे से या इमेज अपलोड करके QR कोड स्कैन करें।", description: "मुफ्त ऑनलाइन QR कोड स्कैनर। अपने डिवाइस के कैमरे से लाइव या फोटो अपलोड करके QR कोड पढ़ें — डिकोडिंग पूरी तरह आपके ब्राउज़र में होती है, कुछ भी अपलोड नहीं होता।", keywords: ["qr कोड स्कैनर", "ऑनलाइन qr रीडर", "qr कोड स्कैन", "qr कोड पढ़ें", "वेबकैम qr रीडर"], useCamera: "कैमरा उपयोग करें", stopCamera: "कैमरा बंद करें", uploadImage: "इमेज अपलोड करें", decoded: "डिकोड की गई सामग्री", noQr: "उस इमेज में कोई QR कोड नहीं मिला।", cameraDenied: "कैमरा अनुपलब्ध या अनुमति अस्वीकृत। इसके बजाय इमेज अपलोड करें।", openLink: "खोलें", privacyNote: "स्कैनिंग पूरी तरह आपके ब्राउज़र में चलती है; कुछ भी अपलोड नहीं होता।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
