import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text to Binary Converter", short: "Convert text to binary and binary back to text (UTF-8).", description: "Free text-to-binary converter. Turn any text into its 8-bit binary representation, or decode space-separated binary back to text. Full UTF-8 support; runs in your browser.", keywords: ["text to binary", "binary to text", "binary translator", "ascii to binary", "binary converter"], toBinary: "Text → Binary", toText: "Binary → Text", placeholder: "Enter text or binary…", invalid: "Invalid binary input." },
  tr: { title: "Metin–İkili (Binary) Dönüştürücü", short: "Metni ikiliye ve ikiliyi metne çevirin (UTF-8).", description: "Ücretsiz metin–ikili dönüştürücü. Herhangi bir metni 8-bit ikili gösterimine çevirin veya boşlukla ayrılmış ikiliyi metne geri çözün. Tam UTF-8 desteği; tarayıcınızda çalışır.", keywords: ["metinden ikiliye", "ikiliden metne", "binary çevirici", "ascii ikili", "ikili dönüştürücü"], toBinary: "Metin → İkili", toText: "İkili → Metin", placeholder: "Metin veya ikili girin…", invalid: "Geçersiz ikili girdi." },
  de: { title: "Text-zu-Binär-Konverter", short: "Text in Binär und Binär zurück in Text umwandeln (UTF-8).", description: "Kostenloser Text-zu-Binär-Konverter. Wandeln Sie Text in seine 8-Bit-Binärdarstellung um oder dekodieren Sie durch Leerzeichen getrennte Binärwerte zurück in Text. Volle UTF-8-Unterstützung.", keywords: ["text zu binär", "binär zu text", "binär übersetzer", "ascii binär", "binär konverter"], toBinary: "Text → Binär", toText: "Binär → Text", placeholder: "Text oder Binär eingeben…", invalid: "Ungültige Binäreingabe." },
  fr: { title: "Convertisseur Texte–Binaire", short: "Convertissez du texte en binaire et inversement (UTF-8).", description: "Convertisseur texte-binaire gratuit. Transformez n'importe quel texte en sa représentation binaire 8 bits, ou décodez du binaire séparé par des espaces en texte. Prise en charge complète UTF-8.", keywords: ["texte vers binaire", "binaire vers texte", "traducteur binaire", "ascii binaire", "convertisseur binaire"], toBinary: "Texte → Binaire", toText: "Binaire → Texte", placeholder: "Saisissez du texte ou du binaire…", invalid: "Entrée binaire invalide." },
  es: { title: "Conversor de Texto a Binario", short: "Convierte texto a binario y binario a texto (UTF-8).", description: "Conversor de texto a binario gratuito. Convierte cualquier texto en su representación binaria de 8 bits, o decodifica binario separado por espacios a texto. Compatibilidad total con UTF-8.", keywords: ["texto a binario", "binario a texto", "traductor binario", "ascii a binario", "conversor binario"], toBinary: "Texto → Binario", toText: "Binario → Texto", placeholder: "Introduce texto o binario…", invalid: "Entrada binaria no válida." },
  it: { title: "Convertitore Testo–Binario", short: "Converti testo in binario e binario in testo (UTF-8).", description: "Convertitore testo-binario gratuito. Trasforma qualsiasi testo nella sua rappresentazione binaria a 8 bit, o decodifica binario separato da spazi in testo. Pieno supporto UTF-8.", keywords: ["testo in binario", "binario in testo", "traduttore binario", "ascii binario", "convertitore binario"], toBinary: "Testo → Binario", toText: "Binario → Testo", placeholder: "Inserisci testo o binario…", invalid: "Input binario non valido." },
  ar: { title: "محوّل النص إلى ثنائي", short: "حوّل النص إلى ثنائي والثنائي إلى نص (UTF-8).", description: "محوّل نص إلى ثنائي مجاني. حوّل أي نص إلى تمثيله الثنائي بـ 8 بت، أو فك ترميز الثنائي المفصول بمسافات إلى نص. دعم كامل لـ UTF-8؛ يعمل في متصفحك.", keywords: ["نص إلى ثنائي", "ثنائي إلى نص", "مترجم ثنائي", "ascii إلى ثنائي", "محول ثنائي"], toBinary: "نص → ثنائي", toText: "ثنائي → نص", placeholder: "أدخل نصًا أو ثنائيًا…", invalid: "إدخال ثنائي غير صالح." },
  ru: { title: "Конвертер Текста в Двоичный Код", short: "Преобразуйте текст в двоичный код и обратно (UTF-8).", description: "Бесплатный конвертер текста в двоичный код. Преобразуйте любой текст в 8-битное двоичное представление или декодируйте двоичный код, разделённый пробелами, обратно в текст. Полная поддержка UTF-8.", keywords: ["текст в двоичный", "двоичный в текст", "двоичный переводчик", "ascii в двоичный", "двоичный конвертер"], toBinary: "Текст → Двоичный", toText: "Двоичный → Текст", placeholder: "Введите текст или двоичный код…", invalid: "Недопустимый двоичный ввод." },
  zh: { title: "文本转二进制转换器", short: "在文本与二进制之间相互转换（UTF-8）。", description: "免费的文本转二进制转换器。将任意文本转换为其 8 位二进制表示，或将以空格分隔的二进制解码为文本。完整 UTF-8 支持；在浏览器中运行。", keywords: ["文本转二进制", "二进制转文本", "二进制翻译", "ascii转二进制", "二进制转换器"], toBinary: "文本 → 二进制", toText: "二进制 → 文本", placeholder: "输入文本或二进制…", invalid: "无效的二进制输入。" },
  ja: { title: "テキスト⇔バイナリ変換", short: "テキストをバイナリに、バイナリをテキストに変換します（UTF-8）。", description: "無料のテキスト⇔バイナリ変換ツール。任意のテキストを 8 ビットのバイナリ表現に変換、またはスペース区切りのバイナリをテキストにデコードします。UTF-8 完全対応。", keywords: ["テキスト バイナリ", "バイナリ テキスト", "バイナリ変換", "ascii バイナリ", "2進数 変換"], toBinary: "テキスト → バイナリ", toText: "バイナリ → テキスト", placeholder: "テキストまたはバイナリを入力…", invalid: "無効なバイナリ入力です。" },
  ko: { title: "텍스트 ⇔ 이진 변환기", short: "텍스트를 이진으로, 이진을 텍스트로 변환합니다(UTF-8).", description: "무료 텍스트-이진 변환기. 임의의 텍스트를 8비트 이진 표현으로 변환하거나 공백으로 구분된 이진을 텍스트로 디코딩합니다. 완전한 UTF-8 지원; 브라우저에서 실행됩니다.", keywords: ["텍스트 이진", "이진 텍스트", "이진 변환기", "ascii 이진", "바이너리 변환"], toBinary: "텍스트 → 이진", toText: "이진 → 텍스트", placeholder: "텍스트 또는 이진 입력…", invalid: "잘못된 이진 입력입니다." },
  hi: { title: "टेक्स्ट से बाइनरी कन्वर्टर", short: "टेक्स्ट को बाइनरी में और बाइनरी को टेक्स्ट में बदलें (UTF-8)।", description: "मुफ्त टेक्स्ट-से-बाइनरी कन्वर्टर। किसी भी टेक्स्ट को उसके 8-बिट बाइनरी रूप में बदलें, या स्पेस से अलग बाइनरी को टेक्स्ट में डिकोड करें। पूर्ण UTF-8 समर्थन; ब्राउज़र में चलता है।", keywords: ["टेक्स्ट से बाइनरी", "बाइनरी से टेक्स्ट", "बाइनरी अनुवादक", "ascii से बाइनरी", "बाइनरी कन्वर्टर"], toBinary: "टेक्स्ट → बाइनरी", toText: "बाइनरी → टेक्स्ट", placeholder: "टेक्स्ट या बाइनरी दर्ज करें…", invalid: "अमान्य बाइनरी इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
