import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IPv4 Format Converter", short: "Convert IPv4 between dotted, decimal, hex and binary.", description: "Free IPv4 format converter. Enter a dotted-decimal address (1.2.3.4), a decimal integer, a hex value (0x...) or dotted binary to see all four representations side by side.", keywords: ["ipv4 converter", "ip to binary", "ip to hex", "ip to decimal", "ipv4 format converter"], input: "IPv4 (dotted, decimal, hex or binary)", dotted: "Dotted decimal", decimal: "Decimal", hex: "Hex", binary: "Binary" },
  nl: { title: "IPv4 Formatteer Converteerer", short: "Converteer IPv4 between dotted, decimal, hex and binair.", description: "Gratis IPv4 formatteer converteerer. Enter a dotted-decimal address (1.2.3.4), a decimal integer, a hex value (0x...) or dotted binair to see all four representations side by side.", keywords: ["ipv4 converteerer", "ip to binair", "ip to hex", "ip to decimal", "ipv4 formatteer converteerer"], input: "IPv4 (dotted, decimal, hex or binair)", dotted: "Dotted decimal", decimal: "Decimal", hex: "Hex", binary: "Binair" },

  pl: { title: "IPv4 Formatuj Konwerter", short: "Konwertuj IPv4 between dotted, decimal, hex and binarny.", description: "Darmowy IPv4 formatuj konwerter. Enter a dotted-decimal address (1.2.3.4), a decimal integer, a hex value (0x...) or dotted binarny to see all four representations side by side.", keywords: ["ipv4 konwerter", "ip to binarny", "ip to hex", "ip to decimal", "ipv4 formatuj konwerter"], input: "IPv4 (dotted, decimal, hex or binarny)", dotted: "Dotted decimal", decimal: "Decimal", hex: "Hex", binary: "Binarny" },
  pt: { title: "Conversor de IPv4 Format", short: "Converter IPv4 entre dotted, decimal, hex e binary.", description: "Gratuito - IPv4 formatar converter. Enter a dotted-decimal address (1.2.3.4), a decimal integer, a hex value (0x...) ou dotted binary para see all four representations side by side.", keywords: ["ipv4 converter", "ip to binary", "ip to hex", "ip to decimal", "ipv4 format converter"], input: "IPv4 (dotted, decimal, hex or binary)", dotted: "Dotted decimal", decimal: "Decimal", hex: "Hex", binary: "Binary" },
  id: { title: "Konverter IPv4 Format", short: "Konversi IPv4 antara dotted, decimal, hex dan binary.", description: "Gratis - IPv4 format converter. Enter a dotted-decimal address (1.2.3.4), a decimal integer, a hex value (0x...) atau dotted binary to see all four representations side by side.", keywords: ["ipv4 converter", "ip to binary", "ip to hex", "ip to decimal", "ipv4 format converter"], input: "IPv4 (dotted, decimal, hex or binary)", dotted: "Dotted decimal", decimal: "Decimal", hex: "Hex", binary: "Binary" },

  tr: { title: "IPv4 Format Dönüştürücü", short: "IPv4'ü noktalı, ondalık, hex ve ikili arasında dönüştürün.", description: "Ücretsiz IPv4 format dönüştürücü. Noktalı ondalık adres (1.2.3.4), ondalık tamsayı, hex değer (0x...) veya noktalı ikili girin ve dört temsili yan yana görün.", keywords: ["ipv4 dönüştürücü", "ip ikili", "ip hex", "ip ondalık", "ipv4 format dönüştürücü"], input: "IPv4 (noktalı, ondalık, hex veya ikili)", dotted: "Noktalı ondalık", decimal: "Ondalık", hex: "Hex", binary: "İkili" },
  de: { title: "IPv4-Format-Konverter", short: "IPv4 zwischen Dotted, Dezimal, Hex und Binär umwandeln.", description: "Kostenloser IPv4-Format-Konverter. Geben Sie eine Dotted-Decimal-Adresse (1.2.3.4), einen Dezimal-Integer, einen Hex-Wert (0x…) oder Dotted Binary ein, um alle vier Darstellungen nebeneinander zu sehen.", keywords: ["ipv4 konverter", "ip zu binär", "ip zu hex", "ip zu dezimal", "ipv4 format konverter"], input: "IPv4 (dotted, dezimal, hex oder binär)", dotted: "Dotted Decimal", decimal: "Dezimal", hex: "Hex", binary: "Binär" },
  fr: { title: "Convertisseur de Format IPv4", short: "Convertissez IPv4 entre pointé, décimal, hex et binaire.", description: "Convertisseur de format IPv4 gratuit. Saisissez une adresse pointée-décimale (1.2.3.4), un entier décimal, une valeur hex (0x...) ou du binaire pointé pour voir les quatre représentations côte à côte.", keywords: ["convertisseur ipv4", "ip vers binaire", "ip vers hex", "ip vers décimal", "convertisseur format ipv4"], input: "IPv4 (pointé, décimal, hex ou binaire)", dotted: "Pointé décimal", decimal: "Décimal", hex: "Hex", binary: "Binaire" },
  es: { title: "Convertidor de Formato IPv4", short: "Convierte IPv4 entre punteado, decimal, hex y binario.", description: "Convertidor de formato IPv4 gratuito. Introduce una dirección punteado-decimal (1.2.3.4), un entero decimal, un valor hex (0x...) o binario punteado para ver las cuatro representaciones lado a lado.", keywords: ["convertidor ipv4", "ip a binario", "ip a hex", "ip a decimal", "convertidor formato ipv4"], input: "IPv4 (punteado, decimal, hex o binario)", dotted: "Punteado decimal", decimal: "Decimal", hex: "Hex", binary: "Binario" },
  it: { title: "Convertitore Formato IPv4", short: "Converti IPv4 tra puntato, decimale, hex e binario.", description: "Convertitore formato IPv4 gratuito. Inserisci un indirizzo puntato-decimale (1.2.3.4), un intero decimale, un valore hex (0x...) o binario puntato per vedere le quattro rappresentazioni affiancate.", keywords: ["convertitore ipv4", "ip in binario", "ip in hex", "ip in decimale", "convertitore formato ipv4"], input: "IPv4 (puntato, decimale, hex o binario)", dotted: "Puntato decimale", decimal: "Decimale", hex: "Hex", binary: "Binario" },
  ar: { title: "محوّل تنسيق IPv4", short: "حوّل IPv4 بين النقطي والعشري والست عشري والثنائي.", description: "محوّل تنسيق IPv4 مجاني. أدخل عنوانًا نقطيًا-عشريًا (1.2.3.4) أو عددًا عشريًا أو قيمة سداسية (0x...) أو ثنائيًا نقطيًا لرؤية التمثيلات الأربعة جنبًا إلى جنب.", keywords: ["محول ipv4", "ip إلى ثنائي", "ip إلى hex", "ip إلى عشري", "محول تنسيق ipv4"], input: "IPv4 (نقطي، عشري، hex أو ثنائي)", dotted: "نقطي عشري", decimal: "عشري", hex: "Hex", binary: "ثنائي" },
  ru: { title: "Конвертер форматов IPv4", short: "Конвертируйте IPv4 между точечным, десятичным, hex и двоичным.", description: "Бесплатный конвертер форматов IPv4. Введите точечно-десятичный адрес (1.2.3.4), десятичное число, hex-значение (0x...) или точечный двоичный, чтобы увидеть все четыре представления рядом.", keywords: ["конвертер ipv4", "ip в двоичный", "ip в hex", "ip в десятичный", "конвертер формата ipv4"], input: "IPv4 (точечный, десятичный, hex или двоичный)", dotted: "Точечно-десятичный", decimal: "Десятичный", hex: "Hex", binary: "Двоичный" },
  zh: { title: "IPv4 格式转换器", short: "在点分十进制、十进制、十六进制和二进制之间转换 IPv4。", description: "免费的 IPv4 格式转换器。输入点分十进制地址（1.2.3.4）、十进制整数、十六进制值（0x...）或点分二进制，并排查看四种表示。", keywords: ["ipv4 转换器", "ip 转二进制", "ip 转十六进制", "ip 转十进制", "ipv4 格式转换器"], input: "IPv4（点分、十进制、十六进制或二进制）", dotted: "点分十进制", decimal: "十进制", hex: "十六进制", binary: "二进制" },
  ja: { title: "IPv4 形式変換", short: "IPv4 をドット表記・10進・16進・2進で変換。", description: "無料の IPv4 形式変換ツール。ドット10進アドレス（1.2.3.4）、10進整数、16進値（0x...）またはドット2進を入力すると、4つの表現を並べて表示します。", keywords: ["ipv4 変換", "ip を2進数に", "ip を16進数に", "ip を10進数に", "ipv4 形式変換"], input: "IPv4（ドット表記、10進、16進または2進）", dotted: "ドット10進", decimal: "10進", hex: "16進", binary: "2進" },
  ko: { title: "IPv4 형식 변환기", short: "IPv4를 점 표기, 10진수, 16진수, 2진수 사이에 변환합니다.", description: "무료 IPv4 형식 변환기. 점 표기 10진수 주소(1.2.3.4), 10진수 정수, 16진수 값(0x...) 또는 점 표기 2진수를 입력하면 네 가지 표현을 나란히 볼 수 있습니다.", keywords: ["ipv4 변환기", "ip 2진수", "ip 16진수", "ip 10진수", "ipv4 형식 변환기"], input: "IPv4 (점 표기, 10진수, 16진수 또는 2진수)", dotted: "점 표기 10진수", decimal: "10진수", hex: "16진수", binary: "2진수" },
  hi: { title: "IPv4 प्रारूप कन्वर्टर", short: "IPv4 को डॉटेड, दशमलव, हेक्स और बाइनरी के बीच बदलें।", description: "मुफ्त IPv4 प्रारूप कन्वर्टर। एक डॉटेड-डेसिमल पता (1.2.3.4), एक दशमलव पूर्णांक, एक हेक्स मान (0x...) या डॉटेड बाइनरी दर्ज करें और चारों प्रतिनिधित्व एक साथ देखें।", keywords: ["ipv4 कन्वर्टर", "ip से बाइनरी", "ip से हेक्स", "ip से दशमलव", "ipv4 प्रारूप कन्वर्टर"], input: "IPv4 (डॉटेड, दशमलव, हेक्स या बाइनरी)", dotted: "डॉटेड दशमलव", decimal: "दशमलव", hex: "हेक्स", binary: "बाइनरी" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
