import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Unicode Character Inspector", short: "Inspect each character's Unicode code point, decimal value and UTF-8 bytes.", description: "Free Unicode inspector. Paste text to break it into characters and see each one's U+ code point, decimal value and UTF-8 byte sequence. Handles emoji and astral characters. Runs in your browser.", keywords: ["unicode inspector", "code point lookup", "character codes", "utf-8 bytes", "unicode character info"], placeholder: "Enter text to inspect…", character: "Character", codePoint: "Code point", decimal: "Decimal", utf8: "UTF-8" },
  nl: { title: "Unicode Character Inspecteur", short: "Inspect each character's Unicode code point, decimal value and UTF-8 bytes.", description: "Gratis Unicode inspector. Paste tekst to break it into tekens and see each one's U+ code point, decimal value and UTF-8 byte sequence. Handles emoji and astral tekens. Runs in uw browser.", keywords: ["unicode inspector", "code point lookup", "character codes", "utf-8 bytes", "unicode character info"], placeholder: "Enter tekst to inspect…", character: "Character", codePoint: "Code point", decimal: "Decimal", utf8: "UTF-8" },

  pl: { title: "Unikod Character Inspektor", short: "Inspect each character's Unikod kod point, decimal value and UTF-8 bytes.", description: "Darmowy Unikod inspector. Paste tekst to break it into znaków and see each one's U+ kod point, decimal value and UTF-8 byte sequence. Handles emoji and astral znaków. Runs w Twojej przeglądarce.", keywords: ["unikod inspector", "kod point lookup", "character kods", "utf-8 bytes", "unikod character info"], placeholder: "Enter tekst to inspect…", character: "Character", codePoint: "Kod point", decimal: "Decimal", utf8: "UTF-8" },
  pt: { title: "Inspetor de Unicode Character", short: "Inspect each character's Unicode code point, decimal value e UTF-8 bytes.", description: "Gratuito - Unicode inspector. Paste text para break it into characters e see each one's U+ code point, decimal value e UTF-8 byte sequence. Handles emoji e astral characters. Runs no seu navegador.", keywords: ["unicode inspector", "code point lookup", "character codes", "utf-8 bytes", "unicode character info"], placeholder: "Enter text to inspect…", character: "Character", codePoint: "Code point", decimal: "Decimal", utf8: "UTF-8" },
  id: { title: "Pemeriksa Unicode Character", short: "Inspect each character's Unicode code point, decimal value dan UTF-8 bytes.", description: "Gratis - Unicode inspector. Paste text to break it into characters dan see each one's U+ code point, decimal value dan UTF-8 byte sequence. Handles emoji dan astral characters. Runs di browser Anda.", keywords: ["unicode inspector", "code point lookup", "character codes", "utf-8 bytes", "unicode character info"], placeholder: "Enter text to inspect…", character: "Character", codePoint: "Code point", decimal: "Decimal", utf8: "UTF-8" },

  tr: { title: "Unicode Karakter İnceleyici", short: "Her karakterin Unicode kod noktasını, ondalık değerini ve UTF-8 baytlarını inceleyin.", description: "Ücretsiz Unicode inceleyici. Metni yapıştırın; karakterlere ayrılsın ve her birinin U+ kod noktasını, ondalık değerini ve UTF-8 bayt dizisini görün. Emoji ve astral karakterleri işler. Tarayıcınızda çalışır.", keywords: ["unicode inceleyici", "kod noktası arama", "karakter kodları", "utf-8 baytları", "unicode karakter bilgisi"], placeholder: "İncelenecek metni girin…", character: "Karakter", codePoint: "Kod noktası", decimal: "Ondalık", utf8: "UTF-8" },
  de: { title: "Unicode-Zeichen-Inspektor", short: "Untersuchen Sie Code-Point, Dezimalwert und UTF-8-Bytes jedes Zeichens.", description: "Kostenloser Unicode-Inspektor. Fügen Sie Text ein, um ihn in Zeichen zu zerlegen und für jedes den U+-Code-Point, Dezimalwert und die UTF-8-Bytefolge zu sehen. Unterstützt Emoji. Läuft im Browser.", keywords: ["unicode inspektor", "code point suche", "zeichencodes", "utf-8 bytes", "unicode zeicheninfo"], placeholder: "Zu untersuchenden Text eingeben…", character: "Zeichen", codePoint: "Code-Point", decimal: "Dezimal", utf8: "UTF-8" },
  fr: { title: "Inspecteur de Caractères Unicode", short: "Examinez le point de code Unicode, la valeur décimale et les octets UTF-8 de chaque caractère.", description: "Inspecteur Unicode gratuit. Collez du texte pour le décomposer en caractères et voir, pour chacun, son point de code U+, sa valeur décimale et sa séquence d'octets UTF-8. Gère les emoji. S'exécute dans votre navigateur.", keywords: ["inspecteur unicode", "recherche point de code", "codes de caractères", "octets utf-8", "info caractère unicode"], placeholder: "Saisissez le texte à inspecter…", character: "Caractère", codePoint: "Point de code", decimal: "Décimal", utf8: "UTF-8" },
  es: { title: "Inspector de Caracteres Unicode", short: "Inspecciona el punto de código Unicode, el valor decimal y los bytes UTF-8 de cada carácter.", description: "Inspector Unicode gratuito. Pega texto para descomponerlo en caracteres y ver, de cada uno, su punto de código U+, valor decimal y secuencia de bytes UTF-8. Maneja emoji. Se ejecuta en tu navegador.", keywords: ["inspector unicode", "búsqueda punto de código", "códigos de caracteres", "bytes utf-8", "info carácter unicode"], placeholder: "Introduce el texto a inspeccionar…", character: "Carácter", codePoint: "Punto de código", decimal: "Decimal", utf8: "UTF-8" },
  it: { title: "Ispettore di Caratteri Unicode", short: "Esamina il code point Unicode, il valore decimale e i byte UTF-8 di ogni carattere.", description: "Ispettore Unicode gratuito. Incolla il testo per scomporlo in caratteri e vedere, per ciascuno, il code point U+, il valore decimale e la sequenza di byte UTF-8. Gestisce le emoji. Funziona nel browser.", keywords: ["ispettore unicode", "ricerca code point", "codici dei caratteri", "byte utf-8", "info carattere unicode"], placeholder: "Inserisci il testo da ispezionare…", character: "Carattere", codePoint: "Code point", decimal: "Decimale", utf8: "UTF-8" },
  ar: { title: "فاحص أحرف Unicode", short: "افحص نقطة شفرة Unicode والقيمة العشرية وبايتات UTF-8 لكل حرف.", description: "فاحص Unicode مجاني. الصق النص لتقسيمه إلى أحرف ورؤية نقطة شفرة U+ والقيمة العشرية وتسلسل بايتات UTF-8 لكل حرف. يدعم الرموز التعبيرية. يعمل في متصفحك.", keywords: ["فاحص unicode", "بحث نقطة الشفرة", "رموز الأحرف", "بايتات utf-8", "معلومات حرف unicode"], placeholder: "أدخل النص للفحص…", character: "الحرف", codePoint: "نقطة الشفرة", decimal: "عشري", utf8: "UTF-8" },
  ru: { title: "Инспектор Символов Unicode", short: "Изучите код-поинт Unicode, десятичное значение и UTF-8 байты каждого символа.", description: "Бесплатный инспектор Unicode. Вставьте текст, чтобы разбить его на символы и увидеть для каждого код-поинт U+, десятичное значение и последовательность UTF-8 байтов. Поддерживает эмодзи. Работает в браузере.", keywords: ["инспектор unicode", "поиск код-поинта", "коды символов", "utf-8 байты", "информация о символе unicode"], placeholder: "Введите текст для анализа…", character: "Символ", codePoint: "Код-поинт", decimal: "Десятичное", utf8: "UTF-8" },
  zh: { title: "Unicode 字符检查器", short: "检查每个字符的 Unicode 码点、十进制值和 UTF-8 字节。", description: "免费的 Unicode 检查器。粘贴文本将其拆分为字符，查看每个字符的 U+ 码点、十进制值和 UTF-8 字节序列。支持表情符号和增补字符。在浏览器中运行。", keywords: ["unicode检查器", "码点查询", "字符编码", "utf-8字节", "unicode字符信息"], placeholder: "输入要检查的文本…", character: "字符", codePoint: "码点", decimal: "十进制", utf8: "UTF-8" },
  ja: { title: "Unicode 文字インスペクター", short: "各文字の Unicode コードポイント、10進値、UTF-8 バイトを調べます。", description: "無料の Unicode インスペクター。テキストを貼り付けて文字に分解し、それぞれの U+ コードポイント、10進値、UTF-8 バイト列を表示します。絵文字やサロゲートペアにも対応。ブラウザ内で動作します。", keywords: ["unicode インスペクター", "コードポイント 検索", "文字コード", "utf-8 バイト", "unicode 文字情報"], placeholder: "調べるテキストを入力…", character: "文字", codePoint: "コードポイント", decimal: "10進", utf8: "UTF-8" },
  ko: { title: "유니코드 문자 검사기", short: "각 문자의 유니코드 코드 포인트, 10진값, UTF-8 바이트를 검사합니다.", description: "무료 유니코드 검사기. 텍스트를 붙여넣어 문자로 분해하고 각 문자의 U+ 코드 포인트, 10진값, UTF-8 바이트 시퀀스를 확인하세요. 이모지와 보충 문자를 지원합니다. 브라우저에서 실행됩니다.", keywords: ["유니코드 검사기", "코드 포인트 조회", "문자 코드", "utf-8 바이트", "유니코드 문자 정보"], placeholder: "검사할 텍스트 입력…", character: "문자", codePoint: "코드 포인트", decimal: "10진", utf8: "UTF-8" },
  hi: { title: "यूनिकोड कैरेक्टर इंस्पेक्टर", short: "हर वर्ण का यूनिकोड कोड पॉइंट, दशमलव मान और UTF-8 बाइट्स देखें।", description: "मुफ्त यूनिकोड इंस्पेक्टर। टेक्स्ट पेस्ट करें ताकि वह वर्णों में टूटे और हर एक का U+ कोड पॉइंट, दशमलव मान और UTF-8 बाइट क्रम दिखे। इमोजी और एस्ट्रल वर्णों को संभालता है। ब्राउज़र में चलता है।", keywords: ["यूनिकोड इंस्पेक्टर", "कोड पॉइंट खोज", "वर्ण कोड", "utf-8 बाइट्स", "यूनिकोड वर्ण जानकारी"], placeholder: "जाँचने के लिए टेक्स्ट दर्ज करें…", character: "वर्ण", codePoint: "कोड पॉइंट", decimal: "दशमलव", utf8: "UTF-8" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
