import type { CalculatorI18n } from "@/types/i18n";

const i18n: CalculatorI18n = {
  en: {
    title: "Compound Interest Calculator",
    short: "Calculate how your savings grow over time with compound interest and regular contributions.",
    description:
      "Free compound interest calculator. Enter your principal, annual return, compounding frequency, and monthly contributions to see your future value and year-by-year growth.",
    keywords: [
      "compound interest calculator",
      "investment growth calculator",
      "savings calculator",
      "future value calculator",
      "compound growth",
      "interest calculator",
      "investment calculator",
    ],
    inputs: {
      principal: { label: "Initial Investment", help: "The amount you invest today." },
      annualRate: { label: "Annual Interest Rate (%)", help: "Expected annual return or interest rate." },
      years: { label: "Time Period (years)", help: "How long the money is invested or saved." },
      compoundFrequency: { label: "Compounding Frequency", help: "How often interest is calculated and added to the balance." },
      monthlyContribution: { label: "Monthly Contribution", help: "Additional amount added each month. Enter 0 if none." },
    },
    outputs: {
      futureValue: { label: "Future Value", help: "Total account value at the end of the period." },
      totalContributions: { label: "Total Contributions", help: "Sum of initial investment plus all monthly contributions." },
      totalInterest: { label: "Total Interest Earned", help: "The growth generated by compound interest." },
      yearlyBreakdown: { label: "Year-by-Year Breakdown", help: "Annual balance, total contributed, and interest earned each year." },
    },
    options: {
      compoundFrequency: {
        annually: "Annually (1×/year)",
        quarterly: "Quarterly (4×/year)",
        monthly: "Monthly (12×/year)",
        daily: "Daily (365×/year)",
      },
    },
    errors: {
      principalRange: "Initial investment must be between $0 and $10,000,000.",
      rateRange: "Annual rate must be between 0% and 50%.",
      yearsRange: "Time period must be between 1 and 50 years.",
      contributionRange: "Monthly contribution must be between $0 and $100,000.",
    },
    faq: [
      {
        q: "What is compound interest?",
        a: "Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods. Unlike simple interest, which is only calculated on the principal, compound interest causes exponential growth over time.",
      },
      {
        q: "How does compounding frequency affect growth?",
        a: "More frequent compounding leads to slightly higher returns. Daily compounding generates marginally more than monthly compounding at the same annual rate, because interest is added to the balance more often. The difference becomes more significant at higher interest rates and longer time periods.",
      },
      {
        q: "What is the Rule of 72?",
        a: "The Rule of 72 is a quick mental shortcut: divide 72 by the annual interest rate to estimate how many years it takes for an investment to double. At 8% annual return, money doubles in approximately 72 ÷ 8 = 9 years.",
      },
      {
        q: "How important are regular contributions vs. initial investment?",
        a: "Over long periods, regular contributions often matter more than the initial investment. $500/month invested for 30 years at 7% grows to over $567,000 from contributions alone — with initial investment of $0.",
      },
    ],
  },
  pt: {
    title: "Compound Interest Calculator",
    short: "Calculate how your savings grow over time with compound interest and regular contributions.",
    description:
      "Free compound interest calculator. Enter your principal, annual return, compounding frequency, and monthly contributions to see your future value and year-by-year growth.",
    keywords: [
      "compound interest calculator",
      "investment growth calculator",
      "savings calculator",
      "future value calculator",
      "compound growth",
      "interest calculator",
      "investment calculator",
    ],
    inputs: {
      principal: { label: "Initial Investment", help: "The amount you invest today." },
      annualRate: { label: "Annual Interest Rate (%)", help: "Expected annual return or interest rate." },
      years: { label: "Time Period (years)", help: "How long the money is invested or saved." },
      compoundFrequency: { label: "Compounding Frequency", help: "How often interest is calculated and added to the balance." },
      monthlyContribution: { label: "Monthly Contribution", help: "Additional amount added each month. Enter 0 if none." },
    },
    outputs: {
      futureValue: { label: "Future Value", help: "Total account value at the end of the period." },
      totalContributions: { label: "Total Contributions", help: "Sum of initial investment plus all monthly contributions." },
      totalInterest: { label: "Total Interest Earned", help: "The growth generated by compound interest." },
      yearlyBreakdown: { label: "Year-by-Year Breakdown", help: "Annual balance, total contributed, and interest earned each year." },
    },
    options: {
      compoundFrequency: {
        annually: "Annually (1×/year)",
        quarterly: "Quarterly (4×/year)",
        monthly: "Monthly (12×/year)",
        daily: "Daily (365×/year)",
      },
    },
    errors: {
      principalRange: "Initial investment must be between $0 and $10,000,000.",
      rateRange: "Annual rate must be between 0% and 50%.",
      yearsRange: "Time period must be between 1 and 50 years.",
      contributionRange: "Monthly contribution must be between $0 and $100,000.",
    },
    faq: [
      {
        q: "What is compound interest?",
        a: "Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods. Unlike simple interest, which is only calculated on the principal, compound interest causes exponential growth over time.",
      },
      {
        q: "How does compounding frequency affect growth?",
        a: "More frequent compounding leads to slightly higher returns. Daily compounding generates marginally more than monthly compounding at the same annual rate, because interest is added to the balance more often. The difference becomes more significant at higher interest rates and longer time periods.",
      },
      {
        q: "What is the Rule of 72?",
        a: "The Rule of 72 is a quick mental shortcut: divide 72 by the annual interest rate to estimate how many years it takes for an investment to double. At 8% annual return, money doubles in approximately 72 ÷ 8 = 9 years.",
      },
      {
        q: "How important are regular contributions vs. initial investment?",
        a: "Over long periods, regular contributions often matter more than the initial investment. $500/month invested for 30 years at 7% grows to over $567,000 from contributions alone — with initial investment of $0.",
      },
    ],
  },
  id: {
    title: "Compound Interest Calculator",
    short: "Calculate how your savings grow over time with compound interest and regular contributions.",
    description:
      "Free compound interest calculator. Enter your principal, annual return, compounding frequency, and monthly contributions to see your future value and year-by-year growth.",
    keywords: [
      "compound interest calculator",
      "investment growth calculator",
      "savings calculator",
      "future value calculator",
      "compound growth",
      "interest calculator",
      "investment calculator",
    ],
    inputs: {
      principal: { label: "Initial Investment", help: "The amount you invest today." },
      annualRate: { label: "Annual Interest Rate (%)", help: "Expected annual return or interest rate." },
      years: { label: "Time Period (years)", help: "How long the money is invested or saved." },
      compoundFrequency: { label: "Compounding Frequency", help: "How often interest is calculated and added to the balance." },
      monthlyContribution: { label: "Monthly Contribution", help: "Additional amount added each month. Enter 0 if none." },
    },
    outputs: {
      futureValue: { label: "Future Value", help: "Total account value at the end of the period." },
      totalContributions: { label: "Total Contributions", help: "Sum of initial investment plus all monthly contributions." },
      totalInterest: { label: "Total Interest Earned", help: "The growth generated by compound interest." },
      yearlyBreakdown: { label: "Year-by-Year Breakdown", help: "Annual balance, total contributed, and interest earned each year." },
    },
    options: {
      compoundFrequency: {
        annually: "Annually (1×/year)",
        quarterly: "Quarterly (4×/year)",
        monthly: "Monthly (12×/year)",
        daily: "Daily (365×/year)",
      },
    },
    errors: {
      principalRange: "Initial investment must be between $0 and $10,000,000.",
      rateRange: "Annual rate must be between 0% and 50%.",
      yearsRange: "Time period must be between 1 and 50 years.",
      contributionRange: "Monthly contribution must be between $0 and $100,000.",
    },
    faq: [
      {
        q: "What is compound interest?",
        a: "Compound interest is interest calculated on both the initial principal and the accumulated interest from previous periods. Unlike simple interest, which is only calculated on the principal, compound interest causes exponential growth over time.",
      },
      {
        q: "How does compounding frequency affect growth?",
        a: "More frequent compounding leads to slightly higher returns. Daily compounding generates marginally more than monthly compounding at the same annual rate, because interest is added to the balance more often. The difference becomes more significant at higher interest rates and longer time periods.",
      },
      {
        q: "What is the Rule of 72?",
        a: "The Rule of 72 is a quick mental shortcut: divide 72 by the annual interest rate to estimate how many years it takes for an investment to double. At 8% annual return, money doubles in approximately 72 ÷ 8 = 9 years.",
      },
      {
        q: "How important are regular contributions vs. initial investment?",
        a: "Over long periods, regular contributions often matter more than the initial investment. $500/month invested for 30 years at 7% grows to over $567,000 from contributions alone — with initial investment of $0.",
      },
    ],
  },


  tr: {
    title: "Bileşik Faiz Hesaplayıcı",
    short: "Tasarruflarınızın bileşik faiz ve düzenli katkılarla zaman içinde nasıl büyüdüğünü hesaplayın.",
    description:
      "Ücretsiz bileşik faiz hesaplayıcı. Anapara, yıllık getiri, bileşikleşme sıklığı ve aylık katkıları girerek gelecekteki değerinizi ve yıllık büyümeyi görün.",
    keywords: [
      "bileşik faiz hesaplayıcı",
      "yatırım büyümesi",
      "tasarruf hesaplayıcı",
      "gelecek değer",
      "bileşik büyüme",
      "faiz hesaplama",
      "yatırım getirisi",
    ],
    inputs: {
      principal: { label: "Başlangıç Yatırımı", help: "Bugün yatırdığınız tutar." },
      annualRate: { label: "Yıllık Faiz Oranı (%)", help: "Beklenen yıllık getiri veya faiz oranı." },
      years: { label: "Süre (yıl)", help: "Paranın yatırımda veya tasarrufta kaldığı süre." },
      compoundFrequency: { label: "Bileşikleşme Sıklığı", help: "Faizin ne sıklıkla hesaplanıp bakiyeye eklendiği." },
      monthlyContribution: { label: "Aylık Katkı", help: "Her ay eklenen ek tutar. Yoksa 0 girin." },
    },
    outputs: {
      futureValue: { label: "Gelecekteki Değer", help: "Dönem sonunda toplam hesap değeri." },
      totalContributions: { label: "Toplam Katkı", help: "Başlangıç yatırımı artı tüm aylık katkıların toplamı." },
      totalInterest: { label: "Toplam Faiz Kazancı", help: "Bileşik faizin oluşturduğu büyüme." },
      yearlyBreakdown: { label: "Yıllık Dökümü", help: "Her yıl için yıllık bakiye, toplam katkı ve kazanılan faiz." },
    },
    options: {
      compoundFrequency: {
        annually: "Yıllık (1×/yıl)",
        quarterly: "Üç Aylık (4×/yıl)",
        monthly: "Aylık (12×/yıl)",
        daily: "Günlük (365×/yıl)",
      },
    },
    errors: {
      principalRange: "Başlangıç yatırımı 0 ile 10.000.000 arasında olmalıdır.",
      rateRange: "Yıllık oran %0 ile %50 arasında olmalıdır.",
      yearsRange: "Süre 1 ile 50 yıl arasında olmalıdır.",
      contributionRange: "Aylık katkı 0 ile 100.000 arasında olmalıdır.",
    },
    faq: [
      {
        q: "Bileşik faiz nedir?",
        a: "Bileşik faiz, hem başlangıç anaparası hem de önceki dönemlerden birikmiş faiz üzerinden hesaplanan faizdir. Basit faizden farklı olarak, bileşik faiz zaman içinde üstel büyüme sağlar.",
      },
      {
        q: "72 kuralı nedir?",
        a: "72 sayısını yıllık faiz oranına bölerek yatırımın değerini ikiye katlaması için gereken yaklaşık süreyi bulabilirsiniz. %8 yıllık getiri ile para yaklaşık 9 yılda iki katına çıkar.",
      },
    ],
  },

  de: {
    title: "Zinseszinsrechner",
    short: "Berechnen Sie, wie Ihr Erspartes durch Zinseszins und regelmäßige Einzahlungen wächst.",
    description:
      "Kostenloser Zinseszinsrechner. Geben Sie Startkapital, Jahresrendite, Zinsfrequenz und monatliche Einzahlungen ein und sehen Sie den zukünftigen Wert.",
    keywords: [
      "Zinseszinsrechner",
      "Investitionsrechner",
      "Sparrechner",
      "Zukunftswert",
      "Renditerechner",
      "Kapitalwachstum",
      "Zinseszins berechnen",
    ],
    inputs: {
      principal: { label: "Startkapital", help: "Der Betrag, den Sie heute anlegen." },
      annualRate: { label: "Jährlicher Zinssatz (%)", help: "Erwartete jährliche Rendite oder Zinssatz." },
      years: { label: "Laufzeit (Jahre)", help: "Wie lange das Geld angelegt wird." },
      compoundFrequency: { label: "Zinsfrequenz", help: "Wie oft Zinsen berechnet und dem Kapital hinzugefügt werden." },
      monthlyContribution: { label: "Monatliche Sparrate", help: "Zusätzlicher Betrag, der jeden Monat eingezahlt wird." },
    },
    outputs: {
      futureValue: { label: "Endkapital", help: "Gesamtwert des Kontos am Ende des Zeitraums." },
      totalContributions: { label: "Gesamte Einzahlungen", help: "Startkapital plus alle monatlichen Einzahlungen." },
      totalInterest: { label: "Zinserträge", help: "Durch Zinseszins erzielte Wertsteigerung." },
      yearlyBreakdown: { label: "Jahresaufschlüsselung", help: "Jährliches Kapital, eingezahlter Betrag und Zinsen." },
    },
    options: {
      compoundFrequency: {
        annually: "Jährlich (1×/Jahr)",
        quarterly: "Vierteljährlich (4×/Jahr)",
        monthly: "Monatlich (12×/Jahr)",
        daily: "Täglich (365×/Jahr)",
      },
    },
    errors: {
      principalRange: "Startkapital muss zwischen 0 und 10.000.000 liegen.",
      rateRange: "Jahreszins muss zwischen 0 % und 50 % liegen.",
      yearsRange: "Laufzeit muss zwischen 1 und 50 Jahren liegen.",
      contributionRange: "Monatliche Sparrate muss zwischen 0 und 100.000 liegen.",
    },
    faq: [
      {
        q: "Was ist Zinseszins?",
        a: "Zinseszins bezeichnet die Berechnung von Zinsen sowohl auf das Anfangskapital als auch auf die bereits aufgelaufenen Zinsen. Im Gegensatz zum einfachen Zins führt Zinseszins zu exponentiellem Wachstum über die Zeit.",
      },
    ],
  },

  fr: {
    title: "Calculateur d'Intérêts Composés",
    short: "Calculez la croissance de votre épargne avec les intérêts composés et des versements réguliers.",
    description:
      "Calculateur d'intérêts composés gratuit. Entrez le capital initial, le taux, la fréquence de capitalisation et les versements mensuels pour voir votre valeur future.",
    keywords: [
      "calculateur intérêts composés",
      "calcul placement",
      "calculateur épargne",
      "valeur future",
      "croissance composée",
      "intérêts calculateur",
      "rendement investissement",
    ],
    inputs: {
      principal: { label: "Capital initial", help: "Le montant investi aujourd'hui." },
      annualRate: { label: "Taux annuel (%)", help: "Rendement annuel attendu ou taux d'intérêt." },
      years: { label: "Durée (années)", help: "Combien d'années l'argent est investi." },
      compoundFrequency: { label: "Fréquence de capitalisation", help: "À quelle fréquence les intérêts sont calculés et ajoutés au capital." },
      monthlyContribution: { label: "Versement mensuel", help: "Montant supplémentaire versé chaque mois. Saisissez 0 si aucun." },
    },
    outputs: {
      futureValue: { label: "Valeur future", help: "Valeur totale du compte à la fin de la période." },
      totalContributions: { label: "Total des versements", help: "Capital initial plus tous les versements mensuels." },
      totalInterest: { label: "Intérêts gagnés", help: "La croissance générée par les intérêts composés." },
      yearlyBreakdown: { label: "Détail annuel", help: "Capital annuel, total versé et intérêts gagnés chaque année." },
    },
    options: {
      compoundFrequency: {
        annually: "Annuellement (1×/an)",
        quarterly: "Trimestriellement (4×/an)",
        monthly: "Mensuellement (12×/an)",
        daily: "Quotidiennement (365×/an)",
      },
    },
    errors: {
      principalRange: "Le capital doit être compris entre 0 et 10 000 000.",
      rateRange: "Le taux annuel doit être entre 0 % et 50 %.",
      yearsRange: "La durée doit être entre 1 et 50 ans.",
      contributionRange: "Le versement mensuel doit être entre 0 et 100 000.",
    },
    faq: [
      {
        q: "Qu'est-ce que l'intérêt composé ?",
        a: "L'intérêt composé est calculé sur le capital initial et sur les intérêts déjà accumulés. Contrairement à l'intérêt simple, il entraîne une croissance exponentielle dans le temps.",
      },
    ],
  },

  es: {
    title: "Calculadora de Interés Compuesto",
    short: "Calcula cómo crece tu ahorro con el interés compuesto y aportaciones periódicas.",
    description:
      "Calculadora de interés compuesto gratuita. Introduce el capital inicial, la tasa anual, la frecuencia de capitalización y las aportaciones mensuales para ver el valor futuro.",
    keywords: [
      "calculadora interés compuesto",
      "calculadora inversión",
      "calculadora ahorro",
      "valor futuro",
      "crecimiento compuesto",
      "interés calculadora",
      "rendimiento inversión",
    ],
    inputs: {
      principal: { label: "Inversión inicial", help: "El importe que inviertes hoy." },
      annualRate: { label: "Tipo de interés anual (%)", help: "Rentabilidad anual esperada o tipo de interés." },
      years: { label: "Período (años)", help: "Cuántos años está invertido el dinero." },
      compoundFrequency: { label: "Frecuencia de capitalización", help: "Con qué frecuencia se calculan y añaden los intereses al capital." },
      monthlyContribution: { label: "Aportación mensual", help: "Importe adicional aportado cada mes. Introduce 0 si no hay." },
    },
    outputs: {
      futureValue: { label: "Valor futuro", help: "Valor total de la cuenta al final del período." },
      totalContributions: { label: "Total aportado", help: "Inversión inicial más todas las aportaciones mensuales." },
      totalInterest: { label: "Intereses ganados", help: "El crecimiento generado por el interés compuesto." },
      yearlyBreakdown: { label: "Desglose anual", help: "Capital anual, total aportado e intereses ganados cada año." },
    },
    options: {
      compoundFrequency: {
        annually: "Anual (1×/año)",
        quarterly: "Trimestral (4×/año)",
        monthly: "Mensual (12×/año)",
        daily: "Diario (365×/año)",
      },
    },
    errors: {
      principalRange: "La inversión inicial debe estar entre 0 y 10.000.000.",
      rateRange: "El tipo anual debe estar entre 0 % y 50 %.",
      yearsRange: "El período debe estar entre 1 y 50 años.",
      contributionRange: "La aportación mensual debe estar entre 0 y 100.000.",
    },
    faq: [
      {
        q: "¿Qué es el interés compuesto?",
        a: "El interés compuesto se calcula sobre el capital inicial y sobre los intereses acumulados en períodos anteriores. A diferencia del interés simple, genera un crecimiento exponencial con el tiempo.",
      },
    ],
  },

  it: {
    title: "Calcolatore Interesse Composto",
    short: "Calcola come cresce il tuo risparmio con l'interesse composto e contributi mensili.",
    description:
      "Calcolatore di interesse composto gratuito. Inserisci il capitale iniziale, il tasso annuo, la frequenza di capitalizzazione e i contributi mensili per vedere il valore futuro.",
    keywords: [
      "calcolatore interesse composto",
      "calcolatore investimento",
      "calcolatore risparmio",
      "valore futuro",
      "crescita composta",
      "interesse calcolatore",
      "rendimento investimento",
    ],
    inputs: {
      principal: { label: "Investimento iniziale", help: "L'importo investito oggi." },
      annualRate: { label: "Tasso annuo (%)", help: "Rendimento annuo atteso o tasso di interesse." },
      years: { label: "Periodo (anni)", help: "Per quanti anni il denaro è investito." },
      compoundFrequency: { label: "Frequenza di capitalizzazione", help: "Con quale frequenza gli interessi vengono calcolati e aggiunti al capitale." },
      monthlyContribution: { label: "Contributo mensile", help: "Importo aggiuntivo versato ogni mese. Inserisci 0 se assente." },
    },
    outputs: {
      futureValue: { label: "Valore futuro", help: "Valore totale del conto alla fine del periodo." },
      totalContributions: { label: "Totale versamenti", help: "Capitale iniziale più tutti i contributi mensili." },
      totalInterest: { label: "Interessi maturati", help: "La crescita generata dall'interesse composto." },
      yearlyBreakdown: { label: "Dettaglio annuale", help: "Capitale annuale, totale versato e interessi maturati ogni anno." },
    },
    options: {
      compoundFrequency: {
        annually: "Annuale (1×/anno)",
        quarterly: "Trimestrale (4×/anno)",
        monthly: "Mensile (12×/anno)",
        daily: "Giornaliero (365×/anno)",
      },
    },
    errors: {
      principalRange: "L'investimento deve essere tra 0 e 10.000.000.",
      rateRange: "Il tasso annuo deve essere tra 0% e 50%.",
      yearsRange: "Il periodo deve essere tra 1 e 50 anni.",
      contributionRange: "Il contributo mensile deve essere tra 0 e 100.000.",
    },
    faq: [
      {
        q: "Che cos'è l'interesse composto?",
        a: "L'interesse composto viene calcolato sia sul capitale iniziale che sugli interessi già maturati nei periodi precedenti. A differenza dell'interesse semplice, genera una crescita esponenziale nel tempo.",
      },
    ],
  },

  ar: {
    title: "حاسبة الفائدة المركبة",
    short: "احسب كيف ينمو مدخراتك مع الفائدة المركبة والمساهمات المنتظمة.",
    description:
      "حاسبة فائدة مركبة مجانية. أدخل رأس المال الأولي ومعدل العائد وتكرار التركيب والمساهمات الشهرية لرؤية قيمتك المستقبلية.",
    keywords: [
      "حاسبة الفائدة المركبة",
      "حاسبة الاستثمار",
      "حاسبة المدخرات",
      "القيمة المستقبلية",
      "النمو المركب",
      "حساب الفائدة",
      "عائد الاستثمار",
    ],
    inputs: {
      principal: { label: "الاستثمار الأولي", help: "المبلغ الذي تستثمره اليوم." },
      annualRate: { label: "معدل العائد السنوي (%)", help: "العائد السنوي المتوقع أو معدل الفائدة." },
      years: { label: "المدة (سنوات)", help: "عدد السنوات التي يُستثمر فيها المال." },
      compoundFrequency: { label: "تكرار التركيب", help: "مدى تكرار احتساب الفائدة وإضافتها إلى الرصيد." },
      monthlyContribution: { label: "المساهمة الشهرية", help: "مبلغ إضافي يُضاف كل شهر. أدخل 0 إذا لم يكن هناك مساهمة." },
    },
    outputs: {
      futureValue: { label: "القيمة المستقبلية", help: "إجمالي قيمة الحساب في نهاية الفترة." },
      totalContributions: { label: "إجمالي المساهمات", help: "الاستثمار الأولي بالإضافة إلى جميع المساهمات الشهرية." },
      totalInterest: { label: "إجمالي الفوائد المكتسبة", help: "النمو الناتج عن الفائدة المركبة." },
      yearlyBreakdown: { label: "التفصيل السنوي", help: "الرصيد السنوي والمساهمات المتراكمة والفائدة المكتسبة لكل عام." },
    },
    options: {
      compoundFrequency: {
        annually: "سنوياً (مرة/سنة)",
        quarterly: "ربع سنوي (4 مرات/سنة)",
        monthly: "شهرياً (12 مرة/سنة)",
        daily: "يومياً (365 مرة/سنة)",
      },
    },
    errors: {
      principalRange: "يجب أن يكون الاستثمار الأولي بين 0 و10,000,000.",
      rateRange: "يجب أن يكون المعدل السنوي بين 0% و50%.",
      yearsRange: "يجب أن تكون المدة بين سنة واحدة و50 سنة.",
      contributionRange: "يجب أن تكون المساهمة الشهرية بين 0 و100,000.",
    },
    faq: [
      {
        q: "ما هي الفائدة المركبة؟",
        a: "الفائدة المركبة هي الفائدة المحسوبة على رأس المال الأصلي وعلى الفوائد المتراكمة من الفترات السابقة. على عكس الفائدة البسيطة، تُولّد الفائدة المركبة نمواً أسياً مع مرور الوقت.",
      },
    ],
  },

  ru: {
    title: "Калькулятор сложных процентов",
    short: "Рассчитайте, как растут ваши сбережения за счёт сложных процентов и регулярных взносов.",
    description:
      "Бесплатный калькулятор сложных процентов. Введите начальный капитал, годовую ставку, частоту начисления и ежемесячные взносы — получите будущую стоимость.",
    keywords: [
      "калькулятор сложных процентов",
      "калькулятор инвестиций",
      "калькулятор накоплений",
      "будущая стоимость",
      "сложный рост",
      "расчёт процентов",
      "доходность инвестиций",
    ],
    inputs: {
      principal: { label: "Начальный капитал", help: "Сумма, вкладываемая сегодня." },
      annualRate: { label: "Годовая ставка (%)", help: "Ожидаемая годовая доходность или процентная ставка." },
      years: { label: "Срок (лет)", help: "Как долго деньги находятся в инвестиции." },
      compoundFrequency: { label: "Частота начисления", help: "Как часто проценты начисляются и добавляются к капиталу." },
      monthlyContribution: { label: "Ежемесячный взнос", help: "Дополнительная сумма, вносимая каждый месяц. Введите 0, если взносов нет." },
    },
    outputs: {
      futureValue: { label: "Будущая стоимость", help: "Общая стоимость счёта в конце периода." },
      totalContributions: { label: "Итого вложено", help: "Начальный капитал плюс все ежемесячные взносы." },
      totalInterest: { label: "Заработано процентов", help: "Прирост капитала за счёт сложных процентов." },
      yearlyBreakdown: { label: "Разбивка по годам", help: "Годовой баланс, накопленные взносы и проценты за каждый год." },
    },
    options: {
      compoundFrequency: {
        annually: "Ежегодно (1 раз/год)",
        quarterly: "Ежеквартально (4 раза/год)",
        monthly: "Ежемесячно (12 раз/год)",
        daily: "Ежедневно (365 раз/год)",
      },
    },
    errors: {
      principalRange: "Начальный капитал должен быть от 0 до 10 000 000.",
      rateRange: "Годовая ставка должна быть от 0 % до 50 %.",
      yearsRange: "Срок должен быть от 1 до 50 лет.",
      contributionRange: "Ежемесячный взнос должен быть от 0 до 100 000.",
    },
    faq: [
      {
        q: "Что такое сложные проценты?",
        a: "Сложные проценты начисляются как на начальный капитал, так и на уже накопленные проценты. В отличие от простых процентов, они обеспечивают экспоненциальный рост с течением времени.",
      },
    ],
  },

  zh: {
    title: "复利计算器",
    short: "计算您的储蓄通过复利和定期投入随时间增长的情况。",
    description:
      "免费复利计算器。输入初始本金、年利率、复利频率和每月投入金额，即可查看未来价值及逐年增长明细。",
    keywords: [
      "复利计算器",
      "投资增长计算器",
      "储蓄计算器",
      "未来价值计算",
      "复合增长",
      "利息计算器",
      "投资回报计算",
    ],
    inputs: {
      principal: { label: "初始投资", help: "今天投入的金额。" },
      annualRate: { label: "年利率 (%)", help: "预期年回报率或利率。" },
      years: { label: "投资期限（年）", help: "资金投资的年数。" },
      compoundFrequency: { label: "复利频率", help: "利息计算并计入本金的频率。" },
      monthlyContribution: { label: "每月投入", help: "每月额外投入的金额。如无则填 0。" },
    },
    outputs: {
      futureValue: { label: "未来价值", help: "期末账户的总价值。" },
      totalContributions: { label: "总投入", help: "初始投资加上所有每月投入的总和。" },
      totalInterest: { label: "总利息收益", help: "复利产生的增长部分。" },
      yearlyBreakdown: { label: "逐年明细", help: "每年的余额、累计投入和利息收益。" },
    },
    options: {
      compoundFrequency: {
        annually: "每年（1次/年）",
        quarterly: "每季度（4次/年）",
        monthly: "每月（12次/年）",
        daily: "每日（365次/年）",
      },
    },
    errors: {
      principalRange: "初始投资必须在 0 至 10,000,000 之间。",
      rateRange: "年利率必须在 0% 至 50% 之间。",
      yearsRange: "投资期限必须在 1 至 50 年之间。",
      contributionRange: "每月投入必须在 0 至 100,000 之间。",
    },
    faq: [
      {
        q: "什么是复利？",
        a: "复利是在初始本金和已累积利息的基础上计算的利息。与单利不同，复利会随着时间的推移产生指数级增长。",
      },
    ],
  },

  ja: {
    title: "複利計算機",
    short: "複利と定期積立によって資産がどのように成長するかを計算します。",
    description:
      "無料の複利計算機です。初期投資額、年利、複利頻度、毎月の積立額を入力して、将来の資産価値と年次成長を確認できます。",
    keywords: [
      "複利計算機",
      "投資成長計算",
      "貯蓄計算機",
      "将来価値",
      "複利成長",
      "利息計算",
      "投資収益計算",
    ],
    inputs: {
      principal: { label: "初期投資額", help: "現在投資する金額。" },
      annualRate: { label: "年利 (%)", help: "期待する年間利回りまたは金利。" },
      years: { label: "運用期間（年）", help: "資金を運用する年数。" },
      compoundFrequency: { label: "複利頻度", help: "利息が計算されて残高に加算される頻度。" },
      monthlyContribution: { label: "毎月の積立額", help: "毎月追加で積み立てる金額。なければ0を入力。" },
    },
    outputs: {
      futureValue: { label: "将来価値", help: "期間終了時の口座の総額。" },
      totalContributions: { label: "総投資額", help: "初期投資額と全積立額の合計。" },
      totalInterest: { label: "利息合計", help: "複利によって生まれた増加分。" },
      yearlyBreakdown: { label: "年次内訳", help: "各年の残高・累計投資額・獲得利息。" },
    },
    options: {
      compoundFrequency: {
        annually: "年1回",
        quarterly: "年4回（四半期）",
        monthly: "年12回（毎月）",
        daily: "年365回（毎日）",
      },
    },
    errors: {
      principalRange: "初期投資額は 0 ～ 10,000,000 の範囲で入力してください。",
      rateRange: "年利は 0% ～ 50% の範囲で入力してください。",
      yearsRange: "運用期間は 1 ～ 50 年の範囲で入力してください。",
      contributionRange: "毎月の積立額は 0 ～ 100,000 の範囲で入力してください。",
    },
    faq: [
      {
        q: "複利とは何ですか？",
        a: "複利とは、元本だけでなく過去の利息にも利息が付く仕組みです。単利と異なり、複利は時間が経つにつれて指数関数的な成長をもたらします。",
      },
    ],
  },

  ko: {
    title: "복리 계산기",
    short: "복리와 정기 적립금으로 저축이 시간에 따라 얼마나 성장하는지 계산하세요.",
    description:
      "무료 복리 계산기입니다. 초기 투자금, 연이율, 복리 빈도, 월 적립액을 입력하면 미래 가치와 연도별 성장 내역을 확인할 수 있습니다.",
    keywords: [
      "복리 계산기",
      "투자 성장 계산기",
      "저축 계산기",
      "미래 가치 계산",
      "복합 성장",
      "이자 계산기",
      "투자 수익 계산",
    ],
    inputs: {
      principal: { label: "초기 투자금", help: "오늘 투자하는 금액." },
      annualRate: { label: "연이율 (%)", help: "예상 연간 수익률 또는 이자율." },
      years: { label: "투자 기간 (년)", help: "자금을 투자하는 연수." },
      compoundFrequency: { label: "복리 빈도", help: "이자가 계산되어 잔액에 추가되는 빈도." },
      monthlyContribution: { label: "월 적립금", help: "매월 추가 투자하는 금액. 없으면 0을 입력하세요." },
    },
    outputs: {
      futureValue: { label: "미래 가치", help: "기간 말 계좌의 총 가치." },
      totalContributions: { label: "총 투자금", help: "초기 투자금과 모든 월 적립금의 합계." },
      totalInterest: { label: "총 이자 수익", help: "복리로 발생한 성장 금액." },
      yearlyBreakdown: { label: "연도별 내역", help: "연도별 잔액, 누적 투자금 및 이자 수익." },
    },
    options: {
      compoundFrequency: {
        annually: "연간 (1회/년)",
        quarterly: "분기별 (4회/년)",
        monthly: "월별 (12회/년)",
        daily: "일별 (365회/년)",
      },
    },
    errors: {
      principalRange: "초기 투자금은 0 ~ 10,000,000 사이여야 합니다.",
      rateRange: "연이율은 0% ~ 50% 사이여야 합니다.",
      yearsRange: "투자 기간은 1 ~ 50년 사이여야 합니다.",
      contributionRange: "월 적립금은 0 ~ 100,000 사이여야 합니다.",
    },
    faq: [
      {
        q: "복리란 무엇인가요?",
        a: "복리는 초기 원금뿐만 아니라 이전 기간에 누적된 이자에도 이자가 붙는 방식입니다. 단리와 달리 복리는 시간이 지남에 따라 지수적 성장을 가져옵니다.",
      },
    ],
  },

  hi: {
    title: "चक्रवृद्धि ब्याज कैलकुलेटर",
    short: "जानें कि आपकी बचत चक्रवृद्धि ब्याज और नियमित योगदान के साथ समय के साथ कैसे बढ़ती है।",
    description:
      "मुफ़्त चक्रवृद्धि ब्याज कैलकुलेटर। मूलधन, वार्षिक दर, चक्रवृद्धि आवृत्ति और मासिक योगदान दर्ज करें और भविष्य का मूल्य देखें।",
    keywords: [
      "चक्रवृद्धि ब्याज कैलकुलेटर",
      "निवेश वृद्धि कैलकुलेटर",
      "बचत कैलकुलेटर",
      "भविष्य मूल्य",
      "चक्रवृद्धि वृद्धि",
      "ब्याज कैलकुलेटर",
      "निवेश रिटर्न",
    ],
    inputs: {
      principal: { label: "प्रारंभिक निवेश", help: "आज जो राशि निवेश की जा रही है।" },
      annualRate: { label: "वार्षिक ब्याज दर (%)", help: "अपेक्षित वार्षिक रिटर्न या ब्याज दर।" },
      years: { label: "समय अवधि (वर्ष)", help: "धन कितने वर्षों के लिए निवेशित रहेगा।" },
      compoundFrequency: { label: "चक्रवृद्धि आवृत्ति", help: "ब्याज की गणना कितनी बार होती है और शेष में जुड़ती है।" },
      monthlyContribution: { label: "मासिक योगदान", help: "हर महीने जोड़ी जाने वाली अतिरिक्त राशि। न हो तो 0 दर्ज करें।" },
    },
    outputs: {
      futureValue: { label: "भविष्य मूल्य", help: "अवधि के अंत में खाते का कुल मूल्य।" },
      totalContributions: { label: "कुल योगदान", help: "प्रारंभिक निवेश और सभी मासिक योगदानों का योग।" },
      totalInterest: { label: "कुल ब्याज अर्जित", help: "चक्रवृद्धि ब्याज से उत्पन्न वृद्धि।" },
      yearlyBreakdown: { label: "वार्षिक विवरण", help: "प्रत्येक वर्ष की शेष राशि, योगदान और ब्याज।" },
    },
    options: {
      compoundFrequency: {
        annually: "वार्षिक (1 बार/वर्ष)",
        quarterly: "त्रैमासिक (4 बार/वर्ष)",
        monthly: "मासिक (12 बार/वर्ष)",
        daily: "दैनिक (365 बार/वर्ष)",
      },
    },
    errors: {
      principalRange: "प्रारंभिक निवेश 0 से 10,000,000 के बीच होना चाहिए।",
      rateRange: "वार्षिक दर 0% से 50% के बीच होनी चाहिए।",
      yearsRange: "समय अवधि 1 से 50 वर्ष के बीच होनी चाहिए।",
      contributionRange: "मासिक योगदान 0 से 100,000 के बीच होना चाहिए।",
    },
    faq: [
      {
        q: "चक्रवृद्धि ब्याज क्या है?",
        a: "चक्रवृद्धि ब्याज वह ब्याज है जो मूल मूलधन और पिछली अवधियों के संचित ब्याज दोनों पर गणना की जाती है। साधारण ब्याज के विपरीत, यह समय के साथ घातांकीय वृद्धि प्रदान करता है।",
      },
    ],
  },
};

export default i18n;
