import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Neumorphism CSS Generator", short: "Build neumorphic soft-shadow CSS with a live preview.", description: "Free neumorphism CSS generator. Adjust background, shadow distance, blur, intensity and radius — toggle inset for a pressed look. Copies a single block of CSS with the matched light and dark shadows.", keywords: ["neumorphism generator", "soft ui shadow", "neumorphic css", "soft shadow generator", "neumorphism css"], background: "Background", distance: "Distance", blur: "Blur", intensity: "Intensity", radius: "Radius", inset: "Inset (pressed)", preview: "Preview" },
  tr: { title: "Neumorphism CSS Oluşturucu", short: "Canlı önizlemeyle neumorfik yumuşak gölge CSS'i oluşturun.", description: "Ücretsiz neumorphism CSS oluşturucu. Arka plan, gölge mesafesi, bulanıklık, yoğunluk ve yarıçapı ayarlayın — basılı görünüm için inset'i değiştirin. Eşleşen açık ve koyu gölgelerle tek bir CSS bloğu kopyalar.", keywords: ["neumorphism oluşturucu", "soft ui gölge", "neumorphic css", "yumuşak gölge oluşturucu", "neumorphism css"], background: "Arka plan", distance: "Mesafe", blur: "Bulanıklık", intensity: "Yoğunluk", radius: "Yarıçap", inset: "Inset (basılı)", preview: "Önizleme" },
  de: { title: "Neumorphism-CSS-Generator", short: "Erzeugen Sie neumorphes Soft-Shadow-CSS mit Live-Vorschau.", description: "Kostenloser Neumorphism-CSS-Generator. Passen Sie Hintergrund, Schattenabstand, Unschärfe, Intensität und Radius an — Inset für einen gedrückten Look. Kopiert einen CSS-Block mit passenden hellen und dunklen Schatten.", keywords: ["neumorphism generator", "soft ui schatten", "neumorphes css", "soft shadow generator", "neumorphism css"], background: "Hintergrund", distance: "Abstand", blur: "Unschärfe", intensity: "Intensität", radius: "Radius", inset: "Inset (gedrückt)", preview: "Vorschau" },
  fr: { title: "Générateur CSS Neumorphism", short: "Créez du CSS neumorphic à ombres douces avec aperçu en direct.", description: "Générateur CSS neumorphism gratuit. Ajustez l'arrière-plan, la distance d'ombre, le flou, l'intensité et le rayon — activez inset pour un look enfoncé. Copie un bloc CSS avec ombres claires et sombres assorties.", keywords: ["générateur neumorphism", "ombre soft ui", "css neumorphic", "générateur ombre douce", "css neumorphism"], background: "Arrière-plan", distance: "Distance", blur: "Flou", intensity: "Intensité", radius: "Rayon", inset: "Inset (enfoncé)", preview: "Aperçu" },
  es: { title: "Generador CSS Neumorphism", short: "Crea CSS neumorphic de sombras suaves con vista previa en vivo.", description: "Generador CSS neumorphism gratuito. Ajusta fondo, distancia de sombra, desenfoque, intensidad y radio — activa inset para un aspecto presionado. Copia un bloque CSS con sombras claras y oscuras coincidentes.", keywords: ["generador neumorphism", "sombra soft ui", "css neumorphic", "generador sombra suave", "css neumorphism"], background: "Fondo", distance: "Distancia", blur: "Desenfoque", intensity: "Intensidad", radius: "Radio", inset: "Inset (presionado)", preview: "Vista previa" },
  it: { title: "Generatore CSS Neumorphism", short: "Crea CSS neumorphic con ombre morbide e anteprima dal vivo.", description: "Generatore CSS neumorphism gratuito. Regola sfondo, distanza ombra, sfocatura, intensità e raggio — attiva inset per un aspetto premuto. Copia un blocco CSS con ombre chiare e scure abbinate.", keywords: ["generatore neumorphism", "ombra soft ui", "css neumorphic", "generatore ombra morbida", "css neumorphism"], background: "Sfondo", distance: "Distanza", blur: "Sfocatura", intensity: "Intensità", radius: "Raggio", inset: "Inset (premuto)", preview: "Anteprima" },
  ar: { title: "مولّد Neumorphism CSS", short: "أنشئ CSS neumorphic بظلال ناعمة مع معاينة حية.", description: "مولّد neumorphism CSS مجاني. اضبط الخلفية، ومسافة الظل، والتمويه، والشدة، ونصف القطر — بدّل inset للحصول على مظهر مضغوط. ينسخ كتلة CSS واحدة مع ظلال فاتحة وداكنة متطابقة.", keywords: ["مولد neumorphism", "ظل soft ui", "css neumorphic", "مولد الظل الناعم", "neumorphism css"], background: "الخلفية", distance: "المسافة", blur: "التمويه", intensity: "الشدة", radius: "نصف القطر", inset: "Inset (مضغوط)", preview: "معاينة" },
  ru: { title: "Генератор Neumorphism CSS", short: "Создавайте neumorphic CSS с мягкими тенями и живым превью.", description: "Бесплатный генератор neumorphism CSS. Настройте фон, расстояние тени, размытие, интенсивность и радиус — включите inset для нажатого вида. Копирует один блок CSS с подобранными светлой и тёмной тенями.", keywords: ["генератор neumorphism", "тень soft ui", "css neumorphic", "генератор мягкой тени", "css neumorphism"], background: "Фон", distance: "Расстояние", blur: "Размытие", intensity: "Интенсивность", radius: "Радиус", inset: "Inset (нажатый)", preview: "Превью" },
  zh: { title: "Neumorphism CSS 生成器", short: "构建带实时预览的 neumorphic 柔和阴影 CSS。", description: "免费的 neumorphism CSS 生成器。调整背景、阴影距离、模糊、强度和半径——切换 inset 以获得按下效果。复制带匹配的浅色和深色阴影的单个 CSS 块。", keywords: ["neumorphism 生成器", "soft ui 阴影", "neumorphic css", "柔和阴影生成器", "neumorphism css"], background: "背景", distance: "距离", blur: "模糊", intensity: "强度", radius: "半径", inset: "Inset（按下）", preview: "预览" },
  ja: { title: "Neumorphism CSS ジェネレーター", short: "ライブプレビュー付きでニューモーフィックなソフトシャドウ CSS を構築。", description: "無料の neumorphism CSS ジェネレーター。背景、影の距離、ぼかし、強度、半径を調整——inset を切り替えて押し下げた外観に。一致する明るい影と暗い影を持つ単一の CSS ブロックをコピーします。", keywords: ["neumorphism ジェネレーター", "soft ui シャドウ", "ニューモーフィック css", "ソフトシャドウ ジェネレーター", "neumorphism css"], background: "背景", distance: "距離", blur: "ぼかし", intensity: "強度", radius: "半径", inset: "Inset（押し下げ）", preview: "プレビュー" },
  ko: { title: "Neumorphism CSS 생성기", short: "실시간 미리보기로 neumorphic 소프트 그림자 CSS를 만듭니다.", description: "무료 neumorphism CSS 생성기. 배경, 그림자 거리, 흐림, 강도, 반경을 조정하세요 — 눌린 모양을 위해 inset을 토글하세요. 일치하는 밝은 그림자와 어두운 그림자가 있는 단일 CSS 블록을 복사합니다.", keywords: ["neumorphism 생성기", "soft ui 그림자", "neumorphic css", "소프트 그림자 생성기", "neumorphism css"], background: "배경", distance: "거리", blur: "흐림", intensity: "강도", radius: "반경", inset: "Inset (눌림)", preview: "미리보기" },
  hi: { title: "Neumorphism CSS जनरेटर", short: "लाइव प्रीव्यू के साथ neumorphic सॉफ्ट-शैडो CSS बनाएं।", description: "मुफ्त neumorphism CSS जनरेटर। पृष्ठभूमि, छाया दूरी, ब्लर, तीव्रता और रेडियस को समायोजित करें — दबाए हुए लुक के लिए inset को टॉगल करें। मेल खाने वाली हल्की और गहरी छायाओं के साथ एकल CSS ब्लॉक कॉपी करता है।", keywords: ["neumorphism जनरेटर", "soft ui छाया", "neumorphic css", "सॉफ्ट छाया जनरेटर", "neumorphism css"], background: "पृष्ठभूमि", distance: "दूरी", blur: "ब्लर", intensity: "तीव्रता", radius: "रेडियस", inset: "Inset (दबाया हुआ)", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
