import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "QR Code Generator", short: "Create QR codes for text, URLs, WiFi networks and vCards.", description: "Free QR code generator. Encode plain text, a URL, a WiFi network or a contact (vCard) as a downloadable PNG QR code — generated entirely in your browser, nothing uploaded.", keywords: ["qr code generator", "wifi qr code", "vcard qr code", "create qr code online", "qr code maker"], modeText: "Text / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Text or URL", ssid: "Network name (SSID)", password: "Password", encryption: "Encryption", hidden: "Hidden network", name: "Full name", phone: "Phone", email: "Email", org: "Organization", url: "URL", download: "Download PNG" },
  pt: { title: "Gerador de QR Code", short: "Create QR codes para text, URLs, WiFi networks e vCards.", description: "Gratuito - QR code generator. Codificar plain text, a URL, a WiFi network ou a contact (vCard) as a downloadable PNG QR code â generated entirely no seu navegador, nothing uploaded.", keywords: ["qr code generator", "wifi qr code", "vcard qr code", "create qr code online", "qr code maker"], modeText: "Text / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Text or URL", ssid: "Network name (SSID)", password: "Password", encryption: "Encryption", hidden: "Hidden network", name: "Full name", phone: "Phone", email: "Email", org: "Organization", url: "URL", download: "Download PNG" },
  id: { title: "Generator QR Code", short: "Create QR codes for text, URLs, WiFi networks dan vCards.", description: "Gratis - QR code generator. Enkode plain text, a URL, a WiFi network atau a contact (vCard) as a downloadable PNG QR code â generated entirely di browser Anda, nothing uploaded.", keywords: ["qr code generator", "wifi qr code", "vcard qr code", "create qr code online", "qr code maker"], modeText: "Text / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Text or URL", ssid: "Network name (SSID)", password: "Password", encryption: "Encryption", hidden: "Hidden network", name: "Full name", phone: "Phone", email: "Email", org: "Organization", url: "URL", download: "Download PNG" },

  tr: { title: "QR Kod Oluşturucu", short: "Metin, URL, WiFi ağları ve vCard'lar için QR kod oluşturun.", description: "Ücretsiz QR kod oluşturucu. Düz metin, URL, WiFi ağı veya kişi (vCard) verisini indirilebilir bir PNG QR kod olarak kodlayın — tamamen tarayıcınızda oluşturulur, hiçbir şey yüklenmez.", keywords: ["qr kod oluşturucu", "wifi qr kod", "vcard qr kod", "online qr kod oluştur", "qr kod yapıcı"], modeText: "Metin / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Metin veya URL", ssid: "Ağ adı (SSID)", password: "Parola", encryption: "Şifreleme", hidden: "Gizli ağ", name: "Ad soyad", phone: "Telefon", email: "E-posta", org: "Kurum", url: "URL", download: "PNG indir" },
  de: { title: "QR-Code-Generator", short: "Erstellen Sie QR-Codes für Text, URLs, WLAN-Netzwerke und vCards.", description: "Kostenloser QR-Code-Generator. Codieren Sie Text, eine URL, ein WLAN-Netzwerk oder einen Kontakt (vCard) als herunterladbaren PNG-QR-Code — vollständig im Browser erzeugt, nichts wird hochgeladen.", keywords: ["qr code generator", "wifi qr code", "vcard qr code", "qr code online erstellen", "qr code maker"], modeText: "Text / URL", modeWifi: "WLAN", modeVcard: "vCard", text: "Text oder URL", ssid: "Netzwerkname (SSID)", password: "Passwort", encryption: "Verschlüsselung", hidden: "Verstecktes Netzwerk", name: "Vollständiger Name", phone: "Telefon", email: "E-Mail", org: "Organisation", url: "URL", download: "PNG herunterladen" },
  fr: { title: "Générateur de QR Code", short: "Créez des QR codes pour du texte, des URLs, des réseaux WiFi et des vCards.", description: "Générateur de QR code gratuit. Encodez du texte, une URL, un réseau WiFi ou un contact (vCard) en QR code PNG téléchargeable — généré entièrement dans votre navigateur, rien n'est envoyé.", keywords: ["générateur qr code", "qr code wifi", "qr code vcard", "créer qr code en ligne", "fabricant qr code"], modeText: "Texte / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Texte ou URL", ssid: "Nom du réseau (SSID)", password: "Mot de passe", encryption: "Chiffrement", hidden: "Réseau caché", name: "Nom complet", phone: "Téléphone", email: "E-mail", org: "Organisation", url: "URL", download: "Télécharger PNG" },
  es: { title: "Generador de Códigos QR", short: "Crea códigos QR para texto, URLs, redes WiFi y vCards.", description: "Generador de códigos QR gratuito. Codifica texto, una URL, una red WiFi o un contacto (vCard) en un código QR PNG descargable — generado completamente en tu navegador, nada se sube.", keywords: ["generador código qr", "qr wifi", "qr vcard", "crear código qr online", "creador código qr"], modeText: "Texto / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Texto o URL", ssid: "Nombre de red (SSID)", password: "Contraseña", encryption: "Cifrado", hidden: "Red oculta", name: "Nombre completo", phone: "Teléfono", email: "Email", org: "Organización", url: "URL", download: "Descargar PNG" },
  it: { title: "Generatore di Codici QR", short: "Crea codici QR per testo, URL, reti WiFi e vCard.", description: "Generatore di codici QR gratuito. Codifica testo, un URL, una rete WiFi o un contatto (vCard) in un codice QR PNG scaricabile — generato interamente nel browser, nulla viene caricato.", keywords: ["generatore codice qr", "qr wifi", "qr vcard", "creare codice qr online", "creatore codice qr"], modeText: "Testo / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Testo o URL", ssid: "Nome rete (SSID)", password: "Password", encryption: "Crittografia", hidden: "Rete nascosta", name: "Nome completo", phone: "Telefono", email: "Email", org: "Organizzazione", url: "URL", download: "Scarica PNG" },
  ar: { title: "مولّد رمز QR", short: "أنشئ رموز QR للنصوص وعناوين URL وشبكات WiFi و vCard.", description: "مولّد رمز QR مجاني. شفّر نصًا أو عنوان URL أو شبكة WiFi أو جهة اتصال (vCard) كرمز QR PNG قابل للتنزيل — يتم إنشاؤه بالكامل في متصفحك، لا شيء يُرفع.", keywords: ["مولد رمز qr", "qr واي فاي", "qr vcard", "إنشاء رمز qr عبر الإنترنت", "صانع رمز qr"], modeText: "نص / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "نص أو URL", ssid: "اسم الشبكة (SSID)", password: "كلمة المرور", encryption: "التشفير", hidden: "شبكة مخفية", name: "الاسم الكامل", phone: "الهاتف", email: "البريد الإلكتروني", org: "المؤسسة", url: "URL", download: "تنزيل PNG" },
  ru: { title: "Генератор QR-кодов", short: "Создавайте QR-коды для текста, URL, сетей WiFi и vCard.", description: "Бесплатный генератор QR-кодов. Закодируйте текст, URL, сеть WiFi или контакт (vCard) в загружаемый PNG QR-код — генерируется полностью в вашем браузере, ничего не загружается.", keywords: ["генератор qr-кодов", "wifi qr-код", "vcard qr-код", "создать qr-код онлайн", "создатель qr-кода"], modeText: "Текст / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "Текст или URL", ssid: "Имя сети (SSID)", password: "Пароль", encryption: "Шифрование", hidden: "Скрытая сеть", name: "Полное имя", phone: "Телефон", email: "Email", org: "Организация", url: "URL", download: "Скачать PNG" },
  zh: { title: "二维码生成器", short: "为文本、URL、WiFi 网络和 vCard 生成二维码。", description: "免费的二维码生成器。将纯文本、URL、WiFi 网络或联系人 (vCard) 编码为可下载的 PNG 二维码——完全在浏览器中生成，不上传任何内容。", keywords: ["二维码生成器", "wifi 二维码", "vcard 二维码", "在线创建二维码", "二维码制作"], modeText: "文本 / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "文本或 URL", ssid: "网络名称 (SSID)", password: "密码", encryption: "加密", hidden: "隐藏网络", name: "姓名", phone: "电话", email: "电子邮件", org: "组织", url: "URL", download: "下载 PNG" },
  ja: { title: "QR コード生成", short: "テキスト、URL、WiFi、vCard 用の QR コードを作成。", description: "無料の QR コード生成ツール。プレーンテキスト、URL、WiFi ネットワーク、連絡先 (vCard) をダウンロード可能な PNG QR コードにエンコード——すべてブラウザ内で生成、何もアップロードされません。", keywords: ["qr コード 生成", "wifi qr コード", "vcard qr コード", "オンライン qr コード作成", "qr コードメーカー"], modeText: "テキスト / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "テキストまたは URL", ssid: "ネットワーク名 (SSID)", password: "パスワード", encryption: "暗号化", hidden: "非公開ネットワーク", name: "氏名", phone: "電話", email: "メール", org: "組織", url: "URL", download: "PNG をダウンロード" },
  ko: { title: "QR 코드 생성기", short: "텍스트, URL, WiFi 네트워크, vCard용 QR 코드를 만듭니다.", description: "무료 QR 코드 생성기. 일반 텍스트, URL, WiFi 네트워크 또는 연락처(vCard)를 다운로드 가능한 PNG QR 코드로 인코딩 — 모두 브라우저에서 생성되며 아무것도 업로드되지 않습니다.", keywords: ["qr 코드 생성기", "wifi qr 코드", "vcard qr 코드", "온라인 qr 코드 만들기", "qr 코드 메이커"], modeText: "텍스트 / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "텍스트 또는 URL", ssid: "네트워크 이름 (SSID)", password: "비밀번호", encryption: "암호화", hidden: "숨겨진 네트워크", name: "성명", phone: "전화", email: "이메일", org: "조직", url: "URL", download: "PNG 다운로드" },
  hi: { title: "QR कोड जनरेटर", short: "टेक्स्ट, URL, WiFi नेटवर्क और vCard के लिए QR कोड बनाएं।", description: "मुफ्त QR कोड जनरेटर। सादे टेक्स्ट, URL, WiFi नेटवर्क या संपर्क (vCard) को डाउनलोड करने योग्य PNG QR कोड में एन्कोड करें — पूरी तरह आपके ब्राउज़र में जनरेट, कुछ भी अपलोड नहीं।", keywords: ["qr कोड जनरेटर", "wifi qr कोड", "vcard qr कोड", "ऑनलाइन qr कोड बनाएं", "qr कोड मेकर"], modeText: "टेक्स्ट / URL", modeWifi: "WiFi", modeVcard: "vCard", text: "टेक्स्ट या URL", ssid: "नेटवर्क नाम (SSID)", password: "पासवर्ड", encryption: "एन्क्रिप्शन", hidden: "छिपा नेटवर्क", name: "पूरा नाम", phone: "फोन", email: "ईमेल", org: "संगठन", url: "URL", download: "PNG डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
