import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JWT Decoder", short: "Decode a JSON Web Token to read its header and payload.", description: "Free JWT decoder. Paste a JSON Web Token to instantly see its decoded header and payload as formatted JSON, plus the signature. Decoding is local; the signature is not verified.", keywords: ["jwt decoder", "json web token", "decode jwt", "jwt parser", "token decoder"], placeholder: "Paste a JWT (header.payload.signature)…", header: "Header", payload: "Payload", signature: "Signature", invalid: "Not a valid JWT." },
  tr: { title: "JWT Çözücü", short: "Bir JSON Web Token'ı çözerek başlığını ve yükünü okuyun.", description: "Ücretsiz JWT çözücü. Bir JSON Web Token yapıştırın; çözülmüş başlığını ve yükünü biçimlendirilmiş JSON olarak, imzayla birlikte anında görün. Çözme yereldir; imza doğrulanmaz.", keywords: ["jwt çözücü", "json web token", "jwt çöz", "jwt ayrıştırıcı", "token çözücü"], placeholder: "Bir JWT yapıştırın (header.payload.signature)…", header: "Başlık", payload: "Yük", signature: "İmza", invalid: "Geçerli bir JWT değil." },
  de: { title: "JWT-Decoder", short: "Dekodieren Sie einen JSON Web Token, um Header und Payload zu lesen.", description: "Kostenloser JWT-Decoder. Fügen Sie einen JSON Web Token ein, um Header und Payload sofort als formatiertes JSON sowie die Signatur zu sehen. Dekodierung erfolgt lokal; die Signatur wird nicht geprüft.", keywords: ["jwt decoder", "json web token", "jwt dekodieren", "jwt parser", "token decoder"], placeholder: "JWT einfügen (header.payload.signature)…", header: "Header", payload: "Payload", signature: "Signatur", invalid: "Kein gültiges JWT." },
  fr: { title: "Décodeur JWT", short: "Décodez un JSON Web Token pour lire son en-tête et sa charge utile.", description: "Décodeur JWT gratuit. Collez un JSON Web Token pour voir instantanément son en-tête et sa charge utile décodés en JSON formaté, ainsi que la signature. Le décodage est local ; la signature n'est pas vérifiée.", keywords: ["décodeur jwt", "json web token", "décoder jwt", "analyseur jwt", "décodeur de jeton"], placeholder: "Collez un JWT (header.payload.signature)…", header: "En-tête", payload: "Charge utile", signature: "Signature", invalid: "JWT non valide." },
  es: { title: "Decodificador JWT", short: "Decodifica un JSON Web Token para leer su encabezado y carga útil.", description: "Decodificador JWT gratuito. Pega un JSON Web Token para ver al instante su encabezado y carga útil decodificados como JSON formateado, además de la firma. La decodificación es local; la firma no se verifica.", keywords: ["decodificador jwt", "json web token", "decodificar jwt", "analizador jwt", "decodificador de token"], placeholder: "Pega un JWT (header.payload.signature)…", header: "Encabezado", payload: "Carga útil", signature: "Firma", invalid: "No es un JWT válido." },
  it: { title: "Decodificatore JWT", short: "Decodifica un JSON Web Token per leggerne header e payload.", description: "Decodificatore JWT gratuito. Incolla un JSON Web Token per vederne all'istante header e payload decodificati come JSON formattato, oltre alla firma. La decodifica è locale; la firma non viene verificata.", keywords: ["decodificatore jwt", "json web token", "decodifica jwt", "parser jwt", "decodificatore token"], placeholder: "Incolla un JWT (header.payload.signature)…", header: "Header", payload: "Payload", signature: "Firma", invalid: "JWT non valido." },
  ar: { title: "مفكّك JWT", short: "فك ترميز JSON Web Token لقراءة رأسه وحمولته.", description: "مفكّك JWT مجاني. الصق JSON Web Token لرؤية رأسه وحمولته المفكوكة كـ JSON منسّق فورًا، بالإضافة إلى التوقيع. الفك محلي؛ ولا يتم التحقق من التوقيع.", keywords: ["مفكك jwt", "json web token", "فك jwt", "محلل jwt", "مفكك الرمز"], placeholder: "الصق JWT (header.payload.signature)…", header: "الرأس", payload: "الحمولة", signature: "التوقيع", invalid: "ليس JWT صالحًا." },
  ru: { title: "Декодер JWT", short: "Декодируйте JSON Web Token, чтобы прочитать его заголовок и полезную нагрузку.", description: "Бесплатный декодер JWT. Вставьте JSON Web Token, чтобы мгновенно увидеть его декодированные заголовок и полезную нагрузку как форматированный JSON, а также подпись. Декодирование локальное; подпись не проверяется.", keywords: ["декодер jwt", "json web token", "декодировать jwt", "парсер jwt", "декодер токена"], placeholder: "Вставьте JWT (header.payload.signature)…", header: "Заголовок", payload: "Полезная нагрузка", signature: "Подпись", invalid: "Недействительный JWT." },
  zh: { title: "JWT 解码器", short: "解码 JSON Web Token 以读取其头部和载荷。", description: "免费的 JWT 解码器。粘贴 JSON Web Token，即可立即查看其解码后的头部和载荷（格式化 JSON）以及签名。解码在本地进行；不验证签名。", keywords: ["jwt解码器", "json web token", "解码jwt", "jwt解析器", "令牌解码器"], placeholder: "粘贴 JWT (header.payload.signature)…", header: "头部", payload: "载荷", signature: "签名", invalid: "不是有效的 JWT。" },
  ja: { title: "JWT デコーダー", short: "JSON Web Token をデコードしてヘッダーとペイロードを読み取ります。", description: "無料の JWT デコーダー。JSON Web Token を貼り付けると、デコードされたヘッダーとペイロードが整形 JSON として、署名とともに即座に表示されます。デコードはローカルで行われ、署名は検証されません。", keywords: ["jwt デコーダー", "json web token", "jwt デコード", "jwt パーサー", "トークンデコーダー"], placeholder: "JWT を貼り付け (header.payload.signature)…", header: "ヘッダー", payload: "ペイロード", signature: "署名", invalid: "有効な JWT ではありません。" },
  ko: { title: "JWT 디코더", short: "JSON Web Token을 디코딩하여 헤더와 페이로드를 읽습니다.", description: "무료 JWT 디코더. JSON Web Token을 붙여넣으면 디코딩된 헤더와 페이로드가 서식 있는 JSON으로, 서명과 함께 즉시 표시됩니다. 디코딩은 로컬에서 수행되며 서명은 검증되지 않습니다.", keywords: ["jwt 디코더", "json web token", "jwt 디코딩", "jwt 파서", "토큰 디코더"], placeholder: "JWT 붙여넣기 (header.payload.signature)…", header: "헤더", payload: "페이로드", signature: "서명", invalid: "유효한 JWT가 아닙니다." },
  hi: { title: "JWT डिकोडर", short: "JSON Web Token को डिकोड करके उसका हेडर और पेलोड पढ़ें।", description: "मुफ्त JWT डिकोडर। एक JSON Web Token पेस्ट करें और उसका डिकोड किया हेडर व पेलोड फॉर्मेटेड JSON के रूप में, हस्ताक्षर सहित तुरंत देखें। डिकोडिंग स्थानीय है; हस्ताक्षर सत्यापित नहीं होता।", keywords: ["jwt डिकोडर", "json web token", "jwt डिकोड", "jwt पार्सर", "टोकन डिकोडर"], placeholder: "एक JWT पेस्ट करें (header.payload.signature)…", header: "हेडर", payload: "पेलोड", signature: "हस्ताक्षर", invalid: "मान्य JWT नहीं है।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
