import type { CalculatorI18n } from "@/types/i18n";

const io = (d: string, e: string, p: string, tc: string, fu: string, cpd: string) => ({
  inputs: { distance: { label: d }, efficiency: { label: e }, fuelPrice: { label: p } },
  outputs: { totalCost: { label: tc }, fuelUsed: { label: fu }, costPerDistance: { label: cpd } },
});

const i18n: CalculatorI18n = {
  en: { title: "Fuel Cost Calculator", short: "Estimate the fuel cost of a trip from distance, economy and price.", description: "Free fuel cost calculator. Enter trip distance, fuel economy (litres per 100 km) and the price per litre to get total fuel cost, litres used and cost per kilometre.", keywords: ["fuel cost calculator", "trip cost calculator", "gas cost", "petrol cost", "fuel consumption cost"], ...io("Distance", "Fuel economy (L/100km)", "Fuel price (per litre)", "Total fuel cost", "Fuel used (litres)", "Cost per km"), faq: [{ q: "How is fuel cost calculated?", a: "Fuel used = distance ÷ 100 × L/100km; cost = fuel used × price per litre. A 500 km trip at 7 L/100km and $1.50/L costs about $52.50." }, { q: "What if I know km/L or mpg?", a: "Convert to L/100km first: L/100km = 100 ÷ (km/L). For US mpg, L/100km ≈ 235.21 ÷ mpg." }] },
  pt: { title: "Calculadora de Custo de Combustível", short: "Calcule o custo de combustível de uma viagem.", description: "Calculadora gratuita de custo de combustível. Calcule o custo de uma viagem com base na distância, consumo do veículo e preço do combustível.", keywords: ["custo combustível", "preço viagem", "consumo combustível", "calculadora viagem", "gasolina"], ...io("Distance", "Fuel economy (L/100km)", "Fuel price (per litre)", "Total fuel cost", "Fuel used (litres)", "Cost per km"), faq: [{ q: "How is fuel cost calculated?", a: "Fuel used = distance ÷ 100 × L/100km; cost = fuel used × price per litre. A 500 km trip at 7 L/100km and $1.50/L costs about $52.50." }, { q: "What if I know km/L or mpg?", a: "Convert to L/100km first: L/100km = 100 ÷ (km/L). For US mpg, L/100km ≈ 235.21 ÷ mpg." }] },
  id: { title: "Kalkulator Biaya Bahan Bakar", short: "Hitung biaya bahan bakar perjalanan Anda.", description: "Kalkulator biaya bahan bakar gratis. Hitung biaya perjalanan berdasarkan jarak, konsumsi kendaraan, dan harga bahan bakar.", keywords: ["biaya bahan bakar", "harga perjalanan", "konsumsi BBM", "kalkulator perjalanan", "bensin"], ...io("Distance", "Fuel economy (L/100km)", "Fuel price (per litre)", "Total fuel cost", "Fuel used (litres)", "Cost per km"), faq: [{ q: "How is fuel cost calculated?", a: "Fuel used = distance ÷ 100 × L/100km; cost = fuel used × price per litre. A 500 km trip at 7 L/100km and $1.50/L costs about $52.50." }, { q: "What if I know km/L or mpg?", a: "Convert to L/100km first: L/100km = 100 ÷ (km/L). For US mpg, L/100km ≈ 235.21 ÷ mpg." }] },

  tr: { title: "Yakıt Maliyeti Hesaplayıcı", short: "Mesafe, tüketim ve fiyattan bir yolculuğun yakıt maliyetini tahmin edin.", description: "Ücretsiz yakıt maliyeti hesaplayıcı. Yolculuk mesafesi, yakıt tüketimi (100 km'de litre) ve litre fiyatını girerek toplam yakıt maliyetini, kullanılan litreyi ve kilometre başına maliyeti öğrenin.", keywords: ["yakıt maliyeti hesaplama", "yolculuk maliyeti", "benzin maliyeti", "akaryakıt maliyeti", "yakıt tüketim maliyeti"], ...io("Mesafe", "Yakıt tüketimi (L/100km)", "Yakıt fiyatı (litre)", "Toplam yakıt maliyeti", "Kullanılan yakıt (litre)", "Km başına maliyet"), faq: [{ q: "Yakıt maliyeti nasıl hesaplanır?", a: "Kullanılan yakıt = mesafe ÷ 100 × L/100km; maliyet = kullanılan yakıt × litre fiyatı. 7 L/100km ve 1,50 ₺/L ile 500 km yolculuk yaklaşık 52,50 ₺'dir." }, { q: "km/L veya mpg biliyorsam?", a: "Önce L/100km'ye çevirin: L/100km = 100 ÷ (km/L). ABD mpg için L/100km ≈ 235,21 ÷ mpg." }] },
  de: { title: "Kraftstoffkosten-Rechner", short: "Schätzen Sie die Kraftstoffkosten einer Fahrt aus Distanz, Verbrauch und Preis.", description: "Kostenloser Kraftstoffkosten-Rechner. Geben Sie Fahrtdistanz, Verbrauch (Liter pro 100 km) und Preis pro Liter ein, um Gesamtkosten, verbrauchte Liter und Kosten pro Kilometer zu erhalten.", keywords: ["kraftstoffkosten rechner", "fahrtkosten rechner", "spritkosten", "benzinkosten", "verbrauchskosten"], ...io("Distanz", "Verbrauch (L/100km)", "Kraftstoffpreis (pro Liter)", "Gesamtkosten", "Verbrauch (Liter)", "Kosten pro km") },
  fr: { title: "Calculateur de Coût de Carburant", short: "Estimez le coût de carburant d'un trajet selon distance, consommation et prix.", description: "Calculateur de coût de carburant gratuit. Saisissez la distance, la consommation (litres aux 100 km) et le prix au litre pour obtenir le coût total, les litres consommés et le coût au kilomètre.", keywords: ["calculateur coût carburant", "coût de trajet", "coût essence", "coût carburant", "consommation coût"], ...io("Distance", "Consommation (L/100km)", "Prix du carburant (par litre)", "Coût total", "Carburant utilisé (litres)", "Coût par km") },
  es: { title: "Calculadora de Coste de Combustible", short: "Estima el coste de combustible de un viaje según distancia, consumo y precio.", description: "Calculadora de coste de combustible gratuita. Introduce la distancia, el consumo (litros por 100 km) y el precio por litro para obtener el coste total, los litros usados y el coste por kilómetro.", keywords: ["calculadora coste combustible", "coste de viaje", "coste gasolina", "coste de combustible", "consumo coste"], ...io("Distancia", "Consumo (L/100km)", "Precio del combustible (por litro)", "Coste total", "Combustible usado (litros)", "Coste por km") },
  it: { title: "Calcolatore Costo Carburante", short: "Stima il costo del carburante di un viaggio da distanza, consumo e prezzo.", description: "Calcolatore di costo carburante gratuito. Inserisci distanza, consumo (litri per 100 km) e prezzo al litro per ottenere il costo totale, i litri usati e il costo per chilometro.", keywords: ["calcolatore costo carburante", "costo viaggio", "costo benzina", "costo carburante", "consumo costo"], ...io("Distanza", "Consumo (L/100km)", "Prezzo carburante (al litro)", "Costo totale", "Carburante usato (litri)", "Costo per km") },
  ar: { title: "حاسبة تكلفة الوقود", short: "قدّر تكلفة وقود رحلة من المسافة والاستهلاك والسعر.", description: "حاسبة تكلفة وقود مجانية. أدخل مسافة الرحلة والاستهلاك (لتر لكل 100 كم) وسعر اللتر للحصول على إجمالي التكلفة واللترات المستخدمة والتكلفة لكل كيلومتر.", keywords: ["حاسبة تكلفة الوقود", "تكلفة الرحلة", "تكلفة البنزين", "تكلفة الوقود", "تكلفة الاستهلاك"], ...io("المسافة", "الاستهلاك (L/100km)", "سعر الوقود (لكل لتر)", "إجمالي التكلفة", "الوقود المستخدم (لتر)", "التكلفة لكل كم") },
  ru: { title: "Калькулятор Стоимости Топлива", short: "Оцените стоимость топлива поездки по расстоянию, расходу и цене.", description: "Бесплатный калькулятор стоимости топлива. Введите расстояние, расход (литров на 100 км) и цену за литр, чтобы получить общую стоимость, израсходованные литры и стоимость за километр.", keywords: ["калькулятор стоимости топлива", "стоимость поездки", "стоимость бензина", "стоимость топлива", "расход стоимость"], ...io("Расстояние", "Расход (L/100km)", "Цена топлива (за литр)", "Общая стоимость", "Израсходовано (литры)", "Стоимость за км") },
  zh: { title: "燃油费用计算器", short: "根据距离、油耗和价格估算一次行程的燃油费用。", description: "免费的燃油费用计算器。输入行程距离、油耗（每 100 公里升数）和每升价格，即可得到总燃油费用、用油量和每公里费用。", keywords: ["燃油费用计算器", "行程费用", "油费", "燃油成本", "油耗费用"], ...io("距离", "油耗 (L/100km)", "燃油价格（每升）", "总燃油费用", "用油量（升）", "每公里费用") },
  ja: { title: "燃料費計算機", short: "距離・燃費・価格から走行の燃料費を見積もります。", description: "無料の燃料費計算機。走行距離、燃費（100 km あたりリットル）、1 リットルの価格を入力すると、総燃料費、使用リットル、1 km あたりの費用が得られます。", keywords: ["燃料費 計算機", "走行費用", "ガソリン代", "燃料コスト", "燃費 費用"], ...io("距離", "燃費 (L/100km)", "燃料価格（1リットル）", "総燃料費", "使用燃料（リットル）", "1kmあたり費用") },
  ko: { title: "연료비 계산기", short: "거리, 연비, 가격으로 여행의 연료비를 추정합니다.", description: "무료 연료비 계산기. 주행 거리, 연비(100 km당 리터), 리터당 가격을 입력하면 총 연료비, 사용 리터, 킬로미터당 비용을 얻을 수 있습니다.", keywords: ["연료비 계산기", "여행 비용", "기름값", "연료 비용", "연비 비용"], ...io("거리", "연비 (L/100km)", "연료 가격(리터당)", "총 연료비", "사용 연료(리터)", "km당 비용") },
  hi: { title: "ईंधन लागत कैलकुलेटर", short: "दूरी, माइलेज और कीमत से किसी यात्रा की ईंधन लागत अनुमानित करें।", description: "मुफ्त ईंधन लागत कैलकुलेटर। यात्रा की दूरी, ईंधन खपत (प्रति 100 किमी लीटर) और प्रति लीटर कीमत दर्ज करें और कुल ईंधन लागत, उपयोग किए लीटर तथा प्रति किलोमीटर लागत पाएं।", keywords: ["ईंधन लागत कैलकुलेटर", "यात्रा लागत", "पेट्रोल लागत", "ईंधन खर्च", "खपत लागत"], ...io("दूरी", "ईंधन खपत (L/100km)", "ईंधन कीमत (प्रति लीटर)", "कुल ईंधन लागत", "उपयोग ईंधन (लीटर)", "प्रति किमी लागत") },
};

export default i18n;
