import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "URL Rewrite Generator", short: "Generate Apache and nginx rewrite rules from a pretty URL pattern.", description: "Free URL rewrite generator. Turn a clean URL pattern like /product/:id/:slug into Apache mod_rewrite and nginx rewrite rules with capture groups. Runs entirely in your browser.", keywords: ["url rewrite generator", "nginx rewrite", "apache rewriterule", "mod_rewrite generator", "pretty url rewrite"], pretty: "Pretty URL pattern", prettyPlaceholder: "/product/:id/:slug", target: "Internal target", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Enter both a pretty pattern and a target." },
  pt: { title: "URL Rewrite Generator", short: "Generate Apache e nginx rewrite rules a partir de a pretty URL pattern.", description: "Gratuito - url rewrite generator. Turn a clean URL pattern como /product/:id/:slug em Apache mod_rewrite e nginx rewrite rules com capture groups. Runs entirely no seu navegador.", keywords: ["url rewrite generator", "nginx rewrite", "apache rewriterule", "mod_rewrite generator", "pretty url rewrite"], pretty: "Padrão de URL amigável", prettyPlaceholder: "/product/:id/:slug", target: "Destino interno", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Informe um padrão amigável e um destino." },
  id: { title: "URL Rewrite Generator", short: "Generate Apache dan nginx rewrite rules dari a pretty URL pattern.", description: "Gratis - url rewrite generator. Turn a clean URL pattern seperti /product/:id/:slug menjadi Apache mod_rewrite dan nginx rewrite rules dengan capture groups. Runs entirely di browser Anda.", keywords: ["url rewrite generator", "nginx rewrite", "apache rewriterule", "mod_rewrite generator", "pretty url rewrite"], pretty: "Pola URL rapi", prettyPlaceholder: "/product/:id/:slug", target: "Target internal", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Masukkan pola rapi dan target." },

  tr: { title: "URL Yeniden Yazma Oluşturucu", short: "Temiz bir URL kalıbından Apache ve nginx yeniden yazma kuralları oluşturun.", description: "Ücretsiz URL yeniden yazma oluşturucu. /product/:id/:slug gibi temiz bir URL kalıbını yakalama gruplarıyla Apache mod_rewrite ve nginx yeniden yazma kurallarına dönüştürün. Tamamen tarayıcınızda çalışır.", keywords: ["url yeniden yazma oluşturucu", "nginx rewrite", "apache rewriterule", "mod_rewrite oluşturucu", "temiz url yeniden yazma"], pretty: "Temiz URL kalıbı", prettyPlaceholder: "/product/:id/:slug", target: "Dahili hedef", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Hem bir kalıp hem de bir hedef girin." },
  de: { title: "URL-Rewrite-Generator", short: "Erzeugen Sie Apache- und nginx-Rewrite-Regeln aus einem sauberen URL-Muster.", description: "Kostenloser URL-Rewrite-Generator. Wandeln Sie ein sauberes URL-Muster wie /product/:id/:slug in Apache-mod_rewrite- und nginx-Rewrite-Regeln mit Capture-Gruppen um. Läuft vollständig in Ihrem Browser.", keywords: ["url rewrite generator", "nginx rewrite", "apache rewriterule", "mod_rewrite generator", "saubere url umschreiben"], pretty: "Sauberes URL-Muster", prettyPlaceholder: "/product/:id/:slug", target: "Internes Ziel", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Geben Sie ein Muster und ein Ziel ein." },
  fr: { title: "Générateur de Réécriture d'URL", short: "Générez des règles de réécriture Apache et nginx à partir d'un motif d'URL propre.", description: "Générateur de réécriture d'URL gratuit. Transformez un motif d'URL propre comme /product/:id/:slug en règles de réécriture Apache mod_rewrite et nginx avec des groupes de capture. Fonctionne entièrement dans votre navigateur.", keywords: ["générateur de réécriture url", "réécriture nginx", "apache rewriterule", "générateur mod_rewrite", "réécriture url propre"], pretty: "Motif d'URL propre", prettyPlaceholder: "/product/:id/:slug", target: "Cible interne", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Saisissez un motif et une cible." },
  es: { title: "Generador de Reescritura de URL", short: "Genera reglas de reescritura de Apache y nginx desde un patrón de URL limpio.", description: "Generador de reescritura de URL gratuito. Convierte un patrón de URL limpio como /product/:id/:slug en reglas de reescritura de Apache mod_rewrite y nginx con grupos de captura. Funciona enteramente en tu navegador.", keywords: ["generador de reescritura url", "reescritura nginx", "apache rewriterule", "generador mod_rewrite", "reescritura url limpia"], pretty: "Patrón de URL limpio", prettyPlaceholder: "/product/:id/:slug", target: "Destino interno", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Introduce un patrón y un destino." },
  it: { title: "Generatore di Riscrittura URL", short: "Genera regole di riscrittura Apache e nginx da un pattern di URL pulito.", description: "Generatore di riscrittura URL gratuito. Trasforma un pattern di URL pulito come /product/:id/:slug in regole di riscrittura Apache mod_rewrite e nginx con gruppi di cattura. Funziona interamente nel tuo browser.", keywords: ["generatore riscrittura url", "riscrittura nginx", "apache rewriterule", "generatore mod_rewrite", "riscrittura url pulita"], pretty: "Pattern URL pulito", prettyPlaceholder: "/product/:id/:slug", target: "Destinazione interna", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Inserisci un pattern e una destinazione." },
  ar: { title: "مولّد إعادة كتابة الروابط", short: "أنشئ قواعد إعادة الكتابة لـ Apache وnginx من نمط رابط نظيف.", description: "مولّد إعادة كتابة روابط مجاني. حوّل نمط رابط نظيفًا مثل /product/:id/:slug إلى قواعد إعادة كتابة Apache mod_rewrite وnginx مع مجموعات الالتقاط. يعمل بالكامل في متصفحك.", keywords: ["مولد إعادة كتابة الروابط", "إعادة كتابة nginx", "apache rewriterule", "مولد mod_rewrite", "إعادة كتابة رابط نظيف"], pretty: "نمط الرابط النظيف", prettyPlaceholder: "/product/:id/:slug", target: "الهدف الداخلي", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "أدخل نمطًا وهدفًا." },
  ru: { title: "Генератор Перезаписи URL", short: "Создавайте правила перезаписи Apache и nginx из чистого шаблона URL.", description: "Бесплатный генератор перезаписи URL. Превратите чистый шаблон URL вроде /product/:id/:slug в правила перезаписи Apache mod_rewrite и nginx с группами захвата. Работает полностью в браузере.", keywords: ["генератор перезаписи url", "перезапись nginx", "apache rewriterule", "генератор mod_rewrite", "перезапись чистого url"], pretty: "Шаблон чистого URL", prettyPlaceholder: "/product/:id/:slug", target: "Внутренняя цель", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "Введите шаблон и цель." },
  zh: { title: "URL 重写规则生成器", short: "从简洁的 URL 模式生成 Apache 和 nginx 重写规则。", description: "免费的 URL 重写规则生成器。将像 /product/:id/:slug 这样的简洁 URL 模式转换为带捕获组的 Apache mod_rewrite 和 nginx 重写规则。完全在浏览器中运行。", keywords: ["url 重写生成器", "nginx 重写", "apache rewriterule", "mod_rewrite 生成器", "简洁 url 重写"], pretty: "简洁 URL 模式", prettyPlaceholder: "/product/:id/:slug", target: "内部目标", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "请输入模式和目标。" },
  ja: { title: "URL リライト生成ツール", short: "きれいな URL パターンから Apache と nginx のリライトルールを生成します。", description: "無料の URL リライト生成ツール。/product/:id/:slug のようなきれいな URL パターンを、キャプチャグループ付きの Apache mod_rewrite と nginx リライトルールに変換します。すべてブラウザ内で動作します。", keywords: ["url リライト生成", "nginx リライト", "apache rewriterule", "mod_rewrite 生成", "きれいな url リライト"], pretty: "きれいな URL パターン", prettyPlaceholder: "/product/:id/:slug", target: "内部ターゲット", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "パターンとターゲットを入力してください。" },
  ko: { title: "URL 재작성 생성기", short: "깔끔한 URL 패턴에서 Apache 및 nginx 재작성 규칙을 생성합니다.", description: "무료 URL 재작성 생성기. /product/:id/:slug 같은 깔끔한 URL 패턴을 캡처 그룹이 포함된 Apache mod_rewrite 및 nginx 재작성 규칙으로 변환합니다. 모두 브라우저에서 실행됩니다.", keywords: ["url 재작성 생성기", "nginx 재작성", "apache rewriterule", "mod_rewrite 생성기", "깔끔한 url 재작성"], pretty: "깔끔한 URL 패턴", prettyPlaceholder: "/product/:id/:slug", target: "내부 대상", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "패턴과 대상을 입력하세요." },
  hi: { title: "URL रीराइट जनरेटर", short: "साफ़ URL पैटर्न से Apache और nginx रीराइट नियम बनाएँ।", description: "मुफ्त URL रीराइट जनरेटर। /product/:id/:slug जैसे साफ़ URL पैटर्न को कैप्चर समूहों के साथ Apache mod_rewrite और nginx रीराइट नियमों में बदलें। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["url रीराइट जनरेटर", "nginx रीराइट", "apache rewriterule", "mod_rewrite जनरेटर", "साफ़ url रीराइट"], pretty: "साफ़ URL पैटर्न", prettyPlaceholder: "/product/:id/:slug", target: "आंतरिक लक्ष्य", targetPlaceholder: "product.php?id=$1&slug=$2", apache: "Apache (.htaccess)", nginx: "nginx", invalid: "एक पैटर्न और एक लक्ष्य दर्ज करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
