import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IPv6 Expand / Compress", short: "Expand or compress an IPv6 address into canonical form.", description: "Free IPv6 expand and compress tool. Paste a shorthand IPv6 to see its full 8-group form, or paste a fully padded address to get the shortest canonical form — all in your browser.", keywords: ["ipv6 expand", "ipv6 compress", "ipv6 normalize", "ipv6 shorten", "ipv6 full form"], input: "IPv6", expanded: "Expanded", compressed: "Compressed" },
  pt: { title: "IPv6 Expand / Compress", short: "Expand ou compress an IPv6 address into canonical form.", description: "Gratuito - IPv6 expand e compress tool. Paste a shorthand IPv6 para see its full 8-group form, ou paste a fully padded address para get the shortest canonical form â all no seu navegador.", keywords: ["ipv6 expand", "ipv6 compress", "ipv6 normalize", "ipv6 shorten", "ipv6 full form"], input: "IPv6", expanded: "Expanded", compressed: "Compressed" },
  id: { title: "IPv6 Expand / Compress", short: "Expand atau compress an IPv6 address into canonical form.", description: "Gratis - IPv6 expand dan compress tool. Paste a shorthand IPv6 to see its full 8-group form, atau paste a fully padded address to get the shortest canonical form â all di browser Anda.", keywords: ["ipv6 expand", "ipv6 compress", "ipv6 normalize", "ipv6 shorten", "ipv6 full form"], input: "IPv6", expanded: "Expanded", compressed: "Compressed" },

  tr: { title: "IPv6 Genişlet / Sıkıştır", short: "Bir IPv6 adresini standart biçimine genişletin veya sıkıştırın.", description: "Ücretsiz IPv6 genişletme ve sıkıştırma aracı. Kısaltılmış IPv6'yı yapıştırın ve tam 8 grup formunu görün veya tam doldurulmuş bir adresi yapıştırıp en kısa kanonik biçimi alın — hepsi tarayıcınızda.", keywords: ["ipv6 genişlet", "ipv6 sıkıştır", "ipv6 normalize", "ipv6 kısalt", "ipv6 tam form"], input: "IPv6", expanded: "Genişletilmiş", compressed: "Sıkıştırılmış" },
  de: { title: "IPv6 erweitern / komprimieren", short: "IPv6-Adresse in die kanonische Form erweitern oder komprimieren.", description: "Kostenloses IPv6-Tool zum Erweitern und Komprimieren. Fügen Sie eine kurze IPv6 ein, um die 8-Gruppen-Form zu sehen, oder eine voll gepolsterte Adresse, um die kürzeste kanonische Form zu erhalten — alles im Browser.", keywords: ["ipv6 erweitern", "ipv6 komprimieren", "ipv6 normalisieren", "ipv6 kürzen", "ipv6 vollform"], input: "IPv6", expanded: "Erweitert", compressed: "Komprimiert" },
  fr: { title: "Étendre / Compresser IPv6", short: "Étendez ou compressez une adresse IPv6 sous sa forme canonique.", description: "Outil gratuit pour étendre et compresser IPv6. Collez une IPv6 raccourcie pour voir sa forme complète à 8 groupes, ou une adresse entièrement complétée pour obtenir la forme canonique la plus courte — le tout dans votre navigateur.", keywords: ["étendre ipv6", "compresser ipv6", "normaliser ipv6", "raccourcir ipv6", "ipv6 forme complète"], input: "IPv6", expanded: "Étendu", compressed: "Compressé" },
  es: { title: "Expandir / Comprimir IPv6", short: "Expande o comprime una dirección IPv6 en su forma canónica.", description: "Herramienta gratuita para expandir y comprimir IPv6. Pega una IPv6 abreviada para ver su forma completa de 8 grupos, o una dirección totalmente rellenada para obtener la forma canónica más corta — todo en tu navegador.", keywords: ["expandir ipv6", "comprimir ipv6", "normalizar ipv6", "acortar ipv6", "ipv6 forma completa"], input: "IPv6", expanded: "Expandido", compressed: "Comprimido" },
  it: { title: "Espandi / Comprimi IPv6", short: "Espandi o comprimi un indirizzo IPv6 nella forma canonica.", description: "Strumento gratuito per espandere e comprimere IPv6. Incolla un IPv6 abbreviato per vedere la forma completa a 8 gruppi, o un indirizzo completamente padded per ottenere la forma canonica più corta — tutto nel browser.", keywords: ["espandi ipv6", "comprimi ipv6", "normalizza ipv6", "abbrevia ipv6", "ipv6 forma completa"], input: "IPv6", expanded: "Espanso", compressed: "Compresso" },
  ar: { title: "توسيع / ضغط IPv6", short: "وسّع أو اضغط عنوان IPv6 إلى صيغته القياسية.", description: "أداة مجانية لتوسيع وضغط IPv6. الصق IPv6 المختصر لرؤية صيغته الكاملة المكوّنة من 8 مجموعات، أو الصق عنوانًا ممتلئًا للحصول على أقصر صيغة قياسية — كل ذلك في متصفحك.", keywords: ["توسيع ipv6", "ضغط ipv6", "تطبيع ipv6", "اختصار ipv6", "ipv6 الصيغة الكاملة"], input: "IPv6", expanded: "الموسّع", compressed: "المضغوط" },
  ru: { title: "Расширение / Сжатие IPv6", short: "Расширьте или сожмите IPv6-адрес в каноническую форму.", description: "Бесплатный инструмент для расширения и сжатия IPv6. Вставьте сокращённый IPv6, чтобы увидеть полную 8-группную форму, или полностью дополненный адрес, чтобы получить кратчайшую каноническую форму — всё в браузере.", keywords: ["расширить ipv6", "сжать ipv6", "нормализовать ipv6", "сократить ipv6", "ipv6 полная форма"], input: "IPv6", expanded: "Развёрнутый", compressed: "Сжатый" },
  zh: { title: "IPv6 展开 / 压缩", short: "将 IPv6 地址展开或压缩为规范形式。", description: "免费的 IPv6 展开与压缩工具。粘贴简写 IPv6 查看完整的 8 组表示，或粘贴完全填充的地址获得最短规范形式——全部在浏览器中完成。", keywords: ["ipv6 展开", "ipv6 压缩", "ipv6 规范化", "ipv6 缩短", "ipv6 完整形式"], input: "IPv6", expanded: "展开", compressed: "压缩" },
  ja: { title: "IPv6 展開 / 圧縮", short: "IPv6 アドレスを正規形式に展開・圧縮。", description: "無料の IPv6 展開・圧縮ツール。省略形の IPv6 を貼り付けると完全な8グループ形式が表示され、完全にパディングされたアドレスを貼り付けると最短の正規形式が得られます——すべてブラウザ内で。", keywords: ["ipv6 展開", "ipv6 圧縮", "ipv6 正規化", "ipv6 短縮", "ipv6 完全形式"], input: "IPv6", expanded: "展開済み", compressed: "圧縮" },
  ko: { title: "IPv6 확장 / 압축", short: "IPv6 주소를 표준 형식으로 확장하거나 압축합니다.", description: "무료 IPv6 확장 및 압축 도구. 약식 IPv6를 붙여넣으면 전체 8그룹 형식을, 완전히 패딩된 주소를 붙여넣으면 가장 짧은 표준 형식을 얻습니다 — 모두 브라우저에서.", keywords: ["ipv6 확장", "ipv6 압축", "ipv6 정규화", "ipv6 축약", "ipv6 전체 형식"], input: "IPv6", expanded: "확장됨", compressed: "압축됨" },
  hi: { title: "IPv6 विस्तार / संपीड़न", short: "एक IPv6 पते को विहित रूप में विस्तारित या संपीड़ित करें।", description: "मुफ्त IPv6 विस्तार और संपीड़न उपकरण। संक्षिप्त IPv6 पेस्ट करें और इसका पूर्ण 8-समूह रूप देखें, या पूरी तरह से भरा हुआ पता पेस्ट करें और सबसे छोटा विहित रूप पाएं — सब आपके ब्राउज़र में।", keywords: ["ipv6 विस्तार", "ipv6 संपीड़न", "ipv6 सामान्यीकरण", "ipv6 छोटा करें", "ipv6 पूर्ण रूप"], input: "IPv6", expanded: "विस्तारित", compressed: "संपीड़ित" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
