import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "UUID Generator (v4)", short: "Generate random version-4 UUIDs in bulk, with formatting options.", description: "Free UUID/GUID generator. Create one or many cryptographically-random version-4 UUIDs, with options for uppercase and hyphen removal. Everything is generated locally with the Web Crypto API.", keywords: ["uuid generator", "guid generator", "uuid v4", "random uuid", "unique id generator"], count: "How many", uppercase: "Uppercase", hyphens: "Include hyphens", generate: "Generate" },
  tr: { title: "UUID Üretici (v4)", short: "Toplu olarak rastgele sürüm-4 UUID üretin, biçimlendirme seçenekleriyle.", description: "Ücretsiz UUID/GUID üretici. Bir veya birçok kriptografik rastgele sürüm-4 UUID oluşturun; büyük harf ve tire kaldırma seçenekleriyle. Her şey Web Crypto API ile yerel üretilir.", keywords: ["uuid üretici", "guid üretici", "uuid v4", "rastgele uuid", "benzersiz kimlik"], count: "Adet", uppercase: "Büyük harf", hyphens: "Tireleri ekle", generate: "Üret" },
  de: { title: "UUID-Generator (v4)", short: "Erzeugen Sie zufällige Version-4-UUIDs in großer Menge, mit Formatierungsoptionen.", description: "Kostenloser UUID/GUID-Generator. Erstellen Sie eine oder viele kryptografisch zufällige Version-4-UUIDs, mit Optionen für Großschreibung und Bindestrich-Entfernung. Alles lokal mit der Web Crypto API.", keywords: ["uuid generator", "guid generator", "uuid v4", "zufällige uuid", "eindeutige id"], count: "Anzahl", uppercase: "Großbuchstaben", hyphens: "Bindestriche einfügen", generate: "Erzeugen" },
  fr: { title: "Générateur d'UUID (v4)", short: "Générez des UUID version 4 aléatoires en masse, avec options de format.", description: "Générateur d'UUID/GUID gratuit. Créez un ou plusieurs UUID version 4 cryptographiquement aléatoires, avec options de majuscules et de suppression des tirets. Tout est généré localement via la Web Crypto API.", keywords: ["générateur uuid", "générateur guid", "uuid v4", "uuid aléatoire", "id unique"], count: "Combien", uppercase: "Majuscules", hyphens: "Inclure les tirets", generate: "Générer" },
  es: { title: "Generador de UUID (v4)", short: "Genera UUID versión 4 aleatorios en lote, con opciones de formato.", description: "Generador de UUID/GUID gratuito. Crea uno o varios UUID versión 4 criptográficamente aleatorios, con opciones de mayúsculas y eliminación de guiones. Todo se genera localmente con la Web Crypto API.", keywords: ["generador uuid", "generador guid", "uuid v4", "uuid aleatorio", "id único"], count: "Cuántos", uppercase: "Mayúsculas", hyphens: "Incluir guiones", generate: "Generar" },
  it: { title: "Generatore di UUID (v4)", short: "Genera UUID versione 4 casuali in blocco, con opzioni di formato.", description: "Generatore di UUID/GUID gratuito. Crea uno o molti UUID versione 4 crittograficamente casuali, con opzioni per maiuscolo e rimozione dei trattini. Tutto generato localmente con la Web Crypto API.", keywords: ["generatore uuid", "generatore guid", "uuid v4", "uuid casuale", "id univoco"], count: "Quanti", uppercase: "Maiuscolo", hyphens: "Includi trattini", generate: "Genera" },
  ar: { title: "مولّد UUID (v4)", short: "أنشئ معرّفات UUID عشوائية من الإصدار 4 بالجملة، مع خيارات التنسيق.", description: "مولّد UUID/GUID مجاني. أنشئ واحدًا أو عدة معرّفات UUID عشوائية تشفيريًا من الإصدار 4، مع خيارات الأحرف الكبيرة وإزالة الشرطات. كل شيء يُنشأ محليًا عبر Web Crypto API.", keywords: ["مولد uuid", "مولد guid", "uuid v4", "uuid عشوائي", "معرف فريد"], count: "العدد", uppercase: "أحرف كبيرة", hyphens: "تضمين الشرطات", generate: "توليد" },
  ru: { title: "Генератор UUID (v4)", short: "Генерируйте случайные UUID версии 4 пакетами, с опциями форматирования.", description: "Бесплатный генератор UUID/GUID. Создавайте один или много криптографически случайных UUID версии 4, с опциями верхнего регистра и удаления дефисов. Всё генерируется локально через Web Crypto API.", keywords: ["генератор uuid", "генератор guid", "uuid v4", "случайный uuid", "уникальный id"], count: "Количество", uppercase: "Верхний регистр", hyphens: "С дефисами", generate: "Сгенерировать" },
  zh: { title: "UUID 生成器 (v4)", short: "批量生成随机版本 4 UUID，并提供格式选项。", description: "免费的 UUID/GUID 生成器。生成一个或多个加密随机的版本 4 UUID，可选大写和去除连字符。一切都通过 Web Crypto API 在本地生成。", keywords: ["uuid生成器", "guid生成器", "uuid v4", "随机uuid", "唯一id"], count: "数量", uppercase: "大写", hyphens: "包含连字符", generate: "生成" },
  ja: { title: "UUID ジェネレーター (v4)", short: "ランダムなバージョン 4 UUID を一括生成。書式オプション付き。", description: "無料の UUID/GUID ジェネレーター。暗号学的にランダムなバージョン 4 UUID を 1 つまたは複数生成。大文字化やハイフン除去のオプションあり。すべて Web Crypto API でローカル生成されます。", keywords: ["uuid ジェネレーター", "guid ジェネレーター", "uuid v4", "ランダム uuid", "一意 id"], count: "個数", uppercase: "大文字", hyphens: "ハイフンを含める", generate: "生成" },
  ko: { title: "UUID 생성기 (v4)", short: "버전 4 랜덤 UUID를 대량 생성하며 형식 옵션을 제공합니다.", description: "무료 UUID/GUID 생성기. 암호학적으로 무작위인 버전 4 UUID를 하나 또는 여러 개 생성하며, 대문자 및 하이픈 제거 옵션을 제공합니다. 모든 것이 Web Crypto API로 로컬 생성됩니다.", keywords: ["uuid 생성기", "guid 생성기", "uuid v4", "랜덤 uuid", "고유 id"], count: "개수", uppercase: "대문자", hyphens: "하이픈 포함", generate: "생성" },
  hi: { title: "UUID जनरेटर (v4)", short: "फॉर्मेटिंग विकल्पों के साथ बल्क में रैंडम संस्करण-4 UUID बनाएं।", description: "मुफ्त UUID/GUID जनरेटर। एक या कई क्रिप्टोग्राफ़िक रूप से रैंडम संस्करण-4 UUID बनाएं, अपरकेस और हाइफन हटाने के विकल्पों के साथ। सब कुछ Web Crypto API से स्थानीय रूप से बनता है।", keywords: ["uuid जनरेटर", "guid जनरेटर", "uuid v4", "रैंडम uuid", "अद्वितीय id"], count: "कितने", uppercase: "अपरकेस", hyphens: "हाइफन शामिल करें", generate: "बनाएं" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
