import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: ".htaccess Redirect Generator", short: "Build an Apache .htaccess redirect block visually.", description: "Free .htaccess redirect generator. Add 301 (permanent) or 302 (temporary) redirect rules and copy a ready-to-deploy Apache mod_alias block.", keywords: ["htaccess redirect generator", "301 redirect", "302 redirect", "apache redirect", ".htaccess rules"], from: "From path", to: "To URL", status: "Status", add: "Add rule", remove: "Remove", output: "Output" },
  nl: { title: ".htaccess Redirect Generator", short: "Build an Apache .htaccess redirect block visually.", description: "Gratis .htaccess redirect generator. Add 301 (permanent) or 302 (temporary) redirect rules and copy a ready-to-deploy Apache mod_alias block.", keywords: ["htaccess redirect generator", "301 redirect", "302 redirect", "apache redirect", ".htaccess rules"], from: "From path", to: "To URL", status: "Status", add: "Add rule", remove: "Verwijder", output: "Output" },

  pl: { title: ".htaccess Redirect Generator", short: "Build an Apache .htaccess redirect block visually.", description: "Darmowy .htaccess redirect generator. Add 301 (permanent) or 302 (temporary) redirect rules and copy a ready-to-deploy Apache mod_alias block.", keywords: ["htaccess redirect generator", "301 redirect", "302 redirect", "apache redirect", ".htaccess rules"], from: "From path", to: "To URL", status: "Status", add: "Add rule", remove: "Usuń", output: "Output" },
  pt: { title: "Gerador de .htaccess Redirect", short: "Build an Apache .htaccess redirect block visually.", description: "Gratuito - .htaccess redirect generator. Add 301 (permanent) ou 302 (temporary) redirect rules e copy a ready-para-deploy Apache mod_alias block.", keywords: ["htaccess redirect generator", "301 redirect", "302 redirect", "apache redirect", ".htaccess rules"], from: "From path", to: "To URL", status: "Status", add: "Add rule", remove: "Remove", output: "Output" },
  id: { title: "Generator .htaccess Redirect", short: "Build an Apache .htaccess redirect block visually.", description: "Gratis - .htaccess redirect generator. Add 301 (permanent) atau 302 (temporary) redirect rules dan copy a ready-to-deploy Apache mod_alias block.", keywords: ["htaccess redirect generator", "301 redirect", "302 redirect", "apache redirect", ".htaccess rules"], from: "From path", to: "To URL", status: "Status", add: "Add rule", remove: "Remove", output: "Output" },

  tr: { title: ".htaccess Yönlendirme Oluşturucu", short: "Görsel olarak Apache .htaccess yönlendirme bloğu oluşturun.", description: "Ücretsiz .htaccess yönlendirme oluşturucu. 301 (kalıcı) veya 302 (geçici) yönlendirme kuralları ekleyin ve dağıtıma hazır bir Apache mod_alias bloğunu kopyalayın.", keywords: ["htaccess yönlendirme oluşturucu", "301 yönlendirme", "302 yönlendirme", "apache yönlendirme", ".htaccess kuralları"], from: "Kaynak yol", to: "Hedef URL", status: "Durum", add: "Kural ekle", remove: "Kaldır", output: "Çıktı" },
  de: { title: ".htaccess-Weiterleitungs-Generator", short: "Erstellen Sie einen Apache-.htaccess-Weiterleitungsblock visuell.", description: "Kostenloser .htaccess-Weiterleitungs-Generator. Fügen Sie 301- (permanent) oder 302- (temporär) Weiterleitungsregeln hinzu und kopieren Sie einen einsatzbereiten Apache-mod_alias-Block.", keywords: ["htaccess weiterleitungs generator", "301 weiterleitung", "302 weiterleitung", "apache weiterleitung", ".htaccess regeln"], from: "Quellpfad", to: "Ziel-URL", status: "Status", add: "Regel hinzufügen", remove: "Entfernen", output: "Ausgabe" },
  fr: { title: "Générateur de Redirections .htaccess", short: "Construisez visuellement un bloc de redirections Apache .htaccess.", description: "Générateur de redirections .htaccess gratuit. Ajoutez des règles de redirection 301 (permanente) ou 302 (temporaire) et copiez un bloc Apache mod_alias prêt à déployer.", keywords: ["générateur redirections htaccess", "redirection 301", "redirection 302", "redirection apache", "règles .htaccess"], from: "Chemin source", to: "URL cible", status: "Statut", add: "Ajouter une règle", remove: "Supprimer", output: "Sortie" },
  es: { title: "Generador de Redirecciones .htaccess", short: "Construye visualmente un bloque de redirecciones Apache .htaccess.", description: "Generador de redirecciones .htaccess gratuito. Añade reglas de redirección 301 (permanente) o 302 (temporal) y copia un bloque Apache mod_alias listo para implementar.", keywords: ["generador redirecciones htaccess", "redirección 301", "redirección 302", "redirección apache", "reglas .htaccess"], from: "Ruta origen", to: "URL destino", status: "Estado", add: "Añadir regla", remove: "Eliminar", output: "Salida" },
  it: { title: "Generatore di Redirect .htaccess", short: "Crea visivamente un blocco di redirect Apache .htaccess.", description: "Generatore di redirect .htaccess gratuito. Aggiungi regole di redirect 301 (permanente) o 302 (temporaneo) e copia un blocco Apache mod_alias pronto per il deploy.", keywords: ["generatore redirect htaccess", "redirect 301", "redirect 302", "redirect apache", "regole .htaccess"], from: "Percorso origine", to: "URL destinazione", status: "Stato", add: "Aggiungi regola", remove: "Rimuovi", output: "Output" },
  ar: { title: "مولّد إعادة توجيه .htaccess", short: "أنشئ كتلة إعادة توجيه Apache .htaccess بصريًا.", description: "مولّد إعادة توجيه .htaccess مجاني. أضف قواعد إعادة توجيه 301 (دائمة) أو 302 (مؤقتة) وانسخ كتلة Apache mod_alias جاهزة للنشر.", keywords: ["مولد إعادة توجيه htaccess", "إعادة توجيه 301", "إعادة توجيه 302", "إعادة توجيه apache", "قواعد .htaccess"], from: "المسار المصدر", to: "عنوان URL الهدف", status: "الحالة", add: "إضافة قاعدة", remove: "إزالة", output: "الإخراج" },
  ru: { title: "Генератор редиректов .htaccess", short: "Создайте блок редиректов Apache .htaccess визуально.", description: "Бесплатный генератор редиректов .htaccess. Добавляйте правила 301 (постоянных) или 302 (временных) редиректов и копируйте готовый к развёртыванию блок Apache mod_alias.", keywords: ["генератор редиректов htaccess", "редирект 301", "редирект 302", "редирект apache", "правила .htaccess"], from: "Исходный путь", to: "Целевой URL", status: "Статус", add: "Добавить правило", remove: "Удалить", output: "Вывод" },
  zh: { title: ".htaccess 重定向生成器", short: "可视化构建 Apache .htaccess 重定向块。", description: "免费的 .htaccess 重定向生成器。添加 301（永久）或 302（临时）重定向规则，并复制可直接部署的 Apache mod_alias 块。", keywords: ["htaccess 重定向生成器", "301 重定向", "302 重定向", "apache 重定向", ".htaccess 规则"], from: "源路径", to: "目标 URL", status: "状态", add: "添加规则", remove: "移除", output: "输出" },
  ja: { title: ".htaccess リダイレクト生成", short: "Apache .htaccess リダイレクトブロックを視覚的に構築。", description: "無料の .htaccess リダイレクト生成ツール。301（永続）または 302（一時）リダイレクトルールを追加し、デプロイ可能な Apache mod_alias ブロックをコピー。", keywords: ["htaccess リダイレクト 生成", "301 リダイレクト", "302 リダイレクト", "apache リダイレクト", ".htaccess ルール"], from: "ソースパス", to: "ターゲット URL", status: "ステータス", add: "ルールを追加", remove: "削除", output: "出力" },
  ko: { title: ".htaccess 리디렉션 생성기", short: "Apache .htaccess 리디렉션 블록을 시각적으로 만듭니다.", description: "무료 .htaccess 리디렉션 생성기. 301(영구) 또는 302(임시) 리디렉션 규칙을 추가하고 배포 준비된 Apache mod_alias 블록을 복사하세요.", keywords: ["htaccess 리디렉션 생성기", "301 리디렉션", "302 리디렉션", "apache 리디렉션", ".htaccess 규칙"], from: "출발 경로", to: "대상 URL", status: "상태", add: "규칙 추가", remove: "제거", output: "출력" },
  hi: { title: ".htaccess रीडायरेक्ट जनरेटर", short: "Apache .htaccess रीडायरेक्ट ब्लॉक को विज़ुअली बनाएं।", description: "मुफ्त .htaccess रीडायरेक्ट जनरेटर। 301 (स्थायी) या 302 (अस्थायी) रीडायरेक्ट नियम जोड़ें और तैनाती के लिए तैयार Apache mod_alias ब्लॉक कॉपी करें।", keywords: ["htaccess रीडायरेक्ट जनरेटर", "301 रीडायरेक्ट", "302 रीडायरेक्ट", "apache रीडायरेक्ट", ".htaccess नियम"], from: "स्रोत पथ", to: "लक्ष्य URL", status: "स्थिति", add: "नियम जोड़ें", remove: "हटाएं", output: "आउटपुट" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
