import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Glassmorphism CSS Generator", short: "Frosted-glass backdrop-filter CSS with a live preview.", description: "Free glassmorphism CSS generator. Adjust blur, transparency, saturation, border radius and border opacity to build a frosted-glass card — backdrop-filter is used, so the effect needs a colourful background behind it.", keywords: ["glassmorphism generator", "frosted glass css", "backdrop filter generator", "glass effect css", "glassmorphism css"], blur: "Blur", transparency: "Transparency", saturation: "Saturation (%)", radius: "Border radius", borderOpacity: "Border opacity", preview: "Preview" },
  tr: { title: "Glassmorphism CSS Oluşturucu", short: "Canlı önizlemeyle buzlu cam backdrop-filter CSS.", description: "Ücretsiz glassmorphism CSS oluşturucu. Bulanıklık, şeffaflık, doygunluk, kenar yarıçapı ve kenar opaklığını ayarlayarak buzlu cam kart oluşturun — backdrop-filter kullanılır, bu yüzden efekt için arkasında renkli bir arka plan gerekir.", keywords: ["glassmorphism oluşturucu", "buzlu cam css", "backdrop filter oluşturucu", "cam efekt css", "glassmorphism css"], blur: "Bulanıklık", transparency: "Şeffaflık", saturation: "Doygunluk (%)", radius: "Kenar yarıçapı", borderOpacity: "Kenar opaklığı", preview: "Önizleme" },
  de: { title: "Glassmorphism-CSS-Generator", short: "Frosted-Glass-Backdrop-Filter-CSS mit Live-Vorschau.", description: "Kostenloser Glassmorphism-CSS-Generator. Passen Sie Unschärfe, Transparenz, Sättigung, Border-Radius und Border-Opazität an, um eine Frosted-Glass-Karte zu erstellen — backdrop-filter wird verwendet, also benötigt der Effekt einen farbigen Hintergrund.", keywords: ["glassmorphism generator", "frosted glass css", "backdrop filter generator", "glass effect css", "glassmorphism css"], blur: "Unschärfe", transparency: "Transparenz", saturation: "Sättigung (%)", radius: "Border-Radius", borderOpacity: "Border-Opazität", preview: "Vorschau" },
  fr: { title: "Générateur CSS Glassmorphism", short: "CSS backdrop-filter verre dépoli avec aperçu en direct.", description: "Générateur CSS glassmorphism gratuit. Ajustez flou, transparence, saturation, rayon de bordure et opacité de bordure pour construire une carte en verre dépoli — backdrop-filter est utilisé, donc l'effet nécessite un fond coloré derrière.", keywords: ["générateur glassmorphism", "verre dépoli css", "générateur backdrop filter", "effet verre css", "glassmorphism css"], blur: "Flou", transparency: "Transparence", saturation: "Saturation (%)", radius: "Rayon de bordure", borderOpacity: "Opacité bordure", preview: "Aperçu" },
  es: { title: "Generador CSS Glassmorphism", short: "CSS backdrop-filter de vidrio esmerilado con vista previa en vivo.", description: "Generador CSS glassmorphism gratuito. Ajusta desenfoque, transparencia, saturación, radio de borde y opacidad de borde para construir una tarjeta de vidrio esmerilado — se usa backdrop-filter, así que el efecto necesita un fondo colorido detrás.", keywords: ["generador glassmorphism", "vidrio esmerilado css", "generador backdrop filter", "efecto vidrio css", "glassmorphism css"], blur: "Desenfoque", transparency: "Transparencia", saturation: "Saturación (%)", radius: "Radio borde", borderOpacity: "Opacidad borde", preview: "Vista previa" },
  it: { title: "Generatore CSS Glassmorphism", short: "CSS backdrop-filter vetro smerigliato con anteprima dal vivo.", description: "Generatore CSS glassmorphism gratuito. Regola sfocatura, trasparenza, saturazione, raggio bordo e opacità bordo per costruire una carta di vetro smerigliato — backdrop-filter è usato, quindi l'effetto richiede uno sfondo colorato dietro.", keywords: ["generatore glassmorphism", "vetro smerigliato css", "generatore backdrop filter", "effetto vetro css", "glassmorphism css"], blur: "Sfocatura", transparency: "Trasparenza", saturation: "Saturazione (%)", radius: "Raggio bordo", borderOpacity: "Opacità bordo", preview: "Anteprima" },
  ar: { title: "مولّد Glassmorphism CSS", short: "CSS backdrop-filter زجاج محبب مع معاينة حية.", description: "مولّد glassmorphism CSS مجاني. اضبط التمويه والشفافية والتشبع ونصف قطر الحدود وعتامة الحدود لبناء بطاقة زجاج محبب — يتم استخدام backdrop-filter، لذا يحتاج التأثير إلى خلفية ملوّنة وراءه.", keywords: ["مولد glassmorphism", "زجاج محبب css", "مولد backdrop filter", "تأثير الزجاج css", "glassmorphism css"], blur: "التمويه", transparency: "الشفافية", saturation: "التشبع (%)", radius: "نصف قطر الحدود", borderOpacity: "عتامة الحدود", preview: "معاينة" },
  ru: { title: "Генератор Glassmorphism CSS", short: "CSS backdrop-filter матового стекла с живым превью.", description: "Бесплатный генератор glassmorphism CSS. Настройте размытие, прозрачность, насыщенность, радиус и непрозрачность границы, чтобы построить карточку из матового стекла — используется backdrop-filter, поэтому эффект требует цветного фона позади.", keywords: ["генератор glassmorphism", "матовое стекло css", "генератор backdrop filter", "эффект стекла css", "glassmorphism css"], blur: "Размытие", transparency: "Прозрачность", saturation: "Насыщенность (%)", radius: "Радиус границы", borderOpacity: "Непрозрачность границы", preview: "Превью" },
  zh: { title: "Glassmorphism CSS 生成器", short: "带实时预览的磨砂玻璃 backdrop-filter CSS。", description: "免费的 glassmorphism CSS 生成器。调整模糊、透明度、饱和度、边框半径和边框不透明度来构建磨砂玻璃卡片——使用 backdrop-filter，因此效果需要彩色背景在其后。", keywords: ["glassmorphism 生成器", "磨砂玻璃 css", "backdrop filter 生成器", "玻璃效果 css", "glassmorphism css"], blur: "模糊", transparency: "透明度", saturation: "饱和度 (%)", radius: "边框半径", borderOpacity: "边框不透明度", preview: "预览" },
  ja: { title: "Glassmorphism CSS ジェネレーター", short: "ライブプレビュー付きの曇りガラス backdrop-filter CSS。", description: "無料の glassmorphism CSS ジェネレーター。ぼかし、透明度、彩度、ボーダー半径、ボーダー不透明度を調整して曇りガラスカードを構築——backdrop-filter を使うので、背景にカラフルな要素が必要です。", keywords: ["glassmorphism ジェネレーター", "曇りガラス css", "backdrop filter ジェネレーター", "ガラス効果 css", "glassmorphism css"], blur: "ぼかし", transparency: "透明度", saturation: "彩度 (%)", radius: "ボーダー半径", borderOpacity: "ボーダー不透明度", preview: "プレビュー" },
  ko: { title: "Glassmorphism CSS 생성기", short: "실시간 미리보기로 서리 유리 backdrop-filter CSS.", description: "무료 glassmorphism CSS 생성기. 흐림, 투명도, 채도, 테두리 반경, 테두리 불투명도를 조정해 서리 유리 카드를 만드세요 — backdrop-filter를 사용하므로 효과에는 뒤에 컬러풀한 배경이 필요합니다.", keywords: ["glassmorphism 생성기", "서리 유리 css", "backdrop filter 생성기", "유리 효과 css", "glassmorphism css"], blur: "흐림", transparency: "투명도", saturation: "채도 (%)", radius: "테두리 반경", borderOpacity: "테두리 불투명도", preview: "미리보기" },
  hi: { title: "Glassmorphism CSS जनरेटर", short: "लाइव प्रीव्यू के साथ फ्रॉस्टेड-ग्लास backdrop-filter CSS।", description: "मुफ्त glassmorphism CSS जनरेटर। ब्लर, पारदर्शिता, संतृप्ति, बॉर्डर रेडियस और बॉर्डर अपारदर्शिता समायोजित करें ताकि फ्रॉस्टेड-ग्लास कार्ड बने — backdrop-filter का उपयोग होता है, इसलिए प्रभाव के लिए पीछे रंगीन पृष्ठभूमि चाहिए।", keywords: ["glassmorphism जनरेटर", "फ्रॉस्टेड ग्लास css", "backdrop filter जनरेटर", "ग्लास इफेक्ट css", "glassmorphism css"], blur: "ब्लर", transparency: "पारदर्शिता", saturation: "संतृप्ति (%)", radius: "बॉर्डर रेडियस", borderOpacity: "बॉर्डर अपारदर्शिता", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
