import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Pantone Converter", short: "Find the closest Pantone PMS color from a HEX, RGB, CMYK or HSV value.", description: "Free Pantone converter. Enter a HEX, RGB, CMYK or HSV color to find the closest approximate Pantone PMS Coated match, with side-by-side swatches and the Pantone code. Approximation for screen use only — verify with a physical guide.", keywords: ["pantone converter", "hex to pantone", "rgb to pantone", "cmyk to pantone", "pantone color finder"], inputColor: "Input color", nearest: "Nearest Pantone", code: "Pantone code", distance: "Distance", approxNote: "Approximate match for screen use only. Pantone is a proprietary system — confirm with a physical Pantone guide for print.", invalid: "Enter a valid color value for the selected mode." },
  pt: { title: "Conversor Pantone", short: "Encontre a cor Pantone PMS mais próxima a partir de um valor HEX, RGB, CMYK ou HSV.", description: "Conversor Pantone gratuito. Insira uma cor HEX, RGB, CMYK ou HSV para encontrar a correspondência Pantone PMS Coated aproximada mais próxima, com amostras lado a lado e o código Pantone. Aproximação apenas para tela — verifique com um guia físico.", keywords: ["pantone converter", "hex to pantone", "rgb to pantone", "cmyk to pantone", "pantone color finder"], inputColor: "Cor de entrada", nearest: "Pantone mais próximo", code: "Código Pantone", distance: "Distância", approxNote: "Correspondência aproximada apenas para tela. Pantone é um sistema proprietário — confirme com um guia Pantone físico para impressão.", invalid: "Insira um valor de cor válido para o modo selecionado." },
  id: { title: "Konverter Pantone", short: "Temukan warna Pantone PMS terdekat dari nilai HEX, RGB, CMYK, atau HSV.", description: "Konverter Pantone gratis. Masukkan warna HEX, RGB, CMYK, atau HSV untuk menemukan kecocokan Pantone PMS Coated perkiraan terdekat, dengan sampel berdampingan dan kode Pantone. Perkiraan hanya untuk layar — verifikasi dengan panduan fisik.", keywords: ["pantone converter", "hex to pantone", "rgb to pantone", "cmyk to pantone", "pantone color finder"], inputColor: "Warna input", nearest: "Pantone terdekat", code: "Kode Pantone", distance: "Jarak", approxNote: "Kecocokan perkiraan hanya untuk layar. Pantone adalah sistem berpemilik — konfirmasikan dengan panduan Pantone fisik untuk cetak.", invalid: "Masukkan nilai warna yang valid untuk mode yang dipilih." },

  tr: { title: "Pantone Dönüştürücü", short: "Bir HEX, RGB, CMYK veya HSV değerinden en yakın Pantone PMS rengini bulun.", description: "Ücretsiz Pantone dönüştürücü. En yakın yaklaşık Pantone PMS Coated eşleşmesini bulmak için bir HEX, RGB, CMYK veya HSV rengi girin; yan yana örnekler ve Pantone kodu ile. Yalnızca ekran için yaklaşımdır — fiziksel kılavuzla doğrulayın.", keywords: ["pantone dönüştürücü", "hex'ten pantone'a", "rgb'den pantone'a", "cmyk'ten pantone'a", "pantone renk bulucu"], inputColor: "Giriş rengi", nearest: "En yakın Pantone", code: "Pantone kodu", distance: "Mesafe", approxNote: "Yalnızca ekran kullanımı için yaklaşık eşleşme. Pantone tescilli bir sistemdir — baskı için fiziksel bir Pantone kılavuzuyla doğrulayın.", invalid: "Seçilen mod için geçerli bir renk değeri girin." },
  de: { title: "Pantone-Konverter", short: "Finden Sie die nächste Pantone-PMS-Farbe aus einem HEX-, RGB-, CMYK- oder HSV-Wert.", description: "Kostenloser Pantone-Konverter. Geben Sie eine HEX-, RGB-, CMYK- oder HSV-Farbe ein, um die nächste ungefähre Pantone-PMS-Coated-Übereinstimmung zu finden, mit nebeneinanderliegenden Mustern und dem Pantone-Code. Nur Näherung für den Bildschirm — mit einem physischen Fächer prüfen.", keywords: ["pantone konverter", "hex zu pantone", "rgb zu pantone", "cmyk zu pantone", "pantone farbfinder"], inputColor: "Eingabefarbe", nearest: "Nächstes Pantone", code: "Pantone-Code", distance: "Abstand", approxNote: "Ungefähre Übereinstimmung nur für den Bildschirm. Pantone ist ein proprietäres System — für den Druck mit einem physischen Pantone-Fächer bestätigen.", invalid: "Geben Sie einen gültigen Farbwert für den gewählten Modus ein." },
  fr: { title: "Convertisseur Pantone", short: "Trouvez la couleur Pantone PMS la plus proche à partir d'une valeur HEX, RGB, CMJN ou TSV.", description: "Convertisseur Pantone gratuit. Saisissez une couleur HEX, RGB, CMJN ou TSV pour trouver la correspondance Pantone PMS Coated approximative la plus proche, avec des échantillons côte à côte et le code Pantone. Approximation pour écran uniquement — vérifiez avec un nuancier physique.", keywords: ["convertisseur pantone", "hex vers pantone", "rgb vers pantone", "cmjn vers pantone", "trouveur de couleur pantone"], inputColor: "Couleur saisie", nearest: "Pantone le plus proche", code: "Code Pantone", distance: "Distance", approxNote: "Correspondance approximative pour écran uniquement. Pantone est un système propriétaire — confirmez avec un nuancier Pantone physique pour l'impression.", invalid: "Saisissez une valeur de couleur valide pour le mode sélectionné." },
  es: { title: "Conversor Pantone", short: "Encuentra el color Pantone PMS más cercano a partir de un valor HEX, RGB, CMYK o HSV.", description: "Conversor Pantone gratuito. Introduce un color HEX, RGB, CMYK o HSV para encontrar la coincidencia Pantone PMS Coated aproximada más cercana, con muestras lado a lado y el código Pantone. Aproximación solo para pantalla — verifica con una guía física.", keywords: ["conversor pantone", "hex a pantone", "rgb a pantone", "cmyk a pantone", "buscador de color pantone"], inputColor: "Color de entrada", nearest: "Pantone más cercano", code: "Código Pantone", distance: "Distancia", approxNote: "Coincidencia aproximada solo para pantalla. Pantone es un sistema propietario — confirma con una guía Pantone física para impresión.", invalid: "Introduce un valor de color válido para el modo seleccionado." },
  it: { title: "Convertitore Pantone", short: "Trova il colore Pantone PMS più vicino da un valore HEX, RGB, CMYK o HSV.", description: "Convertitore Pantone gratuito. Inserisci un colore HEX, RGB, CMYK o HSV per trovare la corrispondenza Pantone PMS Coated approssimativa più vicina, con campioni affiancati e il codice Pantone. Approssimazione solo per schermo — verifica con una guida fisica.", keywords: ["convertitore pantone", "hex in pantone", "rgb in pantone", "cmyk in pantone", "cerca colore pantone"], inputColor: "Colore di input", nearest: "Pantone più vicino", code: "Codice Pantone", distance: "Distanza", approxNote: "Corrispondenza approssimativa solo per schermo. Pantone è un sistema proprietario — conferma con una guida Pantone fisica per la stampa.", invalid: "Inserisci un valore di colore valido per la modalità selezionata." },
  ar: { title: "محوّل بانتون", short: "اعثر على أقرب لون Pantone PMS من قيمة HEX أو RGB أو CMYK أو HSV.", description: "محوّل بانتون مجاني. أدخل لون HEX أو RGB أو CMYK أو HSV للعثور على أقرب تطابق تقريبي لـ Pantone PMS Coated، مع عينات جنبًا إلى جنب ورمز بانتون. تقريب للشاشة فقط — تحقّق بدليل بانتون مادي.", keywords: ["محول بانتون", "hex إلى بانتون", "rgb إلى بانتون", "cmyk إلى بانتون", "باحث لون بانتون"], inputColor: "لون الإدخال", nearest: "أقرب بانتون", code: "رمز بانتون", distance: "المسافة", approxNote: "تطابق تقريبي للشاشة فقط. بانتون نظام مملوك — تأكّد بدليل بانتون مادي للطباعة.", invalid: "أدخل قيمة لون صالحة للوضع المحدد." },
  ru: { title: "Конвертер Pantone", short: "Найдите ближайший цвет Pantone PMS по значению HEX, RGB, CMYK или HSV.", description: "Бесплатный конвертер Pantone. Введите цвет HEX, RGB, CMYK или HSV, чтобы найти ближайшее приблизительное соответствие Pantone PMS Coated с образцами рядом и кодом Pantone. Приближение только для экрана — сверяйтесь с физическим веером.", keywords: ["конвертер pantone", "hex в pantone", "rgb в pantone", "cmyk в pantone", "поиск цвета pantone"], inputColor: "Введённый цвет", nearest: "Ближайший Pantone", code: "Код Pantone", distance: "Расстояние", approxNote: "Приблизительное совпадение только для экрана. Pantone — проприетарная система; для печати сверяйтесь с физическим веером Pantone.", invalid: "Введите корректное значение цвета для выбранного режима." },
  zh: { title: "Pantone 转换器", short: "根据 HEX、RGB、CMYK 或 HSV 值查找最接近的 Pantone PMS 颜色。", description: "免费的 Pantone 转换器。输入 HEX、RGB、CMYK 或 HSV 颜色，查找最接近的近似 Pantone PMS Coated 匹配色，并排显示色样和 Pantone 编号。仅供屏幕参考的近似值——请用实体色卡核对。", keywords: ["pantone 转换器", "hex 转 pantone", "rgb 转 pantone", "cmyk 转 pantone", "pantone 颜色查找"], inputColor: "输入颜色", nearest: "最接近的 Pantone", code: "Pantone 编号", distance: "距离", approxNote: "仅供屏幕使用的近似匹配。Pantone 是专有系统——印刷请用实体 Pantone 色卡确认。", invalid: "请为所选模式输入有效的颜色值。" },
  ja: { title: "Pantone 変換ツール", short: "HEX・RGB・CMYK・HSV 値から最も近い Pantone PMS カラーを探します。", description: "無料の Pantone 変換ツール。HEX・RGB・CMYK・HSV のカラーを入力すると、最も近い近似 Pantone PMS Coated を見つけ、並べたスウォッチと Pantone 番号を表示します。画面表示用の近似値です — 印刷は実物の色見本で確認してください。", keywords: ["pantone 変換", "hex から pantone", "rgb から pantone", "cmyk から pantone", "pantone カラー検索"], inputColor: "入力カラー", nearest: "最も近い Pantone", code: "Pantone 番号", distance: "距離", approxNote: "画面用の近似一致です。Pantone は独自規格のため、印刷では実物の Pantone 見本で確認してください。", invalid: "選択したモードに有効なカラー値を入力してください。" },
  ko: { title: "Pantone 변환기", short: "HEX, RGB, CMYK, HSV 값에서 가장 가까운 Pantone PMS 색상을 찾습니다.", description: "무료 Pantone 변환기. HEX, RGB, CMYK 또는 HSV 색상을 입력하면 가장 가까운 근사 Pantone PMS Coated 매치를 찾아 나란히 놓인 견본과 Pantone 코드를 보여줍니다. 화면용 근사치이므로 실물 가이드로 확인하세요.", keywords: ["pantone 변환기", "hex를 pantone으로", "rgb를 pantone으로", "cmyk를 pantone으로", "pantone 색상 찾기"], inputColor: "입력 색상", nearest: "가장 가까운 Pantone", code: "Pantone 코드", distance: "거리", approxNote: "화면용 근사 매치입니다. Pantone은 독점 시스템이므로 인쇄 시 실물 Pantone 가이드로 확인하세요.", invalid: "선택한 모드에 유효한 색상 값을 입력하세요." },
  hi: { title: "Pantone कन्वर्टर", short: "HEX, RGB, CMYK या HSV मान से निकटतम Pantone PMS रंग खोजें।", description: "मुफ्त Pantone कन्वर्टर। निकटतम अनुमानित Pantone PMS Coated मिलान खोजने के लिए HEX, RGB, CMYK या HSV रंग दर्ज करें, साथ-साथ स्वैच और Pantone कोड के साथ। केवल स्क्रीन उपयोग के लिए अनुमान — भौतिक गाइड से सत्यापित करें।", keywords: ["pantone कन्वर्टर", "hex से pantone", "rgb से pantone", "cmyk से pantone", "pantone रंग खोजक"], inputColor: "इनपुट रंग", nearest: "निकटतम Pantone", code: "Pantone कोड", distance: "दूरी", approxNote: "केवल स्क्रीन उपयोग के लिए अनुमानित मिलान। Pantone एक स्वामित्व प्रणाली है — प्रिंट के लिए भौतिक Pantone गाइड से पुष्टि करें।", invalid: "चयनित मोड के लिए मान्य रंग मान दर्ज करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
