import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "robots.txt Generator", short: "Build a robots.txt file with crawl rules and sitemaps.", description: "Free robots.txt generator. Add User-agent groups with Allow / Disallow patterns, an optional Crawl-delay, and Sitemap URLs to assemble a clean robots.txt — all in your browser.", keywords: ["robots.txt generator", "robots txt", "crawler rules", "sitemap declaration", "seo robots"], group: "Group", userAgent: "User-agent", allow: "Allow paths (one per line)", disallow: "Disallow paths (one per line)", crawlDelay: "Crawl-delay (seconds)", addGroup: "Add group", removeGroup: "Remove", sitemaps: "Sitemap URLs (one per line)", output: "robots.txt" },
  pt: { title: "Gerador de robots.txt", short: "Build a robots.txt file com crawl rules e sitemaps.", description: "Gratuito - robots.txt generator. Add User-agent groups com Allow / Disallow patterns, an optional Crawl-delay, e Sitemap URLs para assemble a clean robots.txt â all no seu navegador.", keywords: ["robots.txt generator", "robots txt", "crawler rules", "sitemap declaration", "seo robots"], group: "Group", userAgent: "User-agent", allow: "Allow paths (one per line)", disallow: "Disallow paths (one per line)", crawlDelay: "Crawl-delay (seconds)", addGroup: "Add group", removeGroup: "Remove", sitemaps: "Sitemap URLs (one per line)", output: "robots.txt" },
  id: { title: "Generator robots.txt", short: "Build a robots.txt file with crawl rules dan sitemaps.", description: "Gratis - robots.txt generator. Add User-agent groups with Allow / Disallow patterns, an optional Crawl-delay, dan Sitemap URLs to assemble a clean robots.txt â all di browser Anda.", keywords: ["robots.txt generator", "robots txt", "crawler rules", "sitemap declaration", "seo robots"], group: "Group", userAgent: "User-agent", allow: "Allow paths (one per line)", disallow: "Disallow paths (one per line)", crawlDelay: "Crawl-delay (seconds)", addGroup: "Add group", removeGroup: "Remove", sitemaps: "Sitemap URLs (one per line)", output: "robots.txt" },

  tr: { title: "robots.txt Oluşturucu", short: "Tarama kuralları ve site haritalarıyla bir robots.txt dosyası oluşturun.", description: "Ücretsiz robots.txt oluşturucu. Allow / Disallow desenleri, isteğe bağlı Crawl-delay ve Sitemap URL'leriyle User-agent grupları ekleyerek temiz bir robots.txt oluşturun — hepsi tarayıcınızda.", keywords: ["robots.txt oluşturucu", "robots txt", "tarayıcı kuralları", "site haritası bildirimi", "seo robots"], group: "Grup", userAgent: "User-agent", allow: "Allow yolları (her satıra bir)", disallow: "Disallow yolları (her satıra bir)", crawlDelay: "Crawl-delay (saniye)", addGroup: "Grup ekle", removeGroup: "Kaldır", sitemaps: "Sitemap URL'leri (her satıra bir)", output: "robots.txt" },
  de: { title: "robots.txt-Generator", short: "Erzeugen Sie eine robots.txt mit Crawl-Regeln und Sitemaps.", description: "Kostenloser robots.txt-Generator. Fügen Sie User-agent-Gruppen mit Allow/Disallow-Mustern, optionalem Crawl-delay und Sitemap-URLs hinzu, um eine saubere robots.txt zusammenzustellen — alles im Browser.", keywords: ["robots.txt generator", "robots txt", "crawler regeln", "sitemap deklaration", "seo robots"], group: "Gruppe", userAgent: "User-agent", allow: "Erlaubte Pfade (einer pro Zeile)", disallow: "Nicht erlaubte Pfade (einer pro Zeile)", crawlDelay: "Crawl-delay (Sekunden)", addGroup: "Gruppe hinzufügen", removeGroup: "Entfernen", sitemaps: "Sitemap-URLs (eine pro Zeile)", output: "robots.txt" },
  fr: { title: "Générateur de robots.txt", short: "Créez un fichier robots.txt avec règles de crawl et sitemaps.", description: "Générateur de robots.txt gratuit. Ajoutez des groupes User-agent avec des motifs Allow/Disallow, un Crawl-delay optionnel et des URL Sitemap pour assembler un robots.txt propre — le tout dans votre navigateur.", keywords: ["générateur robots.txt", "robots txt", "règles crawler", "déclaration sitemap", "seo robots"], group: "Groupe", userAgent: "User-agent", allow: "Chemins Allow (un par ligne)", disallow: "Chemins Disallow (un par ligne)", crawlDelay: "Crawl-delay (secondes)", addGroup: "Ajouter un groupe", removeGroup: "Supprimer", sitemaps: "URL Sitemap (une par ligne)", output: "robots.txt" },
  es: { title: "Generador de robots.txt", short: "Crea un archivo robots.txt con reglas de rastreo y sitemaps.", description: "Generador de robots.txt gratuito. Añade grupos User-agent con patrones Allow/Disallow, un Crawl-delay opcional y URLs de Sitemap para ensamblar un robots.txt limpio — todo en tu navegador.", keywords: ["generador robots.txt", "robots txt", "reglas crawler", "declaración sitemap", "seo robots"], group: "Grupo", userAgent: "User-agent", allow: "Rutas Allow (una por línea)", disallow: "Rutas Disallow (una por línea)", crawlDelay: "Crawl-delay (segundos)", addGroup: "Añadir grupo", removeGroup: "Eliminar", sitemaps: "URLs de Sitemap (una por línea)", output: "robots.txt" },
  it: { title: "Generatore di robots.txt", short: "Crea un file robots.txt con regole di crawl e sitemap.", description: "Generatore di robots.txt gratuito. Aggiungi gruppi User-agent con pattern Allow/Disallow, un Crawl-delay opzionale e URL di Sitemap per assemblare un robots.txt pulito — tutto nel browser.", keywords: ["generatore robots.txt", "robots txt", "regole crawler", "dichiarazione sitemap", "seo robots"], group: "Gruppo", userAgent: "User-agent", allow: "Percorsi Allow (uno per riga)", disallow: "Percorsi Disallow (uno per riga)", crawlDelay: "Crawl-delay (secondi)", addGroup: "Aggiungi gruppo", removeGroup: "Rimuovi", sitemaps: "URL Sitemap (uno per riga)", output: "robots.txt" },
  ar: { title: "مولّد robots.txt", short: "أنشئ ملف robots.txt بقواعد الزحف وخرائط الموقع.", description: "مولّد robots.txt مجاني. أضف مجموعات User-agent مع أنماط Allow/Disallow وCrawl-delay اختياري وعناوين URL لـ Sitemap لتجميع robots.txt نظيف — كل ذلك في متصفحك.", keywords: ["مولد robots.txt", "robots txt", "قواعد الزاحف", "إعلان خريطة الموقع", "seo robots"], group: "المجموعة", userAgent: "User-agent", allow: "مسارات Allow (واحد لكل سطر)", disallow: "مسارات Disallow (واحد لكل سطر)", crawlDelay: "Crawl-delay (ثوانٍ)", addGroup: "إضافة مجموعة", removeGroup: "إزالة", sitemaps: "عناوين Sitemap (واحد لكل سطر)", output: "robots.txt" },
  ru: { title: "Генератор robots.txt", short: "Создайте robots.txt с правилами обхода и sitemap.", description: "Бесплатный генератор robots.txt. Добавьте группы User-agent с шаблонами Allow/Disallow, опциональный Crawl-delay и URL Sitemap, чтобы собрать чистый robots.txt — всё в браузере.", keywords: ["генератор robots.txt", "robots txt", "правила краулера", "декларация sitemap", "seo robots"], group: "Группа", userAgent: "User-agent", allow: "Allow пути (по одному в строке)", disallow: "Disallow пути (по одному в строке)", crawlDelay: "Crawl-delay (секунд)", addGroup: "Добавить группу", removeGroup: "Удалить", sitemaps: "Sitemap URL (по одному в строке)", output: "robots.txt" },
  zh: { title: "robots.txt 生成器", short: "构建带抓取规则和站点地图的 robots.txt 文件。", description: "免费的 robots.txt 生成器。添加带 Allow/Disallow 模式的 User-agent 组、可选的 Crawl-delay 和 Sitemap URL，组装一个整洁的 robots.txt——全部在浏览器中完成。", keywords: ["robots.txt 生成器", "robots txt", "爬虫规则", "sitemap 声明", "seo robots"], group: "组", userAgent: "User-agent", allow: "Allow 路径（每行一个）", disallow: "Disallow 路径（每行一个）", crawlDelay: "Crawl-delay（秒）", addGroup: "添加组", removeGroup: "移除", sitemaps: "Sitemap URL（每行一个）", output: "robots.txt" },
  ja: { title: "robots.txt 生成", short: "クロールルールとサイトマップを含む robots.txt ファイルを構築。", description: "無料の robots.txt 生成ツール。Allow/Disallow パターン付きの User-agent グループ、オプションの Crawl-delay、Sitemap URL を追加して整理された robots.txt を組み立てます——すべてブラウザ内で。", keywords: ["robots.txt 生成", "robots txt", "クローラー ルール", "サイトマップ 宣言", "seo robots"], group: "グループ", userAgent: "User-agent", allow: "Allow パス（1行に1つ）", disallow: "Disallow パス（1行に1つ）", crawlDelay: "Crawl-delay（秒）", addGroup: "グループを追加", removeGroup: "削除", sitemaps: "Sitemap URL（1行に1つ）", output: "robots.txt" },
  ko: { title: "robots.txt 생성기", short: "크롤링 규칙과 사이트맵이 포함된 robots.txt 파일을 만듭니다.", description: "무료 robots.txt 생성기. Allow/Disallow 패턴이 있는 User-agent 그룹, 선택적 Crawl-delay, Sitemap URL을 추가해 깔끔한 robots.txt를 조립하세요 — 모두 브라우저에서.", keywords: ["robots.txt 생성기", "robots txt", "크롤러 규칙", "사이트맵 선언", "seo robots"], group: "그룹", userAgent: "User-agent", allow: "Allow 경로 (한 줄에 하나)", disallow: "Disallow 경로 (한 줄에 하나)", crawlDelay: "Crawl-delay (초)", addGroup: "그룹 추가", removeGroup: "제거", sitemaps: "Sitemap URL (한 줄에 하나)", output: "robots.txt" },
  hi: { title: "robots.txt जनरेटर", short: "क्रॉल नियमों और साइटमैप के साथ एक robots.txt फ़ाइल बनाएं।", description: "मुफ्त robots.txt जनरेटर। Allow/Disallow पैटर्न वाले User-agent समूह, वैकल्पिक Crawl-delay और Sitemap URL जोड़ें ताकि एक स्वच्छ robots.txt इकट्ठा हो — सब आपके ब्राउज़र में।", keywords: ["robots.txt जनरेटर", "robots txt", "क्रॉलर नियम", "साइटमैप घोषणा", "seo robots"], group: "समूह", userAgent: "User-agent", allow: "Allow पथ (प्रति पंक्ति एक)", disallow: "Disallow पथ (प्रति पंक्ति एक)", crawlDelay: "Crawl-delay (सेकंड)", addGroup: "समूह जोड़ें", removeGroup: "हटाएं", sitemaps: "Sitemap URL (प्रति पंक्ति एक)", output: "robots.txt" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
