import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Color Palette Generator", short: "Generate color harmony palettes from a base color.", description: "Free color palette generator. Pick a base color and a harmony rule (complementary, analogous, triadic, tetradic or monochromatic) to get a matching color scheme with hex codes.", keywords: ["color palette generator", "color scheme generator", "complementary colors", "analogous colors", "triadic color scheme"], baseColor: "Base color", harmony: "Harmony", complementary: "Complementary", analogous: "Analogous", triadic: "Triadic", tetradic: "Tetradic", monochromatic: "Monochromatic" },
  pt: { title: "Color Palette Generator", short: "Generate color harmony palettes from a base color.", description: "Free color palette generator. Pick a base color and a harmony rule (complementary, analogous, triadic, tetradic or monochromatic) to get a matching color scheme with hex codes.", keywords: ["color palette generator", "color scheme generator", "complementary colors", "analogous colors", "triadic color scheme"], baseColor: "Base color", harmony: "Harmony", complementary: "Complementary", analogous: "Analogous", triadic: "Triadic", tetradic: "Tetradic", monochromatic: "Monochromatic" },
  id: { title: "Color Palette Generator", short: "Generate color harmony palettes from a base color.", description: "Free color palette generator. Pick a base color and a harmony rule (complementary, analogous, triadic, tetradic or monochromatic) to get a matching color scheme with hex codes.", keywords: ["color palette generator", "color scheme generator", "complementary colors", "analogous colors", "triadic color scheme"], baseColor: "Base color", harmony: "Harmony", complementary: "Complementary", analogous: "Analogous", triadic: "Triadic", tetradic: "Tetradic", monochromatic: "Monochromatic" },

  tr: { title: "Renk Paleti Oluşturucu", short: "Bir temel renkten uyumlu renk paletleri oluşturun.", description: "Ücretsiz renk paleti oluşturucu. Bir temel renk ve uyum kuralı (tamamlayıcı, analog, üçlü, dörtlü veya monokromatik) seçerek hex kodlarıyla eşleşen bir renk şeması alın.", keywords: ["renk paleti oluşturucu", "renk şeması oluşturucu", "tamamlayıcı renkler", "analog renkler", "üçlü renk şeması"], baseColor: "Temel renk", harmony: "Uyum", complementary: "Tamamlayıcı", analogous: "Analog", triadic: "Üçlü", tetradic: "Dörtlü", monochromatic: "Monokromatik" },
  de: { title: "Farbpaletten-Generator", short: "Erzeugen Sie harmonische Farbpaletten aus einer Grundfarbe.", description: "Kostenloser Farbpaletten-Generator. Wählen Sie eine Grundfarbe und eine Harmonieregel (komplementär, analog, triadisch, tetradisch oder monochromatisch), um ein passendes Farbschema mit Hex-Codes zu erhalten.", keywords: ["farbpaletten generator", "farbschema generator", "komplementärfarben", "analoge farben", "triadisches farbschema"], baseColor: "Grundfarbe", harmony: "Harmonie", complementary: "Komplementär", analogous: "Analog", triadic: "Triadisch", tetradic: "Tetradisch", monochromatic: "Monochrom" },
  fr: { title: "Générateur de Palette de Couleurs", short: "Générez des palettes harmonieuses à partir d'une couleur de base.", description: "Générateur de palette de couleurs gratuit. Choisissez une couleur de base et une règle d'harmonie (complémentaire, analogue, triadique, tétradique ou monochromatique) pour obtenir un schéma de couleurs avec codes hex.", keywords: ["générateur palette couleurs", "générateur schéma couleurs", "couleurs complémentaires", "couleurs analogues", "schéma triadique"], baseColor: "Couleur de base", harmony: "Harmonie", complementary: "Complémentaire", analogous: "Analogue", triadic: "Triadique", tetradic: "Tétradique", monochromatic: "Monochromatique" },
  es: { title: "Generador de Paleta de Colores", short: "Genera paletas de colores armónicas desde un color base.", description: "Generador de paleta de colores gratuito. Elige un color base y una regla de armonía (complementario, análogo, triádico, tetrádico o monocromático) para obtener un esquema de color con códigos hex.", keywords: ["generador paleta colores", "generador esquema colores", "colores complementarios", "colores análogos", "esquema triádico"], baseColor: "Color base", harmony: "Armonía", complementary: "Complementario", analogous: "Análogo", triadic: "Triádico", tetradic: "Tetrádico", monochromatic: "Monocromático" },
  it: { title: "Generatore di Palette di Colori", short: "Genera palette di colori armoniose da un colore base.", description: "Generatore di palette di colori gratuito. Scegli un colore base e una regola di armonia (complementare, analogo, triadico, tetradico o monocromatico) per ottenere uno schema di colori con codici hex.", keywords: ["generatore palette colori", "generatore schema colori", "colori complementari", "colori analoghi", "schema triadico"], baseColor: "Colore base", harmony: "Armonia", complementary: "Complementare", analogous: "Analogo", triadic: "Triadico", tetradic: "Tetradico", monochromatic: "Monocromatico" },
  ar: { title: "مولّد لوحة الألوان", short: "أنشئ لوحات ألوان متناسقة من لون أساسي.", description: "مولّد لوحة ألوان مجاني. اختر لونًا أساسيًا وقاعدة تناسق (تكميلي، متماثل، ثلاثي، رباعي أو أحادي اللون) للحصول على نظام ألوان مطابق مع أكواد hex.", keywords: ["مولد لوحة ألوان", "مولد نظام ألوان", "ألوان تكميلية", "ألوان متماثلة", "نظام ثلاثي"], baseColor: "اللون الأساسي", harmony: "التناسق", complementary: "تكميلي", analogous: "متماثل", triadic: "ثلاثي", tetradic: "رباعي", monochromatic: "أحادي اللون" },
  ru: { title: "Генератор цветовой палитры", short: "Создавайте гармоничные палитры из базового цвета.", description: "Бесплатный генератор цветовой палитры. Выберите базовый цвет и правило гармонии (комплементарная, аналоговая, триадная, тетрадная или монохромная), чтобы получить цветовую схему с hex-кодами.", keywords: ["генератор цветовой палитры", "генератор цветовой схемы", "комплементарные цвета", "аналоговые цвета", "триадная схема"], baseColor: "Базовый цвет", harmony: "Гармония", complementary: "Комплементарная", analogous: "Аналоговая", triadic: "Триадная", tetradic: "Тетрадная", monochromatic: "Монохромная" },
  zh: { title: "调色板生成器", short: "从基础颜色生成和谐配色方案。", description: "免费的调色板生成器。选择一个基础颜色和配色规则（互补、类似、三色、四色或单色），即可获得带有十六进制代码的配色方案。", keywords: ["调色板生成器", "配色方案生成器", "互补色", "类似色", "三色配色"], baseColor: "基础颜色", harmony: "配色规则", complementary: "互补色", analogous: "类似色", triadic: "三色", tetradic: "四色", monochromatic: "单色" },
  ja: { title: "カラーパレット生成", short: "ベースカラーから調和の取れたパレットを生成。", description: "無料のカラーパレット生成ツール。ベースカラーと調和ルール（補色、類似色、三色、四色、単色）を選ぶと、16進コード付きの配色が得られます。", keywords: ["カラーパレット 生成", "配色 生成", "補色", "類似色", "三色配色"], baseColor: "ベースカラー", harmony: "調和", complementary: "補色", analogous: "類似色", triadic: "三色", tetradic: "四色", monochromatic: "単色" },
  ko: { title: "색상 팔레트 생성기", short: "기준 색상에서 조화로운 색상 팔레트를 생성합니다.", description: "무료 색상 팔레트 생성기. 기준 색상과 조화 규칙(보색, 유사색, 삼색, 사색 또는 단색)을 선택하면 hex 코드가 포함된 색상 구성을 얻습니다.", keywords: ["색상 팔레트 생성기", "색상 구성 생성기", "보색", "유사색", "삼색 구성"], baseColor: "기준 색상", harmony: "조화", complementary: "보색", analogous: "유사색", triadic: "삼색", tetradic: "사색", monochromatic: "단색" },
  hi: { title: "रंग पैलेट जनरेटर", short: "एक आधार रंग से सामंजस्यपूर्ण रंग पैलेट बनाएं।", description: "मुफ्त रंग पैलेट जनरेटर। एक आधार रंग और सामंजस्य नियम (पूरक, समान, त्रिक, चतुष्क या एकवर्णी) चुनें और hex कोड के साथ मेल खाती रंग योजना पाएं।", keywords: ["रंग पैलेट जनरेटर", "रंग योजना जनरेटर", "पूरक रंग", "समान रंग", "त्रिक रंग योजना"], baseColor: "आधार रंग", harmony: "सामंजस्य", complementary: "पूरक", analogous: "समान", triadic: "त्रिक", tetradic: "चतुष्क", monochromatic: "एकवर्णी" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
