import type { CalculatorI18n } from "@/types/i18n";

const i18n: CalculatorI18n = {
  en: {
    title: "LED Resistor Calculator",
    short: "Calculate the correct current-limiting resistor for your LED circuit.",
    description:
      "Free LED resistor calculator. Enter supply voltage, LED forward voltage, and desired current to find the exact and standard E12 resistor value, power dissipation, and color code.",
    keywords: [
      "LED resistor calculator",
      "current limiting resistor",
      "LED circuit",
      "E12 resistor series",
      "resistor color code",
      "LED forward voltage",
      "electronics calculator",
    ],
    inputs: {
      supplyVoltage: {
        label: "Supply Voltage (V)",
        help: "The DC voltage of your power supply (e.g., 5V for USB, 12V for car circuits).",
      },
      forwardVoltage: {
        label: "LED Forward Voltage (V)",
        help: "The voltage drop across a single LED when conducting (typical: red=2.0V, blue/white=3.2V).",
      },
      forwardCurrentMa: {
        label: "Desired Current (mA)",
        help: "Target LED operating current in milliamps. Most standard LEDs run at 20mA.",
      },
      ledCount: {
        label: "Number of LEDs in Series",
        help: "How many LEDs are connected in series on the same resistor.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Exact Resistance (Ω)",
        help: "Calculated resistor value using Ohm's Law: R = (Vsupply - Vforward×n) / I.",
      },
      standardResistanceOhm: {
        label: "Standard E12 Resistance (Ω)",
        help: "Nearest standard E12 series value rounded up — provides a safe lower current for the LED.",
      },
      powerDissipatedW: {
        label: "Power Dissipated (W)",
        help: "Heat generated by the resistor: P = (Vsupply - Vforward×n) × I. Use a resistor rated at 2× this value.",
      },
      actualCurrentMa: {
        label: "Actual Current with Standard Resistor (mA)",
        help: "Real LED current when using the standard E12 resistor value.",
      },
      resistorColorCode: {
        label: "Resistor Color Code",
        help: "4-band color code for the standard E12 resistor (tolerance band = gold ±5%).",
      },
    },
    errors: {
      supplyTooLow: "Supply voltage must be greater than the total LED forward voltage.",
    },
    faq: [
      {
        q: "Why do LEDs need a current-limiting resistor?",
        a: "LEDs have very low internal resistance. Without a series resistor, even a small voltage increase causes a large current surge that can permanently destroy the LED. The resistor limits current to a safe operating level.",
      },
      {
        q: "What is the E12 resistor series?",
        a: "E12 is a standard set of 12 preferred resistor values per decade defined by the EIA. These values (10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82) are spaced roughly equally on a logarithmic scale, and commercially available resistors follow this sequence.",
      },
      {
        q: "Why round up to the nearest standard value?",
        a: "Rounding up gives a higher resistance than calculated, which means slightly less current flows through the LED. This is the safe direction — the LED remains within its rated current and its brightness is only marginally reduced.",
      },
      {
        q: "What power rating should I choose for the resistor?",
        a: "Always choose a resistor with a power rating at least twice the calculated power dissipation. For example, if the calculator shows 0.08W, use a 0.25W (1/4W) resistor for adequate safety margin.",
      },
      {
        q: "Can I connect multiple LEDs to one resistor?",
        a: "Yes — in series. The calculator supports up to 10 LEDs in series. The total forward voltage is the sum of all individual LED forward voltages. Connecting LEDs in parallel with a single resistor is not recommended because slight differences in forward voltage can cause unequal current sharing.",
      },
    ],
  },
  pt: {
    title: "Calculadora de Resistor para LED",
    short: "Calcule o resistor necessário para alimentar um LED.",
    description:
      "Calculadora gratuita de resistor para LED. Calcule a resistência limitadora de corrente com base na tensão de alimentação, tensão e corrente do LED.",
    keywords: ["resistor LED", "calculadora LED", "corrente LED", "tensão LED", "limitador corrente"],
    inputs: {
      supplyVoltage: {
        label: "Supply Voltage (V)",
        help: "The DC voltage of your power supply (e.g., 5V for USB, 12V for car circuits).",
      },
      forwardVoltage: {
        label: "LED Forward Voltage (V)",
        help: "The voltage drop across a single LED when conducting (typical: red=2.0V, blue/white=3.2V).",
      },
      forwardCurrentMa: {
        label: "Desired Current (mA)",
        help: "Target LED operating current in milliamps. Most standard LEDs run at 20mA.",
      },
      ledCount: {
        label: "Number of LEDs in Series",
        help: "How many LEDs are connected in series on the same resistor.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Exact Resistance (Ω)",
        help: "Calculated resistor value using Ohm's Law: R = (Vsupply - Vforward×n) / I.",
      },
      standardResistanceOhm: {
        label: "Standard E12 Resistance (Ω)",
        help: "Nearest standard E12 series value rounded up — provides a safe lower current for the LED.",
      },
      powerDissipatedW: {
        label: "Power Dissipated (W)",
        help: "Heat generated by the resistor: P = (Vsupply - Vforward×n) × I. Use a resistor rated at 2× this value.",
      },
      actualCurrentMa: {
        label: "Actual Current with Standard Resistor (mA)",
        help: "Real LED current when using the standard E12 resistor value.",
      },
      resistorColorCode: {
        label: "Resistor Color Code",
        help: "4-band color code for the standard E12 resistor (tolerance band = gold ±5%).",
      },
    },
    errors: {
      supplyTooLow: "Supply voltage must be greater than the total LED forward voltage.",
    },
    faq: [
      {
        q: "Why do LEDs need a current-limiting resistor?",
        a: "LEDs have very low internal resistance. Without a series resistor, even a small voltage increase causes a large current surge that can permanently destroy the LED. The resistor limits current to a safe operating level.",
      },
      {
        q: "What is the E12 resistor series?",
        a: "E12 is a standard set of 12 preferred resistor values per decade defined by the EIA. These values (10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82) are spaced roughly equally on a logarithmic scale, and commercially available resistors follow this sequence.",
      },
      {
        q: "Why round up to the nearest standard value?",
        a: "Rounding up gives a higher resistance than calculated, which means slightly less current flows through the LED. This is the safe direction — the LED remains within its rated current and its brightness is only marginally reduced.",
      },
      {
        q: "What power rating should I choose for the resistor?",
        a: "Always choose a resistor with a power rating at least twice the calculated power dissipation. For example, if the calculator shows 0.08W, use a 0.25W (1/4W) resistor for adequate safety margin.",
      },
      {
        q: "Can I connect multiple LEDs to one resistor?",
        a: "Yes — in series. The calculator supports up to 10 LEDs in series. The total forward voltage is the sum of all individual LED forward voltages. Connecting LEDs in parallel with a single resistor is not recommended because slight differences in forward voltage can cause unequal current sharing.",
      },
    ],
  },
  id: {
    title: "Kalkulator Resistor LED",
    short: "Hitung resistor yang diperlukan untuk mengoperasikan LED.",
    description:
      "Kalkulator resistor LED gratis. Hitung resistansi pembatas arus berdasarkan tegangan sumber, tegangan dan arus LED.",
    keywords: ["resistor LED", "kalkulator LED", "arus LED", "tegangan LED", "pembatas arus"],
    inputs: {
      supplyVoltage: {
        label: "Supply Voltage (V)",
        help: "The DC voltage of your power supply (e.g., 5V for USB, 12V for car circuits).",
      },
      forwardVoltage: {
        label: "LED Forward Voltage (V)",
        help: "The voltage drop across a single LED when conducting (typical: red=2.0V, blue/white=3.2V).",
      },
      forwardCurrentMa: {
        label: "Desired Current (mA)",
        help: "Target LED operating current in milliamps. Most standard LEDs run at 20mA.",
      },
      ledCount: {
        label: "Number of LEDs in Series",
        help: "How many LEDs are connected in series on the same resistor.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Exact Resistance (Ω)",
        help: "Calculated resistor value using Ohm's Law: R = (Vsupply - Vforward×n) / I.",
      },
      standardResistanceOhm: {
        label: "Standard E12 Resistance (Ω)",
        help: "Nearest standard E12 series value rounded up — provides a safe lower current for the LED.",
      },
      powerDissipatedW: {
        label: "Power Dissipated (W)",
        help: "Heat generated by the resistor: P = (Vsupply - Vforward×n) × I. Use a resistor rated at 2× this value.",
      },
      actualCurrentMa: {
        label: "Actual Current with Standard Resistor (mA)",
        help: "Real LED current when using the standard E12 resistor value.",
      },
      resistorColorCode: {
        label: "Resistor Color Code",
        help: "4-band color code for the standard E12 resistor (tolerance band = gold ±5%).",
      },
    },
    errors: {
      supplyTooLow: "Supply voltage must be greater than the total LED forward voltage.",
    },
    faq: [
      {
        q: "Why do LEDs need a current-limiting resistor?",
        a: "LEDs have very low internal resistance. Without a series resistor, even a small voltage increase causes a large current surge that can permanently destroy the LED. The resistor limits current to a safe operating level.",
      },
      {
        q: "What is the E12 resistor series?",
        a: "E12 is a standard set of 12 preferred resistor values per decade defined by the EIA. These values (10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68, 82) are spaced roughly equally on a logarithmic scale, and commercially available resistors follow this sequence.",
      },
      {
        q: "Why round up to the nearest standard value?",
        a: "Rounding up gives a higher resistance than calculated, which means slightly less current flows through the LED. This is the safe direction — the LED remains within its rated current and its brightness is only marginally reduced.",
      },
      {
        q: "What power rating should I choose for the resistor?",
        a: "Always choose a resistor with a power rating at least twice the calculated power dissipation. For example, if the calculator shows 0.08W, use a 0.25W (1/4W) resistor for adequate safety margin.",
      },
      {
        q: "Can I connect multiple LEDs to one resistor?",
        a: "Yes — in series. The calculator supports up to 10 LEDs in series. The total forward voltage is the sum of all individual LED forward voltages. Connecting LEDs in parallel with a single resistor is not recommended because slight differences in forward voltage can cause unequal current sharing.",
      },
    ],
  },


  tr: {
    title: "LED Direnç Hesaplayıcı",
    short: "LED devreniz için doğru akım sınırlama direncini hesaplayın.",
    description:
      "Ücretsiz LED direnç hesaplayıcı. Besleme gerilimi, LED ileri gerilimi ve istenen akımı girerek kesin ve standart E12 direnç değerini, güç tüketimini ve renk kodunu öğrenin.",
    keywords: [
      "LED direnç hesaplayıcı",
      "akım sınırlama direnci",
      "LED devresi",
      "E12 direnç serisi",
      "direnç renk kodu",
      "LED ileri gerilim",
      "elektronik hesaplayıcı",
    ],
    inputs: {
      supplyVoltage: {
        label: "Besleme Gerilimi (V)",
        help: "Güç kaynağınızın DC gerilimi (ör. USB için 5V, araç devreleri için 12V).",
      },
      forwardVoltage: {
        label: "LED İleri Gerilimi (V)",
        help: "İletimde tek bir LED'deki gerilim düşümü (tipik: kırmızı=2.0V, mavi/beyaz=3.2V).",
      },
      forwardCurrentMa: {
        label: "İstenen Akım (mA)",
        help: "Hedef LED çalışma akımı, miliamper cinsinden. Standart LED'lerin çoğu 20mA'de çalışır.",
      },
      ledCount: {
        label: "Seri Bağlı LED Sayısı",
        help: "Aynı dirence bağlı seri LED sayısı.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Kesin Direnç (Ω)",
        help: "Ohm Kanunu ile hesaplanan direnç değeri: R = (Vbeslem - Vileri×n) / I.",
      },
      standardResistanceOhm: {
        label: "Standart E12 Direnci (Ω)",
        help: "Yukarı yuvarlanan en yakın E12 standart değeri — LED için güvenli düşük akım sağlar.",
      },
      powerDissipatedW: {
        label: "Harcanan Güç (W)",
        help: "Direncin ürettiği ısı: P = (Vbeslem - Vileri×n) × I. Bu değerin 2 katı güç sınıflamasına sahip direnç kullanın.",
      },
      actualCurrentMa: {
        label: "Standart Dirençle Gerçek Akım (mA)",
        help: "Standart E12 direnç değeri kullanıldığında gerçek LED akımı.",
      },
      resistorColorCode: {
        label: "Direnç Renk Kodu",
        help: "Standart E12 direnci için 4 bantlı renk kodu (tolerans bandı = altın ±%5).",
      },
    },
    errors: {
      supplyTooLow: "Besleme gerilimi toplam LED ileri geriliminden büyük olmalıdır.",
    },
    faq: [
      {
        q: "LED'ler neden akım sınırlama direncine ihtiyaç duyar?",
        a: "LED'lerin iç direnci çok düşüktür. Seri direnç olmadan küçük bir gerilim artışı bile LED'i kalıcı olarak tahrip edecek büyük bir akım artışına neden olur. Direnç, akımı güvenli çalışma düzeyiyle sınırlar.",
      },
      {
        q: "E12 direnç serisi nedir?",
        a: "E12, EIA tarafından her dekad için 12 tercih edilen direnç değeri içeren standart bir settir. 10, 12, 15, 18, 22, 27, 33, 39, 47, 56, 68 ve 82 değerleri logaritmik ölçekte yaklaşık eşit aralıklarla yerleştirilmiştir.",
      },
      {
        q: "Neden en yakın standart değere yukarı yuvarlıyoruz?",
        a: "Yukarı yuvarlamak, hesaplanan değerden daha yüksek direnç verir ve LED'den biraz daha az akım geçmesini sağlar. Bu, LED'in güvenli bölgede kalmasını sağlar.",
      },
      {
        q: "Direnç için ne kadar güç sınıflaması seçmeliyim?",
        a: "Her zaman hesaplanan güç tüketiminin en az iki katı olan bir güç sınıflaması seçin. Örneğin hesaplayıcı 0.08W gösteriyorsa, yeterli güvenlik payı için 0.25W (1/4W) direnç kullanın.",
      },
      {
        q: "Birden fazla LED'i tek bir dirençle kullanabilir miyim?",
        a: "Evet, seri bağlantıda. Hesaplayıcı 10'a kadar seri LED'i destekler. Toplam ileri gerilim tüm LED'lerin ileri gerilimlerinin toplamıdır. Paralel bağlantı önerilmez.",
      },
    ],
  },

  de: {
    title: "LED-Vorwiderstand-Rechner",
    short: "Berechnen Sie den richtigen Vorwiderstand für Ihre LED-Schaltung.",
    description:
      "Kostenloser LED-Vorwiderstand-Rechner. Geben Sie Versorgungsspannung, LED-Flussspannung und Sollstrom ein, um den genauen und standardisierten E12-Widerstandswert, Verlustleistung und Farbcode zu ermitteln.",
    keywords: [
      "LED Vorwiderstand Rechner",
      "Strombegrenzungswiderstand",
      "LED-Schaltung",
      "E12-Widerstandsreihe",
      "Widerstandsfarbcode",
      "LED-Flussspannung",
      "Elektronikrechner",
    ],
    inputs: {
      supplyVoltage: {
        label: "Versorgungsspannung (V)",
        help: "Die Gleichspannung Ihrer Stromversorgung (z. B. 5 V für USB, 12 V für Kfz-Schaltungen).",
      },
      forwardVoltage: {
        label: "LED-Flussspannung (V)",
        help: "Spannungsabfall an einer einzelnen LED im leitenden Zustand (typisch: rot=2,0 V, blau/weiß=3,2 V).",
      },
      forwardCurrentMa: {
        label: "Sollstrom (mA)",
        help: "Ziel-LED-Betriebsstrom in Milliampere. Die meisten Standard-LEDs laufen mit 20 mA.",
      },
      ledCount: {
        label: "Anzahl LEDs in Reihe",
        help: "Anzahl der in Reihe geschalteten LEDs am gleichen Widerstand.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Genauer Widerstandswert (Ω)",
        help: "Berechneter Widerstandswert nach dem Ohmschen Gesetz: R = (Vversor - Vfluss×n) / I.",
      },
      standardResistanceOhm: {
        label: "Genormter E12-Widerstandswert (Ω)",
        help: "Nächster gerundeter E12-Standardwert — sorgt für einen sicheren Niedrigerstrom für die LED.",
      },
      powerDissipatedW: {
        label: "Verlustleistung (W)",
        help: "Vom Widerstand erzeugte Wärme: P = (Vversor - Vfluss×n) × I. Wählen Sie einen Widerstand mit doppelter Nennleistung.",
      },
      actualCurrentMa: {
        label: "Tatsächlicher Strom mit Normwiderstand (mA)",
        help: "Realer LED-Strom bei Verwendung des E12-Normwiderstands.",
      },
      resistorColorCode: {
        label: "Widerstandsfarbcode",
        help: "4-Band-Farbcode für den E12-Normwiderstand (Toleranzband = Gold ±5 %).",
      },
    },
    errors: {
      supplyTooLow: "Die Versorgungsspannung muss größer als die Gesamt-LED-Flussspannung sein.",
    },
    faq: [
      {
        q: "Warum benötigen LEDs einen Vorwiderstand?",
        a: "LEDs haben einen sehr geringen Innenwiderstand. Ohne Vorwiderstand kann bereits eine kleine Spannungserhöhung einen großen Stromstoß verursachen, der die LED dauerhaft zerstört.",
      },
      {
        q: "Was ist die E12-Widerstandsreihe?",
        a: "E12 ist eine vom EIA definierte Norm mit 12 bevorzugten Widerstandswerten pro Dekade. Diese Werte sind auf einer logarithmischen Skala gleichmäßig verteilt.",
      },
      {
        q: "Welche Nennleistung soll ich für den Widerstand wählen?",
        a: "Wählen Sie immer eine Nennleistung, die mindestens doppelt so hoch wie die berechnete Verlustleistung ist. Bei 0,08 W verwenden Sie beispielsweise einen 0,25-W-Widerstand.",
      },
    ],
  },

  fr: {
    title: "Calculateur de résistance LED",
    short: "Calculez la résistance de limitation de courant correcte pour votre circuit LED.",
    description:
      "Calculateur de résistance LED gratuit. Entrez la tension d'alimentation, la tension directe de la LED et le courant souhaité pour trouver la valeur exacte et normalisée E12, la puissance dissipée et le code couleur.",
    keywords: [
      "calculateur résistance LED",
      "résistance limitatrice de courant",
      "circuit LED",
      "série E12",
      "code couleur résistance",
      "tension directe LED",
      "calculateur électronique",
    ],
    inputs: {
      supplyVoltage: {
        label: "Tension d'alimentation (V)",
        help: "Tension continue de votre alimentation (ex. 5 V pour USB, 12 V pour circuits automobiles).",
      },
      forwardVoltage: {
        label: "Tension directe de la LED (V)",
        help: "Chute de tension aux bornes d'une LED en conduction (typique : rouge=2,0 V, bleue/blanche=3,2 V).",
      },
      forwardCurrentMa: {
        label: "Courant souhaité (mA)",
        help: "Courant de fonctionnement cible de la LED en milliampères. La plupart des LEDs standard fonctionnent à 20 mA.",
      },
      ledCount: {
        label: "Nombre de LEDs en série",
        help: "Nombre de LEDs connectées en série sur la même résistance.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Résistance exacte (Ω)",
        help: "Valeur calculée par la loi d'Ohm : R = (Valim - Vdirecte×n) / I.",
      },
      standardResistanceOhm: {
        label: "Résistance E12 normalisée (Ω)",
        help: "Valeur E12 standard la plus proche arrondie à la hausse — fournit un courant inférieur sécurisé pour la LED.",
      },
      powerDissipatedW: {
        label: "Puissance dissipée (W)",
        help: "Chaleur générée par la résistance : P = (Valim - Vdirecte×n) × I. Utilisez une résistance avec le double de cette puissance nominale.",
      },
      actualCurrentMa: {
        label: "Courant réel avec résistance standard (mA)",
        help: "Courant LED réel lors de l'utilisation de la résistance E12 standard.",
      },
      resistorColorCode: {
        label: "Code couleur de la résistance",
        help: "Code couleur 4 bandes pour la résistance E12 (bande de tolérance = or ±5 %).",
      },
    },
    errors: {
      supplyTooLow: "La tension d'alimentation doit être supérieure à la tension directe totale de la LED.",
    },
    faq: [
      {
        q: "Pourquoi les LEDs ont-elles besoin d'une résistance de limitation de courant ?",
        a: "Les LEDs ont une très faible résistance interne. Sans résistance série, même une légère augmentation de tension provoque un afflux de courant important qui peut détruire définitivement la LED.",
      },
      {
        q: "Qu'est-ce que la série E12 ?",
        a: "E12 est un ensemble standard de 12 valeurs de résistances préférées par décade défini par l'EIA. Ces valeurs sont espacées de manière approximativement égale sur une échelle logarithmique.",
      },
      {
        q: "Quelle puissance nominale choisir pour la résistance ?",
        a: "Choisissez toujours une puissance nominale au moins deux fois supérieure à la puissance dissipée calculée. Si le calculateur indique 0,08 W, utilisez une résistance de 0,25 W.",
      },
    ],
  },

  es: {
    title: "Calculadora de resistencia LED",
    short: "Calcula la resistencia limitadora de corriente correcta para tu circuito LED.",
    description:
      "Calculadora de resistencia LED gratuita. Introduce la tensión de alimentación, la tensión directa del LED y la corriente deseada para encontrar el valor exacto y estándar E12, la disipación de potencia y el código de colores.",
    keywords: [
      "calculadora resistencia LED",
      "resistencia limitadora de corriente",
      "circuito LED",
      "serie E12",
      "código de colores resistencia",
      "tensión directa LED",
      "calculadora electrónica",
    ],
    inputs: {
      supplyVoltage: {
        label: "Tensión de alimentación (V)",
        help: "La tensión continua de tu fuente de alimentación (ej. 5V para USB, 12V para circuitos de automóvil).",
      },
      forwardVoltage: {
        label: "Tensión directa del LED (V)",
        help: "Caída de tensión en un único LED en conducción (típico: rojo=2,0V, azul/blanco=3,2V).",
      },
      forwardCurrentMa: {
        label: "Corriente deseada (mA)",
        help: "Corriente de funcionamiento objetivo del LED en miliamperios. La mayoría de los LEDs estándar funcionan a 20mA.",
      },
      ledCount: {
        label: "Número de LEDs en serie",
        help: "Cuántos LEDs están conectados en serie en la misma resistencia.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Resistencia exacta (Ω)",
        help: "Valor de resistencia calculado con la Ley de Ohm: R = (Valiment - Vdirecta×n) / I.",
      },
      standardResistanceOhm: {
        label: "Resistencia E12 estándar (Ω)",
        help: "Valor estándar E12 más cercano redondeado hacia arriba — proporciona una corriente menor y segura para el LED.",
      },
      powerDissipatedW: {
        label: "Potencia disipada (W)",
        help: "Calor generado por la resistencia: P = (Valiment - Vdirecta×n) × I. Usa una resistencia con el doble de esta potencia nominal.",
      },
      actualCurrentMa: {
        label: "Corriente real con resistencia estándar (mA)",
        help: "Corriente real del LED al usar el valor de resistencia E12 estándar.",
      },
      resistorColorCode: {
        label: "Código de colores de la resistencia",
        help: "Código de colores de 4 bandas para la resistencia E12 estándar (banda de tolerancia = oro ±5%).",
      },
    },
    errors: {
      supplyTooLow: "La tensión de alimentación debe ser mayor que la tensión directa total del LED.",
    },
    faq: [
      {
        q: "¿Por qué los LEDs necesitan una resistencia limitadora de corriente?",
        a: "Los LEDs tienen una resistencia interna muy baja. Sin una resistencia en serie, incluso un pequeño aumento de tensión provoca una gran subida de corriente que puede destruir permanentemente el LED.",
      },
      {
        q: "¿Qué es la serie de resistencias E12?",
        a: "E12 es un conjunto estándar de 12 valores de resistencias preferidos por década definido por la EIA. Estos valores están espaciados de forma aproximadamente igual en una escala logarítmica.",
      },
      {
        q: "¿Qué potencia nominal debo elegir para la resistencia?",
        a: "Elige siempre una potencia nominal al menos el doble de la potencia disipada calculada. Si la calculadora muestra 0,08W, usa una resistencia de 0,25W.",
      },
    ],
  },

  it: {
    title: "Calcolatore resistenza LED",
    short: "Calcola la resistenza limitatrice di corrente corretta per il tuo circuito LED.",
    description:
      "Calcolatore di resistenza LED gratuito. Inserisci la tensione di alimentazione, la tensione diretta del LED e la corrente desiderata per trovare il valore esatto e standard E12, la dissipazione di potenza e il codice colore.",
    keywords: [
      "calcolatore resistenza LED",
      "resistenza limitatrice di corrente",
      "circuito LED",
      "serie E12",
      "codice colore resistenza",
      "tensione diretta LED",
      "calcolatore elettronico",
    ],
    inputs: {
      supplyVoltage: {
        label: "Tensione di alimentazione (V)",
        help: "La tensione continua del tuo alimentatore (es. 5V per USB, 12V per circuiti auto).",
      },
      forwardVoltage: {
        label: "Tensione diretta del LED (V)",
        help: "Caduta di tensione su un singolo LED in conduzione (tipico: rosso=2,0V, blu/bianco=3,2V).",
      },
      forwardCurrentMa: {
        label: "Corrente desiderata (mA)",
        help: "Corrente di funzionamento target del LED in milliampere. La maggior parte dei LED standard funziona a 20mA.",
      },
      ledCount: {
        label: "Numero di LED in serie",
        help: "Quanti LED sono collegati in serie sulla stessa resistenza.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Resistenza esatta (Ω)",
        help: "Valore di resistenza calcolato con la legge di Ohm: R = (Valim - Vdiretta×n) / I.",
      },
      standardResistanceOhm: {
        label: "Resistenza E12 standard (Ω)",
        help: "Valore standard E12 più vicino arrotondato per eccesso — fornisce una corrente inferiore sicura per il LED.",
      },
      powerDissipatedW: {
        label: "Potenza dissipata (W)",
        help: "Calore generato dalla resistenza: P = (Valim - Vdiretta×n) × I. Usa una resistenza con il doppio di questa potenza nominale.",
      },
      actualCurrentMa: {
        label: "Corrente reale con resistenza standard (mA)",
        help: "Corrente LED reale usando il valore di resistenza E12 standard.",
      },
      resistorColorCode: {
        label: "Codice colore della resistenza",
        help: "Codice colore a 4 bande per la resistenza E12 standard (banda di tolleranza = oro ±5%).",
      },
    },
    errors: {
      supplyTooLow: "La tensione di alimentazione deve essere maggiore della tensione diretta totale del LED.",
    },
    faq: [
      {
        q: "Perché i LED hanno bisogno di una resistenza limitatrice di corrente?",
        a: "I LED hanno una resistenza interna molto bassa. Senza una resistenza in serie, anche un piccolo aumento di tensione può causare un grande aumento di corrente che distrugge permanentemente il LED.",
      },
      {
        q: "Cos'è la serie di resistenze E12?",
        a: "E12 è un insieme standard di 12 valori di resistenze preferiti per decennio definito dall'EIA. Questi valori sono distribuiti approssimativamente in modo uniforme su una scala logaritmica.",
      },
      {
        q: "Quale potenza nominale devo scegliere per la resistenza?",
        a: "Scegli sempre una potenza nominale almeno doppia rispetto alla potenza dissipata calcolata. Se il calcolatore mostra 0,08W, usa una resistenza da 0,25W.",
      },
    ],
  },

  ar: {
    title: "حاسبة مقاومة LED",
    short: "احسب مقاومة تحديد التيار الصحيحة لدائرة LED الخاصة بك.",
    description:
      "حاسبة مقاومة LED مجانية. أدخل جهد الإمداد وجهد LED الأمامي والتيار المطلوب للحصول على القيمة الدقيقة والمعيارية E12 وفقدان الطاقة ورمز الألوان.",
    keywords: [
      "حاسبة مقاومة LED",
      "مقاومة تحديد التيار",
      "دائرة LED",
      "سلسلة E12",
      "رمز ألوان المقاومة",
      "جهد LED الأمامي",
      "حاسبة إلكترونية",
    ],
    inputs: {
      supplyVoltage: {
        label: "جهد الإمداد (V)",
        help: "جهد التيار المستمر لمصدر الطاقة (مثلاً 5V لـ USB، 12V لدوائر السيارات).",
      },
      forwardVoltage: {
        label: "الجهد الأمامي للـ LED (V)",
        help: "انخفاض الجهد عبر LED واحد عند التوصيل (نموذجي: أحمر=2.0V، أزرق/أبيض=3.2V).",
      },
      forwardCurrentMa: {
        label: "التيار المطلوب (mA)",
        help: "تيار تشغيل LED المستهدف بالميلي أمبير. تعمل معظم LEDs القياسية عند 20mA.",
      },
      ledCount: {
        label: "عدد LEDs على التوالي",
        help: "عدد LEDs المتصلة على التوالي على نفس المقاومة.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "المقاومة الدقيقة (Ω)",
        help: "قيمة المقاومة المحسوبة باستخدام قانون أوم: R = (Vإمداد - Vأمامي×n) / I.",
      },
      standardResistanceOhm: {
        label: "مقاومة E12 القياسية (Ω)",
        help: "أقرب قيمة قياسية E12 مقربة للأعلى — توفر تياراً أقل وأكثر أماناً لـ LED.",
      },
      powerDissipatedW: {
        label: "الطاقة المبددة (W)",
        help: "الحرارة الناتجة عن المقاومة: P = (Vإمداد - Vأمامي×n) × I. استخدم مقاومة بضعف هذه الطاقة الاسمية.",
      },
      actualCurrentMa: {
        label: "التيار الفعلي مع المقاومة القياسية (mA)",
        help: "تيار LED الفعلي عند استخدام قيمة مقاومة E12 القياسية.",
      },
      resistorColorCode: {
        label: "رمز ألوان المقاومة",
        help: "رمز الألوان بـ 4 نطاقات للمقاومة E12 القياسية (نطاق التفاوت = ذهبي ±5%).",
      },
    },
    errors: {
      supplyTooLow: "يجب أن يكون جهد الإمداد أكبر من إجمالي الجهد الأمامي لـ LED.",
    },
    faq: [
      {
        q: "لماذا تحتاج LEDs إلى مقاومة تحديد التيار؟",
        a: "تمتلك LEDs مقاومة داخلية منخفضة جداً. بدون مقاومة توالي، حتى زيادة طفيفة في الجهد يمكن أن تسبب ارتفاعاً كبيراً في التيار يتلف LED بشكل دائم.",
      },
      {
        q: "ما هي سلسلة مقاومات E12؟",
        a: "E12 هي مجموعة قياسية من 12 قيمة مقاومة مفضلة لكل ديكاد محددة من قبل EIA. هذه القيم موزعة بالتساوي تقريباً على مقياس لوغاريتمي.",
      },
      {
        q: "ما معدل الطاقة الذي يجب اختياره للمقاومة؟",
        a: "اختر دائماً معدل طاقة لا يقل عن ضعف قدرة التبديد المحسوبة. إذا أظهرت الحاسبة 0.08W، استخدم مقاومة 0.25W.",
      },
    ],
  },

  ru: {
    title: "Калькулятор резистора для светодиода",
    short: "Рассчитайте токоограничивающий резистор для вашей схемы со светодиодом.",
    description:
      "Бесплатный калькулятор резистора для светодиода. Введите напряжение питания, прямое напряжение светодиода и желаемый ток, чтобы найти точное и стандартное значение E12, мощность рассеивания и цветовой код.",
    keywords: [
      "калькулятор резистора светодиода",
      "токоограничивающий резистор",
      "схема светодиода",
      "ряд E12",
      "цветовой код резистора",
      "прямое напряжение светодиода",
      "электронный калькулятор",
    ],
    inputs: {
      supplyVoltage: {
        label: "Напряжение питания (В)",
        help: "Постоянное напряжение источника питания (например, 5В для USB, 12В для автомобильных схем).",
      },
      forwardVoltage: {
        label: "Прямое напряжение светодиода (В)",
        help: "Падение напряжения на одном светодиоде в проводящем состоянии (типично: красный=2,0В, синий/белый=3,2В).",
      },
      forwardCurrentMa: {
        label: "Желаемый ток (мА)",
        help: "Целевой рабочий ток светодиода в миллиамперах. Большинство стандартных светодиодов работают при 20 мА.",
      },
      ledCount: {
        label: "Количество светодиодов в цепи",
        help: "Количество последовательно соединённых светодиодов на одном резисторе.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "Точное сопротивление (Ом)",
        help: "Рассчитанное значение резистора по закону Ома: R = (Vпит - Vпр×n) / I.",
      },
      standardResistanceOhm: {
        label: "Стандартное сопротивление E12 (Ом)",
        help: "Ближайшее стандартное значение ряда E12 с округлением вверх — обеспечивает меньший безопасный ток для светодиода.",
      },
      powerDissipatedW: {
        label: "Рассеиваемая мощность (Вт)",
        help: "Тепло, выделяемое резистором: P = (Vпит - Vпр×n) × I. Используйте резистор с мощностью вдвое больше расчётной.",
      },
      actualCurrentMa: {
        label: "Фактический ток со стандартным резистором (мА)",
        help: "Реальный ток светодиода при использовании стандартного резистора ряда E12.",
      },
      resistorColorCode: {
        label: "Цветовой код резистора",
        help: "4-полосный цветовой код стандартного резистора E12 (полоса допуска = золотая ±5%).",
      },
    },
    errors: {
      supplyTooLow: "Напряжение питания должно быть больше суммарного прямого напряжения светодиодов.",
    },
    faq: [
      {
        q: "Почему светодиодам нужен токоограничивающий резистор?",
        a: "Светодиоды имеют очень низкое внутреннее сопротивление. Без последовательного резистора даже небольшое увеличение напряжения вызывает большой скачок тока, который может необратимо повредить светодиод.",
      },
      {
        q: "Что такое ряд резисторов E12?",
        a: "E12 — это стандартный набор 12 предпочтительных значений сопротивлений на декаду, определённый EIA. Значения расположены примерно равномерно в логарифмическом масштабе.",
      },
      {
        q: "Какую мощность выбрать для резистора?",
        a: "Всегда выбирайте мощность резистора не менее чем вдвое больше расчётной рассеиваемой мощности. Если калькулятор показывает 0,08 Вт, используйте резистор на 0,25 Вт.",
      },
    ],
  },

  zh: {
    title: "LED限流电阻计算器",
    short: "计算LED电路所需的限流电阻值。",
    description:
      "免费LED电阻计算器。输入电源电压、LED正向电压和所需电流，获取精确值和E12标准电阻值、功耗及色环代码。",
    keywords: [
      "LED电阻计算器",
      "限流电阻",
      "LED电路",
      "E12电阻系列",
      "电阻色环",
      "LED正向电压",
      "电子计算器",
    ],
    inputs: {
      supplyVoltage: {
        label: "电源电压（V）",
        help: "电源的直流电压（如USB为5V，汽车电路为12V）。",
      },
      forwardVoltage: {
        label: "LED正向电压（V）",
        help: "单个LED导通时的电压降（典型值：红色=2.0V，蓝色/白色=3.2V）。",
      },
      forwardCurrentMa: {
        label: "目标电流（mA）",
        help: "LED工作电流目标值（毫安）。大多数标准LED工作电流为20mA。",
      },
      ledCount: {
        label: "串联LED数量",
        help: "连接在同一电阻上的串联LED数量。",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "精确电阻值（Ω）",
        help: "根据欧姆定律计算的电阻值：R = (V供电 - V正向×n) / I。",
      },
      standardResistanceOhm: {
        label: "E12标准电阻值（Ω）",
        help: "向上取整的最近E12标准值——为LED提供较低的安全电流。",
      },
      powerDissipatedW: {
        label: "功率耗散（W）",
        help: "电阻产生的热量：P = (V供电 - V正向×n) × I。选择额定功率为计算值两倍的电阻。",
      },
      actualCurrentMa: {
        label: "使用标准电阻的实际电流（mA）",
        help: "使用E12标准电阻值时LED的实际电流。",
      },
      resistorColorCode: {
        label: "电阻色环代码",
        help: "E12标准电阻的4色环代码（容差色环=金色±5%）。",
      },
    },
    errors: {
      supplyTooLow: "电源电压必须大于LED正向总电压。",
    },
    faq: [
      {
        q: "为什么LED需要限流电阻？",
        a: "LED的内阻非常低。没有串联电阻，即使电压轻微升高也会引起大电流冲击，永久损坏LED。",
      },
      {
        q: "什么是E12电阻系列？",
        a: "E12是EIA定义的每十倍频程12个优选电阻值的标准系列，这些值在对数坐标上大致均匀分布。",
      },
      {
        q: "应选择多大功率的电阻？",
        a: "始终选择额定功率至少为计算功耗两倍的电阻。例如计算器显示0.08W，则使用0.25W电阻。",
      },
    ],
  },

  ja: {
    title: "LED抵抗計算機",
    short: "LED回路に必要な電流制限抵抗を計算します。",
    description:
      "無料のLED抵抗計算機。電源電圧・LEDの順方向電圧・目標電流を入力するだけで、正確な抵抗値とE12標準値、電力損失、カラーコードが分かります。",
    keywords: [
      "LED抵抗計算機",
      "電流制限抵抗",
      "LED回路",
      "E12抵抗シリーズ",
      "抵抗カラーコード",
      "LED順方向電圧",
      "電子回路計算",
    ],
    inputs: {
      supplyVoltage: {
        label: "電源電圧（V）",
        help: "電源のDC電圧（例：USBは5V、車載回路は12V）。",
      },
      forwardVoltage: {
        label: "LED順方向電圧（V）",
        help: "LEDが導通している際の電圧降下（目安：赤=2.0V、青/白=3.2V）。",
      },
      forwardCurrentMa: {
        label: "目標電流（mA）",
        help: "LEDの動作電流の目標値（ミリアンペア）。一般的なLEDは20mAで動作します。",
      },
      ledCount: {
        label: "直列接続LED数",
        help: "同じ抵抗に直列接続されているLEDの数。",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "計算抵抗値（Ω）",
        help: "オームの法則による計算値：R = (V電源 - V順方向×n) / I。",
      },
      standardResistanceOhm: {
        label: "E12標準抵抗値（Ω）",
        help: "切り上げた最近接E12標準値——LEDに対して安全な低電流を提供します。",
      },
      powerDissipatedW: {
        label: "電力損失（W）",
        help: "抵抗が発生させる熱：P = (V電源 - V順方向×n) × I。この値の2倍以上の定格抵抗を使用してください。",
      },
      actualCurrentMa: {
        label: "標準抵抗使用時の実電流（mA）",
        help: "E12標準抵抗値使用時のLED実電流。",
      },
      resistorColorCode: {
        label: "抵抗カラーコード",
        help: "E12標準抵抗の4バンドカラーコード（許容差バンド＝金色±5%）。",
      },
    },
    errors: {
      supplyTooLow: "電源電圧はLEDの合計順方向電圧より大きくなければなりません。",
    },
    faq: [
      {
        q: "LEDに電流制限抵抗が必要なのはなぜですか？",
        a: "LEDは内部抵抗が非常に低いため、直列抵抗がないと電圧が少し上がるだけで大電流が流れ、LEDが永久に破損します。",
      },
      {
        q: "E12抵抗シリーズとは何ですか？",
        a: "E12はEIAが定義した、1桁あたり12個の優先抵抗値の標準セットです。これらの値は対数スケール上でほぼ等間隔に並んでいます。",
      },
      {
        q: "抵抗の定格電力はどう選びますか？",
        a: "計算した電力損失の少なくとも2倍の定格電力を持つ抵抗を選んでください。例えば0.08Wなら0.25Wの抵抗を使います。",
      },
    ],
  },

  ko: {
    title: "LED 저항 계산기",
    short: "LED 회로에 필요한 전류 제한 저항을 계산하세요.",
    description:
      "무료 LED 저항 계산기. 공급 전압, LED 순방향 전압, 원하는 전류를 입력하면 정확한 값과 E12 표준 저항값, 소비 전력, 색상 코드를 확인할 수 있습니다.",
    keywords: [
      "LED 저항 계산기",
      "전류 제한 저항",
      "LED 회로",
      "E12 저항 시리즈",
      "저항 색상 코드",
      "LED 순방향 전압",
      "전자 계산기",
    ],
    inputs: {
      supplyVoltage: {
        label: "공급 전압(V)",
        help: "전원 공급 장치의 DC 전압(예: USB는 5V, 자동차 회로는 12V).",
      },
      forwardVoltage: {
        label: "LED 순방향 전압(V)",
        help: "단일 LED가 도통될 때의 전압 강하(전형적: 빨간색=2.0V, 파란색/흰색=3.2V).",
      },
      forwardCurrentMa: {
        label: "원하는 전류(mA)",
        help: "목표 LED 동작 전류(밀리암페어). 대부분의 표준 LED는 20mA로 동작합니다.",
      },
      ledCount: {
        label: "직렬 LED 수",
        help: "동일한 저항에 직렬로 연결된 LED 수.",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "정확한 저항값(Ω)",
        help: "옴의 법칙으로 계산된 저항값: R = (V공급 - V순방향×n) / I.",
      },
      standardResistanceOhm: {
        label: "E12 표준 저항값(Ω)",
        help: "올림한 가장 가까운 E12 표준값 — LED에 안전한 낮은 전류를 제공합니다.",
      },
      powerDissipatedW: {
        label: "소비 전력(W)",
        help: "저항이 발생시키는 열: P = (V공급 - V순방향×n) × I. 이 값의 2배 이상 정격 저항을 사용하세요.",
      },
      actualCurrentMa: {
        label: "표준 저항 사용 시 실제 전류(mA)",
        help: "E12 표준 저항값 사용 시 LED의 실제 전류.",
      },
      resistorColorCode: {
        label: "저항 색상 코드",
        help: "E12 표준 저항의 4밴드 색상 코드(허용 오차 밴드 = 금색 ±5%).",
      },
    },
    errors: {
      supplyTooLow: "공급 전압은 LED 총 순방향 전압보다 커야 합니다.",
    },
    faq: [
      {
        q: "LED에 전류 제한 저항이 필요한 이유는 무엇인가요?",
        a: "LED는 내부 저항이 매우 낮습니다. 직렬 저항 없이는 전압이 조금만 상승해도 큰 전류가 흘러 LED가 영구적으로 손상될 수 있습니다.",
      },
      {
        q: "E12 저항 시리즈란 무엇인가요?",
        a: "E12는 EIA가 정의한 10배 구간당 12개의 선호 저항값의 표준 세트입니다. 이 값들은 로그 스케일에서 거의 균등하게 배치되어 있습니다.",
      },
      {
        q: "저항에 어떤 정격 전력을 선택해야 하나요?",
        a: "계산된 소비 전력의 최소 2배 이상의 정격 전력을 가진 저항을 선택하세요. 계산기가 0.08W를 표시하면 0.25W 저항을 사용하세요.",
      },
    ],
  },

  hi: {
    title: "LED रेसिस्टर कैलकुलेटर",
    short: "अपने LED सर्किट के लिए सही करंट-लिमिटिंग रेसिस्टर की गणना करें।",
    description:
      "मुफ़्त LED रेसिस्टर कैलकुलेटर। सप्लाई वोल्टेज, LED फॉरवर्ड वोल्टेज और वांछित करंट दर्ज करें और सटीक तथा मानक E12 रेसिस्टर मान, बिजली हानि और रंग कोड प्राप्त करें।",
    keywords: [
      "LED रेसिस्टर कैलकुलेटर",
      "करंट लिमिटिंग रेसिस्टर",
      "LED सर्किट",
      "E12 रेसिस्टर सीरीज",
      "रेसिस्टर रंग कोड",
      "LED फॉरवर्ड वोल्टेज",
      "इलेक्ट्रॉनिक्स कैलकुलेटर",
    ],
    inputs: {
      supplyVoltage: {
        label: "सप्लाई वोल्टेज (V)",
        help: "आपकी पावर सप्लाई का DC वोल्टेज (जैसे USB के लिए 5V, कार सर्किट के लिए 12V)।",
      },
      forwardVoltage: {
        label: "LED फॉरवर्ड वोल्टेज (V)",
        help: "एकल LED पर कंडक्शन के दौरान वोल्टेज ड्रॉप (सामान्य: लाल=2.0V, नीला/सफेद=3.2V)।",
      },
      forwardCurrentMa: {
        label: "वांछित करंट (mA)",
        help: "LED का लक्ष्य ऑपरेटिंग करंट मिलीएम्पियर में। अधिकांश मानक LED 20mA पर चलते हैं।",
      },
      ledCount: {
        label: "सीरीज में LED की संख्या",
        help: "एक ही रेसिस्टर पर सीरीज में जुड़े LED की संख्या।",
      },
    },
    outputs: {
      exactResistanceOhm: {
        label: "सटीक रेसिस्टेंस (Ω)",
        help: "ओम के नियम से गणना की गई रेसिस्टर मान: R = (Vसप्लाई - Vफॉरवर्ड×n) / I।",
      },
      standardResistanceOhm: {
        label: "मानक E12 रेसिस्टेंस (Ω)",
        help: "ऊपर की ओर गोल किया गया निकटतम E12 मानक मान — LED के लिए सुरक्षित कम करंट प्रदान करता है।",
      },
      powerDissipatedW: {
        label: "बिजली हानि (W)",
        help: "रेसिस्टर द्वारा उत्पन्न गर्मी: P = (Vसप्लाई - Vफॉरवर्ड×n) × I। इस मान के 2× रेटिंग वाला रेसिस्टर उपयोग करें।",
      },
      actualCurrentMa: {
        label: "मानक रेसिस्टर के साथ वास्तविक करंट (mA)",
        help: "मानक E12 रेसिस्टर मान उपयोग करने पर LED का वास्तविक करंट।",
      },
      resistorColorCode: {
        label: "रेसिस्टर रंग कोड",
        help: "मानक E12 रेसिस्टर के लिए 4-बैंड रंग कोड (टॉलरेंस बैंड = गोल्ड ±5%)।",
      },
    },
    errors: {
      supplyTooLow: "सप्लाई वोल्टेज कुल LED फॉरवर्ड वोल्टेज से अधिक होना चाहिए।",
    },
    faq: [
      {
        q: "LED को करंट-लिमिटिंग रेसिस्टर की आवश्यकता क्यों होती है?",
        a: "LED का आंतरिक प्रतिरोध बहुत कम होता है। बिना सीरीज रेसिस्टर के, वोल्टेज में थोड़ी सी भी वृद्धि से बड़ा करंट सर्ज हो सकता है जो LED को स्थायी रूप से नष्ट कर सकता है।",
      },
      {
        q: "E12 रेसिस्टर सीरीज क्या है?",
        a: "E12 EIA द्वारा परिभाषित प्रति दशमलव 12 पसंदीदा रेसिस्टर मानों का एक मानक सेट है। ये मान लॉगरिदमिक स्केल पर लगभग समान रूप से वितरित होते हैं।",
      },
      {
        q: "रेसिस्टर के लिए कौन सी पावर रेटिंग चुनूं?",
        a: "हमेशा गणना की गई बिजली हानि से कम से कम दोगुनी पावर रेटिंग वाला रेसिस्टर चुनें। अगर कैलकुलेटर 0.08W दिखाता है, तो 0.25W रेसिस्टर उपयोग करें।",
      },
    ],
  },
};

export default i18n;
