import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "String Escape / Unescape", short: "Escape text for JSON/JavaScript strings or unescape it back.", description: "Free string escape and unescape tool. Escape special characters (quotes, backslashes, newlines, tabs) so text is safe inside a JSON or JavaScript string, or reverse the process. Runs in your browser.", keywords: ["string escape", "unescape string", "json escape", "javascript escape", "backslash escape", "escape quotes"], escape: "Escape", unescape: "Unescape", placeholder: "Enter text…", invalid: "Invalid escape sequence." },
  pt: { title: "String Escape / Unescape", short: "Escape text for JSON/JavaScript strings or unescape it back.", description: "Free string escape and unescape tool. Escape special characters (quotes, backslashes, newlines, tabs) so text is safe inside a JSON or JavaScript string, or reverse the process. Runs in your browser.", keywords: ["string escape", "unescape string", "json escape", "javascript escape", "backslash escape", "escape quotes"], escape: "Escape", unescape: "Unescape", placeholder: "Enter text…", invalid: "Invalid escape sequence." },
  id: { title: "String Escape / Unescape", short: "Escape text for JSON/JavaScript strings or unescape it back.", description: "Free string escape and unescape tool. Escape special characters (quotes, backslashes, newlines, tabs) so text is safe inside a JSON or JavaScript string, or reverse the process. Runs in your browser.", keywords: ["string escape", "unescape string", "json escape", "javascript escape", "backslash escape", "escape quotes"], escape: "Escape", unescape: "Unescape", placeholder: "Enter text…", invalid: "Invalid escape sequence." },

  tr: { title: "Dize Kaçışlama / Kaçışı Çözme", short: "Metni JSON/JavaScript dizeleri için kaçışlayın veya geri çözün.", description: "Ücretsiz dize kaçışlama ve çözme aracı. Özel karakterleri (tırnak, ters eğik çizgi, yeni satır, sekme) kaçışlayarak metni bir JSON veya JavaScript dizesi içinde güvenli hale getirin veya işlemi tersine çevirin. Tarayıcınızda çalışır.", keywords: ["dize kaçışlama", "kaçışı çöz", "json kaçış", "javascript kaçış", "ters eğik çizgi kaçış"], escape: "Kaçışla", unescape: "Kaçışı çöz", placeholder: "Metin girin…", invalid: "Geçersiz kaçış dizisi." },
  de: { title: "String Escapen / Unescapen", short: "Text für JSON-/JavaScript-Strings escapen oder zurück-unescapen.", description: "Kostenloses Tool zum Escapen und Unescapen von Strings. Escapen Sie Sonderzeichen (Anführungszeichen, Backslashes, Zeilenumbrüche, Tabs), damit Text in einem JSON- oder JavaScript-String sicher ist, oder kehren Sie den Vorgang um.", keywords: ["string escapen", "string unescapen", "json escape", "javascript escape", "backslash escape"], escape: "Escapen", unescape: "Unescapen", placeholder: "Text eingeben…", invalid: "Ungültige Escape-Sequenz." },
  fr: { title: "Échapper / Déséchapper une Chaîne", short: "Échappez du texte pour des chaînes JSON/JavaScript ou inversez l'opération.", description: "Outil gratuit d'échappement de chaînes. Échappez les caractères spéciaux (guillemets, antislash, sauts de ligne, tabulations) pour rendre le texte sûr dans une chaîne JSON ou JavaScript, ou inversez l'opération.", keywords: ["échapper chaîne", "déséchapper chaîne", "échappement json", "échappement javascript", "antislash"], escape: "Échapper", unescape: "Déséchapper", placeholder: "Saisissez du texte…", invalid: "Séquence d'échappement non valide." },
  es: { title: "Escapar / Desescapar Cadena", short: "Escapa texto para cadenas JSON/JavaScript o invierte el proceso.", description: "Herramienta gratuita para escapar y desescapar cadenas. Escapa caracteres especiales (comillas, barras invertidas, saltos de línea, tabulaciones) para que el texto sea seguro dentro de una cadena JSON o JavaScript, o invierte el proceso.", keywords: ["escapar cadena", "desescapar cadena", "escape json", "escape javascript", "barra invertida"], escape: "Escapar", unescape: "Desescapar", placeholder: "Introduce texto…", invalid: "Secuencia de escape no válida." },
  it: { title: "Escape / Unescape di Stringa", short: "Esegui l'escape del testo per stringhe JSON/JavaScript o inverti il processo.", description: "Strumento gratuito per escape e unescape di stringhe. Esegui l'escape dei caratteri speciali (virgolette, barre rovesciate, a capo, tab) per rendere il testo sicuro in una stringa JSON o JavaScript, o inverti il processo.", keywords: ["escape stringa", "unescape stringa", "escape json", "escape javascript", "barra rovesciata"], escape: "Escape", unescape: "Unescape", placeholder: "Inserisci testo…", invalid: "Sequenza di escape non valida." },
  ar: { title: "هروب / إلغاء هروب السلسلة", short: "طبّق الهروب على النص لسلاسل JSON/JavaScript أو اعكس العملية.", description: "أداة مجانية لهروب السلاسل وإلغائه. طبّق الهروب على الأحرف الخاصة (علامات الاقتباس، الشرطة المائلة العكسية، الأسطر الجديدة، علامات الجدولة) لجعل النص آمنًا داخل سلسلة JSON أو JavaScript، أو اعكس العملية.", keywords: ["هروب السلسلة", "إلغاء هروب السلسلة", "هروب json", "هروب javascript", "الشرطة العكسية"], escape: "هروب", unescape: "إلغاء الهروب", placeholder: "أدخل نصًا…", invalid: "تسلسل هروب غير صالح." },
  ru: { title: "Экранирование Строки", short: "Экранируйте текст для строк JSON/JavaScript или выполните обратное.", description: "Бесплатный инструмент экранирования строк. Экранируйте спецсимволы (кавычки, обратные слэши, переводы строк, табы), чтобы текст был безопасен внутри строки JSON или JavaScript, или выполните обратную операцию.", keywords: ["экранирование строки", "снятие экранирования", "json экранирование", "javascript экранирование", "обратный слэш"], escape: "Экранировать", unescape: "Снять экранирование", placeholder: "Введите текст…", invalid: "Недопустимая escape-последовательность." },
  zh: { title: "字符串转义 / 反转义", short: "为 JSON/JavaScript 字符串转义文本，或反向还原。", description: "免费的字符串转义和反转义工具。转义特殊字符（引号、反斜杠、换行、制表符），使文本在 JSON 或 JavaScript 字符串中安全，或反向还原。在浏览器中运行。", keywords: ["字符串转义", "反转义字符串", "json转义", "javascript转义", "反斜杠转义"], escape: "转义", unescape: "反转义", placeholder: "输入文本…", invalid: "无效的转义序列。" },
  ja: { title: "文字列エスケープ / アンエスケープ", short: "JSON/JavaScript 文字列用にテキストをエスケープ、または元に戻します。", description: "無料の文字列エスケープ・アンエスケープツール。特殊文字（引用符、バックスラッシュ、改行、タブ）をエスケープして JSON や JavaScript 文字列内で安全にする、またはその逆を行います。ブラウザ内で動作します。", keywords: ["文字列エスケープ", "アンエスケープ", "json エスケープ", "javascript エスケープ", "バックスラッシュ"], escape: "エスケープ", unescape: "アンエスケープ", placeholder: "テキストを入力…", invalid: "無効なエスケープシーケンスです。" },
  ko: { title: "문자열 이스케이프 / 언이스케이프", short: "JSON/JavaScript 문자열용으로 텍스트를 이스케이프하거나 되돌립니다.", description: "무료 문자열 이스케이프/언이스케이프 도구. 특수 문자(따옴표, 백슬래시, 줄바꿈, 탭)를 이스케이프하여 JSON 또는 JavaScript 문자열 안에서 안전하게 만들거나 반대로 되돌립니다. 브라우저에서 실행됩니다.", keywords: ["문자열 이스케이프", "언이스케이프", "json 이스케이프", "javascript 이스케이프", "백슬래시"], escape: "이스케이프", unescape: "언이스케이프", placeholder: "텍스트 입력…", invalid: "잘못된 이스케이프 시퀀스입니다." },
  hi: { title: "स्ट्रिंग एस्केप / अनएस्केप", short: "JSON/JavaScript स्ट्रिंग्स के लिए टेक्स्ट एस्केप करें या वापस अनएस्केप करें।", description: "मुफ्त स्ट्रिंग एस्केप और अनएस्केप टूल। विशेष वर्णों (उद्धरण, बैकस्लैश, नई पंक्ति, टैब) को एस्केप करें ताकि टेक्स्ट JSON या JavaScript स्ट्रिंग में सुरक्षित हो, या प्रक्रिया उलटें। ब्राउज़र में चलता है।", keywords: ["स्ट्रिंग एस्केप", "अनएस्केप स्ट्रिंग", "json एस्केप", "javascript एस्केप", "बैकस्लैश एस्केप"], escape: "एस्केप", unescape: "अनएस्केप", placeholder: "टेक्स्ट दर्ज करें…", invalid: "अमान्य एस्केप अनुक्रम।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
