import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "TC Kimlik No Validator", short: "Validate the checksum of a Turkish national ID number.", description: "Free TC Kimlik No validator. Check whether an 11-digit Turkish national identification number satisfies the official checksum rules — runs entirely in your browser and verifies structure only, not any government registry.", keywords: ["tc kimlik validator", "tc kimlik no doğrulama", "turkish id validator", "tc no kontrol", "turkish identification number"], input: "TC Kimlik No", valid: "Valid TC Kimlik No", invalid: "Invalid TC Kimlik No" },
  tr: { title: "TC Kimlik No Doğrulayıcı", short: "Bir TC Kimlik Numarasının sağlama toplamını doğrulayın.", description: "Ücretsiz TC Kimlik No doğrulayıcı. 11 haneli bir TC Kimlik Numarasının resmi sağlama kurallarını sağlayıp sağlamadığını kontrol edin — tamamen tarayıcınızda çalışır ve yalnızca yapıyı doğrular, herhangi bir devlet kaydını sorgulamaz.", keywords: ["tc kimlik doğrulayıcı", "tc kimlik no doğrulama", "kimlik numarası doğrulama", "tc no kontrol", "tc kimlik kontrol"], input: "TC Kimlik No", valid: "Geçerli TC Kimlik No", invalid: "Geçersiz TC Kimlik No" },
  de: { title: "TC-Kimlik-Validator", short: "Validieren Sie die Prüfsumme einer türkischen Personalausweisnummer.", description: "Kostenloser TC-Kimlik-No-Validator. Prüfen Sie, ob eine 11-stellige türkische Personalausweisnummer den offiziellen Prüfsummenregeln entspricht — läuft vollständig im Browser und prüft nur die Struktur, kein Behördenregister.", keywords: ["tc kimlik validator", "türkische id validator", "tc kimlik prüfen", "türkische personalnummer", "tc no prüfung"], input: "TC Kimlik No", valid: "Gültige TC Kimlik No", invalid: "Ungültige TC Kimlik No" },
  fr: { title: "Validateur TC Kimlik No", short: "Validez la somme de contrôle d'un numéro d'identité national turc.", description: "Validateur TC Kimlik No gratuit. Vérifiez si un numéro d'identité national turc à 11 chiffres respecte les règles de somme de contrôle officielles — fonctionne entièrement dans votre navigateur et ne vérifie que la structure, aucun registre officiel.", keywords: ["validateur tc kimlik", "validateur id turc", "vérification tc kimlik", "numéro identité turc", "vérification tc no"], input: "TC Kimlik No", valid: "TC Kimlik No valide", invalid: "TC Kimlik No invalide" },
  es: { title: "Validador TC Kimlik No", short: "Valida la suma de verificación de un número de identidad nacional turco.", description: "Validador TC Kimlik No gratuito. Comprueba si un número de identidad nacional turco de 11 dígitos cumple las reglas de suma de verificación oficiales — funciona completamente en tu navegador y solo verifica la estructura, ningún registro gubernamental.", keywords: ["validador tc kimlik", "validador id turco", "verificación tc kimlik", "número identidad turco", "verificación tc no"], input: "TC Kimlik No", valid: "TC Kimlik No válido", invalid: "TC Kimlik No no válido" },
  it: { title: "Validatore TC Kimlik No", short: "Valida il checksum di un numero di identità nazionale turco.", description: "Validatore TC Kimlik No gratuito. Verifica se un numero di identità nazionale turco di 11 cifre rispetta le regole di checksum ufficiali — funziona interamente nel browser e verifica solo la struttura, nessun registro governativo.", keywords: ["validatore tc kimlik", "validatore id turco", "verifica tc kimlik", "numero identità turco", "verifica tc no"], input: "TC Kimlik No", valid: "TC Kimlik No valido", invalid: "TC Kimlik No non valido" },
  ar: { title: "أداة التحقق من TC Kimlik", short: "تحقق من المجموع الاختباري لرقم الهوية الوطنية التركية.", description: "أداة تحقق TC Kimlik No مجانية. تحقق مما إذا كان رقم الهوية الوطنية التركية المكون من 11 رقمًا يستوفي قواعد المجموع الاختباري الرسمية — يعمل بالكامل في متصفحك ويتحقق من البنية فقط، وليس من أي سجل حكومي.", keywords: ["تحقق tc kimlik", "تحقق الهوية التركية", "tc kimlik فحص", "رقم الهوية التركي", "tc no فحص"], input: "TC Kimlik No", valid: "TC Kimlik No صالح", invalid: "TC Kimlik No غير صالح" },
  ru: { title: "Валидатор TC Kimlik No", short: "Проверяйте контрольную сумму номера турецкого ID.", description: "Бесплатный валидатор TC Kimlik No. Проверьте, соответствует ли 11-значный номер турецкого национального ID официальным правилам контрольной суммы — работает полностью в браузере и проверяет только структуру, никаких государственных реестров.", keywords: ["валидатор tc kimlik", "валидатор турецкого id", "проверка tc kimlik", "номер турецкого id", "tc no проверка"], input: "TC Kimlik No", valid: "Действительный TC Kimlik No", invalid: "Недействительный TC Kimlik No" },
  zh: { title: "TC Kimlik 验证器", short: "验证土耳其国民身份证号的校验和。", description: "免费的 TC Kimlik No 验证器。检查 11 位土耳其国民身份证号是否符合官方校验和规则——完全在浏览器中运行，仅验证结构，不查询任何政府登记。", keywords: ["tc kimlik 验证器", "土耳其 id 验证器", "tc kimlik 检查", "土耳其身份号", "tc no 检查"], input: "TC Kimlik No", valid: "有效的 TC Kimlik No", invalid: "无效的 TC Kimlik No" },
  ja: { title: "TC Kimlik バリデーター", short: "トルコ国民 ID 番号のチェックサムを検証。", description: "無料の TC Kimlik No バリデーター。11桁のトルコ国民 ID 番号が公式チェックサム規則を満たすかを確認します——すべてブラウザ内で動作し、構造のみを検証し、政府登録は照会しません。", keywords: ["tc kimlik バリデーター", "トルコ id バリデーター", "tc kimlik チェック", "トルコ国民 id 番号", "tc no チェック"], input: "TC Kimlik No", valid: "有効な TC Kimlik No", invalid: "無効な TC Kimlik No" },
  ko: { title: "TC Kimlik 검증기", short: "터키 국민 ID 번호의 체크섬을 검증합니다.", description: "무료 TC Kimlik No 검증기. 11자리 터키 국민 ID 번호가 공식 체크섬 규칙을 만족하는지 확인합니다 — 모두 브라우저에서 실행되며 구조만 검증하고 어떤 정부 등록도 조회하지 않습니다.", keywords: ["tc kimlik 검증기", "터키 id 검증기", "tc kimlik 확인", "터키 국민 id", "tc no 확인"], input: "TC Kimlik No", valid: "유효한 TC Kimlik No", invalid: "잘못된 TC Kimlik No" },
  hi: { title: "TC Kimlik No सत्यापनकर्ता", short: "तुर्की राष्ट्रीय आईडी संख्या के चेकसम को सत्यापित करें।", description: "मुफ्त TC Kimlik No सत्यापनकर्ता। जांचें कि क्या 11-अंकीय तुर्की राष्ट्रीय पहचान संख्या आधिकारिक चेकसम नियमों को संतुष्ट करती है — पूरी तरह आपके ब्राउज़र में चलता है और केवल संरचना सत्यापित करता है, किसी सरकारी रजिस्ट्री से नहीं।", keywords: ["tc kimlik सत्यापनकर्ता", "तुर्की आईडी सत्यापनकर्ता", "tc kimlik जांच", "तुर्की पहचान संख्या", "tc no जांच"], input: "TC Kimlik No", valid: "मान्य TC Kimlik No", invalid: "अमान्य TC Kimlik No" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
