import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Cubic Bezier Editor", short: "Edit a CSS cubic-bezier() easing curve visually.", description: "Free cubic-bezier curve editor. Drag the two control points or pick a preset (ease, ease-in, ease-out, ease-in-out, linear) to build a CSS easing function — copy the cubic-bezier(…) value straight into your transitions.", keywords: ["cubic bezier editor", "easing curve editor", "css cubic bezier", "easing function builder", "transition timing"], preset: "Preset", value: "CSS value", animate: "Animation preview" },
  pt: { title: "Cubic Bezier Editor", short: "Edit a CSS cubic-bezier() easing curve visually.", description: "Free cubic-bezier curve editor. Drag the two control points or pick a preset (ease, ease-in, ease-out, ease-in-out, linear) to build a CSS easing function — copy the cubic-bezier(…) value straight into your transitions.", keywords: ["cubic bezier editor", "easing curve editor", "css cubic bezier", "easing function builder", "transition timing"], preset: "Preset", value: "CSS value", animate: "Animation preview" },
  id: { title: "Cubic Bezier Editor", short: "Edit a CSS cubic-bezier() easing curve visually.", description: "Free cubic-bezier curve editor. Drag the two control points or pick a preset (ease, ease-in, ease-out, ease-in-out, linear) to build a CSS easing function — copy the cubic-bezier(…) value straight into your transitions.", keywords: ["cubic bezier editor", "easing curve editor", "css cubic bezier", "easing function builder", "transition timing"], preset: "Preset", value: "CSS value", animate: "Animation preview" },

  tr: { title: "Cubic Bezier Düzenleyici", short: "Bir CSS cubic-bezier() easing eğrisini görsel olarak düzenleyin.", description: "Ücretsiz cubic-bezier eğri düzenleyici. İki kontrol noktasını sürükleyin veya bir ön ayar seçin (ease, ease-in, ease-out, ease-in-out, linear) ve bir CSS easing fonksiyonu oluşturun — cubic-bezier(…) değerini doğrudan geçişlerinize kopyalayın.", keywords: ["cubic bezier düzenleyici", "easing eğri düzenleyici", "css cubic bezier", "easing fonksiyon oluşturucu", "geçiş zamanlaması"], preset: "Ön ayar", value: "CSS değeri", animate: "Animasyon önizleme" },
  de: { title: "Cubic-Bezier-Editor", short: "Bearbeiten Sie eine CSS-cubic-bezier()-Easing-Kurve visuell.", description: "Kostenloser cubic-bezier-Kurven-Editor. Ziehen Sie die zwei Kontrollpunkte oder wählen Sie ein Preset (ease, ease-in, ease-out, ease-in-out, linear), um eine CSS-Easing-Funktion zu bauen — den cubic-bezier(…)-Wert direkt in Ihre Transitionen kopieren.", keywords: ["cubic bezier editor", "easing kurven editor", "css cubic bezier", "easing funktion builder", "transition timing"], preset: "Preset", value: "CSS-Wert", animate: "Animationsvorschau" },
  fr: { title: "Éditeur Cubic Bezier", short: "Modifiez visuellement une courbe d'easing CSS cubic-bezier().", description: "Éditeur de courbe cubic-bezier gratuit. Faites glisser les deux points de contrôle ou choisissez un preset (ease, ease-in, ease-out, ease-in-out, linear) pour construire une fonction d'easing CSS — copiez la valeur cubic-bezier(…) directement dans vos transitions.", keywords: ["éditeur cubic bezier", "éditeur courbe easing", "css cubic bezier", "constructeur fonction easing", "transition timing"], preset: "Preset", value: "Valeur CSS", animate: "Aperçu animation" },
  es: { title: "Editor Cubic Bezier", short: "Edita visualmente una curva de easing CSS cubic-bezier().", description: "Editor de curva cubic-bezier gratuito. Arrastra los dos puntos de control o elige un preset (ease, ease-in, ease-out, ease-in-out, linear) para construir una función de easing CSS — copia el valor cubic-bezier(…) directamente en tus transiciones.", keywords: ["editor cubic bezier", "editor curva easing", "css cubic bezier", "constructor función easing", "timing transición"], preset: "Preset", value: "Valor CSS", animate: "Vista previa animación" },
  it: { title: "Editor Cubic Bezier", short: "Modifica visivamente una curva di easing CSS cubic-bezier().", description: "Editor di curva cubic-bezier gratuito. Trascina i due punti di controllo o scegli un preset (ease, ease-in, ease-out, ease-in-out, linear) per costruire una funzione di easing CSS — copia il valore cubic-bezier(…) direttamente nelle tue transizioni.", keywords: ["editor cubic bezier", "editor curva easing", "css cubic bezier", "costruttore funzione easing", "timing transizione"], preset: "Preset", value: "Valore CSS", animate: "Anteprima animazione" },
  ar: { title: "محرر Cubic Bezier", short: "حرّر منحنى easing الخاص بـ CSS cubic-bezier() بصريًا.", description: "محرر منحنى cubic-bezier مجاني. اسحب نقطتي التحكم أو اختر إعدادًا مسبقًا (ease، ease-in، ease-out، ease-in-out، linear) لبناء دالة easing CSS — انسخ قيمة cubic-bezier(…) مباشرة إلى انتقالاتك.", keywords: ["محرر cubic bezier", "محرر منحنى easing", "css cubic bezier", "منشئ دالة easing", "توقيت الانتقال"], preset: "إعداد مسبق", value: "قيمة CSS", animate: "معاينة الرسوم المتحركة" },
  ru: { title: "Редактор Cubic Bezier", short: "Визуально редактируйте кривую easing CSS cubic-bezier().", description: "Бесплатный редактор кривой cubic-bezier. Перетаскивайте две контрольные точки или выберите пресет (ease, ease-in, ease-out, ease-in-out, linear), чтобы построить CSS-функцию easing — скопируйте значение cubic-bezier(…) прямо в свои переходы.", keywords: ["редактор cubic bezier", "редактор кривой easing", "css cubic bezier", "конструктор функции easing", "тайминг перехода"], preset: "Пресет", value: "Значение CSS", animate: "Превью анимации" },
  zh: { title: "Cubic Bezier 编辑器", short: "可视化编辑 CSS cubic-bezier() 缓动曲线。", description: "免费的 cubic-bezier 曲线编辑器。拖动两个控制点或选择预设（ease、ease-in、ease-out、ease-in-out、linear）以构建 CSS 缓动函数——将 cubic-bezier(…) 值直接复制到你的过渡中。", keywords: ["cubic bezier 编辑器", "缓动曲线编辑器", "css cubic bezier", "缓动函数构建器", "过渡计时"], preset: "预设", value: "CSS 值", animate: "动画预览" },
  ja: { title: "Cubic Bezier エディター", short: "CSS cubic-bezier() イージングカーブを視覚的に編集。", description: "無料の cubic-bezier カーブエディター。2 つの制御点をドラッグするか、プリセット（ease、ease-in、ease-out、ease-in-out、linear）を選んで CSS イージング関数を構築——cubic-bezier(…) 値をトランジションに直接コピーできます。", keywords: ["cubic bezier エディター", "イージングカーブ エディター", "css cubic bezier", "イージング関数 ビルダー", "トランジション タイミング"], preset: "プリセット", value: "CSS 値", animate: "アニメーションプレビュー" },
  ko: { title: "Cubic Bezier 편집기", short: "CSS cubic-bezier() 이징 곡선을 시각적으로 편집합니다.", description: "무료 cubic-bezier 곡선 편집기. 두 개의 제어점을 드래그하거나 프리셋(ease, ease-in, ease-out, ease-in-out, linear)을 선택해 CSS 이징 함수를 만드세요 — cubic-bezier(…) 값을 트랜지션에 직접 복사하세요.", keywords: ["cubic bezier 편집기", "이징 곡선 편집기", "css cubic bezier", "이징 함수 빌더", "트랜지션 타이밍"], preset: "프리셋", value: "CSS 값", animate: "애니메이션 미리보기" },
  hi: { title: "Cubic Bezier एडिटर", short: "एक CSS cubic-bezier() ईज़िंग कर्व को विज़ुअली संपादित करें।", description: "मुफ्त cubic-bezier कर्व एडिटर। दो नियंत्रण बिंदुओं को खींचें या एक प्रीसेट (ease, ease-in, ease-out, ease-in-out, linear) चुनें और एक CSS ईज़िंग फ़ंक्शन बनाएं — cubic-bezier(…) मान को सीधे अपने ट्रांज़िशन में कॉपी करें।", keywords: ["cubic bezier एडिटर", "ईज़िंग कर्व एडिटर", "css cubic bezier", "ईज़िंग फ़ंक्शन बिल्डर", "ट्रांज़िशन टाइमिंग"], preset: "प्रीसेट", value: "CSS मान", animate: "एनिमेशन प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
