import type { CalculatorI18n } from "@/types/i18n";
const i18n: CalculatorI18n = {
  en: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  tr: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  de: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  fr: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  es: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  it: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  ar: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  ru: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  zh: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  ja: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  ko: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
  hi: {'title': 'Scientific Notation', 'short': 'Scientific Notation', 'description': 'Scientific Notation', 'keywords': ['notation'], 'inputs': {'value': {'label': 'Value'}, 'mode': {'label': 'Mode'}}, 'outputs': {'scientific': {'label': 'Scientific'}, 'standard': {'label': 'Standard'}}, 'errors': {}, 'options': {'mode': {'toScientific': 'Scientific', 'toStandard': 'Standard', 'toEngineering': 'Engineering'}}, 'faq': []},
};
export default i18n;