import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "MAC Address Validator", short: "Validate and normalise an Ethernet MAC address.", description: "Free MAC address validator. Paste any 48-bit MAC (`:`, `-`, `.` or no separators) to verify it and see canonical, Cisco dotted, no-separator and OUI prefix forms, plus unicast/multicast and local/universal flags.", keywords: ["mac address validator", "mac address format", "mac normalizer", "ethernet mac", "oui prefix"], input: "MAC address", canonical: "Canonical (colons)", noSeparator: "No separator", cisco: "Cisco dotted", oui: "OUI prefix", type: "Type", valid: "Valid MAC address", invalid: "Invalid MAC address" },
  tr: { title: "MAC Adresi Doğrulayıcı", short: "Bir Ethernet MAC adresini doğrulayın ve normalleştirin.", description: "Ücretsiz MAC adresi doğrulayıcı. Herhangi bir 48 bitlik MAC'i (`:`, `-`, `.` veya ayırıcısız) yapıştırın ve doğrulayın; kanonik, Cisco noktalı, ayırıcısız ve OUI öneki formlarını ve unicast/multicast ile yerel/evrensel bayrakları görün.", keywords: ["mac adresi doğrulayıcı", "mac adresi formatı", "mac normalleştirici", "ethernet mac", "oui öneki"], input: "MAC adresi", canonical: "Kanonik (iki nokta)", noSeparator: "Ayırıcısız", cisco: "Cisco noktalı", oui: "OUI öneki", type: "Tür", valid: "Geçerli MAC adresi", invalid: "Geçersiz MAC adresi" },
  de: { title: "MAC-Adresse-Validator", short: "Validieren und normalisieren Sie eine Ethernet-MAC-Adresse.", description: "Kostenloser MAC-Adressen-Validator. Fügen Sie eine beliebige 48-Bit-MAC ein (`:`, `-`, `.` oder ohne Trennzeichen), um sie zu verifizieren und kanonische, Cisco-Dotted-, separator-lose und OUI-Präfix-Formen sowie Unicast/Multicast- und lokale/universelle Flags zu sehen.", keywords: ["mac adresse validator", "mac adressformat", "mac normalisierer", "ethernet mac", "oui präfix"], input: "MAC-Adresse", canonical: "Kanonisch (Doppelpunkte)", noSeparator: "Ohne Trennzeichen", cisco: "Cisco Dotted", oui: "OUI-Präfix", type: "Typ", valid: "Gültige MAC-Adresse", invalid: "Ungültige MAC-Adresse" },
  fr: { title: "Validateur d'Adresse MAC", short: "Validez et normalisez une adresse MAC Ethernet.", description: "Validateur d'adresse MAC gratuit. Collez n'importe quelle MAC 48 bits (`:`, `-`, `.` ou sans séparateur) pour la vérifier et voir les formes canonique, Cisco pointée, sans séparateur et préfixe OUI, plus les drapeaux unicast/multicast et local/universel.", keywords: ["validateur adresse mac", "format adresse mac", "normaliseur mac", "mac ethernet", "préfixe oui"], input: "Adresse MAC", canonical: "Canonique (deux-points)", noSeparator: "Sans séparateur", cisco: "Cisco pointée", oui: "Préfixe OUI", type: "Type", valid: "Adresse MAC valide", invalid: "Adresse MAC invalide" },
  es: { title: "Validador de Dirección MAC", short: "Valida y normaliza una dirección MAC Ethernet.", description: "Validador de dirección MAC gratuito. Pega cualquier MAC de 48 bits (`:`, `-`, `.` o sin separador) para verificarla y ver las formas canónica, Cisco con puntos, sin separador y prefijo OUI, además de banderas unicast/multicast y local/universal.", keywords: ["validador dirección mac", "formato dirección mac", "normalizador mac", "mac ethernet", "prefijo oui"], input: "Dirección MAC", canonical: "Canónica (dos puntos)", noSeparator: "Sin separador", cisco: "Cisco con puntos", oui: "Prefijo OUI", type: "Tipo", valid: "Dirección MAC válida", invalid: "Dirección MAC inválida" },
  it: { title: "Validatore di Indirizzo MAC", short: "Valida e normalizza un indirizzo MAC Ethernet.", description: "Validatore di indirizzo MAC gratuito. Incolla qualsiasi MAC a 48 bit (`:`, `-`, `.` o senza separatore) per verificarlo e vedere le forme canonica, Cisco puntata, senza separatore e prefisso OUI, oltre alle bandiere unicast/multicast e locale/universale.", keywords: ["validatore indirizzo mac", "formato indirizzo mac", "normalizzatore mac", "mac ethernet", "prefisso oui"], input: "Indirizzo MAC", canonical: "Canonico (due punti)", noSeparator: "Senza separatore", cisco: "Cisco puntato", oui: "Prefisso OUI", type: "Tipo", valid: "Indirizzo MAC valido", invalid: "Indirizzo MAC non valido" },
  ar: { title: "أداة التحقق من عنوان MAC", short: "تحقق ووحّد عنوان MAC إيثرنت.", description: "أداة تحقق MAC مجانية. الصق أي MAC بـ 48 بت (`:` أو `-` أو `.` أو بدون فواصل) للتحقق منه ورؤية الأشكال القياسية و Cisco النقطية وبدون فاصل وبادئة OUI، بالإضافة إلى أعلام unicast/multicast و local/universal.", keywords: ["تحقق عنوان mac", "تنسيق عنوان mac", "موحّد mac", "mac إيثرنت", "بادئة oui"], input: "عنوان MAC", canonical: "قياسي (نقطتان)", noSeparator: "بدون فاصل", cisco: "Cisco نقطي", oui: "بادئة OUI", type: "النوع", valid: "عنوان MAC صالح", invalid: "عنوان MAC غير صالح" },
  ru: { title: "Валидатор MAC-адреса", short: "Проверяйте и нормализуйте Ethernet MAC-адрес.", description: "Бесплатный валидатор MAC-адреса. Вставьте любой 48-битный MAC (`:`, `-`, `.` или без разделителей), чтобы проверить и увидеть канонический, Cisco точечный, без разделителей и OUI-префиксный форматы, плюс флаги unicast/multicast и локальный/универсальный.", keywords: ["валидатор mac адреса", "формат mac адреса", "нормализатор mac", "ethernet mac", "oui префикс"], input: "MAC-адрес", canonical: "Канонический (двоеточия)", noSeparator: "Без разделителя", cisco: "Cisco с точками", oui: "OUI префикс", type: "Тип", valid: "Действительный MAC", invalid: "Недействительный MAC" },
  zh: { title: "MAC 地址验证器", short: "验证并规范化 Ethernet MAC 地址。", description: "免费的 MAC 地址验证器。粘贴任何 48 位 MAC（`:`、`-`、`.` 或无分隔符）以验证并查看规范、Cisco 点分、无分隔符和 OUI 前缀形式，以及单播/组播和本地/全球标志。", keywords: ["mac 地址验证器", "mac 地址格式", "mac 规范化", "以太网 mac", "oui 前缀"], input: "MAC 地址", canonical: "规范（冒号）", noSeparator: "无分隔符", cisco: "Cisco 点分", oui: "OUI 前缀", type: "类型", valid: "有效 MAC 地址", invalid: "无效 MAC 地址" },
  ja: { title: "MAC アドレス バリデーター", short: "Ethernet MAC アドレスを検証して正規化。", description: "無料の MAC アドレス バリデーター。48ビット MAC（`:`、`-`、`.`、または区切り文字なし）を貼り付けて検証し、正規形、Cisco ドット形、区切りなし、OUI プレフィックスの各形と、unicast/multicast およびローカル/ユニバーサルフラグを確認できます。", keywords: ["mac アドレス バリデーター", "mac アドレス フォーマット", "mac 正規化", "ethernet mac", "oui プレフィックス"], input: "MAC アドレス", canonical: "正規形（コロン）", noSeparator: "区切りなし", cisco: "Cisco ドット形", oui: "OUI プレフィックス", type: "種類", valid: "有効な MAC アドレス", invalid: "無効な MAC アドレス" },
  ko: { title: "MAC 주소 검증기", short: "이더넷 MAC 주소를 검증하고 정규화합니다.", description: "무료 MAC 주소 검증기. 48비트 MAC(`:`, `-`, `.` 또는 구분자 없음)을 붙여넣어 검증하고 표준, Cisco 점 형식, 구분자 없음, OUI 접두사 형식과 unicast/multicast 및 로컬/유니버설 플래그를 확인하세요.", keywords: ["mac 주소 검증기", "mac 주소 형식", "mac 정규화", "이더넷 mac", "oui 접두사"], input: "MAC 주소", canonical: "표준 (콜론)", noSeparator: "구분자 없음", cisco: "Cisco 점 형식", oui: "OUI 접두사", type: "유형", valid: "유효한 MAC 주소", invalid: "잘못된 MAC 주소" },
  hi: { title: "MAC एड्रेस वैलिडेटर", short: "ईथरनेट MAC एड्रेस को सत्यापित और सामान्य करें।", description: "मुफ्त MAC एड्रेस वैलिडेटर। किसी भी 48-बिट MAC (`:`, `-`, `.` या बिना सेपरेटर) पेस्ट करें ताकि उसे सत्यापित कर सकें और कैनोनिकल, Cisco डॉटेड, बिना सेपरेटर और OUI उपसर्ग फॉर्म तथा unicast/multicast और स्थानीय/सार्वभौमिक झंडे देख सकें।", keywords: ["mac एड्रेस वैलिडेटर", "mac एड्रेस फॉर्मेट", "mac सामान्यीकरण", "ईथरनेट mac", "oui उपसर्ग"], input: "MAC एड्रेस", canonical: "कैनोनिकल (कोलन)", noSeparator: "बिना सेपरेटर", cisco: "Cisco डॉटेड", oui: "OUI उपसर्ग", type: "प्रकार", valid: "मान्य MAC एड्रेस", invalid: "अमान्य MAC एड्रेस" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
