import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Line Numberer", short: "Add sequential line numbers to a list of lines.", description: "Free line numbering tool. Prefix every line with a number, choosing the starting value, step and separator. Useful for numbered lists, references and code snippets. Runs in your browser.", keywords: ["add line numbers", "line numberer", "number lines", "numbered list", "line numbering"], placeholder: "Paste lines to number…", start: "Start at", step: "Step", separator: "Separator" },
  nl: { title: "Line Nummerer", short: "Add sequential line nummers to a list of lines.", description: "Gratis line nummering tool. Prefix every line with a nummer, choosing the starting value, step and separator. Useful for nummered lists, references and code snippets. Runs in uw browser.", keywords: ["add line nummers", "line nummerer", "nummer lines", "nummered list", "line nummering"], placeholder: "Paste lines to nummer…", start: "Start at", step: "Step", separator: "Separator" },

  pl: { title: "Line Liczbaer", short: "Add sequential line liczbas to a list of lines.", description: "Darmowy line liczbaing narzędzie. Prefix every line with a liczba, choosing the starting value, step and separator. Useful for liczbaed lists, references and kod snippets. Runs w Twojej przeglądarce.", keywords: ["add line liczbas", "line liczbaer", "liczba lines", "liczbaed list", "line liczbaing"], placeholder: "Paste lines to liczba…", start: "Start at", step: "Step", separator: "Separator" },
  pt: { title: "Line Numberer", short: "Add sequential line numbers para a list de lines.", description: "Gratuito - line numbering tool. Prefix every line com a number, choosing the starting value, step e separator. Useful para numbered lists, references e code snippets. Runs no seu navegador.", keywords: ["add line numbers", "line numberer", "number lines", "numbered list", "line numbering"], placeholder: "Paste lines to number…", start: "Start at", step: "Step", separator: "Separator" },
  id: { title: "Line Numberer", short: "Add sequential line numbers to a list dari lines.", description: "Gratis - line numbering tool. Prefix every line with a number, choosing the starting value, step dan separator. Useful for numbered lists, references dan code snippets. Runs di browser Anda.", keywords: ["add line numbers", "line numberer", "number lines", "numbered list", "line numbering"], placeholder: "Paste lines to number…", start: "Start at", step: "Step", separator: "Separator" },

  tr: { title: "Satır Numaralandırıcı", short: "Bir satır listesine sıralı satır numaraları ekleyin.", description: "Ücretsiz satır numaralandırma aracı. Her satırın başına bir numara ekleyin; başlangıç değeri, adım ve ayırıcıyı seçin. Numaralı listeler, kaynaklar ve kod parçacıkları için kullanışlı. Tarayıcınızda çalışır.", keywords: ["satır numarası ekle", "satır numaralandırıcı", "satırları numaralandır", "numaralı liste"], placeholder: "Numaralandırılacak satırları yapıştırın…", start: "Başlangıç", step: "Adım", separator: "Ayırıcı" },
  de: { title: "Zeilennummerierer", short: "Fügen Sie einer Zeilenliste fortlaufende Zeilennummern hinzu.", description: "Kostenloses Zeilennummerierungs-Tool. Stellen Sie jeder Zeile eine Nummer voran, mit wählbarem Startwert, Schritt und Trennzeichen. Nützlich für nummerierte Listen, Referenzen und Code.", keywords: ["zeilennummern hinzufügen", "zeilennummerierer", "zeilen nummerieren", "nummerierte liste"], placeholder: "Zu nummerierende Zeilen einfügen…", start: "Beginn bei", step: "Schritt", separator: "Trennzeichen" },
  fr: { title: "Numéroteur de Lignes", short: "Ajoutez des numéros de ligne séquentiels à une liste de lignes.", description: "Outil de numérotation de lignes gratuit. Préfixez chaque ligne d'un numéro, en choisissant la valeur de départ, le pas et le séparateur. Utile pour les listes numérotées, références et extraits de code.", keywords: ["ajouter numéros de ligne", "numéroteur de lignes", "numéroter lignes", "liste numérotée"], placeholder: "Collez les lignes à numéroter…", start: "Commencer à", step: "Pas", separator: "Séparateur" },
  es: { title: "Numerador de Líneas", short: "Añade números de línea secuenciales a una lista de líneas.", description: "Herramienta de numeración de líneas gratuita. Antepón un número a cada línea, eligiendo el valor inicial, el paso y el separador. Útil para listas numeradas, referencias y fragmentos de código.", keywords: ["añadir números de línea", "numerador de líneas", "numerar líneas", "lista numerada"], placeholder: "Pega las líneas a numerar…", start: "Empezar en", step: "Paso", separator: "Separador" },
  it: { title: "Numeratore di Righe", short: "Aggiungi numeri di riga sequenziali a un elenco di righe.", description: "Strumento di numerazione righe gratuito. Anteponi un numero a ogni riga, scegliendo valore iniziale, passo e separatore. Utile per elenchi numerati, riferimenti e snippet di codice.", keywords: ["aggiungi numeri di riga", "numeratore di righe", "numerare righe", "elenco numerato"], placeholder: "Incolla le righe da numerare…", start: "Inizia da", step: "Passo", separator: "Separatore" },
  ar: { title: "مُرقّم الأسطر", short: "أضف أرقام أسطر متسلسلة إلى قائمة أسطر.", description: "أداة ترقيم أسطر مجانية. ضع رقمًا قبل كل سطر، مع اختيار القيمة الأولية والخطوة والفاصل. مفيدة للقوائم المرقمة والمراجع ومقاطع الشيفرة. تعمل في متصفحك.", keywords: ["إضافة أرقام الأسطر", "مرقم الأسطر", "ترقيم الأسطر", "قائمة مرقمة"], placeholder: "الصق الأسطر للترقيم…", start: "البدء من", step: "الخطوة", separator: "الفاصل" },
  ru: { title: "Нумератор Строк", short: "Добавьте последовательные номера строк к списку строк.", description: "Бесплатный инструмент нумерации строк. Добавьте номер перед каждой строкой, выбрав начальное значение, шаг и разделитель. Полезно для нумерованных списков, ссылок и фрагментов кода.", keywords: ["добавить номера строк", "нумератор строк", "нумеровать строки", "нумерованный список"], placeholder: "Вставьте строки для нумерации…", start: "Начать с", step: "Шаг", separator: "Разделитель" },
  zh: { title: "行号添加器", short: "为一组行添加连续的行号。", description: "免费的行号添加工具。在每行前添加编号，可选择起始值、步长和分隔符。适合编号列表、引用和代码片段。在浏览器中运行。", keywords: ["添加行号", "行号添加器", "行编号", "编号列表"], placeholder: "粘贴要编号的行…", start: "起始值", step: "步长", separator: "分隔符" },
  ja: { title: "行番号付与ツール", short: "行のリストに連番の行番号を付けます。", description: "無料の行番号付与ツール。各行の先頭に番号を付けます。開始値・ステップ・区切り文字を選べます。番号付きリスト、参照、コードスニペットに便利。ブラウザ内で動作します。", keywords: ["行番号を付ける", "行番号 付与", "行に番号", "番号付きリスト"], placeholder: "番号を付ける行を貼り付け…", start: "開始番号", step: "ステップ", separator: "区切り" },
  ko: { title: "줄 번호 매기기", short: "줄 목록에 순차적인 줄 번호를 추가합니다.", description: "무료 줄 번호 매기기 도구. 각 줄 앞에 번호를 붙이며 시작 값, 간격, 구분자를 선택할 수 있습니다. 번호 매긴 목록, 참조, 코드 조각에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["줄 번호 추가", "줄 번호 매기기", "줄에 번호", "번호 목록"], placeholder: "번호를 매길 줄을 붙여넣으세요…", start: "시작 값", step: "간격", separator: "구분자" },
  hi: { title: "लाइन नंबरिंग टूल", short: "पंक्तियों की सूची में क्रमिक पंक्ति संख्याएँ जोड़ें।", description: "मुफ्त लाइन नंबरिंग टूल। हर पंक्ति के आगे एक संख्या लगाएं, आरंभिक मान, स्टेप और विभाजक चुनें। नंबर वाली सूची, संदर्भ और कोड स्निपेट के लिए उपयोगी। ब्राउज़र में चलता है।", keywords: ["लाइन नंबर जोड़ें", "लाइन नंबरिंग", "पंक्ति संख्या", "नंबर सूची"], placeholder: "नंबर देने के लिए पंक्तियाँ पेस्ट करें…", start: "से शुरू", step: "स्टेप", separator: "विभाजक" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
