import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Remove Duplicate Lines & Sort", short: "Remove duplicate lines, sort, trim and delete empty lines from a list.", description: "Free line tool. Paste a list to remove duplicate lines, sort alphabetically, trim whitespace, drop empty lines, and ignore case — all at once. Runs in your browser.", keywords: ["remove duplicate lines", "dedupe lines", "sort lines", "unique lines", "delete empty lines", "line tools"], placeholder: "Paste your list, one item per line…", dedupe: "Remove duplicates", trim: "Trim each line", removeEmpty: "Remove empty lines", caseInsensitive: "Ignore case", sort: "Sort", none: "None", asc: "A → Z", desc: "Z → A" },
  tr: { title: "Yinelenen Satırları Kaldır ve Sırala", short: "Bir listeden yinelenen satırları kaldırın, sıralayın, kırpın ve boş satırları silin.", description: "Ücretsiz satır aracı. Bir liste yapıştırın; yinelenen satırları kaldırın, alfabetik sıralayın, boşlukları kırpın, boş satırları silin ve büyük/küçük harf ayrımını yok sayın — hepsi tek seferde. Tarayıcınızda çalışır.", keywords: ["yinelenen satırları kaldır", "satır tekilleştirme", "satırları sırala", "benzersiz satırlar", "boş satırları sil", "satır araçları"], placeholder: "Listenizi yapıştırın, her satıra bir öğe…", dedupe: "Yinelenenleri kaldır", trim: "Her satırı kırp", removeEmpty: "Boş satırları kaldır", caseInsensitive: "Büyük/küçük harf yok say", sort: "Sırala", none: "Yok", asc: "A → Z", desc: "Z → A" },
  de: { title: "Doppelte Zeilen Entfernen & Sortieren", short: "Doppelte Zeilen entfernen, sortieren, trimmen und leere Zeilen löschen.", description: "Kostenloses Zeilen-Tool. Liste einfügen, um doppelte Zeilen zu entfernen, alphabetisch zu sortieren, Leerzeichen zu trimmen, leere Zeilen zu löschen und Groß-/Kleinschreibung zu ignorieren – alles auf einmal.", keywords: ["doppelte zeilen entfernen", "zeilen deduplizieren", "zeilen sortieren", "eindeutige zeilen", "leere zeilen löschen"], placeholder: "Liste einfügen, ein Eintrag pro Zeile…", dedupe: "Duplikate entfernen", trim: "Jede Zeile trimmen", removeEmpty: "Leere Zeilen entfernen", caseInsensitive: "Groß-/Kleinschreibung ignorieren", sort: "Sortieren", none: "Keine", asc: "A → Z", desc: "Z → A" },
  fr: { title: "Supprimer les Doublons & Trier", short: "Supprimez les lignes en double, triez, élaguez et supprimez les lignes vides.", description: "Outil de lignes gratuit. Collez une liste pour supprimer les doublons, trier par ordre alphabétique, élaguer les espaces, supprimer les lignes vides et ignorer la casse — tout en une fois.", keywords: ["supprimer doublons", "dédupliquer lignes", "trier lignes", "lignes uniques", "supprimer lignes vides"], placeholder: "Collez votre liste, un élément par ligne…", dedupe: "Supprimer les doublons", trim: "Élaguer chaque ligne", removeEmpty: "Supprimer les lignes vides", caseInsensitive: "Ignorer la casse", sort: "Trier", none: "Aucun", asc: "A → Z", desc: "Z → A" },
  es: { title: "Eliminar Líneas Duplicadas y Ordenar", short: "Elimina líneas duplicadas, ordena, recorta y borra líneas vacías.", description: "Herramienta de líneas gratuita. Pega una lista para eliminar duplicados, ordenar alfabéticamente, recortar espacios, borrar líneas vacías e ignorar mayúsculas — todo a la vez.", keywords: ["eliminar líneas duplicadas", "deduplicar líneas", "ordenar líneas", "líneas únicas", "borrar líneas vacías"], placeholder: "Pega tu lista, un elemento por línea…", dedupe: "Eliminar duplicados", trim: "Recortar cada línea", removeEmpty: "Eliminar líneas vacías", caseInsensitive: "Ignorar mayúsculas", sort: "Ordenar", none: "Ninguno", asc: "A → Z", desc: "Z → A" },
  it: { title: "Rimuovi Righe Duplicate e Ordina", short: "Rimuovi righe duplicate, ordina, taglia e cancella righe vuote.", description: "Strumento per righe gratuito. Incolla un elenco per rimuovere i duplicati, ordinare alfabeticamente, tagliare gli spazi, eliminare le righe vuote e ignorare le maiuscole — tutto in una volta.", keywords: ["rimuovi righe duplicate", "deduplica righe", "ordina righe", "righe uniche", "elimina righe vuote"], placeholder: "Incolla il tuo elenco, un elemento per riga…", dedupe: "Rimuovi duplicati", trim: "Taglia ogni riga", removeEmpty: "Rimuovi righe vuote", caseInsensitive: "Ignora maiuscole", sort: "Ordina", none: "Nessuno", asc: "A → Z", desc: "Z → A" },
  ar: { title: "إزالة الأسطر المكررة والفرز", short: "أزل الأسطر المكررة، وافرز، وقصّ، واحذف الأسطر الفارغة.", description: "أداة أسطر مجانية. الصق قائمة لإزالة الأسطر المكررة، والفرز أبجديًا، وقص المسافات، وحذف الأسطر الفارغة، وتجاهل حالة الأحرف — كل ذلك دفعة واحدة.", keywords: ["إزالة الأسطر المكررة", "إزالة تكرار الأسطر", "فرز الأسطر", "أسطر فريدة", "حذف الأسطر الفارغة"], placeholder: "الصق قائمتك، عنصر واحد لكل سطر…", dedupe: "إزالة المكررات", trim: "قص كل سطر", removeEmpty: "إزالة الأسطر الفارغة", caseInsensitive: "تجاهل حالة الأحرف", sort: "فرز", none: "بدون", asc: "أ → ي", desc: "ي → أ" },
  ru: { title: "Удалить Повторяющиеся Строки и Сортировать", short: "Удаляйте дубликаты строк, сортируйте, обрезайте и удаляйте пустые строки.", description: "Бесплатный инструмент для строк. Вставьте список, чтобы удалить дубликаты, отсортировать по алфавиту, обрезать пробелы, удалить пустые строки и игнорировать регистр — всё сразу.", keywords: ["удалить дубликаты строк", "дедупликация строк", "сортировка строк", "уникальные строки", "удалить пустые строки"], placeholder: "Вставьте список, по одному элементу в строке…", dedupe: "Удалить дубликаты", trim: "Обрезать каждую строку", removeEmpty: "Удалить пустые строки", caseInsensitive: "Игнорировать регистр", sort: "Сортировать", none: "Нет", asc: "А → Я", desc: "Я → А" },
  zh: { title: "删除重复行并排序", short: "删除重复行、排序、修剪并删除空行。", description: "免费的行工具。粘贴列表即可删除重复行、按字母排序、修剪空格、删除空行并忽略大小写——一次完成。在浏览器中运行。", keywords: ["删除重复行", "行去重", "行排序", "唯一行", "删除空行"], placeholder: "粘贴你的列表，每行一项…", dedupe: "删除重复项", trim: "修剪每行", removeEmpty: "删除空行", caseInsensitive: "忽略大小写", sort: "排序", none: "无", asc: "A → Z", desc: "Z → A" },
  ja: { title: "重複行の削除と並べ替え", short: "重複行の削除、並べ替え、トリム、空行の削除を行います。", description: "無料の行ツール。リストを貼り付けると、重複行の削除、アルファベット順の並べ替え、空白のトリム、空行の削除、大文字小文字の無視を一括で実行できます。", keywords: ["重複行 削除", "行 重複除去", "行 並べ替え", "一意の行", "空行 削除"], placeholder: "リストを貼り付け、1 行に 1 項目…", dedupe: "重複を削除", trim: "各行をトリム", removeEmpty: "空行を削除", caseInsensitive: "大文字小文字を無視", sort: "並べ替え", none: "なし", asc: "A → Z", desc: "Z → A" },
  ko: { title: "중복 줄 제거 및 정렬", short: "중복 줄 제거, 정렬, 공백 제거, 빈 줄 삭제를 수행합니다.", description: "무료 줄 도구. 목록을 붙여넣으면 중복 줄 제거, 알파벳순 정렬, 공백 제거, 빈 줄 삭제, 대소문자 무시를 한 번에 수행합니다. 브라우저에서 실행됩니다.", keywords: ["중복 줄 제거", "줄 중복 제거", "줄 정렬", "고유 줄", "빈 줄 삭제"], placeholder: "목록을 붙여넣으세요. 한 줄에 한 항목…", dedupe: "중복 제거", trim: "각 줄 다듬기", removeEmpty: "빈 줄 제거", caseInsensitive: "대소문자 무시", sort: "정렬", none: "없음", asc: "A → Z", desc: "Z → A" },
  hi: { title: "डुप्लिकेट पंक्तियाँ हटाएं और क्रमबद्ध करें", short: "डुप्लिकेट पंक्तियाँ हटाएं, क्रमबद्ध करें, ट्रिम करें और खाली पंक्तियाँ हटाएं।", description: "मुफ्त लाइन टूल। एक सूची पेस्ट करें और डुप्लिकेट पंक्तियाँ हटाएं, वर्णानुक्रम में क्रमबद्ध करें, स्पेस ट्रिम करें, खाली पंक्तियाँ हटाएं और केस अनदेखा करें — सब एक साथ।", keywords: ["डुप्लिकेट पंक्तियाँ हटाएं", "पंक्ति डीडुप", "पंक्तियाँ क्रमबद्ध", "अद्वितीय पंक्तियाँ", "खाली पंक्तियाँ हटाएं"], placeholder: "अपनी सूची पेस्ट करें, हर पंक्ति में एक आइटम…", dedupe: "डुप्लिकेट हटाएं", trim: "हर पंक्ति ट्रिम करें", removeEmpty: "खाली पंक्तियाँ हटाएं", caseInsensitive: "केस अनदेखा करें", sort: "क्रमबद्ध करें", none: "कोई नहीं", asc: "A → Z", desc: "Z → A" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
