import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "IBAN Validator", short: "Validate any IBAN with the ISO 13616 checksum.", description: "Free IBAN validator. Paste an International Bank Account Number from any country to check its length and mod-97 checksum, view the country code, check digits, BBAN and a nicely formatted version — all in your browser.", keywords: ["iban validator", "validate iban", "iban checker", "iban verify online", "bank account number check"], input: "IBAN", country: "Country", checkDigits: "Check digits", bban: "BBAN", formatted: "Formatted", valid: "Valid IBAN", invalid: "Invalid IBAN" },
  tr: { title: "IBAN Doğrulayıcı", short: "Herhangi bir IBAN'ı ISO 13616 sağlamasıyla doğrulayın.", description: "Ücretsiz IBAN doğrulayıcı. Herhangi bir ülkenin Uluslararası Banka Hesap Numarası'nı yapıştırın; uzunluğunu ve mod-97 sağlamasını kontrol edin, ülke kodu, kontrol haneleri, BBAN ve düzgün biçimlendirilmiş halini görün — tarayıcınızda.", keywords: ["iban doğrulayıcı", "iban doğrula", "iban kontrol", "iban online doğrula", "banka hesap numarası kontrol"], input: "IBAN", country: "Ülke", checkDigits: "Kontrol haneleri", bban: "BBAN", formatted: "Biçimlendirilmiş", valid: "Geçerli IBAN", invalid: "Geçersiz IBAN" },
  de: { title: "IBAN-Validator", short: "Validieren Sie jede IBAN mit der ISO-13616-Prüfsumme.", description: "Kostenloser IBAN-Validator. Fügen Sie eine internationale Bankkontonummer eines beliebigen Landes ein, um Länge und mod-97-Prüfsumme zu prüfen, sowie Ländercode, Prüfziffern, BBAN und eine schön formatierte Version anzuzeigen — alles im Browser.", keywords: ["iban validator", "iban prüfen", "iban checker", "iban online prüfen", "bankkontonummer prüfen"], input: "IBAN", country: "Land", checkDigits: "Prüfziffern", bban: "BBAN", formatted: "Formatiert", valid: "Gültige IBAN", invalid: "Ungültige IBAN" },
  fr: { title: "Validateur IBAN", short: "Validez tout IBAN avec la somme de contrôle ISO 13616.", description: "Validateur IBAN gratuit. Collez un numéro de compte bancaire international de n'importe quel pays pour vérifier sa longueur et sa somme de contrôle mod-97, et voir le code pays, les chiffres de contrôle, le BBAN et une version joliment formatée — le tout dans votre navigateur.", keywords: ["validateur iban", "valider iban", "vérificateur iban", "vérifier iban en ligne", "vérification numéro compte bancaire"], input: "IBAN", country: "Pays", checkDigits: "Chiffres de contrôle", bban: "BBAN", formatted: "Formaté", valid: "IBAN valide", invalid: "IBAN invalide" },
  es: { title: "Validador IBAN", short: "Valida cualquier IBAN con la suma de verificación ISO 13616.", description: "Validador IBAN gratuito. Pega un número de cuenta bancaria internacional de cualquier país para comprobar su longitud y la suma de verificación mod-97, y ver el código de país, dígitos de control, BBAN y una versión bien formateada — todo en tu navegador.", keywords: ["validador iban", "validar iban", "verificador iban", "verificar iban online", "comprobación número cuenta bancaria"], input: "IBAN", country: "País", checkDigits: "Dígitos de control", bban: "BBAN", formatted: "Formateado", valid: "IBAN válido", invalid: "IBAN inválido" },
  it: { title: "Validatore IBAN", short: "Valida qualsiasi IBAN con il checksum ISO 13616.", description: "Validatore IBAN gratuito. Incolla un numero di conto bancario internazionale di qualsiasi paese per verificarne la lunghezza e il checksum mod-97, e visualizzare il codice paese, le cifre di controllo, il BBAN e una versione ben formattata — tutto nel browser.", keywords: ["validatore iban", "validare iban", "controllo iban", "verifica iban online", "verifica numero conto bancario"], input: "IBAN", country: "Paese", checkDigits: "Cifre di controllo", bban: "BBAN", formatted: "Formattato", valid: "IBAN valido", invalid: "IBAN non valido" },
  ar: { title: "أداة التحقق من IBAN", short: "تحقق من أي IBAN باستخدام مجموع التحقق ISO 13616.", description: "أداة تحقق IBAN مجانية. الصق رقم حساب بنكي دولي من أي بلد للتحقق من طوله ومجموع التحقق mod-97، وعرض رمز البلد وأرقام التحقق وBBAN ونسخة منسّقة بشكل أنيق — كل ذلك في متصفحك.", keywords: ["تحقق iban", "التحقق من iban", "فاحص iban", "تحقق iban عبر الإنترنت", "تحقق رقم حساب بنكي"], input: "IBAN", country: "البلد", checkDigits: "أرقام التحقق", bban: "BBAN", formatted: "المنسّق", valid: "IBAN صالح", invalid: "IBAN غير صالح" },
  ru: { title: "Валидатор IBAN", short: "Проверяйте любой IBAN с контрольной суммой ISO 13616.", description: "Бесплатный валидатор IBAN. Вставьте международный номер банковского счёта любой страны, чтобы проверить его длину и контрольную сумму mod-97, увидеть код страны, контрольные цифры, BBAN и аккуратно отформатированную версию — всё в браузере.", keywords: ["валидатор iban", "проверить iban", "проверка iban", "iban онлайн", "проверка номера счёта"], input: "IBAN", country: "Страна", checkDigits: "Контрольные цифры", bban: "BBAN", formatted: "Форматированный", valid: "Действительный IBAN", invalid: "Недействительный IBAN" },
  zh: { title: "IBAN 验证器", short: "使用 ISO 13616 校验和验证任意 IBAN。", description: "免费的 IBAN 验证器。粘贴任何国家的国际银行账号，即可检查其长度和 mod-97 校验和，并查看国家代码、校验位、BBAN 和格式化版本——全部在浏览器中完成。", keywords: ["iban 验证器", "验证 iban", "iban 检查器", "在线验证 iban", "银行账号检查"], input: "IBAN", country: "国家", checkDigits: "校验位", bban: "BBAN", formatted: "格式化", valid: "有效 IBAN", invalid: "无效 IBAN" },
  ja: { title: "IBAN バリデーター", short: "ISO 13616 チェックサムで任意の IBAN を検証。", description: "無料の IBAN バリデーター。任意の国の国際銀行口座番号を貼り付けると、長さと mod-97 チェックサムを確認し、国コード、チェックディジット、BBAN、整形済みバージョンを表示します——すべてブラウザ内で。", keywords: ["iban バリデーター", "iban 検証", "iban チェック", "iban オンライン検証", "銀行口座番号チェック"], input: "IBAN", country: "国", checkDigits: "チェックディジット", bban: "BBAN", formatted: "整形", valid: "有効な IBAN", invalid: "無効な IBAN" },
  ko: { title: "IBAN 검증기", short: "ISO 13616 체크섬으로 모든 IBAN을 검증합니다.", description: "무료 IBAN 검증기. 어느 국가의 국제 은행 계좌 번호든 붙여넣으면 길이와 mod-97 체크섬을 확인하고 국가 코드, 체크 디지트, BBAN, 깔끔하게 포맷된 버전을 표시합니다 — 모두 브라우저에서.", keywords: ["iban 검증기", "iban 검증", "iban 확인", "iban 온라인 확인", "은행 계좌 번호 검사"], input: "IBAN", country: "국가", checkDigits: "체크 디지트", bban: "BBAN", formatted: "포맷됨", valid: "유효한 IBAN", invalid: "잘못된 IBAN" },
  hi: { title: "IBAN सत्यापनकर्ता", short: "ISO 13616 चेकसम के साथ किसी भी IBAN को सत्यापित करें।", description: "मुफ्त IBAN सत्यापनकर्ता। किसी भी देश का अंतर्राष्ट्रीय बैंक खाता संख्या पेस्ट करें ताकि उसकी लंबाई और mod-97 चेकसम जांच सकें, और देश कोड, चेक अंक, BBAN और एक अच्छी तरह से फॉर्मेट किया संस्करण देख सकें — सब आपके ब्राउज़र में।", keywords: ["iban सत्यापनकर्ता", "iban सत्यापित करें", "iban चेकर", "iban ऑनलाइन सत्यापित", "बैंक खाता संख्या जांच"], input: "IBAN", country: "देश", checkDigits: "चेक अंक", bban: "BBAN", formatted: "फॉर्मेटेड", valid: "मान्य IBAN", invalid: "अमान्य IBAN" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
