import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "DMARC Record Checker", short: "Look up and validate a domain's DMARC record.", description: "Free DMARC checker. Look up a domain's _dmarc TXT record, parse its policy (p), subdomain policy, percentage, alignment and rua/ruf reporting addresses, and flag weak policies. Runs in your browser via Cloudflare DoH.", keywords: ["dmarc checker", "dmarc record lookup", "dmarc validator", "email authentication", "dmarc policy"], domain: "Domain", check: "Check", record: "DMARC record", policy: "Policy (p)", subPolicy: "Subdomain policy (sp)", pct: "Percentage (pct)", rua: "Aggregate reports (rua)", ruf: "Forensic reports (ruf)", alignment: "Alignment", noRecord: "No DMARC record found for this domain.", hint: "Enter a domain (e.g. example.com); we look up _dmarc.<domain>." },
  nl: { title: "DMARC Record Controleur", short: "Look up and valideer a domain's DMARC record.", description: "Gratis DMARC controleur. Look up a domain's _dmarc TXT record, parse its policy (p), subdomain policy, percentage, alignment and rua/ruf reporting addresses, and flag weak policies. Runs in uw browser via Cloudflare DoH.", keywords: ["dmarc controleur", "dmarc record lookup", "dmarc validator", "email authentication", "dmarc policy"], domain: "Domain", check: "Controleer", record: "DMARC record", policy: "Policy (p)", subPolicy: "Subdomain policy (sp)", pct: "Percentage (pct)", rua: "Aggregate reports (rua)", ruf: "Forensic reports (ruf)", alignment: "Alignment", noRecord: "No DMARC record found for this domain.", hint: "Enter a domain (e.g. example.com); we look up _dmarc.<domain>." },

  pl: { title: "DMARC Record Sprawdzarka", short: "Look up and waliduj a domain's DMARC record.", description: "Darmowy DMARC sprawdzarka. Look up a domain's _dmarc TXT record, parse its policy (p), subdomain policy, percentage, alignment and rua/ruf reporting addresses, and flag weak policies. Runs w Twojej przeglądarce via Cloudflare DoH.", keywords: ["dmarc sprawdzarka", "dmarc record lookup", "dmarc walidator", "email authentication", "dmarc policy"], domain: "Domain", check: "Sprawdź", record: "DMARC record", policy: "Policy (p)", subPolicy: "Subdomain policy (sp)", pct: "Procent (pct)", rua: "Aggregate reports (rua)", ruf: "Forensic reports (ruf)", alignment: "Alignment", noRecord: "No DMARC record found for this domain.", hint: "Enter a domain (e.g. example.com); we look up _dmarc.<domain>." },
  pt: { title: "Verificador de Registro DMARC", short: "Pesquise e valide o registro DMARC de um domínio.", description: "Verificador DMARC gratuito. Pesquise o registro TXT _dmarc de um domínio, analise sua política (p), política de subdomínio, porcentagem, alinhamento e endereços de relatório rua/ruf, e sinalize políticas fracas. Roda no navegador via Cloudflare DoH.", keywords: ["dmarc checker", "dmarc record lookup", "dmarc validator", "email authentication", "dmarc policy"], domain: "Domínio", check: "Verificar", record: "Registro DMARC", policy: "Política (p)", subPolicy: "Política de subdomínio (sp)", pct: "Porcentagem (pct)", rua: "Relatórios agregados (rua)", ruf: "Relatórios forenses (ruf)", alignment: "Alinhamento", noRecord: "Nenhum registro DMARC encontrado para este domínio.", hint: "Digite um domínio (ex.: example.com); pesquisamos _dmarc.<domínio>." },
  id: { title: "Pemeriksa Rekaman DMARC", short: "Cari dan validasi rekaman DMARC domain.", description: "Pemeriksa DMARC gratis. Cari rekaman TXT _dmarc domain, urai kebijakannya (p), kebijakan subdomain, persentase, penyelarasan, dan alamat laporan rua/ruf, serta tandai kebijakan lemah. Berjalan di browser via Cloudflare DoH.", keywords: ["dmarc checker", "dmarc record lookup", "dmarc validator", "email authentication", "dmarc policy"], domain: "Domain", check: "Periksa", record: "Rekaman DMARC", policy: "Kebijakan (p)", subPolicy: "Kebijakan subdomain (sp)", pct: "Persentase (pct)", rua: "Laporan agregat (rua)", ruf: "Laporan forensik (ruf)", alignment: "Penyelarasan", noRecord: "Tidak ada rekaman DMARC ditemukan untuk domain ini.", hint: "Masukkan domain (mis. example.com); kami mencari _dmarc.<domain>." },

  tr: { title: "DMARC Kaydı Denetleyici", short: "Bir alan adının DMARC kaydını sorgulayın ve doğrulayın.", description: "Ücretsiz DMARC denetleyici. Bir alan adının _dmarc TXT kaydını sorgulayın; politikasını (p), alt alan politikasını, yüzdeyi, hizalamayı ve rua/ruf rapor adreslerini ayrıştırın, zayıf politikaları işaretleyin. Cloudflare DoH üzerinden tarayıcınızda çalışır.", keywords: ["dmarc denetleyici", "dmarc kaydı sorgu", "dmarc doğrulayıcı", "e-posta kimlik doğrulama", "dmarc politikası"], domain: "Alan adı", check: "Denetle", record: "DMARC kaydı", policy: "Politika (p)", subPolicy: "Alt alan politikası (sp)", pct: "Yüzde (pct)", rua: "Toplu raporlar (rua)", ruf: "Adli raporlar (ruf)", alignment: "Hizalama", noRecord: "Bu alan adı için DMARC kaydı bulunamadı.", hint: "Bir alan adı girin (ör. example.com); _dmarc.<alan> sorgulanır." },
  de: { title: "DMARC-Eintrag-Prüfer", short: "DMARC-Eintrag einer Domain abfragen und validieren.", description: "Kostenloser DMARC-Prüfer. Fragen Sie den _dmarc-TXT-Eintrag einer Domain ab, analysieren Sie die Richtlinie (p), Subdomain-Richtlinie, Prozentsatz, Ausrichtung und rua/ruf-Berichtsadressen und markieren Sie schwache Richtlinien. Läuft im Browser über Cloudflare DoH.", keywords: ["dmarc prüfer", "dmarc eintrag abfrage", "dmarc validator", "e-mail authentifizierung", "dmarc richtlinie"], domain: "Domain", check: "Prüfen", record: "DMARC-Eintrag", policy: "Richtlinie (p)", subPolicy: "Subdomain-Richtlinie (sp)", pct: "Prozentsatz (pct)", rua: "Aggregierte Berichte (rua)", ruf: "Forensische Berichte (ruf)", alignment: "Ausrichtung", noRecord: "Kein DMARC-Eintrag für diese Domain gefunden.", hint: "Geben Sie eine Domain ein (z. B. example.com); wir fragen _dmarc.<Domain> ab." },
  fr: { title: "Vérificateur d'Enregistrement DMARC", short: "Recherchez et validez l'enregistrement DMARC d'un domaine.", description: "Vérificateur DMARC gratuit. Recherchez l'enregistrement TXT _dmarc d'un domaine, analysez sa politique (p), la politique de sous-domaine, le pourcentage, l'alignement et les adresses de rapport rua/ruf, et signalez les politiques faibles. Fonctionne dans votre navigateur via Cloudflare DoH.", keywords: ["vérificateur dmarc", "recherche enregistrement dmarc", "validateur dmarc", "authentification email", "politique dmarc"], domain: "Domaine", check: "Vérifier", record: "Enregistrement DMARC", policy: "Politique (p)", subPolicy: "Politique de sous-domaine (sp)", pct: "Pourcentage (pct)", rua: "Rapports agrégés (rua)", ruf: "Rapports forensiques (ruf)", alignment: "Alignement", noRecord: "Aucun enregistrement DMARC trouvé pour ce domaine.", hint: "Saisissez un domaine (ex. example.com) ; nous interrogeons _dmarc.<domaine>." },
  es: { title: "Verificador de Registro DMARC", short: "Consulta y valida el registro DMARC de un dominio.", description: "Verificador DMARC gratuito. Consulta el registro TXT _dmarc de un dominio, analiza su política (p), política de subdominio, porcentaje, alineación y direcciones de informe rua/ruf, y señala políticas débiles. Funciona en tu navegador vía Cloudflare DoH.", keywords: ["verificador dmarc", "consulta registro dmarc", "validador dmarc", "autenticación de correo", "política dmarc"], domain: "Dominio", check: "Verificar", record: "Registro DMARC", policy: "Política (p)", subPolicy: "Política de subdominio (sp)", pct: "Porcentaje (pct)", rua: "Informes agregados (rua)", ruf: "Informes forenses (ruf)", alignment: "Alineación", noRecord: "No se encontró un registro DMARC para este dominio.", hint: "Introduce un dominio (p. ej. example.com); consultamos _dmarc.<dominio>." },
  it: { title: "Verificatore Record DMARC", short: "Cerca e valida il record DMARC di un dominio.", description: "Verificatore DMARC gratuito. Cerca il record TXT _dmarc di un dominio, analizza la sua policy (p), la policy del sottodominio, la percentuale, l'allineamento e gli indirizzi di report rua/ruf, e segnala policy deboli. Funziona nel tuo browser tramite Cloudflare DoH.", keywords: ["verificatore dmarc", "ricerca record dmarc", "validatore dmarc", "autenticazione email", "policy dmarc"], domain: "Dominio", check: "Verifica", record: "Record DMARC", policy: "Policy (p)", subPolicy: "Policy sottodominio (sp)", pct: "Percentuale (pct)", rua: "Report aggregati (rua)", ruf: "Report forensi (ruf)", alignment: "Allineamento", noRecord: "Nessun record DMARC trovato per questo dominio.", hint: "Inserisci un dominio (es. example.com); cerchiamo _dmarc.<dominio>." },
  ar: { title: "فاحص سجل DMARC", short: "ابحث عن سجل DMARC لنطاق وتحقق منه.", description: "فاحص DMARC مجاني. ابحث عن سجل TXT الخاص بـ _dmarc لنطاق، وحلّل سياسته (p)، وسياسة النطاق الفرعي، والنسبة المئوية، والمحاذاة، وعناوين تقارير rua/ruf، وأبرز السياسات الضعيفة. يعمل في متصفحك عبر Cloudflare DoH.", keywords: ["فاحص dmarc", "بحث سجل dmarc", "مدقق dmarc", "مصادقة البريد", "سياسة dmarc"], domain: "النطاق", check: "فحص", record: "سجل DMARC", policy: "السياسة (p)", subPolicy: "سياسة النطاق الفرعي (sp)", pct: "النسبة (pct)", rua: "التقارير المجمّعة (rua)", ruf: "التقارير الجنائية (ruf)", alignment: "المحاذاة", noRecord: "لم يتم العثور على سجل DMARC لهذا النطاق.", hint: "أدخل نطاقًا (مثل example.com)؛ نبحث عن _dmarc.<النطاق>." },
  ru: { title: "Проверка DMARC-записи", short: "Найдите и проверьте DMARC-запись домена.", description: "Бесплатная проверка DMARC. Найдите _dmarc TXT-запись домена, разберите её политику (p), политику поддоменов, процент, выравнивание и адреса отчётов rua/ruf, выявите слабые политики. Работает в браузере через Cloudflare DoH.", keywords: ["проверка dmarc", "поиск dmarc записи", "валидатор dmarc", "аутентификация почты", "политика dmarc"], domain: "Домен", check: "Проверить", record: "DMARC-запись", policy: "Политика (p)", subPolicy: "Политика поддомена (sp)", pct: "Процент (pct)", rua: "Сводные отчёты (rua)", ruf: "Криминалистические отчёты (ruf)", alignment: "Выравнивание", noRecord: "Для этого домена DMARC-запись не найдена.", hint: "Введите домен (например, example.com); мы запросим _dmarc.<домен>." },
  zh: { title: "DMARC 记录检查器", short: "查询并验证域名的 DMARC 记录。", description: "免费的 DMARC 检查器。查询域名的 _dmarc TXT 记录，解析其策略（p）、子域策略、百分比、对齐方式和 rua/ruf 报告地址，并标记弱策略。通过 Cloudflare DoH 在浏览器中运行。", keywords: ["dmarc 检查器", "dmarc 记录查询", "dmarc 验证器", "邮件认证", "dmarc 策略"], domain: "域名", check: "检查", record: "DMARC 记录", policy: "策略 (p)", subPolicy: "子域策略 (sp)", pct: "百分比 (pct)", rua: "汇总报告 (rua)", ruf: "取证报告 (ruf)", alignment: "对齐方式", noRecord: "未找到此域名的 DMARC 记录。", hint: "输入域名（如 example.com）；我们查询 _dmarc.<域名>。" },
  ja: { title: "DMARC レコードチェッカー", short: "ドメインの DMARC レコードを検索・検証します。", description: "無料の DMARC チェッカー。ドメインの _dmarc TXT レコードを検索し、ポリシー（p）、サブドメインポリシー、割合、アラインメント、rua/ruf レポートアドレスを解析し、弱いポリシーを指摘します。Cloudflare DoH を介してブラウザ内で動作します。", keywords: ["dmarc チェッカー", "dmarc レコード 検索", "dmarc 検証", "メール認証", "dmarc ポリシー"], domain: "ドメイン", check: "チェック", record: "DMARC レコード", policy: "ポリシー (p)", subPolicy: "サブドメインポリシー (sp)", pct: "割合 (pct)", rua: "集計レポート (rua)", ruf: "フォレンジックレポート (ruf)", alignment: "アラインメント", noRecord: "このドメインの DMARC レコードは見つかりませんでした。", hint: "ドメイン（例: example.com）を入力します。_dmarc.<ドメイン> を検索します。" },
  ko: { title: "DMARC 레코드 검사기", short: "도메인의 DMARC 레코드를 조회하고 검증합니다.", description: "무료 DMARC 검사기. 도메인의 _dmarc TXT 레코드를 조회하고 정책(p), 하위 도메인 정책, 백분율, 정렬, rua/ruf 보고 주소를 분석하며 약한 정책을 표시합니다. Cloudflare DoH를 통해 브라우저에서 실행됩니다.", keywords: ["dmarc 검사기", "dmarc 레코드 조회", "dmarc 검증기", "이메일 인증", "dmarc 정책"], domain: "도메인", check: "검사", record: "DMARC 레코드", policy: "정책 (p)", subPolicy: "하위 도메인 정책 (sp)", pct: "백분율 (pct)", rua: "집계 보고 (rua)", ruf: "포렌식 보고 (ruf)", alignment: "정렬", noRecord: "이 도메인에 대한 DMARC 레코드를 찾을 수 없습니다.", hint: "도메인(예: example.com)을 입력하세요. _dmarc.<도메인>을 조회합니다." },
  hi: { title: "DMARC रिकॉर्ड चेकर", short: "किसी डोमेन का DMARC रिकॉर्ड देखें और मान्य करें।", description: "मुफ्त DMARC चेकर। किसी डोमेन का _dmarc TXT रिकॉर्ड देखें, उसकी नीति (p), सबडोमेन नीति, प्रतिशत, संरेखण और rua/ruf रिपोर्ट पते पार्स करें, और कमजोर नीतियों को चिह्नित करें। Cloudflare DoH के माध्यम से आपके ब्राउज़र में चलता है।", keywords: ["dmarc चेकर", "dmarc रिकॉर्ड lookup", "dmarc validator", "ईमेल प्रमाणीकरण", "dmarc नीति"], domain: "डोमेन", check: "जाँचें", record: "DMARC रिकॉर्ड", policy: "नीति (p)", subPolicy: "सबडोमेन नीति (sp)", pct: "प्रतिशत (pct)", rua: "समग्र रिपोर्ट (rua)", ruf: "फोरेंसिक रिपोर्ट (ruf)", alignment: "संरेखण", noRecord: "इस डोमेन के लिए कोई DMARC रिकॉर्ड नहीं मिला।", hint: "एक डोमेन दर्ज करें (जैसे example.com); हम _dmarc.<डोमेन> देखते हैं।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
