import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Credit Card Validator (Luhn)", short: "Check a card number with the Luhn algorithm and detect its brand.", description: "Free credit card number validator. Verify whether a card number passes the Luhn checksum and detect its brand (Visa, Mastercard, Amex, Discover and more). Format check only — nothing is sent anywhere.", keywords: ["credit card validator", "luhn check", "card number validator", "luhn algorithm", "card brand detector"], placeholder: "Enter a card number…", valid: "Valid number (passes Luhn)", invalid: "Invalid number (fails Luhn)", brand: "Brand", unknownBrand: "Unknown" },
  nl: { title: "Creditcard Validator (Luhn)", short: "Controleer a card nummer with the Luhn algorithm and detect its brand.", description: "Gratis credit card nummer validator. Verify whether a card nummer passes the Luhn controleersum and detect its brand (Visa, Mastercard, Amex, Discover and more). Formatteer controleer only — nothing is sent anywhere.", keywords: ["credit card validator", "luhn controleer", "card nummer validator", "luhn algorithm", "card brand detector"], placeholder: "Enter a card nummer…", valid: "Valid nummer (passes Luhn)", invalid: "Invalid nummer (fails Luhn)", brand: "Brand", unknownBrand: "Unknown" },

  pl: { title: "Karta Kredytowa Walidator (Luhn)", short: "Sprawdź a card liczba with the Luhn algorithm and detect its brand.", description: "Darmowy credit card liczba walidator. Verify whether a card liczba passes the Luhn sprawdźsum and detect its brand (Visa, Mastercard, Amex, Discover and more). Formatuj sprawdź only — nothing is sent anywhere.", keywords: ["credit card walidator", "luhn sprawdź", "card liczba walidator", "luhn algorithm", "card brand detector"], placeholder: "Enter a card liczba…", valid: "Valid liczba (passes Luhn)", invalid: "Invalid liczba (fails Luhn)", brand: "Brand", unknownBrand: "Unknown" },
  pt: { title: "Credit Card Validator (Luhn)", short: "Verificar a card number com the Luhn algorithm e detect its brand.", description: "Gratuito - credit card number validator. Verify whether a card number passes the Luhn checksum e detect its brand (Visa, Mastercard, Amex, Discover e more). Formatar verificar only â nothing is sent anywhere.", keywords: ["credit card validator", "luhn check", "card number validator", "luhn algorithm", "card brand detector"], placeholder: "Enter a card number…", valid: "Valid number (passes Luhn)", invalid: "Invalid number (fails Luhn)", brand: "Brand", unknownBrand: "Unknown" },
  id: { title: "Credit Card Validator (Luhn)", short: "Periksa a card number with the Luhn algorithm dan detect its brand.", description: "Gratis - credit card number validator. Verify whether a card number passes the Luhn checksum dan detect its brand (Visa, Mastercard, Amex, Discover dan more). Format periksa only â nothing is sent anywhere.", keywords: ["credit card validator", "luhn check", "card number validator", "luhn algorithm", "card brand detector"], placeholder: "Enter a card number…", valid: "Valid number (passes Luhn)", invalid: "Invalid number (fails Luhn)", brand: "Brand", unknownBrand: "Unknown" },

  tr: { title: "Kredi Kartı Doğrulayıcı (Luhn)", short: "Bir kart numarasını Luhn algoritmasıyla kontrol edin ve markasını tespit edin.", description: "Ücretsiz kredi kartı numarası doğrulayıcı. Bir kart numarasının Luhn sağlamasını geçip geçmediğini doğrulayın ve markasını (Visa, Mastercard, Amex, Discover ve daha fazlası) tespit edin. Yalnızca biçim kontrolü — hiçbir yere gönderilmez.", keywords: ["kredi kartı doğrulayıcı", "luhn kontrolü", "kart numarası doğrulayıcı", "luhn algoritması", "kart markası tespiti"], placeholder: "Bir kart numarası girin…", valid: "Geçerli numara (Luhn'u geçer)", invalid: "Geçersiz numara (Luhn başarısız)", brand: "Marka", unknownBrand: "Bilinmiyor" },
  de: { title: "Kreditkarten-Validator (Luhn)", short: "Prüfen Sie eine Kartennummer mit dem Luhn-Algorithmus und erkennen Sie die Marke.", description: "Kostenloser Kreditkartennummer-Validator. Prüfen Sie, ob eine Kartennummer die Luhn-Prüfsumme besteht, und erkennen Sie die Marke (Visa, Mastercard, Amex, Discover u. a.). Nur Formatprüfung — nichts wird gesendet.", keywords: ["kreditkarten validator", "luhn prüfung", "kartennummer validator", "luhn algorithmus", "kartenmarke erkennen"], placeholder: "Kartennummer eingeben…", valid: "Gültige Nummer (besteht Luhn)", invalid: "Ungültige Nummer (Luhn fehlgeschlagen)", brand: "Marke", unknownBrand: "Unbekannt" },
  fr: { title: "Validateur de Carte Bancaire (Luhn)", short: "Vérifiez un numéro de carte avec l'algorithme de Luhn et détectez la marque.", description: "Validateur de numéro de carte gratuit. Vérifiez si un numéro de carte passe la somme de contrôle de Luhn et détectez sa marque (Visa, Mastercard, Amex, Discover, etc.). Vérification de format uniquement — rien n'est envoyé.", keywords: ["validateur carte bancaire", "vérification luhn", "validateur numéro de carte", "algorithme de luhn", "détecteur de marque"], placeholder: "Saisissez un numéro de carte…", valid: "Numéro valide (passe Luhn)", invalid: "Numéro invalide (échoue Luhn)", brand: "Marque", unknownBrand: "Inconnue" },
  es: { title: "Validador de Tarjeta (Luhn)", short: "Comprueba un número de tarjeta con el algoritmo de Luhn y detecta su marca.", description: "Validador de número de tarjeta gratuito. Verifica si un número de tarjeta pasa la suma de comprobación de Luhn y detecta su marca (Visa, Mastercard, Amex, Discover y más). Solo comprobación de formato — no se envía nada.", keywords: ["validador de tarjeta", "comprobación luhn", "validador número de tarjeta", "algoritmo de luhn", "detector de marca"], placeholder: "Introduce un número de tarjeta…", valid: "Número válido (pasa Luhn)", invalid: "Número no válido (falla Luhn)", brand: "Marca", unknownBrand: "Desconocida" },
  it: { title: "Validatore Carta di Credito (Luhn)", short: "Controlla un numero di carta con l'algoritmo di Luhn e rileva il circuito.", description: "Validatore di numero di carta gratuito. Verifica se un numero di carta supera il checksum di Luhn e rileva il circuito (Visa, Mastercard, Amex, Discover e altri). Solo verifica del formato — nulla viene inviato.", keywords: ["validatore carta di credito", "controllo luhn", "validatore numero carta", "algoritmo di luhn", "rilevatore circuito"], placeholder: "Inserisci un numero di carta…", valid: "Numero valido (supera Luhn)", invalid: "Numero non valido (fallisce Luhn)", brand: "Circuito", unknownBrand: "Sconosciuto" },
  ar: { title: "مدقّق بطاقة الائتمان (Luhn)", short: "تحقق من رقم بطاقة باستخدام خوارزمية Luhn واكتشف نوعها.", description: "مدقّق رقم بطاقة ائتمان مجاني. تحقق مما إذا كان رقم البطاقة يجتاز مجموع Luhn الاختباري واكتشف نوعها (Visa، Mastercard، Amex، Discover وغيرها). فحص التنسيق فقط — لا يُرسل شيء.", keywords: ["مدقق بطاقة الائتمان", "فحص luhn", "مدقق رقم البطاقة", "خوارزمية luhn", "كاشف نوع البطاقة"], placeholder: "أدخل رقم بطاقة…", valid: "رقم صالح (يجتاز Luhn)", invalid: "رقم غير صالح (يفشل في Luhn)", brand: "النوع", unknownBrand: "غير معروف" },
  ru: { title: "Валидатор Карты (Luhn)", short: "Проверьте номер карты алгоритмом Луна и определите платёжную систему.", description: "Бесплатный валидатор номера карты. Проверьте, проходит ли номер карты контрольную сумму Луна, и определите платёжную систему (Visa, Mastercard, Amex, Discover и др.). Только проверка формата — ничего не отправляется.", keywords: ["валидатор карты", "проверка luhn", "валидатор номера карты", "алгоритм луна", "определение платёжной системы"], placeholder: "Введите номер карты…", valid: "Корректный номер (проходит Luhn)", invalid: "Некорректный номер (не проходит Luhn)", brand: "Система", unknownBrand: "Неизвестно" },
  zh: { title: "信用卡校验器（Luhn）", short: "用 Luhn 算法校验卡号并识别其品牌。", description: "免费的信用卡卡号校验器。验证卡号是否通过 Luhn 校验和，并识别其品牌（Visa、Mastercard、Amex、Discover 等）。仅格式检查——不发送任何内容。", keywords: ["信用卡校验器", "luhn校验", "卡号校验器", "luhn算法", "卡品牌识别"], placeholder: "输入卡号…", valid: "有效卡号（通过 Luhn）", invalid: "无效卡号（未通过 Luhn）", brand: "品牌", unknownBrand: "未知" },
  ja: { title: "クレジットカード検証（Luhn）", short: "Luhn アルゴリズムでカード番号を検証し、ブランドを判定します。", description: "無料のクレジットカード番号検証ツール。カード番号が Luhn チェックサムを通過するか検証し、ブランド（Visa、Mastercard、Amex、Discover など）を判定します。形式チェックのみ — どこにも送信されません。", keywords: ["クレジットカード 検証", "luhn チェック", "カード番号 検証", "luhn アルゴリズム", "ブランド判定"], placeholder: "カード番号を入力…", valid: "有効な番号（Luhn を通過）", invalid: "無効な番号（Luhn 不合格）", brand: "ブランド", unknownBrand: "不明" },
  ko: { title: "신용카드 검증기(Luhn)", short: "Luhn 알고리즘으로 카드 번호를 확인하고 브랜드를 감지합니다.", description: "무료 신용카드 번호 검증기. 카드 번호가 Luhn 체크섬을 통과하는지 확인하고 브랜드(Visa, Mastercard, Amex, Discover 등)를 감지합니다. 형식 검사만 — 아무것도 전송되지 않습니다.", keywords: ["신용카드 검증기", "luhn 검사", "카드 번호 검증기", "luhn 알고리즘", "카드 브랜드 감지"], placeholder: "카드 번호 입력…", valid: "유효한 번호(Luhn 통과)", invalid: "유효하지 않은 번호(Luhn 실패)", brand: "브랜드", unknownBrand: "알 수 없음" },
  hi: { title: "क्रेडिट कार्ड वैलिडेटर (Luhn)", short: "Luhn एल्गोरिदम से कार्ड नंबर जांचें और उसका ब्रांड पहचानें।", description: "मुफ्त क्रेडिट कार्ड नंबर वैलिडेटर। जांचें कि कोई कार्ड नंबर Luhn चेकसम पास करता है या नहीं और उसका ब्रांड (Visa, Mastercard, Amex, Discover आदि) पहचानें। केवल फॉर्मेट जांच — कुछ भी कहीं नहीं भेजा जाता।", keywords: ["क्रेडिट कार्ड वैलिडेटर", "luhn जांच", "कार्ड नंबर वैलिडेटर", "luhn एल्गोरिदम", "कार्ड ब्रांड पहचान"], placeholder: "कार्ड नंबर दर्ज करें…", valid: "मान्य नंबर (Luhn पास)", invalid: "अमान्य नंबर (Luhn विफल)", brand: "ब्रांड", unknownBrand: "अज्ञात" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
