import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "MIME Type Lookup", short: "Find the MIME (content) type for a file extension and vice versa.", description: "Free MIME type lookup. Search by file extension (png, pdf, json) or by MIME type to find the matching content type, useful for Content-Type headers and uploads. Runs in your browser.", keywords: ["mime type lookup", "content type", "file extension mime type", "mime types list", "media type"], searchPlaceholder: "Search extension or type (e.g. png, json)…", extension: "Extension", mimeType: "MIME type", noResults: "No matching types." },
  tr: { title: "MIME Türü Arama", short: "Bir dosya uzantısı için MIME (içerik) türünü ve tersini bulun.", description: "Ücretsiz MIME türü arama. Dosya uzantısına (png, pdf, json) veya MIME türüne göre arayarak eşleşen içerik türünü bulun; Content-Type başlıkları ve yüklemeler için kullanışlı. Tarayıcınızda çalışır.", keywords: ["mime türü arama", "içerik türü", "dosya uzantısı mime türü", "mime türleri listesi", "ortam türü"], searchPlaceholder: "Uzantı veya tür ara (örn. png, json)…", extension: "Uzantı", mimeType: "MIME türü", noResults: "Eşleşen tür yok." },
  de: { title: "MIME-Typ-Suche", short: "Finden Sie den MIME-Typ (Content-Type) für eine Dateiendung und umgekehrt.", description: "Kostenlose MIME-Typ-Suche. Suchen Sie nach Dateiendung (png, pdf, json) oder MIME-Typ, um den passenden Content-Type zu finden — nützlich für Content-Type-Header und Uploads.", keywords: ["mime-typ suche", "content type", "dateiendung mime-typ", "mime-typen liste", "medientyp"], searchPlaceholder: "Endung oder Typ suchen (z. B. png, json)…", extension: "Endung", mimeType: "MIME-Typ", noResults: "Keine passenden Typen." },
  fr: { title: "Recherche de Type MIME", short: "Trouvez le type MIME (Content-Type) d'une extension de fichier et inversement.", description: "Recherche de type MIME gratuite. Recherchez par extension de fichier (png, pdf, json) ou par type MIME pour trouver le Content-Type correspondant — utile pour les en-têtes Content-Type et les uploads.", keywords: ["recherche type mime", "content type", "extension fichier type mime", "liste types mime", "type de média"], searchPlaceholder: "Recherche extension ou type (ex. png, json)…", extension: "Extension", mimeType: "Type MIME", noResults: "Aucun type correspondant." },
  es: { title: "Búsqueda de Tipo MIME", short: "Encuentra el tipo MIME (Content-Type) de una extensión de archivo y viceversa.", description: "Búsqueda de tipo MIME gratuita. Busca por extensión de archivo (png, pdf, json) o por tipo MIME para encontrar el Content-Type correspondiente — útil para encabezados Content-Type y subidas.", keywords: ["búsqueda tipo mime", "content type", "extensión archivo tipo mime", "lista tipos mime", "tipo de medio"], searchPlaceholder: "Busca extensión o tipo (p. ej. png, json)…", extension: "Extensión", mimeType: "Tipo MIME", noResults: "No hay tipos coincidentes." },
  it: { title: "Ricerca Tipo MIME", short: "Trova il tipo MIME (Content-Type) di un'estensione di file e viceversa.", description: "Ricerca tipo MIME gratuita. Cerca per estensione file (png, pdf, json) o per tipo MIME per trovare il Content-Type corrispondente — utile per gli header Content-Type e gli upload.", keywords: ["ricerca tipo mime", "content type", "estensione file tipo mime", "lista tipi mime", "tipo di media"], searchPlaceholder: "Cerca estensione o tipo (es. png, json)…", extension: "Estensione", mimeType: "Tipo MIME", noResults: "Nessun tipo corrispondente." },
  ar: { title: "البحث عن نوع MIME", short: "ابحث عن نوع MIME (Content-Type) لامتداد ملف والعكس.", description: "بحث عن نوع MIME مجاني. ابحث بامتداد الملف (png، pdf، json) أو بنوع MIME لإيجاد Content-Type المطابق — مفيد لرؤوس Content-Type والرفع. يعمل في متصفحك.", keywords: ["بحث نوع mime", "content type", "امتداد الملف نوع mime", "قائمة أنواع mime", "نوع الوسائط"], searchPlaceholder: "ابحث بالامتداد أو النوع (مثل png، json)…", extension: "الامتداد", mimeType: "نوع MIME", noResults: "لا توجد أنواع مطابقة." },
  ru: { title: "Поиск MIME-типа", short: "Найдите MIME-тип (Content-Type) для расширения файла и наоборот.", description: "Бесплатный поиск MIME-типа. Ищите по расширению файла (png, pdf, json) или по MIME-типу, чтобы найти соответствующий Content-Type — полезно для заголовков Content-Type и загрузок.", keywords: ["поиск mime типа", "content type", "расширение файла mime тип", "список mime типов", "тип медиа"], searchPlaceholder: "Поиск расширения или типа (напр. png, json)…", extension: "Расширение", mimeType: "MIME-тип", noResults: "Нет подходящих типов." },
  zh: { title: "MIME 类型查询", short: "查找文件扩展名对应的 MIME（内容）类型，反之亦然。", description: "免费的 MIME 类型查询。按文件扩展名（png、pdf、json）或 MIME 类型搜索，找到匹配的内容类型——适用于 Content-Type 头和上传。在浏览器中运行。", keywords: ["mime类型查询", "content type", "文件扩展名mime类型", "mime类型列表", "媒体类型"], searchPlaceholder: "搜索扩展名或类型（如 png、json）…", extension: "扩展名", mimeType: "MIME 类型", noResults: "没有匹配的类型。" },
  ja: { title: "MIME タイプ検索", short: "ファイル拡張子に対応する MIME（コンテンツ）タイプを検索します。", description: "無料の MIME タイプ検索。ファイル拡張子（png、pdf、json）または MIME タイプで検索し、対応するコンテンツタイプを見つけます。Content-Type ヘッダーやアップロードに便利。ブラウザ内で動作します。", keywords: ["mime タイプ 検索", "content type", "拡張子 mime タイプ", "mime タイプ 一覧", "メディアタイプ"], searchPlaceholder: "拡張子またはタイプで検索（例: png, json）…", extension: "拡張子", mimeType: "MIME タイプ", noResults: "一致するタイプがありません。" },
  ko: { title: "MIME 타입 조회", short: "파일 확장자에 해당하는 MIME(콘텐츠) 타입을 찾고 그 반대도 가능합니다.", description: "무료 MIME 타입 조회. 파일 확장자(png, pdf, json)나 MIME 타입으로 검색하여 일치하는 콘텐츠 타입을 찾으세요 — Content-Type 헤더와 업로드에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["mime 타입 조회", "content type", "파일 확장자 mime 타입", "mime 타입 목록", "미디어 타입"], searchPlaceholder: "확장자 또는 타입 검색 (예: png, json)…", extension: "확장자", mimeType: "MIME 타입", noResults: "일치하는 타입이 없습니다." },
  hi: { title: "MIME टाइप लुकअप", short: "किसी फ़ाइल एक्सटेंशन का MIME (कंटेंट) टाइप और इसके विपरीत खोजें।", description: "मुफ्त MIME टाइप लुकअप। फ़ाइल एक्सटेंशन (png, pdf, json) या MIME टाइप से खोजें और मिलान कंटेंट टाइप पाएं — Content-Type हेडर और अपलोड के लिए उपयोगी। ब्राउज़र में चलता है।", keywords: ["mime टाइप लुकअप", "content type", "फ़ाइल एक्सटेंशन mime टाइप", "mime टाइप सूची", "मीडिया टाइप"], searchPlaceholder: "एक्सटेंशन या टाइप खोजें (जैसे png, json)…", extension: "एक्सटेंशन", mimeType: "MIME टाइप", noResults: "कोई मिलान टाइप नहीं।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
