import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Open Graph Meta Tag Generator", short: "Build the og:* meta tags with a social-card preview.", description: "Free Open Graph meta tag generator. Fill in title, description, image and URL to get a clean set of og:* tags plus a live preview of how Facebook, LinkedIn and Slack will render your link.", keywords: ["open graph generator", "og meta tags", "facebook meta tags", "linkedin preview", "social meta tags"], titleField: "Title", descriptionField: "Description", url: "URL", image: "Image URL", siteName: "Site name", type: "Type", localeField: "Locale", output: "Open Graph tags", preview: "Preview" },
  tr: { title: "Open Graph Meta Etiketi Oluşturucu", short: "Sosyal kart önizlemesiyle og:* meta etiketlerini oluşturun.", description: "Ücretsiz Open Graph meta etiketi oluşturucu. Başlık, açıklama, görsel ve URL alanlarını doldurarak temiz bir og:* etiket seti ve Facebook, LinkedIn ve Slack'in bağlantınızı nasıl göstereceğine dair canlı önizleme alın.", keywords: ["open graph oluşturucu", "og meta etiketleri", "facebook meta etiketleri", "linkedin önizleme", "sosyal meta etiketleri"], titleField: "Başlık", descriptionField: "Açıklama", url: "URL", image: "Görsel URL'si", siteName: "Site adı", type: "Tür", localeField: "Yerel ayar", output: "Open Graph etiketleri", preview: "Önizleme" },
  de: { title: "Open-Graph-Meta-Tag-Generator", short: "Erzeugen Sie og:* Meta-Tags mit Social-Card-Vorschau.", description: "Kostenloser Open-Graph-Meta-Tag-Generator. Füllen Sie Titel, Beschreibung, Bild und URL aus, um saubere og:*-Tags plus eine Live-Vorschau, wie Facebook, LinkedIn und Slack Ihren Link darstellen, zu erhalten.", keywords: ["open graph generator", "og meta tags", "facebook meta tags", "linkedin vorschau", "social meta tags"], titleField: "Titel", descriptionField: "Beschreibung", url: "URL", image: "Bild-URL", siteName: "Site-Name", type: "Typ", localeField: "Locale", output: "Open-Graph-Tags", preview: "Vorschau" },
  fr: { title: "Générateur de Meta Tags Open Graph", short: "Construisez les meta tags og:* avec aperçu de carte sociale.", description: "Générateur de meta tags Open Graph gratuit. Remplissez titre, description, image et URL pour obtenir un ensemble propre de tags og:* et un aperçu en direct du rendu de votre lien sur Facebook, LinkedIn et Slack.", keywords: ["générateur open graph", "meta tags og", "meta tags facebook", "aperçu linkedin", "meta tags sociaux"], titleField: "Titre", descriptionField: "Description", url: "URL", image: "URL de l'image", siteName: "Nom du site", type: "Type", localeField: "Locale", output: "Tags Open Graph", preview: "Aperçu" },
  es: { title: "Generador de Meta Tags Open Graph", short: "Construye las meta tags og:* con vista previa de tarjeta social.", description: "Generador de meta tags Open Graph gratuito. Rellena título, descripción, imagen y URL para obtener un conjunto limpio de tags og:* y una vista previa de cómo se verá tu enlace en Facebook, LinkedIn y Slack.", keywords: ["generador open graph", "meta tags og", "meta tags facebook", "vista previa linkedin", "meta tags sociales"], titleField: "Título", descriptionField: "Descripción", url: "URL", image: "URL de la imagen", siteName: "Nombre del sitio", type: "Tipo", localeField: "Locale", output: "Tags Open Graph", preview: "Vista previa" },
  it: { title: "Generatore di Meta Tag Open Graph", short: "Costruisci i meta tag og:* con anteprima social.", description: "Generatore di meta tag Open Graph gratuito. Compila titolo, descrizione, immagine e URL per ottenere un set pulito di tag og:* e un'anteprima dal vivo di come Facebook, LinkedIn e Slack renderizzeranno il tuo link.", keywords: ["generatore open graph", "meta tag og", "meta tag facebook", "anteprima linkedin", "meta tag social"], titleField: "Titolo", descriptionField: "Descrizione", url: "URL", image: "URL immagine", siteName: "Nome sito", type: "Tipo", localeField: "Locale", output: "Tag Open Graph", preview: "Anteprima" },
  ar: { title: "مولّد علامات Open Graph", short: "أنشئ علامات og:* مع معاينة البطاقة الاجتماعية.", description: "مولّد علامات Open Graph مجاني. املأ العنوان والوصف والصورة وعنوان URL للحصول على مجموعة نظيفة من علامات og:* ومعاينة حية لكيفية عرض Facebook و LinkedIn و Slack لرابطك.", keywords: ["مولد open graph", "علامات og meta", "علامات facebook meta", "معاينة linkedin", "علامات meta اجتماعية"], titleField: "العنوان", descriptionField: "الوصف", url: "URL", image: "عنوان URL للصورة", siteName: "اسم الموقع", type: "النوع", localeField: "Locale", output: "علامات Open Graph", preview: "معاينة" },
  ru: { title: "Генератор Open Graph", short: "Создайте og:* meta-теги с предпросмотром карточки.", description: "Бесплатный генератор Open Graph. Заполните title, description, image и URL, чтобы получить чистый набор og:*-тегов и живое превью того, как Facebook, LinkedIn и Slack отрисуют вашу ссылку.", keywords: ["генератор open graph", "og meta теги", "facebook meta теги", "linkedin превью", "социальные meta теги"], titleField: "Заголовок", descriptionField: "Описание", url: "URL", image: "URL изображения", siteName: "Имя сайта", type: "Тип", localeField: "Locale", output: "Open Graph теги", preview: "Превью" },
  zh: { title: "Open Graph Meta 标签生成器", short: "构建带社交卡片预览的 og:* meta 标签。", description: "免费的 Open Graph meta 标签生成器。填写标题、描述、图片和 URL，即可获得整洁的 og:* 标签集，并实时预览 Facebook、LinkedIn 和 Slack 如何渲染你的链接。", keywords: ["open graph 生成器", "og meta 标签", "facebook meta 标签", "linkedin 预览", "社交 meta 标签"], titleField: "标题", descriptionField: "描述", url: "URL", image: "图片 URL", siteName: "站点名称", type: "类型", localeField: "Locale", output: "Open Graph 标签", preview: "预览" },
  ja: { title: "Open Graph Meta タグ生成", short: "ソーシャルカードプレビュー付きで og:* メタタグを構築。", description: "無料の Open Graph メタタグ生成ツール。タイトル、説明、画像、URL を記入すると、整理された og:* タグセットと Facebook、LinkedIn、Slack でのレンダリングのライブプレビューが得られます。", keywords: ["open graph 生成", "og meta タグ", "facebook meta タグ", "linkedin プレビュー", "ソーシャル meta タグ"], titleField: "タイトル", descriptionField: "説明", url: "URL", image: "画像 URL", siteName: "サイト名", type: "種類", localeField: "Locale", output: "Open Graph タグ", preview: "プレビュー" },
  ko: { title: "Open Graph Meta 태그 생성기", short: "소셜 카드 미리보기와 함께 og:* meta 태그를 만듭니다.", description: "무료 Open Graph meta 태그 생성기. 제목, 설명, 이미지, URL을 입력하면 깔끔한 og:* 태그 세트와 Facebook, LinkedIn, Slack에서 링크가 어떻게 보일지 실시간 미리보기를 얻습니다.", keywords: ["open graph 생성기", "og meta 태그", "facebook meta 태그", "linkedin 미리보기", "소셜 meta 태그"], titleField: "제목", descriptionField: "설명", url: "URL", image: "이미지 URL", siteName: "사이트 이름", type: "유형", localeField: "Locale", output: "Open Graph 태그", preview: "미리보기" },
  hi: { title: "Open Graph Meta टैग जनरेटर", short: "सोशल कार्ड प्रीव्यू के साथ og:* meta टैग बनाएं।", description: "मुफ्त Open Graph meta टैग जनरेटर। शीर्षक, विवरण, छवि और URL भरें और og:* टैग का साफ सेट और Facebook, LinkedIn व Slack आपके लिंक को कैसे प्रस्तुत करेंगे इसका लाइव प्रीव्यू पाएं।", keywords: ["open graph जनरेटर", "og meta टैग", "facebook meta टैग", "linkedin प्रीव्यू", "सोशल meta टैग"], titleField: "शीर्षक", descriptionField: "विवरण", url: "URL", image: "छवि URL", siteName: "साइट नाम", type: "प्रकार", localeField: "Locale", output: "Open Graph टैग", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
