import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Random Picker", short: "Pick random items or winners from a list.", description: "Free random picker. Paste a list (one item per line), choose how many to draw and whether picks should be unique, and let the tool choose at random — great for raffles, name draws and decisions.", keywords: ["random picker", "random name picker", "raffle picker", "pick from list", "random choice generator"], placeholder: "One item per line…", count: "How many", unique: "No repeats", pick: "Pick" },
  nl: { title: "Willekeurig Kiezer", short: "Pick willekeurig items or winners from a list.", description: "Gratis willekeurig picker. Paste a list (one item per line), choose how many to draw and whether picks should be unique, and let the tool choose at willekeurig — great for raffles, name draws and decisions.", keywords: ["willekeurig picker", "willekeurig name picker", "raffle picker", "pick from list", "willekeurig choice generator"], placeholder: "One item per line…", count: "How many", unique: "No repeats", pick: "Pick" },

  pl: { title: "Losowy Wybór", short: "Pick losowy items or winners from a list.", description: "Darmowy losowy picker. Paste a list (one item per line), choose how many to draw and whether picks should be unique, and let the narzędzie choose at losowy — great for raffles, name draws and decisions.", keywords: ["losowy picker", "losowy name picker", "raffle picker", "pick from list", "losowy choice generator"], placeholder: "One item per line…", count: "How many", unique: "No repeats", pick: "Pick" },
  pt: { title: "Seletor de Random", short: "Pick random items ou winners a partir de a list.", description: "Gratuito - random picker. Paste a list (one item per line), choose how many para draw e whether picks should be unique, e let the tool choose at random â great para raffles, name draws e decisions.", keywords: ["random picker", "random name picker", "raffle picker", "pick from list", "random choice generator"], placeholder: "One item per line…", count: "How many", unique: "No repeats", pick: "Pick" },
  id: { title: "Pemilih Random", short: "Pick random items atau winners from a list.", description: "Gratis - random picker. Paste a list (one item per line), choose how many to draw dan whether picks should be unique, dan let the tool choose at random â great for raffles, name draws dan decisions.", keywords: ["random picker", "random name picker", "raffle picker", "pick from list", "random choice generator"], placeholder: "One item per line…", count: "How many", unique: "No repeats", pick: "Pick" },

  tr: { title: "Rastgele Seçici", short: "Bir listeden rastgele öğe veya kazanan seçin.", description: "Ücretsiz rastgele seçici. Bir liste yapıştırın (her satıra bir öğe), kaç tane çekileceğini ve seçimlerin benzersiz olup olmayacağını seçin; araç rastgele seçsin — çekilişler, isim çekme ve kararlar için harika.", keywords: ["rastgele seçici", "rastgele isim seçici", "çekiliş seçici", "listeden seç", "rastgele seçim"], placeholder: "Her satıra bir öğe…", count: "Adet", unique: "Tekrarsız", pick: "Seç" },
  de: { title: "Zufalls-Auswähler", short: "Wählen Sie zufällige Einträge oder Gewinner aus einer Liste.", description: "Kostenloser Zufalls-Auswähler. Fügen Sie eine Liste ein (ein Eintrag pro Zeile), wählen Sie die Anzahl und ob die Auswahl eindeutig sein soll — ideal für Verlosungen, Namensziehungen und Entscheidungen.", keywords: ["zufalls auswähler", "zufälliger namens-picker", "verlosung", "aus liste wählen", "zufällige auswahl"], placeholder: "Ein Eintrag pro Zeile…", count: "Anzahl", unique: "Ohne Wiederholungen", pick: "Auswählen" },
  fr: { title: "Sélecteur Aléatoire", short: "Choisissez des éléments ou gagnants au hasard dans une liste.", description: "Sélecteur aléatoire gratuit. Collez une liste (un élément par ligne), choisissez combien tirer et si les choix doivent être uniques — parfait pour tirages au sort, noms et décisions.", keywords: ["sélecteur aléatoire", "tirage de noms", "tirage au sort", "choisir dans une liste", "choix aléatoire"], placeholder: "Un élément par ligne…", count: "Combien", unique: "Sans répétition", pick: "Choisir" },
  es: { title: "Selector Aleatorio", short: "Elige elementos o ganadores al azar de una lista.", description: "Selector aleatorio gratuito. Pega una lista (un elemento por línea), elige cuántos sacar y si las selecciones deben ser únicas — ideal para sorteos, nombres y decisiones.", keywords: ["selector aleatorio", "selector de nombres", "sorteo", "elegir de una lista", "elección aleatoria"], placeholder: "Un elemento por línea…", count: "Cuántos", unique: "Sin repetir", pick: "Elegir" },
  it: { title: "Selettore Casuale", short: "Scegli elementi o vincitori a caso da un elenco.", description: "Selettore casuale gratuito. Incolla un elenco (un elemento per riga), scegli quanti estrarre e se le scelte devono essere uniche — ideale per estrazioni, nomi e decisioni.", keywords: ["selettore casuale", "estrazione nomi", "estrazione a sorte", "scegli da elenco", "scelta casuale"], placeholder: "Un elemento per riga…", count: "Quanti", unique: "Senza ripetizioni", pick: "Scegli" },
  ar: { title: "المنتقي العشوائي", short: "اختر عناصر أو فائزين عشوائيًا من قائمة.", description: "منتقي عشوائي مجاني. الصق قائمة (عنصر واحد لكل سطر)، واختر العدد وما إذا كانت الاختيارات فريدة — رائع للسحوبات واختيار الأسماء والقرارات.", keywords: ["المنتقي العشوائي", "منتقي أسماء عشوائي", "السحب", "اختيار من قائمة", "اختيار عشوائي"], placeholder: "عنصر واحد لكل سطر…", count: "العدد", unique: "بدون تكرار", pick: "اختر" },
  ru: { title: "Случайный Выбор", short: "Выбирайте случайные элементы или победителей из списка.", description: "Бесплатный случайный выбор. Вставьте список (по одному в строке), выберите сколько вытянуть и должны ли выборы быть уникальными — отлично для розыгрышей, имён и решений.", keywords: ["случайный выбор", "случайный выбор имён", "розыгрыш", "выбор из списка", "случайный выбор"], placeholder: "По одному элементу в строке…", count: "Количество", unique: "Без повторов", pick: "Выбрать" },
  zh: { title: "随机选择器", short: "从列表中随机抽取项目或获奖者。", description: "免费的随机选择器。粘贴列表（每行一项），选择抽取数量以及是否不重复，让工具随机选择——非常适合抽奖、抽名字和做决定。", keywords: ["随机选择器", "随机抽名字", "抽奖器", "从列表选择", "随机选择"], placeholder: "每行一项…", count: "数量", unique: "不重复", pick: "选择" },
  ja: { title: "ランダム選択ツール", short: "リストからランダムに項目や当選者を選びます。", description: "無料のランダム選択ツール。リストを貼り付け（1行に1項目）、引く個数と重複なしかを選ぶと、ランダムに選ばれます。抽選・名前選び・意思決定に最適。", keywords: ["ランダム選択", "ランダム 名前 抽選", "抽選ツール", "リストから選ぶ", "ランダム チョイス"], placeholder: "1行に1項目…", count: "個数", unique: "重複なし", pick: "選ぶ" },
  ko: { title: "랜덤 선택기", short: "목록에서 무작위로 항목이나 당첨자를 뽑습니다.", description: "무료 랜덤 선택기. 목록을 붙여넣고(한 줄에 한 항목) 뽑을 개수와 중복 없이 여부를 선택하면 무작위로 선택됩니다. 추첨, 이름 뽑기, 결정에 적합합니다.", keywords: ["랜덤 선택기", "랜덤 이름 뽑기", "추첨기", "목록에서 선택", "무작위 선택"], placeholder: "한 줄에 한 항목…", count: "개수", unique: "중복 없음", pick: "뽑기" },
  hi: { title: "रैंडम पिकर", short: "सूची से रैंडम आइटम या विजेता चुनें।", description: "मुफ्त रैंडम पिकर। एक सूची पेस्ट करें (हर पंक्ति में एक आइटम), कितने निकालने हैं और चयन अद्वितीय हों या नहीं चुनें — रैफल, नाम ड्रॉ और निर्णयों के लिए बढ़िया।", keywords: ["रैंडम पिकर", "रैंडम नाम पिकर", "रैफल पिकर", "सूची से चुनें", "रैंडम चयन"], placeholder: "हर पंक्ति में एक आइटम…", count: "कितने", unique: "बिना दोहराव", pick: "चुनें" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
