import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Base64 to Image Converter", short: "Decode a Base64 string or data URL into an image.", description: "Free Base64 to image converter. Paste a Base64 string or data URL to preview the image and download it — all in your browser, nothing uploaded.", keywords: ["base64 to image", "base64 image decoder", "data url to image", "decode base64 image", "view base64 image"], input: "Base64 or data URL", preview: "Preview", download: "Download", invalid: "That doesn't look like a valid Base64 image." },
  tr: { title: "Base64'ten Görsele Dönüştürücü", short: "Bir Base64 dizesini veya veri URL'sini görsele dönüştürün.", description: "Ücretsiz Base64'ten görsele dönüştürücü. Bir Base64 dizesi veya veri URL'si yapıştırın, görseli önizleyin ve indirin — hepsi tarayıcınızda, hiçbir şey yüklenmez.", keywords: ["base64 görsel", "base64 görsel çözücü", "veri url görsel", "base64 görsel çöz", "base64 görseli görüntüle"], input: "Base64 veya veri URL'si", preview: "Önizleme", download: "İndir", invalid: "Bu geçerli bir Base64 görseli gibi görünmüyor." },
  de: { title: "Base64-zu-Bild-Konverter", short: "Dekodieren Sie eine Base64-Zeichenfolge oder Daten-URL in ein Bild.", description: "Kostenloser Base64-zu-Bild-Konverter. Fügen Sie eine Base64-Zeichenfolge oder Daten-URL ein, um das Bild anzuzeigen und herunterzuladen — alles im Browser, nichts wird hochgeladen.", keywords: ["base64 zu bild", "base64 bild decoder", "daten url zu bild", "base64 bild dekodieren", "base64 bild anzeigen"], input: "Base64 oder Daten-URL", preview: "Vorschau", download: "Herunterladen", invalid: "Das sieht nicht nach einem gültigen Base64-Bild aus." },
  fr: { title: "Convertisseur Base64 vers Image", short: "Décodez une chaîne Base64 ou URL de données en image.", description: "Convertisseur Base64 vers image gratuit. Collez une chaîne Base64 ou URL de données pour prévisualiser l'image et la télécharger — le tout dans votre navigateur, rien n'est envoyé.", keywords: ["base64 vers image", "décodeur image base64", "url données vers image", "décoder image base64", "voir image base64"], input: "Base64 ou URL de données", preview: "Aperçu", download: "Télécharger", invalid: "Cela ne ressemble pas à une image Base64 valide." },
  es: { title: "Convertidor de Base64 a Imagen", short: "Decodifica una cadena Base64 o URL de datos en una imagen.", description: "Convertidor de Base64 a imagen gratuito. Pega una cadena Base64 o URL de datos para previsualizar la imagen y descargarla — todo en tu navegador, nada se sube.", keywords: ["base64 a imagen", "decodificador imagen base64", "url datos a imagen", "decodificar imagen base64", "ver imagen base64"], input: "Base64 o URL de datos", preview: "Vista previa", download: "Descargar", invalid: "Eso no parece una imagen Base64 válida." },
  it: { title: "Convertitore da Base64 a Immagine", short: "Decodifica una stringa Base64 o URL di dati in un'immagine.", description: "Convertitore da Base64 a immagine gratuito. Incolla una stringa Base64 o URL di dati per visualizzare l'immagine e scaricarla — tutto nel browser, nulla viene caricato.", keywords: ["base64 a immagine", "decodificatore immagine base64", "url dati a immagine", "decodificare immagine base64", "vedere immagine base64"], input: "Base64 o URL dati", preview: "Anteprima", download: "Scarica", invalid: "Non sembra un'immagine Base64 valida." },
  ar: { title: "محوّل Base64 إلى صورة", short: "فك ترميز سلسلة Base64 أو عنوان URL لبيانات إلى صورة.", description: "محوّل Base64 إلى صورة مجاني. الصق سلسلة Base64 أو عنوان URL لبيانات لمعاينة الصورة وتنزيلها — كل ذلك في متصفحك، لا شيء يُرفع.", keywords: ["base64 إلى صورة", "مفكّك صورة base64", "url بيانات إلى صورة", "فك ترميز صورة base64", "عرض صورة base64"], input: "Base64 أو عنوان URL للبيانات", preview: "معاينة", download: "تنزيل", invalid: "لا يبدو هذا كصورة Base64 صالحة." },
  ru: { title: "Конвертер Base64 в изображение", short: "Декодируйте строку Base64 или data URL в изображение.", description: "Бесплатный конвертер Base64 в изображение. Вставьте строку Base64 или data URL, чтобы предпросмотреть изображение и скачать его — всё в браузере, ничего не загружается.", keywords: ["base64 в изображение", "декодер изображения base64", "data url в изображение", "декодировать изображение base64", "посмотреть изображение base64"], input: "Base64 или data URL", preview: "Превью", download: "Скачать", invalid: "Это не похоже на корректное изображение Base64." },
  zh: { title: "Base64 转图片转换器", short: "将 Base64 字符串或数据 URL 解码为图片。", description: "免费的 Base64 转图片转换器。粘贴 Base64 字符串或数据 URL 即可预览图片并下载——全部在浏览器中完成，不上传任何内容。", keywords: ["base64 转图片", "base64 图片解码器", "数据 url 转图片", "解码 base64 图片", "查看 base64 图片"], input: "Base64 或数据 URL", preview: "预览", download: "下载", invalid: "这看起来不是有效的 Base64 图片。" },
  ja: { title: "Base64 から画像変換", short: "Base64 文字列やデータ URL を画像にデコード。", description: "無料の Base64 から画像変換ツール。Base64 文字列やデータ URL を貼り付けると画像をプレビューしてダウンロードできます——すべてブラウザ内で、アップロードなし。", keywords: ["base64 画像", "base64 画像デコーダー", "データ url 画像", "base64 画像デコード", "base64 画像 表示"], input: "Base64 またはデータ URL", preview: "プレビュー", download: "ダウンロード", invalid: "有効な Base64 画像ではないようです。" },
  ko: { title: "Base64 to 이미지 변환기", short: "Base64 문자열 또는 데이터 URL을 이미지로 디코딩합니다.", description: "무료 Base64 to 이미지 변환기. Base64 문자열 또는 데이터 URL을 붙여넣으면 이미지를 미리보고 다운로드할 수 있습니다 — 모두 브라우저에서, 업로드 없음.", keywords: ["base64 이미지", "base64 이미지 디코더", "데이터 url 이미지", "base64 이미지 디코딩", "base64 이미지 보기"], input: "Base64 또는 데이터 URL", preview: "미리보기", download: "다운로드", invalid: "유효한 Base64 이미지가 아닌 것 같습니다." },
  hi: { title: "Base64 से इमेज कन्वर्टर", short: "एक Base64 स्ट्रिंग या डेटा URL को इमेज में डिकोड करें।", description: "मुफ्त Base64 से इमेज कन्वर्टर। एक Base64 स्ट्रिंग या डेटा URL पेस्ट करें और इमेज का प्रीव्यू देखें व डाउनलोड करें — सब आपके ब्राउज़र में, कोई अपलोड नहीं।", keywords: ["base64 से इमेज", "base64 इमेज डिकोडर", "डेटा url से इमेज", "base64 इमेज डिकोड", "base64 इमेज देखें"], input: "Base64 या डेटा URL", preview: "प्रीव्यू", download: "डाउनलोड", invalid: "यह एक मान्य Base64 इमेज नहीं लगती।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
