import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Caesar Cipher & ROT13", short: "Shift letters by any amount to encode or decode a Caesar cipher, or apply ROT13.", description: "Free Caesar cipher tool. Shift the letters of your text by any amount (0–25) to encrypt or decrypt, or apply the classic ROT13. Non-letters are kept unchanged. Runs in your browser.", keywords: ["caesar cipher", "rot13", "letter shift cipher", "encode decode cipher", "shift cipher"], placeholder: "Enter text…", shift: "Shift", rot13: "ROT13" },
  pt: { title: "Caesar Cipher & ROT13", short: "Shift letters by any amount to encode or decode a Caesar cipher, or apply ROT13.", description: "Free Caesar cipher tool. Shift the letters of your text by any amount (0–25) to encrypt or decrypt, or apply the classic ROT13. Non-letters are kept unchanged. Runs in your browser.", keywords: ["caesar cipher", "rot13", "letter shift cipher", "encode decode cipher", "shift cipher"], placeholder: "Enter text…", shift: "Shift", rot13: "ROT13" },
  id: { title: "Caesar Cipher & ROT13", short: "Shift letters by any amount to encode or decode a Caesar cipher, or apply ROT13.", description: "Free Caesar cipher tool. Shift the letters of your text by any amount (0–25) to encrypt or decrypt, or apply the classic ROT13. Non-letters are kept unchanged. Runs in your browser.", keywords: ["caesar cipher", "rot13", "letter shift cipher", "encode decode cipher", "shift cipher"], placeholder: "Enter text…", shift: "Shift", rot13: "ROT13" },

  tr: { title: "Sezar Şifresi ve ROT13", short: "Harfleri istediğiniz kadar kaydırarak Sezar şifresini kodlayın/çözün veya ROT13 uygulayın.", description: "Ücretsiz Sezar şifresi aracı. Metninizin harflerini istediğiniz kadar (0–25) kaydırarak şifreleyin veya çözün ya da klasik ROT13'ü uygulayın. Harf olmayanlar değişmeden kalır. Tarayıcınızda çalışır.", keywords: ["sezar şifresi", "rot13", "harf kaydırma şifresi", "şifre kodla çöz", "kaydırma şifresi"], placeholder: "Metin girin…", shift: "Kaydırma", rot13: "ROT13" },
  de: { title: "Cäsar-Chiffre & ROT13", short: "Verschieben Sie Buchstaben beliebig, um eine Cäsar-Chiffre zu kodieren/dekodieren, oder wenden Sie ROT13 an.", description: "Kostenloses Cäsar-Chiffre-Tool. Verschieben Sie die Buchstaben Ihres Textes beliebig (0–25) zum Ver- oder Entschlüsseln oder wenden Sie das klassische ROT13 an. Nicht-Buchstaben bleiben unverändert.", keywords: ["cäsar-chiffre", "rot13", "verschiebechiffre", "chiffre kodieren dekodieren"], placeholder: "Text eingeben…", shift: "Verschiebung", rot13: "ROT13" },
  fr: { title: "Chiffre de César & ROT13", short: "Décalez les lettres pour coder ou décoder un chiffre de César, ou appliquez ROT13.", description: "Outil de chiffre de César gratuit. Décalez les lettres de votre texte (0–25) pour chiffrer ou déchiffrer, ou appliquez le ROT13 classique. Les non-lettres restent inchangées. S'exécute dans votre navigateur.", keywords: ["chiffre de césar", "rot13", "chiffre par décalage", "coder décoder chiffre"], placeholder: "Saisissez du texte…", shift: "Décalage", rot13: "ROT13" },
  es: { title: "Cifrado César y ROT13", short: "Desplaza las letras para codificar o decodificar un cifrado César, o aplica ROT13.", description: "Herramienta de cifrado César gratuita. Desplaza las letras de tu texto (0–25) para cifrar o descifrar, o aplica el clásico ROT13. Los caracteres no alfabéticos se mantienen. Se ejecuta en tu navegador.", keywords: ["cifrado césar", "rot13", "cifrado por desplazamiento", "codificar decodificar cifrado"], placeholder: "Introduce texto…", shift: "Desplazamiento", rot13: "ROT13" },
  it: { title: "Cifrario di Cesare & ROT13", short: "Sposta le lettere per codificare o decodificare un cifrario di Cesare, o applica ROT13.", description: "Strumento gratuito per il cifrario di Cesare. Sposta le lettere del tuo testo (0–25) per cifrare o decifrare, o applica il classico ROT13. I non-lettera restano invariati. Funziona nel browser.", keywords: ["cifrario di cesare", "rot13", "cifrario a scorrimento", "codifica decodifica cifrario"], placeholder: "Inserisci testo…", shift: "Scorrimento", rot13: "ROT13" },
  ar: { title: "شيفرة قيصر و ROT13", short: "أزِح الأحرف بأي مقدار لترميز شيفرة قيصر أو فك ترميزها، أو طبّق ROT13.", description: "أداة شيفرة قيصر مجانية. أزِح أحرف نصك بأي مقدار (0–25) للتشفير أو فك التشفير، أو طبّق ROT13 الكلاسيكية. تبقى غير الأحرف دون تغيير. تعمل في متصفحك.", keywords: ["شيفرة قيصر", "rot13", "شيفرة الإزاحة", "ترميز فك ترميز الشيفرة"], placeholder: "أدخل نصًا…", shift: "الإزاحة", rot13: "ROT13" },
  ru: { title: "Шифр Цезаря и ROT13", short: "Сдвигайте буквы на любое число для шифрования/дешифрования шифра Цезаря или примените ROT13.", description: "Бесплатный инструмент шифра Цезаря. Сдвиньте буквы текста на любое число (0–25) для шифрования или дешифрования или примените классический ROT13. Не-буквы остаются без изменений. Работает в браузере.", keywords: ["шифр цезаря", "rot13", "шифр сдвига", "шифрование дешифрование"], placeholder: "Введите текст…", shift: "Сдвиг", rot13: "ROT13" },
  zh: { title: "凯撒密码与 ROT13", short: "按任意位移对字母进行凯撒密码编码/解码，或应用 ROT13。", description: "免费的凯撒密码工具。将文本中的字母按任意位移（0–25）进行加密或解密，或应用经典的 ROT13。非字母保持不变。在浏览器中运行。", keywords: ["凯撒密码", "rot13", "位移密码", "密码编码解码", "移位密码"], placeholder: "输入文本…", shift: "位移", rot13: "ROT13" },
  ja: { title: "シーザー暗号 & ROT13", short: "文字を任意の数だけずらしてシーザー暗号を暗号化/復号、または ROT13 を適用します。", description: "無料のシーザー暗号ツール。テキストの文字を任意の数（0–25）だけずらして暗号化・復号、または定番の ROT13 を適用します。文字以外はそのまま。ブラウザ内で動作します。", keywords: ["シーザー暗号", "rot13", "シフト暗号", "暗号 エンコード デコード"], placeholder: "テキストを入力…", shift: "シフト量", rot13: "ROT13" },
  ko: { title: "시저 암호 & ROT13", short: "글자를 원하는 만큼 이동하여 시저 암호를 인코딩/디코딩하거나 ROT13을 적용합니다.", description: "무료 시저 암호 도구. 텍스트의 글자를 임의의 양(0–25)만큼 이동하여 암호화 또는 복호화하거나 고전적인 ROT13을 적용합니다. 글자가 아닌 문자는 그대로 유지됩니다. 브라우저에서 실행됩니다.", keywords: ["시저 암호", "rot13", "이동 암호", "암호 인코딩 디코딩"], placeholder: "텍스트 입력…", shift: "이동", rot13: "ROT13" },
  hi: { title: "सीज़र साइफर & ROT13", short: "अक्षरों को किसी भी मात्रा में शिफ्ट करके सीज़र साइफर एन्कोड/डिकोड करें, या ROT13 लगाएं।", description: "मुफ्त सीज़र साइफर टूल। अपने टेक्स्ट के अक्षरों को किसी भी मात्रा (0–25) में शिफ्ट करके एन्क्रिप्ट या डिक्रिप्ट करें, या क्लासिक ROT13 लगाएं। गैर-अक्षर अपरिवर्तित रहते हैं। ब्राउज़र में चलता है।", keywords: ["सीज़र साइफर", "rot13", "शिफ्ट साइफर", "साइफर एन्कोड डिकोड"], placeholder: "टेक्स्ट दर्ज करें…", shift: "शिफ्ट", rot13: "ROT13" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
