import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Text Repeater", short: "Repeat any text a chosen number of times with an optional separator.", description: "Free text repeater. Duplicate any text or string N times, separated by nothing, a space, a comma or a new line. Handy for testing, padding and quick mockups.", keywords: ["text repeater", "repeat text", "duplicate text", "repeat string", "repeat a word"], placeholder: "Enter text to repeat…", count: "Repetitions", separator: "Separator", none: "None", space: "Space", newline: "New line", comma: "Comma" },
  nl: { title: "Tekst Repeater", short: "Repeat any tekst a chosen nummer of times with an optional separator.", description: "Gratis tekst repeater. Duplicate any tekst or string N times, separated by nothing, a space, a comma or a new line. Handy for testing, padding and quick mockups.", keywords: ["tekst repeater", "repeat tekst", "duplicate tekst", "repeat string", "repeat a word"], placeholder: "Enter tekst to repeat…", count: "Repetitions", separator: "Separator", none: "None", space: "Space", newline: "New line", comma: "Comma" },

  pl: { title: "Tekst Repeater", short: "Repeat any tekst a chosen liczba of times with an optional separator.", description: "Darmowy tekst repeater. Duplicate any tekst or string N times, separated by nothing, a space, a comma or a new line. Handy for testing, padding and quick mockups.", keywords: ["tekst repeater", "repeat tekst", "duplicate tekst", "repeat string", "repeat a word"], placeholder: "Enter tekst to repeat…", count: "Repetitions", separator: "Separator", none: "None", space: "Space", newline: "New line", comma: "Comma" },
  pt: { title: "Text Repeater", short: "Repeat any text a chosen number de times com an optional separator.", description: "Gratuito - text repeater. Duplicate any text ou string N times, separated by nothing, a space, a comma ou a new line. Handy para testing, padding e quick mockups.", keywords: ["text repeater", "repeat text", "duplicate text", "repeat string", "repeat a word"], placeholder: "Enter text to repeat…", count: "Repetitions", separator: "Separator", none: "None", space: "Space", newline: "New line", comma: "Comma" },
  id: { title: "Text Repeater", short: "Repeat any text a chosen number dari times with an optional separator.", description: "Gratis - text repeater. Duplicate any text atau string N times, separated by nothing, a space, a comma atau a new line. Handy for testing, padding dan quick mockups.", keywords: ["text repeater", "repeat text", "duplicate text", "repeat string", "repeat a word"], placeholder: "Enter text to repeat…", count: "Repetitions", separator: "Separator", none: "None", space: "Space", newline: "New line", comma: "Comma" },

  tr: { title: "Metin Tekrarlayıcı", short: "Herhangi bir metni seçtiğiniz sayıda, isteğe bağlı ayırıcıyla tekrarlayın.", description: "Ücretsiz metin tekrarlayıcı. Herhangi bir metni veya dizeyi N kez çoğaltın; ayırıcısız, boşluk, virgül veya yeni satırla ayrılmış. Test, doldurma ve hızlı maketler için kullanışlı.", keywords: ["metin tekrarlayıcı", "metni tekrarla", "metni çoğalt", "dizeyi tekrarla", "kelime tekrarla"], placeholder: "Tekrarlanacak metni girin…", count: "Tekrar sayısı", separator: "Ayırıcı", none: "Yok", space: "Boşluk", newline: "Yeni satır", comma: "Virgül" },
  de: { title: "Text-Wiederholer", short: "Wiederholen Sie Text beliebig oft mit optionalem Trennzeichen.", description: "Kostenloser Text-Wiederholer. Vervielfältigen Sie Text oder Zeichenfolgen N-mal, getrennt durch nichts, Leerzeichen, Komma oder Zeilenumbruch. Praktisch für Tests und Mockups.", keywords: ["text wiederholer", "text wiederholen", "text duplizieren", "string wiederholen"], placeholder: "Text zum Wiederholen eingeben…", count: "Wiederholungen", separator: "Trennzeichen", none: "Keins", space: "Leerzeichen", newline: "Zeilenumbruch", comma: "Komma" },
  fr: { title: "Répéteur de Texte", short: "Répétez n'importe quel texte un nombre de fois choisi avec un séparateur.", description: "Répéteur de texte gratuit. Dupliquez n'importe quel texte ou chaîne N fois, séparé par rien, un espace, une virgule ou un saut de ligne. Pratique pour les tests et les maquettes.", keywords: ["répéteur de texte", "répéter du texte", "dupliquer du texte", "répéter une chaîne"], placeholder: "Saisissez le texte à répéter…", count: "Répétitions", separator: "Séparateur", none: "Aucun", space: "Espace", newline: "Saut de ligne", comma: "Virgule" },
  es: { title: "Repetidor de Texto", short: "Repite cualquier texto el número de veces que elijas con un separador.", description: "Repetidor de texto gratuito. Duplica cualquier texto o cadena N veces, separado por nada, un espacio, una coma o un salto de línea. Útil para pruebas y maquetas.", keywords: ["repetidor de texto", "repetir texto", "duplicar texto", "repetir cadena"], placeholder: "Introduce el texto a repetir…", count: "Repeticiones", separator: "Separador", none: "Ninguno", space: "Espacio", newline: "Salto de línea", comma: "Coma" },
  it: { title: "Ripetitore di Testo", short: "Ripeti qualsiasi testo un numero scelto di volte con un separatore.", description: "Ripetitore di testo gratuito. Duplica qualsiasi testo o stringa N volte, separato da nulla, uno spazio, una virgola o un a capo. Comodo per test e mockup.", keywords: ["ripetitore di testo", "ripeti testo", "duplica testo", "ripeti stringa"], placeholder: "Inserisci il testo da ripetere…", count: "Ripetizioni", separator: "Separatore", none: "Nessuno", space: "Spazio", newline: "A capo", comma: "Virgola" },
  ar: { title: "مكرّر النص", short: "كرّر أي نص بعدد المرات الذي تختاره مع فاصل اختياري.", description: "مكرّر نص مجاني. كرّر أي نص أو سلسلة N مرة، مفصولة بلا شيء أو مسافة أو فاصلة أو سطر جديد. مفيد للاختبار والنماذج.", keywords: ["مكرر النص", "تكرار النص", "تكرار النص", "تكرار سلسلة"], placeholder: "أدخل النص المراد تكراره…", count: "عدد التكرارات", separator: "الفاصل", none: "بدون", space: "مسافة", newline: "سطر جديد", comma: "فاصلة" },
  ru: { title: "Повторитель Текста", short: "Повторяйте текст выбранное число раз с необязательным разделителем.", description: "Бесплатный повторитель текста. Дублируйте любой текст или строку N раз, разделяя ничем, пробелом, запятой или новой строкой. Удобно для тестов и макетов.", keywords: ["повторитель текста", "повторить текст", "дублировать текст", "повторить строку"], placeholder: "Введите текст для повтора…", count: "Повторений", separator: "Разделитель", none: "Нет", space: "Пробел", newline: "Новая строка", comma: "Запятая" },
  zh: { title: "文本重复器", short: "用可选的分隔符将任意文本重复指定的次数。", description: "免费的文本重复器。将任意文本或字符串重复 N 次，可用无分隔、空格、逗号或换行分隔。适合测试、填充和快速原型。", keywords: ["文本重复器", "重复文本", "复制文本", "重复字符串"], placeholder: "输入要重复的文本…", count: "重复次数", separator: "分隔符", none: "无", space: "空格", newline: "换行", comma: "逗号" },
  ja: { title: "テキストリピーター", short: "任意のテキストを指定回数、任意の区切りで繰り返します。", description: "無料のテキストリピーター。任意のテキストや文字列を N 回複製し、なし・スペース・カンマ・改行で区切れます。テストや埋め草、簡単なモックアップに便利。", keywords: ["テキストリピーター", "テキスト繰り返し", "テキスト複製", "文字列繰り返し"], placeholder: "繰り返すテキストを入力…", count: "繰り返し回数", separator: "区切り", none: "なし", space: "スペース", newline: "改行", comma: "カンマ" },
  ko: { title: "텍스트 반복기", short: "원하는 횟수만큼 선택적 구분자로 텍스트를 반복합니다.", description: "무료 텍스트 반복기. 임의의 텍스트나 문자열을 N번 복제하며 없음, 공백, 쉼표 또는 줄바꿈으로 구분합니다. 테스트, 패딩, 빠른 목업에 유용합니다.", keywords: ["텍스트 반복기", "텍스트 반복", "텍스트 복제", "문자열 반복"], placeholder: "반복할 텍스트 입력…", count: "반복 횟수", separator: "구분자", none: "없음", space: "공백", newline: "줄바꿈", comma: "쉼표" },
  hi: { title: "टेक्स्ट रिपीटर", short: "किसी भी टेक्स्ट को चुनी हुई बार वैकल्पिक विभाजक के साथ दोहराएं।", description: "मुफ्त टेक्स्ट रिपीटर। किसी भी टेक्स्ट या स्ट्रिंग को N बार दोहराएं — बिना विभाजक, स्पेस, अल्पविराम या नई पंक्ति से अलग। परीक्षण और मॉकअप के लिए उपयोगी।", keywords: ["टेक्स्ट रिपीटर", "टेक्स्ट दोहराएं", "टेक्स्ट डुप्लिकेट", "स्ट्रिंग दोहराएं"], placeholder: "दोहराने के लिए टेक्स्ट दर्ज करें…", count: "पुनरावृत्तियाँ", separator: "विभाजक", none: "कोई नहीं", space: "स्पेस", newline: "नई पंक्ति", comma: "अल्पविराम" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
