import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Markdown to HTML", short: "Convert Markdown to HTML with a side-by-side live preview.", description: "Free Markdown to HTML converter. Paste Markdown to get clean HTML — headings, lists, code blocks, quotes, emphasis, links and images, all rendered in your browser.", keywords: ["markdown to html", "md to html", "markdown converter", "markdown preview", "render markdown"], input: "Markdown", html: "HTML", preview: "Preview" },
  pt: { title: "Markdown to HTML", short: "Converter Markdown para HTML com a side-by-side live preview.", description: "Gratuito - Markdown para HTML converter. Paste Markdown para get clean HTML â headings, lists, code blocks, quotes, emphasis, links e images, all rendered no seu navegador.", keywords: ["markdown to html", "md to html", "markdown converter", "markdown preview", "render markdown"], input: "Markdown", html: "HTML", preview: "Preview" },
  id: { title: "Markdown to HTML", short: "Konversi Markdown to HTML with a side-by-side live preview.", description: "Gratis - Markdown to HTML converter. Paste Markdown to get clean HTML â headings, lists, code blocks, quotes, emphasis, links dan images, all rendered di browser Anda.", keywords: ["markdown to html", "md to html", "markdown converter", "markdown preview", "render markdown"], input: "Markdown", html: "HTML", preview: "Preview" },

  tr: { title: "Markdown'dan HTML'e", short: "Markdown'ı yan yana canlı önizlemeyle HTML'e dönüştürün.", description: "Ücretsiz Markdown'dan HTML'e dönüştürücü. Markdown yapıştırın ve temiz HTML alın — başlıklar, listeler, kod blokları, alıntılar, vurgu, bağlantılar ve görseller, hepsi tarayıcınızda işlenir.", keywords: ["markdown html", "md html", "markdown dönüştürücü", "markdown önizleme", "markdown işleme"], input: "Markdown", html: "HTML", preview: "Önizleme" },
  de: { title: "Markdown zu HTML", short: "Konvertieren Sie Markdown mit Live-Vorschau zu HTML.", description: "Kostenloser Markdown-zu-HTML-Konverter. Fügen Sie Markdown ein und erhalten Sie sauberes HTML — Überschriften, Listen, Codeblöcke, Zitate, Hervorhebungen, Links und Bilder, alles im Browser gerendert.", keywords: ["markdown zu html", "md zu html", "markdown konverter", "markdown vorschau", "markdown rendern"], input: "Markdown", html: "HTML", preview: "Vorschau" },
  fr: { title: "Markdown vers HTML", short: "Convertissez Markdown en HTML avec aperçu côte à côte.", description: "Convertisseur Markdown vers HTML gratuit. Collez du Markdown pour obtenir du HTML propre — titres, listes, blocs de code, citations, emphase, liens et images, tout rendu dans votre navigateur.", keywords: ["markdown vers html", "md vers html", "convertisseur markdown", "aperçu markdown", "rendu markdown"], input: "Markdown", html: "HTML", preview: "Aperçu" },
  es: { title: "Markdown a HTML", short: "Convierte Markdown a HTML con vista previa lado a lado.", description: "Convertidor Markdown a HTML gratuito. Pega Markdown para obtener HTML limpio — encabezados, listas, bloques de código, citas, énfasis, enlaces e imágenes, todo renderizado en tu navegador.", keywords: ["markdown a html", "md a html", "convertidor markdown", "vista previa markdown", "renderizar markdown"], input: "Markdown", html: "HTML", preview: "Vista previa" },
  it: { title: "Markdown a HTML", short: "Converti Markdown in HTML con anteprima dal vivo.", description: "Convertitore Markdown a HTML gratuito. Incolla Markdown per ottenere HTML pulito — intestazioni, elenchi, blocchi di codice, citazioni, enfasi, link e immagini, tutto renderizzato nel browser.", keywords: ["markdown a html", "md a html", "convertitore markdown", "anteprima markdown", "rendering markdown"], input: "Markdown", html: "HTML", preview: "Anteprima" },
  ar: { title: "Markdown إلى HTML", short: "حوّل Markdown إلى HTML مع معاينة جنبًا إلى جنب.", description: "محوّل Markdown إلى HTML مجاني. الصق Markdown للحصول على HTML نظيف — العناوين والقوائم وكتل التعليمات البرمجية والاقتباسات والتوكيد والروابط والصور، الكل مُعاد في متصفحك.", keywords: ["markdown إلى html", "md إلى html", "محول markdown", "معاينة markdown", "عرض markdown"], input: "Markdown", html: "HTML", preview: "معاينة" },
  ru: { title: "Markdown в HTML", short: "Конвертируйте Markdown в HTML с живым превью.", description: "Бесплатный конвертер Markdown в HTML. Вставьте Markdown, чтобы получить чистый HTML — заголовки, списки, блоки кода, цитаты, выделение, ссылки и изображения, всё рендерится в браузере.", keywords: ["markdown в html", "md в html", "конвертер markdown", "превью markdown", "рендер markdown"], input: "Markdown", html: "HTML", preview: "Превью" },
  zh: { title: "Markdown 转 HTML", short: "将 Markdown 转换为 HTML 并实时预览。", description: "免费的 Markdown 转 HTML 转换器。粘贴 Markdown 获得干净的 HTML——标题、列表、代码块、引用、强调、链接和图片，全部在浏览器中渲染。", keywords: ["markdown 转 html", "md 转 html", "markdown 转换器", "markdown 预览", "渲染 markdown"], input: "Markdown", html: "HTML", preview: "预览" },
  ja: { title: "Markdown から HTML", short: "Markdown を並列ライブプレビュー付きで HTML に変換。", description: "無料の Markdown から HTML 変換ツール。Markdown を貼り付けると、見出し、リスト、コードブロック、引用、強調、リンク、画像のクリーンな HTML がブラウザでレンダリングされます。", keywords: ["markdown から html", "md から html", "markdown 変換", "markdown プレビュー", "markdown レンダリング"], input: "Markdown", html: "HTML", preview: "プレビュー" },
  ko: { title: "Markdown to HTML", short: "Markdown을 나란히 라이브 미리보기와 함께 HTML로 변환합니다.", description: "무료 Markdown to HTML 변환기. Markdown을 붙여넣으면 제목, 목록, 코드 블록, 인용문, 강조, 링크, 이미지의 깨끗한 HTML이 브라우저에서 렌더링됩니다.", keywords: ["markdown to html", "md to html", "markdown 변환기", "markdown 미리보기", "markdown 렌더링"], input: "Markdown", html: "HTML", preview: "미리보기" },
  hi: { title: "Markdown से HTML", short: "Markdown को साथ-साथ लाइव प्रीव्यू के साथ HTML में बदलें।", description: "मुफ्त Markdown से HTML कन्वर्टर। Markdown पेस्ट करके स्वच्छ HTML पाएं — शीर्षक, सूचियाँ, कोड ब्लॉक, उद्धरण, बल, लिंक और छवियाँ, सब आपके ब्राउज़र में रेंडर होते हैं।", keywords: ["markdown से html", "md से html", "markdown कन्वर्टर", "markdown प्रीव्यू", "markdown रेंडर"], input: "Markdown", html: "HTML", preview: "प्रीव्यू" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
