import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "PDF Rotator", short: "Rotate PDF pages 90, 180 or 270 degrees, in your browser.", description: "Free PDF rotator. Drop a PDF, choose an angle (90, 180, 270°) and optionally limit to specific pages — runs entirely in your browser via pdf-lib. Nothing is uploaded.", keywords: ["pdf rotator", "rotate pdf", "pdf rotate online", "turn pdf pages", "fix pdf orientation"], drop: "Drop a PDF here or click to choose", angle: "Rotation", pages: "Pages (blank = all)", run: "Rotate", download: "Download rotated.pdf" },
  tr: { title: "PDF Döndürücü", short: "PDF sayfalarını tarayıcınızda 90, 180 veya 270 derece döndürün.", description: "Ücretsiz PDF döndürücü. Bir PDF bırakın, bir açı seçin (90, 180, 270°) ve isteğe bağlı olarak belirli sayfalara sınırlandırın — tamamen tarayıcınızda pdf-lib ile çalışır. Hiçbir şey yüklenmez.", keywords: ["pdf döndürücü", "pdf döndür", "online pdf döndür", "pdf sayfa çevir", "pdf yönü düzelt"], drop: "Bir PDF bırakın veya seçmek için tıklayın", angle: "Döndürme", pages: "Sayfalar (boş = tümü)", run: "Döndür", download: "rotated.pdf indir" },
  de: { title: "PDF-Rotator", short: "Drehen Sie PDF-Seiten um 90, 180 oder 270 Grad im Browser.", description: "Kostenloser PDF-Rotator. Legen Sie eine PDF ab, wählen Sie einen Winkel (90, 180, 270°) und beschränken Sie optional auf bestimmte Seiten — läuft vollständig im Browser über pdf-lib. Nichts wird hochgeladen.", keywords: ["pdf rotator", "pdf drehen", "pdf drehen online", "pdf seiten drehen", "pdf orientierung korrigieren"], drop: "PDF hier ablegen oder klicken zum Auswählen", angle: "Drehung", pages: "Seiten (leer = alle)", run: "Drehen", download: "rotated.pdf herunterladen" },
  fr: { title: "Rotateur de PDF", short: "Faites pivoter les pages PDF de 90, 180 ou 270 degrés.", description: "Rotateur de PDF gratuit. Déposez un PDF, choisissez un angle (90, 180, 270°) et limitez éventuellement à certaines pages — fonctionne entièrement dans votre navigateur via pdf-lib. Rien n'est envoyé.", keywords: ["rotateur pdf", "faire pivoter pdf", "rotation pdf en ligne", "tourner pages pdf", "corriger orientation pdf"], drop: "Déposez un PDF ici ou cliquez pour choisir", angle: "Rotation", pages: "Pages (vide = toutes)", run: "Pivoter", download: "Télécharger rotated.pdf" },
  es: { title: "Rotador de PDF", short: "Rota páginas PDF 90, 180 o 270 grados, en tu navegador.", description: "Rotador de PDF gratuito. Arrastra un PDF, elige un ángulo (90, 180, 270°) y opcionalmente limita a páginas específicas — funciona completamente en tu navegador con pdf-lib. Nada se sube.", keywords: ["rotador pdf", "rotar pdf", "rotación pdf online", "girar páginas pdf", "corregir orientación pdf"], drop: "Arrastra un PDF aquí o haz clic para elegir", angle: "Rotación", pages: "Páginas (vacío = todas)", run: "Rotar", download: "Descargar rotated.pdf" },
  it: { title: "Rotatore di PDF", short: "Ruota pagine PDF di 90, 180 o 270 gradi nel browser.", description: "Rotatore di PDF gratuito. Trascina un PDF, scegli un angolo (90, 180, 270°) e limita opzionalmente a pagine specifiche — funziona interamente nel browser tramite pdf-lib. Nulla viene caricato.", keywords: ["rotatore pdf", "ruota pdf", "rotazione pdf online", "girare pagine pdf", "correggere orientamento pdf"], drop: "Trascina un PDF qui o clicca per scegliere", angle: "Rotazione", pages: "Pagine (vuoto = tutte)", run: "Ruota", download: "Scarica rotated.pdf" },
  ar: { title: "أداة تدوير PDF", short: "أدر صفحات PDF بزاوية 90 أو 180 أو 270 درجة في متصفحك.", description: "أداة تدوير PDF مجانية. أفلِت ملف PDF، اختر زاوية (90، 180، 270°) واختياريًا حدد صفحات معينة — يعمل بالكامل في متصفحك عبر pdf-lib. لا شيء يُرفع.", keywords: ["تدوير pdf", "أدر pdf", "تدوير pdf عبر الإنترنت", "تدوير صفحات pdf", "تصحيح اتجاه pdf"], drop: "أفلِت ملف PDF هنا أو انقر للاختيار", angle: "التدوير", pages: "الصفحات (فارغ = الكل)", run: "تدوير", download: "تنزيل rotated.pdf" },
  ru: { title: "Поворот PDF", short: "Поворачивайте страницы PDF на 90, 180 или 270 градусов.", description: "Бесплатный поворот PDF. Перетащите PDF, выберите угол (90, 180, 270°) и опционально ограничьте конкретными страницами — работает полностью в браузере через pdf-lib. Ничего не загружается.", keywords: ["поворот pdf", "повернуть pdf", "поворот pdf онлайн", "повернуть страницы pdf", "исправить ориентацию pdf"], drop: "Перетащите PDF сюда или нажмите для выбора", angle: "Поворот", pages: "Страницы (пусто = все)", run: "Повернуть", download: "Скачать rotated.pdf" },
  zh: { title: "PDF 旋转器", short: "在浏览器中将 PDF 页面旋转 90、180 或 270 度。", description: "免费的 PDF 旋转器。拖入 PDF，选择角度（90、180、270°），可选择性地限制到特定页面——通过 pdf-lib 完全在浏览器中运行。不上传任何内容。", keywords: ["pdf 旋转器", "旋转 pdf", "在线 pdf 旋转", "翻转 pdf 页面", "修正 pdf 方向"], drop: "将 PDF 拖到此处或点击选择", angle: "旋转", pages: "页面（留空 = 全部）", run: "旋转", download: "下载 rotated.pdf" },
  ja: { title: "PDF 回転", short: "ブラウザで PDF ページを 90、180、270 度回転。", description: "無料の PDF 回転ツール。PDF をドロップし、角度（90、180、270°）を選び、オプションで特定のページに限定できます——pdf-lib によりすべてブラウザ内で動作。何もアップロードされません。", keywords: ["pdf 回転", "pdf 回転 オンライン", "pdf ページ 回転", "pdf 向き 修正", "pdf ローテーター"], drop: "PDF をここにドロップまたはクリックして選択", angle: "回転", pages: "ページ（空欄 = すべて）", run: "回転", download: "rotated.pdf をダウンロード" },
  ko: { title: "PDF 회전기", short: "브라우저에서 PDF 페이지를 90, 180 또는 270도 회전합니다.", description: "무료 PDF 회전기. PDF를 드롭하고 각도(90, 180, 270°)를 선택하고 선택적으로 특정 페이지로 제한하세요 — pdf-lib를 통해 모두 브라우저에서 실행됩니다. 아무것도 업로드되지 않습니다.", keywords: ["pdf 회전기", "pdf 회전", "pdf 회전 온라인", "pdf 페이지 회전", "pdf 방향 수정"], drop: "여기에 PDF를 드롭하거나 클릭하여 선택", angle: "회전", pages: "페이지 (비어 있음 = 전체)", run: "회전", download: "rotated.pdf 다운로드" },
  hi: { title: "PDF रोटेटर", short: "अपने ब्राउज़र में PDF पेजों को 90, 180 या 270 डिग्री घुमाएं।", description: "मुफ्त PDF रोटेटर। एक PDF छोड़ें, एक कोण चुनें (90, 180, 270°) और वैकल्पिक रूप से विशिष्ट पेजों तक सीमित करें — pdf-lib के माध्यम से पूरी तरह आपके ब्राउज़र में चलता है। कुछ भी अपलोड नहीं होता।", keywords: ["pdf रोटेटर", "pdf घुमाएं", "ऑनलाइन pdf रोटेट", "pdf पेज पलटें", "pdf ओरिएंटेशन ठीक करें"], drop: "यहाँ एक PDF छोड़ें या चुनने के लिए क्लिक करें", angle: "घूर्णन", pages: "पेज (खाली = सभी)", run: "घुमाएं", download: "rotated.pdf डाउनलोड" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
