import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Bandwidth / Download Time Calculator", short: "How long will this file take to download at this speed?", description: "Free bandwidth calculator. Enter a file size and a connection speed (Kbps / Mbps / Gbps) to see the estimated download time — handy for sizing transfers and planning rollouts.", keywords: ["bandwidth calculator", "download time calculator", "transfer time", "mbps to mb/s", "file download estimator"], size: "File size", speed: "Connection speed", duration: "Estimated duration" },
  pt: { title: "Bandwidth / Download Time Calculator", short: "How long will this file take to download at this speed?", description: "Free bandwidth calculator. Enter a file size and a connection speed (Kbps / Mbps / Gbps) to see the estimated download time — handy for sizing transfers and planning rollouts.", keywords: ["bandwidth calculator", "download time calculator", "transfer time", "mbps to mb/s", "file download estimator"], size: "File size", speed: "Connection speed", duration: "Estimated duration" },
  id: { title: "Bandwidth / Download Time Calculator", short: "How long will this file take to download at this speed?", description: "Free bandwidth calculator. Enter a file size and a connection speed (Kbps / Mbps / Gbps) to see the estimated download time — handy for sizing transfers and planning rollouts.", keywords: ["bandwidth calculator", "download time calculator", "transfer time", "mbps to mb/s", "file download estimator"], size: "File size", speed: "Connection speed", duration: "Estimated duration" },

  tr: { title: "Bant Genişliği / İndirme Süresi Hesaplayıcı", short: "Bu dosyayı bu hızda ne kadar sürede indirebilirsiniz?", description: "Ücretsiz bant genişliği hesaplayıcı. Bir dosya boyutu ve bağlantı hızı (Kbps / Mbps / Gbps) girin ve tahmini indirme süresini görün — aktarımları boyutlandırmak ve dağıtımları planlamak için kullanışlı.", keywords: ["bant genişliği hesaplayıcı", "indirme süresi hesaplayıcı", "aktarım süresi", "mbps mb/s", "dosya indirme tahmincisi"], size: "Dosya boyutu", speed: "Bağlantı hızı", duration: "Tahmini süre" },
  de: { title: "Bandbreiten- / Downloadzeit-Rechner", short: "Wie lange dauert der Download dieser Datei bei dieser Geschwindigkeit?", description: "Kostenloser Bandbreiten-Rechner. Geben Sie eine Dateigröße und Verbindungsgeschwindigkeit (Kbps / Mbps / Gbps) ein, um die geschätzte Downloadzeit zu sehen — praktisch zum Dimensionieren von Transfers und Planen von Rollouts.", keywords: ["bandbreiten rechner", "downloadzeit rechner", "übertragungszeit", "mbps zu mb/s", "datei download schätzer"], size: "Dateigröße", speed: "Verbindungsgeschwindigkeit", duration: "Geschätzte Dauer" },
  fr: { title: "Calculateur Bande Passante / Temps de Téléchargement", short: "Combien de temps prendra ce fichier à cette vitesse ?", description: "Calculateur de bande passante gratuit. Entrez une taille de fichier et une vitesse de connexion (Kbps / Mbps / Gbps) pour voir le temps de téléchargement estimé — utile pour dimensionner les transferts et planifier les déploiements.", keywords: ["calculateur bande passante", "calculateur temps téléchargement", "temps transfert", "mbps vers mo/s", "estimateur téléchargement fichier"], size: "Taille du fichier", speed: "Vitesse de connexion", duration: "Durée estimée" },
  es: { title: "Calculadora de Ancho de Banda / Tiempo de Descarga", short: "¿Cuánto tardará este archivo en descargarse a esta velocidad?", description: "Calculadora de ancho de banda gratuita. Ingresa un tamaño de archivo y velocidad de conexión (Kbps / Mbps / Gbps) para ver el tiempo de descarga estimado — útil para dimensionar transferencias y planificar despliegues.", keywords: ["calculadora ancho banda", "calculadora tiempo descarga", "tiempo transferencia", "mbps a mb/s", "estimador descarga archivo"], size: "Tamaño archivo", speed: "Velocidad conexión", duration: "Duración estimada" },
  it: { title: "Calcolatore Banda / Tempo di Download", short: "Quanto tempo impiegherà questo file a questa velocità?", description: "Calcolatore di banda gratuito. Inserisci la dimensione del file e la velocità di connessione (Kbps / Mbps / Gbps) per vedere il tempo di download stimato — utile per dimensionare trasferimenti e pianificare distribuzioni.", keywords: ["calcolatore banda", "calcolatore tempo download", "tempo trasferimento", "mbps a mb/s", "stimatore download file"], size: "Dimensione file", speed: "Velocità connessione", duration: "Durata stimata" },
  ar: { title: "حاسبة عرض النطاق / زمن التنزيل", short: "كم سيستغرق تنزيل هذا الملف عند هذه السرعة؟", description: "حاسبة عرض النطاق مجانية. أدخل حجم الملف وسرعة الاتصال (Kbps / Mbps / Gbps) لرؤية وقت التنزيل المُقدَّر — مفيدة لتحديد حجم النقل وتخطيط عمليات النشر.", keywords: ["حاسبة عرض النطاق", "حاسبة زمن التنزيل", "زمن النقل", "mbps إلى mb/s", "مقدر تنزيل الملف"], size: "حجم الملف", speed: "سرعة الاتصال", duration: "المدة المقدرة" },
  ru: { title: "Калькулятор пропускной способности / времени загрузки", short: "Сколько времени уйдёт на скачивание файла на этой скорости?", description: "Бесплатный калькулятор пропускной способности. Введите размер файла и скорость соединения (Kbps / Mbps / Gbps), чтобы увидеть оценочное время загрузки — удобно для планирования передач и развёртываний.", keywords: ["калькулятор пропускной способности", "калькулятор времени загрузки", "время передачи", "mbps в mb/s", "оценщик загрузки файла"], size: "Размер файла", speed: "Скорость соединения", duration: "Оценочная длительность" },
  zh: { title: "带宽 / 下载时间计算器", short: "在此速度下下载此文件需要多长时间？", description: "免费的带宽计算器。输入文件大小和连接速度（Kbps / Mbps / Gbps）以查看估计下载时间——适用于调整传输大小和规划部署。", keywords: ["带宽计算器", "下载时间计算器", "传输时间", "mbps 转 mb/s", "文件下载估算"], size: "文件大小", speed: "连接速度", duration: "估计时长" },
  ja: { title: "帯域幅 / ダウンロード時間計算機", short: "この速度でこのファイルをダウンロードするのにどのくらいかかるか？", description: "無料の帯域幅計算機。ファイルサイズと接続速度（Kbps / Mbps / Gbps）を入力して推定ダウンロード時間を確認——転送のサイズ調整やロールアウト計画に便利。", keywords: ["帯域幅 計算", "ダウンロード 時間 計算", "転送 時間", "mbps から mb/s", "ファイル ダウンロード 推定"], size: "ファイルサイズ", speed: "接続速度", duration: "推定時間" },
  ko: { title: "대역폭 / 다운로드 시간 계산기", short: "이 속도에서 이 파일을 다운로드하는 데 얼마나 걸릴까요?", description: "무료 대역폭 계산기. 파일 크기와 연결 속도(Kbps / Mbps / Gbps)를 입력해 예상 다운로드 시간을 확인하세요 — 전송 크기 조정 및 롤아웃 계획에 유용합니다.", keywords: ["대역폭 계산기", "다운로드 시간 계산기", "전송 시간", "mbps를 mb/s", "파일 다운로드 추정기"], size: "파일 크기", speed: "연결 속도", duration: "예상 시간" },
  hi: { title: "बैंडविड्थ / डाउनलोड समय कैलकुलेटर", short: "इस गति पर इस फ़ाइल को डाउनलोड करने में कितना समय लगेगा?", description: "मुफ्त बैंडविड्थ कैलकुलेटर। फ़ाइल आकार और कनेक्शन गति (Kbps / Mbps / Gbps) दर्ज करें ताकि अनुमानित डाउनलोड समय देख सकें — स्थानांतरण आकार और रोलआउट योजना के लिए उपयोगी।", keywords: ["बैंडविड्थ कैलकुलेटर", "डाउनलोड समय कैलकुलेटर", "स्थानांतरण समय", "mbps से mb/s", "फ़ाइल डाउनलोड अनुमानक"], size: "फ़ाइल आकार", speed: "कनेक्शन गति", duration: "अनुमानित अवधि" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
