import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "DMARC Record Generator", short: "Build a DMARC TXT record from a simple form.", description: "Free DMARC record generator. Choose a policy (none, quarantine, reject), set percentage, rua/ruf reporting addresses and SPF/DKIM alignment, and get a ready-to-publish DMARC TXT record plus the _dmarc host name. Runs entirely in your browser.", keywords: ["dmarc generator", "dmarc record builder", "dmarc policy", "email authentication", "create dmarc record"], domain: "Domain", policy: "Policy (p)", subPolicy: "Subdomain policy (sp)", pct: "Percentage (pct)", rua: "Aggregate reports (rua)", ruf: "Forensic reports (ruf)", adkim: "DKIM alignment (adkim)", aspf: "SPF alignment (aspf)", fo: "Forensic options (fo)", record: "DMARC record", host: "DNS host", none: "none (monitor only)", quarantine: "quarantine", reject: "reject", strict: "strict (s)", relaxed: "relaxed (r)", notSet: "Not set", hint: "Publish the generated TXT record at the shown _dmarc host in your DNS." },
  pt: { title: "Gerador de Registro DMARC", short: "Crie um registro TXT DMARC a partir de um formulário simples.", description: "Gerador de registro DMARC gratuito. Escolha uma política (none, quarantine, reject), defina a porcentagem, endereços de relatório rua/ruf e alinhamento SPF/DKIM, e obtenha um registro TXT DMARC pronto para publicar, além do nome do host _dmarc. Roda inteiramente no navegador.", keywords: ["dmarc generator", "dmarc record builder", "dmarc policy", "email authentication", "create dmarc record"], domain: "Domínio", policy: "Política (p)", subPolicy: "Política de subdomínio (sp)", pct: "Porcentagem (pct)", rua: "Relatórios agregados (rua)", ruf: "Relatórios forenses (ruf)", adkim: "Alinhamento DKIM (adkim)", aspf: "Alinhamento SPF (aspf)", fo: "Opções forenses (fo)", record: "Registro DMARC", host: "Host DNS", none: "none (apenas monitorar)", quarantine: "quarantine", reject: "reject", strict: "estrito (s)", relaxed: "relaxado (r)", notSet: "Não definido", hint: "Publique o registro TXT gerado no host _dmarc mostrado no seu DNS." },
  id: { title: "Pembuat Rekaman DMARC", short: "Buat rekaman TXT DMARC dari formulir sederhana.", description: "Pembuat rekaman DMARC gratis. Pilih kebijakan (none, quarantine, reject), atur persentase, alamat laporan rua/ruf, dan penyelarasan SPF/DKIM, lalu dapatkan rekaman TXT DMARC siap pakai beserta nama host _dmarc. Berjalan sepenuhnya di browser Anda.", keywords: ["dmarc generator", "dmarc record builder", "dmarc policy", "email authentication", "create dmarc record"], domain: "Domain", policy: "Kebijakan (p)", subPolicy: "Kebijakan subdomain (sp)", pct: "Persentase (pct)", rua: "Laporan agregat (rua)", ruf: "Laporan forensik (ruf)", adkim: "Penyelarasan DKIM (adkim)", aspf: "Penyelarasan SPF (aspf)", fo: "Opsi forensik (fo)", record: "Rekaman DMARC", host: "Host DNS", none: "none (hanya pantau)", quarantine: "quarantine", reject: "reject", strict: "ketat (s)", relaxed: "longgar (r)", notSet: "Tidak diatur", hint: "Publikasikan rekaman TXT yang dibuat di host _dmarc yang ditampilkan di DNS Anda." },

  tr: { title: "DMARC Kaydı Oluşturucu", short: "Basit bir formdan DMARC TXT kaydı oluşturun.", description: "Ücretsiz DMARC kaydı oluşturucu. Bir politika seçin (none, quarantine, reject), yüzdeyi, rua/ruf rapor adreslerini ve SPF/DKIM hizalamasını ayarlayın; yayınlamaya hazır bir DMARC TXT kaydı ile _dmarc host adını alın. Tamamen tarayıcınızda çalışır.", keywords: ["dmarc oluşturucu", "dmarc kaydı oluşturucu", "dmarc politikası", "e-posta kimlik doğrulama", "dmarc kaydı oluştur"], domain: "Alan adı", policy: "Politika (p)", subPolicy: "Alt alan politikası (sp)", pct: "Yüzde (pct)", rua: "Toplu raporlar (rua)", ruf: "Adli raporlar (ruf)", adkim: "DKIM hizalama (adkim)", aspf: "SPF hizalama (aspf)", fo: "Adli seçenekler (fo)", record: "DMARC kaydı", host: "DNS host", none: "none (yalnızca izle)", quarantine: "quarantine", reject: "reject", strict: "katı (s)", relaxed: "esnek (r)", notSet: "Ayarlanmadı", hint: "Oluşturulan TXT kaydını DNS'inizde gösterilen _dmarc host'unda yayınlayın." },
  de: { title: "DMARC-Eintrag-Generator", short: "DMARC-TXT-Eintrag aus einem einfachen Formular erstellen.", description: "Kostenloser DMARC-Eintrag-Generator. Wählen Sie eine Richtlinie (none, quarantine, reject), legen Sie Prozentsatz, rua/ruf-Berichtsadressen und SPF/DKIM-Ausrichtung fest und erhalten Sie einen publikationsfertigen DMARC-TXT-Eintrag samt _dmarc-Hostname. Läuft vollständig in Ihrem Browser.", keywords: ["dmarc generator", "dmarc eintrag generator", "dmarc richtlinie", "e-mail authentifizierung", "dmarc eintrag erstellen"], domain: "Domain", policy: "Richtlinie (p)", subPolicy: "Subdomain-Richtlinie (sp)", pct: "Prozentsatz (pct)", rua: "Aggregierte Berichte (rua)", ruf: "Forensische Berichte (ruf)", adkim: "DKIM-Ausrichtung (adkim)", aspf: "SPF-Ausrichtung (aspf)", fo: "Forensik-Optionen (fo)", record: "DMARC-Eintrag", host: "DNS-Host", none: "none (nur überwachen)", quarantine: "quarantine", reject: "reject", strict: "strikt (s)", relaxed: "locker (r)", notSet: "Nicht gesetzt", hint: "Veröffentlichen Sie den erzeugten TXT-Eintrag am angezeigten _dmarc-Host in Ihrem DNS." },
  fr: { title: "Générateur d'Enregistrement DMARC", short: "Créez un enregistrement TXT DMARC à partir d'un formulaire simple.", description: "Générateur d'enregistrement DMARC gratuit. Choisissez une politique (none, quarantine, reject), définissez le pourcentage, les adresses de rapport rua/ruf et l'alignement SPF/DKIM, et obtenez un enregistrement TXT DMARC prêt à publier ainsi que le nom d'hôte _dmarc. Fonctionne entièrement dans votre navigateur.", keywords: ["générateur dmarc", "création enregistrement dmarc", "politique dmarc", "authentification email", "créer enregistrement dmarc"], domain: "Domaine", policy: "Politique (p)", subPolicy: "Politique de sous-domaine (sp)", pct: "Pourcentage (pct)", rua: "Rapports agrégés (rua)", ruf: "Rapports forensiques (ruf)", adkim: "Alignement DKIM (adkim)", aspf: "Alignement SPF (aspf)", fo: "Options forensiques (fo)", record: "Enregistrement DMARC", host: "Hôte DNS", none: "none (surveillance seule)", quarantine: "quarantine", reject: "reject", strict: "strict (s)", relaxed: "souple (r)", notSet: "Non défini", hint: "Publiez l'enregistrement TXT généré sur l'hôte _dmarc affiché dans votre DNS." },
  es: { title: "Generador de Registro DMARC", short: "Crea un registro TXT DMARC a partir de un formulario simple.", description: "Generador de registro DMARC gratuito. Elige una política (none, quarantine, reject), establece el porcentaje, las direcciones de informe rua/ruf y la alineación SPF/DKIM, y obtén un registro TXT DMARC listo para publicar junto con el nombre de host _dmarc. Funciona completamente en tu navegador.", keywords: ["generador dmarc", "creador de registro dmarc", "política dmarc", "autenticación de correo", "crear registro dmarc"], domain: "Dominio", policy: "Política (p)", subPolicy: "Política de subdominio (sp)", pct: "Porcentaje (pct)", rua: "Informes agregados (rua)", ruf: "Informes forenses (ruf)", adkim: "Alineación DKIM (adkim)", aspf: "Alineación SPF (aspf)", fo: "Opciones forenses (fo)", record: "Registro DMARC", host: "Host DNS", none: "none (solo monitorear)", quarantine: "quarantine", reject: "reject", strict: "estricto (s)", relaxed: "relajado (r)", notSet: "No establecido", hint: "Publica el registro TXT generado en el host _dmarc mostrado en tu DNS." },
  it: { title: "Generatore di Record DMARC", short: "Crea un record TXT DMARC da un modulo semplice.", description: "Generatore di record DMARC gratuito. Scegli una policy (none, quarantine, reject), imposta la percentuale, gli indirizzi di report rua/ruf e l'allineamento SPF/DKIM, e ottieni un record TXT DMARC pronto da pubblicare insieme al nome host _dmarc. Funziona interamente nel tuo browser.", keywords: ["generatore dmarc", "creazione record dmarc", "policy dmarc", "autenticazione email", "crea record dmarc"], domain: "Dominio", policy: "Policy (p)", subPolicy: "Policy sottodominio (sp)", pct: "Percentuale (pct)", rua: "Report aggregati (rua)", ruf: "Report forensi (ruf)", adkim: "Allineamento DKIM (adkim)", aspf: "Allineamento SPF (aspf)", fo: "Opzioni forensi (fo)", record: "Record DMARC", host: "Host DNS", none: "none (solo monitoraggio)", quarantine: "quarantine", reject: "reject", strict: "rigido (s)", relaxed: "rilassato (r)", notSet: "Non impostato", hint: "Pubblica il record TXT generato sull'host _dmarc mostrato nel tuo DNS." },
  ar: { title: "مولّد سجل DMARC", short: "أنشئ سجل TXT لـ DMARC من نموذج بسيط.", description: "مولّد سجل DMARC مجاني. اختر سياسة (none أو quarantine أو reject)، واضبط النسبة المئوية وعناوين تقارير rua/ruf ومحاذاة SPF/DKIM، واحصل على سجل TXT لـ DMARC جاهز للنشر مع اسم مضيف _dmarc. يعمل بالكامل في متصفحك.", keywords: ["مولّد dmarc", "منشئ سجل dmarc", "سياسة dmarc", "مصادقة البريد", "إنشاء سجل dmarc"], domain: "النطاق", policy: "السياسة (p)", subPolicy: "سياسة النطاق الفرعي (sp)", pct: "النسبة (pct)", rua: "التقارير المجمّعة (rua)", ruf: "التقارير الجنائية (ruf)", adkim: "محاذاة DKIM (adkim)", aspf: "محاذاة SPF (aspf)", fo: "خيارات جنائية (fo)", record: "سجل DMARC", host: "مضيف DNS", none: "none (مراقبة فقط)", quarantine: "quarantine", reject: "reject", strict: "صارم (s)", relaxed: "مرن (r)", notSet: "غير محدد", hint: "انشر سجل TXT المُنشأ على مضيف _dmarc المعروض في DNS الخاص بك." },
  ru: { title: "Генератор DMARC-записи", short: "Создайте DMARC TXT-запись из простой формы.", description: "Бесплатный генератор DMARC-записи. Выберите политику (none, quarantine, reject), задайте процент, адреса отчётов rua/ruf и выравнивание SPF/DKIM, и получите готовую к публикации DMARC TXT-запись вместе с именем хоста _dmarc. Работает полностью в браузере.", keywords: ["генератор dmarc", "создание dmarc записи", "политика dmarc", "аутентификация почты", "создать dmarc запись"], domain: "Домен", policy: "Политика (p)", subPolicy: "Политика поддомена (sp)", pct: "Процент (pct)", rua: "Сводные отчёты (rua)", ruf: "Криминалистические отчёты (ruf)", adkim: "Выравнивание DKIM (adkim)", aspf: "Выравнивание SPF (aspf)", fo: "Криминалистические опции (fo)", record: "DMARC-запись", host: "DNS-хост", none: "none (только мониторинг)", quarantine: "quarantine", reject: "reject", strict: "строгое (s)", relaxed: "нестрогое (r)", notSet: "Не задано", hint: "Опубликуйте сгенерированную TXT-запись на показанном хосте _dmarc в вашем DNS." },
  zh: { title: "DMARC 记录生成器", short: "通过简单表单生成 DMARC TXT 记录。", description: "免费的 DMARC 记录生成器。选择策略（none、quarantine、reject），设置百分比、rua/ruf 报告地址和 SPF/DKIM 对齐方式，即可获得可直接发布的 DMARC TXT 记录以及 _dmarc 主机名。完全在浏览器中运行。", keywords: ["dmarc 生成器", "dmarc 记录生成", "dmarc 策略", "邮件认证", "创建 dmarc 记录"], domain: "域名", policy: "策略 (p)", subPolicy: "子域策略 (sp)", pct: "百分比 (pct)", rua: "汇总报告 (rua)", ruf: "取证报告 (ruf)", adkim: "DKIM 对齐 (adkim)", aspf: "SPF 对齐 (aspf)", fo: "取证选项 (fo)", record: "DMARC 记录", host: "DNS 主机", none: "none（仅监控）", quarantine: "quarantine", reject: "reject", strict: "严格 (s)", relaxed: "宽松 (r)", notSet: "未设置", hint: "将生成的 TXT 记录发布到 DNS 中显示的 _dmarc 主机。" },
  ja: { title: "DMARC レコードジェネレーター", short: "簡単なフォームから DMARC TXT レコードを作成します。", description: "無料の DMARC レコードジェネレーター。ポリシー（none、quarantine、reject）を選択し、割合、rua/ruf レポートアドレス、SPF/DKIM アラインメントを設定すると、公開できる DMARC TXT レコードと _dmarc ホスト名が得られます。完全にブラウザ内で動作します。", keywords: ["dmarc ジェネレーター", "dmarc レコード作成", "dmarc ポリシー", "メール認証", "dmarc レコード作成"], domain: "ドメイン", policy: "ポリシー (p)", subPolicy: "サブドメインポリシー (sp)", pct: "割合 (pct)", rua: "集計レポート (rua)", ruf: "フォレンジックレポート (ruf)", adkim: "DKIM アラインメント (adkim)", aspf: "SPF アラインメント (aspf)", fo: "フォレンジックオプション (fo)", record: "DMARC レコード", host: "DNS ホスト", none: "none（監視のみ）", quarantine: "quarantine", reject: "reject", strict: "厳格 (s)", relaxed: "緩和 (r)", notSet: "未設定", hint: "生成された TXT レコードを DNS の表示された _dmarc ホストに公開してください。" },
  ko: { title: "DMARC 레코드 생성기", short: "간단한 양식으로 DMARC TXT 레코드를 생성합니다.", description: "무료 DMARC 레코드 생성기. 정책(none, quarantine, reject)을 선택하고 백분율, rua/ruf 보고 주소, SPF/DKIM 정렬을 설정하면 게시 준비가 된 DMARC TXT 레코드와 _dmarc 호스트 이름을 얻습니다. 완전히 브라우저에서 실행됩니다.", keywords: ["dmarc 생성기", "dmarc 레코드 생성", "dmarc 정책", "이메일 인증", "dmarc 레코드 만들기"], domain: "도메인", policy: "정책 (p)", subPolicy: "하위 도메인 정책 (sp)", pct: "백분율 (pct)", rua: "집계 보고 (rua)", ruf: "포렌식 보고 (ruf)", adkim: "DKIM 정렬 (adkim)", aspf: "SPF 정렬 (aspf)", fo: "포렌식 옵션 (fo)", record: "DMARC 레코드", host: "DNS 호스트", none: "none(모니터링만)", quarantine: "quarantine", reject: "reject", strict: "엄격 (s)", relaxed: "완화 (r)", notSet: "설정 안 함", hint: "생성된 TXT 레코드를 DNS에 표시된 _dmarc 호스트에 게시하세요." },
  hi: { title: "DMARC रिकॉर्ड जेनरेटर", short: "एक सरल फ़ॉर्म से DMARC TXT रिकॉर्ड बनाएं।", description: "मुफ्त DMARC रिकॉर्ड जेनरेटर। एक नीति चुनें (none, quarantine, reject), प्रतिशत, rua/ruf रिपोर्ट पते और SPF/DKIM संरेखण सेट करें, और प्रकाशित करने के लिए तैयार DMARC TXT रिकॉर्ड के साथ _dmarc होस्ट नाम पाएं। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["dmarc generator", "dmarc record builder", "dmarc policy", "email authentication", "create dmarc record"], domain: "डोमेन", policy: "नीति (p)", subPolicy: "सबडोमेन नीति (sp)", pct: "प्रतिशत (pct)", rua: "समग्र रिपोर्ट (rua)", ruf: "फोरेंसिक रिपोर्ट (ruf)", adkim: "DKIM संरेखण (adkim)", aspf: "SPF संरेखण (aspf)", fo: "फोरेंसिक विकल्प (fo)", record: "DMARC रिकॉर्ड", host: "DNS होस्ट", none: "none (केवल निगरानी)", quarantine: "quarantine", reject: "reject", strict: "सख्त (s)", relaxed: "ढीला (r)", notSet: "सेट नहीं", hint: "उत्पन्न TXT रिकॉर्ड को अपने DNS में दिखाए गए _dmarc होस्ट पर प्रकाशित करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
