import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Multi URL Opener", short: "Open many URLs at once, each in its own new browser tab.", description: "Free multi URL opener. Paste a list of links, one per line, and open them all in new tabs with a single click. Missing https:// is added automatically. Runs entirely in your browser.", keywords: ["multi url opener", "open multiple urls", "bulk url opener", "open links in new tabs", "batch link opener"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Open all", count: "{n} valid URL(s) detected.", popupNote: "Your browser may block opening multiple tabs. Allow popups for this site if some links don't open." },
  pt: { title: "Multi URL Opener", short: "Open many URLs at once, cada um em sua own new aba do browser.", description: "Gratuito - multi url opener. Paste a list of links, one per line, e open them all em new tabs com a single click. Missing https:// é added automatically. Runs entirely no seu navegador.", keywords: ["multi url opener", "open multiple urls", "bulk url opener", "open links in new tabs", "batch link opener"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Abrir todos", count: "{n} URL(s) válida(s) detectada(s).", popupNote: "Seu navegador pode bloquear a abertura de várias abas. Permita pop-ups para este site se alguns links não abrirem." },
  id: { title: "Multi URL Opener", short: "Open many URLs sekaligus, masing-masing di tab browser baru.", description: "Gratis - multi url opener. Paste a list of links, one per line, dan open them all di new tabs dengan a single click. Missing https:// ditambahkan automatically. Runs entirely di browser Anda.", keywords: ["multi url opener", "open multiple urls", "bulk url opener", "open links in new tabs", "batch link opener"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Buka semua", count: "{n} URL valid terdeteksi.", popupNote: "Browser Anda mungkin memblokir pembukaan beberapa tab. Izinkan pop-up untuk situs ini jika beberapa tautan tidak terbuka." },

  tr: { title: "Çoklu URL Açıcı", short: "Birçok URL'yi tek seferde, her birini yeni bir sekmede açın.", description: "Ücretsiz çoklu URL açıcı. Her satıra bir tane olacak şekilde bir bağlantı listesi yapıştırın ve tek tıklamayla hepsini yeni sekmelerde açın. Eksik https:// otomatik eklenir. Tamamen tarayıcınızda çalışır.", keywords: ["çoklu url açıcı", "birden fazla url aç", "toplu url açıcı", "bağlantıları yeni sekmede aç", "toplu bağlantı açıcı"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Tümünü aç", count: "{n} geçerli URL bulundu.", popupNote: "Tarayıcınız birden fazla sekme açmayı engelleyebilir. Bazı bağlantılar açılmazsa bu site için açılır pencerelere izin verin." },
  de: { title: "Multi-URL-Öffner", short: "Öffnen Sie viele URLs auf einmal, jede in einem eigenen neuen Tab.", description: "Kostenloser Multi-URL-Öffner. Fügen Sie eine Liste von Links ein, einen pro Zeile, und öffnen Sie alle mit einem Klick in neuen Tabs. Fehlendes https:// wird automatisch ergänzt. Läuft vollständig in Ihrem Browser.", keywords: ["multi url öffner", "mehrere urls öffnen", "massen url öffner", "links in neuen tabs öffnen", "stapel link öffner"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Alle öffnen", count: "{n} gültige URL(s) erkannt.", popupNote: "Ihr Browser blockiert möglicherweise das Öffnen mehrerer Tabs. Erlauben Sie Popups für diese Seite, falls einige Links nicht öffnen." },
  fr: { title: "Ouvre-URL Multiple", short: "Ouvrez plusieurs URL d'un coup, chacune dans un nouvel onglet.", description: "Ouvre-URL multiple gratuit. Collez une liste de liens, un par ligne, et ouvrez-les tous dans de nouveaux onglets en un clic. Le https:// manquant est ajouté automatiquement. Fonctionne entièrement dans votre navigateur.", keywords: ["ouvre url multiple", "ouvrir plusieurs urls", "ouvre url en masse", "ouvrir liens nouveaux onglets", "ouvre liens par lot"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Tout ouvrir", count: "{n} URL valide(s) détectée(s).", popupNote: "Votre navigateur peut bloquer l'ouverture de plusieurs onglets. Autorisez les pop-ups pour ce site si certains liens ne s'ouvrent pas." },
  es: { title: "Abridor de URL Múltiples", short: "Abre muchas URL a la vez, cada una en su propia pestaña nueva.", description: "Abridor de URL múltiples gratuito. Pega una lista de enlaces, uno por línea, y ábrelos todos en pestañas nuevas con un clic. El https:// que falta se añade automáticamente. Funciona enteramente en tu navegador.", keywords: ["abridor de url múltiples", "abrir varias urls", "abridor de url masivo", "abrir enlaces en pestañas nuevas", "abridor de enlaces por lotes"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Abrir todo", count: "{n} URL válida(s) detectada(s).", popupNote: "Tu navegador puede bloquear la apertura de varias pestañas. Permite ventanas emergentes para este sitio si algunos enlaces no se abren." },
  it: { title: "Apri URL Multiple", short: "Apri molte URL in una volta, ciascuna in una nuova scheda.", description: "Apri URL multiple gratuito. Incolla un elenco di link, uno per riga, e aprili tutti in nuove schede con un clic. Lo https:// mancante viene aggiunto automaticamente. Funziona interamente nel tuo browser.", keywords: ["apri url multiple", "apri più url", "apri url in massa", "apri link in nuove schede", "apri link in batch"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Apri tutto", count: "{n} URL valida/e rilevata/e.", popupNote: "Il browser potrebbe bloccare l'apertura di più schede. Consenti i popup per questo sito se alcuni link non si aprono." },
  ar: { title: "فاتح روابط متعدد", short: "افتح روابط متعددة دفعة واحدة، كل رابط في علامة تبويب جديدة.", description: "فاتح روابط متعدد مجاني. الصق قائمة روابط، رابطًا في كل سطر، وافتحها كلها في علامات تبويب جديدة بنقرة واحدة. تُضاف https:// المفقودة تلقائيًا. يعمل بالكامل في متصفحك.", keywords: ["فاتح روابط متعدد", "فتح روابط متعددة", "فاتح روابط مجمّع", "فتح روابط في علامات تبويب", "فتح روابط دفعة"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "افتح الكل", count: "تم اكتشاف {n} رابطًا صالحًا.", popupNote: "قد يحظر متصفحك فتح عدة علامات تبويب. اسمح بالنوافذ المنبثقة لهذا الموقع إذا لم تُفتح بعض الروابط." },
  ru: { title: "Открыватель Нескольких URL", short: "Откройте сразу множество URL, каждый в новой вкладке браузера.", description: "Бесплатный открыватель нескольких URL. Вставьте список ссылок, по одной на строку, и откройте их все в новых вкладках одним кликом. Отсутствующий https:// добавляется автоматически. Работает полностью в браузере.", keywords: ["открыватель нескольких url", "открыть несколько url", "массовый открыватель url", "открыть ссылки в новых вкладках", "пакетный открыватель ссылок"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "Открыть все", count: "Обнаружено допустимых URL: {n}.", popupNote: "Браузер может блокировать открытие нескольких вкладок. Разрешите всплывающие окна для этого сайта, если некоторые ссылки не открываются." },
  zh: { title: "批量网址打开器", short: "一次打开多个网址，每个网址在新的浏览器标签页中打开。", description: "免费的批量网址打开器。粘贴一份链接列表，每行一个，单击即可在新标签页中全部打开。缺少的 https:// 会自动补全。完全在浏览器中运行。", keywords: ["批量网址打开器", "打开多个网址", "批量链接打开器", "在新标签页打开链接", "批量打开链接"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "全部打开", count: "检测到 {n} 个有效网址。", popupNote: "您的浏览器可能会阻止打开多个标签页。如果某些链接未打开，请允许此站点的弹出窗口。" },
  ja: { title: "複数URLオープナー", short: "多数のURLを一度に、それぞれ新しいタブで開きます。", description: "無料の複数URLオープナー。1行に1つずつリンクのリストを貼り付け、ワンクリックですべて新しいタブで開きます。不足している https:// は自動的に補われます。すべてブラウザ内で動作します。", keywords: ["複数urlオープナー", "複数のurlを開く", "一括urlオープナー", "リンクを新しいタブで開く", "一括リンクオープナー"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "すべて開く", count: "{n} 件の有効なURLを検出しました。", popupNote: "ブラウザが複数タブの表示をブロックする場合があります。一部のリンクが開かない場合は、このサイトのポップアップを許可してください。" },
  ko: { title: "다중 URL 열기", short: "여러 URL을 한 번에 각각 새 브라우저 탭에서 엽니다.", description: "무료 다중 URL 열기 도구. 한 줄에 하나씩 링크 목록을 붙여넣고 클릭 한 번으로 모두 새 탭에서 엽니다. 누락된 https:// 는 자동으로 추가됩니다. 모두 브라우저에서 실행됩니다.", keywords: ["다중 url 열기", "여러 url 열기", "대량 url 열기", "링크 새 탭에서 열기", "일괄 링크 열기"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "모두 열기", count: "유효한 URL {n}개를 감지했습니다.", popupNote: "브라우저가 여러 탭 열기를 차단할 수 있습니다. 일부 링크가 열리지 않으면 이 사이트의 팝업을 허용하세요." },
  hi: { title: "मल्टी URL ओपनर", short: "कई URL एक साथ खोलें, हर एक अपने नए ब्राउज़र टैब में।", description: "मुफ्त मल्टी URL ओपनर। प्रति पंक्ति एक लिंक की सूची चिपकाएँ और एक क्लिक में उन्हें नए टैब में खोलें। गायब https:// अपने आप जोड़ दिया जाता है। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["मल्टी url ओपनर", "कई url खोलें", "बल्क url ओपनर", "लिंक नए टैब में खोलें", "बैच लिंक ओपनर"], placeholder: "https://example.com\nexample.org\nhttps://example.net/page", openAll: "सभी खोलें", count: "{n} मान्य URL मिले।", popupNote: "आपका ब्राउज़र कई टैब खोलने को ब्लॉक कर सकता है। यदि कुछ लिंक न खुलें तो इस साइट के लिए पॉपअप की अनुमति दें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
