import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "ASCII Banner Generator", short: "Render text as 5-row ASCII block letters.", description: "Free ASCII banner generator. Type a word or short phrase to get a 5-row block-letter banner — choose between block (█), hash (#) or dot (·) characters.", keywords: ["ascii banner generator", "figlet text", "ascii art text", "block letters", "text banner"], input: "Text", style: "Style", block: "Block █", hash: "Hash #", dot: "Dot ·", output: "Banner" },
  pt: { title: "Gerador de ASCII Banner", short: "Render text as 5-row ASCII block letters.", description: "Gratuito - ASCII banner generator. Type a word ou short phrase para get a 5-row block-letter banner â choose entre block (â), hash (#) ou dot (Â·) characters.", keywords: ["ascii banner generator", "figlet text", "ascii art text", "block letters", "text banner"], input: "Text", style: "Style", block: "Block █", hash: "Hash #", dot: "Dot ·", output: "Banner" },
  id: { title: "Generator ASCII Banner", short: "Render text as 5-row ASCII block letters.", description: "Gratis - ASCII banner generator. Type a word atau short phrase to get a 5-row block-letter banner â choose antara block (â), hash (#) atau dot (Â·) characters.", keywords: ["ascii banner generator", "figlet text", "ascii art text", "block letters", "text banner"], input: "Text", style: "Style", block: "Block █", hash: "Hash #", dot: "Dot ·", output: "Banner" },

  tr: { title: "ASCII Banner Oluşturucu", short: "Metni 5 satırlı ASCII blok harfler olarak işleyin.", description: "Ücretsiz ASCII banner oluşturucu. Bir kelime veya kısa cümle yazın ve 5 satırlı blok harf banner alın — blok (█), kare (#) veya nokta (·) karakterleri arasında seçim yapın.", keywords: ["ascii banner oluşturucu", "figlet metin", "ascii sanat metin", "blok harfler", "metin banner"], input: "Metin", style: "Stil", block: "Blok █", hash: "Kare #", dot: "Nokta ·", output: "Banner" },
  de: { title: "ASCII-Banner-Generator", short: "Text als 5-Zeilen-ASCII-Blockbuchstaben rendern.", description: "Kostenloser ASCII-Banner-Generator. Geben Sie ein Wort oder eine kurze Phrase ein, um ein 5-Zeilen-Blockbuchstaben-Banner zu erhalten — wählen Sie zwischen Block (█), Raute (#) oder Punkt (·).", keywords: ["ascii banner generator", "figlet text", "ascii kunst text", "blockbuchstaben", "text banner"], input: "Text", style: "Stil", block: "Block █", hash: "Raute #", dot: "Punkt ·", output: "Banner" },
  fr: { title: "Générateur de Bannière ASCII", short: "Rendez du texte en lettres ASCII en blocs sur 5 lignes.", description: "Générateur de bannière ASCII gratuit. Tapez un mot ou une phrase courte pour obtenir une bannière de lettres en blocs sur 5 lignes — choisissez entre les caractères bloc (█), dièse (#) ou point (·).", keywords: ["générateur bannière ascii", "texte figlet", "art ascii texte", "lettres bloc", "bannière texte"], input: "Texte", style: "Style", block: "Bloc █", hash: "Dièse #", dot: "Point ·", output: "Bannière" },
  es: { title: "Generador de Banner ASCII", short: "Renderiza texto como letras ASCII en bloques de 5 filas.", description: "Generador de banner ASCII gratuito. Escribe una palabra o frase corta para obtener un banner de letras en bloques de 5 filas — elige entre caracteres bloque (█), almohadilla (#) o punto (·).", keywords: ["generador banner ascii", "texto figlet", "arte ascii texto", "letras bloque", "banner texto"], input: "Texto", style: "Estilo", block: "Bloque █", hash: "Almohadilla #", dot: "Punto ·", output: "Banner" },
  it: { title: "Generatore di Banner ASCII", short: "Renderizza testo come lettere ASCII a blocchi su 5 righe.", description: "Generatore di banner ASCII gratuito. Digita una parola o una frase breve per ottenere un banner di lettere a blocchi su 5 righe — scegli tra caratteri blocco (█), hash (#) o punto (·).", keywords: ["generatore banner ascii", "testo figlet", "arte ascii testo", "lettere blocco", "banner testo"], input: "Testo", style: "Stile", block: "Blocco █", hash: "Hash #", dot: "Punto ·", output: "Banner" },
  ar: { title: "مولّد لافتة ASCII", short: "حوّل النص إلى حروف ASCII كتلية من 5 صفوف.", description: "مولّد لافتة ASCII مجاني. اكتب كلمة أو عبارة قصيرة للحصول على لافتة حروف كتلية من 5 صفوف — اختر بين الكتلة (█) أو الهاش (#) أو النقطة (·).", keywords: ["مولد لافتة ascii", "نص figlet", "فن ascii النص", "حروف كتلية", "لافتة نص"], input: "النص", style: "النمط", block: "كتلة █", hash: "هاش #", dot: "نقطة ·", output: "اللافتة" },
  ru: { title: "Генератор ASCII-баннера", short: "Отображайте текст как 5-строчные ASCII-блочные буквы.", description: "Бесплатный генератор ASCII-баннера. Введите слово или короткую фразу, чтобы получить 5-строчный блочный буквенный баннер — выберите между символами блок (█), решётка (#) или точка (·).", keywords: ["генератор ascii баннера", "figlet текст", "ascii арт текст", "блочные буквы", "текстовый баннер"], input: "Текст", style: "Стиль", block: "Блок █", hash: "Решётка #", dot: "Точка ·", output: "Баннер" },
  zh: { title: "ASCII 横幅生成器", short: "将文本渲染为 5 行 ASCII 块字母。", description: "免费的 ASCII 横幅生成器。输入单词或短语，获得 5 行块字母横幅——在块（█）、井号（#）或点（·）字符之间选择。", keywords: ["ascii 横幅生成器", "figlet 文本", "ascii 艺术 文本", "块字母", "文本横幅"], input: "文本", style: "样式", block: "块 █", hash: "井号 #", dot: "点 ·", output: "横幅" },
  ja: { title: "ASCII バナー ジェネレーター", short: "テキストを 5 行の ASCII ブロック文字としてレンダリング。", description: "無料の ASCII バナー ジェネレーター。単語や短いフレーズを入力すると 5 行のブロック文字バナーが得られます——ブロック（█）、ハッシュ（#）、ドット（·）文字から選択。", keywords: ["ascii バナー ジェネレーター", "figlet テキスト", "ascii アート テキスト", "ブロック文字", "テキスト バナー"], input: "テキスト", style: "スタイル", block: "ブロック █", hash: "ハッシュ #", dot: "ドット ·", output: "バナー" },
  ko: { title: "ASCII 배너 생성기", short: "텍스트를 5줄 ASCII 블록 문자로 렌더링합니다.", description: "무료 ASCII 배너 생성기. 단어나 짧은 문구를 입력하면 5줄 블록 문자 배너를 얻습니다 — 블록(█), 해시(#), 점(·) 문자 중에서 선택하세요.", keywords: ["ascii 배너 생성기", "figlet 텍스트", "ascii 아트 텍스트", "블록 글자", "텍스트 배너"], input: "텍스트", style: "스타일", block: "블록 █", hash: "해시 #", dot: "점 ·", output: "배너" },
  hi: { title: "ASCII बैनर जनरेटर", short: "टेक्स्ट को 5-पंक्ति ASCII ब्लॉक अक्षरों के रूप में रेंडर करें।", description: "मुफ्त ASCII बैनर जनरेटर। एक शब्द या छोटा वाक्यांश टाइप करें और 5-पंक्ति ब्लॉक अक्षर बैनर पाएं — ब्लॉक (█), हैश (#) या डॉट (·) वर्णों में से चुनें।", keywords: ["ascii बैनर जनरेटर", "figlet टेक्स्ट", "ascii कला टेक्स्ट", "ब्लॉक अक्षर", "टेक्स्ट बैनर"], input: "टेक्स्ट", style: "शैली", block: "ब्लॉक █", hash: "हैश #", dot: "डॉट ·", output: "बैनर" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
