import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "RSA Key Pair Generator", short: "Generate an RSA public/private key pair in PEM format.", description: "Free RSA key pair generator. Create a 2048-, 3072- or 4096-bit RSA keypair in PEM (SPKI public, PKCS#8 private) for signing JWTs or other crypto — generated entirely in your browser via Web Crypto.", keywords: ["rsa key generator", "rsa keypair", "generate rsa pem", "rsa public private key", "rsa key generator online"], modulus: "Key size", generate: "Generate", publicKey: "Public key", privateKey: "Private key" },
  nl: { title: "RSA Key Pair Generator", short: "Genereer an RSA public/private key pair in PEM formatteer.", description: "Gratis RSA key pair generator. Maak aan a 2048-, 3072- or 4096-bit RSA keypair in PEM (SPKI public, PKCS#8 private) for signing JWTs or other crypto — genereerd entirely in uw browser via Web Crypto.", keywords: ["rsa key generator", "rsa keypair", "genereer rsa pem", "rsa public private key", "rsa key generator online"], modulus: "Key grootte", generate: "Genereer", publicKey: "Public key", privateKey: "Private key" },

  pl: { title: "RSA Key Pair Generator", short: "Generuj an RSA public/private key pair in PEM formatuj.", description: "Darmowy RSA key pair generator. Utwórz a 2048-, 3072- or 4096-bit RSA keypair in PEM (SPKI public, PKCS#8 private) for signing JWTs or other crypto — generujd entirely w Twojej przeglądarce via Web Crypto.", keywords: ["rsa key generator", "rsa keypair", "generuj rsa pem", "rsa public private key", "rsa key generator online"], modulus: "Key rozmiar", generate: "Generuj", publicKey: "Public key", privateKey: "Private key" },
  pt: { title: "Gerador de RSA Key Pair", short: "Gerar an RSA public/private key pair em PEM formatar.", description: "Gratuito - RSA key pair generator. Create a 2048-, 3072- ou 4096-bit RSA keypair em PEM (SPKI public, PKCS#8 private) para signing JWTs ou other crypto â generated entirely no seu navegador via Web Crypto.", keywords: ["rsa key generator", "rsa keypair", "generate rsa pem", "rsa public private key", "rsa key generator online"], modulus: "Key size", generate: "Generate", publicKey: "Public key", privateKey: "Private key" },
  id: { title: "Generator RSA Key Pair", short: "Hasilkan an RSA public/private key pair in PEM format.", description: "Gratis - RSA key pair generator. Create a 2048-, 3072- atau 4096-bit RSA keypair in PEM (SPKI public, PKCS#8 private) for signing JWTs atau other crypto â generated entirely di browser Anda via Web Crypto.", keywords: ["rsa key generator", "rsa keypair", "generate rsa pem", "rsa public private key", "rsa key generator online"], modulus: "Key size", generate: "Generate", publicKey: "Public key", privateKey: "Private key" },

  tr: { title: "RSA Anahtar Çifti Oluşturucu", short: "PEM formatında bir RSA açık/özel anahtar çifti oluşturun.", description: "Ücretsiz RSA anahtar çifti oluşturucu. JWT veya diğer kripto imzalama için 2048, 3072 veya 4096 bitlik bir RSA anahtar çiftini PEM (açık SPKI, özel PKCS#8) formatında oluşturun — tamamen tarayıcınızda Web Crypto ile üretilir.", keywords: ["rsa anahtar oluşturucu", "rsa anahtar çifti", "rsa pem oluştur", "rsa açık özel anahtar", "rsa anahtar oluşturucu online"], modulus: "Anahtar boyutu", generate: "Oluştur", publicKey: "Açık anahtar", privateKey: "Özel anahtar" },
  de: { title: "RSA-Schlüsselpaar-Generator", short: "Erzeugen Sie ein RSA-Schlüsselpaar im PEM-Format.", description: "Kostenloser RSA-Schlüsselpaar-Generator. Erstellen Sie ein 2048-, 3072- oder 4096-Bit-RSA-Keypair im PEM-Format (SPKI öffentlich, PKCS#8 privat) zum Signieren von JWTs oder anderer Krypto — vollständig im Browser mit Web Crypto erzeugt.", keywords: ["rsa schlüssel generator", "rsa schlüsselpaar", "rsa pem erzeugen", "rsa öffentlicher privater schlüssel", "rsa schlüssel generator online"], modulus: "Schlüsselgröße", generate: "Erzeugen", publicKey: "Öffentlicher Schlüssel", privateKey: "Privater Schlüssel" },
  fr: { title: "Générateur de Paire de Clés RSA", short: "Générez une paire de clés RSA publique/privée au format PEM.", description: "Générateur de paire de clés RSA gratuit. Créez un keypair RSA 2048, 3072 ou 4096 bits au format PEM (SPKI public, PKCS#8 privé) pour signer des JWT ou d'autres usages cryptographiques — entièrement généré dans votre navigateur via Web Crypto.", keywords: ["générateur clé rsa", "paire clés rsa", "générer rsa pem", "clé rsa publique privée", "générateur clé rsa en ligne"], modulus: "Taille de clé", generate: "Générer", publicKey: "Clé publique", privateKey: "Clé privée" },
  es: { title: "Generador de Par de Claves RSA", short: "Genera un par de claves RSA pública/privada en formato PEM.", description: "Generador de par de claves RSA gratuito. Crea un keypair RSA de 2048, 3072 o 4096 bits en PEM (SPKI público, PKCS#8 privado) para firmar JWTs u otras tareas criptográficas — generado completamente en tu navegador con Web Crypto.", keywords: ["generador clave rsa", "par claves rsa", "generar rsa pem", "clave rsa pública privada", "generador clave rsa online"], modulus: "Tamaño de clave", generate: "Generar", publicKey: "Clave pública", privateKey: "Clave privada" },
  it: { title: "Generatore di Coppia di Chiavi RSA", short: "Genera una coppia di chiavi RSA pubblica/privata in formato PEM.", description: "Generatore di coppia di chiavi RSA gratuito. Crea una keypair RSA da 2048, 3072 o 4096 bit in PEM (SPKI pubblica, PKCS#8 privata) per firmare JWT o altre crittografie — generato interamente nel browser tramite Web Crypto.", keywords: ["generatore chiave rsa", "coppia chiavi rsa", "generare rsa pem", "chiave rsa pubblica privata", "generatore chiave rsa online"], modulus: "Dimensione chiave", generate: "Genera", publicKey: "Chiave pubblica", privateKey: "Chiave privata" },
  ar: { title: "مولّد زوج مفاتيح RSA", short: "أنشئ زوج مفاتيح RSA عام/خاص بتنسيق PEM.", description: "مولّد زوج مفاتيح RSA مجاني. أنشئ زوج مفاتيح RSA بحجم 2048 أو 3072 أو 4096 بت بتنسيق PEM (SPKI عام، PKCS#8 خاص) لتوقيع JWT أو استخدامات تشفيرية أخرى — يتم التوليد بالكامل في متصفحك عبر Web Crypto.", keywords: ["مولد مفاتيح rsa", "زوج مفاتيح rsa", "إنشاء rsa pem", "مفاتيح rsa عامة خاصة", "مولد مفاتيح rsa عبر الإنترنت"], modulus: "حجم المفتاح", generate: "توليد", publicKey: "المفتاح العام", privateKey: "المفتاح الخاص" },
  ru: { title: "Генератор пары ключей RSA", short: "Создайте пару ключей RSA (публичный/приватный) в формате PEM.", description: "Бесплатный генератор пары ключей RSA. Создайте RSA-keypair 2048, 3072 или 4096 бит в PEM (SPKI публичный, PKCS#8 приватный) для подписи JWT или другой криптографии — полностью генерируется в браузере через Web Crypto.", keywords: ["генератор ключей rsa", "пара ключей rsa", "создать rsa pem", "rsa публичный приватный ключ", "генератор ключей rsa онлайн"], modulus: "Размер ключа", generate: "Создать", publicKey: "Публичный ключ", privateKey: "Приватный ключ" },
  zh: { title: "RSA 密钥对生成器", short: "生成 PEM 格式的 RSA 公钥/私钥对。", description: "免费的 RSA 密钥对生成器。生成 2048、3072 或 4096 位的 RSA 密钥对（公钥 SPKI、私钥 PKCS#8 PEM），可用于签署 JWT 或其他加密用途——通过 Web Crypto 完全在浏览器中生成。", keywords: ["rsa 密钥生成器", "rsa 密钥对", "生成 rsa pem", "rsa 公钥私钥", "在线 rsa 密钥生成器"], modulus: "密钥长度", generate: "生成", publicKey: "公钥", privateKey: "私钥" },
  ja: { title: "RSA 鍵ペア生成", short: "PEM 形式の RSA 公開/秘密鍵ペアを生成。", description: "無料の RSA 鍵ペア生成ツール。2048、3072、4096 ビットの RSA 鍵ペアを PEM（公開 SPKI、秘密 PKCS#8）形式で作成し、JWT の署名やその他の暗号用途に使えます——Web Crypto によりすべてブラウザ内で生成されます。", keywords: ["rsa 鍵 生成", "rsa 鍵ペア", "rsa pem 生成", "rsa 公開鍵 秘密鍵", "オンライン rsa 鍵 生成"], modulus: "鍵サイズ", generate: "生成", publicKey: "公開鍵", privateKey: "秘密鍵" },
  ko: { title: "RSA 키 쌍 생성기", short: "PEM 형식의 RSA 공개/개인 키 쌍을 생성합니다.", description: "무료 RSA 키 쌍 생성기. JWT 서명 또는 기타 암호화 작업을 위해 2048, 3072 또는 4096비트 RSA 키 쌍을 PEM(공개 SPKI, 개인 PKCS#8)으로 생성합니다 — Web Crypto를 통해 모두 브라우저에서.", keywords: ["rsa 키 생성기", "rsa 키 쌍", "rsa pem 생성", "rsa 공개 개인 키", "rsa 키 생성기 온라인"], modulus: "키 크기", generate: "생성", publicKey: "공개 키", privateKey: "개인 키" },
  hi: { title: "RSA की पेयर जनरेटर", short: "PEM प्रारूप में एक RSA सार्वजनिक/निजी की पेयर बनाएं।", description: "मुफ्त RSA की पेयर जनरेटर। JWT पर हस्ताक्षर करने या अन्य क्रिप्टो के लिए 2048, 3072 या 4096 बिट का RSA कीपेयर PEM (सार्वजनिक SPKI, निजी PKCS#8) में बनाएं — Web Crypto के माध्यम से पूरी तरह आपके ब्राउज़र में जनरेट।", keywords: ["rsa की जनरेटर", "rsa की पेयर", "rsa pem जनरेट करें", "rsa सार्वजनिक निजी की", "rsa की जनरेटर ऑनलाइन"], modulus: "की आकार", generate: "जनरेट करें", publicKey: "सार्वजनिक की", privateKey: "निजी की" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
