import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JSON Formatter & Validator", short: "Beautify, minify and validate JSON instantly.", description: "Free JSON formatter, validator and minifier. Paste JSON to pretty-print it with 2/4-space or tab indentation, minify it to one line, or catch syntax errors. Everything runs in your browser.", keywords: ["json formatter", "json beautifier", "json validator", "json minify", "pretty print json", "format json online"], placeholder: "Paste JSON here…", format: "Beautify", minify: "Minify", indent: "Indent", tab: "Tab", valid: "Valid JSON", spaces: "spaces" },
  pt: { title: "Validador de JSON Formatter &", short: "Beautify, minificar e validar JSON instantaneamente.", description: "Gratuito - JSON formatter, validator e minifier. Paste JSON para pretty-print it com 2/4-space ou tab indentation, minificar it para one line, ou catch syntax errors. Everything runs no seu navegador.", keywords: ["json formatter", "json beautifier", "json validator", "json minify", "pretty print json", "format json online"], placeholder: "Paste JSON here…", format: "Beautify", minify: "Minify", indent: "Indent", tab: "Tab", valid: "Valid JSON", spaces: "spaces" },
  id: { title: "Validator JSON Formatter &", short: "Beautify, perkecil dan validasi JSON secara instan.", description: "Gratis - JSON formatter, validator dan minifier. Paste JSON to pretty-print it with 2/4-space atau tab indentation, perkecil it to one line, atau catch syntax errors. Everything runs di browser Anda.", keywords: ["json formatter", "json beautifier", "json validator", "json minify", "pretty print json", "format json online"], placeholder: "Paste JSON here…", format: "Beautify", minify: "Minify", indent: "Indent", tab: "Tab", valid: "Valid JSON", spaces: "spaces" },

  tr: { title: "JSON Biçimlendirici ve Doğrulayıcı", short: "JSON'u anında güzelleştirin, küçültün ve doğrulayın.", description: "Ücretsiz JSON biçimlendirici, doğrulayıcı ve küçültücü. JSON yapıştırın; 2/4 boşluk veya sekme girintisiyle güzelce yazdırın, tek satıra küçültün veya sözdizimi hatalarını yakalayın. Her şey tarayıcınızda çalışır.", keywords: ["json biçimlendirici", "json güzelleştirici", "json doğrulayıcı", "json küçültme", "json formatla"], placeholder: "JSON'u buraya yapıştırın…", format: "Güzelleştir", minify: "Küçült", indent: "Girinti", tab: "Sekme", valid: "Geçerli JSON", spaces: "boşluk" },
  de: { title: "JSON-Formatter & Validator", short: "JSON sofort verschönern, minimieren und validieren.", description: "Kostenloser JSON-Formatter, -Validator und -Minifier. JSON einfügen, mit 2/4 Leerzeichen oder Tab einrücken, auf eine Zeile minimieren oder Syntaxfehler finden. Alles läuft im Browser.", keywords: ["json formatter", "json verschönern", "json validator", "json minify", "json formatieren"], placeholder: "JSON hier einfügen…", format: "Verschönern", minify: "Minimieren", indent: "Einrückung", tab: "Tab", valid: "Gültiges JSON", spaces: "Leerzeichen" },
  fr: { title: "Formateur & Validateur JSON", short: "Embellissez, minifiez et validez du JSON instantanément.", description: "Formateur, validateur et minifieur JSON gratuit. Collez du JSON pour l'indenter avec 2/4 espaces ou une tabulation, le minifier sur une ligne ou détecter les erreurs de syntaxe.", keywords: ["formateur json", "json beautifier", "validateur json", "minifier json", "formater json"], placeholder: "Collez le JSON ici…", format: "Embellir", minify: "Minifier", indent: "Indentation", tab: "Tabulation", valid: "JSON valide", spaces: "espaces" },
  es: { title: "Formateador y Validador JSON", short: "Embellece, minifica y valida JSON al instante.", description: "Formateador, validador y minificador JSON gratuito. Pega JSON para formatearlo con 2/4 espacios o tabulación, minificarlo en una línea o detectar errores de sintaxis.", keywords: ["formateador json", "embellecedor json", "validador json", "minificar json", "formatear json"], placeholder: "Pega el JSON aquí…", format: "Embellecer", minify: "Minificar", indent: "Sangría", tab: "Tabulación", valid: "JSON válido", spaces: "espacios" },
  it: { title: "Formattatore e Validatore JSON", short: "Abbellisci, minimizza e valida JSON all'istante.", description: "Formattatore, validatore e minificatore JSON gratuito. Incolla JSON per formattarlo con 2/4 spazi o tabulazione, minimizzarlo su una riga o individuare errori di sintassi.", keywords: ["formattatore json", "abbellitore json", "validatore json", "minify json", "formatta json"], placeholder: "Incolla il JSON qui…", format: "Abbellisci", minify: "Minimizza", indent: "Rientro", tab: "Tabulazione", valid: "JSON valido", spaces: "spazi" },
  ar: { title: "منسّق ومدقّق JSON", short: "نسّق وصغّر وتحقّق من JSON فورًا.", description: "منسّق ومدقّق ومصغّر JSON مجاني. الصق JSON لتنسيقه بمسافتين/أربع أو علامة جدولة، أو تصغيره في سطر واحد، أو اكتشاف أخطاء الصياغة. كل شيء يعمل في متصفحك.", keywords: ["منسق json", "تجميل json", "مدقق json", "تصغير json", "تنسيق json"], placeholder: "الصق JSON هنا…", format: "تجميل", minify: "تصغير", indent: "إزاحة", tab: "جدولة", valid: "JSON صالح", spaces: "مسافات" },
  ru: { title: "Форматтер и Валидатор JSON", short: "Мгновенно форматируйте, минифицируйте и проверяйте JSON.", description: "Бесплатный форматтер, валидатор и минификатор JSON. Вставьте JSON, чтобы отформатировать его с отступом в 2/4 пробела или табуляцию, сжать в одну строку или найти синтаксические ошибки.", keywords: ["форматтер json", "json beautifier", "валидатор json", "минификация json", "форматировать json"], placeholder: "Вставьте JSON сюда…", format: "Форматировать", minify: "Минифицировать", indent: "Отступ", tab: "Табуляция", valid: "Корректный JSON", spaces: "пробела" },
  zh: { title: "JSON 格式化与校验器", short: "即时美化、压缩和校验 JSON。", description: "免费的 JSON 格式化、校验和压缩工具。粘贴 JSON 即可使用 2/4 空格或制表符缩进进行美化、压缩为一行，或捕获语法错误。一切都在浏览器中运行。", keywords: ["json格式化", "json美化", "json校验", "json压缩", "格式化json"], placeholder: "在此粘贴 JSON…", format: "美化", minify: "压缩", indent: "缩进", tab: "制表符", valid: "有效的 JSON", spaces: "空格" },
  ja: { title: "JSON フォーマッター・バリデーター", short: "JSON を即座に整形・圧縮・検証します。", description: "無料の JSON フォーマッター・バリデーター・圧縮ツール。JSON を貼り付けて 2/4 スペースまたはタブで整形、1 行に圧縮、構文エラーの検出ができます。すべてブラウザ内で動作します。", keywords: ["json フォーマッター", "json 整形", "json バリデーター", "json 圧縮", "json 整形 オンライン"], placeholder: "ここに JSON を貼り付け…", format: "整形", minify: "圧縮", indent: "インデント", tab: "タブ", valid: "有効な JSON", spaces: "スペース" },
  ko: { title: "JSON 포맷터 및 검증기", short: "JSON을 즉시 정리, 압축, 검증합니다.", description: "무료 JSON 포맷터, 검증기 및 압축기. JSON을 붙여넣어 2/4칸 또는 탭 들여쓰기로 정리하거나 한 줄로 압축하고 구문 오류를 찾으세요. 모든 것이 브라우저에서 실행됩니다.", keywords: ["json 포맷터", "json 정리", "json 검증기", "json 압축", "json 포맷"], placeholder: "여기에 JSON 붙여넣기…", format: "정리", minify: "압축", indent: "들여쓰기", tab: "탭", valid: "유효한 JSON", spaces: "칸" },
  hi: { title: "JSON फॉर्मेटर और वैलिडेटर", short: "JSON को तुरंत सुंदर बनाएं, छोटा करें और सत्यापित करें।", description: "मुफ्त JSON फॉर्मेटर, वैलिडेटर और मिनिफायर। JSON पेस्ट करें और 2/4 स्पेस या टैब इंडेंट के साथ सुंदर बनाएं, एक पंक्ति में छोटा करें, या सिंटैक्स त्रुटियाँ पकड़ें। सब कुछ ब्राउज़र में चलता है।", keywords: ["json फॉर्मेटर", "json ब्यूटिफायर", "json वैलिडेटर", "json मिनिफाई", "json फॉर्मेट"], placeholder: "यहाँ JSON पेस्ट करें…", format: "सुंदर बनाएं", minify: "छोटा करें", indent: "इंडेंट", tab: "टैब", valid: "मान्य JSON", spaces: "स्पेस" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
