import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "DNS Lookup (DoH)", short: "Look up A, AAAA, MX, TXT and more via Cloudflare DoH.", description: "Free DNS lookup tool. Query A, AAAA, MX, TXT, CNAME, NS, SOA, CAA or PTR records through Cloudflare's public DNS-over-HTTPS — no separate backend, runs from your browser.", keywords: ["dns lookup", "doh lookup", "dns query online", "a record lookup", "mx record check"], hostname: "Hostname", type: "Record type", run: "Lookup", name: "Name", ttl: "TTL", data: "Data", status: "Status", noAnswers: "No records returned." },
  tr: { title: "DNS Sorgu (DoH)", short: "Cloudflare DoH üzerinden A, AAAA, MX, TXT ve daha fazlasını sorgulayın.", description: "Ücretsiz DNS sorgu aracı. Cloudflare'in genel DNS-over-HTTPS'i üzerinden A, AAAA, MX, TXT, CNAME, NS, SOA, CAA veya PTR kayıtlarını sorgulayın — ayrı bir backend yok, tarayıcınızdan çalışır.", keywords: ["dns sorgu", "doh sorgu", "online dns sorgu", "a kaydı sorgu", "mx kaydı kontrol"], hostname: "Ana bilgisayar adı", type: "Kayıt türü", run: "Sorgula", name: "Ad", ttl: "TTL", data: "Veri", status: "Durum", noAnswers: "Kayıt döndürülmedi." },
  de: { title: "DNS-Lookup (DoH)", short: "A, AAAA, MX, TXT und mehr über Cloudflare DoH abfragen.", description: "Kostenloses DNS-Lookup-Tool. Fragen Sie A-, AAAA-, MX-, TXT-, CNAME-, NS-, SOA-, CAA- oder PTR-Einträge über Cloudflares öffentliches DNS-over-HTTPS ab — kein separates Backend, läuft im Browser.", keywords: ["dns lookup", "doh lookup", "dns abfrage online", "a-record lookup", "mx-record check"], hostname: "Hostname", type: "Record-Typ", run: "Abfragen", name: "Name", ttl: "TTL", data: "Daten", status: "Status", noAnswers: "Keine Datensätze zurückgegeben." },
  fr: { title: "Lookup DNS (DoH)", short: "Recherchez A, AAAA, MX, TXT et plus via Cloudflare DoH.", description: "Outil DNS lookup gratuit. Interrogez les enregistrements A, AAAA, MX, TXT, CNAME, NS, SOA, CAA ou PTR via le DNS-over-HTTPS public de Cloudflare — pas de backend séparé, fonctionne dans votre navigateur.", keywords: ["dns lookup", "doh lookup", "requête dns en ligne", "lookup enregistrement a", "vérification mx"], hostname: "Nom d'hôte", type: "Type d'enregistrement", run: "Rechercher", name: "Nom", ttl: "TTL", data: "Données", status: "Statut", noAnswers: "Aucun enregistrement retourné." },
  es: { title: "DNS Lookup (DoH)", short: "Consulta A, AAAA, MX, TXT y más vía Cloudflare DoH.", description: "Herramienta DNS lookup gratuita. Consulta registros A, AAAA, MX, TXT, CNAME, NS, SOA, CAA o PTR a través del DNS-over-HTTPS público de Cloudflare — sin backend separado, funciona desde tu navegador.", keywords: ["dns lookup", "doh lookup", "consulta dns online", "lookup registro a", "verificación mx"], hostname: "Nombre de host", type: "Tipo de registro", run: "Consultar", name: "Nombre", ttl: "TTL", data: "Datos", status: "Estado", noAnswers: "No se devolvieron registros." },
  it: { title: "DNS Lookup (DoH)", short: "Cerca A, AAAA, MX, TXT e altro tramite Cloudflare DoH.", description: "Strumento DNS lookup gratuito. Interroga record A, AAAA, MX, TXT, CNAME, NS, SOA, CAA o PTR tramite il DNS-over-HTTPS pubblico di Cloudflare — nessun backend separato, funziona dal tuo browser.", keywords: ["dns lookup", "doh lookup", "query dns online", "lookup record a", "verifica mx"], hostname: "Nome host", type: "Tipo record", run: "Cerca", name: "Nome", ttl: "TTL", data: "Dati", status: "Stato", noAnswers: "Nessun record restituito." },
  ar: { title: "بحث DNS (DoH)", short: "ابحث في A و AAAA و MX و TXT والمزيد عبر Cloudflare DoH.", description: "أداة بحث DNS مجانية. استعلم عن سجلات A و AAAA و MX و TXT و CNAME و NS و SOA و CAA أو PTR عبر DNS-over-HTTPS العام لـ Cloudflare — لا backend منفصل، تعمل من متصفحك.", keywords: ["بحث dns", "بحث doh", "استعلام dns عبر الإنترنت", "بحث سجل a", "فحص سجل mx"], hostname: "اسم المضيف", type: "نوع السجل", run: "بحث", name: "الاسم", ttl: "TTL", data: "البيانات", status: "الحالة", noAnswers: "لم يتم إرجاع أي سجلات." },
  ru: { title: "DNS-запрос (DoH)", short: "Запросите A, AAAA, MX, TXT и др. через Cloudflare DoH.", description: "Бесплатный инструмент DNS-запроса. Запрашивайте записи A, AAAA, MX, TXT, CNAME, NS, SOA, CAA или PTR через публичный DNS-over-HTTPS Cloudflare — без отдельного бэкенда, работает из вашего браузера.", keywords: ["dns lookup", "doh запрос", "dns запрос онлайн", "поиск записи a", "проверка mx"], hostname: "Имя хоста", type: "Тип записи", run: "Запросить", name: "Имя", ttl: "TTL", data: "Данные", status: "Статус", noAnswers: "Записи не возвращены." },
  zh: { title: "DNS 查询（DoH）", short: "通过 Cloudflare DoH 查询 A、AAAA、MX、TXT 等记录。", description: "免费的 DNS 查询工具。通过 Cloudflare 的公共 DNS-over-HTTPS 查询 A、AAAA、MX、TXT、CNAME、NS、SOA、CAA 或 PTR 记录——无需单独后端，从你的浏览器运行。", keywords: ["dns 查询", "doh 查询", "在线 dns 查询", "a 记录查询", "mx 记录检查"], hostname: "主机名", type: "记录类型", run: "查询", name: "名称", ttl: "TTL", data: "数据", status: "状态", noAnswers: "未返回记录。" },
  ja: { title: "DNS 検索（DoH）", short: "Cloudflare DoH 経由で A、AAAA、MX、TXT などを検索。", description: "無料の DNS 検索ツール。Cloudflare の公開 DNS-over-HTTPS を介して A、AAAA、MX、TXT、CNAME、NS、SOA、CAA、PTR レコードを問い合わせ——別途バックエンドなしでブラウザから実行できます。", keywords: ["dns 検索", "doh 検索", "オンライン dns 問い合わせ", "a レコード 検索", "mx レコード チェック"], hostname: "ホスト名", type: "レコードタイプ", run: "検索", name: "名前", ttl: "TTL", data: "データ", status: "ステータス", noAnswers: "レコードは返されませんでした。" },
  ko: { title: "DNS 조회 (DoH)", short: "Cloudflare DoH로 A, AAAA, MX, TXT 등 조회.", description: "무료 DNS 조회 도구. Cloudflare의 공개 DNS-over-HTTPS를 통해 A, AAAA, MX, TXT, CNAME, NS, SOA, CAA 또는 PTR 레코드를 쿼리하세요 — 별도 백엔드 없이 브라우저에서 실행됩니다.", keywords: ["dns 조회", "doh 조회", "온라인 dns 쿼리", "a 레코드 조회", "mx 레코드 확인"], hostname: "호스트 이름", type: "레코드 유형", run: "조회", name: "이름", ttl: "TTL", data: "데이터", status: "상태", noAnswers: "반환된 레코드가 없습니다." },
  hi: { title: "DNS Lookup (DoH)", short: "Cloudflare DoH के माध्यम से A, AAAA, MX, TXT आदि देखें।", description: "मुफ्त DNS lookup टूल। Cloudflare के सार्वजनिक DNS-over-HTTPS के माध्यम से A, AAAA, MX, TXT, CNAME, NS, SOA, CAA या PTR रिकॉर्ड क्वेरी करें — कोई अलग बैकएंड नहीं, आपके ब्राउज़र से चलता है।", keywords: ["dns lookup", "doh lookup", "ऑनलाइन dns क्वेरी", "a रिकॉर्ड lookup", "mx रिकॉर्ड जाँच"], hostname: "होस्टनेम", type: "रिकॉर्ड प्रकार", run: "खोजें", name: "नाम", ttl: "TTL", data: "डेटा", status: "स्थिति", noAnswers: "कोई रिकॉर्ड नहीं लौटा।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
