import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "URL Parser", short: "Break a URL into its parts and list its query parameters.", description: "Free URL parser. Paste a URL to see its protocol, host, port, path, query string and fragment, plus a table of all query parameters. Runs in your browser.", keywords: ["url parser", "parse url", "query string parser", "url components", "query parameters"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "Protocol", host: "Host", port: "Port", path: "Path", query: "Query string", hash: "Fragment", params: "Query parameters", key: "Key", value: "Value", invalid: "Enter a valid absolute URL." },
  pt: { title: "URL Parser", short: "Break a URL into its parts and list its query parameters.", description: "Free URL parser. Paste a URL to see its protocol, host, port, path, query string and fragment, plus a table of all query parameters. Runs in your browser.", keywords: ["url parser", "parse url", "query string parser", "url components", "query parameters"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "Protocol", host: "Host", port: "Port", path: "Path", query: "Query string", hash: "Fragment", params: "Query parameters", key: "Key", value: "Value", invalid: "Enter a valid absolute URL." },
  id: { title: "URL Parser", short: "Break a URL into its parts and list its query parameters.", description: "Free URL parser. Paste a URL to see its protocol, host, port, path, query string and fragment, plus a table of all query parameters. Runs in your browser.", keywords: ["url parser", "parse url", "query string parser", "url components", "query parameters"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "Protocol", host: "Host", port: "Port", path: "Path", query: "Query string", hash: "Fragment", params: "Query parameters", key: "Key", value: "Value", invalid: "Enter a valid absolute URL." },

  tr: { title: "URL Ayrıştırıcı", short: "Bir URL'yi parçalarına ayırın ve sorgu parametrelerini listeleyin.", description: "Ücretsiz URL ayrıştırıcı. Bir URL yapıştırın; protokol, ana bilgisayar, port, yol, sorgu dizesi ve parçayı, ayrıca tüm sorgu parametrelerinin tablosunu görün. Tarayıcınızda çalışır.", keywords: ["url ayrıştırıcı", "url parçala", "sorgu dizesi ayrıştırıcı", "url bileşenleri", "sorgu parametreleri"], placeholder: "https://example.com:8080/yol?x=1&y=2#bolum", protocol: "Protokol", host: "Ana bilgisayar", port: "Port", path: "Yol", query: "Sorgu dizesi", hash: "Parça", params: "Sorgu parametreleri", key: "Anahtar", value: "Değer", invalid: "Geçerli bir mutlak URL girin." },
  de: { title: "URL-Parser", short: "Zerlegen Sie eine URL in ihre Teile und listen Sie die Query-Parameter auf.", description: "Kostenloser URL-Parser. Fügen Sie eine URL ein, um Protokoll, Host, Port, Pfad, Query-String und Fragment sowie eine Tabelle aller Query-Parameter zu sehen. Läuft im Browser.", keywords: ["url parser", "url zerlegen", "query string parser", "url komponenten", "query parameter"], placeholder: "https://example.com:8080/pfad?x=1&y=2#abschnitt", protocol: "Protokoll", host: "Host", port: "Port", path: "Pfad", query: "Query-String", hash: "Fragment", params: "Query-Parameter", key: "Schlüssel", value: "Wert", invalid: "Geben Sie eine gültige absolute URL ein." },
  fr: { title: "Analyseur d'URL", short: "Décomposez une URL en ses parties et listez ses paramètres de requête.", description: "Analyseur d'URL gratuit. Collez une URL pour voir son protocole, hôte, port, chemin, chaîne de requête et fragment, ainsi qu'un tableau de tous les paramètres de requête.", keywords: ["analyseur d'url", "décomposer url", "analyseur de chaîne de requête", "composants url", "paramètres de requête"], placeholder: "https://example.com:8080/chemin?x=1&y=2#section", protocol: "Protocole", host: "Hôte", port: "Port", path: "Chemin", query: "Chaîne de requête", hash: "Fragment", params: "Paramètres de requête", key: "Clé", value: "Valeur", invalid: "Saisissez une URL absolue valide." },
  es: { title: "Analizador de URL", short: "Descompón una URL en sus partes y lista sus parámetros de consulta.", description: "Analizador de URL gratuito. Pega una URL para ver su protocolo, host, puerto, ruta, cadena de consulta y fragmento, además de una tabla con todos los parámetros de consulta.", keywords: ["analizador de url", "descomponer url", "analizador de query string", "componentes url", "parámetros de consulta"], placeholder: "https://example.com:8080/ruta?x=1&y=2#seccion", protocol: "Protocolo", host: "Host", port: "Puerto", path: "Ruta", query: "Cadena de consulta", hash: "Fragmento", params: "Parámetros de consulta", key: "Clave", value: "Valor", invalid: "Introduce una URL absoluta válida." },
  it: { title: "Analizzatore di URL", short: "Scomponi un URL nelle sue parti ed elenca i parametri di query.", description: "Analizzatore di URL gratuito. Incolla un URL per vederne protocollo, host, porta, percorso, query string e frammento, oltre a una tabella di tutti i parametri di query.", keywords: ["analizzatore url", "scomponi url", "analizzatore query string", "componenti url", "parametri di query"], placeholder: "https://example.com:8080/percorso?x=1&y=2#sezione", protocol: "Protocollo", host: "Host", port: "Porta", path: "Percorso", query: "Query string", hash: "Frammento", params: "Parametri di query", key: "Chiave", value: "Valore", invalid: "Inserisci un URL assoluto valido." },
  ar: { title: "محلّل عناوين URL", short: "قسّم عنوان URL إلى أجزائه واعرض معلمات الاستعلام.", description: "محلّل URL مجاني. الصق عنوان URL لرؤية البروتوكول والمضيف والمنفذ والمسار وسلسلة الاستعلام والجزء، بالإضافة إلى جدول بكل معلمات الاستعلام. يعمل في متصفحك.", keywords: ["محلل url", "تحليل url", "محلل سلسلة الاستعلام", "مكونات url", "معلمات الاستعلام"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "البروتوكول", host: "المضيف", port: "المنفذ", path: "المسار", query: "سلسلة الاستعلام", hash: "الجزء", params: "معلمات الاستعلام", key: "المفتاح", value: "القيمة", invalid: "أدخل عنوان URL مطلقًا صالحًا." },
  ru: { title: "Парсер URL", short: "Разберите URL на части и перечислите его параметры запроса.", description: "Бесплатный парсер URL. Вставьте URL, чтобы увидеть протокол, хост, порт, путь, строку запроса и фрагмент, а также таблицу всех параметров запроса. Работает в браузере.", keywords: ["парсер url", "разбор url", "парсер строки запроса", "компоненты url", "параметры запроса"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "Протокол", host: "Хост", port: "Порт", path: "Путь", query: "Строка запроса", hash: "Фрагмент", params: "Параметры запроса", key: "Ключ", value: "Значение", invalid: "Введите корректный абсолютный URL." },
  zh: { title: "URL 解析器", short: "将 URL 分解为各部分并列出其查询参数。", description: "免费的 URL 解析器。粘贴 URL，即可查看其协议、主机、端口、路径、查询字符串和片段，以及所有查询参数的表格。在浏览器中运行。", keywords: ["url解析器", "解析url", "查询字符串解析", "url组成部分", "查询参数"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "协议", host: "主机", port: "端口", path: "路径", query: "查询字符串", hash: "片段", params: "查询参数", key: "键", value: "值", invalid: "请输入有效的绝对 URL。" },
  ja: { title: "URL パーサー", short: "URL を各部分に分解し、クエリパラメータを一覧表示します。", description: "無料の URL パーサー。URL を貼り付けると、プロトコル・ホスト・ポート・パス・クエリ文字列・フラグメント、およびすべてのクエリパラメータの表が表示されます。ブラウザ内で動作します。", keywords: ["url パーサー", "url 解析", "クエリ文字列 パーサー", "url 構成要素", "クエリパラメータ"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "プロトコル", host: "ホスト", port: "ポート", path: "パス", query: "クエリ文字列", hash: "フラグメント", params: "クエリパラメータ", key: "キー", value: "値", invalid: "有効な絶対 URL を入力してください。" },
  ko: { title: "URL 파서", short: "URL을 각 부분으로 분해하고 쿼리 매개변수를 나열합니다.", description: "무료 URL 파서. URL을 붙여넣으면 프로토콜, 호스트, 포트, 경로, 쿼리 문자열, 프래그먼트와 모든 쿼리 매개변수 표를 볼 수 있습니다. 브라우저에서 실행됩니다.", keywords: ["url 파서", "url 분석", "쿼리 문자열 파서", "url 구성요소", "쿼리 매개변수"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "프로토콜", host: "호스트", port: "포트", path: "경로", query: "쿼리 문자열", hash: "프래그먼트", params: "쿼리 매개변수", key: "키", value: "값", invalid: "유효한 절대 URL을 입력하세요." },
  hi: { title: "URL पार्सर", short: "एक URL को उसके भागों में तोड़ें और उसके क्वेरी पैरामीटर सूचीबद्ध करें।", description: "मुफ्त URL पार्सर। एक URL पेस्ट करें और उसका प्रोटोकॉल, होस्ट, पोर्ट, पथ, क्वेरी स्ट्रिंग और फ्रैगमेंट, साथ ही सभी क्वेरी पैरामीटर की तालिका देखें। ब्राउज़र में चलता है।", keywords: ["url पार्सर", "url पार्स करें", "क्वेरी स्ट्रिंग पार्सर", "url घटक", "क्वेरी पैरामीटर"], placeholder: "https://example.com:8080/path?x=1&y=2#section", protocol: "प्रोटोकॉल", host: "होस्ट", port: "पोर्ट", path: "पथ", query: "क्वेरी स्ट्रिंग", hash: "फ्रैगमेंट", params: "क्वेरी पैरामीटर", key: "कुंजी", value: "मान", invalid: "एक मान्य निरपेक्ष URL दर्ज करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
