import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Slugify — URL Slug Generator", short: "Turn any title or text into a clean, URL-safe slug.", description: "Free slug generator. Convert any title or text into a clean, lowercase, URL-safe slug — diacritics removed, spaces and punctuation replaced with a hyphen or underscore. Great for permalinks and SEO.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug", "text to slug"], placeholder: "Enter a title or text…", separator: "Separator", hyphen: "Hyphen (-)", underscore: "Underscore (_)", lowercase: "Lowercase" },
  nl: { title: "Slugify — URL Slug Generator", short: "Turn any title or tekst into a clean, URL-safe slug.", description: "Gratis slug generator. Converteer any title or tekst into a clean, lowercase, URL-safe slug — diacritics verwijderd, spaces and punctuation replaced with a hyphen or underscore. Great for permalinks and SEO.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug", "tekst to slug"], placeholder: "Enter a title or tekst…", separator: "Separator", hyphen: "Hyphen (-)", underscore: "Underscore (_)", lowercase: "Lowercase" },

  pl: { title: "Slugify — URL Slug Generator", short: "Turn any title or tekst into a clean, URL-safe slug.", description: "Darmowy slug generator. Konwertuj any title or tekst into a clean, lowercase, URL-safe slug — diacritics usuńd, spaces and punctuation replaced with a hyphen or underscore. Great for permalinks and SEO.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug", "tekst to slug"], placeholder: "Enter a title or tekst…", separator: "Separator", hyphen: "Hyphen (-)", underscore: "Underscore (_)", lowercase: "Lowercase" },
  pt: { title: "Gerador de Slugify â URL Slug", short: "Turn any title ou text into a clean, URL-safe slug.", description: "Gratuito - slug generator. Converter any title ou text into a clean, lowercase, URL-safe slug â diacritics removed, spaces e punctuation replaced com a hyphen ou underscore. Great para permalinks e SEO.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug", "text to slug"], placeholder: "Enter a title or text…", separator: "Separator", hyphen: "Hyphen (-)", underscore: "Underscore (_)", lowercase: "Lowercase" },
  id: { title: "Generator Slugify â URL Slug", short: "Turn any title atau text into a clean, URL-safe slug.", description: "Gratis - slug generator. Konversi any title atau text into a clean, lowercase, URL-safe slug â diacritics removed, spaces dan punctuation replaced with a hyphen atau underscore. Great for permalinks dan SEO.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug", "text to slug"], placeholder: "Enter a title or text…", separator: "Separator", hyphen: "Hyphen (-)", underscore: "Underscore (_)", lowercase: "Lowercase" },

  tr: { title: "Slugify — URL Slug Oluşturucu", short: "Herhangi bir başlığı veya metni temiz, URL-güvenli bir slug'a çevirin.", description: "Ücretsiz slug oluşturucu. Herhangi bir başlığı veya metni temiz, küçük harfli, URL-güvenli bir slug'a çevirin — aksanlar kaldırılır, boşluk ve noktalama tire veya alt çizgiyle değiştirilir. Kalıcı bağlantılar ve SEO için idealdir.", keywords: ["slugify", "url slug oluşturucu", "slug", "kalıcı bağlantı", "seo slug", "metinden slug"], placeholder: "Bir başlık veya metin girin…", separator: "Ayırıcı", hyphen: "Tire (-)", underscore: "Alt çizgi (_)", lowercase: "Küçük harf" },
  de: { title: "Slugify — URL-Slug-Generator", short: "Verwandeln Sie jeden Titel oder Text in einen sauberen, URL-sicheren Slug.", description: "Kostenloser Slug-Generator. Wandeln Sie Titel oder Text in einen sauberen, kleingeschriebenen, URL-sicheren Slug um — Diakritika entfernt, Leerzeichen und Satzzeichen durch Bindestrich oder Unterstrich ersetzt.", keywords: ["slugify", "url slug generator", "slug", "permalink", "seo slug"], placeholder: "Titel oder Text eingeben…", separator: "Trennzeichen", hyphen: "Bindestrich (-)", underscore: "Unterstrich (_)", lowercase: "Kleinschreibung" },
  fr: { title: "Slugify — Générateur de Slug d'URL", short: "Transformez n'importe quel titre ou texte en slug propre et compatible URL.", description: "Générateur de slug gratuit. Convertissez tout titre ou texte en slug propre, en minuscules et compatible URL — accents supprimés, espaces et ponctuation remplacés par un tiret ou un trait de soulignement.", keywords: ["slugify", "générateur de slug", "slug", "permalien", "slug seo"], placeholder: "Saisissez un titre ou un texte…", separator: "Séparateur", hyphen: "Tiret (-)", underscore: "Trait de soulignement (_)", lowercase: "Minuscules" },
  es: { title: "Slugify — Generador de Slug de URL", short: "Convierte cualquier título o texto en un slug limpio y apto para URL.", description: "Generador de slug gratuito. Convierte cualquier título o texto en un slug limpio, en minúsculas y apto para URL — sin acentos, con espacios y puntuación reemplazados por guion o guion bajo.", keywords: ["slugify", "generador de slug", "slug", "enlace permanente", "slug seo"], placeholder: "Introduce un título o texto…", separator: "Separador", hyphen: "Guion (-)", underscore: "Guion bajo (_)", lowercase: "Minúsculas" },
  it: { title: "Slugify — Generatore di Slug URL", short: "Trasforma qualsiasi titolo o testo in uno slug pulito e adatto agli URL.", description: "Generatore di slug gratuito. Converti qualsiasi titolo o testo in uno slug pulito, in minuscolo e adatto agli URL — diacritici rimossi, spazi e punteggiatura sostituiti da trattino o trattino basso.", keywords: ["slugify", "generatore di slug", "slug", "permalink", "slug seo"], placeholder: "Inserisci un titolo o un testo…", separator: "Separatore", hyphen: "Trattino (-)", underscore: "Trattino basso (_)", lowercase: "Minuscolo" },
  ar: { title: "Slugify — مولّد روابط نصية (Slug)", short: "حوّل أي عنوان أو نص إلى slug نظيف وآمن للروابط.", description: "مولّد slug مجاني. حوّل أي عنوان أو نص إلى slug نظيف بأحرف صغيرة وآمن للروابط — تُزال الحركات وتُستبدل المسافات وعلامات الترقيم بشرطة أو شرطة سفلية.", keywords: ["slugify", "مولد slug", "slug", "رابط دائم", "slug seo"], placeholder: "أدخل عنوانًا أو نصًا…", separator: "الفاصل", hyphen: "شرطة (-)", underscore: "شرطة سفلية (_)", lowercase: "أحرف صغيرة" },
  ru: { title: "Slugify — Генератор URL-слагов", short: "Превратите любой заголовок или текст в чистый URL-совместимый слаг.", description: "Бесплатный генератор слагов. Преобразуйте любой заголовок или текст в чистый слаг в нижнем регистре, безопасный для URL — диакритика убрана, пробелы и пунктуация заменены дефисом или подчёркиванием.", keywords: ["slugify", "генератор слагов", "слаг", "постоянная ссылка", "seo слаг"], placeholder: "Введите заголовок или текст…", separator: "Разделитель", hyphen: "Дефис (-)", underscore: "Подчёркивание (_)", lowercase: "Нижний регистр" },
  zh: { title: "Slugify — URL 别名生成器", short: "将任意标题或文本转换为干净、URL 安全的 slug。", description: "免费的 slug 生成器。将任意标题或文本转换为干净、小写、URL 安全的 slug — 去除变音符号，空格和标点替换为连字符或下划线。适合永久链接和 SEO。", keywords: ["slugify", "url别名生成器", "slug", "永久链接", "seo slug"], placeholder: "输入标题或文本…", separator: "分隔符", hyphen: "连字符 (-)", underscore: "下划线 (_)", lowercase: "小写" },
  ja: { title: "Slugify — URL スラッグ生成", short: "タイトルやテキストをクリーンで URL セーフなスラッグに変換します。", description: "無料のスラッグ生成ツール。任意のタイトルやテキストを、クリーンで小文字、URL セーフなスラッグに変換します — 発音記号を除去し、空白と句読点をハイフンまたはアンダースコアに置換。", keywords: ["slugify", "url スラッグ生成", "スラッグ", "パーマリンク", "seo スラッグ"], placeholder: "タイトルまたはテキストを入力…", separator: "区切り文字", hyphen: "ハイフン (-)", underscore: "アンダースコア (_)", lowercase: "小文字" },
  ko: { title: "Slugify — URL 슬러그 생성기", short: "제목이나 텍스트를 깔끔하고 URL에 안전한 슬러그로 변환합니다.", description: "무료 슬러그 생성기. 제목이나 텍스트를 깔끔하고 소문자이며 URL에 안전한 슬러그로 변환합니다 — 발음 구별 기호 제거, 공백과 문장 부호를 하이픈 또는 밑줄로 대체.", keywords: ["slugify", "url 슬러그 생성기", "슬러그", "퍼머링크", "seo 슬러그"], placeholder: "제목 또는 텍스트 입력…", separator: "구분자", hyphen: "하이픈 (-)", underscore: "밑줄 (_)", lowercase: "소문자" },
  hi: { title: "Slugify — URL स्लग जनरेटर", short: "किसी भी शीर्षक या टेक्स्ट को साफ, URL-सुरक्षित स्लग में बदलें।", description: "मुफ्त स्लग जनरेटर। किसी भी शीर्षक या टेक्स्ट को साफ, लोअरकेस, URL-सुरक्षित स्लग में बदलें — डायक्रिटिक्स हटाए जाते हैं, स्पेस और विराम चिह्न हाइफन या अंडरस्कोर से बदले जाते हैं।", keywords: ["slugify", "url स्लग जनरेटर", "स्लग", "पर्मालिंक", "seo स्लग"], placeholder: "शीर्षक या टेक्स्ट दर्ज करें…", separator: "विभाजक", hyphen: "हाइफन (-)", underscore: "अंडरस्कोर (_)", lowercase: "लोअरकेस" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
