import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Number Base Converter", short: "Convert numbers between binary, octal, decimal and hexadecimal.", description: "Free number base converter. Enter a value and its base to instantly see it in binary, octal, decimal and hexadecimal. Supports base 2, 8, 10 and 16. Runs in your browser.", keywords: ["number base converter", "binary to decimal", "hex to decimal", "decimal to binary", "base converter", "radix converter"], fromBase: "Input base", binary: "Binary", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Enter a number…", invalid: "Invalid number for the selected base." },
  nl: { title: "Nummer Base Converteerer", short: "Converteer nummers between binair, octal, decimal and hexadecimal.", description: "Gratis nummer base converteerer. Enter a value and its base to direct see it in binair, octal, decimal and hexadecimal. Supports base 2, 8, 10 and 16. Runs in uw browser.", keywords: ["nummer base converteerer", "binair to decimal", "hex to decimal", "decimal to binair", "base converteerer", "radix converteerer"], fromBase: "Input base", binary: "Binair", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Enter a nummer…", invalid: "Invalid nummer for the selected base." },

  pl: { title: "Liczba Base Konwerter", short: "Konwertuj liczbas between binarny, octal, decimal and hexadecimal.", description: "Darmowy liczba base konwerter. Enter a value and its base to natychmiast see it in binarny, octal, decimal and hexadecimal. Supports base 2, 8, 10 and 16. Runs w Twojej przeglądarce.", keywords: ["liczba base konwerter", "binarny to decimal", "hex to decimal", "decimal to binarny", "base konwerter", "radix konwerter"], fromBase: "Input base", binary: "Binarny", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Enter a liczba…", invalid: "Invalid liczba for the selected base." },
  pt: { title: "Conversor de Number Base", short: "Converter numbers entre binary, octal, decimal e hexadecimal.", description: "Gratuito - number base converter. Enter a value e its base para instantaneamente see it em binary, octal, decimal e hexadecimal. Supports base 2, 8, 10 e 16. Runs no seu navegador.", keywords: ["number base converter", "binary to decimal", "hex to decimal", "decimal to binary", "base converter", "radix converter"], fromBase: "Input base", binary: "Binary", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Enter a number…", invalid: "Invalid number for the selected base." },
  id: { title: "Konverter Number Base", short: "Konversi numbers antara binary, octal, decimal dan hexadecimal.", description: "Gratis - number base converter. Enter a value dan its base to secara instan see it in binary, octal, decimal dan hexadecimal. Supports base 2, 8, 10 dan 16. Runs di browser Anda.", keywords: ["number base converter", "binary to decimal", "hex to decimal", "decimal to binary", "base converter", "radix converter"], fromBase: "Input base", binary: "Binary", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Enter a number…", invalid: "Invalid number for the selected base." },

  tr: { title: "Sayı Tabanı Dönüştürücü", short: "Sayıları ikili, sekizli, onlu ve onaltılı arasında dönüştürün.", description: "Ücretsiz sayı tabanı dönüştürücü. Bir değer ve tabanını girin; ikili, sekizli, onlu ve onaltılı olarak anında görün. Taban 2, 8, 10 ve 16 desteklenir. Tarayıcınızda çalışır.", keywords: ["sayı tabanı dönüştürücü", "ikiliden onluya", "onaltılıdan onluya", "onludan ikiliye", "taban dönüştürücü"], fromBase: "Giriş tabanı", binary: "İkili", octal: "Sekizli", decimal: "Onlu", hex: "Onaltılı", placeholder: "Bir sayı girin…", invalid: "Seçilen taban için geçersiz sayı." },
  de: { title: "Zahlensystem-Konverter", short: "Zahlen zwischen Binär, Oktal, Dezimal und Hexadezimal umwandeln.", description: "Kostenloser Zahlensystem-Konverter. Geben Sie einen Wert und seine Basis ein, um ihn sofort in Binär, Oktal, Dezimal und Hexadezimal zu sehen. Unterstützt Basis 2, 8, 10 und 16.", keywords: ["zahlensystem konverter", "binär zu dezimal", "hex zu dezimal", "dezimal zu binär", "basis konverter"], fromBase: "Eingabebasis", binary: "Binär", octal: "Oktal", decimal: "Dezimal", hex: "Hexadezimal", placeholder: "Zahl eingeben…", invalid: "Ungültige Zahl für die gewählte Basis." },
  fr: { title: "Convertisseur de Base Numérique", short: "Convertissez des nombres entre binaire, octal, décimal et hexadécimal.", description: "Convertisseur de base numérique gratuit. Saisissez une valeur et sa base pour la voir instantanément en binaire, octal, décimal et hexadécimal. Prend en charge les bases 2, 8, 10 et 16.", keywords: ["convertisseur de base", "binaire en décimal", "hex en décimal", "décimal en binaire", "convertisseur de radix"], fromBase: "Base d'entrée", binary: "Binaire", octal: "Octal", decimal: "Décimal", hex: "Hexadécimal", placeholder: "Saisissez un nombre…", invalid: "Nombre invalide pour la base sélectionnée." },
  es: { title: "Conversor de Base Numérica", short: "Convierte números entre binario, octal, decimal y hexadecimal.", description: "Conversor de base numérica gratuito. Introduce un valor y su base para verlo al instante en binario, octal, decimal y hexadecimal. Admite base 2, 8, 10 y 16. Se ejecuta en tu navegador.", keywords: ["conversor de base", "binario a decimal", "hex a decimal", "decimal a binario", "conversor de radix"], fromBase: "Base de entrada", binary: "Binario", octal: "Octal", decimal: "Decimal", hex: "Hexadecimal", placeholder: "Introduce un número…", invalid: "Número no válido para la base seleccionada." },
  it: { title: "Convertitore di Base Numerica", short: "Converti numeri tra binario, ottale, decimale ed esadecimale.", description: "Convertitore di base numerica gratuito. Inserisci un valore e la sua base per vederlo all'istante in binario, ottale, decimale ed esadecimale. Supporta base 2, 8, 10 e 16.", keywords: ["convertitore di base", "binario in decimale", "hex in decimale", "decimale in binario", "convertitore radix"], fromBase: "Base di input", binary: "Binario", octal: "Ottale", decimal: "Decimale", hex: "Esadecimale", placeholder: "Inserisci un numero…", invalid: "Numero non valido per la base selezionata." },
  ar: { title: "محوّل أساس الأرقام", short: "حوّل الأرقام بين الثنائي والثماني والعشري والسداسي عشري.", description: "محوّل أساس أرقام مجاني. أدخل قيمة وأساسها لرؤيتها فورًا بالثنائي والثماني والعشري والسداسي عشري. يدعم الأساس 2 و8 و10 و16. يعمل في متصفحك.", keywords: ["محول أساس الأرقام", "ثنائي إلى عشري", "سداسي إلى عشري", "عشري إلى ثنائي", "محول الأساس"], fromBase: "أساس الإدخال", binary: "ثنائي", octal: "ثماني", decimal: "عشري", hex: "سداسي عشري", placeholder: "أدخل رقمًا…", invalid: "رقم غير صالح للأساس المحدد." },
  ru: { title: "Конвертер Систем Счисления", short: "Преобразуйте числа между двоичной, восьмеричной, десятичной и шестнадцатеричной.", description: "Бесплатный конвертер систем счисления. Введите значение и его основание, чтобы сразу увидеть его в двоичной, восьмеричной, десятичной и шестнадцатеричной системах. Поддерживает основания 2, 8, 10 и 16.", keywords: ["конвертер систем счисления", "двоичное в десятичное", "hex в десятичное", "десятичное в двоичное", "конвертер основания"], fromBase: "Основание ввода", binary: "Двоичная", octal: "Восьмеричная", decimal: "Десятичная", hex: "Шестнадцатеричная", placeholder: "Введите число…", invalid: "Недопустимое число для выбранного основания." },
  zh: { title: "数字进制转换器", short: "在二进制、八进制、十进制和十六进制之间转换数字。", description: "免费的数字进制转换器。输入数值及其进制，即可立即看到二进制、八进制、十进制和十六进制表示。支持 2、8、10 和 16 进制。在浏览器中运行。", keywords: ["进制转换器", "二进制转十进制", "十六进制转十进制", "十进制转二进制", "基数转换"], fromBase: "输入进制", binary: "二进制", octal: "八进制", decimal: "十进制", hex: "十六进制", placeholder: "输入一个数字…", invalid: "对于所选进制无效的数字。" },
  ja: { title: "基数変換ツール", short: "数値を2進・8進・10進・16進の間で変換します。", description: "無料の基数変換ツール。値とその基数を入力すると、2進・8進・10進・16進で即座に表示されます。基数 2・8・10・16 に対応。ブラウザ内で動作します。", keywords: ["基数変換", "2進数から10進数", "16進数から10進数", "10進数から2進数", "基数コンバーター"], fromBase: "入力の基数", binary: "2進数", octal: "8進数", decimal: "10進数", hex: "16進数", placeholder: "数値を入力…", invalid: "選択した基数に対して無効な数値です。" },
  ko: { title: "진법 변환기", short: "숫자를 2진법, 8진법, 10진법, 16진법 사이에서 변환합니다.", description: "무료 진법 변환기. 값과 진법을 입력하면 2진법, 8진법, 10진법, 16진법으로 즉시 표시됩니다. 2, 8, 10, 16진법을 지원합니다. 브라우저에서 실행됩니다.", keywords: ["진법 변환기", "2진법을 10진법으로", "16진법을 10진법으로", "10진법을 2진법으로", "기수 변환"], fromBase: "입력 진법", binary: "2진법", octal: "8진법", decimal: "10진법", hex: "16진법", placeholder: "숫자를 입력하세요…", invalid: "선택한 진법에 유효하지 않은 숫자입니다." },
  hi: { title: "संख्या आधार कन्वर्टर", short: "संख्याओं को बाइनरी, ऑक्टल, दशमलव और हेक्साडेसिमल के बीच बदलें।", description: "मुफ्त संख्या आधार कन्वर्टर। एक मान और उसका आधार दर्ज करें और उसे तुरंत बाइनरी, ऑक्टल, दशमलव और हेक्साडेसिमल में देखें। आधार 2, 8, 10 और 16 समर्थित। ब्राउज़र में चलता है।", keywords: ["संख्या आधार कन्वर्टर", "बाइनरी से दशमलव", "हेक्स से दशमलव", "दशमलव से बाइनरी", "आधार कन्वर्टर"], fromBase: "इनपुट आधार", binary: "बाइनरी", octal: "ऑक्टल", decimal: "दशमलव", hex: "हेक्साडेसिमल", placeholder: "एक संख्या दर्ज करें…", invalid: "चयनित आधार के लिए अमान्य संख्या।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
