import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JSON to TypeScript", short: "Generate TypeScript interfaces from a JSON sample.", description: "Free JSON to TypeScript interface generator. Paste a JSON object or array to get a tidy set of TypeScript interfaces with nested types, optional reserved-word handling and array unions.", keywords: ["json to typescript", "json to ts", "typescript interface generator", "json schema", "infer ts types"], rootName: "Root name", input: "JSON", output: "TypeScript" },
  tr: { title: "JSON'dan TypeScript'e", short: "Bir JSON örneğinden TypeScript arayüzleri oluşturun.", description: "Ücretsiz JSON'dan TypeScript arayüz oluşturucu. Bir JSON nesnesi veya dizisini yapıştırın; iç içe türler, ayrılmış kelime ele alımı ve dizi birleşimleriyle düzgün bir TypeScript arayüzü seti alın.", keywords: ["json typescript", "json ts", "typescript arayüz oluşturucu", "json şema", "ts türleri çıkarma"], rootName: "Kök ad", input: "JSON", output: "TypeScript" },
  de: { title: "JSON zu TypeScript", short: "Erzeugen Sie TypeScript-Interfaces aus einem JSON-Beispiel.", description: "Kostenloser JSON-zu-TypeScript-Interface-Generator. Fügen Sie ein JSON-Objekt oder -Array ein, um eine saubere Reihe TypeScript-Interfaces mit verschachtelten Typen, reservierter-Wort-Behandlung und Array-Unions zu erhalten.", keywords: ["json zu typescript", "json zu ts", "typescript interface generator", "json schema", "ts typen ableiten"], rootName: "Root-Name", input: "JSON", output: "TypeScript" },
  fr: { title: "JSON vers TypeScript", short: "Générez des interfaces TypeScript à partir d'un échantillon JSON.", description: "Générateur d'interfaces TypeScript à partir de JSON gratuit. Collez un objet ou tableau JSON pour obtenir un ensemble net d'interfaces TypeScript avec types imbriqués, gestion des mots réservés et unions de tableau.", keywords: ["json vers typescript", "json vers ts", "générateur interface typescript", "schéma json", "déduire types ts"], rootName: "Nom racine", input: "JSON", output: "TypeScript" },
  es: { title: "JSON a TypeScript", short: "Genera interfaces TypeScript desde una muestra JSON.", description: "Generador de interfaces TypeScript desde JSON gratuito. Pega un objeto o array JSON para obtener un conjunto ordenado de interfaces TypeScript con tipos anidados, manejo de palabras reservadas y uniones de array.", keywords: ["json a typescript", "json a ts", "generador interface typescript", "esquema json", "inferir tipos ts"], rootName: "Nombre raíz", input: "JSON", output: "TypeScript" },
  it: { title: "JSON a TypeScript", short: "Genera interfacce TypeScript da un campione JSON.", description: "Generatore di interfacce TypeScript da JSON gratuito. Incolla un oggetto o array JSON per ottenere un insieme ordinato di interfacce TypeScript con tipi annidati, gestione di parole riservate e unioni di array.", keywords: ["json a typescript", "json a ts", "generatore interface typescript", "schema json", "inferire tipi ts"], rootName: "Nome radice", input: "JSON", output: "TypeScript" },
  ar: { title: "JSON إلى TypeScript", short: "أنشئ واجهات TypeScript من عينة JSON.", description: "مولّد واجهات TypeScript من JSON مجاني. الصق كائن أو مصفوفة JSON للحصول على مجموعة منظّمة من واجهات TypeScript مع أنواع متداخلة ومعالجة الكلمات المحجوزة واتحادات المصفوفات.", keywords: ["json إلى typescript", "json إلى ts", "مولد واجهات typescript", "مخطط json", "استنتاج أنواع ts"], rootName: "اسم الجذر", input: "JSON", output: "TypeScript" },
  ru: { title: "JSON в TypeScript", short: "Создавайте интерфейсы TypeScript из примера JSON.", description: "Бесплатный генератор интерфейсов TypeScript из JSON. Вставьте JSON-объект или массив, чтобы получить аккуратный набор интерфейсов TypeScript с вложенными типами, обработкой зарезервированных слов и объединениями массивов.", keywords: ["json в typescript", "json в ts", "генератор интерфейсов typescript", "json схема", "вывод типов ts"], rootName: "Имя корня", input: "JSON", output: "TypeScript" },
  zh: { title: "JSON 转 TypeScript", short: "从 JSON 样本生成 TypeScript 接口。", description: "免费的 JSON 转 TypeScript 接口生成器。粘贴 JSON 对象或数组，即可获得整洁的 TypeScript 接口集，包括嵌套类型、保留字处理和数组联合类型。", keywords: ["json 转 typescript", "json 转 ts", "typescript 接口生成器", "json 模式", "推断 ts 类型"], rootName: "根名称", input: "JSON", output: "TypeScript" },
  ja: { title: "JSON から TypeScript", short: "JSON サンプルから TypeScript インターフェースを生成。", description: "無料の JSON から TypeScript インターフェース生成ツール。JSON オブジェクトまたは配列を貼り付けると、ネストした型、予約語の処理、配列のユニオン付きの整理された TypeScript インターフェース群が得られます。", keywords: ["json から typescript", "json から ts", "typescript インターフェース 生成", "json スキーマ", "ts 型 推論"], rootName: "ルート名", input: "JSON", output: "TypeScript" },
  ko: { title: "JSON to TypeScript", short: "JSON 샘플에서 TypeScript 인터페이스를 생성합니다.", description: "무료 JSON to TypeScript 인터페이스 생성기. JSON 객체나 배열을 붙여넣으면 중첩 타입, 예약어 처리, 배열 유니온이 포함된 깔끔한 TypeScript 인터페이스 세트를 얻습니다.", keywords: ["json to typescript", "json to ts", "typescript 인터페이스 생성기", "json 스키마", "ts 타입 추론"], rootName: "루트 이름", input: "JSON", output: "TypeScript" },
  hi: { title: "JSON से TypeScript", short: "एक JSON नमूने से TypeScript इंटरफेस बनाएं।", description: "मुफ्त JSON से TypeScript इंटरफेस जनरेटर। एक JSON ऑब्जेक्ट या एरे पेस्ट करें और नेस्टेड प्रकार, आरक्षित-शब्द हैंडलिंग और एरे यूनियनों के साथ TypeScript इंटरफेसों का एक साफ सेट पाएं।", keywords: ["json से typescript", "json से ts", "typescript इंटरफेस जनरेटर", "json स्कीमा", "ts प्रकार अनुमान"], rootName: "रूट नाम", input: "JSON", output: "TypeScript" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
