import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Syllable Counter", short: "Estimate syllables in English text for haiku and poetry.", description: "Free English syllable counter. Paste text to count syllables and words using a vowel-group heuristic with silent-e and -le corrections — useful for haiku, poetry and ESL practice. Runs in your browser.", keywords: ["syllable counter", "count syllables", "haiku counter", "syllables in word", "english syllable counter"], input: "Text", words: "Words", syllables: "Syllables" },
  nl: { title: "Lettergreep Counter", short: "Estimate syllables in English tekst for haiku and poetry.", description: "Gratis English syllable counter. Paste tekst to count syllables and words using a vowel-group heuristic with silent-e and -le corrections — useful for haiku, poetry and ESL practice. Runs in uw browser.", keywords: ["syllable counter", "count syllables", "haiku counter", "syllables in word", "english syllable counter"], input: "Tekst", words: "Words", syllables: "Lettergreeps" },

  pl: { title: "Sylaba Counter", short: "Estimate syllables in English tekst for haiku and poetry.", description: "Darmowy English syllable counter. Paste tekst to count syllables and words using a vowel-group heuristic with silent-e and -le corrections — useful for haiku, poetry and ESL practice. Runs w Twojej przeglądarce.", keywords: ["syllable counter", "count syllables", "haiku counter", "syllables in word", "english syllable counter"], input: "Tekst", words: "Words", syllables: "Sylabas" },
  pt: { title: "Contador de Syllable", short: "Estimate syllables em English text para haiku e poetry.", description: "Gratuito - English syllable counter. Paste text para count syllables e words usando a vowel-group heuristic com silent-e e -le corrections â useful para haiku, poetry e ESL practice. Runs no seu navegador.", keywords: ["syllable counter", "count syllables", "haiku counter", "syllables in word", "english syllable counter"], input: "Text", words: "Words", syllables: "Syllables" },
  id: { title: "Penghitung Syllable", short: "Estimate syllables in English text for haiku dan poetry.", description: "Gratis - English syllable counter. Paste text to count syllables dan words menggunakan a vowel-group heuristic with silent-e dan -le corrections â useful for haiku, poetry dan ESL practice. Runs di browser Anda.", keywords: ["syllable counter", "count syllables", "haiku counter", "syllables in word", "english syllable counter"], input: "Text", words: "Words", syllables: "Syllables" },

  tr: { title: "Hece Sayacı", short: "Haiku ve şiir için İngilizce metindeki heceleri tahmin edin.", description: "Ücretsiz İngilizce hece sayacı. Sessiz -e ve -le düzeltmeleriyle ünlü grup sezgisi kullanarak hece ve kelime sayısını alın — haiku, şiir ve ESL pratiği için faydalı. Tarayıcınızda çalışır.", keywords: ["hece sayacı", "hece say", "haiku sayacı", "kelimedeki heceler", "ingilizce hece sayacı"], input: "Metin", words: "Kelime", syllables: "Hece" },
  de: { title: "Silbenzähler", short: "Silben in englischem Text für Haiku und Lyrik schätzen.", description: "Kostenloser englischer Silbenzähler. Fügen Sie Text ein, um Silben und Wörter mit einer Vokalgruppen-Heuristik samt stummem -e und -le-Korrekturen zu zählen — nützlich für Haiku, Lyrik und ESL-Übungen. Läuft im Browser.", keywords: ["silbenzähler", "silben zählen", "haiku zähler", "silben im wort", "englischer silbenzähler"], input: "Text", words: "Wörter", syllables: "Silben" },
  fr: { title: "Compteur de Syllabes", short: "Estimez les syllabes dans un texte anglais pour haïku et poésie.", description: "Compteur de syllabes anglais gratuit. Collez du texte pour compter syllabes et mots à l'aide d'une heuristique de groupes de voyelles avec corrections pour -e silencieux et -le — utile pour haïku, poésie et apprentissage ESL. Fonctionne dans votre navigateur.", keywords: ["compteur syllabes", "compter syllabes", "compteur haïku", "syllabes dans mot", "compteur syllabes anglais"], input: "Texte", words: "Mots", syllables: "Syllabes" },
  es: { title: "Contador de Sílabas", short: "Estima sílabas en texto inglés para haiku y poesía.", description: "Contador de sílabas en inglés gratuito. Pega texto para contar sílabas y palabras con una heurística de grupos vocálicos y correcciones de -e muda y -le — útil para haiku, poesía y práctica ESL. Funciona en tu navegador.", keywords: ["contador sílabas", "contar sílabas", "contador haiku", "sílabas en palabra", "contador sílabas inglés"], input: "Texto", words: "Palabras", syllables: "Sílabas" },
  it: { title: "Contatore di Sillabe", short: "Stima le sillabe in testo inglese per haiku e poesia.", description: "Contatore di sillabe inglese gratuito. Incolla testo per contare sillabe e parole con un'euristica di gruppi vocalici e correzioni per -e muta e -le — utile per haiku, poesia e pratica ESL. Funziona nel browser.", keywords: ["contatore sillabe", "contare sillabe", "contatore haiku", "sillabe in parola", "contatore sillabe inglese"], input: "Testo", words: "Parole", syllables: "Sillabe" },
  ar: { title: "عدّاد المقاطع", short: "قدّر المقاطع في النص الإنجليزي للهايكو والشعر.", description: "عدّاد مقاطع إنجليزي مجاني. الصق نصًا لعدّ المقاطع والكلمات باستخدام استدلال مجموعات الحروف الصوتية مع تصحيحات -e الصامتة و -le — مفيد للهايكو والشعر وممارسة ESL. يعمل في متصفحك.", keywords: ["عداد المقاطع", "عد المقاطع", "عداد الهايكو", "مقاطع الكلمة", "عداد المقاطع الإنجليزية"], input: "النص", words: "الكلمات", syllables: "المقاطع" },
  ru: { title: "Счётчик слогов", short: "Оцените количество слогов в английском тексте для хайку и поэзии.", description: "Бесплатный счётчик слогов английского текста. Вставьте текст, чтобы посчитать слоги и слова с помощью эвристики гласных групп и поправок на немую -e и -le — полезно для хайку, поэзии и ESL-практики. Работает в браузере.", keywords: ["счётчик слогов", "посчитать слоги", "счётчик хайку", "слоги в слове", "счётчик слогов английский"], input: "Текст", words: "Слова", syllables: "Слоги" },
  zh: { title: "音节计数器", short: "估算英语文本中的音节，适合俳句和诗歌。", description: "免费的英语音节计数器。粘贴文本，使用元音组启发式以及无声 -e 和 -le 校正来计数音节和单词——适用于俳句、诗歌和 ESL 练习。在浏览器中运行。", keywords: ["音节计数器", "计数音节", "俳句计数器", "单词中的音节", "英语音节计数器"], input: "文本", words: "单词", syllables: "音节" },
  ja: { title: "音節カウンター", short: "俳句や詩のための英語テキストの音節を推定。", description: "無料の英語音節カウンター。テキストを貼り付け、母音グループのヒューリスティックとサイレント -e および -le の補正を使って音節と単語を数えます——俳句、詩、ESL 練習に便利。ブラウザ内で動作します。", keywords: ["音節 カウンター", "音節 数える", "俳句 カウンター", "単語の音節", "英語 音節 カウンター"], input: "テキスト", words: "単語", syllables: "音節" },
  ko: { title: "음절 카운터", short: "하이쿠와 시를 위한 영어 텍스트의 음절을 추정합니다.", description: "무료 영어 음절 카운터. 텍스트를 붙여넣어 모음 그룹 휴리스틱과 묵음 -e 및 -le 보정으로 음절과 단어를 셉니다 — 하이쿠, 시, ESL 연습에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["음절 카운터", "음절 세기", "하이쿠 카운터", "단어 음절", "영어 음절 카운터"], input: "텍스트", words: "단어", syllables: "음절" },
  hi: { title: "अक्षर गणक", short: "हाइकु और कविता के लिए अंग्रेज़ी पाठ में अक्षर अनुमानित करें।", description: "मुफ्त अंग्रेज़ी अक्षर गणक। मूक -e और -le सुधार के साथ स्वर समूह उपयोग करके अक्षर और शब्दों की गिनती के लिए पाठ पेस्ट करें — हाइकु, कविता और ESL अभ्यास के लिए उपयोगी। आपके ब्राउज़र में चलता है।", keywords: ["अक्षर गणक", "अक्षर गिनें", "हाइकु गणक", "शब्द में अक्षर", "अंग्रेज़ी अक्षर गणक"], input: "टेक्स्ट", words: "शब्द", syllables: "अक्षर" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
