import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Base64 Encode / Decode", short: "Encode text to Base64 or decode Base64 back to text, with full UTF-8 support.", description: "Free Base64 encoder and decoder. Convert any text (including UTF-8 and emoji) to Base64 and back. Everything runs locally in your browser — nothing is uploaded.", keywords: ["base64", "base64 encode", "base64 decode", "base64 converter", "encoder decoder"], encode: "Encode", decode: "Decode", placeholder: "Enter text or Base64…", invalid: "Invalid Base64 input." },
  tr: { title: "Base64 Kodla / Çöz", short: "Metni Base64'e kodlayın veya Base64'ü metne geri çözün, tam UTF-8 desteğiyle.", description: "Ücretsiz Base64 kodlayıcı ve çözücü. Herhangi bir metni (UTF-8 ve emoji dâhil) Base64'e ve geri çevirin. Her şey tarayıcınızda yerel çalışır — hiçbir şey yüklenmez.", keywords: ["base64", "base64 kodlama", "base64 çözme", "base64 dönüştürücü", "kodlayıcı çözücü"], encode: "Kodla", decode: "Çöz", placeholder: "Metin veya Base64 girin…", invalid: "Geçersiz Base64 girdisi." },
  de: { title: "Base64 Kodieren / Dekodieren", short: "Text in Base64 kodieren oder Base64 zurück in Text dekodieren, mit voller UTF-8-Unterstützung.", description: "Kostenloser Base64-Encoder und -Decoder. Wandeln Sie beliebigen Text (inkl. UTF-8 und Emoji) in Base64 und zurück. Alles läuft lokal im Browser.", keywords: ["base64", "base64 kodieren", "base64 dekodieren", "base64 konverter", "encoder decoder"], encode: "Kodieren", decode: "Dekodieren", placeholder: "Text oder Base64 eingeben…", invalid: "Ungültige Base64-Eingabe." },
  fr: { title: "Encoder / Décoder Base64", short: "Encodez du texte en Base64 ou décodez du Base64 en texte, avec prise en charge UTF-8.", description: "Encodeur et décodeur Base64 gratuit. Convertissez n'importe quel texte (y compris UTF-8 et emoji) en Base64 et inversement. Tout s'exécute localement dans votre navigateur.", keywords: ["base64", "encoder base64", "décoder base64", "convertisseur base64", "encodeur décodeur"], encode: "Encoder", decode: "Décoder", placeholder: "Saisissez du texte ou du Base64…", invalid: "Entrée Base64 invalide." },
  es: { title: "Codificar / Decodificar Base64", short: "Codifica texto a Base64 o decodifica Base64 a texto, con soporte UTF-8 completo.", description: "Codificador y decodificador Base64 gratuito. Convierte cualquier texto (incluido UTF-8 y emoji) a Base64 y viceversa. Todo se ejecuta localmente en tu navegador.", keywords: ["base64", "codificar base64", "decodificar base64", "conversor base64", "codificador decodificador"], encode: "Codificar", decode: "Decodificar", placeholder: "Introduce texto o Base64…", invalid: "Entrada Base64 no válida." },
  it: { title: "Codifica / Decodifica Base64", short: "Codifica testo in Base64 o decodifica Base64 in testo, con pieno supporto UTF-8.", description: "Codificatore e decodificatore Base64 gratuito. Converti qualsiasi testo (incluso UTF-8 ed emoji) in Base64 e viceversa. Tutto viene eseguito localmente nel browser.", keywords: ["base64", "codifica base64", "decodifica base64", "convertitore base64", "codificatore decodificatore"], encode: "Codifica", decode: "Decodifica", placeholder: "Inserisci testo o Base64…", invalid: "Input Base64 non valido." },
  ar: { title: "ترميز / فك ترميز Base64", short: "رمّز النص إلى Base64 أو فك ترميز Base64 إلى نص، مع دعم كامل لـ UTF-8.", description: "مرمّز ومفكّك Base64 مجاني. حوّل أي نص (بما في ذلك UTF-8 والرموز التعبيرية) إلى Base64 والعكس. كل شيء يعمل محليًا في متصفحك.", keywords: ["base64", "ترميز base64", "فك ترميز base64", "محول base64", "مرمز مفكك"], encode: "ترميز", decode: "فك الترميز", placeholder: "أدخل نصًا أو Base64…", invalid: "إدخال Base64 غير صالح." },
  ru: { title: "Кодирование / Декодирование Base64", short: "Кодируйте текст в Base64 или декодируйте Base64 обратно в текст с полной поддержкой UTF-8.", description: "Бесплатный кодировщик и декодировщик Base64. Преобразуйте любой текст (включая UTF-8 и эмодзи) в Base64 и обратно. Всё работает локально в браузере.", keywords: ["base64", "кодирование base64", "декодирование base64", "конвертер base64", "кодировщик декодировщик"], encode: "Кодировать", decode: "Декодировать", placeholder: "Введите текст или Base64…", invalid: "Недопустимый ввод Base64." },
  zh: { title: "Base64 编码 / 解码", short: "将文本编码为 Base64 或将 Base64 解码为文本，完整支持 UTF-8。", description: "免费的 Base64 编码器和解码器。将任意文本（包括 UTF-8 和表情符号）转换为 Base64 并还原。一切都在浏览器本地运行，不上传任何内容。", keywords: ["base64", "base64 编码", "base64 解码", "base64 转换器", "编码解码"], encode: "编码", decode: "解码", placeholder: "输入文本或 Base64…", invalid: "无效的 Base64 输入。" },
  ja: { title: "Base64 エンコード / デコード", short: "テキストを Base64 にエンコード、または Base64 をテキストにデコード。UTF-8 完全対応。", description: "無料の Base64 エンコーダー・デコーダー。任意のテキスト（UTF-8 や絵文字を含む）を Base64 に変換し、元に戻せます。すべてブラウザ内でローカルに動作します。", keywords: ["base64", "base64 エンコード", "base64 デコード", "base64 変換", "エンコーダー デコーダー"], encode: "エンコード", decode: "デコード", placeholder: "テキストまたは Base64 を入力…", invalid: "無効な Base64 入力です。" },
  ko: { title: "Base64 인코딩 / 디코딩", short: "텍스트를 Base64로 인코딩하거나 Base64를 텍스트로 디코딩합니다. UTF-8 완전 지원.", description: "무료 Base64 인코더 및 디코더. 모든 텍스트(UTF-8 및 이모지 포함)를 Base64로 변환하고 되돌립니다. 모든 것이 브라우저에서 로컬로 실행됩니다.", keywords: ["base64", "base64 인코딩", "base64 디코딩", "base64 변환기", "인코더 디코더"], encode: "인코딩", decode: "디코딩", placeholder: "텍스트 또는 Base64 입력…", invalid: "잘못된 Base64 입력입니다." },
  hi: { title: "Base64 एन्कोड / डिकोड", short: "टेक्स्ट को Base64 में एन्कोड करें या Base64 को टेक्स्ट में डिकोड करें, पूर्ण UTF-8 समर्थन के साथ।", description: "मुफ्त Base64 एन्कोडर और डिकोडर। किसी भी टेक्स्ट (UTF-8 और इमोजी सहित) को Base64 में और वापस बदलें। सब कुछ आपके ब्राउज़र में स्थानीय रूप से चलता है।", keywords: ["base64", "base64 एन्कोड", "base64 डिकोड", "base64 कन्वर्टर", "एन्कोडर डिकोडर"], encode: "एन्कोड", decode: "डिकोड", placeholder: "टेक्स्ट या Base64 दर्ज करें…", invalid: "अमान्य Base64 इनपुट।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, encode, decode, placeholder, invalid } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], encode, decode, placeholder, invalid } }];
  }),
) as unknown as ToolI18n;

export default i18n;
