import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "JSON Diff", short: "Compare two JSON documents and see exactly what changed.", description: "Free JSON diff tool. Paste two JSON documents to see additions, removals and value changes by path — works on nested objects and arrays, entirely in your browser.", keywords: ["json diff", "compare json", "json compare online", "json structural diff", "json comparator"], left: "JSON A", right: "JSON B", added: "Added", removed: "Removed", changed: "Changed", identical: "Identical" },
  pt: { title: "JSON Diff", short: "Compare two JSON documents e see exactly what changed.", description: "Gratuito - JSON diff tool. Paste two JSON documents para see additions, removals e value changes by path â works on nested objects e arrays, entirely no seu navegador.", keywords: ["json diff", "compare json", "json compare online", "json structural diff", "json comparator"], left: "JSON A", right: "JSON B", added: "Added", removed: "Removed", changed: "Changed", identical: "Identical" },
  id: { title: "JSON Diff", short: "Compare two JSON documents dan see exactly what changed.", description: "Gratis - JSON diff tool. Paste two JSON documents to see additions, removals dan value changes by path â works on nested objects dan arrays, entirely di browser Anda.", keywords: ["json diff", "compare json", "json compare online", "json structural diff", "json comparator"], left: "JSON A", right: "JSON B", added: "Added", removed: "Removed", changed: "Changed", identical: "Identical" },

  tr: { title: "JSON Karşılaştırıcı", short: "İki JSON belgesini karşılaştırın ve farkları görün.", description: "Ücretsiz JSON karşılaştırma aracı. İki JSON belgesini yapıştırın; eklemeleri, silmeleri ve yola göre değer değişikliklerini görün — iç içe nesneler ve dizilerde çalışır, tamamen tarayıcınızda.", keywords: ["json karşılaştır", "json fark", "json karşılaştırma online", "json yapısal fark", "json kıyasla"], left: "JSON A", right: "JSON B", added: "Eklendi", removed: "Silindi", changed: "Değişti", identical: "Aynı" },
  de: { title: "JSON-Vergleich", short: "Vergleichen Sie zwei JSON-Dokumente und sehen Sie die Unterschiede.", description: "Kostenloses JSON-Vergleichs-Tool. Fügen Sie zwei JSON-Dokumente ein, um Hinzufügungen, Entfernungen und Wertänderungen nach Pfad zu sehen — funktioniert für verschachtelte Objekte und Arrays, vollständig im Browser.", keywords: ["json vergleich", "json diff", "json online vergleichen", "json strukturvergleich", "json comparator"], left: "JSON A", right: "JSON B", added: "Hinzugefügt", removed: "Entfernt", changed: "Geändert", identical: "Identisch" },
  fr: { title: "JSON Diff", short: "Comparez deux documents JSON et voyez exactement ce qui a changé.", description: "Outil JSON diff gratuit. Collez deux documents JSON pour voir les ajouts, suppressions et changements de valeur par chemin — fonctionne sur les objets et tableaux imbriqués, entièrement dans votre navigateur.", keywords: ["json diff", "comparer json", "json compare en ligne", "diff structurel json", "comparateur json"], left: "JSON A", right: "JSON B", added: "Ajouté", removed: "Supprimé", changed: "Modifié", identical: "Identique" },
  es: { title: "JSON Diff", short: "Compara dos documentos JSON y ve exactamente qué cambió.", description: "Herramienta JSON diff gratuita. Pega dos documentos JSON para ver adiciones, eliminaciones y cambios de valor por ruta — funciona en objetos y arrays anidados, todo en tu navegador.", keywords: ["json diff", "comparar json", "json compare online", "diff estructural json", "comparador json"], left: "JSON A", right: "JSON B", added: "Añadido", removed: "Eliminado", changed: "Modificado", identical: "Idénticos" },
  it: { title: "JSON Diff", short: "Confronta due documenti JSON e vedi esattamente cosa è cambiato.", description: "Strumento JSON diff gratuito. Incolla due documenti JSON per vedere aggiunte, rimozioni e modifiche di valore per percorso — funziona su oggetti e array annidati, interamente nel browser.", keywords: ["json diff", "confronta json", "json compare online", "diff strutturale json", "comparatore json"], left: "JSON A", right: "JSON B", added: "Aggiunto", removed: "Rimosso", changed: "Modificato", identical: "Identici" },
  ar: { title: "JSON Diff", short: "قارن بين مستندي JSON وشاهد ما تغيّر بالضبط.", description: "أداة JSON diff مجانية. الصق مستندي JSON لرؤية الإضافات والإزالات وتغييرات القيم حسب المسار — تعمل على الكائنات والمصفوفات المتداخلة، بالكامل في متصفحك.", keywords: ["json diff", "مقارنة json", "json compare عبر الإنترنت", "diff بنيوي json", "مقارن json"], left: "JSON A", right: "JSON B", added: "مضاف", removed: "مُزال", changed: "تغيّر", identical: "متطابقان" },
  ru: { title: "JSON Diff", short: "Сравните два JSON-документа и увидьте, что изменилось.", description: "Бесплатный инструмент JSON diff. Вставьте два JSON-документа, чтобы увидеть добавления, удаления и изменения значений по пути — работает с вложенными объектами и массивами, всё в браузере.", keywords: ["json diff", "сравнить json", "json compare онлайн", "структурный diff json", "json компаратор"], left: "JSON A", right: "JSON B", added: "Добавлено", removed: "Удалено", changed: "Изменено", identical: "Идентичны" },
  zh: { title: "JSON 比对", short: "比较两个 JSON 文档，查看具体差异。", description: "免费的 JSON 比对工具。粘贴两个 JSON 文档，按路径查看添加、删除和值更改——适用于嵌套对象和数组，完全在浏览器中运行。", keywords: ["json 比对", "比较 json", "json 在线比较", "json 结构比对", "json 比较器"], left: "JSON A", right: "JSON B", added: "添加", removed: "删除", changed: "更改", identical: "相同" },
  ja: { title: "JSON Diff", short: "2つの JSON ドキュメントを比較し、変更点を確認。", description: "無料の JSON diff ツール。2つの JSON ドキュメントを貼り付けると、パスごとの追加・削除・値変更を確認できます——ネストしたオブジェクトや配列にも対応、すべてブラウザ内で。", keywords: ["json diff", "json 比較", "json compare オンライン", "json 構造比較", "json コンパレーター"], left: "JSON A", right: "JSON B", added: "追加", removed: "削除", changed: "変更", identical: "同一" },
  ko: { title: "JSON Diff", short: "두 JSON 문서를 비교하여 변경 사항을 정확히 확인합니다.", description: "무료 JSON diff 도구. 두 JSON 문서를 붙여넣으면 경로별 추가, 제거, 값 변경을 확인할 수 있습니다 — 중첩된 객체와 배열에서도 작동하며 모두 브라우저에서 실행됩니다.", keywords: ["json diff", "json 비교", "json compare 온라인", "json 구조 비교", "json 비교기"], left: "JSON A", right: "JSON B", added: "추가됨", removed: "제거됨", changed: "변경됨", identical: "동일" },
  hi: { title: "JSON Diff", short: "दो JSON दस्तावेज़ों की तुलना करें और ठीक देखें कि क्या बदला।", description: "मुफ्त JSON diff टूल। दो JSON दस्तावेज़ पेस्ट करें और पथ के अनुसार जोड़, हटाने और मान परिवर्तन देखें — नेस्टेड ऑब्जेक्ट्स और एरे पर काम करता है, पूरी तरह आपके ब्राउज़र में।", keywords: ["json diff", "json तुलना", "json compare ऑनलाइन", "json संरचनात्मक diff", "json कम्पेरेटर"], left: "JSON A", right: "JSON B", added: "जोड़ा गया", removed: "हटाया गया", changed: "बदला गया", identical: "समान" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
