import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Binary Calculator", short: "Add, subtract, AND, OR, XOR and shift binary numbers.", description: "Free binary calculator. Add, subtract, multiply, divide, AND, OR, XOR or shift two binary numbers — BigInt-backed for arbitrary precision. Results are shown in binary, decimal, hex and octal.", keywords: ["binary calculator", "bitwise calculator", "binary arithmetic", "and or xor calculator", "binary shift calculator"], a: "A (binary)", b: "B (binary)", op: "Operator", result: "Result", binary: "Binary", decimal: "Decimal", hex: "Hex", octal: "Octal" },
  pt: { title: "Calculadora de Binary", short: "Add, subtract, AND, OR, XOR e shift binary numbers.", description: "Gratuito - binary calculator. Add, subtract, multiply, divide, AND, OR, XOR ou shift two binary numbers â BigInt-backed para arbitrary precision. Results are shown em binary, decimal, hex e octal.", keywords: ["binary calculator", "bitwise calculator", "binary arithmetic", "and or xor calculator", "binary shift calculator"], a: "A (binary)", b: "B (binary)", op: "Operator", result: "Result", binary: "Binary", decimal: "Decimal", hex: "Hex", octal: "Octal" },
  id: { title: "Kalkulator Binary", short: "Add, subtract, AND, OR, XOR dan shift binary numbers.", description: "Gratis - binary calculator. Add, subtract, multiply, divide, AND, OR, XOR atau shift two binary numbers â BigInt-backed for arbitrary precision. Results are shown in binary, decimal, hex dan octal.", keywords: ["binary calculator", "bitwise calculator", "binary arithmetic", "and or xor calculator", "binary shift calculator"], a: "A (binary)", b: "B (binary)", op: "Operator", result: "Result", binary: "Binary", decimal: "Decimal", hex: "Hex", octal: "Octal" },

  tr: { title: "İkili Hesap Makinesi", short: "İkili sayıları toplayın, çıkarın, AND, OR, XOR ve kaydırın.", description: "Ücretsiz ikili hesap makinesi. İki ikili sayıyı toplayın, çıkarın, çarpın, bölün, AND, OR, XOR veya kaydırın — BigInt destekli, keyfi hassasiyet. Sonuçlar ikili, ondalık, hex ve sekizlik olarak gösterilir.", keywords: ["ikili hesap makinesi", "bit düzeyi hesaplama", "ikili aritmetik", "and or xor hesaplama", "ikili kaydırma"], a: "A (ikili)", b: "B (ikili)", op: "İşleç", result: "Sonuç", binary: "İkili", decimal: "Ondalık", hex: "Hex", octal: "Sekizlik" },
  de: { title: "Binär-Rechner", short: "Addieren, subtrahieren, AND, OR, XOR und Shift von Binärzahlen.", description: "Kostenloser Binär-Rechner. Addieren, subtrahieren, multiplizieren, dividieren, AND, OR, XOR oder shiften Sie zwei Binärzahlen — BigInt-gestützt für beliebige Präzision. Ergebnisse in Binär, Dezimal, Hex und Oktal.", keywords: ["binär rechner", "bitweise rechner", "binäre arithmetik", "and or xor rechner", "binär shift rechner"], a: "A (binär)", b: "B (binär)", op: "Operator", result: "Ergebnis", binary: "Binär", decimal: "Dezimal", hex: "Hex", octal: "Oktal" },
  fr: { title: "Calculatrice Binaire", short: "Additionnez, soustrayez, AND, OR, XOR et décalez des nombres binaires.", description: "Calculatrice binaire gratuite. Additionnez, soustrayez, multipliez, divisez, AND, OR, XOR ou décalez deux nombres binaires — BigInt pour une précision arbitraire. Résultats en binaire, décimal, hex et octal.", keywords: ["calculatrice binaire", "calculatrice bit à bit", "arithmétique binaire", "calculatrice and or xor", "décalage binaire"], a: "A (binaire)", b: "B (binaire)", op: "Opérateur", result: "Résultat", binary: "Binaire", decimal: "Décimal", hex: "Hex", octal: "Octal" },
  es: { title: "Calculadora Binaria", short: "Suma, resta, AND, OR, XOR y desplaza números binarios.", description: "Calculadora binaria gratuita. Suma, resta, multiplica, divide, AND, OR, XOR o desplaza dos números binarios — respaldado por BigInt para precisión arbitraria. Resultados en binario, decimal, hex y octal.", keywords: ["calculadora binaria", "calculadora bit a bit", "aritmética binaria", "calculadora and or xor", "desplazamiento binario"], a: "A (binario)", b: "B (binario)", op: "Operador", result: "Resultado", binary: "Binario", decimal: "Decimal", hex: "Hex", octal: "Octal" },
  it: { title: "Calcolatrice Binaria", short: "Aggiungi, sottrai, AND, OR, XOR e sposta numeri binari.", description: "Calcolatrice binaria gratuita. Aggiungi, sottrai, moltiplica, dividi, AND, OR, XOR o sposta due numeri binari — supportato da BigInt per precisione arbitraria. Risultati in binario, decimale, hex e ottale.", keywords: ["calcolatrice binaria", "calcolatrice bit a bit", "aritmetica binaria", "calcolatrice and or xor", "spostamento binario"], a: "A (binario)", b: "B (binario)", op: "Operatore", result: "Risultato", binary: "Binario", decimal: "Decimale", hex: "Hex", octal: "Ottale" },
  ar: { title: "حاسبة ثنائية", short: "اجمع واطرح و AND و OR و XOR وأزِح الأرقام الثنائية.", description: "حاسبة ثنائية مجانية. اجمع واطرح واضرب واقسم و AND و OR و XOR أو أزِح رقمين ثنائيين — مدعومة بـ BigInt لدقة غير محدودة. تُعرض النتائج بصيغ ثنائية وعشرية وست عشرية وثمانية.", keywords: ["حاسبة ثنائية", "حاسبة بت", "حساب ثنائي", "حاسبة and or xor", "إزاحة ثنائية"], a: "A (ثنائي)", b: "B (ثنائي)", op: "العامل", result: "النتيجة", binary: "ثنائي", decimal: "عشري", hex: "Hex", octal: "ثماني" },
  ru: { title: "Двоичный калькулятор", short: "Складывайте, вычитайте, AND, OR, XOR и сдвигайте двоичные числа.", description: "Бесплатный двоичный калькулятор. Складывайте, вычитайте, умножайте, делите, AND, OR, XOR или сдвигайте два двоичных числа — на BigInt для произвольной точности. Результаты в двоичном, десятичном, hex и восьмеричном.", keywords: ["двоичный калькулятор", "битовый калькулятор", "двоичная арифметика", "and or xor калькулятор", "двоичный сдвиг"], a: "A (двоичный)", b: "B (двоичный)", op: "Оператор", result: "Результат", binary: "Двоичный", decimal: "Десятичный", hex: "Hex", octal: "Восьмеричный" },
  zh: { title: "二进制计算器", short: "对二进制数进行加、减、AND、OR、XOR 和位移。", description: "免费的二进制计算器。对两个二进制数进行加、减、乘、除、AND、OR、XOR 或位移——由 BigInt 支持，任意精度。结果以二进制、十进制、十六进制和八进制显示。", keywords: ["二进制计算器", "按位计算器", "二进制算术", "and or xor 计算器", "二进制位移"], a: "A（二进制）", b: "B（二进制）", op: "运算符", result: "结果", binary: "二进制", decimal: "十进制", hex: "十六进制", octal: "八进制" },
  ja: { title: "2進数電卓", short: "2進数の加減算、AND、OR、XOR、シフトを実行。", description: "無料の 2進数電卓。2つの 2進数を加減算、乗除算、AND、OR、XOR、またはシフトします——任意精度のために BigInt を採用。結果は 2進、10進、16進、8進で表示。", keywords: ["2進数 電卓", "ビット演算 電卓", "2進数 算術", "and or xor 電卓", "2進数 シフト"], a: "A（2進数）", b: "B（2進数）", op: "演算子", result: "結果", binary: "2進数", decimal: "10進数", hex: "16進数", octal: "8進数" },
  ko: { title: "이진수 계산기", short: "이진수의 덧셈, 뺄셈, AND, OR, XOR, 시프트를 수행합니다.", description: "무료 이진수 계산기. 두 이진수의 덧셈, 뺄셈, 곱셈, 나눗셈, AND, OR, XOR 또는 시프트 — 임의 정밀도를 위해 BigInt 사용. 결과는 이진수, 10진수, 16진수, 8진수로 표시됩니다.", keywords: ["이진수 계산기", "비트 계산기", "이진수 산술", "and or xor 계산기", "이진수 시프트"], a: "A (이진수)", b: "B (이진수)", op: "연산자", result: "결과", binary: "이진수", decimal: "10진수", hex: "16진수", octal: "8진수" },
  hi: { title: "बाइनरी कैलकुलेटर", short: "बाइनरी संख्याओं को जोड़ें, घटाएं, AND, OR, XOR और शिफ्ट करें।", description: "मुफ्त बाइनरी कैलकुलेटर। दो बाइनरी संख्याओं को जोड़ें, घटाएं, गुणा करें, भाग करें, AND, OR, XOR या शिफ्ट करें — मनमानी सटीकता के लिए BigInt समर्थित। परिणाम बाइनरी, दशमलव, हेक्स और अष्टक में दिखाए जाते हैं।", keywords: ["बाइनरी कैलकुलेटर", "बिटवाइज कैलकुलेटर", "बाइनरी अंकगणित", "and or xor कैलकुलेटर", "बाइनरी शिफ्ट"], a: "A (बाइनरी)", b: "B (बाइनरी)", op: "ऑपरेटर", result: "परिणाम", binary: "बाइनरी", decimal: "दशमलव", hex: "हेक्स", octal: "अष्टक" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
