import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Clamp Generator", short: "Generate a fluid responsive CSS clamp() value.", description: "Free CSS clamp() generator for fluid typography. Enter min/max sizes and viewport widths to get a responsive clamp() value you can paste straight into your CSS.", keywords: ["css clamp generator", "fluid typography", "responsive font size", "clamp css", "fluid type calculator"], minSize: "Min size (px)", maxSize: "Max size (px)", minViewport: "Min viewport (px)", maxViewport: "Max viewport (px)", result: "Result" },
  nl: { title: "CSS Clamp Generator", short: "Genereer a fluid responsive CSS clamp() value.", description: "Gratis CSS clamp() generator for fluid typography. Enter min/max groottes and viewport breedtes to get a responsive clamp() value you can paste straight into your CSS.", keywords: ["css clamp generator", "fluid typography", "responsive font grootte", "clamp css", "fluid type calculator"], minSize: "Min grootte (px)", maxSize: "Max grootte (px)", minViewport: "Min viewport (px)", maxViewport: "Max viewport (px)", result: "Resultaat" },

  pl: { title: "CSS Clamp Generator", short: "Generuj a fluid responsive CSS clamp() value.", description: "Darmowy CSS clamp() generator for fluid typography. Enter min/max rozmiars and viewport szerokośćs to get a responsive clamp() value you can paste straight into your CSS.", keywords: ["css clamp generator", "fluid typography", "responsive font rozmiar", "clamp css", "fluid type kalkulator"], minSize: "Min rozmiar (px)", maxSize: "Max rozmiar (px)", minViewport: "Min viewport (px)", maxViewport: "Max viewport (px)", result: "Wynik" },
  pt: { title: "Gerador de CSS Clamp", short: "Gerar a fluid responsive CSS clamp() value.", description: "Gratuito - CSS clamp() generator para fluid typography. Enter min/max sizes e viewport widths para get a responsive clamp() value you can paste straight into seu CSS.", keywords: ["css clamp generator", "fluid typography", "responsive font size", "clamp css", "fluid type calculator"], minSize: "Min size (px)", maxSize: "Max size (px)", minViewport: "Min viewport (px)", maxViewport: "Max viewport (px)", result: "Result" },
  id: { title: "Generator CSS Clamp", short: "Hasilkan a fluid responsive CSS clamp() value.", description: "Gratis - CSS clamp() generator for fluid typography. Enter min/max sizes dan viewport widths to get a responsive clamp() value you can paste straight into Anda CSS.", keywords: ["css clamp generator", "fluid typography", "responsive font size", "clamp css", "fluid type calculator"], minSize: "Min size (px)", maxSize: "Max size (px)", minViewport: "Min viewport (px)", maxViewport: "Max viewport (px)", result: "Result" },

  tr: { title: "CSS Clamp Oluşturucu", short: "Akışkan duyarlı CSS clamp() değeri oluşturun.", description: "Akışkan tipografi için ücretsiz CSS clamp() oluşturucu. Min/maks boyutları ve görünüm genişliklerini girerek doğrudan CSS'inize yapıştırabileceğiniz duyarlı bir clamp() değeri alın.", keywords: ["css clamp oluşturucu", "akışkan tipografi", "duyarlı yazı tipi boyutu", "clamp css", "akışkan tip hesaplayıcı"], minSize: "Min boyut (px)", maxSize: "Maks boyut (px)", minViewport: "Min görünüm (px)", maxViewport: "Maks görünüm (px)", result: "Sonuç" },
  de: { title: "CSS-Clamp-Generator", short: "Erzeugen Sie einen flüssigen, responsiven CSS-clamp()-Wert.", description: "Kostenloser CSS-clamp()-Generator für flüssige Typografie. Geben Sie Min/Max-Größen und Viewport-Breiten ein, um einen responsiven clamp()-Wert zum direkten Einfügen in Ihr CSS zu erhalten.", keywords: ["css clamp generator", "flüssige typografie", "responsive schriftgröße", "clamp css", "fluid type rechner"], minSize: "Min-Größe (px)", maxSize: "Max-Größe (px)", minViewport: "Min-Viewport (px)", maxViewport: "Max-Viewport (px)", result: "Ergebnis" },
  fr: { title: "Générateur de CSS Clamp", short: "Générez une valeur CSS clamp() fluide et responsive.", description: "Générateur de clamp() CSS gratuit pour la typographie fluide. Saisissez les tailles min/max et les largeurs de viewport pour obtenir une valeur clamp() responsive à coller directement dans votre CSS.", keywords: ["générateur css clamp", "typographie fluide", "taille de police responsive", "clamp css", "calculateur type fluide"], minSize: "Taille min (px)", maxSize: "Taille max (px)", minViewport: "Viewport min (px)", maxViewport: "Viewport max (px)", result: "Résultat" },
  es: { title: "Generador de CSS Clamp", short: "Genera un valor CSS clamp() fluido y responsive.", description: "Generador de clamp() CSS gratuito para tipografía fluida. Introduce tamaños mín/máx y anchos de viewport para obtener un valor clamp() responsive listo para pegar en tu CSS.", keywords: ["generador css clamp", "tipografía fluida", "tamaño de fuente responsive", "clamp css", "calculadora tipo fluido"], minSize: "Tamaño mín (px)", maxSize: "Tamaño máx (px)", minViewport: "Viewport mín (px)", maxViewport: "Viewport máx (px)", result: "Resultado" },
  it: { title: "Generatore di CSS Clamp", short: "Genera un valore CSS clamp() fluido e responsive.", description: "Generatore di clamp() CSS gratuito per tipografia fluida. Inserisci dimensioni min/max e larghezze viewport per ottenere un valore clamp() responsive da incollare direttamente nel tuo CSS.", keywords: ["generatore css clamp", "tipografia fluida", "dimensione font responsive", "clamp css", "calcolatore tipo fluido"], minSize: "Dimensione min (px)", maxSize: "Dimensione max (px)", minViewport: "Viewport min (px)", maxViewport: "Viewport max (px)", result: "Risultato" },
  ar: { title: "مولّد CSS Clamp", short: "أنشئ قيمة CSS clamp() مرنة ومتجاوبة.", description: "مولّد clamp() مجاني للطباعة المرنة. أدخل الأحجام الدنيا/القصوى وعرض نافذة العرض للحصول على قيمة clamp() متجاوبة جاهزة للصق مباشرة في CSS.", keywords: ["مولد css clamp", "طباعة مرنة", "حجم خط متجاوب", "clamp css", "حاسبة النوع المرن"], minSize: "أصغر حجم (px)", maxSize: "أكبر حجم (px)", minViewport: "أصغر عرض (px)", maxViewport: "أكبر عرض (px)", result: "النتيجة" },
  ru: { title: "Генератор CSS Clamp", short: "Создайте плавное адаптивное значение CSS clamp().", description: "Бесплатный генератор clamp() CSS для плавной типографики. Введите мин/макс размеры и ширину области просмотра, чтобы получить адаптивное значение clamp() для вставки в ваш CSS.", keywords: ["генератор css clamp", "плавная типографика", "адаптивный размер шрифта", "clamp css", "калькулятор плавного типа"], minSize: "Мин размер (px)", maxSize: "Макс размер (px)", minViewport: "Мин viewport (px)", maxViewport: "Макс viewport (px)", result: "Результат" },
  zh: { title: "CSS Clamp 生成器", short: "生成流式响应式 CSS clamp() 值。", description: "免费的流式排版 CSS clamp() 生成器。输入最小/最大尺寸和视口宽度，即可获得可直接粘贴到 CSS 中的响应式 clamp() 值。", keywords: ["css clamp 生成器", "流式排版", "响应式字体大小", "clamp css", "流式字号计算器"], minSize: "最小尺寸 (px)", maxSize: "最大尺寸 (px)", minViewport: "最小视口 (px)", maxViewport: "最大视口 (px)", result: "结果" },
  ja: { title: "CSS Clamp 生成", short: "流動的でレスポンシブな CSS clamp() 値を生成。", description: "流動的タイポグラフィ用の無料 CSS clamp() 生成ツール。最小/最大サイズとビューポート幅を入力すると、CSS に直接貼り付けられるレスポンシブな clamp() 値が得られます。", keywords: ["css clamp 生成", "流動的タイポグラフィ", "レスポンシブ フォントサイズ", "clamp css", "流動的タイプ計算"], minSize: "最小サイズ (px)", maxSize: "最大サイズ (px)", minViewport: "最小ビューポート (px)", maxViewport: "最大ビューポート (px)", result: "結果" },
  ko: { title: "CSS Clamp 생성기", short: "유동적이고 반응형인 CSS clamp() 값을 생성합니다.", description: "유동적 타이포그래피를 위한 무료 CSS clamp() 생성기. 최소/최대 크기와 뷰포트 너비를 입력하면 CSS에 바로 붙여넣을 수 있는 반응형 clamp() 값을 얻습니다.", keywords: ["css clamp 생성기", "유동적 타이포그래피", "반응형 글꼴 크기", "clamp css", "유동 타입 계산기"], minSize: "최소 크기 (px)", maxSize: "최대 크기 (px)", minViewport: "최소 뷰포트 (px)", maxViewport: "최대 뷰포트 (px)", result: "결과" },
  hi: { title: "CSS Clamp जनरेटर", short: "एक फ्लूइड रिस्पॉन्सिव CSS clamp() मान बनाएं।", description: "फ्लूइड टाइपोग्राफी के लिए मुफ्त CSS clamp() जनरेटर। न्यूनतम/अधिकतम आकार और व्यूपोर्ट चौड़ाई दर्ज करें और अपने CSS में सीधे पेस्ट करने योग्य रिस्पॉन्सिव clamp() मान पाएं।", keywords: ["css clamp जनरेटर", "फ्लूइड टाइपोग्राफी", "रिस्पॉन्सिव फॉन्ट आकार", "clamp css", "फ्लूइड टाइप कैलकुलेटर"], minSize: "न्यूनतम आकार (px)", maxSize: "अधिकतम आकार (px)", minViewport: "न्यूनतम व्यूपोर्ट (px)", maxViewport: "अधिकतम व्यूपोर्ट (px)", result: "परिणाम" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
