import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "SERP Snippet Preview", short: "Preview how your title, URL and meta description look in Google results.", description: "Free SERP snippet preview tool. See how your page title, URL and meta description appear in Google search results, with pixel-based truncation warnings. Runs entirely in your browser.", keywords: ["serp snippet preview", "google snippet preview", "seo title length", "meta description preview", "search result preview"], titleLabel: "Page title", titlePlaceholder: "Your page title", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta description", descPlaceholder: "Your meta description", preview: "Google preview", titleTruncated: "Title is too long and will be truncated.", descTruncated: "Description is too long and will be truncated." },
  nl: { title: "SERP Fragment Voorbeeld", short: "Voorbeeld how your title, URL and meta description look in Google results.", description: "Gratis SERP snippet voorbeeld tool. See how your page title, URL and meta description appear in Google zoek results, with pixel-based truncation warnings. Runs entirely in uw browser.", keywords: ["serp snippet voorbeeld", "google snippet voorbeeld", "seo title lengte", "meta description voorbeeld", "zoek result voorbeeld"], titleLabel: "Page title", titlePlaceholder: "Your page title", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta description", descPlaceholder: "Your meta description", preview: "Google voorbeeld", titleTruncated: "Title is too long and will be truncated.", descTruncated: "Description is too long and will be truncated." },

  pl: { title: "Fragment SERP Podgląd", short: "Podgląd how your title, URL and meta description look in Google results.", description: "Darmowy SERP snippet podgląd narzędzie. See how your page title, URL and meta description appear in Google szukaj results, with pixel-based truncation warnings. Runs entirely w Twojej przeglądarce.", keywords: ["serp snippet podgląd", "google snippet podgląd", "seo title długość", "meta description podgląd", "szukaj result podgląd"], titleLabel: "Page title", titlePlaceholder: "Your page title", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta description", descPlaceholder: "Your meta description", preview: "Google podgląd", titleTruncated: "Title is too long and will be truncated.", descTruncated: "Description is too long and will be truncated." },
  pt: { title: "SERP Snippet Preview", short: "Preview how your title, URL e meta description aparecem nos resultados do Google.", description: "Gratuito - serp snippet preview tool. See how your page title, URL e meta description aparecem nos resultados de busca do Google, com avisos de truncamento baseados em pixels. Runs entirely no seu navegador.", keywords: ["serp snippet preview", "google snippet preview", "seo title length", "meta description preview", "search result preview"], titleLabel: "Título da página", titlePlaceholder: "Título da sua página", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta descrição", descPlaceholder: "Sua meta descrição", preview: "Pré-visualização do Google", titleTruncated: "O título é muito longo e será cortado.", descTruncated: "A descrição é muito longa e será cortada." },
  id: { title: "SERP Snippet Preview", short: "Preview how your title, URL dan meta description tampil di hasil Google.", description: "Gratis - serp snippet preview tool. See how your page title, URL dan meta description muncul di hasil pencarian Google, dengan peringatan pemotongan berbasis piksel. Runs entirely di browser Anda.", keywords: ["serp snippet preview", "google snippet preview", "seo title length", "meta description preview", "search result preview"], titleLabel: "Judul halaman", titlePlaceholder: "Judul halaman Anda", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta deskripsi", descPlaceholder: "Meta deskripsi Anda", preview: "Pratinjau Google", titleTruncated: "Judul terlalu panjang dan akan dipotong.", descTruncated: "Deskripsi terlalu panjang dan akan dipotong." },

  tr: { title: "SERP Snippet Önizleme", short: "Başlığınızın, URL'nizin ve meta açıklamanızın Google sonuçlarında nasıl göründüğünü görün.", description: "Ücretsiz SERP snippet önizleme aracı. Sayfa başlığınızın, URL'nizin ve meta açıklamanızın Google arama sonuçlarında nasıl göründüğünü piksel tabanlı kırpma uyarılarıyla görün. Tamamen tarayıcınızda çalışır.", keywords: ["serp snippet önizleme", "google snippet önizleme", "seo başlık uzunluğu", "meta açıklama önizleme", "arama sonucu önizleme"], titleLabel: "Sayfa başlığı", titlePlaceholder: "Sayfa başlığınız", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta açıklama", descPlaceholder: "Meta açıklamanız", preview: "Google önizlemesi", titleTruncated: "Başlık çok uzun ve kırpılacak.", descTruncated: "Açıklama çok uzun ve kırpılacak." },
  de: { title: "SERP-Snippet-Vorschau", short: "Sehen Sie, wie Titel, URL und Meta-Beschreibung in Google-Ergebnissen aussehen.", description: "Kostenloses SERP-Snippet-Vorschau-Tool. Sehen Sie, wie Seitentitel, URL und Meta-Beschreibung in den Google-Suchergebnissen erscheinen – mit pixelbasierten Kürzungswarnungen. Läuft vollständig in Ihrem Browser.", keywords: ["serp snippet vorschau", "google snippet vorschau", "seo titellänge", "meta beschreibung vorschau", "suchergebnis vorschau"], titleLabel: "Seitentitel", titlePlaceholder: "Ihr Seitentitel", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta-Beschreibung", descPlaceholder: "Ihre Meta-Beschreibung", preview: "Google-Vorschau", titleTruncated: "Der Titel ist zu lang und wird gekürzt.", descTruncated: "Die Beschreibung ist zu lang und wird gekürzt." },
  fr: { title: "Aperçu de Snippet SERP", short: "Visualisez votre titre, URL et méta-description dans les résultats Google.", description: "Outil d'aperçu de snippet SERP gratuit. Visualisez l'apparence de votre titre de page, URL et méta-description dans les résultats de recherche Google, avec des avertissements de troncature basés sur les pixels. Fonctionne entièrement dans votre navigateur.", keywords: ["aperçu snippet serp", "aperçu snippet google", "longueur titre seo", "aperçu méta description", "aperçu résultat recherche"], titleLabel: "Titre de la page", titlePlaceholder: "Votre titre de page", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Méta-description", descPlaceholder: "Votre méta-description", preview: "Aperçu Google", titleTruncated: "Le titre est trop long et sera tronqué.", descTruncated: "La description est trop longue et sera tronquée." },
  es: { title: "Vista Previa de Snippet SERP", short: "Previsualiza cómo se ven tu título, URL y meta descripción en Google.", description: "Herramienta gratuita de vista previa de snippet SERP. Mira cómo aparecen el título de tu página, la URL y la meta descripción en los resultados de Google, con avisos de truncado basados en píxeles. Funciona enteramente en tu navegador.", keywords: ["vista previa snippet serp", "vista previa snippet google", "longitud título seo", "vista previa meta descripción", "vista previa resultado búsqueda"], titleLabel: "Título de la página", titlePlaceholder: "El título de tu página", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta descripción", descPlaceholder: "Tu meta descripción", preview: "Vista previa de Google", titleTruncated: "El título es demasiado largo y se truncará.", descTruncated: "La descripción es demasiado larga y se truncará." },
  it: { title: "Anteprima Snippet SERP", short: "Visualizza titolo, URL e meta descrizione come appaiono nei risultati Google.", description: "Strumento gratuito di anteprima snippet SERP. Visualizza come titolo della pagina, URL e meta descrizione appaiono nei risultati di ricerca Google, con avvisi di troncamento basati sui pixel. Funziona interamente nel tuo browser.", keywords: ["anteprima snippet serp", "anteprima snippet google", "lunghezza titolo seo", "anteprima meta descrizione", "anteprima risultato ricerca"], titleLabel: "Titolo della pagina", titlePlaceholder: "Il titolo della tua pagina", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Meta descrizione", descPlaceholder: "La tua meta descrizione", preview: "Anteprima Google", titleTruncated: "Il titolo è troppo lungo e verrà troncato.", descTruncated: "La descrizione è troppo lunga e verrà troncata." },
  ar: { title: "معاينة مقتطف SERP", short: "عاين كيف يظهر العنوان والرابط ووصف الميتا في نتائج Google.", description: "أداة معاينة مقتطف SERP مجانية. شاهد كيف يظهر عنوان صفحتك ورابطها ووصف الميتا في نتائج بحث Google، مع تحذيرات اقتطاع تعتمد على البكسل. تعمل بالكامل في متصفحك.", keywords: ["معاينة مقتطف serp", "معاينة مقتطف google", "طول عنوان seo", "معاينة وصف الميتا", "معاينة نتيجة البحث"], titleLabel: "عنوان الصفحة", titlePlaceholder: "عنوان صفحتك", urlLabel: "الرابط", urlPlaceholder: "https://example.com/page", descLabel: "وصف الميتا", descPlaceholder: "وصف الميتا الخاص بك", preview: "معاينة Google", titleTruncated: "العنوان طويل جدًا وسيُقتطع.", descTruncated: "الوصف طويل جدًا وسيُقتطع." },
  ru: { title: "Превью Сниппета SERP", short: "Посмотрите, как ваш заголовок, URL и метаописание выглядят в результатах Google.", description: "Бесплатный инструмент превью сниппета SERP. Посмотрите, как заголовок страницы, URL и метаописание отображаются в результатах поиска Google, с пиксельными предупреждениями об обрезке. Работает полностью в браузере.", keywords: ["превью сниппета serp", "превью сниппета google", "длина seo заголовка", "превью метаописания", "превью результата поиска"], titleLabel: "Заголовок страницы", titlePlaceholder: "Заголовок вашей страницы", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "Метаописание", descPlaceholder: "Ваше метаописание", preview: "Превью Google", titleTruncated: "Заголовок слишком длинный и будет обрезан.", descTruncated: "Описание слишком длинное и будет обрезано." },
  zh: { title: "SERP 摘要预览", short: "预览您的标题、URL 和元描述在 Google 结果中的显示效果。", description: "免费的 SERP 摘要预览工具。查看您的页面标题、URL 和元描述在 Google 搜索结果中的显示效果，并提供基于像素的截断提示。完全在浏览器中运行。", keywords: ["serp 摘要预览", "google 摘要预览", "seo 标题长度", "元描述预览", "搜索结果预览"], titleLabel: "页面标题", titlePlaceholder: "您的页面标题", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "元描述", descPlaceholder: "您的元描述", preview: "Google 预览", titleTruncated: "标题过长，将被截断。", descTruncated: "描述过长，将被截断。" },
  ja: { title: "SERP スニペットプレビュー", short: "タイトル・URL・メタディスクリプションが Google 結果でどう見えるかを確認。", description: "無料の SERP スニペットプレビューツール。ページタイトル・URL・メタディスクリプションが Google の検索結果でどのように表示されるかを、ピクセルベースの省略警告とともに確認できます。すべてブラウザ内で動作します。", keywords: ["serp スニペットプレビュー", "google スニペットプレビュー", "seo タイトル長", "メタディスクリプション プレビュー", "検索結果プレビュー"], titleLabel: "ページタイトル", titlePlaceholder: "ページのタイトル", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "メタディスクリプション", descPlaceholder: "メタディスクリプション", preview: "Google プレビュー", titleTruncated: "タイトルが長すぎるため省略されます。", descTruncated: "説明が長すぎるため省略されます。" },
  ko: { title: "SERP 스니펫 미리보기", short: "제목, URL, 메타 설명이 Google 결과에서 어떻게 보이는지 미리 봅니다.", description: "무료 SERP 스니펫 미리보기 도구. 페이지 제목, URL, 메타 설명이 Google 검색 결과에 어떻게 표시되는지 픽셀 기반 잘림 경고와 함께 확인하세요. 모두 브라우저에서 실행됩니다.", keywords: ["serp 스니펫 미리보기", "google 스니펫 미리보기", "seo 제목 길이", "메타 설명 미리보기", "검색 결과 미리보기"], titleLabel: "페이지 제목", titlePlaceholder: "페이지 제목", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "메타 설명", descPlaceholder: "메타 설명", preview: "Google 미리보기", titleTruncated: "제목이 너무 길어 잘립니다.", descTruncated: "설명이 너무 길어 잘립니다." },
  hi: { title: "SERP स्निपेट पूर्वावलोकन", short: "देखें कि आपका शीर्षक, URL और मेटा विवरण Google परिणामों में कैसे दिखते हैं।", description: "मुफ्त SERP स्निपेट पूर्वावलोकन टूल। देखें कि आपका पेज शीर्षक, URL और मेटा विवरण Google खोज परिणामों में कैसे दिखाई देते हैं, पिक्सेल-आधारित कटाव चेतावनियों के साथ। पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["serp स्निपेट पूर्वावलोकन", "google स्निपेट पूर्वावलोकन", "seo शीर्षक लंबाई", "मेटा विवरण पूर्वावलोकन", "खोज परिणाम पूर्वावलोकन"], titleLabel: "पेज शीर्षक", titlePlaceholder: "आपका पेज शीर्षक", urlLabel: "URL", urlPlaceholder: "https://example.com/page", descLabel: "मेटा विवरण", descPlaceholder: "आपका मेटा विवरण", preview: "Google पूर्वावलोकन", titleTruncated: "शीर्षक बहुत लंबा है और काट दिया जाएगा।", descTruncated: "विवरण बहुत लंबा है और काट दिया जाएगा।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
