import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Email Header Analyzer", short: "Trace an email's delivery path and check SPF, DKIM and DMARC results.", description: "Free email header analyzer. Paste raw email headers to trace every Received hop, see the delivery delay between servers, and check SPF, DKIM and DMARC authentication results. Runs entirely in your browser.", keywords: ["email header analyzer", "email header trace", "spf dkim dmarc check", "received headers parser", "email delivery path"], placeholder: "Paste raw email headers here…", analyze: "Analyze", hops: "Delivery hops", hop: "Hop", from: "From", by: "By", protocol: "Protocol", delay: "Delay", auth: "Authentication results", noHops: "No Received headers found.", invalid: "Could not parse the headers. Paste the full raw header block." },
  pt: { title: "Analisador de Cabeçalho de E-mail", short: "Rastreie o caminho de entrega de um e-mail e verifique SPF, DKIM e DMARC.", description: "Analisador de cabeçalho de e-mail gratuito. Cole os cabeçalhos brutos para rastrear cada salto Received, ver o atraso entre servidores e verificar os resultados de autenticação SPF, DKIM e DMARC. Roda no seu navegador.", keywords: ["email header analyzer", "email header trace", "spf dkim dmarc check", "received headers parser", "email delivery path"], placeholder: "Cole os cabeçalhos brutos do e-mail aqui…", analyze: "Analisar", hops: "Saltos de entrega", hop: "Salto", from: "De", by: "Por", protocol: "Protocolo", delay: "Atraso", auth: "Resultados de autenticação", noHops: "Nenhum cabeçalho Received encontrado.", invalid: "Não foi possível analisar os cabeçalhos. Cole o bloco completo." },
  id: { title: "Penganalisis Header Email", short: "Lacak jalur pengiriman email dan periksa hasil SPF, DKIM, dan DMARC.", description: "Penganalisis header email gratis. Tempel header email mentah untuk melacak setiap hop Received, melihat jeda pengiriman antar server, dan memeriksa hasil autentikasi SPF, DKIM, dan DMARC. Berjalan di browser Anda.", keywords: ["email header analyzer", "email header trace", "spf dkim dmarc check", "received headers parser", "email delivery path"], placeholder: "Tempel header email mentah di sini…", analyze: "Analisis", hops: "Hop pengiriman", hop: "Hop", from: "Dari", by: "Oleh", protocol: "Protokol", delay: "Jeda", auth: "Hasil autentikasi", noHops: "Tidak ada header Received ditemukan.", invalid: "Tidak dapat memproses header. Tempel seluruh blok header mentah." },

  tr: { title: "E-posta Başlığı Analizcisi", short: "Bir e-postanın teslim yolunu izleyin ve SPF, DKIM, DMARC sonuçlarını kontrol edin.", description: "Ücretsiz e-posta başlığı analizcisi. Ham e-posta başlıklarını yapıştırarak her Received atlamasını izleyin, sunucular arasındaki gecikmeyi görün ve SPF, DKIM, DMARC kimlik doğrulama sonuçlarını kontrol edin. Tamamen tarayıcınızda çalışır.", keywords: ["e-posta başlığı analizcisi", "e-posta başlığı izleme", "spf dkim dmarc kontrol", "received başlık ayrıştırıcı", "e-posta teslim yolu"], placeholder: "Ham e-posta başlıklarını buraya yapıştırın…", analyze: "Analiz Et", hops: "Teslim atlamaları", hop: "Atlama", from: "Kimden", by: "Tarafından", protocol: "Protokol", delay: "Gecikme", auth: "Kimlik doğrulama sonuçları", noHops: "Received başlığı bulunamadı.", invalid: "Başlıklar ayrıştırılamadı. Tam ham başlık bloğunu yapıştırın." },
  de: { title: "E-Mail-Header-Analyse", short: "Verfolgen Sie den Zustellweg einer E-Mail und prüfen Sie SPF, DKIM und DMARC.", description: "Kostenlose E-Mail-Header-Analyse. Fügen Sie rohe E-Mail-Header ein, um jeden Received-Hop nachzuverfolgen, die Zustellverzögerung zwischen Servern zu sehen und die SPF-, DKIM- und DMARC-Ergebnisse zu prüfen. Läuft in Ihrem Browser.", keywords: ["e-mail-header-analyse", "e-mail-header verfolgen", "spf dkim dmarc prüfen", "received header parser", "e-mail zustellweg"], placeholder: "Rohe E-Mail-Header hier einfügen…", analyze: "Analysieren", hops: "Zustell-Hops", hop: "Hop", from: "Von", by: "Über", protocol: "Protokoll", delay: "Verzögerung", auth: "Authentifizierungsergebnisse", noHops: "Keine Received-Header gefunden.", invalid: "Header konnten nicht verarbeitet werden. Fügen Sie den vollständigen Header-Block ein." },
  fr: { title: "Analyseur d'En-têtes E-mail", short: "Retracez le chemin de livraison d'un e-mail et vérifiez SPF, DKIM et DMARC.", description: "Analyseur d'en-têtes e-mail gratuit. Collez les en-têtes bruts pour retracer chaque saut Received, voir le délai de livraison entre serveurs et vérifier les résultats d'authentification SPF, DKIM et DMARC. Fonctionne dans votre navigateur.", keywords: ["analyseur d'en-têtes email", "trace en-tête email", "vérifier spf dkim dmarc", "analyseur received", "chemin de livraison email"], placeholder: "Collez les en-têtes bruts de l'e-mail ici…", analyze: "Analyser", hops: "Sauts de livraison", hop: "Saut", from: "De", by: "Par", protocol: "Protocole", delay: "Délai", auth: "Résultats d'authentification", noHops: "Aucun en-tête Received trouvé.", invalid: "Impossible d'analyser les en-têtes. Collez le bloc complet." },
  es: { title: "Analizador de Encabezados de Correo", short: "Rastrea la ruta de entrega de un correo y verifica SPF, DKIM y DMARC.", description: "Analizador de encabezados de correo gratuito. Pega los encabezados sin procesar para rastrear cada salto Received, ver el retraso de entrega entre servidores y verificar los resultados de autenticación SPF, DKIM y DMARC. Se ejecuta en tu navegador.", keywords: ["analizador de encabezados de correo", "rastrear encabezado email", "verificar spf dkim dmarc", "analizador received", "ruta de entrega de correo"], placeholder: "Pega aquí los encabezados sin procesar…", analyze: "Analizar", hops: "Saltos de entrega", hop: "Salto", from: "De", by: "Por", protocol: "Protocolo", delay: "Retraso", auth: "Resultados de autenticación", noHops: "No se encontraron encabezados Received.", invalid: "No se pudieron analizar los encabezados. Pega el bloque completo." },
  it: { title: "Analizzatore Intestazioni Email", short: "Traccia il percorso di consegna di un'email e verifica SPF, DKIM e DMARC.", description: "Analizzatore di intestazioni email gratuito. Incolla le intestazioni grezze per tracciare ogni hop Received, vedere il ritardo di consegna tra i server e verificare i risultati di autenticazione SPF, DKIM e DMARC. Funziona nel tuo browser.", keywords: ["analizzatore intestazioni email", "traccia intestazione email", "verifica spf dkim dmarc", "parser received", "percorso di consegna email"], placeholder: "Incolla qui le intestazioni grezze dell'email…", analyze: "Analizza", hops: "Hop di consegna", hop: "Hop", from: "Da", by: "Tramite", protocol: "Protocollo", delay: "Ritardo", auth: "Risultati di autenticazione", noHops: "Nessuna intestazione Received trovata.", invalid: "Impossibile analizzare le intestazioni. Incolla l'intero blocco." },
  ar: { title: "محلّل ترويسة البريد الإلكتروني", short: "تتبّع مسار تسليم البريد وتحقّق من نتائج SPF وDKIM وDMARC.", description: "محلّل ترويسة بريد إلكتروني مجاني. الصق الترويسات الخام لتتبّع كل قفزة Received، ومعرفة تأخير التسليم بين الخوادم، والتحقّق من نتائج مصادقة SPF وDKIM وDMARC. يعمل بالكامل في متصفحك.", keywords: ["محلل ترويسة البريد", "تتبع ترويسة البريد", "فحص spf dkim dmarc", "محلل received", "مسار تسليم البريد"], placeholder: "الصق ترويسات البريد الخام هنا…", analyze: "تحليل", hops: "قفزات التسليم", hop: "قفزة", from: "من", by: "عبر", protocol: "البروتوكول", delay: "التأخير", auth: "نتائج المصادقة", noHops: "لم يتم العثور على ترويسات Received.", invalid: "تعذّر تحليل الترويسات. الصق كتلة الترويسة الخام كاملة." },
  ru: { title: "Анализатор Заголовков Письма", short: "Проследите путь доставки письма и проверьте результаты SPF, DKIM и DMARC.", description: "Бесплатный анализатор заголовков письма. Вставьте сырые заголовки, чтобы проследить каждый переход Received, увидеть задержку доставки между серверами и проверить результаты аутентификации SPF, DKIM и DMARC. Работает в браузере.", keywords: ["анализатор заголовков письма", "трассировка заголовков", "проверка spf dkim dmarc", "парсер received", "путь доставки письма"], placeholder: "Вставьте сюда сырые заголовки письма…", analyze: "Анализировать", hops: "Переходы доставки", hop: "Переход", from: "От", by: "Через", protocol: "Протокол", delay: "Задержка", auth: "Результаты аутентификации", noHops: "Заголовки Received не найдены.", invalid: "Не удалось разобрать заголовки. Вставьте полный блок заголовков." },
  zh: { title: "邮件头分析器", short: "追踪邮件的投递路径并检查 SPF、DKIM 和 DMARC 结果。", description: "免费的邮件头分析器。粘贴原始邮件头即可追踪每个 Received 跳转、查看服务器之间的投递延迟，并检查 SPF、DKIM 和 DMARC 认证结果。完全在浏览器中运行。", keywords: ["邮件头分析器", "邮件头追踪", "spf dkim dmarc 检查", "received 解析", "邮件投递路径"], placeholder: "在此粘贴原始邮件头…", analyze: "分析", hops: "投递跳转", hop: "跳转", from: "来自", by: "经由", protocol: "协议", delay: "延迟", auth: "认证结果", noHops: "未找到 Received 头。", invalid: "无法解析邮件头。请粘贴完整的原始头部块。" },
  ja: { title: "メールヘッダー解析ツール", short: "メールの配信経路を追跡し、SPF・DKIM・DMARC の結果を確認します。", description: "無料のメールヘッダー解析ツール。生のメールヘッダーを貼り付けると、各 Received ホップを追跡し、サーバー間の配信遅延を確認し、SPF・DKIM・DMARC の認証結果をチェックできます。すべてブラウザ内で動作します。", keywords: ["メールヘッダー解析", "メールヘッダー追跡", "spf dkim dmarc チェック", "received パーサー", "メール配信経路"], placeholder: "生のメールヘッダーをここに貼り付け…", analyze: "解析", hops: "配信ホップ", hop: "ホップ", from: "送信元", by: "経由", protocol: "プロトコル", delay: "遅延", auth: "認証結果", noHops: "Received ヘッダーが見つかりません。", invalid: "ヘッダーを解析できませんでした。生のヘッダーブロック全体を貼り付けてください。" },
  ko: { title: "이메일 헤더 분석기", short: "이메일의 전달 경로를 추적하고 SPF, DKIM, DMARC 결과를 확인합니다.", description: "무료 이메일 헤더 분석기. 원본 이메일 헤더를 붙여넣으면 각 Received 홉을 추적하고, 서버 간 전달 지연을 확인하며, SPF, DKIM, DMARC 인증 결과를 점검할 수 있습니다. 브라우저에서 실행됩니다.", keywords: ["이메일 헤더 분석기", "이메일 헤더 추적", "spf dkim dmarc 확인", "received 파서", "이메일 전달 경로"], placeholder: "원본 이메일 헤더를 여기에 붙여넣으세요…", analyze: "분석", hops: "전달 홉", hop: "홉", from: "보낸 곳", by: "경유", protocol: "프로토콜", delay: "지연", auth: "인증 결과", noHops: "Received 헤더를 찾을 수 없습니다.", invalid: "헤더를 분석할 수 없습니다. 전체 원본 헤더 블록을 붙여넣으세요." },
  hi: { title: "ईमेल हेडर विश्लेषक", short: "ईमेल का डिलीवरी पथ ट्रेस करें और SPF, DKIM, DMARC परिणाम जांचें।", description: "मुफ्त ईमेल हेडर विश्लेषक। कच्चे ईमेल हेडर पेस्ट करें ताकि हर Received हॉप को ट्रेस कर सकें, सर्वर के बीच डिलीवरी देरी देख सकें, और SPF, DKIM, DMARC प्रमाणीकरण परिणाम जांच सकें। पूरी तरह ब्राउज़र में चलता है।", keywords: ["ईमेल हेडर विश्लेषक", "ईमेल हेडर ट्रेस", "spf dkim dmarc जांच", "received पार्सर", "ईमेल डिलीवरी पथ"], placeholder: "कच्चे ईमेल हेडर यहां पेस्ट करें…", analyze: "विश्लेषण करें", hops: "डिलीवरी हॉप", hop: "हॉप", from: "से", by: "द्वारा", protocol: "प्रोटोकॉल", delay: "देरी", auth: "प्रमाणीकरण परिणाम", noHops: "कोई Received हेडर नहीं मिला।", invalid: "हेडर पार्स नहीं हो सके। पूरा कच्चा हेडर ब्लॉक पेस्ट करें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
