import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Random String Generator", short: "Generate random strings or tokens with chosen length and character sets.", description: "Free random string generator. Create random strings, tokens or nonces of any length from lowercase, uppercase, numbers and symbols. Generate many at once. Uses the Web Crypto API.", keywords: ["random string generator", "random token", "nonce generator", "random text", "random id generator"], length: "Length", count: "How many", lowercase: "Lowercase (a–z)", uppercase: "Uppercase (A–Z)", numbers: "Numbers (0–9)", symbols: "Symbols", generate: "Generate", selectOne: "Select at least one character set." },
  tr: { title: "Rastgele Dize Üretici", short: "Seçtiğiniz uzunluk ve karakter kümeleriyle rastgele dizeler veya token'lar üretin.", description: "Ücretsiz rastgele dize üretici. Küçük harf, büyük harf, rakam ve sembollerden istediğiniz uzunlukta rastgele dizeler, token'lar veya nonce'lar oluşturun. Aynı anda birçok üretin. Web Crypto API kullanır.", keywords: ["rastgele dize üretici", "rastgele token", "nonce üretici", "rastgele metin", "rastgele kimlik"], length: "Uzunluk", count: "Adet", lowercase: "Küçük harf (a–z)", uppercase: "Büyük harf (A–Z)", numbers: "Rakamlar (0–9)", symbols: "Semboller", generate: "Üret", selectOne: "En az bir karakter kümesi seçin." },
  de: { title: "Zufalls-String-Generator", short: "Erzeugen Sie zufällige Strings oder Token mit Länge und Zeichensätzen Ihrer Wahl.", description: "Kostenloser Zufalls-String-Generator. Erstellen Sie zufällige Strings, Token oder Nonces beliebiger Länge aus Klein-, Großbuchstaben, Zahlen und Symbolen. Viele auf einmal. Nutzt die Web Crypto API.", keywords: ["zufalls-string-generator", "zufälliges token", "nonce generator", "zufallstext", "zufällige id"], length: "Länge", count: "Anzahl", lowercase: "Kleinbuchstaben (a–z)", uppercase: "Großbuchstaben (A–Z)", numbers: "Ziffern (0–9)", symbols: "Symbole", generate: "Erzeugen", selectOne: "Mindestens einen Zeichensatz wählen." },
  fr: { title: "Générateur de Chaîne Aléatoire", short: "Générez des chaînes ou jetons aléatoires avec la longueur et les jeux de caractères choisis.", description: "Générateur de chaîne aléatoire gratuit. Créez des chaînes, jetons ou nonces aléatoires de toute longueur à partir de minuscules, majuscules, chiffres et symboles. Plusieurs à la fois. Utilise la Web Crypto API.", keywords: ["générateur de chaîne aléatoire", "jeton aléatoire", "générateur de nonce", "texte aléatoire", "id aléatoire"], length: "Longueur", count: "Combien", lowercase: "Minuscules (a–z)", uppercase: "Majuscules (A–Z)", numbers: "Chiffres (0–9)", symbols: "Symboles", generate: "Générer", selectOne: "Sélectionnez au moins un jeu de caractères." },
  es: { title: "Generador de Cadenas Aleatorias", short: "Genera cadenas o tokens aleatorios con la longitud y los conjuntos de caracteres elegidos.", description: "Generador de cadenas aleatorias gratuito. Crea cadenas, tokens o nonces aleatorios de cualquier longitud a partir de minúsculas, mayúsculas, números y símbolos. Varios a la vez. Usa la Web Crypto API.", keywords: ["generador de cadenas aleatorias", "token aleatorio", "generador de nonce", "texto aleatorio", "id aleatorio"], length: "Longitud", count: "Cuántos", lowercase: "Minúsculas (a–z)", uppercase: "Mayúsculas (A–Z)", numbers: "Números (0–9)", symbols: "Símbolos", generate: "Generar", selectOne: "Selecciona al menos un conjunto de caracteres." },
  it: { title: "Generatore di Stringhe Casuali", short: "Genera stringhe o token casuali con lunghezza e set di caratteri scelti.", description: "Generatore di stringhe casuali gratuito. Crea stringhe, token o nonce casuali di qualsiasi lunghezza da minuscole, maiuscole, numeri e simboli. Molti in una volta. Usa la Web Crypto API.", keywords: ["generatore di stringhe casuali", "token casuale", "generatore di nonce", "testo casuale", "id casuale"], length: "Lunghezza", count: "Quanti", lowercase: "Minuscole (a–z)", uppercase: "Maiuscole (A–Z)", numbers: "Numeri (0–9)", symbols: "Simboli", generate: "Genera", selectOne: "Seleziona almeno un set di caratteri." },
  ar: { title: "مولّد سلاسل عشوائية", short: "أنشئ سلاسل أو رموزًا عشوائية بطول ومجموعات أحرف من اختيارك.", description: "مولّد سلاسل عشوائية مجاني. أنشئ سلاسل أو رموزًا أو nonces عشوائية بأي طول من الأحرف الصغيرة والكبيرة والأرقام والرموز. أنشئ الكثير دفعة واحدة. يستخدم Web Crypto API.", keywords: ["مولد سلاسل عشوائية", "رمز عشوائي", "مولد nonce", "نص عشوائي", "معرف عشوائي"], length: "الطول", count: "العدد", lowercase: "أحرف صغيرة (a–z)", uppercase: "أحرف كبيرة (A–Z)", numbers: "أرقام (0–9)", symbols: "رموز", generate: "توليد", selectOne: "اختر مجموعة أحرف واحدة على الأقل." },
  ru: { title: "Генератор Случайных Строк", short: "Генерируйте случайные строки или токены с заданной длиной и наборами символов.", description: "Бесплатный генератор случайных строк. Создавайте случайные строки, токены или nonce любой длины из строчных, прописных, цифр и символов. Сразу много. Использует Web Crypto API.", keywords: ["генератор случайных строк", "случайный токен", "генератор nonce", "случайный текст", "случайный id"], length: "Длина", count: "Количество", lowercase: "Строчные (a–z)", uppercase: "Прописные (A–Z)", numbers: "Цифры (0–9)", symbols: "Символы", generate: "Сгенерировать", selectOne: "Выберите хотя бы один набор символов." },
  zh: { title: "随机字符串生成器", short: "按选定的长度和字符集生成随机字符串或令牌。", description: "免费的随机字符串生成器。从小写、大写、数字和符号中生成任意长度的随机字符串、令牌或 nonce，可一次生成多个。使用 Web Crypto API。", keywords: ["随机字符串生成器", "随机令牌", "nonce生成器", "随机文本", "随机id"], length: "长度", count: "数量", lowercase: "小写 (a–z)", uppercase: "大写 (A–Z)", numbers: "数字 (0–9)", symbols: "符号", generate: "生成", selectOne: "请至少选择一个字符集。" },
  ja: { title: "ランダム文字列ジェネレーター", short: "選んだ長さと文字セットでランダムな文字列やトークンを生成します。", description: "無料のランダム文字列ジェネレーター。小文字・大文字・数字・記号から任意の長さのランダム文字列、トークン、nonce を生成。一度に複数生成可能。Web Crypto API を使用します。", keywords: ["ランダム文字列 生成", "ランダムトークン", "nonce 生成", "ランダムテキスト", "ランダム id"], length: "長さ", count: "個数", lowercase: "小文字 (a–z)", uppercase: "大文字 (A–Z)", numbers: "数字 (0–9)", symbols: "記号", generate: "生成", selectOne: "少なくとも1つの文字セットを選択してください。" },
  ko: { title: "랜덤 문자열 생성기", short: "선택한 길이와 문자 집합으로 랜덤 문자열이나 토큰을 생성합니다.", description: "무료 랜덤 문자열 생성기. 소문자, 대문자, 숫자, 기호로 임의 길이의 랜덤 문자열, 토큰 또는 nonce를 생성하며 한 번에 여러 개 생성할 수 있습니다. Web Crypto API를 사용합니다.", keywords: ["랜덤 문자열 생성기", "랜덤 토큰", "nonce 생성기", "랜덤 텍스트", "랜덤 id"], length: "길이", count: "개수", lowercase: "소문자 (a–z)", uppercase: "대문자 (A–Z)", numbers: "숫자 (0–9)", symbols: "기호", generate: "생성", selectOne: "문자 집합을 하나 이상 선택하세요." },
  hi: { title: "रैंडम स्ट्रिंग जनरेटर", short: "चुनी हुई लंबाई और वर्ण सेट के साथ रैंडम स्ट्रिंग या टोकन बनाएं।", description: "मुफ्त रैंडम स्ट्रिंग जनरेटर। लोअरकेस, अपरकेस, संख्या और प्रतीकों से किसी भी लंबाई की रैंडम स्ट्रिंग, टोकन या nonce बनाएं। एक साथ कई बनाएं। Web Crypto API का उपयोग करता है।", keywords: ["रैंडम स्ट्रिंग जनरेटर", "रैंडम टोकन", "nonce जनरेटर", "रैंडम टेक्स्ट", "रैंडम id"], length: "लंबाई", count: "कितने", lowercase: "लोअरकेस (a–z)", uppercase: "अपरकेस (A–Z)", numbers: "संख्याएँ (0–9)", symbols: "प्रतीक", generate: "बनाएं", selectOne: "कम से कम एक वर्ण सेट चुनें।" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
