import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "NATO Phonetic Alphabet Converter", short: "Spell text using the NATO phonetic alphabet (Alfa, Bravo, Charlie…).", description: "Free NATO phonetic alphabet converter. Turn any text into its spelling alphabet equivalent — Alfa, Bravo, Charlie — so names, codes and passwords can be read aloud without confusion.", keywords: ["nato phonetic alphabet", "phonetic spelling", "alfa bravo charlie", "spelling alphabet", "military alphabet converter"], placeholder: "Enter text to spell out…" },
  pt: { title: "Conversor de NATO Phonetic Alphabet", short: "Spell text usando the NATO phonetic alphabet (Alfa, Bravo, Charlieâ¦).", description: "Gratuito - NATO phonetic alphabet converter. Turn any text into its spelling alphabet equivalent â Alfa, Bravo, Charlie â so names, codes e passwords can be read aloud without confusion.", keywords: ["nato phonetic alphabet", "phonetic spelling", "alfa bravo charlie", "spelling alphabet", "military alphabet converter"], placeholder: "Enter text to spell out…" },
  id: { title: "Konverter NATO Phonetic Alphabet", short: "Spell text menggunakan the NATO phonetic alphabet (Alfa, Bravo, Charlieâ¦).", description: "Gratis - NATO phonetic alphabet converter. Turn any text into its spelling alphabet equivalent â Alfa, Bravo, Charlie â so names, codes dan passwords can be read aloud without confusion.", keywords: ["nato phonetic alphabet", "phonetic spelling", "alfa bravo charlie", "spelling alphabet", "military alphabet converter"], placeholder: "Enter text to spell out…" },

  tr: { title: "NATO Fonetik Alfabe Dönüştürücü", short: "Metni NATO fonetik alfabesiyle hecele (Alfa, Bravo, Charlie…).", description: "Ücretsiz NATO fonetik alfabe dönüştürücü. Herhangi bir metni heceleme alfabesi karşılığına çevirin — Alfa, Bravo, Charlie — böylece isimler, kodlar ve şifreler karışıklık olmadan sesli okunabilir.", keywords: ["nato fonetik alfabe", "fonetik heceleme", "alfa bravo charlie", "heceleme alfabesi", "askeri alfabe"], placeholder: "Hecelenecek metni girin…" },
  de: { title: "NATO-Buchstabieralphabet-Konverter", short: "Buchstabieren Sie Text mit dem NATO-Alphabet (Alfa, Bravo, Charlie…).", description: "Kostenloser NATO-Buchstabieralphabet-Konverter. Wandeln Sie Text in das Buchstabieralphabet um — Alfa, Bravo, Charlie — damit Namen, Codes und Passwörter ohne Verwechslung vorgelesen werden können.", keywords: ["nato alphabet", "buchstabieralphabet", "alfa bravo charlie", "funkalphabet"], placeholder: "Text zum Buchstabieren eingeben…" },
  fr: { title: "Convertisseur d'Alphabet Phonétique OTAN", short: "Épelez du texte avec l'alphabet phonétique OTAN (Alfa, Bravo, Charlie…).", description: "Convertisseur d'alphabet phonétique OTAN gratuit. Transformez n'importe quel texte en son équivalent d'épellation — Alfa, Bravo, Charlie — pour lire noms, codes et mots de passe à voix haute sans confusion.", keywords: ["alphabet phonétique otan", "épellation phonétique", "alfa bravo charlie", "alphabet radio"], placeholder: "Saisissez le texte à épeler…" },
  es: { title: "Conversor del Alfabeto Fonético OTAN", short: "Deletrea texto con el alfabeto fonético OTAN (Alfa, Bravo, Charlie…).", description: "Conversor del alfabeto fonético OTAN gratuito. Convierte cualquier texto en su equivalente de deletreo — Alfa, Bravo, Charlie — para leer nombres, códigos y contraseñas en voz alta sin confusión.", keywords: ["alfabeto fonético otan", "deletreo fonético", "alfa bravo charlie", "alfabeto radiofónico"], placeholder: "Introduce el texto a deletrear…" },
  it: { title: "Convertitore Alfabeto Fonetico NATO", short: "Compita il testo con l'alfabeto fonetico NATO (Alfa, Bravo, Charlie…).", description: "Convertitore dell'alfabeto fonetico NATO gratuito. Trasforma qualsiasi testo nel suo equivalente di compitazione — Alfa, Bravo, Charlie — per leggere nomi, codici e password ad alta voce senza confusione.", keywords: ["alfabeto fonetico nato", "compitazione fonetica", "alfa bravo charlie", "alfabeto radio"], placeholder: "Inserisci il testo da compitare…" },
  ar: { title: "محوّل أبجدية الناتو الصوتية", short: "تهجّ النص باستخدام أبجدية الناتو الصوتية (Alfa، Bravo، Charlie…).", description: "محوّل أبجدية الناتو الصوتية مجاني. حوّل أي نص إلى مكافئه في أبجدية التهجئة — Alfa، Bravo، Charlie — حتى يمكن قراءة الأسماء والرموز وكلمات المرور بصوت عالٍ دون لبس.", keywords: ["أبجدية الناتو الصوتية", "تهجئة صوتية", "alfa bravo charlie", "أبجدية الراديو"], placeholder: "أدخل النص المراد تهجئته…" },
  ru: { title: "Конвертер Фонетического Алфавита НАТО", short: "Произносите текст по фонетическому алфавиту НАТО (Alfa, Bravo, Charlie…).", description: "Бесплатный конвертер фонетического алфавита НАТО. Преобразуйте любой текст в его эквивалент для произношения по буквам — Alfa, Bravo, Charlie — чтобы имена, коды и пароли можно было прочитать вслух без путаницы.", keywords: ["фонетический алфавит нато", "произношение по буквам", "alfa bravo charlie", "радиоалфавит"], placeholder: "Введите текст для произношения…" },
  zh: { title: "北约音标字母转换器", short: "使用北约音标字母拼读文本（Alfa、Bravo、Charlie…）。", description: "免费的北约音标字母转换器。将任意文本转换为其拼读字母对应形式——Alfa、Bravo、Charlie——以便清晰无误地朗读姓名、代码和密码。", keywords: ["北约音标字母", "音标拼读", "alfa bravo charlie", "无线电字母表"], placeholder: "输入要拼读的文本…" },
  ja: { title: "NATO フォネティックコード変換", short: "NATO フォネティックコードでテキストを綴ります（Alfa, Bravo, Charlie…）。", description: "無料の NATO フォネティックコード変換ツール。任意のテキストを綴り字アルファベット（Alfa, Bravo, Charlie）に変換し、名前・コード・パスワードを混乱なく読み上げられます。", keywords: ["nato フォネティックコード", "フォネティックコード", "alfa bravo charlie", "通話表"], placeholder: "綴るテキストを入力…" },
  ko: { title: "NATO 음성 알파벳 변환기", short: "NATO 음성 알파벳으로 텍스트를 철자합니다(Alfa, Bravo, Charlie…).", description: "무료 NATO 음성 알파벳 변환기. 임의의 텍스트를 철자 알파벳(Alfa, Bravo, Charlie)으로 변환하여 이름, 코드, 비밀번호를 혼동 없이 소리내어 읽을 수 있습니다.", keywords: ["nato 음성 알파벳", "음성 철자", "alfa bravo charlie", "무선 알파벳"], placeholder: "철자할 텍스트 입력…" },
  hi: { title: "NATO ध्वन्यात्मक वर्णमाला कन्वर्टर", short: "NATO ध्वन्यात्मक वर्णमाला से टेक्स्ट की वर्तनी करें (Alfa, Bravo, Charlie…)।", description: "मुफ्त NATO ध्वन्यात्मक वर्णमाला कन्वर्टर। किसी भी टेक्स्ट को उसकी वर्तनी वर्णमाला समकक्ष में बदलें — Alfa, Bravo, Charlie — ताकि नाम, कोड और पासवर्ड बिना भ्रम के बोलकर पढ़े जा सकें।", keywords: ["nato ध्वन्यात्मक वर्णमाला", "ध्वन्यात्मक वर्तनी", "alfa bravo charlie", "रेडियो वर्णमाला"], placeholder: "वर्तनी के लिए टेक्स्ट दर्ज करें…" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
