import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Color Converter — HEX, RGB, HSL", short: "Convert colors between HEX, RGB and HSL and preview the result.", description: "Free color converter. Enter a color as HEX, rgb() or hsl() and instantly get all three formats plus a live preview swatch. Useful for web design and CSS.", keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "hex rgb hsl", "css color"], placeholder: "#3b82f6, rgb(59,130,246) or hsl(217,91%,60%)…", invalid: "Enter a valid HEX, RGB or HSL color.", preview: "Preview" },
  pt: { title: "Color Converter â HEX, RGB, HSL", short: "Converter colors entre HEX, RGB e HSL e preview the result.", description: "Gratuito - color converter. Enter a color as HEX, rgb() ou hsl() e instantaneamente get all three formats plus a live preview swatch. Useful para web design e CSS.", keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "hex rgb hsl", "css color"], placeholder: "#3b82f6, rgb(59,130,246) or hsl(217,91%,60%)…", invalid: "Enter a valid HEX, RGB or HSL color.", preview: "Preview" },
  id: { title: "Color Converter â HEX, RGB, HSL", short: "Konversi colors antara HEX, RGB dan HSL dan preview the result.", description: "Gratis - color converter. Enter a color as HEX, rgb() atau hsl() dan secara instan get all three formats plus a live preview swatch. Useful for web design dan CSS.", keywords: ["color converter", "hex to rgb", "rgb to hex", "hsl converter", "hex rgb hsl", "css color"], placeholder: "#3b82f6, rgb(59,130,246) or hsl(217,91%,60%)…", invalid: "Enter a valid HEX, RGB or HSL color.", preview: "Preview" },

  tr: { title: "Renk Dönüştürücü — HEX, RGB, HSL", short: "Renkleri HEX, RGB ve HSL arasında dönüştürün ve sonucu önizleyin.", description: "Ücretsiz renk dönüştürücü. Bir rengi HEX, rgb() veya hsl() olarak girin; üç biçimi de canlı önizleme örneğiyle birlikte anında alın. Web tasarımı ve CSS için kullanışlıdır.", keywords: ["renk dönüştürücü", "hex to rgb", "rgb to hex", "hsl dönüştürücü", "hex rgb hsl", "css renk"], placeholder: "#3b82f6, rgb(59,130,246) veya hsl(217,91%,60%)…", invalid: "Geçerli bir HEX, RGB veya HSL rengi girin.", preview: "Önizleme" },
  de: { title: "Farbkonverter — HEX, RGB, HSL", short: "Farben zwischen HEX, RGB und HSL umwandeln und das Ergebnis ansehen.", description: "Kostenloser Farbkonverter. Geben Sie eine Farbe als HEX, rgb() oder hsl() ein und erhalten Sie sofort alle drei Formate plus eine Live-Vorschau. Nützlich für Webdesign und CSS.", keywords: ["farbkonverter", "hex zu rgb", "rgb zu hex", "hsl konverter", "css farbe"], placeholder: "#3b82f6, rgb(59,130,246) oder hsl(217,91%,60%)…", invalid: "Gültige HEX-, RGB- oder HSL-Farbe eingeben.", preview: "Vorschau" },
  fr: { title: "Convertisseur de Couleurs — HEX, RGB, HSL", short: "Convertissez les couleurs entre HEX, RGB et HSL et prévisualisez le résultat.", description: "Convertisseur de couleurs gratuit. Saisissez une couleur en HEX, rgb() ou hsl() et obtenez instantanément les trois formats avec un aperçu en direct. Utile pour le web design et le CSS.", keywords: ["convertisseur de couleurs", "hex vers rgb", "rgb vers hex", "convertisseur hsl", "couleur css"], placeholder: "#3b82f6, rgb(59,130,246) ou hsl(217,91%,60%)…", invalid: "Saisissez une couleur HEX, RGB ou HSL valide.", preview: "Aperçu" },
  es: { title: "Conversor de Colores — HEX, RGB, HSL", short: "Convierte colores entre HEX, RGB y HSL y previsualiza el resultado.", description: "Conversor de colores gratuito. Introduce un color en HEX, rgb() o hsl() y obtén al instante los tres formatos más una vista previa en vivo. Útil para diseño web y CSS.", keywords: ["conversor de colores", "hex a rgb", "rgb a hex", "conversor hsl", "color css"], placeholder: "#3b82f6, rgb(59,130,246) o hsl(217,91%,60%)…", invalid: "Introduce un color HEX, RGB o HSL válido.", preview: "Vista previa" },
  it: { title: "Convertitore di Colori — HEX, RGB, HSL", short: "Converti i colori tra HEX, RGB e HSL e visualizza l'anteprima.", description: "Convertitore di colori gratuito. Inserisci un colore in HEX, rgb() o hsl() e ottieni all'istante tutti e tre i formati più un'anteprima dal vivo. Utile per web design e CSS.", keywords: ["convertitore di colori", "hex in rgb", "rgb in hex", "convertitore hsl", "colore css"], placeholder: "#3b82f6, rgb(59,130,246) o hsl(217,91%,60%)…", invalid: "Inserisci un colore HEX, RGB o HSL valido.", preview: "Anteprima" },
  ar: { title: "محوّل الألوان — HEX و RGB و HSL", short: "حوّل الألوان بين HEX و RGB و HSL وعاين النتيجة.", description: "محوّل ألوان مجاني. أدخل لونًا بصيغة HEX أو rgb() أو hsl() واحصل فورًا على الصيغ الثلاث مع معاينة حية. مفيد لتصميم الويب وCSS.", keywords: ["محول الألوان", "hex إلى rgb", "rgb إلى hex", "محول hsl", "لون css"], placeholder: "#3b82f6 أو rgb(59,130,246) أو hsl(217,91%,60%)…", invalid: "أدخل لون HEX أو RGB أو HSL صالحًا.", preview: "معاينة" },
  ru: { title: "Конвертер Цветов — HEX, RGB, HSL", short: "Конвертируйте цвета между HEX, RGB и HSL с предпросмотром.", description: "Бесплатный конвертер цветов. Введите цвет как HEX, rgb() или hsl() и сразу получите все три формата плюс живой образец. Полезно для веб-дизайна и CSS.", keywords: ["конвертер цветов", "hex в rgb", "rgb в hex", "конвертер hsl", "css цвет"], placeholder: "#3b82f6, rgb(59,130,246) или hsl(217,91%,60%)…", invalid: "Введите корректный цвет HEX, RGB или HSL.", preview: "Предпросмотр" },
  zh: { title: "颜色转换器 — HEX、RGB、HSL", short: "在 HEX、RGB 和 HSL 之间转换颜色并预览结果。", description: "免费的颜色转换器。以 HEX、rgb() 或 hsl() 输入颜色，即可立即获得三种格式以及实时预览色块。适用于网页设计和 CSS。", keywords: ["颜色转换器", "hex转rgb", "rgb转hex", "hsl转换", "css颜色"], placeholder: "#3b82f6、rgb(59,130,246) 或 hsl(217,91%,60%)…", invalid: "请输入有效的 HEX、RGB 或 HSL 颜色。", preview: "预览" },
  ja: { title: "カラーコンバーター — HEX・RGB・HSL", short: "色を HEX・RGB・HSL 間で変換し、結果をプレビューします。", description: "無料のカラーコンバーター。色を HEX・rgb()・hsl() で入力すると、3 形式すべてとライブプレビューが即座に得られます。Web デザインや CSS に便利です。", keywords: ["カラーコンバーター", "hexからrgb", "rgbからhex", "hsl変換", "css色"], placeholder: "#3b82f6、rgb(59,130,246) または hsl(217,91%,60%)…", invalid: "有効な HEX・RGB・HSL の色を入力してください。", preview: "プレビュー" },
  ko: { title: "색상 변환기 — HEX, RGB, HSL", short: "HEX, RGB, HSL 간에 색상을 변환하고 결과를 미리 봅니다.", description: "무료 색상 변환기. 색상을 HEX, rgb() 또는 hsl()로 입력하면 세 가지 형식과 라이브 미리보기를 즉시 얻을 수 있습니다. 웹 디자인과 CSS에 유용합니다.", keywords: ["색상 변환기", "hex를 rgb로", "rgb를 hex로", "hsl 변환", "css 색상"], placeholder: "#3b82f6, rgb(59,130,246) 또는 hsl(217,91%,60%)…", invalid: "유효한 HEX, RGB 또는 HSL 색상을 입력하세요.", preview: "미리보기" },
  hi: { title: "रंग कन्वर्टर — HEX, RGB, HSL", short: "रंगों को HEX, RGB और HSL के बीच बदलें और परिणाम का पूर्वावलोकन करें।", description: "मुफ्त रंग कन्वर्टर। रंग को HEX, rgb() या hsl() के रूप में दर्ज करें और तीनों प्रारूप तथा लाइव प्रीव्यू तुरंत पाएं। वेब डिज़ाइन और CSS के लिए उपयोगी।", keywords: ["रंग कन्वर्टर", "hex से rgb", "rgb से hex", "hsl कन्वर्टर", "css रंग"], placeholder: "#3b82f6, rgb(59,130,246) या hsl(217,91%,60%)…", invalid: "मान्य HEX, RGB या HSL रंग दर्ज करें।", preview: "पूर्वावलोकन" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
