import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Dice Roller", short: "Roll any number of dice with any number of sides.", description: "Free online dice roller. Roll one or many dice with any number of sides (d6, d20, or custom) and see each result, the total and the average. Uses the Web Crypto API for fair rolls.", keywords: ["dice roller", "roll dice online", "d20 roller", "virtual dice", "random dice"], count: "Number of dice", sides: "Sides per die", roll: "Roll", sum: "Sum", average: "Average" },
  pt: { title: "Lançador de Dados", short: "Roll any number de dice com any number de sides.", description: "Gratuito - online dice roller. Roll one ou many dice com any number de sides (d6, d20, ou custom) e see each result, the total e the average. Uses the Web Crypto API para fair rolls.", keywords: ["dice roller", "roll dice online", "d20 roller", "virtual dice", "random dice"], count: "Number of dice", sides: "Sides per die", roll: "Roll", sum: "Sum", average: "Average" },
  id: { title: "Pelempar Dadu", short: "Roll any number dari dice with any number dari sides.", description: "Gratis - online dice roller. Roll one atau many dice with any number dari sides (d6, d20, atau custom) dan see each result, the total dan the average. Uses the Web Crypto API for fair rolls.", keywords: ["dice roller", "roll dice online", "d20 roller", "virtual dice", "random dice"], count: "Number of dice", sides: "Sides per die", roll: "Roll", sum: "Sum", average: "Average" },

  tr: { title: "Zar Atıcı", short: "İstediğiniz kadar, istediğiniz yüz sayısıyla zar atın.", description: "Ücretsiz çevrimiçi zar atıcı. Bir veya birçok zarı istediğiniz yüz sayısıyla (d6, d20 veya özel) atın; her sonucu, toplamı ve ortalamayı görün. Adil atışlar için Web Crypto API kullanır.", keywords: ["zar atıcı", "çevrimiçi zar at", "d20 zar", "sanal zar", "rastgele zar"], count: "Zar sayısı", sides: "Yüz sayısı", roll: "At", sum: "Toplam", average: "Ortalama" },
  de: { title: "Würfel-Roller", short: "Würfeln Sie beliebig viele Würfel mit beliebig vielen Seiten.", description: "Kostenloser Online-Würfel-Roller. Würfeln Sie einen oder viele Würfel mit beliebigen Seiten (W6, W20 oder benutzerdefiniert) und sehen Sie jedes Ergebnis, die Summe und den Durchschnitt.", keywords: ["würfel roller", "online würfeln", "w20 würfel", "virtuelle würfel", "zufallswürfel"], count: "Anzahl Würfel", sides: "Seiten pro Würfel", roll: "Würfeln", sum: "Summe", average: "Durchschnitt" },
  fr: { title: "Lanceur de Dés", short: "Lancez autant de dés que vous voulez, avec n'importe quel nombre de faces.", description: "Lanceur de dés en ligne gratuit. Lancez un ou plusieurs dés avec n'importe quel nombre de faces (d6, d20 ou personnalisé) et voyez chaque résultat, le total et la moyenne.", keywords: ["lanceur de dés", "lancer des dés en ligne", "dé d20", "dés virtuels", "dés aléatoires"], count: "Nombre de dés", sides: "Faces par dé", roll: "Lancer", sum: "Somme", average: "Moyenne" },
  es: { title: "Lanzador de Dados", short: "Lanza cualquier número de dados con cualquier número de caras.", description: "Lanzador de dados en línea gratuito. Lanza uno o varios dados con cualquier número de caras (d6, d20 o personalizado) y ve cada resultado, el total y el promedio.", keywords: ["lanzador de dados", "tirar dados en línea", "dado d20", "dados virtuales", "dados aleatorios"], count: "Número de dados", sides: "Caras por dado", roll: "Lanzar", sum: "Suma", average: "Promedio" },
  it: { title: "Lanciatore di Dadi", short: "Lancia un numero qualsiasi di dadi con un numero qualsiasi di facce.", description: "Lanciatore di dadi online gratuito. Lancia uno o più dadi con qualsiasi numero di facce (d6, d20 o personalizzato) e vedi ogni risultato, il totale e la media.", keywords: ["lanciatore di dadi", "tirare dadi online", "dado d20", "dadi virtuali", "dadi casuali"], count: "Numero di dadi", sides: "Facce per dado", roll: "Lancia", sum: "Somma", average: "Media" },
  ar: { title: "رامي النرد", short: "ارمِ أي عدد من النرد بأي عدد من الأوجه.", description: "رامي نرد مجاني عبر الإنترنت. ارمِ نردًا واحدًا أو عدة نردات بأي عدد من الأوجه (d6 أو d20 أو مخصص) وشاهد كل نتيجة والمجموع والمتوسط. يستخدم Web Crypto API لرميات عادلة.", keywords: ["رامي النرد", "رمي النرد عبر الإنترنت", "نرد d20", "نرد افتراضي", "نرد عشوائي"], count: "عدد النرد", sides: "أوجه كل نرد", roll: "ارمِ", sum: "المجموع", average: "المتوسط" },
  ru: { title: "Бросок Костей", short: "Бросайте любое число костей с любым числом граней.", description: "Бесплатный онлайн-бросок костей. Бросайте одну или много костей с любым числом граней (d6, d20 или своё) и смотрите каждый результат, сумму и среднее. Использует Web Crypto API.", keywords: ["бросок костей", "бросить кости онлайн", "кость d20", "виртуальные кости", "случайные кости"], count: "Число костей", sides: "Граней на кость", roll: "Бросить", sum: "Сумма", average: "Среднее" },
  zh: { title: "掷骰器", short: "掷任意数量、任意面数的骰子。", description: "免费的在线掷骰器。掷一个或多个任意面数的骰子（d6、d20 或自定义），查看每个结果、总和与平均值。使用 Web Crypto API 保证公平。", keywords: ["掷骰器", "在线掷骰子", "d20骰子", "虚拟骰子", "随机骰子"], count: "骰子数量", sides: "每个骰子面数", roll: "掷", sum: "总和", average: "平均值" },
  ja: { title: "ダイスローラー", short: "任意の数・任意の面数のサイコロを振ります。", description: "無料のオンラインダイスローラー。任意の面数（d6・d20・カスタム）のサイコロを1つまたは複数振り、各結果・合計・平均を表示します。公平な出目のため Web Crypto API を使用。", keywords: ["ダイスローラー", "オンライン サイコロ", "d20 ダイス", "仮想サイコロ", "ランダム サイコロ"], count: "サイコロの数", sides: "1個の面数", roll: "振る", sum: "合計", average: "平均" },
  ko: { title: "주사위 굴리기", short: "원하는 개수와 면 수의 주사위를 굴립니다.", description: "무료 온라인 주사위 굴리기. 임의의 면 수(d6, d20 또는 사용자 지정) 주사위를 하나 또는 여러 개 굴리고 각 결과, 합계, 평균을 확인하세요. 공정한 굴림을 위해 Web Crypto API를 사용합니다.", keywords: ["주사위 굴리기", "온라인 주사위", "d20 주사위", "가상 주사위", "무작위 주사위"], count: "주사위 개수", sides: "주사위 면 수", roll: "굴리기", sum: "합계", average: "평균" },
  hi: { title: "डाइस रोलर", short: "किसी भी संख्या में, किसी भी फलक संख्या के पासे फेंकें।", description: "मुफ्त ऑनलाइन डाइस रोलर। किसी भी फलक संख्या (d6, d20 या कस्टम) के एक या कई पासे फेंकें और हर परिणाम, योग और औसत देखें। निष्पक्ष रोल के लिए Web Crypto API का उपयोग।", keywords: ["डाइस रोलर", "ऑनलाइन पासा फेंकें", "d20 पासा", "वर्चुअल पासा", "रैंडम पासा"], count: "पासों की संख्या", sides: "प्रति पासा फलक", roll: "फेंकें", sum: "योग", average: "औसत" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
