import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CRC32 Checksum Calculator", short: "Compute the CRC-32 checksum of any text.", description: "Free CRC32 checksum calculator. Get the CRC-32 (IEEE 802.3) value of any text as hex and unsigned decimal — useful for verifying data integrity. Runs in your browser.", keywords: ["crc32 checksum", "crc-32 calculator", "crc32 hash", "checksum generator", "crc32 online"], input: "Text", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },
  nl: { title: "CRC32 Controleersum Calculator", short: "Compute the CRC-32 controleersum of any tekst.", description: "Gratis CRC32 controleersum calculator. Get the CRC-32 (IEEE 802.3) value of any tekst as hex and unsigned decimal — useful for verifying data integrity. Runs in uw browser.", keywords: ["crc32 controleersum", "crc-32 calculator", "crc32 hash", "controleersum generator", "crc32 online"], input: "Tekst", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },

  pl: { title: "CRC32 Sprawdźsum Kalkulator", short: "Compute the CRC-32 sprawdźsum of any tekst.", description: "Darmowy CRC32 sprawdźsum kalkulator. Get the CRC-32 (IEEE 802.3) value of any tekst as hex and unsigned decimal — useful for verifying data integrity. Runs w Twojej przeglądarce.", keywords: ["crc32 sprawdźsum", "crc-32 kalkulator", "crc32 hash", "sprawdźsum generator", "crc32 online"], input: "Tekst", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },
  pt: { title: "Calculadora de CRC32 Checksum", short: "Compute the CRC-32 checksum de any text.", description: "Gratuito - CRC32 checksum calculator. Get the CRC-32 (IEEE 802.3) value de any text as hex e unsigned decimal â useful para verifying data integrity. Runs no seu navegador.", keywords: ["crc32 checksum", "crc-32 calculator", "crc32 hash", "checksum generator", "crc32 online"], input: "Text", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },
  id: { title: "Kalkulator CRC32 Checksum", short: "Compute the CRC-32 checksum dari any text.", description: "Gratis - CRC32 checksum calculator. Get the CRC-32 (IEEE 802.3) value dari any text as hex dan unsigned decimal â useful for verifying data integrity. Runs di browser Anda.", keywords: ["crc32 checksum", "crc-32 calculator", "crc32 hash", "checksum generator", "crc32 online"], input: "Text", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },

  tr: { title: "CRC32 Sağlama Toplamı Hesaplayıcı", short: "Herhangi bir metnin CRC-32 sağlama toplamını hesaplayın.", description: "Ücretsiz CRC32 sağlama toplamı hesaplayıcı. Herhangi bir metnin CRC-32 (IEEE 802.3) değerini hex ve işaretsiz ondalık olarak alın — veri bütünlüğünü doğrulamak için kullanışlı. Tarayıcınızda çalışır.", keywords: ["crc32 sağlama toplamı", "crc-32 hesaplayıcı", "crc32 hash", "sağlama toplamı oluşturucu", "crc32 online"], input: "Metin", hex: "CRC-32 (hex)", decimal: "CRC-32 (ondalık)" },
  de: { title: "CRC32-Prüfsummen-Rechner", short: "Berechnen Sie die CRC-32-Prüfsumme eines Textes.", description: "Kostenloser CRC32-Prüfsummen-Rechner. Erhalten Sie den CRC-32-Wert (IEEE 802.3) eines Textes als Hex und vorzeichenlose Dezimalzahl — nützlich zur Überprüfung der Datenintegrität. Läuft im Browser.", keywords: ["crc32 prüfsumme", "crc-32 rechner", "crc32 hash", "prüfsummen generator", "crc32 online"], input: "Text", hex: "CRC-32 (hex)", decimal: "CRC-32 (dezimal)" },
  fr: { title: "Calculateur de Somme de Contrôle CRC32", short: "Calculez la somme de contrôle CRC-32 de tout texte.", description: "Calculateur de somme de contrôle CRC32 gratuit. Obtenez la valeur CRC-32 (IEEE 802.3) de tout texte en hexadécimal et décimal non signé — utile pour vérifier l'intégrité des données. Fonctionne dans votre navigateur.", keywords: ["somme contrôle crc32", "calculateur crc-32", "hash crc32", "générateur somme contrôle", "crc32 en ligne"], input: "Texte", hex: "CRC-32 (hex)", decimal: "CRC-32 (décimal)" },
  es: { title: "Calculadora de Suma de Verificación CRC32", short: "Calcula la suma de verificación CRC-32 de cualquier texto.", description: "Calculadora de suma de verificación CRC32 gratuita. Obtén el valor CRC-32 (IEEE 802.3) de cualquier texto en hexadecimal y decimal sin signo — útil para verificar la integridad de los datos. Funciona en tu navegador.", keywords: ["suma verificación crc32", "calculadora crc-32", "hash crc32", "generador suma verificación", "crc32 online"], input: "Texto", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimal)" },
  it: { title: "Calcolatore di Checksum CRC32", short: "Calcola il checksum CRC-32 di qualsiasi testo.", description: "Calcolatore di checksum CRC32 gratuito. Ottieni il valore CRC-32 (IEEE 802.3) di qualsiasi testo in esadecimale e decimale senza segno — utile per verificare l'integrità dei dati. Funziona nel browser.", keywords: ["checksum crc32", "calcolatore crc-32", "hash crc32", "generatore checksum", "crc32 online"], input: "Testo", hex: "CRC-32 (hex)", decimal: "CRC-32 (decimale)" },
  ar: { title: "حاسبة المجموع الاختباري CRC32", short: "احسب المجموع الاختباري CRC-32 لأي نص.", description: "حاسبة مجموع اختباري CRC32 مجانية. احصل على قيمة CRC-32 (IEEE 802.3) لأي نص بصيغة سداسية وعشرية غير موقّعة — مفيدة للتحقق من سلامة البيانات. تعمل في متصفحك.", keywords: ["مجموع اختباري crc32", "حاسبة crc-32", "تجزئة crc32", "مولد المجموع الاختباري", "crc32 عبر الإنترنت"], input: "النص", hex: "CRC-32 (سداسي)", decimal: "CRC-32 (عشري)" },
  ru: { title: "Калькулятор контрольной суммы CRC32", short: "Вычислите контрольную сумму CRC-32 любого текста.", description: "Бесплатный калькулятор контрольной суммы CRC32. Получите значение CRC-32 (IEEE 802.3) любого текста в hex и беззнаковом десятичном виде — полезно для проверки целостности данных. Работает в браузере.", keywords: ["контрольная сумма crc32", "калькулятор crc-32", "хеш crc32", "генератор контрольной суммы", "crc32 онлайн"], input: "Текст", hex: "CRC-32 (hex)", decimal: "CRC-32 (десятичный)" },
  zh: { title: "CRC32 校验和计算器", short: "计算任意文本的 CRC-32 校验和。", description: "免费的 CRC32 校验和计算器。以十六进制和无符号十进制获取任意文本的 CRC-32（IEEE 802.3）值——用于验证数据完整性。在浏览器中运行。", keywords: ["crc32 校验和", "crc-32 计算器", "crc32 哈希", "校验和生成器", "crc32 在线"], input: "文本", hex: "CRC-32（十六进制）", decimal: "CRC-32（十进制）" },
  ja: { title: "CRC32 チェックサム計算", short: "任意のテキストの CRC-32 チェックサムを計算。", description: "無料の CRC32 チェックサム計算ツール。任意のテキストの CRC-32（IEEE 802.3）値を16進と符号なし10進で取得——データ整合性の検証に便利。ブラウザ内で動作します。", keywords: ["crc32 チェックサム", "crc-32 計算", "crc32 ハッシュ", "チェックサム 生成", "crc32 オンライン"], input: "テキスト", hex: "CRC-32（16進）", decimal: "CRC-32（10進）" },
  ko: { title: "CRC32 체크섬 계산기", short: "모든 텍스트의 CRC-32 체크섬을 계산합니다.", description: "무료 CRC32 체크섬 계산기. 모든 텍스트의 CRC-32(IEEE 802.3) 값을 16진수와 부호 없는 10진수로 얻습니다 — 데이터 무결성 검증에 유용합니다. 브라우저에서 실행됩니다.", keywords: ["crc32 체크섬", "crc-32 계산기", "crc32 해시", "체크섬 생성기", "crc32 온라인"], input: "텍스트", hex: "CRC-32 (16진수)", decimal: "CRC-32 (10진수)" },
  hi: { title: "CRC32 चेकसम कैलकुलेटर", short: "किसी भी टेक्स्ट का CRC-32 चेकसम गणना करें।", description: "मुफ्त CRC32 चेकसम कैलकुलेटर। किसी भी टेक्स्ट का CRC-32 (IEEE 802.3) मान हेक्स और अहस्ताक्षरित दशमलव में पाएं — डेटा अखंडता सत्यापित करने के लिए उपयोगी। आपके ब्राउज़र में चलता है।", keywords: ["crc32 चेकसम", "crc-32 कैलकुलेटर", "crc32 हैश", "चेकसम जनरेटर", "crc32 ऑनलाइन"], input: "टेक्स्ट", hex: "CRC-32 (हेक्स)", decimal: "CRC-32 (दशमलव)" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
