import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "sitemap.xml Generator", short: "Build an XML sitemap from a list of URLs.", description: "Free XML sitemap generator. Paste a list of URLs (one per line), set defaults for lastmod, changefreq and priority, and download a valid sitemap.xml — runs entirely in your browser.", keywords: ["sitemap.xml generator", "xml sitemap", "create sitemap", "seo sitemap", "sitemap maker"], urls: "URLs (one per line)", lastmod: "Last modified", changefreq: "Change frequency", priority: "Priority", output: "sitemap.xml" },
  tr: { title: "sitemap.xml Oluşturucu", short: "URL listesinden XML site haritası oluşturun.", description: "Ücretsiz XML site haritası oluşturucu. URL'leri (her satıra bir tane) yapıştırın, lastmod, changefreq ve priority için varsayılanları ayarlayın ve geçerli bir sitemap.xml indirin — tamamen tarayıcınızda çalışır.", keywords: ["sitemap.xml oluşturucu", "xml site haritası", "site haritası oluştur", "seo site haritası", "site haritası yapıcı"], urls: "URL'ler (her satıra bir tane)", lastmod: "Son değiştirilme", changefreq: "Değişim sıklığı", priority: "Öncelik", output: "sitemap.xml" },
  de: { title: "sitemap.xml-Generator", short: "Erzeugen Sie eine XML-Sitemap aus einer URL-Liste.", description: "Kostenloser XML-Sitemap-Generator. Fügen Sie eine Liste von URLs ein (eine pro Zeile), setzen Sie Standardwerte für lastmod, changefreq und priority und laden Sie eine gültige sitemap.xml herunter — läuft vollständig im Browser.", keywords: ["sitemap.xml generator", "xml sitemap", "sitemap erstellen", "seo sitemap", "sitemap maker"], urls: "URLs (eine pro Zeile)", lastmod: "Zuletzt geändert", changefreq: "Änderungshäufigkeit", priority: "Priorität", output: "sitemap.xml" },
  fr: { title: "Générateur de sitemap.xml", short: "Créez un sitemap XML à partir d'une liste d'URLs.", description: "Générateur de sitemap XML gratuit. Collez une liste d'URLs (une par ligne), définissez des valeurs par défaut pour lastmod, changefreq et priority, puis téléchargez un sitemap.xml valide — fonctionne entièrement dans votre navigateur.", keywords: ["générateur sitemap.xml", "sitemap xml", "créer sitemap", "sitemap seo", "fabricant sitemap"], urls: "URLs (une par ligne)", lastmod: "Dernière modification", changefreq: "Fréquence de changement", priority: "Priorité", output: "sitemap.xml" },
  es: { title: "Generador de sitemap.xml", short: "Crea un sitemap XML desde una lista de URLs.", description: "Generador de sitemap XML gratuito. Pega una lista de URLs (una por línea), establece valores por defecto para lastmod, changefreq y priority, y descarga un sitemap.xml válido — funciona completamente en tu navegador.", keywords: ["generador sitemap.xml", "sitemap xml", "crear sitemap", "sitemap seo", "fabricante sitemap"], urls: "URLs (una por línea)", lastmod: "Última modificación", changefreq: "Frecuencia de cambio", priority: "Prioridad", output: "sitemap.xml" },
  it: { title: "Generatore di sitemap.xml", short: "Crea una sitemap XML da un elenco di URL.", description: "Generatore di sitemap XML gratuito. Incolla un elenco di URL (uno per riga), imposta valori predefiniti per lastmod, changefreq e priority e scarica una sitemap.xml valida — funziona interamente nel browser.", keywords: ["generatore sitemap.xml", "sitemap xml", "creare sitemap", "sitemap seo", "creatore sitemap"], urls: "URL (uno per riga)", lastmod: "Ultima modifica", changefreq: "Frequenza di cambio", priority: "Priorità", output: "sitemap.xml" },
  ar: { title: "مولّد sitemap.xml", short: "أنشئ خريطة موقع XML من قائمة عناوين URL.", description: "مولّد خريطة موقع XML مجاني. الصق قائمة بعناوين URL (واحد في كل سطر)، اضبط القيم الافتراضية لـ lastmod و changefreq و priority، ونزّل sitemap.xml صالحًا — يعمل بالكامل في متصفحك.", keywords: ["مولد sitemap.xml", "خريطة موقع xml", "إنشاء خريطة موقع", "خريطة موقع seo", "صانع خريطة الموقع"], urls: "عناوين URL (واحد في كل سطر)", lastmod: "آخر تعديل", changefreq: "تكرار التغيير", priority: "الأولوية", output: "sitemap.xml" },
  ru: { title: "Генератор sitemap.xml", short: "Создайте XML-карту сайта из списка URL.", description: "Бесплатный генератор XML-карты сайта. Вставьте список URL (по одному в строке), задайте значения по умолчанию для lastmod, changefreq и priority и скачайте валидный sitemap.xml — работает полностью в браузере.", keywords: ["генератор sitemap.xml", "xml карта сайта", "создать sitemap", "seo карта сайта", "создатель sitemap"], urls: "URL (по одному в строке)", lastmod: "Последнее изменение", changefreq: "Частота изменения", priority: "Приоритет", output: "sitemap.xml" },
  zh: { title: "sitemap.xml 生成器", short: "从 URL 列表构建 XML 网站地图。", description: "免费的 XML 网站地图生成器。粘贴 URL 列表（每行一个），为 lastmod、changefreq 和 priority 设置默认值，然后下载有效的 sitemap.xml——完全在浏览器中运行。", keywords: ["sitemap.xml 生成器", "xml 网站地图", "创建网站地图", "seo 网站地图", "网站地图制作"], urls: "URL（每行一个）", lastmod: "最后修改", changefreq: "更改频率", priority: "优先级", output: "sitemap.xml" },
  ja: { title: "sitemap.xml 生成", short: "URL リストから XML サイトマップを構築。", description: "無料の XML サイトマップ生成ツール。URL のリスト（1 行に 1 つ）を貼り付け、lastmod、changefreq、priority のデフォルトを設定して有効な sitemap.xml をダウンロード——すべてブラウザ内で動作。", keywords: ["sitemap.xml 生成", "xml サイトマップ", "サイトマップ 作成", "seo サイトマップ", "サイトマップ メーカー"], urls: "URL（1 行に 1 つ）", lastmod: "最終更新", changefreq: "変更頻度", priority: "優先度", output: "sitemap.xml" },
  ko: { title: "sitemap.xml 생성기", short: "URL 목록에서 XML 사이트맵을 만듭니다.", description: "무료 XML 사이트맵 생성기. URL 목록(한 줄에 하나)을 붙여넣고 lastmod, changefreq, priority의 기본값을 설정한 다음 유효한 sitemap.xml을 다운로드하세요 — 모두 브라우저에서 실행됩니다.", keywords: ["sitemap.xml 생성기", "xml 사이트맵", "사이트맵 만들기", "seo 사이트맵", "사이트맵 메이커"], urls: "URL (한 줄에 하나)", lastmod: "최종 수정", changefreq: "변경 빈도", priority: "우선순위", output: "sitemap.xml" },
  hi: { title: "sitemap.xml जनरेटर", short: "URL की सूची से XML साइटमैप बनाएं।", description: "मुफ्त XML साइटमैप जनरेटर। URL की सूची पेस्ट करें (प्रति पंक्ति एक), lastmod, changefreq और priority के लिए डिफ़ॉल्ट सेट करें, और एक मान्य sitemap.xml डाउनलोड करें — पूरी तरह आपके ब्राउज़र में चलता है।", keywords: ["sitemap.xml जनरेटर", "xml साइटमैप", "साइटमैप बनाएं", "seo साइटमैप", "साइटमैप मेकर"], urls: "URL (प्रति पंक्ति एक)", lastmod: "अंतिम संशोधन", changefreq: "परिवर्तन आवृत्ति", priority: "प्राथमिकता", output: "sitemap.xml" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
