import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: ".gitignore Generator", short: "Tick languages, OSes and editors to build a .gitignore.", description: "Free .gitignore generator. Pick languages (Node, Python, Go…), frameworks (React, Astro, Vite…), operating systems and editors to assemble a clean .gitignore file ready to copy.", keywords: ["gitignore generator", "gitignore template", "create gitignore", "git ignore", "gitignore file"], pick: "Pick the stacks you use", result: ".gitignore" },
  nl: { title: ".gitignore Generator", short: "Tick languages, OSes and editors to build a .gitignore.", description: "Gratis .gitignore generator. Pick languages (Node, Python, Go…), frameworks (React, Astro, Vite…), operating systems and editors to assemble a clean .gitignore file ready to copy.", keywords: ["gitignore generator", "gitignore template", "maak aan gitignore", "git ignore", "gitignore file"], pick: "Pick the stacks you use", result: ".gitignore" },

  pl: { title: ".gitignore Generator", short: "Tick languages, OSes and editors to build a .gitignore.", description: "Darmowy .gitignore generator. Pick languages (Node, Python, Go…), frameworks (React, Astro, Vite…), operating systems and editors to assemble a clean .gitignore file ready to copy.", keywords: ["gitignore generator", "gitignore template", "utwórz gitignore", "git ignore", "gitignore file"], pick: "Pick the stacks you use", result: ".gitignore" },
  pt: { title: "Gerador de .gitignore", short: "Tick languages, OSes e editors para build a .gitignore.", description: "Gratuito - .gitignore generator. Pick languages (Node, Python, Goâ¦), frameworks (React, Astro, Viteâ¦), operating systems e editors para assemble a clean .gitignore file ready para copy.", keywords: ["gitignore generator", "gitignore template", "create gitignore", "git ignore", "gitignore file"], pick: "Pick the stacks you use", result: ".gitignore" },
  id: { title: "Generator .gitignore", short: "Tick languages, OSes dan editors to build a .gitignore.", description: "Gratis - .gitignore generator. Pick languages (Node, Python, Goâ¦), frameworks (React, Astro, Viteâ¦), operating systems dan editors to assemble a clean .gitignore file ready to copy.", keywords: ["gitignore generator", "gitignore template", "create gitignore", "git ignore", "gitignore file"], pick: "Pick the stacks you use", result: ".gitignore" },

  tr: { title: ".gitignore Oluşturucu", short: "Dil, işletim sistemi ve editör seçerek .gitignore oluşturun.", description: "Ücretsiz .gitignore oluşturucu. Diller (Node, Python, Go…), framework'ler (React, Astro, Vite…), işletim sistemleri ve editörleri seçerek kopyalanmaya hazır temiz bir .gitignore dosyası oluşturun.", keywords: ["gitignore oluşturucu", "gitignore şablonu", "gitignore oluştur", "git ignore", "gitignore dosyası"], pick: "Kullandığınız stack'leri seçin", result: ".gitignore" },
  de: { title: ".gitignore-Generator", short: "Sprachen, Betriebssysteme und Editoren ankreuzen, um eine .gitignore zu erstellen.", description: "Kostenloser .gitignore-Generator. Wählen Sie Sprachen (Node, Python, Go…), Frameworks (React, Astro, Vite…), Betriebssysteme und Editoren, um eine saubere .gitignore-Datei zum Kopieren zusammenzustellen.", keywords: ["gitignore generator", "gitignore vorlage", "gitignore erstellen", "git ignore", "gitignore datei"], pick: "Wählen Sie Ihren Stack", result: ".gitignore" },
  fr: { title: "Générateur .gitignore", short: "Cochez langages, OS et éditeurs pour construire un .gitignore.", description: "Générateur .gitignore gratuit. Choisissez langages (Node, Python, Go…), frameworks (React, Astro, Vite…), systèmes d'exploitation et éditeurs pour assembler un fichier .gitignore propre prêt à copier.", keywords: ["générateur gitignore", "modèle gitignore", "créer gitignore", "git ignore", "fichier gitignore"], pick: "Cochez vos stacks", result: ".gitignore" },
  es: { title: "Generador .gitignore", short: "Marca lenguajes, SO y editores para construir un .gitignore.", description: "Generador .gitignore gratuito. Elige lenguajes (Node, Python, Go…), frameworks (React, Astro, Vite…), sistemas operativos y editores para ensamblar un archivo .gitignore limpio listo para copiar.", keywords: ["generador gitignore", "plantilla gitignore", "crear gitignore", "git ignore", "archivo gitignore"], pick: "Elige tu stack", result: ".gitignore" },
  it: { title: "Generatore .gitignore", short: "Spunta linguaggi, OS ed editor per costruire un .gitignore.", description: "Generatore .gitignore gratuito. Scegli linguaggi (Node, Python, Go…), framework (React, Astro, Vite…), sistemi operativi ed editor per assemblare un file .gitignore pulito pronto da copiare.", keywords: ["generatore gitignore", "template gitignore", "creare gitignore", "git ignore", "file gitignore"], pick: "Scegli il tuo stack", result: ".gitignore" },
  ar: { title: "مولّد .gitignore", short: "حدّد اللغات وأنظمة التشغيل والمحرّرات لإنشاء .gitignore.", description: "مولّد .gitignore مجاني. اختر اللغات (Node، Python، Go…)، أطر العمل (React، Astro، Vite…)، أنظمة التشغيل والمحرّرات لتجميع ملف .gitignore نظيف جاهز للنسخ.", keywords: ["مولد gitignore", "قالب gitignore", "إنشاء gitignore", "git ignore", "ملف gitignore"], pick: "اختر مكدسك", result: ".gitignore" },
  ru: { title: "Генератор .gitignore", short: "Отметьте языки, ОС и редакторы для создания .gitignore.", description: "Бесплатный генератор .gitignore. Выберите языки (Node, Python, Go…), фреймворки (React, Astro, Vite…), ОС и редакторы, чтобы собрать чистый файл .gitignore для копирования.", keywords: ["генератор gitignore", "шаблон gitignore", "создать gitignore", "git ignore", "файл gitignore"], pick: "Выберите ваш стек", result: ".gitignore" },
  zh: { title: ".gitignore 生成器", short: "勾选语言、操作系统和编辑器以构建 .gitignore。", description: "免费的 .gitignore 生成器。选择语言（Node、Python、Go…）、框架（React、Astro、Vite…）、操作系统和编辑器，组装一个可直接复制的整洁 .gitignore 文件。", keywords: ["gitignore 生成器", "gitignore 模板", "创建 gitignore", "git ignore", "gitignore 文件"], pick: "选择你的技术栈", result: ".gitignore" },
  ja: { title: ".gitignore 生成", short: "言語・OS・エディタを選んで .gitignore を作成。", description: "無料の .gitignore 生成ツール。言語（Node、Python、Go…）、フレームワーク（React、Astro、Vite…）、OS、エディタを選んでコピー可能なクリーンな .gitignore ファイルを組み立てます。", keywords: ["gitignore 生成", "gitignore テンプレート", "gitignore 作成", "git ignore", "gitignore ファイル"], pick: "使用するスタックを選択", result: ".gitignore" },
  ko: { title: ".gitignore 생성기", short: "언어, OS, 에디터를 선택해 .gitignore를 만듭니다.", description: "무료 .gitignore 생성기. 언어(Node, Python, Go…), 프레임워크(React, Astro, Vite…), 운영체제와 에디터를 선택하여 복사할 수 있는 깔끔한 .gitignore 파일을 조합합니다.", keywords: ["gitignore 생성기", "gitignore 템플릿", "gitignore 만들기", "git ignore", "gitignore 파일"], pick: "사용하는 스택 선택", result: ".gitignore" },
  hi: { title: ".gitignore जनरेटर", short: ".gitignore बनाने के लिए भाषाएँ, OS और एडिटर चुनें।", description: "मुफ्त .gitignore जनरेटर। भाषाएँ (Node, Python, Go…), फ्रेमवर्क (React, Astro, Vite…), ऑपरेटिंग सिस्टम और एडिटर चुनें ताकि कॉपी करने के लिए तैयार एक स्वच्छ .gitignore फ़ाइल बने।", keywords: ["gitignore जनरेटर", "gitignore टेम्पलेट", "gitignore बनाएं", "git ignore", "gitignore फ़ाइल"], pick: "अपना स्टैक चुनें", result: ".gitignore" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
