import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Lottery Number Generator", short: "Pick random lottery numbers for Powerball, EuroMillions and more.", description: "Free lottery number generator. Choose Powerball, Mega Millions, EuroMillions, UK Lotto or Sayısal Loto and generate a draw of random main and bonus numbers — entirely in your browser with crypto-grade randomness.", keywords: ["lottery number generator", "lucky numbers", "powerball generator", "euromillions generator", "sayısal loto"], preset: "Game", generate: "Generate", main: "Main numbers", bonus: "Bonus numbers" },
  pt: { title: "Gerador de Lottery Number", short: "Pick random lottery numbers para Powerball, EuroMillions e more.", description: "Gratuito - lottery number generator. Choose Powerball, Mega Millions, EuroMillions, UK Lotto ou SayÄ±sal Loto e gerar a draw de random main e bonus numbers â entirely no seu navegador com crypto-grade randomness.", keywords: ["lottery number generator", "lucky numbers", "powerball generator", "euromillions generator", "sayısal loto"], preset: "Game", generate: "Generate", main: "Main numbers", bonus: "Bonus numbers" },
  id: { title: "Generator Lottery Number", short: "Pick random lottery numbers for Powerball, EuroMillions dan more.", description: "Gratis - lottery number generator. Choose Powerball, Mega Millions, EuroMillions, UK Lotto atau SayÄ±sal Loto dan hasilkan a draw dari random main dan bonus numbers â entirely di browser Anda with crypto-grade randomness.", keywords: ["lottery number generator", "lucky numbers", "powerball generator", "euromillions generator", "sayısal loto"], preset: "Game", generate: "Generate", main: "Main numbers", bonus: "Bonus numbers" },

  tr: { title: "Loto Sayı Oluşturucu", short: "Powerball, EuroMillions ve Sayısal Loto için rastgele loto sayıları seçin.", description: "Ücretsiz loto sayı oluşturucu. Powerball, Mega Millions, EuroMillions, UK Lotto veya Sayısal Loto seçerek rastgele ana ve bonus sayılarla bir çekiliş oluşturun — tamamen tarayıcınızda kripto sınıfı rastgelelikle.", keywords: ["loto sayı oluşturucu", "şanslı sayılar", "powerball oluşturucu", "euromillions oluşturucu", "sayısal loto"], preset: "Oyun", generate: "Oluştur", main: "Ana sayılar", bonus: "Bonus sayılar" },
  de: { title: "Lottozahlen-Generator", short: "Wählen Sie zufällige Lottozahlen für Powerball, EuroMillions und mehr.", description: "Kostenloser Lottozahlen-Generator. Wählen Sie Powerball, Mega Millions, EuroMillions, UK Lotto oder Sayısal Loto und erzeugen Sie eine Ziehung mit zufälligen Haupt- und Zusatzzahlen — vollständig im Browser mit kryptographischer Zufälligkeit.", keywords: ["lottozahlen generator", "glückszahlen", "powerball generator", "euromillions generator", "sayısal loto"], preset: "Spiel", generate: "Erzeugen", main: "Hauptzahlen", bonus: "Zusatzzahlen" },
  fr: { title: "Générateur de Numéros de Loterie", short: "Choisissez des numéros de loterie aléatoires pour Powerball, EuroMillions et plus.", description: "Générateur de numéros de loterie gratuit. Choisissez Powerball, Mega Millions, EuroMillions, UK Lotto ou Sayısal Loto et générez un tirage avec numéros principaux et bonus aléatoires — entièrement dans votre navigateur avec un aléa cryptographique.", keywords: ["générateur numéros loterie", "numéros chance", "générateur powerball", "générateur euromillions", "sayısal loto"], preset: "Jeu", generate: "Générer", main: "Numéros principaux", bonus: "Numéros bonus" },
  es: { title: "Generador de Números de Lotería", short: "Elige números de lotería aleatorios para Powerball, EuroMillions y más.", description: "Generador de números de lotería gratuito. Elige Powerball, Mega Millions, EuroMillions, UK Lotto o Sayısal Loto y genera un sorteo con números principales y bonus aleatorios — completamente en tu navegador con aleatoriedad criptográfica.", keywords: ["generador números lotería", "números suerte", "generador powerball", "generador euromillions", "sayısal loto"], preset: "Juego", generate: "Generar", main: "Números principales", bonus: "Números bonus" },
  it: { title: "Generatore di Numeri della Lotteria", short: "Scegli numeri casuali per Powerball, EuroMillions e altre lotterie.", description: "Generatore di numeri della lotteria gratuito. Scegli Powerball, Mega Millions, EuroMillions, UK Lotto o Sayısal Loto e genera un'estrazione con numeri principali e bonus casuali — interamente nel browser con casualità crittografica.", keywords: ["generatore numeri lotteria", "numeri fortunati", "generatore powerball", "generatore euromillions", "sayısal loto"], preset: "Gioco", generate: "Genera", main: "Numeri principali", bonus: "Numeri bonus" },
  ar: { title: "مولّد أرقام اليانصيب", short: "اختر أرقام يانصيب عشوائية لـ Powerball و EuroMillions وغيرها.", description: "مولّد أرقام يانصيب مجاني. اختر Powerball أو Mega Millions أو EuroMillions أو UK Lotto أو Sayısal Loto وأنشئ سحبًا بأرقام رئيسية وإضافية عشوائية — بالكامل في متصفحك بعشوائية بمستوى تشفيري.", keywords: ["مولد أرقام اليانصيب", "أرقام محظوظة", "مولد powerball", "مولد euromillions", "sayısal loto"], preset: "اللعبة", generate: "توليد", main: "الأرقام الرئيسية", bonus: "الأرقام الإضافية" },
  ru: { title: "Генератор лотерейных номеров", short: "Выбирайте случайные номера для Powerball, EuroMillions и других лотерей.", description: "Бесплатный генератор лотерейных номеров. Выберите Powerball, Mega Millions, EuroMillions, UK Lotto или Sayısal Loto и сгенерируйте тираж со случайными основными и бонусными номерами — полностью в браузере с криптографической случайностью.", keywords: ["генератор лотерейных номеров", "счастливые номера", "генератор powerball", "генератор euromillions", "sayısal loto"], preset: "Игра", generate: "Создать", main: "Основные номера", bonus: "Бонусные номера" },
  zh: { title: "彩票号码生成器", short: "为 Powerball、EuroMillions 等彩票随机选号。", description: "免费的彩票号码生成器。选择 Powerball、Mega Millions、EuroMillions、UK Lotto 或 Sayısal Loto，生成包含随机主号码和奖金号码的一注——完全在浏览器中以加密级随机性进行。", keywords: ["彩票号码生成器", "幸运号码", "powerball 生成器", "euromillions 生成器", "sayısal loto"], preset: "彩票", generate: "生成", main: "主号码", bonus: "奖金号码" },
  ja: { title: "宝くじ番号生成", short: "Powerball、EuroMillions などのランダム宝くじ番号を選択。", description: "無料の宝くじ番号生成ツール。Powerball、Mega Millions、EuroMillions、UK Lotto、または Sayısal Loto を選び、ランダムなメイン番号とボーナス番号で抽選を生成します——すべてブラウザ内で暗号級の乱数により。", keywords: ["宝くじ番号 生成", "ラッキーナンバー", "powerball 生成", "euromillions 生成", "sayısal loto"], preset: "ゲーム", generate: "生成", main: "メイン番号", bonus: "ボーナス番号" },
  ko: { title: "복권 번호 생성기", short: "Powerball, EuroMillions 등의 복권 번호를 무작위로 선택합니다.", description: "무료 복권 번호 생성기. Powerball, Mega Millions, EuroMillions, UK Lotto 또는 Sayısal Loto를 선택하고 무작위 메인 및 보너스 번호로 추첨을 생성하세요 — 모두 브라우저에서 암호화 수준의 난수로.", keywords: ["복권 번호 생성기", "행운의 번호", "powerball 생성기", "euromillions 생성기", "sayısal loto"], preset: "게임", generate: "생성", main: "메인 번호", bonus: "보너스 번호" },
  hi: { title: "लॉटरी नंबर जनरेटर", short: "Powerball, EuroMillions और अन्य के लिए यादृच्छिक लॉटरी नंबर चुनें।", description: "मुफ्त लॉटरी नंबर जनरेटर। Powerball, Mega Millions, EuroMillions, UK Lotto या Sayısal Loto चुनें और यादृच्छिक मुख्य और बोनस नंबरों के साथ एक ड्रॉ बनाएं — पूरी तरह क्रिप्टो-ग्रेड यादृच्छिकता के साथ आपके ब्राउज़र में।", keywords: ["लॉटरी नंबर जनरेटर", "भाग्यशाली संख्याएँ", "powerball जनरेटर", "euromillions जनरेटर", "sayısal loto"], preset: "खेल", generate: "जनरेट करें", main: "मुख्य नंबर", bonus: "बोनस नंबर" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
