import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "CSS Minifier", short: "Minify CSS by removing comments and unnecessary whitespace.", description: "Free CSS minifier. Paste CSS to strip comments and collapse whitespace, reducing file size. Shows the original and minified sizes and the percentage saved. Runs in your browser.", keywords: ["css minifier", "minify css", "css compressor", "compress css", "css optimizer"], placeholder: "Paste your CSS here…", minify: "Minify", original: "Original", minified: "Minified", saved: "Saved" },
  nl: { title: "CSS Minifier", short: "Minify CSS by removing comments and unnecessary whitespace.", description: "Gratis CSS minifier. Paste CSS to strip comments and collapse whitespace, reducing file grootte. Shows the original and minified groottes and the percentage saved. Runs in uw browser.", keywords: ["css minifier", "minify css", "css compressor", "compress css", "css optimizer"], placeholder: "Paste your CSS here…", minify: "Minify", original: "Original", minified: "Minified", saved: "Opslaand" },

  pl: { title: "CSS Minifier", short: "Minify CSS by removing comments and unnecessary whitespace.", description: "Darmowy CSS minifier. Paste CSS to strip comments and collapse whitespace, reducing file rozmiar. Shows the original and minified rozmiars and the percentage saved. Runs w Twojej przeglądarce.", keywords: ["css minifier", "minify css", "css compressor", "compress css", "css optimizer"], placeholder: "Paste your CSS here…", minify: "Minify", original: "Original", minified: "Minified", saved: "Zapiszd" },
  pt: { title: "Minificador de CSS", short: "Minificar CSS by removing comments e unnecessary whitespace.", description: "Gratuito - CSS minifier. Paste CSS para strip comments e collapse whitespace, reducing file size. Shows the original e minified sizes e the percentage saved. Runs no seu navegador.", keywords: ["css minifier", "minify css", "css compressor", "compress css", "css optimizer"], placeholder: "Paste your CSS here…", minify: "Minify", original: "Original", minified: "Minified", saved: "Saved" },
  id: { title: "Minifier CSS", short: "Perkecil CSS by removing comments dan unnecessary whitespace.", description: "Gratis - CSS minifier. Paste CSS to strip comments dan collapse whitespace, reducing file size. Shows the original dan minified sizes dan the percentage saved. Runs di browser Anda.", keywords: ["css minifier", "minify css", "css compressor", "compress css", "css optimizer"], placeholder: "Paste your CSS here…", minify: "Minify", original: "Original", minified: "Minified", saved: "Saved" },

  tr: { title: "CSS Küçültücü", short: "Yorumları ve gereksiz boşlukları kaldırarak CSS'i küçültün.", description: "Ücretsiz CSS küçültücü. CSS yapıştırın; yorumları kaldırın ve boşlukları daraltarak dosya boyutunu azaltın. Orijinal ve küçültülmüş boyutu ve kazanılan yüzdeyi gösterir. Tarayıcınızda çalışır.", keywords: ["css küçültücü", "css küçült", "css sıkıştırıcı", "css sıkıştır", "css optimize"], placeholder: "CSS'inizi buraya yapıştırın…", minify: "Küçült", original: "Orijinal", minified: "Küçültülmüş", saved: "Kazanılan" },
  de: { title: "CSS-Minifizierer", short: "Minifizieren Sie CSS durch Entfernen von Kommentaren und unnötigem Leerraum.", description: "Kostenloser CSS-Minifizierer. CSS einfügen, um Kommentare zu entfernen und Leerraum zu reduzieren und so die Dateigröße zu verringern. Zeigt Original- und minifizierte Größe sowie die Ersparnis.", keywords: ["css minifizierer", "css minify", "css kompressor", "css komprimieren", "css optimieren"], placeholder: "CSS hier einfügen…", minify: "Minifizieren", original: "Original", minified: "Minifiziert", saved: "Gespart" },
  fr: { title: "Minifieur CSS", short: "Minifiez le CSS en supprimant commentaires et espaces inutiles.", description: "Minifieur CSS gratuit. Collez du CSS pour supprimer les commentaires et réduire les espaces, diminuant la taille. Affiche la taille d'origine, minifiée et le pourcentage économisé.", keywords: ["minifieur css", "minifier css", "compresseur css", "compresser css", "optimiseur css"], placeholder: "Collez votre CSS ici…", minify: "Minifier", original: "Original", minified: "Minifié", saved: "Économisé" },
  es: { title: "Minificador CSS", short: "Minifica CSS eliminando comentarios y espacios innecesarios.", description: "Minificador CSS gratuito. Pega CSS para eliminar comentarios y colapsar espacios, reduciendo el tamaño. Muestra el tamaño original, minificado y el porcentaje ahorrado.", keywords: ["minificador css", "minificar css", "compresor css", "comprimir css", "optimizador css"], placeholder: "Pega tu CSS aquí…", minify: "Minificar", original: "Original", minified: "Minificado", saved: "Ahorrado" },
  it: { title: "Minificatore CSS", short: "Minimizza il CSS rimuovendo commenti e spazi superflui.", description: "Minificatore CSS gratuito. Incolla il CSS per rimuovere commenti e comprimere gli spazi, riducendo la dimensione. Mostra la dimensione originale, minimizzata e la percentuale risparmiata.", keywords: ["minificatore css", "minimizza css", "compressore css", "comprimi css", "ottimizzatore css"], placeholder: "Incolla il tuo CSS qui…", minify: "Minimizza", original: "Originale", minified: "Minimizzato", saved: "Risparmiato" },
  ar: { title: "مصغّر CSS", short: "صغّر CSS بإزالة التعليقات والمسافات غير الضرورية.", description: "مصغّر CSS مجاني. الصق CSS لإزالة التعليقات وضغط المسافات، مما يقلل الحجم. يعرض الحجم الأصلي والمصغّر والنسبة الموفّرة. يعمل في متصفحك.", keywords: ["مصغر css", "تصغير css", "ضاغط css", "ضغط css", "محسن css"], placeholder: "الصق CSS هنا…", minify: "تصغير", original: "الأصلي", minified: "المصغّر", saved: "الموفّر" },
  ru: { title: "CSS-Минификатор", short: "Минифицируйте CSS, удаляя комментарии и лишние пробелы.", description: "Бесплатный CSS-минификатор. Вставьте CSS, чтобы удалить комментарии и сжать пробелы, уменьшив размер. Показывает исходный и минифицированный размер и процент экономии.", keywords: ["css минификатор", "минифицировать css", "css компрессор", "сжать css", "оптимизатор css"], placeholder: "Вставьте CSS сюда…", minify: "Минифицировать", original: "Исходный", minified: "Минифицированный", saved: "Сэкономлено" },
  zh: { title: "CSS 压缩器", short: "通过删除注释和多余空白来压缩 CSS。", description: "免费的 CSS 压缩器。粘贴 CSS 以删除注释并折叠空白，减小文件大小。显示原始大小、压缩后大小和节省的百分比。在浏览器中运行。", keywords: ["css压缩器", "压缩css", "css压缩", "css优化", "css minify"], placeholder: "在此粘贴你的 CSS…", minify: "压缩", original: "原始", minified: "压缩后", saved: "节省" },
  ja: { title: "CSS 圧縮ツール", short: "コメントと不要な空白を削除して CSS を圧縮します。", description: "無料の CSS 圧縮ツール。CSS を貼り付けてコメントを削除し空白を圧縮、ファイルサイズを削減します。元のサイズ・圧縮後サイズ・削減率を表示します。ブラウザ内で動作します。", keywords: ["css 圧縮", "css minify", "css 圧縮ツール", "css 最適化"], placeholder: "ここに CSS を貼り付け…", minify: "圧縮", original: "元", minified: "圧縮後", saved: "削減" },
  ko: { title: "CSS 압축기", short: "주석과 불필요한 공백을 제거하여 CSS를 압축합니다.", description: "무료 CSS 압축기. CSS를 붙여넣어 주석을 제거하고 공백을 줄여 파일 크기를 축소합니다. 원본 크기, 압축 크기, 절감 비율을 표시합니다. 브라우저에서 실행됩니다.", keywords: ["css 압축기", "css 압축", "css 최적화", "css minify"], placeholder: "여기에 CSS를 붙여넣으세요…", minify: "압축", original: "원본", minified: "압축됨", saved: "절감" },
  hi: { title: "CSS मिनिफायर", short: "टिप्पणियाँ और अनावश्यक व्हाइटस्पेस हटाकर CSS को छोटा करें।", description: "मुफ्त CSS मिनिफायर। CSS पेस्ट करें ताकि टिप्पणियाँ हटें और व्हाइटस्पेस कम हो, फ़ाइल आकार घटे। मूल और मिनिफाई किया आकार तथा बचाया गया प्रतिशत दिखाता है। ब्राउज़र में चलता है।", keywords: ["css मिनिफायर", "css मिनिफाई", "css कंप्रेसर", "css संपीड़ित", "css ऑप्टिमाइज़र"], placeholder: "अपना CSS यहाँ पेस्ट करें…", minify: "मिनिफाई", original: "मूल", minified: "मिनिफाई", saved: "बचाया" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
