import type { ToolI18n } from "@/types/tool";
import { COMMON_UI } from "../_shared/ui";

const data = {
  en: { title: "Port Number Lookup", short: "Search common TCP/UDP port assignments.", description: "Free port-number reference. Search by port number, service name (SSH, HTTPS, PostgreSQL …) or description across the IANA well-known and most-used registered ports.", keywords: ["port number lookup", "iana ports", "well known ports", "tcp udp ports", "port reference"], search: "Search by number or service", port: "Port", protocol: "Protocol", name: "Service", desc: "Description" },
  tr: { title: "Port Numarası Arama", short: "Yaygın TCP/UDP port atamalarında arama yapın.", description: "Ücretsiz port numarası referansı. IANA bilinen ve en çok kullanılan kayıtlı portlar arasında port numarası, hizmet adı (SSH, HTTPS, PostgreSQL …) veya açıklamayla arayın.", keywords: ["port numarası arama", "iana portları", "bilinen portlar", "tcp udp portları", "port referansı"], search: "Numara veya hizmete göre arayın", port: "Port", protocol: "Protokol", name: "Hizmet", desc: "Açıklama" },
  de: { title: "Portnummer-Suche", short: "Suchen Sie gängige TCP/UDP-Portzuweisungen.", description: "Kostenlose Portnummer-Referenz. Suchen Sie nach Portnummer, Dienstname (SSH, HTTPS, PostgreSQL …) oder Beschreibung über die IANA-Wellknown-Ports und meistgenutzten registrierten Ports.", keywords: ["portnummer suche", "iana ports", "well known ports", "tcp udp ports", "port referenz"], search: "Suche nach Nummer oder Dienst", port: "Port", protocol: "Protokoll", name: "Dienst", desc: "Beschreibung" },
  fr: { title: "Recherche de Numéro de Port", short: "Recherchez les assignations de ports TCP/UDP courantes.", description: "Référence de numéros de port gratuite. Recherchez par numéro de port, nom de service (SSH, HTTPS, PostgreSQL …) ou description parmi les ports bien connus IANA et les ports enregistrés les plus utilisés.", keywords: ["recherche numéro port", "ports iana", "well known ports", "ports tcp udp", "référence ports"], search: "Rechercher par numéro ou service", port: "Port", protocol: "Protocole", name: "Service", desc: "Description" },
  es: { title: "Búsqueda de Número de Puerto", short: "Busca asignaciones comunes de puertos TCP/UDP.", description: "Referencia gratuita de números de puerto. Busca por número de puerto, nombre de servicio (SSH, HTTPS, PostgreSQL …) o descripción entre los puertos well-known de IANA y los puertos registrados más usados.", keywords: ["búsqueda número puerto", "puertos iana", "puertos well known", "puertos tcp udp", "referencia puertos"], search: "Buscar por número o servicio", port: "Puerto", protocol: "Protocolo", name: "Servicio", desc: "Descripción" },
  it: { title: "Ricerca Numero di Porta", short: "Cerca assegnazioni di porte TCP/UDP comuni.", description: "Riferimento gratuito di numeri di porta. Cerca per numero di porta, nome del servizio (SSH, HTTPS, PostgreSQL …) o descrizione tra le porte well-known IANA e le porte registrate più utilizzate.", keywords: ["ricerca numero porta", "porte iana", "porte well known", "porte tcp udp", "riferimento porte"], search: "Cerca per numero o servizio", port: "Porta", protocol: "Protocollo", name: "Servizio", desc: "Descrizione" },
  ar: { title: "بحث رقم المنفذ", short: "ابحث في تخصيصات منافذ TCP/UDP الشائعة.", description: "مرجع أرقام منافذ مجاني. ابحث برقم المنفذ أو اسم الخدمة (SSH، HTTPS، PostgreSQL …) أو الوصف عبر منافذ IANA المعروفة والمنافذ المسجلة الأكثر استخدامًا.", keywords: ["بحث رقم المنفذ", "منافذ iana", "well known ports", "منافذ tcp udp", "مرجع المنافذ"], search: "ابحث بالرقم أو الخدمة", port: "المنفذ", protocol: "البروتوكول", name: "الخدمة", desc: "الوصف" },
  ru: { title: "Поиск номеров портов", short: "Ищите общие назначения TCP/UDP портов.", description: "Бесплатный справочник номеров портов. Ищите по номеру порта, имени сервиса (SSH, HTTPS, PostgreSQL …) или описанию среди well-known портов IANA и наиболее используемых зарегистрированных портов.", keywords: ["поиск номера порта", "iana порты", "well known порты", "tcp udp порты", "справочник портов"], search: "Искать по номеру или сервису", port: "Порт", protocol: "Протокол", name: "Сервис", desc: "Описание" },
  zh: { title: "端口号查询", short: "搜索常见的 TCP/UDP 端口分配。", description: "免费的端口号参考。在 IANA 知名端口和最常用的注册端口中按端口号、服务名（SSH、HTTPS、PostgreSQL …）或描述进行搜索。", keywords: ["端口号查询", "iana 端口", "知名端口", "tcp udp 端口", "端口参考"], search: "按号码或服务搜索", port: "端口", protocol: "协议", name: "服务", desc: "描述" },
  ja: { title: "ポート番号 検索", short: "一般的な TCP/UDP ポート割り当てを検索。", description: "無料のポート番号リファレンス。IANA のウェルノウンポートと最もよく使われる登録ポートをポート番号、サービス名（SSH、HTTPS、PostgreSQL …）、または説明で検索できます。", keywords: ["ポート番号 検索", "iana ポート", "ウェルノウン ポート", "tcp udp ポート", "ポート リファレンス"], search: "番号またはサービスで検索", port: "ポート", protocol: "プロトコル", name: "サービス", desc: "説明" },
  ko: { title: "포트 번호 조회", short: "일반적인 TCP/UDP 포트 할당을 검색합니다.", description: "무료 포트 번호 참조. IANA의 well-known 포트와 가장 많이 사용되는 등록된 포트에서 포트 번호, 서비스 이름(SSH, HTTPS, PostgreSQL …) 또는 설명으로 검색하세요.", keywords: ["포트 번호 조회", "iana 포트", "well known 포트", "tcp udp 포트", "포트 참조"], search: "번호 또는 서비스로 검색", port: "포트", protocol: "프로토콜", name: "서비스", desc: "설명" },
  hi: { title: "पोर्ट नंबर खोज", short: "सामान्य TCP/UDP पोर्ट असाइनमेंट खोजें।", description: "मुफ्त पोर्ट नंबर संदर्भ। IANA well-known पोर्ट और सबसे अधिक उपयोग किए जाने वाले पंजीकृत पोर्टों में पोर्ट नंबर, सेवा नाम (SSH, HTTPS, PostgreSQL …) या विवरण द्वारा खोजें।", keywords: ["पोर्ट नंबर खोज", "iana पोर्ट", "well known पोर्ट", "tcp udp पोर्ट", "पोर्ट संदर्भ"], search: "नंबर या सेवा द्वारा खोजें", port: "पोर्ट", protocol: "प्रोटोकॉल", name: "सेवा", desc: "विवरण" },
};

const i18n = Object.fromEntries(
  (Object.keys(data) as Array<keyof typeof data>).map((loc) => {
    const { title, short, description, keywords, ...rest } = data[loc];
    return [loc, { title, short, description, keywords, ui: { ...COMMON_UI[loc], ...rest } }];
  }),
) as unknown as ToolI18n;

export default i18n;
